### ISSUE TITLE
Incorporate Mesher into service mesh landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#10]
@tianxiaoliang, would you like to assist in providing details of Mesher into the this landscape? - https://layer5.io/landscape

**Comment by tianxiaoliang** [comment]
sure.
https://github.com/go-mesh/mesher
Open Source?: yes
Primary Language: Go
Project Announce Date: November 2017
GA / 1.0 Date:  November 2017

**Comment by leecalcote** [comment]
Excellent. Thanks, @tianxiaoliang. Will you take a crack at the **Functional** section as well? Feel free to note if we're missing a column/category you think should be included.

**Comment by tianxiaoliang** [comment]
Auto Proxy Injection: yes
TCP + WebSockets: no
HTTP, HTTP/2: yes
gRPC: yes
Multi-Cluster:  Yes, Powered by ServiceComb 
Multi-Tenant: huawei cloud only

**Comment by leecalcote** [comment]
Thank you, @tianxiaoliang. We'll get these details posted!
