### ISSUE TITLE
[NG] html tags visible on the Landscape page of layer5-ng 

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/layer5#1003]
**Description**

The HTML tags are clearly visible on the [landscape page](https://layer5ng.netlify.app/landscape) of layer5-ng. The styling of the tables used within the landscape page looks very clustered.

**Expected Behavior**

The HTML tags should not be visible and proper styling that was supposed to be implemented using those tags is required.

**Screenshots**

HTML tags:
![chrome_pIXTpJq30l](https://user-images.githubusercontent.com/54861487/96871260-a8373000-148f-11eb-87d4-080faed4e9b4.png)
The font should be changed to something which is more easily readable.
![chrome_YfkTYsZjxu](https://user-images.githubusercontent.com/54861487/96871709-45926400-1490-11eb-994e-75c5658ce622.png)

**Enviroment:**
 - OS: Windows 10
 - Browser: Chrome
 - Device: laptop

---

**To Reproduce**

1. Go to [landscape page](https://layer5ng.netlify.app/landscape)
2. Scroll down to the functional table

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vinayaksh42** [comment]
@Tanuj22 shall I go ahead and solve this myself?

**Comment by leecalcote** [comment]
Tagging @geraldmaboshe, who you may wish to collaborate with on this, @vinayaksh42.

**Comment by vinayaksh42** [comment]
@leecalcote sure

**Comment by Tanuj22** [comment]
@vinayaksh42 You may want to take a look a [this](https://youtu.be/uN3gGouPK6s?t=2854) . This is is the feedback that was given in the websites call. For reference, this was what we were talking about this in the call - https://www.npmjs.com/package/react-tabs , https://www.npmjs.com/package/react-table. If you have ideas of your own about the page please post in the websites channel.

**Comment by vinayaksh42** [comment]
@Tanuj22 Thanks for the info, I will look into it.

**Comment by naman360** [comment]
Can I work on it?

**Comment by Sudhish2101** [comment]
I have made the required changes. I have also hyperlinked every column entry of SOFAMesh since it's a project shutdown, so I thought it would be better that way. Any more suggestions?

**Comment by Nikhil-Ladha** [comment]
It's fixed now :)
