### ISSUE TITLE
[Meshery] Add NGINX Service Mesh as alpha state on /meshery page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1005]
**Current Behavior**
NGINX Service Mesh is missing. A new adapter has been created - https://github.com/layer5io/meshery-nginx-sm

**Desired Behavior**
- https://layer5.io/meshery should have NGINX Service Mesh adapter listed as an alpha adapter.
- use the Nginx service mesh logo recently included in the /landscape

<img width="602" alt="Screen Shot 2020-10-22 at 4 33 34 PM" src="https://user-images.githubusercontent.com/7570704/96932344-589f3700-1484-11eb-8810-6c5dd23eb030.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by codetheorem** [comment]
Assign this to me.
