### ISSUE TITLE
[SMP] SMP Twitter Card is pinned to a single tweet

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1007]
**Description**
On [this page](https://layer5.io/projects/service-mesh-performance), the SMP Twitter Card is pinned to a single tweet.

**Expected Behavior**
The embedded twitter card should be a feed showing the last few tweets currently from @smp_spec account.

**Screenshots**
<img width="1316" alt="Screen Shot 2020-10-22 at 9 00 56 PM" src="https://user-images.githubusercontent.com/7570704/96947826-c742bb80-14a9-11eb-99f4-dbca30af830a.png">
---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Fahdmoh01** [comment]
Kindly assign me to this issue @leecalcote  @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Go on @Fahdmoh01 .
