### ISSUE TITLE
[NG] Wrong link of Distributed performance project in the navigation bar.

### ISSUE THREAD

**Issue by codetheorem** [layer5io/layer5#1009]
**Description**

There is wrong link of the Distributed performance project in the navigation bar . When we click over distributed performance under projects it shows 404.

**Expected Behavior**

Currently, it redirects to [this](https://layer5ng.netlify.app/projects/distributed-performance-management) change its url to [this](https://layer5ng.netlify.app/projects/distributed-performance-management-of-service-meshes).

---
 **To Reproduce**

1. Go to 'https://layer5ng.netlify.app/'
2. Click on 'Projects->Distributed Performance'
3. See error

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Thanks for this, @codetheorem

**Comment by Jashpatel1** [comment]
Closing with #1015
