### ISSUE TITLE
Add CNCF Testbed to Landscape Tools section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#101]
Hi @taylor, @robertstarmer, will you consider adding (via PR) to include the CNCF Testbed in the list of service mesh to the [service mesh landscape](https://layer5.io/landscape#tools)? We'd love to have an accurate listing of the tool described here.

An update to the [service-mesh-tools.html](https://github.com/layer5io/layer5/blob/f6883f41ad4edd3a3aa540042c8b2af94c6fa6c5/_includes/service-mesh-tools.html) would do the trick.

**Comment by PseudoNerd** [comment]
Do we just need to change the HTML file here ?

**Comment by leecalcote** [comment]
Yes, that’s right, @PseudoNerd.

**Comment by PseudoNerd** [comment]
May I take this up ?

**Comment by leecalcote** [comment]
Yes, @PseudoNerd, that would be great. @taylor, @robertstarmer, @michaelspedersen, @lixuna can assist in reviewing when ready.

**Comment by PseudoNerd** [comment]
Made a PR

![Screenshot from 2019-10-25 09-29-59](https://user-images.githubusercontent.com/26699089/67542379-31dfe080-f70a-11e9-923a-a22bb2687a3b.png)

**Comment by michaelspedersen** [comment]
Generally it looks good. One goal is definitely to have network code/functions that can be used across platforms (Kubernetes, Openstack), but also to showcase tools and additions that can be used with a specific platform, one example being the Network Service Mesh (Kubernetes) examples currently in the testbed.

**Comment by leecalcote** [comment]
Much appreciated, @michaelspedersen. 👍
