### ISSUE TITLE
[Landscape] Add SPIFFEE Support to the Service Mesh Landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1020]
**Current State:**
SPIFFEE is a well-used specification amongst service meshes and their proxies, like Istio, Envoy, Kuma, NGINX Service Mesh,...

**Desired State:**
It would be helpful to individuals reviewing the landscape if the Functional section included a column for SPIFFEE Support. 

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

**Comment by leecalcote** [comment]
// @ajessup @yogi4

**Comment by ajessup** [comment]
Hey Lee - Yogi and I can take a look at this. What's the best next step - a PR to the landscape site?

**Comment by Nikhil-Ladha** [comment]
Yeah, please go ahead @ajessup . The landscape site is basically layer5.io/landscape only.

**Comment by ajessup** [comment]
Hey Nikhil - thanks for taking the lead on this. It's looking good! I made some suggestions on the PR.

**Comment by Nikhil-Ladha** [comment]
> Hey Nikhil - thanks for taking the lead on this. It's looking good! I made some suggestions on the PR.

Cool, thanks for the feedback @ajessup . I will update the PR accordingly.

**Comment by ajessup** [comment]
Hey @Nikhil-Ladha friendly ping here! Our SPIFFE community day is tomorrow and it would be great to be able to tell folks about the SPIFFE information in the service mesh catalog. Let me know if I can help.

**Comment by leecalcote** [comment]
@ajessup, agreed! Having a look now...

**Comment by leecalcote** [comment]
@ajessup, thank you for your collaboration here. Your work is now on display. We're live. 👍

**Comment by ajessup** [comment]
Love it. Great work.
