### ISSUE TITLE
[NG] Enhance the Partners page for layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1024]
**Current Behavior**
The current partners page is found [here](https://layer5ng.netlify.app/partners/partners).

**Desired Behavior**
Suggest and implement new layout for the partners page.
Also, the current page has URL redundancy(siteurl/partners/partners) due to creation of partners folder. Remove the partners folder and bring the file outside in pages section.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by dDab-panda** [comment]
I'll take up this issue

**Comment by Jashpatel1** [comment]
Sure, please go ahead. This issue will take discussion and feedback. Please feel free to share whatever ideas you have in mind.

**Comment by dDab-panda** [comment]
> @dDab-panda Sure, please go ahead. This issue will take discussion and feedback. Please feel free to share whatever ideas you have in mind

> @dDab-panda Sure, please go ahead. This issue will take discussion and feedback. Please feel free to share whatever ideas you have in mind.

Sure, will ping you

**Comment by dDab-panda** [comment]
> @dDab-panda Sure, please go ahead. This issue will take discussion and feedback. Please feel free to share whatever ideas you have in mind.

Sure, will ping you
