### ISSUE TITLE
[NG] Add the second edition of service mesh architecture book to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1025]
**Current Behavior**
Recently, the second edition of [service mesh architecture book](https://layer5.io/books/the-enterprise-path-to-service-mesh-architectures-2nd-Edition) has been added to current layer5 website.

**Desired Situation**
Add the book to layer5-ng website as well in the [books section](https://layer5ng.netlify.app/books).

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
@akashgp09 Would you like to solve this issue?

**Comment by akashgp09** [comment]
Yes, assign me.
