### ISSUE TITLE
[NG] Add recently joined contributors to community members page of layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1026]
**Current Behavior**
Recently, two contributors have been added to community members of current layer5 website.

**Desired Situation**
Add those community members to layer5-ng website as well.

- [ ] [Kishore Kumar](https://layer5.io/community/members/kishore-kumar)
- [ ] [Vinayak Sharma](https://layer5.io/community/members/vinayak-sharma)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by dDab-panda** [comment]
I would like to take up this issue

**Comment by Jashpatel1** [comment]
> I would like to take up this issue

Sure, please go ahead.

**Comment by Jashpatel1** [comment]
Closing with #1027
