### ISSUE TITLE
Add a pre-commit hook for linting files 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1030]
**Desired Behavior**
Lint files using a pre-commit hook 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Oops. I thought this was a PR, and so was going to ask @kushthedude for review.

**Comment by Tanuj22** [comment]
Fixed in #1038

**Comment by kushthedude** [comment]
Didn't the issue self-close?

**Comment by Tanuj22** [comment]
The PRs to the `layer5-ng` branch doesn't self-close

**Comment by leecalcote** [comment]
I believe the keyword has to be mentioned in the description or the title, not comments.
