### ISSUE TITLE
Recognizing Gerald Moboshe as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1033]
**Current Behavior**
@geraldmaboshe has been a consistent contributor and community member.

**Desired Behavior**
A profile for @geraldmaboshe should be created and visible on `/community/members` on both the **current** and **next-gen** layer5.io sites.

- Github: https://github.com/geraldmaboshe
- Twitter: https://twitter.com/geraldmaboshe
- Profile picture: https://drive.google.com/file/d/1hpsLYkRO0AAWK7A3d3KqzS_RZULO-N29/view?usp=sharing

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by tripathyprateek** [comment]
For both layer5 and layer5-ng right?

**Comment by leecalcote** [comment]
@tripathyprateek, yes, please.
