### ISSUE TITLE
[Community] Update Michael Gfeller's member profile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1034]
**Current Behavior**
Through his thoughtful contributions, earnest effort to push forward Layer5's projects, and consistent demonstration of a pay-it-forward mentality, @mgfeller has earned a seat at the maintainers table. Through unanimous vote by the collection of current maintainers, @mgfeller has been welcomed into the role of Meshery Maintainer, Adapters.

**Desired Situation**
[His member profile](https://layer5.io/community/members/michael-gfeller) on layer5.io should reflect this accomplishment and designation. This update should be made on the current and next-gen layer5.io sites.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by naman360** [comment]
Can I work on this?

**Comment by PluckyPrecious** [comment]
Sure @naman360.👍🏽

**Comment by naman360** [comment]
Do I need to create 2 PR's respectively for master and layer5-ng branch?

**Comment by Tanuj22** [comment]
Yes @naman360

**Comment by naman360** [comment]
Have a look #1043 #1044
