### ISSUE TITLE
[NG]: Add "Maintainers" filter and "Maintainer" Designation to Community Member Profile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1035]
**Current Behavior**
Community members carry a number of different roles and the responsibilities that come with that role. They are also assigned the title associated with that role. For example, much is expected of a Layer5 MeshMate. Consequently, much consideration is given to Layer5 MeshMates, including a filter to view only individuals carrying that title in the community.

Similarly, a filter should be available for individuals carrying the Maintainer role.
 
**Desired Behavior**
A view filter should existing for the layer5.io/community/member profiles carrying a "Maintainer" role. See the "MeshMates" view filter on https://meshery.io/community/meshmate/members as an example.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@dDab-panda will you like to give it a try?

**Comment by dDab-panda** [comment]
> @dDab-panda will you like to give it a try?

Sure
