### ISSUE TITLE
[News] Market Landscape – Kubernetes Evolves into an Enterprise Platform

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1036]
Add the following research report to the layer5/news collection

**Article:**
- Title: Market Landscape – Kubernetes Evolves into an Enterprise Platform
- Link: https://amalgaminsights.com/product/market-landscape-kubernetes-evolves-into-an-enterprise-platform/

"The open source project Meshery is also providing a service mesh management plane as separate software that can interact using the Service Mesh Interface or through built-for-purpose adapters for a variety of existing service mesh products and projects." 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by dDab-panda** [comment]
Hey @leecalcote, I would like to take up this issue

**Comment by Ruth-ikegah** [comment]
Sure you can @dDab-panda

**Comment by Tanuj22** [comment]
Fixed in #1039
