### ISSUE TITLE
Add Eureka to the landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#104]
Hi @qiangdavidliu, @tbak, will you consider adding (via PR) a listing for Eureka to the [service mesh landscape](https://layer5.io/landscape)? We'd love to have an accurate listing of this load balancers described here.

[Contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) - an update to both the [non-functional.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/non-functional.yml) file would do the trick.

Thanks!

**Comment by leecalcote** [comment]
@qiangdavidliu, @tbak, any interest in having Eureka listed in the [service mesh landscape](https://layer5.io/landscape)?

**Comment by jijillery** [comment]
Hi @qiangdavidliu, @tbak, I’m working to ensure all relevant projects are represented in the [service mesh landscape](https://layer5.io/landscape). We would love to have Eureka included. Will you consider updating the landscape with a quick pull request? 

We do our best to ensure that projects and their capabilities are accurately represented, and so, we ask for project representatives to submit these updates directly. 

Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for making your edits.

Thank you!

**Comment by leecalcote** [comment]
Hi @qiangdavidliu, @tbak, it'd be great to have Eureka listed in the landscape. Will you consider adding it using the instructions above?
