### ISSUE TITLE
[NG] Remove .vscode folder

### ISSUE THREAD

**Issue by kushthedude** [layer5io/layer5#1040]
**Current Behavior**

.vscode folder is used for local IDE config, it is something to be pushed upstream.
**Desired Situation**

Remove .vscode folder
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by jomefavourite** [comment]
I'll do this

**Comment by kushthedude** [comment]
Please go ahead

**Comment by leecalcote** [comment]
@jomefavourite you're welcome to self-assign now that you're a member of the Layer5 community. 💪

**Comment by leecalcote** [comment]
✊

**Comment by jomefavourite** [comment]
> @jomefavourite you're welcome to self-assign now that you're a member of the Layer5 community. 💪

Okay, I've done that 🤞

**Comment by jomefavourite** [comment]
Damn! I forgot to signoff. Do I make a new PR?

**Comment by Tanuj22** [comment]
Fixed in #1083
