### ISSUE TITLE
[NG] Add alt texts to all images present in layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1050]
**Current Behavior**
Currently, many image tags do not have alt texts present in the layer5-ng site.

**Desired Situation**
Add related alt texts to images.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
An `alt` tag has to be added in the `Image` component already present in `reusecore` directory before. Anyone taking up this, if you need any more information regarding this, ping me

**Comment by kishore007k** [comment]
Can I take this one?

**Comment by Tanuj22** [comment]
Go ahead
