### ISSUE TITLE
Recognizing Hussaina Begum as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1054]
**Current Behavior**
@hexxdump has been a consistent contributor and community member.

**Desired Behavior**
A profile for @hexxdump should be created and visible on `/community/members` on both the **current** and **next-gen** layer5.io sites.

- Github: https://github.com/hexxdump
- Twitter: https://twitter.com/hexxdump
- Profile picture: need a picture from @hexxdump 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by naman360** [comment]
Should I take up this?

**Comment by Jashpatel1** [comment]
> Should I take up this?

Yaa sure, please go ahead. This issue relates to the creation of profile on both layer5 and layer5-ng. You will have to open up 2 PRs for this issue.

**Comment by naman360** [comment]
okay cool @Jashpatel1

**Comment by naman360** [comment]
Check it out #1060 #1061
