### ISSUE TITLE
[NG] Fix the button component

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1058]
**Description**
The button component is taking unexpected fixed width.

**Expected Behavior**
Fix the issue with the width of button component in layer5-ng.
You can find these buttons on programs page([GSOC](https://layer5ng.netlify.app/programs/gsoc/2020), [Community Bridge](https://layer5ng.netlify.app/programs/communitybridge)).

**Screenshots**
![image](https://user-images.githubusercontent.com/43696490/97796548-33a38480-1c39-11eb-97fa-c8c2a44272e9.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@codetheorem will you look into it?

**Comment by naman360** [comment]
Can I solve it?

**Comment by codetheorem** [comment]
go ahead @naman360

**Comment by naman360** [comment]
What width is to be applied?

**Comment by Jashpatel1** [comment]
> What width is to be applied?

I don't think fixed width is required. Keep it dynamic(adaptive to text length inside it).

**Comment by naman360** [comment]
Okay cool

**Comment by codetheorem** [comment]
@Jashpatel1 Now it is working fine.

**Comment by codetheorem** [comment]
This issue has been resolved no need to work on this @naman360.

**Comment by Tanuj22** [comment]
Thanks @naman360 @codetheorem
