### ISSUE TITLE
Discrepancy: Linkerd 2 encryption no longer considered experimental

### ISSUE THREAD

**Issue by hawkw** [layer5io/layer5#106]
As of Linkerd 2's `stable-2.3` release, the mTLS feature is no longer experimental; in fact, it's now enabled by default. See https://linkerd.io/2019/04/16/announcing-linkerd-2.3/

**Comment by leecalcote** [comment]
Thank you, @hawkw. Will have this updated. You're most welcome to give it a quick PR as well --> https://github.com/layer5io/layer5/blob/master/_data/categories/meshes.yml

**Comment by hawkw** [comment]
Ah, thanks for the pointer, I couldn't figure out what to update. 

Worth noting that autoinjection is also no longer considered experimental --- I can update that as well.
