### ISSUE TITLE
[NG] Use <a> tags in footer 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1063]
**Desired Situation**
The links in the [footer](https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/Footer/index.js) that point to an **external link** should use `<a>` tags instead of `<Link>` 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ayushk1804** [comment]
I would like to work on this issue.

**Comment by Tanuj22** [comment]
Go ahead
