### ISSUE TITLE
[Layer5] Add a newcomers page to the site

### ISSUE THREAD

**Issue by tripathyprateek** [layer5io/layer5#1064]
**Current Behavior**

**Desired Behavior**

Take a look at all the things which need to be added.
- [x] Add the newcomers meeting detail available on [this page](https://docs.google.com/document/d/1aHarIyIL__HRq_4klYOUsEXP5SQLlmb50W17yKdNmpU/edit#heading=h.69qskjv558bk)
- [x] Add all the tutorials made during Hacktoberfest
- [x] Newcomers resources for getting started
- [x] Newcomers meeting table at the bottom of the page
- [ ] Newcomers Questionnaire

The working link should also be visible in the nav bar under the Community section.

Tagging @leecalcote @chandrashritii @Ruth-ikegah if I am missing something.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Ruth-ikegah** [comment]
Thanks for being thoughtful about this and opening an issue @tripathyprateek, I think you should also point out the [Newcomer's Welcome Guide](https://docs.google.com/document/d/1tpg2sLxirozNt3Ofr3GdM002f9rExp74EqrsGZBU710/edit?usp=sharing) too as it has some good basic info for the page.

**Comment by navendu-pottekkat** [comment]
Is anyone working on this? Seems like a good issue for me to work on. Can I take it?

**Comment by Ruth-ikegah** [comment]
> Is anyone working on this? Seems like a good issue for me to work on. Can I take it?
Sure take it up, I have assigned it to you.

**Comment by navendu-pottekkat** [comment]
@Ruth-ikegah Thanks, I will make a PR soon

**Comment by navendu-pottekkat** [comment]
@Ruth-ikegah Please check #1095 and let me know of any changes or things to add.
