### ISSUE TITLE
Adding Hover Effect for Flags.

### ISSUE THREAD

**Issue by akashprasher** [layer5io/layer5#1068]
**Current Behavior**

On the layer5.io homepage, there is a section for Language(Refer Image),
`filter: grayscale(90%);` is used, and currently, nothing happens when we hover mouse on these flags
![image](https://user-images.githubusercontent.com/42891970/97829112-f7326000-1cee-11eb-8db2-74b47eb1199d.png)

**Desired Behavior**

So the desired change is to change the `filter: grayscale(90%);` to `filter: none;` on `:hover`. Also, add a little `transition on hover` so it looks nicer. In the image below, `filter: none;` for the flag India.
![image](https://user-images.githubusercontent.com/42891970/97829267-8dff1c80-1cef-11eb-9822-009a7a7d71db.png)
_Maintainers, please review this issue._

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by naman360** [comment]
Can I work on it?

**Comment by leecalcote** [comment]
Hi @akashprasher, heads-up - these flags may not be included when the new site goes live.

The other buttons next to the flags, however, do need work to make them interactive onHover.

**Comment by akashprasher** [comment]
Sorry @naman360 
Now this enhancement is no longer required.

**Comment by naman360** [comment]
Okay fine

**Comment by akashprasher** [comment]
@leecalcote social icons already looks nice. But I would like to add an antribute `target="_blank`" in `<a></a>` links for social icons. So whenever someone click then, they don't need to leave the site so, page will open in new Tab. What do you think?

**Comment by leecalcote** [comment]
@akashprasher, yes, opening in a new window would be good. 

I would like for the social buttons to have a similar effect onHover as they do on the current generation site. If this makes sense and is something that you would like to implement, will you create an issue for this? If not, no problem, I'll make it an issue so that another contributor can pick it up.￼￼

**Comment by akashprasher** [comment]
I'll do it for branch layer5-ng, Please create an issue and assign me.
The language option is also there(layer5-ng), will remove it?

**Comment by Tanuj22** [comment]
> I'll do it for branch layer5-ng, Please create an issue and assign me.
> The language option is also there(layer5-ng), will remove it?

@akashprasher feel free to create an issue on your own. 
Yes the language option is there in layer5-ng, but we will probably remove it.

**Comment by akashprasher** [comment]
> > I'll do it for branch layer5-ng, Please create an issue and assign me.
> > The language option is also there(layer5-ng), will remove it?
> 
> @akashprasher feel free to create an issue on your own.
> Yes the language option is there in layer5-ng, but we will probably remove it.

Sure!
