### ISSUE TITLE
[NG] Migrate two recent blogs to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1069]
**Current Behavior**
Two blogs have been added to layer5 website recently.

**Desired Situation**
Migrate both the blogs to layer5-ng website.

- [ ] [Performance Benchmarking using Meshery and NightHawk
](https://layer5.io/blog/performance-benchmarking-using-meshery-and-nighthawk)
- [ ] [Meshery Adapter for Open Service Mesh
](https://layer5.io/blog/meshery/announcing-the-meshery-adapter-for-open-service-mesh)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
Happy to be back, taking on this.

**Comment by lolyparty** [comment]
I'm having a problem running the layer5-ng, I don't know what the problem is. I keep getting an error on `_npm run start_`

**Comment by tripathyprateek** [comment]
@lolyparty have you installed Gatsby CLI?

**Comment by lolyparty** [comment]
> @lolyparty have you installed Gatsby CLI?

Yes, I do.

**Comment by Tanuj22** [comment]
@lolyparty Can you send a SS of the error

**Comment by lolyparty** [comment]
> @lolyparty Can you send a screenshot of the error

Thanks, I got it running already. Apparently, the node modules were outdated since I've been away for a while.

**Comment by Jashpatel1** [comment]
Closing with #1081
