### ISSUE TITLE
[NG] Align the logo

### ISSUE THREAD

**Issue by codetheorem** [layer5io/layer5#1070]
**Description**

Community Bridge logo is on the top of the card.
**Expected Behavior**

Align the logo of the community bridge according to other logos and make that mobile-friendly as well.

**Screenshots**

![screencapture-layer5ng-netlify-app-careers-1604326583533](https://user-images.githubusercontent.com/54779517/97878626-e01e5d00-1d44-11eb-9a0b-04f2e609a4c8.png)

---

 **To Reproduce**
1. Go to [layer5ng](https://layer5ng.netlify.app/)
2. Scroll down to the footer
3. Click on [careers](https://layer5ng.netlify.app/careers)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
The community bridge logo doesn't look like it has so much height like other logos, that would mean aligning it to the middle right?

**Comment by codetheorem** [comment]
Yes @lolyparty  align the logo to middle right.

**Comment by lolyparty** [comment]
> Yes @lolyparty align the logo to middle right.

Can you help me our here as I've been trying to align the logo but I don't seem to get it. I'm trying to style the logo from the programsgrid.style.js is this right?

**Comment by AnkitSingh-zm** [comment]
Can I start working on this issue.

**Comment by lolyparty** [comment]
> Can I start working on this issue.

Yh we can work on this together. Let's chat on slack

**Comment by AnkitSingh-zm** [comment]
> > Can I start working on this issue.
> 
> Yh we can work on this together. Let's chat on slack

The logo has been changed and aligned properly(not by me). You can close this issue.
website - https://layer5ng.netlify.app/careers
