### ISSUE TITLE
[NG] Add color legend in members page 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1071]
**Desired Behavior**
Add a color legend on the left side of `Active Members`(green) and `Inactive Members`(gray) in the dropdown present in the [community members page](https://layer5ng.netlify.app/community/members). The CSS for the color boxes should already be present. The component we are using for drop-down is [react-select](https://react-select.com/)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@Tanuj22 Any progress here?

**Comment by leecalcote** [comment]
@EmperorYP7, assuming success on your other issue, this one might be your next stop. 🙂

**Comment by EmperorYP7** [comment]
@leecalcote sure! :+1:

**Comment by Jashpatel1** [comment]
Closed with #1435
