### ISSUE TITLE
Wrong alignment of Layer5 intro video.

### ISSUE THREAD

**Issue by naman360** [layer5io/layer5#1076]
**Description**
The intro video is left aligned which hides some part of the video.

**Expected Behavior**
It should be centered so that the whole video is properly visible.

**Screenshots**
![Screenshot_20201104-202753_Chrome.jpg](https://user-images.githubusercontent.com/40193621/98127242-78027f00-1edc-11eb-8665-3c92a320d989.jpg)

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---

[Optional] **To Reproduce**
1. Go to https://layer5.io/programs/gsoc
2. Scroll down to the video

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by navendu-pottekkat** [comment]
Could I work on this issue? Seems like an easy fix and I think it would be a good first PR to Layer5 for me

**Comment by naman360** [comment]
@leecalcote

**Comment by leecalcote** [comment]
Sounds great, @navendu-pottekkat.

**Comment by leecalcote** [comment]
Thanks for identifying this issue, @naman360.

**Comment by navendu-pottekkat** [comment]
Thanks @leecalcote I will make a PR
