### ISSUE TITLE
Community: Recognizing Rodolfo Martínez as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1077]
**Current Behavior**
@ramrodo has been a consistent contributor and community member.

**Desired Behavior**
A profile for @ ramrodo should be created and visible on `/community/members` on both the current layer5.io site.

- Github: https://github.com/ramrodo
- Twitter: https://twitter.com/ramrodo
- Profile picture: https://rodomar.mx/assets/images/profile-2.jpg	 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by OlushesiToheeb** [comment]
I want to take the issue

**Comment by leecalcote** [comment]
@OlushesiToheeb did this update land already and we just need to close this issue or is this work still in-progress?

**Comment by OlushesiToheeb** [comment]
It merged already @leecalcote

**Comment by OlushesiToheeb** [comment]
![Uploading image.png…]()

**Comment by OlushesiToheeb** [comment]
![image](https://user-images.githubusercontent.com/46800177/98915827-b4307380-24ca-11eb-85ef-7a8ed7e8ffca.png)

**Comment by leecalcote** [comment]
Oh, very good.

**Comment by leecalcote** [comment]
Thanks, @OlushesiToheeb
