### ISSUE TITLE
[NG] Community: Recognizing Rodolfo Martínez as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1078]
**Current Behavior**
@ramrodo has been a consistent contributor and community member.

**Desired Behavior**
A profile for @ ramrodo should be created and visible on `/community/members` on both the next-generation layer5.io site (`layer5-ng` branch).

- Github: https://github.com/ramrodo
- Twitter: https://twitter.com/ramrodo
- Profile picture: https://rodomar.mx/assets/images/profile-2.jpg	 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by shivam-51** [comment]
I would like to work on this issue.


> A profile for @ ramrodo should be created and visible on `/community/members` on both the next-generation layer5.io site (`layer5-ng` branch).

We need to add the profile on https://deploy-preview-1045--layer5ng.netlify.app/community/members, right? What do you mean by "both" here?

**Comment by leecalcote** [comment]
Thanks, @shivam-51. "Both" is a errant article in the sentence in the description. You're safe to ignore. Yes, this issue refers to the layer5ng site only.

**Comment by Jashpatel1** [comment]
Closing with #1079
