### ISSUE TITLE
[NG] Improvise the Community Members Page on layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1085]
**Current Behavior**
The current [community members](https://layer5ng.netlify.app/community/members) page looks a bit plain and simple.

**Desired Behavior**
Try out some different ways of representing each member card on the page.
Also, incorporate 4 member cards in a single row as compared to 3 member cards currently.
Incorporate LinkedIn profile links along with github and twitter in member card.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@chandrashritii can you help with the LinkedIn profile links?

**Comment by Jashpatel1** [comment]
@aayushdutt @dDab-panda can anyone of you give it a try?

**Comment by vinayaksh42** [comment]
sure @Jashpatel1
