### ISSUE TITLE
Add Solo Gloo to API Gateway Landscape

### ISSUE THREAD

**Issue by bettyjunod** [layer5io/layer5#109]
Description: Next generation API Gateway

link to 
www.solo.io/glooe

**Comment by vegasbrianc** [comment]
Hi @bettyjunod Added PR https://github.com/layer5io/layer5/pull/110 to include SuperGloo

**Comment by vegasbrianc** [comment]
@bettyjunod Added Gloo gateway as well https://github.com/layer5io/layer5/pull/111

**Comment by leecalcote** [comment]
Thank you, @bettyjunod and @vegasbrianc. Let's get Gloo into the landscape before KubeCon begins.
