### ISSUE TITLE
[Community] Member profile LinkedIn update

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1092]
**Current Behavior**
[Layer5-ng community member](https://layer5ng.netlify.app/community/members) profiles now have the ability to include a link to their LinkedIn profile.

**Desired Situation**
Update the @Aisuko profile to include the following front matter:

```
linkedin: bowen-li-10101197
```

- [Source code](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/members) of member profiles.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ashutosh1401** [comment]
Could i work on this one ?

**Comment by Aisuko** [comment]
@ashutosh1401 Yes, please

**Comment by ashutosh1401** [comment]
WorkerError: Processing C:/Users/Ashutosh/myprojects/layer5/src/collections/books/2018-06-12-istio-up-and-running/istio-up-and-running_top.png failed
  Original error:
  Command failed with ENOENT: C:\Users\Ashutosh\myprojects\layer5\node_modules\pngquant-bin\vendor\pngquant.exe - --strip --quality 50-75
  spawn C:\Users\Ashutosh\myprojects\layer5\node_modules\pngquant-bin\vendor\pngquant.exe ENOENT
  'C:\Users\Ashutosh\myprojects\layer5\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command, 
  operable program or batch file. 

I am facing this error as soon as i start the site by using npm start.

**Comment by Tanuj22** [comment]
@ashutosh1401 try deleting the `.cache` and `public` folders

**Comment by ashutosh1401** [comment]
Command failed with ENOENT: C:\Users\Ashutosh\myprojects\layer5\node_modules\pngquant-bin\vendor\pngquant.exe - --strip --quality 50-75
spawn C:\Users\Ashutosh\myprojects\layer5\node_modules\pngquant-bin\vendor\pngquant.exe ENOENT
'C:\Users\Ashutosh\myprojects\layer5\node_modules\pngquant-bin\vendor\pngquant.exe' is not recognized as an internal or external command,
operable program or batch file. 

Still this error is showing up.

**Comment by Tanuj22** [comment]
Some dependencies were changes. Try to run `npm install`

**Comment by ashutosh1401** [comment]
I have also tried `npm install` but still same error is showing up

**Comment by Tanuj22** [comment]
@ashutosh1401 this looks a problem local to your machine. Can you do `npm rebuild`?
