### ISSUE TITLE
[Community] Member profile LinkedIn update: lidor-ettinger-a4725b134

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1094]
**Current Behavior**
[Layer5-ng community member](https://layer5ng.netlify.app/community/members) profiles now have the ability to include a link to their LinkedIn profile.

**Desired Situation**
Update the @naturalett profile to include the following front matter:

```
linkedin: lidor-ettinger-a4725b134
```

- [Source code](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/members) of member profiles.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by OlushesiToheeb** [comment]
I want to take this issue

**Comment by kishore007k** [comment]
Sure @OlushesiToheeb
