### ISSUE TITLE
[NG] Community: Update member profile to include LinkedIn account: Abhishek Kumar

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1116]
**Current Behavior**
[Layer5-ng community member](https://layer5ng.netlify.app/community/members) profiles now have the ability to include a link to their LinkedIn profile.

**Desired Situation**
Update the @kumarabd profile to include the following front matter:

```
linkedin: kumar-abishek-51a1761b
```

- [Source code](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/members) of member profiles.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by KarenEfereyan** [comment]
@leecalcote waow there are a number of good first issues here. Let me make some noise and get some more people into open source.

**Comment by leecalcote** [comment]
Sounds great 👌

**Comment by naman360** [comment]
should i take it up?

**Comment by leecalcote** [comment]
@naman360 this issue is open, if interested.

**Comment by KarenEfereyan** [comment]
@naman360 im assigning to you...

**Comment by naman360** [comment]
No dont assign me I am looking for some new kind of issues to solve

**Comment by KarenEfereyan** [comment]
Ok

**Comment by anuraagbarde** [comment]
Ok, I just checked, [https://linkedin.com/in/kumar-abishek-51a1761b](https://linkedin.com/in/kumar-abishek-51a1761b) is not valid link.

**Comment by anuraagbarde** [comment]
I just check, [https://linkedin.com/in/kumar-abishek-51a1761b](https://linkedin.com/in/kumar-abishek-51a1761b) is not a valid link.

**Comment by leecalcote** [comment]
@kumarabd, do you have another link that can be used?

**Comment by kumarabd** [comment]
@leecalcote  this one is good https://www.linkedin.com/in/abishek-kumar-51a1761b
