### ISSUE TITLE
Add App Insight to the landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#112]
@dtzar @paulbouwer should we consider inclusion of Azure's Istio Mixer adapter to the service mesh landscape - https://layer5.io/landscape? Under Tools or a new integrated systems section?

**Comment by paulbouwer** [comment]
@leecalcote - I think it would make sense to add it under a new integrated systems section. There are a number of other Istio Mixer adapters we should add then too.

**Comment by anandrkskd** [comment]
@paulbouwer , it'd be great to have Azure's Istio Mixer adapter represented in the [landscape](https://layer5.io/landscape). Will you consider a contributing PR? It would be great have PR from you soon.

**Comment by paulbouwer** [comment]
Since Istio Mixer is deprecated, and the App Insights Istio Mixer adapter is also deprecated, this no longer makes sense.
