### ISSUE TITLE
Updates on Newcomers Page

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1121]
**Current Behavior**
The current layer5 site can be found at [https://layer5.io/newcomers](https://layer5.io/newcomers).

**Desired Behavior**
A few changes are required on the newcomers page on layer5 site.
Responsiveness issues on screens having a width of less than 400 px.
Other content and layout changes would be suggested by @chandrashritii and @leecalcote 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by navendu-pottekkat** [comment]
Here are the changes proposed in yesterday's meeting:

- [ ] Change "Slack Channel" to "Slack Workspace"

- [ ] Add padding to the top table

- [ ] Add missing #newcomers channel link

- [ ] Add CSS to table as in the [community page](https://layer5.io/community).

- [ ] Change link from https://layer5.io/newcomers to https://layer5.io/community/newcomers

- [ ] Fix responsiveness issues.

Will make a PR soon.

**Comment by leecalcote** [comment]
Good work.
