### ISSUE TITLE
[NG] latest blogs section

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1125]
**Current Behavior**
The sidebar of the https://layer5ng.netlify.app/blog contains a `Latest Post` section. It is not populated currently

**Desired Behavior**
Populate the section with 4 latest blog post. 
Note - This is to be done dynamically using graphql query.  

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by OmkarPh** [comment]
Hi @Tanuj22 
I'm new to GraphQL, but will try this out

Let me look around the repo. I may bore you with few questions soon 😅

**Comment by Tanuj22** [comment]
@OmkarPh please do bore me :laughing: . I will be happy to help!

**Comment by OmkarPh** [comment]
Hi @leecalcote and @Tanuj22 
I am almost done, but wanted to share a few things before making PR.


Following is the output on blogs page:
![image](https://user-images.githubusercontent.com/48476025/99142138-49bd3600-2678-11eb-93c5-3469e8814b37.png)


On single blog page:
![image](https://user-images.githubusercontent.com/48476025/99142146-60fc2380-2678-11eb-8990-e3831eff2f63.png)

As per the previous blog thumbnail, I gave width and height of 80px, but it doesn't look perfect enough (my thoughts) as some images are in landscape.

Also, I talked about irrelevant use of latest blogs section on [all blogs page](https://layer5ng.netlify.app/blog) with @Tanuj22 . This page already shows latest blogs, so you might want to think of removing it from there.

Ignoring these two things, everything looks good to me.

**Comment by Tanuj22** [comment]
@OmkarPh Can you also check these out https://github.com/layer5io/layer5/pull/1155#pullrequestreview-531146315

**Comment by OmkarPh** [comment]
Can you tell me how this looks, I made images bigger using classNames already available. 
Bigger thumnails look better according to me.
Checkout these:
[Service Mesh (Istio) patterns for Multitenancy _ Layer5 - The Service Mesh Company.pdf](https://github.com/layer5io/layer5/files/5553042/Service.Mesh.Istio.patterns.for.Multitenancy._.Layer5.-.The.Service.Mesh.Company.pdf)
[Blog _ Layer5 - The Service Mesh Company.pdf](https://github.com/layer5io/layer5/files/5553045/Blog._.Layer5.-.The.Service.Mesh.Company.pdf)

**Comment by Tanuj22** [comment]
Umm...not so sure about keeping bigger thumbnails as maybe it's taking too much attention from the user. @Nikhil-Ladha what do you think?

**Comment by Nikhil-Ladha** [comment]
The `Latest post` section can be removed in the blogs page, it's just redundant.
And, for the bigger thumbnails part I agree with @Tanuj22 it draws too much attention. But, the way of showing the posts in the latest update looks better than the one in this [comment](https://github.com/layer5io/layer5/issues/1125#issuecomment-727160558). 
Also, do we really need the `search` bar in this page?

**Comment by OmkarPh** [comment]
On all blogs page, latest post section is ultimately getting deleted,
Is this [ScreenShot of latest post section on single blog](https://github.com/layer5io/layer5/files/5565001/Service.Mesh.Istio.patterns.for.Multitenancy._.Layer5.-.The.Service.Mesh.Company.1.pdf) good or should I keep it as it is here: https://layer5ng.netlify.app/blog/performance-benchmarking-using-meshery-and-nighthawk

**Comment by Nikhil-Ladha** [comment]
Use the design in the pdf but, place it in the position listed in the preview.

**Comment by OmkarPh** [comment]
I didn't understand; What 'listed in preview' refers to?

**Comment by Nikhil-Ladha** [comment]
Means the way it is in preview.

**Comment by OmkarPh** [comment]
Oh, yes

**Comment by OmkarPh** [comment]
Can you suggest what to put in place of this section in all blogs page

**Comment by Nikhil-Ladha** [comment]
Can you share a demo of what you are trying to say, I didn't get that clearly :thinking:

**Comment by OmkarPh** [comment]
This is how the all blog page looks without sidebar:
[Blog _ Layer5 - The Service Mesh Company.pdf](https://github.com/layer5io/layer5/files/5573371/Blog._.Layer5.-.The.Service.Mesh.Company.pdf)

since, search bar and categories are included in sidebar

**Comment by Nikhil-Ladha** [comment]
Okay. So, finally what you can do is:
- Remove the sidebar completely in the single blog page, which is for example this page (https://layer5ng.netlify.app/blog/performance-benchmarking-using-meshery-and-nighthawk) and shift the lates blogs section at the end in which each blogs should have this design 
![Screenshot from 2020-11-20 17-57-37](https://user-images.githubusercontent.com/29438875/99800356-3f100e80-2b5a-11eb-90a0-4c236fcc05d5.png)

- For the all blogs page, just remove the latest post section and keep everything else which is the serach bar, categories and tags.

**Comment by OmkarPh** [comment]
> Can you share a demo of what you are trying to say, I didn't get that clearly 🤔
> 
> Also, for the single blog page simply remove the sidebar and move the latest post section at the end of the content.

It doesn't look good at the bottom though :(
If they're catching attention, then I'd rather reduce their size rather than moving entire section to bottom.

**Comment by OmkarPh** [comment]
> Okay. So, finally what you can do is:
> 
> * Remove the sidebar completely in the single blog page, which is for example this page (https://layer5ng.netlify.app/blog/performance-benchmarking-using-meshery-and-nighthawk) and shift the lates blogs section at the end in which each blogs should have this design
>   ![Screenshot from 2020-11-20 17-57-37](https://user-images.githubusercontent.com/29438875/99800356-3f100e80-2b5a-11eb-90a0-4c236fcc05d5.png)
> * For the all blogs page, just remove the latest post section and keep everything else which is the serach bar, categories and tags.

But the tags and search bar are in sidebar component itself

**Comment by Nikhil-Ladha** [comment]
> But the tags and search bar are in sidebar component itself

Move the latest post section code out of that component, and make it a new one.

**Comment by OmkarPh** [comment]
> > But the tags and search bar are in sidebar component itself
> 
> Move the latest post section code out of that component, and make it a new one.

Ok I'll do that

**Comment by Nikhil-Ladha** [comment]
> It doesn't look good at the bottom though :(
> If they're catching attention, then I'd rather reduce their size rather than moving entire section to bottom.

Checkout this page https://www.hashicorp.com/blog/hashicorp-boundary. This looks pretty good and decent. I was talking about something similar to that.

**Comment by Tanuj22** [comment]
@Nikhil-Ladha we need to add a related post section at the bottom of each page

**Comment by Nikhil-Ladha** [comment]
Yup, but that would require us to have the categories ready and working. So, for the time being we can work with this one, what say?

**Comment by OmkarPh** [comment]
What if I make a new component as Related posts which uses latest post graphql query for now, later we can change the query?

**Comment by Nikhil-Ladha** [comment]
> What if I make a new component as Related posts which uses latest post graphql query for now, later we can change the query?

Sure, please do that :+1:

**Comment by OmkarPh** [comment]
Can you explain me how these 'Col' components work,
![image](https://user-images.githubusercontent.com/48476025/99806993-d4180500-2b64-11eb-99ba-c1f5626316c3.png)

I remove one col, so want the first one to span over more area horizontally

**Comment by Nikhil-Ladha** [comment]
I think you can sort this out with @Tanuj22 or @Jashpatel1 on slack. Please join the workspace if you haven't yet.

**Comment by OmkarPh** [comment]
Hi @Nikhil-Ladha 
Checkout deployment of #1175

**Comment by OmkarPh** [comment]
Hi @Nikhil-Ladha 
Can you see why the deployment fails :(
Everything worked fine on my local machine and I haven't changed any config file yet there's some build error.

**Comment by Tanuj22** [comment]
> Hi @Nikhil-Ladha and @Tanuj22
> Can you see why the deployment fails in above PR :(
> Everything worked fine on my local machine and I haven't changed any config file yet there's some build error.

Maybe an error with the cache. I have re run the deployment. Should work now
