### ISSUE TITLE
[NG] Filter blogs by categories

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1126]
**Current Behavior**
There is a category section on the sidebar of https://layer5ng.netlify.app/blog

**Desired Behavior**
A feature is needed to filter blogs by categories. For now, some dummy categories can be added. Each blog will contain a single category. Reference on how to implement this feature can be taken from filtering by tags. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by codetheorem** [comment]
@Tanuj22 to implement this we have to add categories to each blog and then sort it out like we are doing currently for tags or there is another implementation for this?

**Comment by Tanuj22** [comment]
@codetheorem It would be the same. But in this, each blog would have only one category

**Comment by kishore007k** [comment]
Hey @Tanuj22, As far as I understand we have to create a new frontmatter and filter the blog posts using them. Is that right?
It would be nice to know what blogs come under what categories or what are all the categories each blog should have.

**Comment by Tanuj22** [comment]
> Hey @Tanuj22, As far as I understand we have to create a new frontmatter and filter the blog posts using them. Is that right?
> It would be nice to know what blogs come under what categories or what are all the categories each blog should have.

You can add a dummy 2 categories and implement the functionality using that.

**Comment by kishore007k** [comment]
@Tanuj22 , So I have to create two types of categories say `development` and `technology` for all the blogs and sort them using those. Is that it?

**Comment by kishore007k** [comment]
On clicking on those categories it should show only those bloga that have that categories in the `/blogs` page?

**Comment by Tanuj22** [comment]
@kishore007k just hold on for some time. We should have the categories for each blogs soon.

**Comment by kishore007k** [comment]
> @kishore007k just hold on for some time. We should have the categories for each blogs soon. 

ok 👍

**Comment by leecalcote** [comment]
We should be ready for this. The GraphQL query doesn't need to identify the names of specific categories. Rather, it just needs to query for all posts, group and count them by category name. Category name should be read from the .mdx frontmatter.
