### ISSUE TITLE
[NG] social links not working properly on community members page

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1127]
**Description**
The[ community members page](https://layer5ng.netlify.app/community/members)  cards contain social links (`github, twitter, ...`) of the members. When clicked on them they are not directing to the correct page instead the individual member page gets open. 

**Expected Behavior**
The social links on clicked should direct to the correct page. This is probably an issue with CSS of the page 

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by dDab-panda** [comment]
I would like to take up this issue

**Comment by leecalcote** [comment]
Thank you, @dDab-panda

**Comment by Jashpatel1** [comment]
Closing with #1140
