### ISSUE TITLE
[NG] Update the hacktobefest page

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1128]
**Current Behavior**
The tutorials table has last to fields as `to be announced`. 

**Desired Situation**
Update the table with the information available [here](https://layer5.io/programs/hacktoberfest) 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@naman360 could be a good one for you to pick up...

**Comment by naman360** [comment]
Yup @leecalcote

**Comment by naman360** [comment]
@Tanuj22 can you provide me the link of tutorials table?

**Comment by Nikhil-Ladha** [comment]
https://layer5ng.netlify.app/community the table is at the bottom of the page.

**Comment by naman360** [comment]
There is no To Be Announced written anywhere in the table. @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
My bad, this is the correct link https://layer5ng.netlify.app/programs/hacktoberfest/2020

**Comment by naman360** [comment]
Cool thanks.

**Comment by Jashpatel1** [comment]
Closing with #1137
