### ISSUE TITLE
Issue in PR Template

### ISSUE THREAD

**Issue by Aniruddha-Shriwant** [layer5io/layer5#1131]
**Description**

When I had made my first PR #1122 , there I had seen this :

![image](https://user-images.githubusercontent.com/58624108/98694257-3d468e00-2397-11eb-84d5-65ab1338fa89.png)
But when I had clicked on that link it shows the following result  : 

![image](https://user-images.githubusercontent.com/58624108/98694423-6d8e2c80-2397-11eb-8505-5890780c761c.png)

**Expected Behavior**

I think it should point out to this :

![image](https://user-images.githubusercontent.com/58624108/98694606-a7f7c980-2397-11eb-8f56-289c40b8e8d8.png)

**Enviroment:**

- Browser: 

---

[Optional] **To Reproduce**
1. Go to #1122 
2. Click on 'Signed commits on first comment'
3. See error

[Optional] **Additional Context**

I had seen similar behavior in some other PR's so opened this issue :)
Also, I apologize because I was not knowing the right format for opening a new issue, I had seen [NG], [Community] in some issues title but was not knowing what to add here :)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Aniruddha-Shriwant** [comment]
So Should I make a new PR for this by editing [this](https://github.com/layer5io/layer5/blob/master/.github/PULL_REQUEST_TEMPLATE.md)
where I will replace : 
`**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**`
by: 
`**[Signed commits](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**`

**Comment by leecalcote** [comment]
Good catch, @Aniruddha-Shriwant
