### ISSUE TITLE
[Community] Recognizing Bart Kalanski as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1139]
**Current Behavior**
@bartkalanski has been a consistent contributor and community member.

**Desired Behavior**
A profile for @bartkalanski should be created and visible on `/community/members` on both the current layer5.io site.

- Github: https://github.com/bartkalanski
- Twitter: bartkodes
- LinkedIn: bart-kalanski
- Profile picture: https://pbs.twimg.com/profile_images/1271353670211375106/n4l3xu3k_400x400.jpg 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Aniruddha-Shriwant** [comment]
I would like to work on this issue :)

**Comment by leecalcote** [comment]
> sounds great, @Aniruddha-Shriwant

**Comment by bartkalanski** [comment]
Wow, that's made my week, I'm really grateful, thank you :)
