### ISSUE TITLE
[NG] Add Community Calendar page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1151]
**Current Behavior**
Similar to the calendar page on https://meshery.io/calendar, the Layer5-NG site should have a page to peruse the community calendar.

**Desired Behavior**
- This page should be styled to match Layer5-NG.
- This page should be positioned at layer5.io/community/calendar.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vinayaksh42** [comment]
@leecalcote there is already a little bit of discussion going on this issue at this [issue](https://github.com/layer5io/layer5/issues/934)

**Comment by leecalcote** [comment]
Oh, I see. Thank you, @vinayaksh42. This issue is a duplicate of #934. Got it.
