### ISSUE TITLE
[NG] Fix typo error on Nikhil Ladha Blog post

### ISSUE THREAD

**Issue by OlushesiToheeb** [layer5io/layer5#1157]
**Current Behavior**
markdown text is showing instead of a link

**Expected Behavior**
[Meshery](https://meshery.io/) should be a link, not a markdown text

**Screenshots**

![image](https://user-images.githubusercontent.com/46800177/99390449-eed64980-28d8-11eb-83b7-1e6df49677b0.png)

- [source code](https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/blog/2020-08-11-my-journey-from-a-contributor-to-a-maintainer/index.mdx) of the Blog post.

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Thank you, @OlushesiToheeb

**Comment by Pratyush-Saxena** [comment]
@leecalcote pls have a look to pr #1163
