### ISSUE TITLE
[Projects] SMI: Add SMI and Meshery Logos to /smi page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1161]
**Current Behavior**
This page should have the SMI and Meshery logos on it - https://layer5.io/projects/service-mesh-interface

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Pratyush-Saxena** [comment]
@leecalcote i wanna work on this ...

**Comment by leecalcote** [comment]
@Pratyush-Saxena thank you. Excellent. 👍

**Comment by Pratyush-Saxena** [comment]
@leecalcote  where should i put these logo on page??

**Comment by Jashpatel1** [comment]
@leecalcote Any updates?

**Comment by Elijah699** [comment]
@leecalcote @Jashpatel1 is this issue still open??

**Comment by leecalcote** [comment]
Wow. How did I miss each of these comments? My apologies. Yes, this is still an open issue. Placement of the logos isn't critical, but just that they are included.

At this point, we're quite close to publishing a whole new version of the layer5.io website, referred to as "layer5-ng", which is Gatsbyjs based. We can safely set aside the work on the current version of layer5.io (Jekyll-based) and focus all energy on getting the new [layer5-ng](https://github.com/layer5io/layer5/tree/layer5-ng) (see layer5-ng branch). You're most welcome and encouraged to jump into any open issues there. See latest build of the new site -https://layer5ng.netlify.app

**Comment by leecalcote** [comment]
Here is the new version of the SMI Conformance page - https://layer5ng.netlify.app/projects/service-mesh-interface-conformance.

Designs for this page an others can be found here - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs

**Comment by Tanuj22** [comment]
Closing as the new site design has been implemented
