### ISSUE TITLE
[Landscape] linkerd suppports multi cluster

### ISSUE THREAD

**Issue by WLun001** [layer5io/layer5#1168]
**Current State:**
linkerd multicluster experimenent

**Desired State:**
support multicluster, https://linkerd.io/2/features/multicluster/

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

**Comment by Nikhil-Ladha** [comment]
Thanks for opening this issue @WLun001 .
Would you like to submit a PR for the same, if you don't mind :slightly_smiling_face:

**Comment by Jashpatel1** [comment]
@Nikhil-Ladha @WLun001 Any progress here?

**Comment by Nikhil-Ladha** [comment]
I will update it, no worries.
