### ISSUE TITLE
[NG] Migrate the Newcomers page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1169]
**Desired Situation**

Migrate the [Newcomers page](https://layer5.io/community/newcomers) from layer5.io to the Layer5-ng site.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
I would like to work on this!
Can I take this issue?

**Comment by chandrashritii** [comment]
Sure. Take it away @kishore007k

**Comment by kishore007k** [comment]
Hey! @chandrashritii, As I was working on the issue It struck my mind that It would be nice to have some kind of introduction video on what is `layer5` and what are all the projects that are currently going on. And maybe display some of the popular events or something like that if applicable.
What are your thoughts? @chandrashritii, @leecalcote
