### ISSUE TITLE
Add Book Contents to a Page on Layer5 site and Layer5-ng site

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1171]
**Current Behavior**
The website has book contents page at https://layer5.io/books/service-mesh-patterns.

**Desired Situation**
Add the [book contents](https://docs.google.com/spreadsheets/d/1sJAsBPAc08Pml5uBijHpb0AvJxe6IoVtzhwBFDiVLCw/edit#gid=1453706035) to the page.

---

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
hey @Jashpatel1 can you expatiate on this issue? The book to be added to the websites is in a google doc, right?

**Comment by Jashpatel1** [comment]
@lolyparty The book is already added. You will have to add the book contents(provided in the doc) in the book page on both the sites.

**Comment by lolyparty** [comment]
> @lolyparty The book is already added. You will have to add the book contents(provided in the doc) in the book page on both the sites.

ok so I' to add the whole content of the docs in tabular form as it is to the page, right?

**Comment by lolyparty** [comment]
> > @lolyparty The book is already added. You will have to add the book contents(provided in the doc) in the book page on both the sites.
> 
> ok so I have to add the whole content of the docs in tabular form as it is to the page, right?

**Comment by Jashpatel1** [comment]
> > @lolyparty The book is already added. You will have to add the book contents(provided in the doc) in the book page on both the sites.
> 
> ok, so I'm to add the whole content of the docs in tabular form as it is to the page, right?

Yes

**Comment by lolyparty** [comment]
> > > @lolyparty The book is already added. You will have to add the book contents(provided in the doc) in the book page on both the sites.
> > 
> > 
> > ok, so I'm to add the whole content of the docs in tabular form as it is to the page, right?
> 
> Yes

Ok, on it.

**Comment by Jashpatel1** [comment]
@lolyparty Any progress here?

**Comment by lolyparty** [comment]
> @lolyparty Any progress here?

Yes, just having difficulty adding the table in layer5-ng

**Comment by lolyparty** [comment]
![layer5 jekyll](https://user-images.githubusercontent.com/49575651/101918917-40b57b00-3bca-11eb-8cc7-f46f6483c699.png)

Hey, @Jashpatel1 I can't seem to style the table is there a way I can do that?
