### ISSUE TITLE
[NG] Add the meshmate brand kit 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1172]
**Desired Behavior**

Add a section for meshmate brand kit ([link](https://drive.google.com/file/d/1KCXC0a4VNxJDxTNVHMl3R8-XaLntLu_3/view?usp=sharing)) to layer5-ng (https://layer5ng.netlify.app/brand). The folder related to this is [here](https://github.com/layer5io/layer5/tree/layer5-ng/src/sections/Brand) 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Anita-ihuman** [comment]
I would like to take on this issue

**Comment by Anita-ihuman** [comment]
Thank you @Tanuj22 fro assigning the issue, I want to be clear on something, So i am supposed to include this brandkit in the folder containing brand? as a seperate file? or in an existing file

**Comment by leecalcote** [comment]
@Anita-ihuman, good clarifications.

1. Yes, you'll upload the .zip brand kit file so that people can click a yellow-colored button (that you will create) to download the kit.
2. You will create a new section for the MeshMate logo similar to the SMP section:

<img width="1212" alt="Screen Shot 2020-11-22 at 9 36 19 PM" src="https://user-images.githubusercontent.com/7570704/99927426-f9467800-2d0a-11eb-991f-e66e6af6cd89.png">

**Comment by Nikhil-Ladha** [comment]
Hi @Anita-ihuman how this coming up?
If you are not able to move ahead with it, shall I take it up?

**Comment by Anita-ihuman** [comment]
Hi @Nikhil-Ladha  I was just talking withTanuj yesterday on how I can fix this issue, but you take it up.

**Comment by Anita-ihuman** [comment]
If it is ok with you tho I would like to watch you fix the issue perhaps on a call?

**Comment by Nikhil-Ladha** [comment]
Assigning this issue to @OlushesiToheeb as you are already working on revamping the brand page, it can be done along with that.

**Comment by Jashpatel1** [comment]
@OlushesiToheeb Any progress here?

**Comment by Tanuj22** [comment]
Fixed in #1326
