### ISSUE TITLE
in mobile view, text crashes with right border

### ISSUE THREAD

**Issue by anjali1102** [layer5io/layer5#1177]
**Description**

**Expected Behavior**

in mobile view, text crashes with right border

**Screenshots**

![anjali_issue](https://user-images.githubusercontent.com/56559378/99901584-9b4f6b80-2cdd-11eb-927a-de80c16dc64a.png)

**Enviroment:**
- Host OS: windows
- Browser: google chrome

---

[Optional] **To Reproduce**
1. Go to 'https://layer5.io/programs/hacktoberfest'
2. set the mobile view

**Comment by anjali1102** [comment]
i want to work on it!

**Comment by lolyparty** [comment]
> i want to work on it!

Hey go ahead and work on it. Thank you.

**Comment by Jashpatel1** [comment]
Fixed with new design.
