### ISSUE TITLE
[NG] Improve the Events Page on layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1184]
**Current Behavior**
Currently, the [events page](https://layer5ng.netlify.app/community/events) on layer5-ng has a single list of events.

**Desired Behavior**
Divide the events into categories and show them into tabs layout. 
Add the "Attend an Event" section to the page.
Any improvements in design/layout will be heartily welcomed.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
Are there any upcoming events or workshops @leecalcote?

**Comment by kishore007k** [comment]
@Jashpatel1 Can we move the `/collection/meetups` to the `collection/events` since we are presenting both of them on the same page. And it would reduce querying separate for each of them.

**Comment by Tanuj22** [comment]
> @Jashpatel1 Can we move the `/collection/meetups` to the `collection/events` since we are presenting both of them on the same page. And it would reduce querying separate for each of them.

Yes
