### ISSUE TITLE
[NG] Improve the Newcomers Page on layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1185]
**Current Behavior**
The current [newcomers page](https://layer5ng.netlify.app/community/newcomers) needs a few changes in terms of design/layout.

**Desired Behavior**
The information, guides and issue for grabs doesn't justify being in a tabular format. Kindly use some other layout.
Make use of react-tables for the tutorial table present at the end.
Replcae the graphic with another one more formal. @leecalcote can provide the graphic if needed. 
Any improvements in design/layout will be heartily welcomed.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@kishore007k will you like to work on this or keep it open for others to work upon?

**Comment by kishore007k** [comment]
Let it be for now. After I finish working on the other issue I'll take it. If in-between any wants to take it It's fine.

**Comment by Nikhil-Ladha** [comment]
@adekanyetomie

**Comment by kishore007k** [comment]
Is there any kind of design for this page? That we can use. @Jashpatel1

**Comment by Nikhil-Ladha** [comment]
@kishore007k , @adekanyetomie is working on some designs. So, you can take up other issues for the time being.

**Comment by kishore007k** [comment]
Ok @Nikhil-Ladha

**Comment by leecalcote** [comment]
// @austinogiza

**Comment by kishore007k** [comment]
Closing with #1280

**Comment by Jashpatel1** [comment]
@kishore007k I think Omkar and Tomi are working on this.

**Comment by kishore007k** [comment]
Oh sorry wrong issue😅

**Comment by chandrashritii** [comment]
Call for pictures to be added to the Newcomers page [@Nikhil-Ladha, @shivaylamba]

@adekanyetomie
- Use kepple green (darker green) for links

**Comment by Nikhil-Ladha** [comment]
> Call for pictures to be added to the Newcomers page [@Nikhil-Ladha, @shivaylamba]
> 
> @adekanyetomie
> 
> * Use kepple green (darker green) for links

Infact everyone are welcome to share 😆

**Comment by Tanuj22** [comment]
FIxed in #1346
