### ISSUE TITLE
add validation to "Stay meshy and subscribe"

### ISSUE THREAD

**Issue by kmlhsn** [layer5io/layer5#1186]
**Description**
add validation to "Stay meshy and subscribe"

**Expected Behavior**
form should validate forms when submitting
It shows no error message when click on "Subscribe" Button
**Screenshots**
![image](https://user-images.githubusercontent.com/32615215/100106466-c5965a00-2e92-11eb-8b17-ebba3499aacf.png)
![image](https://user-images.githubusercontent.com/32615215/100106487-ca5b0e00-2e92-11eb-95f0-92f1c9832829.png)

**Enviroment:**
- Host OS: Windows 10
- Meshery Version: 
- Kubernetes Version: 
- Browser:  Mozilla Firefox 83

---

[Optional] **To Reproduce**
1. Go to https://layer5.io/'
2. Scroll down to 'Stay meshy and subscribe'

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Hi @kmlhsn, good highlight here. Thank you for creating an issue. This is a very timely issue as this form has just begun to be the target of fake subscriptions. In fact, earlier today a captcha was added to prevent these fake subscriptions. You should now be presented a captcha after filling in the form and clicking Subscribe. Before the subscription is allowed a captcha has to be completed. Will you test and verify?

**Comment by leecalcote** [comment]
I believe that we're good to go here. Please reopen if you find differently, @kmlhsn.
