### ISSUE TITLE
Transition of Nupur Thakur to MeshMate Emeritus 

### ISSUE THREAD

**Issue by NupurThakur27** [layer5io/layer5#1187]
**Current Behavior**
Nupur Thakur is a MeshMate who is quite inactive for her role.

**Desired Situation**
Due to inactivity in the community Nupur Thakur should be moved from MeshMate to Meshmate Emeritus

---

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Rupesh-2003** [comment]
I would like to work on it.

**Comment by Ruth-ikegah** [comment]
> I would like to work on it.

Nice! You have been assigned the issue @Rupesh-2003

**Comment by leecalcote** [comment]
Witness @NupurThakur27's graduation from the MeshMate program. What a wonderful moment this is. Such a thing to be celebrated. Hats off to, Nupur. She will be missed.
