### ISSUE TITLE
[NG] Move button to bottom of Partners page in layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1191]
**Current Behavior**
The "Become a Partner" button is present in the top part of the [partners page](https://layer5ng.netlify.app/partners).

**Desired Behavior**
Move the button to the bottom part, after the description of all partners is done.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@leecalcote thoughts?

**Comment by ColinFendrick** [comment]
I have created a PR for this[here](https://github.com/layer5io/layer5/pull/1193). Notes on some styling adjustments I think should occur are in the comments.

**Comment by Jashpatel1** [comment]
Closing with #1193
