### ISSUE TITLE
[NG] Add latest blog to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1196]
**Current Behavior**
The [Layer5 at Kubecon blog](https://layer5.io/blog/layer5-at-kubecon-na-2020) has been added recently to layer5 site. 

**Desired Situation**
Migrate the blog to layer5-ng site as well. The blogs on layer5-ng can be found [here](https://layer5ng.netlify.app/blog).

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by akashgp09** [comment]
I would like to work on this.

**Comment by Jashpatel1** [comment]
> I would like to work on this.

Sure, please go ahead

**Comment by Jashpatel1** [comment]
Closing with #1202
