### ISSUE TITLE
In addition - Layer5-ng Contribtution.md 

### ISSUE THREAD

**Issue by OlushesiToheeb** [layer5io/layer5#1197]
**Description**

![image](https://user-images.githubusercontent.com/46800177/100457142-cb25b700-30c1-11eb-99b6-c3744dd2d724.png)
Since the layer5-ng is running on Node I would suggest this should be 
`make setup-libs` / `npm install` - To install the dependencies for running the site.
`make site` / `npm start` - To run the website locally.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by akashgp09** [comment]
both the command **make setup-libs** and **make site** are ultimately running **npm install** and **npm start** respectively.

**Comment by OlushesiToheeb** [comment]
I do get make: command not found 
![image](https://user-images.githubusercontent.com/46800177/100460521-9d437100-30c7-11eb-90dc-fc224cdeaf45.png)

**Comment by akashgp09** [comment]
Which OS are you using ?
try **mingw32-make site**

**Comment by Nikhil-Ladha** [comment]
> I do get make: command not found
> ![image](https://user-images.githubusercontent.com/46800177/100460521-9d437100-30c7-11eb-90dc-fc224cdeaf45.png)

Well, that doesn't imply that there is a typo in the doc 🙂. You need to install the `make` tool to use it.

**Comment by OlushesiToheeb** [comment]
> > I do get make: command not found
> > ![image](https://user-images.githubusercontent.com/46800177/100460521-9d437100-30c7-11eb-90dc-fc224cdeaf45.png)
> 
> Well, that doesn't imply that there is a typo in the doc 🙂. You need to install the `make` tool to use it.

Oh yea maybe I shouldn't have to say typo error.

**Comment by leecalcote** [comment]
@vijcheru will you point @OlushesiToheeb to the Windows instructions that you've written and post a request for comment in #general?

**Comment by adekanyetomie** [comment]
@OlushesiToheeb I got this on my end
<img width="364" alt="Screenshot 2020-11-30 at 21 12 52" src="https://user-images.githubusercontent.com/32320578/100659574-1acde200-3351-11eb-839d-839b4f25e3d3.png">

**Comment by vijcheru** [comment]
Sure Lee, I will do that right
away.

**Comment by Nikhil-Ladha** [comment]
I think we are good to close this issue, please re-open it if you have any other concerns @OlushesiToheeb
