### ISSUE TITLE
[NG] Integrate new font

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1206]
**Current Behavior**

Layer5 uses Open Sans as our official font across all our sites, both for paragraphs as well as headings.

**Desired Situation**

We will now be using **Quanelas Soft** for headings and continue with Open Sans for paragraphs or in situations where Quanelas Soft cannot be loaded. The font is ready to be [installed](https://drive.google.com/drive/u/0/folders/1NfWLitxhb3l8zXz7jdGMEwE-lHim1k0h) on your system. 
This change should be reflected across the Layer5-ng site. 

---
**Contributor Resources**

[Layer5 Brand Guide](https://docs.google.com/presentation/d/12XWzUN3MqCm4jchV4RWgkqikPbgkKeTDhipVufNU2BU/edit#slide=id.g984d490928_2_634)

The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@chandrashritii @Tanuj22 Is this addressed completely?
