### ISSUE TITLE
[NG] Add new sections

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1207]
**Desired Situation**

Add the following, new component sections on Layer-ng:

- [x]  Do I need a service mesh?
- [x]  What is a service mesh?

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
@OmkarPh Take it away 👍🏻

**Comment by OmkarPh** [comment]
Yep 👍

**Comment by Nikhil-Ladha** [comment]
I think this issue is complete, but I couldn't find the link to check it out. Can some paste the link here?

**Comment by OmkarPh** [comment]
Actually it's just a section I built for the new home page.
I included it in home page for preview and once everything was reviewed by @Jashpatel1 removed it again.

**Comment by Jashpatel1** [comment]
@OmkarPh Any progress in the second section?

**Comment by Jashpatel1** [comment]
Closing with #1213, #1294
