### ISSUE TITLE
[NG] Revamp the Brand Page

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1208]
**Current Behavior**
The current brand page has cards for each section. The page can be found [here.](https://layer5ng.netlify.app/brand)

**Desired Behavior**
Remove the cards and make it a simple layout. You can take inspiration from [here.](https://www.hashicorp.com/brand)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@OlushesiToheeb will you take this up?

**Comment by OlushesiToheeb** [comment]
yes I'll

**Comment by Nikhil-Ladha** [comment]
Hey, @OlushesiToheeb any progress here?

**Comment by OlushesiToheeb** [comment]
Yes @Nikhil-Ladha, am on it

**Comment by Jashpatel1** [comment]
@OlushesiToheeb We are in a bit of a hurry due to launching the site soon. Can you do it a bit earlier?

**Comment by Jashpatel1** [comment]
Closing with #1320
