### ISSUE TITLE
Twitter card not showing project image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#121]
When a link like https://layer5.io/meshery is shared, social media sites like Twitter should show the image linked within the page. Currently, Twitter does not show the meshery logo in tweets that share the https://layer5.io/meshery link.

Resources:
- https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary
- https://maxchadwick.xyz/blog/twitter-cards-for-jekyll-with-jekyll-seo-tag
- https://css-tricks.com/essential-meta-tags-social-media/

Example:
![Screen Shot 2019-06-15 at 2 23 51 PM](https://user-images.githubusercontent.com/7570704/59555524-50261a80-8f79-11e9-917e-c0c0a8865272.png)

**Comment by leecalcote** [comment]
@anandrkskd do you mind taking a crack at this?

**Comment by anandrkskd** [comment]
yeah will look into that.
