### ISSUE TITLE
[NG] News: KubeCon+CloudNativeCon: Service Mesh Battle Stories and Fixes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1215]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the Layer5 Newsroom. Note: this issue is for the `layer5-ng` branch (site).

**Article:**
- Title: KubeCon+CloudNativeCon: Service Mesh Battle Stories and Fixes
- Link: https://thenewstack.io/kubeconcloudnativecon-service-mesh-battle-stories-and-fixes/

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@bartkalanski how comfortable are you feeling with Gatsby issues? Perhaps, pick this one up?

**Comment by bartkalanski** [comment]
> @bartkalanski how comfortable are you feeling with Gatsby issues? Perhaps, pick this one up?

I haven't got any Gatsby experience, but I'm comfortable with JS and React so perhaps this could be a good learning opportunity ? I'm happy to have a go!

**Comment by leecalcote** [comment]
Good deal. There is little doubt that you’ll be successful in that contributing in this particular area is rather similar to the current Jekyll-based site.
