### ISSUE TITLE
[NG] Add subscribe component to Service Mesh Patterns page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1217]
**Current Behavior**
Please add the mailing list subscriber to this page - https://layer5ng.netlify.app/books/service-mesh-patterns

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
So We simply have to add the subscribe component at the bottom of the page?

**Comment by leecalcote** [comment]
@kishore007k yes, that’s right. So that when someone is intrigued by the book and wants to know when it comes out, theyhave an opportunity to subscribe.

**Comment by kishore007k** [comment]
What the users will be subscribing to, Is it like a mail address or something like in the `home page`?

**Comment by leecalcote** [comment]
layer5.io/subscribe

**Comment by Jashpatel1** [comment]
Closing with #1280

**Comment by Jashpatel1** [comment]
1.
