### ISSUE TITLE
[NG] Use <a> tags instead of <Link> 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1220]
**Desired Situation**
In [SocialLinks](https://github.com/layer5io/layer5/blob/layer5-ng/src/components/SocialLinks/index.js) component use `<a>` tags instead of `<Link>` for all the links 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by thadanipaarth** [comment]
Is this issue still open @Tanuj22 ? I'd like to work on it!

**Comment by Tanuj22** [comment]
@thadanipaarth please go ahead

**Comment by leecalcote** [comment]
Excellent. Good of you to jump in, @thadanipaarth. 👍

**Comment by Nikhil-Ladha** [comment]
Hey @thadanipaarth , how's it coming up? If stuck anywhere feel free to drop your question in the websites channel in our [slack](layer5io.slack.com
) workspace.

**Comment by thadanipaarth** [comment]
I have made the changes and will create PR by EOD. I was going through the documentation of Gatsby and was trying to figure out why exactly are we making this change (https://www.gatsbyjs.com/docs/linking-between-pages/), the documentation mentions this  but reasoning is not provided.

**Comment by Tanuj22** [comment]
> I have made the changes and will create PR by EOD. I was going through the documentation of Gatsby and was trying to figure out why exactly are we making this change (https://www.gatsbyjs.com/docs/linking-between-pages/), the documentation mentions this but reasoning is not provided.

<Link> is used for navigating in between pages of the site. It prevents reloading of the site and hence doesn't destroy the states which would have occurred for <a>. In this issue all the links point to external sites so there is not need for <Link>. So it says to replace it with <a>

**Comment by thadanipaarth** [comment]
Okayy, I have created the PR. Have a look! I took the liberty to open the social media pages in a new window.

**Comment by Jashpatel1** [comment]
Closing with #1249
