### ISSUE TITLE
[NG] New Post Wanted: Functional Testing with Cypress in Meshery UI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1223]
**Current Behavior**
@ramrodo delivered a great presentation on Cypress and considerations for its use.

**Desired Behavior**
A follow up blog post accompanied with slides from [the presentation](url) would be a nice addition.

- Title: _Functional Testing with Cypress in Meshery UI_
- Ideal post content: 
  - What Meshery UI and the Meshery Provider UI are and why end-to-end testing is necessary
  - how Meshery UI and the Meshery CI process uses Cypress
    - anti-fragile test writing practices
  - what we like about Cypress; what we don't like about Cypress
  - one or more of the slides exported and provided for context
  - an invitation and call to action to join @ramrodo in the community and engage in Layer5 projects 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
Closing with #1278
