### ISSUE TITLE
[NG] Add some description text to certain pages present on layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1226]
**Current Behavior**
A few pages on the layer5-ng website do contain only collections and no description on the type or category of collections.

**Desired Behavior**
Add a description to [projects](https://layer5ng.netlify.app/projects), [learn](https://layer5ng.netlify.app/learn), [book](https://layer5ng.netlify.app/learn/books), [workshops](https://layer5ng.netlify.app/learn/workshops), and [programs](https://layer5ng.netlify.app/programs) page on the layer5-ng website.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@leecalcote @chandrashritii ^^

**Comment by leecalcote** [comment]
A little snark will go a long way. Thank you for tasking me here, @Jashpatel1

**Comment by Jashpatel1** [comment]
Closing as issue is solved.
