### ISSUE TITLE
[News] Service Mesh Offers Promising Solution for Cloud Native Networking

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1229]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the Layer5 Newsroom.

**Article:**
- Title: Service Mesh Offers Promising Solution for Cloud Native Networking
- Link: http://www.enterprisenetworkingplanet.com/datacenter/datacenter-blog/service-mesh-cloud-native-networking.html

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by pjzzz** [comment]
I would like to work on this issue.

**Comment by pjzzz** [comment]
Since there is no image in the news article Layer5 logo appears or something else is expected.
![layer5](https://user-images.githubusercontent.com/35733240/101593348-c9d78100-3a15-11eb-9180-2a2037e49a4a.png)

**Comment by leecalcote** [comment]
Hi @pjzzz, yes, that'll work... apologies... we need this up immediately. I'm going to post now.

**Comment by leecalcote** [comment]
@pjzzz thank you for picking up this issue. A time-sensitive need caused me to knock this one out quickly earlier today. There  are a few other open issues similar in nature to this one that you are welcome to, though.

**Comment by pjzzz** [comment]
@leecalcote Oh Okay. I will look for other similar issue and try working on them :)
