### ISSUE TITLE
[NG] News: Service Mesh Offers Promising Solution for Cloud Native Networking

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1230]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the Layer5 Newsroom.

**Article:**
- Title: Service Mesh Offers Promising Solution for Cloud Native Networking
- Link: http://www.enterprisenetworkingplanet.com/datacenter/datacenter-blog/service-mesh-cloud-native-networking.html

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
@leecalcote, Is there some Image for this `news` to show on the site? I can't find any Image from the News article.

**Comment by leecalcote** [comment]
Here we are...

![enterprise-networking-planet](https://user-images.githubusercontent.com/7570704/101868761-a874b300-3b43-11eb-9b14-ccf0ef1ff63f.png)

**Comment by Jashpatel1** [comment]
Closed with #1267
