### ISSUE TITLE
[NG] Community: Recognizing Jome Favorite as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1232]
**Current Behavior**
@jomefavourite has been a consistent contributor and community member.

**Desired Behavior**
A profile for @jomefavourite should be created and visible on `/community/members` on next generation layer5.io site.

- Github: https://github.com/jomefavourite
- Twitter: FavouriteJome1
- LinkedIn: jome-favourite-677766184 
- Profile picture: https://media-exp1.licdn.com/dms/image/C4D03AQExGngMYEUpyw/profile-displayphoto-shrink_800_800/0/1567155649833?e=1613001600&v=beta&t=nMVIParV5cTDbnrVl9ETaD-dRUqtpDzEPybu0xhJJ3g

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by jomefavourite** [comment]
I'm sorry, I changed my username so it LinkedIn: favourite-jome-677766184

**Comment by PluckyPrecious** [comment]
Hey @jomefavourite could you kindly provide a short bio, thanks.

**Comment by jomefavourite** [comment]
Something short right?

**Comment by PluckyPrecious** [comment]
> Something short right?

Right. One or two lines.👌🏽

**Comment by jomefavourite** [comment]
Okay

Aspiring Fullstack Developer, with an enthusiasm for learning.
