### ISSUE TITLE
[NG] reduce the size of megamenu

### ISSUE THREAD

**Issue by vineethvanga18** [layer5io/layer5#1233]
**Current Behavior**

The current megamenu is slightly large
![Screenshot from 2020-12-08 07-54-27](https://user-images.githubusercontent.com/44473939/101430398-ed71cd00-392a-11eb-82dc-dc7d78878955.png)

**Desired Situation**

Reduce the overall size of this menu

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Thank you, @vineethvanga18

**Comment by Jashpatel1** [comment]
@vineethvanga18 @leecalcote Is it completed?
