### ISSUE TITLE
[NG] image sizing in megamenu

### ISSUE THREAD

**Issue by vineethvanga18** [layer5io/layer5#1234]
**Current Behavior**

Currently image sizes in megamenu are not the same
![Screenshot from 2020-12-08 08-21-40](https://user-images.githubusercontent.com/44473939/101432284-97068d80-392e-11eb-898d-ed9a549862f5.png)

**Desired Situation**

Use card component around these images and resize them 

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@vineethvanga18 will you identify the ideal image size and ideal aspect ratio for images to fit into these spots?

**Comment by leecalcote** [comment]
@vineethvanga18, you can add a section in the site design spec to document this - https://docs.google.com/document/d/1rvUZy2_S1a2_14BAQIg6b9cMhUuu04kYzkOPDPaPptI/edit#

**Comment by vineethvanga18** [comment]
@leecalcote yes, maybe we can use cards in https://layer5ng.netlify.app/blog

**Comment by leecalcote** [comment]
@vineethvanga18 good suggestion, however, it ends up being too many cards on cards.

**Comment by Jashpatel1** [comment]
@leecalcote @vineethvanga18 Is it completed?

**Comment by vineethvanga18** [comment]
@Jashpatel1 yes.
Iam closing this along with #1233
