### ISSUE TITLE
[NG] Community: Recognizing Augustine Ogiza as a Contributor and Community Member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1237]
**Current Behavior**
@austinogiza has been a consistent contributor and community member.

**Desired Behavior**
A profile for @austinogiza should be created and visible on `/community/members` on next generation layer5.io site.

- Github: https://github.com/austinogiza
- Twitter: austinogiza
- LinkedIn: augustine-ogiza-b1730691
- Profile picture: https://media-exp1.licdn.com/dms/image/C4D03AQEkdMLe7eA0ZA/profile-displayphoto-shrink_400_400/0/1580390262400?e=1613001600&v=beta&t=1vHMaGmx3NzUusof7lgpK8X29U2Is_yTE1fZXoitSuk

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by MaximeCoignus** [comment]
Hi @leecalcote, @Ruth-ikegah,

Can I take this one?

**Comment by Ruth-ikegah** [comment]
> Hi @leecalcote, @Ruth-ikegah,
> 
> Can I take this one?

sure! Assigned to you now
