### ISSUE TITLE
[Landscape] Kuma

### ISSUE THREAD

**Issue by subnetmarco** [layer5io/layer5#1239]
**Current State:**

It is stated that Kuma doesn't support proxy auto injection.

**Desired State:**

Kuma does indeed support proxy auto injection in Kubernetes environments.

Also: What is the criteria to adding projects in your "Comparison of Service Mesh Strengths" section at the top, and how can Kuma be included in it?

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

**Comment by nik-redhat** [comment]
@subnetmarco thank you for opening this issue and bringing it to our notice. I will soon be sending out a PR to update the same on the landscape :)

**Comment by Nikhil-Ladha** [comment]
@subnetmarco thank you for opening this issue and bringing it to our notice. I will soon be sending out a PR to update the same on the landscape :)

**Comment by Nikhil-Ladha** [comment]
> Also: What is the criteria to adding projects in your >"Comparison of Service Mesh Strengths" section at the >top, and how can Kuma be included in it?

Tagging @leecalcote and @dhruv0000 here for the same.

**Comment by Nikhil-Ladha** [comment]
@subnetmarco you might also wanna look at https://layer5.io/landscape#smi table to get some reference about the same.

**Comment by dhruv0000** [comment]
Hey @subnetmarco. The meshes represented in the section are the ones that are active part of the initiavities we are involved in. One such initiative is [SMI](https://smi-spec.io/). Kuma’s participation in [SMI conformance testing initiative](https://layer5.io/projects/service-mesh-interface) will significantly bolster Kuma's chances of landing in the comparison section. You can check out our ongoing effort [here](https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit?usp=sharing) and maybe even drop some suggestions.
