### ISSUE TITLE
Add HAProxy to Landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#124]
@dcorbett-haproxy, it'd be great to have HAProxy represented in the landscape. Will you consider a contributing a PR to ensure its accuracy?

[Contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by anandrkskd** [comment]
hi @subhamkrai , will you consider adding (via PR) for Adding HAProxy to the [service mesh landscape](https://layer5.io/landscape)?
[Contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) 
 We would love to have your PR.

Thanks!

**Comment by leecalcote** [comment]
//cc @dcorbett-haproxy

**Comment by subhamkrai** [comment]
@anandrkskd thank you for adding me. Looking forward to this.

**Comment by anandrkskd** [comment]
@dcorbett-haproxy , would you consider taking a look for adding HAProxy to [Landscape](https://layer5.io/landscape)?
 We would love to have your PR.
[Contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Much appreciated, @dcorbett-haproxy!
