### ISSUE TITLE
[NG] Community: Recognizing Utkarsh Srivastava as a Contributor and Community Member

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#1243]
**Current Behavior**

@utkarsh-pro has been a consistent contributor and community member.

**Desired Situation**

A profile for @utkarsh-pro should be created and visible on /community/members on the next-generation layer5.io site.

- Github: https://github.com/utkarsh-pro
- Twitter: 
- LinkedIn and Profile picture: @utkarsh-pro please can you provide a link to your LinkedIn, Twitter, and a profile picture

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by MaximeCoignus** [comment]
Hi @Ruth-ikegah,

Can I take this one up?

**Comment by Ruth-ikegah** [comment]
Sure! You have been assigned to it!
