### ISSUE TITLE
[NG] [Blog] New Post Wanted: Buf protocols

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1244]
**Current Behavior**

@kalradev presented a highly informative presentation on Buf, followed by a demo.

**Desired Situation**

A post to follow up and elaborate on the topic, with insights from the [original presentation](https://docs.google.com/presentation/d/1lnZq-d-Q__Mxhay0psJ-TAuKOLHApxOC1xeLy4HxCxE/edit?usp=sharing)

Tentative Title: Buf - Rethinking Protocol Buffers 
Content: 
- What is Buf?
- Features
- Comparison between Protobuf and Buf
- What caught our eye?
- Roadmap to adopting Buf
- An invitation and call to action to join @kalradev in the community and engage in Layer5 projects

Slides from the deck can directly be used as info-graphics for the post

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@kalradev Any progress here?

**Comment by leecalcote** [comment]
Applying the 'layer5-ng' label. When this blog post is written, it can land there.

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha Is this issue up for grabs? 👀

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Is this issue up for grabs? 👀

Ohh, I guess you will have to write the blog post yourself. Just a CAUTION incase you were not sure. If, you are comfortable, please go ahead.

**Comment by adithyaakrishna** [comment]
No worries, I'll do this for sure 💪🏻
