### ISSUE TITLE
[NG] Community: Recognizing Lolyparty as a Contributor and Community Member 

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/layer5#1247]
**Current Behavior**
 @lolyparty has been a consistent contributor and community member.

**Desired Situation**
A profile for @lolyparty should be created and visible on /community/members on next generation layer5.io site.

Github: https://github.com/lolyparty
Twitter: lolyparty
LinkedIn: olayiwola-ololade-064933168
Profile picture: https://i.postimg.cc/vZkSsNq5/IMG-20180929-155636.jpg

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Yay, @lolyparty! 🎈

**Comment by KarenEfereyan** [comment]
Lovely

**Comment by KarenEfereyan** [comment]
And I always thought lolyparty was a girl. Nice one anyway

**Comment by lolyparty** [comment]
> And I always thought lolyparty was a girl. Nice one anyway

Lol no, we did HNG internship together and we were in the same group. Don't know if you can remember.

**Comment by MaximeCoignus** [comment]
Hi @Ruth-ikegah,

Can I take this one up?

**Comment by lolyparty** [comment]
> Hi @Ruth-ikegah,
> 
> Can I take this one up?

Yes, you can. p. s. My Twitter handle has changed to `lolyparty`

**Comment by PluckyPrecious** [comment]
> Hi @Ruth-ikegah,
> 
> Can I take this one up?

Hey @MaximeCoignus would you like to add this issue #1232 as you’ll be working on same file?
