### ISSUE TITLE
[NG] Community : Contributor and Community Member Profile Template

### ISSUE THREAD

**Issue by pjzzz** [layer5io/layer5#1256]
**Current Behavior**

Community Members need to mimic a fellow member.

**Desired Situation**

A generic Member Profile Template with instructions to add New Community Members to the new Website.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@pjzzz Thanks for opening this up. Would you mind to work upon this issue?

**Comment by pjzzz** [comment]
Yeah I am working on it. But I need some help. Since we dont want to create this member-template page similar to skipping news-template I added the attribute _published: false_ but I think that way we will need to add this attribute to all members and maybe also make changes in gatsby-node.js.  What exactly is the way to approach this?

**Comment by Tanuj22** [comment]
> Yeah I am working on it. But I need some help. Since we dont want to create this member-template page similar to skipping news-template I added the attribute _published: false_ but I think that way we will need to add this attribute to all members and maybe also make changes in gatsby-node.js. What exactly is the way to approach this?

Yes you are correct. `published` attribute will have to added to all the profiles. Then in the gatsby node query for only the published true and and also in `section/Members-gird/`

**Comment by Tanuj22** [comment]
If you need more help please feel free to ping me on slack :)
