### ISSUE TITLE
Subscribe Link

### ISSUE THREAD

**Issue by brinal8055** [layer5io/layer5#1275]
**Description**
At the bottom of "Service Mesh Patterns" introductory page, _Subscribe below for updates on this book._  is a simple text.

**Expected Behavior**
Rather than Simple text it should be **Hyperlink Text** .

**Screenshots**
![1](https://user-images.githubusercontent.com/55130735/102345691-c7e86180-3fc3-11eb-930b-ca5b1c80b44f.png)

---

[Optional] **To Reproduce**
1. Go to [this page](https://layer5ng.netlify.app/books/service-mesh-patterns)
3. Scroll down to 'End of the page'

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@brinal8055 Thanks for opening this up. Will you like to take this up?

**Comment by Nikhil-Ladha** [comment]
Hi, @brinal8055 thanks for exploring our upcoming site. But as the statement says 'Subscribe **below** for updates on this book', by which it means to check for a subscribe component below which we have in our footer. And I think that's evident from the text itself.
Or if the text would have something like 'Please `Subscribe Us` for more updates on this book' then it should have been a hyperlink.

Hopefully, I was clear at my point and I think this is not an issue.

**Comment by Jashpatel1** [comment]
I totally agree with Nikhil's point. But for the time being, we work on the component, @brinal8055 you can add this link for now: https://layer5.io/subscribe

**Comment by Jashpatel1** [comment]
Closing with #1277
