### ISSUE TITLE
Add badge for open "help wanted" issues

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#128]
Within the project README, it would be nice to have a badge showing the number of currently open issues carrying the "help wanted" label. This snippet of markdown should do the trick when added to the [README](https://github.com/layer5io/layer5/blob/master/README.md):

`![GitHub issues by-label](https://img.shields.io/github/issues/layer5io/layer5/help%20wanted.svg)
`

**Comment by subhamkrai** [comment]
closes #128
