### ISSUE TITLE
Incorrect logo next to Meshery adapter for Open Service Mesh

### ISSUE THREAD

**Issue by draychev** [layer5io/layer5#1292]
On the https://layer5.io/meshery page, next to `Meshery adapter for Open Service Mesh`, the logo placed is for Octarine instead of OSM.  The OSM logo is already available on layer5.io [here](https://layer5.io/assets/images/service-mesh-icons/osm.svg).

Screenshot: 
![image](https://user-images.githubusercontent.com/49918230/102811473-3a699080-437a-11eb-8273-d8d1a62fc09c.png)

**Expected Behavior**
As described above - the logo highlighted in the screenshot below should be replaced with 
![image](https://user-images.githubusercontent.com/49918230/102811738-b2d05180-437a-11eb-9da6-830c07d09cb2.png)

![image](https://user-images.githubusercontent.com/49918230/102811695-9c29fa80-437a-11eb-9d57-29cbff438fe7.png)

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
@Harshita-Kanal, yes, please. Thank you for highlighting this issue, @draychev. :thu
