### ISSUE TITLE
[NG] Community: Add "MeshMate" filter to community members list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1296]
**Current Behavior**
MeshMates are individuals that freely give of their time to enable and grow others. Their works are appreciated and they as individuals should be highlighted.

**Desired Behavior**
Add "MeshMate filter to this dropdown on the https://layer5ng.netlify.app/community/members/ page:

<img width="285" alt="Screen Shot 2020-12-22 at 1 18 37 PM" src="https://user-images.githubusercontent.com/7570704/102925021-43309400-4458-11eb-8913-53541d77ff33.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
That would be much appreciated, @Harshita-Kanal 👍
