### ISSUE TITLE
[NG] Meshery page - Mega Menu

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1307]
**Current Behavior**

The menu is not visible on the [Meshery](https://layer5ng.netlify.app/projects/meshery) page because of the blue-green color splash.

**Desired Situation**

 The possible solutions here are to either change mega menu highlight colors so that its visible against the blue-green color splash or add an off-white background to the menu headers.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
CC// @Jashpatel1

**Comment by leecalcote** [comment]
Fixed.
