### ISSUE TITLE
[NG] Site - Mega Menu

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1308]
**Current Behavior**

The Mega Menu has poor visibility in mobile view.

**Desired Situation**

Add highlights to make it more obvious (Maybe have a shadow or subtle color transitions on either side)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
@Neil-140301 Will you be taking this up?

**Comment by Neil-140301** [comment]
I'll give it a try

**Comment by leecalcote** [comment]
Ideally, the fact that the user is looking at a (mega) menu is a bit more obvious to them in the mobile view. The following changes should help:
- Add shadow on the left and right sides of the menu (see https://strapi.io mobile menu).
- Change the hamburger menu icon to an "X" or other to distinguish between open and closed.
--- Optional:
- On hover, add a small arrow to the right side of the menu item (see https://stripe.com mobile menu).
- Add a small icon for each menu item (see https://stripe.com mobile menu).

**Comment by vineethvanga18** [comment]
Should we close this? @leecalcote

**Comment by leecalcote** [comment]
Way to bring this one home, @vineethvanga18! I wonder if we will circle back to get the optionals here. Maybe... we can close and refer back this issue, though.
