### ISSUE TITLE
[NG] Workshops Page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1310]
**Desired Situation**

Add a uniform padding for mobile screens on both, the left and right margins so that the content does not look cramped. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
@Nikhil-Ladha Will you be taking this up yourself?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha Will you be taking this up yourself?

Yes, Shriti 👍🏼

**Comment by Tanuj22** [comment]
Sorry, @Nikhil-Ladha didn't see that there is an issue for this and you are assigned :sweat_smile: . I fixed it in #1314

**Comment by Nikhil-Ladha** [comment]
Dang!
You 😆

**Comment by Nikhil-Ladha** [comment]
Fixed in #1314
