### ISSUE TITLE
[NG] Community: Recognizing Adekanye Tomi as a Contributor and Community Member 

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1316]
**Current Behavior**

@adekanyetomie has been a consistent contributor and community member.

**Desired Behavior**
A profile for @adekanyetomie should be created and visible on /community/members on next generation layer5.io site.

 Github: https://github.com/adekanyetomie
 Twitter: adetomiie
 LinkedIn: oluwatomiyin-adekanye-485852150
 Profile picture: https://twitter.com/adetomiie/photo

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@chandrashritii will you use this issue as a template for creating this type of issue: - https://github.com/layer5io/layer5/issues/1232? The required information is captured here.

**Comment by leecalcote** [comment]
Congratulations, @adekanyetomie!

**Comment by Elijah699** [comment]
Can i work on this @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
> Can i work on this @Ruth-ikegah

sure, go ahead

**Comment by Elijah699** [comment]
@chandrashritii there is no information/write-up to fill in for the bio

**Comment by chandrashritii** [comment]
@adekanyetomi  Congratulations! Can you provide a short write up to serve as the bio for your community profile? It can be a one liner or a paragraph. You can see examples of community member bios by clicking on any profile on this page -  https://layer5ng.netlify.app/community/members

**Comment by adekanyetomie** [comment]
m a creative software engineer focused on implementing scalable solutions, thorough communication, writing efficient code, and collaboration with people. I have strong interest in open-source development, advocacy and community building.
