### ISSUE TITLE
Add a new issue Template: New Member Profile

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#1322]
**Current Behavior**

There is no issue template for new member profile, adding an issue template will help make creating that kind of issue easier

**Desired Situation**

- Navigate to https://github.com/layer5io/layer5/tree/master/.github/ISSUE_TEMPLATE
- Add a new md file with the name "New Member Profile"
- Populate it with https://github.com/layer5io/layer5/issues/1316 leaving out spaces for the new member details
---

Feel free to ask questions if this is not clear enough.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Elijah699** [comment]
@Ruth-ikegah i would love to work on this

**Comment by Ruth-ikegah** [comment]
Sure, go ahead!

**Comment by leecalcote** [comment]
Thank you, @Ruth-ikegah. 

@Elijah699 please reference https://github.com/layer5io/layer5/issues/1243. Care was not taken in the formatting used in #1316

**Comment by Tanuj22** [comment]
Fixed in #1325
