### ISSUE TITLE
[NG] FAQ Page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1339]
**Current Behavior**

The questions are not differentiated based on active or inactive state at the moment.

**Desired Situation**

Denote active questions with a color transition (green to grey or vice versa).
[@leecalcote] FAQ Questions need to be updated with appropriate answers.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chinmaym07** [comment]
Hey Can I work on this issue .?

**Comment by leecalcote** [comment]
Yes, that would be great, @chinmaym07 👍

**Comment by chinmaym07** [comment]
Hey @leecalcote did active here is referred to as when a user clicks on the chosen question , then the background  of that question's header block should be changed from green to grey.? Just to verify ...as I cannot see the info about faq in the next gen doc.

**Comment by leecalcote** [comment]
@chinmaym07 thank you for checking the next gen design specification. That's a good thing to do. And you're right, this isn't defined in there. There is, however, a link to the Figma project where Layer5NG designs are held. This behavior isn't defined in those mockups, either, but you will certainly find those mockups helpful.

What you've here is precisely what's been asked for. This is great. Reflecting on the ask, now that I see the behavior in-action, will you make a tweak to the gray that is used and instead use the Dark Jungle Green color?

**Comment by chinmaym07** [comment]
Sure .. Thanks a lot for the feedback @leecalcote. 😀

**Comment by chinmaym07** [comment]
@leecalcote  Can I open a PR for the same .?

![Peek 2021-01-23 01-48](https://user-images.githubusercontent.com/44670961/105541067-3a640400-5d1d-11eb-94b8-eb8fb6bf1bdc.gif)

**Comment by leecalcote** [comment]
Looks great. Yea, please.

**Comment by leecalcote** [comment]
If you’re up for it, a follow-on need here is the ability to filter on specific categories of FAQs, so that this component may be reused on multiple pages, but only show questions and answers from a specific category on a given page. The approach To doing so would be to add a category property to the FAQ component (the filter doesn’t need to be user-facing).

**Comment by chinmaym07** [comment]
Yes sure ..will work on that ... Please list out some of the categories..

**Comment by leecalcote** [comment]
Excellent. Actually, the categories will be dynamic based on information in the FAQ data. Currently, there are two, but this is just a text string match that the component property will do to filter and only show questions of a specific category.

Alternatively, GraphQL can be used to query for questions matching a specific category - again, a string match. Example usage:

`<Faq category="Meshery" />`

**Comment by leecalcote** [comment]
here we are - https://github.com/layer5io/layer5/issues/1401

**Comment by chinmaym07** [comment]
@leecalcote  can we just filter out the FAQ based on the input provided by the user as a radio input ..?

**Comment by Jashpatel1** [comment]
Closing with #1409
