### ISSUE TITLE
[NG] Testing and Tracking the move to Github pages

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1340]
**Task**

This issue is to be used as a tracking point for the move to Github pages. The aim is to build the site, test it locally, report back any roadblocks and fix them before the official move.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
CC// @shubhank-saxena

**Comment by leecalcote** [comment]
Thank you for your help here, @chandrashritii and @shubhank-saxena!
