### ISSUE TITLE
[NG] Contact Page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1341]
**Current Behavior**

The [contact form](https://layer5ng.netlify.app/company/contact#open) currently opens on the same page.
![Screenshot_2021-01-05 Contact(1)](https://user-images.githubusercontent.com/34476976/103569421-3f3b5200-4eed-11eb-966d-32471f6e1cf4.png)

**Desired Situation**

The form should either open in a modal or on a different page.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
@raghavaggarwal99 Do you want to take this up?

**Comment by raghavaggarwal99** [comment]
> @raghavaggarwal99 Do you want to take this up?

**Comment by raghavaggarwal99** [comment]
Cool

**Comment by leecalcote** [comment]
Wait, this isn’t quite what is needed. It’s fine that it opens on the same page. Best to let @Nikhil-Ladha tie this one off.

**Comment by Nikhil-Ladha** [comment]
What we need is a callout to this form on the `faq` page. When, the yser clicks on that callout/button on the faq page then either he should be directed to the contact page with the form 'open'/'visible' or the form can be displayed in a modal in the faq page itself.

I didn't thought about a modal previously, but now I think that might be better. Though @raghavaggarwal99 you are free to implement either of them, whichever is less complex and easier.

**Comment by fatima-ola** [comment]
I will like to work on this

**Comment by leecalcote** [comment]
Hi @raghavaggarwal99, are you still investigating this one or would it be good for @fatima-ola to take a crack at it?

**Comment by Tanuj22** [comment]
Fixed in #1460
