### ISSUE TITLE
Make layer5 logo on layer5-ng bigger on screens of width 912px and below

### ISSUE THREAD

**Issue by lolyparty** [layer5io/layer5#1349]
**Description**

Layer5 logo isn't responsive, it's very tiny on mobile screens(from the width of 912px and below)

**Expected Behavior**

Layer5 logo should be bigger 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@lolyparty are you working on this or I can include this in my ongoing PR?

**Comment by lolyparty** [comment]
> @lolyparty are you working on this or I can include this in my ongoing PR?

No, I'm not working on it. You can include it in your PR

**Comment by Tanuj22** [comment]
FIxed in #1346
