### ISSUE TITLE
[NG] Interactive Partners page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1355]
**Current Behavior**
Layer5 has a number of partners, but in academia and technology.

**Desired Behavior**
A categorized (by type), alternating list of partners with expandable Learn More panel should be available at layer5.io/partners

**Mockups**
See https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=293%3A0

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Here we are, @shubhank-saxena.

**Comment by Nikhil-Ladha** [comment]
@shubhank-saxena how is it coming up? Are we there already?

**Comment by Tanuj22** [comment]
Tracked #1522
