### ISSUE TITLE
[Community] Member Profile: Neil Alvares

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1359]
**Current Behaviour**

@Neil-140301 has been a consistent contributor and community member.

**Desired Situation**
Let's recognizing @Neil-140301 as a contributor and community member by creating a profile on https://layer5ng.netlify.app/community/members.

- GitHub: Neil-140301 
- Twitter: 
- LinkedIn: neil-alvares-2986561a0
- Link to profile picture:

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/layer5-ng">`layer5-ng` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by leecalcote** [comment]
@Neil-140301! Looking good. 😄

**Comment by Neil-140301** [comment]
Thank you @leecalcote  @Jashpatel1 🥳 😁

**Comment by Anita-ihuman** [comment]
Can I take up this issue?

**Comment by leecalcote** [comment]
Yes, please. 👍

**Comment by leecalcote** [comment]
Link to Neil's profile photo - https://drive.google.com/file/d/1-M2IW_zs1GeFpBKtEyZSFoVaNyv8xGVP/view?usp=sharing
