### ISSUE TITLE
[NG] Overlap in pricing section of the landing page

### ISSUE THREAD

**Issue by bartkalanski** [layer5io/layer5#1360]
**Description**
![landing-page-bug](https://user-images.githubusercontent.com/61667381/104463992-57286b00-55aa-11eb-8437-50739b309768.png)
---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Grumpyyash** [comment]
I am working on this if it is still open

**Comment by Nikhil-Ladha** [comment]
Hi @Grumpyyash this is not an issue for the time being. This site is under development and the page will be redesigned completely. 
So, closing the issue.
/cc @bartkalanski

**Comment by bartkalanski** [comment]
> Hi @Grumpyyash this is not an issue for the time being. This site is under development and the page will be redesigned completely.
> So, closing the issue.
> /cc @bartkalanski

No worries, thank you for letting me know!

**Comment by leecalcote** [comment]
@bartkalanski @Grumpyyash speaking of the development of the next version of the layer5.io site (referred to as Layer5-NG), here are the designs for the site - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1231%3A2067. You're most welcome to participate in here by commenting in Figma and picking up any designs that don't have a green checkmark (that aren't already done). Navigation is a little tough to familiarize with at first. Be sure to look to the left menu under Pages. There are lots of designs.

**Comment by bartkalanski** [comment]
It sounds like fun, I'll have a look through the designs! Once I find something suitable I should comment on Figma, and then start building it ?

**Comment by leecalcote** [comment]
@bartkalanski good deal. 😄 Essentially, yes, that'll work. 👍 

There is a collection of maintainers @Nikhil-Ladha, @Tanuj22, @Jashpatel1, and a number of consistent contributors that in are continual communication in the #websites channel in Slack, coordinating who is working on what, feedback, status and so on. They meet weekly on Mondays at 1:30pm (GMT) UK. Details here - https://meet.layer5.io/websites. The team has been fairly diligent with tracking outstanding items at the bottom of [this doc](https://docs.google.com/document/d/1rvUZy2_S1a2_14BAQIg6b9cMhUuu04kYzkOPDPaPptI/edit#heading=h.2ql7puxp02yc) as well.
