### ISSUE TITLE
[NG] Mega Menu: Text overlapping in highlights area

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1375]
**Screenshots**
<img width="963" alt="Screen Shot 2021-01-17 at 10 48 26 PM" src="https://user-images.githubusercontent.com/7570704/104873471-3481b380-5916-11eb-9336-078670263677.png">

**Enviroment:**
- Browser: Chrome
- Browser Width: 1080px

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vineethvanga18** [comment]
@leecalcote looks like someone messed it up since my last PR
![Screenshot from 2021-01-18 10-29-15](https://user-images.githubusercontent.com/44473939/104874164-3f6d3000-5978-11eb-9519-afa3521766a9.png)

**Comment by leecalcote** [comment]
@vineethvanga18 oh, I see. This update might have affected it - https://github.com/layer5io/layer5/commit/a4569972c83f09ca45da66b5246f7a322428cd7a#diff-eae57ae6241cb82daa009e64133fea0bd9fbae67253fb77d46cb1aae7b7b734d. I'm not sure.

While you're in there, will you have the blog title line wrap two lines then cut-off? We have the space for a second line, I believe, and the need for it with longer blog post titles.

**Comment by leecalcote** [comment]
@vineethvanga18 Are these divs being used any longer? https://github.com/layer5io/layer5/blob/a60f6709f20ef33a422347379d2b1c7a13ef22e6/src/sections/Navigation/utility/menu-items.js#L120-L126

**Comment by vineethvanga18** [comment]
closing this @leecalcote
