### ISSUE TITLE
[NG] FAQ Addition: I have already selected and am operating a service mesh. Should I use Meshery? 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1379]
**Desired Enhancement**
Please add the following Q&A to the [layer5-ng FAQ](https://github.com/layer5io/layer5/tree/layer5-ng/src/sections/Faq):

```
Question: I have already selected and am operating a service mesh. Should I use Meshery? 

Answer: As a management plane, Meshery provides value in a number of ways post-adoption of a service mesh. For example, Meshery analyzes your deployments in evaluation of service mesh best practices and patterns, highlighting where you might be deviating. Meshery's Other ways can be articulated in its set of features spanning:

- Lifecycle Management
- Configuration Management
- Performance Management
- Workload Management
```

Link: /projects/service-mesh-management/meshery/features

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
That would be excellent. :)

**Comment by leecalcote** [comment]
All done here!
