### ISSUE TITLE
Link to Welcome Guide

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#138]
A link to the [welcome guide](https://docs.google.com/document/d/17OPtDE_rdnPQxmk2Kauhm3GwXF1R5dZ3Cj8qZLKdo5E/edit?usp=sharing) needs to be added to the Meshery project page under the Community section.

**Comment by arghac14** [comment]
@leecalcote can i help?

**Comment by leecalcote** [comment]
@arghac14 yes, that would be fantastic! The [Contribution Flow](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#contribution-flow) section of the Contribution guide should be what you need to tackle this issue. Thanks for raising your hand. Help here is most appreciated.
