### ISSUE TITLE
[Community] Member Profile: MeshMate Jash Patel 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1382]
**Current Behaviour**

@Jashpatel1 demonstrably embraces the values of and executes upon the activities outlined in Layer5's mentorship program as he supports open source contributors in our community. We invite Jash to don the MeshMate badge and officially join the Layer5 MeshMate program.

**Desired Situation**
Let's recognize Jash as a MeshMate by having his community member profile reflect this role.

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/master">`master` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by bartkalanski** [comment]
I’m on it!
