### ISSUE TITLE
[NG] Links to brand kit zips broken

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1384]
**Description**
The download links here are broken - https://layer5ng.netlify.app/company/brand

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@last-saiyan Will you like to take this up?

**Comment by Nikhil-Ladha** [comment]
I know about this issue.....the path of the zip files are correct but I think it's not working because of being hosted on netlify (just an assumption)....so I would request to keep it as a backlog item and wait for is to go live, and then we can check this.

**Comment by Nikhil-Ladha** [comment]
Ok, so my assumption seems to be wrong and it requires a JS based approach for it to work by making an AJAX request for the file.

**Comment by leecalcote** [comment]
In order to push the file to the browser, specifying the application-type, ok.

**Comment by EmperorYP7** [comment]
May I start working on this if it's not WIP?

**Comment by Nikhil-Ladha** [comment]
Yes, please @EmperorYP7 .

**Comment by EmperorYP7** [comment]
I think this can be closed now.
