### ISSUE TITLE
[NG] Overlapping text in interactive lab cards on Learn page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1385]
**Description**
The https://layer5ng.netlify.app/learn page has overlapping text in interactive lab cards.

**Expected Behavior**
The "Learn how to do..." row should remain on one line and truncate with a trailing "...".

**Screenshots**
![Screenshot from 2021-01-21 11-39-20](https://user-images.githubusercontent.com/7570704/105292891-99d7dd80-5b7e-11eb-88d5-f5aa671df6fc.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by EmperorYP7** [comment]
I'd be glad to work on this. May I go ahead?

**Comment by Nikhil-Ladha** [comment]
@EmperorYP7 actually I have some WIP for this page, so I will be taking this one. You can take some of the other open issues 🙂

**Comment by leecalcote** [comment]
@EmperorYP7 there are plenty more where this comes from, though. Let me know if you don't find one... that just means that they haven't been written up, yet.

**Comment by EmperorYP7** [comment]
@Nikhil-Ladha No problem 😄

**Comment by EmperorYP7** [comment]
@leecalcote only if they ain't WIP by someone else. I'll stick around for a while to find one. Thanks!

**Comment by Nikhil-Ladha** [comment]
@Jashpatel1 can you confirm if the issue is still present for you?
I have checked in my system and it works fine for all views.
