### ISSUE TITLE
[NG] Make Service Mesh Patterns table sortable and filterable

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1386]
**Current Behavior**
The [table of service mesh patterns](https://layer5ng.netlify.app/books/service-mesh-patterns) has two columns, neither of which are sortable, nor filterable.

**Desired Behavior**
1. Users can click on the column name to sort each column, toggling between ascending and descending alphabetical order.
2. Users can filter on Category type. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Yoo-hoo, @EmperorYP7... in case this is of interest.

**Comment by EmperorYP7** [comment]
@leecalcote Thanks for following up so quick. I'd love to take this up! 😄

**Comment by leecalcote** [comment]
Beautiful. :) The description leaves a little room for creativity with respect to item #2 - filtering on Category. I don't know that we have a standard approach to filtering on table columns (tagging @Nikhil-Ladha, @Tanuj22, @Jashpatel1 for guidance). If not, it'd be good to see a suggestion or two from you on the approach.

**Comment by Nikhil-Ladha** [comment]
There is an option to filter columns in react-table, please use that.
Checkout this link: https://react-table.tanstack.com/docs/overview

**Comment by EmperorYP7** [comment]
@Nikhil-Ladha Thanks for the docs.

Here's one quick question, do I need to retain the subsections (or "Areas") in the table while sorting i.e. sort each subsection independently?

**Comment by Nikhil-Ladha** [comment]
Hmm, yeah that should be the way.

**Comment by Jashpatel1** [comment]
Closing with #1400
