### ISSUE TITLE
[Community] Member Profile: Harshita Kanal

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1389]
**Current Behaviour**

@Harshita-Kanal has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Harshita-Kanal  as a contributor and community member by creating a profile on https://layer5ng.netlify.app/community/members.

- GitHub: Harshita-Kanal
- Twitter: harshita_kanal
- LinkedIn: https://www.linkedin.com/in/harshita-kanal-400563166/
- Link to profile picture: https://drive.google.com/file/d/1P2wVbjk_BPrT2ubLLS517OYXnuZsJgft/view?usp=sharing

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/layer5-ng">`layer5-ng` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by Harshita-Kanal** [comment]
Thank you! 😄

**Comment by leecalcote** [comment]
Whoo-hoo! 🎈

**Comment by Jashpatel1** [comment]
@EmperorYP7 will you like to take this up?

**Comment by Jashpatel1** [comment]
@Harshita-Kanal Can you provide a short bio which could feature on your member page?

**Comment by EmperorYP7** [comment]
@Jashpatel1 Sure!

**Comment by Harshita-Kanal** [comment]
> @Harshita-Kanal Can you provide a short bio which could feature on your member page?
Sure, thanks 🙂
My bio:
"I am a Computer Science undergraduate, Web developer and an Open Source enthusiast. I love building things that impact people's lives."

**Comment by Jashpatel1** [comment]
@EmperorYP7 Any updates here?

**Comment by EmperorYP7** [comment]
Sorry for being dormant for a while. Will be working on it now.

**Comment by Jashpatel1** [comment]
Closed with #1470
