### ISSUE TITLE
[Community] MeshMate Profile: Dev Kalra and Jash Patel

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#1390]
**Current Behavior**

@kalradev and @Jashpatel1 have been consistent contributors and community leaders. They are both considered worthy by the community and have thus been asked to take up the responsibility of being a [Layer5 MeshMate](https://layer5ng.netlify.app/community).

**Desired Situation**

Dev Kalra and Jash Patel should be recognized as MeshMates by creating their profiles on the  [MeshMates](https://layer5ng.netlify.app/community/meshmates) page.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
A half duplicate - https://github.com/layer5io/layer5/issues/1382

**Comment by leecalcote** [comment]
Closing, because this is a duplicate. @kalradev ping @chandrashritii when you come back. 👍
