### ISSUE TITLE
[NG] Blog Modal Pops In

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1392]
**Description**

**Expected Behavior**

Initially when the layer5-ng website loads ,when you hover beneath layer5 logo the blog modal pops-in . 
I have attached the gif of the same .
**Screenshots**

![Peek 2021-01-21 21-50](https://user-images.githubusercontent.com/44670961/105383478-2cd44e80-5c37-11eb-98ab-9f6038d5421a.gif)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Yikes. Would you like to try your hand at this one, @chinmaym07? If so, great!

See @vineethvanga18 with any questions. He is the component lead for the navbar and mega menu.

**Comment by chinmaym07** [comment]
Yes ..sure.!!

**Comment by vineethvanga18** [comment]
closing this, as this is resolved.
