### ISSUE TITLE
[Epic] Discourse-based Discussion Forum

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1394]
### Discourse-based Discussion Forum
In the course of serving visitors, we need to establish [discuss.layer5.io](https://discuss.layer5.io). This website will use 
[Discourse](https://www.discourse.org) as the underlying platform to provide a forum for discussion of service mesh technology.

While none of Layer5’s blog posts will allow for commenting, discuss.layer5.io will. This will be the platform for engaging users and customers in a discussion forum-style interaction with topics spanning all areas of service mesh concerns.

#### Goal
1. Be _the_ user-facing place to have asynchronous discussion about all service meshes and all Layer5 projects.

#### Objectives

1. [DevOps] Identify Discourse server configuration (archival, spam, authentication, and so on)
1. [DevOps] Establish Discourse deployment (highly-available server and domain)
1. [Design] Establish Discourse information architecture (categories, topics, and so on)
1. [Design] Customize visual appearance and layout to complement the main layer5.io site.
1. [Content] Seed site content prior to public release.

- **[Design Specification](https://docs.google.com/document/d/1MDdIZGr8cw_iyZD1H4G7k8AbcFJ79_4UhbKgGltfa7U/edit)**
- **[Mockups](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4850%3A10)**
- **Implementation**
  - [x] Nav Bar #1716
  - [x] Hero #1717
  - [x] Footer #1715
  - [ ] Plugins
    - Mandatory
    - [ ] Akismet
    - [ ] Solution
    - [ ] Calendar
    - [ ] 
    - Optional
    - [ ] GitHub
    - [ ] Vote
    - [ ] 
---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by vinayaksh42** [comment]
we can use [gatsby talkyard plugin](https://www.gatsbyjs.com/plugins/@debiki/gatsby-plugin-talkyard/?=disqus) for having discussions under blogs.

**Comment by leecalcote** [comment]
@ramrodo is this of interest to you?

**Comment by leecalcote** [comment]
> we can use [gatsby talkyard plugin](https://www.gatsbyjs.com/plugins/@debiki/gatsby-plugin-talkyard/?=disqus) for having discussions under blogs.

Oh, thank you, @vinayaksh42. In this case, we're looking for a broad set of topics and discussions on service mesh and all of Layer5's projects.

**Comment by vinayaksh42** [comment]
okay, @leecalcote so it's more like a web forum and not just simple comments on a page

**Comment by ramrodo** [comment]
> @ramrodo is this of interest to you?

The platform sounds interesting but maybe I don't have enough time to set up but I can offer my help to those who is assigned 👍🏼

**Comment by leecalcote** [comment]
@ramrodo thank you for considering this. Sounds real good. Understood regarding being out of time. ✔️

**Comment by leecalcote** [comment]
@Jashpatel1 we're in need of issues for each of the checklist items.

**Comment by Jashpatel1** [comment]
> @Jashpatel1 we're in need of issues for each of the checklist items.

Sure, will add them.

**Comment by Jashpatel1** [comment]
Closing as issue is solved.
