### ISSUE TITLE
[NG] SEO Mechanics and Process

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1395]
### [NG] SEO Mechanics and Process

The website needs to espouse the culture and values of Layer5 and it needs to attract, serve, and sell to visitors. Visitors come in different forms:

1. Contributors evaluating and participating in our community.
1. Adopters evaluating and using our projects.
1. Customers evaluating and using our products.

#### Goal: Attracting visitors
Layer5.io should be the epitome of where people find helpful service mesh resources. Ultimately, thousands of pages need to be created in order to realize this vision. Search Engine Optimization and visitor analytics will be important. A thoughtful approach to facilitating the sourcing of this content will be important.

#### Objectives

1. Consider for search engine optimization. 
1. Use maximally efficient information architecture to improve domain authority and domain relevance for service mesh technology keywords.
1. Ensure framework adheres to SEO best practices, so that content contributors follow these guidelines.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Jashpatel1** [comment]
@leecalcote I will be taking this up.

**Comment by leecalcote** [comment]
@Jashpatel1 have you been able to confirm the desired behavior with the images metadata using https://cards-dev.twitter.com/validator or https://www.linkedin.com/post-inspector/?

**Comment by Jashpatel1** [comment]
> @Jashpatel1 have you been able to confirm the desired behavior with the images metadata using https://cards-dev.twitter.com/validator or https://www.linkedin.com/post-inspector/?

LinkedIn works fine, Twitter images has some issue, will fix.
