### ISSUE TITLE
"https://layer5.io/programs/past/gsoc/2019" link gives a 404

### ISSUE THREAD

**Issue by pranav-bhatt** [layer5io/layer5#1397]
Found on [the Layer5 GSoC page](https://layer5.io/programs/gsoc)

**Comment by leecalcote** [comment]
Thanks for opening this, @pranav-bhatt. Will you identify where you found this broken link, so that it might be fixed?

**Comment by pranav-bhatt** [comment]
For some weird reason, it hadn't updated the description. Fixed it now!

**Comment by leecalcote** [comment]
Would you like to take this one on, @pranav-bhatt? 

The fix here can be quick (can be simple - maybe removing the reference/link) given the we will be moving to a completely new layer5.io site shortly.

It would be good to confirm whether the new site handles this same issue or not.

**Comment by pranav-bhatt** [comment]
Sure, I'll remove the link for now.
