### ISSUE TITLE
[NG] Enhance FAQ component to support filtering on Q&A category

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1401]
**Current Behavior**
The FAQ component retrieves the full set of questions and answers, but offers no ability to only display questions and answers of a specific category (e.g. "service mesh", "meshery").

**Desired Behavior**
Enhance the FAQ component to support the ability to filter on specific categories of FAQs, so that this component may be reused on multiple pages, but only show questions and answers from a specific category on a given page. 

#### Implementation 
The approach to doing so would be to add a category property to the FAQ component (the filter doesn’t need to be user-facing). The categories will be dynamic based on information in the FAQ data. The FAQ component isn't aware of the name of the category beforehand.

Example usage:

```
<Faq category="Meshery" />
```

1. (preferred) Use GraphQL to query for questions matching a specific category provided as a prop.

or ...

2. (alternative) Retrieve all FAQs, iterate through the FAQs, only showing those that belong to a category matching the string provided as a component property.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
That’s be great, yes, @Harshita-Kanal
