### ISSUE TITLE
[NG] Custom React Component: Blockquote

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1402]
**Current Behavior**
In blogs and other pages, the Layer5 site needs to the ability to show a stylized quote from a person. 

**Desired Behavior**
A new custom React component needs to show the person's quote, name, and title. Name and title can be optional properties.

**Implementation**
Turn this into a custom component called "Blockquote" - https://codepen.io/jupago/pen/GPxqLX

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by bartkalanski** [comment]
I’ve got this!

**Comment by leecalcote** [comment]
uh-oh.... I couldn't help myself and gave it a quick try... Let me point you at it and see what you think...

**Comment by leecalcote** [comment]
A WIP, but functional - https://github.com/layer5io/layer5/tree/leecalcote/blockquote

**Comment by leecalcote** [comment]
Let me tie this off real quick and send your way for review and improvement (particularly around optional properties), @bartkalanski.

**Comment by bartkalanski** [comment]
@leecalcote No worries at all, I look forward to seeing how you’ve approached this!

**Comment by leecalcote** [comment]
Ok, 😅. Nearly done... it would be nice to support multiple styles of this, if you're inclined to pick it up and run with it a little further.

**Comment by bartkalanski** [comment]
@leecalcote sounds good!

**Comment by Jashpatel1** [comment]
@leecalcote Does #1403 solve this completely?

**Comment by leecalcote** [comment]
Great question. This weekend, @bartkalanski will be looking at bringing a second or third format to this component, which is great. 

Given that we have and initial version of the component in place, immediacy of the need here is somewhat relieved and so we can mark this issue milestone post go live.
