### ISSUE TITLE
[NG] Mega Menu: Active menu reverting to "blog" menu on page load

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1405]
**Description**
When the user is on a page and has the mega menu open with cursor on a particular nav bar item, as they click on the nav bar item to navigate to that page, the active menu changes to "blog" even though the user clicked on and _is_ on a different page.

**Expected Behavior**
Active menu stays the same as the nav bar item that they had the menu open to.

**Screenshots**
https://user-images.githubusercontent.com/7570704/105601700-c3e5f700-5d5a-11eb-920b-0746031afaba.mov

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vineethvanga18** [comment]
@leecalcote that is because every time the navigation component mounts the state is set to "blog" menu, previously it was set to "about" menu, for which the mega menu was not there. I will set it to "landscape" menu which doesn't have mega menu.

**Comment by leecalcote** [comment]
Oh, I see
