### ISSUE TITLE
unanswered Faq question

### ISSUE THREAD

**Issue by akashgp09** [layer5io/layer5#1410]
**Description**

In the FAQ section of Layer5-NG  website one of the the question is unanswered

**Expected Behavior**

Provide the appropriate answer to the question

**Screenshots**

<img src="https://i.imgur.com/6jb6RIA.png">

---

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Good eye, @akashgp09. There are a number of these that need content added. Thanks for highlighting this. 👍 

Allow me to bear the burden of responsibility for this content and take this assignment, if you will.

**Comment by akashgp09** [comment]
yeah Sure
