### ISSUE TITLE
[NG] FAQ: Support Variable Number of Answers

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1411]
**Current Behavior**
Answers to FAQs might be long in nature and include multiple sentences (bullet points). The current FAQ component supports a static number of "answers" and does not dynamically account for a variable number of answers. 

```
        {
            question: "Why do I need a service mesh?",
            category: "Service Mesh",
            answer: "",
            answer_2: "",
            answer_3: "",
            answer_4: "",
            answer_5: "",
            link: "",
            linktext: "",
        },
```

**Desired Behavior**
Enhance the FAQ component to support any number of answers (bullet points). 

**Implementation**
Use an iterator to return all of the answers to each question without hard-coding the number of possible answers.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@Harshita-Kanal... what do you think?

**Comment by Grumpyyash** [comment]
Should I give it a try?

**Comment by leecalcote** [comment]
Yes, please, @Grumpyyash 👍
