### ISSUE TITLE
[doc]: Update the document of install ruby

### ISSUE THREAD

**Issue by Aisuko** [layer5io/layer5#1414]
**Current Behavior**

https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md

**Desired Behavior**

The doc can help the contributor install the specific version of the development environment and need to confirm the ruby version is stable for use.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

Reference link:

https://linuxize.com/post/how-to-install-ruby-on-ubuntu-20-04/#installing-ruby-using-rbenv

**Comment by leecalcote** [comment]
I wonder if either of these should be enhanced or links to them published:

1. Jekyll Tutorial - https://docs.google.com/document/d/1JoPujIO_dyX3pTHvbGtQ5OBXERlSInac3ecLSkgFFSo/edit
2. Meshery Documentation - https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit

**Comment by leecalcote** [comment]
I'll suggest that we start with those two resources. What do you think @Anita-ihuman? @PluckyPrecious?

**Comment by PluckyPrecious** [comment]
Hi @leecalcote i think this will be perfect. Is @Aisuko still on this? If no, I can help with it.

> I wonder if either of these should be enhanced or links to them published:
> 
> 1. Jekyll Tutorial - https://docs.google.com/document/d/1JoPujIO_dyX3pTHvbGtQ5OBXERlSInac3ecLSkgFFSo/edit
> 2. Meshery Documentation - https://docs.google.com/document/d/17guuaxb0xsfutBCzyj2CT6OZiFnMu9w4PzoILXhRXSo/edit

**Comment by Anita-ihuman** [comment]
The commands for setting up Jekyll could be made more prominent by writing it as code and not as plain text.
An example of what I mean is this :

2.sudo apt install curl g++ gnupg gcc autoconf automake bison build-essential libc6-dev \
    	libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool \
    	libyaml-dev make pkg-config sqlite3 zlib1g-dev libgmp-dev \
    	libreadline-dev libssl-dev

**Comment by Aisuko** [comment]
@Anita-ihuman Thanks. We use `vscode-dev-containers` to handle this. Please check https://github.com/layer5io/layer5/tree/master/.devcontainer

**Comment by Aisuko** [comment]
Close due to #1597
