### ISSUE TITLE
Implementation of Service Mesh Management section in the homepage

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1420]
**Current Behavior**
We currently have no implementation of the Service Mesh Management section. 

**Desired Situation**
The design of the home page is currently approved on figma, and we will appreciate someone jumping on the task of implementing it 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1869%3A2967

Check out the design below

<img width="997" alt="Group 1008" src="https://user-images.githubusercontent.com/7570704/105899472-5519cf80-5fe0-11eb-8cf8-e393079b55ab.png">

[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by vineethvanga18** [comment]
@Harshita-Kanal how are you getting on with this?

**Comment by Harshita-Kanal** [comment]
Almost done, just sending the PR
