### ISSUE TITLE
Implementation of Proudly maintainers and contributors section on homepage

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1421]
**Current Behavior**
We currently have no implementation of the  Proudly maintainers and contributors section on homepage 

**Desired Situation**
The design of the home page is currently approved on figma, and we will appreciate someone jumping on the task of implementing it 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1869%3A2967

Check out the design below
<img width="1440" alt="proudly" src="https://user-images.githubusercontent.com/44683018/105884100-e5b7d600-6007-11eb-905d-7b67bf5b6a38.png">

[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by adekanyetomie** [comment]
hi @austinogiza I can't find this part in the design. Please can you point it out? Thanks

**Comment by austinogiza** [comment]
@adekanyetomie Kindly check this screenshot for guidance 
![proud](https://user-images.githubusercontent.com/44683018/105827933-dbbfb400-5fc2-11eb-93ba-79298bcd6273.PNG)

**Comment by Grumpyyash** [comment]
Can I try taking this up?

**Comment by Nikhil-Ladha** [comment]
@adekanyetomie are you working on this? Or shall we let @Grumpyyash take it?
