### ISSUE TITLE
Implementation of the Layer5 So Special section on homepage 

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1425]
**Current Behavior**
We currently have no implementation of the Layer5 So Special section on homepage 

**Desired Situation**
The design of the home page is currently approved on figma, and we will appreciate someone jumping on the task of implementing it 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1869%3A2967

**Implementation**
- use react slick (see xxxx page as an example)

**Screenshots**
<img width="1253" alt="Group 1007" src="https://user-images.githubusercontent.com/7570704/105865247-5800ca00-5fb8-11eb-87d2-f0be3ef71ccb.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by UnkleTayo** [comment]
I will like to take this up

**Comment by leecalcote** [comment]
@UnkleTayo that would be great. 👍

**Comment by vineethvanga18** [comment]
@UnkleTayo any updates?

**Comment by Tanuj22** [comment]
@UnkleTayo we need to move fast to get the page ready, so i am opening up the issue for other contributors. Please signal here if you are willing to work on this

**Comment by Tanuj22** [comment]
@chinmaym07 would you like to take it?

**Comment by chinmaym07** [comment]
Yes @Tanuj22 I can try this.

**Comment by Jashpatel1** [comment]
Is it complete @Tanuj22 @chinmaym07 ?
