### ISSUE TITLE
[NG] Meshery Overview page: Feature Showcase Section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1428]
**Current Behavior**
The Meshery overview page needs a section to showcase Meshery's features.

**Desired Behavior**
A vertical carousel allows visitors to browse through a pictorial catalog of Meshery features

**Screenshots / Mockups**
<img width="1440" alt="Group 969" src="https://user-images.githubusercontent.com/7570704/105888973-3e20b080-5fd3-11eb-933e-eeb883884c0f.png">

See [Project: Meshery](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=1107%3A0) page in Figma

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by vinayaksh42** [comment]
Can i work on this?

**Comment by Nikhil-Ladha** [comment]
Well, I was thinking of working on it...but have not yet started..... I just have to say this that if you take this, you will have to complete it by tomorrow afternoon 😅

**Comment by vinayaksh42** [comment]
I don't think I will be able to do it within those time constraints, I would suggest that you should go ahead with this issue. @Nikhil-Ladha

**Comment by Jashpatel1** [comment]
Closing with #1447
