### ISSUE TITLE
[Community] Member Profile: Navendu Pottekkat

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1429]
**Current Behaviour**

@navendu-pottekkat  has been a consistent contributor and community member.

**Desired Situation**
Let's recognizing @navendu-pottekkat  as a contributor and community member by creating a profile on https://layer5ng.netlify.app/community/members

- GitHub: navendu-pottekkat
- Twitter: sudo_navendu
- LinkedIn: navendup
- Link to profile picture:

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/layer5-ng">`layer5-ng` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by Jashpatel1** [comment]
@navendu-pottekkat Can you provide a profile picture and short bio to be featured on your member page?

**Comment by navendu-pottekkat** [comment]
Sure @Jashpatel1 Here is the [link to a DP](https://drive.google.com/file/d/10lTmgNh2U38Kwk6AVwFfQ-ZShy011s6F/view?usp=sharing)

**Comment by navendu-pottekkat** [comment]
The bio could be: "I'm working on open-source projects in Deep Learning, Web Development and Cloud-Native Development. My research interests are in memristive systems and computer vision. Coding all day, everyday!"

**Comment by leecalcote** [comment]
Yay! A member profile for @navendu-pottekkat 🎈

**Comment by Jashpatel1** [comment]
Closing with #1430
