### ISSUE TITLE
[Landscape] Comparison Matrix: Table row formatting

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1452]
**Description**
In _Safari_, the following table formatting is improper:

<img width="1218" alt="Screen Shot 2021-01-31 at 3 54 43 PM" src="https://user-images.githubusercontent.com/7570704/106399206-e623e880-63dc-11eb-8847-04dfe00dd622.png">

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
Fixed in #1589
