### ISSUE TITLE
[Landscape] SMI Conformance: Inaccurate data in results

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1453]
@dhruv0000 

Please update the static data in this table. Email to confirm when it is ready to go-live.

What is our ETA on dynamic data?

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@dhruv0000 this has been addressed right?

**Comment by dhruv0000** [comment]
yes
