### ISSUE TITLE
[Community] Picture Slider not filling space

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1454]
**Description**
On the layer5.io/community page, the image slider on the /community page does not fill the space in its container.

**Expected Behavior**
- The image slider on the /community page should fill the majority of the space in its container.

**Screenshots**
<img width="1678" alt="Screen Shot 2021-01-31 at 4 01 54 PM" src="https://user-images.githubusercontent.com/7570704/106399427-1e77f680-63de-11eb-83e1-6d209cc08743.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chinmaym07** [comment]
@leecalcote Can I take this. ?

**Comment by Tanuj22** [comment]
@chinmaym07 looks this this has been addressed but there is not responsiveness issue if you would like to take it up 
![Screenshot from 2021-02-03 21-47-33](https://user-images.githubusercontent.com/42486853/106775858-855d1000-6669-11eb-875b-6afc3d881732.png)

**Comment by chinmaym07** [comment]
Yes .Ohk .I'll work on that .thanks!.

**Comment by Tanuj22** [comment]
Fixed #1476
