### ISSUE TITLE
[Community] Open Source Mentorship Program arrow not vertically centered

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1455]
**Description**
On the layer5.io/community page, the learn more arrow is not vertically center aligned within the green button.

**Screenshots**
<img width="578" alt="Screen Shot 2021-01-31 at 4 06 34 PM" src="https://user-images.githubusercontent.com/7570704/106399500-947c5d80-63de-11eb-860b-1e35e336de24.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chinmaym07** [comment]
I want to take this up.
