### ISSUE TITLE
[Home] Proud Maintainers: responsiveness issues

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1456]
Great job on the ProudMaintainers section, @Grumpyyash.

A few residual issues await you regarding vertical alignment, margins, padding and responsiveness.

@Grumpyyash the update is done....can you fix the responsiveness now....also please check the issue with the path which is causing the build failure.

_Originally posted by @Nikhil-Ladha in https://github.com/layer5io/layer5/issues/1448#issuecomment-770572029_

**Comment by Nikhil-Ladha** [comment]
@Grumpyyash wanna clear this out?

**Comment by Grumpyyash** [comment]
Working on it now

**Comment by Jashpatel1** [comment]
@Nikhil-Ladha @Grumpyyash Is this issue solved?

**Comment by Nikhil-Ladha** [comment]
Yup, wonder why the issue didn't got closed 😂
