### ISSUE TITLE
[NG] Links of books and workshops under Learn tab (navbar) leading to incorrect links

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/layer5#1465]
**Description**

Incorrect link of books and workshops sections in the navbar under the Learn tab.

**Expected Behavior**

Link needs to be /learn/service-mesh-books instead of /learn/books
similarly for /learn/service-mesh-workshops instead of /learn/workshops

File which is needed to be fixed:
https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/General/Navigation/utility/menu-items.js#L95

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Abiola-Farounbi** [comment]
Hi, I would like to be assigned to this issue.

**Comment by Tanuj22** [comment]
@Abiola-Farounbi please go ahead

**Comment by Jashpatel1** [comment]
Closing with #1466
