### ISSUE TITLE
[Community] Member Profile: Chinmay Mehta

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1469]
**Current Behaviour**

@chinmaym07 has been a consistent contributor and community member.

**Desired Situation**
Let's recognizing @chinmaym07 as a contributor and community member by creating a profile on https://layer5ng.netlify.app/community/members.

- GitHub: chinmaym07
- Twitter: 
- LinkedIn: chinmay-mehta-009132193
- Link to profile picture:

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/layer5-ng">`layer5-ng` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by Jashpatel1** [comment]
@chinmaym07 Can you provide a link to your profile picture and a short bio that could feature on your member page?

**Comment by 96RadhikaJadhav** [comment]
@Jashpatel1 Can I work on the issue?

**Comment by Jashpatel1** [comment]
> @Jashpatel1 Can I work on the issue?

Sure, please go ahead.

**Comment by chinmaym07** [comment]
Yes sure @Jashpatel1 . Thanks a lot . 👍🏻  😀 
link : https://drive.google.com/file/d/1x_-sQc3OuJfwqE89oJKqxQrKb-Lbv5i9/view?usp=sharing
Bio :I am an undergraduate student at IIIT Bhubaneswar. I am a Web developer & Open Source enthusiast .I love problem solving & always ready to learn and explore something new everyday.

**Comment by Jashpatel1** [comment]
@96RadhikaJadhav Will you create a PR for layer5-ng branch as well?

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav Will you create a PR for layer5-ng branch as well?

@Jashpatel1 Yeah sure. I have searched how to do it, but didn't get proper answer. Could you please help me in getting an idea about the steps to do it?

**Comment by Jashpatel1** [comment]
> > @96RadhikaJadhav Will you create a PR for layer5-ng branch as well?
> 
> @Jashpatel1 Yeah sure. I have searched how to do it, but didn't get proper answer. Could you please help me in getting an idea about the steps to do it?

https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md#contributor-instructions
You can ping me on Slack, if you get stuck anywhere. You can join layer5 on slack - http://slack.layer5.io/

**Comment by 96RadhikaJadhav** [comment]
@Jashpatel1 Created a PR for layer5-ng branch #1501 . Please review and let me know if any changes required.

**Comment by Jashpatel1** [comment]
Closing with #1501
