### ISSUE TITLE
[Community] Add subtly bouncing "Start here -->" to Contributor Journey Map

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1471]
**Current Behavior**
The Contributor Journey map is interactive, but many visitors may over look this fact and miss out on the resources.

**Desired Behavior**
Using the theme's Keppel green color, add a subtly bouncing arrow and "Start here", like in the mockup.

**Screenshots / Mockups**
<img width="1208" alt="Screen Shot 2021-02-03 at 2 36 49 PM" src="https://user-images.githubusercontent.com/7570704/106806436-9720c200-662d-11eb-82ad-310a72c7a4db.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by bartkalanski** [comment]
Will get this done by Friday eve

**Comment by leecalcote** [comment]
Good, good!
