### ISSUE TITLE
Add Cilium to Service Mesh category

### ISSUE THREAD

**Issue by ziruihao** [layer5io/layer5#148]
[https://cilium.io/](Cilium) is a DaemonSet-based service mesh data and control plane for microservices.

**Comment by leecalcote** [comment]
@ziruihao thanks for this! It'd be great to have Cilium included in the landscape. As much as possible, we ask for the community to curate the landscape, so as to both ensure the accuracy of its contents and ownership of the specific projects/products once they have been added. 

We very warmly welcome a PR to add Cilium. The steps to do so are straight forward - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md. Would you mind submitting an edit for inclusion?

**Comment by leecalcote** [comment]
//@tgraf @aanm

**Comment by ziruihao** [comment]
@leecalcote thanks for the information, Lee. I'll try to do my best but a bit busy - I came into this topic from a VC perspective looking into mesh startups.

Cilium was of interest to enterprises because of its on-premise support.

**Comment by ziruihao** [comment]
What is the `ga-1-date` property in `non-functional.yml`? @leecalcote

**Comment by leecalcote** [comment]
Good question, @ziruihao. It's essentially the date by which version 1.0 of the product/product was publicly offered. The "General Availability" date, which is sometimes distinct from that of the project announcement date (most often is in the case of OSS projects).

**Comment by leecalcote** [comment]
@tgraf @aanm, it would be great to have you represent Cilium in this landscape.

**Comment by leecalcote** [comment]
@tgraf @aanm, any interest here?
