### ISSUE TITLE
[Community] Unwanted whitespace on right side of Newcomers section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1480]
**Description**
The /community page has unwanted whitespace on right side of Newcomers section.

**Expected Behavior**
Gray background should be edge-to-edge (full bleed)

**Screenshots**
<img width="1506" alt="Screen Shot 2021-02-04 at 12 17 22 PM" src="https://user-images.githubusercontent.com/7570704/106937338-4075bf80-66e3-11eb-88b2-b51af0557f99.png">

**Environment:**
- Browser: Safari... and others?

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Abiola-Farounbi** [comment]
Hi, I would like to be assigned to this issue

**Comment by leecalcote** [comment]
Excellent!
