### ISSUE TITLE
[Home] Proud Maintainers: spacing is off in grid; escaped logos

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1483]
**Description**
In the Proud Maintainers section of the Home page, the issues shown in the screenshot are present.

**Screenshots**
<img width="1141" alt="Screen Shot 2021-02-04 at 9 44 50 PM" src="https://user-images.githubusercontent.com/7570704/106987039-42b33a80-6732-11eb-92ed-2e43d1896d09.png">

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@grumpyyash is this something you're able to promptly address? If not, that's ok. Please let us know quickly.

**Comment by Grumpyyash** [comment]
I will just check where the issue is arising
