### ISSUE TITLE
[Community] Member Profile: Alonso López Romo

### ISSUE THREAD

**Issue by jesuslerma** [layer5io/layer5#1492]
**Current Behaviour**

@alonsolopezr has been a consistent contributor and community member.

**Desired Situation**
Let's recognizing @alonsolopezr as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: alonsolopezr
- Twitter: 
- LinkedIn: 
- Link to profile picture:

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/master">`master` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by leecalcote** [comment]
Awesome. @alonsolopezr! 🎈
