### ISSUE TITLE
[Community] Newcomer's tutorial: Golang and contributing to mesheryctl

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1495]
**Current Behavior**
@navendu-pottekkat recently gave an introduction and walkthrough on what `mesheryctl` is and how it fits on the Meshery project. It is on YouTube. https://www.youtube.com/watch?v=hh_kFLZx3G4

**Desired Behavior**
This tutorial should be added to the /community/newcomers table of recordings

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@jesuslerma you might want to take on this issue...

**Comment by jesuslerma** [comment]
@leecalcote  of course. Will try to do that during this week

**Comment by leecalcote** [comment]
@jesuslerma feel free to reassign if this is an item that you are actively working toward.

**Comment by navendu-pottekkat** [comment]
@leecalcote Should we also add the list of resources i.e the links to learn things like Kubernetes, Microservices Architecture etc in some place too?

**Comment by Ruth-ikegah** [comment]
@navendu-pottekkat that thread you made in the channel will be super great, but wherein the site will be best to add it, or the youtube video description?

**Comment by navendu-pottekkat** [comment]
@Ruth-ikegah Maybe in the newcomer docs in the community drive? It will be too messy for the website I think...

**Comment by Ruth-ikegah** [comment]
Definitely, and editing the Youtube description too
