### ISSUE TITLE
Install Prismjs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1497]
**Current Behavior**
Code snippets on the layer5.io site should be optionally styled with the Prismjs plugin.

**Desired Behavior**
- Configure with support for markup, css, bash, shell, javascript, golang
- Configure with "tomorrow-night" theme
- Configure with clipboard.js support

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Tanuj22** [comment]
@leecalcote prismjs is already present. The theme is different though, which can be changed

**Comment by leecalcote** [comment]
Oh, good! Is there an example use of this package that you can point out in our code base?

**Comment by Tanuj22** [comment]
When used in a .js file - https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/Meshery/Meshery-platforms/index.js#L57 (a language prop can also be passed) 
When used in mdx - https://github.com/layer5io/layer5/blob/layer5-ng/src/collections/blog/2020-05-21-getting-started-with-mesheryctl/index.mdx

**Comment by leecalcote** [comment]
Thank you, sir.

**Comment by leecalcote** [comment]
@Tanuj22 do we have the clipboard.js support enabled in Meshery-platform section?

**Comment by Tanuj22** [comment]
> @Tanuj22 do we have the clipboard.js support enabled in Meshery-platform section?

Yes
