### ISSUE TITLE
[Meshery] Getting Started: Missing logos under Patterns and Performance sections

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1507]
**Description**
Even thought images are defined and identified to be displayed, they are not being displayed under two of the sections on https://layer5ng.netlify.app/service-mesh-management/meshery/getting-started

**Screenshots**
<img width="1154" alt="Screen Shot 2021-02-08 at 8 22 06 AM" src="https://user-images.githubusercontent.com/7570704/107234230-0f4e0580-69e9-11eb-9d56-4e76d05bbc17.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@EmperorYP7 would you like to investigate?

**Comment by EmperorYP7** [comment]
Sure!
