### ISSUE TITLE
Implementation of Learn Service Mesh CTA Section above footer

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1509]
**Current Behavior**
There is currently no CTA on the bottom of /books page and as such, we have made a design/section for it
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=4028%3A62

**Desired Situation**
To create a section for the learn service mesh CTA at the bottom of the / book section
Below is how the section should look
![Learn Service Mesh CTA](https://user-images.githubusercontent.com/44683018/107271702-e4959880-6a4c-11eb-9154-cbdf1c88c544.png)

Below is the asset for the visual topology 
https://drive.google.com/file/d/1sPovcFq4NzF_Qd4y9a3K3D1zwNZMrnen/view?usp=sharing

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by saumyasrivastava08** [comment]
I would like to work on this issue.

**Comment by Tanuj22** [comment]
> I would like to work on this issue.

@saumyasrivastava08 please go ahead

**Comment by Nikhil-Ladha** [comment]
@saumyasrivastava08 any updates on this?
We are a bit short in time, so any update would be appreciated 🙂

**Comment by Tanuj22** [comment]
@saumyasrivastava08 since we are a bit short on time. I am taking this. Please feel free to take up any of the other open issues

**Comment by Nikhil-Ladha** [comment]
@Tanuj22 once you update the CTA, we can get this closed.
