### ISSUE TITLE
[Blog] Starting SMI Conformance Testing with Meshery

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1516]
**Description**
This blog post has a few issues to be fixed:

- broken link:
<img width="1005" alt="Screen Shot 2021-02-10 at 10 55 33 PM" src="https://user-images.githubusercontent.com/7570704/107603725-4db71080-6bf3-11eb-9a7d-ee4a5fea572e.png">

- need margin on left and bottom of SMI logo 
<img width="1022" alt="Screen Shot 2021-02-10 at 10 56 08 PM" src="https://user-images.githubusercontent.com/7570704/107603721-4b54b680-6bf3-11eb-9474-aeb96c0ad7e5.png">

- Remove bold font weight on green "Meshery" hyperlink.
<img width="501" alt="Screen Shot 2021-02-10 at 10 58 11 PM" src="https://user-images.githubusercontent.com/7570704/107603771-78a16480-6bf3-11eb-852b-d0b53852ed85.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@chinmaym07 do you mind taking this up?

**Comment by chinmaym07** [comment]
Nope 👍🏻
