### ISSUE TITLE
Refactoring Partner's Page

### ISSUE THREAD

**Issue by shubhank-saxena** [layer5io/layer5#1522]
As discussed in Website call by Lee, there are some features that are to be implemented and thus partner's page needs to be refactored - 

- Make alternating rows dynamic using modulus.
- Only set either the width or the height of the logos, so that images expand to fill the 256 x 256 (as much as they can depending on their shape).
- Ensure that all logos are in SVG format.
- Work toward a subsequent PR with the “learn more” expander.

**Comment by leecalcote** [comment]
@shubhank-saxena we await your works he with the most eager eyes. 😄

**Comment by chinmaym07** [comment]
Can I work on this issue ?

**Comment by leecalcote** [comment]
Reopening. This is good work. I need to deliver a bit of content here.
