### ISSUE TITLE
Colorize social buttons on hover

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#153]
Currently, the social buttons on the layer5.io site show an informative tooltip when hovering:

<img width="309" alt="Screen Shot 2019-08-29 at 2 37 36 PM" src="https://user-images.githubusercontent.com/7570704/63970757-8cdabb80-ca6a-11e9-9962-adfbe54471f8.png">

But, do not change in color when hovered over.  This issue is to track an enhancement of the user experience to have the social buttons colorize when hovered over (in addition to have a tooltip displayed). Here's a mockup example:

![Screen-Shot-2019-08-29-at-2 35 57-PM](https://user-images.githubusercontent.com/7570704/63971013-302bd080-ca6b-11e9-9f72-71bc66d0d993.png)

The color of each icon should remain as-is when the mouse is not over the button. Colors used for each button should be specific to the original logo (e.g. the red used in the youtube icon should match the red used in the official icon).

SVGs of the social buttons may be found here - https://github.com/layer5io/layer5/tree/master/assets/images/buttons

HTML that display the social buttons may be found here - https://github.com/layer5io/layer5/tree/master/_includes/partials

**Comment by Silvyre** [comment]
Hey there, I'd love to work on this as my first Hacktoberfest issue.

**Comment by ibokg** [comment]
Hi! Can I try doing it?

**Comment by Sweta271097** [comment]
Is the issue still open?

**Comment by leecalcote** [comment]
@Sweta271097 no, but we have lots of open issues in the Meshery project here - https://github.com/layer5io/meshery.  We would love to help you pick one up. 

@ibokg @Sweta271097, It would be great to have you join the community Slack, so that you might get better engaged - http://slack.layer5.io
