### ISSUE TITLE
[NG] Prompts not set on Meshery Getting Started page

### ISSUE THREAD

**Issue by EmperorYP7** [layer5io/layer5#1535]
**Description**
I found this while working on a issue in the [Meshery Getting Started](https://layer5ng.netlify.app/service-mesh-management/meshery/getting-started) page. Prompts shown at some of the tiles are set to "test" which is not ideal.

**Expected Behavior**
The prompt should correspond to the tile which is being focused. (clicked)

**Screenshots**
![Test](https://user-images.githubusercontent.com/62606998/107800180-76224480-6d84-11eb-90ce-9f51f1d3a6f4.gif)

**Enviroment:**
- Host OS: Darwin arm64 20.3.0
- Meshery Version: NA
- Kubernetes Version: NA
- Browser: Safari Version 14.0.3

---

[Optional] **To Reproduce**
1. Go to https://layer5ng.netlify.app/service-mesh-management/meshery/getting-started
1. Scroll down to "1 step install to managing service meshes"
1. Click on the tiles.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
Yeah, content needs to be added here? 
@leecalcote are you feeling this content or is there somewhere I can look it up?

**Comment by leecalcote** [comment]
I missed this question earlier... if you can pull instructions from docs.meshery.io, that would be helpful.

**Comment by Tanuj22** [comment]
Closing as data updated
