### ISSUE TITLE
Add Vulcand to Service Proxies

### ISSUE THREAD

**Issue by ziruihao** [layer5io/layer5#154]
I just found this from a blog https://www.mailgun.com/blog/how-and-why-we-adopted-service-mesh-with-vulcand-and-nginx on how Mailgun developed Vulcand in 2014. At first, it was an ingress load balancer. But then the developers realized they can extend it to internal traffic, and create a service mesh.

https://github.com/vulcand/vulcand/

**Comment by leecalcote** [comment]
Good highlight, @ziruihao. 

@thrawn01, @horkhe, @ikandars, @klizhentas, @agalitsyn, @alxrem, @jrudolph, will you consider adding Vulcand to the [service mesh landscape](https://layer5.io/landscape)? The [process](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for doing so is simply editing some yaml and sending a PR. Thanks!

**Comment by thrawn01** [comment]
Thanks for bringing attention to layer5. Didn't know this existed. I've created a PR https://github.com/layer5io/layer5/pull/161

@horkhe @klizhentas Not sure if mailgun has governance over vulcand or it's a completely open now. Thoughts?

**Comment by klizhentas** [comment]
@thrawn01 I declare you Vulcand's governor :D On a serious note it's mostly up to us (folks who care about vulcand) to see what makes sense, so far everything you've been doing makes sense to me, so go for it.

**Comment by leecalcote** [comment]
Layer5 landscape now include vulcand. Thank you, @ziruihao, @thrawn01, @klizhentas!
