### ISSUE TITLE
[Home] Hero: Create alternative hero: 5 icon

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1542]
**Current Behavior**
The home page has a single hero created. 

**Desired Behavior**
Ideally, a few versions of the hero section are available to rotate through. There is a hero design with a large "5" icon in the design mockups that would be ideal to have.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@EmperorYP7 is this an item you might pickup?

**Comment by EmperorYP7** [comment]
@leecalcote Sure! It'd be helpful if someone dropped in the exact design we're talking about here to avoid confusion.

**Comment by Nikhil-Ladha** [comment]
> @leecalcote Sure! It'd be helpful if someone dropped in the exact design we're talking about here to avoid confusion.

Here you go @EmperorYP7 ....the hero sections of the two designs https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=354%3A441

**Comment by leecalcote** [comment]
Deep-linking in Figma is bothersome. This url might get a little closer - 

https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=3359%3A0

<img width="907" alt="Screen Shot 2021-02-18 at 8 38 02 AM" src="https://user-images.githubusercontent.com/7570704/108372642-a45cb580-71c4-11eb-8d08-95946adb0847.png">

**Comment by EmperorYP7** [comment]
@leecalcote @Nikhil-Ladha oops! 
<img width="417" alt="Screenshot 2021-02-19 at 1 07 51 AM" src="https://user-images.githubusercontent.com/62606998/108411756-03670c80-724f-11eb-8b57-3fb04d37c5c1.png">
