### ISSUE TITLE
[Home] Hero: Create section randomizer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1543]
**Current Behavior**
Different versions of the hero section are available. The hero section is statically configured, though.

**Desired Behavior**
Ideally, the hero section is set to randomly load a design from a collection of designs.

This issue calls for implementation of a hero randomizer akin to the randomizer on the 404 error page.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by vineethvanga18** [comment]
@leecalcote We only have one hero section implemented right?

**Comment by leecalcote** [comment]
@vineethvanga18 yes, that's right. Here's an issue calling for another: https://github.com/layer5io/layer5/issues/1542

**Comment by leecalcote** [comment]
We will create other heros. A randomizer is needed.

**Comment by vineethvanga18** [comment]
@leecalcote sure. Will create one. Should it be random or linear?

**Comment by leecalcote** [comment]
Good question. Linear may make more sense

**Comment by vineethvanga18** [comment]
@leecalcote We need to make use of local storage for this to be linear. Is that okay?

**Comment by leecalcote** [comment]
Yes, we’re ok to use localstorage for this.
