### ISSUE TITLE
GitHub Issue Template update

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1544]
**Description**
The [Member Profile Update](https://github.com/layer5io/layer5/blob/master/.github/ISSUE_TEMPLATE/New%20Member%20Profile.md) github template in this repo uses the British spelling of "behaviour" in the first section's heading. 

**Expected Behavior**
Expected behavior is to spell behavior in the "correct" (_hmpf!_) format.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Minjiicho** [comment]
I was going to ask you if I could assign it, but it seems already been updated 😢 
You can close this issue now.

**Comment by Tanuj22** [comment]
@Minjiicho Thank you! Looks like linking the PR to the issue was missed. Please do check if any of the other issues are of interest to you.
