### ISSUE TITLE
[Community] Member Profiles: Set default filter as "Active Members"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1546]
**Current Behavior**
The community members page displays with the all **All Members** filter by default.

**Desired Situation**
The community members page displays with the all **Active Members** filter by default.

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/master">`master` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by leecalcote** [comment]
@EmperorYP7 heads-up

**Comment by EmperorYP7** [comment]
On it! 👍🏻
