### ISSUE TITLE
[News] Add Related News Section on Single News page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1555]
**Current Behavior**
The single blog page has a Related Posts section at the bottom of the page. The single news page does not.

**Desired Behavior**
A Related New section should be presented the bottom of the single News page.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@Harshita-Kanal is this something you might take on?

**Comment by Tanuj22** [comment]
@leecalcote how would we consider if a news is related to other? For blogs we considering common tags and category which we don't have for news

**Comment by leecalcote** [comment]
@Tanuj22 great question. We can either add new frontmatter variables (tags) to news articles or we can create a LatestNews instead of a RelatedNews.

**Comment by Harshita-Kanal** [comment]
So which approach should I go with, latestNews or relatednews ?

**Comment by leecalcote** [comment]
LatestNews, pretty please.

**Comment by leecalcote** [comment]
@Harshita-Kanal checking in... any luck?

**Comment by Harshita-Kanal** [comment]
Yeah almost done :+1:

**Comment by Tanuj22** [comment]
@Harshita-Kanal any updates here ?

**Comment by chinmaym07** [comment]
Hey @Harshita-Kanal !! 👋🏻 
Can you please provide an update here !!
If you have completed the required work for this issue ,then please do open a pr 🚀  🎆  .
If not, Can I go ahead & make a PR for this issue ?

**Comment by Tanuj22** [comment]
@chinmaym07 go ahead
