### ISSUE TITLE
[Meshery] Add "+" sign behind the count of users

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1557]
**Description**
Meshery has more users than the count listed on  the`/service-mesh-management/meshery` page

**Expected Behavior**
Akin to the number of performance tests run, a plus sign should be behind the user count.

**Screenshots**
<img width="772" alt="Screen Shot 2021-02-17 at 2 47 55 PM" src="https://user-images.githubusercontent.com/7570704/108266183-68c3dc00-712f-11eb-8012-bed431d4016a.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Nikhil-Ladha** [comment]
I am fixing this in my fonts PR
