### ISSUE TITLE
Member profile in /community/members for Yash Pandey

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1558]
**Current Behavior**
Yash Pandey currently doesn't have a community member profile/card

**Desired Situation**
Creation of community member profile/card
![Yash Pandey](https://user-images.githubusercontent.com/44683018/108275450-a5ff8c80-7176-11eb-85f9-6129ea9fec3f.png)

![Yash Pandey](https://user-images.githubusercontent.com/44683018/108279720-51abdb00-717d-11eb-9638-9587b86c3a1c.jpeg)

Here is the exported asset 
https://drive.google.com/file/d/1jo43k3xaB0jZCmaBTGcczRkaZOZ6D_CG/view
https://drive.google.com/file/d/167Vnea3TOHp7XCdnFikQnwB3X0zewU9I/view?usp=sharing
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
This image is needs updated.

**Comment by 96RadhikaJadhav** [comment]
@leecalcote  I want to work on the issue.

**Comment by 96RadhikaJadhav** [comment]
I will be needing some more info about Yash Pandey. Such as linked profile link, github profile link, twitter link, bio etc.

**Comment by leecalcote** [comment]
@Jashpatel1 will you kindly provide this info?

**Comment by Jashpatel1** [comment]
- GitHub:  EmperorYP7
- Twitter: pandeyyash04
- LinkedIn: emperoryp
- Link to profile picture: https://drive.google.com/file/d/1jo43k3xaB0jZCmaBTGcczRkaZOZ6D_CG/view
https://drive.google.com/file/d/167Vnea3TOHp7XCdnFikQnwB3X0zewU9I/view?usp=sharing

@EmperorYP7 Can you provide a short bio to feature on your member page.

**Comment by EmperorYP7** [comment]
> @EmperorYP7 Can you provide a short bio to feature on your member page.

Sure! Here it goes:

A passionate sophomore at Indian Institute of Information Technology, Ranchi pursuing Bachelors in Computer Science and Engineering trying to create an impact on open-source community by helping in making great softwares to empower people around the globe. I am interested to contribute and learn about the web and love to work on tools related to computer graphics.
