### ISSUE TITLE
[Meshery] Change single install step to to CodeBlock component

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1559]
**Desired Behavior**
Implement the code section on /service-mesh-management/meshery/getting-started with the copy-to-clipboard support using src/components/CodeBlock component.

**Screenshots / Mockups**
<img width="547" alt="Screen Shot 2021-02-17 at 5 06 49 PM" src="https://user-images.githubusercontent.com/7570704/108279774-beee4a80-7142-11eb-8c17-1c08368bb5ad.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Nikhil-Ladha** [comment]
Hey @Tanuj22, would you mind knocking out this simple item?

**Comment by Tanuj22** [comment]
I seemed to have missed this. WIll do it ASAP
