### ISSUE TITLE
[README] Add smp_spec twitter handle to list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1571]
**Current Behavior**
"Find us on Twitter: @layer5 and @mesheryio. Subscribe on Youtube" statement at the bottom of the README is missing the twitter.com/smp_spec handle.

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Vi1234sh12** [comment]
@leecalcote  Can I work on this?

**Comment by Nikhil-Ladha** [comment]
> @leecalcote Can I work on this?

Sure @Vi1234sh12 . Go ahead.
