### ISSUE TITLE
[Docs] Contributing instructions need updated for new site deployment

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1572]
**Current Behavior**
1. The new source and deployment target locations need updating in the contributor guide. See https://github.com/layer5io/layer5/blob/9e24d81e0e4883ab3413bc3cf79f2e639c198349/.github/workflows/gatsby.yml#L18-L19 for details.

2. The Chore/Task Issue template needs updated to remove `layer5-ng` reference.

**Desired Situation**
- No references to `layer5-ng` should remain.

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by supzi-del** [comment]
Hey, can you elaborate on this issue?

**Comment by leecalcote** [comment]
Hi @supzi-del Thanks for asking. Yes: 

1) Details of the GitHub Action/workflow should ideally be documented in the CONTRIBUTING.md, so that contributors know when to expect a build / build preview to show. // @rav121 
2) The GitHub Issue Templates and the CONTRIBUTING.md should make reference to `master` branch and not `layer5-ng` branch. I think @EmperorYP7 has taken care of the GH issue templates.

**Comment by UnkleTayo** [comment]
I'd love to take this up

**Comment by Nikhil-Ladha** [comment]
Sure, go ahead @UnkleTayo 👍🏼
