### ISSUE TITLE
[Landscape] Add GetNighthawk to the tools table

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1573]
**Current State:**
The service mesh landscape currently excludes listing of GetNighthawk.

**Desired State:**
The Tools tables should have an entry for GetNighthawk.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@vinayaksh42 @Grumpyyash @aneeshnema @rav121 @ramrodo, this issue is up for grabs.

**Comment by vinayaksh42** [comment]
The following field already exists in the tools table:
![chrome_sJCMj6v9Cb](https://user-images.githubusercontent.com/54861487/109268195-b7a8fa00-7830-11eb-8a5c-7242d82549be.png)

**Comment by leecalcote** [comment]
@vinayaksh42 let's get GetNighthawk represented more directly here.
