### ISSUE TITLE
[CI] Create or augment workflow for site deployment previews

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1578]
**Current Behavior**
Deployment previews are very helpful in saving time during PR reviews.

**Desired Behavior**
This should exclude use of Netlify. This should use GitHub Actions to create a new branch on an alternative "layer5-preview" repo, generate new builds of the site under a folder using the PR #, push the built site files, then update the originating PR when the preview files are pushed.

Example url path: https://layer5io.github.io/layer5-preview/280 (to preview build or PR #280)

When the PR merges or is closed, a workflow should clean up and remove the preview deployment.

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Nikhil-Ladha** [comment]
Took a slight different approach, but it's working now. Hence, closing the issue.

**Comment by leecalcote** [comment]
You bludgeoned this thing into submission.
