### ISSUE TITLE
[Related Posts] Slider arrow being cut off from view

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1585]
**Description**
Visit any of the [individual blog pages](https://layer5.io/blog/community/meet-the-maintainer-michael-gfeller) and you will find a Related Posts section at the bottom of the page.

**Expected Behavior**
Both of the slider arrows on either the left or right side should be completely visible to the visitor.

**Screenshots**
<img width="260" alt="Screen Shot 2021-02-20 at 7 41 02 AM" src="https://user-images.githubusercontent.com/7570704/108597868-cb47f280-7350-11eb-916a-b1d76b782f2b.png">
 
**Environment:**
- Browser: Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by chinmaym07** [comment]
@leecalcote sir can I work on this ?

**Comment by leecalcote** [comment]
Sounds real good. There will be a number more of these coming...

**Comment by leecalcote** [comment]
> @leecalcote sir can I work on this ?
> Sir I can see the slider arrow looks perfect but on lower size screens below 992px one has to refresh to enable slick dots & disable silder arrows .
> ![Peek 2021-02-20 21-55](https://user-images.githubusercontent.com/44670961/108602261-16045180-73c7-11eb-957b-313150de35ef.gif)

Oh, interesting....

**Comment by Nikhil-Ladha** [comment]
Yeah, the arrows are there only from 992 px and after that, it changes to dots. Now, since when the site loads on a device it will automatically get the size of the screen this issue will never occur. So, I think we can close this issue.

**Comment by leecalcote** [comment]
What do we about the issue that I'm seeing in the screenshot in this description, though?

**Comment by Nikhil-Ladha** [comment]
> What do we about the issue that I'm seeing in the screenshot in this description, though?

At which resolution?

**Comment by chinmaym07** [comment]
@leecalcote sir Can you please confirm whether this is a browser specific issue ?
As I have tried to test this on firefox as well as chrome . I didn't find this issue on either of them.

**Comment by Tanuj22** [comment]
This was a safari related issue if I remember correctly. @EmperorYP7 you have safari right? Can you take this up?

**Comment by chinmaym07** [comment]
I tried to install safari on ubuntu using playonlinux , Safari is clearly getting installed & running . But When I try to navigate to http:localhost:8000/ in safari .. then website is not rendering at all. Yes @EmperorYP7 If you could do this . It will be really helpful . Thankyou !!

**Comment by EmperorYP7** [comment]
> This was a safari related issue if I remember correctly. @EmperorYP7 you have safari right? Can you take this up?

Sure!

**Comment by chinmaym07** [comment]
This issue will be there Related Blogs on Single Blog & Latest News on single News page . @EmperorYP7 Do rectify both !!
