### ISSUE TITLE
[Community] Member Profile: Aneesh Neema

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#1592]
**Current Behaviour**

@aneeshnema has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @aneeshnema as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  aneeshnema 
- Twitter:  aneeshnema
- LinkedIn:  aneesh-nema
- Link to profile picture: https://avatars3.githubusercontent.com/u/31976598?s=460&u=d6bdd33fec1343f12c7dd5637a55c916ff78a844&v=4

@aneeshnema Could you please check and confirm this?

---

**Contributor Resources**

The layer5.io website, which uses GatsbyJS and GitHub Pages. Site content is found under the <a href="https://github.com/layer5io/layer5/tree/master">`master` branch</a>. See <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md">`layer5` contributing instructions</a>.

**Comment by aneeshnema** [comment]
@navendu-pottekkat all details are correct 😁

**Comment by chinmaym07** [comment]
Can I knock this ?

**Comment by aneeshnema** [comment]
@chinmaym07, here you go

An aspiring software developer with a passion for solving impactful problems. Undergraduate at IIT Indore.


@navendu-pottekkat it's "Nema"
