### ISSUE TITLE
Twitter: Image / page previews

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1594]
**Description**
Images from layer5.io pages (or at least the landscape page) are not showing when shared in a tweet.

Example - https://twitter.com/mesheryio/status/1363721452801781765?s=20

**Screenshots**
<img width="626" alt="Screen Shot 2021-02-21 at 11 54 23 PM" src="https://user-images.githubusercontent.com/7570704/108668227-6b606180-74a0-11eb-9e4b-8a5ad8ce01d3.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by UnkleTayo** [comment]
I'd like to take this up

**Comment by Tanuj22** [comment]
Fixed in #1674
