### ISSUE TITLE
[Events] Allow users to view details locally

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1595]
**Current Behavior**
All events have a single link, which is an external link.

**Desired Behavior**
Each event should allow users to view details of the event locally on layer5.io and optionally allow users to click to exit the layer5.io site. Allow users to click on the event and show the contents of the .mdx file?

Example:
This event has details in its .mdx file, but those details are not shown to the user (the user is not allowed to view details).

<img width="438" alt="Screen Shot 2021-02-22 at 12 28 48 AM" src="https://user-images.githubusercontent.com/7570704/108670985-6a7dfe80-74a5-11eb-9bb1-8037b53fa824.png">

---
**Contributor Resources**
The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
There’s little difference between events and workshops most of the time. It still makes sense that they are separately displayed, but it might make sense to reuse the same .mdx file (share between the collections). Like if one .mdx file in the workshops collection has a frontmatter variable type that is an array of values (“event”, “workshop”), then show it on both /events and on /workshops.

**Comment by adithyaakrishna** [comment]
Hey @Tanuj22 Can you assign me this?

**Comment by Tanuj22** [comment]
Fixed in #1814

**Comment by Lezette** [comment]
@adithyaakrishna what am I supposed to fix?
