### ISSUE TITLE
[Learn] Service Mesh Labs: Animate show/hide of lab details

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1596]
**Current Behavior**
The /learn/service-mesh-labs page has cards that expand when to show the visitor more details when the visitor clicks on the card.

This card is missing an animation for the opening action (the expanding / collapsing action), though. Without the animation, it’s something of a jarring experience for the visitor.

**Desired Behavior**
`/learn/service-mesh-labs` page would be a lot nicer if it behaved like the `/workshops` page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@kishore007k you might beat @vineethvanga18 to the punch here. 😉

**Comment by leecalcote** [comment]
@vineethvanga18 can you knock this one out?

**Comment by vineethvanga18** [comment]
@leecalcote sure, sir.
