### ISSUE TITLE
[Mailing List] Create long-form version of subscribe component

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1603]
**Current Behavior**
The current "[subscribe](https://github.com/layer5io/layer5/tree/master/src/sections/subscribe)" component has a single field for email. 

<img width="967" alt="Screen Shot 2021-02-24 at 5 29 43 AM" src="https://user-images.githubusercontent.com/7570704/108994524-83cbaa00-7661-11eb-9f72-0070ded9fb41.png">

**Desired Behavior**
The current, short-form serves as a simple Call to Action for the visitor and should remain as-is.

Ideally, a long-form version of this component that includes two additional fields (first name and last name) can be made available at https://layer5.io/subscribe so that the visitor's first and last name may also, optionally be captured.

---
**Contributor Resources**
The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Nikhil-Ladha** [comment]
Actually, there is a long-form subscribe component...but we are not using it anywhere. Previously, it was used on the home page but not it has been replaced by the current implementation.
Link to the component: https://github.com/layer5io/layer5/tree/master/src/components/ContactCard

P.S: Incorrect name has been used 😝

**Comment by leecalcote** [comment]
Thank you 😄
