### ISSUE TITLE
[Proudly Maintaining] Text escaping on Image Hub card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1604]
**Description**
On the home page, in the [proud maintainers section](https://github.com/layer5io/layer5/tree/master/src/sections/Home/Proud-maintainers), the label "Image Hub" is escaping its card.

**Expected Behavior**
Labels should be contained to the card. They will need to shrink or disappear as the screen width is reduced.

**Screenshots**
<img width="648" alt="Screen Shot 2021-02-24 at 7 01 22 AM" src="https://user-images.githubusercontent.com/7570704/109004563-84b70880-766e-11eb-8876-0815f483917f.png">

**Environment:**
- Browser: Safari

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Harshita-Kanal** [comment]
I am unable to reproduce the issue, it is looking fine 🙂
