### ISSUE TITLE
[Blog] Single Post View: Hyperlink blog categories

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1613]
**Current Behavior**
An individual blog post can be assigned to a single category. Readers of the post can see what category is assigned, but cannot click on that category to see a filtered list of other blog posts of that same category.
<img width="186" alt="Screen Shot 2021-02-25 at 8 23 24 PM" src="https://user-images.githubusercontent.com/7570704/109246290-8fc18400-77a7-11eb-94d4-9d2ea4cd45dd.png">

**Desired Behavior**
Provide a hyperlinked blog post category, leading to a filtered list of blogs belonging to the same category.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by UnkleTayo** [comment]
I would love to take this up

**Comment by leecalcote** [comment]
Excellent, @UnkleTayo 🙂
