### ISSUE TITLE
[Brand] Add smooth navigation transition to sidebar menu

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1614]
**Current Behavior**
On the https://layer5.io/brand page, when a user clicks on the links in the sidebar navigator (see screenshot), the transition to the respective section is not smooth.

<img width="646" alt="Screen Shot 2021-02-25 at 9 20 09 PM" src="https://user-images.githubusercontent.com/7570704/109250519-71f81d00-77af-11eb-912b-7fe99f022665.png">

**Desired Behavior**
Upon click, the page should smoothly scroll (transition) to the desired section and not do so abruptly.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by chinmaym07** [comment]
Can I knock this ?

**Comment by leecalcote** [comment]
Sounds great, @chinmaym07. Looking over [these others](https://github.com/issues?q=is%3Aopen+is%3Aissue+assignee%3Achinmaym07+archived%3Afalse+org%3Alayer5io), we might want to close out the first of these regarding the presentations on Meshery. I'm not sure that we want to carry that one through at the moment. We can always reopen.
