### ISSUE TITLE
[Projects] Add call to join community; remove contact us button

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1615]
**Current Behavior**
On the https://layer5.io/projects page, a contact us button is shown under the projects grid.

<img width="1197" alt="Screen Shot 2021-02-25 at 9 17 34 PM" src="https://user-images.githubusercontent.com/7570704/109250340-1e85cf00-77af-11eb-912c-a92803557d81.png">

**Desired Behavior**
A call to action to contribute to the projects and join the community should be shown instead. A horizontal version of the `CommunityCallCard` component should be used.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Anita-ihuman** [comment]
The Figma link shows this.
![Screenshot 2021-02-26 at 08 23 29](https://user-images.githubusercontent.com/62384659/109268941-160fb180-780c-11eb-9317-7842ee1ee30a.png)

**Comment by Anita-ihuman** [comment]
I will like to fix this issue

**Comment by leecalcote** [comment]
invitation to Figma project sent...

**Comment by Abiola-Farounbi** [comment]
Hi, @leecalcote, 
the call to join the community, does it lead to the slack channel?
