### ISSUE TITLE
[Blog] Standardize blog post sign-off

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1616]
**Current Behavior**
Each blog post on https://layer5.io/blog ends with a sign-off from the post author, like so:

<img width="776" alt="Screen Shot 2021-02-25 at 9 38 33 PM" src="https://user-images.githubusercontent.com/7570704/109251927-f77ccc80-77b1-11eb-8889-037b5cea7a03.png">

Anyone authoring a post also has a community member profile.

**Desired Behavior**

Blog post sign-offs should be standardized and done through a common component built into the blog template. 

**Implementation**

Augment existing single blog post view with Author sign-off in this format: 
```
\- <Link to="/community/member/{author}">{author}</Link>
```
The first reference to author will need to be slugified.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by chinmaym07** [comment]
@leecalcote sir as a separate component is required . One has to remove 
```\- <Link to="/community/member/{author}">{author}</Link>``` from every blog post & add that new component in blog-single component. 
Can I work on this ?

**Comment by leecalcote** [comment]
@chinmaym07 that sounds right. Yes, that would be great. 👍

**Comment by leecalcote** [comment]
Good work, gents.
