### ISSUE TITLE
Add link to Meshery docs site

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#162]
*Issue*: 
The Meshery project page (https://layer5.io/meshery) is missing a link to its docs site at https://meshery.layer5.io/docs.

*Requested Fix*:
Update https://github.com/layer5io/layer5/blob/master/_includes/meshery.html to include a callout and link to the project's doc site in area highlighted in screenshot.

*Screenshot*
<img width="892" alt="Screen Shot 2019-10-09 at 7 18 55 PM" src="https://user-images.githubusercontent.com/7570704/66529659-da1a6600-eac9-11e9-88c3-e171f8b982cf.png">

**Comment by AninditaBasu** [comment]
May I take this up?

**Comment by leecalcote** [comment]
Fixed by #208
