### ISSUE TITLE
[Community] Member Profile: Shubhank Saxena

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1622]
**Current Behavior**

@shubhank-saxena  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @shubhank-saxena  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: shubhank-saxena
- Twitter: 19_saxena
- LinkedIn: shubhank-saxena
- Link to profile picture: https://ca.slack-edge.com/TDL4L01AR-U01H9TDUR4P-499a41baa4a2-512

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Jashpatel1** [comment]
@shubhank-saxena Will you please provide a small bio that could feature on your individual member page?

**Comment by shubhank-saxena** [comment]
> @shubhank-saxena Will you please provide a small bio that could feature on your individual member page?

I am an electronics student who is always looking for opportunities to learn something new and grow. I have a goal of helping differentially abled people with my tech and innovation. I have experience with OSS contributions and wearable hardware devices.

**Comment by Anita-ihuman** [comment]
I would like to take this issue
