### ISSUE TITLE
[Projects] Addition of GetNightHawk to the Projects page

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/layer5#1624]
**Current Behavior**

Getnighthawk missing from https://layer5.io/projects

**Desired Behavior**

Addition of GetnightHawk to https://layer5.io/projects

@austinogiza @leecalcote this requires a new layout design in order to incorporate it.

---
[Optional] **Screenshots / Mockups**

[Optional] **Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
FYI @bartkalanski

**Comment by austinogiza** [comment]
Will do something

**Comment by austinogiza** [comment]
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=4568%3A97

@vinayaksh42 @leecalcote  kindly check this out 
<img width="1075" alt="projects" src="https://user-images.githubusercontent.com/44683018/109364893-181b5400-7890-11eb-80de-05dcbe8fd7f4.png">
