### ISSUE TITLE
[Community] Changes to be addressed

### ISSUE THREAD

**Issue by EmperorYP7** [layer5io/layer5#1628]
**List of changes to be made to [Community Page](https://layer5.io/community)**

- "Join the community" column is 800 px wide. The column should be 1000px width/max-width
- The whitespacing between the open source title and the largest collection section is small, increase the margin
- "Jump in.  The community is warm!" to be placed before "Our Community Members" and the section's height should be increased.
- "An onboarding and mentoring program" to be placed before "Layer5 MeshMates" title in Meshmates section.
- **Screenshots attached for each change respectively**

---
**Additional context**

<img width="1440" alt="Screenshot 2021-02-26 at 2 15 19 PM" src="https://user-images.githubusercontent.com/62606998/109277512-723ef980-783d-11eb-9ffa-098020f74775.png">

<img width="1165" alt="Screenshot 2021-02-26 at 2 07 44 PM" src="https://user-images.githubusercontent.com/62606998/109277003-bd0c4180-783c-11eb-8c44-fe427c55050b.png">

<img width="865" alt="Screenshot 2021-02-26 at 2 50 49 PM" src="https://user-images.githubusercontent.com/62606998/109281431-4d00ba00-7842-11eb-8f52-de576a005f54.png">

<img width="779" alt="Screenshot 2021-02-26 at 2 54 13 PM" src="https://user-images.githubusercontent.com/62606998/109281610-89ccb100-7842-11eb-9b45-3572d1bae3cd.png">

---
**Contributor Resources**

[Design for the Community Page](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=1231%3A1819)

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Grumpyyash** [comment]
Should I try these?

**Comment by EmperorYP7** [comment]
@Grumpyyash Sure! 😄
