### ISSUE TITLE
Expose total performance test runs on Meshery page

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/layer5#164]
**Enhancement Description**
Each time someone runs a performance test in Meshery, the total count of performance tests is incremented. This enhancement describes the need to expose that number to visitors.

The total performance test runs will be exposed at the following endpoint:
```
https://meshery.layer5.io/result/total
```

The result will be a json:
```
{"total_runs":1}
```

**Implementation**
1. This can be accomplished by using an ajax call to the above mentioned endpoint.
1. Style the total results number using CSS; should be prominently displayed as a card with large number indicating the total number of performance tests run using Meshery.

**Comment by girishranganathan** [comment]
@leecalcote, please feel to add more info as needed

**Comment by leecalcote** [comment]
@madhabpaul @Nikhil-Ladha @subhamkrai would one of you like to grab this one?

**Comment by leecalcote** [comment]
@gunjanmimo Here's a mockup for reference - 
![total performance test results mockup](https://user-images.githubusercontent.com/7570704/65426691-54629f00-ddd6-11e9-9e53-0a08cd4510b7.png)

Eventually, this message will be clickable. It will by hyperlinked to a page that presents an analysis of the test results.

**Comment by leecalcote** [comment]
@gunjanmimo a working example:

```
<span id="testresults"></span>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $.get("https://meshery.layer5.io/result/total", function(data, status){
    var testresults = JSON.parse(data);
    document.getElementById("testresults").innerHTML = testresults.total_runs;
  });
});
</script>
```
