### ISSUE TITLE
[Books] Use full cover image for The Enterprise Path to Service Mesh Architectures book

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1658]
**Description**
This page, https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures, should have an image of the full book cover. The full book cover image is available here - https://raw.githubusercontent.com/layer5io/layer5/master/src/collections/service-mesh-books/the-enterprise-path-to-service-mesh-architectures/The-Enterprise-Path-to-Service-Mesh-Architectures.png

**Screenshots**
<img width="458" alt="Screen Shot 2021-03-02 at 5 04 06 PM" src="https://user-images.githubusercontent.com/7570704/109727218-8b1b1800-7b79-11eb-8651-a51d4db127f4.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by chinmaym07** [comment]
knock knock 😆 . Want to knock this ?
