### ISSUE TITLE
Community calender links leads to the wrong links

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/layer5#1663]
**Description**

at https://layer5.io/community/calendar the section labeled as `layer5 meetings`  has a few misleading links

**Expected Behavior**

The meeting minutes link of CNCF SMI Community Meeting and CNCF SIG Network Meeting leads to the meeting minutes google Doc of Layer5 Community Meeting

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
- CNCF SIG Network Meeting Minutes link - https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#
- SMI Community Meeting Minutes link - https://docs.google.com/document/d/1NTBaJf6LhUBlF8_lfvBBt_MbyPvT-6CZNg6Ckpm_yCo/edit

**Comment by Abiola-Farounbi** [comment]
Hi @vinayaksh42 
I would like to be assigned this issue

**Comment by vinayaksh42** [comment]
@Abiola-Farounbi sure, I am assigning you for this issue.
