### ISSUE TITLE
[News] HashiCorp partnership page has broken link to image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1667]
**Description**
This page has a broken image - https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership

<img width="1263" alt="Screen Shot 2021-03-04 at 9 28 00 PM" src="https://user-images.githubusercontent.com/7570704/110063341-995f6480-7d30-11eb-99e5-ca721dd15a27.png">

**Expected Behavior**
Image should be displayed on page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by shivaylamba** [comment]
Can I take this up?  @leecalcote

**Comment by leecalcote** [comment]
Thank you, @shivaylamba
