### ISSUE TITLE
Add Kuma to Service Mesh

### ISSUE THREAD

**Issue by ziruihao** [layer5io/layer5#167]
[https://kuma.io/docs/0.1.0/](Kuma) was just announced today by Kong. Universal service mehs built on top of Envoy that spans containers and VMs.

@leecalcote I pinged you via LinkedIn about other service meshes & connecting. Let me know if you got those messages.

**Comment by leecalcote** [comment]
I hope I have the right @wayofthepie. Please jump in here, if interested. Your input is most welcome.

**Comment by ashiscs** [comment]
I guess this issue needs to be closed now

**Comment by leecalcote** [comment]
Kuma is now incorporated into the landscape.
