### ISSUE TITLE
[Community] Hero section too small

### ISSUE THREAD

**Issue by EmperorYP7** [layer5io/layer5#1680]
**Description**
Hero section needs to be a bit taller according to the design. (800 px tall for 1440p wide screens)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Anita-ihuman** [comment]
Hello @EmperorYP7  you could drop a link to the Hero section on the webpage or link to the codebase here.  I would like to handle this issue

**Comment by EmperorYP7** [comment]
@Anita-ihuman here's the webpage: https://layer5.io/community

here's the visual:
<img width="1440" alt="Screenshot 2021-03-26 at 10 12 29 PM" src="https://user-images.githubusercontent.com/62606998/112665280-e4c4e880-8e80-11eb-9f3e-71fee438c9d4.png">

and here's a relevant file/folder:  https://github.com/layer5io/layer5/blob/master/src/sections/Community/index.js
https://github.com/layer5io/layer5/blob/master/src/sections/Community

**Comment by Anita-ihuman** [comment]
Thank you
