### ISSUE TITLE
[Community] Member Profile: Soham Sonawane

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/layer5#1687]
**Current Behavior**

@killbotXD has been a consistent contributor and community member.
**Desired Situation**
Let's recognize @killbotXD as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @killbotXD 
- Twitter: @killbot_XD
- LinkedIn: soham-sonawane-66b606178
- Link to profile picture: [link](https://drive.google.com/uc?export=view&id=1kV-nlPMm9yB3P9LOL6obw35kAPurEZLI)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by 96RadhikaJadhav** [comment]
@dhruv0000 Can I work on it?

**Comment by leecalcote** [comment]
Yes, that’d be great, @96RadhikaJadhav

**Comment by Tanuj22** [comment]
@killbotXD can you provide a small bio and your location.

**Comment by killbotXD** [comment]
> @killbotXD can you provide a small bio and your location.

Small bio - An Otaku who is also a developer ;) , loves to design beautiful stuff, is also an awesome photographer and can debug 99.9% of the bugs out there.  
Location - Pune, India

**Comment by leecalcote** [comment]
Whoo-hoo, @killbotXD! 🎈
