### ISSUE TITLE
[Community] Member Profile: Abiola Farounbi

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#1691]
**Current Behavior**

@Abiola-Farounbi  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Abiola-Farounbi  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Abiola-Farounbi
- Twitter: @abiolaEsther_
- LinkedIn: https://www.linkedin.com/in/abiola-farounbi-94ba571a0/
- Link to profile picture: https://rdre.me/abiolaFarounbi_profile_image

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by chinmaym07** [comment]
Can I do this  ? @Abiola-Farounbi Can you please provide a short bio & a location for your profile .

**Comment by Ruth-ikegah** [comment]
Hi, @chinmaym07 here you go!

Bio: I am a Front-End Developer based in Lagos, Nigeria. I'm passionate about creating user-friendly, aesthetic, and web-accessible websites, I write technical content and articles in my Blog.
I also contribute to open-source projects and volunteer in different programs available. I am also a Microsoft Student Learn Ambassador. In my Funtime, I engage in editing, designing photos for fun, watching movies, and giving reviews.

Location: Lagos, Nigeria

**Comment by Abiola-Farounbi** [comment]
Bio: I am a Front-End Developer based in Lagos, Nigeria. I'm passionate about creating user-friendly, aesthetic, and web-accessible websites, I write technical articles in my [Blog](https://abiolaesther.me/writing.html).
I contribute to open-source projects and volunteer in different programs, I am also a Microsoft Student Learn Ambassador. In my Funtime, I engage in editing, designing photos for fun, watching movies, and giving reviews.

Location: Lagos, Nigeria

**Comment by Abiola-Farounbi** [comment]
Hi @chinmaym07 ,

I made a few changes to the bio.
