### ISSUE TITLE
Upgrade to Gatsby v3

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1699]
**Current Behavior**
layer5.io runs on Gatsby v2. v3 has [helpful improvements](https://www.gatsbyjs.com/blog/gatsby-v3/), notably around the handling of images.

**Desired Situation**
layer5.io is running on Gatsby v3

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by adithyaakrishna** [comment]
@leecalcote Is this issue open? 👀

**Comment by leecalcote** [comment]
Yes, indeed. This is a good one to undertake. Someone needs to attempt to upgrade, show the site functioning as expected, and let a few of the maintainers poke around it to test. It’d be great for you to carry this forward.

**Comment by adithyaakrishna** [comment]
Hey @leecalcote  I have successfully upgraded it to v3 and most of its dependent packages to their latest versions 

There were some dependency issues which have been solved and the logs are below,
[Layer5-NPM-Logs.zip](https://github.com/layer5io/layer5/files/6267210/Layer5-NPM-Logs.zip)

To see the set of commands run when I worked upon this,
[Layer-Cprompt-Logs.txt](https://github.com/layer5io/layer5/files/6267223/Layer-Cprompt-Logs.txt)

After all these, the site is up and running 🎉
![image](https://user-images.githubusercontent.com/23498248/113771427-f9d32e80-9740-11eb-8761-873d281dedb9.png)

**Comment by leecalcote** [comment]
Great progress. Would you like to open a PR with these changes so that the build system might creat a preview and others can review?
