### ISSUE TITLE
[Community] Member Profile: Aadhitya Amarendiran

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#1702]
**Current Behavior**

@alphaX86 has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @alphaX86 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  alphaX86
- Twitter:  KryoX64
- LinkedIn:  alphaX86
- Link to profile picture: https://drive.google.com/file/d/1NpkDcvdSzRQPSafk4_z9vjXZs6pkjLBQ/view?usp=sharing

@alphaX86 could you please review the details provided here and also share a brief profile summary to include?

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by alphaX86** [comment]
@navendu-pottekkat is it ok to use my username of LinkedIn alone? Or is link needed?

**Comment by alphaX86** [comment]
And yeah, here's my description:
"I'm a 19-year-old student who loves to explore tech and tinker products. I joined Layer5 since Jan 2021 and contributed to Meshery in documentation field. I'm now currently learning Go and so yeah, hoping to contribute core type too!"

And would I get added to GitHub org after this? Just asking as a doubt

**Comment by navendu-pottekkat** [comment]
> @navendu-pottekkat is it ok to use my username of LinkedIn alone? Or is link needed?

Yes, it would be linked in your profile.

**Comment by alphaX86** [comment]
> **Current Behavior**
> 
> @alphaX86 has been a consistent contributor and community member.
> 
> **Desired Situation**
> 
> Let's recognize @alphaX86 as a contributor and community member by creating a profile on https://layer5.io/community/members.
> 
> * GitHub:  alphaX86
> * Twitter:  KryoX64
> * LinkedIn:  alphaX86
> * Link to profile picture: https://drive.google.com/file/d/1NpkDcvdSzRQPSafk4_z9vjXZs6pkjLBQ/view?usp=sharing
> 
> @alphaX86 could you please review the details provided here and also share a brief profile summary to include?
> 
> **Contributor Resources**
> 
> The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> 
> * See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> * See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

LGTM on the details! 👍 No issues!

**Comment by chinmaym07** [comment]
Can I do this ?

**Comment by leecalcote** [comment]
Thank you, @chinmaym07
