### ISSUE TITLE
[Community] Member Profile: Yash Vardhan

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1704]
**Current Behavior**

@Grumpyyash has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Grumpyyash  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Grumpyyash
- Twitter: 
- LinkedIn: yash-vardhan-688952188
- Link to profile picture:

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Jashpatel1** [comment]
@Grumpyyash Can you please provide a link to your profile picture and a short description that can feature on your individual member page?

**Comment by Grumpyyash** [comment]
Thank you so much for this @Jashpatel1 sir! It is really encouraging for me!

Link to the profile picture:  https://drive.google.com/file/d/1wkpIPkjEbJyxBj3ayl_nkG00DRlXEgSd/view?usp=sharing

Twitter-handle: Yash_dn
Short Bio: 'Undergraduate at IIT Dhanbad (India). A Developer, Programmer and a Keen Learner'

**Comment by buquio** [comment]
I'm interested in taking this issue

**Comment by Ruth-ikegah** [comment]
Nice! you have been assigned now @buquio

**Comment by Tanuj22** [comment]
@buquio any updates here?

**Comment by buquio** [comment]
@Tanuj22 I'm working on it.

**Comment by leecalcote** [comment]
Thank you, @buquio
