### ISSUE TITLE
[Meshery] Use live performance test count

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1705]
**Current Behavior**
The Meshery project page (https://layer5.io/service-mesh-management/meshery) counts up to a static number (2,000+).

**Desired Behavior**
Use the public endpoint (https://meshery.layer5.io/result/total) that has a real-time test result count instead.

See an example of its use here - https://meshery.io

The animated count should still occur, but count to the actual number instead of a hardcoded number.

 **Screenshots / Mockups**
<img width="381" alt="Screen Shot 2021-03-16 at 12 18 23 PM" src="https://user-images.githubusercontent.com/7570704/111352112-dccfa200-8651-11eb-8139-716b2cea305e.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by chinmaym07** [comment]
Can I do this ?
