### ISSUE TITLE
[Career] Changing location of Layer5 in the Job Description

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1707]
**Current Behavior**
The current location placement in layer5 careers is at the bottom of all the job description.

https://layer5.io/careers/ui-visual-designer/

![JD](https://user-images.githubusercontent.com/44683018/111488702-c6047a80-8739-11eb-8768-0c33056222dc.PNG)

**Desired Situation**
Moving the location to the top of all the job description we currently have in Layer5 for quick information

![JD1](https://user-images.githubusercontent.com/44683018/111488895-f5b38280-8739-11eb-8bcb-3db59e854e12.PNG)

**Comment by lumenCodes** [comment]
Hi, @austinogiza let me give this a shot.

**Comment by Ruth-ikegah** [comment]
sure @lumenCodes! Assigned you now!

**Comment by adithyaakrishna** [comment]
@Ruth-ikegah Is this issue still being worked on? If not, I would really love to work on it 😶

**Comment by lumenCodes** [comment]
@adithyaakrishna Please do. I can't meet up with it again.

**Comment by adithyaakrishna** [comment]
@austinogiza Had a doubt, there is already a location option in the page, should I remove it across all pages and then change it to the one mentioned below?

![image](https://user-images.githubusercontent.com/23498248/113702266-ec915200-96f6-11eb-9c80-61af50928e43.png)

![image](https://user-images.githubusercontent.com/23498248/113702296-f7e47d80-96f6-11eb-9f96-468a3a7ad739.png)

**Comment by austinogiza** [comment]
@adithyaakrishna let me provide more context. We want to remove from the bottom of all the openings and put it at the top of all the openings. Basically we are just switching/swapping the positions on all

**Comment by adithyaakrishna** [comment]
Okay, got it but, there exists another Location option what to do about that?

**Comment by austinogiza** [comment]
@adithyaakrishna  let's use a map icon instead of location for the new one, what do you think?

**Comment by adithyaakrishna** [comment]
Yeah, that would be great. Like the Pointer kind of one right?
![image](https://user-images.githubusercontent.com/23498248/113704694-1c8e2480-96fa-11eb-9bf8-87518bfb434b.png)

**Comment by leecalcote** [comment]
Gents, we needed this completed quickly and so I went ahead and knocked this out earlier. I neglected to circle back to close it out. We’re ok to close this issue. Thank you, all, for your help.
