### ISSUE TITLE
[FAQs] Breakdown FAQs into sections

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1708]
**Current Behavior**
The FAQs component is capable of displaying only specific topics (a topic passed in as a property). The FAQ component is used on different pages with different topics listed. However, this page has ALL of the FAQs included - https://layer5.io/company/faq.

<img width="1289" alt="Screen Shot 2021-03-17 at 11 41 16 AM" src="https://user-images.githubusercontent.com/7570704/111504665-e4587f00-8715-11eb-8c2c-f2bfe9856d4b.png">

**Desired Behavior**
Ideally, https://layer5.io/company/faq breaks the questions into different sections by category. See mockup.

Topics should not be statically configured on this page, the number of sections shown is dynamically determined from datafile / GraphQL queries.

 **Screenshots / Mockups**
![Screen Shot 2021-03-17 at 11 41 16 AM](https://user-images.githubusercontent.com/7570704/111505670-de16d280-8716-11eb-975c-f707b9048447.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@Harshita-Kanal would you like to implement this?

**Comment by Harshita-Kanal** [comment]
Yes sure 👍

**Comment by leecalcote** [comment]
Awesome. :)

**Comment by leecalcote** [comment]
Hi @Harshita-Kanal, do you anticipate being able to spend time on this item this weekend?

**Comment by Harshita-Kanal** [comment]
Yeah so sorry for the delay would complete as soon as possible 👍

**Comment by leecalcote** [comment]
OK, sounds great.

**Comment by Tanuj22** [comment]
@Harshita-Kanal any updates here?
