### ISSUE TITLE
Add AppSwitch to the Service Mesh Landscape

### ISSUE THREAD

**Issue by yogi4** [layer5io/layer5#171]
Hi @subhraveti will you consider adding(via PR) a listing for AppSwitch to the  [service mesh landscape](https://layer5.io/landscape)? We'd love to have an accurate listing of AppSwitch in Landscape. 

[Contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) - an update to  the [meshes.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/meshes.yml) and [non-functional.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/non-functional.yml) file would do the trick.

Thanks!

**Comment by ashiscs** [comment]
updated meshes.yml
https://github.com/layer5io/layer5/pull/185

**Comment by ashiscs** [comment]
@yogi4 https://github.com/layer5io/layer5/pull/185
Sir can you review this description?

**Comment by leecalcote** [comment]
Hi @subhraveti, does it make sense to list App Switch?

**Comment by subhraveti** [comment]
@leecalcote Thanks for resurfacing this.  Yes, please go ahead with it.  The description looks good.

**Comment by ashiscs** [comment]
@leecalcote sir, needs your attention here

**Comment by leecalcote** [comment]
AppSwitch added. Thank you, @subhraveti, @yogi4, @ashiscs!
