### ISSUE TITLE
[Discuss] Footer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1715]
_See [Epic] Discourse-based Discussion Forum #1394_

#### Description
The discuss.layer5.io site needs a footer. Ideally, this footer is identical to layer5.io's footer.

#### Implementation
See the **[Design Specification](https://docs.google.com/document/d/1MDdIZGr8cw_iyZD1H4G7k8AbcFJ79_4UhbKgGltfa7U/edit)**

#### Mockups
- **[discuss designs](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4850%3A10)**

Desktop

![footer](https://user-images.githubusercontent.com/7570704/112028017-c0c27980-8b05-11eb-96d6-5c9a11e02a49.png)

Mobile

![mobile footer](https://user-images.githubusercontent.com/7570704/112028005-bdc78900-8b05-11eb-8718-9b0c32d4f12b.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Hi @Grumpyyash, were you able to get logged in and start to customize?

**Comment by Grumpyyash** [comment]
Yes @leecalcote, I was able to log in and will start customizing

**Comment by adithyaakrishna** [comment]
@Grumpyyash Any Update on this? 😶

**Comment by rijusougata13** [comment]
anyone working on this or can i take this one?

**Comment by adithyaakrishna** [comment]
@rijusougata13 We are waiting for an update from @Grumpyyash , if he isn't working on this then you can take this up :)

**Comment by Grumpyyash** [comment]
> @Grumpyyash Any Update on this? 😶

Myself and @Jashpatel1 sir are working on this, I think it's completed for desktop view. If you want you can start working on the mobile view of the same. @Jashpatel1 sir?

**Comment by leecalcote** [comment]
@Grumpyyash good deal. Two items to overcome:

- use of font (should be Qanelas Soft)
- font weight should be lighter for the list items. 

We’ll want for the user not to be able to tell the difference between the two sides, if we can.

**Comment by rijusougata13** [comment]
doesn't this desktop view also optimized (chage its shape like in picture) for mobile view like using grid or flexbox.?

**Comment by adithyaakrishna** [comment]
> > @Grumpyyash Any Update on this? 😶
> 
> Myself and @Jashpatel1 sir are working on this, I think it's completed for desktop view. If you want you can start working on the mobile view of the same. @Jashpatel1 sir?

@rijusougata13 If @Jashpatel1 and @Grumpyyash agrees, Ig you can start working on the mobile view of the same, what would you say?

**Comment by Jashpatel1** [comment]
> > > @Grumpyyash Any Update on this? no_mouth
> > 
> > 
> > Myself and @Jashpatel1 sir are working on this, I think it's completed for desktop view. If you want you can start working on the mobile view of the same. @Jashpatel1 sir?
> 
> @rijusougata13 If @Jashpatel1 and @Grumpyyash agrees, Ig you can start working on the mobile view of the same, what would you say?

Yaa sure

**Comment by Grumpyyash** [comment]
> @Grumpyyash good deal. Two items to overcome:
> 
> * use of font (should be Qanelas Soft)
> * font weight should be lighter for the list items.
> 
> We’ll want for the user not to be able to tell the difference between the two sides, if we can.

Yes, I will do that @leecalcote sir!

**Comment by rijusougata13** [comment]
are you guys creating separate component for footer for mobile view and desktop view? like we can simply use flex to make the same code compatible for mobile view and desktop view

**Comment by leecalcote** [comment]
@Jashpatel1 we might want to close this issue given Friday's soft launch of the site. Here is a bug issue tracking the need for responsiveness - https://github.com/layer5io/layer5/issues/1894. We probably need another issue to track the missing Qanelas Soft font.
