### ISSUE TITLE
[discuss] Nav Bar

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1716]
_See [Epic] Discourse-based Discussion Forum #1394_

#### Description
The discuss.layer5.io site needs a nav bar. Ideally, this nav bar is identical to layer5.io's nav bar, but does not include the Mega Menu. Onhover (active state) styles should be the same on hyperlinks.

#### Implementation
See the **[Design Specification](https://docs.google.com/document/d/1MDdIZGr8cw_iyZD1H4G7k8AbcFJ79_4UhbKgGltfa7U/edit)**

#### Mockups
- **[discuss designs](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4850%3A10)**

Desktop

![Group 4](https://user-images.githubusercontent.com/7570704/112027791-8a84fa00-8b05-11eb-81fa-64ccd3685b78.png)

Mobile

![Group 4](https://user-images.githubusercontent.com/7570704/112027907-a7b9c880-8b05-11eb-9ab0-43d43a2ef423.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@Jashpatel1 Is this you?

**Comment by leecalcote** [comment]
@Jashpatel1 are you taking this one?

**Comment by Jashpatel1** [comment]
> @Jashpatel1 are you taking this one?

Yes

**Comment by blossom-babs** [comment]
Can I work on this?

**Comment by rijusougata13** [comment]
hey anyone working on this or can i take this issue?

**Comment by leecalcote** [comment]
Hi @blossom-babs, @rijusougata13, Thank you for asking. This one has been implemented already by @Jashpatel1. 

I believe all that’s left on the discuss.layer5.io initiative is configuration of plugins, decisions on topic categories, and a production deployment.

**Comment by leecalcote** [comment]
@Jashpatel1, all clear to close this one when ready.

**Comment by Nikhil-Ladha** [comment]
Are we good to close this now @leecalcote @Jashpatel1 ?

**Comment by leecalcote** [comment]
We have a couple issues in mobile view that need to be addressed:

https://user-images.githubusercontent.com/7570704/116925363-b6c08a00-ac1e-11eb-84ed-8522752f84f3.MP4

**Comment by leecalcote** [comment]
@Jashpatel1 I think we can close this issue now, if you're reach. A bug-tracking issue has been opened to make the nav bar responsive - https://github.com/layer5io/layer5/issues/1893
