### ISSUE TITLE
[discuss] Hero

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1717]
_See [Epic] Discourse-based Discussion Forum #1394_

#### Description
The discuss.layer5.io site needs a hero. Ideally, this hero includes a simple navigation to community resources:

- service mesh (link to the top-level service mesh topic in discuss.layer5.io)
- calendar (link to community calendar)
- playlists (link to YouTube channel)

#### Implementation
See the **[Design Specification](https://docs.google.com/document/d/1MDdIZGr8cw_iyZD1H4G7k8AbcFJ79_4UhbKgGltfa7U/edit)**

#### Mockups
- **[discuss designs](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4850%3A10)**

Desktop

Mobile

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@austinogiza do you have another iteration of this design?

**Comment by leecalcote** [comment]
@EmperorYP7 we're all set with the first iteration of the hero design.

**Comment by EmperorYP7** [comment]
On it! 🔨

**Comment by blossom-babs** [comment]
Can I work on this too. Though I noticed the figma links are design specification links are not live

**Comment by EmperorYP7** [comment]
Hey @blossom-babs, I am working on a test component for this which is deployed on discuss.layer5.io : https://github.com/EmperorYP7/discourse-search-banner

I'll add you as a collaborator for this. Let me know if you're in!

**Comment by Nikhil-Ladha** [comment]
Good to close this @leecalcote, @Jashpatel1  ?

**Comment by leecalcote** [comment]
@Nikhil-Ladha, yes, I think so. ✔️
