### ISSUE TITLE
Add Maistra to service mesh Landscape 

### ISSUE THREAD

**Issue by yogi4** [layer5io/layer5#172]
Hi @brian-avery will you consider adding(via PR) a listing for Maistra to the  [service mesh landscape](https://layer5.io/landscape)? We'd love to have an accurate listing of Maistra  in Landscape. 

[Contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) - an update to both the [meshes.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/meshes.yml) and [non-functional.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/non-functional.yml) file would do the trick.
Thanks

**Comment by leecalcote** [comment]
@brian-avery @nmasse-itix @hguerrero does this look accurate? https://github.com/layer5io/layer5/pull/182/files

Thanks, @gunjanmimo

**Comment by gunjanmimo** [comment]
sir, should i i change something ?

**Comment by leecalcote** [comment]
No, looks great. In general, we want for the project / product owners to verify the accuracy of a project's representation.

**Comment by gunjanmimo** [comment]
ok sir, i will add the project/product owner details?
so, what should be project/ product owner details for maistra?

**Comment by brian-avery** [comment]
Apologies for the delay. Looking at this now. 

We have two different versions of Maistra. Maistra itself, and OpenShift Service Mesh (commercially supported downstream version).  Should we list both?

**Comment by leecalcote** [comment]
@brian-avery thanks for taking a look! Yes, I think having OpenShift Service Mesh listed under the *Commercial Offerings* column of the Maistra entry makes much sense. 

We encourage the project representatives to directly contribute to the landscape as much as possible. It would be fantastic if you were to update @gunjanmimo's branch (https://github.com/layer5io/layer5/tree/gunjanmimo-patch-2-1) to reflect this suggestion.

**Comment by brian-avery** [comment]
Happy to. Thanks!

**Comment by brian-avery** [comment]
Added Maistra details in #186

**Comment by brian-avery** [comment]
Moving Maistra details to #251

**Comment by brian-avery** [comment]
@girishranganathan Now that #251 is merged and live on the site, I think we can close this. Thanks for the approval.

**Comment by girishranganathan** [comment]
Hello @brian-avery, sorry my bad. Yes I will close this. Thx again.
