### ISSUE TITLE
[Community] Member Profile: Aditi Ahuja

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#1732]
**Current Behavior**

@metonymic-smokey  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @metonymic-smokey  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: metonymic-smokey
- Twitter: Aditi09039216
- LinkedIn: aditi-ahuja-334394193
- Link to profile picture: https://drive.google.com/file/d/1sROf4zwuDpy-4u44wvSD-1BstkEzojT5/view?usp=sharing

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by navendu-pottekkat** [comment]
@metonymic-smokey could you provide a short bio to be added to your profile here?

**Comment by metonymic-smokey** [comment]
@navendu-pottekkat , here is a bio:

"Student developer from Bangalore, India passionate about venturing into newer, niche fields.
Open to challenges and opportunities, technical or otherwise!"

**Comment by Abiola-Farounbi** [comment]
I will like to be assigned this issue

**Comment by leecalcote** [comment]
Wonderful, @Abiola-Farounbi
