### ISSUE TITLE
Smooth Transition of Navigation Menu on Mobile view

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1733]
**Description**

Menu is not opening smoothly

**Expected Behavior**

On clicking Hamburger menu button , Menu should open smoothly.
**Screenshots**

https://user-images.githubusercontent.com/44670961/113262508-4f957a00-92ee-11eb-9c79-70bebe3011af.mp4

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by tileitner** [comment]
You can assign this to me

**Comment by leecalcote** [comment]
Good deal. Thank you, @tileitner
