### ISSUE TITLE
[Community] Member Profile: Update Navendu Pottekkat to Maintainer, Meshery CLI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1735]
**Current Behavior**
@navendu-pottekkat is now a maintainer of Meshery CLI.

**Desired Situation**
[Navendu's profile](https://layer5.io/community/members/navendu-pottekkat) should reflect this role.

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by adithyaakrishna** [comment]
@leecalcote Can I Work on this?
