### ISSUE TITLE
[CONTRIBUTING.md] Update with instructions for modifying community member profiles

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1736]
**Current Behavior**
The [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) file has a "Common Types of Site Updates" section with a couple of examples.

**Desired Situation**
The Layer5.io website has many community member profiles. Updates to these profiles happen with some regularity. A new section should be added to the contributing guide with instructions on:

1. where to find source code for profiles
2. what badges are and when to assign what badges to whom.

The GitHub Issue template for [Member Profile updates](https://github.com/layer5io/layer5/blob/master/.github/ISSUE_TEMPLATE/community_member_profile.md) should also be updated with a link to this new section.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by blossom-babs** [comment]
Hi Lee, I would like to start with this task. Can I be assigned to it.

**Comment by leecalcote** [comment]
Yes, @blossom-babs. That would be lovely.
