### ISSUE TITLE
[Image Hub] Description in Readme needs updated

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1737]
**Current Behavior**
The Image Hub description in the readme of this repo needs to reflect compatibility with Istio and other potential updates.

---
**Contributor Resources**
Reference to the `ImageHub` Readme and add accordingly https://github.com/layer5io/image-hub#readme

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by adithyaakrishna** [comment]
@Chadha93 Let's knock this out over our call today, what say?

**Comment by Chadha93** [comment]
> @Chadha93 Let's knock this out over our call today, what say?

Sure lets do it

**Comment by sudo-NithishKarthik** [comment]
@Chadha93 , any updates ?

**Comment by Chadha93** [comment]
> @Chadha93 , any updates ?

Oops! how it got slipped from my list. IMO @sudo-NithishKarthik, how about giving this issue a "first-timers only". I will provide a link to the description which should be referenced. Sounds good ??

**Comment by sudo-NithishKarthik** [comment]
Yup

**Comment by Goodiec** [comment]
Hi @sudo-NithishKarthik could this be assigned to me?

**Comment by warunicorn19** [comment]
for sure @Goodiec, here you go!

**Comment by Goodiec** [comment]
@Chadha93, please provide the link to the description you mentioned.

**Comment by Chadha93** [comment]
> @Chadha93, please provide the link to the description you mentioned.

@Goodiec I have updated it in the description of the issue. https://github.com/layer5io/image-hub#readme
