### ISSUE TITLE
[Community] Member Profile: Yash Pandey's profile photo is wrapped in an unnecessary layer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1738]
**Screenshot**
<img width="349" alt="Screen Shot 2021-04-01 at 10 53 25 PM" src="https://user-images.githubusercontent.com/7570704/113379263-a1fe8700-933e-11eb-8f48-ea2afaef10d5.png">

**Current Behavior**
@austinogiza, I believe @EmperorYP7's profile photo was exported from Figma as a member card inadvertently and used in his member profile. 

**Desired Situation**
[@EmperorYP7's member profile](https://layer5.io/community/members/yash-pandey) should simply have his photo, not a double-layering of outer edging. Yash's photo - https://drive.google.com/file/d/1jo43k3xaB0jZCmaBTGcczRkaZOZ6D_CG/view?usp=sharing

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by siddhantdixit** [comment]
Can I work on this ?

**Comment by leecalcote** [comment]
@siddhantdixit that would be great, yes.
