### ISSUE TITLE
Mobile menu icon animation

### ISSUE THREAD

**Issue by tileitner** [layer5io/layer5#1739]
**Description**
Mobile menu icon has no closing animation

![ezgif com-gif-maker](https://user-images.githubusercontent.com/56436108/113390773-a94f8000-9392-11eb-985d-cdd3fdcfd3aa.gif)

**Expected Behavior**
On closing the mobile menu, the icon should have some sort of animation

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Good eye, @tileitner. You’re right, the menu should have a closing animation.

**Comment by leecalcote** [comment]
@tileitner I’m assigning you assuming that you’re just the person to take this on. 😀

**Comment by leecalcote** [comment]
@tileitner I encourage you to join the Layer5 community. You’ll find a warm and welcoming bunch inside - http://slack.layer5.io
