### ISSUE TITLE
Add Kuma to list of Meshery adapters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#174]
Meshery's adapter for Kuma is in an alpha state - https://github.com/layer5io/meshery-kuma - and needs represented on the https://layer5.io/meshery page.

See [contributing Instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for editing https://github.com/layer5io/layer5/blob/master/_includes/meshery.html

Also, there's a missing whitespace in this line: ```Meshery adapter for Maesh(alpha)```. Whitespace needs inserted before the "(".

**Comment by gunjanmimo** [comment]
it is done properly.
