### ISSUE TITLE
[Event] KubeCon EU 2021: Add CNCF SIG Network talk to events list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1741]
**Event:**
- Event Title: CNCF SIG Network Intro and Deep Dive
- Event Link: https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/
- Talk Description: “It’s the network!” is the cry of every system administrator, every developer. With the increased prevalence of microservice-based distributed systems, it’s true - networking as a discipline has never been more critical in the efficient operation of cloud native deployments. Networking primitives, including load balancing, observability, authentication, authorization, policy, rate limiting, QoS, mesh networks, legacy infrastructure bridging, and so on are now receiving substantial development and investment throughout the industry and are the subject of focus of the CNCF Network SIG.
- Talk Link: https://kccnceu2021.sched.com/event/ijVr/cncf-sig-network-intro-and-deep-dive-lee-calcote-layer5-ken-owens-fiserv
- Deck: N/A
- Video: N/A

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by adithyaakrishna** [comment]
@leecalcote If this issue is up for grabs, I would love to work on it 👀
