### ISSUE TITLE
Smooth Transition of "Choose Your Platform" Command div

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1752]
**Current Behavior**

Command div neither smoothly opens nor does it close.

**Desired Behavior**

Command div should open & close smoothly.

---
[Optional] **Screenshots / Mockups**

https://user-images.githubusercontent.com/44670961/113507184-9b525880-9566-11eb-839e-0b44334f174b.mp4

[Optional] **Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by iamayushdas** [comment]
Assign this to me

**Comment by adithyaakrishna** [comment]
@iamayushdas Is this being worked on by you? 😶

**Comment by iamayushdas** [comment]
Yes

**Comment by Tanuj22** [comment]
@iamayushdas any updates here?

**Comment by iamayushdas** [comment]
No i tried but unable to do this . need help!

**Comment by OlaoluwaM** [comment]
Hey @iamayushdas do you still need help?

**Comment by iamayushdas** [comment]
yes

**Comment by leecalcote** [comment]
@OlaoluwaM if you are considering adding a helping hand, I'll encourage you to join the Layer5 Community Slack, as you might find it a convenient way to collaborate and chat (http://slack.layer5.io) as this issue is worked through.

**Comment by OlaoluwaM** [comment]
Oh alright, how do I join

**Comment by leecalcote** [comment]
See the link in the comment above

**Comment by OlaoluwaM** [comment]
Done! What's the URL for the problem area on the website?

**Comment by chinmaym07** [comment]
Here it is @OlaoluwaM  https://layer5.io/service-mesh-management/meshery/getting-started

**Comment by OlaoluwaM** [comment]
Hey @chinmaym07 , could you assign me to this issue so I can easily keep track of it. It took me a while to find

**Comment by sudo-NithishKarthik** [comment]
If no one is currently working on it, i can take up this issue ✌🏽

**Comment by adithyaakrishna** [comment]
Yes sure @sudo-NithishKarthik 
This has been pending from a long time, you can knock it down 🎉

**Comment by sudo-NithishKarthik** [comment]
https://user-images.githubusercontent.com/75248557/122863051-c0718e80-d33f-11eb-9ffa-a02a921d3b8a.mov

Will this do ?

**Comment by Tanuj22** [comment]
@sudo-NithishKarthik transition should be present when the code block appear i.e smooth transition to expand downward when the button is clicked.

**Comment by sudo-NithishKarthik** [comment]
> @sudo-NithishKarthik transition should be present when the code block appear i.e smooth transition to expand downward when the button is clicked.

You are talking about the movement of **Manage your mesh** component right?

**Comment by Tanuj22** [comment]
Yes

**Comment by sudo-NithishKarthik** [comment]
https://user-images.githubusercontent.com/75248557/123033264-1bb98480-d405-11eb-8cd6-41aa989654ad.mov

**Comment by sudo-NithishKarthik** [comment]
Any comments ?

**Comment by Tanuj22** [comment]
@sudo-NithishKarthik looks good. Please open up a PR
