### ISSUE TITLE
Notify user when the code block content is copied

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1753]
**Current Behavior**

Currently When clicking on Copy button ,the command is getting copied ,but there is no notification to the user that the command is copied. 

**Desired Behavior**

Notify user On Clicking Copy Button on CodeBlock component that the command is copied.

---
[Optional] **Screenshots / Mockups**

https://user-images.githubusercontent.com/44670961/113516703-598ed580-9599-11eb-891c-729a1057f9e2.mp4

[Optional] **Alternatives**

Refer to [mehery.io](https://meshery.io/) Codeblock Component.

https://user-images.githubusercontent.com/44670961/113516816-ffdadb00-9599-11eb-8a0e-bdbc65fddc37.mp4

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by arsen1c** [comment]
Can you assign this to me?

**Comment by chinmaym07** [comment]
Thankyou @arsen1c !! Happy Contributing 👍🏻  😁

**Comment by rijusougata13** [comment]
can i work on this ? @chinmaym07

**Comment by rijusougata13** [comment]
hey what's the step to reproduce?

**Comment by chinmaym07** [comment]
Let @arsen1c try work on this issue. meanwhile you can try your hands on other available issues . 
You can navigate to https://layer5.io/service-mesh-management/meshery/getting-started to reproduce the above issue or you can navigate to any blog where this Code Block Component is used & click on the copy button inside the code block then you will be able to identify the issue.

**Comment by arsen1c** [comment]
@chinmaym07 @Nikhil-Ladha Can we close this issue now?
