### ISSUE TITLE
[Meshery] Use Live Performance Text Count on Operating Service Meshes page 

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1757]
**Current Behavior**

1. Operating Service Meshes page counts up to a static number (2,000+)
https://layer5.io/service-mesh-management/meshery/operating-service-meshes
2. Gettnighthawk project page counts up to static number (2000+)
https://layer5.io/projects/getnighthawk

**Desired Situation**

Use the public endpoint (https://meshery.layer5.io/result/total) that has a real-time test result count instead.

See an example of its use here - https://layer5.io/service-mesh-management/meshery

The animated count should still occur, but count to the actual number instead of a hardcoded number.

---

**Screenshots / Mockups**
![Screenshot_2021-04-05 Meshery, Multi-Mesh Manager](https://user-images.githubusercontent.com/44670961/113550241-613d9100-9610-11eb-9fec-cdc1357f05f7.png)

![Screenshot_2021-04-05 GetNighthawk](https://user-images.githubusercontent.com/44670961/113554727-63efb480-9617-11eb-9181-7e1d1ac79296.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by ting-c** [comment]
Hi @chinmaym07 , I would like to work on this.

**Comment by Anita-ihuman** [comment]
Sure, go ahead @ting-c

**Comment by adithyaakrishna** [comment]
Hey @ting-c , you can refer [this branch](https://github.com/adithyaakrishna/layer5/tree/feature/adithyaakrishna/issue%231757), I had solved this issue but hadn't committed it, feel free to refer that and make the changes in your fork

**Comment by ting-c** [comment]
Many thanks @adithyaakrishna, it is really helpful.

**Comment by adithyaakrishna** [comment]
Happy Hacking @ting-c 🚀
