### ISSUE TITLE
Smooth Opening & closing of Workshops Card

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1758]
**Current Behavior**

Each Workshop Card neither opens smoothly nor does it close.
https://layer5.io/learn/service-mesh-workshops

**Desired Behavior**

Workshop card should open smoothly on clicking ``Read More`` button & close smoothly on clicking ``Read Less`` button.

---
[Optional] **Screenshots / Mockups**

https://user-images.githubusercontent.com/44670961/113560099-17f53d80-9620-11eb-8628-e6b80f9b96b1.mp4

[Optional] **Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Thea10** [comment]
@Ruth-ikegah assign this to me, please

**Comment by adithyaakrishna** [comment]
@chinmaym07 Would this be good? 😶

https://user-images.githubusercontent.com/23498248/113574534-ed17e300-9639-11eb-99a1-4c5f5da1d457.mp4

**Comment by chinmaym07** [comment]
You can refer to https://layer5.io/learn/service-mesh-labs to understand the desired nature.. @Thea10 .
Hey @adithyaakrishna thanks for showing interest ..As this issue is already assigned .. Meanwhile you can have a look on other available issues..Happy Contributing !! 😀

**Comment by adithyaakrishna** [comment]
Yeah sure @chinmaym07 , I had multiple PRs in the pipeline but yeah will work on others :)
Happy Hacking @Thea10 🚀

**Comment by Thea10** [comment]
Alright, thank you @chinmaym07 .
thanks @adithyaakrishna
