### ISSUE TITLE
[Learn] Implementation of Learn.layer5.io Navbar 

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1759]
**Current Behavior**
Currently we have no navbar for the learn.layer5.io

**Desired Situation**
Creation  of the first iteration of the learn.layer5.io navbar  

below is the design 
<img width="1440" alt="navbar" src="https://user-images.githubusercontent.com/44683018/113569562-a2cb3d80-960a-11eb-9e48-e65827c7fd00.png">

design location in figma 
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=4853%3A208

Design asset
logo --- https://drive.google.com/file/d/1YT3sHgmQFfBjlbaR_omdYyaEnFGsK6Ms/view?usp=sharing

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Lezette** [comment]
I would like to work on this @Ruth-ikegah

**Comment by Nikhil-Ladha** [comment]
I think we can close this issue, for the time being, considering the current goal is to reuse the same navbar.

**Comment by leecalcote** [comment]
Thank you, @Nikhil-Ladha
