### ISSUE TITLE
Smooth transition of values to it's final value on getnighthawk page

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1761]
**Current Behavior**

Currently the values on getnighthawk page https://layer5.io/projects/getnighthawk are not smoothly getting to it's final value
 like we have here https://layer5.io/service-mesh-management/meshery

**As Currently ```<h3 /> tag``` is used . Just replace that with ```<Counter />``` Component present in /sections/reusecore** .

![Screenshot_2021-04-05 GetNighthawk(2)](https://user-images.githubusercontent.com/44670961/113593218-ca92c380-9653-11eb-8ccf-312e993f6d3f.png)
 
**Desired Behavior**

 when the page renders ,values should reach there final values smoothly not instantly.

---
[Optional] **Screenshots / Mockups**

https://user-images.githubusercontent.com/44670961/113593149-b3ec6c80-9653-11eb-8da2-5ea1c8ce6c2c.mp4

[Optional] **Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by h3ndry** [comment]
Please asign me to this issue. Is my first time.

**Comment by chinmaym07** [comment]
Thankyou @h3ndry !! Happy Contributing !!
Here is small info for you to solve this issue :- 
**As Currently ```<h3 /> tag``` is used . Just replace that with ```<Counter />``` Component present in /sections/reusecore .**

**Comment by Tanuj22** [comment]
Hey @h3ndry any updates here?

**Comment by OlaoluwaM** [comment]
Hey @Tanuj22 , is this issue still available?

**Comment by Tanuj22** [comment]
> Hey @Tanuj22 , is this issue still available?

Please go ahead

**Comment by OlaoluwaM** [comment]
Hey, would it make sense to add the gatsby-cli as a dependency rather than having other contributors install it globally?

**Comment by OlaoluwaM** [comment]
https://user-images.githubusercontent.com/37044906/115118937-73ea8b00-9f6b-11eb-85f3-ed6bf18cce00.mp4

**Comment by OlaoluwaM** [comment]
Also, I found an issue with the site, was wondering if I should just reference it here or create a separate issue

**Comment by Tanuj22** [comment]
> Hey, would it make sense to add the gatsby-cli as a dependency rather than having other contributors install it globally?

I believe it was added as a dependency but the guide wasn't. Do you mind updating it?

**Comment by Tanuj22** [comment]
>  GetNighthawk-Layer5-metrics-animation.mp4

Looks good. Please open a PR

**Comment by Tanuj22** [comment]
> Also, I found an issue with the site, was wondering if I should just reference it here or create a separate issue

You can open up an issue

**Comment by OlaoluwaM** [comment]
https://user-images.githubusercontent.com/37044906/115119117-6a155780-9f6c-11eb-971c-b825b5ebd508.mp4

**Comment by OlaoluwaM** [comment]
I'll open another issue

**Comment by OlaoluwaM** [comment]
> > Hey, would it make sense to add the gatsby-cli as a dependency rather than having other contributors install it globally?
> 
> I believe it was added as a dependency but the guide wasn't. Do you mind updating it?

Sure, but in my branch I updated it to the latest minor version, 3.3.0. Whereas on the master branch here it is version 3.2.0. Should I still go ahead? The update will be part of this PR

**Comment by Tanuj22** [comment]
Yeah sure
