### ISSUE TITLE
[Event] KubeCon EU: Multiple speakers hyperlinked to same member profile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1762]
**Description**
The hyperlink to speakers on [this event](https://layer5.io/community/events/cncf-sig-network-intro-and-deep-dive) is broken in that it points to two people on the same member profile. Member profiles are individually hosted.

Ken does not have a profile.
Lee has a profile.

**Expected Behavior**
Either no hyperlink at all or only Lee's name hyperlinked.

**Screenshots**
<img width="1172" alt="Screen Shot 2021-04-05 at 2 48 25 PM" src="https://user-images.githubusercontent.com/7570704/113619206-52f67180-961e-11eb-835f-37c0229c4e64.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@adithyaakrishna fyi

**Comment by SachiniAbeygunawardhana** [comment]
Hi, I'm new to Open Source Contributions. Shall I work on this issue?

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna fyi
@leecalcote  Will fix this ASAP 😶

**Comment by adithyaakrishna** [comment]
@leecalcote Can the page be like this? 
https://layer5.io/community/events/kubecon-eu-2020
It does not have any speaker, If not I will change the code which renders the mdx file such that it will be like

- Speaker 1: (With Link)
- Speaker 2: (Without Link)

**Comment by Tanuj22** [comment]
@adithyaakrishna its fine as not all of these individual pages are referenced.

**Comment by Tanuj22** [comment]
> Hi, I'm new to Open Source Contributions. Shall I work on this issue?

@SachiniAbeygunawardhana I think @adithyaakrishna is already working on this. Take a look at the others issues. A lot more of them to be tackled :)

**Comment by leecalcote** [comment]
Wait, @adithyaakrishna. @SachiniAbeygunawardhana inquired first. Given that @SachiniAbeygunawardhana is new to open source, let’s be good stewards and ensure @SachiniAbeygunawardhana has a great first experience. 

@SachiniAbeygunawardhana, please do take this issue forward. @adithyaakrishna is here to answer any questions that you might have - any at all. Please join the Layer5 community Slack if chatting is helpful. @adithyaakrishna will get on a call with you if that helps. I know that he won’t rest until you’ve been successful here. 😄

**Comment by adithyaakrishna** [comment]
Yess Sure @leecalcote 🚀
@SachiniAbeygunawardhana Lmk if you have any issues, I would love to help you out 🦾

**Comment by SachiniAbeygunawardhana** [comment]
@leecalcote, @adithyaakrishna Thanks a lot for assigning this to me. @adithyaakrishna Please excuse me if you had already started working on this. I will contact you if I need any help.

**Comment by SachiniAbeygunawardhana** [comment]
The page looks like this after doing some minor changes.
![image](https://user-images.githubusercontent.com/47135264/113784938-d2d22800-9753-11eb-9ffb-34f250f5c825.png)
The hyperlink is removed. I tried to add the hyperlink only to the second speaker, but could not succeed yet. 
Could you please tell me whether the above solution is acceptable?

**Comment by leecalcote** [comment]
Nice progress, @SachiniAbeygunawardhana 👍 I'll let @adithyaakrishna help identify a mechanism for adding a hyperlink.

**Comment by adithyaakrishna** [comment]
LGTM @SachiniAbeygunawardhana , @leecalcote The code for the events page, renders each member in speakers to a link associated with `/community/members/{speakerName}`

But in future events, we might not be sure if every speaker has a profile in our community so IMO we can add links to both of the speakers and the one who does not have will get the 404 Page.

So if this is implemented we can have the links like this

#### Speakers:

- [Lee Calcote](https://layer5.io/community/members/lee-calcote)
- [Ken Owens](https://layer5.io/community/members/ken-owens)

**Comment by SachiniAbeygunawardhana** [comment]
@adithyaakrishna  thank you, but I had already tried it. I thought it is not appropriate to provide a link that directs to a 404 page, for some speakers. That's why I needed to see whether there is a way to filter out the members who have profiles and provide hyperlinks only for them. In brief, I needed to provide a link for Lee Calcote, but not for Ken Owens in the above scenario.

But, if providing a link which directs to 404 page is okay, I will implement it. @leecalcote

**Comment by Tanuj22** [comment]
@SachiniAbeygunawardhana you can add a check to see if a member exist. Check PageHeader component for reference. Ping me on slack of you any question regarding this.

**Comment by Nikhil-Ladha** [comment]
Also, @SachiniAbeygunawardhana  while you are working on the issue please add the description (in the same  PR) as well for this event as mentioned in the description of this issue #1741 . Otherwise, the page looks empty.

**Comment by leecalcote** [comment]
Spot on, @SachiniAbeygunawardhana. 404s are always to be avoided. // @Jashpatel1

**Comment by leecalcote** [comment]
@SachiniAbeygunawardhana, a quick check-in here.... we're in need of getting this item fixed today (on Friday). Do message if this timeline is too tight and we'll get you switched to another, open issue that isn't as urgently needed. 👍

**Comment by SachiniAbeygunawardhana** [comment]
> 
> 
> @SachiniAbeygunawardhana, a quick check-in here.... we're in need of getting this item fixed today (on Friday). Do message if this timeline is too tight and we'll get you switched to another, open issue that isn't as urgently needed. 👍

@leecalcote I'm really sorry for the delay. I'm already done with the hyperlink. Now I'm working on adding the description as @Nikhil-Ladha  requested. Additionally, I figured out that the date of the event too is not visible in the particular page. An overflow occurs in the SwiperSlide element and I'm trying to fix it. I think I will be able to complete it today.
This is the current view of the page. Only Lee Calcot's name is hyperlinked.
![Screenshot_2021-04-09 CNCF SIG Network Intro and Deep Dive](https://user-images.githubusercontent.com/47135264/114123613-415be500-9910-11eb-94bb-d0b64e6654a7.png)

**Comment by SachiniAbeygunawardhana** [comment]
@leecalcote 
The main part of the issue - **hyperlinking** is already fixed and the changes are pushed in to a separate branch. 
But it seems a bit hard to render the date and the description to the page. I doubt that it is a overflow, but couldn't fix it yet. As this is needed to be completed today, I have no problem if someone else can look into it too, and I'm really sorry for not be able to add the description.

**Comment by Tanuj22** [comment]
@SachiniAbeygunawardhana what seems to be the problem with adding the description? Is simply writing HTML on the mdx file not working? You can take a reference of [Istiocon workshop](https://raw.githubusercontent.com/layer5io/layer5/master/src/collections/events/istiocon2020/index.mdx). 

You can open a PR and I will help in figuring out the issue

**Comment by leecalcote** [comment]
@Tanuj22 great suggestion. @SachiniAbeygunawardhana  getting a PR up (even in draft) will facilitate the assistance of others.

**Comment by SachiniAbeygunawardhana** [comment]
@Tanuj22 Thanks a lot for the tip. I was trying to add a variable for the description in the mdx file. Simply adding the description as the abstract solved the issue. 

really sorry for taking this much time, I'll immediately open up a PR.
