### ISSUE TITLE
[Blog] Fix responsiveness of a blog

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1773]
**Description**
The blog [Meshmate of the Year 2020](https://layer5.io/blog/community/meshmate-of-the-year-2020-nikhil-ladha) is not responsive for mobile view. 

**Expected Behavior**
The blog should be responsive 

**Screenshots**
![Screenshot from 2021-04-09 17-58-34](https://user-images.githubusercontent.com/42486853/114179935-3b402580-995d-11eb-9ad7-b95ab5d12d0c.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Ruth-ikegah** [comment]
@blossom-babs wanna take this up?

**Comment by blossom-babs** [comment]
Yes please.  Can I get assigned to this?

**Comment by Tanuj22** [comment]
@blossom-babs please go ahead
