### ISSUE TITLE
[Program] Add SheCodeAfrica Contributhon Program to Open Source Programs Page

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1774]
**Current Behavior**

Layer5 is participating in SheCodeAfrica Contributhon Program & [Programs Page](https://layer5.io/careers/programs) is missing card & details for it .  

**Desired Situation**

Add a Card & details for SheCodeAfrica Program .
Please refer to this doc for more details about the program 
https://docs.google.com/document/d/1_LUAqcCnAl-8lCZMKBSRUsZB1358SjHT3cPyej2wTcg/edit#

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
// @Ruth-ikegah

**Comment by Thea10** [comment]
@Ruth-ikegah  please assign this to me
