### ISSUE TITLE
[Community] Member Profile: Stephen Miller

### ISSUE THREAD

**Issue by ramrodo** [layer5io/layer5#1776]
**Current Behavior**

@smille02a has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @smille02a as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: `@smille02a`
- Twitter: `@smille02`
- LinkedIn: http://www.linkedin.com/in/swmps
- Link to profile picture: 
![profile-1602695611518](https://user-images.githubusercontent.com/2797052/114287872-37c99e80-9a30-11eb-9e18-2881ec5448ad.jpg)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Anita-ihuman** [comment]
@Smille02a  can you please provide a short bio about yourself.

**Comment by Anita-ihuman** [comment]
@ramrodo can i take up this issue?

**Comment by ramrodo** [comment]
Sure @Anita-ihuman, please go ahead 😊

**Comment by Smille02a** [comment]
Sure. Please feel free to prune at your discretion.


I am a Senior IT Solutions Architect with over 29 years of experience in F50/F500 enterprise-class systems. My experience includes over 10-years of virtualization (Windows, Solaris) and various cloud platforms with modern software stacks.
Current activities include DevOps and Microservices, cloud migrations (lift and shift, greenfield, redesign), with a proven ability to document, implement, PM manage, design, and troubleshoot complex, enterprise-level systems, often with numerous upstream and downstream dependencies.  Also in the purview are key performance indicators. These may include ROI, regulatory, security, AAA  authentication, latency, bandwidth, scalability and elasticity, DR, and BCE SLA requirements. These can be designed as required, and if performed and communicated correctly, a significant ROI can be achieved.


Thank you.
--
Regards,
Stephen W.  Miller
***@***.******@***.***>        Secondary: ***@***.******@***.***>
Cell:      917.704.5934     Fax:      212.225.8247
Skype:  live:smille02      Skype: 816.548.2929
Twitter: @Smille02        WhatsApp: Cell +1 917.704.5934
Schedule a meeting:     https://calendly.com/smille02
LinkedIn URL:                 https://www.linkedin.com/in/swmps

**Comment by Anita-ihuman** [comment]
Please can you include your location(state & country)

**Comment by Smille02a** [comment]
Sure, Manhattan, NYC, NY, US


thx-swm
