### ISSUE TITLE
[Community] Handbook: Add link to New Community Member form

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1778]
**Current Behavior**
A new, vanity link has been created to make it simple to direct newcomers to the Community Member form.

**Desired Behavior**
https://layer5.io/newcomer redirects to the community member form at https://docs.google.com/forms/d/e/1FAIpQLSdMLeZY6hZ46yYNkoKKV5OM-jCypjbYcqptbUNltEE73EqCjA/viewform

A note about the availability of this convenient link can be made in the Layer5 Community Handbook.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
FYI @Ruth-ikegah 

// @Annysah, @sandygudie, @Abiola-Farounbi

**Comment by Ruth-ikegah** [comment]
noted! @leecalcote

**Comment by sandygudie** [comment]
Noted @leecalcote

**Comment by leecalcote** [comment]
Good, good. Thank you. We need a propagating this link a little. Including it in read me is next to callouts for joining the community might be a good idea.

**Comment by Annysah** [comment]
Noted

**Comment by Abiola-Farounbi** [comment]
> 
> 
> Good, good. Thank you. We need a propagating this link a little. Including it in read me is next to callouts for joining the community might be a good idea.

Yes it is

**Comment by adithyaakrishna** [comment]
@leecalcote How about if we can add a button here at https://layer5.io/community/newcomers to redirect to the form for newcomers? 😶

**Comment by leecalcote** [comment]
@adithyaakrishna, yes. We’re in need of butting a link to https://layer5.io/newcomer is a few places.

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna, yes. Let’s do it. We’re in need of butting a link to https://layer5.io/newcomer is a few places.

Okay Sure @leecalcote , do let me know all the other places where the button & link has to be present. Will work on it and finish by tomorrow 🚀

**Comment by leecalcote** [comment]
Before I suggest a spot or two across the site, I'm curious if others have suggestions. @Abiola-Farounbi @sandygudie @Annysah @Ruth-ikegah?

**Comment by Ruth-ikegah** [comment]
> Before I suggest a spot or two across the site, I'm curious if others have suggestions. @Abiola-Farounbi @sandygudie @Annysah @Ruth-ikegah?

A button just before "How to contribute" sounds good to me. @adithyaakrishna 

Another suggestion will be to add it to the map, but then a redesign might need to happen. Although with the coming of the community handbook, some items like Newcomer's guide, community guide, and Repository overview will be replaced since the community handbook will have that

**Comment by adithyaakrishna** [comment]
> > Before I suggest a spot or two across the site, I'm curious if others have suggestions. @Abiola-Farounbi @sandygudie @Annysah @Ruth-ikegah?
> 
> A button just before "How to contribute" sounds good to me. @adithyaakrishna
> 
> Another suggestion will be to add it to the map, but then a redesign might need to happen. Although with the coming of the community handbook, some items like Newcomer's guide, community guide, and Repository overview will be replaced since the community handbook will have that

@Ruth-ikegah  Okay sure will add it there. Also, if it's to be added to community handbook, I would love to work on it as it involves redesigning part too 👀

**Comment by Chadha93** [comment]
@leecalcote @Ruth-ikegah @adithyaakrishna  I also have an idea for this, what we can do that add a fixed component at the right side so the newcomer can access it throughout the page.
Idea image: 
![Desktop - 1](https://user-images.githubusercontent.com/65453826/116803590-bd73d200-ab36-11eb-8bc4-f975e0569eac.png)

**Comment by adithyaakrishna** [comment]
@Chadha93 This is a great idea 🎉
But how would it be visible in mobile view?

**Comment by Chadha93** [comment]
@adithyaakrishna This is the mobile view in two different stacking of the component 
First:
![Android - 1](https://user-images.githubusercontent.com/65453826/116804757-0a5ba680-ab3f-11eb-8603-1bc131ad91b1.jpg)
Second:
![Android - 2](https://user-images.githubusercontent.com/65453826/116804765-18112c00-ab3f-11eb-9d4c-21978b996aeb.jpg)

**Comment by adithyaakrishna** [comment]
@Chadha93 The second one looks amazing, goes well with the overall site also 👀

**Comment by leecalcote** [comment]
// @austinogiza

**Comment by adithyaakrishna** [comment]
@leecalcote I guess we can go ahead with @Chadha93 's idea on this, as it was a great suggestion from him. What's your opinion on this? 👀

**Comment by adithyaakrishna** [comment]
@Chadha93 Let's knock this out too, I guess we can go ahead with your proposed thing and create a PR for this, once done we can make changes during review
