### ISSUE TITLE
[BUG] Meshery Landscape Page Distorted

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/layer5#1779]
**Description**

![image](https://user-images.githubusercontent.com/44001539/114449955-06e59700-9bf3-11eb-8d80-b5e70be78479.png)
![image](https://user-images.githubusercontent.com/44001539/114450021-1d8bee00-9bf3-11eb-8e81-6977ab35795b.png)

**Expected Behavior**

**Screenshots**

**Enviroment:**
- Host OS: Ubuntu 20.04.2 LTS
- Kubernetes Version: 
- Browser: Chrome 89.0.4389.114

---

[Optional] **To Reproduce**
1. Go to https://layer5.io/service-mesh-landscape

Is this only me, or is it a common issue?

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
On macOS Big Sur with either Safari 14.0.3 or Chrome 89.0.4389.114, I don't see this issue. Doesn't mean that this isn't an issue, but here are two additional data points for you.

**Comment by Tanuj22** [comment]
Can't replicate the issue on Ubuntu 20.04 and Chrome 89.0.4389.114 :thinking:

**Comment by Nikhil-Ladha** [comment]
@dhruv0000  Open the page, and then again reload it.

**Comment by dhruv0000** [comment]
@Nikhil-Ladha Still the issue persists. The issue doesn't persists in Firefox though. Since it is local to my machine, I think I will take a look into it when I get some time.

**Comment by Nikhil-Ladha** [comment]
@dhruv0000 is this issue still reproducible?
Could you please try it out in incognito mode for Chrome, if it doesn't reproduce there might be a cache issue?

**Comment by leecalcote** [comment]
@dhruv0000 have you seen this again?
