### ISSUE TITLE
[Brand] Create new section for GetNighthawk

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1780]
**Current Behavior**
GetNighthawk is an upcoming Layer5 project. It now has a logo and small brand kit that needs to be made available on https://layer5.io/brand

**Desired Behavior**
On https://layer5.io/brand:
1. A new section for GetNighthawk needs to be created.
1. The zipped brand kit needs to be made available for download. 
[getnighthawk-brand-kit.zip](https://github.com/layer5io/layer5/files/6305014/getnighthawk-brand-kit.zip)
(updated)

1. The project logo should be displayed on the page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Thea10** [comment]
@Ruth-ikegah please assign this to me

**Comment by Ruth-ikegah** [comment]
sure!

> @Ruth-ikegah please assign this to me

**Comment by leecalcote** [comment]
@Ruth-ikegah, @Thea10 thank you. @Thea10, please note that I _just_ uploaded a new version of the brand-kit zip file in the issue description above.

**Comment by Thea10** [comment]
noted @leecalcote
