### ISSUE TITLE
[Programs] Logo not centered 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#1782]
**Description**
The logo is not vertically centered for Linux Foundation at https://layer5.io/careers/programs 

**Expected Behavior**
The logo should be vertically centered 

**Screenshots**

![Screenshot from 2021-04-13 16-09-57](https://user-images.githubusercontent.com/42486853/114540042-b9a90a00-9c72-11eb-9018-8b2917e42df5.png)

**Enviroment:**
- Host OS: Ubuntu 20.04
- Browser: Chrome 89.0.4389.114

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by adithyaakrishna** [comment]
@Tanuj22 Can I work on this?

**Comment by Jashpatel1** [comment]
> @Tanuj22 Can I work on this?

Yes, please go ahead.

**Comment by adithyaakrishna** [comment]
@Tanuj22 @Jashpatel1 This can be immediately changed using `position: initital` property but since we are upgrading gatsby to a latest version some of the images may need realignment again which I'm working on already. Should I fix this individually or should I fix it as part of #1767 ?

**Comment by Jashpatel1** [comment]
> @Tanuj22 @Jashpatel1 This can be immediately changed using `position: initital` property but since we are upgrading gatsby to a latest version some of the images may need realignment again which I'm working on already. Should I fix this individually or should I fix it as part of #1767 ?

You can fix it in #1767
