### ISSUE TITLE
[Blog] Meet The Maintainer : Jash Patel 

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1789]
**Current Behavior**

Maintainer Update : Meet The Maintainer Jash Patel is a new blog post .
It's not on the layer5.io website 

**Desired Situation**

To make a new blog post & add it to [layer5.io](https://layer5.io)
Refer to this doc for more info 
https://docs.google.com/document/d/1o5MasuMXM8unApoTaqrscZy34BQe0_-mdAvmP-6qqjc/edit

Here is a link to the cover photo
https://layer5.io/static/551ae052af26d99e23ae0ab5a053815e/I%20Jash%20Patel.png

Here is blog post that you can refer to solve this issue
https://layer5.io/blog/community/meet-the-maintainer-michael-gfeller

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by blossom-babs** [comment]
I’ll work on this

**Comment by Ruth-ikegah** [comment]
sure @blossom-babs go ahead!
