### ISSUE TITLE
Bump Gatsby CLI from version 3.2.0 to 3.3.0

### ISSUE THREAD

**Issue by OlaoluwaM** [layer5io/layer5#1791]
**Current Behavior**

Project is using version 3.2.0 of gatsby-cli

**Desired Situation**

Project should use latest minor version 3.3.0

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Related to https://github.com/layer5io/layer5/pull/1767

**Comment by Nikhil-Ladha** [comment]
I would recommend we should not bump dependencies so fast as 3.3.0 was out recently and many times new version can bring unwanted issues.
Also, what benefit does 3.3.0 give over 3.2.0?

**Comment by OlaoluwaM** [comment]
I was given the go-ahead by @Tanuj22 so you can ask him 🙂

**Comment by Tanuj22** [comment]
I didn't knew that 3.3.0 was out recently. Then 3.2.0 would be better 😅

**Comment by Nikhil-Ladha** [comment]
I checked the release notes and the updates are good, but only beneficial if we are using Gatsbyv3. So, considering that is still in progress, I would suggest only make the doc update and the dependency can be updated In the other PR, i.e, #1767
