### ISSUE TITLE
[Project] Getnighthawk Logo update for Project Grid

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/layer5#1794]
**Current Behavior**
The old logo of Getnighthawk is currently on the Project Grid page 

![chrome_8GiA6JJjbW](https://user-images.githubusercontent.com/54861487/115142021-0b7bd680-a05d-11eb-8c8b-29404d5d46ea.png)

**Desired Situation**
Update it to the new logo of getnighthawk. You can find the suitable files required for this at https://layer5.io/company/brand or simply link it with the already existing logo at https://github.com/layer5io/layer5/blob/master/src/assets/images/getnighthawk/icon-only/SVG/getnighthawk-logo.svg

The Logo already exists in the assets.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by adithyaakrishna** [comment]
@vinayaksh42 Can You Assign this to Me?
If it's okay will fix this issue as part of PR #1767

**Comment by vinayaksh42** [comment]
@adithyaakrishna that PR already refers to 2 different issues. It would be better if you open a separate PR for this issue so that it is easy to review it.

**Comment by adithyaakrishna** [comment]
Okay Sure @vinayaksh42

**Comment by adithyaakrishna** [comment]
@vinayaksh42 Could you please assign this to me?
