### ISSUE TITLE
Nav toggles back and forth between elevated and flat state

### ISSUE THREAD

**Issue by OlaoluwaM** [layer5io/layer5#1795]
**Description**

The navbar, after you scroll up to a certain point then stop scrolling, toggles quickly between elevated (with box shadow) and flat states causing to look as if its shaking 

**Expected Behavior**

It should remain in one place. I think this is an edge-case because this behavior occurs at the instant where the box-shadow is supposed to be applied to the nav.

**Screenshots**

https://user-images.githubusercontent.com/37044906/115149163-70690980-a028-11eb-8a96-b8a3908c2780.mp4

**Enviroment:**
- Host OS: Windows
- Meshery Version: 
- Kubernetes Version: 
- Browser: Chrome 89

---

[Optional] **To Reproduce**
1. Open up the layer5.io site
2. Resize the browser until the nav is replaced with a clickable burger (at  a width of about 900px)
3. Scroll down just untill the point where the nav is given a light green shadow, then stop scrolling at that point
4. The nav toggles between the elevated state (with box shadow) and flat state

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by karinape** [comment]
Hi! I would like to take a look at this!

**Comment by leecalcote** [comment]
@karinape that would be excellent. 👍
