### ISSUE TITLE
[Feature] Upgrading <img> to <StaticImage> using gatsby-plugin-image

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/layer5#1801]
**Current Behavior**
After the upgradation of Gatsby from v2 to v3, it bought some major changes to the way images are rendered. 
As of now `<GatsbyImage> `is used for images along with `<img`> for .svg files

**Desired Behavior**

We need to explore complete possibilities of `gatsby-plugin-image` along with its benefits for all the images on the site
Eg. We need to utilize the plugin for using `<StaticImage>` tags in place of `<img>` tags

---
**Screenshots / Mockups**
The below screenshot shows the usage of `<img>` along with `<GatsbyImage>` tags

<img src="https://user-images.githubusercontent.com/23498248/115301923-76bdc980-a17f-11eb-8574-63e7fc8345fb.png" width="615" height="228" >

Some Starter Resources: https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by karinape** [comment]
I would like to work on this!

**Comment by Tanuj22** [comment]
@karinape please go ahead. Do note that this issue is a bit vague so you need to explore how we would go about replacing all the `<img>` tags. If you have questions please reach out in slack

**Comment by karinape** [comment]
Will do! @Tanuj22

**Comment by Jashpatel1** [comment]
Any updates here @karinape

**Comment by Anita-ihuman** [comment]
@karinape any updates on this?

**Comment by Amishakumari544** [comment]
can I take this issue?

**Comment by warunicorn19** [comment]
Here you go, @Amishakumari544!

**Comment by warunicorn19** [comment]
@Amishakumari544 any updates?

**Comment by Amishakumari544** [comment]
No @warunicorn19 o discussed with the seniors they told me that they will discuss this in the meeting as no proper solution found till now for this

**Comment by warunicorn19** [comment]
@Amishakumari544 okay , @Jashpatel1 @Tanuj22 should we put this as an agenda in the community meeting?

**Comment by Tanuj22** [comment]
@warunicorn19 websites call will be better for this ig

**Comment by warunicorn19** [comment]
@Tanuj22 okay, sounds good.

**Comment by Amishakumari544** [comment]
Is there any update on this @warunicorn19 ??

**Comment by warunicorn19** [comment]
@Amishakumari544 it would be great if you could be on tomorrow's websites' call and bring this up. We tend to keep forgetting😅.

**Comment by Tanuj22** [comment]
@warunicorn19 @Amishakumari544 can you list this down as topic in the meeting minutes?

**Comment by warunicorn19** [comment]
@Tanuj22 Yup did it already

**Comment by Amishakumari544** [comment]
Oh sorry I will join tomorrow 😅

**Comment by Zain-Muiz** [comment]
@warunicorn19 , ping! Has the discussion on this issue come to an outcome ?

**Comment by warunicorn19** [comment]
@Zain-Muiz we spoke on this in a meeting, any updates @Amishakumari544?

**Comment by Amishakumari544** [comment]
The process of including images using path is working fine but there are lot images and its very hard to change for every images if you want you can take this issue @Zain-Muiz

**Comment by Zain-Muiz** [comment]
Can we not replace all img tags directly through search and replace ? I'm not aware of what this issue is, @warunicorn19 , Is the find all and replace all method possible here ?

**Comment by Amishakumari544** [comment]
No you can't . I already done this thing you have import images as path.
