### ISSUE TITLE
[Projects] Update Distributed Performance Management Page

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1802]
**Current Behavior**

1. Currently Some info is missing from [Distributed Performance Management Page](https://layer5.io/projects/distributed-performance-management) 
2. Padding & margin is also missing.

**Desired Situation**

Add Some more info to this page using the slides 
https://docs.google.com/presentation/d/1mDE9K8OJ3lyl4GN98Ja3c9ATGWS4rByRtCPIKcoc7LY/edit#slide=id.g77e93b29e5_1_0
& increase padding & margin

[Optional] **Additional context**

![Screenshot_2021-04-21 Distributed Performance Management](https://user-images.githubusercontent.com/44670961/115510336-381e3100-a29d-11eb-85d7-b1ad8b062a71.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Anita-ihuman** [comment]
If i understand you correctly you want include the slides(https://docs.google.com/presentation/d/1mDE9K8OJ3lyl4GN98Ja3c9ATGWS4rByRtCPIKcoc7LY/edit#slide=id.g77e93b29e5_1_0) on this page ?

**Comment by chinmaym07** [comment]
Yes @Anita-ihuman  It would be good if we can include some info present in the slides directly without adding the slides itself . As slides are already present on this page https://layer5.io/projects/service-mesh-performance
