### ISSUE TITLE
[Community] Member Profile: Adithya Krishna

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1804]
**Current Behavior**
@adithyaakrishna  has been a consistent contributor and community member. It's time to recognize his contributions by adding a member profile on the layer5.io/community/members page.

**Desired Situation**
Let's recognize @adithyaakrishna  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: adithyaakrishna
- Twitter: adii_kris
- LinkedIn: adiiikris
- Link to profile picture: https://drive.google.com/file/d/1G50o5fIC6YtD5Bhakm1SLwyca_tRuZ72/view?usp=sharing
- Short Bio: TBA
- Location: Bengaluru, India
- Badge: `Landscape`

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples, which the contributor can follow here.

---

**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by OlaoluwaM** [comment]
Hey @Nikhil-Ladha  can I take this?

**Comment by Nikhil-Ladha** [comment]
@adithyaakrishna if you could share the requested details here, it would be helpful. 🙂

**Comment by Nikhil-Ladha** [comment]
@OlaoluwaM I have updated almost all the details above, you can open a PR with the above data, while we wait for a short bio from Adithya.

**Comment by adithyaakrishna** [comment]
> @adithyaakrishna if you could share the requested details here, it would be helpful. 🙂

- Name: Adithya Krishna
- Location: Bengaluru, Karnataka, IN
- GitHub: https://github.com/adithyaakrishna
- Twitter: https://twitter.com/adii_kris
- LinkedIn: https://linkedin.com/in/adiiikris
- Bio: 
An enthusiastic Final Year CSE student at Jyothy Institute of Technology, Bengaluru and trying to explore newer fields and a person who loves to contribute to Open Source Software. I'm also the type of person who says Yes! to everything spontaneously as I believe in utilizing every opportunity I can get and learning/upskilling myself in the mean process 👨‍💻

**Comment by Tanuj22** [comment]
@OlaoluwaM any updates here?

**Comment by OlaoluwaM** [comment]
Hey @Tanuj22 , so sorry for the delay I had to take care of some personal things. I will finish this up soo. Thanks🙂

**Comment by OlaoluwaM** [comment]
What does the `blurb` field represent?

**Comment by Tanuj22** [comment]
> What does the `blurb` field represent?

Its not being used currently. You can just keep it `Mesh Head` for now

**Comment by OlaoluwaM** [comment]
Done!
