### ISSUE TITLE
[README] Broken image link for GetNighthawk

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1805]
**Current Behavior**
The GetNighthawk logo is missing in this repo's readme. The GetNightHawk logo can be found here - https://layer5.io/brand.

**Desired Situation**
GetNighthawk logo image should be stored in and reference from here - https://github.com/layer5io/layer5/tree/master/.github/assets/images

**Screenshot**
<img width="889" alt="Screen Shot 2021-04-21 at 10 40 37 AM" src="https://user-images.githubusercontent.com/7570704/115582058-300ac500-a28e-11eb-80af-cd5d13ecaaef.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Abiola-Farounbi** [comment]
can i be assigned

**Comment by Abiola-Farounbi** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
Perfect. 🙂
