### ISSUE TITLE
[Careers] Add a Layer5 card to the list of internship programs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1807]
**Current Behavior**
The [internship programs page](https://layer5.io/careers/programs) is missing an entry for Layer5. Layer5 sponsors internships in collaboration with other groups as well as offers internships directly.

**Desired Behavior**
A Layer5 card should be shown and should lead to https://layer5.io/careers/internships

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by jomefavourite** [comment]
I'll like do this

**Comment by leecalcote** [comment]
Perfect. 🙂

**Comment by jomefavourite** [comment]
@leecalcote I've successfully added the layer5 card but the permalink isn't working it keeps routing to `program/careers/internships` when it like this `permalink: 'careers/internship'`. How I'm I to add the link please

**Comment by leecalcote** [comment]
Thank you, @jomefavourite! Way to stick with this and see it through.
