### ISSUE TITLE
[Careers] Create animated peek-in on hover of internship card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1809]
**Current Behavior**
The internship cards on [this page](https://layer5.io/careers/internships) elevate off the page when they are hovered over.

https://user-images.githubusercontent.com/7570704/115794699-118ef180-a394-11eb-92c0-dae092fd1faf.mov

**Desired Behavior**
Using CSS, it would be nice to add an effect of a Layer5 card peeking in on hover; transitioning in from the right-hand side.

**Mockups**
![Untitled-1](https://user-images.githubusercontent.com/7570704/115795833-48660700-a396-11eb-8fe9-5ca26e2000ec.png)

**Resources**
- [layer5-cards.svg.zip](https://github.com/layer5io/layer5/files/6361707/layer5-cards.svg.zip)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Thea10** [comment]
@leecalcote I'd like to work on this

**Comment by adithyaakrishna** [comment]
Hey @Thea10 
I guess you can start working on this directly as @leecalcote had mentioned it here regarding self-assigning of issues, 
https://github.com/layer5io/layer5/issues/1811#issuecomment-825936617 👀

**Comment by Thea10** [comment]
thank you @adithyaakrishna
