### ISSUE TITLE
Typo in the descriptions section of the UI job listing

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1811]
**Description**

Typo in the description of the UI Job posting page, under careers.

**Expected Behavior**

Comformable -> Comfortable

**Screenshots**

![IMG_5893](https://user-images.githubusercontent.com/29438875/115887599-b8948b80-a46f-11eb-817c-944417e49214.jpg)

---

[Optional] **To Reproduce**
1. Go to https://layer5.io/careers/ui-engineer
2. Scroll to 'Desired Qualifications' section to see the error.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by adithyaakrishna** [comment]
@Nikhil-Ladha There's a Typo in this page too, https://layer5.io/careers/software-engineer 😶

- Go to : https://layer5.io/careers/software-engineer
- Scroll to 'Desired Qualifications' section

![image](https://user-images.githubusercontent.com/23498248/115903393-26957e80-a481-11eb-8538-dcd6e6ae5032.png)

**Comment by leecalcote** [comment]
Softhaired engineers are welcome to apply.

**Comment by leecalcote** [comment]
Good catch, Aadhitya

**Comment by adithyaakrishna** [comment]
> Softhaired engineers are welcome to apply.

I can't stop laughing at this 😂😂😂

@github should add this "😂" emoji to the reactions

**Comment by Abiola-Farounbi** [comment]
I would like to be assigned this issue

**Comment by leecalcote** [comment]
@Abiola-Farounbi a quick note to ensure that ensure that you're able to contribute with a little friction as possible, as a community member you are empowered to self-assign issues as you see fit. 👍

**Comment by Abiola-Farounbi** [comment]
Wow, I didn't know 
Thanks lee
