### ISSUE TITLE
Layer5 event website improvment

### ISSUE THREAD

**Issue by Lezette** [layer5io/layer5#1813]
**Current Behavior**
When an event card is clicked it takes the user straight to an external link for the card

**Desired Behavior**
When the title is clicked we want it to take the user to an internal page that contains a short write up about the event

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thank you, @Lezette ✔️
