### ISSUE TITLE
[CONTRIBUTING] Missing GetNighthawk badge

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1815]
**Description**
Contributors receive badges on their member profiles when they engage in specific projects. The list of batches can be seen in the [contributing.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) . This list is missing an entry for GetNighthawk and has a duplicate entry for SMP

**Expected Behavior**
- no duplications
- the getnighthawk badge

GetNighthawk logo can be found on https://layer5.io/brand

**Screenshots**

![image](https://user-images.githubusercontent.com/7570704/115942095-14f6ab80-a46e-11eb-830c-34a9c7fb0e8f.jpeg)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by josephmidura** [comment]
I can fix this one.

**Comment by leecalcote** [comment]
Thank you, @josephmidura. That would be great. 👍
