### ISSUE TITLE
[Blog] - SIG Network at KubeCon EU 2021

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/layer5#1822]
**Current Behavior**
The upcoming event at KubeCon EU 2021 regarding CNCF SIG Network Intro and Deep Dive doesn't have a blog at https://layer5.io/blog

**Desired Situation**
A post about the upcoming talk by Ken Owens and Lee Calcote. For reference, we have the [Presentation](https://static.sched.com/hosted_files/kccnceu2021/77/SIG%20Network%20at%20KubeCon%20EU%202021%20with%20Lee%20Calcote%20and%20Ken%20Owens.pdf)

**[Event Link](https://kccnceu2021.sched.com/event/ijVr/cncf-sig-network-intro-and-deep-dive-lee-calcote-layer5-ken-owens-fiserv)**
**Tentative Title:** Intro and Deep Dive for SIG Network + Service Mesh WG
**Content:**
- Introduction
- Mission Statement
- Service Mesh Working Group - A Brief about Service Mesh Patterns, Specifications, Interface Conformance, Performance 
- MeshMark & GetNightHawk
- An invitation and call to participation to join #sig-network at [Slack Channel](https://app.slack.com/client/T08PSQ7BQ/CMG237Z5Z) [SIG Network](sig-network@lists.cncf.io) and [Service Mesh WG](cncf-sig-network-servicemesh-wg@lists.cncf.io) mailing lists at [lists.cncf.io](lists.cncf.io)

Slides and Content from the [Presentation](https://static.sched.com/hosted_files/kccnceu2021/77/SIG%20Network%20at%20KubeCon%20EU%202021%20with%20Lee%20Calcote%20and%20Ken%20Owens.pdf)  can be used directly for images and other information.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by adithyaakrishna** [comment]
@leecalcote Could you please confirm this and suggest if any changes are necessary with respect to the contents of the blog?

**Comment by leecalcote** [comment]
Another Tentative Title: "Diving into the CNCF Service Mesh WG at KubeCon EU 2021"

**Comment by adithyaakrishna** [comment]
Completely forgot about this😶
@adithyaakrishna Assign P1

**Comment by leecalcote** [comment]
Thank you.
