### ISSUE TITLE
[Community] Set Contributor Journey map block background to white

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1827]
**Description**
The background here is off-white.

**Expected Behavior**
Background of this section should be pure white.

**Screenshots**
<img width="1228" alt="Screen Shot 2021-04-29 at 8 51 16 AM" src="https://user-images.githubusercontent.com/7570704/116561777-3b7e7180-a8c8-11eb-8a3f-08ddc6fa530a.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Chadha93** [comment]
@leecalcote I have fixed the issue please review it and provide feedback if possible

**Comment by Nikhil-Ladha** [comment]
@Abiola-Farounbi is it fine with you, if we take in @Chadha93's PR. Or have you already fixed it and want to make a PR?
Considering you were already assigned to this issue..

**Comment by Abiola-Farounbi** [comment]
Ooh, just seeing this.
was planning on making a pr later, but since it's already done, @Chadha93  can go ahead.

**Comment by Chadha93** [comment]
> Ooh, just seeing this.
> was planning on making a pr later, but since it's already done, @Chadha93 can go ahead.

Apologize, I think I should have asked for assigning the issue first since I am a newcomer I will take care of it in the future.
