### ISSUE TITLE
[Community] Member Profile: Piyush Singariya

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#1832]
**Current Behavior**

@piyushsingariya has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @piyushsingariya as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  piyushsingariya 
- Twitter:  piyushsingariya
- LinkedIn:  piyushsingariya
- Link to profile picture: https://drive.google.com/file/d/1LpZfiOxYm5MO4O9Bh3yd6DD5XsJyPj7i/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by navendu-pottekkat** [comment]
@piyushsingariya could you provide a short bio to add here?

**Comment by piyushsingariya** [comment]
A Software Engineer from Bikaner, India. Passionate about Anime and solving impactful problems. Open to challenges and opportunities!

~~~ I think this would be fine!

**Comment by adithyaakrishna** [comment]
Check this out, @sachindavra 
Lmk if you can work on it :)

**Comment by sachindavra** [comment]
Thanks @adithyaakrishna , i will work on this.

**Comment by piyushsingariya** [comment]
@sachindavra Use this image instead - https://drive.google.com/file/d/1OroW82tGiNwvRczBMXzIXP5e8WoRAx25/view?usp=sharing

**Comment by sachindavra** [comment]
Could you let me know about blurb and badges you have. @navendu-pottekkat @piyushsingariya 

Thanks.

**Comment by chinmaym07** [comment]
Hey @sachindavra !! 👋🏻 
A detailed explanation on badges for a community member profile can be found here in the [CONTRIBUTING.md#badges-for-community-members](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#badges-for-community-members) ..
For blurb: I think it's currently used . but you can refer to it as a Member's tagline, if they have one (a short quip or phrase) . AFAIK You can use ```  Mesh Head ``` .

**Comment by Nikhil-Ladha** [comment]
You can use the `meshery` badge for Piyush.

**Comment by sachindavra** [comment]
Thank you @Nikhil-Ladha @chinmaym07

**Comment by leecalcote** [comment]
HELLO! 💥 @piyushsingariya 🎉

**Comment by leecalcote** [comment]
Thank you, @sachindavra 👍
