### ISSUE TITLE
[Community] Transition of Kelechi Nwachukwu to Meshmate Emeritus

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#1837]
**Current Behavior**

@PluckyPrecious has been an amazing contributor and Meshmate. Due to some other engagements, she is graduating to Meshmate Emeritus Status. 

**Desired Situation**

Move @PluckyPrecious profile from the [Meshmate section](https://layer5.io/community/meshmates) to the Meshmate Emeritus section following the same pattern.

[Optional] **Additional context**

![Meshmates-Layer5-The-Service-Mesh-Company](https://user-images.githubusercontent.com/62059002/116884593-d061d180-ac1e-11eb-9492-1be7b402a22b.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thank you for all of your MeshMating, @PluckyPrecious! 😄

**Comment by PluckyPrecious** [comment]
It’s a pleasure.🙌🏽☺️

**Comment by iamrajiv** [comment]
@leecalcote I want to work on this.

**Comment by leecalcote** [comment]
Thank you, @iamrajiv. That would be great. 👍
