### ISSUE TITLE
[Learn] Implementation of Card Component of homepage 

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1840]
**Current Behavior**

Currently we have no card component that is used on the homepage of layer5.io/learn-ng

**Desired Situation**

Creation of the first iteration of the card component for homepage

![Screenshot from 2021-05-04 16-43-30](https://user-images.githubusercontent.com/44670961/116995604-e4c5cd00-acf7-11eb-8a99-0600af7c1925.png)

---

[Optional] **Additional context**

Refer to the Figma file to see the designs [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by theprogrammedwords** [comment]
Let me take this up. Thanks.

**Comment by chinmaym07** [comment]
Thankyou @theprogrammedwords .. 👍🏻 .. Happy Contributing ... Assigned to you .. 😀

**Comment by theprogrammedwords** [comment]
Thank you Chinmay. :)

**Comment by theprogrammedwords** [comment]
I am not able to work up on this, I am unassigning myself. Sorry for keeping you up at expectations.

**Comment by leecalcote** [comment]
Hi @theprogrammedwords, no sweat. Thank you for sending this update.

**Comment by OlaoluwaM** [comment]
Hey, can I have a go?

**Comment by leecalcote** [comment]
@OlaoluwaM That would be great, yes!

**Comment by Nikhil-Ladha** [comment]
A potential design for this issue could be this https://www.figma.com/proto/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?page-id=4853%3A0&node-id=6045%3A0&viewport=-777%2C881%2C0.03125&scaling=min-zoom

**Comment by Nikhil-Ladha** [comment]
Also, @OlaoluwaM have tou started working on the issue? Any progress?

**Comment by OlaoluwaM** [comment]
Hey, I'm so sorry for the delay. At the time I saw this issue I thought I'd be able to get to it but then a lot of personal stuff started popping up including an interview 👀.  Hope to get started with this soon, but if someone wants to take over they are free to do so. Sorry 😫

**Comment by Nikhil-Ladha** [comment]
No problem @OlaoluwaM. For the time being, If you don't mind shall I take up this issue?
In the meantime, you can clear out your pending tasks and hop back to work on new issues which we would soon be opening as we progress. What say?

**Comment by OlaoluwaM** [comment]
@Nikhil-Ladha sure, no problem

**Comment by Nikhil-Ladha** [comment]
Closing this issue since the component is already in place.
Closed via #1860
