### ISSUE TITLE
[Learn] Implementation of Sidebar Table of Contents Component

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1841]
**Current Behavior**

Currently We don't have the sidebar table of contents component .

**Desired Situation**

Creation of the first iteration of the sidebar table of contents component .

![Screenshot from 2021-05-05 17-21-11](https://user-images.githubusercontent.com/44670961/117136680-54a28900-adc6-11eb-9a34-e0d7da0b1e23.png)

[Optional] **Additional context**

Refer to the sidebar table of components used here 
1) [Reference Sidebar Table of Contents Component](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/)
2) [Table of Contents Component](https://github.com/chromaui/learnstorybook.com/tree/master/src/components/screens/GuideScreen)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thank you, Chinmay!

**Comment by sgm28** [comment]
Good afternoon, how are you?

I would like to work on this issue. 
Before selecting me, please keep the follow things in mind:
I would have to learn how storyboard works, I would have to review react, and I would need time to learn how everything else is working together. The issue  might take me a month to resolve. I am newbie when it comes to working with open source code consider having patience with me. 

Never Give Up,
Sakar Michel

**Comment by chinmaym07** [comment]
That's a good practise @sgm28  .. Go Ahead ..I'll assign it to you .. Happy Contributing & Learning ..!!  😀 👍🏻 🚀 

If you face any issues do reach out to us on slack . We'll be more happy to help ..! 👍🏻 

Have you joined the Layer5 Community - http://slack.layer5.io? We have many helpful people out there always ready to help ..

**Comment by sgm28** [comment]
Dear @chinmaym07,

Good morning, how are you?
Thank you for giving me a chance.
Okay, I will reach out on slack if I have any issues.
No I haven't join the Layer5 community.
I will join it today.

Never Give Up,
Sakar Michel

**Comment by Nikhil-Ladha** [comment]
Hi @sgm28 how's the issue comyup? Any progress to share?

**Comment by sgm28** [comment]
@Nikhil-Ladha, good morning, how are you?
I did the following things:
-Completed reading section React ES6 https://www.w3schools.com/react/react_render.asp
-Install NodeJS
-Create first react app
-Using w3schools to learn react. The website can be found here https://www.w3schools.com/react/

**Comment by Nikhil-Ladha** [comment]
Hey @sgm28 , what's the progress on this issue? Would you be able to send out a PR by this Saturday?
We are tight on time, and need this to be tackled soon.
If you are unable to make it, please signal so that someone else can tackle this issue, and you can try out your hands on multiple other open issues.

**Comment by sgm28** [comment]
Dear @Nikhil-Ladha, 

I ran into a bug which I posted in the #random channel on slack. I can provide the link if necessary. Honestly, no. 
Yes someone else can be reassigned to this issue.

Never Give Up,
Sakar Michel

**Comment by kumar4790** [comment]
Hey, will it be done in reactjs?

**Comment by Nikhil-Ladha** [comment]
Will require gatsby mostly.
