### ISSUE TITLE
[Community] Member Profile: Hussaina Begum needed updated to "Maintainer"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1843]
**Current Behavior**
@hexxdump's [community member profile](https://layer5.io/community/members/hussaina-begum) has the `maintainer: yes` set, but the word "Contributor" is still shown under her name.

**Desired Situation**
"Maintainer, Mesheryctl" should be Hussaina's byline.

<img width="473" alt="Screen Shot 2021-05-05 at 10 52 40 AM" src="https://user-images.githubusercontent.com/7570704/117171260-55b8c380-ad90-11eb-9c23-c6625d1e0635.png">

---

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sachindavra** [comment]
I would like to work on this.

**Comment by adithyaakrishna** [comment]
@sachindavra Here's the directory to help you work on this, https://github.com/layer5io/layer5/tree/master/src/collections/members/hussaina-begum :)
