### ISSUE TITLE
[README] Update README Community Section

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#1844]
**Current Behavior**

The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Desired Situation**

Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"
![layer5io-layer5-Layer5-the-service-mesh-company-representing-every-service-mesh](https://user-images.githubusercontent.com/62059002/117326383-82043b00-ae89-11eb-99e3-2638521c1d5f.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by xdshivani** [comment]
I would like to work on it.

**Comment by Ruth-ikegah** [comment]
sure @xdshivani
