### ISSUE TITLE
[Discuss] Wrong Font-family on Header & Footer & Improve Login Modal 

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1851]
**Current Behavior**

1. The color scheme on Login Modal in [discuss.layer5.io](https://discuss.layer5.io/) does not match with the color scheme of layer5
2. Wrong font-family is used in header & footer in [discuss.layer5.io](https://discuss.layer5.io/)

**Desired Situation**

1. Update the color scheme on Login  Modal [discuss.layer5.io](https://discuss.layer5.io/)
2. Update the Font Family in header & footer 

---
[Optional] **Screenshots**

![image](https://user-images.githubusercontent.com/44670961/117665023-0aebe100-b1c0-11eb-8cd3-f186154ab78a.png)

![image](https://user-images.githubusercontent.com/44670961/117665106-20610b00-b1c0-11eb-93ab-f51b352b3b8c.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Liri-s29** [comment]
You want the colour scheme of the modal to be cyan?

**Comment by chinmaym07** [comment]
I think the whole modal needs to be updated according to the color scheme of Layer5 .
You can refer to [Layer5 Brand kit](https://layer5.io/company/brand) . Also refer to [Layer5 website](https://layer5.io/) . You'll get a clear idea of what changes are required on the login modal .

**Comment by Liri-s29** [comment]
Thank you for the guidance.
This is my first time working on large projects,
I'll do my best. Kindly review once I've made the changes and give me conments.

**Comment by chinmaym07** [comment]
Hey @Liri-s29 .. We are working on the design of the modal ..
As making changes without a design doesn't seem to be consistent. If we get a view of what we have to make , then we can make our work look neat & impressive .
I think we should wait for the design .. Once the design is ready & approved . Then I'll request you to go ahead & work on this issue ..

**Comment by chinmaym07** [comment]
Hey @Liri-s29 ... 👋🏻 
We have our design ready .. Would you like to work on this issue ?

**SignUp Modal**

![image](https://user-images.githubusercontent.com/44670961/117769785-c741b780-b251-11eb-82d2-a868cbb9fc7c.png)

**Login Modal**

![image](https://user-images.githubusercontent.com/44670961/117769834-d7599700-b251-11eb-9dc7-56c929959d8c.png)

Here's a link to design in figma.. 
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5982%3A13333
If you are unable to access the figma file ..  You are invited to jump into the Layer5 community here - http://slack.layer5.io and fill-in a member form - https://layer5.io/newcomer, You'll be granted access thereafter. 
Learn more about the Layer5 Community here - https://layer5.io/community

**Comment by Jashpatel1** [comment]
> @chinmaym07 Thank you.
> Yes, I would like to work on the Aussie. Can you help me with finding the directory of the https://discuss.layer5.io/?.

The project does not have directory. The changes are to be made on console in website itself. Ping me on slack if you are unable to find it.

**Comment by Jashpatel1** [comment]
Closing as issue if fixed.
