### ISSUE TITLE
[Discuss] Update Homepage

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1852]
**Current Behavior**

Homepage of [discuss.layer5.io](https://discuss.layer5.io/) is implemented according to the old design .

**Desired Situation**

Homepage of [discuss.layer5.io](https://discuss.layer5.io/) should be updated according to the new design .
  
![image](https://user-images.githubusercontent.com/44670961/117670771-d0854280-b1c5-11eb-92d7-cf14e0677afe.png)

[Optional] **Additional context**

Refer to [Figma file](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5039%3A6671) for the design 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Alenjojo** [comment]
can you assign me with this issue and share the latest design i'll try my best to redesign it

**Comment by Nikhil-Ladha** [comment]
I doubt we need this anymore @Jashpatel1 @leecalcote

**Comment by leecalcote** [comment]
@Nikhil-Ladha good call. Yes, we’re good to close this issue considering all the work done to complete it already.

**Comment by Nikhil-Ladha** [comment]
@Alenjojo thank you for showing interest, but we are already done with this issue now. You can check out other open issues to work upon.
