### ISSUE TITLE
[Discuss] Research migration of settings and custom header/footer/hero from one Discourse instance to another

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1853]
**Current State:**
https://discuss.layer5.io is in the process of being developed. It's current deployment is for purposes of development. It is deployed as a Docker container. Developed assets like the custom header, footer, hero section, and other plugin settings and site configuration needs to be migrated to a new production deployment.

**Research:**
Identify how each of the following can be migrated:
1. custom content: custom header, footer, hero section, fonts, style and logos
2. custom configuration: plugin settings and site configuration
3. categories (but none of the topics or comments)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Jashpatel1** [comment]
This can be closed, as the issue is resolved.
