### ISSUE TITLE
[Learn] Implement the "Courses" homepage

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1855]
**Current State:**
The Learn Layer5 site lacks a home page for the 'Courses' under a learning path, where all the courses would be listed out.

**Desired State:**
The 'Courses' home page needs to be implemented following this [Figma Deisgn](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5372%3A8479).
In the design, mentioned above the design for the 'Courses' would be the rectangular cards, where each card represents a course.
The list of courses should be fetched dynamically using GraphQl. The list of courses could be found [here](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-service-meshes-for-developers), please add dummy courses while making a PR like `course1`, `course2` and so on...
Also, please add a placeholder image on the left of each card. 

Attaching the screenshot for reference:
![Screenshot from 2021-05-10 22-12-50](https://user-images.githubusercontent.com/29438875/117694614-f833d500-b1dc-11eb-86fd-67c999f3f477.png)

The sidebar implementation is not needed.

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Check out the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by cemeiq** [comment]
@leecalcote I have filled the member form.

**Comment by Nikhil-Ladha** [comment]
Hi @cemeiq how is this issue coming up? Any progress to share?

**Comment by cemeiq** [comment]
@Nikhil-Ladha No. I might need some more time if that is okay with you?

**Comment by cemeiq** [comment]
@Nikhil I will be leaving this issue and try finding myself something else.

**Comment by Nikhil-Ladha** [comment]
No problem, @cemeiq . Once these bases are done we will soon be having smaller issues to take over. You can hop on them.

**Comment by imraghav20** [comment]
@Nikhil-Ladha does it need to be implemented at this URL [https://layer5.io/learn](https://layer5.io/learn) ?
The courses should be implemented in place of `Service Mesh Books`?

**Comment by Nikhil-Ladha** [comment]
No. We are developing a new subsite, layer5.io/learn and the effort for that is going on with layer5.io/learn-ng as rhe homepage. You can check the design spec and the figma file mentioned above for more details on how this page would be and it's potential path.

**Comment by Nikhil-Ladha** [comment]
If you have not joined the community yet, I would encourage you to do so and meet more like minded and talented people. Here is the link to our slack workspace: slack.layer5.io . Also, once joined do remember to fill out the newcomer form at layer5.io/newcomer in order to get access to resources including Figma.

**Comment by Ayush-Khandelwal-007** [comment]
Hey , if no one is working on it right now , can I work on this?
Also I don't have access to figma even though I have filled the newcomer form.

**Comment by Nikhil-Ladha** [comment]
Sure @Ayush-Khandelwal-007 . Check the mail for the figma invite. There will be few changes in this design though, and I am not sure if that's complete yet, @austinogiza any updates?

**Comment by Ayush-Khandelwal-007** [comment]
Yay, I got it!
Okay, I'll hold for now and will start as soon as it's finalised.
