### ISSUE TITLE
[Learn] Implement the Chapter Home Page

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1856]
**Current State:**
The current layer5-ng site doesn't have a dedicated home page for each of the courses within a learning path.
**Desired State:**
A home page component needs to be added, which renders the home page for a course depending upon the course and handled using GraphQl.
Design inspiration: [Storybook Guide Page](https://storybook.js.org/tutorials/intro-to-storybook/)
Reference Component: [Storybook Guide Component](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/screens/GuideScreen/index.js)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Check out the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Nikhil-Ladha** [comment]
@chinmaym07 I wonder this is something that you might knock out?

**Comment by chinmaym07** [comment]
As you say.. Aaye Aaye Captain .. I'll try to work on it ..!! @Nikhil-Ladha  😀 🚀
