### ISSUE TITLE
[Project] In the NightHawk project page there are following issue

### ISSUE THREAD

**Issue by samirparhi-dev** [layer5io/layer5#1857]
**Description**
The Text for 2 section are being cut-off.See the link Below

**Expected Behavior**

All the text should be visible

**Screenshots**

<img width="1286" alt="Screenshot 2021-05-11 at 11 20 01 AM" src="https://user-images.githubusercontent.com/59992800/117765080-12a49780-b24b-11eb-8bd0-ff6055756b5b.png">
<img width="1197" alt="Screenshot 2021-05-11 at 11 21 08 AM" src="https://user-images.githubusercontent.com/59992800/117765097-16d0b500-b24b-11eb-8cb7-853eb0213c79.png">
**Enviroment:**
- Host OS: MAC OS X
- Meshery Version: Latest
- Kubernetes Version: 1.18
- Browser: Chrome 

---

[Optional] **To Reproduce**
1. Go to 'https://layer5.io/projects/getnighthawk'
2. See error

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by ankingcodes** [comment]
@samirparhi-dev @leecalcote : The images seem to have been cropped at source. 
![58](https://user-images.githubusercontent.com/40923324/117954063-490a1180-b334-11eb-8cc6-d509a3a49f8a.PNG)

**Comment by Tanuj22** [comment]
Yes @ankingcodes we are in need of better images. Will update the issue when its available. Meanwhile do check out some of the other issues and also consider joining the Layer5 community here - http://slack.layer5.io :)

**Comment by warunicorn19** [comment]
has this issue been solved?? if it hasn't, can i work on this?

**Comment by Tanuj22** [comment]
> has this issue been solved?? if it hasn't, can i work on this?

No it hasn't. We are still at the problem I mentioned in the above comment 😬

**Comment by warunicorn19** [comment]
Yeah but since the comment is from 2 months ago, I thought of checking😅

**Comment by warunicorn19** [comment]
@Tanuj22 we need better images so that we can close this issue, what do you think we should do?

**Comment by collab456** [comment]
@samirparhi-dev this is my very first try and would like to work on this, can I take this up?

**Comment by warunicorn19** [comment]
@collab456 you could work on this once we decide what images to use, we'll bring this up in the websites call on Monday. I'll keep this assigned to you so that you could work on this in the future.
