### ISSUE TITLE
[Programs] Add "Back to Programs" button

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1859]
**Current Behavior**
The individual open source internship pages (e.g.https://layer5.io/programs/gsoc/2019) do not have a Back to Programs button to help the user navigate back to the main programs page (https://layer5.io/programs).

#### Desired Behavior
A back button is present like that of the one on this page - https://layer5.io/community/members/jash-patel

<img width="165" alt="Screen Shot 2021-05-15 at 11 13 03 AM" src="https://user-images.githubusercontent.com/7570704/118370712-9b367700-b56e-11eb-865e-e16865ec7842.png">

**Screenshots / Mockups**

<img width="1222" alt="Screen Shot 2021-05-15 at 11 09 32 AM" src="https://user-images.githubusercontent.com/7570704/118370715-9d98d100-b56e-11eb-8ff9-acbbdd5c2d48.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by wise-introvert** [comment]
If this hasn't been taken up by someone yet, I'll love to take a stab at it. Is that fine?

**Comment by adithyaakrishna** [comment]
@amino19 would you like to try this? 👀

**Comment by amino19** [comment]
Sure Sir!
You can assign me for this..

Thanks for asking!  : )

**Comment by amino19** [comment]
Done with changes to add Back Button, Pl verify!
