### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by amino19** [layer5io/layer5#1861]
**Current Behavior**

Require some changes in Readme.md over Community and Contributing section.
**Details :**

![tempsnip](https://user-images.githubusercontent.com/75872316/118589124-6704c580-b7bd-11eb-9255-629caa676326.png)

**Desired Situation**

- 1st box : Need two different links to be open, by clicking on "community drive" & "Community Member Form" separately.
- 2nd box : Need to configure texts correctly.

##### (Follow the <a href="https://github.com/layer5io/meshery/blob/master/README.md">reference</a>, if required.)
---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Ideal phrasing for the last bullet point:

```
✔️ <em><strong>Watch</strong></em> community <a href="https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0">meeting recordings</a>.<br />
```

**Comment by Nikhil-Ladha** [comment]
> 1st box : Need two different links to be open, by clicking on "community drive" & "Community Member Form" separately.
Two different links are not required here. The test `Community Member Form` should only have a link., and the other text `community drive` should be under the previous element `<strong>`

**Comment by soham4abc** [comment]
Did make a PR please see to it!
