### ISSUE TITLE
[Learn] Rectify Box-Shadow on Service Mesh Books Page

### ISSUE THREAD

**Issue by chinmaym07** [layer5io/layer5#1863]
**Current Behavior**

Box-shadow around book cards is intersecting other cards on [Service Mesh Books Page](https://layer5.io/learn/service-mesh-books)

---

**Desired Situation**

Rectify the Box-shadow property on book cards.

---
**Screenshots**

![Screenshot_2021-05-18 Service Mesh Books](https://user-images.githubusercontent.com/44670961/118686489-ab29b180-b821-11eb-9c07-bd294b273269.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by nandirishav** [comment]
Please  give me the opportunity to work on this.

**Comment by leecalcote** [comment]
Sounds good, @nandirishav 👍
