### ISSUE TITLE
[Careers] Update Open Source Internships Program Page

### ISSUE THREAD

**Issue by cemeiq** [layer5io/layer5#1864]
**Description**
On the open source internships program page (https://layer5.io/careers/programs), there are individual years broken out for some of the programs.

**Expected Behavior**
Have only one card per program with each year being a sub-collection under the main card. Links to prior years/prior quarters can be included on the specific program page.

**Screenshots**

<img width="1991" alt="open_source_internships" src="https://user-images.githubusercontent.com/16964361/118689919-6d1b9600-b7ff-11eb-82a5-2d6ac357e617.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Awesome. 👍

**Comment by cemeiq** [comment]
@hdck007 yes you can take this.
