### ISSUE TITLE
[Learn] Fetch the card details using GraphQL query on Learn homepage

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1866]
**Current State:**
The cards on the homepage of the upcoming learn site, i.e, the one at layer5.io/learn-ng shows a status course count.

**Desired State:**
The course count should be fetched dynamically using GraphQl. For reference, check out the usage in these components [Index](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/screens/IndexScreen/index.js), [Guide](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/screens/IndexScreen/Guide.js) and [GuidesCard](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/screens/IndexScreen/Guides.js).

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Nikhil-Ladha** [comment]
@vinayaksh42 a small one that you could start off with.

**Comment by vinayaksh42** [comment]
@Nikhil-Ladha sure

**Comment by Nikhil-Ladha** [comment]
@vinayaksh42 any updates?

**Comment by vinayaksh42** [comment]
> @vinayaksh42 any updates?

Hey @Nikhil-Ladha, I won't be able to contribute to this issue because of other engagements.

**Comment by Nikhil-Ladha** [comment]
No problem @vinayaksh42 . Thanks for the heads-up 👍🏼

**Comment by kaushambisharma** [comment]
I'd like to take up this issue.

**Comment by Nikhil-Ladha** [comment]
Sure @kaushambisharma . Please go ahead with it.

**Comment by sudo-NithishKarthik** [comment]
@kaushambisharma , are you working on this issue ?

**Comment by kaushambisharma** [comment]
@sudo-NithishKarthik hey, I was planning on working on the issue after other personal deadlines, you can take the issue.

**Comment by Nikhil-Ladha** [comment]
Thanks for the heads-up @kaushambisharma .
@sudo-NithishKarthik I guess the field is open for you to play :)

**Comment by sudo-NithishKarthik** [comment]
Ya sure :)
