### ISSUE TITLE
[Learn] Add Course, Chapter count component on Learn homepage

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1867]
**Current State:**
The learn homepage i.e the page at layer5.io/learn-ng misses a component that should highlight the Courses, chapters, service-meshes count.

**Desired State:**
The required component needs to be added which highlights the courses, chapters, service-meshes count. These values should be fetched dynamically using graphql.
Reference component: [SiteStat](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/screens/IndexScreen/SiteStats.js)

**Expected Design**
![Screenshot from 2021-05-18 23-59-32](https://user-images.githubusercontent.com/29438875/118705180-8a6b5700-b835-11eb-8baa-16294bce5321.png)

Link to [figma design](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=6090%3A13552)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Nikhil-Ladha** [comment]
@cemeiq I wonder if you might wanna knock out this one? This is a small issue.

**Comment by cemeiq** [comment]
@Nikhil-Ladha Yes its a small issue but I am already working on another one https://github.com/layer5io/layer5/issues/1864. Maybe someone else can take this issue. I am trying to understand graphql by going through some tutorials etc at the moment.

**Comment by Nikhil-Ladha** [comment]
Ohh great. Thanks for the heads up 👍🏼

**Comment by adithyaakrishna** [comment]
@Gautam-Arora24 Willing to work on this? 👀

**Comment by Nikhil-Ladha** [comment]
Once you signal yes here @Gautam-Arora24 , the issue goes under your name 💪🏼

**Comment by Gautam-Arora24** [comment]
I would go ahead with this issue :)

**Comment by Nikhil-Ladha** [comment]
Awesome 👍🏼 @Gautam-Arora24 , here you go..
