### ISSUE TITLE
[Community] Member Profile: Otto Van Der Schaaf

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#1869]
**Current Behavior**

@oschaaf has been a consistent contributor, community member, and maintainer of Service Mesh Performance.

**Desired Situation**
Let's recognize @oschaaf as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @oschaaf
- Twitter: @oschaaf
- LinkedIn:  https://www.linkedin.com/in/oschaaf
- Link to profile picture: https://avatars.githubusercontent.com/u/2239556?v=4
- Short Bio: interested in proxies, meshes, and performance. Nighthawk maintainer @envoyproxy. PageSpeed (incubating) committer and IPMC member @apache. Principal Envoy Engineer at Red Hat.

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by hdck007** [comment]
I will be happy to do this @leecalcote @Ruth-ikegah

**Comment by chinmaym07** [comment]
Go ahead .. Happy Contributing @hdck007 !! 🚀  assigned to you !!
