### ISSUE TITLE
Update the social share image for this layer5.io/projects

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1877]
**Current Behavior**
The current social share image for the layer5.io/projects is old and does not display all the projects.

**Desired Situation**
Update a new social share image for layer5.io/projects
The New image exists in [this doc](https://docs.google.com/presentation/d/1tLcMcyQ-Z6YYISYyR0Eyb30dojQiKHIjs7Rt5m8kcag/edit#slide=id.gd979a305bd_0_0)

---
**Screenshots of issue**
![Screenshot 2021-05-24 at 14 27 05](https://user-images.githubusercontent.com/62384659/119354558-2107a000-bc9c-11eb-85e3-68b02f17c1a5.png)

The old image exists in [this workflow](layer5/static/images/layer5-projects.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by toth2000** [comment]
Can I work on this issue?

**Comment by Gautam-Arora24** [comment]
Can I work on this? 🙂

**Comment by Anita-ihuman** [comment]
Yes, sure

**Comment by leecalcote** [comment]
It's working. 😄 https://www.linkedin.com/post-inspector/inspect/http:%2F%2Flayer5.io%2Fprojects
