### ISSUE TITLE
[Nav Bar] CTA: "Run Meshery" button

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1884]
**Current Behavior**
The navigation bar doesn't have a main call to action button.

**Desired Behavior**
Add a "Run Meshery" button to the upper righthand corner of the site.

**Screenshots / Mockups**

<img width="1440" alt="navbar" src="https://user-images.githubusercontent.com/7570704/119925235-a7d9a880-bf3a-11eb-9c5c-300ec141f6b8.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Ooooh, @Nikhil-Ladha...

**Comment by Nikhil-Ladha** [comment]
Finally, we have decided to keep "Meshery" CTA 😄

**Comment by leecalcote** [comment]
Some folks at HPE said, “I didn’t know Layer5 had Meshery.” Doh!

**Comment by Nikhil-Ladha** [comment]
> Some folks at HPE said, “I didn’t know Layer5 had Meshery.” Doh!

What the.....😂
