### ISSUE TITLE
[Website] Improve "bash" command area UI

### ISSUE THREAD

**Issue by alphaX86** [layer5io/layer5#1886]
**Description**
The site (https://layer5.io/meshery) provides great instructions to run meshery but the UI can be improved on the command box side, especially on bash command area

**Screenshots**

![image](https://user-images.githubusercontent.com/59508546/119935211-be1c4e80-bfa4-11eb-99ad-633a6ee00d3d.png)

![image](https://user-images.githubusercontent.com/59508546/119935221-c4122f80-bfa4-11eb-80cf-1a4636068e6f.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Nikhil-Ladha** [comment]
The terminal box is intended, to be _partly_ hidden for smaller resolutions.
And, what's the updated curl command?

**Comment by Nikhil-Ladha** [comment]
For me, it is completely visible.....my resolution is 1920x1080

**Comment by alphaX86** [comment]
> The terminal box is intended, to be _partly_ hidden for smaller resolutions.
> And, what's the updated curl command?

Lee told to update or fix the command. And IG, it's with the one on Meshery.io

**Comment by alphaX86** [comment]
> For me, it is completely visible.....my resolution is 1920x1080

Hmm... But the UI can be slightly improved. We just talked yesterday and he said about this.... 🤐🤐🤐... Wait I'll ping @leecalcote here... I guess I opened issue under wrong topic!

**Comment by alphaX86** [comment]
Ma bad.... Changing topic @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
> Oh one sec... It's about bash command area! He felt that it can be improved

Okay, which area and what exactly has to be improved?

**Comment by alphaX86** [comment]
![image](https://user-images.githubusercontent.com/59508546/119970869-e2d8ec00-bfcd-11eb-8b1d-a724c7ee4955.png)

**Comment by alphaX86** [comment]
@leecalcote seems I made silly confusions.... could you describe what it needs to be done 🙃

**Comment by sudo-NithishKarthik** [comment]
I can try this out if someone could tell what exactly has to be done 😅

**Comment by alphaX86** [comment]
> I can try this out if someone could tell what exactly has to be done 😅

@leecalcote will explain in detail what needs to be done. But as far as concerned it's the bash command area that needs to be improved in terms of UI.

**Comment by leecalcote** [comment]
@sudo-NithishKarthik, I'll grab you in chat to verbally review.

**Comment by adithyaakrishna** [comment]
@manish-ai 👀

**Comment by bariqhibat** [comment]
I can help take a look into this!

**Comment by alphaX86** [comment]
@bariqhibat that's awesome! Oh and if you're struck ask Lee about this, he'll guide you through 👍

**Comment by bariqhibat** [comment]
Hey @alphaX86, Lee told me that it seems like we can close this issue. Thanks!

**Comment by leecalcote** [comment]
Thank you all. Let's close this one out. It was originally opened to address line cutoff issues and an incorrect syntax.
