### ISSUE TITLE
Links do not have a hovering effect

### ISSUE THREAD

**Issue by sayantan1413** [layer5io/layer5#1891]
**Description**

The privacy and terms links beside the copyright section are not having the hovering effect.

**Expected Behavior**

The privacy and terms links should have a hovering effect.

**Screenshots**

<img width="664" alt="Screenshot 2021-05-30 at 11 30 50 PM" src="https://user-images.githubusercontent.com/64970095/120115064-ac52cb00-c19f-11eb-9b5c-e0aa2a85b544.png">

**Enviroment:**
- Host OS: Any
- Meshery Version: Any
- Kubernetes Version: Any
- Browser: Any

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sayantan1413** [comment]
Hey @leecalcote I would like to work on this issue.

**Comment by leecalcote** [comment]
Wonderful. Thank you, @sayantan1413
