### ISSUE TITLE
[Community] Member Profile: Ayush Khandelwal

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1892]
**Current Behavior**

@Ayush-Khandelwal-007 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Ayush-Khandelwal-007 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Ayush-Khandelwal-007
- Twitter: N/A
- LinkedIn: ayush-khandelwal-741a88194
- Link to profile picture: https://drive.google.com/file/d/1wGvGN0uV_FLBKtT5At9fclXlaGiHyADD/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sayantan1413** [comment]
Hey @leecalcote I would like to work on this issue.

**Comment by Ayush-Khandelwal-007** [comment]
Here you go @sayantan1413 .

**Comment by sayantan1413** [comment]
Thanks @Ayush-Khandelwal-007 for assigning this issue to me.

**Comment by sayantan1413** [comment]
Hey @leecalcote @Ayush-Khandelwal-007 Can you tell me what should I write in the **BLURB** and **Badges** section  ?

**Comment by adithyaakrishna** [comment]
Congrats @Ayush-Khandelwal-007 🎉

**Comment by Ayush-Khandelwal-007** [comment]
Thank you @adithyaakrishna
