### ISSUE TITLE
[Discuss] Nav bar not mobile-friendly

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1893]
**Description**
The https://discuss.layer5.io site's navbar is not responsive.

**Expected Behavior**
Nav bar should adjust in size to accommodate mobile visitors.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by debjani1413** [comment]
Hey, @leecalcote I would like to work on this issue.

**Comment by claire-me** [comment]
@leecalcote I would like to fix the issue. Can you assign me this?

**Comment by sayantan1413** [comment]
Here you go @claire-me 😎

**Comment by leecalcote** [comment]
Hi @claire-me, if you would like any assistance or would like to engage in the community, please join: https://slack.layer5.io

**Comment by debo19** [comment]
Hey @claire-me , can i partner up with you on this issue? I would like to give it a try.

**Comment by claire-me** [comment]
Yes, you can @debo19

**Comment by sayantan1413** [comment]
That's great @claire-me I am assigning the issue to @debo19 also so that you can pair up and solve it together. 🚀

**Comment by debo19** [comment]
Thanks @sayantan1413 :)

**Comment by devartstar** [comment]
Hi is this issue being worked upon. If not I would like to contribute to this.

**Comment by warunicorn19** [comment]
Hey @devartstar, this issue has actually already been fixed🙂.

**Comment by devartstar** [comment]
okay @warunicorn19 , thanks for confirming.
