### ISSUE TITLE
[Discuss] Footer not mobile-friendly

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1894]
**Description**
The https://discuss.layer5.io site's footer is not responsive.

**Expected Behavior**
Footer should adjust in size to accommodate mobile visitors. See layer5.io for an example.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Gautam-Arora24** [comment]
Working on this!

**Comment by leecalcote** [comment]
Wonderful. 👍

**Comment by leecalcote** [comment]
Any luck so far, @Gautam-Arora24? What's your approach to solving this one?

**Comment by sumeetweb** [comment]
I think we need to add the CSS media queries from layer5.io into discuss.layer5.io
The footer style of layer5.io is in here: 
https://github.com/layer5io/layer5/blob/master/src/sections/General/Footer/footer.style.js

**Comment by sumeetweb** [comment]
for changing css in discuss.layer5.io, ig admin permissions are required or an admin will need to apply this change.

**Comment by adithyaakrishna** [comment]
// @Jashpatel1

**Comment by Jashpatel1** [comment]
> for changing css in discuss.layer5.io, ig admin permissions are required or an admin will need to apply this change.

You can make the changes in [https://staging-discuss.layer5.io/](https://staging-discuss.layer5.io/) .  Let me know once you create an account there, will provide you with admin access.

**Comment by sumeetweb** [comment]
> > for changing css in discuss.layer5.io, ig admin permissions are required or an admin will need to apply this change.
> 
> You can make the changes in https://staging-discuss.layer5.io/ . Let me know once you create an account there, will provide you with admin access.

👍  Done. Created an account on staging with username sumeetweb

**Comment by sumeetweb** [comment]
Got it thanks.

**Comment by warunicorn19** [comment]
hey, i see that no one is assigned this issue right now, can i try to work on this?

**Comment by sayantan1413** [comment]
Yeah sure! here you go @warunicorn19.

**Comment by warunicorn19** [comment]
Thanks! @sayantan1413

**Comment by leecalcote** [comment]
Sounds good. @warunicorn19, you'll want to start by creating a user account on https://staging-discuss.layer5.io and signaling to @Jashpatel1 or @sayantan1413, so that they might elevate your user privileges to make and test these changes. From there, you can have these changes reviewed and approved for moving to https://discuss.layer5.io.

**Comment by leecalcote** [comment]
If you're not already part of the Layer5 Community, I encourage you to join, so that you can better engage with @Jashpatel1, @sayantan1413, and the rest of the contributors - https://layer5.io/community/newcomers.

**Comment by warunicorn19** [comment]
Hey @leecalcote , I've already done everything, just waiting for @Jashpatel1 to give me access.

**Comment by sumeetweb** [comment]
I got some issues with CSS not being applied in discourse admin. You can go through [this link](https://meta.discourse.org/t/how-to-make-css-changes-on-your-site/168101), which I followed as I was new to discourse. I hope you will be able to fix this issue.

**Comment by warunicorn19** [comment]
Okay thanks @sumeetweb

**Comment by warunicorn19** [comment]
@Jashpatel1 should we close this issue?

**Comment by adithyaakrishna** [comment]
@warunicorn19 Is this resolved?
Bc I can still see that there are some issues with the footer

![Screenshot_20210805-122632](https://user-images.githubusercontent.com/23498248/128305571-414fc358-e4df-4e24-bdbe-96bfdb6981ea.jpg)

**Comment by warunicorn19** [comment]
@adithyaakrishna check on staging-discuss 😅.

**Comment by Abhijay007** [comment]
@leecalcote @warunicorn19 I want to work on this issue !! , can you please assign me this

**Comment by Abhijay007** [comment]
> @leecalcote @warunicorn19 I want to work on this issue !! , can you please assign me this

![image](https://user-images.githubusercontent.com/64387054/146668141-1779af63-abc5-4b6c-8465-4140ae229d58.png)


it is resolved?  @warunicorn19 can you please tell me what do you mean by  "staging-discuss", is it a branch or something?

**Comment by leecalcote** [comment]
@Abhijay007 the staging server has been turned down. Please make your attempt at a fix separately. Here is where you can find the source for the discuss footer: https://github.com/layer5io/layer5/tree/master/src/assets/discuss

**Comment by Abhijay007** [comment]
> @Abhijay007 the staging server has been turned down. Please make your attempt at a fix separately. Here is where you can find the source for the discuss footer: https://github.com/layer5io/layer5/tree/master/src/assets/discuss

Ok, thanks for sharing resources I will try my best to fix this !!
