### ISSUE TITLE
Capitalize “M” in Mate (as in MeshMates )

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1901]
**Current Behavior**
The references to the word **MeshMate**  have the M in  Mate in small letter.

**Desired Situation**

All references to MeshMates on this site should have the “M” in Mate capitalized.
https://layer5.io/community/meshmates 
![Screenshot 2021-06-03 at 15 31 15](https://user-images.githubusercontent.com/62384659/120663472-f5499e80-c481-11eb-94af-e677021406bd.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by visa-8** [comment]
Hi, 

I am new to GitHub contributions. I would like to work on this issue. It would be great if you could assign this issue to me.

Thanks,
Visa

**Comment by Ayush-Khandelwal-007** [comment]
Here you go @visa-8 ! 😄

**Comment by visa-8** [comment]
Hi, please help!
I am trying to run the code locally and i gave the command "make site" and got the following error. 
npm ERR! node v14.17.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! Layer5@1.0.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Layer5@1.0.0 start script 'npm run develop'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Layer5 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run develop
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Layer5
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Layer5

**Comment by sayantan1413** [comment]
Hey @visa-8 please [join the community](layer5io.slack.com) and join the #newcomers channel and post your query so that someone who faced this issue earlier can help you.

**Comment by sayantan1413** [comment]
Hi @hrishikeshnikam2000, yes. Please jump into the [community Slack](http://slack.layer5.io/) and we'll get you setup.

**Comment by sayantan1413** [comment]
hey @visa-8 please [join the slack](http://slack.layer5.io/) channel and someone will help you to set up.

**Comment by CYBER-BRIX** [comment]
hey, I'm a new contributor and I would like to work on this issue can you help me getting started.
thanks

**Comment by sayantan1413** [comment]
Hey @CYBER-BRIX I think someone is already working in this issue. But don't worry you can find other good first issues and please join our [slack channel](http://slack.layer5.io/) we will help you to setup.

**Comment by CYBER-BRIX** [comment]
Your slack channel is showing some kind of error can you send me the link?

**Comment by sayantan1413** [comment]
Hey @CYBER-BRIX I have updated the link can you verify it?

**Comment by CYBER-BRIX** [comment]
It's showing this.

**Comment by sayantan1413** [comment]
> Hey @CYBER-BRIX I think someone is already working in this issue. But don't worry you can find other good first issues and please join our [slack channel](https://join.slack.com/t/layer5io/shared_invite/zt-q9u1o3kj-78c57c~MDNTf1RudBTfmNg/) we will help you to setup.

I think now this link should work fine.

**Comment by debjani1413** [comment]
Hey, @CYBER-BRIX the link has been updated by @sayantan1413 , 

> Hey @CYBER-BRIX I think someone is already working in this issue. But don't worry you can find other good first issues and please join our [slack channel](https://join.slack.com/t/layer5io/shared_invite/zt-q9u1o3kj-78c57c~MDNTf1RudBTfmNg/) we will help you to setup.

Hey @CYBER-BRIX the link has been updated by @sayantan1413 here ☝️☝️☝️ please click on it and join our slack channel, for more support !

**Comment by CYBER-BRIX** [comment]
> Hi, please help!
> I am trying to run the code locally and i gave the command "make site" and got the following error.
> npm ERR! node v14.17.0
> npm ERR! npm v3.10.5
> npm ERR! code ELIFECYCLE
> npm ERR! Layer5@1.0.0 start: `npm run develop`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the Layer5@1.0.0 start script 'npm run develop'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the Layer5 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! npm run develop
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR! npm bugs Layer5
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! npm owner ls Layer5

Hey,are you stuck with this issue,maybe i can help?

**Comment by visa-8** [comment]
Hi @CYBER-BRIX, yes I am still stuck with the issue. Could you please help?

**Comment by mdahwireng** [comment]
Hello! I want to give it a try

**Comment by CYBER-BRIX** [comment]
it appears to me that you haven't installed nodejs to check go in cmd and
type node -v and after that npm -v

**Comment by visa-8** [comment]
I did install node and npm. Command node -v gives v14.17.0 and npm -v gives v3.10.5

**Comment by CYBER-BRIX** [comment]
Have you tried asking this on layer5's slack channel?

**Comment by visa-8** [comment]
I did long back. Will do it again. One question - From which directory are you giving the command "make setup-libs" to build the site locally?

**Comment by visa-8** [comment]
What is the npm version that needs to be installed? My PC has V 3.10.5 but looks like the latest version is 6.14.13? Any inputs?

**Comment by Tanuj22** [comment]
@visa-8 that should work

**Comment by CYBER-BRIX** [comment]
you should definitely update it ..
