### ISSUE TITLE
[Community] Member Profile: Gautam Arora

### ISSUE THREAD

**Issue by dhruv0000** [layer5io/layer5#1904]
**Current Behavior**

@Gautam-Arora24 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@Gautam-Arora24> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Gautam-Arora24 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by dhruv0000** [comment]
@Gautam-Arora24 Congrats :tada: 
Please do give a short bio for your profile and also your Handles.

**Comment by Gautam-Arora24** [comment]
Bio - I am an undergraduate student at G.L Bajaj Institute of Technology and Management. I am interested into web technologies. I am proficient in MERN stack along with GraphQL and Apollo client. I am very much interested to learn DevOps.

Twitter handle - Gautamarora24

**Comment by sayantan1413** [comment]
I would like to work on this issue.

**Comment by Gautam-Arora24** [comment]
Here you go @sayantan1413 :)

**Comment by sayantan1413** [comment]
@Gautam-Arora24 Please provide a profile picture link.

**Comment by Gautam-Arora24** [comment]
Kindly check your DM in slack

**Comment by sayantan1413** [comment]
Sure!
