### ISSUE TITLE
[Community] Member Profile: Elizabeth Meshioye

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1909]
**Current Behavior**

@Lezette has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Lezette as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Lezette
- Twitter: ilizette7
- LinkedIn: elizabeth-lola
- Link to profile picture: https://drive.google.com/drive/folders/1qUCMYDaQQkuJ-Btbxf1Yw2Wh22SlWiPL
- Short Bio: I am a frontend developer and Open Source enthusiast currently using react and nuxt to build web-accessible and user-friendly websites. I also enjoy writing technical articles. I spend my weekends reading other people's codes or daydreaming.
- Location: Lagos, Nigeria

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by jeantiston** [comment]
Hello! I'd love to start contributing. If no one is working on this yet, I can try to do it.

**Comment by Anita-ihuman** [comment]
Please go ahead.

**Comment by jeantiston** [comment]
Thank you @Anita-ihuman. And thanks for sharing the profile photo with me. Are there any badges that I need to add to @Lezette's profile?

**Comment by Anita-ihuman** [comment]
Not at the moment, but subsequently maybe.
