### ISSUE TITLE
[Community] Member Profile: Joy Nwaiwu

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1911]
**Current Behavior**

@JoyNwaiwu has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @JoyNwaiwu as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @JoyNwaiwu
- Twitter: JoyNwaiwu2
- LinkedIn: joy-nwaiwu-bb3b87177
- Link to profile picture: https://drive.google.com/file/d/1GqQRoBEUqD95Ek0H35-wypWJH8i1SX_O/view?usp=sharing
- About: Joy Nwaiwu is a technical writer, open-source enthusiast and software developer. She is goal-driven with a passion for creating and applying technologies to solve human challenges through well-thought-out solutions. She is stoked about learning new concepts, reading or binge-watching movies in her spare time.
- Location: Port Harcourt, Nigeria 

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by ishitakeshawani** [comment]
@Anita-ihuman I wanted to start contributing to projects. So this issue will be helpful to start. Can you assign me for this issue? I want to solve this.

**Comment by sayantan1413** [comment]
Here you go @ishitakeshawani :)

**Comment by Anita-ihuman** [comment]
Sure @ishitakeshawani please go ahead.

**Comment by ishitakeshawani** [comment]
Thank You @sayantan1413 @Anita-ihuman

**Comment by Tanuj22** [comment]
@ishitakeshawani any updates here?

**Comment by ishitakeshawani** [comment]
@Tanuj22 this issue is very easy but I am facing problems in the project setup.
But I will do it soon.

**Comment by Anita-ihuman** [comment]
Alright.
