### ISSUE TITLE
[Community] Member Profile: Rudraksh Pareek

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1916]
**Current Behavior**

@DelusionalOptimist has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @DelusionalOptimist as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: DelusionalOptimist
- Twitter: Del_Optimist
- LinkedIn: rudraksh-pareek
- Link to profile picture: https://media-exp1.licdn.com/dms/image/C5103AQGuolflyAvO1w/profile-displayphoto-shrink_200_200/0/1581578057823?e=1622073600&v=beta&t=zCCRnaDveJe4onPWVRS0H2xd_kcbcqnKno-QduOrlRU

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by DelusionalOptimist** [comment]
Thanks for this!!! :heart_eyes:
Just a minor correction. The profile picture URL seems to be broken. Please use this instead: https://drive.google.com/file/d/1_kpD1LMzGj3tn4chP-opiu2PJr7XxaYw/view?usp=sharing

**Comment by kaushambisharma** [comment]
I'd like to work on this issue.

**Comment by Jashpatel1** [comment]
Sure, please go ahead

**Comment by kaushambisharma** [comment]
@DelusionalOptimist I'd like some help with the Bio for creating the profile.

**Comment by DelusionalOptimist** [comment]
Sure @kaushambisharma, here you go :slightly_smiling_face: :
I'm an undergrad from India studying Computer Science and Engineering. I like to explore systems and networking and have a keen interest in working on cloud native technologies. I love learning by working on open source software and getting involved with the awesome communities around it.
