### ISSUE TITLE
[Community] Member Profile: Pranav Bhatt

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1917]
**Current Behavior**

@pranav-bhatt  has been a consistent contributor and community member.

**Desired Situation**

Let's recognize <@pranav-bhatt  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: pranav-bhatt 
- Twitter: 
- LinkedIn: pranav--bhatt
- Link to profile picture: https://drive.google.com/file/d/1_zp_z_vSY_iNTiI4qgEzHtQOu4FQ1oUK/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by kaushambisharma** [comment]
I'd like to work on this issue.

**Comment by Jashpatel1** [comment]
> I'd like to work on this issue.

Sure, please go ahead.

**Comment by kaushambisharma** [comment]
@pranav-bhatt  I'd like some help with the Bio for creating the profile.

**Comment by pranav-bhatt** [comment]
@kaushambisharma sure hmu on slack

**Comment by Jashpatel1** [comment]
Closed with #1926
