### ISSUE TITLE
[Discuss] Twitter Feeds

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1918]
**Current Behavior**

The community has three twitter accounts:

- https://twitter.com/layer5
- https://twitter.com/mesheryio
- https://twitter.com/smp_spec

**Desired Behavior**
Consider embedding of a Twitter feed (e.g. https://meta.discourse.org/t/communities-with-embedded-twitter-feeds/133962):

- the Layer5 feed on the main page
- the Meshery feed on the Meshery category
- the SMP feed on the Service Mesh Performance and GetNighthawk categories

**Implementation**
- use https://staging-discuss.layer5.io as the test system

**Screenshots / Mockups**

<img width="1239" alt="Screen Shot 2021-06-09 at 6 28 31 PM" src="https://user-images.githubusercontent.com/7570704/121442382-3134a600-c951-11eb-902c-21f74aa386da.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by rustmn** [comment]
Hi! I can do this. But there is at least 4 ways how to get Twitter feed that come in mind:

1. Public Twitter API (requires approved Twitter developer account, registered Twitter app);
2. Get RSS-feed via 3-d party services and convert into JSON (needs RSS-parser, at least 11kb minified + gzipped);
3. Get Twitter feed via 3-d party services that send json (I don’t know any stable service that would have lived for at least a couple of years);
4. Build own parser;

So, is there a backend service / SE functions repository for hosting this function or it should be implemented on Frontend? 

From FE side it could be a react component that retrieves and renders required Twitter feed based on current route / something else, if you wish.

**Comment by adithyaakrishna** [comment]
This would be a great addition 💯 🎉

**Comment by leecalcote** [comment]
Hi @rustmn! I missed your message earlier. Thanks for engaging here. I suppose we have the first method in mind with a relatively straight-forward embedded timeline. There is an approved developer account with registered Twitter app and credentials loaded into both the production discourse site (discuss.layer5.io) and a staging discourse site (http://staging-discuss.layer5.io). If you'll sign up for an account on the staging site, we'll see that it receives elevated privileges so that you can go about fiddling with embedding a timeline, if you like.

As you move forward here, you might like to hop into the Layer5 Community Slack (https://slack.layer5.io) to engage with @Jashpatel1 and/or @adithyaakrishna to the extent that you bump into issues. 👍

**Comment by Jashpatel1** [comment]
@rustmn This could be of some help: https://meta.discourse.org/t/communities-with-embedded-twitter-feeds/133962/1

**Comment by rustmn** [comment]
> Hi @rustmn! I missed your message earlier. Thanks for engaging here. I suppose we have the first method in mind with a relatively straight-forward embedded timeline. There is an approved developer account with registered Twitter app and credentials loaded into both the production discourse site (discuss.layer5.io) and a staging discourse site (http://staging-discuss.layer5.io). If you'll sign up for an account on the staging site, we'll see that it receives elevated privileges so that you can go about fiddling with embedding a timeline, if you like.
> 
> As you move forward here, you might like to hop into the Layer5 Community Slack (https://slack.layer5.io) to engage with @Jashpatel1 and/or @adithyaakrishna to the extent that you bump into issues. 👍

Got it, thanks. I'll do it ASAP.

**Comment by Jashpatel1** [comment]
@rustmn Is the plugin ready to be added on prod deployment?

**Comment by rustmn** [comment]
> @rustmn Is the plugin ready to be added on prod deployment?

Plugin is written but not ready for production because I didn't recieve API keys for Twitter. I asked @leecalcote and you for them several times in Slack and didn't get them.

Currently plugin written based on response from API endpoint described here: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline. 

I don't know, you can add plugin yourself, add API keys in it settings and test it.
