### ISSUE TITLE
[Events] Meetings: Capitalize "t" in YouTube 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1919]
**Description**
This page https://layer5.io/community/calendar#meetings needs the "t" in Youtube capitalized.

**Screenshots**
<img width="208" alt="Screen Shot 2021-06-09 at 6 41 05 PM" src="https://user-images.githubusercontent.com/7570704/121443052-68578700-c952-11eb-8369-f484b364d224.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by iambami** [comment]
I'd like to take this Lee
