### ISSUE TITLE
[Discuss] Add forum icon to set of social icons in the site footer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1920]
**Current Behavior**
The Layer5 Community Forum is now live and needs links to it propagated across layer5.io.

**Desired Behavior**
A link to this forum inserted into the footer is one such desirable place.

**Screenshots / Mockups**

- icon: https://upload.wikimedia.org/wikipedia/commons/1/17/Discourse_icon.svg
- mockup: ![discourse_bw](https://user-images.githubusercontent.com/7570704/121444210-ab1a5e80-c954-11eb-902d-30c2f3050c9b.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by DARK-art108** [comment]
Can I work upon this @leecalcote ?

**Comment by Jashpatel1** [comment]
> Can I work upon this @leecalcote ?

Yaa sure, please go ahead.

**Comment by Jashpatel1** [comment]
@DARK-art108 Just a small addition. Can you also add Discuss subheading under the Community heading in Footer

<img width="1267" alt="Screenshot 2021-06-10 at 10 24 41 AM" src="https://user-images.githubusercontent.com/43696490/121496057-bd010d80-c9f7-11eb-88ed-795bf321c50b.png">
