### ISSUE TITLE
Add callout sections to join Layer5 Discussion Forum

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#1923]
**Current Behavior**
Currently, no indication to join the [Layer5 Discussion Forum](https://discuss.layer5.io/) is present on site.

**Desired Behavior**
Add a callout section to [Layer5 Discussion Forum](https://discuss.layer5.io/) (similar to Join the Community section present on [Community Page](https://layer5.io/community)), on the [Community Page](https://layer5.io/community) and [FAQs Page](https://layer5.io/company/faq).

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by iambami** [comment]
Hi, I'd love to take this

**Comment by Chadha93** [comment]
> Hi, I'd love to take this

Here you go

**Comment by iambami** [comment]
Thank you.

**Comment by Jashpatel1** [comment]
@iambami Any updates here?

**Comment by kayceeDev** [comment]
Can i still work on this too?

**Comment by Chadha93** [comment]
Sure @kayceeDev ,

**Comment by iambami** [comment]
Yeah, thought it was closed

**Comment by Chadha93** [comment]
@iambami no issue, you are good to go. @kayceeDev Thanks for jumping in there are many other issues you can have a look at. : )

**Comment by leecalcote** [comment]
@kayceeDev good of you to jump in! 🙂

**Comment by kayceeDev** [comment]
@Chadha93 I will do just that.  Thank you.
@iambami you can still reach out if you need me to jump right in and help.
 @leecalcote I am optimistic to make first contribution to an open source project.😊

**Comment by iambami** [comment]
@kayceeDev yes we could do this together

**Comment by iambami** [comment]
@kayceeDev are you on the slack page? You can just message me there.

**Comment by kayceeDev** [comment]
@iambami done👌

**Comment by kayceeDev** [comment]
Hi @Jashpatel1 , I have created a PR with the required changes.

**Comment by kayceeDev** [comment]
> Sure @kayceeDev ,

Done✔

**Comment by iambami** [comment]
@Jashpatel1 I guess that should work. @kayceeDev Weldone.
