### ISSUE TITLE
[ Blog ]Add the She Code Africa Contributhon Boot Camp 

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1930]
**Description**
The Layer5 Blog site is lacking recounts of our participation in She Code Africa Contributhon 2020

**Expected Behavior**
Upload a blog post on the [Layer5 site](https://layer5.io/blog), giving recounts of our participation in She Code Africa Contributhon Boot Camp.
You will find the draft on [here](https://docs.google.com/document/d/1IplKOuPX-QQ0htZ8WrGOL2QRT_hQD7n_RXwCzz6J1Hs/edit#heading=h.57y4l6w9m4xz)

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Jordan-Rob** [comment]
Hi there, can I claim this issue

**Comment by Anita-ihuman** [comment]
Great, you can take it up. Be sure to include the images and links as seen in the daft.

**Comment by Jordan-Rob** [comment]
Alright thanks, I'm having a challenge accessing the draft. How do I gain permission

**Comment by Anita-ihuman** [comment]
Have you filled in the community member form? https://layer5.io/newcomer
That might be the reason you cant access the doc file.

**Comment by Jordan-Rob** [comment]
Okay let me do so

**Comment by Jordan-Rob** [comment]
I needed some clarification on how blog posts are uploaded to the Layer 5 site

**Comment by Anita-ihuman** [comment]
How do you mean?

**Comment by Tanuj22** [comment]
@Jordan-Rob The procedure will be similar for [news ](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news) but for [blogs](https://github.com/layer5io/layer5/tree/master/src/collections/blog)

**Comment by Tanuj22** [comment]
@Jordan-Rob any updates here?

**Comment by Anita-ihuman** [comment]
@Jordan-Rob what's the update on this?

**Comment by Jordan-Rob** [comment]
@Anita-ihuman I'm still facing the other blocker I posted in slack a few colleagues are trying to help me but no solution yet let me tag you on the thread in slack

**Comment by Jashpatel1** [comment]
@Jordan-Rob @Anita-ihuman were you able to find a solution to the blocker?

**Comment by Anita-ihuman** [comment]
Yes, the feedback given says, Rob is supposed to review his code for error.
