### ISSUE TITLE
[Learn][Epic] Add a course to the learn-ng site

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1940]
**Current State:**
The current learn section doesn't have an actual course present within the learning path.

**Desired State:**
A course needs to be added, named `Introduction to Service Mesh - Hands On`. We can start with migrating the labs in the `istio-service-mesh-workshop` course at https://github.com/layer5io/istio-service-mesh-workshop as individual chapters for this course.

This issue can be considered as an epic and, a PR for each chapter/lab can be taken up for migration.

Figma Design for the sample page can be found [here](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5820%3A12409). The sidebar component is not included in this issue.

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Check out the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Harshit-1999** [comment]
Figma File is unavailable.

**Comment by anurag8546** [comment]
@Nikhil-Ladha Where will I find the code for this `Learn Service Mesh`  page? in this repository.

**Comment by kaushambisharma** [comment]
I'd like to work on this issue.

**Comment by Nikhil-Ladha** [comment]
@anurag8546 You can find the code for this section of the site under the [`Learn-Layer5`](https://github.com/layer5io/layer5/tree/master/src/sections/Learn-Layer5).

**Comment by Nikhil-Ladha** [comment]
@kaushambisharma that would be great. Though just wait until today, I will be pushing some updates/a template then it will be easier to start with the migration.

**Comment by Nikhil-Ladha** [comment]
@kaushambisharma and @anurag8546 the wireframe for TOC and a chapter for this issue is already added in the repo. So, now you can start migrating a chapter per PR and use this issue for it.

**Comment by Nikhil-Ladha** [comment]
If you guys have any doubt, feel free to ping me on slack.
And, if you have not joined slack yet....then what are you waiting for? [Join now](slack.layer5.io)
