### ISSUE TITLE
[README] Slack badges for member's stats

### ISSUE THREAD

**Issue by amino19** [layer5io/layer5#1942]
**Description:**
Need to add a Slack badge for Layer5 community, shows member's counts; as shown below:

**Current Behaviour:**
Lost member stats badge

**Desired Behaviour:**
Need to add a badge like: 

**Screenshots**

![image](https://user-images.githubusercontent.com/75872316/122811622-5a105000-d2ee-11eb-9ca3-1b48c5f85e76.png)

**Enviroment:**
- Host OS:  Any
- Meshery Version: Any
- Kubernetes Version: Any
- Browser: Any
-----
**Contributor Resources**
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See [badge resource](https://github.com/rauchg/slackin)

**Comment by DARK-art108** [comment]
Can I work upon this addition? @amino19

**Comment by amino19** [comment]
@DARK-art108 : Yours stage.

@adithyaakrishna : Sir, Pl Assign him.

**Comment by amino19** [comment]
@DARK-art108 : Do you like to give a shot here?

**Comment by DARK-art108** [comment]
Yes, @amino19 sure I will add this!

**Comment by Anita-ihuman** [comment]
@DARK-art108, any updates on this?

**Comment by Anita-ihuman** [comment]
@DARK-art108, any updates on this?

**Comment by khanjasir90** [comment]
@Anita-ihuman  can i work on this? if @DARK-art108 has not done it!

**Comment by Anita-ihuman** [comment]
sure, go ahead

**Comment by khanjasir90** [comment]
@Anita-ihuman  i have doubt!
the slack badge should be static aur dynamic means it should get automatically updated once a new user enters the slack!

**Comment by khanjasir90** [comment]
@Anita-ihuman  i have doubt!
the slack badge should be static aur dynamic means it should get automatically updated once a new user enters the slack!

**Comment by khanjasir90** [comment]
@Anita-ihuman  i have doubt!the slack badge should be static or dynamic means it should get automatically updated once a new user enters the slack!

**Comment by khanjasir90** [comment]
@Anita-ihuman  i have doubt!the slack badge should be static or dynamic means it should get automatically updated once a new user enters the slack!

**Comment by amino19** [comment]
Yes, you are right!

**Comment by khanjasir90** [comment]
@Anita-ihuman  can i get the legacy access token for slackin integration since slack does'nt provide any api to get realtime connect user so i was using slackin-extended which is 3rd party service to get that data and i am attaching a screenshot of the readme file of slackin-extended api which states that it requires legacy access token of the layer5io slack
![slackin-res](https://user-images.githubusercontent.com/53305380/126888886-600cf9ac-7ee6-4c6b-a88c-5e15782372f8.JPG)

**Comment by Anita-ihuman** [comment]
@Jashpatel1 
Please look at this

**Comment by khanjasir90** [comment]
Any update @Jashpatel1  @Anita-ihuman ?

**Comment by leecalcote** [comment]
We previously had the total count of Slack members available through the slackin app. That app hasn't been maintained in a long time and still requires use of Slack's legacy tokens. Unwittingly, we recently deleted our only legacy API token, not knowing that Slack no longer allows new legacy API tokens to be generated. 

So, we'll need to explore other options for collecting the total count of Slack members. Ultimately, it's not a big deal if we can't post the count alongside the Slack badge here. It would be nice, but I'm not sure that we'll find a solution.

@khanjasir90, what are your thoughts? Close this issue and move to another one? Or keep researching other possible solutions?

**Comment by khanjasir90** [comment]
@leecalcote give me a a day or two . I will research and get back to you!

**Comment by warunicorn19** [comment]
@khanjasir90 any updates?

**Comment by leecalcote** [comment]
I assume that slack doesn't have a public API with member account for a given workspace…￼

**Comment by khanjasir90** [comment]
@leecalcote @warunicorn19 @Anita-ihuman i have researched about it and did'nt found anything worthy that fits our need! lets close this issue

**Comment by leecalcote** [comment]
@khanjasir90 Slack doesn’t have an API that returns workspace user count?

**Comment by PulkitSinghDev** [comment]
Hey 👋🏼 , I can work on this issue :)

**Comment by leecalcote** [comment]
This request really isn't feasible without additional infra for secrets and Slack api queries. Let's close this issue down.

**Comment by amino19** [comment]
@leecalcote: Yes, contributors have to work as [slackin]( https://github.com/rauchg/slackin) does, really big task.
