### ISSUE TITLE
[Contact] The contact form fails to submit in Safari

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1953]
**Description**
The submit button on https://layer5.io/company/contact perpetually spins without submission completing when using Safari. It does work when submitting via Chrome.

**Screenshots**
<img width="1468" alt="Screen Shot 2021-06-25 at 3 05 39 PM" src="https://user-images.githubusercontent.com/7570704/123479700-f1afc000-d5c6-11eb-98c2-0c05fdeb50fd.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Nikhil-Ladha** [comment]
Seems like an issue with MailChimp itself 🤔

**Comment by Nikhil-Ladha** [comment]
Could you check if you are able to submit the form through this link: https://us15.list-manage.com/contact-form?u=6b50be5aea3dfe1fd4c041d80&form_id=d0ffe17c92d8014ede6b721aa16096e8

**Comment by leecalcote** [comment]
@Nikhil-Ladha, yes, indeed. That works.

**Comment by Jashpatel1** [comment]
@leecalcote @Nikhil-Ladha Any updates here?

**Comment by Nikhil-Ladha** [comment]
Nope, this is a weird issue and needs to be debugged on Safari specifically. Because, it works on all the other browsers I can't have say much on the issue.

**Comment by leecalcote** [comment]
@Ayush-Khandelwal-007, help a MacOS brother out...

**Comment by Ayush-Khandelwal-007** [comment]
> Nope, this is a weird issue and needs to be debugged on Safari specifically. Because, it works on all the other browsers I can't have say much on the issue.

I don't know what is going on here, its pretty messed up as I "can't see the submit" button in the chrome browser. Let me see what all is going on.

**Comment by sudo-NithishKarthik** [comment]
Actually i am facing this issue irrespective of the browser that i use. On looking into it, i found that it is not able to send the cookie when the form is loaded in iframe.

while using [this](https://us15.list-manage.com/contact-form?u=6b50be5aea3dfe1fd4c041d80&form_id=d0ffe17c92d8014ede6b721aa16096e8) link 
<img width="455" alt="Screenshot 2021-07-03 at 9 49 18 PM" src="https://user-images.githubusercontent.com/75248557/124360637-8611c680-dc48-11eb-8e34-b1d17e7275db.png">

while using it in iframe
<img width="639" alt="Screenshot 2021-07-03 at 9 49 29 PM" src="https://user-images.githubusercontent.com/75248557/124360643-8c07a780-dc48-11eb-8e99-4e50bffcc318.png">

This might be the problem i guess, although i am not sure why its returning 406 as it has nothing to do with cookies as such

**Comment by Ayush-Khandelwal-007** [comment]
@sudo-NithishKarthik Are you able to see the submit button in chrome (from the website, not from the direct link to the form)?

**Comment by sudo-NithishKarthik** [comment]
> @sudo-NithishKarthik Are you able to see the submit button in chrome (from the website, not from the direct link to the form)?

Yes actually

**Comment by Nikhil-Ladha** [comment]
Ok, can you guys try if building the site locally makes any difference in the working or appearance of the button?

**Comment by sudo-NithishKarthik** [comment]
Ya, lemme do that @Nikhil-Ladha

**Comment by sudo-NithishKarthik** [comment]
> Ok, can you guys try if building the site locally makes any difference in the working or appearance of the button?

it doesn't, it still gives the same error

**Comment by sudo-NithishKarthik** [comment]
Ok guys, i found what the issue is, this happens when the user's browser has its preference set to disable 3rd party issues, 
since the browsers consider cookies inside an iframe as third-party-cookies. If you want to verify,

For safari, enable this, 
<img width="1437" alt="Screenshot 2021-07-03 at 11 23 33 PM" src="https://user-images.githubusercontent.com/75248557/124362913-b14ee280-dc55-11eb-83d0-490d16e6a40b.png">
reopen the browser , and try again, it should work.

For brave and chrome, allowing all cookies in the settings should do the job

**Comment by sudo-NithishKarthik** [comment]
Anybody has an idea to fix it ?

**Comment by Nikhil-Ladha** [comment]
Not really 🤔 , if a user fails to submit because of the way MailChimp provide service it is not possible to have any different embedding done for this form. This leaves us to manually tell anyone (who face this issue).

**Comment by sudo-NithishKarthik** [comment]
Ya, and i don't think there's much we can do about it. Because, if somehow we manage to set a third-party-cookie even after it is blocked by the browser, then, i don't see that browser going anywhere 😂

**Comment by sudo-NithishKarthik** [comment]
we can actually have a alert sort of thing to let the users know that they have to allow third party cookies in order for this form to function, or, we should take them to the direct form link
