### ISSUE TITLE
[ Learn-ng ] Fix container to be even

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1955]
**Current Behavior**
As a result of the text "The mastering service meshes for Developer"  wrapping, the container appears longer than the other container.
![Screenshot 2021-06-25 at 16 20 25](https://user-images.githubusercontent.com/62384659/123535893-128b2900-d71f-11eb-8059-08d66038e417.png)
**Desired Behavior**
Adjust The "The mastering service meshes for Developer"  container to be even In length with the other containers.

---
**Screenshots / Mockups**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by parthlaw** [comment]
I can't find these containers on the website. Can you provide a link to where these containers are used?

**Comment by parthlaw** [comment]
I would like to work on this one.

**Comment by parthlaw** [comment]
I would like to work on this one.

**Comment by Anita-ihuman** [comment]
https://layer5.io/learn-ng
