### ISSUE TITLE
[Learn] Navigation to course overview page from chapter page is broken

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [layer5io/layer5#1959]
**Description**
User is not taken to the course overview page on clicking back button from the TOC component in chapter page. Refer the screen recording for clarity.

**Expected Behavior**
User should be taken to the course overview page on clicking the back button.

**Screen recording**

https://user-images.githubusercontent.com/75248557/124100785-6037c680-da7c-11eb-9ac5-84303365a30e.mov

 **Additional Context**

The format of the url for existing pages are,
    layer5.io/learn-ng - Home page
    layer5.io/learn-ng/${learning-path} - Courses list page
    layer5.io/learn-ng/${learning-path}/${course} - Course overview page
    layer5.io/learn-ng/${learning-path}/${course}/${chapter} - Chapter Page

This issue is because of setting an invalid url of the page to which the user is supposed to be taken to.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by devartstar** [comment]
Hi @sudo-NithishKarthik , I would Like to work on this. Can you assign this to me.

**Comment by sudo-NithishKarthik** [comment]
Sure @devartstar , if you are new to the community, don't forget to join our slack(https://slack.layer5.io) where all the fun learning happens 😉 . If you face any difficulties, feel free to reach out ✌🏽 . Happy learning 🎉

**Comment by devartstar** [comment]
I am having some difficulty in setting up the environment.
Getting some errors while running `make site`.
![Screenshot from 2021-07-03 11-37-14](https://user-images.githubusercontent.com/61665451/124345448-8d0fe900-dbf6-11eb-8bda-473e77bac5e6.png)
Can u please help me with it.

**Comment by Nikhil-Ladha** [comment]
Did you ran `make setup-ui-libs` before running `make site`?

**Comment by devartstar** [comment]
yes, and I also updated my npm to the latest version, still got the error.

**Comment by Nikhil-Ladha** [comment]
Delete the `.cache` folder and try again. Also, have you made any changes or this is happening without the changes?

**Comment by devartstar** [comment]
okay...will try this.
No, I didn't make any changes.

**Comment by devartstar** [comment]
Deleted the `.cache` folder and tried again.
https://user-images.githubusercontent.com/61665451/124346502-d2cfb000-dbfc-11eb-9ba0-484ef1a6e856.mov

**Comment by sudo-NithishKarthik** [comment]
Try this

1. run `npm run clean`
2. delete `package-lock.json`
3. run `make setup-libs`
4. run `make site`

**Comment by sudo-NithishKarthik** [comment]
@devartstar , what is the update on this ? Were you able to set up the project ?

**Comment by devartstar** [comment]
@sudo-NithishKarthik sorry for the late reply -
No, I haven't still been able to set up the project,
Earlier the error was `Cannot find module 'vfile'`
Now its showing - `Cannot find module 'chalk'`

**Comment by devartstar** [comment]
I have created a PR # [1980](https://github.com/layer5io/layer5/pull/1980) which fixes this issue. Can you please review it.

**Comment by leecalcote** [comment]
Excellent. 😄
