### ISSUE TITLE
Overflowing Text

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [layer5io/layer5#1961]
**Description**
Overflowing text

**Screenshots**

https://user-images.githubusercontent.com/59086855/124177243-9487a300-dacd-11eb-8305-8e12b333aae5.mov

**Enviroment:**
- Host OS: OSX
- Browser: Google Chrome

---

**To Reproduce**
1. Go to 'https://layer5.io/careers/internships/'
2. Hover on "Software Engineer Internship" card.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by kaushambisharma** [comment]
I'd like to take up this issue.

**Comment by Ayush-Khandelwal-007** [comment]
Here you go @kaushambisharma.

**Comment by Ayush7614** [comment]
@Ayush-Khandelwal-007 i am working on the issue please assign me

**Comment by warunicorn19** [comment]
Isn't there already an existing PR for this made by @kaushambisharma ?
