### ISSUE TITLE
[Learn] Home: Creating the main page of Learn

### ISSUE THREAD

**Issue by austinogiza** [layer5io/layer5#1962]
**Current State:**
There is currently no home page for the learn.layer5.io

**Desired State:**

As such, a design has been created for the learn.layer5

below are some components for the page, its design and its assets

For the card component, this is the styling to aid for pixel perfect implementation
height: 200px;
width: 300px;
background: #FCFCFC;
border-radius: 10px;

For the hero section this is the styling
height: 255px;
width: 1440px;

for the card section,
height: 865px;
width: 1440px;

For the don't learn alone section,
width: 1440px;
height: 500px;
background: #EFEFEF;

For the button in the don't learn alone
height: 55px;
width: 310px;
background: #00B39F;
border-radius: 5px;

Below are the design assets
https://drive.google.com/drive/folders/101p5wW5zFEBTERe5s2uAQqwlVLl4CHGF?usp=sharing

Below is the design
<img width="1440" alt="learn homepage" src="https://user-images.githubusercontent.com/44683018/115625473-04bac100-a2f4-11eb-93a4-c5e3a580c350.png">

below is a link to the design file
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5539%3A10332

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by sudo-NithishKarthik** [comment]
@leecalcote , is this still relevant ?

**Comment by leecalcote** [comment]
No, it’s not. You guys have taken good care of this page.
