### ISSUE TITLE
[Discuss] Newsletter signup not working in the footer

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1963]
**Description**
In the footer of the discuss.layer5.io site, entering an email address and clicking Subscribe seemingly just refreshes the page and does not seem to subscribe the email address to the newsletter.

**Enviroment:**
- Browser: Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
Hey!, Could you assign me this issue?

**Comment by warunicorn19** [comment]
Fixed this Issue. :)

**Comment by warunicorn19** [comment]
Closing the issue because it's fixed.
