### ISSUE TITLE
[Learn] Change the look of terminal in learn-ng homepage

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [layer5io/layer5#1967]
**Current Behavior**
The terminal present in the [Learn-NG](https://layer5.io/learn-ng) is not looking good.

<img width="1440" alt="Screenshot 2021-07-05 at 2 57 19 PM" src="https://user-images.githubusercontent.com/75248557/124449681-4f9b8f00-dda1-11eb-9219-d1e9b301e04f.png">

**Desired Behavior**
Make the terminal look good and display relevant content in it.

Inspiration can be taken from this [terminal](https://layer5.io/service-mesh-management/meshery/getting-started)
Infact, it can be reused 🤔 

<img width="1440" alt="Screenshot 2021-07-05 at 2 59 40 PM" src="https://user-images.githubusercontent.com/75248557/124450009-a2754680-dda1-11eb-8b45-08f24892a1f9.png">

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Tanuj22** [comment]
An example to reuse the terminal is [here](https://layer5.io/service-mesh-management/meshery)
![image](https://user-images.githubusercontent.com/42486853/124474724-80d68800-ddbe-11eb-9f20-385c40985610.png)

**Comment by chetak123** [comment]
Can I take this issue please ?

**Comment by sudo-NithishKarthik** [comment]
sure @chetak123
