### ISSUE TITLE
Area of focus section to be added

### ISSUE THREAD

**Issue by chetak123** [layer5io/layer5#1969]
**Desired Behavior**

Make an **Area of focus** dropdown on [Community Members](https://layer5.io/community/members) page which provide names of each badge for the community members.

---
![Screenshot from 2021-07-05 20-15-27](https://user-images.githubusercontent.com/53306550/124489005-234a3780-ddce-11eb-8d40-547c1d7f4b0d.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by sudo-NithishKarthik** [comment]
@debo19

**Comment by sudo-NithishKarthik** [comment]
@debo19

**Comment by devartstar** [comment]
Hi, can you please describe this issue a little bit more and if it is available to work on.

**Comment by sudo-NithishKarthik** [comment]
@devartstar, @debo19 is working on this issue. You can see if there are any other issues that intrigues you ✌🏽

**Comment by devartstar** [comment]
Okay sure, thanks for confirming.

**Comment by debo19** [comment]
@warunicorn19

**Comment by myhiccupsandglitches** [comment]
Hello @debo19 can I work on this with you?

**Comment by debo19** [comment]
@myhiccupsandglitches Yeah sure
