### ISSUE TITLE
[README] Need to rectify `Slack badge` link

### ISSUE THREAD

**Issue by amino19** [layer5io/layer5#1970]
**Description**

Slack badge link got changed, i.e, `GitHub Link` itself.

**Expected Behavior**

Need rectification & update as:
```
https://slack.layer5.io
```

**Enviroment:**
- Host OS: Any
- Meshery Version: Any 
- Kubernetes Version: Any
- Browser: Any
--------
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Jayita10** [comment]
I am new to open source, would like to work on this issue

**Comment by amino19** [comment]
@Jayita10 : Good, here you go! :rocket:

**Comment by tanmoy27112000** [comment]
can i fix it? i just joined
