### ISSUE TITLE
[Community] Member Profile: Sayantan Bose 

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1976]
**Current Behavior**

@sayantan1413  has been a consistent contributor and community member.

**Desired Situation**

Let's recognize @sayantan1413  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sayantan1413 
- Twitter: sayanta33163352
- LinkedIn: sayantan-bose-14134a1a6
- Link to profile picture: https://drive.google.com/file/d/1HUr29lAPIapMH6V2Fpy0cyIA3c6nQpfu/view?usp=sharing
- About: A pre-final year student from Narula Institute of Technology, who is digging his way into the vast world of programming. I had joined Layer5 on May 2021 to put my hands into open-source and it has opened a wide world in front of me that had all the right things to upskill my knowledge and had helped me to be the best version of myself !!
- Location: West Bengal, India

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by debjani1413** [comment]
I would like to work on this

**Comment by Anita-ihuman** [comment]
Go ahead @debjani1413
