### ISSUE TITLE
[CI] Create a labeler workflow or an issue template for issues related to Discuss

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#1983]
**Current Behavior**
Contributing to the discuss.layer5.io site involves a unique contribution model in which contributors make changes in the discourse server running at staging-discuss.layer5.io first, then those changes are reviewed and propagated.

**Desired Situation**
Ideally, contributors are pointed to these instructions on each issue with an `area/discuss` label or the `framework/discourse` label.

#### Implementation

One or both of the following:

1. an issue template contains these instructions. for items related to Discuss
2. a labeler workflow (like this one - https://github.com/meshery/meshery/blob/master/.github/label-commenter-config.yml) to comment with Discuss contributor instructions.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
We also need instructions on how to persist the site's custom configuration to GitHub, @Jashpatel1. This could be tracked in a separate issue.

**Comment by sayantan1413** [comment]
Hey @leecalcote I would like to take up the issue. But I think the contributor resources should be different for the discuss.layer5.io
