### ISSUE TITLE
[Learn] Add sidebar component to learn path page

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [layer5io/layer5#1984]
**Current State:**
The sidebar component has not been built

<img width="1440" alt="Screenshot 2021-07-09 at 9 44 52 AM" src="https://user-images.githubusercontent.com/75248557/125022436-51fc3280-e09a-11eb-9568-96b224d40100.png">

**Desired State:**

Build the sidebar component taking inspiration from [storybook site](https://storybook.js.org/tutorials/intro-to-storybook/react/en/using-addons/)

**Note**

Use the color scheme of Layer5

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by devartstar** [comment]
@sudo-NithishKarthik can you please assign me this issue.

**Comment by sudo-NithishKarthik** [comment]
Sure @devartstar , go ahead.

**Comment by kayceeDev** [comment]
@sudo-NithishKarthik  has this issue been worked on or can i get assigned too?

**Comment by sudo-NithishKarthik** [comment]
@kayceeDev ,  @devartstar  is already working on this 😅

**Comment by sudo-NithishKarthik** [comment]
@devartstar , whats the progress ?
