### ISSUE TITLE
[Learn] Add the course for introduction to service mesh using linkerd

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1986]
**Current State:**
We have a course: `Introduction to service meshes - Hands On` under the learning path: `Mastering service mesh`. That course only has the tutorial using `istio`.

**Desired State:**
We need to create a new folder: `linkerd` under this [folder](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes) and the chapters inside is similar to what we have [here](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/istio).
The chapter name should remain the same, but the content should be taken up from this [repo](https://github.com/layer5io/linkerd-service-mesh-workshop).

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Blakelist7** [comment]
@Nikhil-Ladha I'd like to help with this issue :)

**Comment by Nikhil-Ladha** [comment]
Sure, go ahead and start by sending out a PR for one chapter only.
Take a look to the code and the structure of the existing course. It will help you.

**Comment by Blakelist7** [comment]
Hey, @Nikhil-Ladha just confirming 😅 
Chapters names should be taken up from <a href="https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/istio">here</a>. For example `deploy-an-application.mdx` and content inside it should be <a href="https://github.com/layer5io/linkerd-service-mesh-workshop/blob/master/lab-1/README.md">this</a>, right?

**Comment by Nikhil-Ladha** [comment]
Yes.

**Comment by Blakelist7** [comment]
@Nikhil-Ladha should I add <a href="https://github.com/layer5io/linkerd-service-mesh-workshop/blob/master/lab-6/README.md">Lab-6</a> or <a href="https://github.com/layer5io/linkerd-service-mesh-workshop/tree/master/lab-4"></a>to chapter 4 `observability`?
As topic `observability` matches `lab 8`.
(P.S similar for `lab 8`)

**Comment by Nikhil-Ladha** [comment]
>I have to add them in the same order as they are here?
Yes, but the problem here is the chapter content and the topic which they cover. They don't seem to be similar to what Istio has and that is my concern.

**Comment by Blakelist7** [comment]
> >I have to add them in the same order as they are here?
> Yes, but the problem here is the chapter content and the topic which they cover. They don't seem to be similar to what Istio has and that is my concern.


Mine too 🤔

**Comment by Nikhil-Ladha** [comment]
You migrate the chapters for now in the order they are, we will take a decision on the order later.

**Comment by Nikhil-Ladha** [comment]
Don't update the title's to match the Istio onne's if they don't resemble.

**Comment by Blakelist7** [comment]
> Don't update the title's to match the Istio onne's if they don't resemble.

ok, then should I change the file name as well or keep them same as it for `istio`?

**Comment by Nikhil-Ladha** [comment]
Change the filename as well
