### ISSUE TITLE
[Learn] Add a new course "Advance concepts of Service Mesh"

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1987]
**Current State:**
We have only 1 course `introduction to service mesh` under the learning path `mastering service mesh`, the `advance concepts of service mesh` course is not yet added.

**Desired State:**
A new course `Advance concepts of service mesh` needs to be added under the learning path `mastering service mesh` [here](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio), it should use the content from this [repo](https://github.com/layer5io/advanced-istio-service-mesh-workshop) and have a structure similar to this [course](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by The-Loony-Coder** [comment]
Hey @Nikhil-Ladha , can I have this issue?

**Comment by Nikhil-Ladha** [comment]
Sure. You can start off with sending out a PR which adds only 1 chapter for the course (probably the first chapter)

**Comment by The-Loony-Coder** [comment]
sorry for taking this long, actually I'am stuck with this issue.I just wanted to know where can I see those mdx [files](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/linkerd) in my localhost project when I run it in browser,for example I'am able to access these files[](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/istio) here in website[](https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes)

**Comment by The-Loony-Coder** [comment]
sorry for taking this long, actually I'am stuck with this issue.I just wanted to know where can I see those mdx [files](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/linkerd) in my localhost project when I run it in browser,for example I'am able to access these [files](https://github.com/layer5io/layer5/tree/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/istio) here in website[path](https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes)

**Comment by Nikhil-Ladha** [comment]
This issue requires you to add a new course, so once you add the course under the `Mastering service mesh`, you will see the course listed on this [page](https://layer5.io/learn-ng/mastering-meshery-istio). Then, when you click on the course and go inside, you will see all the chapters listed. If not, then let me know.

**Comment by The-Loony-Coder** [comment]
why can't I see the latest chapters added by @Blakelist7  in introduction-to-service-meshes/linkered folder in real website,or if they are added please provide me the link of the page in meshery/learn-ng.

**Comment by Nikhil-Ladha** [comment]
If you got to the path on the website it will show, and as far as the content is concerned have you updated your fork with the latest code?

**Comment by Blakelist7** [comment]
@The-Loony-Coder @Nikhil-Ladha 
1) I guess TOC of [Introduction to service meshes](https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes) redirects you directly to [Istio](https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes/istio/getting-started). 
2) I think we need to modify [this page](https://github.com/layer5io/layer5/blob/master/content-learn/mastering-meshery-istio/introduction-to-service-meshes/index.mdx)
3) @The-Loony-Coder btw you can access [Introduction to service mesh using Linkerd](https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes/linkerd/getting-started/) by entering the absolute path

**Comment by Nikhil-Ladha** [comment]
This is the live path for one of the chapters of linked: https://layer5.io/learn-ng/mastering-meshery-istio/introduction-to-service-meshes/linkerd/getting-started/
And, for others, you will have to enter the path manually because the switcher which we have planned to be implemented in this [issue](https://github.com/layer5io/layer5/issues/1988), once that is done it will become easier to navigate the pages.

**Comment by The-Loony-Coder** [comment]
I am trying it again if I am not able to do it,I'll let you know.
And thank you so much.

**Comment by Nikhil-Ladha** [comment]
Things are still in todo, if you checkout the working of the storybook tutorials site then you will understand what we want to achieve.
Also, checkout the figma and the design spec above it will help you.

**Comment by The-Loony-Coder** [comment]
Actually I'am not able to access figma project it says this
![figma](https://user-images.githubusercontent.com/55737921/126517576-33e15358-ae87-4c81-b0fb-7b3727bee40a.png)

**Comment by Nikhil-Ladha** [comment]
Try now.

**Comment by ujju20** [comment]
Is this issue available for work?

**Comment by Nikhil-Ladha** [comment]
Yeah, you van work along with @The-Loony-Coder on this one. Divide rhe chapters and send out PRs for individual chapters.

**Comment by ujju20** [comment]
> Yeah, you can work along with @The-Loony-Coder on this one. Divide rhe chapters and send out PRs for individual chapters.

Ok 👍🏻

**Comment by The-Loony-Coder** [comment]
hey @ujju20 , I'am done with first 4 chapters ,you can add the next 3 chapters, from 5 to 7.

**Comment by ujju20** [comment]
> hey @ujju20 , I'am done with first 4 chapters ,you can add the next 3 chapters, from 5 to 7.

OK I will do that 👍🏻

**Comment by ujju20** [comment]
Is this issue solved ??

**Comment by Nikhil-Ladha** [comment]
Hi @ujju20 no it is not. The issue was closed by mistake, there are still 7 which is to be migrated.
