### ISSUE TITLE
[Learn] Add service mesh switcher for each course

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#1988]
**Current State:**
A user can take a course under a learning path from a variety of service meshes available. But, it lacks the switcher to do so.

**Desired State:**
A section needs to be added under the TOC on each chapter page, which will allow the user to change the service mesh using which they want to take the course. Like the `Service meshes:` section we have in the image below:
![Screenshot from 2021-07-12 19-30-55](https://user-images.githubusercontent.com/29438875/125300562-c6a7c900-e347-11eb-8351-08d8450db79d.png)
The working of the same can be understood from this [page](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/).

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Nikhil-Ladha** [comment]
Sure, do you want me to assign this to you?

**Comment by iambami** [comment]
yes

**Comment by Nikhil-Ladha** [comment]
@iambami any updates here?
