### ISSUE TITLE
Add a FAQ for members of the community

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#1991]
**Current Behavior**
There is no FAQ that points out what is expected from contributors joining the community.

**Desired Situation**
Create a FAQ that answers the question "What is expected of me as a member of Layer5 organisation?"

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Jordan-Rob** [comment]
could I take it on
