### ISSUE TITLE
[Community] Member Profile: Aditya Chatterjee

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/layer5#1998]
**Current Behavior**

@warunicorn19 has been a consistent contributor and community member. :rocket: 

**Desired Situation**
Let's recognize @warunicorn19 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @warunicorn19
- Twitter:
- LinkedIn: aditya-chatterjee-737729159
- Link to profile picture: https://drive.google.com/file/d/1mLojptCXkzVP9HYDJl5En9DQfmq9NQpn/view?usp=drivesdk

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Very cool. 😄

**Comment by Jordan-Rob** [comment]
@DelusionalOptimist can I take this up

**Comment by DelusionalOptimist** [comment]
Sure @Jordan-Rob! Go ahead.
Feel free to reach out if you feel like something is missing :grin:

**Comment by Tanuj22** [comment]
@warunicorn19 can you provide a short bio and location?

**Comment by warunicorn19** [comment]
@Tanuj22  sure, should I dm it to you, or just write it here?

**Comment by Tanuj22** [comment]
Here is fine

**Comment by warunicorn19** [comment]
3rd Year CS undergrad of KIIT, Bhubaneswar. Navigating his way through the rapids of the programming world. I joined layer5 in July 2021, it's been an immense learning elivating not just knowledge but a way of life too.

location: kolkata, India

**Comment by warunicorn19** [comment]
@Tanuj22 is this okay?

**Comment by Tanuj22** [comment]
Yes!

**Comment by Tanuj22** [comment]
@Jordan-Rob you can include this too

**Comment by Jordan-Rob** [comment]
@Tanuj22  alright will do

**Comment by Jordan-Rob** [comment]
Hi @warunicorn19 , you didn't specify the names you would like to use on your profile

**Comment by warunicorn19** [comment]
Hey @Jordan-Rob, I'm really sorry, i think I gave you access now, I didn't realise it was private.

**Comment by warunicorn19** [comment]
Also the name on the profile will be Aditya Chatterjee 😃

**Comment by Jordan-Rob** [comment]
> Hey @Jordan-Rob, I'm really sorry, i think I gave you access now, I didn't realise it was private.

okay thanks
