### ISSUE TITLE
Improve current custom 404 page

### ISSUE THREAD

**Issue by l5io** [layer5io/layer5#200]
It would be nice if the custom 404 page included a bit of related humor like: 

- "Oh, no. Please pardon our meshy site."
- "Oops. Please excuse the mesh."

**Comment by reynaldomartinez** [comment]
Hello. Can i still help with the 404 page?

**Comment by leecalcote** [comment]
Thanks to all who contributed! @reynaldomartinez this one is still in need of assistance - https://github.com/layer5io/meshery/issues/345!
