### ISSUE TITLE
Add SMP Community meeting info to `/community/calendar`

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#2000]
**Current Behavior**

A new SMP meeting has been scheduled on the community calendar.

**Desired Behavior**

The new meeting details should be added to the [/community/calendar](https://layer5.io/community/calendar) page in the table. The details of the meeting are given below:

SMP Community Meeting
Biweekly Thursday
#performance
https://bit.ly/3B7uIy9
https://meet.layer5.io/smp
YouTube playlist to be added

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
Hey, can I work on this issue?

**Comment by warunicorn19** [comment]
Go ahead @debo19 ,
