### ISSUE TITLE
Fix the broken link

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2001]
**Description**
The link for Anisat"s member profile appears to be broken and is throwing an error 404.
Also, the links on the page are acting up.

**Expected Behavior**
Check the link on Anisat Akinbani's name and link it properly to her [member profile](https://layer5.io/community/members) on Layer5.io

**Screenshots**

https://user-images.githubusercontent.com/62384659/126029129-6c1df794-0496-4399-8bab-189acc1d0e9f.mov

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Amishakumari544** [comment]
I would like to work on this.

**Comment by Anita-ihuman** [comment]
Sure go ahead

**Comment by Tanuj22** [comment]
Fixed in #1999. @Amishakumari544 please check out any of the other open issues (#2000 ) and if you haven't already you are most welcome to join http://slack.layer5.io :)
