### ISSUE TITLE
[News] CNCF Projects Bring Service Mesh Interoperability, Benchmarks

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2015]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the Layer5 Newsroom.

**Article:**
- Title: CNCF Projects Bring Service Mesh Interoperability, Benchmarks
- Link: https://thenewstack.io/cncf-projects-bring-service-mesh-interoperability-benchmarks/

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
When this new article is posted, please do not use the SMP logo with awkwardly green-colored background, but an official logo from https://layer5.io/brand

**Comment by Amishakumari544** [comment]
I would like to do this. @leecalcote

**Comment by warunicorn19** [comment]
Here you go! @Amishakumari544

**Comment by leecalcote** [comment]
Thank you, @Amishakumari544 @warunicorn19

**Comment by warunicorn19** [comment]
Hey @Amishakumari544 , any updates?

**Comment by Amishakumari544** [comment]
No, i am facing problem while installation.

**Comment by warunicorn19** [comment]
Okay @Amishakumari544 , it's not a problem, if you're having trouble why don't you ask your questions in the slack channel and I'm sure someone will help you out. Meanwhile, we really need the article to be up on our website, so I'll be completing this issue myself, why don't you take a look at other issues.
