### ISSUE TITLE
[Website] The image in sservicemesh interface page is Buggy 

### ISSUE THREAD

**Issue by samirparhi-dev** [layer5io/layer5#2019]
**Description**

I have observed the image in Service Mesh Interface(https://layer5.io/projects/service-mesh-interface-conformance) has some Servicemesh places being blank. See the image below
<img width="1387" alt="Screenshot 2021-07-22 at 9 03 22 PM" src="https://user-images.githubusercontent.com/59992800/126669708-48c9579c-630a-468c-b440-9d4fb35370ae.png">

**Expected Behavior**

It should look something like this:
<img width="1387" alt="Screenshot 2021-07-22 at 9 12 58 PM" src="https://user-images.githubusercontent.com/59992800/126669733-dee58546-bfc8-4eae-80f5-20a1d30f36b2.png">

**Screenshots**

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by bariqhibat** [comment]
I can definitely help this out!

**Comment by samirparhi-dev** [comment]
Great, Please go ahead
