### ISSUE TITLE
[Community] Member Profile: Joeseph Midura

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2025]
**Current Behavior**

@josephmidura  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @josephmidura  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @josephmidura 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by warunicorn19** [comment]
Yes @ujju20 for sure! But could you just hold off for some time till joseph gives us some of his details.

**Comment by ujju20** [comment]
> Yes @ujju20 for sure! But could you just hold off for some time till joseph gives us some of his details.

Ya Sure 👍🏻

**Comment by josephmidura** [comment]
Here's my details:

- [LinkedIn](https://www.linkedin.com/in/josephmidura/)
- [Twitter](https://twitter.com/josephmidura)
- Bio: I have a background in engineering and have always been interested in open source software and emerging technologies. I enjoy learning new software tools and looking for ways to innovate both in and outside of the workplace. I’m a proponent of incremental process improvements and keeping data organized.

**Comment by josephmidura** [comment]
And a [picture](https://drive.google.com/file/d/11jAdYtq4094-eQ86cGZPKRHvwbSYYZ78/view?usp=sharing).

**Comment by warunicorn19** [comment]
Thanks @josephmidura

**Comment by warunicorn19** [comment]
@ujju20 you can start working on this now🚀

**Comment by ujju20** [comment]
> @ujju20 you can start working on this now

ok 👍🏻

**Comment by josephmidura** [comment]
Thanks @ujju20

**Comment by ujju20** [comment]
> Thanks @ujju20

Your Most welcome.

**Comment by warunicorn19** [comment]
@ujju20 any updates on this?

**Comment by ujju20** [comment]
> @ujju20 any updates on this? Also I think you've referenced a wrong PR to this.

Actually, I have taken another issue also, by mistake the PR of that issue I linked it to this issue.
I will work on this and get back to you soon.

**Comment by warunicorn19** [comment]
okay @ujju20 good deal.

**Comment by warunicorn19** [comment]
hey @ujju20, are you still working on this?

**Comment by debo19** [comment]
Hey, I see this issue has still not been done, can I work on this?

**Comment by warunicorn19** [comment]
Yes sure @debo19.
