### ISSUE TITLE
Safari specific issue on Community Member page on Layer5.io

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2027]
**Description**
The newly added drop-down on the community member page doesn't work on safari.

**Screenshots**
<img width="963" alt="Screenshot 2021-07-26 at 7 10 41 PM" src="https://user-images.githubusercontent.com/53532328/126999301-43148271-d36a-41f2-ac5a-8fa8f87d9175.png">

**Expected Behavior**
Should have the same behaviour as the page on Chrome.
<img width="994" alt="Screenshot 2021-07-26 at 7 16 10 PM" src="https://user-images.githubusercontent.com/53532328/126999543-9333a00c-cb52-4733-a2fb-eeacb17063b5.png">

**Enviroment:**
- Host OS: MacOS
- Meshery Version: 
- Kubernetes Version: 
- Browser: Safar

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Thank you for capturing this, @warunicorn19 👍 

Fyi @debo19

**Comment by debo19** [comment]
Hey @leecalcote a little problem here, so I use a windows system and the safari browser I can access is a really old version which I don't think will be reliable enough :(

**Comment by debo19** [comment]
I'm trying to find an alternative to make this work but if anyone else can, feel free to jump in on this. I can always help out.

**Comment by leecalcote** [comment]
@Revolyssup comes to mind...

**Comment by Revolyssup** [comment]
> @Revolyssup comes to mind...

Weird to know that I come to mind for anything UI related. I suck at these things generally.

**Comment by leecalcote** [comment]
But, you do have a Mac. :)

**Comment by leecalcote** [comment]
But, to your point, there are others with a Mac here, that might be better positioned to assist. @Ayush-Khandelwal-007!

**Comment by Revolyssup** [comment]
> But, you do have a Mac (_I think_).

Oh that was the misconception, sorry to disappoint but I dont have mac.

**Comment by Ayush-Khandelwal-007** [comment]
> But, to your point, there are others with a Mac here, that might be better positioned to assist. @Ayush-Khandelwal-007!

Hmmm, let have a look what's going on.
