### ISSUE TITLE
[Learn] Make TOC component in chapter page sticky

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [layer5io/layer5#2028]
**Current State:**
`Table of contents` component in Chapters page is not **sticky**

**Desired State:**

`Table of contents` component in Chapters page should be **sticky** like the one in courses-list page, for eg. [like this](https://layer5.io/learn-ng/mastering-meshery-istio)

**Screenshots:**

 
<img width="1435" alt="Screenshot 2021-07-27 at 9 11 07 PM" src="https://user-images.githubusercontent.com/75248557/127184426-68c3b844-edf7-4de5-a6d6-4624c9179878.png">

Chapters page ^^

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Anita-ihuman** [comment]
Can I take this up?

**Comment by warunicorn19** [comment]
here you go @Anita-ihuman 😁

**Comment by afzal442** [comment]
hy @Anita-ihuman you can define `position: sticky` for that. Thanks.

**Comment by Nikhil-Ladha** [comment]
I think @chinmaym07 had already finished working up on this. I didn't know there was an issue open for this.
@Anita-ihuman if you don't mind, can you pass this issue to him?

**Comment by afzal442** [comment]
Ah, yes I see! thanks Nikhil.

**Comment by yash112-lang** [comment]
Hello, @Anita-ihuman, is this issue is still open or anyone working on this? If not can I start working on it.

**Comment by Nikhil-Ladha** [comment]
Yes, @yash112-lang this issue is being worked upon by @chinmaym07 . You can look around for other unassigned [`good-first-issues`](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22good+first+issue%22) to start off with.

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik can we close this issue? I believe that the PR has been merged already
