### ISSUE TITLE
Refactor the graphql queries to JS code for community members

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2034]
**Description**
The GraphQL queries being used in the files under the [Members-Grid](https://github.com/layer5io/layer5/tree/master/src/sections/Community/Members-grid) code is mostly the same (except a few), they differ only in some fields like `badges`, `maintainers`, `meshmates` which makes the query of data every time, for each type of data redundant.

**Expected Behavior**
Update the code to use a more JS approach to filter out the data based on the type needed from the complete set of data.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Hi @debo19, are you intending to self-assign this issue? If so we don’t need the “help wanted” label, @warunicorn19. 

I wonder if this really is a “good first issue”. Is it relatively easy? The issue description is late in terms of desired implementation and acceptance tests. 

What does use of fragments bring us? // @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
I don't think we will be needing the use of fragments for the Layer5 site (at least not yet). The queries are generally different in all the cases, I can't remember an instance where we are using the same query in different files, can you share such instance @debo19 ?
/cc @Tanuj22

**Comment by Tanuj22** [comment]
@Nikhil-Ladha my primary reason for this was this PR https://github.com/layer5io/layer5/pull/2014/files. Here most of the query is same but only small difference

**Comment by Nikhil-Ladha** [comment]
I am pretty sure a more JS approach can be taken to optimize that, such as using `filter`.

**Comment by Tanuj22** [comment]
Yeah makes sense. We can close this issue ig then 🤔

**Comment by Nikhil-Ladha** [comment]
Actually do not close this. But, update the issue to tackle the same i.e, update the code of the members file to use a single query and then use a filter to get the required data from it.

**Comment by debo19** [comment]
Okay I'll update the issue with this but as Lee mentioned, I think I couldn't describe the problem accurately, Can someone please help me out with that?

**Comment by Nikhil-Ladha** [comment]
No problem. I will do that update.

**Comment by riteshsp2000** [comment]
Hello!
So I went through the discussion and it makes sense that instead of fragments, this could be tacked easily with a javascript filter function. 
I would like to work on this issue, can someone assign me this?

**Comment by Tanuj22** [comment]
Please go ahead
