### ISSUE TITLE
Enhancing the Community Handbook

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2037]
**Current Behavior**
The community Handbook is could use detailed, self-explanatory guidelines that can be resourceful to Layer5 users and the community.

**Desired Situation**
- The goal is to publish the handbook as a public handbook at the Layer5.io site.
- Outline an index of commonly reference documents.
- Improve the community guidelines and update broken links

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Exciting!
