### ISSUE TITLE
[Bug] Landscape badge enlists all community members when selected

### ISSUE THREAD

**Issue by alphaX86** [layer5io/layer5#2045]
**Description**
The community site (https://layer5.io/community/members) shows all members of the community (Active, Inactive) but when the Landscape option is selected all members are shown instead of ones who have the badge

**Expected Behavior**
The Landscape option should display the members who have the Landscape badge and not all

**Screenshots**

![image](https://user-images.githubusercontent.com/59508546/127679846-77e733fb-7f9f-47f0-92f7-eec515669f74.png)

![image](https://user-images.githubusercontent.com/59508546/127679927-a0fbdef2-10f6-4130-98af-18eb3c4c85c5.png)

---

[Optional] **To Reproduce**
1. Go to the site
2. Click on Landscape
3. See the members
4. Then click on All Members
5. Compare them

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
@alphaX86 did you wan to work on this?

**Comment by alphaX86** [comment]
Nope, I reported to fix. Anyone is welcome to fix it :) 

Go ahead @warunicorn19

**Comment by warunicorn19** [comment]
@alphaX86 cool thanks😅

**Comment by alphaX86** [comment]
Yeah ok... 😅
