### ISSUE TITLE
[Website][Getting started with Meshery] Correct the installation instruction and Delete One HOMEBREW section 

### ISSUE THREAD

**Issue by samirparhi-dev** [layer5io/layer5#2048]
**Description**

Installation instruction in the getting started page (https://layer5.io/service-mesh-management/meshery/getting-started) for some of the plat form are wrong. And also there are two Section which talk about Homebrew (one is under apple logo and another under homebrew logo)
Please correct it .

For Example
```Helm Section should have :
kubectl create namespace meshery
helm install meshery meshery/meshery --namespace meshery
```

**Expected Behavior**

- The correct command should be updated in the below Platform:
Docker, AWS, GKE, KIND, K8s, Linux, Minikube , AKS
- Please delete one of the HomeBrew section as it is listed twice

**Screenshots**

Secreenshot of the section need updation:

<img width="1421" alt="Screenshot 2021-07-30 at 9 54 47 PM" src="https://user-images.githubusercontent.com/59992800/127682887-e145d0d4-5bfd-4760-9de6-6de611447297.png">

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by debjani1413** [comment]
I would like to work on this , may I??

**Comment by samirparhi-dev** [comment]
Thank you @debjani1413 !!! Please go ahead

**Comment by afzal442** [comment]
hi @samirparhi-dev is this issue related to `first timers only`? Happy to collaborate. thanks
