### ISSUE TITLE
Upload the Patterns badge in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2051]
**Description**
Currently, the Layer5 repository is missing a Pattern badge 

**Expected Behavior**
There should be a badge for patterns just like other badges for the projects.
![image](https://user-images.githubusercontent.com/62384659/127747310-a410b0a6-3532-48da-a432-bf23e0ddbfe4.png)
**Screenshots**
![Screenshot 2021-07-31 at 18 07 37](https://user-images.githubusercontent.com/62384659/127747347-b91bba8d-5dde-4df3-a3cf-c9cbcb419e85.png)

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sgibson19** [comment]
I would like to work on this, may I?

**Comment by Anita-ihuman** [comment]
Please go ahead.
