### ISSUE TITLE
[Community] Member Profile: Ashish Tiwari

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2056]
**Current Behavior**

@Revolyssup has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Revolyssup  as a contributor and community member by creating a profile on https://layer5.io/community/members.

Github: @Revolyssup 
Twitter: Ashisht31418366
LinkedIn: at1511
Link to profile picture: https://drive.google.com/file/d/1js8k_zJ76Btc_f0ZlhRn4aANRH8gp4yT/view
About:  I am a final year computer science undergraduate at IP University, Delhi. Passionate Backend Developer with an interest in microservices and cloud-native ecosystems. Constantly learning new things based on interest & curiosity and trying to give back as much in open-source. Other than that, I love solving algorithm problems. A side note about me would be that, once upon a time, I fell in love with mathematics and physics, which still is an ongoing affair.
Location: New Delhi, India

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Rubix982** [comment]
I would like to take this up.

**Comment by sayantan1413** [comment]
Here you go @Rubix982 😃

**Comment by Rubix982** [comment]
@sayantan1413, my first contribution to @meshery, here we go. :smile:

**Comment by sayantan1413** [comment]
Here we start with our first issue and a lot more to go 🚀

**Comment by Rubix982** [comment]
@sayantan1413 @Anita-ihuman can you please review this [PR](https://github.com/layer5io/layer5)? Thank you!
