### ISSUE TITLE
[website][Discuss] command like code block background to be bit more darker and rounded corner

### ISSUE THREAD

**Issue by samirparhi-dev** [layer5io/layer5#2062]
**Description**

Currently, when i am inserting a command like (for example `meshery server` code block) in Discuss forum, it does not distinguished properly 

**Important Note:** 
This feature is only for the small and command like code block not for a huge code block

**Expected Behavior**

- The code block highlighting should be bit more dark grey and rounded corner to distinguish better.
For example the code block look like below :
`Sample code snipet`
- Consider to change  snippet font color which also can give a good viewing feel.
**Screenshots**

NA

[Optional] **Additional Context**

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by debjani1413** [comment]
Hey @samirparhi-dev I would like to work on it.

**Comment by samirparhi-dev** [comment]
Here you go @debjani1413

**Comment by debjani1413** [comment]
Hey @samirparhi-dev , I've  been really busy due this my exams right now, can you please unassign me, really sorry for the inconvenience caused!

**Comment by samirparhi-dev** [comment]
No Sweat ! @debjani1413.

**Comment by shahkushal38** [comment]
Hey @samirparhi-dev , I would like to work on this issue

**Comment by warunicorn19** [comment]
@shahkushal38 go ahead!

**Comment by warunicorn19** [comment]
Head's up: You'll have to create accounts on [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) and [discuss.layer5.io](https://discuss.layer5.io/) and reach to jash to get admin access.

**Comment by shahkushal38** [comment]
Okay will reach to out to Jash for access, through Slack community platform of Layer5

**Comment by warunicorn19** [comment]
@shahkushal38 any updates?

**Comment by Aniket1312** [comment]
hey can I join here

**Comment by Aniket1312** [comment]
hey can I do this.

**Comment by sej28** [comment]
Hey, I want to contribute in this one...

**Comment by samirparhi-dev** [comment]
@Aniket1312 : please go ahed
