### ISSUE TITLE
[Community] Member Profile: Nithish Karthik

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2063]
**Current Behavior**

@sudo-NithishKarthik  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @sudo-NithishKarthik  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sudo-NithishKarthik (https://github.com/sudo-NithishKarthik)
- Twitter: https://twitter.com/NithishKarthi11
- LinkedIn: https://www.linkedin.com/in/nithish-karthik-5389b920a/
- Link to profile picture: https://drive.google.com/file/d/1zSjdqoapHmdr0RG0k8MuT5z1Nwq9NAlw/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by NikhilSharma03** [comment]
@warunicorn19 Can I work on this?

**Comment by NikhilSharma03** [comment]
Also, The bio isn't provided. Should I ask nithish?

**Comment by warunicorn19** [comment]
Yes @NikhilSharma03, go ahead.
@sudo-NithishKarthik could you please provide a small bio?

**Comment by sudo-NithishKarthik** [comment]
**BIO**
Hello there, I am Nithish, a sophomore student at Indian Institute of Technology, Varanasi. I have a keen sense of interest in technology related stuff. I like to explore everything that comes in my way. I am geared towards making a positive impact on people by engaging with open source communities.

**Comment by warunicorn19** [comment]
@sudo-NithishKarthik if you could also provide your location.

**Comment by warunicorn19** [comment]
@NikhilSharma03 you can use the location Tamil Nadu, India

**Comment by NikhilSharma03** [comment]
Ok, Thank you.
