### ISSUE TITLE
[Community] Member Profile: Debopriya Bhattacharjee

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2064]
**Current Behavior**

@debo19  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @debo19  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @debo19 (https://github.com/debo19)
- Twitter: https://twitter.com/debopriyabh19
- LinkedIn: Debopriya Bhattacharjee (https://www.linkedin.com/in/debopriya-bhattacharjee-660861211)
- Link to profile picture: https://drive.google.com/file/d/1ARAfzko8yyhSmhXivnRKUx-5ZlcaYXWN/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@debo19 if you could please provide a small bio for yourself

**Comment by Tanuj22** [comment]
> @debo19 if you could please provide a small bio for yourself

also location

**Comment by NikhilSharma03** [comment]
@warunicorn19 I have added for nithish. Just waiting for his reply for location. In possible, can i work on this too?

**Comment by warunicorn19** [comment]
go ahead @NikhilSharma03

**Comment by debo19** [comment]
Bio: I am a student at Bits Pilani-Hyderabad, passionate about learning and exploring various Front-End technologies. I have gained good experience in web development by contributing to the projects here at Layer5. Engaging in this community has given me immense confidence about the work that I do. I look forward to learn from every opportunity I get here.

**Comment by debo19** [comment]
Location: Hyderabad, India
