### ISSUE TITLE
Document contributor instructions for blog posts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2071]
**Current Behavior**
https://layer5.io/blog encourages blog posts from contributors and community members.

**Desired Situation**
The current [set of contributor instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) do not have a section dedicated to how to contribute a blog post. 

Please document these contributor instructions, including any commonly used CSS styles, how `{Link}` vs `<a>` works, the common post sign-off and so on.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by CIPHERTron** [comment]
Can I know more about this issue, @leecalcote @warunicorn19 ❓

**Comment by Jordan-Rob** [comment]
hi @leecalcote can I work on this

**Comment by nerdynikhil** [comment]
@leecalcote I wish to take up this one.
