### ISSUE TITLE
[Blog] Request for new post: Using Aliases with Meshery CLI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2072]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** Using Aliases with Meshery CLI
**Topic:** tips and tricks of using `mesheryctl`
**Core points to convey in the post:** 
1. What CLI aliases are.
1. What commands are used more frequently based on analysis of 1,500 times of use by one user.
1. Why https://github.com/layer5io/mesheryctl-aliases was created and how to setup these aliases.
1. Example uses.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@josephmidura and @bariqhibat, this could be a tag team-style blog post from the two of you, if it piques interest.

**Comment by bariqhibat** [comment]
> @josephmidura and @bariqhibat, this could be a tag team-style blog post from the two of you, if it piques interest.

Sure I can definitely do a write-up 😀

**Comment by josephmidura** [comment]
Let me know if you need help @bariqhibat

**Comment by leecalcote** [comment]
@bariqhibat you might create a Google Doc in the community drive as both a way of drafting the post and of collaborating with @josephmidura

**Comment by bariqhibat** [comment]
> @bariqhibat you might create a Google Doc in the community drive as both a way of drafting the post and of collaborating with @josephmidura

That works too! Hey @josephmidura, I put the draft for the post [here](https://docs.google.com/document/d/1sH519ZVfB1xshnhz1cZw8Fxpq5zuy7WWml3j62G-Jqw/edit)

**Comment by josephmidura** [comment]
It looks like you're off to a good start @bariqhibat. I'm happy to take a look when you're finished.

**Comment by bariqhibat** [comment]
> It looks like you're off to a good start @bariqhibat. I'm happy to take a look when you're finished.

Hey Joem it should be good now. I do the write-up in markdown-style.

**Comment by josephmidura** [comment]
@bariqhibat Your draft has a solid example of how to use an alias with Meshery. I made a couple comments on the draft. Because you explained the example so well, it's easy for a reader to understand why aliases are useful.

How do you think analysis of the 1500 entry meshery history should be included? My initial thought is that the post could mention that the [aliases repo](https://github.com/layer5io/mesheryctl-aliases) includes 10 (15?) suggested aliases that the average user will appreciate.

**Comment by bariqhibat** [comment]
Hey @josephmidura, I've made some additions and changes according to your reviews. Could you check again [the docs](https://docs.google.com/document/d/1sH519ZVfB1xshnhz1cZw8Fxpq5zuy7WWml3j62G-Jqw/edit)?

**Comment by josephmidura** [comment]
@bariqhibat Hey Bariq I think it looks great. I left a comment on the chart, but I think the content it largely ready to format like the other blog entries.

**Comment by Mr-DG-Wick** [comment]
What is the progress on this one :) ?

**Comment by warunicorn19** [comment]
@bariqhibat the blog is good to publish right?

**Comment by josephmidura** [comment]
I'll put the draft onto GitHub and we can review from there.

**Comment by warunicorn19** [comment]
Alright sounds good, thank you @josephmidura

**Comment by josephmidura** [comment]
@Mr-DG-Wick @warunicorn19 Unfortunately I started a new job recently and don't now to work on this issue if @bariqhibat abandoned it. This issue may need to be assigned to someone else.

**Comment by bariqhibat** [comment]
> 

I'm pretty sure last time I talked with @warunicorn19, the document is ready to be published. Should we push this forward now?

**Comment by leecalcote** [comment]
@josephmidura I completely understand. Thank you for this note. 👍 We're here when routine settles into your new role.

**Comment by leecalcote** [comment]
> I'm pretty sure last time I talked with @warunicorn19, the document is ready to be published. Should we push this forward now?

Yes, please.

**Comment by josephmidura** [comment]
@leecalcote I'm looking forward to getting involved with Layer5 again soon.
