### ISSUE TITLE
Merge the Handbook  and side menu

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2075]
**Description**
Currently,  the handbook has a first page that makes it hide the main content of the handbook. 

**Expected Behavior**
- We need the handbook header and the side menu to appear on the same page, while users navigate the items on the side menu. 
- Also, the selected menu should be highlighted and bold upon selection.
**Screenshots**
![Screenshot 2021-08-11 at 21 15 32](https://user-images.githubusercontent.com/62384659/129098931-4de6ad49-82cf-4181-9dc0-392ed67de841.png)

**Enviroment:**
- Host OS: 
-o help explain your problem. -->Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by kg-kartik** [comment]
Can i pick up this issue?

**Comment by warunicorn19** [comment]
here you go @kg-kartik !

**Comment by Anita-ihuman** [comment]
@kg-kartik any the update on this ?

**Comment by mohankumar27** [comment]
Is this issue still open. Can i take it up ?

**Comment by kg-kartik** [comment]
Sorry for the delay, I will be fixing the issue in a day or two.

**Comment by warunicorn19** [comment]
@kg-kartik the first point of this issue has already been solved, if you could just execute the 2nd point.

**Comment by kg-kartik** [comment]
Okay, I will fix it as soon as possible

**Comment by warunicorn19** [comment]
@kg-kartik any updates?

**Comment by kg-kartik** [comment]
@warunicorn19 Will raise a PR by end of the day!
