### ISSUE TITLE
Move the  Item header in handbook

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2076]
**Description**
Currently, the side menu Header is over the entire items where "Community Handbook " should be.

**Expected Behavior**
The Header for each selected Side menu item should appear just over the content of the selected menu and not on the Blue-green background as seen in the image below.

**Screenshots**
![Screenshot 2021-08-11 at 21 35 47](https://user-images.githubusercontent.com/62384659/129099853-af7df215-b8ff-4561-9e00-cfe29de1dcd3.png)

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by calicomills** [comment]
Hi First timer here!..Can i claim this?

**Comment by warunicorn19** [comment]
For sure @calicomills ✌️.

**Comment by calicomills** [comment]
ok..Thanks! @warunicorn19

**Comment by calicomills** [comment]
Just a suggestion @Anita-ihuman, Wouldn't it be better to just "highlight" the selection on the menu, than display the menu item again above the content, we can avoid the redundancy.

**Comment by Anita-ihuman** [comment]
We can try this and see how it looks.
Currently there is no design layout to best explain this. @calicomills

**Comment by calicomills** [comment]
![image](https://user-images.githubusercontent.com/24970675/129400434-edaad77a-965f-4845-8be0-f4cfb818cc98.png)
How does this look?..I will in the mean time try to get it like I mentioned in my suggestion.(Looks like that's trickier than i first expected)

**Comment by warunicorn19** [comment]
I think it looked better before.

**Comment by Anita-ihuman** [comment]
Looks a lot better,
Alright the heading could use padding at the bottom.
Although,I think instead leaving the spot where the heading was previously, you can  put “Community Handbook “ there to be consistently fixed.

**Comment by calicomills** [comment]
![image](https://user-images.githubusercontent.com/24970675/129408106-bcadfc04-e5e8-419b-8a8f-b68848de348f.png)
@Anita-ihuman I made the changes you suggested.

**Comment by Anita-ihuman** [comment]
Yeah this looks great.

you might want to make a Pull because there was recently a few changes to the side menu, so you won’t have any merge conflict.

**Comment by calicomills** [comment]
Please review. @Anita-ihuman #2085

**Comment by calicomills** [comment]
Could you please review the changes. @Anita-ihuman @leecalcote

**Comment by warunicorn19** [comment]
issue seems to be fixed already.
