### ISSUE TITLE
Increase side menu width

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2077]
**Description**
The side menu appears to be compressed and this has caused the text to break

**Expected Behavior**
- Increase the width of the side menu for the community handbook.
-  remove `margin-inline-end: 75rem;` for this side menu
- Rename "Handbook" to "Table of Content"

**Screenshots**

![Screenshot 2021-08-11 at 21 45 34](https://user-images.githubusercontent.com/62384659/129101215-48cc7380-3e92-41d9-b2fc-cada32f2ff1e.png)

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by shayaan-absar** [comment]
Hi, I'm new to opensource and would like to contribute if that's okay.

**Comment by d-cryptic** [comment]
Hey @Anita-ihuman @leecalcote , I want to contribute to this issue. I think this issue can be solved only by CSS, is there any other requirement?

**Comment by Anita-ihuman** [comment]
Sure @d-cryptic go ahead

**Comment by d-cryptic** [comment]
Ok thanks

**Comment by calicomills** [comment]
Hi @Anita-ihuman @leecalcote, first timer here, Can i give it a shot? Started learning CSS recently.

**Comment by warunicorn19** [comment]
@calicomills seems like someone is already working on this, why don't you have a look at other issues with this label [Help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+)

**Comment by leecalcote** [comment]
@calicomills don't let this discourage you. There's pleeeeenty more where this comes from. We just went over a number of similar issues on today's Newcomers call. We'd love to have you join in --> https://meet.layer5.io - to that call or any of the calls.

**Comment by calicomills** [comment]
> 
> 
> @calicomills seems like someone is already working on this, why don't you have a look at other issues with this label [Help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+)

Thanks..I will check this out!

**Comment by warunicorn19** [comment]
That's great to hear 😃!

**Comment by d-cryptic** [comment]
Hey, I have tried to check the changes on chrome developer console and removed the `margin-inline-end` property and changed the headline to "table of content". Do you want to add more  spacing or width to the side bar?

![image](https://user-images.githubusercontent.com/52271502/129310820-b40b9fac-2f3f-40a7-9441-5a48a0562254.png)

**Comment by Anita-ihuman** [comment]
This looks a lot better. I don't think there is need for additional space there.

**Comment by d-cryptic** [comment]
Hey, I initiated a pull request, will you please review it!
