### ISSUE TITLE
[Website] Handbook not mobile responsive

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2078]
**Description**
The handbook is not is mobile responsive.

**Expected Behavior**
It should be visible in all the views.

**Screenshots**
![Screenshot_20210812-115844](https://user-images.githubusercontent.com/53532328/129150242-a2e14bad-714b-4616-b133-e33e0bf8f319.jpg)

**Enviroment:**
- Host OS: MacOs 
- Browser:  Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by NikhilSharma03** [comment]
@warunicorn19 If possible would love to work on this too.

**Comment by warunicorn19** [comment]
Go ahead @NikhilSharma03
