### ISSUE TITLE
Issue in NewComers meeting minutes

### ISSUE THREAD

**Issue by Jassi10000** [layer5io/layer5#2080]
**Description**

The Newcomers meeting minutes link on https://layer5.io/community/calendar is pointing to the wrong google doc.

**Expected Behavior**

The link should point to correct Google Doc

**Screenshots**

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Jassi10000** [comment]
@Abiola-Farounbi I want to work on this , Lee has already told me to

**Comment by Abiola-Farounbi** [comment]
> 
> 
> @Abiola-Farounbi I want to work on this , @leecalcote has already told me to work on this
> and this issue is for newbies as told by him

okay, good luck with it 😎

**Comment by Jassi10000** [comment]
Ahh , that was a nice coincidence 
@Abiola-Farounbi Nice to meet you

**Comment by Jassi10000** [comment]
> > @Abiola-Farounbi I want to work on this , @leecalcote has already told me to work on this
> > and this issue is for newbies as told by him
> 
> okay, good luck with it 😎

Thanks @Abiola-Farounbi 😀🤘
