### ISSUE TITLE
[Site] Handbook 

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2082]
**Current Behavior**
The entire handbook uses styling in each page as well as a stylesheet, without the use of common classes.
Also, due to this some pages are not mobile responsive while others are.

**Desired Situation**
Create common classes and a single style sheet for the entire handbook so that it is easier to work with.
Also, add mobile responsivness

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thanks for this. Let's note that the community handbook is a sub-section of the overall site (a collection of pages) and that while it might have some specific CSS classes for this collection, it should seek to source from a common, universal set first.

We need to better define that common, universal set. I’m tagging others to coordinate with: @Nikhil-Ladha @Tanuj22 @Jashpatel1. Part of my issue of being able to get blog posts out quickly is a lack of centralized, documented (approved), responsive classes.
