### ISSUE TITLE
Project's name are not responsive in small screen device of layer5 website

### ISSUE THREAD

**Issue by ishitakeshawani** [layer5io/layer5#2086]
**Description**
These project names do not look proper in small screen devices.

**Screenshots**
|![Screen Shot 2021-08-14 at 12 03 53](https://user-images.githubusercontent.com/50510726/129437678-e06fcef8-4b83-466b-b7ac-fe39e135f430.png) |
|-|

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
@ishitakeshawani I think this is the design itself, but do you want to try seeing if you can fit it inside the screen?

**Comment by ishitakeshawani** [comment]
Yes, I can try to fit inside the screen.

**Comment by claire-me** [comment]
@ishitakeshawani Can I fix this issue?

**Comment by AbhishekBhatt072003** [comment]
Hello @warunicorn19 
I wanted to fix this issue. This can be easily corrected with CSS. If you allow me then I can give this a Go.

**Comment by warunicorn19** [comment]
@ishitakeshawani  @claire-me  @AbhishekBhatt072003 hey guys, I'm actually going to close this issue, I've taken a look into this and the thing is that this is the design of the website itself, so there's nothing to fix. Please take a look at the other issues with the [Help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+label%3A%22help+wanted%22+) tag😃.

**Comment by leecalcote** [comment]
@ishitakeshawani its fantastic to see initiative like this taken to file an issue when errors or potential enhancements are recognized. Thank you for this. 

In this particular case, the logo size shown in the screen major is according to design. To confirm this, will you have a look at the components page in the Layer5 Figma designfile?

If the screenshot and the design are the same (which I believe that they are), you can safely close this issue.

**Comment by leecalcote** [comment]
Oh, oops. I'm just now seeing @warunicorn19's last comment and the fact that this issue is already closed. Very good. Carry on as you were, folks.
