### ISSUE TITLE
[Tutorial Request] Newcomers Meeting: "Working with Meshery Docs and Jekyll"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2087]
**Request**
Provide a "Working with Meshery Docs and Jekyll" session in the Newcomers' meeting. This should include example use of docs features like `{% include alert.html %}`.

See existing resources on https://layer5.io/community/newcomers (this tutorial will be posted there as when delivered) and [tutorial tracking spreadsheet](https://docs.google.com/spreadsheets/d/1IY9mxu8nbRBsrlMPDNY5p2yyQf0YOjppi81R6O-F4Ng/edit#gid=891834841).

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
@leecalcote is this for today or can we do this next week ?

**Comment by leecalcote** [comment]
@alphaX86 you might be interested to do this.

**Comment by alphaX86** [comment]
When it'd be?

**Comment by leecalcote** [comment]
// @Anita-ihuman

**Comment by alphaX86** [comment]
I need more details regarding this one...

**Comment by Anita-ihuman** [comment]
We just need a tutorial 30minutes at most, during the newcomers session 
On Meshery docs and Jekyll.

**Comment by alphaX86** [comment]
Ok.... when it'd be? This week or upcoming one? Plus, do we have slides for it or should I make one?

**Comment by Anita-ihuman** [comment]
You are to make the slides. How about you tell me a day that works for you BETWEEN this week or upcoming one?

**Comment by alphaX86** [comment]
Well, I'm bit free tomorrow due to rural elections in state... So, I'll try to utilize and make it this week

**Comment by Anita-ihuman** [comment]
Perfect, Will make sure I put that in the reminder ahead of Thursday

**Comment by alphaX86** [comment]
Initial draft of the slide is made here.. (https://docs.google.com/presentation/d/1GhJH3YF5mBeYX7I7ItEd-EbUmk1cnn3BdK1X230kwII/edit?usp=sharing) 

If there is any changes needed or like can be added, let me know :)

**Comment by alphaX86** [comment]
No issues 👍 @warunicorn19
