### ISSUE TITLE
[Community] Member Profile: Add Meshery badge to Aditi Ahuja's profile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2100]
**Current Behavior**

@metonymic-smokey has been a consistent mesheryctl contributor. 

**Desired Situation**
Aditi Ahuja's profile (https://layer5.io/community/members/aditi-ahuja) should bear the `meshery` badge in recognition of her efforts.

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by ANURAG-PATHAK** [comment]
Hey @leecalcote, I would like to work on this issue

**Comment by warunicorn19** [comment]
Go for it @ANURAG-PATHAK !

**Comment by ANURAG-PATHAK** [comment]
> Go for it @ANURAG-PATHAK !

Thank you @warunicorn19
