### ISSUE TITLE
[Community] Member Profile: Badges for Adithya Chatterjee and Sayantan Bose

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2101]
**Current Behavior**

@warunicorn19 and @sayantan1413 have both donned a community manager hat and have been actively helping steward Layer5 community.

**Desired Situation**
Let's recognize @warunicorn19 and @sayantan1413  as a community managers by adding the `community` badge to their https://layer5.io/community/members profiles.

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by CIPHERTron** [comment]
Heyy @leecalcote @warunicorn19 @sayantan1413 is this issue up for grab?
I would love to work on it 🚀

**Comment by warunicorn19** [comment]
Go for it! @CIPHERTron

**Comment by CIPHERTron** [comment]
Thank you so much @warunicorn19 🙌🏻

**Comment by CIPHERTron** [comment]
I was gonna send a PR just now but I see this issue has been already addressed 😅 
I'll work on some other issues now. Thanks, @warunicorn19 for assigning me this!

**Comment by warunicorn19** [comment]
Uh oh! Sorry for the miscommunication. @ANURAG-PATHAK from next if you could please check if someone is already working on an issue before putting in a PR it'll be much appreciated 😊

**Comment by ANURAG-PATHAK** [comment]
> Uh oh! Sorry for the miscommunication. @ANURAG-PATHAK from next if you could please check if someone is already working on an issue before putting in a PR it'll be much appreciated 😊

I am sorry @warunicorn19 @CIPHERTron from next time I will take care of it.
