### ISSUE TITLE
Readme Issue

### ISSUE THREAD

**Issue by LifeofDan-EL** [layer5io/layer5#2104]
**Description**
The Badges section of the Contributing Readme has the ImageHub badge with the wrong name attached to it.

**Expected Behavior**
It's supposed to be ImageHub instead of Layer5.
 

**Screenshots**
![image](https://user-images.githubusercontent.com/45920948/130336281-f988d253-8f3d-431b-a576-cd4d4413a468.png)

**Comment by ANURAG-PATHAK** [comment]
I would like to work on this issue

**Comment by LifeofDan-EL** [comment]
> I would like to work on this issue

Sure, feel free to go for it.

**Comment by ANURAG-PATHAK** [comment]
> > I would like to work on this issue
> 
> Sure, feel free to go for it.

thank you, please assign me this issue.

**Comment by LifeofDan-EL** [comment]
I'm not in charge of assigning though but @Anita-ihuman is. Everyone is welcomed to contribute. just go through our contribution guide.

**Comment by ANURAG-PATHAK** [comment]
> I'm not in charge of assigning though but @Anita-ihuman is. Everyone is welcomed to contribute. just go through our contribution guide.

okay, thank you ☺️

**Comment by ANURAG-PATHAK** [comment]
<img width="1288" alt="Screenshot 2021-08-22 at 6 18 24 AM" src="https://user-images.githubusercontent.com/81188792/130338385-0bb170b8-5ed0-44ed-a6e8-66d67413db7c.png">


Is it the desired change? should I make a PR with this change?

**Comment by LifeofDan-EL** [comment]
I believe you should capitalize the first letter of community, then the hawk in GetNighthawk, then SMP. Looks great so far.

**Comment by ANURAG-PATHAK** [comment]
> I believe you should capitalize the first letter of community, then the hawk in GetNighthawk, then SMP. Looks great so far.

okay sure, thanks for the review

**Comment by ANURAG-PATHAK** [comment]
> I believe you should capitalize the first letter of community, then the hawk in GetNighthawk, then SMP. Looks great so far.

hey @LifeofDan-EL are you sure about capitalizing hawk in GetNighthawk because on the site I saw that there is no capitalizing of Hawk if you are sure about the change then confirm me I will do the same

**Comment by warunicorn19** [comment]
@ANURAG-PATHAK it's 'GetNighthawk', so no changes required ther.

**Comment by ANURAG-PATHAK** [comment]
> @ANURAG-PATHAK it's 'GetNighthawk', so no changes required ther.

okay thank you
