### ISSUE TITLE
Landscape: Create comparative spectrums for ease of contrasting service meshes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#211]
The service mesh landscape currently provides a repository of facts about service meshes (and related technologies). As an index of projects/products, it provides a simple list as  reference.

Based on its data, the service mesh landscape needs augmented to provide insightful guidance to visitors, through careful and accurate characterization of of service meshes represented alongside one another on comparative spectrums.

Comparative spectrums should be visual / graphical in nature such that their insight is understood by experts as well as layman. Comparative spectrums may include:

- Ease of Installation / Configuration
- Functionality 
- Flexibility
- Telemetry
- Scale

Each spectrum should have a caption describing the way in which viewers should interpret the characterization. It should capture any caveats and highlight any special considerations in the placement of a project along the spectrum.

_Inspiration_ 
Example of an opinionated comparison that can be used as inspiration for this enhancement of the service mesh landscape -[ Container Networking - Open Networking Innovation Forum](https://docs.google.com/presentation/d/1P6LzzG0_alAxshpdfLnix53S9WU4vjbpSCrHJQoWPqc/edit?usp=sharing) (slides 5 through 8)

*Future Comparative Spectrums:*
- Control Plane Performance
- Data Plane Performance

**Comment by Silvyre** [comment]
Looking into this!

**Comment by leecalcote** [comment]
This has been fully merged. No spectrums have been made public, yet, but they will be within a week's time.

**Comment by leecalcote** [comment]
Thank you, @Silvyre! We have finally merged your spectrums branch and are beginning to publish comparative spectrums now.
