### ISSUE TITLE
[Handbook] Change Heading

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2111]
**Description**
Change the heading from "About" to "Community Handbook"

**Screenshots**
<img width="1432" alt="Screenshot 2021-08-23 at 11 01 51 PM" src="https://user-images.githubusercontent.com/53532328/130491391-f16e441b-13e8-4ad5-936a-ca9a353667ea.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by 5hraddha** [comment]
Could you please assign the issue to me?

**Comment by Ishan2077** [comment]
Hi @warunicorn19 . I would love to contribute!

**Comment by warunicorn19** [comment]
@Ishan2077 sorry, I'll have to assign this issue to @5hraddha because she commented first. Why don't you take a look at some other issues with the [Help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+org%3Alayer5io+label%3A%22help+wanted%22+) label

**Comment by 5hraddha** [comment]
Thank you @warunicorn19.

**Comment by 5hraddha** [comment]
Hi @warunicorn19, I have updated the heading and submitted a PR. Could you please have a review? Thank you!!

**Comment by warunicorn19** [comment]
Yes @5hraddha, just waiting for a maintainer to approve the workflow😅.
