### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2112]
**Description**
The current issue template for bug report has some information that is not required.

**Expected Behavior**
Remove "Meshery Version", "Kubernetes Version" and the "To Reproduce" section.
Also, fix the spelling of "Environment".

**Screenshots**
<img width="559" alt="Screenshot 2021-08-23 at 11 07 48 PM" src="https://user-images.githubusercontent.com/53532328/130492805-edbbbf7d-9739-4223-9aae-20c4e103ef12.png">

**Enviroment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: 

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Ishan2077** [comment]
Hi @warunicorn19  ! Can I take this issue?

**Comment by sayantan1413** [comment]
Yeah sure @Ishan2077 go ahead!

**Comment by Ishan2077** [comment]
@sayantan1413 thanks for assigning me the issue! I am trying to clone the repository and trying to install the dependency: ```
```
F:\GnuWin32\bin\make.exe setup-libs
make: *** No rule to make target `setup-libs'.  Stop.
```
Can you please assist me on how I can fix it. Thanks in advance!

**Comment by warunicorn19** [comment]
@Ishan2077 have you installed `make` on your machine?

**Comment by Ishan2077** [comment]
> @Ishan2077 have you installed `make` on your machine?

Yes @warunicorn19 . I have installed `make` on my machine

**Comment by sayantan1413** [comment]
Hey @Ishan2077 you have to move to the Layer5 folder and then install the dependencies.

**Comment by warunicorn19** [comment]
@Ishan2077 i think you've not gone into the Layer5 file

**Comment by sayantan1413** [comment]
And @Ishan2077 for this issue you have to change it here https://github.com/layer5io/layer5/tree/master/.github/ISSUE_TEMPLATE ✔️

**Comment by Ishan2077** [comment]
@sayantan1413 @warunicorn19 I apologize. I was using it in the wrong folder. Thanks for your help!

**Comment by warunicorn19** [comment]
@Ishan2077 any updates?

**Comment by hp77-creator** [comment]
Can I take this one?

**Comment by hp77-creator** [comment]
should I remove the whole `To reproduce` section?

**Comment by warunicorn19** [comment]
Yup @hp77-creator
