### ISSUE TITLE
[Site] Add anchor tag to the meetings table

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2114]
**Description**
The meetings table on layer.io doesn't get redirected to.

**Expected Behavior**
When a user goes to meet.layer5.io it should redirect to the meetings table below the calender.

**Screenshots**

<img width="1440" alt="Screenshot 2021-08-24 at 2 00 10 AM" src="https://user-images.githubusercontent.com/53532328/130515613-aef566f4-b29b-4360-9b58-501a7bcc53c5.png">

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by frankiefab100** [comment]
Please where can I locate this. I want to fix it

**Comment by warunicorn19** [comment]
Hey @frankiefab100, you'll be to find this [here](https://github.com/layer5io/layer5/blob/05292f93d8e39ceb64f6e634b970281ab6f57bbd/src/components/MeetInfo-Table/index.js). Please be sure to through the [Contibuting docs](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#contributor-instructions)😃.

**Comment by frankiefab100** [comment]
Alright, thanks

**Comment by Hell4U** [comment]
Just wanna ask is the issue resolved ?

**Comment by Tanuj22** [comment]
@frankiefab100 any updates here?

**Comment by Tanuj22** [comment]
@Hell4U or @eboriley please go ahead with this

**Comment by frankiefab100** [comment]
@Tanuj22 still trying to figure it out

**Comment by eboriley** [comment]
> @Hell4U or @eboriley please go ahead with this
A little lost here, I could use some help
where exactly should meet.layer5.io sit on the page 🤔

**Comment by warunicorn19** [comment]
@eboriley you'd have to add an anchor to the `Layer5 Meetings` header so that meet.layer5.io leads directly to that table below. you could refer to this https://github.com/layer5io/layer5/pull/2126#issuecomment-907087125

**Comment by eboriley** [comment]
Thanks for clarifying

**Comment by Nikhil-Ladha** [comment]
Fixed in #2185
