### ISSUE TITLE
Community: Write Hacktoberfest blog post

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#212]
A number of Hacktoberfest participants have joined the Layer5 community as contributors. A write-up of their contributions, impact and experience would make for a nice reference for these contributors and elevate their works.

**Comment by gunjanmimo** [comment]
Sir, I wrote some lines about Hacktoberfest 2019 and Meshery.
https://medium.com/@gunjanpaul/my-first-ever-hacktoberfest-contributor-to-meshery-a5f888fc3dbf
fixes #212

**Comment by leecalcote** [comment]
@gunjanmimo, [mission accomplished](https://twitter.com/lcalcote/status/1184678094675812352). Thank you! I'm going to leave this PR open as I'm hoping 

1) I'm hoping others might have drafts in the works.
2) I'd like to get a consolidated blog post going on layer5.io about the collective set of contributions (*ahem*, @Silvyre, @mcastre and others)

**Comment by Ruth-ikegah** [comment]
@leecalcote looks like something I want to do starting with my own experience blog post.
