### ISSUE TITLE
Enhancing the getting started section

### ISSUE THREAD

**Issue by DelusionalOptimist** [layer5io/layer5#2127]
**Description**
The steps for getting started and setting up Meshery at https://layer5.io/service-mesh-management/meshery/getting-started are not clear enough. The current steps based on the "platform" don't offer much distinction between operating systems and type of Kubernetes clusters.
This might lead to users missing important steps specific to their method of deploying Meshery.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by shahkushal38** [comment]
Hey @DelusionalOptimist , can I take up this issue?

**Comment by DelusionalOptimist** [comment]
@leecalcote can you confirm if this is same as https://github.com/layer5io/layer5/issues/2128 ?

**Comment by shahkushal38** [comment]
Hello @leecalcote  and @DelusionalOptimist  I have made small changes in CSS and HTML of Meshery-platforms -> index.js section so as to  solve the problem of command getting cropped - 
1) In our original site the command for different platforms gets cropped for some reason - 

![Screenshot from 2021-08-31 11-50-12](https://user-images.githubusercontent.com/60709835/131452436-3d1891e5-54d0-4d58-9388-10f04fdf6e51.png)
2) Now After changes in CSS for it, the problem gets resolved - 

![Screenshot from 2021-08-31 11-50-29](https://user-images.githubusercontent.com/60709835/131452815-c615549b-3f48-4d9a-bd82-1e9c954c6553.png)

If this looks good to you'll can I make a PR for the same? 
It would be great for any advice, changes or recommendations from your end to enhance this section which I can work on.

**Comment by leecalcote** [comment]
> @leecalcote can you confirm if this is same as #2128 ?

@DelusionalOptimist you're right. # 1 in #2128 duplicates this issue (#2127). @debjani1413, my apologies, I didn't realize that we had duplicative issues. Will you please consider only implementing request # 2 in #2128?
