### ISSUE TITLE
Red underline under performance tests run value

### ISSUE THREAD

**Issue by gunjanmimo** [layer5io/layer5#213]
performance tests run value has red underline which is a little odd. change the red line to the black line.
![Screenshot (19)](https://user-images.githubusercontent.com/46948185/67111891-9de6b400-f1f3-11e9-919b-97a866dfc164.png)
[https://layer5.io/meshery/](url)

**Comment by ashiscs** [comment]
This issue is fixed and needs to be closed.

**Comment by gunjanmimo** [comment]
But now there is a blue curve underline

**Comment by ashiscs** [comment]
@gunjanmimo but the new color is matching with the background instead of previous one which was catching all our attention.

**Comment by leecalcote** [comment]
@gunjanmimo, while we do want attention called to the statistic, you're probably right that use of red was perhaps not the best color as to many, it indicates that something is wrong (e.g. a misspelling).
