### ISSUE TITLE
[UX] Homepage for the handbook

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2135]
**Description**
The current handbook doesn't have a landing page

**Expected Behavior**
A newly designed handbook landing page.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by NikhilSharma03** [comment]
@warunicorn19 Can I look into this?

**Comment by warunicorn19** [comment]
That'll be great @NikhilSharma03
