### ISSUE TITLE
[UI] change the bullet colors in handbook

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2136]
**Description**
The bullets used in the handbook are in kepel green as of now.

**Expected Behavior**
All the bullets should be changed to the charcoal. (please use from theme)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by shreyaansjain** [comment]
Can i work on this issue

**Comment by warunicorn19** [comment]
Go for it!
