### ISSUE TITLE
[UI][Handbook] Links redirecting to TOC components in mobile view

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2138]
**Description**
In mobile view, the link of components TOC are still active.

**Expected Behavior**
It shouldn't be.

**Screenshots**

https://user-images.githubusercontent.com/53532328/131344320-fde2e084-18be-4d65-b61d-202101fd4771.mov

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by StephNathai** [comment]
Hi, can I grab this issue?

**Comment by warunicorn19** [comment]
Sure @StephNathai.
