### ISSUE TITLE
Add Citrix CPX to service mesh landscape 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#214]
Hi @chiradeep, will you (or a member of your team) consider adding (via PR) a listing for Citrix CPX to the  [service mesh landscape](https://layer5.io/landscape)? We'd love to have an accurate listing of CPX in the Service Mesh Landscape. 

In following these [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md), you'll see that an update to the [meshes.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/meshes.yml) and [non-functional.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/non-functional.yml) file is all that is needed.

Thank you for considering this!

**Comment by dheerajng** [comment]
Hi @leecalcote @chiradeep, 
I've created below PR for the ask.
https://github.com/layer5io/layer5/pull/215

Thanks,
Dhiraj

**Comment by leecalcote** [comment]
Looking good, @dheerajng. Thanks for this update!
