### ISSUE TITLE
[UI] Add tooltip in Service Mesh Interface Compliance table

### ISSUE THREAD

**Issue by Meghana-12** [layer5io/layer5#2140]
**Description**
Only logos of the service meshes are provided in the Service Mesh Interface Compliance table, names aren't. I think is good to have a tooltip that displays the name of the mesh. 

**Expected Behavior**
When the user hovers on the service mesh logo, it should display the name of the mesh.

**Screenshots**
![Screenshot 2021-08-30 at 8 43 18 PM](https://user-images.githubusercontent.com/44519203/131361961-ed30edbc-3f36-450b-9275-511effa394fd.png)

**Environment:**
- Host OS: 
- Meshery Version: 
- Kubernetes Version: 
- Browser: Chrome

---

[Optional] **To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://layer5.io/service-mesh-landscape'

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by 5hraddha** [comment]
Hi @Meghana-12, I am interested in adding tooltip to the images. Could you please let know what are the names that you want to show on tooltip on the images? Thank you!!

**Comment by warunicorn19** [comment]
Yes @5hraddha those are the right names.
