### ISSUE TITLE
[Community] Member Profile: Meghana Varanasi

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2141]
**Current Behavior**

@Meghana-12  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Meghana-12  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Meghana-12 
- Twitter: meghana_cosmos (https://twitter.com/meghana_cosmos)
- LinkedIn: Meghana Varanasi (https://www.linkedin.com/in/meghana100/)
- Link to profile picture: https://ibb.co/Y0ptzwj

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Meghana-12** [comment]
Thanks a lot for this <3
