### ISSUE TITLE
[Community] Member Profile:

### ISSUE THREAD

**Issue by sayantan1413** [layer5io/layer5#2148]
**Current Behavior**

@Abhishek-kumar09  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Abhishek-kumar09 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Abhishek-kumar09
- Twitter: Abhi_dev_dude
- LinkedIn: abhishek-kr09
- Link to profile picture: https://avatars.githubusercontent.com/u/48255244

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sayantan1413** [comment]
Hey @Abhishek-kumar09 can you provide a bio and your location ?

**Comment by Abhishek-kumar09** [comment]
very auspicious day for me :smiley: Thanks @sayantan1413 

Bio:

I am an undergrad student from Delhi who loves to work on different open-source projects and their development. Thanks to all open source organisations that has groomed me with providing better knowledge and practical implementation of every problem. Have been part of open source orgs like Checkstyle Java, Codeforcause org and Layer5 Meshery that has taught me 90% I know.
Starting with Web development technologies like React, Node, Express and Nest, I have been growing interest towards Linux, containers and Kubernetes. 
Hit me hard on socials to connect and grow together.

Location: New Delhi, India

**Comment by vishal-codes** [comment]
@sayantan1413 Can I work on this?
Hello @Abhishek-kumar09  bhaiya hope u r doing great and kudos!!!! for your efforts🎉

**Comment by vishal-codes** [comment]
@sayantan1413 , @josephmidura Which all badges should I assign to @Abhishek-kumar09 ?

**Comment by josephmidura** [comment]
@vishal-codes The issue doesn't mention badges. You're just creating the contributor profile.

**Comment by vishal-codes** [comment]
> @vishal-codes The issue doesn't mention badges. You're just creating the contributor profile.

Okaay. Just created a <a href="https://github.com/layer5io/layer5/pull/2156">pr</a> which will solve this.
