### ISSUE TITLE
[CI] Updates label `issue/remind` for PRs

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2149]
**Current Behavior**
Currently, the label `issue/remind` doesn't work for PRs

**Desired Situation**
The label should work for PRs as well.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by MukulKolpe** [comment]
Hey @warunicorn19 can I work on this issue?

**Comment by warunicorn19** [comment]
Sure thing!

**Comment by MukulKolpe** [comment]
Hey @warunicorn19, I should work in [label-commenter-config.yml](https://github.com/layer5io/layer5/blob/master/.github/label-commenter-config.yml) 
 right??

**Comment by sayantan1413** [comment]
Yes @MukulKolpe !
