### ISSUE TITLE
[handbook] Update the content of About, Community & Contributing

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2152]
**Current Behavior**
The current [handbook](https://layer5.io/community/handbook) online is missing some content

**Desired Behavior**
Update the About, Community & Contributing sections with the [new draft](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o/edit#heading=h.vtdtai5j3tq7) on the community handbook

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Goodiec** [comment]
@Anita-ihuman, please assign this to me.

**Comment by warunicorn19** [comment]
Hey, @Goodiec any updates on this?

**Comment by Goodiec** [comment]
> Hey, @Goodiec any updates on this?

Yes, I'm working on it. Sorry I took this long.

**Comment by warunicorn19** [comment]
@Goodiec no problem at all, just checking up😄.

**Comment by Anita-ihuman** [comment]
@Goodiec while you are doing that, please make sure you use the general font used across the layer5 site.
Also, there should be a little padding below each header. (Right now it looks too close to the text).

**Comment by Goodiec** [comment]
> @Goodiec while you are doing that, please make sure you use the general font used across the layer5 site.
> Also, there should be a little padding below each header. (Right now it looks too close to the text).

Alright, thank you.
