### ISSUE TITLE
[Handbook] Update the Learn Layer5, Connect with us &  Code of Conduct sections

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2154]
**Current Behavior**
These sections on the [site](https://layer5.io/community/handbook) are missing some content from the new handbook draft

**Desired Behavior**
Update the Learn Layer5, Connect with us &  Code of Conduct sections according to the details existing in the [new handbook](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o/edit#heading=h.vtdtai5j3tq7)  draft.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by 5hraddha** [comment]
Hi @A, I would like to work on this. Could you please assign it to me?

**Comment by debo19** [comment]
Go ahead @5hraddha

**Comment by 5hraddha** [comment]
Hey @debo19, could you please grant me permission to view the [new handbook](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o/edit#heading=h.vtdtai5j3tq7) draft. I have raised the request for the same. Thank you!

**Comment by Tanuj22** [comment]
@5hraddha fill this https://layer5.io/newcomer/ to get access. And if you haven't already you are most welcome to join http://slack.layer5.io.
