### ISSUE TITLE
[Community] Member Profile: Suhani Agarwal

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2155]
**Current Behavior**

@suhaniii  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @suhaniii  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @suhaniii 
- Twitter: 
- LinkedIn: suhani-agarwal (https://www.linkedin.com/in/suhani-agarwal/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

The CONTRIBUTING.md file has a "Common Types of Site Updates" section with detailed examples to follow here.[CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@suhaniii if you could just provide a couple of things:
1.  picture
2.  bio
3. location
4. Twitter handle(if you have one).

Also, congrats @suhaniii 😁.

**Comment by vishal-codes** [comment]
> @suhaniii if you could just provide a couple of things:
> 
>     1. picture
> 
>     2. bio
> 
>     3. location
> 
>     4. Twitter handle(if you have one).
> 
> 
> Also, congrats @suhaniii grin.

hey @warunicorn19 once suhani provides the requested information then can I start working on this?

**Comment by warunicorn19** [comment]
sure @vishal-codes

**Comment by suhaniii** [comment]
@warunicorn19 
Here is the link to pic - https://drive.google.com/file/d/1-bblDGwi2R68SscYb-Ct82Vx1ZKPVMXY/view?usp=sharing
Bio - "I am a Devops Engineer. Passionate about learning and upskilling myself.
I like to read books, explore new places and contributing to open source projects. In short I love adventures."
Location - Bangalore, India

**Comment by warunicorn19** [comment]
Thanks @suhaniii , @vishal-codes let's get this done😄.

**Comment by vishal-codes** [comment]
> Thanks @suhaniii , @vishal-codes let's get this donesmile.

have created a pr 
🚀

**Comment by vishal-codes** [comment]
@warunicorn19 can this <a href="https://github.com/layer5io/layer5/pull/2156">pr<a> be merged?

**Comment by vishal-codes** [comment]
Hey @warunicorn19 sorry for the trouble caused coz of me :( But this time I made correct changes and have opened a pr

**Comment by warunicorn19** [comment]
@vishal-codes no problem at all😄.
