### ISSUE TITLE
[Community] Member Profile: Acknowledging MeshMate Aditya Chatterjee

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2166]
**Current Behavior**

Aditya Chatterjee (@warunicorn19) has been invited to the Layer5 MeshMate program. As of today, Sept. 8th, 2021, Aditya is the newest MeshMate to join the existing cohort.

**Desired Situation**
Let's recognize @warunicorn19 as a MeshMate by updating [his profile](https://layer5.io/community/members/aditya-chatterjee) on https://layer5.io/community/members with the MeshMate badge and adding his profile to the /community/meshmates page.

_A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)_

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by CIPHERTron** [comment]
Heyy @leecalcote @warunicorn19  can I work on it? Thanks!

**Comment by warunicorn19** [comment]
Sure @CIPHERTron.
