### ISSUE TITLE
[Learn] Add Traefik Mesh lab

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2167]
**Current Behavior**
The newly created Traefik Mesh lab hasn't been added to https://layer5.io/learn

**Desired Situation**
Let's put up the Traefik Mesh lab [here]( https://layer5.io/learn).

https://github.com/layer5io/layer5/blob/master/src/sections/Learn/Service-Mesh-Labs/courseData.js

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Manish-210** [comment]
Hey @warunicorn19, can I work on this?

**Comment by warunicorn19** [comment]
Yes sure @Manish-210, my bad 😅.

**Comment by leecalcote** [comment]
@Manish-210 how is this coming along? 

@warunicorn19 the deadline for this lab to be posted is this Friday. 

@Manish-210, if you're not able to get a PR up by Wednesday, that's no problem (you can grab another issue). @warunicorn19 will take assignment of this issue.

**Comment by Manish-210** [comment]
Yeah, sorry for the late response :disappointed: 
Actually I am confused little bit, How to add traefik-white.svg image? There is only traefik.svg

**Comment by warunicorn19** [comment]
Copy the `traefik.svg` and paste it again in the same folder and rename it `traefik-white.svg` then in the svg you'll be able to see the `color` or `fill` tag and change that to #ffffff.

**Comment by Manish-210** [comment]
![Screenshot from 2021-09-14 17-40-52](https://user-images.githubusercontent.com/58730178/133257340-464e1f12-af86-45e6-8644-0ca01610ea31.png)

Thanks @warunicorn19 , just one more issue when I click on http://localhost:8000/learn/service-mesh-labs/working-with-meshery-and-traefik the link path is not valid, I know I have to add the traefik path but I am not able to figure out where it should be added.

**Comment by warunicorn19** [comment]
🤔even I'm not too sure about this, @Nikhil-Ladha @Tanuj22 could you guys please help here.

**Comment by Nikhil-Ladha** [comment]
The JS file where you need to add the link has been mentioned in the issue description itself. Isn't that working?

**Comment by Manish-210** [comment]
Yeah, I have added the link in the courseData.js file.
Everything works fine untill I click on the right-side top link  http://localhost:8000/learn/service-mesh-labs/working-with-meshery-and-traefik 

![Screenshot from 2021-09-14 20-49-43](https://user-images.githubusercontent.com/58730178/133286351-2164e494-8810-408f-8e38-3ae4475575eb.png)

**Comment by Nikhil-Ladha** [comment]
Create the PR and tag me, I will check it out.

**Comment by Tanuj22** [comment]
@Manish-210 my hunch is you haven't added the lab here https://github.com/layer5io/layer5/tree/master/src/collections/service-mesh-labs

**Comment by Manish-210** [comment]
Thanks,@Nikhil-Ladha and @Tanuj22 (I haven't added the lab file in collections). It is working fine now.
