### ISSUE TITLE
[Gatsby] Two routes that match both page and redirect.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2170]
**Description**
While building the site, the following warning is displayed. The negative affect of these redirects can be seen in Safari, where the redirects seem to be circular in nature (endless).

**Screenshots**

```
warn There are routes that match both page and redirect. It will result in page not being accessible; this is probably not intentional:
 - page: "/blog/community/she-code-africa-contributhon-boot-camp-report" and redirect: "/blog/community/she-code-africa-contributhon-boot-camp-report" ->
"/blog/community/she-code-africa-contributhon-boot-camp-report"
 - page: "/programs/communitybridge/2020" and redirect: "/programs/communitybridge/2020/" -> "/programs/communitybridge/2020"
 ```

**Environment:**
- Host OS: Mac
- Browser: Safari

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@riteshsp2000 an item that might be of interest.

**Comment by riteshsp2000** [comment]
Yeah sure... ill get onto this.

**Comment by san-coding** [comment]
Hey, is this issue still open ? @riteshsp2000

**Comment by riteshsp2000** [comment]
Yeah... im actually on it. Was a bit occupied with university stuff, will get this on soon

**Comment by riteshsp2000** [comment]
@san-coding You can work on this, I'd be a bit busy with some university stuff and won't be able to look into this for the week.

**Comment by san-coding** [comment]
Thanks, could you give any context on how I could fix this ?

**Comment by san-coding** [comment]
My understanding of the issue : 
page `/blog/community/she-code-africa-contributhon-boot-camp-report` (Redirects to the same page ->)
`/blog/community/she-code-africa-contributhon-boot-camp-report`

which results in endless redirects

similarly 

 page: `/programs/communitybridge/2020`  (Redirects to the same page ->) `/programs/communitybridge/2020/` , which also results in endless redirect loop

is this issue only present in safari ?

**Comment by san-coding** [comment]
I think this is where the problem lies for [link to file](https://github.com/layer5io/layer5/blob/16a8266cec5bf079bd9456ca784ebc36d9845487/src/collections/programs/communitybridge/index.mdx)

**Comment by Zain-Muiz** [comment]
@san-coding , I'm not quite sure what the issue could be. Maybe @riteshsp2000 or @warunicorn19 could help you better here.

**Comment by Nikhil-Ladha** [comment]
I think the issue doesn't exist anymore. Could any of you build and confirm once?

**Comment by san-coding** [comment]
> I think the issue doesn't exist anymore. Could any of you build and confirm once?

Yeah, can anyone confirm ?

**Comment by riteshsp2000** [comment]
@san-coding @Nikhil-Ladha I just built the project and there was no such warning getting displayed. I think the issue doesn't persist anymore.

**Comment by warunicorn19** [comment]
Yeah we can close this, the issue seems to be gone.
