### ISSUE TITLE
[Discuss] Reconfigure email account

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2171]
**Description**
The previously existing email account has been deprovisioned. A new account is ready to be used.

**Expected Behavior**
Configure the new account and confirm that email is sending.

---
**Contributor Resources**

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

**Comment by leecalcote** [comment]
@DelusionalOptimist @Jashpatel1 @warunicorn19 email on discuss.layer5.io is fixed. Let's wrap up the new email template and publish. 👍

**Comment by warunicorn19** [comment]
@leecalcote test emails are coming through fine, can we close this issue?

**Comment by leecalcote** [comment]
Yes, sir. Thank you.

**Comment by DelusionalOptimist** [comment]
Niice. Fixed them all in a single go.
True OGs hehe :raised_hands:
