### ISSUE TITLE
[Site Speed] Currently a 40% rating

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2172]
**Current Behavior**
https://layer5.io isn't nearly as fast loading as it could be. See the recommendations on this report - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flayer5.io%2F

**Desired Situation**
Take each recommendation one at-a-time, implementing suggestions to improve page speed. These individual speed enhancements can be broken into separate issues or all tracked against this same epic issue.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by b-hexsoul** [comment]
I am taking a look at this! Thank you for the "good first issue" label

**Comment by leecalcote** [comment]
Very good, @b-hexsoul 👍

**Comment by leecalcote** [comment]
Any luck so far, @b-hexsoul ?

**Comment by leecalcote** [comment]
MeshMate @Nikhil-Ladha suggests an investigation into the automatic conversion of images from jpg, png to webp using Gatsby plugin - https://www.gatsbyjs.com/plugins/gatsby-image/

Whether the visitor's browser support these more modern file formats could be either automatically discerned by the Gatsby plugin (e.g. `sharp`) or could be logic invoked during execution of GraphQL (for which image type to retrieved).

**Comment by kayceeDev** [comment]
@b-hexsoul what is your progress so far, do you need any help, I'd be please to work with you on this as well. @leecalcote can I also take a look?

**Comment by warunicorn19** [comment]
@b-hexsoul are there any updates on this? we would really love to discuss this on our websites' call today.

**Comment by leecalcote** [comment]
@kayceeDev Yes, please do.

**Comment by kayceeDev** [comment]
I just created a PR for this issue. #2363

**Comment by Abhijay007** [comment]
@leecalcote I want to take up this issue if no one is working on it rn.

**Comment by Abhijay007** [comment]
> MeshMate @Nikhil-Ladha suggests an investigation into the automatic conversion of images from jpg, png to webp using Gatsby plugin - https://www.gatsbyjs.com/plugins/gatsby-image/
> 
> Whether the visitor's browser support these more modern file formats could be either automatically discerned by the Gatsby plugin (e.g. `sharp`) or could be logic invoked during execution of GraphQL (for which image type to retrieved).

@leecalcote I have inspected the issue and get to know that some big images files (in terms of size) are not converted using the gatsby-plugin-image plugin most of those files are on the home page itself, these images files are still in png format, we can convert those images by applying the same approach, I just have a little doubt that you mentioned that the site speed is currently 40% but according to Pagespeed analysis it is 95% on the web and 45% on mobile devices I am assuming that at the time of this issue opened it is around 40%, right? 

The PageSpeed analysis also shared reports on reducing or removing unused javascript I will troubleshoot these issues one-by-one and I may raise multiple PR regarding this issue.

**Comment by leecalcote** [comment]
> " at the time of this issue opened it is around 40%, right?"
Right. Also, Google might index us mobile-first (fyi).

> "The PageSpeed analysis also shared reports on reducing or removing unused javascript files, I will troubleshoot these issues one-by-one and I may open multiple PR regarding this issue."
Excellent. 😄

**Comment by leecalcote** [comment]
Context: Keywords list - https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by alceil** [comment]
Hey @Nikhil-Ladha  , I am Ashish Tom, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. And I would also like some pointers on how to get started.Thank you

**Comment by Nikhil-Ladha** [comment]
Hi @alceil , sure.
Since this issue is epic. small improvements are encouraged for it like using the `bg-image` component for `Community Callouts` at the end of the page. Ref: #2596 
Do join our slack workspace at `slack.layer5.io`, and ping me there in case of any doubts. 
Happy to help :)

**Comment by alceil** [comment]
Sure thanks @Nikhil-Ladha

**Comment by leecalcote** [comment]
What rating is layer5.io currently at?

**Comment by Nikhil-Ladha** [comment]
Mobile is still pretty low, but desktop looks good at 95%.

**Comment by leecalcote** [comment]
Desktop 95%?! 🚀 yeah, baby, yeah
