### ISSUE TITLE
[Community] Rudraksh Parekh as a maintainer

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2174]
**Description**
Currently, when filtering maintainers, rudraksh's profile is not visible. This is probably because his `position` has been written in the wrong way.

**Expected Behavior**
His profile should be visible with the other maintainers.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by PuneetDabral** [comment]
sir can i do my first contribution here ...!! i am in beginner level

**Comment by PuneetDabral** [comment]
can you please tell me where i change ??....

**Comment by khanjasir90** [comment]
@warunicorn19 i have changed the position of rudraskh to maintainer can I create a PR

**Comment by warunicorn19** [comment]
@khanjasir90 could you just hold off for 2 days, let @PuneetDabral try to figure it out, and if he's not able to do so, then you could put in the PR.

**Comment by PuneetDabral** [comment]
sir can you check my pr request....

**Comment by PuneetDabral** [comment]
@khanjasir90  can you please help me....??sir
i am very thankful if you please help me !!

**Comment by khanjasir90** [comment]
sure !@PuneetDabral  how can i help u?

**Comment by PuneetDabral** [comment]
@khanjasir90 sir i have sent you mssge in linkdin

**Comment by khanjasir90** [comment]
@warunicorn19 can we both work on this!

**Comment by warunicorn19** [comment]
@khanjasir90 you guys could work on this together but it's a line change, that I've already written in the linked PR. I'll assign it to the both of you, but let's get this done as soon as possible.

**Comment by warunicorn19** [comment]
And you had mentioned that you had a PR ready to go, so if that's the case you could put in the PR too. This is a pretty simple, straightforward issue.

**Comment by khanjasir90** [comment]
@warunicorn19 i have changed the position of rudraksh from contributor to maintainer but it is still not showing rudraksh profile in maintainer filter

**Comment by warunicorn19** [comment]
@khanjasir90 that's not how it'll work, you have to add `maintainer: yes` like Ive mentioned here(https://github.com/layer5io/layer5/pull/2176#pullrequestreview-752155152), you'd have to add it right before the `published` field.

**Comment by PuneetDabral** [comment]
sir i will try ...

**Comment by PuneetDabral** [comment]
sir how my name and image shows in Contributor List of this website....
