### ISSUE TITLE
[Event] ServiceMeshCon NA 2021

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2178]
Please add the following event to layer5.io/events.

**Event:**

- Event Title: ServiceMeshCon North America 2021
- Event Link: https://events.linuxfoundation.org/servicemeshcon-north-america/
- Talk Description: Service Mesh Patterns by the Book
- Talk Link: https://servicemeshconna21.sched.com/?iframe=yes&w=100%&sidebar=yes&bg=no#
- Deck: 
- Video: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Jayita10** [comment]
Can I work on this issue?

**Comment by khanjasir90** [comment]
@leecalcote @Jashpatel1 @warunicorn19 I have created a pull request for this issue can u just go through it

**Comment by khanjasir90** [comment]
@leecalcote @Jashpatel1 @warunicorn19 removed merge conflict in package.json file and created a PR could you go through it once!

**Comment by leecalcote** [comment]
@khanjasir90 I don't see a linked PR.

**Comment by khanjasir90** [comment]
@leecalcote  are u able to see it now

**Comment by leecalcote** [comment]
@Jayita10 oh, my goodness. I didn't see your message. Yes, for certain you could have. Let's find you another issue to grab.

@khanjasir90 be careful not to step on the toes of other contributors.
