### ISSUE TITLE
List Meshery adapter for CPX on project page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#218]
**Description**
Existing adapters have advanced in their status (e.g. from beta to stable) and new adapters have emerged. The list of [supported service meshes on the Meshery page](https://layer5.io/meshery/) needs updated.

**Expected Behavior**
[Supported Service Meshes](https://github.com/layer5io/layer5/blob/master/_includes/meshery.html#L134) should list:

1. [Meshery adapter for CPX](https://github.com/layer5io/meshery-cpx) (alpha)

// @chiradeep @dheerajng

**Comment by leecalcote** [comment]
@firstladymb you might like to try your hand here.

**Comment by leecalcote** [comment]
@dheerajng would you mind knocking this one out?

**Comment by dheerajng** [comment]
@leecalcote : Sure. Sorry for the delay. I am going to resume work on it this week.

**Comment by leecalcote** [comment]
Good to go here.
