### ISSUE TITLE
[Landscape] NGINX Service Mesh SMI results showing "None" version

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2180]
**Desired State:**
On this table, https://layer5.io/service-mesh-landscape#smi, the version of the service mesh should be listed.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by dhruv0000** [comment]
fixed.
