### ISSUE TITLE
Maintainers having position as Contributor

### ISSUE THREAD

**Issue by khanjasir90** [layer5io/layer5#2186]
**Description**
A couple of Maintianers like Utkarsh Srivastava, Tanuj Agarwal are having position as Contributor

**Expected Behavior**
Their position should be Maintainers.

**Screenshots**
![1](https://user-images.githubusercontent.com/53305380/133377486-7d9407da-fb3c-4418-b764-4bc77c49b09f.JPG)
![2](https://user-images.githubusercontent.com/53305380/133377489-258deb95-a266-4c2b-a5d4-2df2ebf4b770.jpg)

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by khanjasir90** [comment]
@warunicorn19 @leecalcote @Jashpatel1 can i work on this

**Comment by warunicorn19** [comment]
Sure @khanjasir90 🙂.

**Comment by Tanuj22** [comment]
@khanjasir90 can you add a bio and location for me too (why did I forget to add my own content :face_with_head_bandage: ).

Location - Guwahati, India

Bio - I am a Computer Science undergraduate from the Indian Institute of Technology, Jodhpur. I am passionate about software development and open source. I like to explore anything that comes along my way and hope to learn from awesome communities like Layer5

**Comment by khanjasir90** [comment]
@Tanuj22 sure i will do the needful!

**Comment by khanjasir90** [comment]
@Tanuj22 should I add ur linkedin profile? if yes could u pls share the link

**Comment by Tanuj22** [comment]
Yes please :laughing: https://www.linkedin.com/in/tanujagarwal22/

**Comment by khanjasir90** [comment]
@warunicorn19 @Tanuj22 i have created a PR just go through it
