### ISSUE TITLE
[Calender] ServiceMeshCon NA 2021

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2187]
**Current Behavior**
ServiceMeshCon NA 21 is not present in the community calendar. (https://layer5.io/community/calendar)

**Desired Situation**
Add this event to the community calendar. (Date: 12th Oct 2021)

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by moazzam07** [comment]
@warunicorn19 can i work on this?

**Comment by warunicorn19** [comment]
Sure @moazzam07.

**Comment by leecalcote** [comment]
@moazzam07 my apologies - this issue is well-suited for community managers (of which you might become one someday!). For now, allow me to reassign this issue, if you would.

**Comment by moazzam07** [comment]
Ok

**Comment by adithyaakrishna** [comment]
Closing this as it was created by @warunicorn19 

Screenshot:
![image](https://user-images.githubusercontent.com/23498248/134762739-dd02404d-9026-4473-8c43-38bdd31ed902.png)

**Comment by warunicorn19** [comment]
@adithyaakrishna actually I've added this to our content calendar, but not to the calendar on meet.layer5.io, so reopening this issue.

**Comment by adithyaakrishna** [comment]
Ohhh Accha, got it 👍🏻
