### ISSUE TITLE
[Learn] Add Open Service Mesh lab 

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2189]
Current Behavior
The newly created Open Service Mesh lab hasn't been added to https://layer5.io/learn .

Desired Situation
Let's put up the Open Service Mesh lab [here](https://layer5.io/learn/service-mesh-labs) .

https://github.com/layer5io/layer5/blob/master/src/sections/Learn/Service-Mesh-Labs/courseData.js

https://github.com/layer5io/layer5/tree/master/src/collections/service-mesh-labs

Contributor Resources

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the master branch.

See contributing instructions
See Layer5 site designs in this Figma project. Join the Layer5 Community for access.

**Comment by khanjasir90** [comment]
@warunicorn19 I'll take this up!

**Comment by leecalcote** [comment]
Sounds real good, @khanjasir90

**Comment by khanjasir90** [comment]
@warunicorn19 @leecalcote  can in get the the cover logo for the traefik lab

**Comment by warunicorn19** [comment]
@khanjasir90 could you elaborate on what you're trying to say?

**Comment by khanjasir90** [comment]
while adding the details in courseData.js file it requires a cover image so i needed that
![c](https://user-images.githubusercontent.com/53305380/133824772-f760a315-58c7-465d-b8c4-3045588ff931.JPG)

**Comment by warunicorn19** [comment]
Oh so you meant the logo for OSM lab

**Comment by khanjasir90** [comment]
yup

**Comment by warunicorn19** [comment]
There are a couple of logos in the assets folder, like this one: https://github.com/layer5io/layer5/blob/master/src/assets/images/service-mesh-icons/open-service-mesh/icon/white/openservicemesh-icon-white.svg. You'd have to see which one looks good there and is white in colour.

**Comment by khanjasir90** [comment]
@warunicorn19  cool ! thanx

**Comment by khanjasir90** [comment]
@warunicorn19 @leecalcote created a PR pls go through it!

**Comment by khanjasir90** [comment]
@leecalcote @warunicorn19 from where i will get the "embed" and "link" data
![c](https://user-images.githubusercontent.com/53305380/133834228-107fd408-60bb-4a65-8434-e72e7c469232.JPG)

**Comment by warunicorn19** [comment]
@khanjasir90 you'll have to put `open-service-mesh-meshery-adapter` in  embed and you'll have to make a page for OSM here https://github.com/layer5io/layer5/tree/master/src/collections/service-mesh-labs and then add that as link.

**Comment by khanjasir90** [comment]
@warunicorn19  got it!

**Comment by khanjasir90** [comment]
and in info : "Working with Open Service Mesh Lab" is this okay!

**Comment by warunicorn19** [comment]
YUP.

**Comment by khanjasir90** [comment]
@warunicorn19 the site builds without any error but when opening it in browser it is giving this error!
![c1](https://user-images.githubusercontent.com/53305380/133882093-93466d25-2a28-4892-aace-d37dd25437ab.JPG)
i have search a lot on internet but did not get useful thing , r u aware of this issue?

**Comment by warunicorn19** [comment]
Yes, I think it's because of some recent changes, looking into it.

**Comment by warunicorn19** [comment]
@khanjasir90 do you use windows?

**Comment by khanjasir90** [comment]
Yes!

**Comment by warunicorn19** [comment]
Seems like a windows specific issue.

**Comment by khanjasir90** [comment]
Ohh i see! so will it take time to get resolved!

**Comment by warunicorn19** [comment]
Still haven't been able to figure out what the problem is. Trying to look into it.

**Comment by warunicorn19** [comment]
@khanjasir90 problem has been fixed now if you could pull the latest and check.

**Comment by khanjasir90** [comment]
@warunicorn19 I'll do that!

**Comment by khanjasir90** [comment]
@warunicorn19 it is working now but when i put the following code embed: "open-service-mesh-meshery-adapter",
        link: "/learn/service-mesh-labs/working-with-open-service-mesh", it shows the below error!
![err2](https://user-images.githubusercontent.com/53305380/133936113-d4d64958-affe-4680-b788-baa3cda16fbc.JPG)

**Comment by warunicorn19** [comment]
Yes @khanjasir90, sorry I forgot to give you the update but today I changed the pathname to `osm-meshery-adapter` today, trying using that, it should work.

**Comment by khanjasir90** [comment]
okay @warunicorn19 !

**Comment by khanjasir90** [comment]
@warunicorn19  created a PR pls check!

**Comment by khanjasir90** [comment]
so sorry @warunicorn19  it keep this in mind next time! :)
