### ISSUE TITLE
README: Improve Slack badge

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#219]
**Issue:**
The Slack badge on this repo's README has an inaccurate member count.

**Request:**
Improve the accuracy of the count by using the same approach to the Slack badge as taken in the [Meshery repo's README](https://github.com/layer5io/meshery/blob/master/README.md). These badges are intended to represent the same Slack account.

**Comment by neckenth** [comment]
@leecalcote I think I can take this one on. Can I be assigned?

**Comment by leecalcote** [comment]
Hi @neckenth! Thank you - yes, I would love for you to give this one a go. :)

**Comment by neckenth** [comment]
@leecalcote Would you mind adding me as a collaborator so I can push up my PR? Or is there another way to do this?

**Comment by leecalcote** [comment]
@neckenth sounds great, yes. For this particular project (repo), cloning, creating a branch, pushing changes to that branch and then submitting a PR should do the trick.

You're most welcome to consider jumping into the sister project, [Meshery](https://github.com/layer5io/meshery) (pretty please ;) ). That project uses a very similar contribution model, save for you'll start by forking instead of starting by cloning there. 

You're most warmly welcome to jump into this [Slack account](http://slack.layer5.io) and/or request access to [Meshery's community resources](https://layer5.io/meshery/#community), too.

**Comment by neckenth** [comment]
@leecalcote thank you so much. Looks like you added me as a contributor, but I'm still getting a 403 when trying to push up my branch. Any thoughts?

**Comment by leecalcote** [comment]
Oops. We have recently rearranged team permissions and contribution models. I __think__ you'll be successful in pushing now...

**Comment by leecalcote** [comment]
Boom, bang! That was fast. :)
