### ISSUE TITLE
Enhance the Layer5 shields in the .github org

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2193]
**Current Behavior**
The https://github.com/layer5io/.github/tree/main/profile#readme controls what is displayed on https://github.com/layer5io. The shields on there should be representative of the community at-large.

**Desired Situation**
Use advanced queries on https://shields.io to:

1. change the `help wanted` shield from showing only issue count on the `layer5` repo to an issue count incorporating all Layer5 orgs like this: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+
2. change the `contributor` shield to include the count from layer5io/layer5 and meshery/meshery repos (if not all the repos).
3. add the twitter accounts for mesheryio and smp_spec in addition to the layer5 twitter shield.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@moazzam07 would you like to take this one on?

**Comment by moazzam07** [comment]
I didn't get the issue.

**Comment by Zain-Muiz** [comment]
@moazzam07 Check the readme file of this repo. I've attached a screenshot below. The badges(i.e : shields) you see there are what this issue is about
![Screenshot (134)](https://user-images.githubusercontent.com/60746360/133934006-ecf3ef74-cf04-40ad-8186-b853337121c5.png)
.

**Comment by moazzam07** [comment]
@leecalcote could you please provide me this repo https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by warunicorn19** [comment]
@moazzam07 this is not actually a repo, these are all the help wanted issues from all our organizations.

**Comment by Zain-Muiz** [comment]
@moazzam07 , That link (the one Lee mentioned in the issue) is what you should replace the current link in the help wanted shield with. Like @warunicorn19 mentioned , This is the link to all the help wanted issues in all repositories across all our organizations. You don't have to add multiple repository links as a separate shield.

**Comment by san-coding** [comment]
Hey, can I work on this if it is still open ?

**Comment by moazzam07** [comment]
I am searching how to do but if you want to do you can.

**Comment by warunicorn19** [comment]
I'll assign it to the both of you, let's see who gets there first😅😅. Good luck guys.

**Comment by moazzam07** [comment]
Yes @san-coding it would be nice

**Comment by san-coding** [comment]
Should I go ahead and create a badge at shields? @warunicorn19 @leecalcote

**Comment by san-coding** [comment]
> **Desired Situation**
> Use advanced queries on https://shields.io to:
> 
> 1. change the `help wanted` shield from showing only issue count on the `layer5` repo to an issue count incorporating all Layer5 orgs like this: https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+
> 2. change the `contributor` shield to include the count from layer5io/layer5 and meshery/meshery repos (if not all the repos).
> 3. add the twitter accounts for mesheryio and smp_spec in addition to the layer5 twitter shield.
> 
> **Contributor Resources**
> 
> The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> 
> * See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> * See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

@leecalcote you have asked to change `help wanted` shield, but https://github.com/layer5io doesn't have a help wanted shield, it only has a contributor shield which counts contributors from `layer5io/layer5 `
<img width="813" alt="image" src="https://user-images.githubusercontent.com/65719940/134196031-6d63d541-1862-4d7b-b940-df1742a78dde.png">

Should I create a shield `help wanted` which shows the count of [https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+)

**Comment by san-coding** [comment]
@leecalcote @warunicorn19 how to generate query [LIKE THIS](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+) for `contributions`

**Comment by Zain-Muiz** [comment]
Heyy @san-coding @debo19 @warunicorn19 , I saw few of the PRs related to this have been merged. Are we good to close this issue  ?

**Comment by san-coding** [comment]
Yes we can close this issue, PRs have been merged
