### ISSUE TITLE
Recreate the .github repo from `layer5_repo_template`

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2194]
**Desired Situation**
1. Delete current .github repo.
2. Create new .github repo using the following settings:
<img width="773" alt="Screen Shot 2021-09-17 at 3 53 56 PM" src="https://user-images.githubusercontent.com/7570704/133852446-2a562492-fbbe-4239-93ed-30ef4398818c.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@debo19 we could close this issue now, right?

**Comment by debo19** [comment]
@warunicorn19 yes the new repo was created, we can close this now.
