### ISSUE TITLE
[Handbook] Add SMP logo to repo overview page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2195]
**Desired Behavior**
Please add the SMP logo to repo overview page - https://layer5.io/community/handbook/repository-overview

Find logo here - https://layer5.io/brand

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by moazzam07** [comment]
@leecalcote i'll take this up!

**Comment by warunicorn19** [comment]
Sounds good @moazzam07

**Comment by moazzam07** [comment]
![image](https://user-images.githubusercontent.com/67731696/133880498-0a7460c0-935b-4f18-ad94-d376cf7564a9.png)
can anyone help me with this error

**Comment by moazzam07** [comment]
@leecalcote @warunicorn19 can you please help me with the above issue

**Comment by warunicorn19** [comment]
Could you tell me which version of node you're using?
`node -v`

**Comment by moazzam07** [comment]
v14.17.4

**Comment by warunicorn19** [comment]
Have you tested out the changes locally? This might be happening due to a syntax error.

**Comment by moazzam07** [comment]
yes, it is working locally

**Comment by warunicorn19** [comment]
Let's shift to slack.

**Comment by moazzam07** [comment]
@leecalcote @warunicorn19 PR created plzz check
