### ISSUE TITLE
[Handbook] Add Contributor Journey Map to About page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2196]
**Desired Behavior**
Under the **Newcomer's Path** section on this page (https://layer5.io/community/handbook/about), add the contributor journey map as shown on https://layer5.io/community/newcomers.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by SURAJITSHAW** [comment]
Hello, this is my first issue. Can I work on that ?

**Comment by warunicorn19** [comment]
Sure @SURAJITSHAW

**Comment by khanjasir90** [comment]
@SURAJITSHAW  do u need any help i can help u out!

**Comment by SURAJITSHAW** [comment]
Yes sir, I need a little help actually. I made my changes first day but I can't test because in my laptop make commands doesn't work, I was seeking for another ways to check what my changes looks like but I can't. I just didn't understand what should I do now?

**Comment by khanjasir90** [comment]
Ok got it @SURAJITSHAW ! let's move to slack there we will solve ur make command problem!

**Comment by SURAJITSHAW** [comment]
Sure sir, I send you a personal message on slack.

**Comment by Aniket1312** [comment]
hey I am  new here can I also join with you.

**Comment by YashKamboj** [comment]
Hey @SURAJITSHAW u still working on it or its done ?, if not can i work on it

**Comment by SURAJITSHAW** [comment]
Sure bro, you can start working on this. Because of my personal issue I
can't solve this issue. Do your best buddy

**Comment by YashKamboj** [comment]
@SURAJITSHAW thnx i thought you solved it so i deleted my comment.

**Comment by warunicorn19** [comment]
@YashKamboj are you taking a look into this.?

**Comment by YashKamboj** [comment]
> @YashKamboj are you taking a look into this.?

@warunicorn19 Yes

**Comment by warunicorn19** [comment]
Great!

**Comment by san-coding** [comment]
@warunicorn19 is this issue closed?

**Comment by warunicorn19** [comment]
No @YashKamboj just started working on it

**Comment by san-coding** [comment]
Ohh okay

**Comment by prashant-isbest** [comment]
I am also looking into this

**Comment by warunicorn19** [comment]
Umm, @prashant-isbest I guess someone's already working on this, you might want to take a look at other issues with the  `help-wanted` label.

**Comment by YashKamboj** [comment]
Hey , can you help me setup in my pc ,i have read the readme , but stuck with make. @warunicorn19

**Comment by khanjasir90** [comment]
@YashKamboj make command is linux based i assume that u use windows. pls go through this blog for setting up the make command https://zainmuiz.hashnode.dev/how-to-install-make-on-windows-machine . this was written by one of our community members @Zain-Muiz kudos to him.

**Comment by YashKamboj** [comment]
Hey @khanjasir90 can you tell how to do the step 3 in the blog you suggested , would be a real help .

**Comment by warunicorn19** [comment]
@Zain-Muiz your input here would be great.

**Comment by prashant-isbest** [comment]
> Hey @khanjasir90 can you tell how to do the step 3 in the blog you suggested , would be a real help .

I would recommend you to install choco 
1 . open powershell as administator
2. Copy the below command and run it
3.  Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
4. Now reopen powershell as administrator and run the below command
5. choco install make
6. It's done now you can run make file command

**Comment by YashKamboj** [comment]
> > Hey @khanjasir90 can you tell how to do the step 3 in the blog you suggested , would be a real help .
> 
> I would recommend you to install choco
> 1 . open powershell as administator
> 2. Copy the below command and run it
> 3. Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
> 4. Now reopen powershell as administrator and run the below command
> 5. choco install make
> 6. It's done now you can run make file command

Thank you very much @prashant-isbest you really helped me was stuck with make for about 2 days.
