### ISSUE TITLE
Meshery: rearrange buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#220]
**Issue:**
There are two buttons on the [Meshery page](https://layer5.io/meshery). One needs to be removed and the other needs to be relocated as shown in the screenshot:

**Screenshot:**
<img width="1253" alt="Screen Shot 2019-10-27 at 4 24 08 PM" src="https://user-images.githubusercontent.com/7570704/67642121-951e6e00-f8d6-11e9-9ae4-ff74336df616.png">

The source for this page is here - https://github.com/layer5io/layer5/blob/master/_includes/meshery.html

**Comment by RamanaVem** [comment]
Hey @leecalcote can i look up in this, please assign to me

**Comment by leecalcote** [comment]
Closed by #222. Thanks, @RamanaVem
