### ISSUE TITLE
A Tooltip required on Read Book Button!

### ISSUE THREAD

**Issue by khanjasir90** [layer5io/layer5#2210]
**Description**
In https://layer5.io/ webpage every button on hover has a tooltip but Read Books button does'nt have a tooltip

**Expected Behavior**
Read Book button should have a tooltip

**Screenshots**

![image](https://user-images.githubusercontent.com/53305380/134285946-832602df-1ad7-4ba5-a353-5d00a111147f.png)
![image](https://user-images.githubusercontent.com/53305380/134286000-cf1c6a7f-52b6-48b9-9f7d-52b749dc7c49.png)

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by ruhi09** [comment]
@khanjasir90 I would like to work on this issue
