### ISSUE TITLE
[Landscape] add go-zero to "Client Library" category

### ISSUE THREAD

**Issue by kevwan** [layer5io/layer5#2212]
**Current State:**
![image](https://user-images.githubusercontent.com/1918356/134470450-8c8c274b-f70a-459d-ad84-d5add2ce1943.png)

**Desired State:**
Would you please add [go-zero](https://github.com/zeromicro/go-zero) to Client Library category?

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by toth2000** [comment]
I am working on this issue.

**Comment by warunicorn19** [comment]
Sounds good @toth2000.
