### ISSUE TITLE
[Discuss] Misaligned Email template

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2224]
**Description**
The discuss.layer5.io email template is in need of being fixed.

**Screenshots**
![Screen Shot 2021-09-28 at 7 23 15 AM](https://user-images.githubusercontent.com/7570704/135086637-5dc0b693-0ce7-40fa-857f-d4d443f9354e.png)

**Environment:**
- Host OS: MacOS
- Client: Apple Mail

---
**Contributor Resources**

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

**Comment by PulkitSinghDev** [comment]
would like to work on this issue :)

**Comment by leecalcote** [comment]
@PulkitSinghDev great. You'll need to execute the instructions given in the issue description in order to work on this issue.

**Comment by leecalcote** [comment]
Any progress to report here? Please join the Websites call today to discuss.

**Comment by PulkitSinghDev** [comment]
yup there are some updates, but how to join that website call ??

**Comment by Mr-DG-Wick** [comment]
hey @PulkitSinghDev , any progress on this one :) ?

**Comment by leecalcote** [comment]
@PulkitSinghDev let's close this issue out and circle back if we see the issue still persisting.
