### ISSUE TITLE
[Handbook] Create a page for FAQ in the community handbook

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2225]
**Current Behavior**
The current handbook doesn't have an FAQ section, the questions are [here](https://docs.google.com/document/d/1vxc8MLhDetIlBa1DCUTMbYLGWL4Df4K1xB_Ov5oUK7o), some of which are not answered yet.

**Desired Situation**
Create a separate page for FAQ and add the questions from the above document here (https://layer5.io/community/handbook)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by siddhantkhariwal** [comment]
Hey, can I fix this issue?

**Comment by YashKamboj** [comment]
If noone working can i work on this.

**Comment by warunicorn19** [comment]
Hey @YashKamboj, will have to assign it to @siddhantkhariwal as he asked first.

**Comment by YashKamboj** [comment]
@warunicorn19 now worry

**Comment by siddhantkhariwal** [comment]
> Hey @YashKamboj, will have to assign it to @siddhantkhariwal as he asked first.

Hey, I have requested access to the document above, please give me access.

**Comment by YashKamboj** [comment]
> > Hey @YashKamboj, will have to assign it to @siddhantkhariwal as he asked first.
> 
> Hey, I have requested access to the document above, please give me access.

Tag @warunicorn19

**Comment by warunicorn19** [comment]
@siddhantkhariwal have you filled in the newcomers form? https://layer5.io/newcomer, that should give you access to the document.

**Comment by YashKamboj** [comment]
Hey @siddhantkhariwal if you are facing some difficulty solving the issue ,i can do it.

**Comment by siddhantkhariwal** [comment]
> Hey @siddhantkhariwal if you are facing some difficulty solving the issue ,i can do it.

No, no worries. I'll complete it today!

**Comment by YashKamboj** [comment]
> > Hey @siddhantkhariwal if you are facing some difficulty solving the issue ,i can do it.
> 
> No, no worries. I'll complete it today!

I will be happy to help.😊

**Comment by siddhantkhariwal** [comment]
> > > Hey @siddhantkhariwal if you are facing some difficulty solving the issue ,i can do it.
> > 
> > 
> > No, no worries. I'll complete it today!
> 
> I will be happy to help.😊

Okay, I'll let you know if I need any help.

**Comment by moazzam07** [comment]
@warunicorn19 can i work on this?

**Comment by siddhantkhariwal** [comment]
@warunicorn19  Have completed the faq section, some minor changes are remaining will put a PR today itself.

**Comment by siddhantkhariwal** [comment]
Hey, @warunicorn19  I have completed the FAQs page and created a pull request, Please look through it for any feedback or changes that I missed.
