### ISSUE TITLE
[Handbook] Create a separate page for the Path to Leadership

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2226]
**Current Behavior**
The current `Community` page in the [handbook](https://layer5.io/community/handbook/community) also has the `Path to leadership` in it.

**Desired Situation**
Let's get that on a separate page and name the page as `Contributor Ladder`

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Rename "Path to Leadership", which can be easily interpreted as "Your puny place in this world to where we should all be" - - which is not the case.

**Comment by warunicorn19** [comment]
@leecalcote 😂😂, updated the issue.
