### ISSUE TITLE
Workshops: Fix broken Montreal Devfest session link

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#223]
The "Session" link is broken on the Deafest workshop card (https://layer5.io/workshops/). The working link is https://devfest.cloud-montreal.ca/schedule/2019-09-28?sessionId=405

**Comment by logichub** [comment]
This link also generating 404 error page:
https://devfest.cloud-montreal.ca/schedule/2019-09-28?sessionId=405

**Comment by subhamkrai** [comment]
@leecalcote every session link is broken...currently the problem is in DevFest links...we are good from our sides.

**Comment by girishranganathan** [comment]
@archyufa, can you please help us here?

**Comment by leecalcote** [comment]
@archyufa, quick check - the devfest.cloud-montreal.ca site isn't coming back, is it?

**Comment by archyufa** [comment]
It is down for now. We going to move to Firebase when start planning next event. For now with COVID it is still question mark if we will do it in 2020 :(

**Comment by leecalcote** [comment]
@chandrashritii the link to the event can be removed.
