### ISSUE TITLE
[Bug] Collaboration's section organization logos not aligned properly.

### ISSUE THREAD

**Issue by sarthakjdev** [layer5io/layer5#2233]
**Description**

The collaboration section is being off-frame, leading to organization logo to be cut off by the screen frame .

**Screenshots**

![Screenshot 2021-10-02 012704](https://user-images.githubusercontent.com/77162721/135679935-a89386ce-de6d-478a-b34b-7c6586d25bca.png)

**Expected Behavior**

![image](https://user-images.githubusercontent.com/77162721/135681084-6058f5b1-1fb1-4300-b42d-189a4f435cb0.png)

**Environment:**
- Host OS: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Thanks for highlighting this, @sarthakjdev. Would you like to work on a fix as well?

**Comment by sarthakjdev** [comment]
@leecalcote Yes for sure, I would like to work on this issue :)

**Comment by warunicorn19** [comment]
@sarthakjdev @leecalcote this is not really a bug, according to the designs on Figma this is how the logos are supposed to look.

**Comment by sarthakjdev** [comment]
@warunicorn19 okay, So if this  supposed to be the real design then what we can do is, we can add a auto-scrolling animation to make the logos appear properly on the standard screen size, correcting the current fault it contains.

**Comment by amino19** [comment]
@warunicorn19: Sarthak needs to enhance a bit, lets ask him if he wanna work on this!

@sarthakjdev: Do you wanna take this issue as well?

**Comment by sarthakjdev** [comment]
@amino19 : Yes I want to work on this issue .

**Comment by warunicorn19** [comment]
@amino19 @sarthakjdev I don't think there's an issue here, a `marquee` is not a part of our design and is a little outdated. @leecalcote thoughts?

**Comment by warunicorn19** [comment]
@sarthakjdev why don't take a look at some [help wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Ameshery+org%3Aservice-mesh-performance+org%3Alayer5io+label%3A%22help+wanted%22+) issues

**Comment by amino19** [comment]
@warunicorn19: Agreed, shall we close this issue for now! :thinking:

**Comment by warunicorn19** [comment]
@amino19 let's wait for what @leecalcote says.

**Comment by sarthakjdev** [comment]
@warunicorn19 @amino19 Yes sure, probably I misunderstood this as an issue. No worries.
