### ISSUE TITLE
Image cropped of Traefik Mesh and  cncf in the proudly maintainers part (Home Page)

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#2237]
**Description**

Image cropped of Traefik Mesh and  cncf in the proudly maintainers part (Home Page)
**Expected Behavior**

**Screenshots**

![Screenshot (94)](https://user-images.githubusercontent.com/75125203/135742635-c83f6245-2e7a-4ea9-b8c1-d565a1f65467.png)
**Environment:**
- Host OS: Windows
- Browser: Google Chrome

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by YashKamboj** [comment]
Can i work on this issue  myself.

**Comment by warunicorn19** [comment]
@YashKamboj this is not a an issue, this is the design of the page.

**Comment by YashKamboj** [comment]
> @YashKamboj this is not a an issue, this is the design of the page. 

Really! O sorry
