### ISSUE TITLE
Workshops: Fix broken image Introduction to Istio - O'Reilly Live Online Training

### ISSUE THREAD

**Issue by logichub** [layer5io/layer5#224]
**Problem**

The session thumbnail image is broken on the **Introduction to Istio - O'Reilly Live Online Training** workshop card (https://layer5.io/workshops/).

![image](https://user-images.githubusercontent.com/6245858/67957986-3891ba80-fc18-11e9-984f-bc9b9c57641b.png)

**Proposed Fix**
- [ ] Rename the image name from `introduction-to-istio.jp2` to `introduction-to-istio.jpg`

**Comment by leecalcote** [comment]
Thanks for reporting this, @logichub!

**Comment by subhamkrai** [comment]
@logichub I think you need to change similar in this file https://github.com/layer5io/layer5/blob/master/collections/_workshops/2019_08_01-introduction_to_istio.md
@leecalcote, please correct me if I'm wrong

**Comment by leecalcote** [comment]
@subhamkrai yes, you're right. I appreciate you triaging these issues. 👍 

@logichub, thanks again for reporting this issue and for fixing it in #225!

**Comment by logichub** [comment]
@subhamkrai Thanks for pointing out this.

@leecalcote Just fixed it through #228
