### ISSUE TITLE
[Community] Member Profile: Add Service Mesh Pattern badge to Shreyas Mishra's profile

### ISSUE THREAD

**Issue by sayantan1413** [layer5io/layer5#2250]
**Current Behavior**

Current Behavior

@Shreyas220  has worked on generating buildtime in meshery-kuma and runtime in meshery-nginx-sm adapter.

Desired Situation
Let's recognize @Shreyas220 's efforts with the patterns badge on his community member profile on https://layer5.io/community/members.

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Shreyas220** [comment]
thank you @YashKamboj for doing this
