### ISSUE TITLE
[handbook] Create an intra-page for the content of the handbook

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2256]
**Description**
Currently, it is difficult to know the subheading that exists within each section of the handbook.

**Expected Behavior**
We need an intra-page nav for the handbook for that we can easily navigate to each subheading on a section. 
A typical example would be the navigation by the right on [this site.](https://docs.meshery.io/concepts/architecture)

**Screenshots**
![Screenshot 2021-10-12 at 01 34 54](https://user-images.githubusercontent.com/62384659/136871417-eb016a5b-11be-42ea-8fff-1ce0205113eb.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Anita-ihuman** [comment]
Why don't you create a PR so we can review it?

**Comment by YashKamboj** [comment]
@warunicorn19  I would have made the PR but my previous PR#2264 have the changes in the same files , so would open a PR as soon as the previous closes.
