### ISSUE TITLE
[handbook] Add a  “next topic” - “previous topic” button

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2257]
**Current Behavior**
There is none existing presently on the site.

**Desired Situation**
At the button of each section, there should be a “next topic” & “previous topic” button that helps users navigate to either the previous or next sections.

---
**Screenshot**

![next-and-previous-buttons-in-php](https://user-images.githubusercontent.com/62384659/136873084-e79f370b-3baa-4f85-94b7-b1e65aeea6fc.jpeg)
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by toth2000** [comment]
Looking into this.

**Comment by Anita-ihuman** [comment]
Sure go ahead.
