### ISSUE TITLE
[handbook] Add a back to the top button

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2258]
**Current Behavior**
There is no back to the top button existing on the community handbook. 

**Desired Situation**
Add a back to the top button on the handbook to help users scroll through the page.
A typical example can be found on [this site](https://smp-spec.io/).

---
**Screenshot**

![Screenshot 2021-10-12 at 02 06 19](https://user-images.githubusercontent.com/62384659/136873783-57ece5ec-cb6b-4209-b7e9-1241b71abf0b.png)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by ManishOffi** [comment]
Hye @Anita-ihuman 
Please can you assign me bcz i  would love to work for you?

**Comment by ely-herrera** [comment]
Hi @Anita-ihuman! Is this something you still need help with?

**Comment by sandeep-v1404** [comment]
Can I work on this issue? @Anita-ihuman

**Comment by Iheanacho-ai** [comment]
@Anita-ihuman is somebody working on it already

**Comment by shreya-gb** [comment]
I guess this issue is solved right?

**Comment by Iheanacho-ai** [comment]
@Anita-ihuman hey what about me 😭

**Comment by shreya-gb** [comment]
> Not at all @shreya-gb would you like to take it up?

Thanks a lot, @Anita-ihuman for assigning :) Working on it immediately!

**Comment by warunicorn19** [comment]
@shreya-gb any updates?

**Comment by vedant-kakde** [comment]
@shreya-gb if you are facing any issues please let us know. Happy to help.

**Comment by MohamadHanafi** [comment]
@Anita-ihuman Is the issue resolved?

**Comment by shreya-gb** [comment]
> @shreya-gb if you are facing any issues please let us know. Happy to help.

Yes, I need help in commenting the issue. My PR is submitted

**Comment by vedant-kakde** [comment]
@shreya-gb Please ping me on slack I'll help you.

**Comment by shreya-gb** [comment]
Okay, Thank you 

> @shreya-gb Please ping me on slack I'll help you.

**Comment by Sayantan-s** [comment]
@Anita-ihuman is this issue still open? If it is, then you can assign it to me.

**Comment by rajaditya28** [comment]
### Add a back to top button
Has this issue been resolved @Anita-ihuman ?
I can see that the [live site](https://layer5.io/) doesn't have a back to top button yet. 
If this issue is open, may I take it up ?
