### ISSUE TITLE
[handbook]Update the font family

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2260]
**Description**
The font used on the handbook homepage does not align with the one used across the entire site.

**Expected Behavior**
Change the font family to either Qanelas Soft or Open Sans for the [home page.](https://layer5.io/community/handbook) 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Anita-ihuman** [comment]
The handbook homepage font family is what I want to change.
Are you sure, you want to take this up as well?

**Comment by jayeclark** [comment]
I'm not sure I understand this issue. The handbook home page font appears to be Qanelas Soft for headers/title and Open Sans for paragraph text, which is consistent with the rest of the site. 

I did notice significant differences in font size and letter spacing for paragraph text, which gives the text a different appearance and almost makes it look like a different font (see 2nd photo). Are these properties what is supposed to be corrected to match the rest of the site? If so, I would like to work on this issue!
  
**HANDBOOK HOMEPAGE**  
(Qanelas headers and Open Sans paragraph text)
<img width="1001" alt="Screen Shot 2021-10-12 at 9 58 51 AM" src="https://user-images.githubusercontent.com/84106309/136970915-994fe802-77fc-4735-8664-fa593b50021d.png">
&nbsp;  
&nbsp;   
**SAMPLE TEXT FROM ELSEWHERE ON SITE**  
(also Open Sans, but a different font size and no font spacing)
<img width="866" alt="Screen Shot 2021-10-12 at 10 02 11 AM" src="https://user-images.githubusercontent.com/84106309/136970926-fd17c7cc-dd7e-4eb9-8c2c-bf3d2717b11e.png">

**Comment by Anita-ihuman** [comment]
Is that so? 
It actually seemed like a different font. 
It the font family corresponds with the other pages, then we might as well close this isssue.
