### ISSUE TITLE
[Community] Member Profile: Nicholas Jackson Name isn't Hyperlinked 

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2269]
**Current Behavior**
Nicholas Jackson name isn't hyperlinked in the project hour: service mesh performance KubeCon speakers

[layer5(https://layer5.io/community/events/project-office-hours-service-mesh-performance-at-kubecon-na-2021)

**Desired Situation**
The profile is under Nic Jackson

[Nic Jackson](https://layer5.io/community/members/nic-jackson)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by san-coding** [comment]
Shall i fix this ?

**Comment by leecalcote** [comment]
@san-coding, I think you _just_ missed this one...
