### ISSUE TITLE
[Brand] Add Service Mesh Patterns brand kit

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2276]
**Current Behavior**
https://layer5.io/company/brand does not have a section for Service Mesh Patterns.

**Desired Behavior**
Create a new section for Service Mesh Patterns.

**Kit**: [service-mesh-patterns-brand-kit.zip](https://github.com/layer5io/layer5/files/7375527/service-mesh-patterns-brand-kit.zip)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by ruhi09** [comment]
@leecalcote I would like to work on this

**Comment by warunicorn19** [comment]
Go ahead @ruhi09

**Comment by chirayumit001** [comment]
Hey, I would also like to work on this issue
I am new here so can multiple people get assigned to a single issue ? and will both their contributions get counted ? 
Really excited about contributing
