### ISSUE TITLE
[Event] KubeCon + CloudNativeCon + Open Source Summit China 2021 - Virtual

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2283]
Please add the following event to layer5.io/events.

**Event:**
- Event Title:  KubeCon + CloudNativeCon + Open Source Summit China 2021 - Virtual
- Event Link: https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/
- Talk Description: 
- Which service mesh should I use and how do I get started? What are the different service meshes, and how do they contrast? Learn about the functionality of different service meshes and visually manipulate mesh configuration. This lightning talk introduces Meshery, an open source, multi-service mesh management plane that provisions (five and counting) different service meshes, their sample applications and benchmarks the performance of service mesh deployments. Meshery facilitates benchmarking various configuration scenarios of Istio, comparison of performance of services (applications) on and off the mesh and across different meshes. It vets mesh and services configuration against deployment best practices. Some of the service mesh projects use Meshery as their performance benchmark tool for each release.
- Talk Link: https://sched.co/nPOK
- Deck: 
- Video: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by davidchengl74** [comment]
hello i'd create the event for you on your web page.
i'm doing this as a school assignment.
it needs to be merged after for me to receive credit for the assignment. 
can you kindly let me know if that works and this can be assigned to me?
