### ISSUE TITLE
Add VMWare NSX-SM to the landscape

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/layer5#229]
**Description**
We need to add VMWare NSX-SM to the right category in the landscape, and also include its functional and non-functional info.

**Comment by girishranganathan** [comment]
@venilnoronha it would be wonderful if you can chime in here.

**Comment by venilnoronha** [comment]
@girishranganathan for sure. I'll send in a PR.

**Comment by leecalcote** [comment]
Hi @dkalani, will you give this landscape a quick PR? We want to ensure all relevant projects are represented in the [service mesh landscape](https://layer5.io/landscape). We would love to have NSX-SM included. Will you consider updating the landscape with a quick pull request? 

We do our best to ensure that projects and their capabilities are accurately represented, and so, we ask for project representatives to submit these updates directly. 

Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for making your edits.

**Comment by dkalani** [comment]
Yes I’ll take care of this today thx
Deepa

**Comment by leecalcote** [comment]
@dkalani awesome. thank you. 👍

**Comment by leecalcote** [comment]
Given Tanzu's launch with NSX SM, I think we're ready for the landscape update. @dkalani @venilnoronha you're help here is much appreciated. 👍

**Comment by leecalcote** [comment]
@sergiopozoh any takers? ;)
