### ISSUE TITLE
[Handbook] no button or part in layer5.io/community which redirect to layer5.io/community/handbook 

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#2298]
**Current Behavior**no button or part in layer5.io/community which redirect to layer5.io/community/handbook , we always have to type the url to redirect to the handbook page

**Desired Behavior**

 -links to this handbook from the /community/newcomers and /community/meshmates pages?
 -a new call-to-action in the shape a small rectangular widget
 -a new, horizontal shaped call-to-action for the handbook
---
**Screenshots / Mockups**

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by YashKamboj** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/75125203/139583425-1554444f-7e43-4b1b-a5f6-ab9f795453e2.png)
Does this callout look okay @warunicorn19

**Comment by warunicorn19** [comment]
@YashKamboj let's discuss this tomorrow on the websites' call.

**Comment by YashKamboj** [comment]
Hey @warunicorn19 does this looks good
![Screenshot (4)](https://user-images.githubusercontent.com/75125203/139728852-5da9455b-7002-4286-838d-f023aa183885.png)

**Comment by warunicorn19** [comment]
@debo19 is better with UX 😅, views?

**Comment by debo19** [comment]
I think it's a little difficult to focus on the text here.  Can you try a darker overlay on the image? Check [this](https://dev.to/ellen_dev/two-ways-to-achieve-an-image-colour-overlay-with-css-eio) out. 
Also, the heading "Community Handbook" has to be bigger.  Let's see how this turns out otherwise we'll brainstorm again 🤔

**Comment by YashKamboj** [comment]
How about now ? @debo19 
![Screenshot (5)](https://user-images.githubusercontent.com/75125203/139874813-884acd03-d19c-4d04-8903-b5a904f38058.png)

**Comment by sambhavsaxena** [comment]
@YashKamboj looks great

**Comment by YashKamboj** [comment]
@sambhavsaxena thnx

**Comment by YashKamboj** [comment]
@debo19 any views ,should i make a pr

**Comment by leecalcote** [comment]
@YashKamboj we also need a size of this that fits into the "widget" column on layer5.io/blog.

**Comment by YashKamboj** [comment]
@leecalcote i can change the size for the blog only , or should i keep the size for every page small.

**Comment by YashKamboj** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/75125203/140878079-78759aaf-cceb-44db-9d99-9eba5716abb6.png)
@debo19 Views??

**Comment by debo19** [comment]
This looks much better @YashKamboj . Can you make the smaller version of this and place it in the site locations we discussed yesterday?
Also, as discussed in yesterday's call, we can explore a new shape other than rectangles and squares.  https://user-images.githubusercontent.com/64528871/135861003-17d1d08a-d92f-48c4-a447-3a2c9cadef3e.png this could be a possible layout.  You can try using this, we can compare both once you're done.

**Comment by YashKamboj** [comment]
@debo19 views?
![Screenshot (12)](https://user-images.githubusercontent.com/75125203/141165350-d4f409e0-cdd7-43ad-9451-294e13f9c1f5.png)
?

**Comment by Abhijay007** [comment]
@leecalcote can we try something like this for the interactive handbook component on [this](https://layer5.io/community/newcomers) page

**Comment by debo19** [comment]
@Abhijay007 This is good but I think we require a more subtle animation than this.  The approach will be similar though; each section (here: a page in the book) will be able to display information about each page of the handbook.

**Comment by Abhijay007** [comment]
> @Abhijay007 This is good but I think we require a more subtle animation than this. The approach will be similar though; each section (here: a page in the book) will be able to display information about each page of the handbook.

Ya, I have some designs too and some different suggestions as well, I will share all the references with you on slack !!

**Comment by debo19** [comment]
![idea](https://user-images.githubusercontent.com/85789734/148989915-d0cd0d61-d01e-4468-8ec2-4a49ab44b4ed.jpg)
I got a very random idea from one of the pictures here 😆 Basically we have cards appearing in this manner, each card representing a topic from the handbook. On hover around the cards, we make the next card appear in front and make that highlighted.

**Comment by leecalcote** [comment]
Whoa. If this can be pulled off, it would be really neat.
