### ISSUE TITLE
[Learn] Width of the call to action (CTA) is getting cut short

### ISSUE THREAD

**Issue by vedant-kakde** [layer5io/layer5#2309]
**Description**

The width of the call to action (CTA) is getting cut short.
Link:- https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/

**Expected Behavior**

If it is expanded the image should display nicely.

**Screenshots**

<img width="1063" alt="Screen Shot 2021-10-29 at 12 49 44 PM" src="https://user-images.githubusercontent.com/69970950/139482824-6308c913-0289-4f9b-b8b9-7e1875cbe790.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
@theBeginner86 do you want to work on this??

**Comment by theBeginner86** [comment]
yeah, I'd like to try it.

**Comment by theBeginner86** [comment]
I've fixed it. Please have a look at the PR. 😃
