### ISSUE TITLE
Overflow of logos in Collaboration section

### ISSUE THREAD

**Issue by akshatnema** [layer5io/layer5#2311]
**Description**
Some of the logos are overflowing on the website. They should be given proper width so that every logo looks well.

**Current Behavior**
![image](https://user-images.githubusercontent.com/76521428/139579129-b7b1f3b9-3d5c-4014-a6ba-12eb53d1b926.png)

**Expected Behavior**
![image](https://user-images.githubusercontent.com/76521428/139579209-d30a4804-3c55-477d-9383-9bc7d95bac54.png)

**Environment:**
- Host OS: Windows
- Browser: Google Chrome

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
@leecalcote we've had this issue created about 5 times now, should we actually consider changing the design?

**Comment by akshatnema** [comment]
@warunicorn19 As per reader point of view, it looks weird to see this section as images are getting clipped at the ends.

**Comment by shubham-tyagi** [comment]
Hey @akshatnema, I have arrived at a solution but I don't think my solution is a long-term fix for this issue. So please solve it and submit the pull request.

**Comment by akshatnema** [comment]
Yeah sure @shubham-tyagi.

**Comment by imabp** [comment]
Just on a note, please do not self-assign, if you are not having a solution. It confuses and a bad practice considered.

**Comment by amino19** [comment]
> Just on a note, please do not self-assign, if you are not having a solution. It confuses and a bad practice considered.

@imabp: Agreed! :100:

**Comment by shubham-tyagi** [comment]
Agreed, Forgot to unassign myself. Still , Would keep that in mind going forward @imabp, thanks for such knowledgeable insight.
