### ISSUE TITLE
[Brand] Refresh Nighthawk logos; Remove "GET" from all pages

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2317]
**Current Behavior**
The current set of Nighthawk logos say "GETNIGHTHAWK". These are being replaced with a set that says "NIGHTHAWK".

**Desired Behavior**
1. Rename mega menu entry and project page to "Nighthawk". 
1. Remove "GET" from any of the descriptions of this project.
1. Rename brand section to "Nighthawk".
1. Replace old kit and logos with new kit and logos.

The website will still be getnighthawk.dev, but the logos have all dropped the "Get".

**Kit**
- [nighthawk-brand-kit.zip](https://github.com/layer5io/layer5/files/7450213/nighthawk-brand-kit.zip)

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Mr-DG-Wick** [comment]
one place where `getnighthawk` needs to be replaced with `nighthawk
![Screenshot (1074)_LI](https://user-images.githubusercontent.com/81250703/139738196-5e311cd5-fc99-422b-a773-3db292fe2846.jpg)
`

**Comment by warunicorn19** [comment]
@Mr-DG-Wick it's nighthawk rn. 
![Screenshot_20211102-020601](https://user-images.githubusercontent.com/53532328/139738520-e780480a-f4e9-4f75-a326-14cf8c428faa.jpg)

**Comment by Mr-DG-Wick** [comment]
Thanks for the info @warunicorn19 . I just realized that I was looking into Depopriya's build in her PR 😅

**Comment by Mr-DG-Wick** [comment]
one place where `getnighthawk` needs to be replaced with `nighthawk`

![Screenshot (1075)_LI](https://user-images.githubusercontent.com/81250703/139742127-0752693c-ef0e-4da9-aff3-063256a069ce.jpg)

**Comment by leecalcote** [comment]
Thank you, @Mr-DG-Wick. I believe each of these items are addressed now. 👍

**Comment by leecalcote** [comment]
Reopen this issue, if you find otherwise.
