### ISSUE TITLE
Add Project Hamlet to the Landscape 

### ISSUE THREAD

**Issue by yogi4** [layer5io/layer5#232]
Add Project Hamlet Secure multi vendor Multi mesh federation to Layer5 landscape . It's a multi-mesh interoperability.  

https://octo.vmware.com/project-hamlet-secure-multi-vendor-multi-mesh-federation-open-source/

**Comment by leecalcote** [comment]
SMI isn’t on the landscape either.

**Comment by yogi4** [comment]
> SMI isn’t on the landscape either.
would it be worth adding that section of service mesh interoperability ? I can envision that gaining some traction given the proliferation of Meshes and  customers wanting the interoperability?
