### ISSUE TITLE
[News] Create news item for the newly published IEEE Bridge article

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#2324]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the Layer5 Newsroom.

Note: The news should be about the published article in IEEE Bridge linked below. The link below is not a news article.

**Article:**
- Title: Analysing Service Mesh Performance
- Link: https://www.nxtbook.com/nxtbooks/ieee/bridge_issue3_2021/index.php#/p/16

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@navendu-pottekkat please see this one through.

**Comment by leecalcote** [comment]
@navendu-pottekkat, is this done?

**Comment by leecalcote** [comment]
Please create a tweet for this as well.

**Comment by navendu-pottekkat** [comment]
Yes. Making a PR for the news item now.
