### ISSUE TITLE
Consolidate two KubeCon China events into one

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2325]
**Current Behavior**
Two KubeCon China events are published, but should be combined into one entry.

**Desired Situation**
Collapse the contents of this event (https://layer5.io/community/events/kubecon-cloudnativecon-open-source-summit-china-2021) virtual into this event (https://layer5.io/community/events/kubecon-china-2021)

Delete the first event.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sakshamgurbhele** [comment]
Hi @leecalcote, I would love to take this issue.

**Comment by shubham-tyagi** [comment]
Thanks @sakshamgurbhele for taking this up.

**Comment by leecalcote** [comment]
Thanks for volunteering, @sakshamgurbhele. After being open a few days without volunteer, I went ahead and completed this task. I neglected to close this issue, though, which I will do now. 

Let's find a new issue for you. 👍

**Comment by sakshamgurbhele** [comment]
Ahhh, no problem.
