### ISSUE TITLE
Modify the CONTRIBUTING.md file to enhance readability

### ISSUE THREAD

**Issue by Mr-DG-Wick** [layer5io/layer5#2326]
**Required changes**
- Restructure the doc such that it is much easier to digest
- Provide a detailed guide on environment set up
- Modify grammar
- Fix links
- Fix minor typos

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by shubham-tyagi** [comment]
Hey @Mr-DG-Wick, you wanna work on this right? I am assuming on the basis of the slack conversation that you wanna work on this.

**Comment by Mr-DG-Wick** [comment]
Yup!

**Comment by shubham-tyagi** [comment]
@Mr-DG-Wick Thanks for taking this up 😃
