### ISSUE TITLE
Add NSMCon 2019 talk

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#234]
Title: "Adopting Network Service Mesh with Meshery"
Link: https://networkservicemesh.io/events/nsmcon2019/#schedule
Slides:

**Comment by gunjanmimo** [comment]
@leecalcote sir, where to add this link? exact file?

**Comment by leecalcote** [comment]
@gunjanmimo here is a link to the event - https://github.com/layer5io/layer5/blob/master/_includes/meshery.html#L188 or https://networkservicemesh.io/events/nsmcon2019/

and here is a link to the deck - https://calcotestudios.com/talks/decks/slides-nsmcon-kubecon-na-2019-adopting-network-service-mesh-with-meshery.html

and here is a link to the recording - https://www.youtube.com/watch?v=4xKixsDTtdM

**Comment by leecalcote** [comment]
Can you add this talk to the list of presentations here - https://github.com/layer5io/meshery/blob/master/docs/pages/index.md?

**Comment by leecalcote** [comment]
Fixed by https://github.com/layer5io/meshery/pull/515
