### ISSUE TITLE
Missing Pagination in Handbook FAQ page

### ISSUE THREAD

**Issue by toth2000** [layer5io/layer5#2342]
**Description**

The FAQ page does not have a pagination (previous and next) button.
Link: https://layer5.io/community/handbook/faq

**Expected Behavior**

Add Previous Button at the bottom of the FAQ section.

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by warunicorn19** [comment]
@toth2000 added this in my recent PR https://github.com/layer5io/layer5/pull/2339

**Comment by warunicorn19** [comment]
we can close this issue, as there's already a fix put in.

**Comment by toth2000** [comment]
@warunicorn19 sorry, I didn't know.

**Comment by warunicorn19** [comment]
No problem 😄 @toth2000
