### ISSUE TITLE
[Task] Modify content such that links open on different tabs.

### ISSUE THREAD

**Issue by Mr-DG-Wick** [layer5io/layer5#2347]
**Current Behavior**

The links under the pre-requisites section redirect user away from the Learning path [website](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers). 
For reference see this : 
https://user-images.githubusercontent.com/81250703/141525085-eef17e46-6dda-46dd-aead-a6a38d0419f1.mp4

**Desired Situation**

The links should open on a different tab.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Sayantan-s** [comment]
Hey, @Mr-DG-Wick can you please assign this to me ?

**Comment by Mr-DG-Wick** [comment]
Thanks for taking this up!! @Sayantan-s

**Comment by Mr-DG-Wick** [comment]
How is the progress on this one? @Sayantan-s . Feel free to join the [slack](https://join.slack.com/t/layer5io/shared_invite/zt-rgbyt4kj-6PUUyqY9SfQGRSt_oZV9yQ) workspace if you need further assistance :)

**Comment by leecalcote** [comment]
The prerequisites direct the user to another page on the layer5.io site. It's not clear to me that a _blank target is necessary.
