### ISSUE TITLE
Change "Topics" to "Resources"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2348]
**Current Behavior**
The current `/topics` needs renamed to `/resources`. This change affects queries, templates, collection, page, and so on.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
@leecalcote I've already changed `topics` to `resources` in my open PR [#2320](https://github.com/layer5io/layer5/pull/2320) while adding the articles 😅

**Comment by leecalcote** [comment]
I just built that branch and just realized this. I was returning to this issue to comment and close out, then I see that you have already commented. Holy moly, ⚡ . There is no question that you continue to earn your nickname. Dang girl, you're a speedy one.
