### ISSUE TITLE
[Task] Organize the content of Navbar to have equal padding

### ISSUE THREAD

**Issue by Mr-DG-Wick** [layer5io/layer5#2350]
**Current Behavior**
The navbar has unequal spacing as you can see from the attached image. According to general UI principle it is not ideal at present.

![site_review_2](https://user-images.githubusercontent.com/81250703/141796266-35552568-09a5-41f1-811b-fc6e2427a428.png)

**Desired Situation**
The white space/padding at the top and bottom must be same or in other words we need to align the content to the middle of the navbar.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
Sounds good @ruhi09

**Comment by Mr-DG-Wick** [comment]
Thanks for taking this up! @ruhi09
