### ISSUE TITLE
[Landscape] Ensure that SPIFFE and SPIRE are displayed on the Service Mesh Landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2364]
**Current State:**
SPIFFE and SPIRE's use by service meshes is cataloged in the [service mesh landscape](https://layer5.io/landscape)'s data model, but doesn't seem to be exposed on the landscape's "Functional" table.

**Desired State:**
A column dedicated to SPIFFE/SPIRE should be visible. See the landscape [data here](https://github.com/layer5io/layer5/tree/master/src/sections/Landscape).

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Ciggzy1312** [comment]
Hey @leecalcote I might give it a try
And the Figma link isn't working at least for me. Probably I don't have the permission for that so if you can look up to it

**Comment by YashKamboj** [comment]
@Ciggzy1312 Fill this https://layer5.io/newcomer form out and join the community for the access.

**Comment by Ciggzy1312** [comment]
Hey @leecalcote can you just lead me on if this is how the desired output should look like?
![image](https://user-images.githubusercontent.com/65884232/142775985-8b8562c9-632c-43d2-9890-72b7ec5c01cb.png)

If yes then here I am using some hardcoded values for the mesh compatibility so if you can tell where to find or how to get the values then I can alter it and make a PR

**Comment by leecalcote** [comment]
@Ciggzy1312, good work. Yes, your mock-up is what is essentially needed. I'll look for this data...

**Comment by Ciggzy1312** [comment]
Hey @leecalcote any update on the required data?

**Comment by Nikhil-Ladha** [comment]
It turns out that for some reason the SPIFFE/SPIRE data was missed out while migration.
Anyways, you can find the data in this PR #1082
