### ISSUE TITLE
[Resources] Navigation in resources

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2369]
**Current Behavior**
Currently, the Resources area looks exactly like the Blog area

**Desired Situation**
We're in need of figuring out how we want to change the way visitors navigate this interface so that it isn't just a repeat of the blog collection, but a perusable catalog of topics. It's ok to include repetitive content from /events, /blogs, /news. Filters that we'll want to account for on this page include content:

```
TYPE

- Case Study
- Presentation
- Demo
- Recorded Webinar
- Interview
- Blog
- News
- White Paper
- Article
- Tutorial
- FAQ
- Guide
- Podcast

---------------------

PRODUCT

- Meshery
- Service Mesh Performance
- Nighthawk

---------------------

TECHNOLOGY

- Cloud
- Kubernetes
- Docker
- WebAssembly
- JWT
- API

---------------------

SERVICE MESH

- Consul
- Linkerd
- Istio
- Open Service Mesh
- Kuma
- Network Service Mesh
- Traefik Mesh

```

For inspiration see:
1.  https://www.hashicorp.com/resources

The way that the categories and filters are on HashiCorp's resources page is perfect. The categories colorize onHover. You can clear the filter. It's great - https://www.hashicorp.com/resources?products=terraform&products=consul

See other examples:
2.  https://datadoghq.com/resources 
3.  https://d2iq.com/resources

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
The segmentation of events into categories as seen on https://layer5.io/community/events is another very simple example.

**Comment by Ciggzy1312** [comment]
I might look into this and give it a try

**Comment by warunicorn19** [comment]
Thank you @Ciggzy1312

**Comment by leecalcote** [comment]
I'm looking forward to seeing this one @Ciggzy1312 😄

**Comment by Ciggzy1312** [comment]
Yep, working on it

**Comment by Ciggzy1312** [comment]
If this is how the sidebar should look and the filtering of resources would be done on the basis of this then we have to alter or add to the data which is being visible in the graphql playground.
Assuming it is being fetched from the backend any idea how to access the data?


```
TYPE

- Case Study
- Presentation
- Demo
- Recorded Webinar
- Interview
- Blog
- News
- White Paper
- Article
- Tutorial
- FAQ
- Guide
- Podcast

---------------------

PRODUCT

- Meshery
- Service Mesh Performance
- Nighthawk

---------------------

TECHNOLOGY

- Cloud
- Kubernetes
- Docker
- WebAssembly
- JWT
- API

---------------------

SERVICE MESH

- Consul
- Linkerd
- Istio
- Open Service Mesh
- Kuma
- Network Service Mesh
- Traefik Mesh
- ```

**Comment by leecalcote** [comment]
@Ciggzy1312 given that this in an unfamiliar area for you and the need for us to move more quickly, let's allow @debo19 to carry this work forward with you onboard in audit-mode; with you as a reviewer, so that we can unblock progress while simultaneously ramping you up.

**Comment by leecalcote** [comment]
@debo19 please proceed as time permits.

**Comment by Ciggzy1312** [comment]
Sure
