### ISSUE TITLE
[Events] KubeCon China: Chinese Translation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2372]
**Current Situation**

Hi @davidchengl74, I didn't see your note earlier. Yes, a Chinese transcription of these two talks - https://github.com/layer5io/layer5/blob/master/src/collections/events/kubecon-china-2021/index.mdx, would be great. You can append a Chinese version of the description of these talks to into this same `index.mdx` file. Please do. 

Also, we will have Meshery (https://meshery.io) and Service Mesh Performance (https://smp-spec.io) project office hours that we will need to post under layer5.io/events as well. We will confirm these project office hours soon.

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/2281#issuecomment-977192322_

**Desired State**

1) Description of two talks in Chinese added to https://layer5.io/community/events/kubecon-china-2021
2) Description of two project office hours in Chinese added to https://layer5.io/community/events/kubecon-china-2021

@navendu-pottekkat please assist with a description of Project Office Hours that @davidchengl74 can use.

**Comment by leecalcote** [comment]
@davidchengl74, if you will comment on this issue, a community manager will see that it gets assigned to you. 👍 

Thanks for jumping in to assist, David!

**Comment by navendu-pottekkat** [comment]
Sure, I will write one for the project office hours.

**Comment by leecalcote** [comment]
If @davidchengl74 doesn't respond today, @Aisuko could you take this one?

**Comment by Aisuko** [comment]
> If @davidchengl74 doesn't respond today, @Aisuko could you take this one?

Hi @leecalcote. You are welcome. I can take this one.

**Comment by Aisuko** [comment]
Please help us do a review. I know you are professional on this. @Micost

**Comment by Micost** [comment]
@Aisuko  Thanks .  let me know then .

**Comment by navendu-pottekkat** [comment]
@Aisuko Here is a description for the Meshery and SMP project office hours.

Meshery project office hours:

```
Join the Meshery project office hours at KubeCon China 2021 to learn more about the CNCF's latest service mesh project and its maintainers.

Come and discover why Meshery is the easiest way to get started with 10+ service meshes!

Speakers:
Aisuko Lee
Navendu Pottekkat
(waiting for other names based on timing and availability)
```

Service Mesh Performance project office hours:

```
Join the Service Mesh Performance project office hours at KubeCon China 2021 and get introduced to the new standard of cloud native performance characterisation and to its open source maintainers.

Learn what Service Mesh Performance is and how Meshery's implementation uses it to measure the performance of any service mesh available.

Speakers:
(waiting for names based on timing and availability)
```

I will confirm the speaker names as soon as possible.

**Comment by Aisuko** [comment]
> @Aisuko Here is a description for the Meshery and SMP project office hours.
> 
> Meshery project office hours:
> 
> ```
> Join the Meshery project office hours at KubeCon China 2021 to learn more about the CNCF's latest service mesh project and its maintainers.
> 
> Come and discover why Meshery is the easiest way to get started with 10+ service meshes!
> 
> Speakers:
> Aisuko Lee
> Navendu Pottekkat
> (waiting for other names based on timing and availability)
> ```
> 
> Service Mesh Performance project office hours:
> 
> ```
> Join the Service Mesh Performance project office hours at KubeCon China 2021 and get introduced to the new standard of cloud native performance characterisation and to its open source maintainers.
> 
> Learn what Service Mesh Performance is and how Meshery's implementation uses it to measure the performance of any service mesh available.
> 
> Speakers:
> (waiting for names based on timing and availability)
> ```
> 
> I will confirm the speaker names as soon as possible.

Noted and thanks.

**Comment by gyohuangxin** [comment]
@Aisuko Hi, it's a good translation and I leaved some suggestions, thanks!

**Comment by Aisuko** [comment]
> @Aisuko Hi, it's a good translation and I leaved some suggestions, thanks!

Thanks a lot and the useful suggestions.
