### ISSUE TITLE
[handbook] Rephrase "Community Ladder" title to "Community Journey"

### ISSUE THREAD

**Issue by MarioArriaga92** [layer5io/layer5#2378]
**Current Behavior**

As a Layer5 Contributor, the word "Ladder" communicates a hierarchy to climb up, while  "Journey" interprets better how a Contributor experiences as described in https://layer5.io/community/newcomers

This applies for both:
1. https://layer5.io/community/handbook
![Screen Shot 2021-11-26 at 10 54 29](https://user-images.githubusercontent.com/23443575/143612265-2a5b7ee0-3ff6-480b-ae26-03c1321abcbc.png)

2. https://layer5.io/community/handbook/contributor-ladder
![Screen Shot 2021-11-26 at 10 55 13](https://user-images.githubusercontent.com/23443575/143612328-50d91654-7e12-4cd5-9a95-32c428b0e1cf.png)

**Desired Situation**

As a Layer5 Contributor, I want to see "Contributor Journey" in "Contributor Handbook" & Contributor Ladder" pages

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by lpizzinidev** [comment]
Hi 🤚 Can I work on this issue?

**Comment by Mr-DG-Wick** [comment]
Here you go @lpizzinidev :)

**Comment by lpizzinidev** [comment]
@Mr-DG-Wick Thanks! I'll be working on this 💪🏻
