### ISSUE TITLE
[Community] Member Profile: Mario Arriaga

### ISSUE THREAD

**Issue by sayantan1413** [layer5io/layer5#2379]
**Current Behavior**

@MarioArriaga92  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @MarioArriaga92  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: MarioArriaga92
- Twitter: 
- LinkedIn: mario-arriaga-29a600b5
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sayantan1413** [comment]
Hey @MarioArriaga92 can you provide a **short bio** and a link to your picture (like a google drive link)?

**Comment by Abusayid693** [comment]
Hey @sayantan1413 I would like to look into it , but would need short bio from Mario, you assign this to me

**Comment by leecalcote** [comment]
Thank you, @sayantan1413

**Comment by MarioArriaga92** [comment]
Thanks @sayantan1413 & @Abusayid693, here's my bio:
"Mario Arriaga is a detail-oriented Mexican Software Engineer specialized in Automated Testing, CI/CD, DevOps, Test Engineering and development of Cloud Native Distributed Microservices & Event-driven applications and services. He strives for excellence when building high-quality software solutions for the most challenging business scenarios and considers himself passionate about mastering latest technologies, methodologies and principles to iteratively improve the quality and impact of what the teams he contributes to deliver together."

**Comment by sambhavsaxena** [comment]
is this issue resolved yet?

**Comment by Abusayid693** [comment]
@sambhavsaxena I am working on it probably by today
