### ISSUE TITLE
[Bug] Careers page cards have unexpected text alignments on hovering 

### ISSUE THREAD

**Issue by Abusayid693** [layer5io/layer5#2380]
**Description**
 The text in career cards tries to self align itself on hovering making a weird transformation.

**Expected Behavior**
The text can be either aligned left or centered and image pop-up on hovering would not effect positioning of text, thus it can avoid  weird transformation 

Please check attached video

**Screenshots**

**Environment:**
- Host OS: Mac OS
- Browser: Safari

---

[Optional] **Additional Context**

https://user-images.githubusercontent.com/35341198/143657421-8e37b3bc-6199-4af3-8d31-f3dc1c32ae9d.mov

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sahilsuman933** [comment]
Hello @Abusayid693, can I work on this issue?

It might take me a few weeks to fix this issue cause this will be my first open-source contribution. So if this fix is not urgent, then can you please assign this task to me?

**Comment by Mr-DG-Wick** [comment]
imo this doesn't seem like an issue. I'll have to talk to other members on this one.

**Comment by Mr-DG-Wick** [comment]
After discussing with @Nikhil-Ladha , We think this issue can be closed as the current animation seems fine to us.
