### ISSUE TITLE
Defect: Bad links in Layer5.io/events/kubecon-china-2021

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2381]
**Description**
The links to "Solving the Service Mesh Adopter’s Dilemma" and "CNCF TAG Network and Service Mesh Working Group" in layer5.io/events/kubecon-china-2021 are broken. 

**Expected Behavior**
The right link to "Solving the Service Mesh Adopter’s Dilemma" can be found [here](https://static.sched.com/hosted_files/kccncosschn21/88/TAG%20Network%20at%20KubeCon%20China%202021.pdf)

The right link to  "CNCF TAG Network and Service Mesh Working Group" can be found [here](https://kccncosschn21.sched.com/?iframe=yes&w=100%25&sidebar=yes&bg=no#)

**Screenshots**
This is the image of the Error message.

![broken link](https://user-images.githubusercontent.com/64528871/143674939-93f2d171-f577-431f-81da-6564805325c7.PNG)

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Mr-DG-Wick** [comment]
Would you like to work on this? @sahilsuman933

**Comment by sahilsuman933** [comment]
@Mr-DG-Wick Yeah Sure! :)

**Comment by iambami** [comment]
Please go ahead @sahilsuman933
