### ISSUE TITLE
[Navigation] "Try Meshery" button not middle-aligned vertically on window size larger than 1550px

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2386]
**Description**
The primary call to action button in the https://layer5.io site is a "Try Meshery" button in the upper righthand corner. These screenshots document its behavior at different window sizes.

Window size < 1550px:
<img width="839" alt="Screen Shot 2021-11-29 at 8 18 19 PM" src="https://user-images.githubusercontent.com/7570704/143973958-b98c2324-89ca-41ff-a0cc-ecaf3e9fc8d1.png">

Window size > 1550px:
<img width="714" alt="Screen Shot 2021-11-29 at 8 16 09 PM" src="https://user-images.githubusercontent.com/7570704/143973967-3b72e5ad-1c12-4e13-bd4b-feab12a6f514.png">

**Expected Behavior**
This button should be vertically-centered at larger window sizes.

**Environment:**
- Host OS: macOS
- Browser: Safari and Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sahilsuman933** [comment]
@leecalcote, sir, can you assign this work to me and I completed the previous fix, so could you please check that too.
