### ISSUE TITLE
[News] 6 CNCF Service Mesh Tools

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2389]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the [Layer5 Newsroom](https://layer5.io/news).

**Article:**
- Title: 6 CNCF Service Mesh Tools
- Link: :meshery: Meshery and :smp: Service Mesh Performance highlighted as two of six CNCF service mesh tools - https://containerjournal.com/features/6-cncf-service-mesh-tools/

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by MukulKolpe** [comment]
Hey @leecalcote can I work on this issue?

**Comment by warunicorn19** [comment]
please go ahead @MukulKolpe

**Comment by leecalcote** [comment]
Thank you, @MukulKolpe

**Comment by MukulKolpe** [comment]
Should I use the same image as on the thumbnail of the article?

![Service-Mesh-Pattern](https://user-images.githubusercontent.com/78664749/144432882-fa2c6e12-3be7-44fb-9ab3-6e8a9c6bb4ec.jpg)

and Date should be today's date or the date on which this article was published?
![image](https://user-images.githubusercontent.com/78664749/144433287-86ebd39d-386d-4d4c-8b5a-0cf76cb99e0e.png)

**Comment by leecalcote** [comment]
Great questions:

- yes, the same image, please.
- use the date of the publication, pretty please.
