### ISSUE TITLE
upload the KubeCon China slides

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#2396]
**Current Behavior**
The recently created [slides for KubeCon China](https://docs.google.com/presentation/d/1vI2FSL4nc37HKpxbsbwVoMXixaTUAIpJuf2mB7LOl-0/edit#slide=id.geac03adfe0_0_398) does not exist on the layer events page

**Desired Behavior**
upload this slide on the [layer5 site](https://layer5.io/community/events)

---
**Screenshots / Mockups**

![Screenshot 2021-12-03 at 17 32 21](https://user-images.githubusercontent.com/62384659/144638487-f339071c-2dd8-4bf7-a08a-f9151bc902a6.png)

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Upload should be in PDF form.

**Comment by Aju100** [comment]
Hi @leecalcote @Anita-ihuman, I am new here and I would love to be part of it. Can you please assign to me ??

**Comment by Anita-ihuman** [comment]
Sure @Aju100
