### ISSUE TITLE
[Community] Add Community badge for Debopriya, Deepak and Bami

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2397]
**Description**
@debo19 @Mr-DG-Wick and @iambami have recently been acknowledged as community managers.

**Expected Behavior**
Add community badges to their member profiles here(https://layer5.io/community/members)

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Prakhar-Agarwal-byte** [comment]
I would like to work on this issue. Please assign this to me

**Comment by vedant-kakde** [comment]
Thanks @Prakhar-Agarwal-byte . Go ahead 🚀

**Comment by Prakhar-Agarwal-byte** [comment]
@vedant-kakde The member profile for @Mr-DG-Wick  and @iambami is missing

**Comment by warunicorn19** [comment]
Hey @Prakhar-Agarwal-byte you're absolutely right, I completely forgot about that. Could you add profiles for them as well?? I'll open up issues for their profiles.

**Comment by Abhijay007** [comment]
@warunicorn19 is resolved right? or do we need that icon that depicts a community in the pictures? just like we did it for meshmates?

**Comment by leecalcote** [comment]
Thanks for asking. I think @Prakhar-Agarwal-byte knocked this one out.
