### ISSUE TITLE
[Community] Member Profile: Deepak Gupta

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2400]
**Current Behavior**

@Mr-DG-Wick  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Mr-DG-Wick as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Mr-DG-Wick 
- Twitter: Mr_dg_wick
- LinkedIn: https://www.linkedin.com/in/mrdgwick/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Prakhar-Agarwal-byte** [comment]
I will create a profile for @Mr-DG-Wick

**Comment by warunicorn19** [comment]
Hey @Mr-DG-Wick could you please provide a small bio, location and a picture of yourself. 😃 Congrats!!

**Comment by Mr-DG-Wick** [comment]
Thanks a ton @Aditya Chatterjee 😄  
Thank you for taking this up @Prakhar Agarwal 😄 
Here's all you need Prakhar: 

**Bio**: Passionate about creative technologies. An organized individual that desires to learn and develop deep understanding of people and tech. Always eager to execute on the array of ideas held together by my sticky notes posted on my wall.

**Location**: Goa, India
**Image** :
![Dev_pic_1](https://user-images.githubusercontent.com/81250703/144724059-7989c04a-70b3-4c32-857e-d24241d643f8.png)
