### ISSUE TITLE
[Community] Member Profile: Atinuke Oluwabamikemi Kayode

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2401]
**Current Behavior**

@iambami  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @iambami  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @iambami 
- Twitter: oluwabamikemi
- LinkedIn: https://www.linkedin.com/in/atinuke-kayode-5b838b1b7/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Prakhar-Agarwal-byte** [comment]
I will create a profile for @iambami

**Comment by warunicorn19** [comment]
@iambami could you please provide a small bio, location, and a picture of yourself.😃 Congratulations!

**Comment by warunicorn19** [comment]
Thank you @Prakhar-Agarwal-byte.

**Comment by iambami** [comment]
Hi🤩🤩
I will do that now.
