### ISSUE TITLE
Add self referencing Canonical URLs to the website

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#2402]
**Current Behavior**

Canonical URLs are used by search engines to identify duplicative content.

We could have unintentional duplicative content due to using "tags" and "categories".

We could also be duplicating content when we create the `/resources` page.

Using Canonical URLs is also recommended by Google.

**Desired Situation**

Add self-referencing canonical URL tags to the page headers.

See:

[Canonical Tags for SEO](https://detailed.com/canonical-tags/)
[What is a Canonical URL](https://blog.alexa.com/canonical-url/)
[gatsby-plugin-canonical-urls](https://www.gatsbyjs.com/plugins/gatsby-plugin-canonical-urls/)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Nikhil-Ladha** [comment]
The solution that we need https://markshust.com/2019/04/27/creating-canonical-urls-specific-pages-gatsby/.
