### ISSUE TITLE
[Chore] Create a gh workflow to notify about beginner-friendly issue on slack.

### ISSUE THREAD

**Issue by Mr-DG-Wick** [layer5io/layer5#2403]
**Current Behavior**

We currently don't have an _automation_ that sends out a message in slack's `#newcomers` channel about beginner friendly issues when one (beginner-friendly issue) is created.

**Desired Situation**

A `gh` workflow needs to be created that posts a message in the `#newcomers` channel if any new issue is marked with `newcomers-only` or `good-first-issue`

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@theBeginner86 you might be interested in this. Acceptance criteria for completion of this issue is: definition of a centralized workflow and its subsequent reuse across all the repos.

**Comment by theBeginner86** [comment]
@Mr-DG-Wick please assign me this issue. I'd like to give it a shot.

**Comment by Mr-DG-Wick** [comment]
Here you go @theBeginner86 🚀 . Thank you!
