### ISSUE TITLE
[Community] Member Profile: Manav Kapoor

### ISSUE THREAD

**Issue by Mr-DG-Wick** [layer5io/layer5#2404]
**Current Behavior**

@manav1403  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @manav1403 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @manav1403 
- LinkedIn: https://www.linkedin.com/in/manav-kapoor-14a14018a
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Mr-DG-Wick** [comment]
@manav1403 could you please provide a small bio, location, and a picture of yourself.😃 Congratulations!

**Comment by leecalcote** [comment]
Whoo-hoo, @manav1403!

**Comment by leecalcote** [comment]
@Mr-DG-Wick see line 349 in Community Members sheet.

**Comment by Deepansharora27** [comment]
I would like to work on this as well 
@leecalcote @Mr-DG-Wick

**Comment by vedant-kakde** [comment]
Thanks @Deepansharora27 . Go ahead 🚀

**Comment by Mr-DG-Wick** [comment]
Thanks @Deepansharora27 😄

**Comment by Mr-DG-Wick** [comment]
@manav1403 could you please provide a small bio, location, and a picture of yourself.😃 Congratulations!

**Comment by manav1403** [comment]
Thanks @Mr-DG-Wick here are the details

Location: Jodhpur. Rajasthan India
Bio: I love technology, so my work is nothing but my love. #lovefortechnology
Picture: 
![my_image](https://user-images.githubusercontent.com/51405571/144991571-c5fcc750-b6f4-41d5-85d1-97bae68fd41c.jpg)
