### ISSUE TITLE
Missing whitespace

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2408]
**Description**
There's a missing whitespace between "Map" and "the" on https://layer5.io/community.  
<img width="1176" alt="Screenshot 2021-12-10 at 12 13 52 PM" src="https://user-images.githubusercontent.com/53532328/145529654-72f071a1-cd9a-415c-9b1b-71c7b6da2f84.png">

**Expected Behavior**
Add space. 

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Abhijay007** [comment]
can I work on this ? @warunicorn19  can you please assign me this issue

**Comment by Mr-DG-Wick** [comment]
alright @Abhijay007 👍🏽

**Comment by Abhijay007** [comment]
@Mr-DG-Wick  for assigning I will soon open a PR for this
