### ISSUE TITLE
Update icon used for social media sharing of layer5.io/meshery page

### ISSUE THREAD

**Issue by girishranganathan** [layer5io/layer5#241]
**Current Behaviour**
The old logo is being used for social media sharing of the layer5.io/meshery page.

**Expected Behaviour**
The new logo should be used for social media sharing of the layer5.io/meshery page.

**Comment by leecalcote** [comment]
This line is the code that needs updated to link to the latest Meshery logo - https://github.com/layer5io/layer5/blob/master/_includes/head.html#L36

**Comment by leecalcote** [comment]
Logos - https://github.com/layer5io/layer5/tree/master/assets/images/meshery

**Comment by leecalcote** [comment]
@anandrkskd we actually need the [landscape icon ](https://github.com/layer5io/layer5/blob/master/assets/images/buttons/landscape.svg) to show up for https://layer5.io/landscape, too.

**Comment by leecalcote** [comment]
I think we're all good here now. 👍
