### ISSUE TITLE
Added dedicated badges to the profiles 

### ISSUE THREAD

**Issue by Abhijay007** [layer5io/layer5#2414]
**Current Behavior**
Currently, on the community manager page we only have badges and a dedicated page for meshmates members. 

**Desired Behavior**
iI we add dedicated badges (just like we did for meshmates( circularar ring depicting meshmate members) ) to every user profile then it looks good and we can also make dedicated page for other members profile such as Meshery, Nighthawk, maintainers, and other community roles as well and if those pages already exist ( in some cases they do ) we can link them to those badges.  

---
**Screenshots / Mockups**
![image](https://user-images.githubusercontent.com/64387054/145703735-f2472fd5-7fc2-4ce5-b087-f4242f60daf2.png)

![image](https://user-images.githubusercontent.com/64387054/145703725-2af0f179-9224-45a4-a23c-ae02f29b3ec5.png)

**Challenge**
Only one challenge I feel is that if a person is associated with multiple roles so how can we display multiple rings around his/her profile 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
@Abhijay007 This behavior is not required at the moment. The intention is to display only the MeshMates badge on the members page. Also, the badges on each individual profile are already linked to the respective pages.

**Comment by debo19** [comment]
Thank you for this, but let's close this for now.
