### ISSUE TITLE
Dropdown enhancement on programs page

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2416]
**Current Behavior**
![Films   TV 13-12-2021 19_50_07 (2)](https://user-images.githubusercontent.com/85789734/145829225-8481f82c-fdd7-425d-b090-69e9a30ad6bf.png)

Most programs pages do not have any record of the previous year's events. This causes the dropdown on each page to only display one item. The purpose of the dropdown isn't quite clear.

**Desired Behavior**
- The dropdown should only be visible on pages where we have past records to navigate to.
- It should be hidden in programs where only one year's information is available.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Ciggzy1312** [comment]
Yeah I will give it a try

**Comment by Mr-DG-Wick** [comment]
Hi @Ciggzy1312 would you like to discuss about this issue in today's website meeting? Just so that we can help you speed up stuff 😄

**Comment by Ciggzy1312** [comment]
@Mr-DG-Wick sure

**Comment by Nikhil-Ladha** [comment]
The issue doesn't seem to be valid.
The dropdown was never intended to be a global navigator, we have the cards on the layer5.io/programs page for that.
And, the dropdown on each program does list all the prior years in the archive. If it's showing only 1 item that means the data is not there, and not that it's an issue. For eg: if you check the GSoC program it lists all the 3 years in the dropdown.

**Comment by debo19** [comment]
@Nikhil-Ladha We actually discussed this in one of the calls. Since the previous year data is not present for any other program other than gsoc, the presence of the drop-down wasn't very clear. That is why it was suggested to probably include all programs and their respective years if any.
