### ISSUE TITLE
Add Meshery Adapter for Cilium Service Mesh as an Alpha adapter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2418]
**Current Behavior**

**Desired Behavior**
- [ ] Add to the list on https://layer5.io/service-mesh-management/meshery

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhijay007** [comment]
I want to work on this issue, please assign this issue to me, thanks

**Comment by Abhijay007** [comment]
Thanks @Sayantan-s :)

**Comment by Abhijay007** [comment]
@leecalcote sorry but I am bit confused, can you please explain it once that which list you are referring to on : https://layer5.io/service-mesh-management/meshery, as I am unable to see any specific list on this page, maybe I am taking it wrong but are you referring to the adapters list on https://docs.meshery.io/concepts/architecture/adapters  ?

**Comment by YashKamboj** [comment]
@Abhijay007 I think he is referring to the list below Lifecycle , i can't find any other list on the page.

**Comment by Abhijay007** [comment]
> @Abhijay007 I think he is referring to the list below Lifecycle, i can't find any other list on the page.

Ya, I also think that but then how can I add Cilium Service Mesh as an "Alpha" adapter, one way of doing this is that I can insert text in this format: cilium service mesh ( Alpha) means by specifying it as an alpha in brackets but then is looks bit differ from others as we haven't specified any of those as "stable" or "beta" In that list.

**Comment by leecalcote** [comment]
Gents, you're right: I shouldn't have included "Alpha" in the issue's description. There isn't a distinguishment between stable, beta, alpha here (only on the other web properties), so please ignore the Alpha portion of this request.

Regarding where to mak
<img width="404" alt="Screen Shot 2021-12-16 at 2 34 44 PM" src="https://user-images.githubusercontent.com/7570704/146445378-0a5213ee-5fb9-438e-b0f3-7063b2d7b912.png">
e the update on the page, it's here:

**Comment by leecalcote** [comment]
> I want to work on this issue, please assign this issue to me, thanks

This is closer, @Abhijay007, but in this case you have put three sentences into a single, run-on sentence.

**Comment by Abhijay007** [comment]
> > I want to work on this issue, please assign this issue to me, thanks
> 
> This is closer, @Abhijay007, but in this case you have put three sentences into a single, run-on sentence.

Thanks again, I will keep that in mind !!
