### ISSUE TITLE
Add Cilium logo to multi-mesh SVG

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2419]
**Current Behavior**
The animated SVG on https://layer5.io/service-mesh-management/meshery/operating-service-meshes is missing the Cilium logo.

**Desired Behavior**
The Cilium logo should be one of the many service mesh logos included in this animation.

**Screenshots / Mockups**

<img width="537" alt="Screen Shot 2021-12-16 at 12 34 09 PM" src="https://user-images.githubusercontent.com/7570704/146428883-deb795ac-99fc-45e0-9338-70265de934ea.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhijay007** [comment]
I am familiar with SVGs animations and know how to manipulate them, can I open a PR for this?

**Comment by warunicorn19** [comment]
Please go ahead @Abhijay007, This is actually not an SVG manipulation actually, you'd have to mention the size of the line and add an SVG for cilium, that should do the trick.

**Comment by Abhijay007** [comment]
> Please go ahead @Abhijay007, Just to help you out you'd have to mention the size of the line and add an SVG for cilium, that should do the trick.

ya got it :)

**Comment by Abhijay007** [comment]
@leecalcote  @warunicorn19  is this fine, do I need to edit positioning? 

https://user-images.githubusercontent.com/64387054/146447059-c1825bf3-61f6-4c71-9dda-a2f58819102d.mp4

can I open a PR for this if this looks fine?

**Comment by warunicorn19** [comment]
Looks okay to me, @leecalcote ??

**Comment by Abhijay007** [comment]
@leecalcote any update on this?

**Comment by leecalcote** [comment]
Not too shabby. The overall symmetry feels a little off in so much as the uniformity of spacing and positioning between elements. If you're able to shift them around a little without much effort, it would be worth it.

**Comment by Abhijay007** [comment]
> Not too shabby. The overall symmetry feels a little off in so much as the uniformity of spacing and positioning between elements. If you're able to shift them around a little without much effort, it would be worth it.

ok got it, will do that :)

**Comment by Abhijay007** [comment]
@leecalcote , @warunicorn19  is it fine now ??

![image](https://user-images.githubusercontent.com/64387054/146657007-431740a2-7d17-4736-b35c-0d6dfec75503.png)
