### ISSUE TITLE
[Event] Measuring Service Mesh Performance 101

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/layer5#2421]
Please add the following event to layer5.io/events.

**Event:**
- Event Title: Measuring Service Mesh Performance 101
- Event Link: https://sched.co/siKF
- Talk Description: See the event link
- Speaker: [Navendu Pottekkat](https://layer5.io/community/members/navendu-pottekkat)
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Abhijay007** [comment]
CI is new for me, but I can give it a try, can you please assign this issue to me

**Comment by Abhijay007** [comment]
I want to work on this issue, can you please assign this to me :)
