### ISSUE TITLE
[Event] Journey Into the World of Service Meshes and Meshery

### ISSUE THREAD

**Issue by sudo-NithishKarthik** [layer5io/layer5#2422]
Please add the following event to layer5.io/events.

Event:

    Event Title: Journey Into the World of Service Meshes and Meshery
    Event Link: sched.co/siEs
    Talk Description: See the event link
    Speakers: Nithish Karthik, Aditya Krishna Sharma

Contributor Resources

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the master branch.

    See contributing instructions
    See Layer5 site designs in this Figma project.

**Comment by Prakhar-Agarwal-byte** [comment]
Can I do this?

**Comment by Mr-DG-Wick** [comment]
sure @Prakhar-Agarwal-byte 😄
