### ISSUE TITLE
[Blog] How to show your Layer5 pride with your iTerm terminal

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2423]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** How to show your Layer5 pride with your iTerm terminal
**Topic:** Using custom terminal settings to include project pride.
**Core points to convey in the post:** 
1. What image format works best. 
1. Where to get different community and project logos. 
1. How to keep high contrast for legibility. 
1. Export and share your sample settings.  

_Note that you'll need access to a MacOS in order to run iTerm2._

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Vidyaa123** [comment]
Hi @leecalcote, I am interested in taking a stab at this... Can you please give me more info? Thanks

**Comment by leecalcote** [comment]
The description is pretty complete and has about as much info as I can provide without writing it. 

Here is a start to the post in this branch - https://github.com/layer5io/layer5/tree/CU-1vjd6x1/Layer5-iTerm2-blog-post. You can checkout this branch and continue from there.

**Comment by unnati914** [comment]
could i help @Vidyaa123 with this? @leecalcote

**Comment by leecalcote** [comment]
That would be great, yes, @unnati914.

**Comment by unnati914** [comment]
thank you so much!

**Comment by Vidyaa123** [comment]
That will be great. Cool thanks @unnati914, @leecalcote

**Comment by leecalcote** [comment]
<img width="883" alt="Screenshot 2022-01-15 at 1 12 48 PM" src="https://user-images.githubusercontent.com/7570704/149635804-9c840d9c-00ed-4609-bf37-afbdc1165b3a.png">

From @warunicorn19

**Comment by leecalcote** [comment]
Clearing stale assignment in order to open up this issue for other contributors who might like to try their hand here.
