### ISSUE TITLE
UI issues in the website

### ISSUE THREAD

**Issue by abrahamalen** [layer5io/layer5#2429]
**Current Behavior**
The **drop shadow** of the **navbar** and other **splash/pop-up screens** are high and not aesthetic for a professional website.

**Desired Behavior**
Drop shadows must be **light** and are used to differentiate the layers when a page overlaps the other. Points given for the drop-shadow should be reduced for more eye-pleasing screens.

---
**Screenshots / Mockups**
![Screenshot from 2021-12-23 23-31-28](https://user-images.githubusercontent.com/53680255/147277379-b98467af-c56d-4f88-b535-398ba2bc9f09.png)

**Alternatives**
**Reduce** the drop shadow wherever drop shadow is provided, the given % of drop shadow is not eye-pleasing and aesthetic.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by msaini0r** [comment]
CC @abrahamalen  @leecalcote I would like to work on this issue.

**Comment by abrahamalen** [comment]
> CC @abrahamalen @leecalcote I would like to work on this issue.

Connect with the maintainers and get it assigned

**Comment by warunicorn19** [comment]
Let's close this one to avoid confusion, I dont think this is an issue we need to look into at the moment. Thank you @abrahamalen for bringing this up, we might have a conversation about this in the future.

**Comment by leecalcote** [comment]
The site's mega menu is currently implemented as designed. Thanks for raising this suggestion, though, @abrahamalen. While the mega menu isn't currently one of them, there are any number of other aspects of the site design that could use improvement.
