### ISSUE TITLE
[Bug] : Items/companies defined in the partnership section is not get redirected to the respected ID's

### ISSUE THREAD

**Issue by Abhijay007** [layer5io/layer5#2432]
**Description**

The items/companies mentioned in the partnership section on the main page is not get redirected to their respected IDs

**Expected Behavior**

when the user clicks on a particular company in the partnership section then the user gets redirected to the respected companies section on the partner page means with which that id is associated to.

**Screenshots/video**

https://user-images.githubusercontent.com/64387054/147394007-eae4e09c-1754-4ae7-a541-7bb65eb2d0b1.mp4

**Environment:**
- Host OS: Windows 11
- Browser: Chrome (Version 96.0.4664.110 (Official Build) (64-bit)

---

[Optional] **Additional Context**

---
PS: I think that we need to add "Rackspace" also, as I am unable to find associated text to it on the "Partners" page !!

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Abhijay007** [comment]
CC @leecalcote I want to work on this  issue , please assign this issue to me

**Comment by warunicorn19** [comment]
Sure @Abhijay007 please go ahead, though I'm not sure how successful you'd be though, this is an issue with anchor-based navigation. Thank you for taking a look.

**Comment by YashKamboj** [comment]
Hey @Abhijay007 if you any help with this, i can help , i know how to deal with this issue.

**Comment by Abhijay007** [comment]
> Hey @Abhijay007 if you any help with this, i can help , i know how to deal with this issue.

Ya sure @YashKamboj, thanks for asking we can schedule a call for this !!

**Comment by Abhijay007** [comment]
@warunicorn19 I am done with all other routing but I want to ask one thing that what to do with "Nitk" and "Rackspace" as it is defined on the "home page" but doesn't have respected sections on the "Partners page"?

**Comment by leecalcote** [comment]
@Abhijay007, let's skip specific anchors for those two for now.

**Comment by Abhijay007** [comment]
> @Abhijay007, let's skip specific anchors for those two for now.

ok, thanks for confirmation @leecalcote, I will soon open a PR

**Comment by leecalcote** [comment]
You're just using `a` tag anchors, right? Nothing more complex, please.

**Comment by Abhijay007** [comment]
> You're just using `a` tag anchors, right? Nothing more complex, please.

ya just an anchor tag around specific Partners names!!
