### ISSUE TITLE
[Handbook] Icons not responsive

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2435]
**Description**
The icons on https://layer5.io/community/handbook/repository-overview are not responsive on different screensizes

**Expected Behavior**
They should be responsive.

**Screenshots**

https://user-images.githubusercontent.com/53532328/147601203-ac215e88-a5b3-4794-9855-1479baf30749.mov

**Environment:**
- Host OS: Mac
- Browser: Chrome

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by rodneycoyer** [comment]
Hello! I'd like to work on this task. Can I have this assignment please?

**Comment by Vidyaa123** [comment]
Hi, Can I work on this issue? Thanks.

**Comment by Mr-DG-Wick** [comment]
Hey @Vidyaa123 👋🏽, good to see you want to contribute here but this issue has already been assigned to @rodneycoyer .
Please look into other open issues and we'll assign you to them. Thank you!

**Comment by leecalcote** [comment]
@Mr-DG-Wick always good to get people pointed either to another similar, specific issue or if one is isn't readily handy, then pointed to the general, cross-org search - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+
