### ISSUE TITLE
[Handbook] Margin needed for intra-page table of contents hyperlinks

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2438]
**Description**

https://user-images.githubusercontent.com/7570704/147682890-e9b7bceb-fb32-412e-9a21-75d1f4b98f9d.mov

**Expected Behavior**
A `top-margin` here might do the trick.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@YashKamboj something that you might look into... ?

**Comment by YashKamboj** [comment]
@leecalcote adding margin is not helping , the same issue is also there in docs.meshery and the partners page, i tried a lot finding the solution to the issue before, but unable.

**Comment by leecalcote** [comment]
Examine meshery.io. If memory serves, it has a solution. There are a number of ways to implement this behavior.

**Comment by YashKamboj** [comment]
@leecalcote It is in docs.meshery.io but it also have the same issue

**Comment by YashKamboj** [comment]
@leecalcote I found a way but a little weird, adding padding and negative margin  😅(its working)

**Comment by leecalcote** [comment]
Great. yes, that makes sense.
