### ISSUE TITLE
[Resources] Mobile-friendly: hide the filters menu or keep it completely collapsed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2439]
Regarding mobile-friendly view for https://layer5.io/resources, the following feedback was given by @warunicorn19:
> @debo19 could you please hide the filters menu or keep it completely collapsed in the mobile view. Right now it covers up a lot of space in mobile view. Though, we can probably work on that separately.

_Originally posted by @warunicorn19 in https://github.com/layer5io/layer5/issues/2430#issuecomment-1003046908_

**Comment by Ciggzy1312** [comment]
Hey @leecalcote I can look into this

**Comment by leecalcote** [comment]
Thank you, @Ciggzy1312!
