### ISSUE TITLE
[Resources] Provide zero count for filter types with no resource entries

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2440]
### Current Behavior

The category filters on layer5.io/resources that have no resource entries are missing a resource count "(0)".

<img width="360" alt="Screen Shot 2021-12-31 at 8 44 40 AM" src="https://user-images.githubusercontent.com/7570704/147828945-87206c42-e2cc-4acc-95d3-dc4ca86aa48b.png">

### Desired behavior
Provide zero count for filter types with no resource entries.

### Context

@leecalcote Since we don't have resources associated with every filter at the moment, not all of them show a number beside the categories. I'm looking for a way to add "(0)" but I'm not sure how that will look. I've made the other enhancements.

_Originally posted by @debo19 in https://github.com/layer5io/layer5/issues/2430#issuecomment-1003045517_

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thanks for picking this up, @14Richa. The issue description has been updated with a little more info.

**Comment by 14Richa** [comment]
Hey, @leecalcote  I have added resource count "(0)". Attaching the screenshot. Do we need to do the same for nighthawk and others as well? 

![Screenshot from 2022-01-03 22-18-30](https://user-images.githubusercontent.com/41283476/147956952-957332a8-a091-41bb-9e69-41e5ff16fb8f.png)

**Comment by debo19** [comment]
@14Richa yes, we'll need it for all the empty filters.

**Comment by warunicorn19** [comment]
Yes @14Richa let's have it for all filters that dont have any resources.
