### ISSUE TITLE
[Community] Member Profile: Aaditya Narayan Subedy

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2443]
**Current Behavior**

@asubedy has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @asubedy as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: asubedy
- Twitter: frexpe12
- LinkedIn: asubedy
- Link to profile picture: https://media-exp1.licdn.com/dms/image/C5603AQFeFuqjWnCLnA/profile-displayphoto-shrink_800_800/0/1623471469094?e=1646265600&v=beta&t=U7LVlzrYvwUMcvmGSZIuRFG-DZiV8Yc8NzsKcR11KM8

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by MukulKolpe** [comment]
Congratulations @asubedy🎉.....

@leecalcote can I work on this issue?

**Comment by warunicorn19** [comment]
Sure thing @MukulKolpe

**Comment by MukulKolpe** [comment]
Hey @asubedy, can you please provide a short bio and your location...

**Comment by asubedy** [comment]
Hi @MukulKolpe, thank you. Here are the details you require

Bio: I am a Computer Engineering student, currently studying at Delhi Technological University. Learning about new technologies fascinates me. I try to give my best at whatever I have been assigned to do. Contributing to the Layer5 organization has been an amazing experience. I am not only learning so much here but also getting to interact and share ideas with community members, thus helping me grow as a person too.

Location: Kathmandu, Nepal.
