### ISSUE TITLE
Add Layer5 logo to list of Istio partners on Istio.io

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#245]
Submit a PR to the Istio project to add the Layer5 logo here - https://istio.io/about/community/partners/

Find the Layer5 logo in the Community drive.

**Comment by gunjanmimo** [comment]
@leecalcote sir, i will like to take this issue, but I want to know what is the exact file for this issue?

**Comment by leecalcote** [comment]
Here we are - https://github.com/istio/istio.io/blob/master/content/en/about/community/partners/index.md

**Comment by gunjanmimo** [comment]
@leecalcote sir, is this issue is resolved?

**Comment by leecalcote** [comment]
@gunjanmimo once the Layer5 logo is visible here - https://istio.io/about/community/partners/, yes.
