### ISSUE TITLE
[Blog]

### ISSUE THREAD

**Issue by unnati914** [layer5io/layer5#2455]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** 
**Topic:**  How I got to know about meshery
**Core points to convey in the post:** 
1.How I got to know about meshery
2. On which technologies does meshery work
3. Why one should contribute to meshery 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Quick thoughts on title proposals for your consideration:

- "How I Discovered Meshery (and the technologies within)"
- "How I Discovered Layer5 (and why you should, too)"
- "How I Stumbled into Layer5 (and found a wonderful mesh)"

**Comment by unnati914** [comment]
nice, will start working on it 🎉

**Comment by StarTrooper08** [comment]
Oh nice, we can contribute as a Content writer too.
I would like to write one blog regarding Layer5, I will need time to explore Layer5.

**Comment by unnati914** [comment]
sure you can open up one issue for it @StarTrooper08 or you can assist me too regarding this

**Comment by StarTrooper08** [comment]
Yep sure👍

**Comment by unnati914** [comment]
@leecalcote FYI
@StarTrooper08 @verma-kunal have started working on it with me

**Comment by StarTrooper08** [comment]
Sorry I was busy few days.
Hey @unnati914 I can create few flowcharts or illustration for the article.
And yes even I'll do the write up work (will need little bit of mentoring/guidance)
You can tag me here on GitHub(issue comment)or ping me on slack/ [twitter](https://twitter.com/_Atharva_08).

**Comment by unnati914** [comment]
sure

**Comment by unnati914** [comment]
@debo19 , can you please tell me the suggestions that you listed that day to me regarding this issue?

**Comment by debo19** [comment]
@unnati914 I don't recall exactly. Can you go through the meeting recording from that day, that should be helpful.
