### ISSUE TITLE
[UI] Add Docs button for Meshery

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#2475]
**Current Behavior**
Currently, there is no docs button under the service-mesh-management/meshery for users/developers to refer directly form Layer5 website.

**Desired Behavior**
Adding a button would ease the navigation and engagement from Layer5 website to Mesehry usage(through DOCS) for developers/users. An ideal place to add a button to docs would be 
![Screenshot from 2022-01-11 11-19-37](https://user-images.githubusercontent.com/65453826/148888817-003732fe-899f-47d4-9b0c-5c2e1d33d607.png)

Note: followup the comments for more info about where to add this button.

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@warunicorn19 @leecalcote thoughts?

**Comment by leecalcote** [comment]
Thank you, but no thank you. 🙂 This page does need updated, but its first job is to sell people on the features and value of Meshery. The docs don't quite do that. Having a link to the docs for more installation instructions can be a good thing. That link should not be prominent, though.

**Comment by Chadha93** [comment]
> Thank you, but no thank you. slightly_smiling_face This page does need updated, but its first job is to sell people on the features and value of Meshery. The docs don't quite do that. Having a link to the docs for more installation instructions can be a good thing. That link should not be prominent, though.

Gotcha! make much sense. Thanks for the clarification.  🙌

**Comment by subhradwip01** [comment]
I would like to work on that issue. Can I?

**Comment by Chadha93** [comment]
@subhradwip01 thanks for jumping in, but we don't require this issue for now. :) You can have a look at some more issues.

**Comment by subhradwip01** [comment]
@Chadha93 ok..got it
