### ISSUE TITLE
[Blog] Validating Meshery CLI Functionality

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2476]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

#### Core points to convey in the post:
1. the need for user acceptance testing.
1. how to checkout a PR’s branch 
1. how to build `mesheryctl` (incorporate instructions for different OSes)
1.  how to test with your compiled binary
1. reference to https://docs.meshery.io/project/contributing/contributing-guide and how these principles and practices should be kept in mind while assessing functionality and UX.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
// @piyushsingariya

**Comment by Chadha93** [comment]
@Revolyssup or @theBeginner86 would one of you like to take this?
