### ISSUE TITLE
Add Badges to certain member profiles

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2480]
**Current Behavior**
A variety of badges exist so that community members and their efforts may be affiliated with a particular project or with a community initiative.

**Desired Situation**
Add the respective badges to the following member profiles to recognize their effort in our projects.

- [Abhishek Kumar](https://layer5.io/community/members/abhishek-kumar): Meshery
- [Aditya Chatterjee](https://layer5.io/community/members/aditya-chatterjee): Meshery
- [Manav Kapoor](https://layer5.io/community/members/manav-kapoor): Meshery
- [Gaurav Chadha](https://layer5.io/community/members/gaurav-chadha): Meshery, Landscape

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by verma-kunal** [comment]
Hey @debo19 , I would like to work on this one 🙂

**Comment by Sunnyio** [comment]
Hey, @debo19 I would like to work on it.

**Comment by sayantan1413** [comment]
Thanking you for jumping in @Sunnyio. It's all yours.
