### ISSUE TITLE
 Reformatting of the single column blog list view on layer5.io/blog.

### ISSUE THREAD

**Issue by AbhishekJamhoriya** [layer5io/layer5#2487]
**Description**
Currently, the blog views are in Grid view. we have to change it into a single column blog list view.

**Current Behaviour **
![Screenshot (590)](https://user-images.githubusercontent.com/62591179/149670182-6eca5663-7ced-4e73-8f28-13e6b8188274.png)

 

**Expected Behavior**
 We have to change it into a single view list. 

**Screenshots**
 see the difference between the blog views? Single and grid?
<img width="1792" alt="Screen Shot 2022-01-16 at 10 13 10 AM" src="https://user-images.githubusercontent.com/62591179/149669854-e5747102-6c8a-416a-9156-e48e418977bb.png">

**Environment:**
- Host OS: 
- Browser: 

---

**Area*
 [layer5.io/blog](https://layer5.io/blog).

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by AbhishekJamhoriya** [comment]
Hi @leecalcote, please assign me this issue.

**Comment by AbhishekJamhoriya** [comment]
Hi @leecalcote and @warunicorn19, made some changes to the list view items and it now looks like this. is this fine or I should make some other changes as well.

![Screenshot (594)](https://user-images.githubusercontent.com/62591179/150209031-9c75231d-7542-4066-b7e9-12bdf2b9d7f0.png)

**Comment by leecalcote** [comment]
Looking pretty good! Missing: tags.

Please confirm that the title will be trimmed and an ellipsis added at the end of the line when the title is too long to fit into a single lie.

**Comment by AbhishekJamhoriya** [comment]
no problem with the long title it's working fine.
![Screenshot (596)](https://user-images.githubusercontent.com/62591179/150215757-d157770f-4103-460b-b805-6937690ea51f.png)

currently working on tags.

**Comment by AbhishekJamhoriya** [comment]
I am not able to find the tags data, can anyone please help.

**Comment by AbhishekJamhoriya** [comment]
Hi @leecalcote, @warunicorn19 or @Abhijay007 please someone help me that how I can get tag data.

**Comment by warunicorn19** [comment]
@AbhishekJamhoriya could you please put in a PR, it'll be easier for us to take a look. Also, @leecalcote by missing tags are you saying that the tags should be visible on the cards?
