### ISSUE TITLE
Adding tooltips

### ISSUE THREAD

**Issue by AbhishekJamhoriya** [layer5io/layer5#2488]
**Description**
When we hover on any footer icons a text message should appear as shown in the image(Expected Bahavior).

**Current Behavior**

![Screenshot (588)](https://user-images.githubusercontent.com/62591179/149670865-74862a87-9101-48c4-8ab0-054099f963ad.png)

**Expected Behavior**
![Screenshot (589)](https://user-images.githubusercontent.com/62591179/149670862-7cca5d1a-3ed0-45f8-ba3e-bdff5d3b8c08.png)

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by AbhishekJamhoriya** [comment]
Hi @leecalcote, please assign me this issue.

**Comment by warunicorn19** [comment]
Let's close this issue, like @leecalcote adding tooltips to the footer is going to be an overkill. It's perfect the way it is right now.
