### ISSUE TITLE
[Landscape] Table Tab Enhancements

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2489]
**Current State:**
Tabs in the [landscape](https://layer5.io/landscape) table are often overlooked. 

**Desired State:**
1. Either add a small outline or slightly different background color to each tab.
2. Make the "Functional" tab the default (open) tab.

#### Screenshot:
<img width="1066" alt="Screen Shot 2022-01-16 at 8 27 56 PM" src="https://user-images.githubusercontent.com/7570704/149697175-366b5d27-2c63-4299-90a1-bfc8611c432b.png">

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by subhradwip01** [comment]
I would like to work on that issue

**Comment by warunicorn19** [comment]
Go ahead @subhradwip01
