### ISSUE TITLE
[Resources] RSS Feed: Create feed for all resources

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2490]
**Current Behavior**
Site visitors can browse [resources](https://layer5.io/resources), but not subscribe for notifications of newly published resources.

**Desired Behavior**
Create `/resources/feed.xml` - an RSS feed containing all resources.

---
**Screenshots / Mockups**
<img width="1233" alt="Screen Shot 2022-01-16 at 8 48 44 PM" src="https://user-images.githubusercontent.com/7570704/149701389-b6f1e73f-1111-4e22-93b6-5b9ad88bf983.png">

**Implementation**
1. Create new RSS feed in `gatsby-config.js` to be available at `/resources/feed.xml`.
1. Add RSS icon with link to feed adjacent to /resources page title as pictured in mockup.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Sunnyio** [comment]
I would like to work on this.

**Comment by Abhijay007** [comment]
@Sunnyio go ahead !!
