### ISSUE TITLE
[Blog] RSS Feed: Create feed for all posts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2491]
**Current Behavior**
Site visitors can browse [blog posts](https://layer5.io/blog), but not subscribe for notifications of newly published posts.

**Desired Behavior**
Create `/blog/feed.xml` - an RSS feed containing all posts.

---
**Screenshots / Mockups**
<img width="1146" alt="Screen Shot 2022-01-16 at 9 03 49 PM" src="https://user-images.githubusercontent.com/7570704/149702125-f0c11ef8-4314-4e43-acc0-238d610226b1.png">

**Implementation**
1. Create new RSS feed in `gatsby-config.js` to be available at `/blog/feed.xml`.
1. Add RSS icon with link to feed adjacent to /blog page title as pictured in mockup.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhijay007** [comment]
sure @subhradwip01 go ahead !!

**Comment by subhradwip01** [comment]
Can you tell me from where can get the svg of RSS feed icon..is there any particular svg that has been already created by layer5? ..or can I use any svg?

**Comment by Abhijay007** [comment]
@YashKamboj is working on something similar, you can ping him on slack and for this purpose you can use custom SVG, Yash already had a PR in progress so you can take reference from that PR, in that pr Yash is using a custom SVG so you can follow the same folder structure he has because we don't want different  SVG files !!

**Comment by subhradwip01** [comment]
@Abhijay007 thank you so much...I will contact him

**Comment by YashKamboj** [comment]
@subhradwip01 you can check this pr #2508

**Comment by subhradwip01** [comment]
> @subhradwip01 you can check this pr #2508

Ok thanks...by the way you are so fast for helping...thank you so much 😀
