### ISSUE TITLE
[News] RSS feed: Add existing news and announcements feed to News page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2492]
**Current Behavior**
Site visitors can browse [news](https://layer5.io/news), but not subscribe for notifications of newly published news.

**Desired Behavior**
Show an RSS icon next the "News" page title as shown in the screenshot.

---
**Screenshots / Mockups**
<img width="1177" alt="Screen Shot 2022-01-16 at 9 06 30 PM" src="https://user-images.githubusercontent.com/7570704/149702350-ecd5c291-5221-417c-a249-9a7ed7b6a88a.png">

**Implementation**
1. Create new RSS feed in `gatsby-config.js` to be available at `/news/feed.xml`. Publish the existing `/rss.xml` - an RSS feed containing all news and announcement posts under the url `/news/feed.xml`. Ideally, make an alias of the same RSS feed or add a second output location.
1. Add RSS icon with link to feed adjacent to /news page title as pictured in mockup.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by YashKamboj** [comment]
Can i work on this?

**Comment by warunicorn19** [comment]
sure @YashKamboj
