### ISSUE TITLE
[Events] Text overlaps with carousel switcher

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2493]
**Description**
On the layer5.io/events page, the main events carousel has circular dots that all visitors to navigate through events. Text describing a given event will occasionally overlap with the switch controls.

**Expected Behavior**
A white background (~50% opacity) should be added to the switcher (with small margin around it), so that any underlapping text is still visible but not as conflicting and confusing to the user trying to flip through different events.

**Screenshots**
<img width="865" alt="Screen Shot 2022-01-16 at 9 12 32 PM" src="https://user-images.githubusercontent.com/7570704/149702762-ce79706e-e5f8-43b6-b70f-ee2f8039e78c.png">nt

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by MukulKolpe** [comment]
Hey @leecalcote, can I work on this issue?

**Comment by leecalcote** [comment]
Thank you, gents. 👍
