### ISSUE TITLE
[Resource] Article: Linkerd

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2496]
Contributors and community members are encouraged to create articles under https://layer5.io/resources. A new article fitting the following description is requested to be written by a community member:

**URL**: /resources/service-mesh/what-is-linkerd
**Article Title:** Service Mesh: Linkerd
**Topic:** Create a page under /resources that generally describes Linkerd.
**Core points to convey in the article:** 
- Genesis
- Governance
- Architecture
- Special Features
- Excerpt of Functional, Non-Functional data from the service mesh landscape (/landscape)

_Articles under the /resources area are to be timeless and broadly helpful to visitors. As such, these articles carry no publish date or byline._

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
CU-1ydyv9k

**Comment by kayceeDev** [comment]
@leecalcote , I will love to push my brain to write this. Do you have any resources to help me understand linkered? I will appreciate your suggestions.

**Comment by legendarykamal** [comment]
@kayceeDev any updates ? May I join you in this as I put forward to see Linkerd ?

**Comment by kayceeDev** [comment]
@legendarykamal  You can take a shot at this. If you may.

**Comment by deepeshaburse** [comment]
@legendarykamal are you working on this issue? In case you aren't, I'd like to take it up 😄

**Comment by leecalcote** [comment]
@deepeshaburse please do.

**Comment by legendarykamal** [comment]
@deepeshaburse I am working on this but I will be happy to have you collaberate on this. 
Let's work together on this 😃.

**Comment by deepeshaburse** [comment]
> @deepeshaburse please do. 

Okay 👍🏼

**Comment by deepeshaburse** [comment]
> @deepeshaburse I am working on this but I will be happy to have you collaberate on this. 
> 
> Let's work together on this 😃. 

Okay, do you have slack? Can we connect there?

**Comment by deepeshaburse** [comment]
> @deepeshaburse I am working on this but I will be happy to have you collaberate on this. 
> 
> Let's work together on this 😃. 

Hey @legendarykamal when do you think we can get started on this?

**Comment by legendarykamal** [comment]
> > @deepeshaburse I am working on this but I will be happy to have you collaberate on this.
> > Let's work together on this smiley.
> 
> Okay, do you have slack? Can we connect there?
I have reached out to you on slack :+1:

**Comment by UtkarshMishra12** [comment]
@legendarykamal @deepeshaburse  Please update 😊

**Comment by divz-codess** [comment]
Hi @leecalcote this issue has not been taken up since quite long and I have interest and experience in article writing so can I take it up. Also help from a mentor would be much appreciated :)
