### ISSUE TITLE
[Resource] Article: Consul Service Mesh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2497]
Contributors and community members are encouraged to create articles under https://layer5.io/resources. A new article fitting the following description is requested to be written by a community member:

**URL**: /resources/service-mesh/what-is-consul-service-mesh
**Article Title:** Service Mesh: Consul
**Topic:** Create a page under /resources that generally describes Consul.
**Core points to convey in the article:** 
- Genesis
- Governance
- Architecture
- Special Features
- Excerpt of Functional, Non-Functional data from the service mesh landscape (/landscape)

_Articles under the /resources area are to be timeless and broadly helpful to visitors. As such, these articles carry no publish date or byline._

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
CU-1ydyvdz

**Comment by deepeshaburse** [comment]
I am interested in writing this article, kindly assign me this issue.
