### ISSUE TITLE
Swap the heading Blog with Resources 

### ISSUE THREAD

**Issue by ShivamTyagi12345** [layer5io/layer5#2498]
**Current Behavior**
https://layer5.io/ has the term **Blog** in the Navbar and in the Menu 

**Desired Situation**

Replace them with **Resources**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sambhavsaxena** [comment]
can i work on this?

**Comment by ShivamTyagi12345** [comment]
> can i work on this?

sorry .Still working ,just a little delayed due to prior commitments

**Comment by warunicorn19** [comment]
@sambhavsaxena, please go ahead if you're still interested.

**Comment by AbhishekJamhoriya** [comment]
@warunicorn19 please assign me this issue. let me give it a shot.

**Comment by moazzam07** [comment]
@warunicorn19 can i work on it?

**Comment by YashKamboj** [comment]
@AbhishekJamhoriya are you still  working on it ??

**Comment by AbhishekJamhoriya** [comment]
Yes, @YashKamboj I'm still working on this issue.

**Comment by subhradwip01** [comment]
@AbhishekJamhoriya ohh..carry on

**Comment by Akshit42-hue** [comment]
Can I work on this issue @ShivamTyagi12345
