### ISSUE TITLE
[Community] Member Profile: Add SMP to Nic Jackson's profile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2507]
**Current Behavior**

@nicholasjackson is an SMP maintainer.

**Desired Situation**
Let's recognize @nicholasjackson as a maintainer by updating his profile on https://layer5.io/community/members.

https://layer5.io/community/members/nic-jackson

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Sunnyio** [comment]
I would like to do this @leecalcote.

**Comment by warunicorn19** [comment]
Go ahead @Sunnyio
