### ISSUE TITLE
[MeshMap] Add "BETA" superscript to page title

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2515]
**Current Behavior**
The [MeshMap beta sign up page](https://layer5.io/service-mesh-management/meshmap) has "MeshMap" as its title.

**Desired Behavior**
Add the word "BETA" as superscript to "MeshMap", like so (except using black font color):

<img width="177" alt="Screen Shot 2022-01-19 at 3 30 48 PM" src="https://user-images.githubusercontent.com/7570704/150217134-732a7ef3-d662-4ccc-ab15-6e079e4d14ed.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by AbhishekJamhoriya** [comment]
Hey @leecalcote, can I work on this issue?

**Comment by Abhijay007** [comment]
@AbhishekJamhoriya go ahead !!

**Comment by AbhishekJamhoriya** [comment]
Hi @leecalcote, superscript has been added to the page title. These are some font sizes and font families. please help me which one should I go for.
font-size:
1) ![70%](https://user-images.githubusercontent.com/62591179/150429610-8414a4b9-1481-425e-ae08-8c67b24e0f05.PNG)
2) ![75%](https://user-images.githubusercontent.com/62591179/150429641-410f84a6-87ee-4ab1-a7ec-3df85fc97b3d.PNG)
3) ![80%](https://user-images.githubusercontent.com/62591179/150429651-88394eab-83d5-458a-ba39-664679a04601.PNG)
Font-family:
1) ![roman](https://user-images.githubusercontent.com/62591179/150429667-2f839db1-8424-4a96-bb59-7304f4ba3bf6.PNG)

**Comment by leecalcote** [comment]
Thanks, @AbhishekJamhoriya.  Qanelas Soft Thin (weight:300) should work pretty well.
