### ISSUE TITLE
[Community] Member Profile: Abhijay Jain

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2517]
**Current Behavior**

@Abhijay007 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Abhijay007 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: Abhijay007
- Twitter: CodeInVeins
- LinkedIn: /abhijay-jain-551b01193
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
@Abhijay007 Can you please provide the drive link to your profile picture and a bio.

**Comment by Chadha93** [comment]
> /assign

@ShivamTyagi12345 would you like to take the assignment for this?

**Comment by ShivamTyagi12345** [comment]
> > /assign
> 
> @ShivamTyagi12345 would you like to take the assignment for this?

Sure @Chadha93 :)

**Comment by Abhijay007** [comment]
> @Abhijay007 Can you please provide the drive link to your profile picture and a bio.

**Comment by Xuewei-Chen** [comment]
Hi, I am taking a course on software development methodology and need to do some work. Can I be assigned some of the work?

**Comment by Abhijay007** [comment]
> Hi, I am taking a course on software development methodology and need to do some work. Can I be assigned some of the work?

Hi @Xuewei-Chen this issue is already assigned you can join our slack community and join the newcomer's channels you will definitely get something to work on there, here is the link : https://layer5io.slack.com/ssb/redirect#/shared-invite/email

**Comment by subhradwip01** [comment]
Is this issue already solved?...If not can I work on that issue?

**Comment by warunicorn19** [comment]
@subhradwip01 please go ahead, @ShivamTyagi12345 seems to be elsewhere

**Comment by subhradwip01** [comment]
@Abhijay007 can you provide your short bio and profile picture please?

**Comment by Abhijay007** [comment]
> @Abhijay007 can you provide your short bio and profile picture please?

ok, I will send it on slack :)

**Comment by warunicorn19** [comment]
@subhradwip01 there's an open PR you can reference.

**Comment by subhradwip01** [comment]
I am working on an issue of layer5 website...while I am trying to commit a change I am getting this error
Can someone tell me why I am getting this?

**Comment by subhradwip01** [comment]
0 verbose cli [
0 verbose cli   '/home/subhradwip/.nvm/versions/node/v16.0.0/bin/node',
0 verbose cli   '/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--yes=false',
0 verbose cli   '--',
0 verbose cli   'husky-run',
0 verbose cli   'pre-commit'
0 verbose cli ]
1 info using npm@8.4.1
2 info using node@v16.0.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/home/subhradwip/Documents/open_source/layer5/.npmrc Completed in 1ms
10 timing config:load:project Completed in 4ms
11 timing config:load:file:/home/subhradwip/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/subhradwip/.nvm/versions/node/v16.0.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 15ms
19 timing npm:load:configload Completed in 15ms
20 timing npm:load:setTitle Completed in 1ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:display Completed in 5ms
23 verbose logfile /home/subhradwip/.npm/_logs/2022-02-08T07_57_25_166Z-debug-0.log
24 timing npm:load:logFile Completed in 23ms
25 timing npm:load:timers Completed in 1ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 46ms
28 silly logfile start cleaning logs, removing 1 files
29 http fetch GET 200 https://registry.npmjs.org/husky-run 1857ms (cache revalidated)
30 timing command:exec Completed in 1918ms
31 verbose stack Error: could not determine executable to run
31 verbose stack     at getBinFromManifest (/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
31 verbose stack     at exec (/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:115:15)
31 verbose stack     at async module.exports (/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/lib/cli.js:66:5)
32 verbose pkgid husky-run@0.0.0
33 verbose cwd /home/subhradwip/Documents/open_source/layer5
34 verbose Linux 5.13.0-28-generic
35 verbose argv "/home/subhradwip/.nvm/versions/node/v16.0.0/bin/node" "/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--yes=false" "--" "husky-run" "pre-commit"
36 verbose node v16.0.0
37 verbose npm  v8.4.1
38 error could not determine executable to run
39 verbose exit 1
40 timing npm Completed in 2537ms
41 verbose code 1
42 error A complete log of this run can be found in:
42 error     /home/subhradwip/.npm/_logs/2022-02-08T07_57_25_166Z-debug-0.log

**Comment by subhradwip01** [comment]
This is debug.log


> 0 verbose cli [ 0 verbose cli '/home/subhradwip/.nvm/versions/node/v16.0.0/bin/node', 0 verbose cli '/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/bin/npm-cli.js', 0 verbose cli 'exec', 0 verbose cli '--yes=false', 0 verbose cli '--', 0 verbose cli 'husky-run', 0 verbose cli 'pre-commit' 0 verbose cli ] 1 info using npm@8.4.1 2 info using node@v16.0.0 3 timing npm:load:whichnode Completed in 0ms 4 timing config:load:defaults Completed in 2ms 5 timing config:load:file:/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/npmrc Completed in 1ms 6 timing config:load:builtin Completed in 1ms 7 timing config:load:cli Completed in 4ms 8 timing config:load:env Completed in 1ms 9 timing config:load:file:/home/subhradwip/Documents/open_source/layer5/.npmrc Completed in 1ms 10 timing config:load:project Completed in 4ms 11 timing config:load:file:/home/subhradwip/.npmrc Completed in 0ms 12 timing config:load:user Completed in 0ms 13 timing config:load:file:/home/subhradwip/.nvm/versions/node/v16.0.0/etc/npmrc Completed in 0ms 14 timing config:load:global Completed in 1ms 15 timing config:load:validate Completed in 0ms 16 timing config:load:credentials Completed in 1ms 17 timing config:load:setEnvs Completed in 1ms 18 timing config:load Completed in 15ms 19 timing npm:load:configload Completed in 15ms 20 timing npm:load:setTitle Completed in 1ms 21 timing config:load:flatten Completed in 3ms 22 timing npm:load:display Completed in 5ms 23 verbose logfile /home/subhradwip/.npm/_logs/2022-02-08T07_57_25_166Z-debug-0.log 24 timing npm:load:logFile Completed in 23ms 25 timing npm:load:timers Completed in 1ms 26 timing npm:load:configScope Completed in 0ms 27 timing npm:load Completed in 46ms 28 silly logfile start cleaning logs, removing 1 files 29 http fetch GET 200 https://registry.npmjs.org/husky-run 1857ms (cache revalidated) 30 timing command:exec Completed in 1918ms 31 verbose stack Error: could not determine executable to run 31 verbose stack at getBinFromManifest (/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23) 31 verbose stack at exec (/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:115:15) 31 verbose stack at async module.exports (/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/lib/cli.js:66:5) 32 verbose pkgid husky-run@0.0.0 33 verbose cwd /home/subhradwip/Documents/open_source/layer5 34 verbose Linux 5.13.0-28-generic 35 verbose argv "/home/subhradwip/.nvm/versions/node/v16.0.0/bin/node" "/home/subhradwip/.nvm/versions/node/v16.0.0/lib/node_modules/npm/bin/npm-cli.js" "exec" "--yes=false" "--" "husky-run" "pre-commit" 36 verbose node v16.0.0 37 verbose npm v8.4.1 38 error could not determine executable to run 39 verbose exit 1 40 timing npm Completed in 2537ms 41 verbose code 1 42 error A complete log of this run can be found in: 42 error /home/subhradwip/.npm/_logs/2022-02-08T07_57_25_166Z-debug-0.log

this is debug.log

**Comment by subhradwip01** [comment]
I resolved that..problem with npm...I reinstall npm and node with latest version and rerun the command npm install..then it is working fine
