### ISSUE TITLE
[Community] Member Profile: Xin Huang

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2553]
**Current Behavior**

@gyohuangxin has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @gyohuangxin as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @gyohuangxin
- Twitter: @gyohuang
- LinkedIn: https://www.linkedin.com/in/Xin-Huang
- Link to profile picture: 

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by verma-kunal** [comment]
Hey @iambami , may i work on this one!?

**Comment by maneeshsagar** [comment]
May I do this ?

**Comment by verma-kunal** [comment]
> May I do this ?

Sure @maneeshsagar go ahead! Feel free to ask any doubts you would have 🙂
This is probably your 1st contribution here, right?

**Comment by iambami** [comment]
Hi @maneeshsagar Please go ahead.

**Comment by maneeshsagar** [comment]
Yes @verma-kunal  it's my first

**Comment by iambami** [comment]
Feel free to reach out should there be any issue.

**Comment by gyohuangxin** [comment]
@maneeshsagar Thank you for taking this issue, this's my bio and picture:

I am a cloud software developer from Intel. I focus on the acceleration on open source softwares for service mesh, such as Istio, Envoy. And I am also a contributor of Service Mesh Performance and the meshery-perf component. I love the open culture of Layer5, where you can find everything about open source and service mesh, and you will love it too.

![IMG_1726 copy](https://user-images.githubusercontent.com/42127654/151648360-6c397f2b-983e-40aa-9341-8f0535854f9f.jpeg)

And my location: Shanghai, China

**Comment by maneeshsagar** [comment]
Hey, @gyohuangxin  please confirm your Twitter: @gyohuang handle please I am not getting any account in your name?

**Comment by gyohuangxin** [comment]
@maneeshsagar Yes, I confirm. Can you get it from https://twitter.com/gyohuang?
