### ISSUE TITLE
[Events] RSS Feed: Create feed for all posts

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2554]
**Current Behavior**
Site visitors can browse [events](https://layer5.io/community/events), but not subscribe for notifications of upcoming events.

**Desired Behavior**
Create `/events/feed.xml` - an RSS feed containing all posts.

---
**Screenshots / Mockups**
<img width="784" alt="Screenshot 2022-01-29 at 1 19 23 AM" src="https://user-images.githubusercontent.com/85789734/151612086-695a0bd3-34e7-4457-a23c-1768ba7cae44.png">

**Implementation**
1. Create new RSS feed in `gatsby-config.js` to be available at `/events/feed.xml`.
1. Add RSS icon with link to feed adjacent to /events page title as pictured in mockup. Check [blog page](https://layer5.io/blog) for example.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Sunnyio** [comment]
I would like to do this.

**Comment by warunicorn19** [comment]
Sure @Sunnyio

**Comment by leecalcote** [comment]
Yay, @Sunnyio picked this one up! Great work on the other RSS feeds, @Sunnyio. 👏

**Comment by Sunnyio** [comment]
Thanks @leecalcote.
