### ISSUE TITLE
[Handbook] Repository Overview: Add GitHub Actions to the list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2562]
**Current Behavior**
The repo overview page at https://layer5.io/community/handbook/repository-overview is missing a couple of the community-created GitHub Actions.

**Desired Behavior**
List these actions on the page:

1. https://github.com/layer5io/meshery-smp-action
2. https://github.com/layer5io/meshery-service-mesh-patterns-action

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by AbhishekJamhoriya** [comment]
Hi @leecalcote, can I work on this issue?

**Comment by Abhijay007** [comment]
@AbhishekJamhoriya are you working on this issue? if you need any assistance you can ping me on slack :)

**Comment by AbhishekJamhoriya** [comment]
yes, I'm working on it, I will definitely ask for help from you @Abhijay007  if needed.
