### ISSUE TITLE
[Community] Member Profile: Yash Kamboj

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2564]
**Current Behavior**

@YashKamboj has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @YashKamboj as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @YashKamboj 
- Twitter: @yashkamboj123
- LinkedIn: https://www.linkedin.com/in/yash-kamboj-9078011b5
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by KXLAA** [comment]
Hey, can I handle this?

**Comment by iambami** [comment]
@YashKamboj kindly send your bio and your photo.

**Comment by KXLAA** [comment]
Waiting on @YashKamboj bio

**Comment by iambami** [comment]
Yash Kamboj is an undergrad student at IP University, Delhi. He is passionate about open-source and front-end development. Always up to learn new things. Love to help others and learn new things from them.

**Comment by YashKamboj** [comment]
@KXLAA , thank you for working on it . If you need any help feel free to reach out to me😊
bio : I am a undergrad student at IP university, Delhi. I am passionate about open-source and front-end development. Always up to learn new things. Love to help others and learning new thing from them.
![IMG_20210301_2325041](https://user-images.githubusercontent.com/75125203/151908597-04013fc7-b69e-4e6f-a20c-874b909930b1.jpg)
