### ISSUE TITLE
[Blog] Collapsible tag and category list

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2577]
**Current Behavior**
The tags and categories list on blog page has become too long. On selecting a specific category, there's a lot of unnecessary blank space on the page. 

https://user-images.githubusercontent.com/85789734/152233646-e8f9280b-8ce5-46a0-a777-f5284d826312.mov

**Desired Situation**
Make the tag list and category list collapsible. They should be collapsed while viewing blogs of any particular category or tag but open on the main blog page.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by padmajabhol** [comment]
I want to work on this, can you assign me?

**Comment by warunicorn19** [comment]
Please go ahead @padmajabhol

**Comment by subhradwip01** [comment]
Is this issue solved?

**Comment by subhradwip01** [comment]
If you want I would like to give a try...If you are not working

**Comment by debo19** [comment]
@padmajabhol any updates on this? @subhradwip01 can help with this one
