### ISSUE TITLE
[Contributing] Broken badge images in Contributing.md

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2583]
**Description**
The images of the badges are broken in the contributing.md 
<img width="302" alt="Screenshot 2022-02-04 at 3 17 39 PM" src="https://user-images.githubusercontent.com/53532328/152597556-776f80d7-0ff9-499f-ad6c-f552b5a6a98d.png">

**Expected Behavior**
They shouldn't be broken

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by AbhishekJamhoriya** [comment]
Hi, @warunicorn19 please assign me this issue.

**Comment by chaitanya-24** [comment]
Can I solve this issue?

**Comment by leecalcote** [comment]
@chaitanya-24, let's see... @AbhishekJamhoriya, are you still working on this issue?

**Comment by AbhishekJamhoriya** [comment]
yes, @leecalcote I'm working on it.

**Comment by chaitanya-24** [comment]
No Problem :)
