### ISSUE TITLE
[Bug] Broken link of GSOC on the partners page

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#2590]
**Description**

Broken link of GSOC on the partners page.  https://layer5.io/partners
**Expected Behavior**

Redirect it to https://layer5.io/programs/gsoc
**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Simba-97** [comment]
@YashKamboj hey Yash, can I work on this issue?

**Comment by YashKamboj** [comment]
Go ahead!!! @Simba-97
