### ISSUE TITLE
[Meshery] Update user count

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2602]
**Current Behavior**
This page, https://layer5.io/service-mesh-management/meshery, lists 1,000+ users currently.

**Desired Behavior**
Meshery is up to 1,200+ users now.

**Screenshots / Mockups**
<img width="1158" alt="Screen Shot 2022-02-10 at 2 50 57 PM" src="https://user-images.githubusercontent.com/7570704/153494464-0d406ad4-14f5-4ae4-ba30-24f8f43a0763.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by furkanmutlu** [comment]
PR: https://github.com/layer5io/layer5/pull/2603
