### ISSUE TITLE
[Discuss] Missing OpenGraph image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2607]
**Description**
When sharing a link to a post on discuss.layer5.io, no image is found for inclusion in the social media share.

**Expected Behavior**
Meta tags for opengraph image(s) should be included in the site. If no image is included in the specific post, the site's logo should be used as the opengraph image.

**Screenshots**
<img width="617" alt="Screen Shot 2022-02-14 at 4 50 10 PM" src="https://user-images.githubusercontent.com/7570704/153959959-ca22d6e2-0412-4eac-b348-94057617a3c4.png">

---
**Contributor Resources**

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

**Comment by leecalcote** [comment]
The site's current configuration includes a setting for these images, though.
<img width="858" alt="Screen Shot 2022-02-14 at 4 56 32 PM" src="https://user-images.githubusercontent.com/7570704/153960644-27b1716b-a182-4cf5-b058-8979788c3207.png">

**Comment by leecalcote** [comment]
The Twitter card validator suggests that all is fine.
<img width="1065" alt="Screen Shot 2022-02-14 at 4 58 09 PM" src="https://user-images.githubusercontent.com/7570704/153960865-e2ad8ac5-09ec-458b-b691-da106ef08e8c.png">


However, as you go to share on Twitter, something else seems amiss. Hmpf.

**Comment by leecalcote** [comment]
Argh. Never mind. 😕 
<img width="621" alt="Screen Shot 2022-02-14 at 5 13 17 PM" src="https://user-images.githubusercontent.com/7570704/153962623-0a18171f-afb3-4e3c-94be-7202dc3bb792.png">

**Comment by verma-kunal** [comment]
Thanks for pointing out @leecalcote !! Will check this

**Comment by verma-kunal** [comment]
> Argh. Never mind. 😕 

Seems to be working for me as well. 
![Screenshot 2022-02-15 at 7 19 21 AM](https://user-images.githubusercontent.com/72245772/153977355-f7973f4f-1721-453e-b52b-10031f5d29c3.png)

**Comment by verma-kunal** [comment]
I think the issue here is the rendering time for these social platforms for the opengraph images with links! Happens with various other links as well 
Should i look more into this one @leecalcote ?

**Comment by verma-kunal** [comment]
Tried the same on LinkedIn:
![Screenshot 2022-02-15 at 7 32 02 AM](https://user-images.githubusercontent.com/72245772/153978516-09510c5b-2bb7-455a-b2ac-8ddd7529fe5f.png)

**Comment by leecalcote** [comment]
In think that you're right, @verma-kunal. This is/was something of a fluke and red herring; not something to research further given that we seem to have the right configuration in place. Thanks for investigating.

**Comment by kayceeDev** [comment]
> Argh. Never mind. 😕 <img alt="Screen Shot 2022-02-14 at 5 13 17 PM" width="621" src="https://user-images.githubusercontent.com/7570704/153962623-0a18171f-afb3-4e3c-94be-7202dc3bb792.png">

Got me smiling 😂.
