### ISSUE TITLE
[Learn] Fix the Statement on Layer5 Landing Page.

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2611]
**Current State:**
The statement on Layer5 [Service-Mesh](https://github.com/layer5io/layer5/blob/master/src/sections/Home/Service-mesh-focussed/index.js#L30) needs a little space.
**Desired State:**
There is a need for space between applications and provide `applications,provide`
![snip1](https://user-images.githubusercontent.com/64528871/156794998-fdbb1a25-9d9e-46fd-9112-6159f5880b51.PNG)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by ShivamTyagi12345** [comment]
Do i need to delete that extra space that happens to occur in the line?

**Comment by iambami** [comment]
Hi @ShivamTyagi12345 You don't have to. Thanks

**Comment by unnati914** [comment]
hey @ShivamTyagi12345 are you working on this issue? if you are working, can I help you with this?
cc @iambami

**Comment by iambami** [comment]
Thanks @unnati91, @ShivamTyagi12345 do you have any issue with this issue? Kindly let us know if there is any.

**Comment by Nikhil-Ladha** [comment]
Hey @iambami , I think the desired state in the issue is not very clear. Can you please explain that in the description?

**Comment by sidd-oo** [comment]
> Hey @iambami , I think the desired state in the issue is not very clear. Can you please explain that in the description?

I think we need to remove this extra spacing on the highlighted line.  @Nikhil-Ladha 
Can I take this issue ?
![image](https://user-images.githubusercontent.com/25115188/156779591-e4071a12-5eca-4e81-a53b-3dab527532db.png)

**Comment by Abhijay007** [comment]
> > Hey @iambami , I think the desired state in the issue is not very clear. Can you please explain that in the description?
> 
> I think we need to remove this extra spacing on the highlighted line. @Nikhil-Ladha Can I take this issue ? ![image](https://user-images.githubusercontent.com/25115188/156779591-e4071a12-5eca-4e81-a53b-3dab527532db.png)

@sidd-oo it is for first-timers only :)

**Comment by sidd-oo** [comment]
> > > Hey @iambami , I think the desired state in the issue is not very clear. Can you please explain that in the description?
> > 
> > 
> > I think we need to remove this extra spacing on the highlighted line. @Nikhil-Ladha Can I take this issue ? ![image](https://user-images.githubusercontent.com/25115188/156779591-e4071a12-5eca-4e81-a53b-3dab527532db.png)
> 
> @sidd-oo it is for first-timers only :)

Okay, I will pass. Thanks

**Comment by Nikhil-Ladha** [comment]
No, that space won't be rendered on the page.

**Comment by iambami** [comment]
Please check out the desired state. it's been updated.

**Comment by RakeshPotnuru** [comment]
@iambami 
Can I take this issue?

**Comment by iambami** [comment]
Sure @RakeshPotnuru. Please go ahead.
