### ISSUE TITLE
[Community] Member Profile: Hersh Dhillon 

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2613]
**Current Behavior**

@hershd23 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize hershd23 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: hershd23
- Twitter: 
- LinkedIn: 
- Link to profile picture: https://drive.google.com/file/d/1CJrziXlIT2RTdWOG0pRCcT8aVQMy1BXk/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by hershd23** [comment]
Twitter :- https://twitter.com/DhillonHersh
LinkedIn :- https://www.linkedin.com/in/hersh-dhillon/

Thanks!

**Comment by sidd-oo** [comment]
Can I take this issue ? @warunicorn19

**Comment by warunicorn19** [comment]
Sure @sidd-oo. @hershd23 would you like to provide a location and a bio as well?

**Comment by hershd23** [comment]
I had edited that above comment and added the location and bio

**Comment by warunicorn19** [comment]
Oops, I didn't see that, sorry my bad 😅.
