### ISSUE TITLE
[Community] Member Profile: Pranav Singh

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2614]
**Current Behavior**

@theBeginner86  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @theBeginner86  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @theBeginner86 
- Twitter: theBeginner86
- LinkedIn: pranav-singh-00904b1bb
- Link to profile picture: https://pbs.twimg.com/profile_images/1353835231292350466/J8QAnAVM_400x400.jpg

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by theBeginner86** [comment]
Thank you, @warunicorn19 😊

**Comment by theBeginner86** [comment]
1. **Bio:**
Pranav is an undergraduate studying computer science at VIT Vellore, India. He is passionate about building technology and making an impact through software development. Currently, he is exploring the software world through open-source contributions. His interest lies in DevOps, microservices, software architecture, and cloud-native technologies.

2. **Location**:
New Delhi, India

**Comment by MukulKolpe** [comment]
Congratulations @theBeginner86 !!
Hey @warunicorn19 can I work on this?

**Comment by leecalcote** [comment]
Thanks, @MukulKolpe
