### ISSUE TITLE
[UI] Event DevConf '22 Image not properly aligned

### ISSUE THREAD

**Issue by sidd-oo** [layer5io/layer5#2622]
**Description**
Event DevConf '22 Image is not properly aligned. 

![image](https://user-images.githubusercontent.com/25115188/155887827-9006bf3b-f3d6-48b6-8885-96aaf02a4236.png)
![image](https://user-images.githubusercontent.com/25115188/155887834-1c44eaec-cc9e-417e-9d27-c9ab66548f48.png)

---
**Expected Behavior**
Either this below new image could be replaced with the old image or resolution can be set using some CSS rule.
![image](https://user-images.githubusercontent.com/25115188/155887886-a09130bd-3157-49b2-97d3-3f3997e8b436.png)

---
**Screenshots**

**Environment:**
- Host OS:  WSL
- Browser:  Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sidd-oo** [comment]
Can I work on this issue?

**Comment by Chadha93** [comment]
@sidd-oo it's great you created an issue regarding this, it would be much better if you would create the CSS globally for this whole image in the card so that it will auto adjust the size according to the component.
Sounds good to you?

**Comment by sidd-oo** [comment]
@Chadha93 I didn't get you, can you explain a little more please.
