### ISSUE TITLE
Lazy load all iframes

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2623]
**Current Behavior**
We use several `<iframes>` across [Resources](https://layer5.io/resources), [Blogs](https://layer5.io/blog/meshery/an-introduction-to-meshery-webinar-on-demand),  [Events](https://layer5.io/community/events/kubecon-china-2021).

**Desired Situation**
Use the lazy load attribute for each of these.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sidd-oo** [comment]
Can I work on this issue?

**Comment by debo19** [comment]
Sure @sidd-oo, go ahead
