### ISSUE TITLE
Layer5 logo is not responsive 

### ISSUE THREAD

**Issue by Krishnapro** [layer5io/layer5#2633]
**Current Behavior**

- Layer5 logo is not responsive on every screen size.

**Desired Behavior**

- Reduce the left margin 
- Like the mentioned picture 

---
**Screenshots / Mockups**

![image](https://user-images.githubusercontent.com/59277887/156593917-3a01b5fc-8ee8-4ca3-8976-ebf9a8986568.png)

![image](https://user-images.githubusercontent.com/59277887/156596316-ccd4fcc7-d36f-4c39-a729-2bd9b224013e.png)

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by YashKamboj** [comment]
Wanna work on this issue?? @Krishnapro

**Comment by Krishnapro** [comment]
Yes I want to work on this. @YashKamboj

**Comment by Nikhil-Ladha** [comment]
What's the screen resolution for which you are hitting this issue?
And for what range of resolution does this issue stay?

**Comment by Krishnapro** [comment]
Already I have start working.

**Comment by Nikhil-Ladha** [comment]
> Already I have start working.

But, it should qualify to be an issue in order to work upon :)

**Comment by warunicorn19** [comment]
@Nikhil-Ladha it seems to be happening when 992px is hit. I think it's happening because of lazy loading, I'm not sure though.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha it seems to be happening when 992px is hit. I think it's happening because of lazy loading, I'm not sure though.

Yeah, but that's really for only the 10px range which again is not a supported resolution anywhere.
Though, let's have the fix to avoid that tini tiny 10px as well ;)

**Comment by warunicorn19** [comment]
It's actually a 50px range😂😂

**Comment by Krishnapro** [comment]
Please tell me should I fix this issue or not.

**Comment by Nikhil-Ladha** [comment]
> Please tell me should I fix this issue or not.

Yes, go ahead

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Nikhil-Ladha

**Comment by Krishnapro** [comment]
I am working on this issue @Nikhil-Ladha

**Comment by Krishnapro** [comment]
I have fixed this issue please review and merge it.
