### ISSUE TITLE
[Landscape] External links on the service mesh landscape page should have the `rel="nofollow"` attribute

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#2634]
**Current State:**
The [Service Mesh Landscape](https://layer5.io/landscape) page has a lot of external links that point to the respective service mesh's site/GitHub repo and the site crawler will rank our site based on those links. This may hamper the SEO of our site.

**Desired State:**
All the external links on the site should have the `rel="nofollow` attribute so that the link is avoided by the crawler.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sidd-oo** [comment]
Can I work on this issue ? @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Sure, go ahead @sidd-oo

**Comment by sidd-oo** [comment]
> **Current State:** The [Service Mesh Landscape](layer5.io/landscape) page has a lot of external links that point to the respective service mesh's site/GitHub repo and the site crawler will rank our site based on those links. This may hamper the SEO of our site.
> 
> **Desired State:** All the external links on the site should have the `rel="nofollow` attribute so that the link is avoided by the crawler.
> 
> **Contributor Resources**
> 
> * [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
>   The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> * See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> * See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

The current state link for [Service Mesh Landscape](https://github.com/layer5io/layer5/issues/layer5.io/landscape) is not workking, Can you please provide it the working URL @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Done
