### ISSUE TITLE
[Learn] Remove the extra sentence

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2635]
**Current State:**
The second sentence on [The Layer5 home page](https://github.com/layer5io/layer5/blob/master/src/sections/Home/Proud-maintainers/index.js#L29) needs to the removed

**Desired State:**
The second sentence is a repetition of the first. Delete the extra sentence.
![snip2](https://user-images.githubusercontent.com/64528871/156799893-aa5900ea-4314-4136-beaa-fc686304cab3.PNG)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by rparias** [comment]
Can I take it?

**Comment by Abhijay007** [comment]
sure @rparias go ahead :)

**Comment by iambami** [comment]
Sure @rparias , please go ahead.

**Comment by iambami** [comment]
Thanks for working on this @rparias

**Comment by iambami** [comment]
#2636
