### ISSUE TITLE
[Discuss-UI] Topic titles not appearing in dark mode

### ISSUE THREAD

**Issue by verma-kunal** [layer5io/layer5#2642]
**Description**
The topic titles of some posts, are not visible in the Dark mode, as they turn black in colour! 

**Expected Behavior**
In dark mode, topic titles should be appearing like this (screenshot below):
![Screenshot 2022-03-07 at 1 06 20 AM](https://user-images.githubusercontent.com/72245772/156939228-0f013580-c769-44ff-9ad1-db7a9ba3bfe3.png)

**Screenshots**
![Screenshot 2022-03-07 at 1 04 05 AM](https://user-images.githubusercontent.com/72245772/156939166-9b480924-b738-42b6-a04d-efbe746ff809.png)

**Enviroment:**
- Host OS: MacOS
- Browser: Brave Browser, Safari 

---
**Contributor Resources**

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

**Comment by verma-kunal** [comment]
/area/discuss

**Comment by kayceeDev** [comment]
@verma-kunal I want to take a look at this issue but I can access the `create account page`
![Capture](https://user-images.githubusercontent.com/42142223/157014601-cdf8a0cf-3c9e-440f-8850-19e48cf6c782.PNG)

**Comment by ghulamyazdani** [comment]
I think I can work on this!

**Comment by verma-kunal** [comment]
> @verma-kunal I want to take a look at this issue but I can access the `create account page` 
The discuss staging has been taken down right now, so would have to set it up locally on the system using Docker

**Comment by verma-kunal** [comment]
> I think I can work on this!

Sure! It would be great to know how you set up the discuss forum locally
Thanks

**Comment by verma-kunal** [comment]
Hey @ghulamyazdani @kayceeDev , this may help you to setup discourse locally! 
https://meta.discourse.org/t/how-do-i-set-up-a-local-discourse-development-environment/182882

**Comment by Ardent10** [comment]
Hey, @verma-kunal 
I think I can work on this issue as a part of OpenForce22 participant.

**Comment by Akshit42-hue** [comment]
Can I work on this issue @verma-kunal

**Comment by verma-kunal** [comment]
Hey @Ardent10 @Akshit42-hue , really glad to see that you wanna work on this issue! 
Last time I checked, @ghulamyazdani had started working on this one & if we don't see any activity from their side in a few days, you can definitely go ahead & assign the issue to yourself!

**Comment by Ardent10** [comment]
> Hey @Ardent10 @Akshit42-hue , really glad to see that you wanna work on this issue! Last time I checked, @ghulamyazdani had started working on this one & if we don't see any activity from their side in a few days, you can definitely go ahead & assign the issue to yourself!

Sure, thankyou. :)

**Comment by Ardent10** [comment]
@verma-kunal 
Can you tell me a work around for this, I can't access the website. I did try to change the permissions in two different browsers but still the same result.
![image](https://user-images.githubusercontent.com/73132031/158547799-5b568836-7847-4d94-9e10-66d0453d67b5.png)

**Comment by kayceeDev** [comment]
> Hey @ghulamyazdani @kayceeDev , this may help you to setup discourse locally! https://meta.discourse.org/t/how-do-i-set-up-a-local-discourse-development-environment/182882

@Ardent10  please take a look at the link in the comment. The staging site is currently down at the moment. What you can do is set up discourse locally through one of the provided steps when you open the link

**Comment by leecalcote** [comment]
Better yet, just use your local inspector to tryout a new style setting. @kayceeDev can you get this knocked out?

**Comment by kayceeDev** [comment]
This issue has been fixed @leecalcote, I want to close this now.
