### ISSUE TITLE
[UI] Remove the second instance of profile image from the mentioned blog

### ISSUE THREAD

**Issue by sidd-oo** [layer5io/layer5#2643]
**Description**
There is a blog [My Open Source Journey @Layer5](https://layer5.io/blog/community/my-open-source-journey-layer5) on the Layer5 site which contains two similar [images](https://layer5.io/static/Intern-profile-dfb22773011aa31539cf2b296decace5.png), the second image needs to be removed as it makes no sense to keep the same instances of the image in a single page.

**Expected Behavior**
Keep the first image which is the title image and remove the second image which is available adjacent to the paragraph content.

**Screenshots**
![image](https://user-images.githubusercontent.com/25115188/157028621-9dd15dbe-12ca-4955-8d41-97a8851c2608.png)

**Environment:**
- Host OS: Windows
- Browser: Chrome
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by rajat4984** [comment]
Hey i think i can handle this issue would love to contribute

**Comment by Nikhil-Ladha** [comment]
Sure, go for it @rajat4984

**Comment by goyalsaksh** [comment]
Hi, I am a contributor to openforce22 . I would like to work on this issue . I would be making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by Nikhil-Ladha** [comment]
> Hi, I am a contributor to openforce22 . I would like to work on this issue . I would be making a PR as soon as I am done with resolving the issue. Thank you.

Hi @goyalsaksh , if Rajat fails to make a PR then you can take up the issue.
In the meantime you could check other open issues.

**Comment by goyalsaksh** [comment]
@Nikhil-Ladha sir, as I am beginner ,I am unable to find issue which i can resolve using c++,please guide me.
