### ISSUE TITLE
[Books] Data is not filtered correctly in the table on the service-mesh-patterns book page.

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#2644]
**Description**

The table in the [Service Mesh Patterns Book](https://layer5.io/learn/service-mesh-books/service-mesh-patterns) is not sorting the data correctly.

**Expected Behavior**

It should not consider the section headers while sorting the data, rather sort the data as per the requested sorting technique under individual sections.

**Screenshots**

[Reference screen recording](https://youtu.be/G3Ks4ddQy1o)

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sidd-oo** [comment]
Can I take this issue? @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Please avoid good-first-issue for sometime, so that people from openforce can take them up.
Un-assigning you for the time being @sidd-oo 
If no one takes it up, in 2-3 days then ping me for assignment.

**Comment by sidd-oo** [comment]
Sure, no worries @Nikhil-Ladha 
Even I think it would be more worthwhile to start taking on tasks that are a little more challenging than good first issues.

**Comment by ghulamyazdani** [comment]
can I work on this @Nikhil-Ladha ?

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Abhijay007

**Comment by nik132-eng** [comment]
If this issue is still open and for beginners please assign it to me, sir.

**Comment by leecalcote** [comment]
@Akshit42-hue @nik132-eng yes, you're both most welcome to give it a try. I'll leave it unassigned until such point as you're able to demonstrate a potential solution.

**Comment by leecalcote** [comment]
@ghulamyazdani still working on this item? If not, please unassign. If so, how's it coming along?

**Comment by Chadha93** [comment]
// @Akshit42-hue

**Comment by Nikhil-Ladha** [comment]
@Akshit42-hue are you working on this issue?

**Comment by Akshit42-hue** [comment]
Can't find any lead @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Ok, then un-assignung you so that @SAEb-ai can take a look, if interested?

**Comment by SAEb-ai** [comment]
Thanks @Nikhil-Ladha!! I will take a look at it then.

**Comment by adithyaakrishna** [comment]
@SAEb-ai Any updates on this? 👀

**Comment by theplayer9** [comment]
Hey @Nikhil-Ladha  Can I work on this issue ?  It will help me to kick start my opensource journey.

**Comment by Nikhil-Ladha** [comment]
Yes, go ahead @theplayer9 .

**Comment by sahilsuman933** [comment]
@theplayer9 are you still working on this issue?

**Comment by theplayer9** [comment]
My College exams are going on. You can work on it.

**Comment by kayceeDev** [comment]
@sahilsuman933 Are you still working on this issue? Do you have any challenges? Whats your status?

**Comment by sahilsuman933** [comment]
@kayceeDev I am still working on it

**Comment by kayceeDev** [comment]
> @kayceeDev I am still working on it

Alright great. 😎
