### ISSUE TITLE
[MeshMap] Create "Accounts to Connect" section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2647]
**Current Behavior**
The form on the [MeshMap signup page](https://layer5.io/meshmap) needs updated slightly to convey that individuals who sign up for the waitlist need to provide at least one of their existing accounts to connect for access to MeshMap.

**Desired Behavior**
1. Visually denote that these for identity providers are part of the same section; that they are part of the same section: **Account(s) to Connect**
1. Make the explanatory text small, gray and under the **Account(s) to Connect**

**Screenshots / Mockups**
<img width="1167" alt="Screen Shot 2022-03-10 at 10 57 02 AM 2" src="https://user-images.githubusercontent.com/7570704/157716110-e107db02-f5a0-4f68-a6d0-162d73be0827.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhijay007** [comment]
@leecalcote  do we need to implement something like a "dropdown" in order to bring up all the fields together to one section called "connected Account"

**Comment by leecalcote** [comment]
@Abhijay007 Thanks for asking. Considering a person may fill in information for more than one account, no, we can leave the fields as for separate text inputs. 

By "creating a section ", I mean putting a section title of "accounts to connect " with text description and some other visual indication that these four inputs are in the same group.

**Comment by Abhijay007** [comment]
> @Abhijay007 Thanks for asking. Considering a person may fill in information for more than one account, no, we can leave the fields as separate text inputs.
> 
> By "creating a section ", I mean putting a section title of "accounts to connect " with text description and some other visual indication that these four inputs are in the same group.

okay got it, Thanks for the info :)

**Comment by shefali12-ab** [comment]
@leecalcote Is someone working on this issue?

**Comment by leecalcote** [comment]
Not to my knowledge, @shefali12-ab. I'll assign to you. Do signal to remove assignment if you either don't desire to work on it or get stuck in doing so.

**Comment by shefali12-ab** [comment]
Thank you @leecalcote  if I get stuck or need help didn't I ask in the community for help?

**Comment by debo19** [comment]
@shefali12-ab How are you getting along with this issue? Any updates?

**Comment by indraantoor** [comment]
This issue has been open for a long time without any update. If so, I would like to work on this issue too.

I am thinking about, what if we just add a **hr** like line above the Google's textbox below the Organization/School/Company textbox and then *hr** like line below Linkedin's textbox that way it would be a visual indicator of a Grouped Section and also above the Google's Textbox we can add the heading of "Connected Account" and below that add the description which needs to be added as shown in the picture of the issue. 

It's layout would look somewhat like this.

<hr />
Horizontal line comes here---

### Connected Account
Choose between Google, Twitter, Github and Linkedin..... (and the rest of the description shown in the image)

**Google:**
_textbox_

**Github:**
_textbox_

**Twitter:**
_textbox_

**Linkedin:**
_textbox_

Horizontal line comes here---
<hr />


I am thinking of the layout like shown above.

**Comment by YashKamboj** [comment]
@debo19 Isn't this issue solved??

**Comment by debo19** [comment]
@YashKamboj Right, it is.
