### ISSUE TITLE
Footer Date

### ISSUE THREAD

**Issue by Ardent10** [layer5io/layer5#2648]
**Description**
The current year setting at the footer is not dynamic I guess and that is why it it showing as 2021.

![image](https://user-images.githubusercontent.com/73132031/157729662-430e368b-e4e7-430e-9ccc-f820cc91d1c8.png)

**Expected Behavior**

The Year should change dynamically every year without the need to change it each year.

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by rajat4984** [comment]
can i take this ?

**Comment by Ardent10** [comment]
@rajat4984 
I am not a the Maintainer but a contributor myself.

**Comment by Abhijay007** [comment]
@rajat4984 @Ardent10 there is already a PR is opened for this issue [2615](https://github.com/layer5io/layer5/pull/2615)

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Abhijay007

**Comment by rajat4984** [comment]
@Abhijay007 okayyy 👍🏻👍🏻

**Comment by Ardent10** [comment]
@rajat4984 I'll be making the year Dynamic. I will make a PR as soon as this is resolved.

**Comment by leecalcote** [comment]
Thank you, @Ardent10 👍

**Comment by leecalcote** [comment]
I missed all of the previous comments and I'm just now seeing them. I'll let @Abhijay007 clarify on how to best proceed.

**Comment by Abhijay007** [comment]
@Ardent10 let me first ask from @Ayush7614 that if he is working on that PR or not, I will notify you if I got any updates :)

**Comment by leecalcote** [comment]
Also, there is a ton of work to do on this site. Join the weekly Websites meetings on Mondays and grab a piece of the action. Details here - https://meet.layer5.io

**Comment by rajat4984** [comment]
@leecalcote looking forward to join this monday 👍🏻
