### ISSUE TITLE
[UI] Increase the count of Blogs/Articles list when filtered

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#2653]
**Current Behavior**
Increase the count of Blogs/Articles list when filtered with categories or tags
Currently, it only shows up to 4 when filtered.
![image](https://user-images.githubusercontent.com/65453826/158256420-16a50b50-f526-402a-83c9-016a4bf9d8a9.png)

**Desired Behavior**
Increase the count to 6 or whichever suits on page greater than 4.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by sayan011** [comment]
Hey @Chadha93 ,can I work on this issue?

**Comment by sayan011** [comment]
Hey @Chadha93  ,can I work on this issue?

**Comment by Abhijay007** [comment]
sure @sayan011 go ahead :)

**Comment by antariksh17** [comment]
I triaged this to src/sections/Blog/Blog-sidebar/index.js
Working on fixing this issue right now.

what exactly do you need it to do. show 10 posts and if more then give the option of "older posts"?

**Comment by sayan011** [comment]
It's great to see that you're putting so much effort on solving  the issue, but sorry to bother you, I've been assigned to this issue and I am still working on it 😅.

**Comment by leecalcote** [comment]
@subhradwip01 something that you would like to take on?

**Comment by leecalcote** [comment]
Or is this fixed?

**Comment by antariksh17** [comment]
This is fixed right?


Warm Regards,

Siddharth (Antariksh) <https://www.liinks.co/antariksh>,
New Delhi, India
IST | GMT+ 0530
<https://www.worldtimebuddy.com/?pl=1&lid=30,100,8,5&h=30&hf=1>

**Comment by subhradwip01** [comment]
> Or is this fixed?

I guess this is issue is fixed

**Comment by subhradwip01** [comment]
> > Or is this fixed?
> 
> I guess this is issue is fixed

But I saw a problem it is showing 6 blogs when it is filtered using category...but when it is filtered by tags it is showing only 4 blogs.... @leecalcote @Abhijay007 i guess it is need to be fixed...I would like to work on that

**Comment by Chadha93** [comment]
> > > Or is this fixed?
> > 
> > 
> > I guess this is issue is fixed
> 
> But I saw a problem it is showing 6 blogs when it is filtered using category...but when it is filtered by tags it is showing only 4 blogs.... @leecalcote @Abhijay007 i guess it is need to be fixed...I would like to work on that

good eye @subhradwip01 you can make a pr for this issue for the tags filtering.

**Comment by subhradwip01** [comment]
@Chadha93 in a recent pr, we can see 10 blog post if we filterd the blogs...should I make it to 6?

**Comment by Chadha93** [comment]
> @Chadha93 in a recent pr, we can see 10 blog post if we filterd the blogs...should I make it to 6?

@subhradwip01 thanks for checking, Let's leave it to 10 only.
