### ISSUE TITLE
[UI] Highlighting the active blog category or tag

### ISSUE THREAD

**Issue by subhradwip01** [layer5io/layer5#2654]
**Current Behavior**

Currently, there is no highlighting feature based on the visited blog category or tag.

https://user-images.githubusercontent.com/88609894/158444347-fec4dea0-8835-487b-b25a-37c60fe37671.mp4

**Desired Behavior**

Tags or categories should be highlighted based on active category or tag. So that users can understand which tag or category they are currently in.
---
**Screenshots / Mockups**

**Alternatives**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by RakeshPotnuru** [comment]
@subhradwip01 
I want to work on this issue.

**Comment by Abhijay007** [comment]
sure @RakeshPotnuru go ahead :)
