### ISSUE TITLE
Align the cards in proper format

### ISSUE THREAD

**Issue by Akshit42-hue** [layer5io/layer5#2657]
**Description**

In the community/members page the cards are not properly Align
**Expected Behavior**

Align the cards properly
**Screenshots**

![Screenshot from 2022-03-16 13-43-20](https://user-images.githubusercontent.com/59443454/158546107-d5ed5116-88d2-4ff9-a9f2-0b08c0cd0c23.png)

**Environment:**
- Host OS: Linux
- Browser: Chrome

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Nikhil-Ladha @asubedy

**Comment by asubedy** [comment]
Yes sure @Akshit42-hue🚀

**Comment by Akshit42-hue** [comment]
Does this alignment looks good to you? @asubedy 
![Screenshot from 2022-03-16 18-04-30](https://user-images.githubusercontent.com/59443454/158590996-1cac0799-fd3b-4833-a66e-db1050439c9d.png)

**Comment by asubedy** [comment]
Lets put a little bit of space below the names. The names having two lines are looking a bit clustered.

**Comment by asubedy** [comment]
Umm, we can try but I think that will create some disparity that will not look nice. But let us see how it looks.

**Comment by Akshit42-hue** [comment]
Here how it looks @asubedy 
![Screenshot from 2022-03-17 16-36-37](https://user-images.githubusercontent.com/59443454/158796435-da94e93c-26f1-4294-94f8-42b2002dc032.png)

**Comment by Akshit42-hue** [comment]
Does this looks good to you @asubedy 
And can you please add **openforce** Label

**Comment by debo19** [comment]
@Akshit42-hue Let's discuss this in the websites call tomorrow
