### ISSUE TITLE
The blog page is not loading from the local build after cloning

### ISSUE THREAD

**Issue by antariksh17** [layer5io/layer5#2662]
**Description**

I am new to open sorce and i tried to clone and run the local environment in browser, I clicked the blog section and the request times out every time. it keeps showing, preparing a page in the bottom

**Expected Behavior**

The blog page is supposed to load

**Screenshots**

**Environment:**
- Host OS: Mac OS 13.2 High  Sierra
- Browser: Chrome V 99

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Great question, @antariksh17. Will you kindly open up this question on https://discuss.layer5.io?

**Comment by antariksh17** [comment]
it was an occasional error it seems

**Comment by warunicorn19** [comment]
MacOS 13.2???
