### ISSUE TITLE
[Learning Paths Quiz] Allow users to review answers

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2672]
**Description**

https://user-images.githubusercontent.com/85789734/159272756-0d4a1d92-0938-4fc0-ac95-c5b350843faf.mov

We immediately move to the next question on clicking on any option. The quiz auto-submits on answering the last question.

**Expected Behavior**

Allow the user to review their answers before submitting. 

- On answering one question, the selected option should remain highlighted and the user should be moved to the next question only on clicking "Next" and not immediately.
-  Similarly, on answering the last question, the quiz should not auto-submit. User might want to visit a previous question, and so the option to "Submit" should specifically be available.

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Lezette** [comment]
Can I work on this issue @debo19

**Comment by debo19** [comment]
Yup go ahead @Lezette

**Comment by Lezette** [comment]
Hello @debo19 I have an issue locating the quiz, I'm currently on the URL in your screen record but this is what I can see
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/42512400/159485104-aaea476d-1823-4a05-a725-afac6c9b01b3.png">
can you please explain how to find the quiz?

**Comment by debo19** [comment]
@Lezette The code is commented here https://github.com/layer5io/layer5/blob/master/src/components/Learn-Components/Pagination/index.js#L55. You'll have to change it here to see it. Do comment it back when you commit your changes.

**Comment by Lezette** [comment]
Thank you
