### ISSUE TITLE
[Blog] Make space between sidebar components uniform

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2673]
**Description**
<img width="573" alt="Screenshot 2022-03-21 at 7 11 43 PM" src="https://user-images.githubusercontent.com/85789734/159274029-9c912368-db2c-426d-ac9c-178e674a716a.png">

**Expected Behavior**
Make the space between the Discuss call-out and "Categories" same as that between "Categories" and "Tags".

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Akshit42-hue** [comment]
Can I work on this issue @debo19

**Comment by debo19** [comment]
Sure @Akshit42-hue Go ahead.

**Comment by Akshit42-hue** [comment]
@debo19 Please do have a look

**Comment by Akshit42-hue** [comment]
Please do have a look @debo19
