### ISSUE TITLE
[UI] Service Mesh pattern project name out of card

### ISSUE THREAD

**Issue by Krishnapro** [layer5io/layer5#2676]
**Current Behavior**

- **service mesh pattern** project name is out of the card on screen size 780 x 1080.

![Screenshot from 2022-03-22 01-37-32 (copy)](https://user-images.githubusercontent.com/59277887/159356058-28b61f53-99b6-4ce7-bbef-58526fcb261c.png)

**Desired Behavior**

-  project name should be in under the card.

---
 

 **Environment:**
- Host: Ubuntu 20.04.02 LTS
- Browser: Chrome

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
yikes! This happens during resizing of the grid layout. Good eye, @Krishnapro ✔️

**Comment by Krishnapro** [comment]
Thank you @leecalcote

**Comment by Krishnapro** [comment]
please assign me this issue I want to work on it.

**Comment by Abhijay007** [comment]
sure @Krishnapro go ahead :)

**Comment by kayceeDev** [comment]
@Krishnapro what's the update with this issue? Have you been able to open a PR with a fix? do you need help working on it?

**Comment by Krishnapro** [comment]
@kayceeDev yes I am working. If need any help I will ask.

**Comment by kayceeDev** [comment]
Alright. Well done @Krishnapro
