### ISSUE TITLE
[UI] See more is out of card 

### ISSUE THREAD

**Issue by Akshit42-hue** [layer5io/layer5#2679]
**Description**

In the "Service Mesh Specifications and Why They Matter" card the **see more** is out of card on screen size 990 x 1080 

**Expected Behavior**

The **see more**  should be in under the card.

**Screenshots**

![Screenshot from 2022-03-23 13-12-35](https://user-images.githubusercontent.com/59443454/159649650-fa9914c2-5cbb-480e-8bdc-947ad503f58c.png)

**Environment:**
- Host OS: Linux
- Browser: chrome

---

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Akshit42-hue** [comment]
Can I work on this issue @asubedy @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Go ahead @Akshit42-hue
