### ISSUE TITLE
[UI] Feature cards not fully responsive

### ISSUE THREAD

**Issue by indraantoor** [layer5io/layer5#2683]
**Description**
In the following page https://layer5.io/service-mesh-management/meshery, the feature cards are not fully responsive. I looked at the code I think the CSS with responsiveness and the readability of the code can be improved.

**Expected Behavior**
Content inside the cards are responsive and don't collide with other elements.

**Screenshots**

![Responsive Bug](https://user-images.githubusercontent.com/64259328/160233923-a6804573-bd09-488b-9290-dfdb552ecf32.gif)

**Environment:**
- Host OS: Windows 11
- Browser: Google Chrome

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

I would love to contribute and work on this issue under **Codeflow Openforce 2022.**

**Comment by indraantoor** [comment]
I would love to contribute and work on this issue under **Codeflow Openforce 2022**.

**Comment by warunicorn19** [comment]
Go ahead @indraantoor
