### ISSUE TITLE
[Community] Member Profile: Uzair Shaikh

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#2688]
**Current Behavior**

@MUzairS15  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @MUzairS15  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @MUzairS15 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation of how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@MUzairS15 Please do provide the links for the bullets in the issue.

**Comment by MUzairS15** [comment]
Twitter: https://twitter.com/MUzairS15
LinkedIn:  https://www.linkedin.com/in/muzairs/
Profile Picture: https://photos.google.com/share/AF1QipOI-DdZ6kz58lPAhEN5fiCNe0Yckj0804-IhG9QEJkb9aK7ywmZwq5Zx4xllimaRQ?key=ei1XR2htcDlhb2ZMMWdEeG9fLXVmSGtPb2h6UWNR

**Comment by vish-han** [comment]
Is this issue assigned to someone,  if not I would love to work.

**Comment by Chadha93** [comment]
> @Chadha93 Is this issue assigned to someone, if not I would love to work.

Nope, go ahead @vish-han

**Comment by leecalcote** [comment]
@vish-han need help?

**Comment by vish-han** [comment]
I was having my college exams Lee, that's why I couldn't able to contribute. Now it's over , I will start from tomorrow

**Comment by leecalcote** [comment]
@vish-han, thanks. If you're unable to PR by end of day on Thursday, @Chadha93, will you knock this out instead? Let's not leave @MUzairS15 hanging.

**Comment by vish-han** [comment]
Ok Lee , I will try to make PR asap

**Comment by Chadha93** [comment]
@vish-han I'm wrapping up on this one, please jump on other issues if you would. Thank you.
