### ISSUE TITLE
[Extension] Adding required field to meshmap form

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2689]
**Current Behavior**
Currently, the `Accounts to connect` portion of the Meshmap sign-up form doesn't have a required field. To be able to give a user permission to access meshmap, it is necessary to fill in one of these fields. 

**Desired Situation**
Add a validation where at least one of these fields is necessary to fill in. 
![Screenshot 2022-04-01 at 12 36 50 AM](https://user-images.githubusercontent.com/53532328/161131441-83d6a074-17fd-4ba9-9a83-72bff2cea71a.png)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by SAEb-ai** [comment]
@warunicorn19 @leecalcote May I please be assigned to this? Thanks!!

**Comment by warunicorn19** [comment]
Sure thing @SAEb-ai

**Comment by leecalcote** [comment]
@SAEb-ai will you present progress on this in tomorrow's Websites meeting?

**Comment by leecalcote** [comment]
@SAEb-ai will you be at today's meeting? If not, do you have progress to report otherwise?

**Comment by SAEb-ai** [comment]
@leecalcote Sorry, I was a bit afk. Can you please help me with [this](https://layer5io.slack.com/archives/C015QJKUMPU/p1649663310965129) ? I have having some issues while installation.
