### ISSUE TITLE
[About] Swap "Community First" image on About page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2690]
**Current Behavior**
The About page (https://layer5.io/company/about) has an image next to "Community First" section with this image:

**Desired Behavior**
Swap the existing image next to "Community First" section with this image: https://pbs.twimg.com/media/FO4vSXcWQAUc1Uj?format=jpg

Reference tweet: https://twitter.com/oluwabamikemi/status/1508194928442159112

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Michellebuchiokonicha** [comment]
I would love to take this up

**Comment by vish-han** [comment]
I would love to work on the issue if I get assigned 😄

**Comment by leecalcote** [comment]
Thanks much for volunteering, @Michellebuchiokonicha and @vish-han.

**Comment by Michellebuchiokonicha** [comment]
I created a PR for this issue.
