### ISSUE TITLE
[Docker Extension] Add Learning call-to-action

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2702]
**Current Behavior**
This page, https://layer5.io/docker-extension-meshery, is without a call to action between the main body and footer.

**Desired Behavior**
Add the "Learn service mesh with interactive labs" call to action to this page. Find an example of that CTA here - https://layer5.io/learn/service-mesh-books/service-mesh-patterns

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by prashantpaidi** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
Sounds real good, @prashantpaidi, yes. As we go to assign this to you, will you quickly confirm that your able to build and run the site? Let’s make sure that you are set up for success.

**Comment by prashantpaidi** [comment]
@leecalcote Yes I am able to run the site.

**Comment by leecalcote** [comment]
Thank you, @prashantpaidi 👏
