### ISSUE TITLE
[Meshery] Add Docker Extension to feature carousel 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2706]
**Current Behavior**
A new Docker Extension for Meshery is being released. See details: https://layer5.io/docker-extension-meshery.

The feature carousel on https://layer5.io/service-mesh-management/meshery does not include a section for this extension, but should.

**Implementation**
Add screenshot, description, and link to extension page in the feature carousel.

---
**Screenshots / Mockups**

<img width="1245" alt="Screen Shot 2022-04-10 at 8 41 36 AM" src="https://user-images.githubusercontent.com/7570704/162621062-23686cd3-2c28-4292-a028-77a2d6646df5.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by ShivamTyagi12345** [comment]
I would like to work on this:)

**Comment by Chadha93** [comment]
> I would like to work on this:)

@ShivamTyagi12345 Are you able to set up the site locally? If yes let's assign you :)

**Comment by ShivamTyagi12345** [comment]
yes it's set up
