### ISSUE TITLE
[UX] Visual Design: Create call-to-action for MeshMap sign-up

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2710]
#### _Note: This issue can be broken into two issues, if needed._

**Current Behavior**
[MeshMap](https://layer5.io/meshmap) is a forthcoming extension to Meshery.

**Desired Behavior**
A new call to action (find an example of what a CTA is on this page - https://layer5.io/learn/service-mesh-books/service-mesh-patterns)

**Implementation**
1. Visual design of the call to action using elements from Layer5's asset library in Figma projects and the community shared drive.
1. Implementation of the new call to action. 

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Abhijay007** [comment]
@leecalcote I want to work on this issue :)

**Comment by leecalcote** [comment]
Alrighty. Sounds real good.

**Comment by SooditK** [comment]
Hii @leecalcote I would like to take up this issue, Just wanted to know some things, I have to implement a Similar Looking CTA(that you gave on the example) in the Meshmap route?

**Comment by Chadha93** [comment]
@SooditK No, this need to have the design first, we don't want the same one to be implemented. Adding design req label.
