### ISSUE TITLE
[Community] Member Profile: Jared Byers

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2713]
**Current Behavior**

@jbyers19 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @jbyers19
- Twitter: N/A
- LinkedIn:  jaredbyers25  
- Link to profile picture: 

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by jbyers** [comment]
@jbyers on Github is not Jared Byers who is related to your project.

**Comment by iambami** [comment]
Hi @jbyers, sorry about that. There is was little mix up. 
The usernames look like. Apologies

**Comment by leecalcote** [comment]
Oops! Thank you, @jbyers

**Comment by Akshit42-hue** [comment]
Hey @leecalcote, can I work on this issue

**Comment by leecalcote** [comment]
Yes, thank you, @Akshit42-hue

**Comment by Akshit42-hue** [comment]
Hey @jbyers19, can you please share your profile picture and the bio

**Comment by jbyers19** [comment]
@Akshit42-hue, will this work?
- **Pic:** https://media-exp1.licdn.com/dms/image/C5603AQECpyFw62R4ow/profile-displayphoto-shrink_400_400/0/1578013835749?e=1655337600&v=beta&t=Fj8t-VNjaT71XkWixUa40ikOpu2I780QOesYU7rrx4s
- **Bio:** "Software Engineer at NGINX developing cloud native solutions."

I never know what to put for a bio, so let me know if that isn't what you're looking for. 😄

**Comment by Akshit42-hue** [comment]
In the pic you looks dope 🔥
and in the bio you can  share which technologies you know and your past experience you can take references from here

**Comment by jbyers19** [comment]
Thanks, @Akshit42-hue! How's this?
> Jared is a Software Engineer at NGINX developing cloud native solutions. In 7+ years in the software industry, he has gained experience in several aspects of software development, including: QA, DevOps, and product development. His past experience includes mobile applications and microservices. Currently he is focused on cloud solutions, particularly those involving kubernetes.

**Comment by Akshit42-hue** [comment]
> Thanks, @Akshit42-hue! How's this?
> 
> > Jared is a Software Engineer at NGINX developing cloud native solutions. In 7+ years in the software industry, he has gained experience in several aspects of software development, including: QA, DevOps, and product development. His past experience includes mobile applications and microservices. Currently he is focused on cloud solutions, particularly those involving kubernetes.

This looks good to me
