### ISSUE TITLE
Breakpoint for responsive change needs updated

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#272]
**Description**
The layer5.io site needs its breakpoints across different elements to be uniform to avoid "screen tearing".

**Screenshot**
<img width="1037" alt="Screen Shot 2020-01-03 at 9 56 30 AM" src="https://user-images.githubusercontent.com/7570704/71819187-cba00400-3050-11ea-92cf-271a793b54e0.png">

**Comment by leecalcote** [comment]
@Nikhil-Ladha given your expertise on such things, do you mind taking a look here?

**Comment by Nikhil-Ladha** [comment]
@leecalcote I saw this error a few days back and was hoping of informing or opening an issue. But i forgot!
Yea I would look upon it :)

**Comment by leecalcote** [comment]
Fixed by #273
