### ISSUE TITLE
Replacing radio button to dropdown list in service-mesh-management/meshmap form

### ISSUE THREAD

**Issue by Akshit42-hue** [layer5io/layer5#2723]
**Current Behavior**

In the form "What role best identifies you?" in this section 
there is a radio button that occupies a lot of space  
![Screenshot from 2022-04-19 18-10-08](https://user-images.githubusercontent.com/59443454/164006174-31629845-369f-46e3-b16e-7857ae4b9a2a.png)

**Desired Behavior**
The radio-button should be replace by drop-down button

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Akshit42-hue** [comment]
Can I work on this issue @debo19 @warunicorn19

**Comment by debo19** [comment]
Sure @Akshit42-hue Go ahead.
