### ISSUE TITLE
[Community] Member Profile: Ruturaj Mohite

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2727]
**Current Behavior**

@gr455 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @gr455 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: gr455
- Twitter: 
- LinkedIn: Ruturaj Mohite https://linkedin.com/in/ruturaj-mohite/ 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by karnatisrinivas** [comment]
Hello @iambami , Can I work on this??/

**Comment by iambami** [comment]
Of course @karnatisrinivas please go ahead.

**Comment by karnatisrinivas** [comment]
Hey @gr455 , Thank you for your awesome work. 

For adding you into wall of members, Would you please share your profile picture link and a bit about yourself (Bio).

**Comment by gr455** [comment]
Profile picture: https://avatars.githubusercontent.com/u/53974118
Bio: "I am a student from India. Recently acquired interest in cloud native tech have been loving it since. I have been an open source contributor and maintainer for a couple years now. I listen to hip-hop, play basketball and eat biscuits whenever I can"

Is this good?

**Comment by Sam-Radnus** [comment]
Can i work on this @iambami ??
