### ISSUE TITLE
[News] Add latest mention of Meshery in news to site

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#2732]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the [Layer5 Newsroom](https://layer5.io/news).

**Article:**
- Title: Meshery gets mentioned as Google Petitions to Donate Istio Service Mesh to CNCF
- Link: https://containerjournal.com/features/google-petitions-to-donate-istio-service-mesh-to-cncf/

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Sam-Radnus** [comment]
@Chadha93 can i work on this ??

**Comment by Sam-Radnus** [comment]
I am having troubles with signed commits ,i am new to this ,help me
