### ISSUE TITLE
[About] Open Source Africa Community: Add caption to "Community First" picture

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2734]
**Desired Behavior**
Add caption to Layer5 Community Members picture on https://layer5.io/company/about page.

"_Layer5 community members at Open Source Africa Community conference, March 2022._"

**Screenshots / Mockups**
<img width="1184" alt="Screen Shot 2022-04-27 at 2 05 47 PM" src="https://user-images.githubusercontent.com/7570704/165601591-1b8420bb-1ae1-4f64-b41a-c7a2f4660012.png">

---

<img src="/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by kingebere** [comment]
Hello Leecalote , I would love to work on this issue

**Comment by St80ene** [comment]
Can I assign myself to this issue? @leecalcote

**Comment by claire-me** [comment]
Hey @leecalcote, can i handle this issue?

**Comment by Nikhil-Ladha** [comment]
Hi, @kingebere, @claire-me , I assigned this issue to @St80ene as he signalled for the same on slack earlier. 
Feel free to move around the community and look out for more such issues.
