### ISSUE TITLE
[Blog] Contributing to Meshery with End-to-End Automation Testing using Cypress

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2737]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** Contributing to Meshery with End-to-End Automation Testing using Cypress
**Topic:** cypress, test automation, meshery
**Core points to convey in the post:** 

Reference: https://layer5io.slack.com/archives/C011VPREG2Z/p1651162390443769?thread_ts=1651113754.202709&cid=C011VPREG2Z

_Great question (“How to start of with cypress testing in Meshery?“), in the future I highly suggest to skim at existing questions in [Layer5 Discuss community](https://discuss.layer5.io/) forum and posting the question if it hasn’t been made yet (No post there yet for this specific one) but answering your question you can (ordering is based on effort and need of cross collaboration, but you can mix and match freely):_

_Lee’s favorite (mine as well) “be a user”: become a whiny regular (Meshery UI) or power user (Meshery CLI) as technically possible to you, we welcome all levels of expertise. Installing, using and gaining familiarity with Meshery and its features is of great use and on the way we’d be delighted if you can raise any questions and suggestions you get (Have you installed Meshery? If not, try out the [Quick Start Guide](https://docs.meshery.io/installation/quick-start) which would get you with a local User-Packaged version of Meshery up and running, What about Meshery’s features like Service Mesh Lifecycle, Application, Pattern, Configuration and/or Performance Management? If not familiar, you may look into articles/guides from this list: [Architecture Adapters Concept](https://docs.meshery.io/concepts/architecture/adapters), [Meshery Functionality](https://docs.meshery.io/functionality),  [Using Multiple Adapters Guide](https://docs.meshery.io/guides/multiple-adapters). Finally, for Managing and using service meshes through Meshery try out some of the [Operation Guides](https://docs.meshery.io/guides) and/or [Meshery CLI Guides](https://docs.meshery.io/guides/mesheryctl))
Refer to our existing blog on “Functional Testing with Cypress in Meshery UI”: https://layer5.io/blog/meshery/functional-testing-with-cypress-in-meshery-ui
Look into [meshery/meshery repo issues with ‘cypress’ tag](https://github.com/meshery/meshery/issues?q=is%3Aopen+is%3Aissue+label%3Acypress) (just added this new tag) and jump into the discussion of existing issues, help split issues from umbrella/epic issues and looking into closed issues’ merged PR’s is also a good way of getting familiar of how this kind of contributions are made.
Look into [meshery/meshery repo’s /ui/cypress folder](https://github.com/meshery/meshery/tree/master/ui/cypress) and see how existing tests are implemented.
Reach out in the [#cypress-testing](https://layer5io.slack.com/archives/C02Q44SSCH4) to request for guidance on meshery, cypress and github workflow specifics as you bump into roadblocks._

_Granted that this is a bit of a stretch of what a new contributor would do but I highly suggest to you and anyone really interested to be one of our alpha/beta users of content for some WIP changes for both [“Contributing to Meshery UI”](https://github.com/MarioArriaga92/meshery/blob/docs/marioarriaga92/5211-contribute-e2e-tests-cypress/docs/pages/project/contributing/contributing-ui.md) and soon-to-be new [“Contributing to Meshery Cypress Tests”](https://github.com/MarioArriaga92/meshery/blob/docs/marioarriaga92/5211-contribute-e2e-tests-cypress/docs/pages/project/contributing/contributing-cypress.md). (These are in [my fork](https://github.com/MarioArriaga92/meshery) only, for now)_

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@MarioArriaga92 for your consideration...

**Comment by MarioArriaga92** [comment]
auto-assigned!

**Comment by leecalcote** [comment]
@MarioArriaga92 if you can get this into markdown, another collaborator can get you the rest of the way.

**Comment by MarioArriaga92** [comment]
Working on this

**Comment by leecalcote** [comment]
👍

**Comment by MarioArriaga92** [comment]
Will get this done this week 🙏
