### ISSUE TITLE
Having focus state on links for keyboard users

### ISSUE THREAD

**Issue by Olaleye-Blessing** [layer5io/layer5#2738]
**Current Behavior**
It is very difficult for keyboard users to know when a link is focused. Most of the links have no way to know when it's focused.

**Desired Behavior**
There should be a different state for focused links/inputs/buttons.

---
**Screenshots / Mockups**
Current

![Screenshot (428)_LI](https://user-images.githubusercontent.com/70102539/165808076-044ea21e-3f00-49a6-b1a2-b74259165e2b.jpg)

Desired

![Screenshot (429)](https://user-images.githubusercontent.com/70102539/165808101-5b01ebcd-f6f4-40c6-98a2-314ed3eeec06.png)

**Alternatives**

---

<img src="/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Good suggestion, @Olaleye-Blessing. While we will avoid use of the bordered outline, I wonder how a bold font weight would look...

**Comment by Olaleye-Blessing** [comment]
Yea, I will.
Using font-weight will only affect links/buttons with text, it won't affect the ones with just images.

An example:

![Screenshot (438)_LI](https://user-images.githubusercontent.com/70102539/165859116-6b7ff7d5-51f1-4351-96d4-a7658e5c75cf.jpg)

What do you think?

**Comment by leecalcote** [comment]
I think that we don't need state tracking on images in general. Right or wrong, I favor aesthetics over strict accessibility. 

In this case specifically, users are directed to a different page onClick, landing on the specific section respective to the partner button clicked (using in-page anchor). My perspective is that this is all that the user needs to retain context of where they are (what image has been clicked).
