### ISSUE TITLE
Navbar accessibility for keyboard users

### ISSUE THREAD

**Issue by Olaleye-Blessing** [layer5io/layer5#2739]
**Current Behavior**
Keyboard users can't access the dropdown menu on the navbar. They can only be accessed when they are hover.

**Desired Behavior**
They should have have access to those drop down menus.

---
**Screenshots / Mockups**

The dropdown menu is only available to mouse users.

![Screenshot (430)_LI](https://user-images.githubusercontent.com/70102539/165812936-8b44f8ed-fc69-4141-8d8c-136004fb476a.jpg)

**Alternatives**

---

<img src="/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Confirmed. This is an accessibility issue. Do you have a proposed solution, @Olaleye-Blessing? `tabindex`?

**Comment by Olaleye-Blessing** [comment]
I'm not really sure if this is going to work since the hover state is achieved through Javascript.

Checking [ScrollspyMenu](https://github.com/layer5io/layer5/blob/master/src/sections/General/Navigation/utility/ScrollspyMenu.js) that displays the content, I think we can call [wrapDisplay](https://github.com/layer5io/layer5/blob/cfbf831f9ab45c95764adc4512d7e3cdbbbf7c65/src/sections/General/Navigation/utility/ScrollspyMenu.js#L26) that displays the submenu when either the nav link is focused or any or its sublink.

A possible solution could look like this:

Have a parent ref for [line 42](https://github.com/layer5io/layer5/blob/cfbf831f9ab45c95764adc4512d7e3cdbbbf7c65/src/sections/General/Navigation/utility/ScrollspyMenu.js#L42).

> const ulRef = useRef(null);

check if any inner sibling is focused
add `onFocus` to parent `ul`: [line 42](https://github.com/layer5io/layer5/blob/cfbf831f9ab45c95764adc4512d7e3cdbbbf7c65/src/sections/General/Navigation/utility/ScrollspyMenu.js#L42).

> function onFocus() {
>  const ul = ulRef.current;
> const isChildFocused= ul.contains(document.activeElement); // checks if any child is focused
> if(isChildFocused) wrapDisplay(); 
> }

[wrapNone](https://github.com/layer5io/layer5/blob/cfbf831f9ab45c95764adc4512d7e3cdbbbf7c65/src/sections/General/Navigation/utility/ScrollspyMenu.js#L32) removes the submenu

add `onBlur` to the last submenu item so as to call `wrapNone`

> function  onBlurred() {
> wrapNone()
> }

I'll like to make a pull request.

**Comment by Olaleye-Blessing** [comment]
I tried the above solution which I proposed but it's not working. There's just a flash of the dropdown menus when the first menu is focused. Someone else can work on it pending the time I figure it out.

**Comment by Palaksharma23** [comment]
@Olaleye-Blessing @leecalcote I would love to work on this issue, can I take this up :)

**Comment by leecalcote** [comment]
Sounds great, @Palaksharma23

**Comment by adithyaakrishna** [comment]
@Palaksharma23 Any updates on this?

**Comment by Palaksharma23** [comment]
I got a little busy @adithyaakrishna, I will do it now!

**Comment by Nikhil-Ladha** [comment]
We can live with the accessibility, no need for this much granularity.
