### ISSUE TITLE
Wrong nested interactive element.

### ISSUE THREAD

**Issue by Olaleye-Blessing** [layer5io/layer5#2740]
**Current Behavior**
Buttons(`<button></button>`) are descendants of Links(`<a></a>`).

**Desired Behavior**
There shouldn't be nested interactive elements. Having them is a bad practice according to:

- [this Reddit post](https://www.reddit.com/r/webdev/comments/ce4w59/is_it_bad_practice_to_wrap_a_button_in_an_a_href/)
- [stackoverflow](https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5#:~:text=It%20is%20illegal%20in%20HTML5,button%20element%20inside%20a%20link.&text=To%20whom%20it%20may%20concern,is%20social%2Dmedia%20type%20laziness.)

Ideally, it should either be a link to go to another page or a button to perform an action. [CSS-tricks post](https://css-tricks.com/buttons-vs-links/) might be of help to determine when to use either.

---
**Screenshots / Mockups**

![Screenshot (437)_LI](https://user-images.githubusercontent.com/70102539/165846143-7ecdacc0-5c25-4449-b8fc-1fb6465c1a31.jpg)

**Alternatives**

On checking the [Button component](https://github.com/layer5io/layer5/blob/master/src/reusecore/Button/index.js), I noticed that this [mistake](https://github.com/layer5io/layer5/blob/98db95541b523d1e4b27d6363d6f42ad1ba41cc1/src/reusecore/Button/index.js#L34) occurs whenever there is a `href` attribute.
Styled-Components have an `as` attribute that can switch elements.
One solution is to use `as="a"` if `URL prop` is present, else `as="button"`. And there should be an `options` object that gets filled depending on whether URL is present or not.

So it might look like:
> let options = {
>    className: addClasses.join(" "),
>    ...props
> }
> if(props.url) {
>   options = { ...options, as: "a", target: "_blank", rel: "noreferrer"}
> } else {
>  options = { ...options, onClick: props.Onclick }
> }

> <BtnStyle { ... options}>
>  ....
> </BtnStyle>

---

<img src="/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Olaleye-Blessing** [comment]
Just checked now and realized there's a `Gatsby Link Component`.
The `as` property for links could be `Link` instead of `"a"` 🤷

**Comment by DesmondSanctity** [comment]
Can this be assigned to me?

**Comment by leecalcote** [comment]
Adding @Olaleye-Blessing to help carry this forward...
