### ISSUE TITLE
[Homepage] Displace Image Hub with Nighthawk

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2741]
**Current Behavior**
Nighthawk is a project in need of representation on the homepage.

**Desired Behavior**
The card for Image Hub can be replaced with one for Nighthawk.

**Screenshots / Mockups**
<img width="1296" alt="Screen Shot 2022-04-28 at 5 20 51 PM" src="https://user-images.githubusercontent.com/7570704/165857344-150132d5-eb1d-483c-aa6c-95d85db40c52.png">

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Sounds good

**Comment by leecalcote** [comment]
@StarTrooper08 progress?

**Comment by StarTrooper08** [comment]
Ya on the way

**Comment by leecalcote** [comment]
@StarTrooper08 the clock is ticking...

**Comment by prasanta10** [comment]
Should I do it?

**Comment by prasanta10** [comment]
@leecalcote 
![Screenshot 2022-05-27 020801](https://user-images.githubusercontent.com/91861864/170576190-dfb1eaa5-e41f-473b-b4ae-c262a5b9cbca.png)

**Comment by leecalcote** [comment]
I know @StarTrooper08 is working on a few items, and so, it might be a welcomed helping hand, @prasanta10. Thank you.
