### ISSUE TITLE
[Docker Extension] Enhance bulleted list with images

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2754]
**Current Behavior**
[The Docker Extension for Meshery page](https://layer5.io/docker-extension-meshery) has a list of three features.

**Desired Behavior**
1. Ideally, each bullet point has a representative image next to it. See mockup.
1. Add a bit of whitespace between each of the three descriptions.

Images:
- visual-topology.svg (available in repo). See `src/sections/Meshery/How-meshery-works/images/visual-topology.svg`
- (available in repo) see https://layer5.io/service-mesh-management/meshery/operating-service-meshes
- [docker-compose-logo](https://user-images.githubusercontent.com/7570704/166245883-b0660ace-1420-4150-8fd8-09eeaa8ff73b.png)

**Screenshots / Mockups**
<img width="972" alt="Screen Shot 2022-05-02 at 8 44 50 AM" src="https://user-images.githubusercontent.com/7570704/166246170-8c9ca45b-66d9-4a18-8c9a-32ab49691b82.png">

**Alternatives**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by SooditK** [comment]
Can I take up the issue?

**Comment by Michellebuchiokonicha** [comment]
I am interested in this as well.

**Comment by subhradwip01** [comment]
Go ahead @SooditK ... @Michellebuchiokonicha you can look other issues also...😃😃

**Comment by SooditK** [comment]
Hii, This is what I've accomplished, Just wanted to know what should I do with the Mobile Version? Is there any specific requirements for it
![Firefox_Screenshot_2022-05-03T17-31-23 746Z](https://user-images.githubusercontent.com/50576944/166508072-e5ac34e6-67e6-49b7-9184-a3b86ddfbb9a.png)

**Comment by leecalcote** [comment]
@SooditK in mobile view, we will _probably_ want to make the graphic and the text single column. Will you try and let's see how it looks?

**Comment by leecalcote** [comment]
@subhradwip01 if you'd like to iterate on these mockups in context of the rest of the site designs, you can do so here - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs

**Comment by leecalcote** [comment]
Invite sent.

**Comment by leecalcote** [comment]
In the meantime, @SooditK, please PR your changes and let's have a look.

**Comment by SooditK** [comment]
Please take a look @leecalcote I've done as previously specified, If you want me to start working on the Figma Designs made by @subhradwip01 I would love to. 👍🏼

**Comment by subhradwip01** [comment]
> Please take a look @leecalcote I've done as previously specified, If you want me to start working on the Figma Designs made by @subhradwip01 I would love to. 👍🏼

Design is not made yet... once it is made...we will open issue don't worry ... till now whatever you made push the commit

**Comment by SooditK** [comment]
> > Please take a look @leecalcote I've done as previously specified, If you want me to start working on the Figma Designs made by @subhradwip01 I would love to. 👍🏼
> 
> Design is not made yet... once it is made...we will open issue don't worry ... till now whatever you made push the commit

The changes that Lee specified, are Committed and a pull request is made for the same.

**Comment by leecalcote** [comment]
Thank you, gents. The deadline on this work is tomorrow, May 8th. DockerCon is on the 9th.
