### ISSUE TITLE
[Community] Member Profile: Inactive Memeber

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2756]
**Current Behavior**
@shubham-tyagi has been inactive for a while, hence his Layer5 membership profile will be flagged inactive. We are looking forward to having him back. 

**Desired Situation**
Let's flag @shubham-tyagi as a community member by flagging his profile on https://layer5.io/community/members as an inactive member.

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by karnatisrinivas** [comment]
Hello @iambami , Can I work on this?

**Comment by Abhijay007** [comment]
sure @karnatisrinivas go ahead :)
