### ISSUE TITLE
[Community] Member Profile: Inactive Member (Shreyas Mishra)

### ISSUE THREAD

**Issue by iambami** [layer5io/layer5#2757]
**Current Behavior**
@Shreyas220  has been inactive for a while, hence his Layer5 membership profile will be flagged inactive. We are looking forward to having him back. 

**Desired Situation**
Let's flag @Shreyas220  as a community member by flagging his profile on https://layer5.io/community/members as an inactive member.

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by karnatisrinivas** [comment]
Hello @iambami , Can I work on this?

**Comment by karnatisrinivas** [comment]
<img width="1166" alt="Screenshot 2022-05-04 at 11 43 51 AM" src="https://user-images.githubusercontent.com/52213014/166630932-43cfe980-cc98-4c4b-afad-5599427dd040.png">

**Comment by karnatisrinivas** [comment]
Hello @Chadha93 , Shreyas profile is already marked as Inactive.

**Comment by Chadha93** [comment]
> Hello @Chadha93 , Shreyas profile is already marked as Inactive.

Thanks for checking @karnatisrinivas. Closing this issue.
