### ISSUE TITLE
[Event] Update ServiceMeshCon EU 2022 talk description to include participating organization logos

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2759]
**Current Behavior**
Speakers from multiple organizations are presenting MeshMark at ServiceMeshCon EU 22. Their respective organizations are not visually represented on event description.

**Desired Behavior**
Please update the event https://layer5.io/community/events/servicemeshcon-eu-2022 to include a "Participating Organizations" section with a small Intel logo and small Layer5 logo.

**Screenshots / Mockups**

<img width="570" alt="Screen Shot 2022-05-03 at 5 55 11 PM" src="https://user-images.githubusercontent.com/7570704/166586614-10eb33fa-a611-462d-a360-e990361193f1.png">

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by karnatisrinivas** [comment]
Hello @leecalcote , Can I work on this?

**Comment by gunwant11** [comment]
hello, new contributor here, if the issue is unassigned can i work on it?

**Comment by leecalcote** [comment]
@karnatisrinivas given you recent assignment to two other issues, let's allow @gunwant11 to take a stab at this one, if you don't mind.

**Comment by karnatisrinivas** [comment]
Yeah sure @leecalcote , no issues.  

I am more than happy to see new contributors @gunwant11
