### ISSUE TITLE
[UI]Some Cards in dashboard are being shown partially

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [layer5io/layer5#2761]
**Description**
Some Cards in dashboard are being shown partially in the main Dashboard

Here---

![Screenshot from 2022-05-04 23-09-14](https://user-images.githubusercontent.com/56961488/166747898-2853f230-ec20-47cf-9114-826d736715de.png)

![Screenshot from 2022-05-04 23-13-56](https://user-images.githubusercontent.com/56961488/166747949-ea8dc2b4-25dd-4cbe-9085-0984bd14eb05.png)

**Expected Behavior**
Full card should be shown

**Screenshots**

**Environment:**
- Host OS: Linux(Ubantu)
- Browser: Chrome

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
This is by design. Not an issue.
