### ISSUE TITLE
Add meshery/meshery-perf to Community Handbook Repository Overview

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2763]
**Current Behavior**
The repo at github.com/meshery/meshery-perf is new and is not yet listed in the [Community Handbook's repository overview.](https://layer5.io/community/handbook/repository-overview)

**Desired Behavior**
Create an entry for the new `meshery/meshery-perf` repo in the repository overview.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@subhradwip01  would like to take this?

**Comment by subhradwip01** [comment]
Ya sure

**Comment by subhradwip01** [comment]
@Chadha93  Is it meshery performance repo right?..Or it falls under another category ? Also is there any logo for that repo?
