### ISSUE TITLE
[UI] Cards not fully responsive in Distributed Performance Management section

### ISSUE THREAD

**Issue by indraantoor** [layer5io/layer5#2766]
**Description**

On the [nighthawk page](https://layer5.io/projects/nighthawk), the cards are not fully responsive.

**Expected Behavior**

The cards should be responsive and their heights should be the same. Also, a little bit of spacing between the text sections in individual cards would make the cards look even better. It will make the cards look more consistent with the overall design of the website. 

**Screenshots**

![Cards1](https://user-images.githubusercontent.com/64259328/167348628-0c7705b8-d26a-4fec-b89b-df60377528e9.png)
![cards2](https://user-images.githubusercontent.com/64259328/167348637-2b10ff2a-2c98-4731-a78a-3820c26fe0b8.png)
![cards3](https://user-images.githubusercontent.com/64259328/167348650-fecaa55d-e95c-498f-83ff-f84c2e8fe7d7.png)

**Environment:**
- Host OS: Windows 11
- Browser: Google Chrome

**I would love to work on this issue.**

---
[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Good eye and suggestions, @indraantoor

**Comment by leecalcote** [comment]
Progress?

**Comment by indraantoor** [comment]
It's almost finished, I will be making the PR tomorrow.
