### ISSUE TITLE
[Resource] Add Search feature  for Resource page 

### ISSUE THREAD

**Issue by subhradwip01** [layer5io/layer5#2767]
**Current Behavior**
Currently, we do not have any search feature on the Resource page : https://layer5.io/resources

**Desired Behavior**
Create a search feature for it

---
**Screenshots / Mockups**

**Alternatives**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Nikhil-Ladha** [comment]
@subhradwip01 I think you are occupied with other stuff, so can I un-assign you from this issue? So, that others can take it up.

**Comment by subhradwip01** [comment]
I am done with that..tonight i will make a PR
