### ISSUE TITLE
Change the "author" of each News item

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2769]
**Current Behavior**
"The Newsroom" author should be listed on each news item published by Layer5, but not on news items published elsewhere.

**Desired Behavior**
List the specific publisher's name (e.g. Container Journal or The New Stack) as the author on externally published news.

<img width="1213" alt="Screen Shot 2022-05-10 at 7 53 29 AM" src="https://user-images.githubusercontent.com/7570704/167633239-1e79f9c6-b51d-4ad5-91d3-54c5585c1cca.png">

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Lezette** [comment]
@leecalcote I'd love to work on this issue

**Comment by leecalcote** [comment]
Thank you, @Lezette :thu

**Comment by leecalcote** [comment]
Hi @lezette, apologies, I'm going to knock this out. It's about 10 days old and we just need this done now.

I'll open a new issue to create the ability to filter between news categories: "Press Releases" and "Coverage", though.

**Comment by leecalcote** [comment]
Fixed.
