### ISSUE TITLE
[Community] Member Profile: Maximiliano Churichi

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#2772]
**Current Behavior**

@mchurichi has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: mchurichi
- Twitter: mchurichi
- LinkedIn:  maximilianochurichi
- Link to profile picture: https://media-exp1.licdn.com/dms/image/C4D03AQE6jtCF9k204g/profile-displayphoto-shrink_800_800/0/1516954557825?e=1655942400&v=beta&t=2OawpONFkyZnXgRo_TVyeJCxzDzMtYCJObJsXhEN_QQ

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@mchurichi could you please provide a short bio and a location 😃

**Comment by mchurichi** [comment]
Thanks @warunicorn19!

Location: Paraná, Argentina
Bio: Maxi is a Sofware Engineer who loves to understand the whole picture, from the pixels on the screen to the bits that travel through the wires. Passionate about mentoring young engineers, open-source, cyber security, cloud infrastructure, and solving complex problems with simple solutions (service meshes being one of them!).
In his free time, Maxi loves to travel abroad as much as time permits, and spend time with his dog Beto and his cat Lola.

**Comment by leecalcote** [comment]
@harshitasao fyi

**Comment by harshitasao** [comment]
Thank you @leecalcote. Could you please assign this issue to me.

**Comment by Chadha93** [comment]
@harshitasao need any help here?

**Comment by harshitasao** [comment]
Hi @Chadha93, apologies for the delay. I'm facing an error while running this `make setup-libs` command. Can you please help me out?

**Comment by leecalcote** [comment]
@harshitasao you'll need provide more details. You're not using Windows, are you? What's the output of the command? Try using Docker, perhaps: `make docker`.

**Comment by harshitasao** [comment]
Yes, @leecalcote. I'm using Windows and, as you suggested, I tried to run `make Docker` but got a similar error.

**Comment by leecalcote** [comment]
Just think, when you share the error, we can actually help. 😉

**Comment by Chadha93** [comment]
Yepp error logs, screen shots would be helpful @harshitasao 😄

**Comment by leecalcote** [comment]
Likely, you're having trouble with not having `make` on Windows. Search the Layer5 Community drive for "Windows make" and you'll find two documents that describe ways in which to get `make` going on Windows or search the web for "Install make on Windows". In general, I recommend WSL2 on Windows as your dev environment. More than this, I recommend macOS or Linux for development (as least in so far as concerned with the projects and tech used here).

**Comment by harshitasao** [comment]
![layer5](https://user-images.githubusercontent.com/84518563/168426729-d509bf60-1cc1-48df-a38d-7fd7add93f7d.png)

**Comment by leecalcote** [comment]
Oh. Use `make setup`.

**Comment by harshitasao** [comment]
Thank you so much @leecalcote.

**Comment by leecalcote** [comment]
No sweat. I'm just filling in for MeshMate @Chadha93, who's the real go-to here.

**Comment by harshitasao** [comment]
Hi, @warunicorn19 Could you please tell me what badges should be present and what the status value should be? 
Thank you.

**Comment by warunicorn19** [comment]
Status should be active, let's leave out the badges for now.

**Comment by harshitasao** [comment]
Alright, thanks.
