### ISSUE TITLE
[CI] Improve build and deploy time

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2773]
**Current Behavior**
Currently, it takes about 8 minutes for this site's [build and preview workflow](https://github.com/layer5io/layer5/actions/workflows/build-and-preview-site.yml) to execute.

**Desired Situation**
Ideally, this time is cut in half.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Nikhil-Ladha** [comment]
Let's experiment the usage of the following flags and see if that helps.
`PARALLEL_SOURCING`
`LMDB_STORE`
`PARALLEL_QUERY_RUNNING`

**Comment by Chadha93** [comment]
> Let's experiment with the usage of the following flags and see if that helps. `PARALLEL_SOURCING` `LMDB_STORE` `PARALLEL_QUERY_RUNNING`

let's also keep temporary caching as another option https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by Nikhil-Ladha** [comment]
> let's also keep temporary caching as another option https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

Interesting stuff. `npm install` on each build could save up to a minute or so.
Do you want to give it a try?

**Comment by leecalcote** [comment]
The Gatsby v4 upgrade is positioned to help with this a bit.
