### ISSUE TITLE
[Docker Extension] Add summary of two DockerCon blog posts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2779]
**Current Behavior**
This page doesn't have information about the two talks given at DockerCon - https://layer5.io/docker-extension-meshery

**Desired Behavior**
Update this page to have a brief description of each talk and a link to each blog post recapping the talk:

Posts:
1. https://layer5.io/blog/docker/extending-the-docker-compose-experience-to-service-mesh
1. https://layer5.io/blog/docker/extending-docker-with-meshery-spire-and-istio

<img width="796" alt="Screen Shot 2022-05-11 at 6 53 44 PM" src="https://user-images.githubusercontent.com/7570704/167965863-b01a309d-d7e2-4b11-9e65-fd1db060edc1.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Nrycord** [comment]
Could you assign this one to me? I would like to get started and give it a try.

**Comment by Chadha93** [comment]
> Could you assign this one to me? I would like to get started and give it a try.

@Nrycord Just a quick check, are you able to build the site locally? If yes you are good to go. :)

**Comment by Nrycord** [comment]
> @Nrycord Just a quick check, are you able to build the site locally? If yes you are good to go. :)

I'm on it, it's my first time using wsl, i do have everything downloaded and the repo copied, but the "make" command is returning an error, figuring out what it could be for now

**Comment by leecalcote** [comment]
The best place to asks questions: https://discuss.layer5.io. // @kayceeDev 

If you have filled in a [community member form ](https://layer5.io/newcomers) you can access this google doc, which describes solutions for `make` on Windows - https://github.com/layer5io/layer5/issues/2779#issuecomment-1125611530.

@Chadha93 given the level of interest on this capability, you might need to pick up this issue and ask that @Nrycord follow along and review your PR when it's up. The need to get this info posted is timely.

**Comment by Chadha93** [comment]
@Nrycord You can have a look at the PR, Try using this command to install make and other essentials `sudo apt-get install build-essential`

**Comment by Nrycord** [comment]
> @Nrycord You can have a look at the PR, Try using this command to install make and other essentials `sudo apt-get install build-essential` if you face any issues feel free to ping on the slack channel :)
So far it seems it's a version problem, I'll ask around and try to solve it. I'll also check the PR. Thanks!
