### ISSUE TITLE
[Blog] Single Post: "About the Author" card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2780]
**Current Behavior**
The single blog post page layout doesn't have a callout for the post author.

**Desired Behavior**
Create an About the Author card in a similar style as to the community member cards on https://layer5.io/community/members.

See https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=190%3A846 for community member cards designs.
See https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=7920%3A13844 for About the Author design.

**Screenshots / Mockups**
![About the Author](https://user-images.githubusercontent.com/7570704/167971207-f7c75122-cb99-4cb7-9421-46f623e1a812.png)

**Acceptance Criteria**
1. Must be responsive. Make the About the Author card disappear on smaller screens.
1. Provide a generic-styled card for the "Layer5 Team" author.2. 
1. About the Author picture hyperlinks to the author's community member page.2. 

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by lolyparty** [comment]
Hey Lee, I'll like to try my hands on this.
The Figma links seem broken though.

**Comment by leecalcote** [comment]
@lolyparty, no, the Figma links are good. We just need to double-check on your access to them. Inquire in Slack, if you can't access after you have signed into Figma.

**Comment by lolyparty** [comment]
I think I need some clarity about this issue. Where exactly is the 'About the Author' card meant to be located? I can't find the location of the card in the Figma file, just the design of the card.

**Comment by leecalcote** [comment]
@lolyparty does this help?

**Comment by leecalcote** [comment]
@Lezette would you like to have a look at this?

**Comment by lolyparty** [comment]
> @lolyparty does this help?

Oh yes, it does.

**Comment by Lezette** [comment]
Sure @leecalcote. @lolyparty are you working on this now or would you need some help with the issue? If you’d need some help we could work on it together

**Comment by lolyparty** [comment]
> Sure @leecalcote. @lolyparty are you working on this now or would you need some help with the issue? If you’d need some help we could work on it together

Yes, I'm working on it, I'll reach out to you when I encounter any problem.

**Comment by lolyparty** [comment]
@Lezette I'll assign this to you now, you can work on it. I'm having some technical issues with my laptop

**Comment by leecalcote** [comment]
Sounds good, @lolyparty
