### ISSUE TITLE
[SCA 2022 Blog Post]

### ISSUE THREAD

**Issue by shebuel-oss** [layer5io/layer5#2786]
This issue is created for the upload of the new article about Layer5's participation in She Code Africa's Contributhon Program on https://layer5.io/blog. 

Here's the link to the written and reviewed article:** https://docs.google.com/document/d/1jAgxoWTd_jBnYoL2Fk-D6ltmN8HT5VrZ8UDy1xB1Sws/edit?usp=sharing

**Title:** Layer5 participates in She Code Africa's Contributhon Program 2022

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Thank you, @shebuel-oss. Let's be sure to include 2022 in the title.

**Comment by shebuel-oss** [comment]
Thank you @leecalcote 
I have just updated that.

**Comment by mzoyinda** [comment]
@Ruth-ikegah can you assign this to me

**Comment by leecalcote** [comment]
> 

@shebuel-oss, I mean in the issue title.

**Comment by yash-dewasthale** [comment]
Hello everyone I'm, new to open source, I have never contributed before this, will anyone give me advice how to start my first contibution

**Comment by Ruth-ikegah** [comment]
Hi @yash-dewasthale ! Thanks for commenting on this! There is already a PR linked to fixing this issue. 

You can check out this other issue: https://github.com/layer5io/layer5/issues/2859

**Comment by Ruth-ikegah** [comment]
Yes! Closing now!
