### ISSUE TITLE
[Brand] Create MeshMark section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2789]
**Current Behavior**

MeshMark is a newly announced measurement index - a sub-project of the SMP project.

**Desired Behavior**
Create section for MeshMark on layer5.io/brand. Add  [meshmark-brand-kit.zip](https://github.com/layer5io/layer5/files/8693081/meshmark-brand-kit.zip) for download.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by SooditK** [comment]
Can I take up the issue?

**Comment by Chadha93** [comment]
Oops, I see that @asubedy is already assigned for this issue(mentioned one) which is a chained issue. @asubedy you are working on this one as a complete issue with the mentioned one, right?

**Comment by asubedy** [comment]
@Chadha93 No I will be working only on the mentioned issue @SooditK can take this one.

**Comment by asubedy** [comment]
Hi @SooditK, this needed to be done urgently, so I completed it. Please feel free to look for other issues that interest you. Thank you.

**Comment by leecalcote** [comment]
@SooditK do review #2801...

**Comment by SooditK** [comment]
I was about to make a Pull Request for the same today, guess I have to work on some other issues then 😃
