### ISSUE TITLE
[Event] Lightning Talk: MeshMates : A New Way of Expanding Open Source Community Mentorship

### ISSUE THREAD

**Issue by kayceeDev** [layer5io/layer5#2791]
Please add the following event to layer5.io/events.

**Event:** Lightning Talk: MeshMates : A New Way of Expanding Open Source Community Mentorship
- Event Title: Open Source Summit North America
- Event Link: https://ossna2022.sched.com/
- Talk Description: See the talk link
- Talk Link: https://ossna2022.sched.com/event/11Pyl/lightning-talk-meshmates-a-new-way-of-expanding-open-source-community-mentorship-shivay-lamba-layer5
- Speaker: [Shivay Lamba](https://ossna2022.sched.com/speaker/shivaylamba)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by shivaylamba** [comment]
Thanks @kayceeDev I will work on this issue

**Comment by Santosh1176** [comment]
Hi, is this issue still open?
If yes, please let me know if I can do this.

**Comment by leecalcote** [comment]
Thank you for asking, @Santosh1176. 

@shivaylamba should take care of this. If not, I’ll assume that he doesn’t consider the talk important enough to promote and I will close this issue if it isn’t completed by Friday.

**Comment by shivaylamba** [comment]
Hi @leecalcote apologies for the delay, here's the PR for the event: https://github.com/layer5io/layer5/pull/2827
