### ISSUE TITLE
Denote active page with menu item coloring

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#280]
**Current Behavior**
The site menu currently shows users when they have navigated to the blog page by coloring the background of the menu item (see screenshot), but does not color the backgrounds of other menu items when users have navigated to other pages.

<img width="991" alt="Screen Shot 2020-01-15 at 9 53 11 AM" src="https://user-images.githubusercontent.com/7570704/72452974-0528eb80-3784-11ea-8f9a-aca4fa41d409.png">

**Desired Behavior**
A menu item's background color should denote which page the user is currently navigated to.
<img width="991" alt="Screen Shot 2020-01-15 at 10 46 31 AM" src="https://user-images.githubusercontent.com/7570704/72453391-9ef09880-3784-11ea-8816-d396e04d9342.png">

Ensure that the menu item (e.g. "Workshops") that matches the current page that the user is navigated to (e.g. "/workshops") has a background color.

Currently, when a user navigates to /blog, the "Blog" menu item receives a background color as the **active** hyperlink (menu item). 

See this section of the CSS that controls this behavior - https://github.com/layer5io/layer5/blob/master/_sass/top-nav.scss#L133-L136.

**Comment by leecalcote** [comment]
@supra08 given your familiarity with this menu system, this is a great issue for you to tackle.

**Comment by vineethvanga18** [comment]
@leecalcote This isn't closed yet?

**Comment by leecalcote** [comment]
@vineethvanga18 no, it's not. The light green should persist and show on the same menu item as to the current page that the user is on.

**Comment by vineethvanga18** [comment]
@leecalcote Can I work on this?

**Comment by leecalcote** [comment]
@vineethvanga18 yes, however, I sent you a better proposal in Slack

**Comment by vineethvanga18** [comment]
@leecalcote sure I will wait for PR on mega menu

**Comment by leecalcote** [comment]
@vineethvanga18 if you don't receive a response from @shivaylamba by end of day Friday, will you please seek out a mega menu that we might use in the layer5-ng site? We're looking for one similar to what you see on https://strapi.io

**Comment by vineethvanga18** [comment]
@leecalcote sure.
