### ISSUE TITLE
Change the tagline of Layer5

### ISSUE THREAD

**Issue by Akshit42-hue** [layer5io/layer5#2802]
**Current State:**
Need to change the logo of Layer5 in readme.md file

**Desired State:**
Instead we can use this logo [Layer5](https://www.google.com/url?sa=i&url=https%3A%2F%2Flayer5.io%2F&psig=AOvVaw0g5Lpz0i1H6Mi2d1Ls6e5D&ust=1652878335238000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCKiCl-PJ5vcCFQAAAAAdAAAAABAI)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by leecalcote** [comment]
Thanks. The version of the logo to use should still be full text of “Layer5” just without tagline.

**Comment by Chadha93** [comment]
@anarayner would you like to take this?
https://github.com/layer5io/layer5/issues/2793#issuecomment-1127740575

**Comment by anarayner** [comment]
@Chadha93  I do, thank you!

**Comment by leecalcote** [comment]
Yay, @anarayner!

**Comment by leecalcote** [comment]
Here's an ideal version of the logo to reference: https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/layer5-no-trim.svg
