### ISSUE TITLE
[Video] Brief Tutorial: How to install Meshery Docker Extension

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2805]
**Current Behavior**
Given that the Meshery Docker Extension is available in the Extensions Marketplace, visitors of the https://layer5.io/docker-extension-meshery page can both sign-up to learn more and also can directly go install the extension.

**Desired Behavior**
Site visitors will benefit from a short (60 second) video demonstrating how to install the Meshery Extension.

**Implementation**
Record a short video of your Docker Desktop app and your mouse installing the Meshery Extension. 
Show how to sign into Meshery Cloud and navigate to Meshery UI.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@cpepper96, this might be of interest to you.

**Comment by cpepper96** [comment]
@leecalcote I can do this once I get it working on my machine

**Comment by leecalcote** [comment]
@cpepper96 let's diagnose on tomorrow's Meshery Development Meeting...

**Comment by cpepper96** [comment]
@leecalcote sounds good!

**Comment by cpepper96** [comment]
@leecalcote got the video, just need to edit it

**Comment by leecalcote** [comment]
Oooh, nice. :)

**Comment by cpepper96** [comment]
@leecalcote just a heads up I've got graduation stuff going on tonight and through the weekend so I'll probably have to finish this up early next week!

**Comment by leecalcote** [comment]
@cpepper96 I very much appreciate this heads-up. Flip that tassel!
