### ISSUE TITLE
[News] Create to filter for news categories: "Press Releases" and "Coverage"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2815]
**Current Behavior**
The [layer5.io/news](https://layer5.io/news) page has no way of filtering between Layer5 produced news and news covered by external sources. The differences between these two news types is captured in the `category` metadata field.

**Desired Behavior**
- Add two filter buttons.
- Apply active state button coloring.
- Allow user to filter and unfilter on each category.

---
**Screenshots / Mockups**
<img width="1405" alt="Screen Shot 2022-05-19 at 5 15 04 PM" src="https://user-images.githubusercontent.com/7570704/169413351-861ceab3-6c27-4d10-864f-65d4f0750cb0.png">

See https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=7978%3A13686

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Harshit-Dandriyal** [comment]
Here :hand:

**Comment by leecalcote** [comment]
Thanks @Harshit-Dandriyal
