### ISSUE TITLE
[Blog] Post on evolution of mesheryctl docs section

### ISSUE THREAD

**Issue by alphaX86** [layer5io/layer5#2816]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** Evolution of mesheryctl docs 
**Topic:** Its all about the doc evolution of mesheryctl reference and how it's being changed to time
**Core points to convey in the post:** 
1. Explain about initial design of reference 
2. How design is revamped on reference index
3. How YAML is cut short to single file and eventually how Cobra CLI is used to generate pages

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Awesome.
