### ISSUE TITLE
[News]see more of our news card is going outside card

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [layer5io/layer5#2817]
**Description**

![Screenshot from 2022-05-20 19-13-47](https://user-images.githubusercontent.com/56961488/169541275-db552bf0-6a62-4812-b14e-29eef027c808.png)

**Environment:**
- Host OS: Linux(Ubantu)
- Browser: Chrome

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by SooditK** [comment]
Hii @Chadha93 Can I take up this issue?
