### ISSUE TITLE
[News] Intel, Layer 5 Announce MeshMark to Quantify Cloud-Native Performance

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2822]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the [Layer5 Newsroom](https://layer5.io/news).

**Article:**
- Title: Intel, Layer 5 Announce MeshMark to Quantify Cloud-Native Performance
- Link: https://www.itprotoday.com/performance-management/intel-layer-5-announce-meshmark-quantify-cloud-native-performance

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by vishal-codes** [comment]
I would like to add this article ! C

**Comment by leecalcote** [comment]
Thanks, @vishal-codes. 👍

**Comment by vishal-codes** [comment]
@leecalcote which image should I use for thumbnail?

**Comment by leecalcote** [comment]
@vishal-codes https://www.itprotoday.com/sites/itprotoday.com/files/styles/article_featured_retina/public/IT%20Pro_RGB_V2_0.png
