### ISSUE TITLE
[Community] Member Profile: Jerod Culpepper

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2826]
**Current Behavior**

@cpepper96 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @cpepper96 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: cpepper96
- Twitter: 
- LinkedIn: jerod-culpepper
- Link to profile picture: https://avatars.githubusercontent.com/u/80851353?v=4
- Badge(s): meshery

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by varunwho** [comment]
Hi @leecalcote can I work on this?

**Comment by asubedy** [comment]
Sure @varunwho go ahead 🚀

**Comment by varunwho** [comment]
Hi @cpepper96, for adding you into wall of members, could you please share a few lines about yourself (Bio).
Thanks!

**Comment by cpepper96** [comment]
@varunwho sure!
I am a recent CS graduate from CSU-San Marcos living in San Diego, CA. I'm interested in all things related to the cloud and containers. Contributing to Layer5 has been an incredible way to learn new topics and develop my technical skills outside of school. I hope to share my experience with students and grow the open source community at CSU-San Marcos. I'll be starting a new job as a software developer at SAIC where I'll be a part of their DevOps team and will continue to be a contributor for Layer5.
