### ISSUE TITLE
Responsive Issue: Adjust padding/margin of "Image Hub" text

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2840]
**Description**
On the main page, the following text is not responsive:

<img width="562" alt="Screen Shot 2022-05-27 at 4 01 17 PM" src="https://user-images.githubusercontent.com/7570704/170789108-48383214-c899-4c3d-9b89-6009ba3e2334.png">

**Expected Behavior**
Text should stay within container in small browser sizes.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by anarayner** [comment]
Can I please take this?

**Comment by asubedy** [comment]
Sure @anarayner go on 🚀

**Comment by kunalchhabra37** [comment]
I would Like to Work On this Issue

**Comment by Chadha93** [comment]
@prasanta10 were you assigned to this issue?  **No.** 

You made a quick PR that's good but  _not the right way  @anarayner was already assigned to this issue. 

Please do follow the code of conduct of the community and open source.

**Comment by prasanta10** [comment]
Sorry @Chadha93, I have closed the pr, I had already fixed the bug therefore I sent the pr without knowing it had been assigned. It was a fault in my part, I will make sure it won't happen again. Sorry @anarayner .

**Comment by Chadha93** [comment]
@prasanta10 No worries, thanks for the response, please reopen your PR, you have given efforts, we will accept it. 😊

**Comment by prasanta10** [comment]
@Chadha93 is it really okay?

**Comment by Chadha93** [comment]
> @Chadha93 is it really okay?

Yepp
