### ISSUE TITLE
[Resource] Lag in filter and search working simultaneously

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2844]
**Description**

https://user-images.githubusercontent.com/85789734/170950482-ef8b64eb-504e-415b-9532-a871f70dea07.mov

Both the search and filter components are working fine individually. However, there is a lag when the use is inter-mixed. Mostly on searching for a word and then applying/modifying the filters.

**Expected Behavior**
The working of filters and search together should be smooth.

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Lezette** [comment]
@debo19 can I work on this?

**Comment by debo19** [comment]
@Lezette I think @subhradwip01 and @Harshit-Dandriyal are already looking into this. You can take a look at any other [help-wanted](https://github.com/layer5io/layer5/labels/help%20wanted) issues.

**Comment by subhradwip01** [comment]
Issue is resolved by @kayceeDev ... thanks for your work...so closing the issue
