### ISSUE TITLE
[Learn] Add instructions for managed Kubernetes service in Learning Paths: Introduction to Service Meshes - Hands On

### ISSUE THREAD

**Issue by AnuragThePathak** [layer5io/layer5#2845]
**Current State:**
The instructions in the learning paths are for local Kubernetes services only. As a result, some of them don't work for managed Kubernetes services like AKS, EKS, GKE etc.

**Desired State:**
Provide the necessary instructions for completing the [Introduction to Service Meshes - Hands On](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes) Learning Path on managed Kubernetes services. At this moment, the Istio portion is expected to have the update, but having that in Linkerd is also welcomed.

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by sshiv5768** [comment]
Hey, @AnuragThePathak I want to work on this issue. Can i go with it?

**Comment by AnuragThePathak** [comment]
Hey @sshiv5768 you can work on it as there are no restrictions, but before that, please let me know if you have access to any of the major managed Kubernetes providers and if you have completed this path or not [Introduction to Service Meshes - Hands On](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes)
