### ISSUE TITLE
Rotational Call-to-Action Framework

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2848]
**Current Behavior**
The community produces any number of noteworthy projects and programs. The layer5.io/blogs and layer5.io/resources offer opportunity to embed a call-to-action (a promotional advert, if you will) letting site visitors and blog reader know of available resources.

**Desired Behavior**
Given these call-to-actions (CTAs) change over time, it is ideal that specific CTAs are not hardcoded into any give blog post, but are centrally configured so that they may be rotated in and out seasonally.

#### Implementation
1. Create three types (locations) of CTAs on the single article view: `image-only`, `full-width`, `bottom`. See mockup for dimensions and CTA attributes.
1. A rotational framework for quickly configuring which CTA will be shown.

#### Acceptance Criteria
1. Both blogs and resources collections support this rotational framework.
1. The CTAs should be responsive. See mockup for dimensions and CTA attributes

#### Mockup

![single blog page](https://user-images.githubusercontent.com/7570704/171293929-6a096879-4a4a-4eb6-9d44-8fc653efb582.png)

[Figma Reference](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=8161%3A13787)

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by srrathi** [comment]
Hey @leecalcote, If this issue is unresolved can I work on it ?
