### ISSUE TITLE
The URL could not found the content

### ISSUE THREAD

**Issue by Aisuko** [layer5io/layer5#285]
I saw the URL https://layer5.io/meshery/adapters on the [project](https://github.com/layer5io/meshery-nsm)   can not be accessed successfully. Not sure the page was down or other reasons.

**Comment by leecalcote** [comment]
We need to add a new page on layer5.io that lists out all of Meshery's adapters and describes their features. In the meantime, I've updated the URL in NSM adatper's repo to be https://meshery.layer5.io/docs/adapters/nsm

**Comment by leecalcote** [comment]
Good eye, @Aisuko. The hyperlink on the meshery-nsm repo has been updated to point to https://docs.meshery.io
