### ISSUE TITLE
Initial banner rotating automatically

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2853]
**Description**
The second banner seems to be loading almost immediately after the first banner. This behavior seems to be consistent in both Safari and Chrome.

https://user-images.githubusercontent.com/7570704/171494792-7edb7eaf-a5c4-4a37-91f2-52a35fd937fc.mov

**Expected Behavior**
Banner should not auto-rotate.

**Environment:**
- Host OS: macOS
- Browser: **Safari and Chrome**
---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Nikhil-Ladha** [comment]
Taken care of.

**Comment by leecalcote** [comment]
Thank you, thank you. 👏👏
