### ISSUE TITLE
Form Info is not retained when we click on `Previous Step` button on newcomers form

### ISSUE THREAD

**Issue by MukulKolpe** [layer5io/layer5#2859]
**Current Behavior**

https://user-images.githubusercontent.com/78664749/171510995-2dda2094-d0b2-42e5-8a62-495745b181e8.mp4

**Desired Situation**

The form information must be retained when we navigate to the previous step using `Previous Step` button on the [newcomers form](https://layer5.io/newcomers).

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Thank you, @MukulKolpe

**Comment by subhradwip01** [comment]
I would like to work on that issue...if it is not solved yet

**Comment by MukulKolpe** [comment]
Sure @subhradwip01, go for it. You can check out [Formik docs](https://formik.org/docs/overview) for reference.
