### ISSUE TITLE
[Blog]: SCA Wrap up blog post

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#2861]
This issue is created for the upload of the new article about She Code Africa's Contributhon Mentees' reflection on their project.

Here's the link to the written and reviewed article: https://docs.google.com/document/d/1vTqKlsqvOi3teEoU2bmPGUbLbjcDpfJb95Cob_9Yhkk/edit

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by mzoyinda** [comment]
Hi @Ruth-ikegah assign this to me

**Comment by Ruth-ikegah** [comment]
@mzoyinda any update on this?

**Comment by mzoyinda** [comment]
yes, here is a link to my pull request https://github.com/layer5io/layer5/pull/2872

**Comment by leecalcote** [comment]
Published and soon to be promoted....
