### ISSUE TITLE
[Hero] Responsiveness of first hero banner

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2868]
**Description**
Text is overlapped the two "5" cards, but should not be.

**Expected Behavior**
Text should be responsive - as large as possible without overlapping the graphics.

**Screenshots**
<img width="560" alt="Screen Shot 2022-06-06 at 6 21 57 PM" src="https://user-images.githubusercontent.com/7570704/172265130-c5de430a-3636-426d-9f8b-09bf1814d966.png">

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by VaibhavArora19** [comment]
I would like to work on this

**Comment by leecalcote** [comment]
Thanks, @VaibhavArora19 👍

**Comment by dike-goodluck-africa-prudential** [comment]
I would like to work on this

**Comment by kingebere** [comment]
i would love to work on this
