### ISSUE TITLE
Add meshery docker extension 

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#2870]
**Current Behavior**

Meshery docker extension is missing from the list

**Desired Situation**
Add meshery docker extension on [layer5.io/projects](https://layer5.io/projects)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Nikhil-Ladha** [comment]
But, it is a part of Meshery itself. Not a separate project 🤔

**Comment by YashKamboj** [comment]
@Nikhil-Ladha  @leecalcote told me to do it

**Comment by leecalcote** [comment]
@Nikhil-Ladha has a good point. I had wondered this myself, but figured that we would list it as some of the other projects are also sub-projects (e.g. SMI Conformance, Service Mesh Patterns ) like the Docker Extension is. I figure that we might as well toot our own horn and that we should point people to this easy deployment method of Meshery when we can. What do you guys think?
