### ISSUE TITLE
MeshMap: "Only w/Agent" card needs SVG for OPA logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2873]
---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by YashKamboj** [comment]
@leecalcote It is already an svg 😅

**Comment by leecalcote** [comment]
@YashKamboj, *sigh*. No, it isn’t. @debo19 please fix.
