### ISSUE TITLE
[Community] Member Profile: Oyin Dawodu and Ednah Akoth

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#2879]
**Current Behavior**

@mzoyinda and @Ed-Neema has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @mzoyinda and @Ed-Neema as a contributors and community members by creating a profile on https://layer5.io/community/members.

- Github: https://github.com/mzoyinda
- Twitter: https://twitter.com/oyindawodu
- Linkedin: https://www.linkedin.com/in/oyin-dawodu-989434b6/
- Profile picture: https://drive.google.com/file/d/1c7aoCjEjwP1XYBFaohz0U9_IiJ1qiC2j/view?usp=sharing

Github: @Ed-Neema
Twitter: edmucious
Linkedin: ednah-akoth-7515a0207
Profile picture: https://drive.google.com/file/d/1gUlOvQFQxm7H2lgIklDduWv_f8ykl5_l/view?usp=sharing 

A detailed explanation of how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by VaibhavArora19** [comment]
I can take this up!

**Comment by leecalcote** [comment]
Excellent, @VaibhavArora19
