### ISSUE TITLE
Add MeshMap to mobile menu

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2880]
**Current Behavior**
MeshMap is missing from the mobile menu

**Desired Behavior**
MeshMap should be the final item in the menu. It can optionally use different coloring to highlight it. 

---
**Screenshots / Mockups**
![3B5DD14E-4E13-4841-B2F5-C136115B682A](https://user-images.githubusercontent.com/7570704/172687029-c075bfc5-1f73-45a6-8bdd-f6d049488b45.png)

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by Santosh1176** [comment]
Hey, I would like to work on this.

**Comment by Santosh1176** [comment]
@leecalcote @Chadha93 Hi, could you please confirm, if this is the desired behavior on mobile screens?
The link leads to [MeshMap page](https://layer5.io/cloud-native-management/meshmap)
![layer5issue](https://user-images.githubusercontent.com/91916466/172818509-c62ca0f2-fd1f-48d0-8c4e-a54b180e904c.png)

**Comment by Chadha93** [comment]
@Santosh1176 Yes, this looks good.

**Comment by Chadha93** [comment]
Nope, please don't add it for large display/desktop mode only add it for mobile view. The Goodbye YAML button is for the MeshMap page.
