### ISSUE TITLE
[News] CNCF Adopts Service Mesh Performance Standard Established by Layer5

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2886]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the [Layer5 Newsroom](https://layer5.io/news).

**Article:**
- Title: CNCF Adopts Service Mesh Performance Standard Established by Layer5
- Link: https://vmblog.com/archive/2021/10/12/cncf-adopts-service-mesh-performance-standard-established-by-layer5.aspx

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Santosh1176** [comment]
Hi, can I take this up?

**Comment by leecalcote** [comment]
Sounds real good, @Santosh1176 👍
