### ISSUE TITLE
[Blog] Display published date in byline

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2887]
**Current Behavior**
In the single blog post view, there is no published date visible.

**Desired Behavior**
It would be nice to see the published date in the byline adjacent to Category and Author.

**Screenshots / Mockups**
<img width="1065" alt="Screen Shot 2022-06-08 at 7 09 20 PM" src="https://user-images.githubusercontent.com/7570704/172737793-e4612db1-9eea-4cd5-aeb1-67b406b44067.png">

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@StarTrooper08 that's not the concern of this feature request, which is to augment the single-post template to incorporate display of the date attribute of any given post.

**Comment by indraantoor** [comment]
I would love to work on this issue.

![Screenshot from 2022-06-10 00-16-50](https://user-images.githubusercontent.com/64259328/172921962-b5232c60-5af6-4f17-8bf8-dd9b6a1e2eb4.png)

Is this how the published date should look like in terms of style or CSS?

**Comment by StarTrooper08** [comment]
> @StarTrooper08 that's not the concern of this feature request, which is to augment the single-post template to incorporate display of the date attribute of any given post.

Ok so we have to fetch blog publish date from somewhere(api/database) and display it for every blog which are currently present and future blogs. Right!!

**Comment by Nikhil-Ladha** [comment]
Yes, @indraantoor

**Comment by indraantoor** [comment]
@Nikhil-Ladha Got it! I'll start working on it as soon as this issue is assigned to me, if it's free to take.

**Comment by Nikhil-Ladha** [comment]
Here you go, take the chance @indraantoor to earn more.

**Comment by indraantoor** [comment]
Thank You! @Nikhil-Ladha
