### ISSUE TITLE
[Docs] Link in Creating a Member Profile does not work.

### ISSUE THREAD

**Issue by VaibhavArora19** [layer5io/layer5#2892]
**Description**
The link provided in <a href="https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updatingcreating-a-community-member-profile">CONTRIBUTING.md</a> named as `Community member profile issue template` redirects to page with a status code of 500.

**Expected Behavior**
It should redirect to the desired page

**Screenshots**
<img width="960" alt="error" src="https://user-images.githubusercontent.com/82141868/172893903-f7d12714-b85b-44f3-87f2-d8ae80e8d252.png">

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by adithyaakrishna** [comment]
@VaibhavArora19 Do you want to work on this? 👀

**Comment by VaibhavArora19** [comment]
I am already working on something else and I've already been assigned 2 issues😅. Maybe we can assign this to someone else.

**Comment by leecalcote** [comment]
@Santosh1176?

**Comment by Santosh1176** [comment]
Sure!
