### ISSUE TITLE
[Projects] Docker Extension padding and alignment

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2901]
**Description**
<img width="1203" alt="Screen Shot 2022-06-10 at 12 35 25 PM" src="https://user-images.githubusercontent.com/7570704/173166379-f1e79b16-d915-4369-a6ac-ed620145e951.png">

**Expected Behavior**
consistent alignment and padding with other cards

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by YashKamboj** [comment]
@leecalcote i already made a pr for this and is merged!!! #2900
