### ISSUE TITLE
The link to Sign-off in Community Handbook

### ISSUE THREAD

**Issue by Santosh1176** [layer5io/layer5#2914]
**Description**

The link to [**Sign-off**](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) in Community handbook's [Contribution](https://layer5.io/community/handbook/contribution) section redirects to the beginning of CONTRIBUTION.md. 

**Expected Behavior**

The link should lead to *Signing-off on Commits* section of CONTRIBUTION.md page.

**Screenshots**

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Santosh1176** [comment]
Sure, I'll get it done. However, I had a small doubt. The contents of Sign-off in the Handbook and Contribution.md are similar. Hence to give more context about sign-off to new contributors, can this link redirect to [Github's DCO page](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)?

**Comment by prasanta10** [comment]
can I work on this?

**Comment by YashKamboj** [comment]
@Santosh1176 your suggestion makes sense , why don't you make a pr , redirect to [Github's DCO page](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) , @debo19 views??

**Comment by Santosh1176** [comment]
@YashKamboj @debo19 should I go ahead with this?

**Comment by Santosh1176** [comment]
> > @YashKamboj @debo19 should I go ahead with this?
> 
> Use the internal contributing guide link itself.

Sure, I'll link it to the correct section in Contribution.md. Any specific reason to link it there, though the content is similar? just curious to know.
