### ISSUE TITLE
Improve responsive design of text in Mega Menu

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2920]
**Current Behavior**

<img width="644" alt="Screen Shot 2022-06-17 at 10 19 40 AM" src="https://user-images.githubusercontent.com/7570704/174328451-76e1b58b-1dc4-4814-a429-4a1b6a7f4e16.png">

**Desired Behavior**
Ideally, left/right margin and padding is removed (or width is adjusted) so that text can fit the full width of the constrained space.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by subhradwip01** [comment]
@OloyedeTobi what's the update for that issue?

**Comment by arishmaurya** [comment]
if @OloyedeTobi is not working on this can i take up this issue ?

**Comment by subhradwip01** [comment]
> if @OloyedeTobi is not working on this can i take up this issue ?

If @OloyedeTobi doesn't reply by tonight... You can take the issue 😊

**Comment by eeshaanSA** [comment]
@subhradwip01 why cant I see this issue on layer5.io? Can you?

**Comment by subhradwip01** [comment]
> @subhradwip01 why cant I see this issue on layer5.io? Can you?

It will occur when your window size will be lesser than 1200px

**Comment by kayceeDev** [comment]
@OloyedeTobi What is the status of this issue? Have you made a PR yet? Do you have questions?
If you are still working on this please indicate.

**Comment by subhradwip01** [comment]
I guess @OloyedeTobi is not working on that issue.. @arishmaurya you can work on that issue

**Comment by arishmaurya** [comment]
@subhradwip01 thanks let me setup the project , if i need any help i will drop a message on slack or here on github

**Comment by legendarykamal** [comment]
@subhradwip01 can i take this up ⬆ as I see no PR s yet on this?

**Comment by subhradwip01** [comment]
@arishmaurya are you working on that issue?

**Comment by arishmaurya** [comment]
yes I'm working on this @subhradwip01  , @legendarykamal you can colaborate with me . I would love to have a team mate

**Comment by legendarykamal** [comment]
Yeah 😄 sounds nicee
 @subhradwip01 assign me too, will work with @arishmaurya

**Comment by subhradwip01** [comment]
@legendarykamal go ahead

**Comment by Nikhil-Ladha** [comment]
@arishmaurya @legendarykamal what's the current progress? Stuck anywhere?

**Comment by legendarykamal** [comment]
@arishmaurya can you open a PR of the changes you have done, I didnt wanted our works to get repeated hence was waiting for you 
@Nikhil-Ladha lets wait for an update from @arishmaurya or I will make a PR soon.

**Comment by Nikhil-Ladha** [comment]
Seems like @arishmaurya is not around.
@legendarykamal please go ahead and send a PR for the issue.

**Comment by rakshitgondwal** [comment]
Hey, is anyone still working on this issue?

**Comment by janvi01** [comment]
Hey, @Nikhil-Ladha I would like to work on this if available.

**Comment by subhradwip01** [comment]
Go ahead.. I hope you complete it
