### ISSUE TITLE
[Docs] slack.png is not rendering for its black color

### ISSUE THREAD

**Issue by bishal7679** [layer5io/layer5#2933]
**Description**

In community and contribution section of README.md, the slack.png is not rendering cause of its blackish color.

**Expected Behavior**
Want to change this slack.png into colourful slack.png

![Screenshot (151)](https://user-images.githubusercontent.com/70086051/175826061-8523515e-71f1-4ef4-b280-fecd337098f0.png)

**Screenshots**

![Screenshot (152)](https://user-images.githubusercontent.com/70086051/175826112-af35de0a-e13c-4168-8fa4-760fe18cb8b0.png)

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by bishal7679** [comment]
Can I go ahead with this issue?

**Comment by YashKamboj** [comment]
@bishal7679 Go Ahead!!

**Comment by bishal7679** [comment]
@YashKamboj Can you tell me why DCO error is coming in the PR?
Can you merge this PR?

**Comment by YashKamboj** [comment]
@bishal7679 have you made the pr from the github site itself?? , try by forking and cloning the repo and while commit add `-s` in the `git commit` command , https://layer5.io/community/handbook/contribution#Sign-off%20commits for reference

**Comment by bishal7679** [comment]
@YashKamboj yes! actually this repo is too big for cloning. that's why I have commited from github

**Comment by bishal7679** [comment]
@YashKamboj Ok then I will clone this repo and then make PR
Thanks!

**Comment by YashKamboj** [comment]
@bishal7679 i guess you can also signoff the commit from the site too, let me check it btw cloning the repo, would be easier for you while doing future contributions

**Comment by bishal7679** [comment]
@YashKamboj yes please check it if I can signoff the commit from the site too or not.
I will clone the repo from next time

**Comment by YashKamboj** [comment]
I see something like this while commiting

![Screenshot 2022-06-27 001155](https://user-images.githubusercontent.com/75125203/175829292-3773216e-6034-4949-86f4-8dcb3ca8db9b.png)

**Comment by bishal7679** [comment]
@YashKamboj yeap!
What can I do now?

**Comment by YashKamboj** [comment]
@bishal7679 The Sign off and propose changes button shows for everyone, so i guess try again, if it still shows DCO error then cloning might be the only option https://github.blog/changelog/2022-06-08-admins-can-require-sign-off-on-web-based-commits/

**Comment by bishal7679** [comment]
Okay! Thanks for helping @YashKamboj

**Comment by bishal7679** [comment]
@YashKamboj now you can check this PR.
