### ISSUE TITLE
[Feature] Integrations Collection

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2943]
**Current Behavior**
Meshery has any number of integrations with other technologies and that number will only grow. While we list the 10 or so service meshes that Meshery integrates with, however, there will be many, many others, like Kubernetes, SPIRE, Argo, Prometheus, Grafana, Jaeger, CloudEvents, and so on…

--> _Meshery needs a catalog of integrations for users to browse._

**Desired Behavior**
1. an `integrations` collection.
  1. integrations should be categorized.
1. a new `/cloud-native-management/meshery/integrations` page with integrations overview and having a sortable grid (or similar) perusable catalog of integrations. 
    1. Ideally, this is something less boring that a blocky grid of cards.
1. an individual page for each integration, describing the functionality of the integration.

**Inspiration**
Design inspiration can be taken from relevant solutions like:

1. https://www.bigpanda.io/integrations
1. https://www.datadoghq.com/product/platform/integrations/#all
1. https://slack.com/integrations
1. https://www.dynatrace.com/hub/
1. A honeycomb-style example:
![image](https://user-images.githubusercontent.com/7570704/176253337-06a57cd5-e8c2-48b5-9ecc-8d9f227244c3.png)

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by sahilsuman933** [comment]
@leecalcote could you please assign this issue to me. I really wanted to work on this issue.

**Comment by leecalcote** [comment]
Sounds good, @sahilsuman933 👍
