### ISSUE TITLE
Replace options[PNG] to svg in meshmap page

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [layer5io/layer5#2959]
![Screenshot from 2022-07-06 20-27-51](https://user-images.githubusercontent.com/56961488/177723351-5f2be056-6dff-403d-8909-fe9a9f401257.png)

**Expected Behavior**

The PowerUp Options  in meshmap page should be in svg instead of png.

**Environment:**
- Host OS: Linux(Ubantu).
- Browser: Chrome.

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Harshit-Dandriyal** [comment]
> @Harshit-Dandriyal Can you please confirm whether these four logos need to be replaced with svg? ![Screenshot (1)](https://user-images.githubusercontent.com/91916466/177722973-2c2bcc53-0df3-4f9f-993d-a275a50baff0.png)

Yes, These four

**Comment by Santosh1176** [comment]
Thank you @Harshit-Dandriyal can you assign this to me?

**Comment by Harshit-Dandriyal** [comment]
Try to find the above one though

**Comment by debo19** [comment]
@Santosh1176 you can just use the logo without the text as the image and place the text separately.

**Comment by Santosh1176** [comment]
> @Santosh1176 you can just use the logo without the text as the image and place the text separately.

The SVG images are including the text. I need to find a way to edit those.

**Comment by Harshit-Dandriyal** [comment]
> > @Santosh1176 you can just use the logo without the text as the image and place the text separately.
> 
> The SVG images are including the text. I need to find a way to edit those.

Try to edit Svgs, try to remove some of its paths, you can check your svg here https://www.svgviewer.dev/

**Comment by Santosh1176** [comment]
Working on this.

![opa2](https://user-images.githubusercontent.com/91916466/177795704-46216a1b-6fc1-42f0-aa5a-c970dac031df.svg)
![wasm3](https://user-images.githubusercontent.com/91916466/177795962-f1bf4312-fb00-4c39-b573-3389d2f8907b.svg)

**Comment by Harshit-Dandriyal** [comment]
cool @Santosh1176

**Comment by debo19** [comment]
@Santosh1176 I can help you with the icons if you don't have them already.
