### ISSUE TITLE
[Community] Member Profile: Harshit Dandriyal

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#2967]
**Current Behavior**

@Harshit-Dandriyal  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Harshit-Dandriyal  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Harshit-Dandriyal 
- Twitter: 
- LinkedIn: https://www.linkedin.com/in/harshit-dandriyal-98866419a/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@Harshit-Dandriyal Please do provide the link for your Twitter handle and profile picture.

**Comment by manikmmalhotra** [comment]
i can work on this @Chadha93

**Comment by manikmmalhotra** [comment]
@Harshit-Dandriyal can you please provide the details:
Photo url,
Bio,
Twitter Handle
