### ISSUE TITLE
[Site] Custom Embedded Video Player 

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#2968]
**Current Behavior**
Currently for adding/embedding video to the site we are just using <iframe> due to which its customization availability limits us. 

**Desired Behavior**
Use [gatsby-remark-embed-video](https://www.gatsbyjs.com/plugins/gatsby-remark-embed-video/?=video) plugin for sourcing a video. It will allow us to write custom components for videos such as controllers and thumbnail customization etc.

---
**Resources*
Do follow this resource and read the documentation before implementation:

- https://www.gatsbyjs.com/docs/how-to/images-and-media/working-with-video/
- https://www.gatsbyjs.com/plugins/gatsby-remark-embed-video/?=video

**Acceptence**

- The component should be reusable across the project.
- Should allow adding custom thumbnails as png/jpeg/svg.
- Let enable/disable controls over videos.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by manikmmalhotra** [comment]
@Chadha93 i would like to work on this

**Comment by a-muk** [comment]
Hello! Since no one has created a pull request till now on this issue, can I try this?

**Comment by manikmmalhotra** [comment]
@a-muk hello, actually i'm working on this one and it's almost complete i'm just creating a PR

**Comment by manikmmalhotra** [comment]
@Nikhil-Ladha my fault i'll complete this asap it's almost done.

**Comment by legendarykamal** [comment]
hi @Chadha93 let me jump on this one , new component sounds a good idea to me :)

**Comment by Chadha93** [comment]
> hi @Chadha93 let me jump on this one , new component sounds a good idea to me :)

Sure sounds good.

**Comment by Nikhil-Ladha** [comment]
@legendarykamal working on it?
If not, please remove your assignment

**Comment by legendarykamal** [comment]
@Nikhil-Ladha working on it, PR coming soon :)
