### ISSUE TITLE
[Community] Calendar page: Add Newcomers Welcome section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2979]
**Current Behavior**
A call to action (to join the community) is missing after the table of meeting information on this page - https://layer5.io/community/calendar#meetings.

**Desired Behavior**
Ideally, Newcomers Welcome section from the /community page is also added to the /community/calendar page after the table full of meeting details.

**Screenshots / Mockups**
<img width="1239" alt="Screen Shot 2022-07-27 at 3 34 35 PM" src="https://user-images.githubusercontent.com/7570704/181367126-5ec61851-ebfe-49e2-905b-7b84e0cf45c5.png">

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by legendarykamal** [comment]
I would like to work on this 🙂
