### ISSUE TITLE
Repository overview document is not accessible

### ISSUE THREAD

**Issue by nishantwrp** [layer5io/layer5#2985]
**Current Behavior**
The link to repository overview document mentioned here opens a google sign-in for layer5.io accounts.

https://github.com/layer5io/layer5/blob/7df4bef81b4d93cec10f755d52ea9219e8051b8e/src/sections/Community/Newcomers-guide/index.js#L123-L127

**Desired Situation**
The link should probably be changed to general version of the doc or something else like [this page](https://layer5.io/community/handbook/repository-overview).

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by legendarykamal** [comment]
hi @nishantwrp may i work on this?

**Comment by nishantwrp** [comment]
Sure @legendarykamal.

**Comment by legendarykamal** [comment]
@nishantwrp i dont observe these issues probably someone has already worked this out, considering pulling the latest branch.

**Comment by nishantwrp** [comment]
Oh yes, looks like @leecalcote already fixed this issue. We can close it.
