### ISSUE TITLE
[Meshery] Integrations: Add Prometheus, Grafana and Argo

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#2986]
**Current Behavior**

The Meshery has three more upcoming integration which has not been added to the [Integration Collection](https://layer5.io/service-mesh-management/meshery/integrations) page. 

**Desired Behavior**

- Prometheus, Grafana and Argo should be on the [Integration Collection](https://layer5.io/service-mesh-management/meshery/integrations) Page.
- These images should be an SVG file.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@Lezette, perhaps, an item of interest to you...

**Comment by abhiyant-10** [comment]
I would like to work on this issue.

**Comment by leecalcote** [comment]
@abhiyant-10, sounds great.

**Comment by moazzam07** [comment]
I would also like to work on this

**Comment by sahilsuman933** [comment]
@abhiyant-10 is already working on this issue 

> I would also like to work on this

**Comment by abhiyant-10** [comment]
Should I change the style of Openshift , Raspberry pi  and slack as  I see their colors are missing or are they kept in that way intentionally.

**Comment by sahilsuman933** [comment]
@abhiyant-10 They are intentionally there to denote the upcoming integrations.

**Comment by abhiyant-10** [comment]
I will make a PR  by EOD .

**Comment by Lezette** [comment]
Oh wow, I’m just seeing this now
