### ISSUE TITLE
Search Component not functional on Resources page

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#2989]
**Description**
When you use pagination and go to any other page other than `1`, the component fails to search and shows a blank screen even though there are articles matching the keyword.

https://user-images.githubusercontent.com/85789734/181833870-6a6d5928-ef8c-47ea-8db9-a2097f12d4e2.mov

**Expected Behavior**
The component should search on every page. Ideally, it should search through the entire collection of resources to match results.

**Environment:**
- Host OS: 
- Browser: 

---

[Optional] **Additional Context**

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@shivaylamba an opportunity....

**Comment by a-muk** [comment]
Hello! Can I work on this issue?

**Comment by debo19** [comment]
Go ahead @a-muk

**Comment by mihir2226** [comment]
Hi @a-muk , do you like to collaborate with me ?
