### ISSUE TITLE
[README] Dark mode support: Add light versions of logos

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2991]
**Current Behavior**
This repo's readme.md (https://github.com/layer5io/layer5#readme) assumes light mode visitors.

**Desired Situation**
Use GitHub's relatively new ability to [define light and dark mode images](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) in markdown for each of the logos.

Find light and dark mode flavors of each of the logos here: https://layer5.io/brand or in the shared, community drive.

---
#### Contributor Resources and [Handbook](https://layer5.io/community/handbook)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mihir2226** [comment]
Hey lee, I want to work on issue #2991

**Comment by leecalcote** [comment]
That'd be great, @mihir2226. 

More context - https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

**Comment by mihir2226** [comment]
Hi @leecalcote I accidentally send you a pull request for code but it needs little changes. So can I close my pull request  and then do that changes?

**Comment by leecalcote** [comment]
Alternatively, you can make changes and push more commits to this same branch and this PR will be automatically update with those changes (commits).

**Comment by mihir2226** [comment]
Hi, @leecalcote now all the images are changing according to the theme. can I close the pull request now?

**Comment by leecalcote** [comment]
Rather, what you want is for a maintainer to review, approve, and merge, I think.

**Comment by mihir2226** [comment]
@leecalcote yes exactly, i want they review and approve my code

**Comment by mihir2226** [comment]
Hii @leecalcote , I fixed the bug. But reviewer saying me to sign off pull request. Of a first commit I done. Actually it's file that I uploaded accidentally.

So I simply deleted that file and sign off. Is this okay now or I have to do something about it?

**Comment by leecalcote** [comment]
Link to the PR? Be sure to reference this issue in that PR. Yes, there are are DCO sign-off instructions in the failed build check. There will be `git` commands to execute. If you can't figure it out, it's not a big deal on that repo.

**Comment by mihir2226** [comment]
@leecalcote , it's showing that workload awaiting approval.

**Comment by leecalcote** [comment]
@mihir2226 sure. There's nothing to build, though.

**Comment by mihir2226** [comment]
@leecalcote can you review my code so it will be merged.

**Comment by leecalcote** [comment]
No, I'll await word from @Chadha93

**Comment by mihir2226** [comment]
okay sir
