### ISSUE TITLE
[Meshery] Integration: make video for each integration 

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#2995]
#### Current Behavior

Meshery supports integrations like dockers, Kubernetes, Minikube, SPIRE, Argo, Prometheus, Grafana, Jaeger, CloudEvents, etc.

To explain how Meshery works with these integrations. We need some volunteers who can make a video with each integration of video length ~ 30 secs. So, for now, you can include that video on this path src/assets/video/meshery-integrations-video/

E.g.: 

- https://calendly.com/integration/zoom
- https://calendly.com/integration/google-meet
- https://calendly.com/integration/typeform

You can check out the list of the integrations that meshery support by going to the [Integration page](https://layer5.io/service-mesh-management/meshery/integrations). These videos will be included in the upcoming individual Integration page. 

**Note:** You don't need to make all videos by yourself. You can work on 1-2 integration at a time. 

#### Desired Behavior

- Make a video about how it works with Meshery for each integration

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
@sahilsuman933 are we using any video making software for those animations ?

I would like to make one for docker.

**Comment by sahilsuman933** [comment]
It depends upon you, @legendarykamal, how you make the video. 

Sure go ahead.

**Comment by sahilsuman933** [comment]
@legendarykamal You can use this video for the intro https://layer5.io/service-mesh-management/meshery

**Comment by legendarykamal** [comment]
Thanks for the suggestion @sahilsuman933 I will look into it

**Comment by sahilsuman933** [comment]
Any update @legendarykamal?

**Comment by legendarykamal** [comment]
Yes Docker desktop setup done, 
have asked permission for access, 
will update you by evening

**Comment by legendarykamal** [comment]
hello @sahilsuman933 I have installed a new ubuntu + docker desktop for the video purpose.
Take a look and let me know if any changes are needed.
this is initial 40 sec.
[Screencast from 07-08-22 12:49:23 PM IST.webm](https://user-images.githubusercontent.com/95926324/183279970-5030f03a-267d-4909-9031-a2f3114e5cf3.webm)

**Comment by sahilsuman933** [comment]
@legendarykamal, it looks excellent. You need to do a few minor things like 

1. Only the Docker Desktop window should be visible, so crop the video. 
2. Remove the extra parts like when your desktop screen is visible, when you are searching for meshery. Also, remove the section when you are waiting for meshery to be installed on your desktop.
3. Make the video speed setting be 2x or 3x
4. Add account setup process in meshery

**Comment by legendarykamal** [comment]
ok by account setup you mean this ?
[mesherywithdocker.webm](https://user-images.githubusercontent.com/95926324/183280682-b0b9e5ff-1f28-40b3-b3be-bd8abe769bfd.webm)

**Comment by sahilsuman933** [comment]
@legendarykamal Yup!

**Comment by legendarykamal** [comment]
yeah done 
https://user-images.githubusercontent.com/95926324/183282497-fe65d993-6af5-46d3-b529-bcb904ff2a21.mp4

**Comment by legendarykamal** [comment]
this is a little slower than before 
https://user-images.githubusercontent.com/95926324/183282809-2dcb30e7-d67f-4911-b81e-0d966f81ff42.mp4
which one is better we can have it @sahilsuman933 :)

**Comment by sahilsuman933** [comment]
@legendarykamal Slower one looks great. Now add the intro part, and it will be all done.

**Comment by legendarykamal** [comment]
sure, I will add it up

**Comment by legendarykamal** [comment]
@sahilsuman933 here we go :100: 

https://user-images.githubusercontent.com/95926324/184277724-0516fe72-45af-4f39-bf42-d51705fa8b39.mp4

**Comment by sahilsuman933** [comment]
Nice work @legendarykamal

**Comment by legendarykamal** [comment]
thanks @sahilsuman933 your help made it in less time :+1:

**Comment by sahilsuman933** [comment]
###
