### ISSUE TITLE
[Performance] Ensure that text remains visible during font load

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2996]
**Current Behavior**
The layer5.io website receives low performance scores. There are a number of recommendations to consider in the report on https://web.dev/measure/?url=https%3A%2F%2Flayer5.io.

<img width="916" alt="Screen Shot 2022-08-01 at 11 27 48 AM" src="https://user-images.githubusercontent.com/7570704/182198277-b7189af7-07b9-4103-9bfe-c3375d546127.png">

**Desired Situation**
layer5.io uses custom fonts. While these fonts download, text should be show in readily available fonts already supported in browsers natively like `font-family: Verdana, sans-serif;`

See - https://web.dev/font-display/?utm_source=lighthouse&utm_medium=lr
How to avoid showing invisible text [#](https://web.dev/font-display/?utm_source=lighthouse&utm_medium=lr#how-to-avoid-showing-invisible-text)
The easiest way to avoid showing invisible text while custom fonts load is to temporarily show a system font. By including font-display: swap in your @font-face style, you can avoid FOIT in most modern browsers.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by manikmmalhotra** [comment]
hey @leecalcote can  i work on this ??

**Comment by YashKamboj** [comment]
@manikmmalhotra Go ahead!!
