### ISSUE TITLE
[Performance] Create performance issues for each of the recommendations from web.dev

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2997]
#### Description
Review the recommendations on https://web.dev/measure/?url=https%3A%2F%2Flayer5.io and open individual issues to have these fixed? 

#### Expected Behavior
Many new, well-documented GitHub issues should be created.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Related to https://github.com/layer5io/layer5/issues/2996

**Comment by leecalcote** [comment]
@YashKamboj complete this today.

**Comment by leecalcote** [comment]
@YashKamboj please tie-off the rest promptly.

**Comment by YashKamboj** [comment]
All done, (i guess), images are covered under the `<StaticImages>` , and i have opened issues for others

**Comment by deepeshaburse** [comment]
> All done, (i guess), images are covered under the `<StaticImages>` , and i have opened issues for others

Hey @YashKamboj, is this issue complete?

**Comment by leecalcote** [comment]
@deepeshaburse please unassign @YashKamboj, reopen, and add `issue/willfix` label.
