### ISSUE TITLE
[Discuss] Use Layer5 logo with dark lettering in mobile view

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#2998]
#### Description
The mobile view of discuss.layer5.io uses white lettering in the logo, causing it to be (essentially) invisible.

#### Screenshots
<img width="563" alt="Screen Shot 2022-08-01 at 1 59 18 PM" src="https://user-images.githubusercontent.com/7570704/182224022-7d82d65c-662c-4246-ae3f-3dc3cda00cee.png">

#### Environment:
- Host OS: macOS and iPhone
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" padding="0px" margin="0px" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Nikhil-Ladha you might be able to work through this one.

**Comment by mihir2226** [comment]
hi @Nikhil-Ladha , let me know if you stuck somewhere okay

**Comment by Nikhil-Ladha** [comment]
> hi @Nikhil-Ladha , let me know if you stuck somewhere okay

Haha, sure!
I will definitely let you know _if_ that happens.

**Comment by Nikhil-Ladha** [comment]
Should be updated now.
Also, @leecalcote I see we are using the `Layer5` logo's in mail digests and mobile view and not the `Layer5 | Discuss` logo, any specific reason? If not, I think it better to use the `Layer5 | Discuss` logos at all places in discuss.

**Comment by Nikhil-Ladha** [comment]
I have updated the images to `Layer5 | Discuss` at all places, let me know if that needs to be reverted.

**Comment by leecalcote** [comment]
@Nikhil-Ladha, mobile view looks great now. And, yes, I think use of the plain Layer5 logo elsewhere instead of the Discuss flavor was just an oversight (wasn’t for a reason). Thanks for taking care of this issue holistically. 😃
