### ISSUE TITLE
[Performance] Set an explicit width and height on image elements

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#3005]
**Current Behavior**

Low performance rating of layer5.io
**Desired Situation**

Set an explicit width and height on image elements to reduce layout shifts and improve CLS . [Resource](https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=lr#images-without-dimensions) 
List of images which needs dimensions:  
[On the home page]
National Institute of Technology Karnataka Icon
![Screenshot 2022-08-02 170523](https://user-images.githubusercontent.com/75125203/182365223-30ca734c-9580-42b3-a26a-d77abf2d5f1e.png)
UEM Icon
![Screenshot 2022-08-02 170601](https://user-images.githubusercontent.com/75125203/182365350-d0b79ae9-acb8-445c-9aec-d2cee8f7c97d.png)
UT Austin Icon
![Screenshot 2022-08-02 170651](https://user-images.githubusercontent.com/75125203/182365478-3a670f6b-2052-4ffa-8992-bbbdb5706fc8.png)
Open service mesh icon
![Screenshot 2022-08-02 170757](https://user-images.githubusercontent.com/75125203/182365641-8fdb601f-ad1b-400b-9c2f-b1f667fa160a.png)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by manikmmalhotra** [comment]
@YashKamboj can i work on this?

**Comment by YashKamboj** [comment]
Go ahead!! @manikmmalhotra

**Comment by leecalcote** [comment]
Do not specify height and width statically. Reserve the required space with [CSS aspect ratio boxes](https://css-tricks.com/aspect-ratio-boxes/).
