### ISSUE TITLE
Restore sitemap.xml for layer5.io

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3008]
#### Description
Sitemap.xml was previously available at [https://layer5.io/sitemap.xml](https://layer5.io/sitemap.xml). It's currently leading to a 404 error page and Sitemap.xml is not found.

#### Expected Behavior
Restore https://layer5.io/sitemap.xml. Refer to [gatsby plugin for sitemap](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/?=sitemap).

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
@debo19 can i work on this ??

**Comment by leecalcote** [comment]
@manikmmalhotra yes, please do. We'll ask others to jump in as well given the urgency of this issue.

**Comment by manikmmalhotra** [comment]
@leecalcote sure , i'll try to complete this asap
