### ISSUE TITLE
Mobile-friendly community buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#301]
**Description**
The set of buttons used for community resources are not responsive and overflow their container in mobile view.

**Expected Behavior**
These buttons should resize and be responsive.

**Screenshots**
<img width="501" alt="Screen Shot 2020-01-21 at 10 02 23 PM" src="https://user-images.githubusercontent.com/7570704/72992202-02984880-3db9-11ea-8259-e78e91bd1359.png">

**Comment by leecalcote** [comment]
@Nikhil-Ladha do you mind taking a look here?

**Comment by Nikhil-Ladha** [comment]
I knew this issue, and thought someone was already working on that so I didn't say anything. But if no one is then I can surely take this up!

**Comment by leecalcote** [comment]
Thank you, @Nikhil-Ladha. Please do. I think Madhu was going to attempt to fix previously, but has been absent for a few months.

**Comment by Nikhil-Ladha** [comment]
Ohh, then it's fine. I will take this up ;)

**Comment by ashiscs** [comment]
This issue is fixed and needs to be closed!!
