### ISSUE TITLE
[Performance] Image Optimization <img> to <StaticImages> in the handbook section

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#3014]
**Current Behavior**

The .png and .jpg images cause a lot of performance issues 
**Desired Situation**

Change `<img>` to `<StaticImagess>` for image optimization in the handbook section.  eg [PR](https://github.com/layer5io/layer5/pull/2597)  [StaticImagePlugin](https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/)
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by legendarykamal** [comment]
I would like to work on this @YashKamboj 
Image optimisation sounds good 🙂

**Comment by YashKamboj** [comment]
Go ahead!! @legendarykamal

**Comment by legendarykamal** [comment]
Yeaa! @YashKamboj  1 out of 3 just got completed 👌
