### ISSUE TITLE
[Performance] Image Optimization <img> to <StaticImages> in the Meshery page

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/layer5#3017]
**Current Behavior**

The .png and .jpg images cause a lot of performance issues
**Desired Situation**

Change  to for image optimization in the handbook section. eg https://github.com/layer5io/layer5/pull/2597 [StaticImagePlugin](https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/)
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Pavel-2004** [comment]
Hi, I would also like to help with this

**Comment by YashKamboj** [comment]
@Pavel-2004 Go Ahead!!

**Comment by YashKamboj** [comment]
@Pavel-2004 Update on the issue?, do you need any help with this issue?

**Comment by Jonathan-Foo** [comment]
Hi @YashKamboj, I would like to give it a try if @Pavel-2004 no longer wants too.

**Comment by Jonathan-Foo** [comment]
Hi @YashKamboj any updates?

**Comment by deveshXm** [comment]
Hi @YashKamboj  if no one is working on this issue then I would like to work on it.

**Comment by leecalcote** [comment]
@Jonathan-Foo’s comment must have been missed accidentally. Congrats on your graduation from frrecodecamp, @Jonathan-Foo 👍

**Comment by Jonathan-Foo** [comment]
That's all good, and thank you @leecalcote

**Comment by deveshXm** [comment]
i wanted to ask that do i need to replace the <img> with <staticImages> for all the components in "src/sections/Meshery". Also am i at the right Meshery folder. Just wanted to confirm this.

**Comment by Jonathan-Foo** [comment]
Hi @deveshXm,
Yes you have to replace img elements you find with Gatsby's StaticImage component, but don't do it if the image source is an .svg, because it will lower the quality. Yep, you are in the right folder.

**Comment by deveshXm** [comment]
@Jonathan-Foo I checked out your PR on a similar issue and i saw that you used constants or props for in eg: src={label1} for staticImages . However , in my case it was not working and i had to paste the whole url of image in the src and also as per the [Gatsby Image Plugin](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#staticimage) documentation, src must be type string. You're currently passing an object {label1}. And also the staticImages were not working for GIFs so i am not changing their tags.

**Comment by siddheshJungade** [comment]
I would like to git it a try for this issue?

**Comment by deveshXm** [comment]
@siddheshJungade i am already working on it

**Comment by toukirkhan** [comment]
Assign me

**Comment by toukirkhan** [comment]
Assign me

**Comment by avikt18** [comment]
hey @leecalcote I can work on this :smile:

**Comment by avikt18** [comment]
@leecalcote kindly review the PR :smile:

**Comment by leecalcote** [comment]
@avikt18, I'll entrust my review to @GaganpreetKaurKalsi.
