### ISSUE TITLE
Vulcan icon blends in the dark mode

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3018]
**Current Behavior**

In dark mode On service mesh landscape the icon blends with the background which doesnt look nice.

![image](https://user-images.githubusercontent.com/95926324/182632090-a7f90ef2-9f4e-41c2-b4aa-7280eba628cd.png)

**Desired Situation**

Making the icon more clear would make it better.
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by mihir2226** [comment]
change icon color or simply reduce font-wight, it might work.

**Comment by Prathamesh-Shanbhag** [comment]
Hey I would like to work on the issue!

**Comment by subhradwip01** [comment]
I guess it is the official color of this logo..so need not to change.. @Nikhil-Ladha once confirm it please

**Comment by Prathamesh-Shanbhag** [comment]
Even if that is the case, usually it is always better to have two color schemes of the same logo?
One that also works in the dark-mode!

**Comment by Nikhil-Ladha** [comment]
Yes, that should be the case @Prathamesh-Shanbhag but unfortunately Vulcan is not maintained anymore (correct me if I am wrong @leecalcote ) . So, we can leave the icon be as it is.

**Comment by DhirajGilda** [comment]
is this issue taken if not i would like to work on this @legendarykamal

**Comment by Nikhil-Ladha** [comment]
Actually, this issue is irrelevant.
Closing it now.

You can take a look around the projects for more such `good-firs-issues` @DhirajGilda :)
