### ISSUE TITLE
[Handbook] Frontend Projects: Add service-mesh-patterns to the list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3019]
#### Current Behavior
The list of frontend projects (https://layer5.io/community/handbook/repository-overview) in the community handbook is missing the new service-mesh-patterns project.

#### Desired Behavior
Add Service Mesh Patterns to the list of projects. 

- Site: https://service-mesh-patterns.github.io/service-mesh-patterns/
- GitHub: https://github.com/service-mesh-patterns/service-mesh-patterns
- Logo: Find here - https://layer5.io/company/brand

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
@leecalcote i can look into this

**Comment by leecalcote** [comment]
Awesome. Thank you, @manikmmalhotra 💪
