### ISSUE TITLE
Community buttons: tooltip hidden behind another section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#302]
**Description**
The z-index of the section neighboring the community buttons causes the rich tooltip to be hidden.

**Expected Behavior**
Community button tooltips should not be hidden.

**Screenshots**
<img width="626" alt="Screen Shot 2020-01-21 at 10 01 50 PM" src="https://user-images.githubusercontent.com/7570704/72992538-82beae00-3db9-11ea-8d77-9b5755b31be1.png">

**Comment by ashiscs** [comment]
@leecalcote sir, this issue is fixed i guess and needs to be closed!!

**Comment by leecalcote** [comment]
Thank you, @ashiscs
