### ISSUE TITLE
[Community] Member Profile: @alvinokafor

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3020]
**Current Behavior**

@alvinokafor has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@alvinokafor> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  @alvinokafor
- Twitter:  @retrosearth
- LinkedIn:  https://www.linkedin.com/in/alvin-okafor-05a4a91a1/
- Link to profile picture: https://avatars.githubusercontent.com/u/60660504?v=4
- Bio: I am a Front-End Engineer and Product Designer based in Port-Harcourt, Nigeria. I am passionate about user-centred design and developing web services that improve users' daily lives. When I'm not pushing pixels on the screen or writing code, I love to make beats as a music producer and play games.
- Location: Port-Harcourt, Nigeria

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by manikmmalhotra** [comment]
@Anita-ihuman i would like to work on this.

**Comment by leecalcote** [comment]
@manikmmalhotra this will be your fourth open assignment. Please complete your other open assignments promptly or remove assignment here, so that others can carry this forward in the meantime.
