### ISSUE TITLE
Cards not Shown Properly

### ISSUE THREAD

**Issue by manikmmalhotra** [layer5io/layer5#3022]
#### Description

below proudly maintaining and contributing the cards are not properly fitted on screen as shown in below image(edges of the image)
![Screenshot from 2022-08-04 02-30-41](https://user-images.githubusercontent.com/63007399/182711287-79310851-13dc-40de-adcb-f295fa524ccf.png)

#### Expected Behavior

cards should be inside the screen

#### Environment:
- Host OS: ubuntu
- Browser: brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
This behavior is by design.

**Comment by leecalcote** [comment]
Thanks for taking the initiative to point it out and have it fixed, though. Please carry-on. 👍
