### ISSUE TITLE
[Light Mode] Change Heading Color

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3024]
#### Description
<img width="1078" alt="Screenshot 2022-08-04 at 3 10 51 AM" src="https://user-images.githubusercontent.com/85789734/182728612-28b6deb9-3097-4ace-a409-e516ba38c009.png">

The heading on [layer5.io/newcomers](https://layer5.io/newcomers) is currently white in light mode.

#### Expected Behavior
It should be changed to the primary text color. Make sure to use the theme color and not hardcode.

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by beingnoble03** [comment]
@debo19 can i work on this?

**Comment by debo19** [comment]
@beingnoble03 go ahead
