### ISSUE TITLE
Picture slider not showing on Community page

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3025]
#### Description
<img width="1440" alt="Screenshot 2022-08-04 at 5 29 45 AM" src="https://user-images.githubusercontent.com/85789734/182736299-28d19b3b-f19e-4381-ba5b-96f12f49d612.png">
The slider is not visible currently.

#### Expected Behavior

https://user-images.githubusercontent.com/85789734/182736336-9b034b27-0c75-42f8-ac3e-1e75d41d6cfc.mov

Restore the Slider on [layer5.io/community](https://layer5.io/community)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Nikhil-Ladha upgrade related, perhaps?

**Comment by leecalcote** [comment]
@Harshit-Dandriyal not dark mode related?

**Comment by legendarykamal** [comment]
@Nikhil-Ladha If this isn't due to any recent upgrades then may I try to restore it?

**Comment by Nikhil-Ladha** [comment]
It is due to upgrade, I will be taking a look at it.

**Comment by legendarykamal** [comment]
Ok

**Comment by debo19** [comment]
Fixed in #3026
