### ISSUE TITLE
[Blog] Search not working on Blog page

### ISSUE THREAD

**Issue by subhradwip01** [layer5io/layer5#3031]
#### Description

After page no. `2`, searching anything it is showing blank page, though the blog with the keyword is present.
#### Expected Behavior

It should work for any page like in `1` and `2`
###
![Screenshot from 2022-08-04 21-57-48](https://user-images.githubusercontent.com/88609894/182902804-f1e2797e-d18e-4dfa-a800-0aa9fcd0819f.png)
# Environment:
- Host OS: Linux
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mihir2226** [comment]
Hi @subhradwip01, Can I work on it?

**Comment by subhradwip01** [comment]
Go ahead @mihir2226 ...
Once look into that issue #2989 .. she is also working with similar issue... you can collaborate with her
