### ISSUE TITLE
[Home] Add MeshMap project card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3032]
#### Current Behavior
On the main page of layer5.io, in the "Operate cloud native infrastructure with confidence." section.

#### Desired Behavior
Add a MeshMap project card to this section.

#### Screenshots / Mockups
<img width="1259" alt="Screen Shot 2022-08-04 at 2 37 02 PM" src="https://user-images.githubusercontent.com/7570704/182938070-55393585-147e-4991-a3b4-95a00485f810.png">

#### Implementation
1. Link to `/meshmap`.
1. Use MeshMap logo.2. 
1. Tagline: "Collaborative Cloud Native Management" 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by karnatisrinivas** [comment]
Hello @leecalcote  Can I work on this?

**Comment by mihir2226** [comment]
Hi @leecalcote , I would like to work on it, thus I'm good at working with cards.

**Comment by leecalcote** [comment]
@karnatisrinivas I missed your message earlier. Yes, please do. 👍

**Comment by leecalcote** [comment]
@karnatisrinivas, I was tardy on this assignment. Is this something that you'll be able to get to this weekend, do you think?

**Comment by karnatisrinivas** [comment]
Hello @leecalcote, Wasn't able to work on this task over the weekend. If anyone is ready to pick this up I would be happy to assist.
