### ISSUE TITLE
[Bug] Cannot select provider to login to interactive labs 

### ISSUE THREAD

**Issue by Rohith-Raju** [layer5io/layer5#3034]
#### Description
Cannot select meshery provider. All the providers are disabled in the dropdown which means we can't go to Meshery's HomePage 

#### Expected Behavior
User should be able to log in 

#### Screenshots

[screen-recorder-fri-aug-05-2022-09-09-36.webm](https://user-images.githubusercontent.com/55309324/182997765-4d1ec063-6979-49a0-9bf1-d1051adac586.webm)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mihir2226** [comment]
Hi @Rohith-Raju, I would like to work on this issue.

**Comment by Rohith-Raju** [comment]
Sure @mihir2226 all yours!!.

**Comment by Rohith-Raju** [comment]
@mihir2226 are you working on this issue?

**Comment by mihir2226** [comment]
Sorry but I don't able to figure out. How to solve this problem. Please Wait till tomorrow than you can assign it to somebody else.

**Comment by leecalcote** [comment]
@asubedy

**Comment by lavakush07** [comment]
- I think the issue is from the **katacoda** side  as they have stopped their free service. Because of it  all the providers has got disabled in the meshery learning path..

**Comment by asubedy** [comment]
Yes,@lavakush07  that's exactly the reason.

**Comment by deepeshaburse** [comment]
> Yes,@lavakush07 that's exactly the reason.

@asubedy do we need to close this issue?
