### ISSUE TITLE
[Community] Member Profile: Harkirat Singh

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3037]
**Current Behavior**

@harkiratsm has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @harkiratsm  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: harkiratsm
- Twitter: harkiratsm
- LinkedIn: harkiratsm 
- Link to profile picture: https://pbs.twimg.com/profile_images/1538715817860141056/lEdWAejx_400x400.jpg

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by 03amir** [comment]
@leecalcote  Can I work on this issue?

**Comment by leecalcote** [comment]
That’d be great.

**Comment by leecalcote** [comment]
A quick double-check - @harkiratsm, are you ok with this token of recognition?

**Comment by harkiratsm** [comment]
Yeah 😍 🚀
Thanks @leecalcote

**Comment by leecalcote** [comment]
Awesome. ✊

**Comment by 03amir** [comment]
@leecalcote  yes I am working

**Comment by leecalcote** [comment]
@03amir great. All that you need to do is fill in the markdown template...

**Comment by 03amir** [comment]
Ok, But  I am having a problem setting up locally.

**Comment by leecalcote** [comment]
@03amir no sweat. In fact, that's why I am pointing this out. All that you have to do is use the GitHub web UI to add a new file with markdown included. Use the member profile template provided.

If you're not able to get this by end of day Friday, let's free up this issue for another contributor to take it on, while you study / learn a bit more.

**Comment by 03amir** [comment]
@leecalcote  unassigning myself as you said, I still have problems to set up locally.

**Comment by legendarykamal** [comment]
@03amir no sweat follow the docs and reach out in slack , Members and I will be happy to help you .

@leecalcote meantime let me wrap this up ?

**Comment by leecalcote** [comment]
Thank you, @03amir. Let's get you onto another issue. The "help wanted" hyperlink in the README.md has many, many issues listed.

That'd be great, @legendarykamal
