### ISSUE TITLE
Subscribe form not dark mode friendly

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3038]
#### Description
<img width="1440" alt="Screenshot 2022-08-05 at 9 38 52 PM" src="https://user-images.githubusercontent.com/85789734/183120282-b431eb19-d7e3-4105-a1bd-cd9bf4c31926.png">

#### Expected Behavior
Make the subscribe card dark mode compatible on [layer5.io/subscribe](https://layer5.io/subscribe)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by divyanshkul** [comment]
Can I take this up?

**Comment by mihir2226** [comment]
i would like to solve it!!

**Comment by leecalcote** [comment]
Hi @divyanshkul, @mihir2226, I'm just seeing your messages. Great! Yes, first come, first serve, so to speak...

**Comment by mihir2226** [comment]
@leecalcote Yeah it's totally fair. @divyanshkul if you need any help I'm here.

**Comment by leecalcote** [comment]
Another `help wanted` - https://github.com/meshery/meshery/issues/5977

**Comment by leecalcote** [comment]
See all `help wanted` --> https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by mihir2226** [comment]
@leecalcote is it for me?

**Comment by leecalcote** [comment]
@mihir2226, yep.

**Comment by debo19** [comment]
@divyanshkul While you work on this, there is another issue here:

<img width="581" alt="Screenshot 2022-08-08 at 12 56 58 AM" src="https://user-images.githubusercontent.com/85789734/183311929-5f3878f6-e7fa-4adb-95fd-e743ed16a9a9.png">

The role should be the `primary` color in light mode. Will you fix this in the same PR?

**Comment by divyanshkul** [comment]
Hey, sure
Will fix this too @debo19 
@leecalcote I'll start working on the issue tonight, sorry about the delay

**Comment by leecalcote** [comment]
Thanks, @divyanshkul. Do send word if you think you'll complete this over the weekend.

**Comment by debo19** [comment]
@divyanshkul updates on this?

**Comment by Shubhcs01** [comment]
@debo19 @leecalcote If the issue still unresolved can I work on this?

**Comment by divyanshkul** [comment]
Hey @Shubhcs01 you can take it up, I am busy with my examinations right now

**Comment by Shubhcs01** [comment]
> Hey @Shubhcs01 you can take it up, I am busy with my examinations right now

okay, Thanks @divyanshkul . @debo19 @leecalcote can you please assign me this issue?
