### ISSUE TITLE
Extra Image on Footer 

### ISSUE THREAD

**Issue by manikmmalhotra** [layer5io/layer5#3040]
#### Description

when we surf layer5 site on a (1920 X 1080) screen there's a extra image in footer showing which isn't showing on normal screen 
#### Expected Behavior

Both the footer should be similar
#### Screenshots

on (1920 X 1080)
![Screenshot from 2022-08-06 15-16-33](https://user-images.githubusercontent.com/63007399/183243850-5b02463b-68f4-4522-a319-1c69e201b33d.png)
on (1366 X 768)
![Screenshot from 2022-08-06 15-19-43](https://user-images.githubusercontent.com/63007399/183243876-5151ccbc-b07c-48b5-a380-0ea484f3a020.png)

#### Environment:
- Host OS: Ubuntu 22.04
- Browser: Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by manikmmalhotra** [comment]
To recreate you can Zoom out(70%) on any screen and the extra image will popup

**Comment by mihir2226** [comment]
do you want images in both screen sizes or do you want to remove image from 1920 * 1080?

**Comment by mihir2226** [comment]
![Capture](https://user-images.githubusercontent.com/99991521/183280144-47651da8-8060-438b-a802-9c75fd7f4a3e.PNG)

@manikmmalhotra is this okay?

**Comment by Rohith-Raju** [comment]
@manikmmalhotra I think this is by design, making use of unused white space. Hence the image is visible on the wider screen

**Comment by manikmmalhotra** [comment]
oh i didn't had access to the figma designs for layer5io @Rohith-Raju , i just found a lil. odd

**Comment by leecalcote** [comment]
> @manikmmalhotra I think this is by design, making use of unused white space. Hence the image is visible on the wider screen

Correct.
