### ISSUE TITLE
Fix Broken Links

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3044]
#### Description
This [spreadsheet](https://docs.google.com/spreadsheets/d/10t0NSlxQVbLS7_uPEJIY6AmkFib-HHqqj_UvGovJL8Q/edit?usp=sharing) contains a list of all broken links throughout the website.

#### Expected Behavior
Fix all broken links. Make sure to use the gatsby `<Link>` tag for all internal links. The spreadsheet contains the correct urls that can be used to replace these broken links. If a correct url is not present, simply remove the `<Link>` or `<a>` tags.

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Pavel-2004** [comment]
Hey, can I be assigned this issue? I would be happy to help.

**Comment by mihir2226** [comment]
I wold like to help.

**Comment by debo19** [comment]
@Pavel-2004 you can take up 2-35.
@mihir2226 you can take 36-70.

**Comment by mihir2226** [comment]
@Pavel-2004 hi do you started working on the issue?

**Comment by Pavel-2004** [comment]
> 

Yes. Why?

**Comment by mihir2226** [comment]
@Pavel-2004 I am kind of stuck. I'm not able to figure out where the link is exactly. do you help me a little?

**Comment by Pavel-2004** [comment]
What link is it?

**Comment by mihir2226** [comment]
number 36

**Comment by mihir2226** [comment]
I just want to know how to figure out which file link is

**Comment by Pavel-2004** [comment]
> I just want to know how to figure out which file link is

@mihir2226 its in src/collections/programs/sca-contributhon

**Comment by AAYUSH-droid** [comment]
Hey can you assign this issue to me aswell!?

**Comment by debo19** [comment]
@Pavel-2004 @mihir2226 any progress here? This is a high priority issue, we need all broken links fixed as soon as possible.

**Comment by mihir2226** [comment]
Sorry but I kind a not able to fix it. Because of lack of understanding.

**Comment by debo19** [comment]
@mihir2226 In that case, let's pass your part of the assignment to @AAYUSH-droid. Take a look at any other [good-firt-issue](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22good+first+issue%22+) if you'd like. 
@AAYUSH-droid you can move forward with this.

**Comment by TarekArar99** [comment]
if this issue is still pending you can assing it to me

**Comment by debo19** [comment]
Yup sure @TarekArar99. Given that there was no response from @AAYUSH-droid or @Pavel-2004, let's keep this issue unassigned for now. @TarekArar99 you can raise a PR covering as many links as you can from the sheet.

**Comment by bhavyastar** [comment]
Hey @debo19 Can I work on this issue?

**Comment by Shubhcs01** [comment]
Hey, if this issue is still pending, can I work on this issue?
