### ISSUE TITLE
News: Meshery listed in top 3 service mesh developments

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#305]
**Current Behavior**
Meshery was recently identity in a news article citing the top 3 service mesh developments for 2020.

**Desired Behavior**
Add news article to [/news collection](https://github.com/layer5io/layer5/tree/master/collections/_news):

 - [The Top 3 Service Mesh Developments in 2020](https://thenewstack.io/the-top-3-service-mesh-developments-in-2020/)

---
**Resources:**
- [news template](https://github.com/layer5io/layer5/blob/master/collections/_news/2020-00-00-news-template.md)

**Comment by nupur-thakur** [comment]
@leecalcote  I am not sure what should be the permanent link for this news article.

**Comment by leecalcote** [comment]
@nupur-thakur good question. For now, you can either leave it blank or use "the-top-3-service-mesh-developments-in-2020".

**Comment by nupur-thakur** [comment]
Okay @leecalcote Sir, For now I am leaving it blank.

**Comment by leecalcote** [comment]
Thank you, @nupur-thakur.
