### ISSUE TITLE
[Community] Member Profile: Nishant Mittal

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/layer5#3054]
**Current Behavior**

@nishantwrp  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @nishantwrp  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @nishantwrp 
- Twitter: nishantwrp
- LinkedIn: nishantwrp
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@nishantwrp could you please provide a small bio, a location, and a link to a picture of yours 😃.

**Comment by legendarykamal** [comment]
I would like to make it for @nishantwrp 
mesheryctl guy 🙂

**Comment by nishantwrp** [comment]
Thanks for the recognition @warunicorn19. Also, @legendarykamal thanks for picking the task up 😄. Here's my info.

**Location**
Sangrur, India

**Picture**
![IMG_1394](https://user-images.githubusercontent.com/36989112/184252864-7bedc2d3-9397-44ab-938d-e500bf6158a9.jpg)

**Bio**
Nishant is a passionate software engineer, open source enthusiast and is studying computer science at IIT (BHU) Varanasi. He is currently contributing to Meshery and exploring DevOps, Cloud Native Computing and Distributed Systems. In the past, he has worked with various companies including Google and Gojek as a software engineering intern. Apart from that he is an active contributor to open source projects and has made significant contributions to projects like Oppia and Joplin. He has also been a part of programs like Google Summer of Code. Apart from programming, he likes to travel, party, and watch sitcoms.

**Comment by legendarykamal** [comment]
Thank you for the details @nishantwrp I will add this up :+1: 
PS:- IIT BHU is a great place.
