### ISSUE TITLE
[Community] Add Badges to Member Profile: Hersh Dillion

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3057]
**Current Behavior**

@hershd23 has been a consistent contributor to the SMP and Meshery projects.

**Desired Situation**
Let's recognize @hershd23 with the addition of the Service Mesh Performance and Meshery badges on his community member profile at https://layer5.io/community/members/hersh-dhillon

A detailed explanation on how to update a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by bensonOSei** [comment]
I'd like to work on this 😊

**Comment by leecalcote** [comment]
Thanks, @bensonOSei
