### ISSUE TITLE
Blog page accessibility could be improved

### ISSUE THREAD

**Issue by Olaleye-Blessing** [layer5io/layer5#3061]
**Current Behavior**
Poor accessibility due to heavy use of divs.

**Desired Situation**
I believe the accessibility of the blog page could be improved by using the right tags for the blog list.

![image](https://user-images.githubusercontent.com/70102539/184025644-a83a17a4-20b0-4f70-be08-e2505fe92d58.png)

At the bare minimum, the divs could be replaced with `ul`, `li`, `a`, `article`, and `header`

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by warunicorn19** [comment]
@Nikhil-Ladha @debo19

**Comment by Nikhil-Ladha** [comment]
Well, using `divs` in cards is not an issue. We don't mind keeping it as it is.
`ul`, `li`, doesn't makes sense for card designs.
`a` is used for links already.
`header` is used for page headers too.
So, I don't see any accessibility issues on the page.

**Comment by debo19** [comment]
> Well, using `divs` in cards is not an issue. We don't mind keeping it as it is. `ul`, `li`, doesn't makes sense for card designs. `a` is used for links already. `header` is used for page headers too. So, I don't see any accessibility issues on the page.

I agree. Closing this issue for now.
