### ISSUE TITLE
[Handbook] Add list of site maintainers to Repository Overview?

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3064]
#### Question:

Is the following list or a similar list desired or is it just more to maintain? It certainly doesn't do a good job of capturing the fact that any of of these people are maintaining any number of the different sites.

List:

Nikhil Ladha on the individual to tag in Figma comments on the http://service-mesh-patterns.github.io/service-mesh-patterns/ site and the [play.meshery.io](http://play.meshery.io/) site.

Aditya Chatterjee is the individual to tag on [meshery.io](http://meshery.io/) site.

Leonard Nwobodo on the [discuss.layer5.io](http://discuss.layer5.io/) site.

Debopriya Bhattacharjee and Gaurav Chadha, Nikhil Ladha Aditya Chatterjee is the person to tag for the [layer5.io](http://layer5.io/) site.

Aaditya Subedy for the :smp: [smp-spec.io](http://smp-spec.io/) and :nighthawk: [getnighthawk.dev](http://getnighthawk.dev/) site.

Adithya Krishna for the [docs.meshery.io](http://docs.meshery.io/) site.

_This is not a list representative of the work and sites that these MeshMates and maintainers span today._ 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
yes @leecalcote I am working on this as you said , will complete this by today.

**Comment by legendarykamal** [comment]
@leecalcote should we take community members view before implementing this ? i just reread and found that this was a more of a question :laughing:

**Comment by leecalcote** [comment]
@legendarykamal, yes, although, there's little harm in starting in the meantime.

I'm curious for @Nikhil-Ladha and @debo19's perspectives on the subject (and anyone else that would like to offer a perspective).

**Comment by Nikhil-Ladha** [comment]
I believe it is fine to go ahead in the meantime.
There won't be a denial for sure, and this idea would be welcomed with both hands wide open!

**Comment by debo19** [comment]
If we go ahead with this, we should also add the other areas to the list - MesheryCTL, Meshery UI, Adapters, etc

**Comment by legendarykamal** [comment]
yess @debo19 we will add that too in the list :smiley:

**Comment by legendarykamal** [comment]
@leecalcote @Nikhil-Ladha only site coloumn is enough or there is a need for repository coloumn too?
