### ISSUE TITLE
[UX] Update page design to incorporate MeshMark

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3065]
#### Current Behavior
The Service Mesh Performance (https://layer5.io/projects/service-mesh-performance) page is missing details of MeshMark.

#### Desired Behavior
Enhance https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2589%3A4349 to provide a summary of MeshMark. Find details at:

- https://smp-spec.io/meshmark
- https://layer5.io/blog/service-mesh-performance/meshmark-cloud-native-value-measurement

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Kanika637** [comment]
I would like to work on this @leecalcote

**Comment by Chadha93** [comment]
Here you go @Kanika637. Assigned.

**Comment by Kanika637** [comment]
I don't have permission to open the Figma file @Chadha93

**Comment by Chadha93** [comment]
> I don't have permission to open the Figma file @Chadha93

https://layer5io.slack.com/archives/C019426UBNY/p1659965954560819

**Comment by leecalcote** [comment]
Invite inside ^^

**Comment by Kanika637** [comment]
Got it @leecalcote 👍

**Comment by Kanika637** [comment]
Hey, @leecalcote, I have the changes in the Figma file:
 https://www.figma.com/file/WS9EQY8PY3oJAuvEkzFlCp/Layer5-Designs-(Copy)?node-id=5595%3A0

Kindly review it so that I can make further changes

**Comment by Nikhil-Ladha** [comment]
@Kanika637 update on the implementation?

**Comment by Kanika637** [comment]
@Nikhil-Ladha  The Figma design is done and will complete the implementation by evening today.

**Comment by Kanika637** [comment]
Actually, I was continuously getting errors while setting up the local environment for layer5.
