### ISSUE TITLE
[UX]New Sections on homepage needed

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3076]
#### Current Behavior
The layer5.io home page does not highlight features and functionality of the individual projects or tell a story of how they all tie together.

#### Desired Behavior

New section designs.

Ideally, functional overviews, feature highlights, user pain-points are all highlighted in new new sections on the home page highlighting Meshery and MeshMap features. 

#### Implementation
Brainstorm new section designs in Figma.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
I came here to update this but found it done already thanks @leecalcote

**Comment by leecalcote** [comment]
So much more needed here. This issue has not been fixed.

**Comment by legendarykamal** [comment]
@debo19 @warunicorn19 if you could sync me for those list of changes, it would be helpful .

**Comment by Mayaleeeee** [comment]
Okay.

Sorry, but I don't understand the Kubernetes stuff.

**Comment by legendarykamal** [comment]
No prob @Mayaleeeee happy that you showed interest , we have seen a couple of improvements including the meshmark and the grid . 
We will see the new k8s section added in near soon.

**Comment by eeshaanSA** [comment]
@legendarykamal updates?
