### ISSUE TITLE
[FAQ] Correcting the FAQ Section

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3079]
**Current Behavior**

None answers are correct and all the three are rather same.

![image](https://user-images.githubusercontent.com/95926324/184542526-7427c334-986a-455c-9909-78890d60b23c.png)

**Desired Situation**

Correct answers are needed to be filled in to Improve User Experience.
---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sourav-sharma7** [comment]
Hi @legendarykamal can I work on this issue

**Comment by legendarykamal** [comment]
Sure @sourav-sharma7 go ahead ⏩ 
You might want to discuss with @debo19 @warunicorn19 @sahilsuman933  of right things to put in the place 😃 .

**Comment by sourav-sharma7** [comment]
Thanks a lot @legendarykamal for the guidance.

**Comment by debo19** [comment]
@sourav-sharma7 Here you go:

1.  Correct the question: How **do*** Meshery ...
- Meshery is an extensible platform. Customize Meshery using any of its purpose-built extension points. 
- Take advantage of these extension points for working with different service meshes via adapters, different load generators and different providers. Use Meshery’s REST API or its GraphQL API both of which allow you to connect to any Kubernetes-native app.
- [Add button link to [Meshery Extensibility](https://docs.meshery.io/extensibility)].

2. 
- Become a Layer5 partner or simply submit an integration proposal,
- [Add button link to [Contact Us](https://layer5.io/company/contact)].

3. 
- Yes, as the cloud native management plane, Meshery provisions and manages the lifecycle of service meshes. 
- [Add button to [Run Meshery](https://layer5.io/service-mesh-management/meshery)]. 
However, we already have this question under "Meshery" faq, so let's remove it from there.

**Comment by bensonOSei** [comment]
I'd like to work this if it's still not fixed

**Comment by sourav-sharma7** [comment]
@bensonOSei Thanks for volunteering. The issue is almost solved I will be making a pr today.  Meanwhile you can checkout #3089 and #3060

**Comment by bensonOSei** [comment]
Alright, thanks
