### ISSUE TITLE
[Contact Form] Reduce response message height after form submission

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3081]
#### Description
<img width="1440" alt="Screenshot 2022-08-12 at 8 18 56 PM" src="https://user-images.githubusercontent.com/85789734/184553614-be635a20-656a-4117-9bf1-b70116414625.png">

#### Expected Behavior
The message should not take up this unwanted space. 

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Nikhil-Ladha** [comment]
Unfortunately, for the animation to be in place this seems like the only workaround. Couldn't gind any when I took a look earlier.
But, will wait if someone gas any ideas around it...

**Comment by roei111** [comment]
Hey @debo19, I would like to work on this issue! Can you assign it to me? :)

**Comment by Nikhil-Ladha** [comment]
Go ahead @roei111

**Comment by bhavyastar** [comment]
Hey, Can I work on this issue @Nikhil-Ladha?

**Comment by Nikhil-Ladha** [comment]
Sure @bhavyastar

**Comment by Shubhcs01** [comment]
@Nikhil-Ladha @debo19 If this issue still not resolved, Can I work on this?

**Comment by Shubhcs01** [comment]
> It's in WIP. I was stuck with one error. Now, it's resolved! I am working on this. @Shubhcs01

okay @bhavyastar no problem, if you need help can ping me.

**Comment by janvi01** [comment]
Hey, @Nikhil-Ladha I would like to work on this if availaible.

**Comment by Nikhil-Ladha** [comment]
Sure, @janvi01 go ahead with it.

**Comment by bhavyastar** [comment]
Yes, I am not working because some errors are coming. Earlier it was
resolved, but now again there are some errors are coming. I am working in
Ubuntu.
