### ISSUE TITLE
Replace outlined Meshery Operators logos with filled logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3085]
#### Current Behavior
The outlined version of the Meshery Operator logo is deprecated and needs to be replaced with the filled version of the logo. The filled version of the logo is available for in light and dark theme depending upon the need of the page/place it is being displayed.

#### Desired Behavior
Replace out outlined Meshery Operators logos with the filled Meshery Operator logo, using light or dark as appropriate.  Use .SVG format where possible.

#### Screenshots / Mockups
Do not use - Deprecated - Outlined
![meshery-operator-8ea331b554c6de098f49b7792c6a5080](https://user-images.githubusercontent.com/7570704/185142723-6bb16f57-d6bc-4b93-b3e4-9651dde95da9.png)

Use -
![meshery-operator](https://user-images.githubusercontent.com/7570704/185142378-23bc7854-4008-4db6-aa18-923c03e2da2f.svg)

![meshery-operator-white](https://user-images.githubusercontent.com/7570704/185148907-ff91e23b-6913-4409-9b93-8b84bf05621f.svg)

Find copies of the Meshery Operator logo in the `meshery-operator-brand-kit.zip` on layer5.io/brand

#### Implementation
Update the following locations and anywhere else the logo is found:

1. https://layer5.io/brand
1. https://layer5.io/community/handbook/repository-overview
1. https://docs.meshery.io/concepts/architecture/operator
1.
1.
1.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
Hi @leecalcote i have used light and dark mode logos before, can i complete this one ☝?

**Comment by sourav-sharma7** [comment]
Hello everyone can I give this a try

**Comment by leecalcote** [comment]
Thank you, gents. Assigning in sequence of response...

**Comment by legendarykamal** [comment]
Hey @sourav-sharma7 don't worry feel free to check more areas to contribute. 
like this one https://github.com/layer5io/layer5/issues/3086

**Comment by sourav-sharma7** [comment]
Thank you @legendarykamal will give try to solve those issues.

**Comment by leecalcote** [comment]
@legendarykamal here's another location to update - https://layer5.io/service-mesh-management/meshery/operating-service-meshes - the hero image on this page.

**Comment by legendarykamal** [comment]
> @legendarykamal here's another location to update - https://layer5.io/service-mesh-management/meshery/operating-service-meshes - the hero image on this page.

@leecalcote I found that https://layer5.io/service-mesh-management/meshery/operating-service-meshes already has the filled form logo in both light and dark mode 
![image](https://user-images.githubusercontent.com/95926324/185562247-2ee9990b-6a9d-4616-a212-76d4f451f12d.png)
![image](https://user-images.githubusercontent.com/95926324/185562291-54c9edde-70f3-4495-8dd4-3ef145bbdaed.png)

**Comment by leecalcote** [comment]
@legendarykamal light mode and dark mode - great - that is half of what is requested. The other half is to refresh the the logos given changes to the design.
