### ISSUE TITLE
[Programs] Add descriptions for 7 LFX 2022 Fall internships

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3086]
#### Current Behavior
This page https://layer5.io/programs/lfx doesn't have the description of the 7 upcoming internships.

#### Desired Behavior
Add the Meshery, SMP, and CNCF TAG Network internship descriptions --> https://github.com/cncf/mentoring/blob/main/lfx-mentorship/2022/03-Sept-Nov/README.md (5)

_Note: Two internships for MeshMap will be added under https://github.com/layer5io/layer5/issues/3087_

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Cypher1002** [comment]
we need to add more content? to the required page? more clearance needed to work on the project

**Comment by legendarykamal** [comment]
Hey @Cypher1002 a good amount of detail is provided but let me ease for u 
You just have to pick and drop the 5 necc details to https://layer5.io/programs/lfx 🙂

**Comment by Cypher1002** [comment]
I get it would work on that

**Comment by legendarykamal** [comment]
Sure go ahead! @Cypher1002

**Comment by legendarykamal** [comment]
hey @Cypher1002 any updates?

**Comment by Cypher1002** [comment]
It's been verry busy out of my hometown for approx 2 weeks i have forked nd work on it on my local system through the time it could be assigned to someone else...

**Comment by legendarykamal** [comment]
No sweat @Cypher1002 thanks for putting efforts in
