### ISSUE TITLE
[Programs] Add descriptions for 2 MeshMap LFX 2022 Fall internships

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3087]
#### Current Behavior
This page https://layer5.io/programs/lfx doesn't have the description of the 2 MeshMap LFX 2022 Fall upcoming internships.

#### Desired Behavior
Add the MeshMap internship descriptions --> https://github.com/cncf/mentoring/blob/main/lfx-mentorship/2022/03-Sept-Nov/README.md (2)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by deveshXm** [comment]
I'd like to work on this issue.

**Comment by deveshXm** [comment]
hi @leecalcote ,looks like the meshmap internship time line which you have attached to this issue is also not updated for 2022. 
For eg : https://github.com/cncf/mentoring/tree/main/lfx-mentorship/2022/02-Summer for the summer 2022 still has information for 2021 summer internship.
