### ISSUE TITLE
[Meshery] Add 4 Kubernetes logos to the "How It Works" animation

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3089]
#### Current Behavior
The animation on the https://layer5.io/service-mesh-management/meshery/operating-service-meshes page, only has service mesh logos.

#### Desired Behavior
It should include a set of four, randomly placed Kubernetes logos, too. Meshery is a Kubernetes manager.

#### Screenshots / Mockups
<img width="640" alt="Screen Shot 2022-08-18 at 7 53 02 AM" src="https://user-images.githubusercontent.com/7570704/185401086-be50ba8b-3b6a-4c35-8e3d-e47069a5b57b.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
wow this sounds pretty interesting, I will collaberate with other ux about the placement of the k8 logos.

**Comment by leecalcote** [comment]
The graphic that I created for this post might help with inspiration - https://layer5.io/blog/meshery/multi-cluster-kubernetes-management-with-meshery

**Comment by legendarykamal** [comment]
:thinking:  those big and small k8s certainly give a good feel

**Comment by leecalcote** [comment]
Perhaps, drop shadows should be added to the rest of the logos.

**Comment by alexisdsgns** [comment]
I will be happy to assist, I just need a set of tasks to follow through with.

**Comment by legendarykamal** [comment]
> I will be happy to assist, I just need a set of tasks to follow through with.

ok @alexisdsgns let's get going with this :)

**Comment by leecalcote** [comment]
@alexisdsgns, were you able to enhance the design with a few K8s logos?

**Comment by alexisdsgns** [comment]
No, I was not able to enhance the design @leecalcote

**Comment by legendarykamal** [comment]
No worries @alexisdsgns me and @DivineOrji are on it.

@leecalcote an update here-> https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN?node-id=9509:14672#256745741

**Comment by eeshaanSA** [comment]
Any Updates?
