### ISSUE TITLE
Just ask form not dark mode friendly moreover just ask button changes to white colour after it is clicked once

### ISSUE THREAD

**Issue by sourav-sharma7** [layer5io/layer5#3094]
#### Description

Just ask form dark mode appears only for a split second and then turn light mode moreover just ask button changes to white colour after it is clicked once
https://layer5.io/company/faq
#### Expected Behavior

Form must be dark mode friendly and the button must remain as original colour even after being clicked
#### Screenshots

![Screenshot from 2022-08-19 13-21-43](https://user-images.githubusercontent.com/78010922/185608507-0735366e-18a3-4f00-b80f-ca57bb6557dc.png)
![Screenshot from 2022-08-19 13-29-28](https://user-images.githubusercontent.com/78010922/185608549-96b19400-cf77-425d-a522-b01cff2fbe58.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sourav-sharma7** [comment]
@leecalcote what are your views on this issue. I would like to fix this myself can you please assign me this issue.

**Comment by sahilsuman933** [comment]
Go ahead and fix this issue @sourav-sharma7.

**Comment by sourav-sharma7** [comment]
Thanks a lot @sahilsuman933  for assigning.

**Comment by sourav-sharma7** [comment]
@Nikhil-Ladha I wanted to confirm should I leave the iframe form as it is and only fix the button issue.

**Comment by Nikhil-Ladha** [comment]
Yes
