### ISSUE TITLE
Copy button overlaps with the terminal code 

### ISSUE THREAD

**Issue by sourav-sharma7** [layer5io/layer5#3095]
#### Description

the copy to clipboard button is overlapping the command in the terminal
https://layer5.io/service-mesh-management/meshery/getting-started
#### Expected Behavior

Add an copy button as shown in the terminal in the meshery docs.
![Screenshot from 2022-08-19 17-02-50](https://user-images.githubusercontent.com/78010922/185609571-794e4254-579d-4c1d-a4e6-108e18138e86.png)
this is what we are trying to achieve.

#### Screenshots

![Screenshot from 2022-08-19 14-20-03](https://user-images.githubusercontent.com/78010922/185609604-313438a4-9cc2-4824-baa4-5631c73d19d3.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sourav-sharma7** [comment]
would like to fix this issue as I have worked with terminal animation before.

**Comment by eeshaanSA** [comment]
i would like to take this up if theres no-one currently working on this.

**Comment by sourav-sharma7** [comment]
Hi Eeshaan the issue is almost solved. I will be making a pr today. Thanks for volunteering.

**Comment by janvi01** [comment]
Hey, I would like to work on this if it's still available. @leecalcote

**Comment by Nikhil-Ladha** [comment]
Waiting for @sourav-sharma7 to reply, else I will assign the issue to you @janvi01

**Comment by sourav-sharma7** [comment]
Hi @Nikhil-Ladha . I am suffering from fracture. Please assign this issue to @janvi01.

**Comment by janvi01** [comment]
Thanks for assigning @Nikhil-Ladha.
I am getting an error while running Layer5 locally, Please can you help me out?
Here is the screenshot while doing `make site` -

<img width="1484" alt="Screenshot 2022-10-15 at 6 42 21 PM" src="https://user-images.githubusercontent.com/34344234/195988431-125b25b8-2073-43e5-b9d6-6ef2b148ae3c.png">

**Comment by eeshaanSA** [comment]
@janvi01 try clearing that cache from those files. It should work.

**Comment by janvi01** [comment]
Thanks @eeshaanSA , it works :)
