### ISSUE TITLE
Add more contrast between font color and select color

### ISSUE THREAD

**Issue by adarsh500** [layer5io/layer5#3097]
#### Description

There is no way to distinguish between the color of the font and the background color of the selected text in dark mode. This issue is present only on firefox.

#### Expected Behavior

Add more contrast between the font color and the selected background color.

#### Screenshots

<img width="1680" alt="Screen Shot 2022-08-20 at 8 47 54 PM" src="https://user-images.githubusercontent.com/73278151/185754087-c21945d8-46a5-4aff-b42c-54cb8f0a20a2.png">
<img width="1680" alt="Screen Shot 2022-08-20 at 8 47 47 PM" src="https://user-images.githubusercontent.com/73278151/185754078-7fd8b5b6-e4af-4c24-ac3b-d50edd459943.png">

#### Environment:
- Host OS: macos
- Browser: firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by adarsh500** [comment]
i'd like to take up this issue.

**Comment by sahilsuman933** [comment]
@adarsh500 Go ahead 🚀
