### ISSUE TITLE
[Meshery] Integrations: Oddity on hover

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3104]
#### Description

https://user-images.githubusercontent.com/7570704/185990389-6052718e-2c5b-4a5a-875b-b984c70871e2.mov

#### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sahilsuman933** [comment]
I am not facing this issue.  @leecalcote 


Host OS: Arch Linux
Browser: Google Chrome

https://user-images.githubusercontent.com/34382211/185996557-dcdbdd10-4b94-49d4-b3f7-6902232ee466.mp4

**Comment by leecalcote** [comment]
@sahilsuman933 ok, not an issue in Chrome, it seems. It is an issue in Safari, though. Perhaps, other browsers? Irrespective, we'll need to plan a fix: whether that is now or after use of the npm package for honeycomb (we're not using that, yet, right?).


@asubedy has access to Safari, if you need to partner with someone.

**Comment by sahilsuman933** [comment]
@leecalcote We are using the honeycomb package right now.

**Comment by leecalcote** [comment]
Mr. macOS, @asubedy.

**Comment by asubedy** [comment]
Ok it seems like the scaling the honeycomb on hover is causing the issue (the slight zoom when hover) are we willing to let go of this? If we remove the scaling there is no flickering

https://user-images.githubusercontent.com/51183483/187387127-80157851-2f28-4b74-b812-61bdc6f7d82b.mov

This is how it looks

// @leecalcote @sahilsuman933

**Comment by sahilsuman933** [comment]
I was also thinking about removing the scaling effect because I felt like it was unnecessary. So, from my side yeah we can remove that effect.  

// @asubedy

**Comment by Nikhil-Ladha** [comment]
While you are there can you also check the border issue while hovering on the honeycomb in dark mode. A s thin white border comes up around the honeycomb. For ease check the honeycombs on the edge of the grid.

**Comment by asubedy** [comment]
@Nikhil-Ladha I could not find it

https://user-images.githubusercontent.com/51183483/187429076-128c89fe-e495-42e5-ac23-ab73532d8b7a.mov

**Comment by Nikhil-Ladha** [comment]
Hmm 🤔 
Are you testing this after removing the scaling effect? If so, try it on the prod i.e, on layer5.io hosted site if you are able to notice it.
If not, try changing the browser.

If you can reproduce and remove the scaling effect, it is resolved. Then GREAT!
