### ISSUE TITLE
[IMPROVE] Change the background color of  bottom to top button

### ISSUE THREAD

**Issue by Himanshu664** [layer5io/layer5#3111]
#### Current Behavior
Background color of bottom to top button is black which is not suited in dark theme 
![Screenshot from 2022-08-23 19-48-01](https://user-images.githubusercontent.com/76220055/186183184-f4381e62-e18c-420d-ae59-cbf8116528f0.png)

#### Desired Behavior
Background color should be flexible to support both dark and light theme maybe grey.

### Environment:
Host OS: Ubuntu 22.04
Browser: Chrome

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
@leecalcote can you assign me this issue

**Comment by legendarykamal** [comment]
@Himanshu664 are you going with the design scheme decided upon for the dark mode?

**Comment by Himanshu664** [comment]
No I Just change the background-color To Grey or anything else whichever suits both Dark and light Theme

**Comment by Himanshu664** [comment]
@legendarykamal Any suggestions

**Comment by legendarykamal** [comment]
To me It looks good slightly greyish type and looks good in both the modes.

![Screenshot from 2022-08-29 07-59-28](https://user-images.githubusercontent.com/95926324/187111337-8709a022-8349-4b32-8f38-4da5f85bba45.png)

Its already grey I  think @Himanshu664 
![image](https://user-images.githubusercontent.com/95926324/187111457-e0add0d4-282d-4f94-b4ac-1f7e73f043ea.png)

**Comment by Himanshu664** [comment]
So what colour I should choose @legendarykamal

**Comment by Nikhil-Ladha** [comment]
I don't see a need to change the color of the button. It's the "Charcoal Green" color and looks fine in both the modes.

Closing out this issue :)

**Comment by legendarykamal** [comment]
agreed with @Nikhil-Ladha :100:
