### ISSUE TITLE
[UI] Change Text and Image alignment

### ISSUE THREAD

**Issue by subhradwip01** [layer5io/layer5#3112]
#### Current Behavior

Currently, for mobile view or small screen view in [docker extension page](https://layer5.io/docker-extension-meshery), the feature section is not properly aligned
#### Desired Behavior

For mobile or small screen view, the image should come first and then the relevant text. (See the large screen view, to know which text is for which image)
#### Screenshots / Mockups

Current
![Screenshot from 2022-08-23 19-13-09](https://user-images.githubusercontent.com/88609894/186229907-9c9cf747-9c16-4fd7-8db3-239b99e5fd2d.png)

Mockup for Desired behavior
![Group 2](https://user-images.githubusercontent.com/88609894/186232605-3c2e324b-09e2-4482-982d-ff728d7bf9b1.png)

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Jonathan-Foo** [comment]
Hi @subhradwip01, Could I please work on this issue?
