### ISSUE TITLE
[Learn] Image Alignment

### ISSUE THREAD

**Issue by Shubhcs01** [layer5io/layer5#3116]
**Current State:**

![Screenshot 2022-08-25 214737](https://user-images.githubusercontent.com/81324145/186717660-ea8b3ebc-6c30-4733-9b56-e686277f35e6.png)

Image not aligned and overlap with text
--------------------------------------------------------------------------------------------------------------------------------------

**Desired State:**

![Screenshot 2022-08-25 214615](https://user-images.githubusercontent.com/81324145/186717677-3d859abc-fc3b-4b22-8e94-9b14574e369a.png)

Suggested UI
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Check out the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Shubhcs01** [comment]
Can I  work on this issue?

**Comment by sreekeshiyer** [comment]
May I work on this?

**Comment by leecalcote** [comment]
This is something of an urgent item, yes, please do proceed. 👍

**Comment by leecalcote** [comment]
Do be aware of the existing effort to fix - https://github.com/layer5io/layer5/pull/3106.

**Comment by Shubhcs01** [comment]
I'm new to open source and I'm not able to find the exact location of the directory, Can anyone please help?
