### ISSUE TITLE
[ReadMe]  meshery-operator logo not visible in light mode

### ISSUE THREAD

**Issue by Shubhcs01** [layer5io/layer5#3117]
**Description**

meshery-operator logo not visible in light mode

**Screenshots**

![Screenshot 2022-08-25 215957](https://user-images.githubusercontent.com/81324145/186721257-b69dc56c-209b-4936-806d-6bceafbf9c55.png)

**Enviroment:**
- Host OS: Windows
- Browser:  Brave

---

---
**Contributor Resources**

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

**Comment by legendarykamal** [comment]
This is due to a recent change by me , let me fix this.

**Comment by Shubhcs01** [comment]
I already fixed it, Can I send PR?

**Comment by legendarykamal** [comment]
@Shubhcs01 though this is still incomplete , we wanted the light mode to be shown in dark mode. Can you improve that?

**Comment by Shubhcs01** [comment]
> Sure @Shubhcs01 :) , though this is still incomplete , we wanted the light mode to be shown in dark mode. Can you improve that?

But the logo is also visible in dark mode as light wallpaper in my forked project with the same code which I changed.

here's screenshot
![Screenshot 2022-08-26 014553](https://user-images.githubusercontent.com/81324145/186760204-8bd12fb8-7bc5-42b6-9a7c-d561c7cfad21.png)

Sorry if I missed something. Can you please explain a little more?
