### ISSUE TITLE
Dark Mode support for CloudNativeManagement Section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3122]
#### Description
The Meshery Integrations section still needs some content updates, but it has been placed onto the site home page a little early anyway. A copy of the `Statement` component has been made and is called `CloudNativeManagement`. 

The `CloudNativeManagement` section on the home page needs to have dark mode support with the font colors and anchor tag behavior.

#### Screenshots
<img width="1115" alt="Screen Shot 2022-08-29 at 7 24 52 PM" src="https://user-images.githubusercontent.com/7570704/187321703-12781774-c089-4eee-a456-0f739a8d9384.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Hi @Nikhil-Ladha, @debo19, will either of the two of you help me in tying off this refactoring on the home page, pretty please?

**Comment by Nikhil-Ladha** [comment]
Sure, will take a look at this ASAP.
