### ISSUE TITLE
[Meshery] Improve  Argo and Raspberry Pi Icon

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#3123]
#### Current Behavior

If we visit the [Meshery Integration Collection](https://layer5.io/cloud-native-management/meshery/integrations) page, we will find that Argo and Raspberry pi icon doesn't look that good. If we can improve the icon somehow, then it will be great.

#### Desired Behavior

- Improve the design Argo and Raspberry Pi icon for the Integration Collection page.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
I want to work on this issue

**Comment by sahilsuman933** [comment]
Sure, Go ahead @Himanshu664

**Comment by Himanshu664** [comment]
@Shubhcs01 I am trying to get the svg images of those icons but I couldn't find yet

**Comment by Shubhcs01** [comment]
> @Shubhcs01 I am trying to get the svg images of those icons but I couldn't find yet

Here-> 
src\sections\Meshery\Meshery-platforms\supported-icons\raspberry-pi.svg
\src\assets\images\service-mesh-icons\argo_cd.svg

**Comment by Himanshu664** [comment]
@sahilsuman933 Please Review
