### ISSUE TITLE
[Meshery] Improve upcoming Integration design

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#3124]
#### Description

The [Meshery Integration Collection](https://layer5.io/cloud-native-management/meshery/integrations) page currently shows both the working and in-production integration. To differentiate between those two we use White and Light slate gray background color. It will be great if we could do something and improve the design for the upcoming Integration.

#### Expected Behavior

- Improve the design for the upcoming Integration

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Swapping labels. It'd be good to point this out as a UX issue in the #newcomers channel.

**Comment by aaqilrk** [comment]
Hey, @leecalcote I would like to work on this.

**Comment by sahilsuman933** [comment]
Sure go ahead @aaqilrk

**Comment by Shubhcs01** [comment]
Hey @aaqilrk if this issue not resolved, I also want to help?

**Comment by aaqilrk** [comment]
Hey @Shubhcs01, I have nearly resolved this issue. We can work together on something else 😄

**Comment by aaqilrk** [comment]
Hey @sahilsuman933, is this design any better or further changes are required?

<img width="939" alt="Screenshot 2022-08-31 at 11 16 54 AM" src="https://user-images.githubusercontent.com/75661314/187603471-07c7771a-d8ad-415f-82ca-f915cf550a77.png">

**Comment by Shubhcs01** [comment]
> Hey @sahilsuman933, is this design any better or further changes are required?
> 
> <img alt="Screenshot 2022-08-31 at 11 16 54 AM" width="939" src="https://user-images.githubusercontent.com/75661314/187603471-07c7771a-d8ad-415f-82ca-f915cf550a77.png">

@aaqilrk In my persp I guess the grayscale color looks better for Inprogress Icons 🤔, @sahilsuman933 your opinion?

**Comment by aaqilrk** [comment]
> > Hey @sahilsuman933, is this design any better or further changes are required?
> > <img alt="Screenshot 2022-08-31 at 11 16 54 AM" width="939" src="https://user-images.githubusercontent.com/75661314/187603471-07c7771a-d8ad-415f-82ca-f915cf550a77.png">
> 
> @aaqilrk In my persp I guess the grayscale color looks better for Inprogress Icons 🤔, @sahilsuman933 your opinion?

<img width="918" alt="Screenshot 2022-08-31 at 11 45 06 AM" src="https://user-images.githubusercontent.com/75661314/187607050-658641a3-cceb-42f6-838a-941f875ea5f4.png">

@Shubhcs01 The grayscale makes it difficult to identify the icons 😅, do you have any other suggestions 😄

**Comment by sahilsuman933** [comment]
It looks good, @aaqilrk, but I know you can do even better. Why don't you post your design on the website channel on slack and ask for reviews?

**Comment by aaqilrk** [comment]
> It looks good, @aaqilrk, but I know you can do even better. Why don't you post your design on the website channel on slack and ask for reviews?

That is a wonderful idea, thank you 😄

**Comment by aaqilrk** [comment]
@sahilsuman933 I didn't get any feedback for the new design could you suggest any changes

**Comment by sahilsuman933** [comment]
I don't have any suggestions but I feel like there is something missing in the design. It doesn't give the vibe of upcoming integration.  

Look for more design inspiration through dribbble or any other websites. I am sure you will be able to do better than this.

// @aaqilrk

**Comment by aaqilrk** [comment]
> I don't have any suggestions but I feel like there is something missing in the design. It doesn't give the vibe of upcoming integration.  
> 
> Look for more design inspiration through dribbble or any other websites. I am sure you will be able to do better than this.
> 
> // @aaqilrk 

I will look into it. Thank you 😊

**Comment by sahilsuman933** [comment]
@Shubhcs01, would you like to take this issue?

**Comment by Shubhcs01** [comment]
> @Shubhcs01, would you like to take this issue?

Yeah sure @sahilsuman933 I'm not very good at UI designs but I'll try my best 🙂

**Comment by AbhishekTiwari23** [comment]
If it is still pending, then I would like to take it.

**Comment by sahilsuman933** [comment]
Sure, go ahead @AbhishekTiwari23

**Comment by AbhishekTiwari23** [comment]
> Sure, go ahead @AbhishekTiwari23

Thanks, @sahilsuman933, for assigning me. I will respond as soon as possible.

**Comment by AbhishekTiwari23** [comment]
> Sure, go ahead @AbhishekTiwari23



> Sure, go ahead @AbhishekTiwari23

Hello @sahilsuman933, sir, you assigned me this task yesterday. I thought about specific changes, and after all, I concluded that we could only change the colour of the inactive cards. I decided to give a red hover effect with some styling, but these do not contain links, so I can't do that. So please let me know if I should change the colour! I am waiting for your suggestions. Please let me know so that I can make the first PR for Layer5

**Comment by sahilsuman933** [comment]
Before the PR, can you show me some sample @AbhishekTiwari23?

**Comment by sahilsuman933** [comment]
@NPDebs, would you like to work on this issue?

**Comment by richardnikolas** [comment]
> @sahilsuman933 Sure. I'm sure @richardnikolas and I can handle it. 🌝

I would love to help 💃

**Comment by sahilsuman933** [comment]
You need to improve the design of the upcoming integration design. 

// @NPDebs @richardnikolas

**Comment by UtkarshMishra12** [comment]
@NPDebs @richardnikolas Please update

**Comment by Oghene-kevwe** [comment]
Hello, I'd like to work on this
