### ISSUE TITLE
[Community] Member Profile: Deepesha Burse

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3144]
**Current Behavior**

@deepeshaburse  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @deepeshaburse  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @deepeshaburse 
- Twitter: [3007Burse](https://twitter.com/3007Burse)
- LinkedIn: [deepeshab](https://www.linkedin.com/in/deepeshab/)
- Link to profile picture: https://drive.google.com/file/d/1aCPVhjT-5vX5Jv8wnKOjtDC42YI13eTD/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
@deepeshaburse Can you please provide a bio for the member profile?

**Comment by Jonathan-Foo** [comment]
Hi @debo19, could you please assign me this issue.

**Comment by Jonathan-Foo** [comment]
Thank you @sahilsuman933

**Comment by Jonathan-Foo** [comment]
Hi @SufyaanKhateeb, this has already been assigned to me.
