### ISSUE TITLE
[Community] Member Profile: Sahil Suman

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3145]
**Current Behavior**

@sahilsuman933  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @sahilsuman933  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sahilsuman933 
- Twitter: [sahilsuman880](https://twitter.com/sahilsuman880)
- LinkedIn: [sahilsuman](https://www.linkedin.com/in/sahilsuman/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
@sahilsuman933 Can you please provide your bio and a link to your profile picture here?

**Comment by legendarykamal** [comment]
Hi, @debo19 I would like to take this one 👍

**Comment by Shubhcs01** [comment]
I'm interested in this issue

**Comment by legendarykamal** [comment]
@Shubhcs01 there are 4 , pick any 1 else 😂

**Comment by Shubhcs01** [comment]
> @Shubhcs01 there are 4 , pick any 1 else 😂

Oh, my bad 🥲 Thanks, I picked another one😂

**Comment by sahilsuman933** [comment]
Thank you, @legendarykamal, for taking this issue. Here is my bio `I'm a student pursuing Computer Engineering at the Vellore Institute of Technology (VIT). I'm a passionate learner who's always willing to learn and work across technologies and domains. I love to explore new technologies and use them to solve real-life problems.` 

Here is my profile picture url: https://drive.google.com/file/d/1gPz4jzaSApCQuoWsZ-gV2Kmea-UvD3yc/view?usp=sharing
