### ISSUE TITLE
[Community] Member Profile: Alexis Abakasanga

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3146]
**Current Behavior**

@alexisdsgns has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @alexisdsgns as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @alexisdsgns
- Twitter: [sanchezways](https://twitter.com/sanchezways)
- LinkedIn: [alexisabakasanga](https://www.linkedin.com/in/alexisabakasanga/)
- Link to profile picture: https://drive.google.com/file/d/1ybm0AEvGt82a_M664PJ_ZOnG0lDS7HpU/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by debo19** [comment]
@alexisdsgns can you please provide a bio for your member profile?

**Comment by Shubhcs01** [comment]
@debo19 can I work on this issue?

**Comment by debo19** [comment]
Sure @Shubhcs01

**Comment by chandu-jadhav** [comment]
can I work on this issue?

**Comment by Shubhcs01** [comment]
Hi, @chandu-jadhav I'm working on this issue. But you can look for other good first issues.

**Comment by alexisdsgns** [comment]
Yes, I would love to provide a bio.

I am a Product Designer using Figma to create clean and usable designs backed by data for digital products. I love reading, contributing to Open Source, and learning. I enjoy my time here at Layer 5 and looking forward to becoming a positive force in the Tech ecosystem.

@debo19 @Shubhcs01

**Comment by Shubhcs01** [comment]
@debo19 done 👍 please review it.
