### ISSUE TITLE
[Community] Member Profile: Cyrine Gamoudi

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3147]
**Current Behavior**

@CyrineG has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @CyrineG  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @CyrineG 
- Twitter: 
- LinkedIn: [cyrine-gamoudi](https://www.linkedin.com/in/cyrine-gamoudi)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by aaqilrk** [comment]
Hey, I would like to work on this issue 😊

**Comment by debo19** [comment]
@CyrineG if you could please provide a bio and a profile picture, that'd be great 😄

**Comment by CyrineG** [comment]
@debo19 here they are :3
bio: "I am a software engineer, opensource enthusiast who is also fascinated by microservices and cloud native ecosystems. Driven by curiosity and interest, I am constantly learning new things. "
pic:[ here](https://drive.google.com/file/d/1h4VqU6KHH8UQ5lLBtn6XJFQJLKay-XG5/view?usp=sharing )

**Comment by aaqilrk** [comment]
@CyrineG Thank you, I'll get to it 🤗

**Comment by abhiyant-10** [comment]
Can I take this issue in case it is open

**Comment by debo19** [comment]
Sure @abhiyant-10

**Comment by abhiyant-10** [comment]
@CyrineG Please give the permission to view picture

**Comment by CyrineG** [comment]
@abhiyant-10 sorry! Changed the[ link](https://drive.google.com/file/d/1v5hF6ijuk4J9tgY0k7VJfUnSCPgviKCz/view?usp=sharing) try clicking again

**Comment by abhiyant-10** [comment]
would you like to have your location and twitter handle mentioned over there?

**Comment by CyrineG** [comment]
sure! I don't have twitter, my location is Tunisia

**Comment by moazzam07** [comment]
Can i take this one up!!
