### ISSUE TITLE
Duplicate filters on patterns page

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3151]
#### Description

Two duplicate filters exist  on patterns page from area I section.

![image](https://user-images.githubusercontent.com/95926324/188538213-6be3899d-6e60-4783-849b-352fbff902d4.png)

#### Expected Behavior

 remove one of them.
#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Himanshu664** [comment]
Hey I can do that

**Comment by legendarykamal** [comment]
Hey @Himanshu664 lets keep this for first timers  for 24 hrs and If no one shows up ofc you can take this up :)

**Comment by Himanshu664** [comment]
Sure @legendarykamal

**Comment by Nawaz027** [comment]
Hey @legendarykamal , I am a first timer. Can you please assign this issue to me?

**Comment by legendarykamal** [comment]
cool , go ahead @Nawaz027 :100:

**Comment by sarkartanmay393** [comment]
@legendarykamal Hey Kamal, I just arrived today. Is the issue still open ?

**Comment by legendarykamal** [comment]
yes @sarkartanmay393 :+1:

**Comment by SaiRev0** [comment]
If no one is working on it, Can I work on the issue @legendarykamal

**Comment by legendarykamal** [comment]
@sarkartanmay393 any updates ?

**Comment by tiger-yash** [comment]
hi @legendarykamal,
please assign this issue to me

**Comment by tiger-yash** [comment]
hi @legendarykamal,
please assign this issue to me, if no one is actively working on it.

**Comment by legendarykamal** [comment]
Ok this should have been fairly simple task to execute, but is taking too much time.

Deassigning and Reassigning based on first come, so @SaiRev0 you are up next. 👍

**Comment by SaiRev0** [comment]
@legendarykamal Can you please explain the error I can see the are no duplicate filters.

So I might me missing something, so please clarify the issue

**Comment by tiger-yash** [comment]
Hey @AbhishekTiwari23, I am already in queue so maybe you can look for some other issue.
Also if it is fine with @SaiRev0 and @legendarykamal, then I would like to take on the issue and submit a PR resolving it.

**Comment by SaiRev0** [comment]
> Hey @AbhishekTiwari23, I am already in queue so maybe you can look for some other issue. Also if it is fine with @SaiRev0 and @legendarykamal, then I would like to take on the issue and submit a PR resolving it.

I m actually working on it so if I m not able to then I will forward this issue to you

**Comment by tiger-yash** [comment]
@SaiRev0 you still working on it?

**Comment by SaiRev0** [comment]
> @SaiRev0 you still working on it?
> 

Actually I'm working on a different issue currently so i guess  you can assign it to someone else
