### ISSUE TITLE
4 Logo Images are missing in Repository overview 

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3152]
#### Description

![image](https://user-images.githubusercontent.com/95926324/188539083-5ceedb85-41c5-4ec4-9780-3a5a2e59c4a7.png)

#### Expected Behavior

Replace with the correct logo images.
#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shubhcs01** [comment]
@legendarykamal can I work on this issue?

**Comment by lavakush07** [comment]
Can I take up this issue ?

**Comment by lavakush07** [comment]
Hello @legendarykamal , I have a doubt  are there any logos for the following projects ? 🤔

**Comment by kirtanchandak** [comment]
Can I take this issue ?

**Comment by kirtanchandak** [comment]
I am a first timer, this would be a good start for me to work on this

**Comment by legendarykamal** [comment]
Since you both are newcomers, going by the FCFS 
@lavakush07 you may proceed with this. 

Meanwhile @kirtanchandak let me find a good one for you :)

**Comment by theVJagrawal** [comment]
hey @legendarykamal, would you please let me know if this issue is solved or not
I am also a first time and would like to work on this.

**Comment by legendarykamal** [comment]
hey @moazzam07 , @theVJagrawal thank you for showing interest , 
this has been assigned to @lavakush07 and is in progress. You may wait a little for him to show some activity :)

**Comment by leecalcote** [comment]
@lavakush07 can we offer any assistance? @alexisdsgns and @legendarykamal can offer a pointer or two.

**Comment by lavakush07** [comment]
> @lavakush07 can we offer any assistance? @alexisdsgns and @legendarykamal can offer a pointer or two.

I'm on it, I have a doubt that what are the logo's to be placed there ?

**Comment by leecalcote** [comment]
1. Meshery for wrk2
2 and 3. Github for actions
4. Patterns for service mesh patterns

**Comment by alexisdsgns** [comment]
I have tried effecting changes, but unfortunately I can not get it done as I have little to no experience using Github.

**Comment by legendarykamal** [comment]
no worries @alexisdsgns , now it would be easy for @lavakush07 to get this done :thinking: 
thanks to @leecalcote :100:

**Comment by lavakush07** [comment]
> no worries @alexisdsgns , now it would be easy for @lavakush07 to get this done 🤔 thanks to @leecalcote 💯
> 
> If not @lavakush07 then let me know , I will fix it 😄

I will make a PR by the EOD.

**Comment by lavakush07** [comment]
- I have made a Pull request, Please check it once.
- https://github.com/layer5io/layer5/pull/3167

**Comment by nik132-eng** [comment]
If this issue remains to solve can I get this? i am new commer

**Comment by legendarykamal** [comment]
Thank you for asking @nik132-eng this has been solved .
