### ISSUE TITLE
[Blog] Make category and tag list scrollable

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3154]
**Current Behavior**
With the ever-growing tags and category list for blogs, the sidebar is becoming too long and is overlapping with the footer.

<img width="596" alt="blog-tag-issue" src="https://user-images.githubusercontent.com/85789734/188614144-ffc86877-79b2-43bc-bb93-2aaf14bab43d.png">

**Desired Situation**
Give the tag and category list a fixed height on the page but make both the the lists scrollable.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by NPDebs** [comment]
Hi. 
Can I work on this task?

**Comment by debo19** [comment]
Sure @NPDebs

**Comment by NPDebs** [comment]
Thank you! 🤲🏻🙂😊

**Comment by zwwang98** [comment]
Hello! May I join you @NPDebs to work on this issue together?

**Comment by vishnus17** [comment]
Hi @NPDebs. 
Are you still working on this issue? If not, can I take over ? I was going through it and I've found a solution. 
Thanks.

**Comment by debo19** [comment]
@zwwang98 Since you commented first, I'll wait for you to respond if you want to take this up. Otherwise we'll assign @vishnus17

**Comment by zwwang98** [comment]
> @zwwang98 Since you commented first, I'll wait for you to respond if you want to take this up. Otherwise we'll assign @vishnus17

I would love to work on it. Really appreciate for this opportunity.

**Comment by debo19** [comment]
Go ahead @zwwang98

**Comment by zwwang98** [comment]
> Go ahead @zwwang98

Hello @debo19 ! Thank you again for this opportunity! I really appreciate it!  

I made some progress and I want to make sure I am on the right track:
1. added another class named `scroll` for the list `ul`
2. set the class with `max-height` and `overflow` in the `style.js` file

Here is how it looks now.
<img width="345" alt="screenshot of scroll categories and tags" src="https://user-images.githubusercontent.com/29494959/190025295-120e214e-f776-4ef4-88e5-8216f55456cd.png">

Also, after checking the contribution guide, I still have some problems with the contribution flow:
1. Is there any rule or convention on the git branch name? Like `<developer name>/<feature or bug>"?
2. Do I need to explain my thought and implementation in detail?

If this is close to the desired situation, I also have some possible next steps in my mind:
1. Now the `max-height` is hard-coded. Do we need to make it dynamic to some variable such as the height of the inner`<Link>` component?
3. In the categories scroll list, there is no space between the numbers and the right scroll bar. I think adding some space could look better.

Thank you again! I really love this inclusive and supportive community. I will dedicate myself to making it better.

**Comment by debo19** [comment]
@zwwang98 That's great! A well described PR is always desirable. You can add screenshots or video recordings to help with the review process. 

The [Contributing Instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#set-up-your-local-development-environment) lists all conventions to follow.

We could use some space between the numbers and the scrollbar. 
I am not sure how it looks in the dark mode. Once you open the PR, I think we can review that further.
