### ISSUE TITLE
[Community] Members: Add "Community Managers" as a role

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3159]
#### Current Behavior
This profile filter on https://layer5.io/community/members is missing the "Community Managers" role.

<img width="210" alt="Screen Shot 2022-09-07 at 9 33 29 PM" src="https://user-images.githubusercontent.com/7570704/189020757-4c1d73f4-c438-4eed-812f-0f14e4e266c5.png">

#### Desired Behavior
1. Ensure a new selection is available and filters on CM profiles.
1. Use  the three-person, green community badge as the icon.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Prajnaprabhu3** [comment]
May I work on this?

**Comment by theVJagrawal** [comment]
hey @leecalcote, I am a first timer and would like to contribute on this can you please assign me this issue

**Comment by sam1code** [comment]
I want to work on this if you guys don't mind! Thanks

**Comment by Mayaleeeee** [comment]
I wwould love to work on this @leecalcote

**Comment by leecalcote** [comment]
Thanks for volunteering, all. Let’s proceed in order by which you volunteered. Just prior to assignment, please confirm:

1. You have some level of comfort with 1) Gatsby / React and 2) GrapqhQL
2. You are build and run the site on your local machine

**Comment by sam1code** [comment]
Also For some reason make site not worked for me( npm thrown error  ) so I used yarn instead of npm and I got this in my localhost

**Comment by legendarykamal** [comment]
> Thanks for volunteering, all. Let’s proceed in order by which you volunteered. Just prior to assignment, please confirm:
> 
> 1. You have some level of comfort with 1) Gatsby / React and 2) GrapqhQL
> 2. You are build and run the site on your local machine

@Prajnaprabhu3 , @theVJagrawal can you update us with the ans please ? before we assign this to @sam1code .

**Comment by theVJagrawal** [comment]
thankyou @legendarykamal for your consideration, I am new on the platform and not so comfortable with these requirements so feel free to assign someone else and if you have any GOOD FIRST ISSUEES I would like to work on that

**Comment by Prajnaprabhu3** [comment]
hey, @legendarykamal  ! I do have experience with React & Gatsby, but not really comfortable with GraphQL. The site is not set on my local machine yet. You can assign the issue to @sam1code. I'll look for working on other issues in the future!

**Comment by legendarykamal** [comment]
ok @theVJagrawal and @Prajnaprabhu3 take your time to finish up with setup and with the project. 
@Prajnaprabhu3 about Graphql I would say is It depends on the issue you are taking up , So consider that in future .
@theVJagrawal many good first issues will be soon added , look for them :eyes:

**Comment by sam1code** [comment]
@legendarykamal @leecalcote Can you check the linked PR ?

**Comment by legendarykamal** [comment]
yes @sam1code checking it now

**Comment by sam1code** [comment]
Thankyou @legendarykamal

**Comment by sam1code** [comment]
![Screenshot from 2022-09-12 23-51-26](https://user-images.githubusercontent.com/74086891/189728002-ed6c7a05-994b-40e2-bf55-737684603d80.png)
it is taking 2 lines! @legendarykamal 
Is it ok?
