### ISSUE TITLE
Introduce "tags" for blog post categories

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#316]
**Current Behavior**
The layer5.io site has blog posts, but is lacking a tags feature to allow separation of posts by topic / by category.

**Desired Behavior**
1. Should have a way of navigating tags. (e.g. `/tag/linkerd`)
1. Main /blog should have some form of a tag cloud.
1. There should be a way to group posts that share tags.
1. https://jameshfisher.com/2019/05/05/how-can-i-add-tags-to-a-jekyll-blog/
1. Document tagging system, so that post authors may follow appropriate tagging conventions.

**Implementation**
Implementation could be done through a plugin like https://github.com/pattex/jekyll-tagging or through a new collection.

Be aware of Jekyll's global, built-in`site.tags` variable. The implementation of tags here, may choose to use or use this built-in variable.

---
**Resources**
- https://longqian.me/2017/02/09/github-jekyll-tag/
- https://www.assertnotmagic.com/2017/04/25/jekyll-tags-the-easy-way/
- https://jameshfisher.com/2019/05/05/how-can-i-add-tags-to-a-jekyll-blog/

**Comment by gunjanmimo** [comment]
@leecalcote sir, I want to try to solve this issue

**Comment by gunjanmimo** [comment]
@leecalcote sir, I have a doubt what is the source of blogs, is it _layout/posts.html?

**Comment by leecalcote** [comment]
@gunjanmimo the blog spans a few different files:

Starts here: https://github.com/layer5io/layer5/blob/master/collections/_pages/blog.html
Goes to here: https://github.com/layer5io/layer5/blob/master/_includes/collections/posts-list.html
Then to here: https://github.com/layer5io/layer5/blob/master/_includes/collections/posts.html
Then to here: https://github.com/layer5io/layer5/tree/master/collections/_blogs
