### ISSUE TITLE
[Community] Member Profile: Kamal Singh

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3161]
**Current Behavior**

@legendarykamal has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @legendarykamal  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @legendarykamal 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@legendarykamal Could you please provide your Twitter, and LinkedIn handle, with a link to your profile pic and bio?

**Comment by sam1code** [comment]
Hii this is really great hearing @legendarykamal
If this is a task and no one taken then I'll love serve...

**Comment by zwwang98** [comment]
Hi! I am new to the community and see this `good first issue`. Can I work on this issue?

**Comment by tinniaru3005** [comment]
Hii @Chadha93 ! I would like yo work on this issue. Can you please assign it to me.

**Comment by legendarykamal** [comment]
Thanks @Chadha93 for putting this up :smile: 
My respective handles are -> 
Twitter - 0xkamal7
Linkedin - kamal-singh7
Profile - https://drive.google.com/file/d/1zOm0cTaud5a4FM8ckttWJRciy4Td5GXz/view?usp=sharing

Bio-> I am an avid contributor and a JavaScript lover from the milkyway galaxy. The desire to contribute to open source led me to Meshery. I am happy to be here , learning many things and got to interact with talented people here making their footprints in the opensource world . I am trying to do my best and become better as a developer and in person too. K8s, docker, service meshes I always feel here the zeal to dive in , to learn more , to excel in the community. Lets Connect and get Meshy !

**Comment by legendarykamal** [comment]
Completed via #3164 :1st_place_medal:
