### ISSUE TITLE
[PR] Add a section to file on how to open new PR for newcomers

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3165]
**Current Behavior**

As dicussed in the previous meet, many newcomers face the issue of getting started . So this will help them in getting started.
**Desired Situation**

1> A small section needs to be added on how to open your first PR. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

file -> https://layer5.io/community/handbook/contribution
---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sam1code** [comment]
Hii @legendarykamal  I will love to work on this but before that I want to know what exactly need to be done! What changes this issue really need? 
I got that it needs some changes to the contribution page but what changes it need! And if you have any mock or where you want to add then that will be helpful to solve this issue.

**Comment by measutosh** [comment]
Hi @sam1code , apparently many docs related to contributions are present at many places. Few at website, few at docs, few at here in Github readme files. So the idea is to make a section which consolidates almost everything at one place if possible so that whenever a newcomer joins it should be an easy ride for them towards their first contribution.
All the resources needed to do execute this has already been provided by Kamal in the issue

**Comment by sam1code** [comment]
Hii @measutosh got it. And will love to work on this thankyou!

**Comment by sam1code** [comment]
Ooh got it

**Comment by sam1code** [comment]
As I said I love to work on this. @legendarykamal

**Comment by legendarykamal** [comment]
yes @sam1code you may go ahead :arrow_forward:

**Comment by legendarykamal** [comment]
> Hi @sam1code , apparently many docs related to contributions are present at many places. Few at website, few at docs, few at here in Github readme files. So the idea is to make a section which consolidates almost everything at one place if possible so that whenever a newcomer joins it should be an easy ride for them towards their first contribution. All the resources needed to do execute this has already been provided by Kamal in the issue

Thankyou @measutosh for the sleek reply :) although much of the things about projects are provided in repo overview section. 
This will be a :heavy_plus_sign:  to it.

**Comment by legendarykamal** [comment]
Yes , agreed Lee, The idea was to open just a normal section on how to open
a new PR for the first time contributors.

**Comment by sam1code** [comment]
So @legendarykamal, Should I give the link or not?

**Comment by legendarykamal** [comment]
No not needed, just the section would be enough.

**Comment by nik132-eng** [comment]
@legendarykamal  can you pls assign me this issue so I can do my first PR at layer5

**Comment by legendarykamal** [comment]
sure @nik132-eng here you go :rocket:
