### ISSUE TITLE
Replacing the small buttons for navigation

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3170]
#### Current Behavior

The buttons are too small and require the user to move to them specifically inorder to change.
#### Desired Behavior

They could be replaced with a broader vertical bar at both left and right hand side to improve the UX.

#### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/95926324/189567548-ce151e17-43a9-47ec-9ed2-dc09e8d2f6ce.png)

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
@legendarykamal I can pick it up!

**Comment by legendarykamal** [comment]
Lets wait for some triage for this before you get working on this.

**Comment by leecalcote** [comment]
@legendarykamal this concern is valid. Thank you for raising this issue. Ideally, the site will have carousel arrows are easier to use than they are in their current state.

**Comment by legendarykamal** [comment]
> 

Your Welcome @leecalcote  its always an effort to improve the site in the best way :)

**Comment by legendarykamal** [comment]
> @legendarykamal this concern is valid. Thank you for raising this issue. Ideally, the site will have carousel arrows are easier to use than they are in their current state.

Your Welcome @leecalcote  its always an effort to improve the site in the best way :)

**Comment by sam1code** [comment]
Sorry I forgot that my exam is starting from day after tomorrow. So, I'll pause till 29th september!
I'll restart from 30 september. So I'll create PR for the newcommer PR section and then I'll be back after 29( on 30th sept ) so till then Sorry

**Comment by legendarykamal** [comment]
// @Nikhil-Ladha a new component is needed or some older one can be used in here  for the carousel arrows ?

**Comment by Nikhil-Ladha** [comment]
Why a component is needed for this?
The arrow sizes can be modified using CSS in the respective pages.

Also, what do you mean by a "vertical bar"?

**Comment by AbhishekTiwari23** [comment]
If this issue still exists, please let me know if I can contribute.

**Comment by Nikhil-Ladha** [comment]
@legendarykamal working on this?

**Comment by legendarykamal** [comment]
oh yes , will try to finish this sooner.
