### ISSUE TITLE
[Site] Update date and new graphic for Hacktoberfest 2022

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3175]
#### Current Behavior
Hacktoberfest is around the corner and https://layer5.io/programs/hacktoberfest this page shows last year's date with 2021 graphic. 

#### Desired Behavior
Update the date and add  new graphics
Hacktoberfest 2022 site: https://hacktoberfest.com/

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Would like to take this up.

**Comment by NPDebs** [comment]
Hi. Can this be assigned to Eeshaan and I? Thank you...

**Comment by legendarykamal** [comment]
Go on devs :rocket:

**Comment by nik132-eng** [comment]
is there any need? I want to contribute to this issue @legendarykamal

**Comment by eeshaanSA** [comment]
the site can be updated once we get the 2022 graphic.

**Comment by legendarykamal** [comment]
the 2022 graphic is official now https://hacktoberfest.com/  so we can update this 
// @eeshaanSA

**Comment by arishmaurya** [comment]
@legendarykamal  i want to work on this can you assign it to me

**Comment by eeshaanSA** [comment]
@legendarykamal I am opening a seperate PR for updating the Graphic. We can have this PR merged, then have my PR(hacktober-graphic PR) merged.

**Comment by legendarykamal** [comment]
ok cool @eeshaanSA 

@arishmaurya thank you for showing interest but this has been already worked upon.  feel free to pick another one .
