### ISSUE TITLE
In Hacktoborfest blog post, the code section, text is in white color. Should be in proper coding color.

### ISSUE THREAD

**Issue by gunjanmimo** [layer5io/layer5#318]
In this blog post, the code section in white color, which is not visible properly/
![Screenshot from 2020-01-30 18-10-47](https://user-images.githubusercontent.com/46948185/73450887-5217df00-438c-11ea-8e6b-7ff96b350ad7.png)
Expected Behavior:
This section should have proper color to be visible to visitors

**Comment by leecalcote** [comment]
Good catch, @gunjanmimo

**Comment by leecalcote** [comment]
@Silvyre would you like to take this one on?

**Comment by Silvyre** [comment]
> 
> 
> @Silvyre would you like to take this one on?

Definitely.
