### ISSUE TITLE
[Community] Member Profile:  Antonette Caldwell

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3180]
**Current Behavior**

@acald-creator has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @acald-creator as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @acald-creator
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
Hi Antonette, could you please provide your Twitter, LinkedIn, Profile picture, and bio?

**Comment by akshatvirmani** [comment]
Hi!
I would like to work on this issue.

**Comment by legendarykamal** [comment]
hi @akshatvirmani are you done with the local setup?

**Comment by akshatvirmani** [comment]
Not yet. I will try do it by evening.

**Comment by acald-creator** [comment]
No problem!

Linkedin profile: https://www.linkedin.com/in/antonettecaldwell/

I will send an updated photo.

Bio is coming momentarily.

**Comment by siddheshJungade** [comment]
Hi 
I am having local env setup 
can I go for this issue ?

**Comment by Chadha93** [comment]
> Hi I am having local env setup can I go for this issue ?

Sure @siddheshJungade

**Comment by siddheshJungade** [comment]
Hi @acald-creator please provide details.

**Comment by acald-creator** [comment]
Do you still need a bio?

**Comment by siddheshJungade** [comment]
No sure ✌️

**Comment by SaiRev0** [comment]
Is this issue resolved or can I work on it??

**Comment by siddheshJungade** [comment]
@SaiRev0 working on it
