### ISSUE TITLE
[MeshMap] Jolting form submission behavior

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3183]
#### Description
When I say visitors submit the form for MeshMap, their browser is navigated to the top of the window and their focus is taken away from the form, which is often not even in view.

#### Expected Behavior
Not have your location updated, but to be shown the submission response in-place.

#### Screenshots
The confirmation dialog presented to visitors, who submit the form:
<img width="466" alt="Screen Shot 2022-09-20 at 5 27 03 PM" src="https://user-images.githubusercontent.com/7570704/191376207-18be9615-2f4c-4b47-94ca-7454e7edb587.png">

#### Environment:
- Host OS: Mac
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by siddheshJungade** [comment]
He @leecalcote should I give it a try ?

**Comment by XDRAGON2002** [comment]
Hi @leecalcote I have the project locally setup as well, would also like to work on and resolve this.
