### ISSUE TITLE
[Area: Blog] Eliminate unwanted artifact on hover of social buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3188]
#### Description
See this blog post as an example: https://layer5.io/blog/docker/extending-docker-with-meshery-spire-and-istio

#### Expected Behavior
No rectangular artifact should appear on hover.

#### Screenshots
<img width="230" alt="Screen Shot 2022-09-21 at 5 15 40 PM" src="https://user-images.githubusercontent.com/7570704/191620356-7d37edf2-ad0e-4a9a-9616-064933301173.png">

#### Environment:
- Host OS: Mac
- Browser:  Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
@leecalcote I would like to attempt to resolve this.

**Comment by leecalcote** [comment]
Thank you, @XDRAGON2002 👍
