### ISSUE TITLE
[Meeting] Updating the highlighted link in place of depreciated meeting link

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3191]
#### Description

The meeting is not active now but is highlighted .
![image](https://user-images.githubusercontent.com/95926324/191814430-c448fbc6-7580-4a25-ad7c-975333c580c1.png)

#### Expected Behavior

Some other Imp active meet link could be highlighted like the Meshery Build & Release Meeting
#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
how about Meshery developement meetings happening each wednesday // @leecalcote @warunicorn19 ?

**Comment by leecalcote** [comment]
Yes, highlighting the Meshery Dev meeting will work. Please only comment out the Layer5 Community meeting - it'll be back.

**Comment by XDRAGON2002** [comment]
@leecalcote @legendarykamal sure, will make the appropriate changes.
