### ISSUE TITLE
[Event] Add KubeCon talk to Events page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3200]
Please add the following event to layer5.io/events.

**Event:**
- Event Title: KubeCon + CloudNative North America 2022
- Event Link: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/
- Talk Link: https://kccncna2022.sched.com/event/1BZJl/the-state-of-the-cloud-native-network-deep-dive-from-tag-network-ed-warnicke-cisco-lee-calcote-layer5
- Talk Description: Every application needs to communicate.

That communication happens over the network.

Cloud Native, at its most basic, is an evolution of how to better meet application developers needs in a world that has moved beyond the mental model of the underlying infrastructure.  The Network is also evolving with new, more powerful, more flexible ways to allow applications to communicate with each other.

Cloud Native Networking is vast, encompassing CNI, CoreDNS, Envoy, gRPC, Linkerd, NATs,  Network Service Mesh, BFE, Contour, Kuma, Service Mesh Interface, Chaos Mesh, Open Service Mesh, Emissary, k8gb, Service Mesh Performance, Submariner, Cilium, Meshery, Fab Edge, Istio, Nighthawk, Aeraki, and FabEdge. The vastness can be daunting.

Come learn about the big picture in Cloud Native Networking in the CNCF from basic L3 Connectivity up to the latest in Service Mesh and how to put it all in a context you can use.
- Deck: 
- Video: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Moscode** [comment]
@leecalcote I will like to give this a shot as a newcomer.

**Comment by leecalcote** [comment]
Excellent, @Moscode 👍

**Comment by Moscode** [comment]
@leecalcote This issue has been submitted #3205, correct me if otherwise.

**Comment by Moscode** [comment]
I noticed that it is a different talk now, my bad.

**Comment by leecalcote** [comment]
@Moscode thats a different talk. We’re giving multiple talks.

**Comment by leecalcote** [comment]
Oh, sure. No sweat. 👍

**Comment by Moscode** [comment]
@leecalcote I want to confirm before making a PR. #3205 has the same title as this issue so each time I tried to view the full details of this event it ends up bringing up the full details of the other event.

**Comment by Moscode** [comment]
@leecalcote I'm waiting for your confirmation on this please.

**Comment by Chadha93** [comment]
@Moscode The difference here is the talk. So the talk title, date, and name will differ, here from #3205  - it will be "The state of the Cloud Native network: Deep-dive from TAG-network - Ed Warnicke, Cisco & Lee Calcote, Layer5". 
Please create a new event for KubeCon + CloudNative North America 2022  with the mentioned details in the description.
