### ISSUE TITLE
[Community] Member Profile: Divine Orji

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3201]
**Current Behavior**

@DivineOrji has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @DivineOrji as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @DivineOrji 
- Twitter: Dhee_graphics
- LinkedIn: divine-orji-b99b00170
- Link to profile picture: https://drive.google.com/file/d/1X3KQoZzKeKkeeOciU8v_1coaKbMmVeS-/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by XDRAGON2002** [comment]
@deepeshaburse I would like to work on this.

**Comment by deepeshaburse** [comment]
@DivineOrji Can you please provide a bio for the member profile?
