### ISSUE TITLE
[Programs] Hacktoberfest: Add dropdown list for years past

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3204]
#### Current Behavior
The [Hacktoberfest page](https://layer5.io/programs/hacktoberfest) does not have a drop-down for users to visit participation details of previous years.

#### Desired Behavior
Akin to the year-over-year drop-down that you can find on the [Google summer of code](https://layer5.io/programs/gsoc) or other programs that we have participated in year over year, the Hacktoberfest page should have a similar drop-down.

#### Screenshots / Mockups
<img width="1042" alt="Screen Shot 2022-09-28 at 10 38 56 AM" src="https://user-images.githubusercontent.com/7570704/192858560-5327c718-c37b-42ae-96b0-114a4d31c281.png">

#### Implementation
1. See GSoC page for an example.

#### Acceptance Tests
1. Visitors can navigate between different years of participation.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
Hi @leecalcote I would like to give this a shot.

**Comment by sunidhisachan** [comment]
hey @leecalcote , I can try this. Please assign this to me.

**Comment by leecalcote** [comment]
Oooh, you missed this by 22 seconds, @sunidhisachan. Not to fret, there will be loads of new issues opened across the ~70 repos that Layer5 Community manages. More about that here, if you haven't seen it - https://layer5.io/community/handbook/repository-overview
