### ISSUE TITLE
[Event]: Add KubeCon talk to Events page

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3205]
Please add the following event to layer5.io/events.

**Event:**
- Event Title: KubeCon + CloudNative North America 2022
- Event Link: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/
- Talk Link: https://kccncna2022.sched.com/event/1Banq/virtual-project-office-hours-meshery
- Talk Description: 

Project Office Hours is an opportunity for KubeCon + CloudNativeCon attendees to meet the maintainers of the projects, learn more about the project, ask questions, and learn about new features and upcoming updates. 

RSVP for Meshery Project Office Hours here: ​https://community.cncf.io/j/8pgn8we7gg8mg/

- Deck: 
- Video: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by abdullah1308** [comment]
Hey @deepeshaburse, I’d like to work on this .

**Comment by leecalcote** [comment]
Great, @abdullah1308. Have you been able to build and run the site locally?

**Comment by abdullah1308** [comment]
I have yet to start. I’ve gone through the steps to do so and I think I’ll be able to do it.

**Comment by leecalcote** [comment]
@abdullah1308, sounds good. If all else fails, ultimately, completion of this issue only requires creation of a mark down file from template. And not strictly the building of the site. Building of the site and a deploy preview will be created when you open a PR.

**Comment by legendarykamal** [comment]
> @abdullah1308, sounds good. If all else fails, ultimately, completion of this issue only requires creation of a markdown file from template. And not strictly the building of the site. Building of the site and a deploy preview will be created when you open a PR.

@abdullah1308 your work made easy  :) use a markdown editor in that case.
