### ISSUE TITLE
[Event]: Add KubeCon talk to Events page

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3206]
Please add the following event to layer5.io/events.

**Event:**
- Event Title: KubeCon + CloudNative North America 2022
- Event Link: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/
- Talk Link: https://kccncna2022.sched.com/event/1BaoI/virtual-project-office-hours-service-mesh-performance
- Talk Description: 

Project Office Hours is an opportunity for KubeCon + CloudNativeCon attendees to meet the maintainers of the projects, learn more about the project, ask questions, learn about new features and upcoming updates.

RSVP for Service Mesh Performance Project Office Hours here: ​https://community.cncf.io/j/ge5ft6dxm3ac5/

- Deck: 
- Video: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by eeshaanSA** [comment]
would like to work on it if the issue is approved and allowed to be worked on.

**Comment by measutosh** [comment]
Hi @deepeshaburse, just want to clarify something. Is this the [location](https://github.com/layer5io/layer5/tree/21f6d86b4728f7a77a1d3037e8aaf9a42e9f5dde/src/collections/events) where I need to add a folder or kubecon

**Comment by deepeshaburse** [comment]
> Hi @deepeshaburse, just want to clarify something. Is this the [location](https://github.com/layer5io/layer5/tree/21f6d86b4728f7a77a1d3037e8aaf9a42e9f5dde/src/collections/events) where I need to add a folder or kubecon
> 
> should be this way right?
> 
> ## ===============================================================================================
> title: "KubeCon + CloudNative North America 2022" date: 2021-05-04 thumbnail: ./kubecon-europe-2021.jpg darkthumbnail: ./kubecon-europe-2021.jpg eurl: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/ type: Event published: true upcoming: true feature: true speakers: []
> 
> Join Layer5 at KubeCon + CloudNative North America 2022. Engage with us in our talks!
> 
> Project Office Hours is an opportunity for KubeCon + CloudNativeCon attendees to meet the maintainers of the projects, learn more about the project, ask questions, learn about new features and upcoming updates.
> 
> * Talk
> ========================================================================================================
> 
> and could you please provide the date, speakerlist, thumbnails etc to add ?

Yes, the location is correct.

Date: 2022-10-27
I don't think you have to add speakers.
Thumbnail is in the kubecon-na-2022 folder.

Sorry for the late response :)

**Comment by measutosh** [comment]
![image](https://user-images.githubusercontent.com/78539272/193435800-f93cfc30-107d-43d5-9299-4b5e1ab24276.png)

Hi @deepeshaburse , couldn't find any `kubecon-na-2022`, could you please lead me the location to it

**Comment by deepeshaburse** [comment]
Location: https://github.com/layer5io/layer5/tree/master/src/collections/events/kubecon-na-2022

It should look like [this](https://layer5.io/community/events/kubecon-cloudnative-north-america-2022).

**Comment by measutosh** [comment]
@deepeshaburse , I am confused, the kubecon-na folder I was going to create but it's already there right, the location which you shared above.
it has been implemented already, then what else left to add?
and only one difference I could find out is, the location you have shared has the date of 24th oct but in the above comments you have suggested to add 27th oct
I am not sure what to implement and what not, please clarify

**Comment by sarkartanmay393** [comment]
@deepeshaburse This issue is closed right ? NA KubeCon event is live on website.

**Comment by leecalcote** [comment]
There are three talks that can be posted under the same event.

**Comment by deepeshaburse** [comment]
@measutosh Any updates? I think Lee answered your question quite some time back. We need this event up asap.
