### ISSUE TITLE
Add multiple languages to the layer footer.

### ISSUE THREAD

**Issue by Aisuko** [layer5io/layer5#321]
**How can we help?**
A brief description of what question(s) you have and how we can help clarify.

As @leecalcote  said in the channel, we could add Chinese into [layer.io](https://layer5.io) footer.

**Comment by Aisuko** [comment]
@gunjanmimo So, Would you like to tell me where you got the national flags? I will get one same size as other flags

**Comment by jijillery** [comment]
The SVGs for these flags were found on Wikipedia ([flag of China](https://en.wikipedia.org/wiki/Flag_of_China#/media/File:Flag_of_the_People's_Republic_of_China.svg)). Not only are these nice SVGs, but they carry a public domain copyright for our use.

**Comment by Aisuko** [comment]
As I discussed with @gunjanmimo. I can confirm add Chinese and Japan flags to the site.
