### ISSUE TITLE
[Events] Event Carousel not clickable

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3217]
#### Description
Site visitors will often attempt to click for more details about a particular event that they are interested in when they see it in the carousel on the https://layer5.io/community/events page. 

The events are not clickable in the carousel, though.

#### Expected Behavior
Allow users to click the image of a particular event and be directed to that specific event page.

#### Screenshots
<img width="1000" alt="Screen Shot 2022-09-29 at 2 40 02 PM" src="https://user-images.githubusercontent.com/7570704/193145520-f95e3f06-8509-49a7-a05d-584ca881dfde.png">

#### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
Hi @leecalcote I would like to try and resolve this issue.

**Comment by leecalcote** [comment]
Eeeexxcellent. 🙂
