### ISSUE TITLE
All logos should have same text color(white) in darkmode

### ISSUE THREAD

**Issue by ghulamyazdani** [layer5io/layer5#3220]
#### Description
On the Projects page, some logos have different text colors in dark mode that is not looking in UI perspective also in the open service mesh logo there is a whitish shade in the "e" alphabet

#### Expected Behavior
All the text in the logos should be of the same color.

#### Screenshots

![image](https://user-images.githubusercontent.com/55938346/193305235-31ad204d-6433-4a8a-a689-e7eeee387513.png)
![image](https://user-images.githubusercontent.com/55938346/193305760-35d8ae35-c708-42a4-9a6d-f8ed330d9935.png)

#### Environment:
- Host OS:  Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ronitblenz** [comment]
I would like to fix this issue, Could you please assign me?

**Comment by lavakush07** [comment]
But I think the logo of envoy is pink in color originally. I think we should not change the color according to me .

**Comment by leecalcote** [comment]
@lavakush07 in general, you're right: you don't want to mutate logos / copyrighted trademarks. In Envoy's case and every other project represented here, they all have white versions of their logos published. 

@ronitblenz please use this one for [Envoy](https://raw.githubusercontent.com/cncf/artwork/master/projects/envoy/horizontal/white/envoy-horizontal-white.svg). Please swap out the Open Application Model logo with [OPA's logo](https://raw.githubusercontent.com/cncf/artwork/master/projects/opa/horizontal/white/opa-horizontal-white.svg).
Please replace Traefik Mesh's logo with [Helm's logo](https://raw.githubusercontent.com/cncf/artwork/master/projects/helm/horizontal/white/helm-horizontal-white.svg), .
Here's [Open Service Mesh white](https://raw.githubusercontent.com/cncf/artwork/master/projects/openservicemesh/stacked/white/openservicemesh-stacked-white.svg)

**Comment by ronitblenz** [comment]
Tag this issue as an Hacktoberfest one please... I will submit a PR soon.

**Comment by tinniaru3005** [comment]
Hey @leecalcote I would like to take the issue. Can you please assign it to me

**Comment by leecalcote** [comment]
> Hey @leecalcote I would like to take the issue. Can you please assign it to me

Thanks! You should be Abel to find all of these logos in github.com/cncf/artwork

**Comment by tinniaru3005** [comment]
> Thanks! You should be Abel to find all of these logos in github.com/cncf/artwork

Hey, I wont't be able to give time this week due to my exams. So, I am unassigning myself. :)

**Comment by Shivam-AfA** [comment]
Hi can I work on this issue?

**Comment by Shivam-AfA** [comment]
Hi! I tried to run the website but I am stuck on this process

![image](https://user-images.githubusercontent.com/88040318/201373895-5683f884-7313-4501-b229-32bf5066bd50.png)

Can anyone help me out here?

**Comment by Shivam-AfA** [comment]
Hi, I have made changes to 3 images, namely **Envoy**, **Open Service Mesh** and **Service Mesh Interface**. The logos are different when theme is changed. Is this right or do I have to change only the text color to white and the logo image shall remain the same?

![image](https://user-images.githubusercontent.com/88040318/201422634-85872684-0974-4c7b-b360-07d509246e6b.png)


![image](https://user-images.githubusercontent.com/88040318/201424368-945a4fc9-8595-45d3-86be-23f5fa60ee38.png)

And regarding this discussion above  
> @lavakush07 in general, you're right: you don't want to mutate logos / copyrighted trademarks. In Envoy's case and every other project represented here, they all have white versions of their logos published.
> 
> @ronitblenz please use this one for [Envoy](https://raw.githubusercontent.com/cncf/artwork/master/projects/envoy/horizontal/white/envoy-horizontal-white.svg). Please swap out the Open Application Model logo with [OPA's logo](https://raw.githubusercontent.com/cncf/artwork/master/projects/opa/horizontal/white/opa-horizontal-white.svg). Please replace Traefik Mesh's logo with [Helm's logo](https://raw.githubusercontent.com/cncf/artwork/master/projects/helm/horizontal/white/helm-horizontal-white.svg), . Here's [Open Service Mesh white](https://raw.githubusercontent.com/cncf/artwork/master/projects/openservicemesh/stacked/white/openservicemesh-stacked-white.svg)

I could not find the image files for OPA and Helm on the paths above.

**Comment by eeshaanSA** [comment]
Please use the images/svgs provided here in this comment. 

> @lavakush07 in general, you're right: you don't want to mutate logos / copyrighted trademarks. In Envoy's case and every other project represented here, they all have white versions of their logos published.
> 
> @ronitblenz please use this one for [Envoy](https://raw.githubusercontent.com/cncf/artwork/master/projects/envoy/horizontal/white/envoy-horizontal-white.svg). Please swap out the Open Application Model logo with [OPA's logo](https://raw.githubusercontent.com/cncf/artwork/master/projects/opa/horizontal/white/opa-horizontal-white.svg). Please replace Traefik Mesh's logo with [Helm's logo](https://raw.githubusercontent.com/cncf/artwork/master/projects/helm/horizontal/white/helm-horizontal-white.svg), . Here's [Open Service Mesh white](https://raw.githubusercontent.com/cncf/artwork/master/projects/openservicemesh/stacked/white/openservicemesh-stacked-white.svg)

**Comment by Shivam-AfA** [comment]
@eeshaanSA Hi! I could not find the images at the links provided in the message. So I changed the text color to white and submitted the PR. It was merged.

**Comment by eeshaanSA** [comment]
Great. Thanks @Shivam-AfA . Be sure to link your PR with Issue next time around. ;)

**Comment by Shivam-AfA** [comment]
Sure @eeshaanSA. Thanks!
