### ISSUE TITLE
Single Pages: Hero images leave much whitespace

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3221]
#### Current Behavior
Hero images on single page entries across many of the collections (like blog posts, events, resources, news, and so on), don't fill the space afforded to the image, but instead leave a smaller image with extra, unused whitespace.

The current CSS with `object-fit: contain;` _should_ work, but seems to not be having the desired affect given conflicting(?) CSS.

#### Desired Behavior
It would be nice to have the images fill the empty space.

#### Screenshots / Mockups
example: https://layer5.io/community/events/hacktoberfest-prep-easing-into-cncf-open-source-projects

<img width="1533" alt="Screen Shot 2022-09-30 at 12 21 47 PM" src="https://user-images.githubusercontent.com/7570704/193324408-83869c20-4e06-4f08-9093-73ff31f499d8.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
Hey @leecalcote I can fix this issue please assign it to me!

**Comment by sam1code** [comment]
Hey @leecalcote I would love to fix this!

**Comment by leecalcote** [comment]
Sounds good, @sam1code

**Comment by sam1code** [comment]
Hello I've gone through this the issue here is that the hero image have lots of space around the PNG file itself...
If we change this one then the menu area getting cropped...

Any suggestions for this?

**Comment by Nikhil-Ladha** [comment]
Re-opening the issue since the PR was reverted.

**Comment by AbhishekTiwari23** [comment]
Can I work over this? If it is not closed yet

**Comment by Nikhil-Ladha** [comment]
Sure

**Comment by Nikhil-Ladha** [comment]
Unless, @sam1code you are working on it?

**Comment by sam1code** [comment]
Sure @Nikhil-Ladha you can assign to anyone I tried but still it is overriding others also.

**Comment by Nikhil-Ladha** [comment]
Ack.
Here is your chance @AbhishekTiwari23

**Comment by AbhishekTiwari23** [comment]
@Nikhil-Ladha, sir, I have a little doubt, should I have to remove the lower and upper white space, or do I have to make it something like this
<img width="1440" alt="Screenshot 2022-10-14 at 12 27 20 AM" src="https://user-images.githubusercontent.com/97469132/195684074-99122513-d0b9-4bdf-9509-0b3058a9babb.png">

**Comment by Nikhil-Ladha** [comment]
You need to remove lower and above white space.
The issue description is pretty self explanatory.

**Comment by AbhishekTiwari23** [comment]
<img width="1440" alt="Screenshot 2022-10-14 at 2 31 52 PM" src="https://user-images.githubusercontent.com/97469132/195807759-498b9101-2651-4ce7-b6bf-3bc707915bb0.png">

@Nikhil-Ladha, the sir, is it okay now? Should I make a PR

**Comment by Nikhil-Ladha** [comment]
The change shouldn't be limited to this page only.
But, in general to the single blog,event pages

**Comment by AbhishekTiwari23** [comment]
> The change shouldn't be limited to this page only. But, in general to the single blog,event pages

Actually, this issue is not because of any kind of padding and margin, but this image itself has so much white space, I just replaced the image with a new one. Might be if making changes in the default values then there might be some errors. so please let me know what should I do

**Comment by AbhishekTiwari23** [comment]
Should I make a pr for this?

**Comment by legendarykamal** [comment]
> The change shouldn't be limited to this page only. But, in general to the single blog,event pages

clarifying more on his words, @AbhishekTiwari23 have you checked other blog / event pages ?

**Comment by AbhishekTiwari23** [comment]
> > The change shouldn't be limited to this page only. But, in general to the single blog,event pages
> 
> clarifying more on his words, @AbhishekTiwari23 have you checked other blog / event pages ?

Oh, now I understand the real issue, please give me a little time, I will respond as early as possible.

**Comment by AbhishekTiwari23** [comment]
<img width="1440" alt="Screenshot 2022-10-22 at 3 19 21 PM" src="https://user-images.githubusercontent.com/97469132/197332950-abb65400-fdce-49a4-b71e-94d0f32fd2c1.png">

Is it fine? I added a new class .feature-image in EventSingle.style and added a negative margin, please have a look, and if I am in the wrong direction then please guide me. 
Thanks.

**Comment by AbhishekTiwari23** [comment]
<img width="1440" alt="Screenshot 2022-10-22 at 3 22 31 PM" src="https://user-images.githubusercontent.com/97469132/197333061-f0da898e-dd4e-4dd9-940c-607848e4cc53.png">
It is the original one. Please have a look. Thanks.

**Comment by Nikhil-Ladha** [comment]
Please create a PR with the changes, so that it is easier to confirm the changes work fine for all the pages.
