### ISSUE TITLE
BUG : Text cutting after the animation in Meshmap site

### ISSUE THREAD

**Issue by ronitblenz** [layer5io/layer5#3222]
#### Description

I have noticed that the animation of the mesh map site ends up with the text which looks to be cut.

https://layer5.io/cloud-native-management/meshmap

#### Expected Behavior

Full view of the text

#### Screenshots

<img width="1440" alt="Screenshot 2022-09-30 at 9 23 35 PM" src="https://user-images.githubusercontent.com/91361382/193328822-36d40b2c-0db3-47a0-82dc-70d1b0d33faf.png">

#### Environment:
- Host OS: MacOS, Windows
- Browser: Chrome, Safari, Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ronitblenz** [comment]
Can you assign me with this issue?

**Comment by leecalcote** [comment]
Thank you, @ronitblenz 👍

**Comment by ronitblenz** [comment]
Hey Lee,

I couldn't find the code base responsible for that site, could you please give me the link to meshmap site project.

And kindly add the hacktoberfest tag to it, I am participating there !

**Comment by tiger-yash** [comment]
Hey @leecalcote!
please assign this to me

**Comment by ronitblenz** [comment]
Hey @tiger-yash 
I found it difficult to solve this, I am unassigning myself.

**Comment by sandeepB3** [comment]
Hey, can I be assigned for this? I have solved it. Would like to make the PR. Thankyou!!
