### ISSUE TITLE
[Programs] Hacktoberfest: Use generic Hacktoberfest logo for program card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3224]
#### Description
The [programs page](https://layer5.io/careers/programs) has a 2022 version of Layer5's Hacktoberfest participation. The Hacktoberfest event design changes from year to year.

#### Expected Behavior
The Hacktoberfest program card should use generic Hacktoberfest logo to represent all years that Layer5 has participated.

#### Screenshots
<img width="1003" alt="Screen Shot 2022-09-30 at 4 59 12 PM" src="https://user-images.githubusercontent.com/7570704/193362203-17b456d2-a94b-46af-9eb3-389836c7c9c2.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
@leecalcote I would like to work on this.
