### ISSUE TITLE
Vulcand logo on service-mesh-landscape in darkmode not properly visible

### ISSUE THREAD

**Issue by sam1code** [layer5io/layer5#3226]
#### Description
The service-mesh-landscape route containing verious logos at Service Mesh Timeline. The Vulcand logo in darkmode is looking very ugly. Sometimes not able to see also.
![image](https://user-images.githubusercontent.com/74086891/193379419-4d9b97b6-959d-4a4f-b955-113e79ab42b8.png)

#### Expected Behavior
We can invert the color or can increase the size (which ever looks good).
![image-removebg-preview (6)-modified](https://user-images.githubusercontent.com/74086891/193379612-fc6605d1-36cc-4691-8383-993a3eb675ba.png)

#### Environment:
- Host OS: any
- Browser: any

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
I'll love to work on this if it is accepted.

**Comment by leecalcote** [comment]
Color inversion make sense. Thank you, @sam1code

**Comment by sam1code** [comment]
Thanks @leecalcote I'm starting working on these 3 issues
