### ISSUE TITLE
The logo Kuma on service-mesh-landscape can be changed in dark mode 

### ISSUE THREAD

**Issue by sam1code** [layer5io/layer5#3227]
#### Description
The logo of kuma is looking bad in dark mode.

#### Expected Behavior
wecan chane the logo to the logo still used on learn/service-mesh-labs.

#### Screenshots
![image](https://user-images.githubusercontent.com/74086891/193379712-e5e6f332-9432-49b9-8f84-23479f46a804.png)
![image](https://user-images.githubusercontent.com/74086891/193379757-284e902e-6826-4f67-8168-f5fd9c017e8a.png)

#### Environment:
- Host OS: any
- Browser: any

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
I'll love to work on this if it is accepted.

**Comment by leecalcote** [comment]
Yes, thank you, @sam1code
