### ISSUE TITLE
Fix the community calendar import URL 

### ISSUE THREAD

**Issue by 17sushmita** [layer5io/layer5#3229]
#### Description

The [community calendar page](https://layer5.io/community/calendar#meetings) has a yellow button `Add to your calendar` which on clicking opens up google calendar to add the events to our own calendar. The link that opens redirects to the secondary account if more than one account is logged in. 

#### Expected Behavior

The URL that should open on clicking the button should redirect to the primary or default account.
#### Screenshots

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/42088159/193403536-19557f1a-b66f-4c5b-bd9d-48843bfbac10.png">

#### Environment:
- Host OS:  mac OS, Windows, linux
- Browser:  Google Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by nishantn31** [comment]
I would like to work on this.

**Comment by legendarykamal** [comment]
hello @nishantn31 can you please confirm if you have set up the env locally before i get you assigned?

**Comment by sarkartanmay393** [comment]
@17sushmita I would like to help on this issue.

**Comment by 17sushmita** [comment]
@sarkartanmay393 I'm already working on it
