### ISSUE TITLE
padding required between email input label and subscribe button this breaks responsive on small screen

### ISSUE THREAD

**Issue by munyanezaarmel** [layer5io/layer5#3231]
#### Description

on the blog route, there is no padding between  subscribe button and the input email label which makes it looks weird and it is breaking responsiveness on small screens 
#### Expected Behavior

there should be some padding to separate them and fix responsiveness on small screen 
#### Screenshots

![image](https://user-images.githubusercontent.com/73389979/193414843-d82a9f8f-01d3-4bc9-97ef-661875fa9786.png)

![image](https://user-images.githubusercontent.com/73389979/193414653-b69aa73c-1d01-4ea1-a9cf-a177f76767bc.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ronitblenz** [comment]
I want to take up this issue

**Comment by YashKamboj** [comment]
@munyanezaarmel are you working on it , if not @ronitblenz can work on it

**Comment by munyanezaarmel** [comment]
am having hard times setting local environment @ronitblenz can take it

**Comment by rakshitgondwal** [comment]
Hey @ronitblenz !!!
are you still working on this issue?

**Comment by AbhishekTiwari23** [comment]
This issue is still going on. Please let me know if I can contribute.

**Comment by ronitblenz** [comment]
Hey @sahilsuman933, I am finding it to be difficult to work on this.
You can pass this issue on to the next person.

**Comment by AbhishekTiwari23** [comment]
@leecalcote, Thanks for assigning me, I will reply as soon as possible

**Comment by AbhishekTiwari23** [comment]
@leecalcote hello, sir, After changing the left-right padding, I came up with this. Please let me know if it is good or nor
<img width="1440" alt="Screenshot 2022-10-07 at 9 25 36 PM" src="https://user-images.githubusercontent.com/97469132/194596605-ab8b3cbc-1af2-4649-a8db-c2d43882cebb.png">

**Comment by AbhishekTiwari23** [comment]
> LGTM! 🚀
> 
> Send a PR @AbhishekTiwari23

ok

**Comment by AbhishekTiwari23** [comment]
> LGTM! 🚀
> 
> Send a PR @AbhishekTiwari23

Hello @sahilsuman933, I made a PR, please have a look and let me know if there is any issue

**Comment by legendarykamal** [comment]
@munyanezaarmel we (me & @Nikhil-Ladha )  are unable to replicate this issue , 
Can you please share the resolution at which you are seeing this issue? would be helpful. Otherwise we will close this issue .

**Comment by legendarykamal** [comment]
@munyanezaarmel we (me & @Nikhil-Ladha )  are unable to replicate this issue , 
Can you share the resolution at which you are seeing this issue? would be helpful. Otherwise we will close this issue .
