### ISSUE TITLE
Rewrite required for the "Recognition" section

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3235]
**Current Behavior**
The title is "Recognitions" instead of Recognition. The "We do not allow" is also present [here](https://layer5.io/community/handbook/community). 

**Desired Situation**
The language of the entire section of "Recognition" needs to be updated and "We do not allow" section needs to be put under Code of Conduct.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by XDRAGON2002** [comment]
@deepeshaburse I'll work on this

**Comment by XDRAGON2002** [comment]
Ah sure no issues! :)
