### ISSUE TITLE
chore: update MeshKit details in Community Handbook

### ISSUE THREAD

**Issue by pk-218** [layer5io/layer5#3236]
**Current Behavior**

There is no description for the MeshKit project in the [Repository Overview](https://layer5.io/community/handbook/repository-overview) section of the Community Handbook

![image](https://user-images.githubusercontent.com/53428217/193423108-44bd488d-0bfa-48f2-89c3-a7e7c6b4fc22.png)

**Desired Situation**

Description for MeshKit should show up or be added.
Recently **Cuelang** was included in the project. List it as the language used for the project along with Golang

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by eeshaanSA** [comment]
would like to work on it.

**Comment by rghdrizzle** [comment]
hey can I work on this ?

**Comment by legendarykamal** [comment]
Getting assigned first before PR is a good practice @rghdrizzle, anyways good 👍 .
