### ISSUE TITLE
Apple Image on the Integrations page is skewed.

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3238]
#### Description

The apple logo on the integrations page needs to unskewed.
![image](https://user-images.githubusercontent.com/100678386/193423793-4526e265-cffb-4f55-ad2c-108924f22995.png)

#### Expected Behavior

unskwed, and even image of the apple logo..

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Would like to fix this issue. @debo19 @legendarykamal

**Comment by legendarykamal** [comment]
Thank you @eeshaanSA  for opening this one.

I will leverage this distinction with @sahilsuman933 to decide.

**Comment by sahilsuman933** [comment]
@eeshaanSA I feel like the logo is not skewed. So, we don't need to fix that.

**Comment by leecalcote** [comment]
I'll offer this statement: "_The white version of the Apple logo is absolutely skewed._" and invite folks to disprove it.

**Comment by eeshaanSA** [comment]
haha, Solidarity, @leecalcote. Willl fix it.
