### ISSUE TITLE
[Community Handbook] Repo Overview: Add "Cuelang" as a language in the MeshKit project

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3239]
**Current Behavior**
The MeshKit entry in the [Repository Overview](https://layer5.io/community/handbook/repository-overview) in the Community Handbook is missing "Cuelang" as on of its languages.

**Desired Situation**
Add Cuelang to the list for MeshKit.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by NPDebs** [comment]
Hi @leecalcote . Shall I pick this one up? 👀

**Comment by leecalcote** [comment]
Oops. This issue is a duplicate of the issue that @pk-218 has already opened - https://github.com/layer5io/layer5/issues/3236. I'll close this issue in lieu of his diligent work there.
