### ISSUE TITLE
layer5 : enhance organizations section in website

### ISSUE THREAD

**Issue by nik132-eng** [layer5io/layer5#3249]
#### Current Behavior
I saw static state of cloud native, envoy, etc.

![image](https://user-images.githubusercontent.com/77881638/193525794-0b07164f-596f-40df-b295-367b0d551258.png)

![image](https://user-images.githubusercontent.com/77881638/193524854-a84e4286-7e9b-444e-aff3-eac7e595f436.png)

#### Desired Behavior
I want to add effect like when you move your mouse from that specific organization it move upward and add transaction into it. 

https://i0.wp.com/css-tricks.com/wp-content/uploads/2018/01/direction-aware-hovers.gif?fit=607%2C303&amp;ssl=1

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by nik132-eng** [comment]
can you please assign me this issue for hacktoberfest?

**Comment by legendarykamal** [comment]
@nik132-eng this needs some triaging, will you mind adding it todays website call?

**Comment by nik132-eng** [comment]
@legendarykamal can you some more elaborate about what is triaging ? I am not getting you

**Comment by legendarykamal** [comment]
Someone preferably a maintainer should approve it right? add it for a discussion as this area has been raised in a number of different issues and has been clarified as a part of design.

 I wonder if those effects would look good here 🤔 , but you can present your idea.
