### ISSUE TITLE
Text Update 

### ISSUE THREAD

**Issue by lavakush07** [layer5io/layer5#3251]
#### Description

The word **to** is written twice. Just need to cancel one out.
#### Screenshots

![image](https://user-images.githubusercontent.com/70131581/193544338-4278931f-b369-40d6-b822-d028f00ae2e5.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by lavakush07** [comment]
Can you assign me this issue ?

**Comment by lavakush07** [comment]
I have made a PR which closes this issue.
https://github.com/layer5io/layer5/pull/3253

**Comment by Gun2902** [comment]
can you assign me this issue???

**Comment by lavakush07** [comment]
> can you assign me this issue??? #3253

Hello @Gun2902 I have already made a PR.
