### ISSUE TITLE
Create a white MiniKube Logo for Dark Theme

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#3257]
**Current Behavior**

You need to create a white logo for MiniKube for the dark theme, which will be used across the website. 

You can find the colored logo in location `layer5/src/sections/Meshery/Meshery-platforms/supported-icons/`.

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by NPDebs** [comment]
@sahilsuman933 This looks interesting.
Does this involve editing the svg image to change the color to white?

**Comment by PriyanshuAhlawat** [comment]
I will like to work on it , pls assign

**Comment by sahilsuman933** [comment]
@NPDebs Yup, you got it correct. We need to convert the SVG image for the dark theme by changing the color to white or black.

**Comment by NPDebs** [comment]
@sahilsuman933 Ah. Nice. I'd love to work on this then...

**Comment by sahilsuman933** [comment]
Go ahead @NPDebs.

**Comment by sahilsuman933** [comment]
@PriyanshuAhlawat, I will be opening a few more issues very soon. You can work on those.

**Comment by NPDebs** [comment]
@sahilsuman933 Thanks! On it. 🚀

**Comment by PriyanshuAhlawat** [comment]
> @PriyanshuAhlawat, I will be opening a few more issues very soon. You can work on those.

sure👍
