### ISSUE TITLE
Create a Layer5 logo with white text

### ISSUE THREAD

**Issue by NPDebs** [layer5io/layer5#3259]
**Current Behavior**
In dark mode, the current logo is barely legible, as a result of the dark text color.

![dark-text-logo](https://user-images.githubusercontent.com/105166953/193747269-edbc06a7-3403-4539-8da6-9c5e62a369e9.png)

**Desired Situation**
Create a new logo with white "LAYER" text by editing the one found in this repo (src/assets/images/layer5/layer5-only/svg/layer5-no-trim.svg). This new logo will be used to fix the readability in dark mode.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sam1code** [comment]
I think Color change will work like what I did for Vulcand! I can Change It and implement everywhere...

**Comment by sahilsuman933** [comment]
We already have a white logo for dark theme.

**Comment by legendarykamal** [comment]
@NPDebs use an existing one probably this ->  https://github.com/layer5io/layer5/blob/master/src/assets/images/layer5/layer5-only/png/layer5-light-bg.png to replace the current one.

**Comment by legendarykamal** [comment]
We can preferably switch to this existing one for dark mode -> https://github.com/layer5io/layer5/blob/master/src/assets/images/layer5/layer5-only/png/layer5-light-bg.png.

// views please @leecalcote @Nikhil-Ladha.

**Comment by Nikhil-Ladha** [comment]
I am not sure how come the current logo is "barely visible".
But, even if it is then we should be using this [logo](https://github.com/layer5io/layer5/blob/master/src/assets/images/layer5/layer5-only/png/layer5-white-no-trim.png)

**Comment by NPDebs** [comment]
This actually looks perfect to me @legendarykamal . 😃🤍

Let's await input from the others. 👀🤞🏼

**Comment by NPDebs** [comment]
@Nikhil-Ladha This will work too. 💯
At the end of the day, the goal is to use a text color that **best** contrasts the background color, as it makes for better UI.

**Comment by sahilsuman933** [comment]
@Nikhil-Ladha If we go for this change, we have to change other logos too. This will lead to visibility issues in light mode.

**Comment by NPDebs** [comment]
@sahilsuman933 That's a very valid concern.

We won't be altering how the logo looks in light mode. The code will be written in such a way that this "white text" logo only shows up in dark mode.

Make sense?

**Comment by Nikhil-Ladha** [comment]
Considering the majority of you agree on the use of the logo Kamal shared, @NPDebs go ahead and send the PR 👍🏼

**Comment by NPDebs** [comment]
Thank you for your input @Nikhil-Ladha .
Could you go ahead and assign this to me, please?

**Comment by Nikhil-Ladha** [comment]
Done ✔️
