### ISSUE TITLE
Need a white logo for the docker image for Dark Mode on Integrations Page

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3260]
#### Description

![image](https://user-images.githubusercontent.com/100678386/193747859-7165e3ef-04b2-45d2-9f52-c66be21301aa.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Would like it to be assigned to me.

**Comment by sahilsuman933** [comment]
We already have a white logo of docker for the dark theme.

**Comment by eeshaanSA** [comment]
it doesnt show up for the dark mode, which ideally it should, right?

**Comment by sahilsuman933** [comment]
@eeshaanSA, a discussion is still going on about whether we should go for the white or dark logos. Also, if we go for the white logos, a PR is already pending.  

https://github.com/layer5io/layer5/pull/3256
