### ISSUE TITLE
[Improvement in description of Integration] AKS 

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3261]
#### Current Behavior

Here is the relevant link to be updated/worked upon 
https://layer5.io/cloud-native-management/meshery/integrations/aks

Following are the list of checks and tasks to perform on the above listed integration.

1> Rewrite integration tagline.
2> Revise the features section and update it with the latest info.
3> Revise the overview section and update it with the latest info.
4> Update the images in "How it works section".

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vishnus17** [comment]
Hi @legendarykamal . Do you mean to work on the readme for AKS?
Can you please provide more clarity on the issue?

**Comment by legendarykamal** [comment]
No, 
I have clarified already in the description, but you may have this https://layer5.io/cloud-native-management/meshery/integrations/aks for better peek in 👍

**Comment by legendarykamal** [comment]
@vishnus17 checking in , have you got a good hold of what is needed here ?  If you have any doubts, feel free to reach on slack or ask here.

**Comment by vishnus17** [comment]
Hi @legendarykamal. 
Yes, the link helped. Before I was wondering where the updates were needed. 
I can take up this issue. Thanks

**Comment by legendarykamal** [comment]
ok hope to see an update soon from you :) .

**Comment by vishnus17** [comment]
Hi. 
Sorry, I'm currently busy with my college and internship. You may unassign me. Thanks

**Comment by leecalcote** [comment]
Closing out abandoned issue and assignment.
