### ISSUE TITLE
[Improvement in description of  Integrations] Docker and Github

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3262]
#### Current Behavior

Here are the relevant links where the details are needed to be updated.

1> https://layer5.io/cloud-native-management/meshery/integrations/docker
2> https://layer5.io/cloud-native-management/meshery/integrations/github

Following are the list of checks and tasks to perform on the above listed integration.

1> Rewrite integration tagline.
2> Revise the features section and update it with the latest info.
3> Revise the overview section and update it with the latest info.
4> Update the images in "How it works section".

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
@legendarykamal I would like to work on this

**Comment by legendarykamal** [comment]
Yes Please do understand that we also need updated/added ss or videos in the how it works section. 

There exist a video of docker that I had added some time back, you may use that also.

**Comment by legendarykamal** [comment]
are you up for it 🎈 ?

**Comment by XDRAGON2002** [comment]
@legendarykamal well I was looking for some harder issues than the ones I have been working on, so I thought this would be a great way to challenge myself!

**Comment by legendarykamal** [comment]
Note:- I have updated the issue descriptions with the relevant links to increase the clarity.

**Comment by ronitblenz** [comment]
I want to take this issue, Could you please assign me?

**Comment by nitishmalang** [comment]
Hey I would like to work with this issue can you please assign me

**Comment by legendarykamal** [comment]
@ronitblenz is your setup up and running ?

**Comment by ronitblenz** [comment]
Yes it is... Running on local host

**Comment by legendarykamal** [comment]
ok go for it @ronitblenz

**Comment by ronitblenz** [comment]
Do I just need to rewrite the content on the page in my own words?
and please provide me with latest tutorials/videos/screenshots which are needed to be updated.

**Comment by legendarykamal** [comment]
the docker is updated by @UtkarshMishra12 , @ronitblenz you can update for the github and the contents of both ,

**Comment by UtkarshMishra12** [comment]
@ronitblenz please update

**Comment by subodhk01** [comment]
@UtkarshMishra12 Can I take this issue?

**Comment by UtkarshMishra12** [comment]
Here you go @subodhk01 🚀

**Comment by subodhk01** [comment]
@UtkarshMishra12 I see that I have to update and rewrite some text content. Can you share with me the updated content which needs to be updated?

**Comment by ronitblenz** [comment]
HI Utkarsh, thanks for assigning @subodhk01. I am inactive for sometime due to emergency.
