### ISSUE TITLE
[Improvement in description of Integration] Helm & Homebrew

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3263]
#### Current Behavior

Here are the relevant links:-

1> https://layer5.io/cloud-native-management/meshery/integrations/helm
2> https://layer5.io/cloud-native-management/meshery/integrations/homebrew

Following are the list of checks and tasks to perform on the above listed integration.

1> Rewrite integration tagline.
2> Revise the features section and update it with the latest info.
3> Revise the overview section and update it with the latest info.
4> Update the images in "How it works section".

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Roseline-Bassey** [comment]
Hey @legendarykamal, could you please assign me this issue?

**Comment by Roseline-Bassey** [comment]
Thanks for assigning me the issue. Should I require clarification, I'll get in touch with you via Slack.

**Comment by Roseline-Bassey** [comment]
Alright, this is helpful.

**Comment by Roseline-Bassey** [comment]
Hello @legendarykamal,

Could you please help clarify my doubts on this issue?

Based on my research, I do understand that Helm is a Kubernetes package manager that can create new charts, and packages, interact with charts, install and uninstall charts, and manage the release cycle of charts.

While Meshery is a service mesh orchestrator.

Regarding the overview section: should the overview be about how both tools work together? If so, could you point me to any documentation that'll help me understand how the integration works?

The Features Section

Helm has features such as being a package manager for Kubernetes, and a templating engine while Meshery has its features too.

Question: I'd like to know what features are required here, Meshery or Helms features? Or, the features of working with both tools?

This will also make the Homebrew section clearer to me.

**Comment by legendarykamal** [comment]
Hi, did you get your question being answered , if not then 

yes the overview section should contain on how both the tools work together . 

The features should essentially include things like how can Meshery prove to be in aid in working with the specific integrations.

a helpful doc could be - https://docs.meshery.io/installation/platforms/kubernetes#using-helm-charts .

**Comment by eeshaanSA** [comment]
@Roseline-Bassey updates?
