### ISSUE TITLE
Dark Mode Switch Delay

### ISSUE THREAD

**Issue by RamGoel** [layer5io/layer5#3266]
#### Description
When we switch between dark mode and light mode, the transition delay of home screen is different from that of navbar which seems like breaking.

#### Expected Behavior
The Transition delay should be same like this .

[screen-capture.webm](https://user-images.githubusercontent.com/71088429/193912167-21d52fe1-160c-49a8-86a6-53b9fa5f1498.webm)

#### Screenshots
[screen-capture (1).webm](https://user-images.githubusercontent.com/71088429/193911960-62db16e2-9977-4e8a-b52e-a4f9977a096d.webm)

#### Environment:
- Host OS:  Windows 10
- Browser:  Google Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by RamGoel** [comment]
Assign me this issue.

**Comment by lavakush07** [comment]
- I think this issue is already opened https://github.com/layer5io/layer5/issues/3060 
Correct me if I'm wrong

**Comment by RamGoel** [comment]
Hi, @lavakush07 the issue #3060 is about flickering of dark mode when page reload but this issue #3266 is about transition delay difference between homePage and Header. 

Thanks 👍

**Comment by rakshitgondwal** [comment]
I was going through the website the other day and I also tried to switch to the light mode and saw this bug but my bad I thought that it was some kind of special effect or was done intentionally lol.
If you don't mind, can we try solving this issue together? I would also like to work on this @RamGoel

**Comment by legendarykamal** [comment]
hello gents thank you for showing concerns over this  but how does it appear to be breaking ? 
frankly it doesn't and is totally intentional and gives a good feel. 

I am open for more arguments and clarifications , if you feel.

**Comment by RamGoel** [comment]
> hello gents thank you for showing concerns over this but how does it appear to be breaking? frankly, it doesn't and is totally intentional and gives a good feel.
> 
> I am open to more arguments and clarifications if you feel.

Hi @legendarykamal @leecalcote @Nikhil-Ladha , I think giving a transition delay of 0.5s to both header and the home screen is a perfect combination.

and one more thing I want to mention that the home screen varies everytime you open the site. and the screen I shared in video has the issue only. other ones are looking good.

**Comment by RamGoel** [comment]
I think we can move forward with this, let me get on it. Could you please assign it to me.

**Comment by Nikhil-Ladha** [comment]
@RamGoel on a separate note what changes did you make to avoid that flickering/transition issue, in the video shared in the issue description?

**Comment by Nikhil-Ladha** [comment]
Also, I doubt you might have any progress on using the plugin I shared earlier, it requires a lot of changes in the stylesheet which might not be feasible for us.
Try using the plugin https://www.gatsbyjs.com/plugins/gatsby-plugin-use-dark-mode/, though you might get an issue while installing the `use-dark-mode` package mentioned in the plugin page, so in that case, install the package from this repo: https://github.com/donavon/use-dark-mode/pull/68

**Comment by RamGoel** [comment]
> @RamGoel on a separate note what changes did you make to avoid that flickering/transition issue, in the video shared in the issue description?

@Nikhil-Ladha I have just removed the transition delay from the header so that that it matches the transition delay of home page.

**Comment by Nikhil-Ladha** [comment]
Where is the transition delay in the code 🤔

**Comment by RamGoel** [comment]
No just the CSS property from the inspect.

**Comment by Nikhil-Ladha** [comment]
Ok! Got it.
There might be a second set of changes required even after the plugin is incorporated.
We would need to update those CSS values for transition properties to be limited to only the changes that are actually happening. That is avoid using `all` so that when there are color/background-color changes there isn't a delay.

Though lets have that plugin added and use that for changing the theme and then we will see if the above change would be needed or not

**Comment by UtkarshMishra12** [comment]
@RamGoel Please Update

**Comment by leecalcote** [comment]
Is the site still experiencing this issue?

**Comment by senali-d** [comment]
> Is the site still experiencing this issue?

@leecalcote Now there is no any kind of delay.


https://user-images.githubusercontent.com/52546856/225902784-7c546ca6-ba48-4662-981d-74e235dfbecb.mp4

**Comment by leecalcote** [comment]
@senali-d guess what? The meshery.io website similarly suffers this issue.

**Comment by senali-d** [comment]
> @senali-d guess what? The meshery.io website similarly suffers this issue.

@leecalcote Yeah it's happen due to the transition set to the header shadow.

Header shadow styles something as follows.
```
header.header-shadow {
    box-shadow: #00b39f 1px -27px 57px;
    transition: background-color 0.2s ease;
    text-shadow: none;
}
```

`transition: background-color 0.2s ease;` This transition delay effects the issue.

**Comment by randychilau** [comment]
Hi All,

I believe this issue has been resolved by [PR# 4003](https://github.com/layer5io/layer5/pull/4003).

The fix was to have the same transition settings:

![image](https://github.com/layer5io/layer5/assets/90356410/1f177799-4c71-4154-bb51-fe2c25ac4e58)

in the `body` globalStyle css in the file `src/sections/app.style.js` 
as well as in the navigation css in the file `src/sections/General/Navigation/navigation.style.js`

Live site demo:

[delay_fixed.webm](https://github.com/layer5io/layer5/assets/90356410/bb90f331-0d25-4147-afc2-6c6cd960ad12)

Based on the information above, I propose this issue should be closed.

Cheers,
Randy
