### ISSUE TITLE
Different size of subscribe botton and email address box

### ISSUE THREAD

**Issue by AbhishekTiwari23** [layer5io/layer5#3268]
#### Description

I found that the email and subscribe buttons on the layer landing page are not the same size, and there is bid space/margin between them, which does not look great.
#### Expected Behavior

Both buttons should be the same size and have a minimum space between them.

#### Screenshots

<img width="1440" alt="Screenshot 2022-10-06 at 12 06 24 AM" src="https://user-images.githubusercontent.com/97469132/194136526-0000299d-7863-4bb3-8c80-7613f8ef9cc3.png">

#### Environment:
- Host OS: 
- Browser: GOOGLE

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AbhishekTiwari23** [comment]
I would like to work on this issue, if you consider it a genuine one then please allow me to contribute

**Comment by legendarykamal** [comment]
@AbhishekTiwari23 did your browser load fully , 
As I find them to be of the same size 
![image](https://user-images.githubusercontent.com/95926324/194218550-f0542cdf-1542-4313-8a20-b5ef22bec369.png)

**Comment by AbhishekTiwari23** [comment]
> @AbhishekTiwari23 did your browser load fully , As I find them to be of the same size ![image](https://user-images.githubusercontent.com/95926324/194218550-f0542cdf-1542-4313-8a20-b5ef22bec369.png)

Sir, please have a look at this photo, it might be you are using a big screen or a window's os, but it is a genuine issue
![WhatsApp Image 2022-10-06 at 7 17 35 PM](https://user-images.githubusercontent.com/97469132/194330615-3a42437b-0fab-44be-98dc-bdf992271cd3.jpeg)

**Comment by AbhishekTiwari23** [comment]
> ok I rechecked , but could not replicate . @Chadha93 can you confirm in please.

@legendarykamal hello sir, I did not get any response, please let me know if this is a genuine one or not.
