### ISSUE TITLE
Overlap of text in service-mesh-landscape

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3271]
Description
in https://layer5.io/service-mesh-landscape two title texts overlap with each other.

Expected Behavior
Both texts should be separated from each other

#### Screenshots

![image](https://user-images.githubusercontent.com/95926324/194326849-9d674ee0-290d-469d-bab9-7f16e997133a.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by PriyanshuAhlawat** [comment]
I will like to work on it, pls assign

**Comment by legendarykamal** [comment]
yes please ,update us soon .

**Comment by legendarykamal** [comment]
hello gents, since there hasn't been an update long yet and you are not done with the local setup.
Please do before asking to work on any issue @PriyanshuAhlawat .

Understanding the priority of the issue ,I am pushing in a PR . feel free to engage in other areas that need `help`
