### ISSUE TITLE
Footer: Social media logos are not aligned with the layer 5 logo.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3274]
#### Current Behavior
Social media logos are not aligned with the layer 5 logo.
![Screenshot 2022-10-07 123820](https://user-images.githubusercontent.com/85894871/194492287-35056b5b-bfc0-4391-9527-fbf365b4f7cd.png)

#### Desired Behavior
![Screenshot 2022-10-07 123911](https://user-images.githubusercontent.com/85894871/194492344-8e694764-f288-4278-b43e-c219d9840b6e.png)

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shubhamdutta2000** [comment]
I would like to work on this issue

**Comment by JayKania** [comment]
Hi @Shubhamdutta2000 , if you are not working on the issue then do let me know. I would like to work on it

**Comment by AbhishekTiwari23** [comment]
I am also ready with my setup. Please assign if it is still uncompleted

**Comment by Shubhamdutta2000** [comment]
I am working on this issue

**Comment by Nikhil-Ladha** [comment]
@Shubhamdutta2000 what's the status here?

**Comment by AbhishekTiwari23** [comment]
If there is no update, then please let me know. My setup is ready.

**Comment by Nikhil-Ladha** [comment]
Unassigning @Shubhamdutta2000 and considering @sandeepB3 PR #3276  for this issue.
