### ISSUE TITLE
Bottom white line upon focus in table tabs

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3277]
#### Description
A white solid line appears at the bottom when a tab is in focus state in table component.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194639689-b8a223dd-adbb-40a1-90b0-53f62e95accd.png">

<br>

#### Expected Behavior
Such white line should probably not exist in focus state as it doesn't go well with the UI and doesn't exist in any other state as well . Below image should be the expected behavior.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194639471-47aea393-de3d-423b-8a7e-96f99e89f562.png">

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Kindly assign me this issue. Would like to work on this.

**Comment by leecalcote** [comment]
Good eye and good suggestion, @GaganpreetKaurKalsi 👍
