### ISSUE TITLE
Right table borders

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3278]
#### Description
In reference to the below attached image, after carefully looking, you can see right borders visible when a row is hovered at. When we hover at white rows, white right borders are visible and when we hover at gray rows, gray borders are visible.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194641009-c6a493e6-4401-40fd-b73f-a1e41722541f.png">

#### Expected Behavior
The borders shouldn't be visible in all sorts of scenarios; when hovered at and when not hovered at.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194641723-8082800e-4dab-403d-9df1-dca394479b06.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194641904-3fdc2ce2-feb1-46e7-95ee-fc3017412528.png">

#### Possible Solution
Either we can remove the right borders completely, or we can change the border-color to match the background-color upon hover.

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Would like to work on this. Kindly assign me this issue.

**Comment by rohanyrane** [comment]
Please assign me this issue. I would like to work on this

**Comment by GaganpreetKaurKalsi** [comment]
What do you think about this issue @leecalcote @legendarykamal ?
Should this be resolved? This issue appears in both dark and light mode.

If yes, then kindly assign it to me. Will make the necessary changes.

**Comment by legendarykamal** [comment]
@GaganpreetKaurKalsi the lines are very faintly visible and even if they are, they differentiate the column's better. 
Changes aren't needed here in my opinion unless a maintainer feels so, till then 'no not needed'.
