### ISSUE TITLE
Tooltip hidden for the last row in table

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3279]
#### Description
Due to the size of the tooltip, the tooltip doesn't find space to render at top or left so it renders below the text and therefore gets hidden.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194645131-995a9a05-8bfb-40b3-83c5-64787c76a0de.png">

#### Expected Behavior
The tooltips should be visible for all cells of the last row.

#### Possible solution
We can determine a max-width value for all the tooltips so that they don't exceed a particular length. Also at some places the text is too long. Having such a long tooltip doesn't look very good.

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Would like to work on this issue. Kindly assign it to me.

**Comment by leecalcote** [comment]
This is a valid bug. Is part of what you're thinking, @GaganpreetKaurKalsi, to use `text-overflow: ellipsis;`?

**Comment by GaganpreetKaurKalsi** [comment]
> This is a valid bug. Is part of what you're thinking, @GaganpreetKaurKalsi, is to use `text-overflow: ellipsis;`?

No, if we use ```text-overflow: ellipsis;``` then the user won't be able to see the complete text. I am thinking of restricting the width of the tooltip container to some max value so that when the text inside takes up more space than the container width, it will wrap in the next line.
