### ISSUE TITLE
Spelling error (navtive)

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3280]
#### Description
Spelling mistakes
- navtive
- candidancy
- futhered

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194651175-2fb7aae8-3d16-46a2-87a5-741dc0e4ebb9.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194652051-d326ae2f-a2e9-4407-ac06-7280b2e844fe.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194652662-b532cef4-0c53-43dd-918e-c23ea027ca29.png">

#### Expected Behavior
- navtive -> native
- candidancy -> candidacy
- futhered -> furthered

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Would like to fix this. Kindly assign it to me.

**Comment by leecalcote** [comment]
Gosh, what is a "cloud navtive" anyway? 😆 

Thank you, @GaganpreetKaurKalsi.

**Comment by GaganpreetKaurKalsi** [comment]
> Gosh, what is a "cloud navtive" anyway? 😆
> 
> Thank you, @GaganpreetKaurKalsi.

Haha! guess will be reading the whole site to find such errors 😅


Another one is here. Issue with the article.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194656237-b899828a-990f-48f2-bd40-e0dcdde966aa.png">

**Comment by leecalcote** [comment]
Oh, my goodness. Another one. 😮

**Comment by legendarykamal** [comment]
> Gosh, what is a "cloud navtive" anyway? 😆
> 
> Thank you, @GaganpreetKaurKalsi.

cloud navtive might be a new subset of cloud native 😄 .
