### ISSUE TITLE
3 different card styles in the same review section on the pricing page.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3281]
#### Description
3 different card styles in the same review section on the pricing page.

#### Expected Behavior
The cards must be of one type and the dimensions also should be the same.

#### Screenshots
![Screenshot 2022-10-08 060933](https://user-images.githubusercontent.com/85894871/194678994-2bea697d-23de-45ac-9729-735d01b16ceb.png)

#### Environment:
- Host OS: Windows
- Browser: Chrome/Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sandeepB3** [comment]
I would like to work on this. Please assign me.

**Comment by sandeepB3** [comment]
Of the three patterns which single pattern would be preferred ?
<img width="1402" alt="Screenshot 2022-10-08 at 1 11 20 PM" src="https://user-images.githubusercontent.com/107111616/194696301-26d9a63d-21ef-4ebe-a8aa-624402ab3bca.png">
**Type2, Type1, Type3** 
The card types are in the above order respectively

**Personally I prefer Type2**

**Comment by sandeepB3** [comment]
<img width="1440" alt="Screenshot 2022-10-08 at 3 54 34 PM" src="https://user-images.githubusercontent.com/107111616/194702893-1dcf071f-e2ac-4b25-a9b5-5e712cabea68.png">

**Is this okay?**

**Comment by leecalcote** [comment]
Thanks for this, @Krishna2323. This behavior is by design.
