### ISSUE TITLE
Smoothly displaying the answers in the FAQ on page /careers/programs.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3286]
#### Current Behavior
The display of answers is sudden.
https://user-images.githubusercontent.com/85894871/194710935-927aea98-73f9-4a4c-91f4-4b022be94755.mp4

#### Desired Behavior
The transition must be smooth.
https://user-images.githubusercontent.com/85894871/194710950-9151c4ae-40a5-47f2-a3d3-389e81254adb.mp4

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Krishna2323** [comment]
I want to work on this issue.

**Comment by Nikhil-Ladha** [comment]
Still interested in working on this issue?

**Comment by janvi01** [comment]
I would like to work on this issue if available. @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Go ahead @janvi01

**Comment by rohanyrane** [comment]
Please assign me this issue
I have my local setup ready

**Comment by janvi01** [comment]
Hey @rohanyrane, you can take up this issue. Do reach out for any help :)

**Comment by ryrGlobalshala** [comment]
@Nikhil-Ladha can you please assign me this issue

**Comment by Nikhil-Ladha** [comment]
Cool, go ahead

**Comment by UtkarshMishra12** [comment]
@rohanyrane Please update

**Comment by UtkarshMishra12** [comment]
@rohanyrane Progress ????(last chance)

**Comment by shiv123-max** [comment]
@leecalcote, I want to work on this issue.

**Comment by Nikhil-Ladha** [comment]
Go ahead @shiv123-max

**Comment by HemanthPaila** [comment]
@leecalcote and @Nikhil-Ladha if it is still open I would like to work on this issue.
could you please assign it to me?
