### ISSUE TITLE
The blog cards on the blogs page is not responsive.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3287]
#### Description
The blog cards on the blog page is not responsive.
![Screenshot 2022-10-08 193715](https://user-images.githubusercontent.com/85894871/194711686-eba5e44a-a86d-4eab-b4da-b87b74e4c653.png)

#### Expected Behavior
![Screenshot 2022-10-08 193634](https://user-images.githubusercontent.com/85894871/194711693-a6c6462d-72f0-48f2-a8a7-b9b6fe68970a.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Krishna2323** [comment]
Would like to work on that.

**Comment by AbhishekTiwari23** [comment]
I tried hard but was not able to detect it. If it is a real issue, then I also want to give it a try

**Comment by legendarykamal** [comment]
thankyou @Krishna2323 for raising but the blog page is completely responsive. I checked and recheked 💯

**Comment by Krishna2323** [comment]
@legendarykamal pls recheck it with the other view option.
![Screenshot 2022-10-08 193715](https://user-images.githubusercontent.com/85894871/194732017-0edceb55-7870-4c0a-8d6c-b49bec20ce28.png)

**Comment by legendarykamal** [comment]
ah you see how words play with us, Please
1> Modify the title with the blog cards on the ''list view''  with the appropriate px ratio you have experienced the issue.
2> this will require the tags to be moved down (from the ss you shared). are we ok with that ?

**Comment by Krishna2323** [comment]
@legendarykamal pls check now.
