### ISSUE TITLE
Overlapping of the text with logo

### ISSUE THREAD

**Issue by AbhishekTiwari23** [layer5io/layer5#3288]
#### Description
The text overlaps with the logo.

#### Expected Behavior
There should be no overlapping, similar to others.

#### Screenshots
<img width="1440" alt="Screenshot 2022-10-08 at 8 26 58 PM" src="https://user-images.githubusercontent.com/97469132/194714973-5ad44fda-f872-466b-91d3-3cda2bb755de.png">

#### Environment:
- Host OS: Mac os
- Browser: Google

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sidd-kointrack** [comment]
Can I work on this issue? @AbhishekTiwari23

**Comment by AbhishekTiwari23** [comment]
Please assign this issue to me.

**Comment by AbhishekTiwari23** [comment]
This issue arises because of the large text setting in my browser. Now I realise it, if you do not consider it genuine, then please close this one. Thanks

**Comment by legendarykamal** [comment]
was the previous one "email address" also due to your browser settings ? 

closing this in the lieu of already fixed , Thanks.

**Comment by AbhishekTiwari23** [comment]
> was the previous one "email address" also due to your browser settings ?
> 
> closing this in the lieu of already fixed , Thanks.

ya, I think so. Thanks for your support.

**Comment by AbhishekTiwari23** [comment]
> was the previous one "email address" also due to your browser settings ?
> 
> closing this in the lieu of already fixed , Thanks.

No, that now arrises in my tablet, and this one is because of my mac book.

**Comment by AbhishekTiwari23** [comment]
@legendarykamal, sir, I am waiting for pr #3275 to be merged. Please have a look. Thanks
