### ISSUE TITLE
Subscribe to news letter button is not responsive

### ISSUE THREAD

**Issue by AbhishekTiwari23** [layer5io/layer5#3290]
#### Description
The subscribe to newsletter button is not responsive to reducing the window size.
#### Expected Behavior
It should be responsive in all cases.

#### Screenshots

![WhatsApp Image 2022-10-08 at 8 31 52 PM](https://user-images.githubusercontent.com/97469132/194715348-6ae112c3-6648-4fab-8146-8e67e42ac2b6.jpeg)

#### Environment:
- Host OS: Android/ Lenovo tablet horizontal alignment
- Browser: Google

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AbhishekTiwari23** [comment]
If this is a genuine one, please allow me to work on it.

**Comment by AbhishekTiwari23** [comment]
This issue arrises because of the large text setting in my browser. Now I realised it, if you do not consider it as a genuine one, then please close this one. Thanks

**Comment by legendarykamal** [comment]
@AbhishekTiwari23 its perfectly responsive , Sorry will have to close this.
