### ISSUE TITLE
"No results found" row when data not present in table

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3295]
#### Current Behavior
When there is no data to show in table upon filter-by-search, table has no body to show.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194771634-0aff207d-aa9a-4857-9f61-2577d5eacdc9.png">

#### Desired Behavior
We can display a row stating "No results found" or "No data found". This tells user that what he/she is looking for isn't available/found.
**Better User Experience**

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54144759/194771726-2c8d4921-36a7-4b05-a41b-dfa96d933756.png">

#### Implementation
When there are no rows, render a row with single column spanning the entire row with message "No results found".

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
If this feels like a desired enhancement, the kindly assign me to this issue. Would like to work on it.

**Comment by Nikhil-Ladha** [comment]
Seems fair.
Also, the suggestion looks good. Go ahead and work on making a PR for it.
