### ISSUE TITLE
[UI]The Related Integration page should show white SVGs instead of Colored.

### ISSUE THREAD

**Issue by Harshit-Dandriyal** [layer5io/layer5#3298]
#### Description

[UI]The Related Integration page should show white SVGs instead of Colored.

https://user-images.githubusercontent.com/56961488/194870275-982f593e-6827-45db-8739-2eb382cc23b4.mp4

#### Environment:
- Host OS: Ubuntu
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by amit-ksh** [comment]
I want to work on this. Please assign this to me.

**Comment by sandeepB3** [comment]
Would like to be assigned, to work on this. Thank you!

**Comment by amit-ksh** [comment]
> Yes of course

**Comment by amit-ksh** [comment]
BTW issue video is not playing

**Comment by Harshit-Dandriyal** [comment]
> BTW issue video is not playing

It's playing in my browser :thinking:

**Comment by Harshit-Dandriyal** [comment]
ok @amit-ksh Assigning it to you, I hope you will not take much time. All the best.
@sandeepB3 There may be many issues like this in Layer5 I hope you will be able to find more.

**Comment by AbhishekTiwari23** [comment]
If the issue still open then I am ready with my setup
