### ISSUE TITLE
Add Istio Vet to tools section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#33]
@nrjpoddar, if you're inclined to add [Istio Vet](https://github.com/aspenmesh/istio-vet) to the tools ([code here](https://github.com/layer5io/layer5/blob/master/_includes/service-mesh-tools.html))section of this [landscape](https://layer5.io/landscape/#tools), we'd welcome its listing.

**Comment by leecalcote** [comment]
@m-eaton^^

**Comment by nrjpoddar** [comment]
@leecalcote that would be great. I will submit a PR to get istio-vet listed. Thanks!

**Comment by leecalcote** [comment]
Fantastic, @nrjpoddar!
