### ISSUE TITLE
Parameter Tampering Issue

### ISSUE THREAD

**Issue by Onyx2406** [layer5io/layer5#3302]
#### Description
Site: https://layer5.io/company/contact
Through this bug, a user can change the "Scope of Question" which is not given on the form and it is not expected from someone to ask question which is not related to "Scope of Question" given on the contact form. The changed Scope of Question also reflects in the auto email sent to the user after the form is submitted.
#### Expected Behavior
Forwarded Request:
```
POST /gguommoyd14634ur9xs7l37widuoa7e9 HTTP/2
Host: hook.us1.make.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
Content-Length: 173
Origin: https://layer5.io
Dnt: 1
Referer: https://layer5.io/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Te: trailers

{"memberFormOne":{"subscribed":false,"firstname":"test","lastname":"test","email":"yashsancheti24@gmail.com","subject":"test","message":"test","scope":"test","form":"contact"}}
```
Maybe using some encrypted text in scope can solve this issue.
#### Screenshots
![image](https://user-images.githubusercontent.com/32770175/194943310-c6de3042-6790-4a1c-aad1-78053321612f.png)
![image](https://user-images.githubusercontent.com/32770175/194943579-843ccaae-cca9-430f-a5d8-b437d81817c3.png)

#### Environment:
- Host OS: Windows 11
- Browser: Google Chrome

#### Checklists:
- [ ] Disallow strings to scope which are not allowed.
- [ ] Apply rate limit on number of times the form is submitted.
- [ ] Check if a user can change "subscribed":false to "subscribed":true to subscribe "email":"xyz".
- [ ] Resolve #3291 which is on this form as well.
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Nikhil-Ladha** [comment]
What's the reproducer?

**Comment by Nikhil-Ladha** [comment]
Well, encryption is not needed, just adding a check in the backend to check if the scope is either of these 5 would do.

**Comment by Onyx2406** [comment]
> What's the reproducer?

I used this request capturing and forwarding tool - Burp Suite.

**Comment by Onyx2406** [comment]
> Well, encryption is not needed, just adding a check in the backend to check if the scope is either of these 5 would do.

Can you assign me this so I can try to solve this? Thanks

**Comment by Nikhil-Ladha** [comment]
> > Well, encryption is not needed, just adding a check in the backend to check if the scope is either of these 5 would do.
> 
> Can you assign me so I can try to solve this? Thanks

Unfortunately this is something you won't be able to solve, since the accounts are restricted for access.
Either me or @debo19 will have to fix this.

**Comment by Onyx2406** [comment]
> > > Well, encryption is not needed, just adding a check in the backend to check if the scope is either of these 5 would do.
> > 
> > 
> > Can you assign me so I can try to solve this? Thanks
> 
> Unfortunately this is something you won't be able to solve, since the accounts are restricted for access. Either me or @debo19 will have to fix this.

okay sure, no problem

**Comment by leecalcote** [comment]
Thank you for filing this, @Onyx2406. While the fix will ultimately be done in a separate system, this _is_ something that you can participate in seeing to resolution. And it's certainly something that we appreciate you engaging with us on. This is helpful. Soon, hopefully, there will word on readiness of testing of a solution that has been implemented and confirmation of the details of that solution (i.e. the rules / checks / protections that have been put in place) and your verification of it.

**Comment by leecalcote** [comment]
@Onyx2406 do you go by `tonyjack1121@gmail.com` in your tests? I'm just confirming that those are from you and not another nefarious actor.

**Comment by Onyx2406** [comment]
> @Onyx2406 do you go by `tonyjack1121@gmail.com` in your tests? I'm just confirming that those are from you and not another nefarious actor.

Yes, its mine which I used just to test from different email.

**Comment by Onyx2406** [comment]
> Thank you for filing this, @Onyx2406. While the fix will ultimately be done in a separate system, this _is_ something that you can participate in seeing to resolution. And it's certainly something that we appreciate you engaging with us on. This is helpful. Soon, hopefully, there will word on readiness of testing of a solution that has been implemented and confirmation of the details of that solution (i.e. the rules / checks / protections that have been put in place) and your verification of it.
> 
> @Onyx2406, to help advance a solution, if you were to list the cases that need to be covered as a checklist, that would be helpful. Example:
> 
> * [ ]  Disallow strings entered into the email address field that are non-conformant to `<alphanumberic+more-alphanumeric@domain.tld>`

Thank you @leecalcote for checking out this issue! I will edit the post soon and list the cases which needs to be covered.

**Comment by UtkarshMishra12** [comment]
@Onyx2406 Please update
