### ISSUE TITLE
[Mailing List] Make all the items width equal.

### ISSUE THREAD

**Issue by legendarykamal** [layer5io/layer5#3303]
#### Description

It looks odd currently.

![image](https://user-images.githubusercontent.com/95926324/195170731-dde05f6a-ef28-42ab-ad4c-269d273906ec.png)

#### Expected Behavior

All of the widths should be same.
#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
// @Krishna2323

**Comment by legendarykamal** [comment]
Oh 😅 yes my bad! wrong repo , opened it in here -> https://github.com/meshery/meshery.io/issues/868.

**Comment by leecalcote** [comment]
No sweat. 👍
