### ISSUE TITLE
Alignment and gap between title and inputs in subscribe section before the footer looks.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3304]
#### Current Behavior
The subscribe section before the footer looks because of the gap between the form heading and inputs is too much.
SS:
![Screenshot 2022-10-12 094608](https://user-images.githubusercontent.com/85894871/195249130-a383497a-e5df-45fc-a1f0-46ac2665d77b.png)

#### Desired Behavior
![Screenshot 2022-10-12 094426](https://user-images.githubusercontent.com/85894871/195249169-9d0d8deb-9a1d-47d5-a9aa-7626e2ef10bb.png)
#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Nikhil-Ladha** [comment]
I don't think any change in the design is needed. The current behavior is by design and looks completely fine.

**Comment by Krishna2323** [comment]
@Nikhil-Ladha ,Ok.

**Comment by Krishna2323** [comment]
No change is needed.
