### ISSUE TITLE
Spell errors

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3305]
#### Description
Spelling errors
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195288067-86088812-4c08-4810-abbe-3f015001788b.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195288782-426a8d5f-2b3b-4008-8ac5-32f5e1424bc7.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195289972-8d5b86f9-5430-45b8-9d3a-a56ee89fa613.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195292913-b1903ea7-c453-46b2-a90e-078f4d5a3636.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195293704-95519610-29b2-41d7-9c51-2dd51cb634cc.png">

#### Expected Behavior
- Confidentally -> Confidently
- to get access the extension -> to get access to the extension.
- learing -> learning
- optimatal -> optimal _(Don't think optimatal is an actual word. Correct me if I am wrong.)_
- Adapative -> Adaptive

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rghdrizzle** [comment]
Hey can i fix these errors ??
