### ISSUE TITLE
The VULCAN logo looks too small on Landscape page.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3306]
#### Description
The VULCAN logo looks too small on Landscape page.
![Screenshot 2022-10-12 164620](https://user-images.githubusercontent.com/85894871/195329376-e9de0861-34d5-41ab-a65d-09ba22da1c80.png)

#### Expected Behavior

![Screenshot 2022-10-12 164549](https://user-images.githubusercontent.com/85894871/195329397-97645d24-6ef1-442c-83e3-10c850712e4c.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by rghdrizzle** [comment]
Hey I would like to work on this.

**Comment by eeshaanSA** [comment]
Go ahead, @rghdrizzle.

**Comment by AbhishekTiwari23** [comment]
My setup is ready. Let me know if I can contribute.

**Comment by eeshaanSA** [comment]
This is already a work in progress issue, @AbhishekTiwari23, we'll find you another one. 🙂
