### ISSUE TITLE
Is this VULCAN or VULCAND.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3307]
#### Description
Seems like a spelling mistake to me.
![spelling-issue](https://user-images.githubusercontent.com/85894871/195330080-ffb66d2b-1725-41b3-ad21-c934be12b2f6.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sandeepB3** [comment]
It is spelled as Vulcand. The logo in the documentation shows Vulcan.  
https://vulcand.github.io/#documentation

**Comment by Krishna2323** [comment]
Thanks, @sandeepB3.
