### ISSUE TITLE
Add attribution to Service Mesh Interface compatibility section

### ISSUE THREAD

**Issue by HPrinz** [layer5io/layer5#331]
**Current State:**

[meshes.yml](https://github.com/layer5io/layer5/blob/master/_data/landscape/meshes.yml) contains information about Service Mesh Interface compatibility. The content and links seem to be based on data at [servicemesh.es](https://servicemesh.es).

**Desired State:**

All data at servicemesh.es can is meant to be copied and used for any purpose, however the attribution (https://creativecommons.org/licenses/by/4.0/) appears to be missing.

**Comment by gunjanmimo** [comment]
@HPrinz should I add attribution for every category?

**Comment by HPrinz** [comment]
Once below the table would be totally sufficient, thanks!
For example "Based on [servicemesh.es](https://servicemesh.es) by [INNOQ](www.innoq.com) / [CC 4.0](https://creativecommons.org/licenses/by/4.0/)"

**Comment by ashiscs** [comment]
@HPrinz sir, is it okay??

**Comment by HPrinz** [comment]
Yes, thank you

**Comment by ashiscs** [comment]
Opening this again sir, as the pr is not merged!!
