### ISSUE TITLE
Social media logos is placed before Layer5 logo.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3311]
#### Description
Social media logos is placed before Layer5 logo.
![Screenshot 2022-10-13 092822](https://user-images.githubusercontent.com/85894871/195496193-6de6f301-118b-445b-8992-cb06f1807280.png)

#### Expected Behavior
![Screenshot 2022-10-13 092909](https://user-images.githubusercontent.com/85894871/195496202-dd27da52-4036-4e28-9653-5a249683819b.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by najeebkp** [comment]
Hi @Krishna2323  please assign this to me

**Comment by Nikhil-Ladha** [comment]
This is by design, no update needed here :)

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, oops, looks like I am really bad at design😂.
