### ISSUE TITLE
Grammatical mistakes: shutdown or Shutdown. 

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3312]
#### Description
In half of the places, the work shutdown is capitalized and in another half, it is not.
![Screenshot 2022-10-13 104711](https://user-images.githubusercontent.com/85894871/195508657-b761fe34-a5f7-4058-8ee2-6850e09e3202.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AbhishekTiwari23** [comment]
My setup is ready. Let me know if I can contribute.
