### ISSUE TITLE
[Site] Remove the code block, switch to normal

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3315]
#### Description
The Traefik Mesh page has a code block that is not desired for [improved security]( https://layer5.io/cloud-native-management/meshery/integrations/traefik-mesh).
![image](https://user-images.githubusercontent.com/65453826/195634134-4ecfa968-b552-42c5-b244-cbcbcd6fe20e.png)

#### Expected Behavior
Remove the code block and keep the regular text/typography.

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by XDRAGON2002** [comment]
I would like to work on this.

**Comment by UtkarshMishra12** [comment]
Hey, @Chadha93 I would like to work on this issue. So we need to remove the block and present the text in the same manner as shown above?

**Comment by leecalcote** [comment]
@UtkarshMishra12, remove the `<code>` block and we should be able to leave the text as-is.

Have you previously worked on this site/with Gatsby?

**Comment by UtkarshMishra12** [comment]
@leecalcote Not yet

**Comment by leecalcote** [comment]
Thanks, @AbhishekTiwari23

**Comment by AbhishekTiwari23** [comment]
> Thanks, @AbhishekTiwari23

Thanks, sir, for appreciating me,  and I am learning all the stuff which helps me to be a part of this outstanding community

**Comment by AbhishekTiwari23** [comment]
I have a doubt. I have to remove that scrolling effect and put the text(which is inside the block ) and put the text as a normal para. Right?

**Comment by Chadha93** [comment]
> [Contributor ](https://github.com/layer5io/layer5/commits?author=AbhishekTiwari23)

Yes, remove the code block and keep the normal text.

**Comment by AbhishekTiwari23** [comment]
Ok, thanks

**Comment by AbhishekTiwari23** [comment]
<img width="1440" alt="Screenshot 2022-10-15 at 1 14 48 AM" src="https://user-images.githubusercontent.com/97469132/195929304-aea28c3b-1357-462b-b000-796686c9a1f7.png">

Is it okay? @Chadha93 sir.

**Comment by AbhishekTiwari23** [comment]
<img width="1440" alt="Screenshot 2022-10-15 at 1 17 39 AM" src="https://user-images.githubusercontent.com/97469132/195929692-c7c4569b-9fe4-4879-9c36-fe49f3a554c9.png">

**Comment by AbhishekTiwari23** [comment]
Should I make a pr now?

**Comment by legendarykamal** [comment]
yes looks good @AbhishekTiwari23 make a PR 👍

**Comment by AbhishekTiwari23** [comment]
Ok, thanks, sir.

**Comment by Ritikkumar992** [comment]
Hey, @Chadha93 I would like to work on this issue. So we need to remove the block and present the text in the same manner as shown above?

**Comment by Chadha93** [comment]
> Hey, @Chadha93 I would like to work on this issue. So we need to remove the block and present the text in the same manner as shown above?

Thanks for jumping in @Ritikkumar992. I see this issue is already completed by @AbhishekTiwari23 's recent PR. Feel free to take a look at other issues.
