### ISSUE TITLE
Blank value needs to be removed on learn/service-mesh-books/service-mesh-patterns

### ISSUE THREAD

**Issue by sam1code** [layer5io/layer5#3320]
#### Description
A blank value for sorting is present in the filtering option of the page learn/service-mesh-books/service-mesh-patterns. Which needs to be removed.

#### Screenshots
![Screenshot from 2022-10-15 01-18-18](https://user-images.githubusercontent.com/74086891/195930448-0dd53ea7-e34e-4738-9462-3540edb61c09.png)

#### Environment:
- Host OS: any 
- Browser: any

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
I would like to work if this is accepted!

**Comment by leecalcote** [comment]
Thank you, @sam1code. Good eye. Yes, this a valid bug.

**Comment by sam1code** [comment]
Thankyou @leecalcote
