### ISSUE TITLE
Make check, half check, cross images consistent across all platforms

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3321]
**Current Behavior**

The check icons aren't consistent across all platforms. Below are the 3 places I could find there occurrence in. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195929241-67607e0d-920f-482a-b235-57c04e862153.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195929837-955e0931-c910-42d5-b39e-b77d7626a377.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/54144759/195931832-e7a2a338-c3c4-48b7-93cb-c652e84b0372.png">

**Desired Behavior**
The check, half-check and cross icons should follow the same pattern across all areas; same icon-type and colors everywhere.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
"Consistency" is a keyword around these parts. Great UX is built on such words.

**Comment by GaganpreetKaurKalsi** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195999408-3c8eff6e-da98-462a-9854-2cec20ace07c.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195999424-3312ceec-d5c7-4d61-ba87-0690607e1d4a.png">


Hey @leecalcote ! I saw at these places there are 2 green ticks and 1 red cross. Should there be a yellow half tick in-place of 1 green tick so the order becomes
- green tick
- yellow half tick
- red cross

Let me know if it sounds correct.

**Comment by leecalcote** [comment]
@GaganpreetKaurKalsi yes, that sounds great. There's one other possibility: "N/A". You'll see this "N/A" in the Compatibility Matrix in Meshery Docs. There is an SVG for the "N/A" and an SVG containing the red X, and green checkmark in the Layer5 Community drive.

**Comment by GaganpreetKaurKalsi** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/196005556-b4db12a8-78cf-4491-91ab-ea9433ad7017.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/196005570-34f39970-e43e-4a3b-8230-d5867427beef.png">

Does the question mark icon and the N/A icon, mean the same? Should one be replaced by other to have consistency at both places?

Also we don't have a legend for the compatibility matrix in meshery docs. Will need to add one in there too to better understand the meaning of each icon. Also what does N/A exactly mean. I see it has some negative values.

@leecalcote

**Comment by GaganpreetKaurKalsi** [comment]
@leecalcote Also let me know what do you prefer ?
- A half yellow check
- or a full yellow check

After adding yellow checks the new images would look like this
<img width="895" alt="image" src="https://user-images.githubusercontent.com/54144759/196007043-58be8824-d889-4f90-b1c5-f9a4000a1d40.png">

**Comment by leecalcote** [comment]
@asubedy, you might have comments here.

**Comment by leecalcote** [comment]
Good point, @GaganpreetKaurKalsi. With the new color of yellow introduced to the set, the half checkmark version is send completely necessary as the yellow color conveys the concept of incompleteness as-is without having to be cut in half. My vote is for the full, yellow circle.
