### ISSUE TITLE
Improve dark-mode colors for table

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3322]
**Current Behavior**
The current dark-mode color combination looks too dark with white borders visible and white color for the selected tab. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195933815-4d758460-491b-4cae-9e6c-a00aeac88047.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195934128-6124438d-0f67-4d71-8002-84140bc656ae.png">

**Desired Behavior**
Would like to improve the color combination for table in dark mode.
- The white border around tabs look weird.
- The active tab can be of a lighter form of dark color instead of white. Too contrasting.
- The active tab and the table heading row should have same color as in light mode.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195934911-3df55be5-0419-4b41-9111-9414657be2b7.png">

<br>

In the below image, the active tab has the same color as that of heading row. This should be the desired behavior.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/195935230-4a793e0c-4ca7-47c1-a2c3-53a8614487af.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by GaganpreetKaurKalsi** [comment]
Would like to work on it.

**Comment by leecalcote** [comment]
...a well-placed suggestion.

**Comment by GaganpreetKaurKalsi** [comment]
@leecalcote  Does this color combination look any better ?

Old -
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/54144759/196009094-04e8f623-3bc9-4e2d-bd81-0abd3a4e2be0.png">

Proposed - 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/54144759/196009077-b749212b-0eb4-4fe8-b0d0-e8c39ff8bfef.png">

**Comment by leecalcote** [comment]
Yes, it does, indeed. 

In addition, something else to consider here is that the keppel (or Caribbean) green used for the blank portion of the table is perhaps calling more attention to that portion than is desired.
