### ISSUE TITLE
Alignment of Image looks odd below 767px on page: /service-mesh-books 

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3325]
#### Description
Alignment of Image looks odd below 767px on page: /service-mesh-books 
![Screenshot 2022-10-15 104825](https://user-images.githubusercontent.com/85894871/195970293-234c5564-4e16-4a8f-b778-350ae5770215.png)

#### Expected Behavior
![Screenshot 2022-10-15 104901](https://user-images.githubusercontent.com/85894871/195970298-7fb4f2a1-2a7c-4384-a400-c5649cbdfd57.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by RahulGopathi** [comment]
I would like to work on this issue. :)

**Comment by RashiSingh20** [comment]
I would like to work on it

**Comment by Krishna2323** [comment]
@RashiSingh20 You can work on Issue #3324 just below this issue.

**Comment by RashiSingh20** [comment]
How should I run the application? Could you provide any documentation?

**Comment by Krishna2323** [comment]
@RashiSingh20 with every project you got the CONTRIBUTING.md file attached to get started with the project and for further questions join the slack channel: https://slack.layer5.io/
![Screenshot 2022-10-15 121005](https://user-images.githubusercontent.com/85894871/195973186-6ccca001-e4f8-4ca0-a2b4-732f6fdc8ae0.png)

**Comment by ALPHAWINS02** [comment]
Can  you assign this to me , I can make this work in little time .

**Comment by leecalcote** [comment]
@RahulGopathi , let’s remove your assignment until such time as you’ve build and can run the website (until you’re ready to contribute).

**Comment by leecalcote** [comment]
@ALPHAWINS02, thanks For volunteering. Have you been successful in building running the project? Can you take a screenshot, if so?

**Comment by sam1code** [comment]
If no one is working on it then you can assign to me! Thankyou

**Comment by AbhishekTiwari23** [comment]
My setup is also ready. Please, let me know if I can contribute.

**Comment by Nikhil-Ladha** [comment]
@sam1code do you have your setup ready? And, still interested in taking up this issue?

**Comment by sam1code** [comment]
Yes @Nikhil-Ladha I'm ready with my setup and interested in taking up this issue!

**Comment by Nikhil-Ladha** [comment]
Cool, here you go @sam1code

**Comment by sam1code** [comment]
Thankyou @Nikhil-Ladha
