### ISSUE TITLE
[Blog]: Meshery Operator

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3327]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** What is Meshery Operator?

**Topic:** Meshery Operator

**Core points to convey in the post:** 
1. General description of Kubernetes Operators
2. Description of each of Meshery Operator's custom controllers and their function (include MeshSync logo)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
Lot's of info available here https://docs.meshery.io/concepts/architecture/operator and in two Meshery Operator design specs in the community drive.

**Comment by sassukeuchiha** [comment]
hey @leecalcote can you share the community drive link for more information on broker and meshsync controller

**Comment by deepeshaburse** [comment]
> hey @leecalcote can you share the community drive link for more information on broker and meshsync controller

You should see it under "shared drives" if you've filled the newcomers form.

**Comment by sassukeuchiha** [comment]
got it thanks @deepeshaburse 👍

**Comment by Revolyssup** [comment]
> Hey @leecalcote @deepeshaburse Kindly review the following document and please let me know what areas require improvement or what must be discarded https://docs.google.com/document/d/1so9Y9mrH61_3Sp_zXqiHu5cascop6dINn2wNEiVfxlU/edit?usp=sharing Things that I feel may be added after approval:
> 
> 1. Whether mesherySync provides ability to compare 2 mesh models and let us know which works best
> 2. Still think there is limited info on Meshery broker

1. Please replace `Meshery Sync` with `Meshsync`
2. The functionalities of both controllers are described inaccurately. Please correct them.

**Comment by sassukeuchiha** [comment]
@Revolyssup Thank you for the corrections
I feel i have been very wrong about both the operators 😅
Would rewrite and share again... meanwhile can you please Direct me to some resources regarding mesh broker ...I did found some resource for MeshSync in community drive but still more resources would be helpful in understanding

**Comment by sassukeuchiha** [comment]
Hello @Revolyssup ,
Please Correct me if i am wrong ,I am referring to the following operator link from the shared path and it is written that MeshSync does service mesh configuration,along with other things
I am not able to take a screenshot or share the exact lines as i don't have the permission

https://docs.google.com/document/d/1D9aXbXqQNiykMYfXuTF1clh90bPYoRh3zR_5nGtLAaw/edit?usp=drivesdk
