### ISSUE TITLE
[Blog]: Managing multiple Meshery deployments using mesheryctl

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3329]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** Managing multiple Meshery deployments using mesheryctl

**Topic:** Managing multiple Meshery deployments using mesheryctl

**Core points to convey in the post:** 
1. Explanation of `meshconfig`
2. Description of mesheryctl `contexts` concept
3. Reflection on similarity to kubectl contexts (or not)
4. Examples of ways to set, update, create, and switch between `mesheryctl contexts`

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by legendarykamal** [comment]
hi, @deepeshaburse  having a sound knowledge and analyzing for some time, I am interested to work on this one.

**Comment by deepeshaburse** [comment]
> hi, @deepeshaburse  having a sound knowledge and analyzing for some time, I am interested to work on this one.

Hi, so sorry for the late reply. You can start working on the issue.

**Comment by UtkarshMishra12** [comment]
@legendarykamal ^^

**Comment by withgaurav** [comment]
@leecalcote I have written a blog
