### ISSUE TITLE
No space between the button from 768px to 991px on page: /cloud-native-management/meshery

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3333]
#### Description

No space between the button from 768px to 991px on page: /cloud-native-management/meshery
![Issue](https://user-images.githubusercontent.com/67385503/196032455-28c0b2b3-1e77-4214-8c1b-9f2f62714973.jpg)

#### Expected Behavior

![After](https://user-images.githubusercontent.com/67385503/196032471-620974dd-4dd5-4791-a3df-d5afce463f41.jpg)

#### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by AbhishekTiwari23** [comment]
My setup is also ready. Let me know if I can contribute.

**Comment by UtkarshMishra12** [comment]
This time I wanna try @AbhishekTiwari23, I'm setting up the environment.😊

**Comment by AbhishekTiwari23** [comment]
Ok, you can tag Leecalcote, sir, and also attach a screenshot of localhost. 
Thanks

**Comment by AbhishekTiwari23** [comment]
Hello @legendarykamal, sir, I just changed the max-width, and the result is acceptable. Please have h look, or should I make a new code for this range?

https://user-images.githubusercontent.com/97469132/197330199-8bd69161-53d4-49c0-a52c-03330f4dd635.mov

**Comment by legendarykamal** [comment]
@AbhishekTiwari23 I am not able to see the video .

**Comment by AbhishekTiwari23** [comment]
https://user-images.githubusercontent.com/97469132/197348566-35fc9509-53c2-4bd7-a42b-46b2076e1ae6.mov

**Comment by AbhishekTiwari23** [comment]
Please check now

**Comment by legendarykamal** [comment]
@AbhishekTiwari23 looks good from here , Please go forward and submit your PR.
