### ISSUE TITLE
Image is not aligned with the text on page: /projects/nighthawk

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3338]
#### Description
Image is not aligned with the text on page: /projects/nighthawk
![Screenshot 2022-10-16 222936](https://user-images.githubusercontent.com/85894871/196048267-4117207b-0e23-40dd-a11d-e73ce15741e7.png)

#### Expected Behavior
![Screenshot 2022-10-16 222826](https://user-images.githubusercontent.com/85894871/196048273-4857d954-19ce-4a67-9b48-089d5aeb2d98.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Nimesh-21** [comment]
Can you please assign this to me? I am new to open source.

**Comment by mritul** [comment]
@Krishna2323  Can i take up this issue and fix it ?

**Comment by NnajiChimuanya** [comment]
Assign me this @Krishna2323

**Comment by AbhishekTiwari23** [comment]
My setup is also ready.

**Comment by legendarykamal** [comment]
@Nimesh-21 @NnajiChimuanya please understand that in order to be assigned, 
you must have atleast your setup ready (a primary requirement) other requirements could be a basic idea of how gatsby works.

I wonder if you have your setup done. ? 🤔

**Comment by Nimesh-21** [comment]
> @Nimesh-21 @NnajiChimuanya please understand that in order to be assigned, 
> you must have atleast your setup ready (a primary requirement) other requirements could be a basic idea of how gatsby works.
> 
> I wonder if you have your setup done. ? 🤔 

No sir, I didn't knew about it. Sorry!

**Comment by aditi5050** [comment]
@legendarykamal  can I work on this issue

**Comment by legendarykamal** [comment]
sure @aditi5050, considering that you have your project setup, yes please  .

**Comment by UtkarshMishra12** [comment]
@aditi5050 Please update

**Comment by Oghene-kevwe** [comment]
Hello, I'd like to work on this

**Comment by UtkarshMishra12** [comment]
@Oghene-kevwe Sure

**Comment by Oghene-kevwe** [comment]
Thank you, I'll start right away and update you on my progress.

**Comment by Oghene-kevwe** [comment]
@UtkarshMishra12  I have figured out the problem but I have problems starting up the local dev server. It takes more than an hour and it doesn't even start up in my browser

**Comment by Oghene-kevwe** [comment]
@UtkarshMishra12 I am done. Please review

**Comment by YarinDay** [comment]
@UtkarshMishra12 While we are trying to achieve fast coding phase, I think this issue took too long. I'm taking this issue and will deliver soon a PR. feel free to assign it to me :)

**Comment by subodhk01** [comment]
@Krishna2323 @UtkarshMishra12 Please close this issue as it is stale now

**Comment by leecalcote** [comment]
Thank you for calling this out, @subodhk01
