### ISSUE TITLE
Align Legend component in the center for consistency on page: https://layer5.io/service-mesh-landscape  

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3339]
#### Current Behavior
Align Legend component in the center for consistency across the page.
on url: https://layer5.io/service-mesh-landscape  
![Screenshot 2022-10-16 224015](https://user-images.githubusercontent.com/85894871/196048742-2fb14b5d-8caf-408c-ae5d-59fe233ad38b.png)

#### Desired Behavior
![Screenshot 2022-10-16 224237](https://user-images.githubusercontent.com/85894871/196048769-f60bbe7f-ab13-4f0f-85b0-d70d6875f25f.png)

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mritul** [comment]
@Krishna2323 This seems to be in my scope. I would love to work on this

**Comment by NnajiChimuanya** [comment]
Assign me if this is free @Krishna2323

**Comment by AbhishekTiwari23** [comment]
My setup is also ready.

**Comment by leecalcote** [comment]
@mritul sounds real good. Will you confirm that you're able to build and run the layer5.io site on you development machine?

**Comment by Nikhil-Ladha** [comment]
I don't think we want to center align the legend at all. It was right aligned on purpose (as per the design) and looks completely fine.

**Comment by mritul** [comment]
@leecalcote @Nikhil-Ladha  So should I be working on this ? If not can I be assigned with some other ui related issue that is open?

**Comment by Nikhil-Ladha** [comment]
Nope, this issue should be closed.
@mritul  You can look out for other UI issues to work on, I am pretty sure you will find something or the other.

**Comment by mritul** [comment]
@Nikhil-Ladha  Thanks for clearing !

**Comment by Krishna2323** [comment]
No changes are needed as suggested by @Nikhil-Ladha.
