### ISSUE TITLE
[Meshery] Integrations: Do not show empty categories

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3340]
**Current Behavior**
A list of Meshery integrations is displayed in a honeycomb-like grid of cells. These integrations are categorized. [Categories](Some categories have zero integrations. ) are displays and available for users to use as filters. Some categories have zero integrations. 

<img width="1076" alt="Screen Shot 2022-10-16 at 9 56 22 PM" src="https://user-images.githubusercontent.com/7570704/196079586-510f7250-ab10-416b-87a5-b188fbe4268b.png">

**Desired Behavior**
Empty categories should not be displayed. Integrations will be added in the future.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by AbhishekTiwari23** [comment]
Can I go for it? I am not sure whether I will succeed or not, but I want to give it a try. This task is enjoyable.

**Comment by legendarykamal** [comment]
@leecalcote I can push on this task and finish successfully , If assigned ✔️ .

**Comment by leecalcote** [comment]
@legendarykamal, yes, please this is high priority.

**Comment by leecalcote** [comment]
@legendarykamal, please be sure to account for `published: false` as well. [Rook is set to false](https://github.com/layer5io/layer5/blob/master/src/collections/integrations/rook/index.mdx?plain=1#L18), but still showing as a cell.

**Comment by legendarykamal** [comment]
> > @legendarykamal, please be sure to account for `published: false` as well. [Rook is set to false](https://github.com/layer5io/layer5/blob/master/src/collections/integrations/rook/index.mdx?plain=1#L18), but still showing as a cell.
> 
> @sahilsuman933 fixed this issue.

Yes, just opened my pc and was looking over that pr itself, don't worry I am always in sync 🙂
