### ISSUE TITLE
Add search bar on page : /cloud-native-management/meshery/integrations

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3345]
#### Current Behavior
Add search bar on page : /cloud-native-management/meshery/integrations
No search option is on the integrations page.

#### Desired Behavior
Need a search bar for better user experience.

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
If mock(design) is ready then I can make the searchbar .

**Comment by tinniaru3005** [comment]
Hey @Krishna2323 , I would like to work on it. Can you please assign it to me?
