### ISSUE TITLE
Show a brief description of integration on hover. 

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3347]
#### Current Behavior
No description on hover about the integration.

#### Desired Behavior
Show a brief description of integration on hover on page: /cloud-native-management/meshery/integrations.

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by amit-ksh** [comment]
I'd like to work on this issues.

**Comment by legendarykamal** [comment]
hello @amit-ksh if you were not present in todays meeting, then I have somethings to be applied and seen here . 
Incase you have an idea feel free to connect at `slack`

**Comment by GaganpreetKaurKalsi** [comment]
Hey! Below I have attached 2 implementations, with and without image ON HOVER.
Let me know if it looks good, @leecalcote 

The API currently doesn't supply any description for integrations to display. If we want to have descriptions, then they will be statically present in the code. The one without image ON HOVER would be good to accommodate the description.
<br>

https://user-images.githubusercontent.com/54144759/196815177-f234d322-ecd8-4d3f-952c-939b600e999f.mp4

https://user-images.githubusercontent.com/54144759/196815681-178c4a69-7472-4afe-89f6-b838a0b6c877.mp4

**Comment by leecalcote** [comment]
I'm a huge fan of video recordings like this and of contributors taking initiative to propose a solution without necessarily having a design predefined. There have been a number of example integrations pages to take inspiration from like https://www.datadoghq.com/integrations/.

**Comment by legendarykamal** [comment]
@GaganpreetKaurKalsi Nice , 

In place of descriptions, a `Learn More` button would be great that redirects to the individual Integrations page for the respective integrations. 
As we already have them for each integrations.

**Comment by leecalcote** [comment]
Oh! We were both working on finishing this up at the same time, @GaganpreetKaurKalsi! 😆
