### ISSUE TITLE
Create a white GKE Logo for Dark Theme

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#3348]
**Current Behavior**
You need to create a white logo for GKE for the dark theme, which will be used across the website.

You can find the colored logo in location layer5/src/sections/Meshery/Meshery-platforms/supported-icons.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sahilsuman933** [comment]
@NPDebs, do you want to work on this issue?

**Comment by NPDebs** [comment]
> @NPDebs, do you want to work on this issue?

Sure. I'd love to. 🙂

**Comment by NPDebs** [comment]
@sahilsuman933 Could you please assign this to @richardnikolas instead? He seems to have a thing for SVGs. 👀🌝

**Comment by ackr-8** [comment]
Can i fix this issue?

**Comment by richardnikolas** [comment]
@sahilsuman933 I though you would assing this to me... 😐☹️

**Comment by sahilsuman933** [comment]
Sorry about this, @richardnikolas. How about you work on this https://github.com/layer5io/layer5/issues/3391 issue?
