### ISSUE TITLE
Create a white Linux Logo for Dark Theme

### ISSUE THREAD

**Issue by sahilsuman933** [layer5io/layer5#3349]
**Current Behavior**
You need to create a white logo for Linux for the dark theme, which will be used across the website.

You can find the colored logo in location `layer5/src/sections/Meshery/Meshery-platforms/supported-icons/`

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by richardnikolas** [comment]
@sahilsuman933 Hey, can you assign this to me, please?

**Comment by sahilsuman933** [comment]
Sure, go ahead @richardnikolas!

**Comment by leecalcote** [comment]
@richardnikolas thank you for volunteering. 🙂

**Comment by richardnikolas** [comment]
@sahilsuman933 @leecalcote I'm not being able to open/access this "Figma project" link. Could any of you guys help me with that?

**Comment by sahilsuman933** [comment]
@richardnikolas For this issue, I don't think you need access to the "Layer5 Figma project". As I mentioned in the description, you can get the colored Linux SVG at this `layer5/src/sections/Meshery/Meshery-platforms/supported-icons/` location.

**Comment by richardnikolas** [comment]
@sahilsuman933 okay, thank you!

**Comment by richardnikolas** [comment]
@sahilsuman933 @leecalcote I just opened the PR :)
https://github.com/layer5io/layer5/pull/3360
