### ISSUE TITLE
[Meshery] Integrations: Display total count of integrations based on the currently applied filter.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3350]
#### Current Behavior
No display of the number of results on selecting a category.

#### Desired Behavior
Display count of integrations based on the currently applied filter on page:/cloud-native-management/meshery/integrations. For example, when the OPERATING SYSTEM filter is applied, a count of 4 should be shown to the site visitor.

#### Mockup
![196338680-fb85e845-d0d2-4ad4-904f-36e090f0b084](https://user-images.githubusercontent.com/7570704/196436099-0f919c04-ee7b-495d-a7fd-3ddc2d42f900.png)

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Krishna2323 you'll need to write this up with a little more detail so that contributors who don't have context from this week's Websites meeting discussion can pick it up.

**Comment by GaganpreetKaurKalsi** [comment]
Would like to take this up.
Further I guess we won't be able to specify the type of filter/integration with count like in the screenshot _"4 Operating System Intergrations"_ as right now we can select multiple integrations at the same time.

Showing the count should suffice.

**Comment by leecalcote** [comment]
@sahilsuman933 expressed some interest here, although, I believe he is focused on more urgent enhancements to the Integrations section currently.

@Krishna2323, yes, that's right - a count of the number of integrations in each category. If a visitor selects multiple categories, show them the combined integration count of the selected categories. When "All" is selected (the default), display the total number of all integrations.

**Comment by leecalcote** [comment]
A brief design on the Meshery page in the "Layer5" Figma design file might be in order.

**Comment by GaganpreetKaurKalsi** [comment]
@leecalcote If this is up for grab then kindly assign it to me. Would like to work on it. 
Also I don't have view access to figma files. Would be great if I could get it.

**Comment by legendarykamal** [comment]
This is fulfilled , so closing it henceforth .
