### ISSUE TITLE
Ensure that categories with zero entries are not displayed in the list of filters.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3351]
#### Description
Ensure that categories with zero entries are not displayed in the list of filters.
#### Screenshots
Like these ones:
![Screenshot 2022-10-17 190444](https://user-images.githubusercontent.com/85894871/196191162-9f761490-9b42-426c-b417-6e4e62937c99.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Krishna2323** [comment]
@leecalcote got it.

**Comment by legendarykamal** [comment]
yes @AbhishekTiwari23 correct , since this is a duplicate issue , Its better to close this 😅

**Comment by Krishna2323** [comment]
The issue already exists.
