### ISSUE TITLE
[Meshery] Integrations: Dysfunctional category filters

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3353]
#### Description
Some of the categories are not selected on click on page: /cloud-native-management/meshery/integrations

https://user-images.githubusercontent.com/85894871/196204825-caaf8376-d0e9-453a-9db9-d86cf941a3e2.mp4

#### Expected Behavior
Must be selected if there are some results on selecting them.

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AbhishekTiwari23** [comment]
Issue #3340, please have a look.

**Comment by AbhishekTiwari23** [comment]
These are currently empty and should be invisible until some content is added.

**Comment by Krishna2323** [comment]
@AbhishekTiwari23 the issue here is that the user can't select them like other categories even if they are empty.
Are you able select them?
