### ISSUE TITLE
Creating a Security Vulnerability page having a set of instructions to report Security Issues on layer5.io

### ISSUE THREAD

**Issue by Onyx2406** [layer5io/layer5#3355]
#### Current Behavior
Currently layer5.io doesn't have any Security Vulnerabilities page just like on https://docs.meshery.io/project/security-vulnerabilities.

#### Desired Behavior
Having a Security Vulnerabilities page consisting of a set of instructions to report a security issue in layer5.io.

#### Implementation
Implementation of a page, consisting of similiar set of instructions as on docs.meshery.io/project/security-vulnerabilities in the community handbook.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Onyx2406** [comment]
If this is accepted, I would like to work on it. pls assign me.

**Comment by sahilsuman933** [comment]
Sure @Onyx2406, Go Ahead! 🚀

**Comment by UtkarshMishra12** [comment]
@Onyx2406 Please update

**Comment by Shivanshu97i** [comment]
Is this issue still open?

**Comment by gurpreet-legend** [comment]
If no one is working on this issue, can someone assign this to me? @UtkarshMishra12 @leecalcote @sahilsuman933

**Comment by leecalcote** [comment]
@gurpreet-legend, excellent. This would be good to have as a page or section inside of the community handbook (https://layer5.io/community/handbook)

**Comment by gurpreet-legend** [comment]
@leecalcote, And just to be sure, the page contents will be exact the same as in https://docs.meshery.io/project/security-vulnerabilities , right?
