### ISSUE TITLE
l5vuln-oct17-1

### ISSUE THREAD

**Issue by Onyx2406** [layer5io/layer5#3357]
#### Description
This is opened to track the Security Issue affecting a subdomain of layer5.io. Once, the issue is fixed, it can be closed.
If given permission, I would be happy to disclose the report here after the fix is implemented.

mailsentTo: security@meshery.dev
mailsentFrom: yashsancheti24@gmail.com

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Onyx2406** [comment]
> @Onyx2406 Thanks for filing this report. Given our use of Discourse as the underlying platform for discuss.layer5.io, has this particular concern been raised with discourse.org? We'll need for this concern to be addressed in the upstream project.

@leecalcote I can't say anything about it as most of the reports submitted on Discourse hacktivity are not disclosed publicly and I don't see this particular concern being pubicly disclosed there but I can always open a report there about this issue and they can let me know if this has already been reported to them by someone or not.

Discourse Program Hacktivity: https://hackerone.com/discourse/hacktivity?type=team

**Comment by leecalcote** [comment]
Oh, very good. Yes, this sounds like the appropriate next step.

**Comment by Onyx2406** [comment]
![image](https://user-images.githubusercontent.com/32770175/197147798-34d19044-d8f2-4a6b-8569-acf135988273.png)

**Comment by leecalcote** [comment]
@Onyx2406 makes sense. Did they give a ticket # to reference?

**Comment by UtkarshMishra12** [comment]
@leecalcote ^^

**Comment by leecalcote** [comment]
Until Discourse offers a fix, our hands are tied.
