### ISSUE TITLE
A gap on the page from 913px to 971px on page: layer5.io/docker-extension-meshery

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3361]
#### Description

A gap on the page from 913px to 971px on page: layer5.io/docker-extension-meshery
![Screenshot 2022-10-18 013010](https://user-images.githubusercontent.com/67385503/196272922-c3564d2b-1fb4-4e4c-928d-2c562b664c2f.jpg)

#### Environment:
- Host OS:  Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue. My local setup is ready now.

**Comment by Nikhil-Ladha** [comment]
Here you go @UtkarshMishra12
