### ISSUE TITLE
Poor Site Performance

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3366]
**Current Behavior**
Current score from web.dev:

<img width="1122" alt="Screen Shot 2022-10-17 at 5 30 43 PM" src="https://user-images.githubusercontent.com/7570704/196296184-e569b407-9df7-4dd8-8b69-08ded5ad3064.png">

**Desired Situation**
Ideally, layer5.io will have a 90 or higher performance.

#### Implementation
1. Iteratively implement each suggestion from web.dev. See https://web.dev/measure/?url=https%3A%2F%2Flayer5.io

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by eeshaanSA** [comment]
![image](https://user-images.githubusercontent.com/100678386/205214253-69a59ea7-35cf-4355-ab19-7cd9efe6203a.png)

**Comment by Udit-takkar** [comment]
@leecalcote @UtkarshMishra12 can i work on this issue ? i will firstly try to figure out whatever possible optimization we can do and keep you guys updated on slack.

**Comment by leecalcote** [comment]
@Udit-takkar wonderful. Yes.
