### ISSUE TITLE
[Site Performance] Incorporate SVGO 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3367]
**Current Behavior**
The layer5.io website has poor performance (see #3366). Portions of its performance can be enhanced by reducing the file size of images, concluding SVG images.

**Desired Situation**
Incorporate https://github.com/svg/svgo into the site's build process or commit hooks or make targets to ensure that SVG images are downsized as much as possible while not losing their original quality.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Onyx2406** [comment]
Hi, I would like to work on this. Pls assign me.

**Comment by sahilsuman933** [comment]
@Onyx2406 any progress?

**Comment by Onyx2406** [comment]
> @Onyx2406 any progress?
> 
> 

Hi, I tried to optimize all the svg images but did not see much improvement in performance as expected.. have to work on other aspects as well.

If anyone wants to collaborate to resolve this and get this assigned.. please feel free to..

**Comment by UtkarshMishra12** [comment]
@Onyx2406 Please update
