### ISSUE TITLE
Change active Navbar link styling

### ISSUE THREAD

**Issue by janvi01** [layer5io/layer5#3368]
#### Current Behavior

When layer5 is navigated to different pages/routes, the navbar link is not highlighted. (Currently, it is highlighted only when hovered)

#### Desired Behavior

Highlight or change the styling of the active link on the navbar to enhance user experience.

#### Screenshots / Mockups

Example: when navigating to [project's page](https://layer5.io/projects)

Current -

<img width="1792" alt="Screenshot 2022-10-18 at 10 25 31 AM" src="https://user-images.githubusercontent.com/34344234/196340848-45db3245-a640-41ca-a26f-df4d1c93de8f.png">

Desired -

<img width="1792" alt="Screenshot 2022-10-18 at 10 25 07 AM" src="https://user-images.githubusercontent.com/34344234/196340927-be088dd7-529d-4036-a4a0-482d214126f0.png">

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by janvi01** [comment]
Hey, I would like to work on this issue.

**Comment by Nikhil-Ladha** [comment]
Sure, @janvi01 assigned the issue to you

**Comment by janvi01** [comment]
@Nikhil-Ladha Also, if you can add hacktoberfest label here? Thanks!
