### ISSUE TITLE
Deploying Meshery needs to add the option (Use Helm chart).

### ISSUE THREAD

**Issue by Aisuko** [layer5io/layer5#337]
**Current State:**

https://meshery.layer5.io/docs/installation/kubernetes#quick-start-with-kubernetes

Only use the .yaml files to deploy meshery

**Desired State:**

Add the option that can deploy meshery by Helm chart. Format like below(Please carefully check Helm v2, I did not did testing for Helm v2)

https://meshery.io/#getting-started

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by gunjanmimo** [comment]
@Aisuko this problem is fixed now, should i close this pr?

**Comment by Aisuko** [comment]
Thanks, please look at this https://github.com/layer5io/meshery/pull/689#pullrequestreview-360054622

**Comment by leecalcote** [comment]
I think we're good to go here. Please reopen, if not.
