### ISSUE TITLE
[UX] Design: Need a new community badge for UI/UX contributors

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3379]
**Current Behavior**

We need a new batch to recognize and appreciate the work of UI/UX'ers in our community. 
![image](https://user-images.githubusercontent.com/100678386/196669886-678755f0-54e3-4bb4-bf0b-8b84e8fd77da.png)

**Desired Situation**

---
[Optional] **Alternatives**

[Optional] **Additional context**

Badges are provided to consistent contributors and people who are active in the community, who hold a good amount of knowledge about the project and the repository, and who are associated to that project for a long time, and are the best people to reach out to. We have different badges for different projects; Landscape, Meshery, SMP etc. You can find different badges for different repositories Layer5 has to offer, in the members section on the layer5 site.
https://layer5.io/community/members

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@eeshaanSA will you expound on the issue description? What is a "badge"? Link to them?

**Comment by sam1code** [comment]
Hey @leecalcote  I would like to work on this. I earlier added Community manager so I can quickly add this also.

**Comment by leecalcote** [comment]
I'm confused as to what this issue is asking for given that there isn't a UX badge available, yet.

**Comment by sam1code** [comment]
Ohh I thought that another role for ux can be there in the member filter section like community, landscape, imagehub etc.

**Comment by eeshaanSA** [comment]
@sam1code, badges are something that are provided to consistent contributors and people who are active in the community, who hold a good amount of knowledge about the project and the repository, and who are associated to that project for a long time.  You can find different badges for different repositories Layer5 has to offer, in the members section on the layer5 site. https://layer5.io/community/members

**Comment by eeshaanSA** [comment]
Recently in the Community, there has been a lot of effort from different UI/UX'ers, who made awesome designs and impactful contributions, and so we need a **NEW** badge for them, so their work can be recognised in the community. 
This badge, will have to be designed from scratch. You will have to come with the design you feel suits the requirement, and if we feel the same way, we'll have your design accepted. 😄

**Comment by eeshaanSA** [comment]
@leecalcote, please correct me if I am wrong. 😄

**Comment by sam1code** [comment]
Thankyou @eeshaanSA.. Also can you suggest me an icon for it ?

**Comment by leecalcote** [comment]
> @leecalcote, please correct me if I am wrong. 😄

@eeshaanSA great description. Spot on. @sam1code once the icon (button) is designed. It'll need to be added to a few pages, like the community members page, the community handbook, the contributor guide/readme,...  I tagged you both in Slack just now so that you can track and partake in the progress of the icon design. // @DivineOrji

**Comment by sam1code** [comment]
Thankyou @leecalcote 🤩

**Comment by Khushi-design-20** [comment]
Hey, is this still open?

**Comment by leecalcote** [comment]
Yes, in that @sam1code has only offered an update for the /community/members page and not other locations that will need to be updated. Understand, though, that a UX badge icon has been approved, yet.
