### ISSUE TITLE
Platforms integration filter missing

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3388]
#### Description
Unable to see the "Platforms" integration filter

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/196818840-51d5163b-e726-4b7c-ae26-b4946bbc628b.png">

<br>

#### Expected Behavior
Platforms integration should be present among other integrations

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/196819054-3999475b-d846-43c7-9907-84995d4933c8.png">

<br>

**Not sure if it is a bug or a deliberate action.**

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
If this seems to be a valid issue then would like to work upon this.

**Comment by sahilsuman933** [comment]
Thank you, @GaganpreetKaurKalsi, for spotting this issue. Indeed "Platform" category should have been there, but I don't think there is any error in the logic part. But it has to be something else cause in the local build, it is showing the `Platform` category, but it is not in the website deployment.

**Comment by sahilsuman933** [comment]
Yup, you are right about this, @GaganpreetKaurKalsi. Due to the cache of the previous website build, I could see the `platform` filter. So, you can go ahead and work on this issue.

**Comment by sahilsuman933** [comment]
@GaganpreetKaurKalsi, Could you please fix this bug as soon as possible because this bug is being displayed in the homepage.

**Comment by GaganpreetKaurKalsi** [comment]
Right away! Will open an MR in half hour max.
