### ISSUE TITLE
Nav links not visible for sub menu dropdown in mobile view

### ISSUE THREAD

**Issue by snitin315** [layer5io/layer5#339]
**Description**
A brief description of the issue.

Nav links not visible for sub menu in mobile view

**Expected Behavior**
A brief description of what you expected to happen.
Should be visible.

**Screenshots**
Add screenshots, if applicable, to help explain your problem.
![Screenshot_2020-02-20-10-52-51-780_com android chrome](https://user-images.githubusercontent.com/46647141/74903633-88ff7480-53cf-11ea-8e27-dee4c86b1016.jpg)

[Optional] **Additional Context**
I will work on it.

**Comment by leecalcote** [comment]
Good eye, @snitin315. Thanks for jumping in here. 👍

**Comment by snitin315** [comment]
@leecalcote Thanks for the complement.  Can I be a member of this organisation on github?

**Comment by leecalcote** [comment]
@supra08 is this something that you might take on?

**Comment by leecalcote** [comment]
I think we have resolved this issue. Here's a screenshot:

<img width="572" alt="Screen Shot 2020-03-16 at 6 06 13 PM" src="https://user-images.githubusercontent.com/7570704/76806960-dabdd380-67b0-11ea-9d44-efc1007415e2.png">
