### ISSUE TITLE
[Integrations Page] Need a better Darkmode logo for Containerssh

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3391]
#### Description

![image](https://user-images.githubusercontent.com/100678386/196933166-e049c9a1-af63-4ff7-8ae1-96af9caa6b5d.png)
![image](https://user-images.githubusercontent.com/100678386/196933242-1f4accc5-d77b-4538-bc2f-4fcd744bddf3.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Bhav00** [comment]
Hello, does the Dark logo for Containerssh need to be saved in the same folder as its color variant? i.e. this folder
 
> layer5/src/collections/integrations/containerssh/

If not, can I be please informed as to where you'd like the DarkMode logo for Containerssh to be?

**Comment by sahilsuman933** [comment]
@Bhav00 Put the dark mode logo to `layer5/src/collections/integrations/containerssh/icon/white` and make sure to update the mdx file for it.

**Comment by Bhav00** [comment]
I have added the .svg in this folder along with the containerssh index.mdx that has the integration icon's field changed to match the icon name 
> layer5/src/collections/integrations/containerssh/icon/white

and made a pull request. That branch might be 1 commit behind that was merged a little while ago.

**Comment by richardnikolas** [comment]
Well, apparently I got here late @sahilsuman933 😅 is there another one of these?

**Comment by sahilsuman933** [comment]
@richardnikolas How about you improve the homebrew icon for the darkmode?
