### ISSUE TITLE
Service mesh timeline is not centered below 767px on page: /service-mesh-landscape

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3393]
#### Description
Service mesh timeline is not centered on page: /service-mesh-landscape
![Screenshot 2022-10-20 190615](https://user-images.githubusercontent.com/85894871/196963947-070394b8-9ef3-4dfa-8f75-31d2725a2261.png)

#### Expected Behavior
![Screenshot 2022-10-20 190653](https://user-images.githubusercontent.com/85894871/196963984-8c21dd6d-43cb-49c5-8dad-446f3a853156.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by mritul** [comment]
Can I take up this issue?

**Comment by Nikhil-Ladha** [comment]
Again, this is by design 🌚

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, that's weird for me.
