### ISSUE TITLE
[Integrations Page] Need a better darkmode logo for CDK8S

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3403]
#### Description

![image](https://user-images.githubusercontent.com/100678386/197127745-8c6b19bc-fc42-4020-8ce5-1e23a92ad11a.png)
![image](https://user-images.githubusercontent.com/100678386/197127851-4a960c43-4e76-4093-8d8f-ad8ec84b7f7b.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
// @richardnikolas

**Comment by sam1code** [comment]
I can make the logo by inverting colors and can implement.

**Comment by tinniaru3005** [comment]
I would like to work on the issue. Can you please assign it to me?

**Comment by eeshaanSA** [comment]
Assigning in the order of requests-

**Comment by legendarykamal** [comment]
Devs , maybe we just need 3 k8s logo on the kube and that would make the deal.

**Comment by sam1code** [comment]
> Devs , maybe we just need 3 k8s logo on the kube and that would make the deal.

Yeah

**Comment by eeshaanSA** [comment]
@sam1code how far are you with this?

**Comment by sam1code** [comment]
Today I'll create the PR sorry for delay

**Comment by UtkarshMishra12** [comment]
@sam1code Please Update
