### ISSUE TITLE
[Integrations] "All" being selected by default on specific integration page

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3408]
#### Description
When we go to specific integration page, the category type of the integration along with All are selected by default.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/197282501-63cd0167-0aea-4ab0-b9f0-dad7d9870d72.png">

#### Expected Behavior
Either "All" alone should be selected or the category type of the specific integration should be selected.
All and some other category type can never be selected together at the same time.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/197282865-2c80519a-dd72-466b-b039-79d795a25e65.png">

#### Environment:
- Host OS: MacOS 
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
@GaganpreetKaurKalsi  I would like to work on this

**Comment by legendarykamal** [comment]
Strange, I don't see any such behaviour on the site . Refrencing a video .


https://user-images.githubusercontent.com/95926324/197317809-5f8acd86-43e6-4821-9bda-99692190b76a.mp4

**Comment by sam1code** [comment]
@legendarykamal  you did it wrong way.
Just click on any card you will be redirected to thay page and then you can get this behavior

**Comment by sam1code** [comment]
https://user-images.githubusercontent.com/74086891/197323003-406c51ec-3def-45b4-a857-52989db1b997.mp4

**Comment by legendarykamal** [comment]
Oh my bad, thanks @sam1code for pointing it out 👍

**Comment by legendarykamal** [comment]
not much change is needed here , in this case the `selected: should be false`  . This should fix it.

**Comment by sahilsuman933** [comment]
This was done intentionally to show the related integrations. @GaganpreetKaurKalsi

**Comment by GaganpreetKaurKalsi** [comment]
> This was done intentionally to show the related integrations. @GaganpreetKaurKalsi

Yeah! But the issue is that All is selected as well (talking about dedicated integration page). We are showing all available integrations instead of only related ones.

Also “All” is a standalone filter. Shouldn’t be paired with any other as it doesn’t make sense.

**Comment by sahilsuman933** [comment]
Yeah, I forgot to take care of this while fetching the category from GraphQL.So, yeah, go ahead and fix this issue, @GaganpreetKaurKalsi.
