### ISSUE TITLE
[Integrations] Convert stack of category filters to a carousel on home page

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3416]
#### Current Behavior
We display a stack of category filters on the home page but display only 2 rows of integration here.

<img width="1440" alt="Screenshot 2022-10-26 at 7 49 59 PM" src="https://user-images.githubusercontent.com/85789734/198051530-4dbe1dd7-df70-4949-bb75-0971eddc52e5.png">

#### Desired Behavior
We will be adding a hundred more integrations very soon. We don't want such a large stack of filters shown on the home page itself. Therefore, we should consider converting this stack into a carousel. 
Example: [make.com](https://www.make.com/en)

<img width="1395" alt="Screenshot 2022-10-26 at 7 50 46 PM" src="https://user-images.githubusercontent.com/85789734/198052399-f1ca243a-c9bf-4f62-a929-27ff9bd60517.png">

#### Implementation
This change should be applicable to only the Home page for now. The stack of filters should remain on the main integrations page.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by legendarykamal** [comment]
designs ready, I would like to take a leap on this 🛩️ .

**Comment by gbotesco** [comment]
The design is done and approved

**Comment by leecalcote** [comment]
@sahilsuman933 you're up.

**Comment by leecalcote** [comment]
Mockup:
<img width="1665" alt="Screenshot 2022-11-28 at 7 15 18 AM" src="https://user-images.githubusercontent.com/7570704/204286872-e49948ac-d9ad-4c2f-a16e-6b7dd4b0db72.png">

**Comment by suhail34** [comment]
Hey I would like to work on this issue

**Comment by leecalcote** [comment]
Great to have you on today's call, @suhail34. 👍

**Comment by suhail34** [comment]
> Mockup: <img alt="Screenshot 2022-11-28 at 7 15 18 AM" width="1665" src="https://user-images.githubusercontent.com/7570704/204286872-e49948ac-d9ad-4c2f-a16e-6b7dd4b0db72.png">

This issue needed to be done like this i mean the design

**Comment by leecalcote** [comment]
Yes, the top row of filters needs to be implemented as a carousel.
