### ISSUE TITLE
[Integrations] Add Search feature to integrations

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3417]
#### Current Behavior
We don't allow users to search for a specific integration they are looking for. 

#### Desired Behavior
Add a search feature to the integrations grid on both the Home page as well as the All Integrations page. Use the existing Search component used in Blogs and Resources.

#### Implementation
The search should match the title/name of each integration.

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by debo19** [comment]
@kayceeDev are you working on this?

**Comment by kayceeDev** [comment]
> @kayceeDev are you working on this?

I will take a jab at it.
