### ISSUE TITLE
[Integrations] Add per category count on All Integrations page

### ISSUE THREAD

**Issue by debo19** [layer5io/layer5#3418]
#### Current Behavior
The category filters do not display the count of integrations available under that particular category.

<img width="1130" alt="Screenshot 2022-10-26 at 8 03 06 PM" src="https://user-images.githubusercontent.com/85789734/198054973-93ba35c5-289c-477d-b0d9-fce7a8e92a9d.png">

#### Desired Behavior
Add per category count on [All Integrations](https://layer5.io/cloud-native-management/meshery/integrations/) page, similar to tags used in [Blogs](https://layer5.io/blog).

<img width="281" alt="Screenshot 2022-10-26 at 8 02 56 PM" src="https://user-images.githubusercontent.com/85789734/198055324-10428774-dba8-4e18-b8aa-c7bf7d5506c0.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by tinniaru3005** [comment]
Hey I would like to work on it. Can you please assign  it to me?

**Comment by legendarykamal** [comment]
here you go 🚀
