### ISSUE TITLE
[Mega Menu] Use full images of the books

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3419]
#### Current Behavior
The "mega menu" (the website's global navigation menu) has half sized images for two of the books (see screenshot).

#### Desired Behavior
Instead of half size images, use the full book cover images. Find full images here - https://layer5.io/learn/service-mesh-books

#### Screenshots / Mockups

<img width="1123" alt="Screen Shot 2022-10-26 at 2 37 22 PM" src="https://user-images.githubusercontent.com/7570704/198120592-ec61eeeb-7d21-4bb1-879c-dc8ac6d2c9c3.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by OmiCoding** [comment]
I'll like to be assigned this issue.

**Comment by AbhishekTiwari23** [comment]
My setup is also ready. Please let me know if I can contribute.

**Comment by leecalcote** [comment]
Sounds good. Thank you, gentlemen.

**Comment by legendarykamal** [comment]
@OmiCoding as you use the full length of the books , make sure that the width on hover is equal which currently isn't .

**Comment by OmiCoding** [comment]
@legendarykamal Thank you! I'll keep that in mind!

**Comment by OmiCoding** [comment]
Hey unfortunately I won't have time to work on this issue. I would rather someone else take it.

**Comment by tinniaru3005** [comment]
Hey @legendarykamal, I would like to work on this also. Can you please assign it to me?

**Comment by happy656** [comment]
Hey @leecalcote, I would like to be assigned this issue.

**Comment by leecalcote** [comment]
@happy656, sounds real good.

**Comment by happy656** [comment]
![image](https://user-images.githubusercontent.com/90033527/203139845-a956bcab-8f09-404e-b7a9-330e92a52676.png)

@legendarykamal   after changing the images the site looks like this. I wanted to ask whether I should center the book images or increase the image sizes.

**Comment by eeshaanSA** [comment]
@happy656 @OmiCoding updates?

**Comment by eeshaanSA** [comment]
> ![image](https://user-images.githubusercontent.com/90033527/203139845-a956bcab-8f09-404e-b7a9-330e92a52676.png)
> 
> @legendarykamal @leecalcote after changing the images the site looks like this. I wanted to ask whether I should center the book images or increase the image sizes.

Yes, it needs to be centered.

**Comment by eeshaanSA** [comment]
> @OmiCoding as you use the full length of the books , please make sure that the width on hover is equal for both of them which currently isn't .

Also, keep this in mind. @happy656

**Comment by Anand-Theertha** [comment]
I'd love to take this up if it's not being currently worked on.

**Comment by UtkarshMishra12** [comment]
@Anand-Theertha Progress ??

**Comment by Brownei** [comment]
I think you should make the height of the image to be slightly larger. I will make use of TailwindCSS and I will give the image a class or className of just two lines which are "max-w-sm or max-w-md(according to your preference sizing) and object-cover"

**Comment by HemanthPaila** [comment]
Hey @leecalcote I am interested to work on this issue

**Comment by HemanthPaila** [comment]
thanks @leecalcote I am working on it.
     -  If any problems I will reach out to you.

**Comment by leecalcote** [comment]
@HemanthPaila great. Please ask on the discuss.layer5.io discussion form if you have challenges.

**Comment by 8rxn** [comment]
Hey @leecalcote , 
I would like to work on this if the issue is still relevant.

**Comment by leecalcote** [comment]
Thank you, @8rxn. That would be most helpful.

**Comment by Savio629** [comment]
@8rxn progress?

**Comment by 8rxn** [comment]
> @8rxn progress?

Yeah I have looked into the issue
Identified the files to change... but haven't  made the changes yet...
Will try to wrap it as soon as I can.
