### ISSUE TITLE
Make Projects sections responsive

### ISSUE THREAD

**Issue by janvi01** [layer5io/layer5#3421]
#### Description

The display of the open-source projects section is not responsive. The side icons get hidden.

#### Expected Behavior

Make it responsive for all resolutions.

#### Screenshots

<img width="1792" alt="Screenshot 2022-10-27 at 1 41 35 PM" src="https://user-images.githubusercontent.com/34344234/198229888-0526edc1-6c5a-495e-9f08-3bbfd4daa8ab.png">

<img width="403" alt="Screenshot 2022-10-27 at 1 43 38 PM" src="https://user-images.githubusercontent.com/34344234/198230021-77dc0af5-fd49-4983-8d25-1ee19adc16b2.png">

<img width="1792" alt="Screenshot 2022-10-27 at 1 43 04 PM" src="https://user-images.githubusercontent.com/34344234/198229981-d2523fb6-65a2-441a-99d7-5917ae991c12.png">

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by janvi01** [comment]
I would like to work on this. Thanks!

**Comment by leecalcote** [comment]
Thanks for filling this issue, @janvi01. 

@NikhilLadha, perhaps, this is as issue to be addressed using the same Cara user being developed for the Integrations category filters on the home page.

**Comment by gbotesco** [comment]
@leecalcote assign the design to me

**Comment by leecalcote** [comment]
Thank you, @gbotesco. That would be great.

**Comment by janvi01** [comment]
Hey, @gbotesco are you done with the design?

**Comment by gbotesco** [comment]
Yes check the figma file

**Comment by janvi01** [comment]
Hi @leecalcote, I don't have access to the figma file.

**Comment by Oghene-kevwe** [comment]
Hello, I'd like to work on this

**Comment by janvi01** [comment]
Since I am busy with my exams, Hey @Oghene-kevwe, You can go ahead with this issue. Do ping me if you have any doubts.

**Comment by Oghene-kevwe** [comment]
I will start work on it and update you.

**Comment by Oghene-kevwe** [comment]
@janvi01 Please I need access to see the figma file so I can apply the correct design

**Comment by Sajiyah-Salat** [comment]
Hello @Oghene-kevwe  @janvi01 I would like to work on this issue. I know little bit of frontend and much of git. Let me know if I can help.

**Comment by Oghene-kevwe** [comment]
@Sajiyah-Salat I'm also trying to do the task. Although, I need to see the design first. @janvi01 hasn't responded yet so I'm still waiting

**Comment by Sajiyah-Salat** [comment]
Ohk if she responds we can connect on [linkedin](https://www.linkedin.com/in/sajiya-salat-0a2a78245/)  and work together. Thank you.

**Comment by Dynamitetechdev** [comment]
any assignee to this?
would love to jump on it. Thank You

**Comment by Manan1304** [comment]
@Oghene-kevwe 
Can I also help you if you don’t mind ?

**Comment by Oghene-kevwe** [comment]
@Manan1304  You'll need to check the figma file for the correct desgin though.
I reached out to @janvi01 for that but there has been no response

**Comment by janvi01** [comment]
@Nikhil-Ladha Please look.

**Comment by Nikhil-Ladha** [comment]
There is no design as such for anyone to take a look at.
We just need to move all the items in one row and have an infinite carousel for it, without the control arrows.

**Comment by avikt18** [comment]
@leecalcote @Nikhil-Ladha I would like to work on this issue 😄

**Comment by Nikhil-Ladha** [comment]
Going by order of ask @Oghene-kevwe or @Sajiyah-Salat , are either of you interested?

**Comment by Oghene-kevwe** [comment]
@Sajiyah-Salat you can have it

**Comment by Sajiyah-Salat** [comment]
Yes I am interested but I need someone to collaborate.

**Comment by Nikhil-Ladha** [comment]
In that case @Sajiyah-Salat you and @avikt18 can work together 🤝

**Comment by Sajiyah-Salat** [comment]
Great then I will start work by today itself. @Oghene-kevwe if you have done any work or advice Ping me [here](https://www.linkedin.com/in/sajiya-salat-0a2a78245/). Hey @avikt18 Let's collaborate and work together.

**Comment by avikt18** [comment]
@Sajiyah-Salat any updates?

**Comment by leecalcote** [comment]
I have my 🤞. 🙂

**Comment by Sajiyah-Salat** [comment]
I have tried my level best to run meshery website locally and got many different errors. I tried to clone it twice from scratch and same error pops out. I will still try but @avikt18 you can take this forward and I will join later. Thank you.

**Comment by leecalcote** [comment]
@Sajiyah-Salat thanks much for sending word about your progress. This is most helpful. @avikt18 are you ready to carry this forward? @Sajiyah-Salat can review your PR when you do.

**Comment by Sajiyah-Salat** [comment]
great I will do that.

**Comment by aman123424** [comment]
@leecalcote , @Nikhil-Ladha , is this issue solved?
 I would like to work on this issue

**Comment by prachiMeshram** [comment]
@leecalcote , @Nikhil-Ladha 
I would like to know whether the issue is solved or not. 
If not, can I go ahead with this?

**Comment by aman123424** [comment]
> @leecalcote , @Nikhil-Ladha I would like to know whether the issue is solved or not. If not, can I go ahead with this?

We can collaborate maybe, if this issue is not fixed yet

**Comment by avikt18** [comment]
@leecalcote will take this forward :+1:

**Comment by leecalcote** [comment]
@aman123424 @prachiMeshram, let's get you some new issues (or other issues that have stagnated). There is a high profile issue on the main banner (4) of the MeshMap video overlapping text in higher resolution screens. This needs to be fixed. 😬

**Comment by leecalcote** [comment]
@Nikhil-Ladha do you, too, see the video overlapping the text?

**Comment by aman123424** [comment]
> @aman123424 @prachiMeshram, let's get you some new issues (or other issues that have stagnated). There is a high profile issue on the main banner (4) of the MeshMap video overlapping text in higher resolution screens. This needs to be fixed. 😬

Okay sure

**Comment by prachiMeshram** [comment]
> @aman123424 @prachiMeshram, let's get you some new issues (or other issues that have stagnated). There is a high profile issue on the main banner (4) of the MeshMap video overlapping text in higher resolution screens. This needs to be fixed. 😬

@leecalcote can you please tag the issue here in comment so that me and @aman123424 can work on it

**Comment by leecalcote** [comment]
I haven’t created an issue, yet. Go ahead and create one.

**Comment by Nikhil-Ladha** [comment]
I will close out this issue for now. Doesn't seem to be worth the time, the section is as per design.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha do you, too, see the video overlapping the text?

I think it was fixed sometime back, do you see that even now?
