### ISSUE TITLE
[Integrations] Replace screenshots on Docker integration

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3424]
#### Current Behavior
Screenshots of the Docker Meshery Extension are available (see project page), but not displayed on the [Docker integration page](https://layer5.io/cloud-native-management/meshery/integrations/docker).

#### Desired Behavior
Replace the existing performance graph screenshots with screenshots of the Docker Extension for Meshery.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue @leecalcote

**Comment by leecalcote** [comment]
Thanks!

**Comment by UtkarshMishra12** [comment]
@leecalcote Do I need to replace this graph with the Docker Extension for Meshery Logo? I was having some confusion so I thought to ask you.

![image](https://user-images.githubusercontent.com/67385503/198689394-984e6c4c-b92a-447b-9cb7-3182aeacf715.png)



Logo :
![image](https://user-images.githubusercontent.com/67385503/198690604-6a9792b6-ddea-4def-b252-e8ca146367d7.png)

**Comment by leecalcote** [comment]
Thanks for asking. Rather, you can replace the existing screenshots with:

- https://layer5.io/static/5c7e71205db1a7b8dc780e41b16d7470/f4c24/docker-extension-meshery.webp

<img width="2560" alt="Screen Shot 2022-10-28 at 12 24 50 PM" src="https://user-images.githubusercontent.com/7570704/198696514-99def80f-8ffa-4017-b87b-2be867e23fe3.png">


<img width="2560" alt="Screen Shot 2022-10-28 at 12 21 04 PM" src="https://user-images.githubusercontent.com/7570704/198696526-91502174-b685-4d62-a908-910012ed9047.png">

**Comment by UtkarshMishra12** [comment]
Ok @leecalcote , so I just have to replace the 3 images (How it Works) sections on the cloud-native-management/meshery/integrations/docker page, with these images. 😊 Correct me If I'm wrong.

**Comment by leecalcote** [comment]
Yes, that's right.
