### ISSUE TITLE
[Landscape] Content is misplaced on the service mesh landscape timeline

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3428]
**Current State:**
Project details are misplaced on the [service mesh landscape](https://layer5.io/service-mesh-landscape) timeline. See screenshot.

<img width="1223" alt="Screen Shot 2022-10-31 at 10 59 04 AM" src="https://user-images.githubusercontent.com/7570704/199053027-cd0e6e8d-0b22-4f12-b380-27f07b4394af.png">

**Desired State:**
Project details should be contained within their respective timeline annotation.

**Environment:**
- Browser: Safari
- OS: MacOS
 

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Nikhil-Ladha** [comment]
I think its more of a cache issue , as we don't use the black background for the timeline items 🤔

**Comment by legendarykamal** [comment]
yes I too wonder from where does that black bg comes ? here is a live screenshot.
![image](https://user-images.githubusercontent.com/95926324/199071780-18fa0ba3-727e-457d-b1a4-36a74463a2be.png)

**Comment by Asmit2952** [comment]
![Screenshot (116)](https://user-images.githubusercontent.com/81866614/199564950-fc1c7088-1e06-4cac-9678-60e708ca9843.png)
The entire <div> has the color: `#3C494F`, instead of timeline's path. Maybe this caused the issue? @legendarykamal

**Comment by leecalcote** [comment]
Hmpf. Funky. I visited the site a minute ago and the issue persisted. I came to this GH issue and saw the suggestion to empty cache. I emptied cache, reloaded, and still saw the issue. I changed from light to dark mode and back again and the issue has gone away. Cookie cache, perhaps?

Either way, this behavior has gone away. 😌 Thank you for investigating this, gentlemen.
