### ISSUE TITLE
Make language flags responsive

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#343]
**Current Behavior**
The language flags do not have a breakpoint similar to the social / contact icons.

**Desired Behavior**
Ideally, the language flags resize at the same breakpoint as does the social / contact icons.

---
**Screenshots**
Full size images:
<img width="524" alt="Screen Shot 2020-02-25 at 11 01 06 PM" src="https://user-images.githubusercontent.com/7570704/75313596-e1e16980-5822-11ea-8722-31cfa6475ba5.png">

Social / Contact buttons are responsive, but not the language flags:
<img width="480" alt="Screen Shot 2020-02-25 at 11 01 00 PM" src="https://user-images.githubusercontent.com/7570704/75313604-e574f080-5822-11ea-8ba0-aec6d97d80f6.png">

**Comment by Nikhil-Ladha** [comment]
@sarthakpranesh, please assign an issue to yourself before taking up one, so that there isn't any misunderstanding in future. And if it's assigned to someone else, do ask them once before working on that 🙂

**Comment by leecalcote** [comment]
@sarthakpranesh, it's fantastic of you to lend a hand here. It looks like React, Go and many of the technologies that we focus on the Layer5 community are of interest to you. We would love to have you join --> http://slack.layer5.io. Please do. 👍

**Comment by sarthakpranesh** [comment]
@leecalcote, I'll be most pleased to join :smile:
