### ISSUE TITLE
[Performance] All Integrations page performance is poor

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3438]
#### Description
The package used to create the honeycomb of integration cells on [this page](https://layer5.io/cloud-native-management/meshery/integrations) is quite poor, leading to a negative user experience of the mouse dragging and animations behaving oddly.

#### Expected Behavior
Rendering of the integrations honeycomb should be brisk, each cell loaded in a non-blocking way and css transitions should be smooth as well.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by AgniveshChaubey** [comment]
Hey @leecalcote, I wanna work on this issue. Can you please elaborate a little more?

**Comment by leecalcote** [comment]
@AgniveshChaubey, nope, the issue description is pretty clear. This this one doesn't quite make sense, I encourage to grab another open issue.

**Comment by leecalcote** [comment]
Click the link above to experience the slow down first-hand.

**Comment by leecalcote** [comment]
@kayceeDev? Would you like to give this a shot?

**Comment by kayceeDev** [comment]
> @kayceeDev? Would you like to give this a shot?

Alright definitely

**Comment by eeshaanSA** [comment]
@kayceeDev is a PR already made?

**Comment by kayceeDev** [comment]
@eeshaanSA I am currently writing my school exams that's why I haven't worked on this. I intend to soon from next weekend but you can take it on if you want.

**Comment by leecalcote** [comment]
Way to be, @GaganpreetKaurKalsi! 👏
