### ISSUE TITLE
[mesheryctl] Error Message

### ISSUE THREAD

**Issue by Ebi27** [layer5io/layer5#3441]
#### Description
The mesheryctl pattern list error response currently displays as ;
```
➜  meshery git:(master) ✗ mesheryctl pattern list
Error: Get "http://localhost:9081/api/pattern": dial tcp [::1]:9081: connect: connection refused
➜  meshery git:(master) ✗
```
#### Page Link:
  http://github.com/meshery/meshery

#### Expected Behavior

The mesheryctl pattern list error response should be “Unable to reach Meshery Server at ….. Please confirm that Meshery Server is available.”

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thanks, @Ebi27! 👍

**Comment by leecalcote** [comment]
Oh, wait. Wrong repo.

**Comment by Ebi27** [comment]
I'll correct that
