### ISSUE TITLE
[Community] Member Profile: Krishna Gupta

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3445]
**Current Behavior**

@Krishna2323  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Krishna2323 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Krishna2323
- Twitter: Web_DevLoving
- LinkedIn: krishnagupta23
- Link to profile:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@Krishna2323 Please add your link to profile picture and a short bio.

**Comment by tinniaru3005** [comment]
Hey I would like to work on it. Can you please assign it to me?

**Comment by Chadha93** [comment]
> Hey I would like to work on it. Can you please assign it to me?

Sure @tinniaru3005

**Comment by Chadha93** [comment]
@tinniaru3005 How is this coming along? Do you need some help? Hint - you may check out previous similar PRs. // @Krishna2323 Please provide details https://github.com/layer5io/layer5/issues/3445#issuecomment-1309878081

**Comment by tinniaru3005** [comment]
Hey @Chadha93, I have checked out similar PRs and got an idea on how to make the changes. Got a bit buzy with my exams. Will send the PR after @Krishna2323 provides the details. Thanks :)
