### ISSUE TITLE
Providing the border-radius to the video block

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3448]
#### Description

Providing the border-radius to the video block

#### Page Link:

[Home Page](https://layer5.io/)
Before
![Before](https://user-images.githubusercontent.com/67385503/201338261-533cbfce-31fa-4476-bbee-cd543bd00094.jpg)
After
![After](https://user-images.githubusercontent.com/67385503/201338289-83bbb567-b008-4232-a94f-f96c20ed8200.jpg)

https://user-images.githubusercontent.com/67385503/201339641-c51eecb2-026e-4bd7-a0f8-4ce4a3190e91.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote your thoughts on this 👀

**Comment by MohOfficial** [comment]
@UtkarshMishra12 That's a nice idea!

**Comment by furkanmutlu** [comment]
Hi there, can you assign this issue for me?

**Comment by leecalcote** [comment]
Folks, thanks for volunteering. This particular issue isn't a direction that we'd like to head in.

Let's get each of you onto other open issues. Here's one - https://github.com/layer5io/layer5/issues/3017

**Comment by leecalcote** [comment]
And here's a long list of others - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+org%3Alayer5labs+label%3A%22help+wanted%22+
