### ISSUE TITLE
[Community] Member Profile: Franklin Ekoh

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3451]
**Current Behavior**

@franklinekoh has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @franklinekoh as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: franklinekoh
- LinkedIn: franklin-ekoh-a11805122
- Link to profile picture: https://avatars.githubusercontent.com/u/30264870?v=4

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by deepeshaburse** [comment]
@franklinekoh Can you please provide a bio for your community member profile?

**Comment by gogoiakash2311** [comment]
Hey @deepeshaburse, Can I work on this issue?

**Comment by gogoiakash2311** [comment]
@franklinekoh Please provide your bio

**Comment by gogoiakash2311** [comment]
okay thanks, I'll soon make a PR

**Comment by gogoiakash2311** [comment]
@sahilsuman933 @deepeshaburse I have made a PR please check #3458

**Comment by Chadha93** [comment]
Thank you @gogoiakash2311
