### ISSUE TITLE
Images are coming out of the box from 573px to 660px  on the page: layer5.io/cloud-native-management/meshmap

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3456]
#### Description

Images are coming out of the box from 573px to 660p on the page: layer5.io/cloud-native-management/meshmap

#### Page Link:

[Link](https://layer5.io/cloud-native-management/meshmap)

#### Screenshots

https://user-images.githubusercontent.com/67385503/201940392-23518d8f-b981-4c85-8631-8d3c33368daf.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to work on this issue.

**Comment by chiomaT** [comment]
Let me fix this.

**Comment by UtkarshMishra12** [comment]
@chiomaT I'm working on this and waiting for this issue to get assigned to me. 😄

**Comment by kayceeDev** [comment]
@UtkarshMishra12 you can go ahead and make a PR on this when you are finished.
