### ISSUE TITLE
[Article] Use MeshMap screenshots instead of generic Kubernetes diagrams

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3460]
In this [resource article](https://layer5.io/resources/kubernetes/getting-started-with-kubernetes)...

        I would love to see MeshMap screenshots of Kubernetes diagrams as opposed to generic diagrams.

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/pull/3446#pullrequestreview-1183094787_

**Comment by KlausMikhaelson** [comment]
Hey @leecalcote if this issue hasn't been taken than I get this assigned to me ? would love to work on it !
Thank you !

**Comment by leecalcote** [comment]
That'd be most helpful, @KlausMikhaelson. 👍

**Comment by KlausMikhaelson** [comment]
awesome will start with it today !

**Comment by eeshaanSA** [comment]
How far are you with this? @KlausMikhaelson

**Comment by KlausMikhaelson** [comment]
hey @eeshaanSA haven't done it yet I am all new to this stuff was just figuring out, can you just give me today ? if I haven't done it till than you can unassign it, but let me just give it a try today.
hank you !

**Comment by eeshaanSA** [comment]
Yea, no worries. 😁 If you have any queries, you can ask them on slack or on the discussion forum. 💪

**Comment by UtkarshMishra12** [comment]
@KlausMikhaelson Please update !!

**Comment by gurpreet-legend** [comment]
If no one is working on this, can you assign this to me? @leecalcote

**Comment by leecalcote** [comment]
You will have amassed a small pile of issues, @gurpreet-legend. 🙂 Given that your pull requests are moving along at a steady clip, yes, let’s get this item is saying to you as well. 💪

**Comment by gurpreet-legend** [comment]
Thanks @leecalcote, will try to resolve all the assigned issues asap :)

**Comment by leecalcote** [comment]
Doing great so far, I think. 😃

**Comment by gurpreet-legend** [comment]
So, @leecalcote, which MeshMap screenshots of K8 that I need to add exactly?

**Comment by gurpreet-legend** [comment]
@leecalcote screen shots added, you can review
