### ISSUE TITLE
Integrations boxes do not have a sufficient margin(Left & Right), due to which it is touching the extreme left and right of the device screen

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3461]
#### Description

Integrations boxes do not have a sufficient margin(Left & Right), due to which it is touching the extreme left and right of the screen

#### Page Link:

[Link](https://layer5.io/)

#### Expected Behavior

There should be a proper left and right margin.

#### Screenshots

https://user-images.githubusercontent.com/67385503/202512803-0344093f-3344-452f-88df-7542ad5bf7ba.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote I would like to solve this issue.

**Comment by leecalcote** [comment]
Thank you, @UtkarshMishra12. Yes, that would be great.
