### ISSUE TITLE
There should be a margin from the top of the image on the page: layer5.io/community/newcomers

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3462]
#### Description

There should be a margin from the top of the image on the page: layer5.io/community/newcomers
#### Page Link:

[link](https://layer5.io/community/newcomers)

#### Screenshots

Before
![image](https://user-images.githubusercontent.com/67385503/202528104-69d11761-24f3-4227-b771-e7e16838d765.png)
After

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
I would like to take up this issue.

**Comment by UtkarshMishra12** [comment]
@leecalcote can you assign it to me?

**Comment by Harshit-Dandriyal** [comment]
All the best @UtkarshMishra12 :star:
