### ISSUE TITLE
Use "gap" property on flexbox instead of margins on every links in the Navbar to make it symmetric.  

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3466]
#### Description
Use "gap" property on flexbox instead of margins on every links in the Navbar to make it symmetric & align the mode toggle icon in center.
#### Page Link:
Navbar
#### Current Behavior
![CUrrent](https://user-images.githubusercontent.com/85894871/202841167-9ccde4b3-84b1-4b30-93ba-bb14351b380e.png)

#### Expected Behavior 
![Screenshot 2022-11-19 131552](https://user-images.githubusercontent.com/85894871/202841170-ffe6e017-19c3-489c-884d-df4eb13e7a59.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sketchomania** [comment]
Can I work on this ?

**Comment by gogoiakash2311** [comment]
@Krishna2323 Can you assign this to me?

**Comment by Krishna2323** [comment]
@Nikhil-Ladha ^^^

**Comment by Nikhil-Ladha** [comment]
Using `gap` property is a seperate case, but here we don't need/want the nav items to be center-aligned. So, no need of an update there.

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, the padding is not similar on the both sides for the Navbar.

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, pls have a look at the issues above this one🙏

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha, the padding is not similar on the both sides for the Navbar.

As I said, technically code might be updated. But, design wise content shouldn't be center aligned.

**Comment by Krishna2323** [comment]
@Nikhil-Ladha, I am not talking about aligning the whole navbar to center, I am just talking about the mode changing icon to be centered or aligned with other elements in the navbar

.

**Comment by Nikhil-Ladha** [comment]
In short, I don't see an issue with the positioning of the icon as of now.
Not exactly sure, what do you mean by center aligning the mode icon specifically?
In the ss attached it seems like the whole content is center aligned and not the icon specifically

**Comment by sketchomania** [comment]
I  think this issue is regarding the theme change icon "☀️"

![Screenshot_20221119_172119](https://user-images.githubusercontent.com/77732479/202849445-09fff75a-d266-48e6-8689-024874963ad8.png)
![Screenshot_20221119_172020](https://user-images.githubusercontent.com/77732479/202849475-0432e4ae-06a3-4add-b987-ab2b59743a34.png)

**Comment by Nikhil-Ladha** [comment]
Again, as I said technically that's a separate concern.
The changing of alignment is not desired.

**Comment by sketchomania** [comment]
Got it.

**Comment by Krishnapro** [comment]
Hey, is anyone working on this issue?
If no one is working on this issue please assign it to me.

**Comment by UtkarshMishra12** [comment]
@Nikhil-Ladha May I close this issue?

**Comment by Nikhil-Ladha** [comment]
Good to close out.
