### ISSUE TITLE
Remove  "text-align: justify" from paragraph.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3467]
#### Description
Remove "text-align: justify" from paragraph, it makes reading the text harder for the user.
![Screenshot 2022-11-19 133351](https://user-images.githubusercontent.com/85894871/202841414-d524c820-bba8-4825-991e-e4e5c0153ff7.png)

#### Page Link:
https://layer5.io/careers

#### Expected Behavior
![expected](https://user-images.githubusercontent.com/85894871/202841402-a90a49fc-d118-42f9-b444-eeb0d392db9a.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Garvit1809** [comment]
hey, can I work on this issue

**Comment by sketchomania** [comment]
Can I give a shot ?

**Comment by gogoiakash2311** [comment]
@Krishna2323 Can i work on this?

**Comment by Nikhil-Ladha** [comment]
How exactly it makes it "easier to read" ?
Could you please explain 🤔

**Comment by eeshaanSA** [comment]
@Krishna2323 i don't see any difference between your current and expected behaviour screenshots 👀

**Comment by Krishna2323** [comment]
@eeshaanSA What😶?.......I think there is a clear difference between those 2...and if we are not using that property on any other paragraph so what is the reason to use it here?

**Comment by Krishna2323** [comment]
@eeshaanS this property adds extra space between the words to take 100% of the width.

**Comment by Nikhil-Ladha** [comment]
> if we are not using that property on any other paragraph so what is the reason to use it here?

I doubt that's the case. A lot of place we already use justify for the text but depending on the use-case/site design it may vary.

**Comment by eeshaanSA** [comment]
+1 to Nikhil.

**Comment by adrianmarinwork** [comment]
I'm sorry for asking this and I'm probably and ignorant, I'm starting in this world of helping with issues in github repositories I would like to know, if it's only changing a CSS property of a page why don't you do it your self?

**Comment by Nikhil-Ladha** [comment]
> I'm sorry for asking this and I'm probably an ignorant, I'm starting in this world of helping with issues in github repositories I would like to know, if it's only changing a CSS property of a page why don't you do it your self?

Indeed a good question @adrianmarinwork .
The simple reason is to allow many such newcomers to step their foot in this vast world of open-source and kick off the long following journey.  These small issues gives them confidence to take up something as they move forward and gain more confidence regarding the codebase of the repo.

Hopefully, this answers your question 🙂

**Comment by leecalcote** [comment]
Great question. Great answer.

**Comment by Anand-Theertha** [comment]
Hello! Is there a PR requested for the issue? If not, I can take this up! 🚀

**Comment by Nikhil-Ladha** [comment]
Hi, @Anand-Theertha I don't think we intend to fix the issue. We can are good to close this one.
In the meantime, you can look for other open issues and comment on them for assignment.
