### ISSUE TITLE
Align internship programs cards to center.

### ISSUE THREAD

**Issue by Krishna2323** [layer5io/layer5#3468]
#### Description
Align internship programs cards to center.
![Current'](https://user-images.githubusercontent.com/85894871/202841585-a3e4dcfb-3c8a-4eba-9fc7-f9dc135fc57e.png)

#### Page Link:
https://layer5.io/careers

#### Expected Behavior
![Screenshot 2022-11-19 134240](https://user-images.githubusercontent.com/85894871/202841607-d3e919c3-44bf-400b-8f6d-33b92635c119.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sketchomania** [comment]
Can I work on this issue ?

**Comment by gogoiakash2311** [comment]
@Krishna2323 Can you assign this to me?

**Comment by Nikhil-Ladha** [comment]
This is a reasonable issue.
@sketchomania were you able to setup the site locally?
Same applies for you @gogoiakash2311

**Comment by gogoiakash2311** [comment]
Yes @Nikhil-Ladha, I have already setup the site locally

**Comment by sketchomania** [comment]
Yes, I am able to setup this site locally 
just running the `make site` command and it is taking a time ,
@Nikhil-Ladha will it take this much time to run or just first time 

following this guide: https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md

**Comment by Nikhil-Ladha** [comment]
It takes time depending on your system, but eventually the site should be running on localhost:8000.

Let me know if it works out for you or not, based on that I will assign you rhe issue.

**Comment by sketchomania** [comment]
Yes its running on localhost 
http://localhost:8000/careers
and graphql
http://localhost:8000/___graphql

**Comment by sketchomania** [comment]
Thanks for assigning.

**Comment by leecalcote** [comment]
You bet, @sketchomania 👍

**Comment by Ellamsg** [comment]
can i worj on this ?

**Comment by gaurav8y785675474** [comment]
hello  @sketchomania 
can you please tell me exact location of code related to this issue

**Comment by YarinDay** [comment]
@leecalcote Hey bro, I've seen this issue opened too way too long. I'm taking this and will create a PR in few hours
Already ran locally and everything works

**Comment by leecalcote** [comment]
@YarinDay... our hero. 🙂

**Comment by anubhav1206** [comment]
Can I work on this?
