### ISSUE TITLE
No padding in the headline on page: https://layer5.io/service-mesh-landscape 

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3471]
#### Description

No padding in the headline on page: layer5.io/service-mesh-landscape from 

#### Page Link:

[Link](https://layer5.io/service-mesh-landscape)

#### Screenshots

Before 
![image](https://user-images.githubusercontent.com/67385503/203110244-88a00801-ae72-4fa2-b58b-4c354edf9552.png)

After:

https://user-images.githubusercontent.com/67385503/203110793-60118215-4a52-48f9-9520-3e1f43694055.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by gogoiakash2311** [comment]
@UtkarshMishra12 Can you assing this to me
