### ISSUE TITLE
No padding is given to the images inside the block on the page: layer5.io/blog 

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3472]
#### Description

No padding is given to the images on the page: layer5.io/blog . There should be padding in all directions.

#### Page Link:

[Link](https://layer5.io/blog)

#### Screenshots

Before
![Problem](https://user-images.githubusercontent.com/67385503/203387353-95d318fa-2362-43eb-8359-3797cd497862.jpg)

After
![After](https://user-images.githubusercontent.com/67385503/203387385-3f120392-e04d-4913-80e8-942f15b4e288.jpg)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by tinniaru3005** [comment]
Hey, @UtkarshMishra12 I would like to work on this, Can you assign it to me?

**Comment by UtkarshMishra12** [comment]
@leecalcote  @Nikhil-Ladha Your thoughts?

**Comment by Nikhil-Ladha** [comment]
It shouldn't be having a padding at all. It is just the incompatibility of the gatsby-image-plugin to render the image such that it is full-width that causes that blank space in some of the blog's thumbnails. The only, thing that can be improved if you or anyone could take up is to make the image full-width consistently for all thumbnails.
Nothing needs to be changed around padding as such.

**Comment by leecalcote** [comment]
Ditto

**Comment by deep1910** [comment]
Thumbnails of some blogs can be made of Full width like as in the thumbnails of  blogs of third row but  thumbnails of some blogs are square shaped and cannot be stretched further ,I think blogs  which can be adjusted  to the full width can be adjusted and others may have slight padding all over

**Comment by withgaurav** [comment]
Can I work on this issue @leecalcote

**Comment by Nikhil-Ladha** [comment]
I still don't think we should plan to fix anything around this issue until and unless you have a solution thaf makes everything consistent without adding a padding.

**Comment by leecalcote** [comment]
My apologies for only now noticing this issue. Thank you much for opening this @UtkarshMishra12, however, I concur with @Nikhil-Ladha we will only be flailing back and other trading one issue for another (different issues will arise given the varying sizes of thumbnails used). Adding padding statically, and not dynamically calculating based on image height and width relative to the space available  only shifts the problem to a new location.
