### ISSUE TITLE
The boxes are getting close to each other on page  : layer5.io/company/contact

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3474]
#### Description

The boxes are getting close to each other on page  : layer5.io/company/contact

#### Page Link:

[Link](https://layer5.io/company/contact)

#### Screenshots

https://user-images.githubusercontent.com/67385503/203619738-aad9ef94-75eb-4811-9dc6-61ca8aeaad23.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by vasucp1207** [comment]
@UtkarshMishra12, can i work on this issue?

**Comment by UtkarshMishra12** [comment]
@vasucp1207 Are you able to setup the site locally?

**Comment by Aniket13122000** [comment]
can I help here

**Comment by vasucp1207** [comment]
@UtkarshMishra12, I run the project on gitpod.

**Comment by UtkarshMishra12** [comment]
@Harshit-Dandriyal  @Chadha93 Please assign it to @vasucp1207 😄

**Comment by eeshaanSA** [comment]
Here you go @vasucp1207, sorry for the delay. :)
