### ISSUE TITLE
Add style to the drop-down menu scroll bar

### ISSUE THREAD

**Issue by tinniaru3005** [layer5io/layer5#3475]
#### Current Behavior
The scroll bar of the drop-down menu has a simple look

#### Desired Behavior
Make the drop-down menu look better by adding some style to the scroll bar

#### Screenshots / Mockups
![layer5 scrollbar](https://user-images.githubusercontent.com/62856848/204097499-1f859cce-55c7-439c-965a-e837c19c4b84.png)

#### Implementation

Use CSS to add some style to the scroll bar

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by tinniaru3005** [comment]
Hey, I would like to work on this issue and make the changes

**Comment by leecalcote** [comment]
Thank you, @tinniaru3005 👍
