### ISSUE TITLE
[Community] Member Profile: Eeshaan Sawant

### ISSUE THREAD

**Issue by deepeshaburse** [layer5io/layer5#3478]
**Current Behavior**

@eeshaanSA has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @eeshaanSA as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @eeshaanSA 
- LinkedIn: sawanteesh
- Link to profile picture: https://drive.google.com/file/d/13Wx8jzaRPSW0oUHXmfShfLNEogjAeU-V/view?usp=drivesdk

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by deepeshaburse** [comment]
@eeshaanSA Kindly provide us with a bio for your profile.

**Comment by deepeshaburse** [comment]
@leecalcote since no one has asked to be assigned this issue, I'll open a PR for this soon.

**Comment by eeshaanSA** [comment]
I am a CS-Undergrad in my Sophomore year, from Pune, India. I love the world of Open-Source and giving back to it. I am currently learning about Cloud-Computing, and Automation. Its great to be making a Mesh of things here at Layer5. I am a full blown Baker and a Home-Barista in my free time. Feel free to connect with me using any of those links below. 😄

**Comment by eeshaanSA** [comment]
Bio 👆🏻
