### ISSUE TITLE
[Programs] Use light version of the She Code Africa logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3479]
#### Current Behavior
The [internship programs page](https://layer5.io/careers/programs) only has a light mode-friendly version of the She Code Africa logo.

#### Desired Behavior
When site visitors have dark mode enabled, they find it difficult to see the current logo version being used. Instead a dark mode-friendly version of the logo should be used.

#### Screenshots / Mockups
<img width="464" alt="Screenshot 2022-11-30 at 9 42 29 PM" src="https://user-images.githubusercontent.com/7570704/204961702-25cdd586-2ff4-433a-8205-ceae3902f667.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by i-dipanshu** [comment]
Hey @leecalcote 
I've few experience on working with same 
I'd like to give it a try 
and hopefully you guys would like it 😊

**Comment by i-dipanshu** [comment]
A question though 
Do we replace the existing inage with a new both dark and loght mode friendly image 
Or just do some manipulation in the existing image

**Comment by Anita-ihuman** [comment]
That would be great Dipanshu, I will assign it to you right now.

**Comment by leecalcote** [comment]
Perfect. Ideally, avoid CSS filtering as it so often just doesn't turn out as well. Instead a new image would be great. The ideal solution here, though, is to get an official version of the logo from the She Code Africa organization. @Ruth-ikegah @Anita-ihuman

**Comment by yangaarts** [comment]
![sca-3163ab3aa802add0574b8eb2149d1157 darkmode yanga](https://user-images.githubusercontent.com/80072645/205294789-9581f3b4-7a74-4134-8468-516c6d823884.svg)

**Comment by i-dipanshu** [comment]
Found this image in the Footer of [She Code Africa](https://shecodeafrica.org/) website ...
![image](https://user-images.githubusercontent.com/84374342/205335124-df3f1a62-aceb-4f4e-99a6-2bb85016abcb.png)

**Comment by i-dipanshu** [comment]
However, we could not just replace it with the existing one as it will mess up render in the light mode
So, I was thinking to use both the images and render them depending on the current state being dark or light.
I looked for the respective codes :-
1. The image is fetched from [sca-contributhon](https://github.com/layer5io/layer5/blob/master/src/collections/programs/sca-contributhon/index.mdx?plain=1#L3)
2. It is fetched at [refer](https://github.com/layer5io/layer5/blob/master/src/sections/Careers/Careers-Programs-grid/index.js#L27)

Then we loop over to render the image ...
### I was wondering would it be efficient to the change queries and render the image based on the state being dark or light

**Comment by Anita-ihuman** [comment]
I have reach out to Omotola Eunice Omotay(SCA community manager ) to help with a light mode for this issue.

**Comment by yangaarts** [comment]
![sca-3163ab3aa802add0574b8eb2149d1157 darkmode yanga rework](https://user-images.githubusercontent.com/80072645/205384695-0115ce3e-e649-4676-9e80-00643c5e6701.svg)

**Comment by i-dipanshu** [comment]
Anu updates @Anita-ihuman ???

**Comment by Anita-ihuman** [comment]
@i-dipanshu @yangaarts 
![Logo pink bg](https://user-images.githubusercontent.com/62384659/205872650-17e1f79b-d965-41e9-b1f5-eb635efe725d.png)
![Logo (darkbg) ](https://user-images.githubusercontent.com/62384659/205872688-a86a826e-8ec7-4ab7-bfb3-0f16ed4169a7.svg)
![Logo (white bg)](https://user-images.githubusercontent.com/62384659/205872710-b3cd9202-dee4-416a-9a52-2beca117ad1c.svg)

**Comment by Anita-ihuman** [comment]
https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T?usp=sharing

**Comment by i-dipanshu** [comment]
Yeah, 'll be doing the first thing tomorrow

**Comment by UtkarshMishra12** [comment]
@i-dipanshu Please Update!!

**Comment by i-dipanshu** [comment]
So sorry for the delay 
Busy with Exams 
Will update soon

**Comment by UtkarshMishra12** [comment]
@i-dipanshu No issue, please make the changes as soon as possible 😊. It'll hardly take 10 mins.

**Comment by i-dipanshu** [comment]
Hey @UtkarshMishra12, could you please help me with some queries regarding this issue

**Comment by UtkarshMishra12** [comment]
@i-dipanshu Please ask in the slack channel.

**Comment by UtkarshMishra12** [comment]
@i-dipanshu Progress???

**Comment by i-dipanshu** [comment]
**The same issue persists for multiple cards, such as the subheading for the MLH card, Layer5 card, and more.
So, I was thinking of more of universal solution to solve the issue rather than fixing just one.**

**Comment by tinniaru3005** [comment]
@i-dipanshu any update on your progress with the issue?

**Comment by Rishikavishnoi** [comment]
@i-dipanshu Any update ? I want to work on this issue..

**Comment by Nikhil-Ladha** [comment]
Fixed by #3760
