### ISSUE TITLE
List Cloud Native Playground as a frontend project

### ISSUE THREAD

**Issue by HM-8** [layer5io/layer5#3480]
**Current Behavior**
Cloud Native Playground (http://play.meshery.io/) is not listed as a frontend project on the repository overview page.

**Desired Situation**
Add playground as a frontend project with the necessary information.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by tinniaru3005** [comment]
Hey, @HM-8 is there any update on this issue? @leecalcote can you please assign it to me if @HM-8 is no longer working on this issue?

**Comment by HM-8** [comment]
Hi @tinniaru3005. Thanks for reaching out. I am working on it. Paused because of some other reasons. I'll let you know as soon as I can't work on it.

**Comment by tinniaru3005** [comment]
> Hi @tinniaru3005. Thanks for reaching out. I am working on it. Paused because of some other reasons. I'll let you know as soon as I can't work on it.

Okay cool. Thanks for the update

**Comment by HM-8** [comment]
> > Okay cool. Thanks for the update 😊
>
No problem :)

**Comment by UtkarshMishra12** [comment]
@HM-8 Please update

**Comment by leecalcote** [comment]
Parallelized assignment.

**Comment by HM-8** [comment]
@leecalcote @UtkarshMishra12 I apologize for delaying this issue.
