### ISSUE TITLE
[CI] Setup GitHub Action to tweet when issue/tweet label is applied

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3489]
#### Current Behavior
Many new and existing issues can benefit from being posted on Twitter for broader reach of potential contributors and for recognizing the efforts of existing contributors.

#### Desired Behavior
1. Upon application of the `issue/tweet` label, tweet link to issue from [layer5](https://twitter.com/layer5) account.

#### Implementation
1. Use https://github.com/marketplace/actions/send-tweet-action.
    1. `status:` should include the title of the [issue | pull request] - link-to-issue-or-pr #opensource 
    2. e.g. "[CI] Setup GitHub Action to tweet when `issue/tweet` label is applied - https://github.com/meshery/meshery/issues/6612 #opensource"
1. Request or create each necessary GitHub secret at the organization level.

#### Acceptance Tests
1. All `layer5io` repos have `issue/tweet` label, which has color of #eee.
1. The [GitHub Process document](https://docs.google.com/document/d/1FzX-C_xy9hZ3Eu9dcCE0unhFV5LRUrb5YLn_MGYuG6Y/edit) is updated.
1. Label should work on both issues and pull requests.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Adi-ty** [comment]
Hey! I wanted to work on this issue but I guess you will need to add twitter accounts access tokens and secret and also twitter Api key to the repo.

**Comment by ayushthe1** [comment]
Hey @leecalcote ,I made a pr for this issue. Could you please review it.

**Comment by ayushthe1** [comment]
I tested this action on my local repo with twitter account and it was working.
