### ISSUE TITLE
Moving the Legend box(Service Mesh Interface Compliance) in the center to improve the UX/Look on the page: layer5.io/service-mesh-landscape 

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3493]
#### Description

Moving the Legend box(Service Mesh Interface Compliance) in the center to improve the UX/Look.
#### Page Link:

[Link](https://layer5.io/service-mesh-landscape)

#### Screenshots

Before:
![image](https://user-images.githubusercontent.com/67385503/205379021-3f36e55b-d528-4797-a8ac-c4566876e1b3.png)

After:
![image](https://user-images.githubusercontent.com/67385503/205379092-5495bb1c-9366-48a6-8afc-ff353e62d5ce.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote Your thoughts on this?

**Comment by leecalcote** [comment]
The right-alignment is by design. I could go either way. 

I'll suggest that perhaps, this isn't worth the time spent changing.

**Comment by leecalcote** [comment]
I concede my power of vote to @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
I have said it in the past and will say it again (agreeing to Lee's comment), rhe legend is completely fine where it is right now. No changes needed there, the issue can be closed.

**Comment by UtkarshMishra12** [comment]
@Nikhil-Ladha I agree with your thoughts. 🙌
