### ISSUE TITLE
[Blog] Single Post Template/Page: Doesn't use dark mode thumbnail

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3505]
#### Current Behavior
The single blog post on [layer5.io/blog](http://layer5.io/blog) doesn’t apply the dark mode thumbnail defined in the .mdx front matter. 

#### Screenshots / Mockups
Example bug - https://layer5.io/blog/kubernetes/structured-logging-in-kubernetes-with-klog. See https://github.com/layer5io/layer5/blob/7fb2d709884ec9c1ea99120c26991838700faa8f/src/collections/blog/2022/2022-12-05-structured-logging-with-klog/index.mdx?plain=1#L7

<img width="713" alt="Screenshot 2022-12-05 at 4 28 12 PM" src="https://user-images.githubusercontent.com/7570704/205809682-8f8eaed4-4f1a-40ab-99a5-a5193ba42c74.png">

#### Implementation
Update the single blog post page/template so that it uses the dark mode thumbnail.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Adi-ty** [comment]
Hey! I want to work on this issue.

**Comment by leecalcote** [comment]
@Adi-ty I completely missed your message. That sounds great.

**Comment by Shivam-AfA** [comment]
Hey @leecalcote! I would love to contribute to this issue. @Adi-ty are you currently working on this?

**Comment by leecalcote** [comment]
Good of you to ask, @Shivam-AfA. Hopefully, @Adi-ty responds.  In the meantime, let’s give you a chance to tackle it as well.

**Comment by Shivam-AfA** [comment]
@leecalcote Kindly review.
