### ISSUE TITLE
Allow null values for GraphQL queries on integrations collection

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3519]
**Current Behavior**
Missing frontmatter values for certain page attributes cause the build to break / page not to load.

**Desired Situation**
Ideally, when required frontmatter attributes are not present, the item in the collection will be skipped over and that specific item will not be built/published, but the rest of the collection will continue building.

In the case of an integration, ideally, the `published` attribute determines whether a page will publish, allowing entries to be present in the collection that are missing required attributes.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
Here's an example of one type of approach - https://github.com/Isaac-Tait/null-gatsby-repo/pull/1/files

**Comment by leecalcote** [comment]
Another being ```{ ne: null }``` used in the GraphQL query.

**Comment by Nikhil-Ladha** [comment]
Explained the real issue [here](https://layer5io.slack.com/archives/G019GNQGPL4/p1671025215418789?thread_ts=1670872439.389079&cid=G019GNQGPL4) on slack. The use of null values is not an issue here, since we are anyways handling it via the `published` frontmatter.
