### ISSUE TITLE
[Blog] New Post Wanted: "How to switch between Meshery release channels"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3520]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** How to switch between Meshery release channels
**Topic:** Meshery's two release channels: stable and edge
**Core points to convey in the post:** 
1. What the two channels are and the purpose for their segregation. See https://docs.meshery.io/project/contributing/build-and-release#release-channels
1. How to switch channels using `mesheryctl`
2. How to switch channels by editing your meshconfig
3. How to confirm that you have switched using Meshery UI, using `mesheryctl version`, and `mesheryctl system channel view`

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by devilkiller-ag** [comment]
Can I try this issue?

**Comment by leecalcote** [comment]
Sounds real good, @devilkiller-ag

**Comment by devilkiller-ag** [comment]
Thanks @leecalcote

**Comment by leecalcote** [comment]
@deepeshaburse

**Comment by leecalcote** [comment]
@devilkiller-ag in a PR or in a google doc.

**Comment by deepeshaburse** [comment]
@devilkiller-ag any updates? Kindly ping on #blog-kitchen channel on slack in case you need any help.

**Comment by Anita-ihuman** [comment]
@devilkiller-ag we have a [draft](https://docs.google.com/document/d/11L-qWNzmhjfbWXN2oeDCLrkKMuD0sCDK/edit#heading=h.39vpeu2yf7se) for this articles available. Do you think you can proceed with the issue?

**Comment by withgaurav** [comment]
I have written a blog on the topic [Switching Between Meshery Release Channels: A Guide] (https://gauravshukla.hashnode.dev/switching-between-meshery-release-channels-a-guide), Can you please tell me where I have to share this blog? @leecalcote

**Comment by leecalcote** [comment]
@withgaurav great! Since you've posted the blog elsewhere, we will send out a tweet to point it out to the project followers.

**Comment by withgaurav** [comment]
@leecalcote Where I share this blog to you?

**Comment by leecalcote** [comment]
Thanks for picking this up, @thisiskaransgit
