### ISSUE TITLE
Create a community badge for the writing program

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3527]
**Current Behavior**
Since we launched the Layer5 writers program, we've witnessed a significant increase in engagement and received outstanding written contributions.

**Desired Situation**
Would be great to have a badge for the Writers program to appreciate members contributing to this program. 
So we need to: 
- Design a badge for the writers program 
---
[Optional] **Alternatives**

[Optional] **Additional context**

Reference to the "[Recognitions](https://layer5.io/community/handbook/community)" in handbook.

<img width="624" alt="Screenshot 2022-12-19 at 3 26 42 PM" src="https://user-images.githubusercontent.com/62384659/208447935-147b9408-7b36-41a3-9f5f-1f886fcacf05.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by shivam-sharma7** [comment]
@Anita-ihuman can you suggest any of one that need to be added? for reference

**Comment by Anita-ihuman** [comment]
@shivam-sharma7 idealy, every badge in the Layer5 community represents a project except the "community"  and now the Writers badge.
So we are looking for design ideas on what the badge should look like.
After which we create issues to implement it accordingly.

**Comment by eeshaanSA** [comment]
We are in need for a design here, @shivam-sharma7. If you just want to "add" the logo, you will have to wait till we have one ready. But, if you want to give us your ideas, you are welcome. Ping anyone of us on slack.

**Comment by DivineOrji** [comment]
https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1

Figma file Link to Proposed Badge for the Writers Program

**Comment by Anita-ihuman** [comment]
Thank you Divine

**Comment by Savio629** [comment]
Hey @DivineOrji can you share the SVG file for the Proposed UX Badge!

**Comment by DivineOrji** [comment]
Sorry for the late reply guys, here is the link to the SVG file 
https://drive.google.com/drive/folders/1rZX_bqz-jWLJQslQypZ_0cxY6ZydqW9B?usp=share_link
