### ISSUE TITLE
BROKEN LINKS UNDER COMMUNITY PAGE

### ISSUE THREAD

**Issue by Abiey2579** [layer5io/layer5#3528]
# BROKEN LINKS

#### Description
Found some broken links under Community Pages. Links are attached to Map-like image, Anywhere under the community page or maybe even entire site try clicking. `Newcomer's Guide` and `Community Guide` link. The broken link looks like;

![Screenshot 2022-12-19 175745](https://user-images.githubusercontent.com/53899426/208479240-deb30110-5b5b-4def-8077-7b9a8147d0b0.jpg)

#### Page Link:
[Community Page](https://layer5.io/community)

#### Expected Behavior
The Links should be taking users to Google Docs to get their;
1. Newcomer's Guide
2. Community Guide

#### Screenshots
![Screenshot 2022-12-19 171606](https://user-images.githubusercontent.com/53899426/208478226-abce2788-3e2e-457b-aee7-46cb0fac0147.jpg)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
Thanks 🙌 @Abiey2579

**Comment by Udit-takkar** [comment]
@Abiey2579 any update?  are you  still working on this issue ?

**Comment by Abiey2579** [comment]
@Udit-takkar I have fixed the issue and created the PR. 
`https://github.com/layer5io/layer5/pull/3566`

**Comment by Udit-takkar** [comment]
@Abiey2579 okay nice. make sure to mention the issue url in the description of the PR.

**Comment by Abiey2579** [comment]
@Udit-takkar Sure

**Comment by Abiey2579** [comment]
The Issue was fixed.
