### ISSUE TITLE
[Handbook] OpenGraph image for social shares

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3530]
**Current Behavior**
Some pages in the community handbook (layer5.io/community/handbook) are missing opengraph images (in PNG format) for display when a shared URL is unfurled. See example in screenshot.

<img width="591" alt="Screenshot 2022-12-19 at 4 19 47 PM" src="https://user-images.githubusercontent.com/7570704/208538119-d7c92b17-6b53-4555-99e6-b290453855e8.png">

**Desired Situation**
All pages should have an image defined and should be visible when testing using https://cards-dev.twitter.com/validator.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by KlausMikhaelson** [comment]
was trying to see if the issue is still there but ig it has been fixed

**Comment by Udit-takkar** [comment]
<img width="554" alt="Screenshot 2022-12-26 at 1 54 56 AM" src="https://user-images.githubusercontent.com/53316345/209481123-b7c2fdfe-4fde-481c-80bf-1d9b1086936f.png">

@leecalcote  @KlausMikhaelson  yes seem to be working fine

**Comment by leecalcote** [comment]
Try https://layer5.io/community/handbook/repository-overview/

**Comment by KlausMikhaelson** [comment]
@leecalcote tried it on my twitter and it was showing the opengraph image, I even checked that tweet that you have added the ss of ig, below is the ss, maybe it was a device issue ?
<img width="450" alt="image" src="https://user-images.githubusercontent.com/100528412/209585969-9b168190-c5e3-43a1-9795-0c8a1a1f031d.png">

**Comment by leecalcote** [comment]
Oh, my goodness. Interesting. Perhaps, a delay in Twitter's retrieval of the image...

Hmm. Either way, it seems that we don't necessarily have an issue here. Thanks for looking into this @Udit-takkar and @KlausMikhaelson 👍
