### ISSUE TITLE
Add the writers program UX badge to the contributing.md file

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3532]
**Current Behavior**
Following up on issue #3527, it would be great to add this design to the contributing.md file like the other badges.

**Desired Situation**
Add the [writers badge](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1) to the [contributing.md file](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---
[Optional] **Alternatives**
<img width="1250" alt="Screenshot 2022-12-20 at 8 54 28 PM" src="https://user-images.githubusercontent.com/62384659/208754875-e20e0bb7-7ec7-4b22-b136-4319e7a888a9.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by DivyanshuSonwal** [comment]
Hey, Can I work on this issue? Could you please assign me this?

**Comment by UtkarshMishra12** [comment]
@DivyanshuSonwal  We need a design here, If you want to work on this, you will have to wait till the logo is finalized. But, you are free to make one and discuss it on the websites channel.😊

**Comment by DivyanshuSonwal** [comment]
> @DivyanshuSonwal We need a design here, If you want to work on this, you will have to wait till the logo is finalized. But, you are free to make one and discuss it on the websites channel.
Ok, Understood, thanks 😄

**Comment by Anita-ihuman** [comment]
@DivyanshuSonwal  the badge is available now in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1), Do you till wish to take it up?

**Comment by DivyanshuSonwal** [comment]
> @DivyanshuSonwal the badge is available now in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1), Do you till wish to take it up?

Yes, sure

**Comment by b0id** [comment]
I have taken care of this.

**Comment by Anita-ihuman** [comment]
@b0id Whats the status of this PR?
Is it something we can discuss on todays weekly call?

**Comment by b0id** [comment]
@Anita-ihuman I had CI/CD issues and PR was closed by me, due to the PR being linked to another PR where I was not aware of the scope.  It is a simple fix, and I can re-issue a PR for the contributing.md ONLY.  @Nikhil-Ladha had said that the images had been uploaded, but I could not find them in the master branch.  @Nikhil-Ladha please identify the badges in the repository.

**Comment by Nikhil-Ladha** [comment]
Here you go: https://github.com/layer5io/layer5/tree/master/src/assets/images/writer-program

**Comment by b0id** [comment]
@Nikhil-Ladha and the UX badge as well.  Thanks

**Comment by Nikhil-Ladha** [comment]
Updated the previous comment :)

**Comment by b0id** [comment]
@Anita-ihuman 

https://github.com/layer5io/layer5/pull/3657
