### ISSUE TITLE
[Handbook]Add the writers program UX badge to the  file

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3533]
**Current Behavior**
Following up on issue https://github.com/layer5io/layer5/issues/3527 we would like to add the writers ux badge to the  "[Recognitions](https://layer5.io/community/handbook/community)" in handbook.

**Desired Situation**

Add the [writers ux badge](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1) to the Recognitions section for the handbook.

---
[Optional] **Alternatives**

<img width="1250" alt="208754875-e20e0bb7-7ec7-4b22-b136-4319e7a888a9" src="https://user-images.githubusercontent.com/62384659/208755960-19590402-0f0c-4e3b-addc-88e166783beb.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Amishakumari544** [comment]
I want to work on this 🙂

**Comment by Anita-ihuman** [comment]
@Amishakumari544  The badge for this issue i snow available in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1), do you still wish to take it up?

**Comment by Savio629** [comment]
@Amishakumari544 The figma file need access...
So you want Writers UX badge which follows the theme of the above badges?

**Comment by Savio629** [comment]
@Anita-ihuman The figma file need access...
So you want Writers UX badge which follows the theme of the above badges?

**Comment by Anita-ihuman** [comment]
@DivineOrji Please can you share the SVG file links here

**Comment by Anita-ihuman** [comment]
@Savio629, we want the SVG file of the badge which @DivineOrji will drop the link to shortly to be added to the handbook like the image above

**Comment by Savio629** [comment]
@Anita-ihuman So I took a look of the website and only the UX writers badge need to be added in community ->recognition section, right?

**Comment by Anita-ihuman** [comment]
@Savio629 Yes we need both badges, however, this issue is specific to the writer's badge

**Comment by chinu-anand** [comment]
@leecalcote @Anita-ihuman I would like to work on this issue, please assign me this. 😃

**Comment by Anita-ihuman** [comment]
@chinu-anand, Savio started working on this so far as I recall. How about we give it some time to get the PR out there? 
@Savio629 what are the obstacles you are having?\

**Comment by Anita-ihuman** [comment]
@Savio629, we are having out website weekly call in 5 minutes, can you jump so we can discuss this together?

**Comment by Savio629** [comment]
Sorry, I saw your message late. By the way, I'm still facing the issue so for a while I'm using Github Codespaces.

**Comment by Anita-ihuman** [comment]
Please create a discussion on https://discuss.layer5.io/

**Comment by leecalcote** [comment]
Completed.
