### ISSUE TITLE
[Community] Add the writers program UX badge to the members profile

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3534]
#### Description
Since we have now have a community badge for the Writer program, it would be great to have it added to the members profile 

#### Page Link:
- [Members](https://layer5.io/community/members/) 
- Badge is available on [Figma ](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1690%3A10102&t=BDGY3h6mSVmZiBAn-1)

#### Expected Behavior
Add the newly created writers badge to the dropdown on the members profile

#### Screenshots
<img width="678" alt="Screenshot 2022-12-20 at 9 09 54 PM" src="https://user-images.githubusercontent.com/62384659/208757341-6e9708c9-71e6-46b4-8b0b-1709691394d3.png">

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by chinu-anand** [comment]
Hi @Anita-ihuman, I would like to work on this issue. Is the logo design finalized?

**Comment by UtkarshMishra12** [comment]
@chinu-anand We need a design here, If you want to work on this, you will have to wait till the logo is finalized. But, you are free to make one and discuss it on the websites channel.😊

**Comment by chinu-anand** [comment]
Oh sure, I will work on this issue once the design part is finished. 🫡

**Comment by Anita-ihuman** [comment]
@chinu-anand the badge for this issue is available, would you still like to take this up?

**Comment by chinu-anand** [comment]
Yes @Anita-ihuman, I am ready to go. 😄
