### ISSUE TITLE
Various typos across files 

### ISSUE THREAD

**Issue by shivaylamba** [layer5io/layer5#354]
**Description**
Various typos across files in layer5 repo. 

**Expected Behavior**
Bug Fixes in Pull request #353 
**Screenshots**
![image](https://user-images.githubusercontent.com/19529592/76625461-460f6780-655d-11ea-84d7-0eee54dfe30a.png)

**Comment by leecalcote** [comment]
Quality work, @shivaylamba. 👍

**Comment by shivaylamba** [comment]
Thankyou @leecote! I hope to improve even further.
