### ISSUE TITLE
Broken URLs in layer5 newcomers guide https://layer5.io/community/newcomers

### ISSUE THREAD

**Issue by prak30** [layer5io/layer5#3544]
### Discussed in https://github.com/layer5io/layer5/discussions/3543

<div type='discussions-op-text'>

<sup>Originally posted by **prak30** December 22, 2022</sup>
![Screenshot 2022-12-22 070839](https://user-images.githubusercontent.com/89302160/209038649-45f7d0ab-d98c-45cb-a6ab-d16a93c4d541.png)
I have notice that the URLs for Newcomers guide and community guide are broken but the others in the diagram seem to be working fine. Check the image below.
![Screenshot 2022-12-22 070957](https://user-images.githubusercontent.com/89302160/209038844-722060db-f6b1-43fc-8a15-66f53d54e50d.png)
</div>

**Comment by UtkarshMishra12** [comment]
@prak30 @Abiey2579 already opens this [issue,](https://github.com/layer5io/layer5/issues/3528) and we are working on recovering the documents. 
Thanks for opening it & I'm closing it. Feel free to find other issues 😊
