### ISSUE TITLE
The logos are not visible in dark mode (Need separate Logo for Dark Mode) on page: layer5.io/careers/programs

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3547]
#### Description

The logos are not visible in dark mode (Need separate Logos for Dark Mode)

#### Page Link:

[Link](https://layer5.io/careers/programs)

#### Screenshots

https://user-images.githubusercontent.com/67385503/209204990-a94cf4c8-8086-426a-9266-eda5901aa03e.mp4

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by UtkarshMishra12** [comment]
@leecalcote @Nikhil-Ladha ^^

**Comment by leecalcote** [comment]
Good eye. This is certainly a bug/ area for improvement.

**Comment by KlausMikhaelson** [comment]
Hello, would like to work on this issue, so if I am not wrong it's the last 2 logos that are not visible correctly so can I work on it ?
Thank you !

**Comment by UtkarshMishra12** [comment]
@KlausMikhaelson The last logo( [issue](https://github.com/layer5io/layer5/issues/3479))  is taken care of by another contributor, here I'm referring to the Layer5 Logo & MLH logo in dark mode. You can work on this issue.

**Comment by KlausMikhaelson** [comment]
Got it !, for the Layer5 logo ig this one will be good, got this from the footer of the site, for mlh will check for one and send it here in few hrs
<img width="185" alt="image" src="https://user-images.githubusercontent.com/100528412/209425878-f4702da7-6d09-46fc-995e-8e2046755c45.png">

**Comment by KlausMikhaelson** [comment]
Hey, 
so there were some logos available on the mlh site as well i.e. 
![mlh-logo-white](https://user-images.githubusercontent.com/100528412/209432845-eeb70c9b-4386-4ee2-ad0e-e07bb593c655.png)
but even I edited the last one and added white text to make it visible i.e.
![mlh-removebg-preview (1)](https://user-images.githubusercontent.com/100528412/209432862-6e0b80d3-0ddb-4019-9e9f-02f1d049e2a4.png)

so which one should I add ?

**Comment by UtkarshMishra12** [comment]
@leecalcote ^^  (I'll go with the second one  👀 )

**Comment by leecalcote** [comment]
I’ll lean into @UtkarshMishra12’s suggestion. ➕

**Comment by leecalcote** [comment]
@KlausMikhaelson, please, ensure that only SVGs are used. Also, see the brand kits on layer5.io/brand

**Comment by KlausMikhaelson** [comment]
@leecalcote Yup got it ! 
thank you !

**Comment by KlausMikhaelson** [comment]
Hey, just a quick update that I am currently going through the codebase rn since I am all new to it but will create the change changes and make the pr asap

**Comment by leecalcote** [comment]
@KlausMikhaelson thank you for setting expectations upfront.

**Comment by GaganpreetKaurKalsi** [comment]
@KlausMikhaelson Any updates? Let us know if facing any issue.

**Comment by KlausMikhaelson** [comment]
Hey @GaganpreetKaurKalsi sorry for the delay, so I figure out what I had to do but now whenever I am trying to run it locally it stucks at 96% again, should I talk about this on slack maybe ?

**Comment by GaganpreetKaurKalsi** [comment]
Hey @KlausMikhaelson, I did 👀 some people facing similar issue before and got it sorted. Slack would be the best place. Drop your issue in the **websites** channel, and let the community members assist you.

**Comment by b0id** [comment]
I have resolved this issue.  See PR #3617

**Comment by Yashsharma1911** [comment]
Hey, @leecalcote I tried an experiment by adding the background effect that we have in integration logos for dark mode and I think it looks good, it will also create consistency around logos on the website for dark mode, what do you say?

![yy](https://user-images.githubusercontent.com/71271069/218308925-f671ebab-d328-4c1f-a490-45ae928a60d5.png)

**Comment by Nikhil-Ladha** [comment]
This is a better value for the background colors of the card: `rgba(255, 255, 255, 0.1)`, though we still need the other logo (with white text) of MLH for dark mode. And, also the darkness of the background color in light mode needs to be increased a bit.

**Comment by Yashsharma1911** [comment]
Yeah, we need padding correction too let me try for MLH, just for confirmation do we need only SVG or png will also work fine?

**Comment by Nikhil-Ladha** [comment]
SVGs are the preferred choice

**Comment by Yashsharma1911** [comment]
okay let me try 👍

**Comment by Yashsharma1911** [comment]
does this one look good? @Nikhil-Ladha it is a svg 

![Group 6](https://user-images.githubusercontent.com/71271069/218320048-be616430-3bc2-4c81-9881-1ce75e0d6ee6.png)

### actual SVG image
![mlh](https://user-images.githubusercontent.com/71271069/218320073-1d8d66a8-3514-4261-b6a9-1b103b61f1e7.svg)

**Comment by Nikhil-Ladha** [comment]
Yes ✅

**Comment by Yashsharma1911** [comment]
Hey @Nikhil-Ladha you can assign this issue to me I will fix it

**Comment by Nikhil-Ladha** [comment]
Sure, go ahead.
Also, take the dark version of the SCA logo from [here](https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T) and update it.
