### ISSUE TITLE
[Blog] List view doesn't use dark mode thumbnail.

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3551]
**Current Behavior**

On the blogs page, when the list view is selected, it does not use the dark thumbnail when switched to dark theme.

![image](https://user-images.githubusercontent.com/88040318/209358077-13564718-8668-4333-bab6-b9a2d15033d5.png)

**Desired Situation**

Dark and light thumbnails should be used for dark and light themes respectively.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Shivam-AfA** [comment]
I am currently working on this issue.

**Comment by leecalcote** [comment]
This post needs to be converted to a resource article.

**Comment by Chadha93** [comment]
@Shivam-AfA Thank you for the issue and PR, will you do a favor and move the first blog (Terraform with Meshery to resources)?

**Comment by Shivam-AfA** [comment]
Sure @Chadha93 I'll look into it.

**Comment by Shivam-AfA** [comment]
@Chadha93 Do you want it to be converted to a Resource Blog or Resosurce Article?

**Comment by Shivam-AfA** [comment]
@Chadha93 Do you want it to be converted to a Resource Blog or a Resource Article?
