### ISSUE TITLE
Problems with product icons in Layer5's home page

### ISSUE THREAD

**Issue by chinu-anand** [layer5io/layer5#3554]
**Current Behavior**

The product icons in the built-in integrations section on the home page of Layer5's website (https://layer5.io/) have problems. The first three icons from the top left and the second and third icons from the bottom right have this issue:
- Azure Active Directory (AAD): icon does not follow the black and white colour scheme in dark mode and stands out from the rest making it inconsistent.
- Akri: icon is incorrect in the light mode, only the bottom half of the icon is visible and the upper half has vanished.
- Azure Application Gateway: icon is incorrect in dark mode, the details of the icon blends into one and making the icon incorrect and also does not follow the dark mode colour scheme and becomes inconsistent.
- Buildpacks: icon is wrong in light mode.
- CDK for Kubernetes: icon is wrong in dark mode, it's a solid cube design with no detailing.

![Screenshot from 2022-12-24 11-06-17](https://user-images.githubusercontent.com/66985303/209423448-9ef4c9ea-cfff-444c-a47f-f83af57f1a09.png)
![Screenshot from 2022-12-24 11-07-07](https://user-images.githubusercontent.com/66985303/209423456-e3b95e7a-e3f3-4167-b43d-82a6606286ff.png)

**Desired Situation**

Correct icon representation in both light and dark modes.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Shivam-AfA** [comment]
Hi @chinu-anand . I would like to work on this issue.

**Comment by chinu-anand** [comment]
Yeah sure @Shivam-AfA , go ahead and make changes. 😊

**Comment by Abiey2579** [comment]
# ATTENTION

Did you guys realize that there are lots of problems with same icons under
`https://layer5.io/cloud-native-management/meshery/integrations/`

Some Icons are not working correctly in both mode `Light and Dark`

@Shivam-AfA @chinu-anand Check it out
