### ISSUE TITLE
[Writing Program] Add link to GH issue label search for "area/blog"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3565]
#### Current Behavior
The [Writing Program page](https://layer5.io/community/handbook/writing-program) doesn't have a hyperlink for quick reference of GH issues that have been created in search of volunteers to author resource articles and blog posts.

#### Desired Behavior
Add this hyperlink to the Writing Program page - https://github.com/layer5io/layer5/labels/area%2Fblog

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by anthonyhamilton123** [comment]
Happy to work on this issue

**Comment by jeffuofa93** [comment]
Would love to take a stab at this! First time contributing to the project.

**Comment by rohinish404** [comment]
hello,
is anyone working on this?

**Comment by leecalcote** [comment]
Oh, my goodness. I missed these messages. 

@anthonyhamilton123 let’s let you take the first stab at this, moving to @anthonyhamilton123 if this issue is still open in a few days time.
