### ISSUE TITLE
Change carousel arrows to white in dark mode - layer5 Home Page

### ISSUE THREAD

**Issue by Abiey2579** [layer5io/layer5#3568]
#### Current Behavior
In the dark mode you can barely see them because they are black or maybe dark gray, barely visible. 

Check layer5 Home Page
https://layer5.io/
Under `LAYER5 IN THE NEWS` Section

#### Desired Behavior
The arrows should be white so it can be clearly visible for better user experience.

#### Screenshots / Mockups
![Screenshot 2022-12-29 235228](https://user-images.githubusercontent.com/53899426/210019045-660c2f75-7ef4-4ab9-944c-3b8c72aa8ab9.jpg)

# I would like to work on that myself.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Sounds great. Thank you for digging into this, @Abiey2579.

**Comment by leecalcote** [comment]
This same carousel component is also used on the main layer5.io/community page. It is worth having a look to see that carousel is equally affected.

**Comment by Abiey2579** [comment]
## This one Below, is working fine, because regardless of the mode, it's background is dark. So it's fine

![Screenshot 2022-12-30 094134](https://user-images.githubusercontent.com/53899426/210051334-0a5f076c-45a4-4840-b8ed-e160de726f6e.jpg)

**Comment by GaganpreetKaurKalsi** [comment]
Closing this issue as it has been addressed in the above mentioned PR(Merged).
