### ISSUE TITLE
Fix grammatical errors

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3583]
**Current Behavior**

**Link - https://layer5.io/cloud-native-management/meshery/operating-service-meshes**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/210279115-b59e77b9-11ad-49a1-b15b-369e005c3ade.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/210279611-5008bbde-cbc5-4830-b993-d8b143c35fcd.png">

**Desired Situation**

The highlighted text has some grammatical/sentence forming errors. Fix them.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Adi-ty** [comment]
Hey please assign this issue to me

**Comment by Adi-ty** [comment]
I have made necessary changes in the sentences to make them grammatically correct if you suggest any other changes, please do tell me and review this PR

**Comment by GaganpreetKaurKalsi** [comment]
Hey @Adi-ty, thanks for fixing it 👍 🚀
