### ISSUE TITLE
sortBy toggle getting triggered even when clicking outside

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3587]
#### Description

Issue :- the sortBy is getting triggered(sorting is happening) whenever we click on anywhere in the header

https://user-images.githubusercontent.com/54144759/210451275-fb4a478e-06b6-41a9-a44e-0c1b9d67e8fa.mov

#### Page Link:
[Link](https://layer5.io/learn/service-mesh-books/service-mesh-patterns)

#### Expected Behavior
Only when we click on the toggle button, the data should be sorted.
<img width="61" alt="image" src="https://user-images.githubusercontent.com/54144759/210451507-b52dac75-3f82-4284-8dcb-e7ff2821b575.png">

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by akashyadav24** [comment]
@GaganpreetKaurKalsi  I will also like to work on this

**Comment by Manan1304** [comment]
@GaganpreetKaurKalsi  I would like to work on this

**Comment by Oghene-kevwe** [comment]
@GaganpreetKaurKalsi @leecalcote  I am done and I have created a PR  #3588  
It turns out that the bug also prevented the links of Authors/Layer5 image  from opening.

**Comment by GaganpreetKaurKalsi** [comment]
> @GaganpreetKaurKalsi @leecalcote I am done and I have created a PR #3588 It turns out that the bug also prevented the links of Authors/Layer5 image from opening.

Thanks @Oghene-kevwe , will review it 🚀 👍

**Comment by GaganpreetKaurKalsi** [comment]
PR #3588 merged, closing issue.
