### ISSUE TITLE
Show a clear successful confirmation message after submitting MeshMap Beta form 

### ISSUE THREAD

**Issue by avikt18** [layer5io/layer5#3590]
**Description**
Upon submission of the signup form on [layer5.io/meshmap](http://layer5.io/meshmap), the page jumps up abruptly and the confirmation message is mostly hidden below the browser’s current view.
![image](https://user-images.githubusercontent.com/56340999/210855558-a11ef53a-696f-4da3-8dc2-5df1f73b8f6e.png)

**Desired Situation**
Bring the browser's view to the existing Signup Confirmation message smoothly or we can word around and show a modal for the confirmation message.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by leecalcote** [comment]
@avikt18, thanks for this. 👍
