### ISSUE TITLE
Yellow checkbox icon in light theme turning green in dark theme

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3591]
#### Description
The yellow checkbox icon in light theme turns green in dark theme.
<br>

Light Theme: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211053944-8a7ff2a1-89b6-4f1b-b909-6b6f70b0db1f.png">

Dark Theme:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211054065-77f23f6a-1894-47d5-ad7c-1504c3a9cf64.png">

#### Page Link:
https://layer5.io/projects/service-mesh-performance

#### Expected Behavior
The color family for a component should remain consistent across themes.
Change the green to yellow in dark theme as shown below.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211053876-b9064408-f344-4fe0-8101-2de8ea19b43b.png">

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
Need your confirmation for the validity of this issue @leecalcote

**Comment by ffshreyansh** [comment]
Can anyone assign this to me, I would love to start contributing through this.

**Comment by leecalcote** [comment]
Good eye, @GaganpreetKaurKalsi. Yes, I can confirm this is a valid issue. 👍

**Comment by Adi-ty** [comment]
Can I also work on this issue?

**Comment by leecalcote** [comment]
@Adi-ty, if @ffshreyansh doesn't have a PR merged by end of day Monday, yes.

**Comment by leecalcote** [comment]
@Adi-ty here's a different issue that you can file and work on:

We need a light version of the SMP logo to be included on https://github.com/layer5io/layer5's readme. The lettering should be white. Find a copy of that version at layer5.io/brand.

<img width="531" alt="Screenshot 2023-01-06 at 2 52 43 PM" src="https://user-images.githubusercontent.com/7570704/211098096-a08625fe-5a0c-4c4a-adb8-f95fe189bdf8.png">

**Comment by Adi-ty** [comment]
Thankyou @leecalcote which logo do you want me to replace the previous one with
<img width="408" alt="image" src="https://user-images.githubusercontent.com/92062352/211138898-78c74b3e-d675-4cb6-8f67-3bfe0100b75d.png">

**Comment by Adi-ty** [comment]
I guess this one would be nice 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/92062352/211139098-332d68d4-8fee-4ed1-a7a4-5c7cbd276669.png">

**Comment by GaganpreetKaurKalsi** [comment]
@Adi-ty I agree. Let me know if you would like me to create an issue for you.

**Comment by Adi-ty** [comment]
yes please create this issue @GaganpreetKaurKalsi

**Comment by ffshreyansh** [comment]
Hey while setting up the site in my local PC, is it normal to take this much time? @GaganpreetKaurKalsi @leecalcote 


![image](https://user-images.githubusercontent.com/51352120/211143966-f731bc67-e527-44b1-8d06-d0deb90c2ee3.png)

**Comment by GaganpreetKaurKalsi** [comment]
@ffshreyansh I guess it depends on the machine. I am able to build the project in less than a minute.

**Comment by ffshreyansh** [comment]
@GaganpreetKaurKalsi  I think there is an issue in dependencies, I am trying to figure it out from a long time but still getting stuck here. Please let me know if you find any error issues here

![image](https://user-images.githubusercontent.com/51352120/211152593-11ea032b-b98f-4751-b348-532f24382307.png)

**Comment by GaganpreetKaurKalsi** [comment]
@ffshreyansh Put the above screenshot with the issue you are facing in slack under websites channel. Someone will help you out.

**Comment by leecalcote** [comment]
Even better, please post on discuss.layer5.io

**Comment by Adi-ty** [comment]
@ffshreyansh try switching to either git bash or wsl not sure if it would resolve your issue but you can try

**Comment by ffshreyansh** [comment]
@Adi-ty  I tried bro but no help yet, you can start working on this if you want to. I will unassign myself.

**Comment by Adi-ty** [comment]
@ffshreyansh that would be really nice of you but if you still want to give it a try you can

**Comment by ffshreyansh** [comment]
@Adi-ty please go ahead, I would be contributing to other issues without assign once I got my errors cleared

**Comment by Adi-ty** [comment]
Ok @ffshreyansh

**Comment by Adi-ty** [comment]
@GaganpreetKaurKalsi @leecalcote I have made the PR regarding the issue as @ffshreyansh unassigned himself please assign me
