### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3592]
#### Description
<img width="583" alt="image" src="https://user-images.githubusercontent.com/54144759/211056743-b6ae07ce-7552-4e59-87a1-63223b94e755.png">
<img width="731" alt="image" src="https://user-images.githubusercontent.com/54144759/211057124-ce6cbaca-a0ed-4a42-8553-e81eff979b89.png">

#### Page Link:
https://layer5.io/company/news/google-petitions-to-donate-istio-service-mesh-to-cncf
https://layer5.io/pricing

#### Expected Behavior
Correct Bouyant -> Buoyant

The Pricing page contains some spelling errors as well. Kindly fix them.

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Samipya039** [comment]
This will be the first time I will be contributing to anything open-source related. As the query mentions the issue will be fixed.

**Comment by GaganpreetKaurKalsi** [comment]
@Samipya039 It's so good to see that you have chosen Layer5 for your first open source contribution 💯 🚀 . This issue is all yours to work upon. Thanks!

**Comment by Samipya039** [comment]
@GaganpreetKaurKalsi Thank you for your kind words! I would like to mention that some parts of the pricing page could use more compact and straightforward grammar. If it won't be an issue, I would like to edit these minute details 😄 . I will see to it that the original message is not lost and no information is ommitted or misintroduced.

**Comment by GitsOfVivek** [comment]
Is this issue still open?
