### ISSUE TITLE
Inconsistency in navbar item highlight across themes

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3593]
#### Description

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211068122-adbc71cf-c832-4c0e-80ad-5c1bd2ded82c.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54144759/211068031-284824ad-33e5-4895-b5d1-bd2bb18e9550.png">

#### Expected Behavior
Only the active tab should be highlighted in a different color, all others should be same.

#### Environment:
- Host OS: MacOS
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
I propose [for dark theme]
We have `white` color (default) for all the navbar items and turn them `green` when hovered at or active. Same behaviour as in light theme.
@leecalcote

**Comment by Shivam-AfA** [comment]
@GaganpreetKaurKalsi That is a good point. I would take this up quickly if @leecalcote agrees.

**Comment by moazzam07** [comment]
i would like to work on this.

**Comment by Shivam-AfA** [comment]
Hey @moazzam07, have you set up the local environment for the website?
