### ISSUE TITLE
Replace SMP logo with it's light version on Layer5's readme

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#3596]
#### Description
Replace SMP logo on Layer5's readme with it's white version(the lettering should be white)
<img width="531" alt="image" src="https://user-images.githubusercontent.com/54144759/211151842-4392a9fc-2783-4359-a5a1-7805ef9eca31.png">

#### Page Link:
Find a copy of that version at layer5.io/brand

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by GaganpreetKaurKalsi** [comment]
@Adi-ty here you go.

**Comment by Adi-ty** [comment]
Thankyou @GaganpreetKaurKalsi
