### ISSUE TITLE
Icons missing for emissary-ingress and NGINX

### ISSUE THREAD

**Issue by pranav767** [layer5io/layer5#3598]
#### Description
Icons in the meshery integration page for emissary-ingress and NGINX are missing

#### Page Link:
https://layer5.io/cloud-native-management/meshery/integrations/

#### Expected Behavior
In the below image it should not be blank but the image for emissary-ingress
![image](https://user-images.githubusercontent.com/116432455/211199589-d202e66d-4633-490f-b43b-2ad5a58b7c8d.png)
Same is the requirement for NGINX 

#### Environment:
- Host OS: Windows
- Browser:  Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Ellamsg** [comment]
please assign this to me

**Comment by Ellamsg** [comment]
@sassukeuchiha pls assign this to me

**Comment by sassukeuchiha** [comment]
Actually I wanted to work out on this one 😶‍🌫️

**Comment by Ellamsg** [comment]
@sassukeuchiha okay  no problem

**Comment by Ellamsg** [comment]
@sassukeuchiha can i open a nw issue?

**Comment by Ellamsg** [comment]
new*

**Comment by sassukeuchiha** [comment]
Sure 😄 @Ellamsg

**Comment by b0id** [comment]
I browse in dark mode and don't see this problem.  @sassukeuchiha 
![L5SS](https://user-images.githubusercontent.com/115111701/211245136-4be7e350-a175-4afa-9891-07598fb0e187.png)

**Comment by sassukeuchiha** [comment]
Yes in dark mode , we can see the icons for both nginx and emissory-ingress, it is issue for the light mode

**Comment by moazzam07** [comment]
if no one is working i would like to take this up??

**Comment by b0id** [comment]
![12 01 2023_01 29 54_REC](https://user-images.githubusercontent.com/115111701/211994368-26027034-00c2-40b4-a382-6282a9aa687c.png)
@sassukeuchiha 

It appears as if there have been breaking changes to the dark mode?

**Comment by sassukeuchiha** [comment]
Hey, @b0id in our last meet ..someone was discussing this same issue ,so I kept this on hold ... should i close this issue or work on it?

**Comment by b0id** [comment]
It appears to be resolved.

**Comment by randychilau** [comment]
Hi All,

Not sure if this was resolved and an update was not posted here, but hoping this summary will allow this issue to move forward to closed status.

Currently the icons for `emissary-ingress` and `NGINX` are appearing correctly in the [meshery integration page](https://layer5.io/cloud-native-management/meshery/integrations) for light and dark mode.

---

`emissary-ingress`

![image](https://github.com/layer5io/layer5/assets/90356410/17f47950-9e77-4963-8779-6fabe236b87e)
![image](https://github.com/layer5io/layer5/assets/90356410/dbcc178b-c43a-4f07-89b5-1f514d367e81)

---

`NGINX`

![image](https://github.com/layer5io/layer5/assets/90356410/c002ef25-e784-42cb-8f5b-dbf062f1a3e8)
![image](https://github.com/layer5io/layer5/assets/90356410/337bd88b-2ea5-4b52-ad2e-2b7c29e88b83)

---

Based on the above information, I propose this issue should be considered for `closed` status.

Cheers,
Randy

**Comment by leecalcote** [comment]
@Shivam-AfA

**Comment by Shivam-AfA** [comment]
Thanks @randychilau for the summary.
