### ISSUE TITLE
Two logo of same

### ISSUE THREAD

**Issue by moazzam07** [layer5io/layer5#3601]
#### Description
logos in meshery integration page for jaeger is added twice

#### Page Link:
https://layer5.io/cloud-native-management/meshery/integrations/github

#### Screenshots
![image](https://user-images.githubusercontent.com/67731696/211266604-3b98523c-d078-468d-b4fe-c0626142f1b7.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Shivam-AfA** [comment]
Good eye @moazzam07

**Comment by moazzam07** [comment]
@Shivam-AfA  Should I start working on it

**Comment by Ellamsg** [comment]
@moazzam07  can i work on this?

**Comment by leecalcote** [comment]
@Ellamsg, yes, that'd be great. Be aware, though, that this section of the website is not updated in the source code here, but is instead directly sourced from a Google Sheet, changes to which are published on nightly basis. So, as it turns out, this particular section of the site is the only portion that works like this. @Shivam-AfA can provide a link and answer questions. He can update the sheet, while you update in the source here, if you like.

**Comment by Shivam-AfA** [comment]
Sure @leecalcote, I'll take care of that.

**Comment by Ellamsg** [comment]
@leecalcote     @Shivam-AfA  shivam said he would take care of that..i would look for another issue to fix if that's fine

**Comment by Ellamsg** [comment]
@leecalcote i cant seem to find the exact problem on the website page

**Comment by Shivam-AfA** [comment]
No problem @Ellamsg, BTW if you need any help, you can join the Layer5 slack community here: https://join.slack.com/t/layer5io/shared_invite/zt-1mxzruuox-~0kO~D7lXdTdpSJi1xrqQA

Connect with other contributors and you will have your issues resolved.
