### ISSUE TITLE
open source projects icons are not Responsive

### ISSUE THREAD

**Issue by moazzam07** [layer5io/layer5#3609]
#### Description
on the project page icons are not responsive

#### Page Link:
https://layer5.io/projects

#### Screenshots
![image](https://user-images.githubusercontent.com/67731696/211525865-557d2dc1-c6c1-4f87-b786-f2b0333094f1.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by avikt18** [comment]
This issue already exists #3421 @moazzam07
