### ISSUE TITLE
[Community] Member Profile: @TolulopeMO

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3611]
**Current Behavior**

@TolulopeMO has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @TolulopeMO as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @TolulopeMO
- Twitter: @tolulope_ola
- LinkedIn: https://www.linkedin.com/in/tolulopeoladavid/
- Link to profile picture: https://drive.google.com/file/d/19byYtp1T4P8mJRRWLahs6JdqjQRf3qrb/view?usp=sharing
- Location: Lagos, Nigeria
- Short bio: Tolulope Ola-David is a highly skilled technical and content writer with over seven years of experience in the field. He has a proven track record of creating compelling and engaging written content for a variety of audiences and purposes and uses his technical expertise to create clear, concise, and accurate documentation. Tolulope is proficient at conducting research, organizing information, and adapting his writing style to fit the needs of the project. He has excellent communication and interpersonal skills, as well as a passion for staying up-to-date on industry trends and best practices

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by chinu-anand** [comment]
I would like to work on this.

**Comment by Ellamsg** [comment]
@chinu-anand can i work on this pls?
