### ISSUE TITLE
[Discuss] Additional custom emojis

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3616]
#### Current Behavior
The  discussion forum has a number of custom emojis loaded, but is missing a larger set.
#### Desired Behavior
- add meshmap
- add community
- add all community badges

#### Screenshots / Mockups
<img width="607" alt="Screenshot 2023-01-11 at 11 11 07 AM" src="https://user-images.githubusercontent.com/7570704/211871575-0135525b-a9b8-4630-b2af-3d37c7a28653.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
I added [:meshmap: and :community:](https://discuss.layer5.io/admin/customize/emojis).

**Comment by Bhawna1203** [comment]
I am interested in working on this issue.
Can you please again in to me?

**Comment by Chadha93** [comment]
HI @Bhawna1203 Thank you for the heads-up, but this issue doesn't require a PR, it will be updated under the admin panel of discuss forum.
Here's a list of issues you can try: https://github.com/layer5io/layer5/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+no%3Aassignee
Feel free to comment on any of the above issues, I'll assign it to you.

**Comment by Chadha93** [comment]
Closing this one, tracking under [CU](https://app.clickup.com/t/85zrj0npt).
