### ISSUE TITLE
[Blog] Mobile formatting issue on Deploying Linkerd with Meshery post

### ISSUE THREAD

**Issue by jijillery** [layer5io/layer5#362]
**Description**
The "Deploying Linkerd with Meshery" post by @antweiss has a formatting issue when viewed on a mobile device.

**Expected Behavior**
- Text should not be overlapping.
- Video frame should reduce in size and stay within bounds of its container.

**Screenshots**
![Screenshot_20200312-104002](https://user-images.githubusercontent.com/53885109/76908943-f5a74b00-6877-11ea-8873-f12aa84feb93.png)

**Comment by antweiss** [comment]
@jijillery  thanks for opening the issue! I should've done this myself instead of complaining on Slack 😂

**Comment by jijillery** [comment]
Ha! 😆

**Comment by leecalcote** [comment]
A recent update addressed this issue, I believe. A quick confirmation can be made here - https://layer5.io/blog/deploying-linkerd-with-meshery

**Comment by kushthedude** [comment]
> A recent update addressed this issue, I believe. A quick confirmation can be made here - https://layer5.io/blog/deploying-linkerd-with-meshery

Yes, I checked it up. Issue is good to be closed !

**Comment by ashiscs** [comment]
> A recent update addressed this issue, I believe. A quick confirmation can be made here - https://layer5.io/blog/deploying-linkerd-with-meshery

Yes, it looks fine now !!

**Comment by leecalcote** [comment]
Thank you, gents.
