### ISSUE TITLE
[Projects] Add a MeshMap project card

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3621]
#### Current Behavior
The [projects page](https://layer5.io/projects) has a grid cards that list and link to our various projects. The [MeshMap](https://layer5.io/cloud-native-management/meshmap) project is missing.

#### Implementation
Using the MeshMap logo, add another project card into the mix.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by avikt18** [comment]
@leecalcote Can I work on this :smile:

**Comment by Shivam-AfA** [comment]
Go ahead @avikt18.

**Comment by Shivam-AfA** [comment]
@avikt18 That's a really great work you've done there! The first one looks kinda uniformed.

**Comment by avikt18** [comment]
Thanks @Shivam-AfA for your thoughts :smile:

**Comment by avikt18** [comment]
@leecalcote Can u give a brief about the Meshery Catalog card, like its content (title and logo)

**Comment by avikt18** [comment]
how about this orientation?
![image](https://user-images.githubusercontent.com/56340999/213532775-749aedad-1171-4e95-868c-deac7012373f.png)

**Comment by leecalcote** [comment]
@avikt18 for the time being, finish up the MeshMap entry and create a new issue for the Meshery Catalog entry, please.
