### ISSUE TITLE
Typo Error in Makefile

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#3624]
#### Description
There is a typo error in Makefile file. While trying to use `make clean` , it popups a message of no command found. It is because the makefile contains a semicolon and a backslash. 

#### Screenshots
<img src="https://user-images.githubusercontent.com/91362589/212485981-82663b32-246f-464b-a630-61f0b532de4c.png" width="600">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Savio629 I'm not convinced that this is a valid issue. Hmm.

**Comment by Nikhil-Ladha** [comment]
Are you on Windows?
If so, can you share a screenshot of the error message?
And, a successful execution after removing the semicolon, backslash?

**Comment by Savio629** [comment]
#### OS : Windows
#### While using make clean command, the following error would occur : 
<img src="https://user-images.githubusercontent.com/91362589/212526036-67cae267-739f-484e-969b-e5bdc81b4538.png" width="600">

#### Successful execution after removing the semicolon, backlash : 
<img src="https://user-images.githubusercontent.com/91362589/212526043-30711317-221d-45a1-bfd4-a8328673e68e.png" width="600">
