### ISSUE TITLE
Make Pricing cards responsive for Tablet view 

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3626]
#### Description

![image](https://user-images.githubusercontent.com/100678386/212663210-95a402ee-157b-4eb1-af1d-7605aa4fdfe9.png)

#### Page Link:

https://layer5.io/pricing

#### Environment:
- Host OS: Linux
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by eeshaanSA** [comment]
Sounds good.

**Comment by Adi-ty** [comment]
Hey, wanted to work on this if no one is assigned yet

**Comment by Arivanantham1003** [comment]
Hey guys, I'm trying to work on this issue. Could you please accept my request for a Figma file?

**Comment by Nikhil-Ladha** [comment]
@Oghene-kevwe interested in working on the issue?
