### ISSUE TITLE
[Docs] Add learnings from performance analysis into Contributors.md

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3628]
**Current Behavior**
[This effort](https://github.com/layer5io/layer5/pull/3572) to improve the layer5.io site's performance resulted in a few coding practices that we should enforce going forward.

**Desired Situation**
Identify those practices and update the contributing.md to include a description and examples of how they are used.

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by withgaurav** [comment]
@leecalcote Can You please assign this to me? I have understood this issue

**Comment by withgaurav** [comment]
Thank you for assigning me

**Comment by Udit-takkar** [comment]
@withgaurav 👍
