### ISSUE TITLE
[Brand] Add MeshMap brand kit

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3629]
#### Current Behavior
https://layer5.io/brand has all of the project brand kits, but is missing MeshMap.

#### Desired Behavior
Create a new MeshMap section in the brand page.

#### Implementation
1. Create a new section for MeshMap
2. Add the following .zip as a download - 
[meshmap-brand-kit.zip](https://github.com/layer5io/layer5/files/10429792/meshmap-brand-kit.zip)

3. Add a few of the logos as samples.

#### Acceptance Tests
1. Users can see the new section.
2. Users can click on the intra-page nav menu to be directed to the in-page anchor for this new section.
3. Users are pushed a .zip file containing the brand-kit on click of the download button.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by ShuvamChatterjee28** [comment]
Hello, can I please work in this issue? I see that it is a good first issue.

**Comment by leecalcote** [comment]
Hi @ShuvamChatterjee28, sounds real good.

**Comment by ShuvamChatterjee28** [comment]
Thanks man, will start as soon as I back from office.

**Comment by RJ025** [comment]
hello @leecalcote is someone assigned to this issue

**Comment by ShuvamChatterjee28** [comment]
Yes, I am working on it.
