### ISSUE TITLE
List Meshery in CNCF Landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#363]
**Current Behavior**
Meshery should be listed in the [CNCF Landscape](https://l.cncf.io) under the "Service Mesh" category. 

**Desired Behavior**
1. Meshery must have [300 GitHub stars](https://github.com/layer5io/meshery/stargazers).
1. Follow these [instructions](https://github.com/cncf/landscape#new-entries) to create a pull request, that identifies the category and logo for Meshery.

**Comment by Aisuko** [comment]
I'm working on this.

**Comment by kushthedude** [comment]
@Aisuko Why the meshery logo you used in the PR on CNCF's landscape is different than our default ?

**Comment by kushthedude** [comment]
<img width="373" alt="Screenshot 2020-04-23 at 4 09 22 PM" src="https://user-images.githubusercontent.com/44091822/80090251-d7babd80-857c-11ea-8d45-6f8ee1660c2a.png">





### This one is quite better than the above
<img width="700" alt="Screenshot 2020-04-23 at 4 09 31 PM" src="https://user-images.githubusercontent.com/44091822/80090257-d9848100-857c-11ea-8c75-59c93bbc9829.png">

**Comment by kushthedude** [comment]
Here is the logo in SVG Format, if that's the issue .
https://github.com/kushthedude/To-Do-App/blob/development/bin/meshery.svg

**Comment by leecalcote** [comment]
Listed! 🎈 https://landscape.cncf.io/category=service-mesh&format=card-mode&grouping=category&selected=meshery
