### ISSUE TITLE
Add a green dot to the Active filter on the Members Page

### ISSUE THREAD

**Issue by tinniaru3005** [layer5io/layer5#3630]
#### Description

The Active filter on the Members page currently has no dot.

#### Page Link:

[Members Page](https://layer5.io/community/members)

#### Expected Behavior

The active filter should have a green dot.

#### Screenshots

![WhatsApp Image 2023-01-17 at 4 00 44 AM](https://user-images.githubusercontent.com/62856848/212774998-63164a60-c700-4d94-bec3-388f4e118205.jpeg)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Thank you, @tinniaru3005 🙂

**Comment by tinniaru3005** [comment]
I am sending a PR too in a few hours :)

**Comment by leecalcote** [comment]
Oh! Very good. 😀

**Comment by AgniveshChaubey** [comment]
Hii @tinniaru3005, are you still working on it? If no, can I pick this one?
