### ISSUE TITLE
[UI] Card radius is not correctly showing

### ISSUE THREAD

**Issue by Yashsharma1911** [layer5io/layer5#3631]
#### Description
In the given screenshot you can see card radius is not correctly showing

#### Page Link:
https://layer5.io/projects

#### Expected Behavior
I made changes via browser console and It should look like something that screenshot that I provided below

#### Screenshots

**Current**

![Screenshot 2023-01-17 at 10 52 16 PM](https://user-images.githubusercontent.com/71271069/212968196-fa4f22e1-fe71-4743-8221-60967dc76d57.png)

**Expected**

![Screenshot 2023-01-17 at 10 36 03 PM](https://user-images.githubusercontent.com/71271069/212968726-cbe706ac-0332-4efc-9168-0703b4eab966.png)

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Yashsharma1911** [comment]
This issue is coming because the radius is given in % and if we will give it in px it will work fine

**Comment by UtkarshMishra12** [comment]
Good eye 🦅 @Yashsharma1911 Here you go
