### ISSUE TITLE
[UI] Card inside dropdown menu doesn't have even spacing

### ISSUE THREAD

**Issue by Yashsharma1911** [layer5io/layer5#3632]
#### Description
Card inside the dropdown menu doesn't have even spacing on hover in desktop resolution

#### Page Link:
[Link](https://layer5.io/)

#### Expected Behavior
It should have even spacing from top and bottom

#### Screenshots
![Group 6](https://user-images.githubusercontent.com/71271069/212971999-4b643bfb-7358-464e-b851-b85f6890a492.jpg)

#### Environment:
- Host OS: Mac
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sakigo9** [comment]
Hi @Yashsharma1911 Can I pick this issue?

**Comment by AgniveshChaubey** [comment]
@UtkarshMishra12 @Yashsharma1911
I have created a PR resolving the above issue. Please consider reviewing it!
