### ISSUE TITLE
[Epic][Performance] Address the issues reported by the lighthouse GitHub action

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#3634]
**Current Behavior**

On each PR, a [lighthouse workflow](https://github.com/layer5io/layer5/actions/workflows/lighthouseci.yml) runs to test the performance of the site and report any such changes which could adversely affect the site's performance. As per the latest reports, there are various improvements that could be done to improve the performance.

**Desired Situation**

We should aim to reduce (preferably 0) the count of issues reported by the lighthouse action.

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by deek121477** [comment]
Can I work on this issue?
