### ISSUE TITLE
Green dot does not appears when the page is refreshed!

### ISSUE THREAD

**Issue by AgniveshChaubey** [layer5io/layer5#3650]
## Description
This issue is in reference to #3630. The green dot on active members does not appear when the page is reloaded. It appears when the 'Active' filter is reapplied.

### When the page is reloaded: 
![image](https://user-images.githubusercontent.com/113545196/213628074-bd1b0be9-a688-49a0-89fc-76979357c1c2.png)

### When the active filter is reapplied:
![image](https://user-images.githubusercontent.com/113545196/213628308-b96f92ea-ab6e-4d36-8054-47bc7eeb6ef8.png)

## Expected Behavior
A green dot should appear with active filter even when the page is reloaded.

#### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by tinniaru3005** [comment]
#3655 This PR is fixing the issue.

**Comment by AgniveshChaubey** [comment]
> #3655 This PR is fixing the issue.

Okey!
