### ISSUE TITLE
Need rectification in meshery docker extension section

### ISSUE THREAD

**Issue by kushvahasumit** [layer5io/layer5#3651]
### current Behavior 
This [meshery docker extension ](https://layer5.io/projects)section is not optimized for mobile . Make responsive for mobile .

### Implementation
use proper width to set docker section as other section , **optimized for mobile**

### Have a look
![Screenshot_2023-01-20-04-02-13-41](https://user-images.githubusercontent.com/121751224/213587104-0bd87e0c-a03b-4133-97c6-de49ceee21ab.jpg)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by kushvahasumit** [comment]
@leecalcote sir please assign me this one.

**Comment by leecalcote** [comment]
@kushvahasumit, not until you've done what I have requested of you in the Slack channel.

**Comment by kushvahasumit** [comment]
@leecalcote sir, I raised this but I_ don't have option to assign myself . I also cloned this on my pc but having issue i am trying to solve with @avikt18

**Comment by leecalcote** [comment]
Right, you're going to need to do what I've asked you to do in Slack first.

**Comment by kushvahasumit** [comment]
I didn't recall, could you please repeat @leecalcote

**Comment by leecalcote** [comment]
@kushvahasumit I'll let you reopen this issue when you're ready to participate.
