### ISSUE TITLE
Creation of a layer5.io/unsubscribe page

### ISSUE THREAD

**Issue by tinniaru3005** [layer5io/layer5#3656]
#### Current Behavior

Currently, there is no unsubscribe page on the layer5.io website

#### Desired Behavior

Creation of a [layer5.io/unsubscribe](http://layer5.io/unsubscribe) page

#### Implementation

- It will need to post to the same location as [this](https://layer5.us15.list-manage.com/unsubscribe?u=6b50be5aea3dfe1fd4c041d80&id=6bb65defeb)  form does
- It can be formatted in a similar way as [layer5.io/subscribe](http://layer5.io/subscribe) is formatted.

#### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by simplysabir** [comment]
Hey, Can I Work on this Issue? as far as I can understand, I will need to design an unsubscribe page with the functionality.
do let me know if I'm missing out on smthn

**Comment by tinniaru3005** [comment]
Hey @simplysabir, welcome to the community. 🤩 You can go ahead and solve the issue. @leecalcote are there any specifications on the design part or something else that you would like to add?

**Comment by UtkarshMishra12** [comment]
@tinniaru3005 @simplysabir It can be formatted in a similar way as [layer5.io/subscribe](http://layer5.io/subscribe) is formatted. (as suggested by @leecalcote )

It will need to post to the same location as this form does - https://layer5.us15.list-manage.com/unsubscribe?u=6b50be5aea3dfe1fd4c041d80&id=6bb65defeb

**Comment by tinniaru3005** [comment]
Thanks, @UtkarshMishra12 for confirming. @simplysabir you can go ahead and solve the issue. Feel free to ask in Slack if you have any further doubts.

**Comment by leecalcote** [comment]
@tinniaru3005 captured these requirements quite well. There should be a confirmation message displayed once the email address is unsubscribed. Again, look to the layer5.io/subscribe for inspiration.

**Comment by simplysabir** [comment]
Okay thanks, I'll keep you updated !!

**Comment by Aarav238** [comment]
Hey @tinniaru3005  @leecalcote  I would like to work on it.

**Comment by leecalcote** [comment]
@simplysabir any progress? Join the weekly Websites meeting on Mondays (tomorrow), please and let’s help you move forward. 

@Aarav238 let us know when you’ve successively built the website, and then, yes, given the lack of visible progress on the PR, let’s get you rolling on it.

**Comment by simplysabir** [comment]
Hey, I Haven't started the work due to some reasons. From today onwards I'm working on it

**Comment by simplysabir** [comment]
Hey, as mentioned i do started it but seems like i won't be able to fi finish it. I guess i have to move onto another issue.

**Comment by leecalcote** [comment]
Given the amount of time passed, yes, it’s time to reassign. Thanks for letting us know, @simplysabir.

**Comment by Aarav238** [comment]
assign it to me @leecalcote  please

**Comment by tinniaru3005** [comment]
@Aarav238 u can go ahead and solve it.

**Comment by Aarav238** [comment]
Thank you @tinniaru3005

**Comment by leecalcote** [comment]
Hi @Aarav238, this couldn't wait any longer. I've opened a PR that you and @simplysabir are most welcome to review.
