### ISSUE TITLE
[Main] Hero: Unwanted black horizontal line

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3660]
#### Description
On the main page of layer5.io in the 2nd or 3rd rotating hero banner (refresh the main page to rotate through the banners) is an unwanted horizontal black line.

#### Expected Behavior
The line should be removed or not visible.

#### Screenshots
![Screenshot 2023-01-22 at 5 17 52 PM](https://user-images.githubusercontent.com/7570704/213946213-679e2c8c-2871-4c5a-a463-a84b9f902a86.png)

#### Environment:
- Host OS: macOS
- Browser:  Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3> Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by Amishakumari544** [comment]
I want to work on this @leecalcote

**Comment by leecalcote** [comment]
Sounds good

**Comment by YarinDay** [comment]
Hey, @leecalcote, I would like to work on this if possible :)

**Comment by Amishakumari544** [comment]
@YarinDay I am already working on it, please check some unassigned issues :)

**Comment by Amishakumari544** [comment]
Hi @leecalcote I tried to find this line but not visible on chrome or edge browser I dont have mac os so not able to complete this issue. @YarinDay if you have mac os you can proceed

**Comment by ShuvamChatterjee28** [comment]
Hey @leecalcote, I have MacOS. I can try to look into the issue.

**Comment by ShuvamChatterjee28** [comment]
@leecalcote, I also tried, but didn't find that black horizontal line like @Amishakumari544. I have used MacOS Safari, MacOS Chrome, iPhone Safari, and localhost to find that line. But everywhere I go, I find it perfect. @YarinDay, if you have found out the line, then you can move and delete it.

Here is a screenshot taken from MacOS Safari --> 

<img width="1009" alt="Screenshot 2023-01-28 at 7 39 23 PM" src="https://user-images.githubusercontent.com/38078961/215271200-78671854-7abd-4a12-94af-35379703af7f.png">

**Comment by leecalcote** [comment]
This seems like and errant bug. Thank you all for taking a look. Let’s close this given that it isn’t reproducible.
