### ISSUE TITLE
Content Form is taking only a single input

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#3661]
### Description

**Steps to Reproduce:**
1. Go to https://layer5.io/community/handbook/writing-program
2. Click on "Layer 5 Content Form" button
3. Choose the type of content

**The type of content form only lets you select a single option.** 
### Expected Behavior
The form should let the user select multiple options.

### Screenshots

![Screenshot from 2023-01-23 19-27-06](https://user-images.githubusercontent.com/92504666/214275617-f6d96885-2091-4826-8dd0-409a0ee58f2d.png)

### Environment:
- Host OS: Ubuntu
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by UtkarshMishra12** [comment]
@thisiskaransgit  You can read more about it [here](https://github.com/layer5io/layer5/issues/3449#issuecomment-1361126912)

**Comment by thisiskaransgit** [comment]
Oh sorry, I overlooked the open issues! will close it then, thank you @UtkarshMishra12

**Comment by leecalcote** [comment]
Thanks for raising this up, though, @thisiskaransgit
