### ISSUE TITLE
Dark-mode: Unable to see text highlight on selection of text

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3663]
### Description
Site visitors using dark-mode can't see what text they have highlighted with their mouse (when they highlight to copy and paste text on any of the pages).

### Expected Behavior
The selection highlight color should have higher contrast with dark mode. 

### Screenshots

![Screenshot 2023-01-24 at 4 27 04 PM](https://user-images.githubusercontent.com/7570704/214451786-301772da-bcb5-4b3f-92e5-8989626a06d9.png)

### Environment:
- Host OS: 
- Browser:  Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AgniveshChaubey** [comment]
I am able to clearly see highlighted in the dark mode. Can you please elaborate which page you are talking about?

**Comment by chinu-anand** [comment]
https://layer5.io/cloud-native-management/meshery/integrations/kubernetes-ui-server, I think this is the page @leecalcote has faced issue. But also on my end, there is no issue in dark mode.

**Comment by leecalcote** [comment]
Yes, that page is an example.

**Comment by theVJagrawal** [comment]
hey @leecalcote can i work on this issue?

**Comment by tinniaru3005** [comment]
Sure @theVJagrawal. Thanks for your interest in contributing. You can go ahead and solve the issue.

**Comment by AgniveshChaubey** [comment]
> https://layer5.io/cloud-native-management/meshery/integrations/kubernetes-ui-server, I think this is the page @leecalcote has faced issue. But also on my end, there is no issue in dark mode.

same here!

**Comment by leecalcote** [comment]
Have you tried in Safari?

**Comment by leecalcote** [comment]
@theVJagrawal, how about you?

**Comment by theVJagrawal** [comment]
@leecalcote , I tried it in my system, all the texts are clearly visible in SAFARI, I don't see any problem
![WhatsApp Image 2023-01-27 at 10 37 50 AM](https://user-images.githubusercontent.com/112813217/215039047-99ae20b1-d69b-4e8d-99ba-c22401c00853.jpeg)

**Comment by leecalcote** [comment]
What?

Try highlighting text in a paragraph and screenshot it.

**Comment by tinniaru3005** [comment]
![highlight](https://user-images.githubusercontent.com/62856848/215105244-edbddb53-ad16-4be2-8de0-aab1e519dff0.png)
Hey @leecalcote, I tried it out on windows and ubuntu. This is how it looks. Cannot say about Safari though.

**Comment by theVJagrawal** [comment]
![WhatsApp Image 2023-01-27 at 7 38 06 PM](https://user-images.githubusercontent.com/112813217/215106778-83fcdc86-d336-46b6-a3a0-b241f36a9c13.jpeg)
hey @leecalcote , i tried the highlighting the text in safari, it is vague

**Comment by theVJagrawal** [comment]
@leecalcote ,@tinniaru3005 I've an approach to solve this. I was thinking if I should change the highlight color to white and the highlighted text to black. It would be done for all the browsers.

**Comment by ShuvamChatterjee28** [comment]
Same with me too. I can properly see the text in Safari and Chrome in dark mode.

**Comment by Riyan911** [comment]
This issue is with the ::selection pseudo-element. While running Safari on IOS, it does it not support changing this pseudo-element. To keep it simple Safari on IOS does not change colour while selecting text. This is why dark mode users are not able to see the change in color while highlighting. This issue is only with people using Safari on IOS.
Read this doc from MDN to understand: https://developer.mozilla.org/en-US/docs/Web/CSS/::selection#browser_compatibility
![image](https://user-images.githubusercontent.com/107925299/215749361-cd33e5d7-459e-458b-8936-44de67d54e8c.png)

**Comment by Vee339** [comment]
Hello everybody, I want to work on this issue.

**Comment by Anurag1008** [comment]
I had previously worked on the same issue. in skyline.
can I contribute here too ?

**Comment by Savio629** [comment]
Thanks @randychilau for mentioning it in the issue 🙌
Completed via #4296
