### ISSUE TITLE
[Community] Member Profile: UI/UX Badge recognition @DivineOrji

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3664]
**Current Behavior**

@DivineOrji has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @DivineOrji as a contributor and community member by creating a profile on https://layer5.io/community/members.

GitHub: https://github.com/DivineOrji
Twitter: https://twitter.com/Dhee_graphics
LinkedIn: https://www.linkedin.com/in/divine-orji-b99b00170/
Link to profile picture: https://drive.google.com/drive/folders/1KPK6cWf6zWPzPxSJMYwTGwDQmK4RMMeO?usp=sharing
Short Bio: I am Divine Orji, a graduate of Business Management from the University of Port-Harcourt, I love Creating Design solutions for meaningful projects, Open Source Gives me the opportunity to try out new challenges which is really interesting.
Location: Port - Harcourt, Nigeria.

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by tinniaru3005** [comment]
Hey @Anita-ihuman can I take up the issue?

**Comment by Anita-ihuman** [comment]
@tinniaru3005 sure, will assign you right away

**Comment by tinniaru3005** [comment]
Thanks @Anita-ihuman :)

**Comment by leecalcote** [comment]
Ladies, heads-up: https://layer5.io/community/members/divine-orji

**Comment by tinniaru3005** [comment]
> Ladies, heads-up: https://layer5.io/community/members/divine-orji

Looks perfect!
