### ISSUE TITLE
Use of italics looks bad UX 

### ISSUE THREAD

**Issue by ItsRoy69** [layer5io/layer5#3668]
### Description
In the footer of the site we see the about is written in italics which is not used in whole website thus that style needs to be removed

### Expected Behavior

This would look better ![image](https://user-images.githubusercontent.com/78967360/214825682-b7a2c015-c154-452f-875c-679d5fee4599.png)

### Screenshots

![image](https://user-images.githubusercontent.com/78967360/214825486-2d3417b5-65db-488d-9405-29eef88576d8.png)

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ItsRoy69** [comment]
I can work on this issue

**Comment by tinniaru3005** [comment]
Thanks for raising the issue @ItsRoy69  but will have to confirm the design changes before we can assign it to you. @leecalcote what do you think about it? 👀
