### ISSUE TITLE
[Community] Member Profile: Abdullah Rafi

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3669]
**Current Behavior**

@abdullah1308  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @abdullah1308  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/abdullah1308
- Twitter: N/A
- LinkedIn: https://www.linkedin.com/in/abdullah-rafi/
- Link to profile picture: https://drive.google.com/file/d/1GuTV7LFlfWuO6iQj2q2RrKjHpt4W5XNE/view?usp=share_link
- Short Bio: I'm an undergrad student majoring in Information Technology at NIT Karnataka. My interests in cloud systems, open source, and software development led me to be a part of the Layer5 organization where I have been able to work on projects that align with my interests and contribute to the community.  I take great satisfaction in building stuff that is useful to others and Layer5 has enabled me to do so.
- Location: Mangalore, India

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by UtkarshMishra12** [comment]
Here you go @Jittojoyes98 🚀

**Comment by Aarav238** [comment]
i would like to work on this @UtkarshMishra12

**Comment by UtkarshMishra12** [comment]
@Jittojoyes98 Progress ??

**Comment by Jittojoyes98** [comment]
Yes

**Comment by Jittojoyes98** [comment]
Is there a need to add any badges , Also is he a active member. If so status should be added right?
