### ISSUE TITLE
Replace the font family from “Open Sans” to “Qanelas Soft” on layer5.io

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3671]
### Desired Behavior

Replace the font family from “Open Sans” to “Qanelas Soft” on [layer5.io](http://layer5.io/)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Adi-ty** [comment]
I want to work on this issue

**Comment by UtkarshMishra12** [comment]
We have to wait until we get the green flag for proceeding with this @Adi-ty

**Comment by Adi-ty** [comment]
ok @UtkarshMishra12

**Comment by Aarav238** [comment]
i would like to work on it @UtkarshMishra12

**Comment by mohit-marathe** [comment]
Hello @UtkarshMishra12 , I would like to work on this issue. Can you assign it to me?

**Comment by Bidhu1024** [comment]
Hey @UtkarshMishra12 Can You please assign the issue to me? It will be my first contribution. Please assign and help me grow.

**Comment by eeshaanSA** [comment]
Hi all, thank you for taking interest in this issue, but unfortunately this issue has already been solved. Let's find you guys another issue you can work on. // @UtkarshMishra12
