### ISSUE TITLE
Adding popup newsletter signup to the below-mentioned pages

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3675]
### Desired Behavior

Adding popup newsletter signup on all pages of these three collections: blog, integration, and resources. The submit form should post to the same form that the layer5.io/subscribe form POSTs to.

Link to designs - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=3830%3A15&t=iQUENkMiJUMvrHov-4

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by avikt18** [comment]
Hey @UtkarshMishra12, I would like to work on this :smile:

**Comment by avikt18** [comment]
To be sure, the popup has to be added on pages:
1. https://layer5.io/blog
2. https://layer5.io/resources
3. https://layer5.io/cloud-native-management/meshery/integrations/

Right?
@UtkarshMishra12

**Comment by Biswajit-Behera** [comment]
Hello @UtkarshMishra12, can I contribute to this issue?

**Comment by eeshaanSA** [comment]
@Biswajit-Behera sorry for the late response, but I am assuming you still want to work on this issue, so I am assigning it to you.

**Comment by Biswajit-Behera** [comment]
Thank You!
@eeshaanSA kindly give me access to (link to design:-) https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=3830%3A15&t=iQUENkMiJUMvrHov-4
I send a request from beherabiswajit0611@gmail.com

**Comment by Biswajit-Behera** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86191708/218000421-b5d884b7-6d3a-404f-a1fe-33a6315f8b68.png">
Not able to edit as it in view form.

**Comment by Mayaleeeee** [comment]
Hi @UtkarshMishra12 I would love to.work on this.
