### ISSUE TITLE
[Homepage] News section: left and right arrows need improvement

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3682]
### Description
See the screenshot.

### Expected Behavior
Arrow should not be cutoff.

### Screenshots
<img width="488" alt="Screenshot 2023-02-02 at 5 01 34 PM" src="https://user-images.githubusercontent.com/7570704/216470799-bc6a7128-5cba-41b4-83b8-9447e2beae75.png">

### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by mukeshwar9** [comment]
Greetings @leecalcote, can I work on this issue?

**Comment by aman123424** [comment]
Hey @leecalcote , if this issue is not solved yet, can I work on this?

**Comment by Vishrut19** [comment]
Hey! Can I work on this issue ?

**Comment by ShuvamChatterjee28** [comment]
Hello @leecalcote, can I work on this one too? Since it is reproducible only in Mac, hence I have solved it.

**Comment by ShuvamChatterjee28** [comment]
PR Submitted.
