### ISSUE TITLE
[Homepage] Banner4: Not properly responsive; leaving too much whitespace.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3686]
### Description
On the site homepage, on banner4, please see the screenshot for a description of the issue.

### Expected Behavior
These two sections should be closer together at all times.

### Screenshots
<img width="874" alt="Screenshot 2023-02-02 at 7 08 36 PM" src="https://user-images.githubusercontent.com/7570704/216487238-8619998a-239c-4877-a133-2cd50c7dedc6.png">

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Oghene-kevwe** [comment]
Hello, I'll like to work on this

**Comment by ShuvamChatterjee28** [comment]
So, I was searching about this issue, and found out something.

@leecalcote, the OS, I am experiencing this error is = iPadOS (iPad Air), Browser = Safari or any.
For iOS, MacOS and Windows, I am not experiencing this issue.

@Oghene-kevwe, you can produce the same error using using google chrome responsive behaviour. Example below.

<img width="478" alt="Screenshot 2023-02-03 at 3 52 07 PM" src="https://user-images.githubusercontent.com/38078961/216575912-668a9d4c-f644-4582-b742-9b71c25cfa1e.png">

Best of luck.

**Comment by gurpreet-legend** [comment]
@leecalcote , need help here?
