### ISSUE TITLE
[Community] Member Profile: Colby Stoker

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3689]
**Current Behavior**

@b0id has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @b0id as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @b0id 
- Twitter: 
- LinkedIn: <profilename> https://www.linkedin.com/in/colby-stoker/
- Link to profile picture: https://lh3.googleusercontent.com/a/AEdFTp4CZjjxz4hW0P_kBw7ZteyRGxQPFQiOd-F5Y6b1iGw=s288-p-rw-no

A detailed explanation of how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by UtkarshMishra12** [comment]
@b0id kindly provide a bio, Twitter Handle & your location for your profile.

**Comment by ShuvamChatterjee28** [comment]
Hey @UtkarshMishra12, can I do this issue please?

**Comment by UtkarshMishra12** [comment]
@ShuvamChatterjee28 Yes please, but let us wait for the information we need from @b0id

**Comment by ShuvamChatterjee28** [comment]
Sure

**Comment by b0id** [comment]
I will finish this tonight, thanks @UtkarshMishra12

**Comment by Savio629** [comment]
I can contribute to this issue...

**Comment by b0id** [comment]
@UtkarshMishra12 I have prepared the bio. Would you like me to submit the profile template `index.mdx` in this thread, or would you prefer a PR? I am not sure about how you want to go about procuring the image, the link(from google) you submitted is the chosen image.

**Comment by ShuvamChatterjee28** [comment]
Hey @b0id, I think you can give it to me, and I can set your profile up in the page. I have already asked @UtkarshMishra12 to assign me this issue. Thanks.

**Comment by Savio629** [comment]
Regarding the bio, I don't think it would require a new pr.
The image can be uploaded in google drive.
You can refer #3669 issue for better understanding.

**Comment by UtkarshMishra12** [comment]
@b0id You just provide your Bio, location & Twitter handle here, and the rest @ShuvamChatterjee28 will take care of. If you want to update the image then you can provide that.

**Comment by b0id** [comment]
---
name: # Colby Stoker
position: # (e.g. Contributor, Maintainer, MeshMate, Community Manager)
image_path: <see above image>
github: # b0id
twitter: # devB0id
linkedin: # <https://www.linkedin.com/in/colby-stoker/>
location: # Calais, Maine, United States
bio: # "Colby Stoker brings expertise, passion for understanding, and innovation to every project. With over a decade of experience in Linux system administration and a passion for open-source technology, he has developed a knack for managing complex variable environments through feedback-regulation cycles. He approaches challenges willingly, continuously improves his performance with an eagerness to understand and increase efficiency. He appreciates thorough technical documentation. 
He is passionate about the human/community element of open source development. His languages of choice are Rust, Go, and Lua. He holds a Bachelor of Science from Texas Tech University."

badges: # List of badges that this member carries. 
            # Badges represent projects that a member has contributed to.
            # Possible badges include
#  - meshery
#  - meshery-operator
#  - smp
#  - nighthawk
#  - community
#  - landscape
#  - image-hub
#  - patterns
#  - ui-ux
blurb: # (Currently not used) Member's tagline, if they have one (a short quip or phrase)
status: # [Active | Inactive]
maintainer: # [no | yes] Designates whether this member is a project maintainer or not.
meshmate: # [no | yes] Designates whether this member is a Layer5 MeshMate or not.
emeritus: # [no | yes] Designates whether ths member is a Layer5 Meshmate Emeritus or not.
community_manager: # [no | yes] Designates whether this member is a Layer5 Community Manager or not.
published: # [true | false] Controls the visibility of the member profile
---

**Comment by UtkarshMishra12** [comment]
@ShuvamChatterjee28 Now you can proceed & raise a PR 🚀
