### ISSUE TITLE
[Homepage] Banner4: leaving too much whitespace at the top. Responsiveness is not working.

### ISSUE THREAD

**Issue by ShuvamChatterjee28** [layer5io/layer5#3691]
### Description

On the site homepage, on banner4, please see the screenshot for a description of the issue. They are a little far apart, which doesn't look good.

### Expected Behavior

Navbar and next section should be closer together at all times. Making the website appearance look good.

### Screenshots

![Screenshot 2023-02-03 at 4 07 36 PM](https://user-images.githubusercontent.com/38078961/216581113-33d4bcf9-4d65-4f41-b5a0-41c44d046e2c.jpg)

### Environment:
- Host OS: iPad mini
- Browser: Safari/Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShuvamChatterjee28** [comment]
@leecalcote, and @UtkarshMishra12, can you please verify this issue? I have found out this one, while working.

**Comment by ShuvamChatterjee28** [comment]
768 x 1024

**Comment by leecalcote** [comment]
This issue is related to, but seems to be slightly different than https://github.com/layer5io/layer5/issues/3686

**Comment by leecalcote** [comment]
@Oghene-kevwe fyi. Here is a related issue.

**Comment by Oghene-kevwe** [comment]
Thank you @leecalcote  I'm on it

**Comment by ShuvamChatterjee28** [comment]
Hello @Nikhil-Ladha, why is this line here, when we are not showing this?
`max-height: 32rem;`
in 'src/components/BGImage/BGImage.styles.js'?

**Comment by gurpreet-legend** [comment]
@leecalcote @Oghene-kevwe if you are busy I can fix this issue for u?

**Comment by leecalcote** [comment]
@gurpreet-legend this is something of an urgent item. @Oghene-kevwe is doing some fine work, however, we do need this addressed quickly. Yes, please, a helping hand would be great, @gurpreet-legend
