### ISSUE TITLE
[MeshMap] Issues with spacing in "Save time with patterns" section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3693]
A few padding / spacing issues in mobile view:

<img width="556" alt="Screenshot 2023-02-03 at 3 32 53 PM" src="https://user-images.githubusercontent.com/7570704/216715269-f34afcd3-b28c-4a98-ab20-2b9c73b06753.png">

The line height / padding between lines is a bit too much in small to medium window sizes. Please reduce the whitespace.

<img width="794" alt="Screenshot 2023-02-03 at 3 34 52 PM" src="https://user-images.githubusercontent.com/7570704/216715187-daade668-5661-43bf-ae9e-979c5a46ec22.png">

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/3690#issuecomment-1416427185_

**Comment by ritiksaxena124** [comment]
can I work on this issue?

**Comment by harshitphoenix** [comment]
@leecalcote I can work on this issue. Shall I start with this?

**Comment by Shivam-AfA** [comment]
On a first come first serve basis, we'll let @ritiksaxena124 work on this. @harshitphoenix can follow up if some help is needed.

**Comment by ritiksaxena124** [comment]
Thank you @Shivam-AfA for assigning me.
How can I setup it up in local development for changes?

**Comment by Shivam-AfA** [comment]
Check the contributing docs in the layer5 repo. @ritiksaxena124

**Comment by AgniveshChaubey** [comment]
Hey @ritiksaxena124, Hope you have set up your local environment by now, but if you are finding it difficult to set up locally, you can use Gitpod instead.

**Comment by ritiksaxena124** [comment]
I tried setting it up locally using Gitpod but I am still getting an error

 ERROR #11615 
There was an error while trying to load dev-404-page:
 Cannot find module 'react-is'

File: webpack/bootstrap:19:1

**Comment by Shivam-AfA** [comment]
@ritiksaxena124 Did you try setting it up locally using WSL2?

**Comment by ritiksaxena124** [comment]
> @ritiksaxena124 Did you try setting it up locally using WSL2?
I don't know how to set it up using WSL2. could you help me with what steps should I follow to set it up?

**Comment by Shivam-AfA** [comment]
https://learn.microsoft.com/en-us/windows/wsl/install 
@ritiksaxena124 
Install wsl2 using the steps here. Then go to your ubuntu file system (assuming that ubuntu will be the distribution that you chose to install) and clone layer5 repo there. Then run `make setup`,  and then `make site`.

**Comment by ritiksaxena124** [comment]
finally Its running Thank you @Shivam-AfA

**Comment by kushvahasumit** [comment]
is this still open ? can i work on this
