### ISSUE TITLE
Service Mesh Landscape Link 404- Need to know where to redirect.

### ISSUE THREAD

**Issue by b0id** [layer5io/layer5#3707]
### Description

Within "Tools" Section of Service Mesh Landscape, the Nighthawk link is 404

### Expected Behavior

The redirect is to [https://github.com/layer5io/nighthawk](url). The question is where does L5 desire to be directed to?
Most of the other links go to source of project, in this case I would expect it to go to, [https://github.com/layer5io/getnighthawk](url) - ?  Unless the purpose is to redirect to 'envoyproxy/nighthawk' :repo
This is a quick fix, and I can do it, or it can be passed to a newcomer, as it is clearly defined in the screenshots, provided, L5 clarifies exactly where they want the link to go.  See SS below.

### Screenshots
![Screenshot 2023-02-06 005708](https://user-images.githubusercontent.com/115111701/216895877-038eb458-f0d8-4c0f-a691-8b16c35f16f5.jpg)
![Screenshot 2023-02-06 005809](https://user-images.githubusercontent.com/115111701/216895903-627b99b0-5382-495e-9cc0-c759959cb8f3.jpg)
![Screenshot 2023-02-06 005843](https://user-images.githubusercontent.com/115111701/216895912-89aab59b-2f75-4916-8003-363d23ee6446.jpg)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by The-Saras** [comment]
Pls assign me this issue I want to work on it!!

**Comment by UtkarshMishra12** [comment]
Here you go @The-Saras 🚀

**Comment by The-Saras** [comment]
I have solved the issue and have made a PR already! Pls review it :D

**Comment by UtkarshMishra12** [comment]
@leecalcote What is should be ? envoyproxy/nighthawk or  llayer5io/getnighthawk🤔

**Comment by leecalcote** [comment]
1st choice: https://getnighthawk.dev
2nd choice: https://github.com/layer5io/getnighthawk

**Comment by The-Saras** [comment]
Do I have to put both links? @leecalcote. I have put the 2nd link already.

**Comment by leecalcote** [comment]
Please heed @UtkarshMishra12 - https://github.com/layer5io/layer5/pull/3708#issuecomment-1419642054. “The link” refers to the first choice (and only the first choice). Thanks for taking care of this, @The-Saras

**Comment by The-Saras** [comment]
Sorry, but I still didn't get this, do I have to change the link to the first link given by you?

**Comment by UtkarshMishra12** [comment]
@The-Saras Please update the link with the first choice (https://getnighthawk.dev/)
