### ISSUE TITLE
[Community] Member Profile: Partik Singh Bumrah

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3709]
**Current Behavior**

@partik03 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize  @partik03 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @partik03
- Twitter: 
- LinkedIn: https://www.linkedin.com/in/partik-singh-945a87227/
- Link to profile picture: https://res.cloudinary.com/dyrimagyz/image/upload/v1669570723/Profile/WhatsApp_Image_2022-11-27_at_11.08.16_PM_jequee.jpg

A detailed explanation of how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by UtkarshMishra12** [comment]
@partik03  kindly provide a bio, Twitter Handle & your location for your profile.

**Comment by Savio629** [comment]
Hey @UtkarshMishra12 ,I can work on this issue!

**Comment by partik03** [comment]
Bio:-
I am a passionate software developer, and an open source enthusiast.I am currently a second year Computer Science undergraduate student  at IIT (BHU) Varanasi. He is currently contributing to Meshery and also exploring new fields like Web3,Cloud Native etc. Apart from programming I love cricket,gyming and partying.

Twitter:-
@PartikSingh17

Location:-
Amritsar,Punjab,India
