### ISSUE TITLE
Resubscribe hyperlink highlight color is not dark mode friendly

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3714]
### Description
On the [unsubscribed page](https://layer5.io/unsubscribed), the resubscribe hyperlink needs dark mode friendly contrast.

### Expected Behavior
This particular css class should have a light and dark mode.

### Screenshots
<img width="741" alt="Screenshot 2023-02-07 at 11 21 29 PM" src="https://user-images.githubusercontent.com/7570704/217441693-3003e987-6222-4114-8caa-9c9efac3f028.png">

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by moazzam07** [comment]
i would like to work on this issue

**Comment by UtkarshMishra12** [comment]
Here you go @moazzam07 🚀

**Comment by moazzam07** [comment]
what background color should be?
for dark theme

**Comment by Yashsharma1911** [comment]
Hey @moazzam07 you can use `rgb(33, 33, 33)` as background color
