### ISSUE TITLE
[Footer] Overlapping content: newsletter subscription

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3719]
### Description
We're in need of a tweak of the media query as it pertains to the footer.

### Expected Behavior
No overlap of elements.

### Screenshots
<img width="734" alt="Screenshot 2023-02-08 at 5 02 09 PM" src="https://user-images.githubusercontent.com/7570704/217671321-c9d34881-6178-4995-a10a-7f95adb3eb39.png">

### Environment:
- Host OS:  macOS
- Browser:  Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this issue?

**Comment by Biswajit-Behera** [comment]
Hello @leecalcote !
Can I work on this issue?

**Comment by leecalcote** [comment]
Thank you, @Sheikh-JamirAlam 👍
