### ISSUE TITLE
[Landscape] Update Linkerd v2's entry

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#372]
**Current Behavior**
- Linkerd v2 uses Jaeger tracing now
 - Multi-cluster is now supported: https://linkerd.io/2020/02/25/multicluster-kubernetes-with-service-mirroring/ 

**Desired Behavior**
The service mesh landscape should reflect these capabilities.

**Updating the Service Mesh Landscape**
- https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-landscape

**Comment by ashiscs** [comment]
This issue is fixed and needs to be closed..
