### ISSUE TITLE
[UI] UI of subscribe button is not consistent

### ISSUE THREAD

**Issue by Yashsharma1911** [layer5io/layer5#3722]
### Description
As you can see in this video in upper `Subscribe` button on page [layer5.io/service-mesh-landscape](https://layer5.io/service-mesh-landscape) on hover text is getting black and not getting background shadow but in the lower `Subscribe` button you can see text is not getting black and have a smooth white background color

https://user-images.githubusercontent.com/71271069/217872570-e7cb3095-6d10-43b6-b2a6-304f9b49789d.mp4

### Expected Behavior
Upper `Subscribe` button should not change text color and it should have a background shadow on hover

### Environment:
- Host OS:  Mac
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Yashsharma1911** [comment]
If it is by design let me know but I think it should have the consistent design if not I would like to work on this issue

**Comment by bhanuteja1901** [comment]
can i work in this

**Comment by kushvahasumit** [comment]
can you visit again ,i think that works good .this is responsive .

**Comment by kushvahasumit** [comment]
can you visit again ,i think that works good .this is responsive .

**Comment by Girishbari** [comment]
I agree with @kushvahasumit there seems to be no issue now with these buttons

**Comment by kushvahasumit** [comment]
@leecalcote can you please review this issue, or close this one.

**Comment by Mayaleeeee** [comment]
Is this project still available @leecalcote ?

**Comment by leecalcote** [comment]
@Mayaleeeee ask the individual that opened the issue.

**Comment by leecalcote** [comment]
@Mayaleeeee better yet... go look at the site. Do you see the issue on https://layer5.io?

**Comment by Mayaleeeee** [comment]
Thanks Lee

**Comment by Yashsharma1911** [comment]
Thanks for confirming @Mayaleeeee as it has no issue I am closing this issue
