### ISSUE TITLE
Spelling Mistake in Layer5 LFX Page

### ISSUE THREAD

**Issue by ShuvamChatterjee28** [layer5io/layer5#3726]
### Description

In the [Layer5's LFX program page](https://layer5.io/programs/lfx), spelling is written as "Descriptio". Need to fix the spelling.

### Expected Behavior

The proper spelling will be "Description".

### Screenshots

<img width="1440" alt="Screenshot 2023-02-10 at 11 56 28 PM" src="https://user-images.githubusercontent.com/38078961/218169028-b6eb0a62-95a7-4fa1-b726-e8dd4dffc32e.png">

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by kushvahasumit** [comment]
Can I fix this

**Comment by ShuvamChatterjee28** [comment]
Yes, @kushvahasumit you can go ahead. I can not assign you as I am not a member of this repo. Requesting @leecalcote to kindly verify and assign. Thank you.

**Comment by kushvahasumit** [comment]
please have a look on my first Pull request #3734 @leecalcote / @ShuvamChatterjee28

**Comment by leecalcote** [comment]
@UtkarshMishra12 and @eeshaanSA are two, trusted community managers, whom I encourage you to engage as well, and who can help with issue triage.

**Comment by eeshaanSA** [comment]
At it, @leecalcote

**Comment by Ashish020202** [comment]
is it still opn.

**Comment by kushvahasumit** [comment]
Noo it's done

**Comment by ShuvamChatterjee28** [comment]
Closing issue as it is fixed with #3734.
