### ISSUE TITLE
Careers Full-Time position UI

### ISSUE THREAD

**Issue by JasonDsouza212** [layer5io/layer5#3732]
### Description
When hovering over the card of a full-time position, some words appear to be **covered behind the animation**

### Expected Behavior
- One thing we can do to fix the issue is to adjust the **CSS**
- or **remove** the **Animation** [removng it seems to be a good idea because when we hover over the card all the data in it changes the position]

### Screenshots

![Screenshot from 2023-02-11 15-24-23](https://user-images.githubusercontent.com/74404894/218252063-b17b90e0-420e-4f1b-8872-14bfbc06e981.png)
![Screenshot from 2023-02-11 15-24-06](https://user-images.githubusercontent.com/74404894/218252065-54327689-8cff-4840-84a1-130fc673707a.png)

### Environment:
- Host OS: Linux
- Browser: Chrome

**Comment by JasonDsouza212** [comment]
If you clearly state what needs to be done, I believe I can work on it

**Comment by AkashS20** [comment]
I'd like to work on this

**Comment by ayushthe1** [comment]
Assigned to you @AkashS20 :+1:
