### ISSUE TITLE
[UI bug]: Description section not fully responsive in events page

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#3733]
### Description
The text highlighted in the picture is not fully visible and is covered by the footer section on mobile phone. The problem is same with all the event descriptions

### Expected Behavior
We should be able to scroll down and be able to read the full text.

### Screenshots

![WhatsApp Image 2023-02-11 at 4 33 23 PM](https://user-images.githubusercontent.com/89864818/218254768-0658bddd-a855-400a-96ba-ea1288cb2b87.jpeg)

### Environment:
- Android OS
- Browser: Chrome 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks for calling out this issue, @money8203 👍

**Comment by MrBehl06** [comment]
@leecalcote If it is not resolved i want to work on this issue

**Comment by money8203** [comment]
I'm working on it @MrBehl06 . Thanks for your help. You can check out other issues which are not assigned or create a new one if you see any bug :)

**Comment by money8203** [comment]
@MrBehl06 wanna work on this, I'm real busy atm

**Comment by AkashS20** [comment]
I'd like to work on this issue
