### ISSUE TITLE
[UI] Header menu item container does not have background shadow on hover in Dark mode

### ISSUE THREAD

**Issue by Yashsharma1911** [layer5io/layer5#3738]
### Description
On hover there should be a little white shadow in dark mode as there is grey shadow in light mode

https://user-images.githubusercontent.com/71271069/218280487-43fc2c3b-8ba8-45f3-b0a1-17955fdcd327.mov

### Expected Behavior
There should be white shadow on hover

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
This is great. You're right that each behavior and each color from light mode should be represented inverted in dark mode.

**Comment by Abbhiishek** [comment]
Hey @leecalcote  @Yashsharma1911 

Is this issue assigned ? as I would like to work on this 🙂

**Comment by Yashsharma1911** [comment]
Hey @Abbhiishek thanks for raising your hand but I already fixed this issue we have other good first issues on which you can work
