### ISSUE TITLE
[UI] Meshmap and Events Page overflow issue 

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#3742]
### Description
There is a page overflow on the right side of the Meshmap page and Events page at a middle-size resolution

### Expected Behavior
The overflow should be removed so that consistency be maintained

### Screenshots
Events Page: https://layer5.io/community/events
![events page overflow error](https://user-images.githubusercontent.com/51539117/218310478-a8c32497-f114-4a31-a2cf-a81a1e997bba.JPG)

Meshmap Page: https://layer5.io/cloud-native-management/meshmap
![meshmap page overflow error](https://user-images.githubusercontent.com/51539117/218310480-1f82ba65-8057-443e-a419-a9abf63cc1f8.JPG)

### Environment:
- Host OS: 
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks, @ritiksaxena124 👍

**Comment by realswikarrr** [comment]
Hi , would love to work on this if anyone else have not started working on this ?

**Comment by ritiksaxena124** [comment]
yeah sure @leecalcote please assign this to him.

**Comment by realswikarrr** [comment]
@ritiksaxena124  thank you so much

@leecalcote i have created the pull request for solving this issue do check it out
