### ISSUE TITLE
[Learn] Academic Partners image issue

### ISSUE THREAD

**Issue by oneknucklehead** [layer5io/layer5#3743]
**Current State:**
The current state under the partners routes shows the same logo for the two different university under the academic partners section
![image](https://user-images.githubusercontent.com/75200954/218312583-6c2a57ad-7c1c-46c9-a576-726e927fcd7f.png)

**Desired State:**
The following should be the desired output:
![image](https://user-images.githubusercontent.com/75200954/218312630-5d04e2fb-3cee-44f1-b660-e8affa5c1b08.png)

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by kushvahasumit** [comment]
can I work on it ...........please provide more details like pagelink or image link.
