### ISSUE TITLE
[Home] Banner 4: Video overlapping with text

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3745]
### Description
The following issue occurs in high resolution windows:

<img width="1128" alt="Screenshot 2023-02-12 at 11 15 11 AM" src="https://user-images.githubusercontent.com/7570704/218326281-3efc878c-bb27-4e5a-a1bc-4ee399f1b213.png">

### Expected Behavior
Video should stay within it's own space (not overlap text).

### Environment:
- Host OS: 
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Manishch27** [comment]
@leecalcote can I work on this issue ?

**Comment by leecalcote** [comment]
Thank you, @Manishch27. That would be helpful.

**Comment by Mayaleeeee** [comment]
Hi @leecalcote 
Is this a design project? Of yes, I would love to work on it.

**Comment by Savio629** [comment]
Ccompleted via #3710
