### ISSUE TITLE
[Community] Member Profile: Arunima Chaudhuri

### ISSUE THREAD

**Issue by eeshaanSA** [layer5io/layer5#3749]
**Current Behavior**

@tinniaru3005  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @tinniaru3005  as a contributor and community member by creating a profile on https://layer5.io/community/members.

GitHub: https://github.com/tinniaru3005
Twitter: https://twitter.com/arunimastwt
LinkedIn: https://www.linkedin.com/in/arunima-chaudhuri/
Link to profile picture: https://drive.google.com/file/d/1TWODLl6whWGhUdPeq81KVC1ReKoQ9VZ-/view?usp=share_link
Short Bio: I am a final-year undergrad student majoring in Computer Science Engineering. I love contributing to open-source projects. I have learnt a lot while contributing to projects at Layer5 and interacting with the community. My contributions are mainly in front-end projects. I also write blogs on Hashnode. I love sharing my knowledge and experiences with others and learning from their backgrounds and journey. I try to give my best in whatever I do. I love travelling and meeting new people from around the world. I also enjoy listening to music and reading books.
Location: Kolkata, India 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this?

**Comment by eeshaanSA** [comment]
@Sheikh-JamirAlam, I see you have already made a PR. Although that is helpful of you, please don't raise a PR unless you are assigned for the issue. This, I think, will be your second warning. Please prevent this from happening in future. Because there is no prior interest on this issue, I am assigning this to you. But, had there been a prior interest, your PR would not have been considered.
