### ISSUE TITLE
Add Event Location in the Event Section

### ISSUE THREAD

**Issue by ShuvamChatterjee28** [layer5io/layer5#3750]
### Current Behavior

Currently in the event section, we have cards to show events but the locations of the event is not showing anywhere.

### Desired Behavior

A location tag with location in the events card will be a good enhancement.

### Screenshots / Mockups

<img width="1440" alt="Screenshot 2023-02-13 at 4 24 28 PM" src="https://user-images.githubusercontent.com/38078961/218439722-e9f036ad-d8e5-4fe0-a80a-44e12b60e587.png">

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShuvamChatterjee28** [comment]
Dear maintainers, I have done similar thing for another project, hence thought to add it here.

**Comment by Ashish020202** [comment]
Have to add event location on the card,  I  mean is it ok below dates section.
or is there any other case?

**Comment by ShuvamChatterjee28** [comment]
That is why I have asked maintainers to describe. Once they clarify, I wish start to work on this.

**Comment by eeshaanSA** [comment]
Where will you put the location? @ShuvamChatterjee28

**Comment by ShuvamChatterjee28** [comment]
The ideal place for the location will be @eeshaanSA, where the type of event (Event/Meetups) is on the card. I am saying because we have a dedicated section to see events, meet-ups, and workshops.

Please suggest if I am mistaken anywhere.

**Comment by ShuvamChatterjee28** [comment]
@eeshaanSA and @Nikhil-Ladha, will it be a good solution? Please see the last comment.

**Comment by Nikhil-Ladha** [comment]
Maybe not on the card, but on the individual pages for each event. Like, a subtitle similar to what we have on single blog pages.

**Comment by ShuvamChatterjee28** [comment]
Sounds good, should I do that @Nikhil-Ladha?
