### ISSUE TITLE
Vertical timeline is not coherent in Dark Mode

### ISSUE THREAD

**Issue by ShuvamChatterjee28** [layer5io/layer5#3751]
### Description

I was seeing the Landscape page in dark mode and the vertical timeline is very hard to spot.

<img width="1440" alt="Screenshot 2023-02-13 at 3 09 12 PM" src="https://user-images.githubusercontent.com/38078961/218448295-b9afbbd1-c795-40db-b5d9-f88d85586353.png">

### Expected Behavior

The timeline colour must adapt with the dark mode.

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Sheikh-JamirAlam** [comment]
How about this? I changed the color to be a bit brighter. Should I work on it?
![image](https://user-images.githubusercontent.com/48979376/218493714-a8c99c6d-8616-4714-8c6b-2ed33e675d1f.png)
