### ISSUE TITLE
[UI] Inconsistent button behavior on hover

### ISSUE THREAD

**Issue by oneknucklehead** [layer5io/layer5#3757]
### Description
The following video shows the issue: 

https://user-images.githubusercontent.com/75200954/218549292-ac76a7e1-4c57-4f12-b3b2-743553d375fd.mp4

### Expected Behavior

Basically, the button should have box shadow on hover and text should be black.

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by oneknucklehead** [comment]
If this issues does not align with the design aspect, can i get assigned to this?

**Comment by leecalcote** [comment]
Thanks for raising this, @oneknucklehead

**Comment by money8203** [comment]
@oneknucklehead Has the issue been completed or you're still working on it!!

**Comment by AkashS20** [comment]
I'd like to work on this issue
