### ISSUE TITLE
Fix the Search Bar position  UI

### ISSUE THREAD

**Issue by Rishikavishnoi** [layer5io/layer5#3758]
### Description
Fix the position of the search bar on the blog page 
Link :- https://layer5.io/blog

### Expected Behavior

Basically ,Centering the search bar on the blog page 

### Screenshots
![Screenshot 2023-02-13 202342](https://user-images.githubusercontent.com/84177590/218566318-1707604c-0e27-45af-b4b9-f85d7b9a42e4.jpg)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Abhishek-kumar09** [comment]
ongoing conversation: https://layer5io.slack.com/archives/C015QJKUMPU/p1676300268982309

**Comment by leecalcote** [comment]
![Uploading Screenshot 2023-02-13 at 3.22.02 PM.png…]()

**Comment by leecalcote** [comment]
@Rishikavishnoi a small bump up here will solve the issue - 
<img width="1348" alt="Screenshot 2023-02-16 at 8 10 10 AM" src="https://user-images.githubusercontent.com/7570704/219387850-371ca4a5-1873-4463-949d-eac077862c8d.png">
