### ISSUE TITLE
[UI] spacing between cards should be corrected

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#3759]
### Current Behavior
spacing between cards is not correct

![cards-error](https://user-images.githubusercontent.com/51539117/218647213-1323624d-3892-49f1-870b-e7d8e417a900.JPG)

### Desired Behavior
![desired](https://user-images.githubusercontent.com/51539117/218647406-63cd6cf9-4817-4c81-ba60-d9d9b4bf5d44.JPG)

### Implementation
Add margin-bottom to the cards

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by swagataroy30** [comment]
Yeah, from 989px - 912px is having the issue, as i just checked. If it is approved, can i work on this?

**Comment by Ashish020202** [comment]
can i work on this .

**Comment by leecalcote** [comment]
Assigning in FIFO order..
