### ISSUE TITLE
Service mesh performance home page icon not aligned centered

### ISSUE THREAD

**Issue by sudhanshutech** [layer5io/layer5#3763]
### Description

The home page of the mesh performance icon is not aligned at centered as others are
![image](https://user-images.githubusercontent.com/90546692/219043515-a52f94bb-4d1b-445a-a27b-0d9cb2eb1ca4.png)

but the other ones are aligned centered like
![image](https://user-images.githubusercontent.com/90546692/219043740-628b3ee0-fc62-4b6e-b276-b7ab758cf07d.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/90546692/219043343-76020388-83e7-45a7-ba4a-dc737c30fbfd.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by pratikdongre** [comment]
@sudhanshutech Hello Sir ! I would like to work on this issue .

**Comment by UtkarshMishra12** [comment]
Are you able to run the website locally @pratikdongre ??

**Comment by oeuvars** [comment]
Hello! Can I work on this issue?

**Comment by pratikdongre** [comment]
hey @oeuvars  i'm working on this. if my PR gets rejected then you can work on it .

**Comment by oeuvars** [comment]
oh cool! Hope you do it. :)

**Comment by sudhanshutech** [comment]
Is anybody working on it? If not I would like to

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by AkashS20** [comment]
I'd like to work on this issue
