### ISSUE TITLE
Add more custom emojis to discussion forum

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3765]
### Description
Missing MeshMate and others...

...add all community badges, and project logos.

### Screenshots
<img width="370" alt="Screenshot 2023-02-15 at 11 56 36 AM" src="https://user-images.githubusercontent.com/7570704/219113933-22326647-a9c3-41b7-9ce5-f653e94d0d29.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by eeshaanSA** [comment]
![image](https://user-images.githubusercontent.com/100678386/219346447-d2579ac1-ebfb-4a4b-a845-00063395db9f.png)
hmm?

**Comment by leecalcote** [comment]
@money8203, I think that @Chadha93 completed this one. Will you confirm?
