### ISSUE TITLE
Highlighting behaviour is missing in dark mode

### ISSUE THREAD

**Issue by ShuvamChatterjee28** [layer5io/layer5#3770]
### Description

In the light mode, when we hover in the list section of this [page](https://layer5.io/learn/service-mesh-books/service-mesh-patterns), we can see some highlighting behaviour.

<img width="1440" alt="Screenshot 2023-02-16 at 9 28 24 PM" src="https://user-images.githubusercontent.com/38078961/219420273-8369c9eb-8dba-4a59-ad28-12009f5dec0a.png">

The same is missing on the dark mode.

<img width="1440" alt="Screenshot 2023-02-16 at 9 28 49 PM" src="https://user-images.githubusercontent.com/38078961/219420350-0911c8e7-74d2-4b6e-b888-f2f8bcdf5f8c.png">

### Expected Behavior

It should show the same type of behaviour in the dark mode too.

### Environment:
- Host OS: MacOS/Windows
- Browser: Chrome/Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShuvamChatterjee28** [comment]
I would like to work on this one.

**Comment by thealoneshadow** [comment]
Is Anyone working on this? Can I work on that?

**Comment by Dheeraj12121** [comment]
![Screenshot_20230303_033354](https://user-images.githubusercontent.com/55842638/224488408-ca4e71cb-d532-40e7-a21a-9df4c550e2e1.png)

**I Fixed this issue **

**Comment by Dheeraj12121** [comment]
Now it highlight in them same as them color

**Comment by Dheeraj12121** [comment]
This is my fist contribution. 😍 I'm feel good

**Comment by Dheeraj12121** [comment]
This is my first contribution I feel good about it.

**Comment by ShuvamChatterjee28** [comment]
@Dheeraj12121 please ask before start working on some issue. 

What is the PR number?

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by Dheeraj12121** [comment]
I want to work on this issue or bug

**Comment by AkashS20** [comment]
I'd like to work on this

**Comment by ayushthe1** [comment]
it's assigned to you now @AkashS20 .
