### ISSUE TITLE
[Community] Member Profile: Yash Sharma

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3775]
**Current Behavior**

@Yashsharma1911  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Yashsharma1911  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Yashsharma1911 
- Twitter: https://twitter.com/yashsharma_f
- LinkedIn: https://www.linkedin.com/in/yash-sharma-4276b61b5/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by UtkarshMishra12** [comment]
@Yashsharma1911  kindly provide a bio, image & your location for your profile.

**Comment by Yashsharma1911** [comment]
🥳 It's great to be part of Layer5 community thanks @UtkarshMishra12

**Comment by Yashsharma1911** [comment]
Profile image link - [link_profile](https://drive.google.com/file/d/17x2WglcyG4Z5zLbAQL9zo2MEqcamD-JA/view?usp=sharing)
Bio - Hi there! I'm an enthusiastic technology lover who's always on the lookout to contribute to open-source. My interest lies in coding with React and Golang, and I've had a lot of fun using these tools to build some cool things. I also believe in the importance of learning and growing as a community, that’s why I like sharing what I have learned and love connecting with new people. So you can hit me on my social handles let’s connect

**Comment by leecalcote** [comment]
Well, well, well... 😄

**Comment by Rishikavishnoi** [comment]
@UtkarshMishra12 Can I work on this?

**Comment by UtkarshMishra12** [comment]
@Rishikavishnoi Hey, this has already been done by me I just have to raise a PR. You can work on another issue. 😄

**Comment by leecalcote** [comment]
@UtkarshMishra12 link to where to find an open, help wanted issue?

**Comment by Rishikavishnoi** [comment]
@UtkarshMishra12 okay 👍No problem
