### ISSUE TITLE
[Community] Member Profile:  Shivam Sood

### ISSUE THREAD

**Issue by UtkarshMishra12** [layer5io/layer5#3783]
**Current Behavior**

@Shivam-AfA  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Shivam-AfA  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Shivam-AfA 
- Twitter: @SoodX21
- LinkedIn: https://www.linkedin.com/in/shivam-sood-66005a1a0/
- Link to profile picture: https://drive.google.com/file/d/1D6e2DekUbQczKWob1YMTBNEdr5LsHXoS/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by UtkarshMishra12** [comment]
@Shivam-AfA kindly provide a bio & location for your profile.

**Comment by Shivam-AfA** [comment]
@UtkarshMishra12 

**Location:** Bathinda, Punjab, India.
**Bio:** Shivam is an aspiring software engineer, currently graduating from National Institute of Technology, Jalandhar. He aims to impact the world of engineering through never-ending passion and curiosity in advancing technologies. He is exploring open source with an inclination towards full-stack development, cloud-native technologies and DevOps in general.

**Comment by Avi-88** [comment]
Hi @UtkarshMishra12 , I would like to take up this task. I have checked out the members template in the collections directory. Apart from adding shivam's profile there , could you please guide me on what more changes will be required, thanks
