### ISSUE TITLE
[UI] The GitHub logo should be replaced with light-version when site in dark-mode

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#3785]
### Current Behavior
when in dark mode the GitHub logo is in black on https://layer5.io/cloud-native-management/meshery/operating-service-meshes

![logo-error](https://user-images.githubusercontent.com/51539117/219962780-dafacbdd-356f-4bab-b0cc-5b8995700b21.JPG)

### Desired Behavior
The GitHub logo should be replaced with the light version of it when the site is in dark-mode 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by nerdynikhil** [comment]
Hey @ritiksaxena124, I want to work on this issue.

**Comment by Anita-ihuman** [comment]
@nerdynikhil sure, go for it

**Comment by Udit-takkar** [comment]
@hirentimbadiya

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya you can start working on this

Thanks @Udit-takkar
