### ISSUE TITLE
[UI] Table isn't scrollable on small screens

### ISSUE THREAD

**Issue by oneknucklehead** [layer5io/layer5#3788]
### Description
The following table is not scrollable on small screens.

https://user-images.githubusercontent.com/75200954/219972787-6682a8dd-76d5-42d6-b72e-6904b124cb7d.mp4

### Expected Behavior
The above mentioned table should be scrollable on smaller screens.

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by swagataroy30** [comment]
Can i work on this?

**Comment by Faizan711** [comment]
is anyone working on this issue?, if not then i would like to be assigned to it.

**Comment by Avi-88** [comment]
Hi @oneknucklehead , as this has become a duplicate issue and there is already someone actively working for the fix , It'd be good if you could close this issue to avoid confusion , thanks
