### ISSUE TITLE
[Handbook] Use light version of the She Code Africa logo

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3790]
### Description
The [mentorship programs](https://layer5.io/community/handbook/mentorship-programs) only has a light mode-friendly version of the She Code Africa logo.

### Expected Behavior
Would be good to have a logo that  is friendly to both darkmode and light mode on the handbook.
Find the various SVG files to the logo here

- https://drive.google.com/drive/folders/12jwnp_ft1gNb-wM_HvZjSmV_DGfopf1T

### Screenshots
<img width="1352" alt="Screenshot 2023-02-20 at 10 00 28 AM" src="https://user-images.githubusercontent.com/62384659/220059889-03266677-b34b-4716-86ec-5032e46a1106.png">

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by oneknucklehead** [comment]
hey @Anita-ihuman can you assign me this issue?

**Comment by Rishikavishnoi** [comment]
@Anita-ihuman Can I work on it ..?

**Comment by Ashish0926** [comment]
if this issue is still open can I work on it?

**Comment by AbhiiVops** [comment]
Hello @Anita-ihuman ,

I hope this message finds you well. I am writing to express my interest in contributing to the project by **working on issue #3790 - Use a light version of the She Code Africa logo.** I believe I can create a suitable light version of the She Code Africa logo that will align with the project's vision and values.

If it's alright with you, could you please assign this issue to me? I would be happy to collaborate with other team members to ensure that the logo is created in a timely manner and meets the project's requirements.

Thank you for your consideration, and I look forward to hearing back from you soon.

Best regards,
**Abhishek Bhattacharjee**

**Comment by Darrendsouza1111** [comment]
can i work on this

**Comment by arjunpotter17** [comment]
Hello @Anita-ihuman / @leecalcote ,

My name is Arjun. I wanted to contribute to Layer5. I have cloned the repo and **fixed the issue**. I understand that @Darrendsouza1111 is assigned and I should not have proceeded without consent. But there was no communication for two weeks. I apologize if I broke any rules. 
I am attaching screenshots of the fixed version below.

![Screenshot (24)](https://user-images.githubusercontent.com/42664767/226156400-b2fdfa04-9801-4fcd-adb9-52206429ef8a.png)
![Screenshot (25)](https://user-images.githubusercontent.com/42664767/226156406-ab448cd1-e70f-4f41-afbb-57480c5ad5d6.png)

I went ahead and added dark mode options to other images in the same page too. 

I also noticed this issue in https://layer5.io/programs/sca-contributhon (attaching screenshot for reference) but I could not figure out a way to implement the theme.

![Screenshot (27)](https://user-images.githubusercontent.com/42664767/226156598-224c58d0-4cf4-48ef-bd7d-bf242c2cad78.png)

I could not find a way to implement the theme state inside the .mdx file. I doubt if it is possible, I would suggest a fix by adding a background that is suitable to both the light and dark versions. As it is done in the blog cards (attaching screenshot below)

![Screenshot (26)](https://user-images.githubusercontent.com/42664767/226156749-1956682f-6f85-4f6d-b499-72a36763f99a.png)

Please let me know if I can make a pull request. Thank you!

**Comment by Anita-ihuman** [comment]
@AbhiiVops I see this issue has been assigmed for over 3weeks. Are there any PR available from your end yet? 
@leecalcote would it be ok to assign this to @Darrendsouza1111 if there is no PR from @AbhiiVops ?

**Comment by arjunpotter17** [comment]
@Anita-ihuman I have fixed the issue as mentioned above (with screenshots provided). Kindly assign the issue to me so I can make a pull request.

**Comment by sambhavgupta0705** [comment]
Hey @Anita-ihuman if @arjunpotter17 is not working on this one and I would like to grab this one.

**Comment by arjunpotter17** [comment]
Hey @sambhavgupta0705, I've solved the issue. I'll be making a PR in a day or so. Just a little held up with other stuff. 😅

**Comment by Anita-ihuman** [comment]
@arjunpotter17 have  you submitted the PR yet?

**Comment by arjunpotter17** [comment]
@Anita-ihuman I'm having a bit of trouble while submitting a PR. Can I have a bit more time?

**Comment by arjunpotter17** [comment]
@Anita-ihuman I have submitted a PR, (numbered 4032), it has no merge conflicts but it seems to fail the build test. Could you please have a look?

**Comment by arjunpotter17** [comment]
@Anita-ihuman Kindly look at PR numbered 4046, the build is failing due to a dev dependency issue.

**Comment by leecalcote** [comment]
@arjunpotter17 the #4046 PR is failing to build do to an invalid path - https://github.com/layer5io/layer5/pull/4046/files#diff-4838c6837b97e6be2c7d3d769c1b88657e5c935458ec05abd5ed9049e7891e26R6

**Comment by DarrenDsouza7273** [comment]
@arjunpotter17 updates?
