### ISSUE TITLE
[Handbook]Add steps on How to participate as a community manager

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3795]
### Current Behavior
Currently, the  Layer5 [handbook](https://layer5.io/community/handbook/community-roles) has no clear way on how to participate/be a community manager in Layer5

### Desired Situation
We need a clearly outlined steps on how one can get involved in community affairs. How you can assume leadership roles in the community and what it takes to be recognised as a community manager within the community.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vedant-z** [comment]
May I work on this please @Anita-ihuman

**Comment by money8203** [comment]
I think I can handle this and it will be a great start towards improving the documentation @Anita-ihuman

**Comment by Srinja333** [comment]
can i work on this?

**Comment by AbhiiVops** [comment]
Hello Anita,

I hope this message finds you well. I am writing to express my interest in contributing to the project as a community manager. I noticed that **issue #3795 is open**, and I would like to take on the task of adding steps on How to participate as a community manager to the project's handbook.

I have experience in managing online communities, moderating discussions, and responding to user feedback. I have also read through the project's contribution guidelines and community code of conduct, and I'm committed to following the established best practices and protocols.

Could you please consider assigning this issue to me? I would be happy to collaborate with other team members and ensure that the content I add is clear, accurate, and relevant to the project's goals.

Thank you for your consideration, and I look forward to hearing back from you soon.

Best regards,
Abhishek Bhattacharjee

**Comment by Suyash699** [comment]
Can I take this up please?

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm is this issue still open?

**Comment by vishalvivekm** [comment]
> @vishalvivekm is this issue still open?
> 

@DarrenDsouza7273 please refer to [community -roles](https://layer5.io/community/handbook/community-roles) and share your opinion if you feel the steps for a community manager role needa be refined? 
// @Anita-ihuman
