### ISSUE TITLE
[Handbook] Recognition page 

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3796]
### Description
The recognition page on the handbook seems to be throwing an error.

### Expected Behavior
Fix the broken link to the [recognition page ](https://layer5.io/community/handbook/recogition)on the community handbook

### Screenshots
<img width="1346" alt="Screenshot 2023-02-21 at 3 46 57 AM" src="https://user-images.githubusercontent.com/62384659/220234649-7c38b6d1-ead1-4cfd-90a5-16b3f9555032.png">

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Aditya-A-G** [comment]
hey, Can I work on this issue ?

**Comment by Sheikh-JamirAlam** [comment]
@Aditya-A-G Are you working on it or should I fix it?

**Comment by Aditya-A-G** [comment]
yes, I'm working @Sheikh-JamirAlam
