### ISSUE TITLE
Add tooltip on hover effect on the badges in Individual member profile page.

### ISSUE THREAD

**Issue by chinu-anand** [layer5io/layer5#3797]
### Current Behavior

Currently, there is no tooltip on hovering over badges in the individual pages of members on the page https://layer5.io/community/members.
![image](https://user-images.githubusercontent.com/66985303/220242954-e030f4f4-9bbb-43a7-b8f9-dfcb262f1556.png)

### Desired Situation

Add the tooltip while hovering over the badges.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by roopeshsn** [comment]
Hi, @chinu-anand! I would like to work on this.

**Comment by Shivam164** [comment]
Hey @chinu-anand, Is there any particular way the tooltip should look, or is it up to us to make it look good?

**Comment by chinu-anand** [comment]
@Shivam164  One which matches the site's color scheme and looks modern also. That's it.

**Comment by chinu-anand** [comment]
@Chadha93 @eeshaanSA Please assign @roopeshsn this issue.

**Comment by niranjan-kurhade** [comment]
Is this issue still open? If yes, I would like to work on it.

**Comment by DarrenDsouza7273** [comment]
@vishalvivekm i would like to work on this issue

**Comment by vishalvivekm** [comment]
Awesome @DarrenDsouza7273 
Look for suggestions in linked pr #4120

**Comment by DarrenDsouza7273** [comment]
on it @vishalvivekm

**Comment by DarrenDsouza7273** [comment]
hi @chinu-anand can u brief about it more, like what is the expected result?

**Comment by chinu-anand** [comment]
@DarrenDsouza7273 add a tooltip to the badges while hovering over that and please make the badges row responsive for smaller devices as well. You can refer to #4120 .

**Comment by ranjanmangla1** [comment]
hey, if it's still open, i would love to work on this issue

**Comment by DarrenDsouza7273** [comment]
Hi @ranjanmangla1 i've been working on this issue for the past weeks and theres a few enhancements(regarding alignment of the tooltip so it looks centered) and i've faced some issues so if you dont mind helping please check out my pr #4436

**Comment by DarrenDsouza7273** [comment]
we can get connected @ranjanmangla1 and work on it together and get it done asap

**Comment by DarrenDsouza7273** [comment]
i will complete this issue by end of this week

**Comment by thisiskaransgit** [comment]
@DarrenDsouza7273 fix this promptly, please

**Comment by DarrenDsouza7273** [comment]
@thisiskaransgit i couldn't find the expected fix for it.

**Comment by ankushbhardwaj408** [comment]
Hi @Chadha93  i would like to work on this issue. Please assign it to me.

**Comment by vishalvivekm** [comment]
There you go @ankushbhardwaj408

**Comment by ankushbhardwaj408** [comment]
Hi @vishalvivekm I have added tooltip hover effect on the badges. Please review it. Here is the recorded video.

https://github.com/layer5io/layer5/assets/93874580/2c1c7adf-25c4-4f32-8f2d-faef53562eb0

**Comment by DarrenDsouza7273** [comment]
Hi @ankushbhardwaj408 i had done the same thing but during the weekly meeting it was suggested that the tooltips should be centered which i couldnt find a way to do,so if you can center them on hover please do. As the hover effect was already implemented its just that it needs to be centered.

**Comment by ankushbhardwaj408** [comment]
Thanks @DarrenDsouza7273 working on it.

**Comment by ankushbhardwaj408** [comment]
Hi @DarrenDsouza7273 @Chadha93 @vishalvivekm please review this change.

https://github.com/layer5io/layer5/assets/93874580/e25b37f8-28d0-484a-a8d6-b03a0855658b
