### ISSUE TITLE
[MeshMap page] Sections scroll only when cursor is inside.

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3798]
### Description
The MeshMap page here: [https://layer5.io/cloud-native-management/meshmap](url) has 3 different feature sections. Each of the sections has a scroll functionality. However, the scroll works only when the section is hovered over, and then scrolled.

### Expected Behavior
The scrolling of each section should occur even when the cursor is not inside the sections.
**A brief example:** When the user reaches the first section, the page scroll should stop, and the section scroll should start. When the section has been completely scrolled, the page scroll should continue. Similarly for the next 2 sections.

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by HarshitSharma007** [comment]
Hey @Shivam-AfA , I want this issue to be assigned to me .

**Comment by Shivam-AfA** [comment]
Sure @HarshitSharma007.

**Comment by aamirv1** [comment]
is this issue still open?

**Comment by Shivam-AfA** [comment]
This issue has been resolved @aamirv1. Maybe find another one?
