### ISSUE TITLE
[MeshMap] Mobile issue

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3801]
Currently, the https://layer5.io/cloud-native-management/meshmap page has some mobile issues as captured in the screen recording below:

https://user-images.githubusercontent.com/7570704/220343899-b2178add-2eaa-4ecd-8ab1-74df4c61998a.MOV

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/3784#issuecomment-1438390903_

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this issue?

**Comment by Faizan711** [comment]
Ok 👍 no issues, thanks for informing

**Comment by leecalcote** [comment]
Thanks much, @Sheikh-JamirAlam , @Faizan711. PR at-will, @Sheikh-JamirAlam
