### ISSUE TITLE
Fix overflow occurring on the Repository Overview page

### ISSUE THREAD

**Issue by tinniaru3005** [layer5io/layer5#3807]
### Description

Currently, there is an overflow occurring on the [Repository overview page](https://layer5.io/community/handbook/repository-overview)

### Expected Behavior

Fix the overflow 

### Screenshots

![rep-overview](https://user-images.githubusercontent.com/62856848/220935282-35468ce5-5e92-480f-800a-fd47a580ace9.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Aditya-A-G** [comment]
hey @tinniaru3005 , I would like to work on this issue

**Comment by tinniaru3005** [comment]
@Aditya-A-G You can go ahead and solve it. :)

**Comment by Aditya-A-G** [comment]
thank you for your response! I appreciate your support. I will start working on the issue now.

**Comment by neeraj12x** [comment]
@tinniaru3005 Will you please assign this issue to me I am new here. I read your hashnode blog it was amazing.

**Comment by tinniaru3005** [comment]
Hey, @neeraj12x welcome to the community. I am glad that u liked my blog. This issue is already assigned and @Aditya-A-G is already working on it. You can have a look at the other issues which are not assigned and ask in the comments if you want to solve it.

**Comment by Aditya-A-G** [comment]
hey @tinniaru3005 . I have made this pr #3834  to solve this issue. you can review it.
