### ISSUE TITLE
Optimization of Honeycomb component's animation in integrations page

### ISSUE THREAD

**Issue by divz-codess** [layer5io/layer5#3809]
# Description
While conducting performance test the CPU usage increases to more than 100% in Safari browser especially.

### Expected Behavior
The CPU usage should be in considerable limits.

### Screenshots
![Image](https://user-images.githubusercontent.com/88512639/221021366-c2a809eb-e534-407f-8dba-5af2669eb6b3.jpeg)

### Environment:
- Host OS: MacOS
- Browser: Safari

I am taking up this issue.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Very good of you to look into this, @divz-codess 👍

**Comment by divz-codess** [comment]
Optimized it by 4% trying to do more :)  @leecalcote

**Comment by Udit-takkar** [comment]
https://user-images.githubusercontent.com/53316345/222955558-a895fe4f-7c11-4317-a215-ddc935aba30b.mov

Yeah even animation doesn't feel smooth



<img width="647" alt="Screenshot 2023-03-05 at 4 10 51 PM" src="https://user-images.githubusercontent.com/53316345/222955532-c1220b78-2c1c-4e37-9bad-d6718d265d96.png">

**Comment by leecalcote** [comment]
And it's only going to get worse as we add more integrations...
