### ISSUE TITLE
[MeshMap] Scroll events not captured in page gutters

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3811]
### Description
We need to evaluate use of other packages that have robust support for controlling scrolling on a page (e.g. scrollspy-like packages for React). The event listeners and handlers for scrolling on the [MeshMap page](https://layer5.io/meshmap) are custom-implemented and they are  having a bit of trouble. 

**Challenge #1:**  Scroll events are not listened to/captured when the visitor's mouse is on either side of the page (in the page gutters), which which isn't good because then the site visitor simply misses all of the animations as they scrolled right past them.

**Challenge #2:** When the site visitor's mouse _is_ hovering over the sections, the animations are sometimes stuck as the bottom of the page and not visible, so the visitor is scrolling, the page isn't moving, and they are not seeing the animation. Also, when the visitor reaches the bottom and scrolls back up the page, the animations should play in reverse, but there is misbehavior here as well. 

### Implementation
Either: 
1. Identify an existing React/npm/open source package with better behavior and logic and displace the existing custom logic ensuring that all of the behaviors described above are addressed.

or

2. Change the current implementation ensuring that all of the behaviors described above are addressed.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

Until you're able to catch up with @Shivam-AfA, an alternative bit of research in this area would be very helpful. 

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/3808#issuecomment-1442564652_

**Comment by Udit-takkar** [comment]
@leecalcote can i work on this issue ?

**Comment by leecalcote** [comment]
Uh-oh... he's back!

**Comment by leecalcote** [comment]
Yes, that would be most helpful, @Udit-takkar 👍

**Comment by Udit-takkar** [comment]
i think we should probably use this library https://greensock.com/scrolltrigger/ instead. It's very difficult to solve these issues in the current implementation.

**Comment by Shivam-AfA** [comment]
This package seems to provide a lot of functionality. Thanks for pointing this out @Udit-takkar. Would you like to try a hand at it?

**Comment by Udit-takkar** [comment]
@Shivam-AfA yeah 👍

**Comment by Shivam-AfA** [comment]
Hey @Udit-takkar Any progress here? It would be great if you could show a demo in the websites meeting this Monday.

**Comment by Udit-takkar** [comment]
Okay

**Comment by Cho202** [comment]
@leecalcoteฉันสามารถทำงานเกี่ยวกับปัญหานี้ได้หรือไม่

**Comment by leecalcote** [comment]
@Cho202 我不知道你在说什么。

**Comment by leecalcote** [comment]
@Cho202 是的，你可以解决这个问题。
