### ISSUE TITLE
Coverage and Press release buttons spacing issue in layer5 news on mobile screen

### ISSUE THREAD

**Issue by ishaandwivedi1234** [layer5io/layer5#3813]
### Description
Coverage and press release buttons need spacing on mobile screen devices 

### Expected Behavior
A horizontal margin should be provided for these buttons when the website is in small screen size

### Screenshots

<img width="455" alt="Screenshot 2023-02-24 at 1 13 41 PM" src="https://user-images.githubusercontent.com/50709505/221122178-e1f98004-8818-4917-a571-eeedafce9b4b.png">

### Environment:
- Host OS: MacOs
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks, @ishaandwivedi1234. I suspect that you're still adding a description in this issue...

**Comment by ishaandwivedi1234** [comment]
Yeah, I  have added the description now 😅. @leecalcote can I start working on this issue if it seems reasonable?

**Comment by leecalcote** [comment]
@ishaandwivedi1234, sounds good, so long as flex is used and no static sizing. 👍

**Comment by ishaandwivedi1234** [comment]
Thanks @leecalcote, I will take care of not using static sizing 👍🏻

**Comment by ishaandwivedi1234** [comment]
@leecalcote I have fixed the problem, and both the buttons are now responsive across all screen sizes, including foldable phones. But while working on this, I found that the search bar is not responsive. Should I raise another issue for search bar responsiveness because it is a different component?
<img width="569" alt="Screenshot 2023-02-25 at 10 42 05 AM" src="https://user-images.githubusercontent.com/50709505/221339638-c6c4ddd2-0bb6-4146-9592-473b3d0c8f73.png">

**Comment by leecalcote** [comment]
Oh, very good, @ishaandwivedi1234. We’re all clear here if you would like to include a couple of fixes in this same PR. In this case, we’re good to go for other way.

**Comment by ishaandwivedi1234** [comment]
#3842

**Comment by AkashS20** [comment]
I'd like to work on this issue
