### ISSUE TITLE
Overlapping of content on the page

### ISSUE THREAD

**Issue by Shivam164** [layer5io/layer5#3814]
### Description
On the page https://layer5.io/community/handbook/repository-overview, there is an overlapping of content.

### Expected Behavior
Different content should not overlap.

### Screenshots
![Screenshot from 2023-02-24 13-49-21](https://user-images.githubusercontent.com/77626594/221129194-baaf771c-64f3-409d-8b52-3b503a127be6.png)

### Environment:
- Host OS: Ubuntu 22.04
- Browser: Chromium

**Comment by money8203** [comment]
Thanks for opening this issue Shivam, I think I've already raised the one!
