### ISSUE TITLE
[Handbook]: Overlaying of Heading over texts

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#3815]
### Description
Heading and the text written under it is overlaying on the initial texts of the paragraph!

### Expected Behavior
Heading "GitHub organizations and repositories" should be put back to the space provided within "Repository overview and the initial paragraph"

### Screenshots
![Screenshot (246)](https://user-images.githubusercontent.com/89864818/221128149-63825954-87cb-473f-b9e2-457a71a8d845.png)

### Environment:
- Host OS: Windows 11
- Browser: Chrome, Bing

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by money8203** [comment]
@Shivam164 you can work on this if you want!

**Comment by Shivam164** [comment]
Yeah sure @money8203.

**Comment by money8203** [comment]
Awesome, good luck!

**Comment by Nikhil-Ladha** [comment]
@money8203 please double check before opening new issues if a similar issue already exists. This helps avoid unhealthy clashes among contributors who start working on the issues and have duplicate PRs.
A similar issuee #3807 already existed with a contributor assigned to it.

**Comment by money8203** [comment]
Oh, my bad Nikhil. I'll double check next time!

**Comment by vishalvivekm** [comment]
completed via #3834
