### ISSUE TITLE
Dark Mode issue on Partner section carousel

### ISSUE THREAD

**Issue by suhail34** [layer5io/layer5#3830]
### Current Behavior

The dots below the partners section carousel aren't visible in dark mode and also gives outline on hovering that doesn't looks good

### Desired Behavior

Remove the outline from dots on hovering and fix the dark mode issue as dots are not visible

### Screenshots / Mockups

https://user-images.githubusercontent.com/77241166/221620857-87cd0a8c-3ad5-4523-b4fe-05518a376099.mp4

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Manishch27** [comment]
@suhail34 can I work on this issue?

**Comment by Sumer312** [comment]
Hey I would like to work on this issue.

**Comment by Srinja333** [comment]
can i work on this?

**Comment by mihir2226** [comment]
@suhail I would love to work on this issue.
