### ISSUE TITLE
[Community] Member Profile: Swathi Loganathan

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3835]
**Current Behavior**

@Swathi-L has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Swathi-L as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Swathi-L
- Twitter: 
- LinkedIn: swathi-l
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@Swathi-L Please provide your social handles, bio, and a profile picture link.

**Comment by roopeshsn** [comment]
Hi, @Chadha93! Could you assign this to me?

**Comment by gauravrattan** [comment]
@Chadha93 pls assign me, thanks

**Comment by UtkarshMishra12** [comment]
Assigning it on a First come basis, Here you go @roopeshsn 🚀

**Comment by roopeshsn** [comment]
Hi @Swathi-L! I need your twitter handle, bio, and profile picture link.

**Comment by Swathi-L** [comment]
Profile pic link:
https://drive.google.com/drive/u/0/folders/1oZ3x73bK49tMuEnQfm8FXmpHc1WbFwf8

**Comment by roopeshsn** [comment]
The profile pic is not public @Swathi-L

**Comment by Swathi-L** [comment]
> Your profile pic is not public @Swathi-L

Permission granted @roopeshsn :-)
