### ISSUE TITLE
[Community] Member Profile: Azanul Haque

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3839]
**Current Behavior**

@azanul has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Azanul as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Azanul 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this?

**Comment by Ashish0926** [comment]
@Chadha93 can you assign me this?

**Comment by Azanul** [comment]
Twitter: [@AzanulZ](https://twitter.com/AzanulZ)
LinkedIn: [@azanul-haque](https://www.linkedin.com/in/azanul-haque/)
Link to profile picture: [drive link](https://drive.google.com/file/d/1tb8nW54eSKhgRi0hPLDTWxegTIHQ-nGY/view?usp=share_link)

**Comment by Sheikh-JamirAlam** [comment]
@Azanul Please provide your location so that I can add it.

**Comment by Azanul** [comment]
Chhattisgarh, India
