### ISSUE TITLE
Theme changer not working 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [layer5io/layer5#3841]
### Description

In theme changer found issue that's not working sometime
### Expected Behavior

when we click theme changer button then theme not changing 
### Screenshots

[Screencast from 01-03-23 12:02:24 PM IST.webm](https://user-images.githubusercontent.com/78332454/222063347-082389d5-a4a6-4c8b-ac1e-d71e09a40998.webm)

### Environment:
- Host OS: Ubuntu
- Browser: Brave
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by leecalcote** [comment]
Uh-oh. 😬 

Thanks for pointing this out, @AnshuPathak-88825 👍

**Comment by swagataroy30** [comment]
But I did check and it's working fine.

https://user-images.githubusercontent.com/116095538/222623467-83042897-674f-471c-81a9-d1a0dcf54af9.mp4

**Comment by AnshuPathak-88825** [comment]
I don't but that time it's not working
