### ISSUE TITLE
[Community] Member Profile:@chinu-anand

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/layer5#3845]
**Current Behavior**
 
<@chinu-anand > has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@chinu-anand> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @chinu-anand 
- Twitter - https://twitter.com/chinustwt
- Linkedin - https://www.linkedin.com/in/chinu-anand/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by roopeshsn** [comment]
Hi @chinu-anand! I need your bio and profile picture link inorder to create your page.
