### ISSUE TITLE
Improve scroll bar

### ISSUE THREAD

**Issue by AnshuPathak-88825** [layer5io/layer5#3846]
### Current Behavior

Currently it is normal scroll bar
![Screenshot from 2023-03-01 20-34-17](https://user-images.githubusercontent.com/78332454/222178915-b9952830-06af-40b1-ba26-4f54fcc57cf4.png)

### Desired Behavior

I want to change scroll bar according to theme mean wanna made scroll bar thin and same colour as button colour rgb(0, 179, 159)

### Implementation

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by leecalcote** [comment]
@Shivam-AfA will you triage?

**Comment by Shivam-AfA** [comment]
@AnshuPathak-88825 Thanks for suggesting this. It would be great if you could demo this. Just to see how that feels. I am supportive of having a thin custom srollbar, but doubtful of the green color.

**Comment by Shivam-AfA** [comment]
@mihir2226 you can work on this if @AnshuPathak-88825 turns out stuck.

**Comment by AnshuPathak-88825** [comment]
I'm starting working on it

**Comment by parmishh** [comment]
@Shivam-AfA it has been 3 days since last comment I have successfully made the changes you can view here.
if no one else is working on it and If you like it I will make a PR.
if you want I can make it even more thinner add different shadows/colors and customize it as you wish.


https://user-images.githubusercontent.com/91942072/223080919-453c8bff-dd51-47a7-a642-ee628921b30a.mp4

**Comment by parmishh** [comment]
@Shivam-AfA I also observed that in previous scroll bar the right side dot of sun symbol remains hidden now its solved with this
<img width="59" alt="123" src="https://user-images.githubusercontent.com/91942072/223082295-fb445b08-0c48-4af5-aeee-07423e889f61.PNG">

**Comment by AnshuPathak-88825** [comment]
sorry for delay here's demo video with green color pls let me know how's it look then it'll make PR
@Shivam-AfA 

[Screencast from 11-03-23 04:31:14 PM IST.webm](https://user-images.githubusercontent.com/78332454/224480640-bcbea32c-89db-42e4-b4cd-eb0281a94ac5.webm)

**Comment by Shivam-AfA** [comment]
@leecalcote What do you think? Thanks for demoing @parmishh @AnshuPathak-88825

**Comment by Shivam-AfA** [comment]
@Nikhil-Ladha Any suggestions over this?

**Comment by Nikhil-Ladha** [comment]
Maybe we can have this change, though I am not so sure.
We can take a consensus in the weekly call next week and then decide.

Though, before that a better update would be to use the charcoal (`#3c494f`) green color in light mode and the carribean(`#00d3a9`) green color in dark mode and be ready for demo.

**Comment by leecalcote** [comment]
Great suggestion. It's hard for even me to believe, @AnshuPathak-88825, but it is possible to have too much green.

**Comment by AnshuPathak-88825** [comment]
which colour should choose grey or green ?

**Comment by Shivam-AfA** [comment]
@AnshuPathak-88825 Let's go with @Nikhil-Ladha 's suggestion

**Comment by AnshuPathak-88825** [comment]
sorry for late reply can I show demo in next meeting ?

**Comment by Shivam-AfA** [comment]
@AnshuPathak-88825 You can demo in a video as well.

**Comment by Shivam-AfA** [comment]
> Maybe we can have this change, though I am not so sure.
We can take a consensus in the weekly call next week and then decide.

>Though, before that a better update would be to use the charcoal (#3c494f) green color in light mode and the carribean(#00d3a9) green color in dark mode and be ready for demo.

@AnshuPathak-88825 Did you follow-up on this?

**Comment by AnshuPathak-88825** [comment]
yeah sure

**Comment by Savio629** [comment]
@AnshuPathak-88825 Any updates?

**Comment by AnshuPathak-88825** [comment]
working on it

**Comment by Savio629** [comment]
Updates @AnshuPathak-88825 ?

**Comment by Ghat0tkach** [comment]
If no one is working on this can I take this up?
@Savio629  @vishalvivekm @Shivam-AfA @leecalcote
