### ISSUE TITLE
Scroll slider not visible in dark mode

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3847]
### Description
On the Meshery project page here [https://layer5.io/cloud-native-management/meshery](https://layer5.io/cloud-native-management/meshery), scroll slider in the features section (for small sized screens) is not visible in dark mode.

### Expected Behavior
The slider dots need to be changed to a lighter color for dark mode. 

### Screenshots
Scroll slider visible in light mode.
![image](https://user-images.githubusercontent.com/88040318/222212814-b85e8d68-8433-426c-ae76-3bf6be37c476.png)

But not visible in dark mode.
![image](https://user-images.githubusercontent.com/88040318/222212825-5434d1e4-5991-4a89-af78-6ea6df0fcf0b.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShravaniAK** [comment]
i would like to work on this

**Comment by melsonic** [comment]
@ShravaniAK are you still working on it?

**Comment by ShravaniAK** [comment]
yes i have finished working on it
