### ISSUE TITLE
[Bug] Title of Repository-Overview Page is misaligned

### ISSUE THREAD

**Issue by sanyamjain036** [layer5io/layer5#3849]
### Description
https://layer5.io/community/handbook/repository-overview

### Expected Behavior
Title of the page should be at proper position.

### Screenshots
<img width="1253" alt="Screenshot 2023-03-01 at 11 18 16 PM" src="https://user-images.githubusercontent.com/75247883/222221652-20f02925-08b2-4abd-a9c1-ca3c5779296b.png">

### Environment:
- Host OS: MacOs
- Browser:  Chrome and Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Shivam-AfA** [comment]
@sanyamjain036 This issue has already been addressed here #3815

**Comment by sanyamjain036** [comment]
ok, I have solved this issue, so I close this issue and attach my PR to #3815.
