### ISSUE TITLE
Add CSS animation on hover

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3854]
### Desired Situation
A CSS animation similar to the one in the image (a ripple effect) is required when the object is hovered.

![image](https://user-images.githubusercontent.com/88040318/222282549-4f9581a7-7115-46f7-a1de-567012e5ab97.png)

SVG link: [https://github.com/layer5io/layer5/blob/master/src/collections/integrations/nginx-service-mesh/icon/color/nginx-service-mesh-color.svg](https://github.com/layer5io/layer5/blob/master/src/collections/integrations/nginx-service-mesh/icon/color/nginx-service-mesh-color.svg)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Should be SVG image(s) only. Try manipulating the CSS from the on hover affect on this page: https://meshery.io/catalog.

**Comment by sanyamjain036** [comment]
I want to work on it; assign this to me.

**Comment by leecalcote** [comment]
@sanyamjain036 what do you think about the css animation on the Meshery Catalog page?

**Comment by sanyamjain036** [comment]
They making me feel dizzy.

**Comment by sanyamjain036** [comment]
https://user-images.githubusercontent.com/75247883/222574677-e4370bb0-0fdb-44f9-acc6-a87f3fb8f6fa.mov

is it fine?

**Comment by leecalcote** [comment]
Looking good, @niranjan-kurhade

**Comment by niranjan-kurhade** [comment]
Thanks, @leecalcote for assigning me this issue. Which object should have the ripple effect when it is hovered? Do I have to give the ripple effect on the meshery page(Different repo)?

**Comment by niranjan-kurhade** [comment]
Hey, @Shivam-AfA Can you guide which object should have the ripple effect on the layer5 website?

**Comment by Shivam-AfA** [comment]
@niranjan-kurhade Thanks for implementing this, currently we're not specific about the place where this should be used. You can add this animation in the form of a react-component in the repo. It'll be published when a suitable UX need is identified. 

You can add this under src/components directory.

**Comment by leecalcote** [comment]
Another way of saying this is that @Shivam-AfA needs to complete his work so that this new animation can land on https://layer5.io/cloud-native-management/meshmap/design. 😉There is an open PR on this topic.
