### ISSUE TITLE
Header is overflowing

### ISSUE THREAD

**Issue by sambhavgupta0705** [layer5io/layer5#3863]
### Description

When you visit : https://layer5.io/community/handbook/repository-overview
You see the header is overflowing

### Screenshots

![image](https://user-images.githubusercontent.com/81870866/222471565-d95753e9-76c4-46cb-8023-8c75ce6f180a.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Srinja333** [comment]
can i work on this?

**Comment by leecalcote** [comment]
Thank you, @sambhavgupta0705

**Comment by leecalcote** [comment]
@Srinja333 @sambhavgupta0705 please be aware that this is a duplicate issue - or at least that there is an open pull request addressing this bug - https://github.com/layer5io/layer5/pull/3834

**Comment by sambhavgupta0705** [comment]
Oh sorry for that @leecalcote 
Closing this issue then.

**Comment by leecalcote** [comment]
Much better that you opened an issue than not opened one, @sambhavgupta0705. Thanks for doing this.

**Comment by leecalcote** [comment]
@sambhavgupta0705 @Srinja333 please offer review of https://github.com/layer5io/layer5/pull/3834

**Comment by sambhavgupta0705** [comment]
> @sambhavgupta0705 @Srinja333 please offer review of #3834

for sure!!
