### ISSUE TITLE
Create card component with CSS animation

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3866]
### Desired Situation

A component with an animation is needed **(referencing to the image below)** where on clicking over a card, it pops out of the stack and gets placed beside the stack as shown in the image. The placed card shows some content. But the cards do not show any content when they are stacked.

![image](https://user-images.githubusercontent.com/88040318/222523601-7eff63d1-bd97-46a2-b43a-e61b6ebd77a7.png)

The color and border-radius that can be used for the card:
`background: linear-gradient(266.65deg, #00B39F 40.19%, #477E96 74.31%, #3C494F 92.89%);`
`border-radius: 20px;`

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sambhavgupta0705** [comment]
Hi @Shivam-AfA ,Can I try my hands on this issue?

**Comment by Shivam-AfA** [comment]
Sure @sambhavgupta0705

**Comment by sudhanshutech** [comment]
Hey @Shivam-AfA are you saying that, the card that is in the middle show content when clicked, it gets popped out then flipped and place over the cards stack present beside it

**Comment by Shivam-AfA** [comment]
@sudhanshutech On clicking over a card in the stack, it should pop out of the stack and get placed in the center. This is what we're aiming for.

**Comment by sudhanshutech** [comment]
> @sudhanshutech On clicking over a card in the stack, it should pop out of the stack and get placed in the center. This is what we're aiming for.

Ok where we have have to implement it right now in figma or directly code

**Comment by Shivam-AfA** [comment]
The card SVGs are present in figma, if you want to go through them, but eventually we need it implemented into code, in a React component.

**Comment by avikt18** [comment]
I have made a rough prototype trying out how it could look :point_down: @Shivam-AfA
https://9vz2dt.csb.app/
this can be improved and made production ready

**Comment by Shivam-AfA** [comment]
This is quite good @avikt18. 🚀 Can you work on this a bit more and place the card in the center?

**Comment by sudhanshutech** [comment]
Hey @avikt18 if you could share the collaboration link, I could help

**Comment by avikt18** [comment]
Sure @sudhanshutech here it is https://codesandbox.io/p/sandbox/layer5-card-component-9vz2dt

**Comment by Shivam-AfA** [comment]
@avikt18 this works really good, great job here! 🚀 and if @sudhanshutech also contributed, credits to him as well. We need this component to highlight features of meshmap designer on this page https://layer5.io/cloud-native-management/meshmap/design, that is, the cards can be used for highlighting the features of designer. Currently a drop down carousel is being used for this. 

It would be nice if any one of you would volunteer to add this enhancement. 

P.S.: Do add a bit of rotating animation when the card pops out of stack and goes to the center.

**Comment by Shivam-AfA** [comment]
@leecalcote Please review component created by @avikt18.

**Comment by leecalcote** [comment]
This is coming along nicely. A bit of drop shadow will help the layers of cards feel more like a deck. Each card dynamically expanding in width as it lands on the center of the page will allow room for the contents of what will be a feature description inside.

**Comment by sudhanshutech** [comment]
Hey, @Shivam-AfA credits goes to @avikt18 , I have made some changes for making it center and added some drop shadow can you review it that this is good?
Ofcourse I would like to volunteer

**Comment by Shivam-AfA** [comment]
This looks good, please implement this on the new design page. Do take into consideration the suggestions offered by @leecalcote.

**Comment by sudhanshutech** [comment]
Sure @Shivam-AfA , are we ready to collaborate @avikt18 ?

**Comment by avikt18** [comment]
Yupp @sudhanshutech :+1:
