### ISSUE TITLE
Misalignment in Head and the text of Repository Overview page

### ISSUE THREAD

**Issue by saqib-masood** [layer5io/layer5#3867]
### Issue
The Heading of the Repository Overview page is overlapping with the paragraph below it
See [https://layer5.io/community/handbook/repository-overview](https://layer5.io/community/handbook/repository-overview)

### Expected Behavior
It is expected that both the Heading and the paragraph appear separately. I have checked on multiple browser but the bug still exists so the problem is not in my system but in the web page

![image](https://user-images.githubusercontent.com/91628331/222526249-66c12327-2580-4f0d-b28b-7d67cd00f8b5.png)

### Environment:
- Host OS: Windows and may be on macOS
- Browser: Chrome , Brave 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sambhavgupta0705** [comment]
Hey @saqib-masood ,this issue has been raised already through https://github.com/layer5io/layer5/issues/3807

**Comment by sudhanshutech** [comment]
Yes @saqib-masood please close this issue as it is been already discussed so it is creating conflict
