### ISSUE TITLE
Github Icon not visible on discussion Forum

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#3868]
### Description
If we hover over the GitHub icon on the footer of the community forum ([discuss.layer.io](http://discuss.layer.io/))  this is what we are seeing, due to the inversion of color, when hovered over the icon it appears black.

### Expected Behavior

The GitHub icon should be glowing with its correct color, as same as other icons.

### Screenshots

![Screenshot from 2023-03-01 23-51-55](https://user-images.githubusercontent.com/92504666/222529518-330bd06d-8184-463d-ab91-41658f1f8bce.png)

### Environment:
- Host OS: Ubuntu
- Browser: Chromium

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by money8203** [comment]
@thisiskaransgit can you please recheck you commits, the issue still persists

![Screenshot (273)](https://user-images.githubusercontent.com/89864818/222927615-b92abea0-64e9-495b-bd32-3c58da800c62.png)
