### ISSUE TITLE
Add material UI select in lfx page

### ISSUE THREAD

**Issue by AnshuPathak-88825** [layer5io/layer5#3875]
### Current Behavior
https://layer5.io/programs/lfx
![Screenshot from 2023-03-03 15-55-35](https://user-images.githubusercontent.com/78332454/222705519-c133672c-48ae-4e69-adf5-8be86b5d5988.png)

### Desired Behavior
![Screenshot from 2023-03-03 16-40-50](https://user-images.githubusercontent.com/78332454/222705976-9989654d-78ec-4c74-8076-d2bb53971ac7.png)

### Requirement reason

1. Material UI select is  more smooth than older select
2. It will improve user experience

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by leecalcote** [comment]
We use Material UI in three of our other projects, but not in this site. Thanks for filing an issue to improve the site, @AnshuPathak-88825.
