### ISSUE TITLE
Improve issue template

### ISSUE THREAD

**Issue by AnshuPathak-88825** [layer5io/layer5#3876]
### Current Behavior
![Screenshot from 2023-03-03 16-55-27](https://user-images.githubusercontent.com/78332454/222708533-6314d116-3ed0-4994-af5c-b54ca4e997f3.png)

### Desired Behavior
Add reason of requirement in feature readme 
![Screenshot from 2023-03-03 16-57-12](https://user-images.githubusercontent.com/78332454/222709005-4a01bd8c-da92-461c-850b-743a77ec6ed8.png)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by leecalcote** [comment]
Thanks for filing this, @AnshuPathak-88825. "Reason of requirement" (which should be "Reason for Requirement") is implicit to the Desired Behavior. We don't want to make contributing any more daunting or arduous than it already is.
