### ISSUE TITLE
[MeshMap] Visualizer page design required: Timeline (DVR)

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#3877]
### Desired Situation
A UI design is required for a section for new MeshMap page that'll highlight this feature of the Visualizer: 

![image](https://user-images.githubusercontent.com/88040318/222729089-72fec47c-21bc-4e4c-8ff2-7286af892b4a.png)

More info: https://layer5.io/cloud-native-management/meshmap/

MeshMap figma designs: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2074%3A853

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Mayaleeeee** [comment]
Hi @leecalcote, can I work on this?

**Comment by leecalcote** [comment]
Please ask, @Shivam-AfA

**Comment by Shivam-AfA** [comment]
Sure @Mayaleeeee . Please drop in any UI idea that you have in Figma. We are expanding the meshmap pages. So we need to keep new content coming. Thanks for jumping in.

**Comment by Mayaleeeee** [comment]
Thanks @Shivam-AfA

**Comment by vishalvivekm** [comment]
> Thanks @Shivam-AfA

Any update on this @Mayaleeeee // @Shivam-AfA

**Comment by vishalvivekm** [comment]
@Shivam-AfA seems a abandoned effort by @Mayaleeeee 
would you see how are we progressing with it now?

**Comment by Shivam-AfA** [comment]
@ritiksaxena124 @avantikajain289
