### ISSUE TITLE
Hover animation on different integration category

### ISSUE THREAD

**Issue by sudhanshutech** [layer5io/layer5#3889]
### Current Behavior

There is no output on hovering over the different integration categories as they are clickable components under [layer5.io](https://layer5.io/)

https://user-images.githubusercontent.com/90546692/222884730-6ff8c97e-d79a-4f54-a8fb-0d105fe10cef.mp4

### Desired Behavior

On hover, animation should be put on so that the user could easily understand that it is a clickable component

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sudhanshutech** [comment]
Hey @Nikhil-Ladha can you assign it to me

**Comment by Nikhil-Ladha** [comment]
Done 👍🏼

**Comment by sudhanshutech** [comment]
Hey @Nikhil-Ladha can you have a look and suggest any changes if needed
in  dark-mode

https://user-images.githubusercontent.com/90546692/222896913-996f4697-116a-43f7-a31e-c3791329097b.mp4

in light-mode

https://user-images.githubusercontent.com/90546692/222897016-40d3f630-d8c1-4962-9b5e-5f73444eb0bf.mp4
