### ISSUE TITLE
Change in number of integrations 

### ISSUE THREAD

**Issue by sudhanshutech** [layer5io/layer5#3890]
### Description

The number of integrations on the page https://layer5.io/cloud-native-management/meshery is 10 and it needs to be changed to 150+ cloud-native integrations

### Expected Behavior

Expected data should be 150+ cloud native integrations
### Screenshots

![image](https://user-images.githubusercontent.com/90546692/222899789-5134e751-a468-41f2-ada8-08230c66d2e9.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
If you can make this a dynamic count just like it is on the home page, (and keep the animated count), that would be great.

**Comment by parmishh** [comment]
IF possible I would like to work on it @leecalcote if no else is doing it currently

**Comment by leecalcote** [comment]
@parmishh, thanks for volunteering. Have you had a chance to build the site, yet? Do you feel quite comfortable with Gatsby and graphql queries?

**Comment by leecalcote** [comment]
If you’re OK with Gatsby, but shaky on graphql, you might have success in copying the query and structure of the main integrations component.

**Comment by sudhanshutech** [comment]
Hey @parmishh are you still in it

**Comment by parmishh** [comment]
@sudhanshutech No, you can ask lee to assign it to you

**Comment by sudhanshutech** [comment]
Should it look like this @leecalcote 

https://user-images.githubusercontent.com/90546692/223025125-59bf167c-6b5c-4eea-b126-80e8ea5028ff.mp4
