### ISSUE TITLE
The pointer disappears when I try to click on search icon

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#3891]
### Description
The pointer disappears when I try to click on search icon   at    https://layer5.io/blog

### Expected Behavior
Pointer must not disappear

### Screenshots

https://user-images.githubusercontent.com/91942072/222900726-bac9d20e-a8c4-4e2f-932e-51091a9d95b4.mp4

@leecalcote I don't know if it is actually a problem or it has to be like that
Please confirm. If it was made like that intentionally then I will close this issue
If its a issue then please assign me😊

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by swagataroy30** [comment]
Can i work on this?

**Comment by parmishh** [comment]
@swagataroy30 I have asked @leecalcote if its actually a issue and I have started working on it so could you please work on some other issues😊

**Comment by swagataroy30** [comment]
@parmishh oh cool then :sweat_smile:, i will take up some other issue :+1:

**Comment by parmishh** [comment]
@leecalcote if have worked a little on it now it looks like this


https://user-images.githubusercontent.com/91942072/222901463-dd0c65c8-9959-41af-a39b-33afa53f48fd.mp4

**Comment by Savio629** [comment]
Hey, @parmishh I don't think this was made intentionally, though the changes look perfect.

**Comment by leecalcote** [comment]
Thanks, @parmishh

**Comment by Savio629** [comment]
@parmishh Are you still working on this issue?

**Comment by parmishh** [comment]
@Savio629 actually I solved this issue and made a PR long back. But it seems that this issue didn't require the fix. So I closed the PR.

**Comment by parmishh** [comment]
If the need to fix the issue is there. I can again make a PR

**Comment by Savio629** [comment]
Oh, so should we close the issue too?

**Comment by parmishh** [comment]
Yeah we should but I was waiting for a comment from a maintainer regarding this. Let's wait little more if there's no response I will close the issue.
