### ISSUE TITLE
Unable to click on Terms link on bottom as go to top button covers it.

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#3894]
### Description
Unable to click on Terms link on bottom .as go to top button covers it. at https://layer5.io/blog

### Expected Behavior
Go to top button can be moved little up so that Terms button is visible and can be clicked.

@leecalcote I have already figured out the solution 
if you want this issue to be addressed You can Assign me.😊

### Screenshots

https://user-images.githubusercontent.com/91942072/222944929-696d295d-752a-4a94-916d-347c0395b4ca.mp4

### Environment:

- Browser:  Any

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Savio629** [comment]
### It looks fine on my system but as soon as the width is between 995 to 1110 the problem arises...

<img src="https://user-images.githubusercontent.com/91362589/222967651-4c69ff09-8258-4044-92be-dbe7b8bcaebb.png" width="600">
<img src= "https://user-images.githubusercontent.com/91362589/222967936-964593fd-ea52-4321-8a5e-96ce6a061ae6.png" width="600">

**Comment by parmishh** [comment]
@Savio629 thanks for informing

**Comment by parmishh** [comment]
@leecalcote I think this issue is also seen in smart phones as well I tested some devices The "Terms" button link is Totally under the Go to Top button. It is completely hidden. If you want this issue to be Addressed you can assign me.
<img width="308" alt="isss" src="https://user-images.githubusercontent.com/91942072/223064178-0e8ff35d-ec89-464b-9ee0-fdca2efd0940.PNG">
