### ISSUE TITLE
there is a major bug in meshery section 

### ISSUE THREAD

**Issue by ShravaniAK** [layer5io/layer5#3899]
### Description

the text and the images are not responsive in the 'manage your cluster' section .

### Screenshots

<img width="669" alt="Screenshot 2023-03-06 at 12 25 12 AM" src="https://user-images.githubusercontent.com/97099574/222980118-844591af-6ed2-40fe-8c5f-29f033836457.png">
<img width="633" alt="Screenshot 2023-03-06 at 12 24 59 AM" src="https://user-images.githubusercontent.com/97099574/222980126-84397f56-d539-44d9-a657-d59e5e80410b.png">

### Environment:
- Host OS: macos
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShravaniAK** [comment]
should i start working on this ?

**Comment by Nikhil-Ladha** [comment]
Please try to write much more meaningful issue titles from next time. It should be to the point and not at all vague like the current one.

**Comment by Nikhil-Ladha** [comment]
Go ahead and please send a fix for the same.
