### ISSUE TITLE
no space between search bar and blogs 

### ISSUE THREAD

**Issue by ShravaniAK** [layer5io/layer5#3907]
### Description

there is no space between search bar and blogs post in mobile view 

### Screenshots

<img width="423" alt="Screenshot 2023-03-06 at 3 37 46 PM" src="https://user-images.githubusercontent.com/97099574/223080082-79a73136-cbff-490b-bd3b-194f5945e3fd.png">

### Environment:
- Host OS: macos
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShravaniAK** [comment]
can i work on this?

**Comment by sudhanshutech** [comment]
Hey @ShravaniAK can you tell exactly from which width you are facing this issue

**Comment by ShravaniAK** [comment]
from 491px width

**Comment by sudhanshutech** [comment]
it's weird but I am not facing this issue
![image](https://user-images.githubusercontent.com/90546692/223100470-b725cfee-4da7-411a-b9f1-ce4169772387.png)

**Comment by ShravaniAK** [comment]
is that because of different browsers?

**Comment by parmishh** [comment]
@sudhanshutech when you select list view then switch to mobile then this issue is seen.
if no one is working on it then you can assign me.

https://user-images.githubusercontent.com/91942072/224471085-cc9efaa8-ae88-46b4-83ce-4e5008bfc0cf.mp4

**Comment by ShravaniAK** [comment]
YES @parmishh u are right , currently i am working on this , and i had a talk with @sudhanshutech in the Slack channel
