### ISSUE TITLE
search bar width is not responsive

### ISSUE THREAD

**Issue by Akash3121** [layer5io/layer5#3909]
**Current Behavior**

width of the search bar is not as it should be, when width is reduced
https://layer5.io/blog
class="search-box " 
outer class="searchboxstyle__SearchWrapper-sc-1wu4lbd-0 cSOsSO"

<img width="554" alt="image" src="https://user-images.githubusercontent.com/87650180/223088575-598f0626-21fe-49a1-ada6-73698fc1ad41.png">

**Desired Behavior**

---
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Akash3121** [comment]
One quick doubt, why there is no option for me to add labels?
Do only members of the project has the option to add them?

**Comment by sudhanshutech** [comment]
Hey, @Akash3121 can you please elaborate on what changes you are suggesting because the screenshot is the current scenario

**Comment by sudhanshutech** [comment]
> One quick doubt, why there is no option for me to add labels? Do only members of the project has the option to add them?

The labels get added automatically when you choose the category of issue you want to raise

**Comment by Akash3121** [comment]
> > One quick doubt, why there is no option for me to add labels? Do only members of the project has the option to add them?
> 
> The labels get added automatically when you choose the category of issue you want to raise

My mistake I have created in the wrong issue.

**Comment by divz-codess** [comment]
Hi @Akash3121 @ishaandwivedi1234 has been working on this issue as mentioned by him in today's meet under the issue #3813 therefore I would suggest you to work on some other issue in the mean time. Thanks :)

**Comment by Akash3121** [comment]
Hi @divz-codess,
Thanks for letting me know, please assign it to https://github.com/ishaandwivedi1234.

**Comment by divz-codess** [comment]
I'm closing this issue @ishaandwivedi1234 please raise a PR with issue #3813 itself.
