### ISSUE TITLE
Add an upcoming tab in the Events.

### ISSUE THREAD

**Issue by Akash3121** [layer5io/layer5#3911]
### Current Behavior

https://layer5.io/community/events

### Desired Behavior

It would be a cool feature to have an upcoming tab. As many people are searching for the upcoming events/meetups to participate/join them.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/87650180/223113357-4d2306fc-91f4-4c68-bee5-16f5bfb6e94f.png">

### Implementation

Inside class = "Container__ContainerWrapper-sc-1i64mot-0 jnYPxU"
"filterBtns" class has the tabs like All, Events ..
<img width="452" alt="image" src="https://user-images.githubusercontent.com/87650180/223114433-4e20a4e4-9191-44d8-9e74-e16c5a18b047.png">

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShuvamChatterjee28** [comment]
I think it will be great. Can I work on this one?

**Comment by imlakshaykumar** [comment]
hello, can i work on this ?

**Comment by moazzam07** [comment]
is anyone working on this issue?

**Comment by Mayaleeeee** [comment]
Hi @Akash3121 can I work on this?

**Comment by ritesh-15** [comment]
Is anybody working on these? Can I work on this issue @Akash3121?
