### ISSUE TITLE
[Community] Member Profile: Manish Tyagi

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3912]
**Current Behavior**

@money8203 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @money8203 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @money8203
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@money8203 Will you add your details here?

**Comment by money8203** [comment]
Thanks a lot @Chadha93 , sure I'll add then now!

**Comment by hirentimbadiya** [comment]
so we need to add @money8203 in community member page right ? I can work on this @Chadha93  can you please assign me this issue.

**Comment by divz-codess** [comment]
Assigning you the same @hirentimbadiya .

**Comment by hirentimbadiya** [comment]
@Chadha93 can you just provide information about manish's badges and he is meshmate or not??

**Comment by Chadha93** [comment]
> @Chadha93 can you just provide information about manish's badges and he is meshmate or not??

No he is not.

**Comment by money8203** [comment]
> > @Chadha93 can you just provide information about manish's badges and he is meshmate or not??
> 
> No he is not.

But I think community badge will be added to me profile, right @Chadha93 ?
