### ISSUE TITLE
[Community] Member Profile: Divyangi Raghav

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3913]
**Current Behavior**

@divz-codess has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @divz-codess as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @divz-codess
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@divz-codess Will you add your details here?

**Comment by divz-codess** [comment]
Yeah sure.. or maybe just assign it to me I'll add them.

**Comment by money8203** [comment]
Awesome, thanks for taking the initiative @divz-codess

**Comment by ayushthe1** [comment]
congrats @divz-codess :partying_face:
