### ISSUE TITLE
GitHub action to check successfull build of website

### ISSUE THREAD

**Issue by kushthedude** [layer5io/layer5#392]
I suggest to have a GitHub Action to check successful build of the website.

**Comment by PluckyPrecious** [comment]
@kushthedude @leecalcote have this been sorted?

**Comment by leecalcote** [comment]
@PluckyPrecious great question. I think it has. @Tanuj22 @Nikhil-Ladha @Jashpatel1, what are your thoughts?

**Comment by Nikhil-Ladha** [comment]
This is something we don't use for any of our sites currently, right?
We just verify that using the netlify build for the time being, which in a way does our job. But yes, a netlify build will be added advantage like if sometimes we disable the netlify build or netlify stops working in such scenarios we can confirm the PR if the test passes.

**Comment by leecalcote** [comment]
Another angle to this could be use of Google Analytics / a dead link checker as a regular maintenance item.
