### ISSUE TITLE
[Community] Member Profile: Avishkar 

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#3920]
**Current Behavior**

@Avi-88   has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Avi-88  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Avi-88  
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by money8203** [comment]
Avi-88 can you please fill in your details ?

**Comment by sidharthviz** [comment]
I would like to work on it @money8203

**Comment by money8203** [comment]
Sure, go ahead @sidharthviz

**Comment by Avi-88** [comment]
> @Avi-88 can you please fill in your details ?

Yup, sorry about the delayed response

- GitHub: @Avi-88
- Twitter: [_4vii_](https://twitter.com/_4vii_)
- LinkedIn: https://www.linkedin.com/in/avishkargunjal/
- Link to profile picture: https://github.com/Avi-88.png
