### ISSUE TITLE
Footer is hiding underneath the keyboard in mobile view

### ISSUE THREAD

**Issue by IshitaPathak** [layer5io/layer5#3922]
### Current Behavior

Footer is hiding underneath the keyboard in mobile view

https://user-images.githubusercontent.com/75848598/223537343-63cfebcf-ed05-4808-964a-ac62d5beb841.mp4

### Expected Behavior

 [discuss.layer.io](https://discuss.layer5.io/) Footer should be pushed up when keyboard is open

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by divz-codess** [comment]
Assigning it to you @IshitaPathak

**Comment by parmishh** [comment]
@IshitaPathak are you still working on this?

**Comment by himanshu1221** [comment]
hey @IshitaPathak what is the status any help do you need ?

**Comment by IshitaPathak** [comment]
I tried to fix this, but it works as expected, on some mobiles while the issue still exists on other mobiles. If anyone knows the cause of this, please take a look.

https://user-images.githubusercontent.com/75848598/229849936-976e0bab-f54a-489b-bf75-c45a9871c38f.mp4

**Comment by probiruk** [comment]
I would like to work on this. Could you assign it to me?

**Comment by Ykumar1415** [comment]
> I tried to fix this, but it works as expected, on some mobiles while the issue still exists on other mobiles. If anyone knows the cause of this, please take a look.
> discuss_forum_layer5.io.mp4
hey @IshitaPathak what is problem with this solution can you please highlight ?.

**Comment by Ykumar1415** [comment]
I want to work on this issue.

**Comment by llcain** [comment]
Is this issue still open or is it closed?

**Comment by Ykumar1415** [comment]
@divz-codess please assign this to me .

**Comment by Ykumar1415** [comment]
I have done some changes and now it is working in all the devices fine. I chacked in below all the mobile Screens : 
![image](https://github.com/layer5io/layer5/assets/97088265/0523b7d7-4a79-4662-b218-3e56f29642b9)
