### ISSUE TITLE
Hey send me invitation to join organisation 

### ISSUE THREAD

**Issue by sumitshinde-84** [layer5io/layer5#3927]

**Comment by leecalcote** [comment]
Absolutely, @sumitshinde-84. That would be wonderful - just as soon as you consistently contribute, while demonstrating your faithful stewardship of the community's cultural values of paying-it-forward to others. You are most encouraged to participate in the [discussion forum](https://discuss.layer5.io), engage with others in the [Slack workspace](https://slack.layer5.io), join anyone of the [community meetings](https://meet.layer5.io), and/or grab a help wanted issue.

Let's close this issue until such time as you've engaged in a meaningful way, and a [community manager](https://layer5.io/community/community-manager) or [MeshMate](https://layer5.io/community/meshmates) has recommended your profile for invitation. They review these nominations and decisions on a weekly basis.
