### ISSUE TITLE
❗Important--Terms button not visible under mobile mode and also on some desktops.

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#3928]
### Description
Terms button is fully covered by go to top button. The user hence can't click on TERMS link.
Seen on mobile mode.

### Expected Behavior
The terms button must be visible.

### Screenshots
<img width="308" alt="before" src="https://user-images.githubusercontent.com/91942072/223839374-aa295841-3537-4d1a-b251-50d969a8be73.PNG">

@Chadha93 I think the terms is a important thing for the user to know so should be solved quickly.
I have made some changes if you want I can do a PR or else if you have any suggestions.
It looks like this now.

<img width="306" alt="after" src="https://user-images.githubusercontent.com/91942072/223840383-d428d585-f821-4d83-aacb-e5d8f399e404.PNG">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by parmishh** [comment]
@leecalcote @Chadha93  does this issue needs to be addressed? Please confirm.if yes then please assign to me😊.

**Comment by adithyaakrishna** [comment]
Seems like a legit issue, Terms button is hidden by the Scroll to top button

![IMG_7F41C483843C-1](https://user-images.githubusercontent.com/23498248/223945294-515e880a-6367-4f73-afac-3a3c652da486.jpeg)

CC @Chadha93

**Comment by parmishh** [comment]
@adithyaakrishna @Chadha93 @leecalcote I have modified to make it visible in all devices. Shall I make a PR?
# Iphone XE
<img width="312" alt="se" src="https://user-images.githubusercontent.com/91942072/224017502-db4f7552-5721-403a-ad42-315e1ed015a2.PNG">
# iphone XR
<img width="349" alt="XR" src="https://user-images.githubusercontent.com/91942072/224017611-e9a9349d-4acb-400d-adc6-495735bef3f7.PNG">

# Galaxy A51

<img width="450" alt="galaxy A51" src="https://user-images.githubusercontent.com/91942072/224017684-2840a048-b1a3-4609-9ace-d7ed38ad4eba.PNG">


# Surface Pro
<img width="395" alt="suface pro" src="https://user-images.githubusercontent.com/91942072/224017760-0725aa82-b8ef-412a-97e4-f10699e033a1.PNG">


# desktop
<img width="593" alt="desktop" src="https://user-images.githubusercontent.com/91942072/224017822-59236a9e-9c9c-4eb8-9616-0f3d2c9ebf0e.PNG">
