### ISSUE TITLE
❕Inconsistent Github logos.

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#3930]
### Description
Different Github logos used in footer

### Expected Behavior
The logos must be consistent.

### Screenshots
<img width="465" alt="1" src="https://user-images.githubusercontent.com/91942072/223856257-5bae963b-bffc-4f47-8d2e-a440edaa3519.PNG">

<img width="350" alt="2" src="https://user-images.githubusercontent.com/91942072/223856275-e6d3b81f-f206-41ca-82b1-3fbcc93fa7b3.PNG">

@Chadha93 If you want this to be addressed please Assign me😊

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks, @parmishh. Will you see that the second of the two logos is used (the one without the cat being filled)?

**Comment by HetviSoni** [comment]
Can i work on this issue?

**Comment by parmishh** [comment]
@HetviSoni actually this issue is not related to this repository. I will close this issue after discussing this in meeting. For now please go ahead and take up some other issue.😊

**Comment by HetviSoni** [comment]
> @HetviSoni actually this issue is not related to this repository. I will close this issue after discussing this in meeting. For now please go ahead and take up some other issue.😊

Thank you for informing😊. Can you please tell me this issue belongs to which repository?
