### ISSUE TITLE
[Community] Member Profile: Yash Tandon

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#3932]
**Current Behavior**

@yashtandon019 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @yashtandon019 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @yashtandon019
- Twitter: https://twitter.com/yashtandon019
- LinkedIn: https://www.linkedin.com/in/yashtandon019/
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by money8203** [comment]
@yashtandon019 could you please provide your profile pic ?

**Comment by yashtandon019** [comment]
Sure @money8203  you can use this
![me](https://user-images.githubusercontent.com/29336300/224336852-f11ee441-798c-4c61-bc25-79cb1e0014cf.jpg)

**Comment by hirentimbadiya** [comment]
I can work on this Issue please assign me @money8203 @Chadha93 @leecalcote @Nikhil-Ladha

**Comment by hirentimbadiya** [comment]
@yashtandon019 Can you please provide your bio to write in profile please ? , and @Chadha93  can you give information about @yashtandon019 's badges , thanks.
@money8203
