### ISSUE TITLE
COLOR OF "Meshery is" so lite

### ISSUE THREAD

**Issue by Srinja333** [layer5io/layer5#3936]
![Screenshot_20230310-085243](https://user-images.githubusercontent.com/66597192/224215613-80bc24b0-3452-4ce4-8116-90fe32574a16.png)

Hey @leecalcote,

I think colour of 1st occurance of "Meshery is"  must be brighter. But it looks pale.

 If this is an issue then can I work on this?

**Comment by leecalcote** [comment]
The color of "Meshery is" is by design, but perhaps, this design could use improvement. @Srinja333, if your suggestion is to make this text the same color as the paragraphs below, that isn't quite ideal, no. Do you have other suggestions?

**Comment by Srinja333** [comment]
no, my suggestion is to highlights it or increase brightness

**Comment by Srinja333** [comment]
ok, i will tell you after some try

**Comment by himanshu1221** [comment]
> The color of "Meshery is" is by design, but perhaps, this design could use improvement. @Srinja333, if your suggestion is to make this text the same color as the paragraphs below, that isn't quite ideal, no. Do you have other suggestions?

i have a suggestion : 
We can change the colour to black so that it will look highlighted

**Comment by Srinja333** [comment]
Or we can make slightly bright version of grey

**Comment by ShivangShandilya** [comment]
If possible can I work on this??

**Comment by Srinja333** [comment]
@leecalcote  please check below screenshots, if you like assign this issue to me

![Screenshot (96)](https://user-images.githubusercontent.com/66597192/227885689-506441b0-ee75-4a4a-ae88-b7f764dab217.png)
![Screenshot (97)](https://user-images.githubusercontent.com/66597192/227885713-b042d9ee-0e71-401f-8764-5adfa1cb988e.png)
