### ISSUE TITLE
Less bright "vmWare"  logo

### ISSUE THREAD

**Issue by Srinja333** [layer5io/layer5#3939]
https://user-images.githubusercontent.com/66597192/224225077-a2be319e-4427-4efe-8344-242202258dee.mp4

when i hover on  vmWare logo it does not highlighting as bright as others like citrix,  Hashicorp  logo. 

  ### Environment:
- Host OS: windows
- Browser: chrome

**Comment by Srinja333** [comment]
@leecalcote  if this is an issue,  can i work on this??

**Comment by leecalcote** [comment]
@Srinja333, thanks for pointing this out. Yes, the current behavior is not ideal.

**Comment by parmishh** [comment]
@Srinja333 are you still working on this?

**Comment by Srinja333** [comment]
Yes

**Comment by bhaskarcsawant** [comment]
@Srinja333 are you still working on it ???

**Comment by Srinja333** [comment]
It's already done

**Comment by vishalvivekm** [comment]
done via #4004
