### ISSUE TITLE
Broken link to GitHub "fork me" image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#394]
**Description**
<img width="1320" alt="Screen Shot 2020-04-29 at 8 16 47 AM" src="https://user-images.githubusercontent.com/7570704/80617488-cacc1d00-8a07-11ea-8e93-3f10a966d4d7.png">

**Comment by Nikhil-Ladha** [comment]
Only one of the link is broken, and that too I suppose the link to fork shouldn't be there in the the "Benchmark and Performance Specification" section. What do you say @leecalcote sir?

**Comment by leecalcote** [comment]
@Nikhil-Ladha you're right that the title of the Benchmark section should be updated to "Service Mesh Performance Specification" and the hyperlink should either point to https://layer5.io/performance or to https://github.com/layer5io/service-mesh-performance-specification. // @kanishkarj

**Comment by kanishkarj** [comment]
https://github.com/layer5io/service-mesh-performance-specification

This makes more sense here.

**Comment by Nikhil-Ladha** [comment]
Yes, I think @kanishkarj has a good suggestion!

**Comment by leecalcote** [comment]
The "fork me" link pointing to GitHub certainly does, yes.

@kanishkarj as SMPS unfolds, we'll want to get a better description going on layer5.io/performance.

**Comment by kanishkarj** [comment]
Agree! We should should, maybe we should be an open issue labelled todo or something so that it stays in our minds.
