### ISSUE TITLE
Events Page should also show upcoming events

### ISSUE THREAD

**Issue by Saksham294** [layer5io/layer5#3943]
### Description
Currently the Events page of the Layer5 website shows 'Join Layer5 at these events' while referring to the events which have already been completed already. 

### Expected Behavior
The 'Join Layer5 at these events' should refer to upcoming events and not the ones which have already been completed.
I think we can either change the title to something like 'Layer5 Past Events' or something different. We can rather introduce a new carousel, which will actually have future events of which Layer 5 will be a part.

### Screenshots

<img width="826" alt="Screenshot 2023-03-10 at 9 06 32 PM" src="https://user-images.githubusercontent.com/86240862/224358181-315d577a-94a0-421c-a76d-ff3eb949d865.png">

### Environment:
- Host OS: MacOS Monterey
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
If you think this as a bug, I would like to work on it.

**Comment by himanshu1221** [comment]
> If you think this as a bug, I would like to work on it.

Hey @Saksham294 this issue has already been addressed as follows

https://github.com/layer5io/layer5/issues/3733

**Comment by money8203** [comment]
@Chadha93

**Comment by leecalcote** [comment]
@Saksham294 thanks for pointing this out. The prior events need to be updated in their frontmatter to denote that this event is not no longer upcoming. There is an existing variable for this. // @divz-codess

**Comment by Saksham294** [comment]
@leecalcote So changing the variable would do the job right?

**Comment by sambhavgupta0705** [comment]
Hey ,I would like to work on this one.

**Comment by vishalvivekm** [comment]
@sambhavgupta0705 @Saksham294 who will take it up?

**Comment by sambhavgupta0705** [comment]
If @Saksham294 doesn't mind then I would like to work on this issue

**Comment by Saksham294** [comment]
This is a very old issue and I thought since there wasn't any discussion on this so maybe this isn't something we are looking to work upon. 
@sambhavgupta0705 sure you can take this issue if it has to be worked upon 😊

**Comment by Ykumar1415** [comment]
I want to work on this issue.

**Comment by Savio629** [comment]
Assigned it to you @sambhavgupta0705 :)

**Comment by Savio629** [comment]
Any update @sambhavgupta0705 ?
