### ISSUE TITLE
[BUG] Logo Of Mesh Map

### ISSUE THREAD

**Issue by himanshu1221** [layer5io/layer5#3952]
### Description
The logo Of Mesh Map is not properly aligned 

### Expected Behavior

It should look properly

### Screenshots

![Screenshot from 2023-03-12 21-14-52](https://user-images.githubusercontent.com/32031706/224555888-02ac2061-8291-4c3e-bfaa-867eea3883ad.png)

### Environment:
- Host OS: UBUNTU
- Browser: CHROME

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by money8203** [comment]
Good catch Himanshu, go ahead!!

**Comment by himanshu1221** [comment]
> Good catch Himanshu, go ahead!!

I am on it !
