### ISSUE TITLE
'/landscape': Sorting incorrect table

### ISSUE THREAD

**Issue by aayushdutt** [layer5io/layer5#396]
**Description**
The service Mesh Interface Compatibility table's sort functionality is not working properly. When trying to sort its columns, it goes ahead to sort the table just above it.

**Expected Behavior**
Sort functionality of the table should work well.

**Screenshots**
![image](https://user-images.githubusercontent.com/25280541/80659694-4c26bc80-8aa7-11ea-83c4-6d3abc93d5dc.png)

**Enviroment:**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 22
 - Device: Laptop

**Additional Improvement**:
The table is not centred horizontally. It might be better if it is centred.

**Comment by leecalcote** [comment]
@Nikhil-Ladha fixed this, I believe.

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha fixed this, I believe.

Yeah @leecalcote . I didn't know there is actually an existing issue for it😆
