### ISSUE TITLE
[Dark Mode] Update text color on 404 page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#3961]
### Description
A small update is needed to make the 404 page dark mode friendly.

### Expected Behavior
"Page does not exist" should be in a light font color.

### Screenshots
<img width="671" alt="Screenshot 2023-03-15 at 5 07 00 PM" src="https://user-images.githubusercontent.com/7570704/225454659-ab27272c-32d0-479e-ad83-112166905eda.png">

### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by weilirs** [comment]
I can work on this. please assign me @leecalcote

**Comment by leecalcote** [comment]
Perfect. Thank you, @weilirs

**Comment by weilirs** [comment]
Is this okay? @leecalcote 
![image](https://user-images.githubusercontent.com/62249815/225487888-7b5eff9d-edb1-4aca-9af8-307f3dd39b2c.png)

**Comment by leecalcote** [comment]
Looks real good, yes.
