### ISSUE TITLE
"Newcomers'Guide" button redirects to "Community Handbook" page

### ISSUE THREAD

**Issue by weilirs** [layer5io/layer5#3963]
### Description

As title.
### Expected Behavior

It should redirect to the "Newcomers'Guide" page if there is one.
### Screenshots

https://user-images.githubusercontent.com/62249815/225492500-f0d7869e-c0f3-4039-bded-0f134e81eeb7.mov

### Environment:
- Host OS: macOS
- Browser: Arc

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by hirentimbadiya** [comment]
any updates @weilirs

**Comment by weilirs** [comment]
I'm a bit busy this week. I'll work on it next week.

**Comment by weilirs** [comment]
Where is this button supposed to redirect? Now it redirects to "https://layer5.io/community/handbook", and it is currently at "https://layer5.io/community/newcomers". @leecalcote

**Comment by ayushgupta4002** [comment]
can I work on this @leecalcote ?

**Comment by vishalvivekm** [comment]
The newcomers guide should ideally refer to the community handbook as the go-to guide. // @Chadha93

**Comment by thisiskaransgit** [comment]
It looks fine as it is, but to be specific, we can update the link to redirect to
 https://layer5.io/community/handbook/contributor-journey#Newcomer%E2%80%99s%20Path
