### ISSUE TITLE
Disappearing table cells on hover in dark mode

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#3964]
### Description

On this [page](https://layer5.io/community/calendar) in Layer5 Meetings table cells disappear on hovering in dark mode

https://user-images.githubusercontent.com/110674407/225637092-eb4c21a1-b3cd-4ea5-8af7-792e1f15c302.mp4

### Expected Behavior

They should be visible on hover

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I would like to work on this issue please assign me @leecalcote , @Chadha93 , @Nikhil-Ladha.
