### ISSUE TITLE
[Community] Member Profile: Vivek Vishal

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#3969]
**Current Behavior**

@vishalvivekm has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@github-username> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @vishalvivekm
- Twitter: https://twitter.com/vishalvivekm
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by sidharthviz** [comment]
@money8203 I would like to work on it

**Comment by vishalvivekm** [comment]
> @vishalvivekm could you please provide your linkedin handle along with your profile pic ?

Yeah, Thanks , [Manish](https://github.com/money8203).
My linkedin : https://www.linkedin.com/in/vivek-v-981326106

and here's the profile pic:
![Screenshot_20230218-173900_1~2](https://user-images.githubusercontent.com/110674407/225832871-72adb02a-5763-4006-a2f7-3af006d1cde2.jpg)

**Comment by hirentimbadiya** [comment]
I would like to work on this can anyone assign me ? @Chadha93 , @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Going by the order here, @sidharthviz do you have the site setup and running locally?

**Comment by sidharthviz** [comment]
> Going by the order here, @sidharthviz do you have the site setup and running locally?

Yes
