### ISSUE TITLE
Button's animation doesn't feel right

### ISSUE THREAD

**Issue by aayushdutt** [layer5io/layer5#398]
**Description**
Don't know if it's just me. I think the button on hover should lift up (like other websites). Currently,
 the behavior is that it it's elevation decreases on hover.

**Expected Behavior**
It might be better if instead of decreasing the elevation, we increase it (like other websites).

![image](https://user-images.githubusercontent.com/25280541/80660616-dc660100-8aa9-11ea-819b-ad047a20001c.png)

**Comment by aayushdutt** [comment]
This might be just me. What do you think @leecalcote ?

**Comment by aayushdutt** [comment]
Here is a good example of it: https://bejamas.io/

**Comment by Nikhil-Ladha** [comment]
Well, @aayushdutt  you are correct at your part. But, if everyone does the same thing then there will be no newness in anything. The current animation in layer5.io site is rather interesting and good (my perspective only), it indicates a sense of pressure applied on the image when hovered over it. Any suggestions @leecalcote sir?

**Comment by ashiscs** [comment]
> Well, @aayushdutt you are correct at your part. But, if everyone does the same thing then there will be no newness in anything. The current animation in layer5.io site is rather interesting and good (my perspective only), it indicates a sense of pressure applied on the image when hovered over it. Any suggestions @leecalcote sir?

Totally agree (my opinion though) !!

**Comment by leecalcote** [comment]
This is an interesting thought. I can't say that I've a real strong opinion here. 

On one hand consistency of experience is key to users feeling like your site / your software is intuitive. This consistency is a consideration both within the confines of your software and across other software individuals use.

On the other hand if we never evolve software UX, user interfaces will be boring and stale. It seems that part of the trick here is to balance experiences intuitive (commonplace) enough with a fresh enough (potentially confusing) experience. Logic follows that UIs that are both fresh (appealing) and intuitive (easy to use) are an evolution (not a revolution) of prior art (software).

This site's current design system is based on Material (here's an [example button](https://material.io/components/buttons)). Here's the same "wave" affect in larger form to have a look at as well - https://layer5.io/projects. 

I think the only stipulation that I'll toss into the mix here is one of consistency; that the sites' user experience be consistent across the property (and ideally, across the docs.meshery.io and meshery.io properties to what degree we can). We want it to be obvious that the stewards of these projects are of the same community.

**Comment by leecalcote** [comment]
@aayushdutt yes, please do execute this change, if you can.
