### ISSUE TITLE
[Community] Member Profile: Sudhanshu Dasgupta

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#3987]
**Current Behavior**

@sudhanshutech has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @sudhanshutech as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sudhanshutech 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by money8203** [comment]
@sudhanshutech can you please share your social handles along with your profile pic !!

**Comment by sudhanshutech** [comment]
Here is it

Twitter: https://twitter.com/SudhanshuDasgu3
Linkedin: https://www.linkedin.com/feed/
Profile: 
![Frame1](https://user-images.githubusercontent.com/90546692/226984777-b219fd4c-612a-4e4c-8c1e-31c9e92c7637.jpg)

**Comment by Saksham294** [comment]
Hey can I work on this ?

**Comment by Chadha93** [comment]
All yours @Saksham294

**Comment by Saksham294** [comment]
@sudhanshutech Hey Sudhanshu can you please resend your linkedIn url as the one provided is not working
