### ISSUE TITLE
In dark mode dot of "i" in "intel" logo is so lite

### ISSUE THREAD

**Issue by Srinja333** [layer5io/layer5#3991]
### Description

when hover on intel logo then dot of "i" is so lite.

### Expected Behavior

must be similar with other logo 

### ScreenRecording

https://user-images.githubusercontent.com/66597192/227189351-227c1803-da63-4823-8d4b-0c0c41b090cc.mp4

### Environment:
- Host OS: windows
- Browser: chrome

If this is an issue I want work on this @leecalcote  @Nikhil-Ladha 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
If this is an issue I'd like to work on this @Chadha93 , @leecalcote

**Comment by Srinja333** [comment]
I have already solved it🙂

**Comment by hirentimbadiya** [comment]
great, no issues.

**Comment by Nikhil-Ladha** [comment]
The dot of the "i" in lntel's logo is of different color than the rest of the logo, hence there is a color difference.
Unfortunately, this is not an issue hence closing it out. Please feel free to explore the site and look out for more issues, if any :)
