### ISSUE TITLE
[Community] Member Profile: Krishna Mahato

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#3993]
**Current Behavior**

@krishna9304 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @krishna9304 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @krishna9304
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by Chadha93** [comment]
@krishna9304 will you toss in the rest of the details here?

**Comment by krishna9304** [comment]
> @krishna9304 will you toss in the rest of the details here?

Sure.

Here are the rest of my details ---
- Twitter: [@krishna_mahato_](https://twitter.com/krishna_mahato_)
- LinkedIn: [@krishna-mahato](https://www.linkedin.com/in/krishna-mahato/)
- Link to profile picture: https://www.krishnamahato.com/images/me.jpeg

**Comment by anirudh-bukka** [comment]
Hi, I want to try this!

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by ShivangShandilya** [comment]
I would like to work on this if possible @Chadha93

**Comment by Chadha93** [comment]
Thank you all for showing interest in working on this. Let's assign this using the FCFS algorithm (first come first serve). @anirudh-bukka assigning this to you. 

@Srinja333 @ShivangShandilya  There are couple of other issues that need help, feel to comment there for the assignment.

**Comment by anirudh-bukka** [comment]
Thanks @Chadha93 , I'm on it!

**Comment by anirudh-bukka** [comment]
Hi @Chadha93 , can you please assign it to someone else? I am unable to spend time on this issue. I will take up another issue soon.

**Comment by sambhavgupta0705** [comment]
Hey @Chadha93 ,I would like to work on this issue

**Comment by vishalvivekm** [comment]
> Hi @Chadha93 , can you please assign it to someone else? I am unable to spend time on this issue. I will take up another issue soon.

Thanks for sending out the word!

**Comment by vishalvivekm** [comment]
Following the Same algorithm as @Chadha93's:

@Srinja333 wanna take it up? expecting a quick response from you, else will assign // @ShivangShandilya

**Comment by Srinja333** [comment]
Yes

**Comment by vishalvivekm** [comment]
> Yes

Thanks! @Srinja333

**Comment by hirentimbadiya** [comment]
what is update? @Srinja333

**Comment by vishalvivekm** [comment]
what's the status on the issue? @Srinja333 
@hirentimbadiya go ahead and toss a PR for this, if you would :)

**Comment by ShivangShandilya** [comment]
@vishalvivekm should I go for it ??

**Comment by vishalvivekm** [comment]
> @vishalvivekm should I go for it ??

Thanks @ShivangShandilya,
All the required informations have already been shared above, so if you can PR this real quick :)

**Comment by ShivangShandilya** [comment]
> > @vishalvivekm should I go for it ??
> 
> Thanks @ShivangShandilya, All the required informations have already been shared above, so if you can PR this real quick :)

what about @krishna9304 bio??

**Comment by Chadha93** [comment]
@ShivangShandilya Thank you for making a PR, but Krishna has stepped away for some time. We can close this PR along with the issue. Again Thank you for your contribution.
