### ISSUE TITLE
Changes in src/collections/resources/articles/kubernetes/multi-cluster/k8s-multi-cluster.mdx

### ISSUE THREAD

**Issue by ShivangShandilya** [layer5io/layer5#3995]
### Current Behavior
If you take a look at the file you can see two import commands which are not exactly importing anything and if you edit the file you can also see a commented blog which should now be uncommented as the blog is now published.

![image](https://user-images.githubusercontent.com/101946115/227396111-33e0a35c-bcb2-4eea-8a4c-efda76436a25.png)

### Desired Situation
Just remove the imported commands and uncomment the blog link so that it is visible.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShivangShandilya** [comment]
I would like to work on this issue ASAP

**Comment by Srinja333** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
@ShivangShandilya ha! What eagle eyes you have. Great catch. 😄
