### ISSUE TITLE
Vertical scollbar not showing up in homepage

### ISSUE THREAD

**Issue by aayushdutt** [layer5io/layer5#400]
The vertical scrollbar is not showing up in http://layer5.io/. Also, there is a horizontal scrollbar present which is not required.

**Comment by sarthakpranesh** [comment]
Hey @aayushdutt, I followed your link to the production website looks like it's already fixed :smile:

**Comment by sarthakpranesh** [comment]
Hey @aayushdutt @Nikhil-Ladha, I looked into this a bit more. It turns out this bug doesn't show up in Firefox but was able to reproduce this on Chromium.
I'll like to take up this issue if no one is already working on it :sweat_smile:

**Comment by Nikhil-Ladha** [comment]
Yes, please @sarthakpranesh. Go ahead, 👍🏼
