### ISSUE TITLE
changes required in the course "introduction to service meshes"

### ISSUE THREAD

**Issue by santosh-sankranthi** [layer5io/layer5#4002]
**Present state**
The screenshots of the course [Introduction to Service Meshes - Hands On](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started/) has not yet been updated.  It looks something like this:

![Screenshot (11)](https://user-images.githubusercontent.com/81618558/227731417-4489ddcf-2f2a-4510-adbf-91dd5835bd99.png)

![Screenshot (12)](https://user-images.githubusercontent.com/81618558/227731419-3848527d-2572-4924-ad6d-81306e42f9b2.png)

**present status** 

The present version of meshery looks something like this:

![Screenshot (9)](https://user-images.githubusercontent.com/81618558/227731579-2f2d6e60-7af6-4b18-9a4f-67e7952230e4.png)

since the UI has changed quite a bit it needs to be changed 
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by santosh-sankranthi** [comment]
could someone please assign this to me

**Comment by hirentimbadiya** [comment]
I would like to work on this

**Comment by santosh-sankranthi** [comment]
@hirentimbadiya  I'm workin on it

**Comment by himanshu1221** [comment]
Hey, @santosh-sankranthi what is the update on this issue?
is there anything I can help you with?

**Comment by santosh-sankranthi** [comment]
I have created a [pr](https://github.com/layer5io/layer5/pull/4016) for this issue but it seems to failing a few test cases, I think I would need some help with that. @himanshu1221
