### ISSUE TITLE
[Community] Member Profile:Sudhanshu Dasgupta

### ISSUE THREAD

**Issue by Saksham294** [layer5io/layer5#4007]
**Current Behavior**

Currently the bio of @sudhanshutech has syntax errors and hence his profile is not visible in the members section

**Desired Situation**

His profile should be visible in the members section
---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by hirentimbadiya** [comment]
I'd like to work on this.

**Comment by Saksham294** [comment]
@Chadha93 Since we have closed the PRs yesterday, has this issue been resolved and further can we now close this issue?Thanks

**Comment by Mayaleeeee** [comment]
Is this available? @leecalcote

**Comment by Indira-kumar** [comment]
I would like to work on this issue @leecalcote if it is still open

**Comment by sambhavgupta0705** [comment]
hey @leecalcote ,I would like to work on this issue
