### ISSUE TITLE
low contrast of play button

### ISSUE THREAD

**Issue by Srinja333** [layer5io/layer5#4012]
### Screenshots / Mockups

![Screenshot (100)](https://user-images.githubusercontent.com/66597192/228005951-fc44f962-3e2b-4059-ae82-7010d662633f.png)

![Screenshot (99)](https://user-images.githubusercontent.com/66597192/228009643-435432c1-f41d-4578-9e65-17d438b9c33b.png)

@leecalcote  if this is an issue can i work on this?

**Comment by hirentimbadiya** [comment]
can you give some more information about issue , I would like to work on this.

**Comment by bhaskarcsawant** [comment]
Please can you assign this to me? I would like to work on it.

What do you think about this? 

![Screenshot 2023-03-28 093841](https://user-images.githubusercontent.com/72681676/228125976-f72d79af-4ea0-483c-9e46-57cd6e982ae1.png)

**Comment by leecalcote** [comment]
Thanks for filing this, @Srinja333.

@bhaskarcsawant, your proposed solution is ideal.

**Comment by bhaskarcsawant** [comment]
Hey, this PR will change the play icon as proposed.😊

PR: [https://github.com/layer5io/layer5/pull/4021](url)

**Comment by hirentimbadiya** [comment]
@leecalcote , @Chadha93  , is this issue still open ? , if the please assign me.

**Comment by bhaskarcsawant** [comment]
@hirentimbadiya @Srinja333 have you tried to run layer 5 on local ?? ... is it running perfectly without errors ??....... I've tried to run it but it's stuck in Image processing job

**Comment by Srinja333** [comment]
If you have problems...then try to ask in slack or post your questions on --->https://discuss.layer5.io/c/meshery/5

**Comment by bhaskarcsawant** [comment]
> @bhaskarcsawant  I had also a problem in landscape page... it's solved by discussion forum.....if u have problem then try to ask  at slack or search/post your questions on https://discuss.layer5.io/c/meshery/5

I've asked, Searched for solution, but none of them in working at all

**Comment by AkashS20** [comment]
I'd like to work on this issue

**Comment by vishalvivekm** [comment]
> I'd like to work on this issue
> 
> How about adding a box-shadow on the play button on hovering over the thumbnail? @Chadha93

@AkashS20  Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by AkashS20** [comment]
Okay!:+1: I'll discuss in the next meet @vishalvivekm

**Comment by vishalvivekm** [comment]
> I'd like to work on this issue
> 
> How about adding a box-shadow on the play button on hovering over the thumbnail? @Chadha93
> Screencast.from.07-04-23.03.10.49.AM.IST.webm

If given the green light, @AkashS20 can start implementing it. // @Shivam-AfA @Chadha93 please

**Comment by niranjan-kurhade** [comment]
Is anyone working on this issue, if not I would like to work on it!
