### ISSUE TITLE
Add CNCF logo to Home page carousel 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4017]
### Desired Behavior
In the "ENGAGING AND COLLABORATING WITH" section, add the CNCF logo (SVG is already present as an asset in the site) to the carousel.

<img width="620" alt="Screenshot 2023-03-28 at 10 29 06 AM" src="https://user-images.githubusercontent.com/7570704/228289100-254ff8e8-816d-4369-a964-0de117d221bd.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by parmishh** [comment]
@leecalcote I would like to work on this.

**Comment by nxveeen** [comment]
@leecalcote I would like to work on this!!

**Comment by leecalcote** [comment]
Thanks for volunteering. Assigning in chronological order...

**Comment by nxveeen** [comment]
Hey!! @ShravaniAK are you working on it?? If not, I would like to work on this issue.

**Comment by ShravaniAK** [comment]
I also made the changes, just the pr is remaining, having some laptop issue, will make a pr by tomorrow

**Comment by nxveeen** [comment]
@ShravaniAK  Great!!👍

**Comment by sambhavgupta0705** [comment]
Hey @ShravaniAK ,are you still working on this issue?
If not then I would like to work on this one.

**Comment by Chadha93** [comment]
@ayushgupta4002 Will you again make a PR without making any update to dependencies? I'm reopening and assigning the issue to you.

**Comment by ayushgupta4002** [comment]
oh,ohk i'll make the PR
