### ISSUE TITLE
Project logos overflow on Porojects webpage

### ISSUE THREAD

**Issue by nxveeen** [layer5io/layer5#4024]
### Description
The layout of the Project logo section is messed up of this [page](https://layer5.io/projects). Few logos are out of frame ( Istio ans Traefik Mesh logos are not visible )

### Screenshots
![Screenshot 2023-03-29 234209](https://user-images.githubusercontent.com/83445952/228630092-f0f38c44-a9c5-4083-ab7f-579e0674e6fc.png)

### Environment:
- Host OS: Windows
- Browser: Firefox Chrome Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by nxveeen** [comment]
Hey! @leecalcote I would like to work on this issue.

**Comment by himanshu1221** [comment]
hey, @nxveeen this is the design for more you can refer to #3954

**Comment by nxveeen** [comment]
Thank you for the reference @himanshu1221. Closing the issue right away.
