### ISSUE TITLE
Changes in README.md

### ISSUE THREAD

**Issue by ShivangShandilya** [layer5io/layer5#4031]
### Current Behavior
The options below the Layer5 logo in README.md such as License and contributors when clicked redirect users back to the repository itself.

![image](https://user-images.githubusercontent.com/101946115/229271080-945b0583-3795-4cec-a73e-7241a35003fd.png)

### Desired Situation
The options below the Layer5 logo in README.md such as License and contributors should redirect users to their respective locations for easier access.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShivangShandilya** [comment]
Would like to work on this small issue

**Comment by sudhanshutech** [comment]
Nice to point out @ShivangShandilya , sure you can work on this. Go ahead

**Comment by aamirv1** [comment]
I have attempted to fix this issue, can you please review it?

**Comment by ShivangShandilya** [comment]
@aamirv1 You should allow members to first allow the issue before working on one and as you can see this issue was assigned to me so I would like to ask you to close this PR and let me work on this. If I'm unable to work on this I'll gladly pass it on to you but for now let's do it how it should be

**Comment by shindodkar** [comment]
is anyone one working on this project? I would like to contribute too...
