### ISSUE TITLE
[SEO] Update Duplicate Title Tags and Meta descriptions

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4041]
### Current Behavior
The pages listed below are using repeated `<title>` tags which confuse users as to which webpage they should follow and affects the search engines to determine which of a website's pages is relevant for a specific search query and which one should be prioritized in search results.

Duplicate meta descriptions make it difficult for search engines and users to differentiate between different webpages. It is better to have no meta description at all than to have a duplicate one.

Pages affected with duplicate `<title>` tags and meta descriptions -

1. https://layer5.io/cloud-native-management/meshmap/collaborate.
2. https://layer5.io/cloud-native-management/meshmap.
3. https://discuss.layer5.io/.
4. https://discuss.layer5.io/categories.
5. Update _http://slack.layer5.io/_ with  _https://slack.layer5.io/_ (https)

### Desired Situation
Provide a unique and concise title for each of the mentioned pages. Provide a relevant title.
- For information on how to create effective titles, please see [this Google article](https://support.google.com/webmasters/answer/35624).
- Remove the meta descriptions.
- You can also view the On-Page SEO Basics: [Meta Descriptions article](https://www.semrush.com/blog/on-page-seo-basics-meta-descriptions/)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Chadha93** [comment]
cc @leecalcote

**Comment by Saksham294** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
@Saksham294, yes, however, let's first get these descriptions written out in comments on this issue, so that execution once assigned isn't blocked. Would you like to draft these?

**Comment by Saksham294** [comment]
@leecalcote sure. Drafting meta descriptions right? Also can you help me navigate discuss.layer5.io in the layer5 repo pls ?

**Comment by Saksham294** [comment]
Link: https://layer5.io/cloud-native-management/meshmap/collaborate
Current Title: MeshMap
Suggested Title: Collaborate-Meshmap

Current Meta description: Collaboratively design and manage your Kubernetes clusters, service mesh deployments, and cloud native apps. Confidently configure your systems with MeshMap's visual topology and built-in design patterns.
 
Suggested Meta description: Configure, design and collaborate to manage your Kubernetes clusters, service mesh deployments and cloud native apps with MeshMap

**Comment by Saksham294** [comment]
Link: https://layer5.io/cloud-native-management/meshmap
Title: MeshMap

Current Meta description : Collaboratively design and manage your Kubernetes clusters, service mesh deployments, and cloud native apps. Confidently configure your systems with MeshMap's visual topology and built-in design patterns.

Suggested: Confidently configure your systems with MeshMap's visual topology and built-in design patterns.

**Comment by Saksham294** [comment]
@leecalcote Open to reviews. 
Regarding the other two links 
1) https://discuss.layer5.io/.
2) https://discuss.layer5.io/categories
These two have the same meta tag but different title. I am not sure if we should have a different meta tag for these two  , though I am open to draft one for both if required. 
For example, the categories page can have a meta description as : Explore different categories to find a solution to your problems.

**Comment by vishalvivekm** [comment]
> @leecalcote Open to reviews. Regarding the other two links
> 
>     1. https://discuss.layer5.io/.
> 
>     2. https://discuss.layer5.io/categories
>        These two have the same meta tag but different title. I am not sure if we should have a different meta tag for these two  , though I am open to draft one for both if required.
>        For example, the categories page can have a meta description as : Explore different categories to find a solution to your problems.

@Saksham294 Let's discuss this on the Websites call. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) if you would. :)

**Comment by Saksham294** [comment]
@vishalvivekm Sure :)

**Comment by Shivam-AfA** [comment]
Thanks @Saksham294 for the suggestions.
