### ISSUE TITLE
Improvement in Layout for mobile view

### ISSUE THREAD

**Issue by sidharthviz** [layer5io/layer5#4044]
### Current Behavior

The CNCF logo on the left side and the left side  Open application model  is getting out of section size
https://layer5.io/projects

### Desired Behavior

The collection section should be fixed for the mobile.

### Screenshots / Mockups

![Screenshot 2023-04-02 at 7 25 37 PM](https://user-images.githubusercontent.com/74046564/229357584-ec66bdd1-292d-4d1e-85ac-84348ed26272.png)

## In mobile View

![Screenshot 2023-04-02 at 7 26 28 PM](https://user-images.githubusercontent.com/74046564/229357590-236d168e-5802-4d02-80f6-79699ac722ba.png)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sidharthviz** [comment]
Can i work on it ?

**Comment by ankushbhardwaj408** [comment]
Can i work on this. I have already set up the local development environment.

**Comment by imjaglan** [comment]
Can you assign me this issue?

**Comment by nxveeen** [comment]
@sidharthviz  this is actual design not a bug for more you can check #3954 and #4024

**Comment by sidharthviz** [comment]
Alright @nxveeen Thank you
