### ISSUE TITLE
[Community] Member Profile: Karan Singh 

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#4048]
**Current Behavior**

@thisiskaransgit has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @thisiskaransgit  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @thisiskaransgit 
- Twitter: [@karanstwt](https://www.twitter.com/karanstwt)
- LinkedIn: [karansli](https://www.linkedin.com/in/karansli/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by thisiskaransgit** [comment]
Ohh wow, thank you Manish for the recognition, 
pfp link: https://www.gravatar.com/avatar/f1b069ed8c36655fcdd3c7cbe203b4b6?=200

Additionally, middle name won't be needed

**Comment by nxveeen** [comment]
@money8203 may i work on this??

**Comment by Chadha93** [comment]
Here you go @nxveeen

**Comment by nxveeen** [comment]
hey, @thisiskaransgit just wanted to know, **Karan Singh** or **Karan Thakur**. Which one should I add?? or **Karan Singh Thakur**

**Comment by thisiskaransgit** [comment]
@nxveeen "Karan Thakur"
