### ISSUE TITLE
[Handbook] Update Information regarding Membership to the Github organizations  

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#4054]
### Current Behavior

The current information does not cover how the membership is awarded to an individual. 

### Desired Behavior

The mentioned information for the Membership in the [handbook](https://layer5.io/community/handbook/recognition) has to be rephrased and updated with new updates in the organization. The number of organizations should be 5 instead of four now.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I would like to work on this. @thisiskaransgit can you describe this issue in detail and what information should be added in handbook and where can i find new updates in org.
@leecalcote , @Chadha93

**Comment by thisiskaransgit** [comment]
@Savio629, since you had already been looking to solve it, will you be taking up this issue?  if not I'll assign it to @hirentimbadiya

**Comment by vishalvivekm** [comment]
> I would like to work on this. @thisiskaransgit can you describe this issue in detail and what information should be added in handbook and where can i find new updates in org. @leecalcote , @Chadha93

assignee can refer to [this](https://www.youtube.com/watch?v=UV5NVFgeR2Y&t=3336s)

**Comment by leecalcote** [comment]
@thisiskaransgit given your understanding here, do you mind putting up the first draft on which others might offer review?

**Comment by Savio629** [comment]
At Layer5, we value consistent engagement and a shared mindset with our community members. When you actively participate in a project and align with its goals and values, you may receive an invitation to join the Github organization for that specific project. The number of invitations you receive will not be solely based on the quantity of code you write, but also on the quality and impact of your contributions. Moreover, you may have the opportunity to join any of the five Github organizations within Layer5 based on your interests and skill set.
