### ISSUE TITLE
Incorrect path for MeshmapDesigner.png

### ISSUE THREAD

**Issue by HetviSoni** [layer5io/layer5#4057]
### Description
 at src/sections/Meshmap/Meshmap-design/Meshmap-design-features/index.js the links for the images are as
![Screenshot (175)](https://user-images.githubusercontent.com/76479104/229864667-fac91c81-9ce5-4b49-a4cd-e51d3326f7d0.png)

Which gives the warning
![Screenshot (176)](https://user-images.githubusercontent.com/76479104/229864269-85e6e9ce-0d3c-464a-8850-f90aea4a9fdc.png)

### Expected Behavior
The correct path should be
const img1 = "../../../../assets/images/meshmap/MeshmapDesigner.png"

I would like to work on this issue.

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I would like to work on this.

**Comment by sant0143** [comment]
can i get assigned to this task?

**Comment by leecalcote** [comment]
Thank you for documenting this issue, @HetviSoni 👏 and for volunteering, @sant0143 👍

**Comment by HetviSoni** [comment]
> Thank you for documenting this issue, @HetviSoni 👏 and for volunteering, @sant0143 👍

Welcome😊. Actually I asked to get assigned for the issue first😅

**Comment by moazzam07** [comment]
@leecalcote can i work on this

**Comment by leecalcote** [comment]
> > Thank you for documenting this issue, @HetviSoni 👏 and for volunteering, @sant0143 👍
> 
> Welcome😊. Actually I asked to get assigned for the issue first😅

Apologies, @HetviSoni. I didn't see that request listed above.

**Comment by HetviSoni** [comment]
This issue is already here: https://github.com/layer5io/layer5/commit/1b161323a84e9a0384ecc32c574638d08400c237
Sorry for the confusion
