### ISSUE TITLE
Text is not Visible when Hovering the Card in Dark Mode

### ISSUE THREAD

**Issue by hirentimbadiya** [layer5io/layer5#4059]
### Description

go to this page https://layer5.io/learn/service-mesh-labs and turn on Dark Mode and hover over any card the text ( Open Scenario ) is not clearly visible in when we hover it in Dark Mode 

### Expected Behavior

That text should give hover effect as it gives in Light Mode that text should change its color to pale green type as it in website.

### Screenshots

https://user-images.githubusercontent.com/86219935/230066488-848a21df-3fcc-40d4-b8e5-b295c597c866.mp4

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I'd love to work on this issue , please assign me @leecalcote , @Chadha93 , @Nikhil-Ladha

**Comment by leecalcote** [comment]
@hirentimbadiya thanks for raising this up. We have a bug on our hands here. 🙂

**Comment by Arka90** [comment]
Please Assign me this issue

**Comment by hirentimbadiya** [comment]
> Please Assign me this issue

I already made PR on this and did it , you can check other issues @Arka90
