### ISSUE TITLE
fix the checklint warnings

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4069]
### Description

Currently there are a number of checklint warnings that appear when any changes are committed locally.

### Expected Behavior

These warnings should be fixed. All of these warnings are related to unused variables ,so this would require just removing those variables from the files

### Screenshots

![image](https://user-images.githubusercontent.com/114604338/230476907-08ea5123-4cf9-464a-9a9c-3e1b00cb7e5d.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by rishavcodes** [comment]
Hello, Can I please be assigned to this issue ?

**Comment by Gaurav-08-dev** [comment]
Hey Can I work on this?
