### ISSUE TITLE
Oveflowing Screen in Small Devices

### ISSUE THREAD

**Issue by hirentimbadiya** [layer5io/layer5#4072]
### Description

Screen in Overflowing in inner in inner Screen in the page https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-linkerd at resolution about 477px width 

### Expected Behavior
Screen should not overflow and Font size of Welcome! should be smaller in smaller devices.

### Screenshots

![overflow](https://user-images.githubusercontent.com/86219935/230542231-24a36175-06e4-45e3-b342-6b3b59788f72.png)

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I'd love to work on this issue , @leecalcote , @Chadha93

**Comment by Jamir2412** [comment]
I tried to find the file or folder which contain all these code of the given page but I couldn't . Can you tell me where I can find the files related to this page :- https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-linkerd

**Comment by Chadha93** [comment]
@thisiskaransgit It's not right to say, "no one will use it on a small device." @hirentimbadiya Do you happen to have a solution for this?

**Comment by Bidhu1024** [comment]
@Chadha93 The "X" axis is overflowing. This is very simple to adjust the width for the small devices. I can fix it for you. Please assign it to me.

**Comment by Bidhu1024** [comment]
@tinniaru3005 Please let me know if I could fix and generate a PR for you.

**Comment by hirentimbadiya** [comment]
Can I Close this Issue @Chadha93 @thisiskaransgit

**Comment by thisiskaransgit** [comment]
@hirentimbadiya, as mentioned by @Chadha93, I might be wrong, so if you have a solution for this issue, do let us know here, and then you can proceed further with the assignment.
