### ISSUE TITLE
[UX] Graphic Design: Create a Layer5-branded 3D book to represent the Community Handbook

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4075]
### Current Behavior
The Community Handbook has a number of pages and is commonly referenced by community members. 

### Desired Behavior
It would be nice to have a visual representation of this handbook to be displayed on pages like the [Community Managers page
](https://layer5.io/community/community-managers).

<img width="819" alt="Screenshot 2023-04-07 at 5 49 47 PM" src="https://user-images.githubusercontent.com/7570704/230689527-129e16db-c76e-49be-835b-1af6b7fe5826.png">

### Screenshots / Mockups
An example of such a 3D book can be seen in the "Cloud native focused" section of the layer5.io home page.

### Implementation
1. Create a graphic using elements of Layer5's brand (see the community shared drive for many, many assets)
2. Use https://3dbookcovergenerator.netlify.app to style that graphic as a 3D book.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
@leecalcote  If I am not wrong then we are just supposed to take the elements/images of Layer5' brand and put them in the link specified for styling, right?

**Comment by Mayaleeeee** [comment]
Hi @leecalcote I would.love to work on this.

**Comment by vishalvivekm** [comment]
> Hi @vishalvivekm I'm working on it.
> 
> I have a question, so I'll be reaching out soon.

Yess, Please do! @Mayaleeeee

**Comment by leecalcote** [comment]
@Mayaleeeee progress to report? How can we help?

**Comment by Mayaleeeee** [comment]
Hy @leecalcote , I have been trying to use this website https://3dbookcovergenerator.netlify.app , but I still don't understand how it works.

**Comment by Savio629** [comment]
@Mayaleeeee progress?
Which part of the website you are finding it difficult to understand?
Do let us know then we can try to help you out.

**Comment by Savio629** [comment]
## Designs for Community Handbook

| For Light Mode:    |   For Dark Mode: |
| -------------------  | ------------------- |
|<img src="https://github.com/layer5io/layer5/assets/91362589/1780f4f9-b332-4b91-95ac-841013624b86" width="300"> | <img src="https://github.com/layer5io/layer5/assets/91362589/25ba9f51-479b-457c-9a62-3e926fa3644f" width="300"> |
