### ISSUE TITLE
Github Logo is not properly visible in Dark Mode 

### ISSUE THREAD

**Issue by hirentimbadiya** [layer5io/layer5#4082]
### Description
Go to Page https://layer5.io/cloud-native-management/meshery/operating-service-meshes and see github logo in dark mode not clearly visible it lacks opacity , not consistent as it in other pages or logo which is in footer.

### Expected Behavior
Github logo should be visible according to the dark mode like it does in other pages.

### Screenshots
![ISSUE ](https://user-images.githubusercontent.com/86219935/231153504-e06b990f-a986-494e-a84f-628e2c069975.png)

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I'd love to contribute to this issue.

**Comment by arunkarthicknm** [comment]
Hey @hirentimbadiya , I'm interested in solving this issue. Can you assign me please?

**Comment by arunkarthicknm** [comment]
@Udit-takkar

**Comment by hirentimbadiya** [comment]
> Hey @hirentimbadiya , I'm interested in solving this issue. Can you assign me please?

i'm also waiting to get assigned

**Comment by Udit-takkar** [comment]
this is a duplicate of https://github.com/layer5io/layer5/issues/3785 but the PR is inactive so I'll assign @hirentimbadiya on that issue
