### ISSUE TITLE
Adding a new adopter logo to layer5 homepage

### ISSUE THREAD

**Issue by money8203** [layer5io/layer5#4089]
### Current Behavior
Recently there was a new logo added to the adopters list on [meshery.io](http://meshery.io/) and we need the same logo to be added to the [layer5.io](http://layer5.io/) homepage!!

### Desired Behavior
Metabit Trading logo needs to be in the list of all the adapters of meshery on the layer5 homepage

### Screenshots / Mockups
![Screenshot 2023-04-13 195700](https://user-images.githubusercontent.com/89864818/231791427-8236afb0-0725-4cf5-a2a2-834d05235388.png)

Similar logo (highlighted one) needs to be added on layer5 homepage, here
![image](https://user-images.githubusercontent.com/89864818/231792464-6d018df2-d6cd-4ce3-8516-cf06e9b4c20e.png)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by arunkarthicknm** [comment]
I like to work on this, can you assign me please? @leecalcote

**Comment by money8203** [comment]
Here you go @arunkarthicknm

**Comment by arunkarthicknm** [comment]
Description for Metabit Trading? @money8203

**Comment by sambhavgupta0705** [comment]
If this issue still open then I would like to work on this issue.
