### ISSUE TITLE
Errors in service-mesh-landscape page when using npm build

### ISSUE THREAD

**Issue by AkashS20** [layer5io/layer5#4090]
### Description

`npm start` or `make site` build is failing on page https://layer5.io/service-mesh-landscape, this error is not occurring when building with `gatsby`

### Video

[Video](https://user-images.githubusercontent.com/92908347/231837267-dc0af1b4-d7a9-4820-970d-9cc6d26412c2.webm)

### Expected Behavior

The build should not break.

### Environment:
- Host OS: Linux
- Browser: Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AkashS20** [comment]
I'd like to work on this issue

**Comment by leecalcote** [comment]
Thanks, @AkashS20. I wonder if this is due to a recent dependency upgrade.
