### ISSUE TITLE
Add user images to the in-line testimonials

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4097]
### Current Behavior
The Layer5 website has in-line testimonials on a few places, including https://layer5.io/cloud-native-management/meshmap/ and https://layer5.io/cloud-native-management/meshery.

![image](https://user-images.githubusercontent.com/88040318/232166990-74243473-093e-43a4-847f-f6047691124a.png)

### Desired Behavior
We need to add a picture of the user in these in-line quotes, similar to the Review slider at the end of the page https://layer5.io/cloud-native-management/meshmap. The image could be creatively placed beside the name of the user.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
Hey @Shivam-AfA I would like to work on this

**Comment by Saksham294** [comment]
I can't find these inline quotes when I am running it on localhost
