### ISSUE TITLE
Redirecting to meshery catalog from meshmap page

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4098]
### Current Behavior
The meshmap page here https://layer5.io/cloud-native-management/meshmap/ contains an animation of floating catalog cards. 

![image](https://user-images.githubusercontent.com/88040318/232167327-a9d986d9-0c74-4bd6-8f9a-b89cf8f839ce.png)

### Desired Situation
By clicking on this animated graphic, the user should be redirected to the meshery catalog here: https://meshery.io/catalog

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AkashS20** [comment]
I'd like to work on this issue
