### ISSUE TITLE
Change heading gradient when hovered

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4099]
### Current Behavior
The MeshMap page https://layer5.io/cloud-native-management/meshmap/ contains three feature sections: Design, Visualize and Collaborate. Each section has a heading which redirects the user to the respective page. 

![image](https://user-images.githubusercontent.com/88040318/232167863-080de6df-55a2-4a65-9018-54fc31e8cd94.png)

### Desired Situation
The color/ gradient of the heading should change when the user hovers over it. The "Learn More" text color should also change to white on hover.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I'd like to contribute to this issue

**Comment by Saksham294** [comment]
Hey @Shivam-AfA I would like to work on this

**Comment by Suyash699** [comment]
Hey @Shivam-AfA I would like to work on this issue.

**Comment by Shivam-AfA** [comment]
On a first come first serve basis, let's assign this to @hirentimbadiya. @Saksham294 or @Suyash699 can work if the task remains unfinished by the end of the next week.

**Comment by DarrenDsouza7273** [comment]
@Shivam-AfA can u elaborate this issue? do you want the heading to appear darker than before when the user howers over it?

**Comment by Ansh1372** [comment]
is this issue still remains? if yes then i would like to work on it

**Comment by Shivam-AfA** [comment]
> @Shivam-AfA can you please specify what colors should i prefer for gradient ?

@hirentimbadiya you can try changing the color to #00d3a9 on hover.

> is this issue still remains? if yes then i would like to work on it

@Ansh1372 Currently @hirentimbadiya is working on it.
