### ISSUE TITLE
[Community] Writing Badge needs hyperlink to Writing Program page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4107]
### Description
Each community member has the opportunity to earn a badges for display on their profile. Each badge is linked to their respective project.

The writing badge is missing such a link.

### Expected Behavior
Need to link to https://layer5.io/community/handbook/writing-program

### Screenshots

<img width="454" alt="Screenshot 2023-04-18 at 4 42 57 PM" src="https://user-images.githubusercontent.com/7570704/232911990-0f2d05b0-c63c-49a3-9c03-cdae05bc0495.png">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
i'd like to contribute to this issue.

**Comment by nitish799** [comment]
i want contribute to this issue.

**Comment by Ansh1372** [comment]
hey, this is first in open source contributions , so if this issue is still available i love to work on it...

**Comment by J0SAL** [comment]
@leecalcote could you please assign me the issue.
Additionally I also wanted to know if the link should be opened in new page or the same page?

**Comment by Savio629** [comment]
As @hirentimbadiya commented first, he can start working on the issue.
Also it should work the same as it is working for other badges.

**Comment by hirentimbadiya** [comment]
hey @leecalcote , instead of writer's badge the ui-ux badge is missing the respective link here.

**Comment by leecalcote** [comment]
Oh, I see. OK, yes, let’s ensure that each badge has a link.

**Comment by hirentimbadiya** [comment]
> Oh, I see. OK, yes, let’s ensure that each badge has a link.

can you please provide a link ?

**Comment by Chadha93** [comment]
> > Oh, I see. OK, yes, let’s ensure that each badge has a link.
> 
> can you please provide a link ?

[@Hiren Timbadiya](https://layer5io.slack.com/team/U04RDPJ6C3W)
 At the moment there is no specific link/page for the UI-UX badge. You can propose a section in the community handbook for it similar to writing program.

**Comment by vishalvivekm** [comment]
@hirentimbadiya any progress here? 
In case you need any help or suggestions: let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) , if you would :)

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya any progress here? In case you need any help or suggestions: let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) , if you would :)

vishal at this point there is no such page in website but gaurav chada suggested me to create a one related to the UI/UX simple information.

**Comment by Chadha93** [comment]
> > @hirentimbadiya any progress here? In case you need any help or suggestions: let's discuss this on websites call, add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) , if you would :)
> 
> vishal at this point there is no such page in website but gaurav chada suggested me to create a one related to the UI/UX simple information.

@hirentimbadiya Did you make progress?

**Comment by hirentimbadiya** [comment]
> Member

not yet

**Comment by vishalvivekm** [comment]
> > Member
> 
> not yet

@hirentimbadiya please sound off on any blockers that you might be facing today in websites call
