### ISSUE TITLE
Pagination should redirect to top

### ISSUE THREAD

**Issue by 777Prabhjot** [layer5io/layer5#4108]
In the blog/resources page i think after click on any page it should scroll to the top of the section so that user can see new resources according to the page right now user have to manually go to top to see new resources after changing the page.

### Screenshots / Mockups

https://user-images.githubusercontent.com/68184118/233058496-b8b979e3-8b6c-4900-aef4-0c1b5062b7f1.mp4

**Comment by Ansh1372** [comment]
Is this issue is available i would love to work on it ? if yes then assign  this ..
