### ISSUE TITLE
Add CommunityBridge next to GSoC

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#411]
**Current Behavior**
Layer5 is participating in CommunityBridge. 

**Desired Behavior**
Let's have a listing of this program next to the GSoC program.
<img width="905" alt="Screen Shot 2020-05-12 at 7 43 51 PM" src="https://user-images.githubusercontent.com/7570704/81759116-6ab68b80-9489-11ea-8a5d-e9f1a4bfb254.png">

**Comment by leecalcote** [comment]
@aayushdutt would you like to knock this one out?

**Comment by kushthedude** [comment]
Fixed!

**Comment by leecalcote** [comment]
@kushthedude, we can revive GSoD now.

**Comment by kushthedude** [comment]
Yes indeed!
