### ISSUE TITLE
Publish Layer5 Brand Guide

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4110]
### Current Behavior
Layer5 has a [Brand Guide](https://docs.google.com/presentation/d/1Ofy15e2bAIz4IYC8X70omnlpX9vI0QZpkRijYbxGAd4/edit#slide=id.g232ed436c58_0_144), which needs cleaned up and published.

_Note: submit a community member form, if you can't access the brand guide --> https://layer5.io/newcomer_

### Desired Behavior
1. Clean up the brand guide; give it final polish.
1. Find a section to include a description of the brand guide on https://layer5.io/company/brand or create a new section and publish.

### Implementation
1. Export as PDF.
1. Include PDF in the overall brand kit.zip
1. Publish on /brand page as an individual section.

### Acceptance Tests
1. Brand guide is complete, polished, and publicly available on layer5.io/company/brand

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
@ritiksaxena124

**Comment by roopeshsn** [comment]
Hi @leecalcote! If given a chance, I would like to work on this!

**Comment by CatherineKiiru** [comment]
I'd also like to work on this issue. Is there a chance for collaboration?

**Comment by J0SAL** [comment]
Hi @leecalcote could you please assign me this issue

**Comment by ritiksaxena124** [comment]
Thank you for your interest folks, as we follow a first come first serve policy, So congratulations @roopeshsn you can start working on this issue.
Submit a community member form if you haven't already to get access to relevant resources --> [ https://layer5.io/newcomer](url), Also we have marked on the guide what needs to be updated, so do check it out. 

Till then @CatherineKiiru and @J0SAL  you can help him with this issue or look for some other issues you might be interested in.

**Comment by CatherineKiiru** [comment]
@leecalcote, I don't have access to the slides. I've sent an access request

**Comment by leecalcote** [comment]
> @leecalcote, I don't have access to the slides. I've sent an access request

@CatherineKiiru excellent. Doc access: Please read the _Note_ in the issue description and @ritiksaxena124's similar guidance as well.

**Comment by roopeshsn** [comment]
Thanks @leecalcote and @ritiksaxena124! I'll try to complete it before Monday.

**Comment by CatherineKiiru** [comment]
Hi, @leecalcote I still don't have access to the file

**Comment by ritiksaxena124** [comment]
Hey @CatherineKiiru, @roopeshsn, @J0SAL have you guys submitted the newcomers form, if submitted, did anyone of you get the access?

**Comment by CatherineKiiru** [comment]
Hey @ritiksaxena124 yes, I submitted the form but haven't gotten access to the brand guide

**Comment by leecalcote** [comment]
@CatherineKiiru, if you submitted the form, then you should see the "Layer5 Community" drive when you visit https://drive.google.com. Look under the Shared Drives section.

**Comment by ritiksaxena124** [comment]
Also when you do, make sure you are logged in with the same account that you used to fill out the form.

**Comment by CatherineKiiru** [comment]
@ritiksaxena124 @leecalcote thank you, I've gotten access to the brand guide

**Comment by roopeshsn** [comment]
Hi @CatherineKiiru! Let me know if you complete the revamping of the brand guide so that we can add the pdf of the brand guide to the brand kit (zip).

**Comment by leecalcote** [comment]
It's be great to get an update on this effort, @ritiksaxena124 @CatherineKiiru

**Comment by CatherineKiiru** [comment]
@leecalcote we're done making the edits to the file. I will publish the brand guide to the website.

**Comment by leecalcote** [comment]
@CatherineKiiru thanks for letting me know that this is ready for review. I've offered up a few comments in the deck to consider prior to publishing.

**Comment by CatherineKiiru** [comment]
@leecalcote I've seen the comments, I'll work on them and notify you once I'm done for one last review before publishing

**Comment by leecalcote** [comment]
Thanks much, @CatherineKiiru ✔️ 

// @avantikajain289

**Comment by leecalcote** [comment]
@roopeshsn we're ready to publish.
