### ISSUE TITLE
[Community] Member Profile: for @suhail34

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4112]
**Current Behavior**

@suhail34 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @suhail34 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @suhail34 
- Twitter: [SuhailK71070185](https://twitter.com/SuhailK71070185)
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](http://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
Your Linkedin and profile picture, please @suhail34

**Comment by Saksham294** [comment]
@vishalvivekm I would like to work on this

**Comment by vishalvivekm** [comment]
> @vishalvivekm I would like to work on this

Thanks @Saksham294

**Comment by Saksham294** [comment]
@suhail34 Also let me know about the bio you would want for your profile

**Comment by suhail34** [comment]
Here it is
LinkedIn: https://www.linkedin.com/in/suhail-khan-b505531b8/
ProfilePic : https://drive.google.com/file/d/1o3zf4n69WgReKLI-cVrdWer3DqYnYKUv/view
bio : https://docs.google.com/document/d/1yL01nmQrihylms8dTjvttvUgx2744X9uHO-IZ3lsnok/edit?usp=sharing

**Comment by Saksham294** [comment]
Hey @vishalvivekm , I have created a new PR which resolved this issue kindly check.  I closed the last one as it had merge conflict with the master, so I resolved the conflict and created a new PR. Thanks
