### ISSUE TITLE
Several options appear on your profile icon while scrolling

### ISSUE THREAD

**Issue by ShivangShandilya** [layer5io/layer5#4113]
### Description
 While creating my topic, I noticed that on my profile icon on top right side of the page whenever I scrolled up or down - profile,messages, bookmark options appeared on it and that too in a weird way.

### Expected Behavior
To fix this so that the options doesn't appear automatically.

### Screenshots

https://user-images.githubusercontent.com/101946115/233421717-e54d4170-33a4-4a0a-8c19-5a2b8b183048.mp4

**Enviroment:**
- Host OS: 
- Browser: 

---

[Optional] **To Reproduce**

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

Contributing to the [discuss.layer5.io](https://discuss.layer5.io/) site involves a unique contribution model in which contributors make changes in the discourse server running at [staging-discuss.layer5.io](https://staging-discuss.layer5.io/) first, then those changes are reviewed and propagated to the [discuss.layer5.io](https://discuss.layer5.io/).

Steps to get an access to the [staging-discuss.layer5.io](https://staging-discuss.layer5.io/)
- First create an account [here](https://staging-discuss.layer5.io/).
- Then ask for the admin access.
- And then start contributing to the discuss forum.

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shubham-singh-748** [comment]
can you share the link, i am not able to find that link

**Comment by ShivangShandilya** [comment]
The issue seems to have been fixed, I'll close this for now.
