### ISSUE TITLE
Navbar item overflow on the logo

### ISSUE THREAD

**Issue by shibu-g** [layer5io/layer5#4117]
### Description

In the main page of layer 5 the nevbar item 'Solutions' overflow on the logo
https://layer5.io/
### Expected Behavior

It should not overflow in the top of the logo it should stay beside the logo
### Environment:
- Host OS: windows 10
- Browser:  Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shibu-g** [comment]
![Screenshot_2023-04-22-08-01-05-350-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/109884948/233763278-5cc04b54-623d-400b-9fa6-dfb41b8942b1.jpg)

**Comment by shibu-g** [comment]
Can I work in it?

**Comment by vishalvivekm** [comment]
"Thanks for bringing it up, @shibu-g!
Go ahead and please ensure that the changes do not cause any/similar issues on other screen sizes as well.
