### ISSUE TITLE
Make SVGs responsive to media queries and changes from desktop to mobile.

### ISSUE THREAD

**Issue by randychilau** [layer5io/layer5#4119]
### Current Behavior
Some recent files were changed from image type to SVGs for color mode transitioning. They are not resizing/responding to the media queries in the styled components.

![svg_no_responsive](https://user-images.githubusercontent.com/90356410/233813601-0b780b52-dc15-438c-883f-32db48f00545.gif)

### Desired Situation

SVGs are responsive to media queries and changing from desktop to mobile.

Need to add "max-width" tag to SVGs.

**Comment by leecalcote** [comment]
Thank you for opening this up, @randychilau 👍

**Comment by Saksham294** [comment]
Hey @randychilau I'd like to work on this

**Comment by randychilau** [comment]
Hi @Saksham294,

Thanks so much for your offer to work on this. Unfortunately, I forgot to mention in the description that I was creating the issue for myself to work on as discussed in the [#websites channel](https://layer5io.slack.com/archives/C015QJKUMPU/p1682184250656499) in Slack

![image](https://user-images.githubusercontent.com/90356410/233821634-ee47bc79-b446-4f74-ad46-3b7a1241b78e.png)
  
Apologies for the confusion,
Randy

**Comment by amankumarnayak** [comment]
Hey @randychilau  i'd work on this .
