### ISSUE TITLE
[Talk] Add Open Source 101 at Home to workshops page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#412]
**Current Behavior**
A talk on Meshery was given at Open Source 101 at Home - "Solving the Service Mesh Adopter’s Dilemma"

**Desired Behavior**

This talk should be added to https://layer5.io/workshops and https://layer5.io/meshery

- Deck - https://calcotestudios.com/talks/decks/slides-open-source-101-at-home-solving-the-service-mesh-adopters-dilemma.html
- Event - https://opensource101.com/sessions/solving-the-service-mesh-adopters-dilemma/

**Comment by leecalcote** [comment]
Recording is now available - https://www.youtube.com/watch?v=Q1zSWbO0RmI&list=PL3A-A6hPO2IN_HSU0pSfijBboiHggs5mC&index=2&t=0s

**Comment by leecalcote** [comment]
@Vineet-Sharma29 you might consider grabbing this issue. This talk should be added to:

- layer5.io/meshery
- docs.meshery.io
----
We may want to create a new section for presentations on this site:
- meshery.io

**Comment by Vineet-Sharma29** [comment]
Would take work on this

**Comment by Vineet-Sharma29** [comment]
@leecalcote can you tell at what time the event was? At present i have set the time to `2020-05-12 +0000` without specific hours

**Comment by ashiscs** [comment]
11:00 AM – 5:00 PM EDT

**Comment by Vineet-Sharma29** [comment]
Is it starting at 11:00 AM EDT?

**Comment by ashiscs** [comment]
@Vineet-Sharma29 yes the event started from 11:00 AM EDT !
Confirmation from @leecalcote sir will mark it's approval

**Comment by Vineet-Sharma29** [comment]
@ashiscs Ok. Thanks!!!!

**Comment by leecalcote** [comment]
Spot on. The event started a little later in the day, I think so as to accommodate those in the Pacific time zone.
