### ISSUE TITLE
Logo Overflowing

### ISSUE THREAD

**Issue by Arka90** [layer5io/layer5#4127]
### Expected Behavior
Currently the Layer5 logo overflowing at 992 px I think the responsive style is firing at 907 px  changing that break point might help

## Screenshots
![Issue](https://user-images.githubusercontent.com/64225385/234070117-dd1c3eed-34f6-4be7-9b87-d8097541c393.JPG)

### Environment:
- Host OS: Windows
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shibu-g** [comment]
@Arka90  sorry to inform you that this bug was already reported and solved.

**Comment by Arka90** [comment]
yeah just checked  the website it's perfect now...but earlier I getting this overflowing thing that's why created this issue
