### ISSUE TITLE
In mobile view After clicking on some links in the nav item the navbar stays on it's place.

### ISSUE THREAD

**Issue by shibu-g** [layer5io/layer5#4128]
### Description

In Mobile view whenever we clicked on any pages in the navbar the navbar stays on it's place .
### Expected Behavior

The expected behaviour should be the navbar got removed from the display because we click on the page to visit it but the navbar blocking our view
### Environment:
- Host OS: Android 
- Browser: Chrome 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shibu-g** [comment]
Can I start working on this?

**Comment by leecalcote** [comment]
@Udit-takkar fyi
