### ISSUE TITLE
[UX] Call to Action: Graphic design needed for Meshery Playground 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4129]
### Current Behavior
As a hosted instance of Meshery running in the CNCF labs, the Meshery Playground is an easy way to use Meshery - https://play.meshery.io. The layer5.io website does not yet highlight this resource for visitors.

### Desired Behavior
The layer5.io website needs a fresh Call to Action (CTA)

### Screenshots / Mockups
Example CTA:
<img width="1178" alt="Screenshot 2023-04-24 at 4 19 19 PM" src="https://user-images.githubusercontent.com/7570704/234119278-eafa4075-b8a9-4014-9ba2-b930d5d24a57.png">

### Implementation
1. Design one or more new Call to Action graphics in Layer5 Community Figma page here -->  https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=0-1

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
@ritiksaxena124 let's get a few of the Playground graphics that you've created loaded as CTAs.

**Comment by Savio629** [comment]
@leecalcote @Shivam-AfA @ritiksaxena124
Made some designs of CTA for Meshery Playground, they still need some final adjustments.
Added this designs of Call to Action graphics in Layer5 Community Figma page --> https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=0-1
![CTA_MP](https://user-images.githubusercontent.com/91362589/235085418-76cc8c40-0eba-4069-bfa6-989264b30c93.PNG)

**Comment by leecalcote** [comment]
@Savio629, these are pretty great. 😀 

Let's move away from “service mesh” and move to “cloud native”…

**Comment by ritiksaxena124** [comment]
LGTM 🚀

**Comment by Shivam-AfA** [comment]
@Savio629 Some really cool design skills shown here.

**Comment by Shivam-AfA** [comment]
@ritiksaxena124 is this complete?

**Comment by Savio629** [comment]
// @ritiksaxena124

**Comment by ritiksaxena124** [comment]
lets use [this](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=13674%3A19462&mode=design&t=GtQWRkEjZwvnPdQ0-1) design by Savio here

**Comment by Savio629** [comment]
@vishalvivekm We are going to add this cta on website,right?

**Comment by Savio629** [comment]
// @leecalcote

**Comment by Chadha93** [comment]
> // @leecalcote

yes @Savio629. Assigning this to you. Use the CTA shared by Ritik above.

**Comment by Savio629** [comment]
I'm working on this issue
