### ISSUE TITLE
Fix the background color of text in green

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4135]
### Description

On https://layer5.io/community page ,besides the newcomers map ,the background color of green text is odd
### Expected Behavior

The background color should be changed to be consistent
### Screenshots

![image](https://user-images.githubusercontent.com/114604338/234256474-d7b67fc4-febe-4277-b1ae-eb83bcfb5d50.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
I'd like to work on this

**Comment by Saksham294** [comment]
The background color is actually a gradient, for consistency either we can remove the color all together or use a solid color. Wdyt @ayushthe1 ?

**Comment by Saksham294** [comment]
<img width="666" alt="Screenshot 2023-04-26 at 4 12 38 PM" src="https://user-images.githubusercontent.com/86240862/234551703-0f127d70-28f5-4b3e-8ae3-0bd792574ae9.png">
This is how it looks once we have removed the background color
