### ISSUE TITLE
Make the filter menu on members page compatible for dark mode

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4136]
### Description

Currently on https://layer5.io/community/members page ,there's a filter menu for sorting out members .The menu's styling hasn't been adapted for dark mode and we see the same version of the menu in both light and dark modes

### Expected Behavior

Make the menu compatible for dark mode 

### Screenshots

![image](https://user-images.githubusercontent.com/114604338/234260243-4ce5149e-d6db-481e-a209-baab7457d5a5.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shibu-g** [comment]
can i start working on this?

**Comment by vishalvivekm** [comment]
@shibu-g Please sound off with your progress on the issue in today's websites call : You can add this as an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#)

**Comment by shibu-g** [comment]
> @shibu-g Please sound off with your progress on the issue in today's websites call : You can add this as an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#) 

Okay 👍

**Comment by shibu-g** [comment]
Hello I am really sorry I am unable to complete this task because i have to go somewhere urgently and there i don't have access of my computer .

**Comment by HetviSoni** [comment]
I would like to work on this issue.

**Comment by SoumyadeepOSD** [comment]
I would like to work on this issue

**Comment by Savio629** [comment]
As @shibu-g is unable to complete this task, @HetviSoni will you be able to take up on this issue?

**Comment by HetviSoni** [comment]
hey I wanted to point out that the dropdown on https://layer5.io/programs/lfx in dark mode is same as the dropdown at given page (https://layer5.io/community/members). So in my opinion it looks good as it is.

**Comment by Savio629** [comment]
Do get some feedback from other folks on slack too.
