### ISSUE TITLE
Increase the size of card & text inside it

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4139]
### Description

The text inside the cards on https://layer5.io/community/handbook is very small and hard to read

### Expected Behavior

increase the card height and and font-size

### Screenshots

Current:
![image](https://user-images.githubusercontent.com/114604338/234281154-dc200a50-1b86-475a-b5f2-d20abd949502.png)

Expected:

![image](https://user-images.githubusercontent.com/114604338/234281363-1fd00c2f-a331-4ae7-a3ee-d20b8c54c1ed.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ayushthe1** [comment]
@Pulkitxm assigned this issue to you. You would need to increase the height of the cards and increase the font-size of text inside them.

**Comment by hirentimbadiya** [comment]
> @ayushthe1 Hi I would like to contribute to this issue can you let me know how I can solve this issue?

all you need to do is just increase the height of card and font size of the text inside it , very easy. and don't forget to check out [https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md](url) before setting up project locally.

**Comment by Pulkitxm** [comment]
In which file do i need to make changes ?

**Comment by Dhairyash-1** [comment]
@ayushthe1 I have made a pr for this issue please have a look

**Comment by Dhairyash-1** [comment]
@ayushthe1 I have made PR  have a look on it

**Comment by Akhil2707** [comment]
i would like to work on this issue ,can someone assign this issue to me ?

**Comment by Vishrut19** [comment]
Can I take this issue?
