### ISSUE TITLE
Switch to relative URLs in the /programs cards

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#414]
**Current Behavior**
The absolute URLs used on the cards in https://layer5.io/programs, prevents PR reviewers from easily navigating to deployment previews created by Netlify.

**Desired Behavior**
These URLs should be relative paths so that reviewers may see changes in a deployment preview before merging a PR.

**Comment by kumarabd** [comment]
@leecalcote I would be interested to work on this issue, however I am pretty new to this community. Can someone give me some initial leads on this? I understood that the cards on the above URL is to be replaced with relative URLs. But where do I get started with and what are the information we have before hand? It would be great if someone helps me in kickstarting. Thanks.

**Comment by Nikhil-Ladha** [comment]
Hi @kumarabd. I was just looking into this issue a few moments earlier before you came up. You can find the files for the programs in the _collections/ directory. And the program page itself is the _includes/collections/programs.html file. Try to go through it and see how you can solve it. Feel free to ping me if you need anything 🙂.

**Comment by kumarabd** [comment]
@leecalcote  Lets close this? As this does not require any changes.

**Comment by leecalcote** [comment]
@Nikhil-Ladha this is something of a curious issue. Will you have a look at @kumarabd's changes in this PR (https://github.com/layer5io/layer5/pull/459) and the Netlify deployment preview?
