### ISSUE TITLE
make the coverage, press-release button dark-mode compatible

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4140]
### Description

The dark-mode ,press-release buttons and search box on https://layer5.io/company/news aren't dark mode compatible .
### Screenshots

Current : 
![image](https://user-images.githubusercontent.com/114604338/234288024-d536e276-8b90-45b5-a9e2-1f9d61fac0d3.png)

somewhat expected:
![image](https://user-images.githubusercontent.com/114604338/234288221-7e344150-deb4-462c-bfc7-c25665174c37.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Sheikh-JamirAlam** [comment]
Can I work on it?

**Comment by ayushthe1** [comment]
assigned to you @Sheikh-JamirAlam

**Comment by Anurag8305** [comment]
hey, @ayushthe1 I am looking for my first open-source contribution and I found this project really interesting. If this issue is still open then can I work on this?
