### ISSUE TITLE
Button for opening a page in new window is not visible in dark mode

### ISSUE THREAD

**Issue by hirentimbadiya** [layer5io/layer5#4141]
### Description

go to https://layer5.io/learn/service-mesh-labs and turn on dark mode the button which is at the top right corner of the each card is not visible when user hovers it in dark mode.

### Expected Behavior

That button should change its color like it changes it in light mode.

### Screenshots

https://user-images.githubusercontent.com/86219935/234333196-091b1101-1536-4668-bc17-2756a002fb14.mp4

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by umer-not-umer** [comment]
@hirentimbadiya  hello i am new to open source never done it before i just forked the layer5 to my account but can you guide me please what to do next so that i can also contribute i know basics of git and github but never worked with any projects i have only practiced git and github on my local machine such as adding files deleting and modifying guide me please

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya hello i am new to open source never done it before i just forked the layer5 to my account but can you guide me please what to do next so that i can also contribute i know basics of git and github but never worked with any projects i have only practiced git and github on my local machine such as adding files deleting and modifying guide me please

please go through at contributing.md and readme.md files and look for some good first issues and also you can join slack for further doubtes solving over there.

**Comment by umer-not-umer** [comment]
@hirentimbadiya Thank you so much

**Comment by kotkaravishkar** [comment]
@hirentimbadiya   I would like to work on this, can you please assign this to me.

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya I would like to work on this, can you please assign this to me.

i'm already working on this. look for other issues in community ;)
