### ISSUE TITLE
Partner svg's not visible in dark/light mode

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4146]
### Description

On https://layer5.io/partners page ,some svg's aren't visible in light/dark mode. 
Below are the ss of svg's having issues : 

On Dark-mode : 

![image](https://user-images.githubusercontent.com/114604338/234584304-beef6a4a-5b9e-4d27-8385-9aaa9f4df762.png)

![image](https://user-images.githubusercontent.com/114604338/234584437-cec4b189-ca7e-4795-b340-8a62323701b1.png)

![image](https://user-images.githubusercontent.com/114604338/234584564-2ec98d3d-10f8-4db7-b85c-05c065dd7a86.png)

On Light mode : 

![image](https://user-images.githubusercontent.com/114604338/234585891-82162ec3-d17d-4ed7-b155-4569833e4273.png)

![image](https://user-images.githubusercontent.com/114604338/234584845-5265412b-b2eb-4de2-bf14-403aa95f9b0c.png)

![image](https://user-images.githubusercontent.com/114604338/234585167-7b0a4d6e-f3a4-479d-8478-a6e960b7e296.png)

![image](https://user-images.githubusercontent.com/114604338/234585307-2a04c1c2-adbc-4d76-b104-35818324eb5d.png)

![image](https://user-images.githubusercontent.com/114604338/234585423-7f93aa34-855b-47ed-8538-60886f009e62.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by niranjan-kurhade** [comment]
Can I work on this issue?

**Comment by randychilau** [comment]
Hi @niranjan-kurhade,

Thanks for working on this issue. 

I worked on the SVGs on this partner page, and I made the mistake that is causing the problem.

if you are still actively troubleshooting this issue and do not mind me providing a hint:

>I would say the cause of the issue is in this [file](https://github.com/layer5io/layer5/blob/master/src/sections/Partners/partner.style.js) and it is a syntax error regarding the SVGs.

Feel free to let me know if you have any questions, would like another hint, or if I can be of any assistance on this issue.

Cheers,
Randy

**Comment by randychilau** [comment]
Hi @niranjan-kurhade,

Thanks for your reply.

Sounds good. Let me know if I can help with issues setting up locally. I have issues with setups and it can be challenging/frustrating when things do not go according to the instructions.

One thing mentioned in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#how-to-contribute) to note is:
![image](https://user-images.githubusercontent.com/90356410/236260604-bd95598b-3a18-4fd1-9c73-b16b9db9b5f6.png)
>Cloning the repo with all its history results in a ~6 GB download. If you don't need the whole history you can use the depth parameter to significantly reduce download size.

There are also various ways to ask questions to the community about getting setup as noted in the [Newcomer's guide](https://layer5.io/community/newcomers):
>If you need some additional help, please join Layer5 [discussion forum](https://discuss.layer5.io/) or find your way to the [#newcomers](https://slack.layer5.io/) channel in our Slack workspace. Introduce yourself and ask questions.

As you can see this topic is discussed on both:
![image](https://user-images.githubusercontent.com/90356410/236284969-03fdb143-f7eb-4c14-b399-601d41572daf.png)
![image](https://user-images.githubusercontent.com/90356410/236285431-d46fbe86-93f3-4a5a-b08c-fc62a521598e.png)

Good luck on the setup.

Cheers,
Randy

**Comment by niranjan-kurhade** [comment]
Thanks, Randy for your help, 
I had already set up the project locally a few weeks back using --depth=1, that time it worked but now it isn't working.
Also tried using my fork,
Using WSL,
and even Github Codespaces.
Now all the methods give me the same error - running gatsby-plugin-sharp.image_processing 99%.
Is there any other way remaining? 😅.
I'll again go through the discussion forum if I can find anything or I'll put a message on Slack.

**Comment by goldfishdolphin** [comment]
It stops at sharp.image_processing for a long time when you run it first time.

**Comment by randychilau** [comment]
Hi @niranjan-kurhade,

Sorry about the delay in responding.

Sounds like you have done a good job trying various methods. 

I just tried the Codespaces route and with the `npm run build`, it gets killed during the image processing:
![image](https://github.com/layer5io/layer5/assets/90356410/d77ff302-705a-4eec-a99d-84b38079a5d1)

If there are still issues and you are interested in troubleshooting this with me, let's start from the beginning and try to get some additional information.

If possible I would delete your local layer5 repo and start from the beginning again with the basic instructions:

1. Go to your terminal
2. run command:  `git clone --depth=1 https://github.com/layer5io/layer5.git`
3. after it is finished downloading, navigate to the project directory: `cd layer5`
4. run command: `npm install`
5. after it is finished installing, run command: `DEBUG=gatsby:gatsby-plugin-sharp npm run build`

this will [give some info](https://github.com/gatsbyjs/gatsby/issues/34051#issuecomment-1077425897) on what image things get stalled on, example:

![image](https://github.com/layer5io/layer5/assets/90356410/ad3f026a-d4ae-4f72-b9d7-19e1b9427073)

It seems from some of the threads reporting this issue [[1](https://github.com/gatsbyjs/gatsby/issues/34051), [2](https://github.com/gatsbyjs/gatsby/issues/34051#issuecomment-1228283971)], the operation requires a lot of processing, there may be some fixes in the posts you can try. 

note: my machine specs are basic and I have been able to successfully run Layer5 builds)
![image](https://github.com/layer5io/layer5/assets/90356410/3c85035d-7ade-425c-af0c-4c148e3202cf)

Let me know how it goes, and we can go from there.

Cheers,
Randy

**Comment by niranjan-kurhade** [comment]
Hey Randy, Thanks for your response! I'll try and inform you about it.

**Comment by vishalvivekm** [comment]
What's the update on this @niranjan-kurhade ?
let's not put off addressing this issue any longer.

**Comment by niranjan-kurhade** [comment]
> What's the update on this @niranjan-kurhade ? let's not put off addressing this issue any longer.

You can work on this issue for now, I am unassigning myself, Trying to setup Layer5

**Comment by vishalvivekm** [comment]
https://github.com/layer5io/layer5/issues/4222#issuecomment-1545806224
@sambhavgupta0705 assigning this to you. 
Some great comments by @randychilau above

**Comment by goldfishdolphin** [comment]
If no one is working, can you please assign me this issue.

**Comment by sambhavgupta0705** [comment]
Ok @vishalvivekm 
If @goldfishdolphin finds any difficulty then I can help

**Comment by randychilau** [comment]
Hi All,

@vishalvivekm, thanks for coordinating everything!

@goldfishdolphin, as I mentioned [earlier in this thread](#issuecomment-1534157592) I am available as a resource if you have any questions regarding this issue.

@niranjan-kurhade, after [Codespaces](https://github.com/features/codespaces) didn't work out, I tried another CDE, [GitPod](https://gitpod.io) and was able to successfully install, develop, and build with my Layer5 fork online using the free basic settings. So you might consider giving that a try, let me know if you have any questions.

![image](https://github.com/layer5io/layer5/assets/90356410/b6a8ccf8-685c-4477-8803-bf383f690187)


![image](https://github.com/layer5io/layer5/assets/90356410/3a299156-b373-4de7-89b5-4f385c53779e)

cheers,
Randy

**Comment by goldfishdolphin** [comment]
Thanks Randy. I usually run code on my local machine but I ll try Gitpod as well.

**Comment by goldfishdolphin** [comment]
Hi @randychilau I tried to make a separate ReactComponent for dark mode CNFC but it is not being displayed.
On this page dark and light mode images are the same. Is there any other way to approach it?

**Comment by sambhavgupta0705** [comment]
Hey @leecalcote I think only cncf logo is fixed 
There were other logos also so we need to reopen this issue

**Comment by randychilau** [comment]
HI Everyone,

Thanks for looking into this issue @goldfishdolphin.

You mentioned:
>On this page dark and light mode images are the same. Is there any other way to approach it?


As you noticed, we are using one SVG file per partner on this page for light and dark mode, this is intentional because we want the SVG to respond to the theme changing between light and dark mode.

This is documented in the [`Changing SVG according to theme`](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#changing-svg-according-to-theme) section of CONTRIBUTING.md.

However there is a syntax error that is preventing the SVG colors from changing on this page. The code responsible for the changing colors is located in [this file](https://github.com/layer5io/layer5/blob/master/src/sections/Partners/partner.style.js), more specifically in this section:

![image](https://github.com/layer5io/layer5/assets/90356410/f002fc28-3188-434f-90f5-f3be510c6d52)

Unfortunately I missed this error when modifying the code, but there is a css syntax error in the section above. Click on `Reveal Error` below to see the issue:

<details>
  <summary>Reveal Error</summary>
  
[CSS syntax states](https://www.w3schools.com/css/css_syntax.asp#:~:text=The%20declaration%20block%20contains%20one,are%20surrounded%20by%20curly%20braces.):
>Multiple CSS declarations are separated with semicolons

There is a missing semi-colon after the `fill` properties:
![image](https://github.com/layer5io/layer5/assets/90356410/ced2ea78-ce8f-4822-b63b-c0bdfa9be323)
  
</details>
 

If you correct the error in both instances and `npm start`, the SVGs on the page will change correctly.

[svg.webm](https://github.com/layer5io/layer5/assets/90356410/3e8c065c-0c82-4f40-9644-d93d35940064)


@leecalcote has merged [PR#4249](https://github.com/layer5io/layer5/pull/4249) and closed this issue, and as @sambhavgupta0705 has commented there are other partner SVGs malfunctioning. I will leave it to the organizers to decide how best to proceed.

@sambhavgupta0705 If you are interested in other issues with this page, here are two more:

1. the Citrix SVG is not responsive (I missed converting this SVG when I worked on this page), so the SVG needs to be modified and added in the same way as the other partners.
2. If you notice in the video above, the partner headings are changing colors faster than the rest of the page, this needs to be fixed so that the color changes in sync with the rest of the page for smooth uniform transition.

Otherwise I am happy to handle the above issues if they are not taken up in the next few days.

Cheers,
Randy

**Comment by sambhavgupta0705** [comment]
Hey @randychilau 
I see that there are many errors on this page and I would like to resolve it .
I need to see how the svg changes with the change in theme.

**Comment by goldfishdolphin** [comment]
Thank you @randychilau for explaining everything so well.

**Comment by sambhavgupta0705** [comment]
@randychilau should I make a new issue with all details or this issue should be reopened?

**Comment by randychilau** [comment]
Hi @sambhavgupta0705,

Thanks for your interest in working on this page.

Let's split up the tasks.

You handle the task regarding:
>The partner headings are changing colors faster than the rest of the page, this needs to be fixed so that the color changes in sync with the rest of the page for smooth uniform transition.

Please create a new issue for this, and I believe I can assign you the task.

I'll handle the Citrix SVG and the CSS issue for the other partner SVGs.

Thanks,
Randy

**Comment by goldfishdolphin** [comment]
@randychilau have you fixed the CSS for the partners page?

**Comment by randychilau** [comment]
Hi @goldfishdolphin,

Thanks for your message. 

The issues on the partner page regarding other svgs and light/dark mode have been resolved in PR #4296  and awaiting review.

Cheers,
Randy
