### ISSUE TITLE
Clearing of search bar upon changing search result view from list to grid.

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4148]
### Description
When performing a search on the blog, the search results are displayed in a grid view by default. However, when the user changes the view to list, the search bar is cleared, and any text that was previously entered in the search bar disappears. It would be more intuitive and user-friendly to maintain the searched text even if the user switches between the list and grid view.

Link : https://layer5.io/blog

### Expected Behavior
The searched text should not disappear if you change the view.

### Screenshots
https://user-images.githubusercontent.com/91362589/234633337-f7af795b-5ca5-4b5f-bfec-4e34b67407e5.mp4

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by niranjan-kurhade** [comment]
I would like to work on this issue. Please assign it to me

**Comment by probiruk** [comment]
@Savio629 I have fixed the issue and created a PR for it https://github.com/layer5io/layer5/pull/4168

**Comment by Savio629** [comment]
@akash1412 @probiruk  Fair warning - Next time please wait for the issue to get assigned before making a PR.
Also we follow FCFS(First come first serve) rule.
@Chadha93 @leecalcote

**Comment by probiruk** [comment]
@Savio629 Okay got it sorry

**Comment by Yash-Var** [comment]
@Savio629 I want to contribute to this issue .....

**Comment by Savio629** [comment]
@Yash-Var The pr for this is already made.
You can work on some other issues.

**Comment by Savio629** [comment]
@Shivam-AfA @thisiskaransgit @vishalvivekm 
Can you guys review the pr?
The fix for this issue is made long time ago...

**Comment by vishalvivekm** [comment]
> @Shivam-AfA @thisiskaransgit @vishalvivekm 
> Can you guys review the pr?
> The fix for this issue is made long time ago...

@Savio629 Let's discuss it on websites call. Please add this as an agenda item in the meeting minutes.

**Comment by AkashS20** [comment]
I will be taking up this issue

**Comment by Shivam-AfA** [comment]
@AkashS20 Do consider the feedbacks provided on the previous PR.

**Comment by vishalvivekm** [comment]
> I will be taking up this issue

🚀 @AkashS20 .
There are a couple of suggestions from Nikhil on the Linked Prs.

**Comment by vishalvivekm** [comment]
Oh thanks @Shivam-AfA already covered it.

**Comment by AkashS20** [comment]
@vishalvivekm I will have a look at them, Thanks 👍
