### ISSUE TITLE
[Landscape] Add Nighthawk to list of load generators in Service Mesh Landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#415]
**Current State:**
Nighthawk is a L7 (HTTP/HTTPS/HTTP2) performance characterization tool.

**Desired State:**
Nighthawk should be included in the service mesh landscape under the [tools section](https://layer5.io/landscape#tools).

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)

**Comment by leecalcote** [comment]
@mum4k thanks for considering getting Nighthawk represented [here](https://layer5.io/landscape#tools). We encourage representatives of the projects/products in the landscape to [curate and maintain](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape) their listings so as to guarantee their freshness and accuracy of representation.

// @kushthedude @DavidCPorter

**Comment by mum4k** [comment]
Thanks for reaching out, I will on on vacation for a few days, so will get in touch sometime in the next two weeks.
