### ISSUE TITLE
[Create] Meshery Catalog page 

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4150]
### Current Behavior

A new page describing Meshery Catalog should be created under Projects. Currently the `Catalog` link in the navbar Project/ leads to the catalog page on the meshery website but now it should link to a seperate new catalog page hosted on layer5 website itself.

There's a section on Catalog on https://layer5.io/cloud-native-management/meshmap page which can be used for reference
### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Or just a section on a page covering the Catalog and its function.

**Comment by senali-d** [comment]
@leecalcote I would like to work on this issue.

**Comment by goldfishdolphin** [comment]
@senali-d I have used this two tone [catalog-icon.zip](https://github.com/layer5io/layer5/files/11461862/catalog-icon.zip) for catalog card. 
It may help you.
