### ISSUE TITLE
[Create] New project card for catalog

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4152]
### Current Behavior

On https://layer5.io/projects a new project card for `Catalog` needs to be created. This card will link to the new page created under issue #4150 .

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by goldfishdolphin** [comment]
I want to work on this issue.

**Comment by leecalcote** [comment]
@goldfishdolphin good deal. If you haven't built this site, yet, here are some quick tips:

1. use a git clone depth of 1 (see command in Contributing.md)
2. `make setup; make site` should be all that you need to build the site.
3

**Comment by leecalcote** [comment]
@senali-d FYI
