### ISSUE TITLE
[Create] New project card for Playground

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4153]
### Current Behavior

On https://layer5.io/projects a new project card for Playground needs to be created. This card will link to the new page created under issue #4151  .
### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by EdwinDij** [comment]
Hello for card have a mockup or we just add it in your design?

**Comment by ayushthe1** [comment]
@ritiksaxena124 Can you please help here.

**Comment by ritiksaxena124** [comment]
Ahh, I missed this, @EdwinDij you can use the meshery logo for the meshery playground with the title "Meshery Playground" and create a card as we have for other projects in the grid.
Link that card to layer5.io/cloud-native-management/playground [ currently this page is in progress ]

**Comment by EdwinDij** [comment]
@ritiksaxena124  No prob, ok now i understand can get. this issue please

**Comment by ritiksaxena124** [comment]
I have assigned it to you @EdwinDij, if you get any problems jump into our [slack channel](https://slack.layer5.io/) and ask your queries.

**Comment by EdwinDij** [comment]
I did my pr

**Comment by Savio629** [comment]
@EdwinDij Any reason for closing your pr #4207 ?

**Comment by EdwinDij** [comment]
No? I thought it was some of you. I really don't know how to close a pr by myself.

**Comment by Savio629** [comment]
You can check on the pr #4207 
Maybe you might have accidently deleted the branch or local repo...
Do you still want to work on this issue?

**Comment by EdwinDij** [comment]
Yes I want 💪🏾
