### ISSUE TITLE
enhance the learn-card section

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4154]
### Current Behavior

The learn-card section on https://layer5.io/learn page can be enhanced a bit to look better.

### Screenshots / Mockups

This is how it looks currently : 
![image](https://user-images.githubusercontent.com/114604338/234672039-3414595a-c35e-4ac2-8253-d9e75304c61e.png)

### Example suggestion : 

[Screencast from 27-04-23 12:12:29 AM IST.webm](https://user-images.githubusercontent.com/114604338/234672718-35e914d0-9514-40ef-9ea4-9862b06601f9.webm)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by TiwariAshuism** [comment]
I want to work on this 🙂

**Comment by Akhil2707** [comment]
i would like to work on this issue

**Comment by ayushthe1** [comment]
assigned to you @Akhil2707 :+1:

**Comment by 8rxn** [comment]
Hey  @Akhil2707, Have you worked on this?
If not, I would like to work on this issue.

**Comment by Nikhil-Ladha** [comment]
I don't see any need to improve this design. We don't want all the boxes on the site to like similar cards. I am closing out this issue, sorry for the trouble @8rxn but appreciate your contribution here. Please jump into other open/stale issues but please confirm any such design change issues by tagging me or Lee before starting to work on it.
