### ISSUE TITLE
Change the text color 

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4159]
### Description

on https://layer5.io/company/about the color of text in a section is black. It should be changed to white
### Screenshots

![image](https://user-images.githubusercontent.com/114604338/235108329-6bbe47af-8c64-4846-9dfd-ff7200b558e1.png)

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Mohith234** [comment]
I would like to work on this. Could you assign it to me ?

**Comment by vishalsingh2972** [comment]
hey @ayushthe1 can you assign this to me if it's still open?

**Comment by Anurag8305** [comment]
hey, @ayushthe1  I am looking for my first open-source contribution and I found this project really interesting. If this issue is still open then can I work on this?
