### ISSUE TITLE
Add Padding between buttons on Image Hub website for Mobile Devices

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4183]
### Description
Add Padding between buttons on Image Hub website for Mobile Devices
https://layer5.io/projects/image-hub

### Screenshots
![test1](https://user-images.githubusercontent.com/91362589/236031080-960becfc-4384-42e5-a75d-997b36a4996f.PNG)

### Environment:
- Host OS: Android 
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shibu-g** [comment]
anyone working on this issue or i can start working on this?

**Comment by hirentimbadiya** [comment]
> anyone working on this issue or i can start working on this?

Go on
