### ISSUE TITLE
Fix text alignment and font size of Image Hub on mobile devices

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4185]
### Description
Fix text alignment and font size of Image Hub on mobile devices

### Expected Behavior
The text alignment and font size of Image Hub should look appropriate for mobile devices

### Screenshots
![7c9fa653-1769-4119-bb26-8ae2f95bd9db](https://user-images.githubusercontent.com/91362589/236109853-92371831-eb6c-41ed-86ab-d5c4f87acffa.jpg)

### Environment:
- Host OS: Android
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
I'd like to work on this

**Comment by hirentimbadiya** [comment]
> I'd like to work on this

All yours.

**Comment by sambhavgupta0705** [comment]
Hey,if it is still open then I would like to work on this one.

**Comment by Saksham294** [comment]
@vishalvivekm I've raised a PR, kindly check. Thanks
