### ISSUE TITLE
Banner image not responsive on mobile devices

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4186]
### Description
Banner image not responsive on mobile devices

### Expected Behavior
Banner image should be responsive on mobile devices

### Screenshots
![448237c7-b5d4-43f4-afbc-012f70478500](https://user-images.githubusercontent.com/91362589/236131010-9fe2af33-b63f-49ed-8181-c2265e4003b6.jpg)

### Environment:
- Host OS: Android
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AkashS20** [comment]
I'd like to work on this issue
