### ISSUE TITLE
Overlap of slide button on meshmap page for mobile devices

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4187]
### Description
Overlap of slide button on meshmap page for mobile devices.
Link: https://layer5.io/cloud-native-management/meshmap

### Expected Behavior
The slide icon shouldn't overlap instead have some padding below it.

### Screenshots
![meshmapissue](https://user-images.githubusercontent.com/91362589/236134092-99586081-ac41-4dd7-a114-fa0057f523d3.PNG)

### Environment:
- Host OS: Android 
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
I'd like to work on this

**Comment by Saksham294** [comment]
@Savio629 I have raised a PR, kindly check. Thanks!
