### ISSUE TITLE
 SVG disappears on smaller screens

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4191]
### Description
When the screen size is reduced, the SVG image disappears and becomes 0x0 in size. This issue occurs because the SVG element is not properly responsive to smaller screen sizes. 
Link : https://layer5.io/cloud-native-management/meshmap/collaborate

### Expected Behavior
The svg should be visible for smaller devices 
### Screenshots

https://user-images.githubusercontent.com/91362589/236462940-32e5bc22-233a-47a0-9bc2-ec89f4e498a0.mp4

### Environment:
- Host OS: Windows/Android
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by aku1310** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by ritiksaxena124** [comment]
Hey @aku1310 thanks for taking this up, you can start working on this issue, if you find any difficulty you can join our [slack](https://slack.layer5.io/) channel and ask about your queries
Happy coding 👍

**Comment by shubhankar-shandilya-india** [comment]
Hello Sir, I want to work on this issue. Could you please assign it to me?

**Comment by aku1310** [comment]
Hey @shubhankar-shandilya-india, I've already opened a PR for this issue which has been approved! You could try looking at other unassigned issues available 😄
