### ISSUE TITLE
map is not visible on small screen size 

### ISSUE THREAD

**Issue by singh1475** [layer5io/layer5#4194]
Description
When the screen size is reduced, the map image is not visible on small screen size as it is visible in dark mode

Expected Behavior
The map should be visible for smaller devices

Screenshots

https://user-images.githubusercontent.com/120357888/236596769-a5fadf4e-27c7-4aa7-b023-3b12803adbc0.mp4

Environment:
Host OS: Windows/Android
Browser: Chrome

**Comment by goldfishdolphin** [comment]
Can I work on this please?

**Comment by Savio629** [comment]
@singh1475 I have already opened an issue for the svg visibility on smaller devices.
#4191

**Comment by vishalvivekm** [comment]
@singh1475 
Thanks for opening up the issue, please make sure that similar issues aren't open already from next time.

**Comment by vishalvivekm** [comment]
> @singh1475 I have already opened an issue for the svg visibility on smaller devices. #4191

We can then close this issue :) //  @Savio629

**Comment by singh1475** [comment]
I am sorry for that next time I will make sure that similar issue don't open
