### ISSUE TITLE
[Handbook] Add Meshery Cloud as a backend project (Golang) in Repo Overview

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4199]
### Current Behavior
Meshery Cloud as a project is missing from the backend projects section on https://layer5.io/community/handbook/repository-overview

### Desired Behavior
Create an entry listing Golang as the primary technology.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by 8rxn** [comment]
Hey @leecalcote , 
Can I be assigned to this issue? 
I would like to work on this.

**Comment by leecalcote** [comment]
Thank you, @thisiskaransgit

**Comment by leecalcote** [comment]
@8rxn were you successful here?

**Comment by 8rxn** [comment]
> @8rxn were you successful here?

Hey @leecalcote 
Do I need to continue this?

I think we had a conversation in Slack where you mentioned that it wasn't required anymore as it was covered in another PR.
Although I did point out that it was added as a frontend project instead of a backend one in that same PR.

**Comment by thisiskaransgit** [comment]
@leecalcote @8rxn, the issue has been completed via #4198, meshery cloud has been added as a Backend project in Repo Overview.
So, closing this issue as completed. 

[![Screenshot](https://github-production-user-asset-6210df.s3.amazonaws.com/92504666/239848058-d7af472b-03d1-45d8-8c24-260cf81b01d3.png)](https://layer5.io/community/handbook/repository-overview#Backend%20Projects)
