### ISSUE TITLE
[Chore] Entity Repetition in Quote Section

### ISSUE THREAD

**Issue by VishrutAggarwal** [layer5io/layer5#4200]
### Current Behavior
As discussed in Websites Weekly Meet on May 8, 2023, an entity from the review section has two quotes. This makes it seem as if the quote section has only two quotes and it's repeating.

Link to the page: https://layer5.io/cloud-native-management/meshmap

Image for reference: 
![image](https://user-images.githubusercontent.com/71827366/236834299-bf59b76f-6612-44e7-b6f3-6a51bd6c4951.png)

### Desired Situation
Removing one of the quotes (preferred removal: right one) would prevent the user from assuming that their are just two quotes.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VishrutAggarwal** [comment]
I would like to work on this issue.

I also noticed another Person to have two quotes.

Images for reference:
![image-1](https://user-images.githubusercontent.com/71827366/236835026-70646146-ea43-4743-a491-eae5d1bd3400.png)
![image-2](https://user-images.githubusercontent.com/71827366/236835097-1fb5dec0-64c8-4f2d-b302-c1390a9d28a1.png)

Do I need to remove one of these too? If yes, which one is preferred to be removed?

**Comment by thisiskaransgit** [comment]
closing as completed via #4201
