### ISSUE TITLE
[Community] Member Profile: Senali

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4205]
**Current Behavior**

@senali-d  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @senali-d  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @senali-d 
- Twitter: [senali_d](https://twitter.com/senali_d)
- LinkedIn: [senali-d](https://www.linkedin.com/in/senali-d/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@senali-d :)
Your bio and a link to profile picture, please!

**Comment by kotkaravishkar** [comment]
@vishalvivekm  Can I work on it ?

**Comment by vishalvivekm** [comment]
> @vishalvivekm  Can I work on it ?

Sounds good @kotkaravishkar

**Comment by senali-d** [comment]
[Bio](https://docs.google.com/document/d/1WTxXUfjs9R68FT7HsvNl8W6m_w3Nvle9zq-lF0hBF60/edit?usp=sharing)
[Profile Picture](https://drive.google.com/file/d/17Uy8ZnVQux5viIlKcxBo5UTAcEcM7zt6/view?usp=sharing)

@kotkaravishkar Link to bio and profile picture // @vishalvivekm
