### ISSUE TITLE
[Add] Docker Extension & Meshery Catalog Badge on layer5.io

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#4209]
### Desired Behavior
Two new badges needed to be added to the [layer5.io](https://layer5.io/community/handbook/recognition) website, those are:

**Docker-Extension:**
- **Logo:** https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=13060%3A39569&t=BaXWaMzs5vb6MR88-1
- **Description:** awarded community members who make consistent and impactful contributions to the [Meshery Catalog](https://meshery.io/catalog) project in recognition and appreciation of their efforts.

**Meshery Catalog**
- **Logo:** https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=13060%3A39569&t=BaXWaMzs5vb6MR88-1
- **Description:** awarded community members who make consistent and impactful contributions to the Docker-Extension of meshery project in recognition and appreciation of their efforts.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sambhavgupta0705** [comment]
I would like to work on this issue✋

**Comment by ritiksaxena124** [comment]
Ohh Great @sambhavgupta0705 👍, assigning it to you, and if you find any difficulty feel free to jump into our [slack channel](https://slack.layer5.io/) and ask your queries

**Comment by Deepak-Choudhary0** [comment]
@ritiksaxena124 Can i work on this?

**Comment by leecalcote** [comment]
@sambhavgupta0705 would it be alright if @Deepak-Choudhary0 grabbed the Meshery Docker Extension badge, while you wrangle the Meshery Catalog badge?

**Comment by Deepak-Choudhary0** [comment]
Yeah meshery docker extension svg is there there

**Comment by ritiksaxena124** [comment]
[meshery-catalog and docker-extension logo.zip](https://github.com/layer5io/layer5/files/11449208/meshery-catalog.and.docker-extension.logo.zip)
In this file you can get logos of meshery-catalog and docker-extension that you can use

**Comment by sambhavgupta0705** [comment]
yeahh @leecalcote for sure

**Comment by sambhavgupta0705** [comment]
>@sambhavgupta0705 would it be alright if @Deepak-Choudhary0 grabbed the Meshery Docker Extension badge, while you wrangle the Meshery Catalog badge?

yeahh @leecalcote for sure
