### ISSUE TITLE
Meshery operator feature isnt visible

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4218]
### Description

When using phone , the meshery operator feature on [this](https://layer5.io/cloud-native-management/meshery) page isnt properly visible .

### Expected Behavior

The image should be intact and the feature should be visible
![image](https://github.com/layer5io/layer5/assets/59855919/457addee-5a50-425b-b486-fe724c1071af)

### Screenshots

Current behaviour
![image](https://github.com/layer5io/layer5/assets/59855919/4d1daab0-2d99-45b0-a9ce-12d0a488b9ff)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks for filing this, @Ghat0tkach. Would you like to work on it, too?

**Comment by Ghat0tkach** [comment]
Yup sure

**Comment by vishalvivekm** [comment]
> @leecalcote Yup sure

Thanks @Ghat0tkach, Go ahead!

**Comment by Ghat0tkach** [comment]
@vishalvivekm 
![image](https://github.com/layer5io/layer5/assets/59855919/2e302f8f-56a5-49fe-9311-461b2d23c046)

**Comment by Ghat0tkach** [comment]
@vishalvivekm could you please help?

**Comment by vishalvivekm** [comment]
@Ghat0tkach 
Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)

Yup sure , thanks a lot @vishalvivekm

**Comment by Ghat0tkach** [comment]
@leecalcote @vishalvivekm  as i am unable to set up this repo in my system and the issue is a beginner friendly , i would like that you assign this request to someone else . Its already been 6 days 😅😊

**Comment by leecalcote** [comment]
Thank you for sending word, @Ghat0tkach. This is much appreciated.
