### ISSUE TITLE
[bug] Update `Get The Book` buttons

### ISSUE THREAD

**Issue by theBeginner86** [layer5io/layer5#4219]
### Description

[layer5.io](https://layer5.io) houses large set of resources for end-users and community members to learn and explore infrastructure skills. One of which is an e-book "**The Enterprise Path to Service Mesh Architectures (2nd Edition)**" available at https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition.
But the link to the book has been recently updated by the publisher due to which `Get The Book` button is not taking users to the right page.

### Expected Behavior

Please update the button `Get The Book` to first class `Sign Up` form, like available at other areas of website.
Should include following form fields:
1. First name
2. Last Name
3. Email
4. Occupation
5. Organization
6. Role

### Screenshots

Refer following forms for reference:
1. https://layer5.io/cloud-native-management/meshmap
2. https://play.meshery.io
3. https://layer5.io/docker-extension-meshery

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Deepak-Choudhary0** [comment]
Can you assign this to me?

**Comment by vishalvivekm** [comment]
> Can you assign this to me?

There you go @Deepak-Choudhary0

**Comment by leecalcote** [comment]
@Deepak-Choudhary0 let's have a PR up and demo for Monday's Websites meeting. If you're not able to meet this timeframe, then let's unassign here and get you onto a different issue. Deal?

**Comment by Deepak-Choudhary0** [comment]
Yeah okay for me

**Comment by ChiragDogra** [comment]
So @theBeginner86 you want to say that the `get the book` button should take us to a dedicated page that contains a sign up form, something like following? Am I getting it right?

![Screenshot from 2023-05-13 21-13-35](https://github.com/layer5io/layer5/assets/78541994/52606b2e-5f8c-48bb-bf59-ba6c390efb60)

**Comment by vishalvivekm** [comment]
@Deepak-Choudhary0 
A PR before the websites meeting today ? 
Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :). // @ChiragDogra

**Comment by vishalvivekm** [comment]
what's the status here ? @Deepak-Choudhary0

**Comment by pseudofool** [comment]
I want to work on this issue. Please assign it to me.

**Comment by Savio629** [comment]
Completed via #4433
