### ISSUE TITLE
[News] Vendors make a splash in 2019 service mesh implementation rush

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#422]
**Current State:**
An article on Meshery was published - https://searchapparchitecture.techtarget.com/feature/Vendors-make-a-splash-in-2019-service-mesh-implementation-rush

**Desired State:**
The __Vendors make a splash in 2019 service mesh implementation rush__ article should be listed in the /news section.

---
**Contributor Resources**
- [Instructions for adding news items](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news)

**Comment by leecalcote** [comment]
@Vineet-Sharma29 Would you like to take this one?

**Comment by Vineet-Sharma29** [comment]
Would work on it
