### ISSUE TITLE
Partner Images

### ISSUE THREAD

**Issue by HetviSoni** [layer5io/layer5#4222]
### Description
On the https://layer5.io/partners page, images of Hashicorp,  HPE, and VMWare are not visible. There is a link to https://www.hashicorp.com/partners/tech/layer5 at Hashicorp image but may be incorrect.
<img width="960" alt="image" src="https://github.com/layer5io/layer5/assets/76479104/8ef2d38a-43f4-460e-9a4f-f9c020af63ed">

### Expected Behavior
Correct links need to be added

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by HetviSoni** [comment]
> Yes, they are not visible for light mode I would like to work on this issue and fix it

ya u are correct. Images are fine in dark mode but invisible in light.

**Comment by vishalvivekm** [comment]
Thanks @HetviSoni for pointing it out. 
Also, in the dark mode, the partners' names ("Microsoft", "Service Mesh Interface", "Cloud Native Computing Foundation (CNCF)") aren't quite visible 
![Screenshot from 2023-05-12 18-48-00](https://github.com/layer5io/layer5/assets/110674407/de8ea7f0-7133-4c7b-97f3-eb51840de105)

Will you see to it that these svgs support both light as well as dark mode? Who'd take up the issue? // @sambhavgupta0705 @HetviSoni

**Comment by HetviSoni** [comment]
> Thanks @HetviSoni for pointing it out. Also, in the dark mode, the partners' names ("Microsoft", "Service Mesh Interface", "Cloud Native Computing Foundation (CNCF)") aren't quite visible ![Screenshot from 2023-05-12 18-48-00](https://user-images.githubusercontent.com/110674407/237982206-de8ea7f0-7133-4c7b-97f3-eb51840de105.png)
> 
> Will you see to it that these svgs support both light as well as dark mode? Who'd take up the issue? // @sambhavgupta0705 @HetviSoni

Let @sambhavgupta0705 take this up as he asked first ☺️

**Comment by sambhavgupta0705** [comment]
ok @HetviSoni I will take this up

**Comment by vishalvivekm** [comment]
Sounds good.

**Comment by randychilau** [comment]
Hi Everyone, 

It is great that so many folks want to help. 

Organizers please note that this is a duplicate issue to the previously posted [Issue #4146](https://github.com/layer5io/layer5/issues/4146), and now there are multiple assignees for the same task. Please provide guidance on how to proceed.

Thanks,
Randy

**Comment by HetviSoni** [comment]
I am sorry I did not notice that a similar issue was already opened. Should I close this one?

**Comment by randychilau** [comment]
HI @HetviSoni,

No worries, I only mention this because I am assisting in the other thread with trying to help troubleshoot a local setup.

Happy with whatever the Organizers decide is best.

Cheers,
Randy

**Comment by vishalvivekm** [comment]
Oh, thanks @randychilau 

@HetviSoni To ensure we don't create duplicate issues, please search the existing issues before opening a new one.
For now, this issue can be closed. // @HetviSoni

**Comment by HetviSoni** [comment]
Will keep that in mind👍Sorry for the inconvenience.
