### ISSUE TITLE
[Docs] Add Catalog project description to Layer5 ReadMe file.

### ISSUE THREAD

**Issue by goldfishdolphin** [layer5io/layer5#4224]
### Current Behavior

Currently there is no description of the Catalog project on the Layer5  ReadMe file.

### Desired Situation

We need a breif summary of the Catalog Project along with the link to the project page and logo. 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vishalvivekm** [comment]
Thanks for opening up the issue Naureen : 🚀

**Comment by goldfishdolphin** [comment]
@leecalcote and @vishalvivekm Is there any description of the catalog that I can use?

**Comment by vishalvivekm** [comment]
@goldfishdolphin 
Let's discuss this on websites call. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#), if you would :)
