### ISSUE TITLE
[Docs] readme and contributing.md 

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4225]
### Current Behavior
To set the repo on the local system , the contributing.md is available on the issue template . however it is not present in the readme file under contributing section. This could be confusing for beginners who are trying to set up the repo on the local system to explore or test it.We could resolve this by simply stating the link to contributing.md .

Secondly in the setting up the repo , i found something strange 
## 

![image](https://github.com/layer5io/layer5/assets/59855919/69612e20-41d1-43ec-a438-139d73ff9349)

### Desired Situation

here it was written to clone the forked repo but the commands were of cloning the current layers repo itself.
a user has already forked the Layer5 project repository, they should clone their forked repository instead of the original repository.

To clone a forked repository, the user should replace layer5io in the git clone command with their own GitHub username. For example, if the user's GitHub username is luser and they have forked the Layer5 project repository, the correct git clone command would be:
git clone --depth=1 https://github.com/luser/layer5.git

## And one more , i dont know whether its a bug or
I discovered one of the things on [this](https://layer5.io/community/newcomers)
all the  presenters are being highlighted through their commuity profile except this one,
![image](https://github.com/layer5io/layer5/assets/59855919/7a09b8c3-4026-4add-8041-74e9198ea4e3)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment]
if the issue is valid , i would like to contribute😅
@leecalcote @vishalvivekm

**Comment by leecalcote** [comment]
The first two items mentioned are issues that are good to work on. The third item is intentional.

**Comment by leecalcote** [comment]
Thanks for documenting these, @Ghat0tkach
