### ISSUE TITLE
[Meshmap] Overlapping found between two elements

### ISSUE THREAD

**Issue by VishrutAggarwal** [layer5io/layer5#4231]
### Description

I found this issue on https://layer5.io/cloud-native-management/meshmap.
The elements are overlapping over each other in mobile mode. This is an issue in responsive design.

### Expected Behavior

Different elements should be separate and not overlap other elements. This also creates a seamless experience on clicking on different buttons.

### Screenshots

![image](https://github.com/layer5io/layer5/assets/71827366/d6d7fef9-97cd-4460-94a4-3ce159e560d9)

### Environment:
- Host OS: Android
- Browser: Google Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VishrutAggarwal** [comment]
I would like to work on this myself.
Can this issue be assigned to me?

**Comment by leecalcote** [comment]
Thanks for filing this issue, @VishrutAggarwal 👍

**Comment by Nikhil-Ladha** [comment]
It is a duplicate issue #4187 , and was recently fixed by a different PR.
Please cross check before filling an issue to avoid duplicate efforts :)
