### ISSUE TITLE
[Docs]Update PR template

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4233]
### Current Behavior

As i was drafting a PR , i found the basic comments missing from the template which can create confusion.
![image](https://github.com/layer5io/layer5/assets/59855919/2f94ae7b-8d8b-4321-abc4-8d264f369de8)

### Desired Situation

basic comments about adding check-marks in the signed-commits and writing about issue number can be added 
![image](https://github.com/layer5io/layer5/assets/59855919/b373bad2-9b94-4550-9027-555bec00a694)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by tanbirali** [comment]
I will like to work on this issue.
