### ISSUE TITLE
In the footer, issue related GitHub logo

### ISSUE THREAD

**Issue by Dnyaneshvn** [layer5io/layer5#4235]
### Current Behavior

While the cursor goes through the GitHub logo then it's turned black, due to which the logo gets invisible.
### Desired Behavior

That logo needs to be turned into contrasting colour or should be visible while moving the cursor over there.
### Implementation

https://github.com/layer5io/layer5/assets/78072155/de10725d-d880-4a6c-8cc2-70169078a4e3

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by 8rxn** [comment]
Hey @Shivam-AfA,
I want to fix this issue.

**Comment by Shivam-AfA** [comment]
@8rxn @Dnyaneshvn This is only happening for discuss.layer5.io and not layer5.io, right?

**Comment by 8rxn** [comment]
> @8rxn @Dnyaneshvn This is only happening for discuss.layer5.io and not layer5.io, right?

Yes.

**Comment by Dnyaneshvn** [comment]
Yes! @Shivam-AfA

**Comment by Dnyaneshvn** [comment]
I'd like to fix this
