### ISSUE TITLE
[Resources] Text visibility affected by image

### ISSUE THREAD

**Issue by aku1310** [layer5io/layer5#4237]
### Description

I found this issue here: https://layer5.io/resources.
The text is getting mixed with the quotes image which affects its visibility. 

### Expected Behavior

There can be 2 ways to fix this:
1. Changing the color of the affected text, and/or
2. Changing the position of the quotes image

### Screenshots

Dark Mode:
![image](https://github.com/layer5io/layer5/assets/72210364/f0a0e1c7-5ed7-4ab7-a24e-5668711a8253)

Light Mode:
![image](https://github.com/layer5io/layer5/assets/72210364/184fbe28-ff83-4871-a0c2-9d2aae1bc820)

### Environment:
- Host OS: Windows
- Browser: Google Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by aku1310** [comment]
I would like to work on this issue. Could it please be assigned to me?

If there are any other suggestions to improve the text visibility, please let me know.

**Comment by ChiragDogra** [comment]
hi @aku1310, a small suggestion, maybe changing the opacity of the image(quotes) will be a better option. You can simply increase the opacity of the image to 2 and it works.

**Comment by aku1310** [comment]
> hi @aku1310, a small suggestion, maybe changing the opacity of the image(quotes) will be a better option. You can simply increase the opacity of the image to 2 and it works.

Yes, that'll work well too. Thanks for the suggestion!
I wanted to confirm with the maintainers if we can change the position of the quotes image or not, and if it would make the UI better.

**Comment by shirsho-roy** [comment]
I do want to work on this , can I be assigned this issue?

**Comment by hirentimbadiya** [comment]
going with FCFS wise , @aku1310 you can start working on this issue.
