### ISSUE TITLE
[Readme] Add MeshMap project entry

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4242]
### Current Behavior
This repository's readme.md has a list of Layer5' projects. Currently, this list is missing an entry for MeshMap (https://layer5.io/meshmap).

### Desired Behavior
Readme.md has an entry for MeshMap.

### Implementation
1. Use MeshMap logos from src/assets/images/meshmap
2. Use SVGs not PNGs.
3. Support both light and dark modes image versions.
4. Follow aa similar format as to the existing project entries.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Meyazhagan** [comment]
@leecalcote Shall I work on this?

**Comment by Meyazhagan** [comment]
@leecalcote do you have any short description for meshmap ?
