### ISSUE TITLE
Private Repository link in repository-overview/frontend-project

### ISSUE THREAD

**Issue by sayyedarib** [layer5io/layer5#4250]
### Current Behavior
a private repo is added in the frontend projects, when user clicks on it , he/she couldn't access 
![1](https://github.com/layer5io/layer5/assets/90370535/9301518e-8856-43d4-bc2c-571c96c6fd45)
![2](https://github.com/layer5io/layer5/assets/90370535/6db0a3ae-a248-4fe1-b84f-20f6e2737004)

### Desired Situation

- [x] add some label to that repo to indicate that it's a private repo and needs permission

**Comment by sudhanshutech** [comment]
good eye @sayyedarib , here you go

**Comment by ranjanmangla1** [comment]
if this issue is open and nobody is working on it, please assign me this issue.

**Comment by sayyedarib** [comment]
@thisiskaransgit I think it's this issue is resolved , you can review the file changes in the PR
