### ISSUE TITLE
[Community] Member Profile: Vivek Jha

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4254]
**Current Behavior**

@duckling69  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @duckling69  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @duckling69
- Twitter: [vivekjha30](https://twitter.com/vivekjha30)
- LinkedIn: [vivek-jha-17000918b](https://www.linkedin.com/in/vivek-jha-17000918b/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
Please toss in your profile picture and a bio @duckling69 :sunglasses:

**Comment by 8rxn** [comment]
Hey @vishalvivekm,
I would like to help out on this.

**Comment by vishalvivekm** [comment]
> Hey @vishalvivekm, I would like to help out on this.

Thanks @8rxn :)

**Comment by duckling69** [comment]
> **Current Behavior**
> 
> @duckling69 has been a consistent contributor and community member.
> 
> **Desired Situation** Let's recognize @duckling69 as a contributor and community member by creating a profile on https://layer5.io/community/members.
> 
> * GitHub: @duckling69
> * Twitter: [vivekjha30](https://twitter.com/vivekjha30)
> * LinkedIn: [vivek-jha-17000918b](https://www.linkedin.com/in/vivek-jha-17000918b/)
> * Link to profile picture:
> 
> A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> 
> **Contributor Resources**
> 
> The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> 
> * See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> * See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

Thankyou @vishalvivekm 😎

**Comment by duckling69** [comment]
> Hey @vishalvivekm, I would like to help out on this.

Bio:Hi I'm a undergrad student at NIT Rourkela who loves to explore new technologies currently diving into world of open-source. I'm proficient with C/C++ ,  JavaScript, React, SQL, Bash and python. I'm currently exploring cloud native and DevOps and learning  golang, CI/CD pipelines,  docker,  kubernetes.  Always up for any kind of collaboration Feel free to connect on any of my social handles.

PIC:
![WhatsApp Image 2023-05-11 at 4 27 01 AM](https://github.com/layer5io/layer5/assets/85884487/b5ae7cb8-3a7f-4b13-9308-f37f254d0407)

Thankyou @8rxn 🚀
