### ISSUE TITLE
dead link for 'Suggested reading' in Meshery doc 

### ISSUE THREAD

**Issue by sayyedarib** [layer5io/layer5#4255]
### Description
There's a section for "Suggested Reading" but there's no content in it, also it has a dead link
It seems that the section is still under development, until it's get ready , this section can removed or hidden in production
![problem_2](https://github.com/layer5io/layer5/assets/90370535/4d16441a-4c12-4308-920d-cf39b399fdbe)

### Expected Behavior

- [ ] remove or hide the "Suggested Reading" section

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sayyedarib** [comment]
@sudhanshutech can you please assign it to me?

**Comment by leecalcote** [comment]
@sayyedarib, let's go ahead and open this issue on https://github.com/meshery/meshery and close the issue here.

**Comment by sayyedarib** [comment]
Sorry, I couldn't notice.
I will do accordingly
