### ISSUE TITLE
Include CTA in Docker Swarm Tutorial

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4259]
@shivam-afa will you drop a CTA into the middle of this tutorial? <https://layer5.io/resources/docker/configuring-highly-available-docker-swarm>

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1684602848788769)

**Comment by Savio629** [comment]
@Shivam-AfA Are we planning on adding this CTA in Docker Swarm Tutorial?

![dockerextension](https://github.com/layer5io/layer5/assets/91362589/cbcab3ea-c33d-4acd-aa3e-681c0691195d)
I didn't got the part of incorporating it without incorporation of a new component as discussed in slack.
Am I missing something here?

**Comment by Savio629** [comment]
// @leecalcote @Shivam-AfA

**Comment by leecalcote** [comment]
Yes, that'd be great.
