### ISSUE TITLE
The responsiveness of some button is not working properly 

### ISSUE THREAD

**Issue by ankur0904** [layer5io/layer5#4267]
### Description

The responsiveness of some button is not working properly [here](https://layer5.io/pricing)

### Screenshots

![Screenshot from 2023-05-22 23-14-22]
![3](https://github.com/layer5io/layer5/assets/98346896/64ceb7e1-d34a-4159-b8c2-55eb8168a979)
![2](https://github.com/layer5io/layer5/assets/98346896/7ede046d-d0b2-4857-ba91-2a2ae02a5bc7)
![1](https://github.com/layer5io/layer5/assets/98346896/5f41a271-e75b-4926-ba09-b1967129f3b0)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by EdwinDij** [comment]
i would like to get this issue please

**Comment by SGA-pranamika-pandey** [comment]
Hello @ankur0904 ,
I'm Pranamika, and new to Meshery, and was looking for some good-first issues. Can I work on this issue please?
Thanks!

**Comment by ankur0904** [comment]
@Chadha93 @vishalvivekm  What are your thoughts about this issue?

**Comment by Akshaybagai52** [comment]
Can i work on this issue

**Comment by Savio629** [comment]
It is a valid issue.
Nice eye @ankur0904 
As @SGA-pranamika-pandey commented first I'll assign him the issue 
@Akshaybagai52 you can checkout some other issues

**Comment by ankur0904** [comment]
@Savio629 Thanks for the feedback.

**Comment by Savio629** [comment]
@SGA-pranamika-pandey updates?

**Comment by Savio629** [comment]
You can reach out for any queries on [slack](https://layer5io.slack.com/ssb/redirect#/shared-invite/email) 😄

**Comment by vishalvivekm** [comment]
What's the status on the issue here @SGA-pranamika-pandey ?

**Comment by Mohith234** [comment]
If no one is working on this issue, I can take up this 

// @Savio629 @SGA-pranamika-pandey

**Comment by HetviSoni** [comment]
Hey @SGA-pranamika-pandey  are u done setting up the project? Or should we assign it to the next person?

**Comment by Gautam-04** [comment]
If no one is working on it I would like to get assigned on this one

**Comment by abhijeetgauravm** [comment]
If its still persist , I would like to fix it!

**Comment by abhijeetgauravm** [comment]
@Gautam-04 r u working on it?
