### ISSUE TITLE
SMI table not responsive

### ISSUE THREAD

**Issue by AkashS20** [layer5io/layer5#4268]
### Description

The SMI table on page https://layer5.io/projects/service-mesh-interface-conformance is begin cutoff

### Expected Behavior
SMI table should be responsive for all sizes

### Screenshots

![Screenshot from 2023-05-23 07-31-47](https://github.com/layer5io/layer5/assets/92908347/6f56ce17-6cb1-4997-b73d-0d7a08a27066)
### Environment:
- Host OS: Linux
- Browser: Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AkashS20** [comment]
I'd like to work on this

**Comment by leecalcote** [comment]
Thanks for raising this issue. The cutoff is by design, though. Let's find you another item to work in, @AkashS20
