### ISSUE TITLE
Incorrect Color Representation of Tick on Pricing Page

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4269]
### Description
Incorrect Color Representation of Tick on Pricing Page.
https://layer5.io/pricing

### Expected Behavior
There are some tick icons with a red color which should be changed to keppel green as others

### Screenshots
![Pricing - Brave 23-05-2023 16_23_05](https://github.com/layer5io/layer5/assets/91362589/b19ee715-dc17-40a3-aa01-eb42fb658881)

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vinyashegde** [comment]
Hey can I work on this issue?
