### ISSUE TITLE
[UI] Dark Mode Color Issue in Table at Service Mesh Patterns page

### ISSUE THREAD

**Issue by 8rxn** [layer5io/layer5#4271]
### Description
The table at Service Mesh Patterns [page](https://layer5.io/learn/service-mesh-books/service-mesh-patterns) seems to have Dark Mode Color issues.

![image](https://github.com/layer5io/layer5/assets/75237697/97db1a1e-00de-402b-aa2f-3953d25df858)

![image](https://github.com/layer5io/layer5/assets/75237697/79a523c5-2790-424b-8ec4-1bf4955a1e20)

### Expected Behavior

The Color of the Header of table does not turn white.

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by niranjan-kurhade** [comment]
I would like to work on this issue. Please assign it to me!
