### ISSUE TITLE
Add Meshery Playground popup on Layer5's home page.

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4276]
A popup is required on the home page of the website (https://layer5.io/) that should redirect users to the Meshery Playground (https://play.meshery.io/). 

Some assests/ graphics that can be used for the poup are available here: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=10869-15222

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saksham294** [comment]
I'd like to work on this

**Comment by Shivam-AfA** [comment]
@Saksham294 Thanks for asking to volunteer here. We need this done by today, so I'll let you work on something else while I finish this off.
