### ISSUE TITLE
[News] Meshery listed in CNCF Landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#428]
Meshery is now listed in the CNCF Landscape. A new [News article](https://layer5.io/news) should be created to highlight this milestone.

**Article:**
- Title: Meshery accepted into CNCF Landscape
- Link: https://landscape.cncf.io/category=service-mesh&format=card-mode&grouping=category&selected=meshery

**Contributor Resources**
- [Instructions for updating news items](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#news)

---

**Screenshot**

<img width="1687" alt="Meshery in CNCF Landscape" src="https://user-images.githubusercontent.com/7570704/83415796-4e04d800-a3e5-11ea-8c6e-d49559399d99.png">

**Comment by leecalcote** [comment]
@NupurThakur27 would you like to take this one?

**Comment by NupurThakur27** [comment]
> @NupurThakur27 would you like to take this one?

@leecalcote Yes. I would.
