### ISSUE TITLE
Link catalog icon to catalog page

### ISSUE THREAD

**Issue by senali-d** [layer5io/layer5#4283]
### Description

Link the Catalog icon in project page to catalog page. Right now it is link to the same page.

### Expected Behavior

Link to [catalog](https://layer5.io/catalog) page.

### Screenshots

![1](https://github.com/layer5io/layer5/assets/52546856/7c79d2ed-d2b4-4c64-9e26-e4b0901a65ec)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by senali-d** [comment]
@goldfishdolphin Catalog page is merged now. Would you like to fix the link.

**Comment by goldfishdolphin** [comment]
Thank you @senali-d

**Comment by goldfishdolphin** [comment]
Sorted @senali-d
