### ISSUE TITLE
Visibility issue on service-mesh-patterns page in dark mode

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4292]
### Description
Visibility issue on service-mesh-patterns page in dark mode

Link : https://layer5.io/learn/service-mesh-books/service-mesh-patterns

### Expected Behavior
The text should be properly visible in dark mode

### Screenshots
Light mode : 
<img src="https://github.com/layer5io/layer5/assets/91362589/95947a63-929a-400d-8d92-cc5b6fad0a01" width="600">

Dark mode : 
<img src="https://github.com/layer5io/layer5/assets/91362589/c7dabf7c-3cb5-4817-838d-8fcd8a66b325" width="600">

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vinyashegde** [comment]
Hey @Savio629 can I work on this issue?

**Comment by 8rxn** [comment]
Hey @Savio629 

Thanks for pointing this out but I think this won't be necessary as I had already raised an issue for it #4271

**Comment by Savio629** [comment]
Sorry I missed out the issue
