### ISSUE TITLE
Add an 'Edit this page' link on layer5.io

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4297]
### Desired Behaviour
An "Edit this page" is required on layer5.io which would redirect the users to the github file for the particluar page.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by 8rxn** [comment]
Hey @Shivam-AfA ,
Does every individual page need a link to their individual figma design pages or will every page have the same button attached with the given link?

**Comment by Shivam-AfA** [comment]
Hey @8rxn. I am changing the issue description a bit, please check.

**Comment by 8rxn** [comment]
> Hey @8rxn. I am changing the issue description a bit, please check.

Ah, so the user will be redirected to the `.js` file under `src/pages` on github.

**Comment by Shivam-AfA** [comment]
Yes. @8rxn

**Comment by 8rxn** [comment]
> Yes, @8rxn. Are you willing to work on this?

Yes, @Shivam-AfA .
The link should be added in the footer I believe but open to other options as well...

**Comment by Shivam-AfA** [comment]
Yes, you can add it in the footer initially, @8rxn.

**Comment by leecalcote** [comment]
@Shivam-AfA this is missing a help wanted label.

**Comment by akshaya-hub** [comment]
@leecalcote is the issue closed if not i would like to work

**Comment by Shivam-AfA** [comment]
@akshaya-hub Thanks for asking. Currently @8rxn is working on this.
