### ISSUE TITLE
[MeshMap Design page] Update hero on page 

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4299]
### Current Behavior
The MeshMap Design page [here](https://layer5.io/cloud-native-management/meshmap/design) features a graphic in the hero (top banner/ first section) of the page. 

### Desired Situation
Some design changes are required in this section. Refer to this Figma page for the final design: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN?node-id=14294:18481#455964622

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Adi-ty** [comment]
Would love to contribute here

**Comment by Manish254252** [comment]
Hello @Shivam-AfA  can you assign this to me ?

**Comment by Shivam-AfA** [comment]
Thanks for asking @Manish254252. This has already been fixed in the PR. You can find many more similar issues. Happy contributing! 🚀
