### ISSUE TITLE
[Learn] Fix the missing images 

### ISSUE THREAD

**Issue by goldfishdolphin** [layer5io/layer5#4303]
**Current State:**
The images are not being displayed at 
https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started
![F6579D50-61CC-4487-A3AB-1B0DFAC6436D](https://github.com/layer5io/layer5/assets/98129474/47049864-0e86-46ee-8242-f91446714dc8)

**Desired State:**
The images should be displaying at the [page](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started) 
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by shyamtawli** [comment]
Hey @goldfishdolphin Can I work on this?

**Comment by kkartik07** [comment]
Hey @shyamtawli were you able to fix it or you need some help?

**Comment by shyamtawli** [comment]
Yes @kkartik07 I have started working on it, I will contact you if any help required. Was busy lately.

**Comment by shyamtawli** [comment]
Hey I have fixed this but the second image is showing error. The solution is we have to change the src of image from the import variable used on top. First image is rendering but as soon as I change the src of second image, error is showing. Can you guide me into it. Or should I open a PR.


First Image rendering.
![layer1](https://github.com/layer5io/layer5/assets/104145978/ad58227a-5121-4e5c-99d5-c14f780acac0)


ERROR after putting variable name on second image src and I have checked the path also it is correct.
![layer2](https://github.com/layer5io/layer5/assets/104145978/f932a3d6-8953-4251-8687-2a45e194b378)

**Comment by shyamtawli** [comment]
Hey, Getting errors while committing, How to fix them?

**Comment by shyamtawli** [comment]
Hey, How to fix this error?
I am not able to commit anything.

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/collections/service-mesh-workshops/2018_velocity_london/Velocity.webp'
  'src/collections/service-mesh-workshops/2018_velocity_london/velocity.webp'

**Comment by pseudofool** [comment]
I want to work on it. Please assign it to me.

**Comment by shyamtawli** [comment]
Hey @pseudofool I have already opened a PR on it.
