### ISSUE TITLE
Redirected to wrong page

### ISSUE THREAD

**Issue by ayushthe1** [layer5io/layer5#4305]
### Description

On [meshery](https://layer5.io/cloud-native-management/meshery) page ,once a user reloads the page and click on `How Meshery Works` button it  redirects the user to the page  https://layer5.io/cloud-native-management/meshery.html/operating-service-meshes  instead of  https://layer5.io/cloud-native-management/meshery/operating-service-meshes. 

Similarly once a user clicks on `Run Meshery` button ,it directs him to the page  https://layer5.io/cloud-native-management/meshery.html/getting-started  instead of  https://layer5.io/cloud-native-management/meshery/getting-started .

Note that this behaviour doesn't happens the first time a user visits the page. It only happens when once the page is being reloaded. Below is a video describing the issue :

[Screencast from 29-05-23 02:23:11 AM IST.webm](https://github.com/layer5io/layer5/assets/114604338/16fda1ce-c63e-4329-acae-08094b528dfb)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ayushthe1** [comment]
@randychilau Can you please take on this issue ?

**Comment by arunkarthicknm** [comment]
I like to work on this issue. Can you assign me please? @ayushthe1
