### ISSUE TITLE
Different icon size on connect-with-us page

### ISSUE THREAD

**Issue by HetviSoni** [layer5io/layer5#4306]
### Description
On https://layer5.io/community/handbook/connect-with-us#Discussion%20Forum page the size of second icon is slightly bigger than other icons.
<img width="562" alt="image" src="https://github.com/layer5io/layer5/assets/76479104/b13c14ef-b05c-4455-a5bd-5ae0eb0b8a85">

### Expected Behavior
Size of all icons should appear same

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Gaurav-create948** [comment]
I want to work on this issue @HetviSoni can you please assign this issue #4306 to me?

**Comment by HetviSoni** [comment]
> I want to work on this issue @HetviSoni can you please assign this issue #4306 to me?

Hey thanks for coming up and showing interest to solve the issue. I am not the maintainer so I can not assign, ask maintainers ..If they find this a valid issue then they would assign you :)

**Comment by Nitishupkr** [comment]
can i solve this issue please assign it to me

**Comment by Manish254252** [comment]
Hello @HetviSoni I have fixed this issue can you assign it to me ?

**Comment by thisiskaransgit** [comment]
⚠️ @Manish254252,  Fair Warning, for all the Layer5 Projects, ask for assignments before working on any issues, we insist everyone on following this rule to avoid conflicts and duplication of effort among contributors. Please keep this in mind for next time. Contributors can follow up on Slack if they did not receive their assignment within a week.

@Gaurav-create948 @Nitishupkr, Thanks for volunteering, we often raise beginner-friendly issues for new contributors to get started in their journey, be an active member in our community and we'll help you to land your first PR :smile:

@HetviSoni, Thank you for raising the issue :thumbsup:

**Comment by Manish254252** [comment]
this PR fix issue #4306

**Comment by Gaurav-create948** [comment]
> this PR fix issue #4306

@Manish254252 clearly what does this means I did not understand?? Is this a valid issue or is this issue already assigned to anyone or already fixed???

**Comment by Gaurav-create948** [comment]
> this PR fix issue #4306

@Manish254252 clearly what does this means I did not understand?? Is this a valid issue or is this issue already assigned to anyone or already fixed???

**Comment by Savio629** [comment]
Any reason for closing the pr @Manish254252 ?

> @Manish254252 clearly what does this means I did not understand?? Is this a valid issue or is this issue already assigned to anyone or already fixed???

@Gaurav-create948, regarding your question, Manish had created a pull request before being assigned, but he has now closed the PR. Let's wait to hear from him. If there is no response, would you like to continue with the issue?

**Comment by DevilsAutumn** [comment]
@Savio629 in case no one's there i can pick it up. 👍

**Comment by Savio629** [comment]
@Nitishupkr @Gaurav-create948 Are you guys still interested on taking up the issue?
If not then I'll assign @DevilsAutumn

**Comment by Savio629** [comment]
@DevilsAutumn You are ready to solve it,right?

**Comment by DevilsAutumn** [comment]
> @DevilsAutumn You are ready to solve it,right?
> 

Yep

**Comment by DevilsAutumn** [comment]
@Savio629 I got some important work, expect a late PR . If anyone else ask for it , assign it to them.

**Comment by HarshDobariya79** [comment]
I would like to work on this issue.
