### ISSUE TITLE
Removal of Simultaneous Highlighting of multiple list items in Navbar

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4309]
### Description
Removal of Simultaneous Highlighting of multiple list items 

### Expected Behavior
The List items should only highlight when the specific page is opened

### Screenshots

https://github.com/layer5io/layer5/assets/91362589/58cbe4ef-1481-416b-93e4-cae5bee22481

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by rohitkori** [comment]
Hey @Savio629 can I work on this issue?

**Comment by Savio629** [comment]
Hey @rohitkori I'm already working on this issue.
You can checkout some other issues
