### ISSUE TITLE
[Community] Member Profile: Randy

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4317]
**Current Behavior**

@randychilau  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @randychilau  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @randychilau 
- Twitter: 
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@randychilau would you please toss in your social handles' links and profile picture?

**Comment by Chadha93** [comment]
Yay @randychilau :1st_place_medal:

**Comment by kotkaravishkar** [comment]
@vishalvivekm Can I work on it ?

**Comment by vishalvivekm** [comment]
Go ahead @kotkaravishkar

**Comment by kotkaravishkar** [comment]
@DarrenDsouza7273  I appreciate it and I am doing well right now but thank you.

**Comment by DarrenDsouza7273** [comment]
no worries @kotkaravishkar

**Comment by kotkaravishkar** [comment]
@randychilau would you please provide social media handle links, link to your profile picture and bio for the community member profile

**Comment by randychilau** [comment]
Hi @kotkaravishkar,

Thanks for offering to work on this.

Sorry for the delay, I have been a boat without a rudder trying to work with Lighthouse and improve site scores. I will aim to have something for you by tomorrow.

Cheers,
Randy

**Comment by DarrenDsouza7273** [comment]
Hi @randychilau please drop your social links

**Comment by randychilau** [comment]
Hi @kotkaravishkar,

Apologies for the delay, I was lost in the dark on some lighthouse related issues.

Currently I don't have any socials set up besides my Github account.

Here is a profile pic: https://avatars.githubusercontent.com/u/90356410

Location: San Francisco, California, USA

Here is a short blurb:
>Randy is an aspiring JavaScript and React programmer. If he could tell someone just starting their coding journey three things, they would be: 1) The baseball player with the highest hitting percentage in history did not get a hit 60% of the time. Frustration, feeling lost, and failing during this journey are normal. Take a break or get some sleep, and you can try again later. Smile, as that is a good thing. 2) Become comfortable with feeling uncomfortable and working with the unfamiliar; it will be one of your superpowers. 3) Open source is an amazing, supportive, and welcoming place on the internet that invites all programmers to participate, regardless of where they are in their coding journey. If you have not gone there yet, stop reading this and go there now.

---

I hope that is acceptable for the profile.

Thanks again for your patience.

Cheers,
Randy

**Comment by vishalvivekm** [comment]
Thanks @randychilau :))
@kotkaravishkar You're up!
