### ISSUE TITLE
[Community] Member Profile: Avantika Jain

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#4318]
**Current Behavior**

@avantikajain289 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @avantikajain289 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @avantikajain289
- Twitter:
- LinkedIn: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by ritiksaxena124** [comment]
@avantikajain289 would you please provide social media handle links and a link to your profile picture for the community member profile

**Comment by avantikajain289** [comment]
Hi Ritik,



Here are my socials:

**LinkedIn:** https://www.linkedin.com/in/avantikaj/
**Behance:** https://www.behance.net/avantikajain
**Website:** https://www.avantikaj.com/
**GitHub:** https://github.com/avantikajain289



Profile Image (headshot):

![avantika-jain-headshot](https://github.com/layer5io/layer5/assets/112201723/af684f14-bca6-4c6c-b740-7f147fc5af37)

**Comment by kotkaravishkar** [comment]
Can I work on it ?

**Comment by vishalvivekm** [comment]
> Can I work on it ?

@kotkaravishkar Thanks :)
have assigned you a similar issue, let's get this one assigned to some other contributor. Cool?

**Comment by aku1310** [comment]
Hey, I would like to work on this. Can this please be assigned to me?

**Comment by vishalvivekm** [comment]
Thanks @aku1310 🎉😎

**Comment by avantikajain289** [comment]
Hey @aku1310 

Here's a short blurb for you:

I’m a New Delhi-based designer with a passion for problem-solving through qualitative UX research methodologies and iterative UI design.

With a background in graphic design, UX research, UI design, and an understanding of frontend development, I am excited to create meaningful solution-oriented design, and collaborate with people and companies looking to make a positive impact in our communities. 

I am thrilled to be a part of open source and their contributions to design and technology.

**Comment by aku1310** [comment]
> Hey @aku1310
> 
> Here's a short blurb for you:
> 
> I’m a New Delhi-based designer with a passion for problem-solving through qualitative UX research methodologies and iterative UI design.
> 
> With a background in graphic design, UX research, UI design, and an understanding of frontend development, I am excited to create meaningful solution-oriented design, and collaborate with people and companies looking to make a positive impact in our communities.
> 
> I am thrilled to be a part of open source and their contributions to design and technology.

Okay, thank you!

**Comment by leecalcote** [comment]
Whoo-hoo, @avantikajain289! 🎈
