### ISSUE TITLE
[Projects] The elements are not completely responsive

### ISSUE THREAD

**Issue by VishrutAggarwal** [layer5io/layer5#4321]
### Description

I found this issue on: https://layer5.io/projects
The page isn't completely responsive and the elements get cut off at certain widths and breakpoints.
I found two such issues on the same page in the same section at different breakpoints.

### Expected Behavior

The elements are expected to be completely responsive to changes in width.

### Screenshots

First:

![Screen Shot 2023-05-31 at 20 17 41](https://github.com/layer5io/layer5/assets/71827366/c6d8eb72-0b4e-4b80-8f91-e66c4ae781ea)

Second:

![Screen Shot 2023-05-31 at 20 17 14](https://github.com/layer5io/layer5/assets/71827366/4851dfa4-451b-4903-b027-f6752a4d8f74)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VishrutAggarwal** [comment]
I would like to work on this issue myself.

**Comment by vermabraj** [comment]
@VishrutAggarwal still open ?, i want to work on this, can you assign me
