### ISSUE TITLE
[Handbook] Text changing to white on hover

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4324]
### Description
On this page: https://layer5.io/community/handbook, on hovering over the cards, the heading text changes to white.

[screen-capture.webm](https://github.com/layer5io/layer5/assets/88040318/da04d92a-3a12-4cbe-974b-e8c0376db59c)

### Expected Behavior
The text color should remain the same i.e. black for light mode and white for dark mode.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by yash37158** [comment]
I would like to fix this

**Comment by 8rxn** [comment]
@yash37158 You can go ahead and fix this issue 🚀

**Comment by yash37158** [comment]
Yeah sure
