### ISSUE TITLE
Describe Layer5 MeshMates program

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#433]
**Current Behavior**
A description of this community member on boarding program would be fantastic to have here https://layer5.io/community as a new section.

**Layer5 MeshMates**
_a community member onboarding program_
https://docs.google.com/document/d/1vquQMD0TTWREahpx_JXuvIbQ4hM2_4jrVFk8xqZ72ok/edit#heading=h.2d4d7xa10wdl

**Comment by Vineet-Sharma29** [comment]
Would work on it

**Comment by leecalcote** [comment]
Thank you, @Vineet-Sharma29
