### ISSUE TITLE
[Landscape] Add FSM

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4332]
**Current State:**
Flomesh Service Mesh (FSM) is not represented in the landscape.

**Desired State:**
Flomesh Service Mesh (FSM) - https://github.com/flomesh-io/fsm - can be listed in the service mesh landscape, following the instructions below.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by martinyis** [comment]
Hey, can I work on this issue?

**Comment by 8rxn** [comment]
@martinyis You can go ahead and work on this 🚀

**Comment by martinyis** [comment]
> @martinyis You can go ahead and work on this 🚀

Thank you, I will try to do my best!

**Comment by leecalcote** [comment]
Hi @naqvis, yes, please do jump in here directly. We ask that representatives of the project be the individuals that directly represent the capabilities of the service mesh. There is a collection of functional capabilities and non-functionality capabilities that we track in the tables that you can fill-in using markdown - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape

**Comment by leecalcote** [comment]
@martinyis, thanks much for jumping in here as well. If @naqvis gets to this before you do, that's no sweat - let's help you grab another open issue to wrangle as well. Here's a link that searches across all of our orgs and projects - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by vishalvivekm** [comment]
done by #4344
