### ISSUE TITLE
coming soon image not rendering on layer5/pricing

### ISSUE THREAD

**Issue by AkashS20** [layer5io/layer5#4335]
### Expected Behavior

Fix the coming soon image
### Screenshots

![Screenshot from 2023-06-05 08-53-41](https://github.com/layer5io/layer5/assets/92908347/c26c2899-c496-41bd-815d-e8731b384776)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AkashS20** [comment]
I'd like to fix this

**Comment by Savio629** [comment]
The issue occurred while attempting to convert images from PNG format to WebP format.

**Comment by AkashS20** [comment]
@Savio629 Yes, the reason behind this is that in the import statement for the `coming_soon` image, the file extension was modified from .png to .webp. However, the image was imported from a web link instead of being located within the project directory.

There are two potential solutions to address this issue. The first option is to include the image in the project directory and the  other is reverting the file extension in the import statement back to .png.

**Comment by Savio629** [comment]
We can discuss both of the solution in today's website meeting.
Do add it in website meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#
