### ISSUE TITLE
[Home Page] Slider dots not visible in Brands carousel in dark mode

### ISSUE THREAD

**Issue by Shivam-AfA** [layer5io/layer5#4336]
### Description
There is a slider on the home page of https://layer5.io/ that features the partner brands. The slider dots are visible in light mode but not in dark mode. The color "#CCC" can be used for inactive dots in dark mode.

![image](https://github.com/layer5io/layer5/assets/88040318/a90c4413-9c78-442c-94f7-88390c1408fa)

![image](https://github.com/layer5io/layer5/assets/88040318/6578a158-c8b6-4dc4-a28d-6814b119a89a)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by HetviSoni** [comment]
I would like to work on this issue

**Comment by hirentimbadiya** [comment]
> I would like to work on this issue

Go on!

**Comment by Manish254252** [comment]
Hello anyone working on this issue

**Comment by Shivam-AfA** [comment]
@HetviSoni Any updates here?

**Comment by Manish254252** [comment]
I set it u locally to fix the issue but the dots are not visible even in the light mode .

**Comment by HetviSoni** [comment]
> @HetviSoni Any updates here?

Actually, I am still having problem running it locally. I am trying different solutions but still...So maybe u can assign it to next person.

**Comment by vishalvivekm** [comment]
> > @HetviSoni Any updates here?
> 
> Actually, I am still having problem running it locally. I am trying different solutions but still...So maybe u can assign it to next person.

@HetviSoni  still stuck running it locally? 
@Manish254252 ready to take it up?

**Comment by Manish254252** [comment]
sure assign it to me .

**Comment by HetviSoni** [comment]
> > > @HetviSoni Any updates here?
> > 
> > 
> > Actually, I am still having problem running it locally. I am trying different solutions but still...So maybe u can assign it to next person.
> 
> @HetviSoni still stuck running it locally? @Manish254252 ready to take it up?

yes 🥲 you can assign it to manish

**Comment by Manish254252** [comment]
Hello @Shivam-AfA I have fixed this issue .
![Screenshot (12)](https://github.com/layer5io/layer5/assets/70832573/35a6099a-c5ee-403d-bf9a-d7054417e808)
![Screenshot (13)](https://github.com/layer5io/layer5/assets/70832573/b519b5a4-c3c0-445c-9f39-6c8e5de4667c)

**Comment by Shivam-AfA** [comment]
@Manish254252 Please raise a PR, you have committed to your branch but haven't raised a PR.

**Comment by Manish254252** [comment]
Raised a PR.

**Comment by Kevin-Usadadiya** [comment]
To resolve Issue number #4447 
This is the Solution
In Partner-home folder --> partnerSection.style.js -->
Change is this from line 26 to 33

.slick-dots li button:before{
color: ${props => props.theme.whiteToGreen00D3A9}
transition: 0.8s cubic-bezier(0.2, 0.8, 0.2, 1);
}
.slick-dots li.slick-active button:before {
color: ${props => props.theme.green009A89ToGreen00B39F};
transition: 0.8s cubic-bezier(0.2, 0.8, 0.2, 1);
}

**Comment by VishwaRaval247** [comment]
If currently there is no update on this issue, Can I work on this issue?

**Comment by Savio629** [comment]
I think there is no updates from @Manish254252, @Kevin-Usadadiya would you like to give it a try?

**Comment by hirentimbadiya** [comment]
> I think there is no updates from @Manish254252, @Kevin-Usadadiya would you like to give it a try?

@Savio629 , I would like to fix this.
