### ISSUE TITLE
Unexpected Horizontal Display of Profile picture in community profile page

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#4340]
### Description
Unexpected Horizontal Display of Profile picture of Usman Siddique

### Expected Behavior
The profile picture of Usman Siddique should be vertical

### Screenshots
![usman](https://github.com/layer5io/layer5/assets/91362589/9f7b4d10-64ac-42de-9b98-e730ffaa0de1)
https://layer5.io/community/members/usman-siddique

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by pandeyprashant123-coder** [comment]
may I work on this issue?

**Comment by pandeyprashant123-coder** [comment]
This photo is already in horizontal display form in path `src/collections/members/usman-siddique`

**Comment by xradeel** [comment]
can you assign this issue to me? I want to work on it

**Comment by Savio629** [comment]
@xradeel This issue has been already assigned..
@pandeyprashant123-coder Fix Nikhil Ladha's profile picture too..

**Comment by Manish254252** [comment]
Hello all I don't  think this is an issue  it is working  fine when I set it up locally.

**Comment by Manish254252** [comment]
This is the screenshot of it. 

![Screenshot (7)](https://github.com/layer5io/layer5/assets/70832573/8cce512c-bf72-4b3d-8eea-7a3003d57da0)

**Comment by Savio629** [comment]
Actually, it was working fine in the local repository, but during the build process, the image was being rotated. Fortunately, the issue has been resolved now. It seems that the problem was related to the conversion of PNG/JPG images to the WebP format.
