### ISSUE TITLE
Enhance the Integrations honeycomb cells with a radial gradient

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4349]
### Current Behavior
These honeycomb cells use a linear gradient:

<img width="431" alt="Screenshot 2023-06-06 at 6 48 23 PM" src="https://github.com/layer5io/layer5/assets/7570704/8b7805d7-e5ce-41f4-9add-623da1ec33cc">

### Desired Behavior
Change from linear gradient by enhance the Integrations honeycomb cells with a radial gradient.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by aabidsofi19** [comment]
@leecalcote  i would love to work on this ...

**Comment by leecalcote** [comment]
Thank you. @aabidsofi19

**Comment by aabidsofi19** [comment]
@leecalcote  should the radial gradient be the same  color as before .

**Comment by leecalcote** [comment]
Not necessarily, no...
