### ISSUE TITLE
Page listing individual MeshMates

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#435]
**Desired Behavior**
I would also be nice to have a page dedicated to MeshMates (e.g. /community/meshmates) and to have the community member profiles of those individuals sourced from the Meshery.io profiles.

**Comment by chandrashritii** [comment]
@leecalcote I would love to work on this. The page would include -
1. An explanation about the Meshmates program.
2. A link to the MeshMates welcome doc 
3. The community member profiles of the mentors, sourced from [meshery.io](https://meshery.io/community/) 

Am I missing something?

**Comment by leecalcote** [comment]
@chandrashritii fantastic. No, you're spot on here. 👍

**Comment by chandrashritii** [comment]
Hey @leecalcote 
The [MeshMates welcome doc](https://docs.google.com/document/d/1vquQMD0TTWREahpx_JXuvIbQ4hM2_4jrVFk8xqZ72ok/edit) is currently set to `Restricted: Only people added can open with this link`. In order for a working link to be added to the MeshMates page, the sharing option should be changed to `anybody with the link`. Can that be done?

**Comment by chandrashritii** [comment]
@leecalcote This has been solved. The issue should be closed.
