### ISSUE TITLE
[Landscape] Add Nasp

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4350]
**Current State:**
Nasp is an lightweight library to expand service mesh capabilities to non-cloud environments by getting rid of the complexity of operating dedicated network proxies.

**Desired State:**
Nasp - https://github.com/cisco-open/nasp - can be represented in service mesh landscape, following the instructions below.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by akshayamadhuri** [comment]
@vishalvivekm  i would like to work on this issue

**Comment by sambhavgupta0705** [comment]
@vishalvivekm Can I work on this issue?

**Comment by vishalvivekm** [comment]
Thank you folks! 
We are waiting for any of the project representatives ( being the most knowledgeable about the project) to come and offer their assistance to accurately represent Nasp in the [Landscape](https://layer5.io/service-mesh-landscape).

**Comment by samyakshah3008** [comment]
Hey @vishalvivekm I would love to work on this issue as well 😄

**Comment by leecalcote** [comment]
@hi-im-aren thanks for asking. The "client library" section sounds the most befitting given your description of Nasp.

**Comment by leecalcote** [comment]
Thank you for jumping in, @hi-im-aren 👍
