### ISSUE TITLE
Image is not properly rendering on Introduction To Service Meshes page

### ISSUE THREAD

**Issue by Yashsharma1911** [layer5io/layer5#4360]
### Description

on [Introduction To Service Meshes](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes) page some images are not properly rendering

![Screenshot 2023-06-09 at 1 14 57 AM](https://github.com/layer5io/layer5/assets/71271069/febf3fd2-8901-4b2d-96e4-14eb564fa175)

### Expected Behavior

Images should be visible

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by SrGnico** [comment]
let me help!

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue. Please assign it to me.

**Comment by Manish254252** [comment]
Hello any update on this ?

**Comment by Yashsharma1911** [comment]
Thanks for jumping in folks let's get this assign to @tarunsamanta2k20 on FCFS also we have some same related issues with which you might like to help @Manish254252

**Comment by Yashsharma1911** [comment]
any update @tarunsamanta2k20?

**Comment by tarunsamanta2k20** [comment]
@Yashsharma1911 working fine.

![image](https://github.com/layer5io/layer5/assets/55488549/a2fe076d-3257-47a8-83fa-390165619bdc)
