### ISSUE TITLE
Add "Star the Repository" button for Meshery 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#4361]
Add a button on the  [meshery page](https://layer5.io/cloud-native-management/meshery) to redirect the user to the meshery Repository 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by tarunsamanta2k20** [comment]
Which location should I add the button?

**Comment by Manish254252** [comment]
Hello any updates on this ?

**Comment by thisiskaransgit** [comment]
Following FCFS, go ahead @tarunsamanta2k20  :rocket: , Below the teaser video would be an ideal position for the button.
Thanks for volunteering @Manish254252, we often open beginner-friendly issues for new contributors to get started in their journey, be an active member in our community and we'll help you to land your first PR 😄

**Comment by tarunsamanta2k20** [comment]
@thisiskaransgit is it fine?
![image](https://github.com/layer5io/layer5/assets/55488549/76dfb31e-4b04-4906-81ef-d248c906ab0a)

**Comment by thisiskaransgit** [comment]
First one, keep it yellow
