### ISSUE TITLE
Wrong links for the Books 

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4364]
### Description

Currently two of the books under learn path of [service mesh bookS](https://layer5.io/learn/service-mesh-books) leads to the wrong urls.
The books are  [Enterprise path to Service mesh architecture edition 1](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures) and
[Enterprise path to service mesh architecture edition 2](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition)

They both are currently leading to the below link.
[this](https://www.nginx.com/blog/how-to-choose-a-service-mesh/?utm_source=calcote)
### Expected Behavior

Upon searching on the O Reilly Website I found that current links should be 
[edition-1](https://www.oreilly.com/library/view/the-enterprise-path/9781492041795/)
[edition-2](https://www.oreilly.com/library/view/the-enterprise-path/9781492089353/)
### Screenshots

| Original page  | Expected Page |
| ------------- | ------------- |
|![image](https://github.com/layer5io/layer5/assets/59855919/2ea231df-3e1a-455c-ba51-4ab316f6b8fc)|![image](https://github.com/layer5io/layer5/assets/59855919/f4760ef6-e655-4818-9113-b570bf6b795c)|
| ![image](https://github.com/layer5io/layer5/assets/59855919/d1bf7572-ba6b-452b-a2d8-340324b041fc)|![image](https://github.com/layer5io/layer5/assets/59855919/eb66788b-8603-4047-bd97-9e60d104c7fc)|  
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment]
I already know the bug and corrected links just wish to know the current location of file to solve this issue . Can any meshmate please guide me?

Thank You

**Comment by Savio629** [comment]
Actually there is an open issue: https://github.com/layer5io/layer5/issues/4219

**Comment by Ghat0tkach** [comment]
> Actually there is an open issue: #4219

Oh but that was mentioned for edition 2 isnt it? 😅 so for edition 1 this link still need to be fixed

**Comment by Savio629** [comment]
Yeah, you're right! You can take up fixing the first edition. 😄
Please have a look at the mentioned PR and make the necessary changes...

**Comment by Ghat0tkach** [comment]
> Yeah, you're right! You can take up fixing the first edition. 😄
> Please have a look at the mentioned PR and make the necessary changes...

Thank you @Savio629

**Comment by Shivam-AfA** [comment]
@Ghat0tkach Please go through the PR #4278 which adds a form to get a copy of the 2nd edition book. The same scenario is required for the 1st edition book.

**Comment by Ghat0tkach** [comment]
@Shivam-AfA Thank you for the guidance will surely do it

**Comment by vishalvivekm** [comment]
@Ghat0tkach would you like to give any update on this?

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach would you like to give any update on this?

Yes , I was finally able to set up website yesterday and  as discussed in referenced pull request . The only issue is the disruptive interface after the form  submits. I know how to resolve (as I already did through in browser tool)  but since its .mdx file , things are going pretty difficult but will soon fix it .

Thank you

**Comment by vishalvivekm** [comment]
> > @Ghat0tkach would you like to give any update on this?
> 
> Yes , I was finally able to set up website yesterday and as discussed in referenced pull request . The only issue is the disruptive interface after the form submits. I know how to resolve (as I already did through in browser tool) but since its .mdx file , things are going pretty difficult but will soon fix it .
> 
> Thank you

Thanks for sounding off with your updates @Ghat0tkach.
Should you face any blockers, please make use of [Discussion Forum](https://discuss.layer5.io) for a timely assistance!
Great!

**Comment by leecalcote** [comment]
@Ghat0tkach let's get this effort tied off on Monday. If this isn't feasible, let's get others to help / get this reassigned. // @Shivam-AfA

**Comment by Savio629** [comment]
@Ghat0tkach 
Just a suggestion, How would it look if we have the book and the form side by side below the text and then the extension?🤔
Your thoughts?

**Comment by Ghat0tkach** [comment]
> @Ghat0tkach 
> Just a suggestion, How would it look if we have the book and the form side by side below the text and then the extension?🤔
> Your thoughts?
> 
> 

I guess thats more feasible to read and I think the disruptive UI could be solved as all the issue is due to float:right of "book" .
Thank you @Savio629 .
Will update you soon regarding the changes

**Comment by Ghat0tkach** [comment]
@Savio629

**Comment by Savio629** [comment]
Will you open a pr for the above changes?
Would be easier to give feedbacks.
The form size needs to increase.

**Comment by vishalsingh2972** [comment]
is this issue resolved? would like to work on it id its open.
