### ISSUE TITLE
Enhance to Community Member Profile Issue Template

### ISSUE THREAD

**Issue by senali-d** [layer5io/layer5#4365]
### Desired Behavior

Request Meshery cloud UUID of the member as well in the "Community Member Profile Issue Template".

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
@senali-d you're opening up another issue to have Meshery Cloud badges added to the user profile pages, right?

<img width="888" alt="Screenshot 2023-06-09 at 2 32 30 PM" src="https://github.com/layer5io/layer5/assets/7570704/618bcbe5-ed33-41f5-81e6-7ac9911df4b8">
