### ISSUE TITLE
Enhancement Community Member Profile Social Links

### ISSUE THREAD

**Issue by senali-d** [layer5io/layer5#4367]
### Desired Behavior

Add Meshery Cloud public profile link of the member next to LinkedIn icon.

1. Add Meshery Cloud logo next to the LinkedIn icon.
2. Add meshery cloud UUID as input in "member-profile-template".

https://layer5.io/community/members/aadhitya-amarendiran

### Screenshots / Mockups

<img width="888" alt="Screenshot 2023-06-09 at 2 32 30 PM" src="https://github.com/layer5io/layer5/assets/7570704/a3fbdc52-0e3f-495e-b698-eb14214b7b80">

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Manish254252** [comment]
Hello I would like to work on this pleas assign this to me .

**Comment by DarrenDsouza7273** [comment]
@senali-d can i work on this issue

**Comment by Manish254252** [comment]
Hello @senali-d  can you  explain the task no 2 in more detail ?

**Comment by senali-d** [comment]
> Hello @senali-d can you explain the task no 2 in more detail ?

@Manish254252 There is a common template for member profile (member-profile-template) add a new field for that template to get the meshery cloud id (uuid). You can find the template [here](https://github.com/layer5io/layer5/blob/master/src/collections/members/_member-profile-template/index.mdx).

**Comment by Manish254252** [comment]
Is this the desired solution ?

please let me know 

![Screenshot (9)](https://github.com/layer5io/layer5/assets/70832573/33addc1d-877a-478e-aece-6f4cdc7c3442)

**Comment by senali-d** [comment]
@Manish254252 You can open a PR. Because it is easy to give feedback.

**Comment by Manish254252** [comment]
I have not implemented the changes in the code this is just a  preview from the browser.

**Comment by Manish254252** [comment]
Just raised the PR

**Comment by Manish254252** [comment]
This PR fix  #4336
