### ISSUE TITLE
Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by samyakshah3008** [layer5io/layer5#4377]
### Current Behavior
Browserslist is outdated and it needs some regular update as mentioned in: 

![image](https://github.com/layer5io/layer5/assets/86982322/0bf6029f-90e3-403f-b002-06be258562f6)

### Desired Situation
We can update it with the command they mentioned in the warning message. 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Savio629** [comment]
Completed via #4379
