### ISSUE TITLE
[Meshery] Installation instructions for Docker Extension

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4386]
### Current Behavior
Docker Extension installation instructions are missing on https://layer5.io/cloud-native-management/meshery/getting-started

### Desired Behavior
The same instructions listed on [https://meshery.io#getting-started](https://meshery.io/#getting-started) should be available on this page.

### Screenshots / Mockups
<img width="966" alt="Screenshot 2023-06-16 at 8 45 41 AM" src="https://github.com/layer5io/layer5/assets/7570704/3e9228e2-c5d7-45df-85f1-514f0c25c825">

### Implementation
Copy/paste from meshery.io

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Saurav-Pant** [comment]
Kindly assign it to me, I want to work on it

**Comment by professorabhay** [comment]
Hey @leecalcote, I would like to work on it.

**Comment by yashh0903** [comment]
Please Assign  this issue to me

**Comment by professorabhay** [comment]
Sure @leecalcote

@Saurav-Pant If you need any help then let me know or if you want to pass it to me then also !!

**Comment by yashh0903** [comment]
Hey @leecalcote could you please assign this issue to me,  I would also like to work on it

**Comment by Saurav-Pant** [comment]
thanks, @professorabhay

**Comment by Saurav-Pant** [comment]
https://discuss.layer5.io/t/issue-with-make-setup-command-on-windows-in-layer5-project/2878 
plz have a look at this error

**Comment by ranjanmangla1** [comment]
@leecalcote I have created this pull request, https://github.com/layer5io/layer5/pull/4419, but due to a typo, in my sign-off  ", i typed ranjanmangla.1 instead of ranjanmangla1 (For my email), so getting the DCO check fail, can you suggest what to do @leecalcote ?

**Comment by ranjanmangla1** [comment]
@leecalcote created the pull request! please review

**Comment by leecalcote** [comment]
@ranjanmangla1 good work. 👍

**Comment by ranjanmangla1** [comment]
> @ranjanmangla1 good work. 👍

thank you very much @leecalcote, this was my first pr in the community, more to go!
