### ISSUE TITLE
Blog Landscape Cards images are not responsive  

### ISSUE THREAD

**Issue by vaibhav-xt** [layer5io/layer5#4387]
### Description
In [blog/category/landscape](https://layer5.io/blog/category/landscape), the first two categories of images are going out of the boxes on mobile view and there should be some minimum gap between the search bar and category boxes.  

### Expected Behavior

It should be inside of the boxes.

### Screenshots
![Screenshot (59)](https://github.com/layer5io/layer5/assets/90946899/ad56d071-1e0e-4ae7-bac3-ac3ad02fb0bd)

#### on mobile:
![screenshot_20230616-212002 (2)](https://github.com/layer5io/layer5/assets/90946899/c5d16ace-ab31-4b1a-b8fb-9d4a8c4e1029)

### Environment:
- Host OS: Windows
- Browser: All 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Yikes. Good eye, @vaibhav-xt

**Comment by harshit-senpai** [comment]
hey i would like to work on it, could you assign it to me

**Comment by manshul014** [comment]
I would like to contribute to it!!

**Comment by 8rxn** [comment]
Assigning in chronological order.
@harshit-senpai Go Ahead and Fix this 🚀

**Comment by harshit-senpai** [comment]
@8rxn fixed the issue facing some problems with the commit and build once i fix that i'll make the PR
![Screenshot 2023-06-17 03233400](https://github.com/layer5io/layer5/assets/93075068/3b5f6733-0afe-47a4-8ec4-7515ef963c51)

**Comment by vaibhav-xt** [comment]
@leecalcote & @8rxn 
It was midnight yesterday I raised an issue and I forgot to write that I would like to work on this issue. The first issue I raised existed and the second I raised was missed by my mistake 😞.

**Comment by 8rxn** [comment]
Sorry to hear that @vaibhav-xt ,

Perhaps we could get you to work on something else as your first pull request, 
Here's a [link to all issues](https://github.com/issues?page=1&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns) under Layer5 Community extending beyond this org, look out for anything that seems interesting to you

Cheers ,

**Comment by DarrenDsouza7273** [comment]
Hi @harshit-senpai can u please update

**Comment by harshit-senpai** [comment]
> Hi @harshit-senpai can u please update

I have made the PR but there was a merg issue because of the Lighthouse test, in today's meeting I got to know about that.

**Comment by Ykumar1415** [comment]
I would Like to work on this issue can you assign this issue to me?

**Comment by harshit-senpai** [comment]
> I would Like to work on this issue can you assign this issue to me?

I have fixed it, there's an issue with the lighthouse test due to which people are not able to make the PR, once that is fixed( folks are working on it ) I will make the PR
