### ISSUE TITLE
[Event] Add KCD Chennai Talk to Events page

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4388]
Please add the following event to layer5.io/events.

**Event:**
- Event Title: KCD Chennai 2023
- Event Link: https://www.kcdchennai.in/
- Talk Description: Multiplayer Kubernetes: GitOps with Friends

Join Pranav Singh at KCD Chennai 2023 to witness firsthand how Meshery revolutionizes Kubernetes operations, enabling seamless orchestration across multiple environments made possible by GitOps principles and multi-user collaboration..

- Talk Link: 
- Deck: 
- Video: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by harshit-senpai** [comment]
hey, i would love to work on it and give it a try, could you assign it to me.

**Comment by manshul014** [comment]
Can i contribute to this!! also it would be my first issue to solve, so could you please assign this issue to me

**Comment by vaibhav-xt** [comment]
Hello @vishalvivekm, I would like to work on this issue.

**Comment by manshul014** [comment]
@vishalvivekm , please assign this issue to someone

**Comment by DarrenDsouza7273** [comment]
@vaibhav-xt @manshul014 please checkout other available issues

**Comment by yashh0903** [comment]
Hey @vishalvivekm,  can you please assign this issue to me  I would like to contribute
