### ISSUE TITLE
Fix Slider double dots in Blog Section

### ISSUE THREAD

**Issue by vaibhav-xt** [layer5io/layer5#4393]
### Description

Another issue on [page](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma), is the bottom of the page in the related blog section slider dots on mobile have two dots for every li tag of dots. 

@8rxn 
- [X] I would like to work on this issue. 

### Expected Behavior

![Screenshot (69)](https://github.com/layer5io/layer5/assets/90946899/c79d8aa9-d4bb-4ff6-8002-d2193b4cf9cd)

### Screenshots

![Screenshot (65)](https://github.com/layer5io/layer5/assets/90946899/7689b34a-c9d2-41df-9f1e-186976605b8a)
![Screenshot (64)](https://github.com/layer5io/layer5/assets/90946899/549c1e6b-7013-4e72-9944-141389fc6bfb)

### Solution
adding code to `relatedPosts.style.js`
![Screenshot (70)](https://github.com/layer5io/layer5/assets/90946899/71fcae30-6907-413a-8586-1d64e2bb8496)

### Environment:
- Host OS: Windows
- Browser: All

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by 8rxn** [comment]
Good point @vaibhav-xt 

Assigned it to you
Work on the PR for the same 🚀
