### ISSUE TITLE
[Site] Enhance and place the graphic onto the about page.

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4404]
### Current Behavior
The About page - http://layer5.io/about doesn't reflect the stats of the community and project.

### Desired Behavior
Enhance this existing graphic from this page - https://layer5.io/blog/community/meshery-surpasses-1000-contributors representing cumulative totals from all of Layer5's projects not just Meshery alone onto the About page.
Reference Slack thread - https://layer5io.slack.com/archives/C015QJKUMPU/p1687195434476819

Note - The issue description will be updated with new statistics to add to the graphic.

### Screenshots / Mockups
Enhance this graphic representing the cumulative totals from all of Layer5's projects too, not just Meshery.
Figma link to design - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=7999-21344&t=7h4iYOk56wjeS06v-0

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer). his blog post’s graphic can be placed onto the <http://layer5.io/about|layer5.io/about> page - <https://layer5.io/blog/community/meshery-surpasses-1000-contributors>

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1687195434476819?thread_ts=1687195434.476819&cid=C015QJKUMPU)

**Comment by anikdhabal** [comment]
I want to work on this issue

**Comment by ankur0904** [comment]
I want to fix this issue

**Comment by harshit-senpai** [comment]
changes the graphics and past it on to the About Us section `http://layer5.io/about`,  got it will like to work on it.

**Comment by leecalcote** [comment]
Thanks for volunteering, guys! Assigning in chronological order...
