### ISSUE TITLE
[GitOps] Add "INSTALL" button under SMP section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4406]
:help-wanted: We’re missing an “INSTALL” button under the :smp: action - <https://layer5.io/cloud-native-management/gitops>

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1687294686882889)

**Comment by Mohith234** [comment]
Can I work on this?

**Comment by leecalcote** [comment]
@Mohith234 thank you much for volunteering. I just spotted a few items that needed fixing promptly. Let me pull you into the PR review...
