### ISSUE TITLE
Landscape cards are not responsive 

### ISSUE THREAD

**Issue by nihalpawar4** [layer5io/layer5#4415]
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by nihalpawar4** [comment]
please assign me the issue will work on it

**Comment by 8rxn** [comment]
> please assign me the issue will work on it

Hey @nihalpawar4 , You might wanna put more info about pages, relevant screenshots and related links to create a well documented issue before anyone may assign it to you, provided it is not already solved in a PR.

**Comment by Chadha93** [comment]
> > please assign me the issue will work on it
> 
> Hey @nihalpawar4 , You might wanna put more info about pages, relevant screenshots and related links to create a well documented issue before anyone may assign it to you, provided it is not already solved in a PR.

@nihalpawar4 ??

**Comment by nihalpawar4** [comment]
> > > please assign me the issue will work on it
> > 
> > 
> > Hey @nihalpawar4 , You might wanna put more info about pages, relevant screenshots and related links to create a well documented issue before anyone may assign it to you, provided it is not already solved in a PR.
> 
> @nihalpawar4 ??

surely I am working on it give me some time

**Comment by vishalsingh2972** [comment]
please assign this to me if its still open!

**Comment by Shivam-AfA** [comment]
Since @nihalpawar4 hasn't responded with the issue description, let's close this one.
