### ISSUE TITLE
[Site] Download Case Study Button

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4416]
### Current Behavior
We don't support downloading the Case Study or any of our resource articles to be downloaded as pdf.

### Desired Behavior
Add a Download case study button on the resource article only if the type is a case study. 

### Implementation
Add it in - https://layer5.io/resources/cloud-native/hpes-adoption-of-meshery-and-meshmap, and add the button under the introduction.

### Acceptance Tests
The button should be a reusable component and should work according to the tag. 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Mohith234** [comment]
I would like to give it a try @Chadha93, Can I work on this ?

**Comment by thisiskaransgit** [comment]
@Mohith234, how are we progressing with this task?

**Comment by Mohith234** [comment]
@thisiskaransgit There was a discussion regarding this issue on slack. 
Waiting for update from @Shivam-AfA

**Comment by sudhanshutech** [comment]
@Mohith234 we can discuss this in website meeting, you can add this an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would

**Comment by cosmos1721** [comment]
is this issue assigned to anyone?
it not, can I work on this?

**Comment by nakulbh** [comment]
Hey @Chadha93 @leecalcote can i work this ?

**Comment by Chadha93** [comment]
Seeing no response or PR from @Mohith234, let's assign this to @cosmos1721, going in order. 
I'm clearing assignments for now. @cosmos1721 @nakulbh, do you have any doubts on the issue, what needs to be accomplished?

**Comment by cosmos1721** [comment]
> do you have any doubts on the issue, what needs to be accomplished?

although, its quite clear. Still I've some basic doubts:
where exactly you want me to add it.
there are some other doubts, but I would like to explore myself first.
will let you know if I have more doubts

**Comment by Mohith234** [comment]
@Chadha93 I was about to raise a PR it was completed. Should I raise or should I help @cosmos1721 ?

**Comment by DkRadhey** [comment]
@Chadha93 Is this issue assigned to anyone? It not, can I work on this?

**Comment by leecalcote** [comment]
@DkRadhey you're welcome and encouraged to review the open PR (see above).
