### ISSUE TITLE
Change text selection color from green to keppel 

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4417]
### Description
Currently, on selecting text it shows green color which is not in our brand color
![image](https://github.com/layer5io/layer5/assets/65453826/f448f48c-1d7d-4b79-bbfd-1c6194198fd9)

### Expected Behavior
Change the text selection color to Keppel rgb(0, 179, 159). from theme.

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sambhavgupta0705** [comment]
@Chadha93 I would like to resolve this issue :smil

**Comment by ranjanmangla1** [comment]
hey @Chadha93 , new to community & open source, i would love to contribute to this. Please assign me this issue.

**Comment by ezioxatul** [comment]
@Chadha93 Please assign me this issue

**Comment by Chadha93** [comment]
Thank you for volunteering guys, let's assign this in chronological order.

**Comment by sambhavgupta0705** [comment]
@gauravchauhan2403 we need to change the color for whole page or only for this h2 tag
