### ISSUE TITLE
[Community] Member Profile: Tejas

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4418]
**Current Behavior**

@0xt3j4s has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @0xt3j4s as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @0xt3j4s
- Twitter: [tejas_jamdade04](https://twitter.com/tejas_jamdade04)
- LinkedIn: [0xt3j4s](https://www.linkedin.com/in/0xt3j4s/)
- Meshery Cloud: [60d7dbbf-2489-4f41-81b9-8edf4605d939](https://meshery.layer5.io/user/60d7dbbf-2489-4f41-81b9-8edf4605d939)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@0xt3j4s please toss in your profile picture a bio :)

**Comment by sambhavgupta0705** [comment]
@vishalvivekm I would like to work on this issue 😄

**Comment by vishalvivekm** [comment]
Thanks @sambhavgupta0705

**Comment by 0xt3j4s** [comment]
Thanks @vishalvivekm!

Here are the details:

Location: Pune, India.
position: contributor
bio: Hey there. I am Tejas, an undergraduate student from the Indian Institute of Technology, Jodhpur. I am passionate about software development, open source, DevOps and Security. I am a hands-on learner and prefer exploring and learning new technologies by building cool projects.
profile picture: ![tejas_jamdade_profile](https://github.com/layer5io/layer5/assets/75741089/34c284c2-c786-4583-bfd9-9cf740fb2fb6)
badges:
    - meshery
    - meshmap

Please let me know if there are any changes.
