### ISSUE TITLE
[Meshery] Installation instructions

### ISSUE THREAD

**Issue by ranjanmangla1** [layer5io/layer5#4427]
### Description
Installation instructions on https://layer5.io/cloud-native-management/meshery/getting-started and https://meshery.io/#getting-started are 

### Expected Behavior

The installation instructions should have a consistency to avoid confusion and all installation instruction should be present.

## **Bash**

at [meshery.io](http://meshery.io/)
![image](https://github.com/layer5io/layer5/assets/93506927/d4fcc143-4b34-458b-8927-10dd3c48b1cc)

at [layer5.io](http://layer5.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/119e6476-bb19-4c43-b0f7-63cd7e8caded)

## **Google Kub Command is different**

at [meshery.io](http://meshery.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/72469e95-baf2-4f09-80d5-a5d33098366f)

at [later5.io](http://later5.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/3fcac2bd-3bbc-4cdd-b21f-175f25790a17)

## Helm

at [meshery.io](http://meshery.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/c04516c8-af0a-4f10-8c78-ebedf72b4e4d)

at [layer5.io](http://layer5.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/c13ebd98-201c-48e3-bdc7-3c8af2ce2658)

## Kind User:

at [meshery.io](http://meshery.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/698a4879-d0fa-414a-87bb-cee6fe94097e)

at [layer5.io](http://layer5.io/)

![image](https://github.com/layer5io/layer5/assets/93506927/cef60df1-11fc-422f-91ed-1db67aa30cb5)

#### Please assign me this issue.
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ranjanmangla1** [comment]
hey @leecalcote, Can you look into this issue, it is open from more than a week now! If not required, should we close it?

**Comment by Chadha93** [comment]
@ranjanmangla1 Good comparison between the steps on the two websites, right, the steps should be consistent for the installation of Meshery on meshery.io and layer5.io.  
Please go ahead with this.

**Comment by ranjanmangla1** [comment]
Ok, @Chadha93, going through it, I think you forgot to assign me this issue, can you do that?

**Comment by Chadha93** [comment]
> Ok, @Chadha93, going through it, I think you forgot to assign me this issue, can you do that?

Good to go @ranjanmangla1

**Comment by thisiskaransgit** [comment]
@ranjanmangla1,  how's the progress on your PR?

**Comment by ranjanmangla1** [comment]
@thisiskaransgit almost done, sending a pr today

**Comment by sudhanshutech** [comment]
Any updates @ranjanmangla1 , we can discuss in website meeting, will you add this an agenda item in [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, Thanks for pointing out the inconsistencies 
For Layer5.io 
- Update the helm commands to support Helm v3 
- Update the GKE command to use the automotive configuration method 

_refer to [docs.meshery.io/installation](https://docs.meshery.io/installation) for reference_

We need to update the Commands in Meshery.io too, we are missing KinD installation along with the commands for other platforms are outdated.

**Comment by DarrenDsouza7273** [comment]
@ranjanmangla1 could you please update

**Comment by nakulbh** [comment]
HEY @ranjanmangla1 @Chadha93 is this issue still open ?. I would like to work on it

**Comment by Ghat0tkach** [comment]
@ranjanmangla1  any updates?

**Comment by thisiskaransgit** [comment]
@Ghat0tkach, since we haven't heard back from @ranjanmangla1, please take over this PR

**Comment by Ghat0tkach** [comment]
@thisiskaransgit  , Thanks a lot
