### ISSUE TITLE
Minor spelling mistake on the getting started page

### ISSUE THREAD

**Issue by KaranJagtiani** [layer5io/layer5#4432]
### Current Behavior
In the `Patterns` section on the [Getting Started](https://layer5.io/cloud-native-management/meshery/getting-started) page, there is a minor spelling mistake.
![Screenshot 2023-06-24 at 8 25 30 PM](https://github.com/layer5io/layer5/assets/39665675/ae95fb3a-8f64-4205-85bb-18ce96e21533)

### Desired Situation
"cancapture" can be changed to "can capture".

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Inayatkmbj** [comment]
can i contribute

**Comment by imaxmayur** [comment]
I want to work on it. Assign me the issue if possible.
