### ISSUE TITLE
[Community] Member Profile: Freedisch

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4435]
**Current Behavior**

@freedisch has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @freedisch as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @freedisch
- Twitter: 
- LinkedIn: [thibaut-freedisch-batale-905843208](https://www.linkedin.com/in/thibaut-freedisch-batale-905843208/)
- Meshery Cloud: [a551897f-da39-4d4d-812e-6b299e82c457](https://meshery.layer5.io/user/a551897f-da39-4d4d-812e-6b299e82c457)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@freedisch We'd need your bio and a link to your profile picute. Do you have twitter?

**Comment by Chetan-Managavi** [comment]
@vishalvivekm I would like to work on this issue.

**Comment by Freedisch** [comment]
@vishalvivekm yes sure.
Twitter: [freedisch](https://twitter.com/freedisch)
Picture: [picture](https://drive.google.com/file/d/1F4rGdYPSxqBXW-B7KQ_eBeenyp1khrrz/view?usp=sharing)

**Comment by DarrenDsouza7273** [comment]
Assigning it to you @Chetan-Managavi

**Comment by Ghat0tkach** [comment]
@Chetan-Managavi are you still working on this issue?

**Comment by Chetan-Managavi** [comment]
@Ghat0tkach I am not working on this issue.

**Comment by Ghat0tkach** [comment]
@vishalvivekm @DarrenDsouza7273  may I work on this issue?

**Comment by vishalvivekm** [comment]
> @vishalvivekm @DarrenDsouza7273  may I work on this issue?

As Chetan's no longer working ok it, sure go do it.
Make use of your new powers @Ghat0tkach ;)
//Self-assign//

**Comment by Ghat0tkach** [comment]
> > @vishalvivekm @DarrenDsouza7273  may I work on this issue?
> 
> As Chetan's no longer working ok it, sure go do it. Make use of your new powers @Ghat0tkach ;) //Self-assign//

Thanks a lot 🙌
