### ISSUE TITLE
[Community] Member Profile: Aabid

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4437]
**Current Behavior**

@aabidsofi19  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @aabidsofi19  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @aabidsofi19 
- Twitter: [codingaabid](https://twitter.com/codingaabid)
- LinkedIn: [aabid-sofi](https://www.linkedin.com/in/aabid-sofi)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
Bio and the link to your profile picture @aabidsofi19 please :)

**Comment by DarrenDsouza7273** [comment]
can i work on this too @vishalvivekm

**Comment by vishalvivekm** [comment]
> can i work on this too @vishalvivekm

@DarrenDsouza7273 let's keep this one for some new members of the community. What d'you say?

**Comment by Ykumar1415** [comment]
can i solve this issue @vishalvivekm

**Comment by DarrenDsouza7273** [comment]
Assigned it to you @Ykumar1415

**Comment by aabidsofi19** [comment]
profile pic : ![Picture-gratscale](https://github.com/layer5io/layer5/assets/65964225/d7e810c5-7817-409f-99ce-effd7d29c88e)

**Comment by aabidsofi19** [comment]
bio : Hi, I'm Aabid Sofi, a software engineer and web developer.

I specialize in creating custom software and web applications that are both functional and visually appealing, with a focus on design, security, and performance.  Highly passionate about cloud native and open source .
