### ISSUE TITLE
[Community] Member Profile: Vaibhav

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4438]
**Current Behavior**

@vaibhav135 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @vaibhav135 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @vaibhav135
- Twitter: [Vaibhav__Bisht](https://twitter.com/Vaibhav__Bisht)
- LinkedIn: [vaibhav-singh-bisht-81619b126](https://www.linkedin.com/in/vaibhav-singh-bisht-81619b126/)
- Meshery Cloud: [b556e60f-f560-4f3c-9a74-ea0327f49163](https://meshery.layer5.io/user/b556e60f-f560-4f3c-9a74-ea0327f49163)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
Would you please toss in your bio and the link to your profile picture @vaibhav135 ?

**Comment by DarrenDsouza7273** [comment]
Can i work on this issue @vishalvivekm

**Comment by vishalvivekm** [comment]
> Can i work on this issue @vishalvivekm

Thanks @DarrenDsouza7273 .
You know what to do ;)

**Comment by DarrenDsouza7273** [comment]
> @vishalvivekm Here is my bio:-
> 
> > I am an enthusiastic Software Developer proficient in a wide range of technologies, including Typescript, React, Django, Cesium, and Posgis. I have a strong desire to continuously expand my knowledge and skills, and currently, I am eager to delve deeper into Kubernetes and its various components. As an avid supporter of open source projects, I am passionate about contributing to the community.
> > I am particularly excited about the opportunity to explore and learn from the vibrant Layer5 community. I believe that engaging with like-minded individuals will allow me to broaden my horizons and gain valuable insights into the world of software development.

your location would just be india right?

**Comment by vaibhav135** [comment]
@DarrenDsouza7273 Yes.
