### ISSUE TITLE
[Community] Member Profile: Philip

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4440]
**Current Behavior**

@philip-21 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @philip-21 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @philip-21
- Twitter: 
- LinkedIn: [philip-obiora-aa09401a9](https://www.linkedin.com/in/philip-obiora-aa09401a9/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@philip-21 Please share your bio and the link to your profile picture :)
Do you have twitter?

**Comment by Philip-21** [comment]
Thanks @vishalvivekm 
My Bio 
 I am a backend developer passionate in developing server side Software. An adept Gopher with an enthusiasm for Open source and continuous learning. I have high interest in Cloud computing and Kubernetes . 

My photo link https://drive.google.com/file/d/1qQO8Z3DepurCiOdNPCjtTBbymqE0Mrge/view?usp=drivesdk

Twitter link 
 https://twitter.com/Philip_obiora21?t=zP0F4uFoFPNWQxoUHiWcMw&s=09
