### ISSUE TITLE
[UX] GitOps: Enhance page with section highlighting What is GitOps resource

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4442]
### Current Behavior
There is a need for a small section on [gitops overview page](https://layer5.io/cloud-native-management/gitops) that highlights the [What is GitOps resource article](https://layer5.io/resources/cloud-native/what-is-gitops).

### Implementation
1. A small design is needed in Figma
2. Implementation of that design 

### Acceptance Tests
1.  A new section highlights the What is GitOps resource and links to that page.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by BlessedAlozie** [comment]
I am on the design board but I am not an editor please I will need someone to make me an editor

**Comment by AryanSharma9917** [comment]
Hi @leecalcote , do you mean a highlighted button or a design underneath the GitOps that will redirect us to, [What is GitOps resource article](https://layer5.io/resources/cloud-native/what-is-gitops)?

**Comment by leecalcote** [comment]
@BlessedAlozie permissions updated. Given that we opened this one up for you from today's meeting, I'm assigning to you.

@AryanSharma9917 good question... If I get your meaning, it's the latter.

**Comment by BlessedAlozie** [comment]
@leecalcote thanks, I am working on the design now.

**Comment by BlessedAlozie** [comment]
@leecalcote Am done with the design, and awaiting review

**Comment by leecalcote** [comment]
@avantikajain289

**Comment by BlessedAlozie** [comment]
@leecalcote please do let me know if there is any other thing to design, I will be willing to contribute.

**Comment by ritiksaxena124** [comment]
> @leecalcote please do let me know if there is any other thing to design, I will be willing to contribute.

Thank you for your contribution @BlessedAlozie 🙌. I have left a comment on your design

**Comment by leecalcote** [comment]
@BlessedAlozie thanks for this. Can we slim this down to a single section to include on the existing GitOps page?

**Comment by leecalcote** [comment]
I'm just looking for a callout to the existing resource article.

**Comment by leecalcote** [comment]
Opening up assignment...

**Comment by Gautam-04** [comment]
@leecalcote  I would like to work on this one, can you assign me this?

**Comment by leecalcote** [comment]
Thanks, @Gautam-04 👌
