### ISSUE TITLE
Home Page All Brands Carousel Dots are not Visible  

### ISSUE THREAD

**Issue by vaibhav-xt** [layer5io/layer5#4447]
### Description

This is a small bug.

### Screenshots

![Screenshot (104)](https://github.com/layer5io/layer5/assets/90946899/72a2ffa3-c572-438e-ba9d-d809588d40c5)

### Expected Behavior

It should be similar to this. 
![Screenshot (107)](https://github.com/layer5io/layer5/assets/90946899/f2fb2d19-5e5e-4625-bced-4bdd15d93818)

### Environment:
- Host OS: Windows
- Browser: All

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment]
There you go @VishwaRaval247  , Dont hesitate to ask any doubts in the slack channel🙌

**Comment by Kevin-Usadadiya** [comment]
I actually have the solution.

**Comment by Kevin-Usadadiya** [comment]
In Partner-home folder --> partnerSection.style.js -->
Change is this from line 26 to 33

.slick-dots li button:before{
			color: ${props => props.theme.whiteToGreen00D3A9}
            transition: 0.8s cubic-bezier(0.2, 0.8, 0.2, 1);
		}
.slick-dots li.slick-active button:before {
			color: ${props => props.theme.green009A89ToGreen00B39F};
            transition: 0.8s cubic-bezier(0.2, 0.8, 0.2, 1);
		}

**Comment by Savio629** [comment]
There's already an open issue #4336 
@vaibhav-xt Do consider checking issues tab before opening an issue...

**Comment by Ghat0tkach** [comment]
//Closing this as its a duplicated issue for #4336
