### ISSUE TITLE
[Partners] Add Docker

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4448]
### Current Behavior
Docker is a Layer5 partner, but not listed on layer5.io/partners

### Desired Behavior
List Docker in the layer5.io/partners page with a description taken as an excerpt of the partnership from https://layer5.io/company/news/layer5-joins-docker-extension-program-bringing-kubernetes-and-service-mesh-management-to-docker-with-meshery

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by martinyis** [comment]
Hey, can I work on this issue?

**Comment by vednp** [comment]
Hey @leecalcote l would like to work on this

**Comment by leecalcote** [comment]
Thank you much, gents. Assigning in chronological order...

**Comment by martinyis** [comment]
@leecalcote  When I am trying to **`make site`** it gives me error below. I downloaded all dependecies and all files but it just does not load a website. What might help?

![image](https://github.com/layer5io/layer5/assets/97173732/a8748ea9-d917-454a-a80e-1272c668eaf9)

**Comment by DarrenDsouza7273** [comment]
Please add it to the discussion forum or u can mention it on the slack channel for a quicker response. @martinyis

**Comment by Savio629** [comment]
@martinyis Try to use gitpod, this issue sometimes occurs because of the specs of your system....

**Comment by ranjanmangla1** [comment]
if nobody is working on it, please assign me this issue
