### ISSUE TITLE
Video Container On Home Page Overflows (No margin on Right)

### ISSUE THREAD

**Issue by saaagarsingh** [layer5io/layer5#4459]
### Description
While exploring the website, I found that On Home page of the Layer5. The container which contains video looks overflowing out of the screen and It makes the User Experience bad.

### Expected Behavior
Expected behavior is that there should be some margin on the right side of the container. So the video does not look like it is overflowing. Currently I has 0 margin.

### Screenshots
![layer5HomePage](https://github.com/layer5io/layer5/assets/85694019/be47cfca-2a6a-42af-8337-9927016d3876)

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by saaagarsingh** [comment]
Also If the maintainers find it a real issue then I would like to work on the same.

**Comment by VamshiReddy02** [comment]
can I work on this issue?

**Comment by VamshiReddy02** [comment]
can I work on this issue? this is my first time contributing to this project.

**Comment by vishalvivekm** [comment]
@saaagarsingh Let's discuss this on websites call today at 5:30 PM IST. Add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit) if you would :)

**Comment by Savio629** [comment]
There's already an open issue https://github.com/layer5io/layer5/issues/3774

@saaagarsingh @VamshiReddy02 If you guys want to solve the issue do comment on the mentioned issue
