### ISSUE TITLE
Text inside icons overflowing the container on hover

### ISSUE THREAD

**Issue by vednp** [layer5io/layer5#4460]
### Description
On the home page of Layer5 website under the section of Built-In Integrations the text on the icons overflows the size of container for some icons on hovering over it and for most the transition is not smooth.

### Expected Behavior
The text should be smaller in size and when hovered over, It should make a smooth transition for in and out with text and icons properly positioned and centered within the container.

### Screenshots
<img width="762" alt="Screenshot 2023-07-01 at 12 59 11 AM" src="https://github.com/layer5io/layer5/assets/114849889/6e76d5e9-67e7-4d9f-9242-6bafe475ceb3">

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vednp** [comment]
I would like to work on this

**Comment by hirentimbadiya** [comment]
whats your take on this ? 
![Screenshot 2023-07-01 082433](https://github.com/layer5io/layer5/assets/86219935/76cd6a04-fb56-4dfb-b99a-32b3073724bd)

**Comment by vednp** [comment]
Great, Did you work on it?

**Comment by hirentimbadiya** [comment]
> Great, Did you work on it?

I did nothing,  I just hovered on that icon do you think this is a valid issue?

**Comment by vednp** [comment]
I checked on chrome and safari, It's still the same

**Comment by Ghat0tkach** [comment]
> I checked on chrome and safari, It's still the same 

I checked on chrome and its working fine , are you focusing on the end result? Or about transition?

**Comment by vednp** [comment]
> > I checked on chrome and safari, It's still the same
> 
> I checked on chrome and its working fine , are you focusing on the end result? Or about transition?

End result I think It might be some browser's issue I don't know
