### ISSUE TITLE
[Footer] Responsive issue with the Subscribe section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4462]
### Description
Overlap is occurring on specific window sizes. See screenshot.

### Expected Behavior
The page content should adjust dynamically to avoid overlap.

### Screenshots
<img width="1102" alt="Screenshot 2023-06-30 at 10 13 45 PM" src="https://github.com/layer5io/layer5/assets/7570704/3a07c724-7a1b-4a8e-9558-84872da25583">

### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vednp** [comment]
Hey @leecalcote can i work on it?

**Comment by itsmenikhill** [comment]
Hi, @leecalcote how can I reproduce this issue?

**Comment by leecalcote** [comment]
Thanks, @vednp, and @itsmenikhill.

**Comment by leecalcote** [comment]
@itsmenikhill, slowly, expand and contract, your browsers window size and watch the footer.

**Comment by itsmenikhill** [comment]
Seems fine to me . I'm using Chrome on windows 11.

**Comment by vednp** [comment]
> Seems fine to me . I'm using Chrome on windows 11.

On screen width of 726-728px its breaking
