### ISSUE TITLE
[Community] Member Profile: Darren

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4463]
**Current Behavior**

@DarrenDsouza7273 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @DarrenDsouza7273 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @DarrenDsouza7273 
- Twitter: 
- LinkedIn: [darren-dsouza-4168a4264](https://www.linkedin.com/in/darren-dsouza-4168a4264/)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@DarrenDsouza7273 Pal please toss in your twitter, bio and a link to your profile picture :)

**Comment by Ghat0tkach** [comment]
Congratulations @DarrenDsouza7273 🙌

**Comment by hirentimbadiya** [comment]
I'll take this one , is it fine @vishalvivekm ?

**Comment by DarrenDsouza7273** [comment]
the link to my profile pic : https://drive.google.com/file/d/1dNhF1IW6mTR-2KzIlC-5DUq_8OOrLCEr/view?usp=sharing 
twitter : https://twitter.com/DarrenDsou52379
Location : Mumbai , India 
Bio : I'm Darren, a dedicated front-end developer and UI designer. As an undergraduate student in Computer Science Engineering, I am constantly expanding my technical expertise. The MERN stack has captured my interest, and I enjoy utilizing its cutting-edge technologies

**Comment by DarrenDsouza7273** [comment]
Thank you @vishalvivekm @hirentimbadiya @Ghat0tkach

**Comment by DarrenDsouza7273** [comment]
ill send the profile pic in a min

**Comment by DarrenDsouza7273** [comment]
Profile pic : https://drive.google.com/file/d/1_g04FmpzaaKGj3PqLpC7dvzcyZGsHfra/view?usp=drivesdk
