### ISSUE TITLE
[MeshMap] Design: Interactive Canvas?

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4475]
### Current Behavior
Site visitors of [this page](https://layer5.io/cloud-native-management/meshmap/design) don't see a pointer for their cursor, and therefore, don't necessarily know that they can interact with this section of the page.

<img width="605" alt="Screenshot 2023-07-03 at 8 16 35 AM" src="https://github.com/layer5io/layer5/assets/7570704/e28cc051-d47c-4e00-9358-ed798b9f358b">

### Desired Situation
Ensure `pointer` cursor type on hover of nodes.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
@Shivam-AfA can you take care of this?

**Comment by HarshDobariya79** [comment]
If @Shivam-AfA is not planning to work on this, I can take it up.

**Comment by HarshDobariya79** [comment]
One more thing I'm noticing is that zooming in and out is so sensitive. Can anyone please confirm? If the same thing is happening for all, I suggest reducing the sensitivity a bit if that's possible.

[zoom-preview.webm](https://github.com/layer5io/layer5/assets/29772969/51cb2f73-7f10-4a32-937f-040cee201c33)

**Comment by Shivam-AfA** [comment]
I can work on this, however, since @HarshDobariya79 volunteered, he can take this up.

On another note, I think we can remove the zoom functionality, since it hinders with the page zoom, and then we'll also be able to show the cytoscape on mobile devices. We're not currently showing it for mobile devices due to scroll issues. @leecalcote

**Comment by leecalcote** [comment]
@Shivam-AfA please take care of this directly.
