### ISSUE TITLE
[UI] Update the Status link  to pill with a pulsating indicator

### ISSUE THREAD

**Issue by aabidsofi19** [layer5io/layer5#4477]
### Current Behavior
Currently our Status link is a plain anchor tag , which does not provide any information about the systems status and is also not much visually appealing 

### Desired Behavior

Change the anchor tag to a pill with the text  `Layer5 Cloud Satus` and a pulsating status indicator 

### Implementation

the status indicator should be :
- green if the systems are up 
- orange if the systems are down 
-
### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thank you, @aabidsofi19
