### ISSUE TITLE
Add description of Image Hub to README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#448]
**Current Behavior**
The [project section](https://github.com/layer5io/layer5#projects) of Layer5 repo's readme is missing a description of the [Image Hub](https://github.com/layer5io/image-hub).

**Desired Behavior**
The Image Hub logo and short description should be present.

**Comment by chandrashritii** [comment]
Hey @leecalcote  
I cannot find any official page dedicated to Image Hub on the [Layer5](https://layer5.io/) website. Should a link to the [Image Hub](https://github.com/layer5io/image-hub) repo be added in the description?

**Comment by leecalcote** [comment]
Hi @chandrashritii! Thank you for jumping in here. 👍 

You're right. The Image Hub project is only to be found on the https://layer5.io/brand page at the moment. We're in need of a new entry in the [`projects` collection](https://github.com/layer5io/layer5/tree/master/collections/_projects) being created for the Image Hub project. 

Unlike the other three projects currently listed, the permalink to the Image Hub project should not be a root-level URL (should not be `/image-hub`), rather it should be `/projects/image-hub`. 

I hope this helps. Keep the questions coming!

**Comment by leecalcote** [comment]
Also, in case you haven't joined this Slack workspace, yet, please do! 👍 http://slack.layer5.io

**Comment by chandrashritii** [comment]
@leecalcote Thank you so much for explaining! Please review #450 
Also, thanks for the tip. I joined the Slack workspace :)

**Comment by leecalcote** [comment]
Nice work, @chandrashritii 😀
