### ISSUE TITLE
Github icon on footer is dimmer than other icons [UI}

### ISSUE THREAD

**Issue by ranjanmangla1** [layer5io/layer5#4480]
### Description

The bug is in the footer of the layer5.io website. If we look closely, when all icons are inactive, github icon looks more dull (more transparent) than other icons: 
![image](https://github.com/layer5io/layer5/assets/93506927/aa5aefe8-bde5-4902-b72b-cec13bc89378)

### Expected Behavior

The icon should be on consisten opacity with other icons

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

Please assign me this issue

**Comment by Ykumar1415** [comment]
@ranjanmangla1 @Chadha93 @vishalvivekm @leecalcote  want to work on this issue. Please assign it to me.

**Comment by vednp** [comment]
Hey @ranjanmangla1, I can work on this

**Comment by vednp** [comment]
I don't think this is really an issue. Everything looks fine to me

**Comment by ranjanmangla1** [comment]
> I don't think this is really an issue. Everything looks fine to me

Yeah, if you look closely, you can see. But it is very close and it's a very minor one, we can drop it if you want

**Comment by HetviSoni** [comment]
> ### Description
> The bug is in the footer of the layer5.io website. If we look closely, when all icons are inactive, twitter icon looks more dull (more transparent) than other icons: ![image](https://user-images.githubusercontent.com/93506927/250661041-aa5aefe8-bde5-4902-b72b-cec13bc89378.png)
> 
> ### Expected Behavior
> The icon should be on consisten opacity with other icons
> 
> ### Screenshots
> ### Environment:
> * Host OS:
> * Browser:
> 
> <img alt="" width="24px" src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg">
> 
> ## Contributor Resources and [Handbook](https://layer5.io/community/handbook)
> The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> 
> * 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
> * 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
> * 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).
> 
> <img alt="" height="22px" src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp">Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).
> 
> Please assign me this issue

hey are u talking about the github icon?

**Comment by leecalcote** [comment]
+1 to @HetviSoni's suggestion that it is the GitHub icon that is the issue.

**Comment by ranjanmangla1** [comment]
Hey @leecalcote, I mentioned this in the PR, there’s a problem with the GitHub icon. My bad, I guess I didn’t explain it well enough.

**Comment by leecalcote** [comment]
I agree - your chosen issue title is most misleading.

**Comment by ranjanmangla1** [comment]
Ok, changing it, meanwhile can you assign me this issue?

**Comment by princerajpoot20** [comment]
@ranjanmangla1 It is of github icon not twitter.

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, Thanks for your ongoing efforts and for looking into the issue, while raising an issue always use the appropriate issue template and add the relevant title and description. Also `kind/bug` refers to anything not working, here the enhancement label should be used.  

Since you are already assigned multiple issues, let's give another contributor chance.

**Comment by saaagarsingh** [comment]
@thisiskaransgit should I work on this?

**Comment by Ykumar1415** [comment]
@saaagarsingh i am working on tis issue and i will make pr today.

**Comment by Harsh-2004** [comment]
Can I work on this @leecalcote pls

**Comment by HetviSoni** [comment]
Hey @Harsh-2004 thank u for coming up and showing interest to solve the issue...But before asking u could just see that a pr has already been created. U can help review the pr or look for other issues👍

**Comment by Harsh-2004** [comment]
Sry I didn't see that 👍👍

**Comment by udaySuryaP** [comment]
@ranjanmangla1  Is anyone currently working on this? If not, would you be able to assign it to me so that I can try to solve it?
