### ISSUE TITLE
FAQ Section need to be enhanced in https://layer5.io/careers/programs

### ISSUE THREAD

**Issue by ranjanmangla1** [layer5io/layer5#4481]
### Current Behavior

In the faq accordion, all 4 drop down qna panels can be open at the same time. But this leads to a bad user experience

### Desired Behavior

Only one panel should be open at a time.

### Screenshots / Mockups

![image](https://github.com/layer5io/layer5/assets/93506927/573df6cd-e196-471b-919e-5ec9cbe71b32)

### Acceptance Tests

Please assign me this issue
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ykumar1415** [comment]
@ranjanmangla1 @Chadha93 @vishalvivekm @leecalcote  want to work on this issue. Please assign it to me.

**Comment by iampaandey** [comment]
Please assign this issue to me @ranjanmangla1 @blake @leecalcote @duckling69

**Comment by leecalcote** [comment]
@Ykumar1415 assuming that you were busy working on the other fresh assignment, perhaps we will let @iampaandey  take a crack at this one.

**Comment by ranjanmangla1** [comment]
actually @leecalcote , i wanted to work on this issue, I mentioned in the issue description too!

**Comment by saaagarsingh** [comment]
Hey @ranjanmangla1 are you still working on this? If you need any help feel free to ping me on slack. Happy Contributing😉

**Comment by ranjanmangla1** [comment]
Thank you @saaagarsingh, working on it, will ping you for sure, if any help will be needed
