### ISSUE TITLE
Invisibility of Text in Meet the Meshmate Blog

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4482]
### Description

Currently in the [blog](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma) meet the meshmate : @Yashsharma1911 by @vishalvivekm 

The name of our friendly meshmate isnt available in dark mode.
![Screenshot_20230704-031118-120.png](https://github.com/layer5io/layer5/assets/59855919/1bcb7998-b995-46a5-9c73-9671e20ca047)
### Expected Behavior

His name should be visible

# Possible Fix
- removing the color attribute from interviewee section of [MeetTheMeshMate.style.js](https://github.com/layer5io/layer5/blob/18114f5603813f9ef5ce6c5226028f8715badc61/src/collections/blog/2023/2023-05-24-meet-the-meshmate-yash-sharma/MeetTheMeshMate.style.js?plain=1#L18)
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ykumar1415** [comment]
@Chadha93 @vishalvivekm @leecalcote  want to work on this issue. Please assign it to me.
