### ISSUE TITLE
[Community] Member Profile: Samyak 

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4494]
**Current Behavior**

@samyakshah3008 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @samyakshah3008 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @samyakshah3008
- Twitter: [SamyakShah_18](https://twitter.com/SamyakShah_18)
- LinkedIn: [samyakshah3008](https://www.linkedin.com/in/samyakshah3008/)
- Meshery Cloud: [e89b2a57-6753-4877-9626-7b6a9ddc6b4f](https://meshery.layer5.io/user/e89b2a57-6753-4877-9626-7b6a9ddc6b4f)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@samyakshah3008
Toss in your bio and a link to your profile picture please :)

**Comment by samyakshah3008** [comment]
Hi @vishalvivekm Thanks a lot for recognizing my efforts! 

Here you go: 

**Profile picture link**: https://drive.google.com/file/d/1l9GIeWuH-hLWTlNikeiftdzsJ2f5fQrn/view?usp=sharing 

**Bio:** 

Hey, there! I’m Samyak Shah - An Aspiring Rockstar Engineer from India! I am a second year student, currently undertaking my Bachelor in Computer Science and Engineering. My experience revolves around building full-stack services, DevOps pipelines, Python libraries, cloud infrastructure and special interest in frontend engineering. I am also a passionate open-source contributor and someone who loves to work with communities. I love to share what I learn daily and connect with amazing like-minded new people. Layer5 is my second open source project as a contributor which has given me immense confidence about my work and capabilities. The community is just amazing. Also on a fun note, I love to read self-help books from last bench of University lectures! Let's connect and grow together!

**Comment by RakshitKumar04** [comment]
Hey @vishalvivekm could you please assign this issue to me.

**Comment by RakshitKumar04** [comment]
Yes, I have set up the site locally

**Comment by vishalvivekm** [comment]
> @vishalvivekm Yes, I have set up the site locally

 @RakshitKumar04 There you go

**Comment by RakshitKumar04** [comment]
Hey, @vishalvivekm please take a look.

**Comment by RakshitKumar04** [comment]
Hey, @vishalvivekm what is this DCO check and how should I resolve this?

Should I again make a commit using this command `git commit -s -m “my commit message w/signoff”`

**Comment by Ghat0tkach** [comment]
Congratulations @samyakshah3008 🥳🎉

**Comment by samyakshah3008** [comment]
Cheers! @Ghat0tkach 

> Congratulations @samyakshah3008 🥳🎉

**Comment by roy2pushkar** [comment]
Hey  @vishalvivekm can you please assign me this issue .
