### ISSUE TITLE
Prevent signup using anonymous mail domains

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4498]
#### Current Behavior
Anyone can signup to use MeshMap. Signup is necessary to ensure accountability given the open cluster nature of the Meshery Playground.

- https://layer5.io/cloud-native-management/meshmap
- https://layer5.io/cloud-native-management/meshmap/design
- https://layer5.io/cloud-native-management/meshmap/visualize
- https://layer5.io/cloud-native-management/meshmap/collaborate

#### Desired Behavior
Disallow signups from the following domains:

- @duck.com
- @anonaddy.me
- @protonmail.com
- @tuta.io

#### Implementation
Field validation using javascript and regex.

#### Acceptance Tests
1. Users who signup with any of the domains listed above are not allowed to submit the form.
1. Users who signup with any of the domains listed above are shown the following message:

"Use of the <matching-domain-name-here> is not allowed. Please use a non-anonymous email address / domain. 

The Meshery Playground is connected to live Kubernetes cluster(s) and allows users full-control over those clusters. Requiring users to register a non-anonymous user account keeps the Playground safe and healthy for all to enjoy. Without requiring users to sign-in, the Meshery Playground would allow anonymous access for anyone and everyone to potentially perform nefarious acts. Sign-up to receive a user account, entitled with perpetually free and full access the Playground environment."

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by saaagarsingh** [comment]
Hey @leecalcote I would lik to get my hands working on this.

**Comment by Ykumar1415** [comment]
@leecalcote do you want this to be implemented in backend or frontend ?

**Comment by leecalcote** [comment]
> @leecalcote do you want this to be implemented in backend or frontend ?

See the Implementation section, please.

**Comment by iampaandey** [comment]
@saaagarsingh please ping me on slack if you need any help with this.

**Comment by leecalcote** [comment]
There is another one of these open issues online the meshery/play repo.

**Comment by saaagarsingh** [comment]
@iampaandey Thanks raghav I'll surely ping you if I get stuck. But for now I'm working on it and to my best I'll try to submit the PR by tomorrow.

**Comment by leecalcote** [comment]
FYI - https://github.com/meshery/play/issues/123#issuecomment-1629542010

**Comment by codingmickey** [comment]
Hi @saaagarsingh if you need any help regarding the implementation, feel free to ask me! (as I've just implemented it in the other repo)

**Comment by saaagarsingh** [comment]
@codingmickey surely. I'll ping you

**Comment by ashutosh887** [comment]
@leecalcote 
Please assign me if the issue is still not resolved... I'll be happy to assist

**Comment by leecalcote** [comment]
Additionally, multiple word first and last names should be allowed both with hyphenations and with whitespace.

<img width="608" alt="Screenshot 2023-07-15 at 8 13 58 PM" src="https://github.com/layer5io/layer5/assets/7570704/70ce889e-e8e6-4d56-948b-2e729b416c99">

@ashutosh887, perhaps, you can tackle this last bit.

**Comment by ashutosh887** [comment]
Sure let me check
What do we expect in this @leecalcote ?

**Comment by leecalcote** [comment]
@codingmickey can answer that.
