### ISSUE TITLE
Add XiaoMi/naftis to landscape.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#45]
January 24, 2019 at 09:02PM<br>

**Comment by leecalcote** [comment]
Hi @sevennt, we would love to have naftis added to the service mesh landscape (https://lqyer5.io/landscape). Will you consider creating a PR to do so?

**Comment by rootsongjc** [comment]
@leecalcote Correct https://layer5.io/landscape

**Comment by sevennt** [comment]
Hi @leecalcote, We will create a PR later.

**Comment by leecalcote** [comment]
Fantastic! Thank you, @sevennt.
