### ISSUE TITLE
[UI] Incorrect formatting of the heading 

### ISSUE THREAD

**Issue by Mohith234** [layer5io/layer5#4502]
### Description

 Incorrect formatting of the heading "Full-Time Terms" as a bullet point instead of a main heading in the [LFX programs page](https://layer5.io/programs/lfx)

### Expected Behavior

- The `Full-Time Terms` should be the heading (Not the bullet point) 
- `Spring Term: March 1st - May 31st` should be the first bullet point.
### Screenshots

![image](https://github.com/layer5io/layer5/assets/88539464/de10e571-f0a5-49cf-9050-ed988d1d8dfd)

- Reference image
![image](https://github.com/layer5io/layer5/assets/88539464/1d9551fa-f875-4c8b-b71c-2f7faaad171f)

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vednp** [comment]
Hey @Mohith234 are you going to work on it?

**Comment by Saurav-Pant** [comment]
Please assign it to me, I want to work on it

**Comment by saaagarsingh** [comment]
Hey @Mohith234 I've resolved the issue on all three years 2021, 2022, 2023 pages. Please have a look at my PR.

**Comment by Mohith234** [comment]
@saaagarsingh Please don't raise any PRs unless you get assigned. Please read the contribution guidelines.

**Comment by ashutosh887** [comment]
@Mohith234 I would like to work on this if needed

**Comment by abhijeetgauravm** [comment]
Can I work on it?

**Comment by nakulbh** [comment]
@Mohith234 I want to work on it, can you please assign it to me i have already setted up the project locally

**Comment by abhijeetgauravm** [comment]
> Can I work on it?

@Mohith234
