### ISSUE TITLE
[UI] No dark mode in discuss.layer5.io

### ISSUE THREAD

**Issue by ranjanmangla1** [layer5io/layer5#4505]
### Description

There is no Dark Mode and no dark/light mode toggle in discusstion section in discuss.layer5.io

### Expected Behavior

There should be a dark / light mode toggle switch in the navbar of discuss.layer5.io and no dark mode support is there.

### Screenshots

![image](https://github.com/layer5io/layer5/assets/93506927/c38637e0-5496-4cc8-a9d4-6f2afedd6986)
![image](https://github.com/layer5io/layer5/assets/93506927/38e645a8-c877-41a8-8499-25b00e4c3f9c)

### Environment:
- Host OS: Ubuntu
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ranjanmangla1** [comment]
please assign me this issue, I would love to work on it

**Comment by Savio629** [comment]
There is dark mode already present on discuss.layer5.io
Profile-> Preferences-> Interface

![discussdark](https://github.com/layer5io/layer5/assets/91362589/846a1281-58cb-4122-81e6-ecb0014b2915)

**Comment by ranjanmangla1** [comment]
@Savio629, but from ux point of view this is a bad placement for the dark mode, the dark mode is in profile section, so we can not find easily, it and second, one must login in order to find the light/dark mode toggle switch.
How about we modify this issue to have a dark/light toggle switch on navbar as other layer5 websites have and reopen this issue?

**Comment by thisiskaransgit** [comment]
@Savio629, let's give @ranjanmangla1 a chance to shine here

**Comment by thisiskaransgit** [comment]
Hey @ranjanmangla1, Thank you for your enhancement proposal for the community forum. Some things to keep in consideration here would be that the forum is not a  section of layer5.io, the community forum is created using the discourse framework, which is different from our Gatsby site. You are welcome to work on this, but before that could you please describe how are you going to approach the desired state here?

**Comment by abhijeetgauravm** [comment]
@ranjanmangla1 updates?
