### ISSUE TITLE
[UI] A weird greenish circle appearing in the footer instead of  Brand Logo

### ISSUE THREAD

**Issue by ranjanmangla1** [layer5io/layer5#4507]
### Description

A plain circle is appearing on the footer instead of the Brand Logo in the footer

### Expected Behavior

This section either should be empty or there should be Brand's Logo

### Screenshots

![image](https://github.com/layer5io/layer5/assets/93506927/d03a0863-cef0-4fd5-a3ff-c02b6ce090c9)

### Environment:
- Host OS: Ubuntu
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ranjanmangla1** [comment]
Please assign me this issue, I would love to work on it

**Comment by Ghat0tkach** [comment]
It isn't visible until the screen size is 4k .
Moreover I think its a feature rather than bug🤔 . Maybe @vishalvivek and @thisiskaransgit  could acknowledge this properly 🤔

**Comment by ashutosh887** [comment]
@Ghat0tkach @thisiskaransgit 
I would like to work on this if needed

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, This is intended. The reason for it is to occupy the left space on the larger screens. but thank you for looking into it though.

@Ghat0tkach, Yes you were right 🙌🏼 .

@ashutosh887, Thank you for volunteering but as the behavior is indeed intended, we are not moving ahead with any change, also take a look at our [help-wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+org%3Alayer5labs+label%3A%22help+wanted%22+) labeled issues, and see where you can provide us a helping hand 😎.

**Comment by ranjanmangla1** [comment]
> @ranjanmangla1, This is intended. The reason for it is to occupy the left space on the larger screens. but thank you for looking into it though.
> 
> @Ghat0tkach, Yes you were right 🙌🏼 .
> 
> @ashutosh887, Thank you for volunteering but as the behavior is indeed intended, we are not moving ahead with any change, also take a look at our [help-wanted](https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+org%3Alayer5labs+label%3A%22help+wanted%22+) labeled issues, and see where you can provide us a helping hand sunglasses.

@thisiskaransgit even if it is intended, it looks quite bad, can't we just have some space on the footer, as many good designed websites don't have anything else there. 
Let's say, the green circle is necessary, How about having meshery's logo with less opaque ness there, then that symbol have some meaning. Because for someone who visits site, it looks like there is a bug here.
