### ISSUE TITLE
GSoD : Revive the content navigator for GSoD-2020

### ISSUE THREAD

**Issue by kushthedude** [layer5io/layer5#451]
**Description**

We are in GSoD with the umbrella organisation as CNCF, it would be great to revive the GSoD content.

**Expected Behavior**

In #441, we removed the GSoD links from homepage & footer. We need to revert them back.

---

[Optional] **Additional Context**

See https://github.com/layer5io/layer5/pull/441, also we don't need to add back the MLH Program we just need GSoD back.

**Comment by kushthedude** [comment]
Hey @chandrashritii, would you like to have this fixed?

**Comment by Tanuj22** [comment]
@kushthedude Can I work on this?

**Comment by kushthedude** [comment]
Please go ahead @Tanuj22

**Comment by Tanuj22** [comment]
@kushthedude  I think I need a white logo for the button. Where can I get that? 
![Screenshot from 2020-06-20 01-07-52](https://user-images.githubusercontent.com/42486853/85174400-e975c400-b292-11ea-88bd-68a38b8738e9.png)

**Comment by kushthedude** [comment]
> @kushthedude I think I need a white logo for the button. Where can I get that?
> ![Screenshot from 2020-06-20 01-07-52](https://user-images.githubusercontent.com/42486853/85174400-e975c400-b292-11ea-88bd-68a38b8738e9.png)

^^ @leecalcote

**Comment by leecalcote** [comment]
@Tanuj22 will you give this SVG a try?

https://github.com/layer5io/layer5/blob/master/assets/images/buttons/gsod.svg

**Comment by Tanuj22** [comment]
Yes I am no it
