### ISSUE TITLE
[Handbook] Contribution Guide Update w/Issue etiquette 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4513]
Please summarize the following information as an update with the [Community Handbook](https://layer5.io/community/handbook).

---

              > Guys please don't create PRs until an issue has been assigned to you.

Sound counsel. Don’t get us wrong, we certainly appreciate the enthusiasm, however, confirming assignment, first will avoid heartache in the form of:

1. Issue not qualified: effort put into an invalid issue.
2. Contributor conflict: a bit of stepping on toes and not so kindly pushing others out of the way. Certainly don't want the project to move slowly, but a little bit of kindness goes a long way.
3. Maintainer cycles spent clarifying and assuaging ruffled feathers (hurt feelings).

Regarding where to go from here:
- Is the issue described above valid? _Yes_
- Do we want this issue fixed? _Yes_
- Do we generally assign issues in chronological order of contributor request? _Yes_
- Are there exceptions to that rule? _Yes_
- If yes, when? _When the requesting contributor is 1) unqualified, or 2) unavailable or incapable of delivering in a timely fashion, or 3) missing too much context and whereas another contributor already has that context, or 4) when a requesting contributor already has one or more other open assignments._

@Saksham294, will you do me a favor and place this info into an FAQ and/or section of the Community Handbook?

@RakshitKumar04, since you have an open PR and the issue is valid, we'll move forth with your assignment. Take note of @Saksham294's counsel for future reference, if you would, please. My counsel is to take a moment to soften your phrasing; too apply a touch of kindness in your interactions.

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/4492#issuecomment-1627561901_

**Comment by Saksham294** [comment]
Sure @leecalcote I'll finish it by the end of the day.

**Comment by leecalcote** [comment]
Thank you

**Comment by Ghat0tkach** [comment]
Shall we also add this in PR template as well?🤔 .
Most of the times , newcomers in the zeal of enthusiasm to Contribute will skip reading the essential community handbook .

**Comment by Saksham294** [comment]
<img width="1116" alt="Screenshot 2023-07-09 at 11 08 27 PM" src="https://github.com/layer5io/layer5/assets/86240862/c76b5fad-195d-41f7-af97-87cdbd62a3d5">

Hey @leecalcote check if this looks good, thanks. And apologies for not fixing the triage and PR review, I was about to do that but got late, really sorry.

**Comment by leecalcote** [comment]
> Shall we also add this in PR template as well?🤔 @leecalcote Most of the times , newcomers in the zeal of enthusiasm to Contribute will skip reading the essential community handbook .
> 
> A simple crisp and short in the PR A checkbox
> 
> * [ ]  This issue is assigned to me

Great suggestion. Although, for a number of reasons, let’s skip the inclusion of this checkbox. Ask me in one of the meetings and I’ll explain, if you like.

**Comment by Ghat0tkach** [comment]
> > Shall we also add this in PR template as well?🤔 @leecalcote Most of the times , newcomers in the zeal of enthusiasm to Contribute will skip reading the essential community handbook .
> > A simple crisp and short in the PR A checkbox
> > 
> > * [ ]   This issue is assigned to me
> 
> Great suggestion. Although, for a number of reasons, let’s skip the inclusion of this checkbox. Ask me in one of the meetings and I’ll explain, if you like.

Thank you , I would love to discuss it in one of our meetings.
