### ISSUE TITLE
[UI]: unwanted {" "} in blog content

### ISSUE THREAD

**Issue by samyakshah3008** [layer5io/layer5#4521]
### Description

There is unwanted {" "} at couple of parts in the blog post of https://layer5.io/blog/community/meet-the-fall-interns-of-2021

### Expected Behavior

Let's remove them.

### Screenshots

![image](https://github.com/layer5io/layer5/assets/86982322/3749fb03-edf0-4169-bdae-988b53401dd4)

![image](https://github.com/layer5io/layer5/assets/86982322/c3a4aa12-b23b-4b40-b32d-74e9e1d15ad6)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ranjanmangla1** [comment]
would love to work on it, please assign me this issue

**Comment by k0T0z** [comment]
Now the PR is ready for u, kindly check for any other modifications

**Comment by samyakshah3008** [comment]
Thanks for showing the passion gents, following the chronological order, I would like to first ask @depleur that have you setup layer5 repo locally? Then I would like to assign you. 
Please answer this same question @VALiUMgithub and @ranjanmangla1

**Comment by samyakshah3008** [comment]
Hi @k0T0z thanks for showing the passion and quickly working on the issue ticket even without getting assigned. I would like to request you that please follow the contributing guidelines of layer5. Any contributor can raise a PR only after getting assigned to it. @vishalvivekm can you please have a look here and guide me the next steps?

**Comment by ranjanmangla1** [comment]
yes @samyakshah3008

**Comment by k0T0z** [comment]
oooh @samyakshah3008, very sorry for that, didn't know actually. It's my first time working for an Org that assigns tasks first. Feel free to discard it if u want and also feel free to assign tasks for me.

**Comment by depleur** [comment]
> Thanks for showing the passion gents, following the chronological order, I would like to first ask @depleur that have you setup layer5 repo locally? Then I would like to assign you. Please answer this same question @VALiUMgithub and @ranjanmangla1

Hey. Yes, I can start working on this right now.

**Comment by vishalvivekm** [comment]
It is certainly important to request assignment before starting work on an issue if there is no assignee.
@k0T0z, I understand that you may not have had the chance to go through the [contributing guidelines](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook). 
Please go through these documents and I hope you'll keep them in mind for future.

**Comment by depleur** [comment]
@samyakshah3008 Can I start working on this now?

**Comment by depleur** [comment]
I was about to raise a PR for this issue when I found that the `{" "}` string appeared in a lot of files in this repo. I haven't seen anything like it so I just wanted to make sure it's something that's routine. Is something wrong? Was this intentional?

**Comment by abhijeetgauravm** [comment]
This Issue has been resolved?

**Comment by abhijeetgauravm** [comment]
Can I work on this issue?

**Comment by abhijeetgauravm** [comment]
@samyakshah3008 @thisiskaransgit I would like too fix it!
