### ISSUE TITLE
[UI] Typo in layer5.io/careers page.

### ISSUE THREAD

**Issue by sakibian** [layer5io/layer5#4522]
### Description
There is a typo in layer5.io/careers - Layer5 Culture Section

### Expected Behavior
pri- oritize to prioritize

### Screenshots
![image](https://github.com/layer5io/layer5/assets/40847839/9a97ad71-42d2-49d2-ba38-51a228b06019)

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sakibian** [comment]
Can I get assigned to this? @leecalcote

**Comment by leecalcote** [comment]
Sounds good, @sakibian

**Comment by abuharish02** [comment]
If no one is working kindly assign to me.
