### ISSUE TITLE
[UI] In layer5/learn Carousel arrows are not aligned properly.

### ISSUE THREAD

**Issue by Modern-artist** [layer5io/layer5#4525]
### **Description:** 
 In layer5/learn page slick-slider(carousel) arrows are not aligned properly.

**Desired State:** 
Arrow would be on center and bigger too.
**Screenshot**
<img width="1440" alt="Screenshot 2023-07-11 at 9 05 41 AM" src="https://github.com/layer5io/layer5/assets/90668597/9a8e55eb-d8a8-497e-a019-b7832dfcf044">

**Evironment:**
Host OS: macOS
Browser: Firefox
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Modern-artist** [comment]
Can I get assigned to this? @leecalcote

**Comment by Harsh-2004** [comment]
Can I get assigned as well

**Comment by Saksham294** [comment]
On a FCFS basis, @Modern-artist go ahead. 
You can have a look at other issues @Harsh-2004
