### ISSUE TITLE
Add Catalog assets to Layer5 brand page.

### ISSUE THREAD

**Issue by goldfishdolphin** [layer5io/layer5#4529]
### Current Behavior

Currently there are no assets of catalog projects. 

https://layer5.io/company/brand

### Desired Situation

There is a need to add catalog assets such as logos and Color scheme to Layer5 brand [page](https://layer5.io/company/brand).

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by saaagarsingh** [comment]
Hey @leecalcote @thisiskaransgit @Chadha93 if this issue is valid and needs to resolved then I think we will need to have some figma desings prepared for the update. What's you thought on this? If improvement is needed I'm ready to complete the work.

**Comment by goldfishdolphin** [comment]
> Hey @leecalcote @thisiskaransgit @Chadha93 if this issue is valid and needs to resolved then I think we will need to have some figma desings prepared for the update. What's you thought on this? If improvement is needed I'm ready to complete the work.

@saaagarsingh you can get designs from Figma as they already exist.

**Comment by leecalcote** [comment]
Thank you, @goldfishdolphin 👍

**Comment by xiaor2** [comment]
Hi @leecalcote @saaagarsingh, I am willing to work on this problem. Can you assign me?

**Comment by goldfishdolphin** [comment]
> Hey by catalog asset you mean all the logos on catalog landing page, that's available on figma? @goldfishdolphin @leecalcote

Yes it is.

**Comment by ayushsinha25** [comment]
Ah...ok...so can you assign me the issue?

**Comment by xiaor2** [comment]
Hi @goldfishdolphin, can I have more information about the catalog assets?
Figma didn't give the specific design.
![image](https://github.com/layer5io/layer5/assets/80271418/fc162b62-7042-4913-90fa-d08ca74802e8)

**Comment by xiaor2** [comment]
Hi @saaagarsingh, is this the design for catalog? And I didn't see the design for where to put the catalog and how it should look like in the Figma. I checked the company page in Figma, and I found nothing about it. Which page do you suggest I should look into? Thanks.
![image](https://github.com/layer5io/layer5/assets/80271418/d1554899-5920-42b8-baf6-dd809a1849ba)

**Comment by Tabhi109** [comment]
@HetviSoni  Please assign this task to me

**Comment by HetviSoni** [comment]
> @HetviSoni Please assign this task to me

Thank you for coming up and showing interest to solve the issue. But as you can see it is already assigned to @xiaor2 , so let us give good enough time to come up with a pr. Meanwhile, you can look up for other issues.

**Comment by xiaor2** [comment]
Hi @goldfishdolphin @leecalcote, I added the catalog part to the website. But I put the assets for layer5 for now because I didn't find the catalog assets design in the Figma. Would you tell me where can I find it?

Fixed Demo:
![image](https://github.com/layer5io/layer5/assets/80271418/38aac870-1ba7-4800-95b8-dbd2d2f31fb1)

No catalog assets design on Figma:
![image](https://github.com/layer5io/layer5/assets/80271418/6f3635a2-a7f9-47e9-8e93-382081410148)

**Comment by xiaor2** [comment]
I added the catalog assets to the website, and I will make a pull request later.

Since there is no "catalog kit" in the `"./src/assets/brand"` folder, the download link is not working yet. I can change the link once the kit is uploaded,

**Comment by goldfishdolphin** [comment]
> 

@xiaor2 I have tagged you Figma page where we have catalog logos. https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=10869-15222&mode=design&t=W3lzKGhuuKXwhByP-0
<img width="200" alt="catalog page" src="https://github.com/layer5io/layer5/assets/98129474/022cea48-5f4f-4f8b-8cab-c85f304572c7">

**Comment by xiaor2** [comment]
> > 
> 
> @xiaor2 I have tagged you Figma page where we have catalog logos. https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=10869-15222&mode=design&t=W3lzKGhuuKXwhByP-0 <img alt="catalog page" width="200" src="https://user-images.githubusercontent.com/98129474/253903809-022cea48-5f4f-4f8b-8cab-c85f304572c7.png">

Great. Thanks for the clarification.

**Comment by xiaor2** [comment]
Hi @leecalcote @saaagarsingh, I made a pull request. #4563 
Let me know if you have any feedbacks.

Do you have any suggestions about the kit? Should I just pack all the logos and put it in the `"./src/assets/brand"` folder?

**Comment by leecalcote** [comment]
@Rexford74 @goldfishdolphin @Shivam-AfA please offer your reviews, if you would.

**Comment by Ghat0tkach** [comment]
closed as completed through PR #4563
