### ISSUE TITLE
[UI]: Overflowing of project-page-wrapper in page of layer5/projects

### ISSUE THREAD

**Issue by Modern-artist** [layer5io/layer5#4533]
### Description:
Overflowing of project-page-wrapper in page of layer5/projects which affects navbar and footer too.

### Expected Behavior
Solve Overflowing of project-page-wrapper which will change nav and footer overflow issue.

### Screenshots
<img width="909" alt="Screenshot 2023-07-12 at 10 34 01 AM" src="https://github.com/layer5io/layer5/assets/90668597/d7eb2ad2-346a-4dae-8da1-4b67da367ad8">

### Environment:
- Host OS: iOS (ipad)
- Browser: firefor

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Modern-artist** [comment]
I would like to resolve this issue @leecalcote @Saksham294 please assign it to me.

**Comment by Saksham294** [comment]
Considering that you will make changes to dimension properties I think  those changes will affect rest of the website /components properties but go ahead

**Comment by Modern-artist** [comment]
@Saksham294 check it out.

**Comment by Modern-artist** [comment]
@Saksham294 close this issue as i have already solved it in different issue.
