### ISSUE TITLE
Add a quote to the Layer5.io/community page

### ISSUE THREAD

**Issue by kayceeDev** [layer5io/layer5#4536]
### Desired Situation
We want to include a comment by community member @priyanshu-kun in the [discuss forum](https://discuss.layer5.io/t/can-someone-explain-me-what-this-meshery-or-none-provider-mean-here/3107/2) as a quote in the [layer5.io/community](https://layer5.io/community) page.

> " Wow, you're incredibly helpful, I wish every open-source community is as friendly as yours."

Be creative and add it to a suitable position.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Yana-Gupta** [comment]
@kayceeDev can you assign me to this issue.

**Comment by leecalcote** [comment]
@Yana-Gupta or @kayceeDev will you open a similar issue on https://github.com/meshery/meshery.io for adding this quote on the /community page, too? [See mockup](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16580-40239&mode=design&t=8zljk0lV92gX8jUQ-4), if helpful. // @Rexford74

**Comment by leecalcote** [comment]
> @kayceeDev can you assign me to this issue.

@Yana-Gupta, here's what you mean to say: "will you assign this issue to me?"

**Comment by Yana-Gupta** [comment]
> > @kayceeDev can you assign me to this issue.
> 
> @Yana-Gupta, FYI, here is the proper grammar of what you mean to ask: "will you assign this issue to me?"

Thank you pointing out the grammar correction. To clarify, @kayceeDev, could you please assign this issue to me? Thank you in advance.

**Comment by Yana-Gupta** [comment]
> @Yana-Gupta or @kayceeDev will you open a similar issue on https://github.com/meshery/meshery.io for adding this quote on the /community page, too? [See mockup](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16580-40239&mode=design&t=8zljk0lV92gX8jUQ-4), if helpful. // @Rexford74

ok, I am will open the issue

**Comment by kayceeDev** [comment]
> > > @kayceeDev can you assign me to this issue.
> > 
> > 
> > @Yana-Gupta, FYI, here is the proper grammar of what you mean to ask: "will you assign this issue to me?"
> 
> Thank you for pointing out the grammar correction. To clarify, @kayceeDev, could you please assign this issue to me? Thank you in advance.

It's already assigned to you. @leecalcote please clarify if the name of the person who made the comments should be included in the quote.
