### ISSUE TITLE
[Case Study] HPE: Low contrast of text in dark mode

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4538]
### Description
This case study has text that is not styled for either light and dark mode - https://layer5.io/resources/cloud-native/hpes-adoption-of-meshery-and-meshmap

### Expected Behavior
Styles applied here are theme-friendly - https://github.com/layer5io/layer5/blob/master/src/collections/resources/articles/hpes-adoption-of-meshery-and-meshmap/hpe.style.js

Read the CONTRIBUTOR.md for information about theme and light/dark mode treatment.

### Screenshots
<img width="1150" alt="Screenshot 2023-07-13 at 8 34 13 AM" src="https://github.com/layer5io/layer5/assets/7570704/3b2e10d2-da59-456d-bd2c-3a9940be8ce6">
<img width="1155" alt="Screenshot 2023-07-13 at 8 34 21 AM" src="https://github.com/layer5io/layer5/assets/7570704/5b7e8140-1bd0-48a0-8b3d-0cba28ac8ccd">

### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by HetviSoni** [comment]
I would like to work on this issue.

**Comment by bupd** [comment]
I am confident that I can resolve issue #4538. I would like to be assigned to this issue.

**Comment by Tabhi109** [comment]
@leecalcote , please assign the current issue to me , I am confident that I can solve this issue #4538

**Comment by leecalcote** [comment]
@Tabhi109, oh, excellent. Thank you for volunteering. As @HetviSoni works through this (hopefully by end of tomorrow), here is another concern with this case study:

It is supposed to be under a "case-studies" folder and "case study" category, not under the “cloud native” category. https://github.com/layer5io/layer5/blob/master/src/collections/resources/articles/hpes-adoption-of-meshery-and-meshmap/index.mdx#L10

Will you please create an issue for this concern and in a PR create the new folder **AND** create a redirect from the current location to the new location, so that no existing links to this case study break?

**Comment by shivm29** [comment]
Hey! Can you assign this to me?

**Comment by Shashank2104125** [comment]
@leecalcote please assign this issue to me.
