### ISSUE TITLE
[Case Study] HPE miscategorized

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4539]
### Issue

> @Tabhi109, oh, excellent. Thank you for volunteering. As @HetviSoni works through this (hopefully by end of tomorrow), here is another concern with this case study:
> 
> It is supposed to be under a "case-studies" folder and "case study" category, not under the “cloud native” category. https://github.com/layer5io/layer5/blob/master/src/collections/resources/articles/hpes-adoption-of-meshery-and-meshmap/index.mdx#L10
> 
> Will you please create an issue for this concern and in a PR create the new folder **AND** create a redirect from the current location to the new location, so that no existing links to this case study break?
> 

_Originally posted by @leecalcote in https://github.com/layer5io/layer5/issues/4538#issuecomment-1634972840_

### Acceptance Criteria:
1. New "Case Study" category shows in the /resources filters.
2. HPE case study is relocated to new folder and recategorized.
3. A redirect is in place for the old location.

**Comment by leecalcote** [comment]
@Tabhi109 FYI

**Comment by Yana-Gupta** [comment]
@leecalcote I would like to work on this issue. Can you assign me.

**Comment by vrinda-mahajan** [comment]
@leecalcote can you please assign this issue to me? I am confident that I can solve this issue.

**Comment by Shashank2104125** [comment]
@leecalcote I would like to work on this issue. Can you please assign it me?

**Comment by Shivam-AfA** [comment]
@vrinda-mahajan Thank you for asking to volunteer here. I apologise that I didn't realise this issue was open, so I opened a PR for this. I'll look for some other issues for you where you can showcase your skills. 😀

**Comment by vrinda-mahajan** [comment]
> @vrinda-mahajan Thank you for asking to volunteer here. I apologise that I didn't realise this issue was open, so I opened a PR for this. I'll look for some other issues for you where you can showcase your skills. 😀

No worries, I was about to raise a PR.
