### ISSUE TITLE
Events and Workshops listed in random order

### ISSUE THREAD

**Issue by Shashank2104125** [layer5io/layer5#4546]
### Description

The 'Events and Workshops' tab section on the Events page does not follow the correct order, as it does not display the most recent events or workshops in the first position. Instead, they are listed randomly. 
### Expected Behavior

They should be listed according to their dates i.e., the most recent event comes first.
### Screenshots

![Screenshot (92)](https://github.com/layer5io/layer5/assets/97789487/584c123f-9d5e-4dc6-a412-b7cd8cd49ccc)

![Screenshot (91)](https://github.com/layer5io/layer5/assets/97789487/95fc06e6-0796-45d3-8c28-f9615d358569)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Shashank2104125** [comment]
I would like to work on this issue.

**Comment by GitsOfVivek** [comment]
can i work on this issue?

**Comment by Savio629** [comment]
The issue is with Events and Workshop Tab.
All and Meetups is following proper order.
@Shashank2104125 While you are on it, the button shadows on hovering is inconsistent in All, Events, Workshop and Meetups tab.
@GitsOfVivek You can look for more issue in mean time :)

**Comment by abhijeetgauravm** [comment]
Can I work on this issue?

**Comment by GitsOfVivek** [comment]
@Savio629 I asked first for this issue. its my first contribution in open source. can you please let me do?

**Comment by Savio629** [comment]
@GitsOfVivek Sorry I missed your message
@abhijeetgauravm You can check for some other issues

**Comment by GitsOfVivek** [comment]
@Savio629 hey, I did a PR. can you check?
