### ISSUE TITLE
Restructure internship Programs buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#455]
**Current Behavior**
In [index.html](https://github.com/layer5io/layer5/blob/master/index.html), the following buttons are defined and shown:

<img width="778" alt="Screen Shot 2020-06-24 at 7 34 39 PM" src="https://user-images.githubusercontent.com/7570704/85642825-2279b400-b658-11ea-84a4-ab4767fe3af3.png">

**Desired Behavior**

Rearrange like so:

![Screen-Shot-2020-06-24-at-7 34 39-PM](https://user-images.githubusercontent.com/7570704/85643285-4be70f80-b659-11ea-8844-58f0260f223f.gif)

**Comment by Neilblaze** [comment]
@leecalcote can you assign me this?

**Comment by NupurThakur27** [comment]
Hey @Neilblaze, It would be great if you work on it. Also from next time Feel free to self assign any issue. :smiley:

**Comment by leecalcote** [comment]
Awesome. Thank you for jumping in, @Neilblaze. As you dig in here, I encourage you to join the Layer5 community - http://slack.layer5.io. Say "hi" when you do. 😄

**Comment by Neilblaze** [comment]
Sure, would love to 😃 @NupurThakur27 .

**Comment by crustyy** [comment]
Is anyone working on this issue?

**Comment by Neilblaze** [comment]
@crustyy I'm :)

**Comment by HeroicHitesh** [comment]
@leecalcote I just checked the website and this issue seems to be resolved, although I am not sure in which PR it's resolved, I guess this is no longer a relevant issue and hence can be closed. Correct me if I am wrong.

**Comment by leecalcote** [comment]
@HeroicHitesh thank you for looking into this. You're right that this issue has essentially been resolved. We're in the process of transitioning this site from Jekyll to Gatsby (see previews at https://layer5ng.netlify.app/). Each of these buttons and program descriptions need to be migrated to this new site (see the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng) in this repo).

**Comment by leecalcote** [comment]
There are a number of other issues up for grabs that might be of interest. Please don't be shy. 👍
