### ISSUE TITLE
[Community] Member Profile: Harsh Dobariya

### ISSUE THREAD

**Issue by samyakshah3008** [layer5io/layer5#4556]
**Current Behavior**

@HarshDobariya79 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @HarshDobariya79  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @HarshDobariya79
- Twitter: HarshDobariya79
- LinkedIn: harshdobariya79
- Meshery Cloud: 27ba20ed-4012-490e-ab2e-a937173283c4
- Link to profile picture: https://drive.google.com/file/d/1Mru2IfCGvXQ0sMV2u0XTN7DGQVMWFRK_/view

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by samyakshah3008** [comment]
@HarshDobariya79
Toss in your bio please :)

**Comment by devarsh10** [comment]
Hey @samyakshah3008, I would like to work on this.

**Comment by vishalvivekm** [comment]
Thanks @devarsh10

**Comment by HarshDobariya79** [comment]
> @HarshDobariya79 Toss in your bio please :)

Gujarat, India

Hey there! I'm a dedicated full-stack developer and DevOps enthusiast currently pursuing a Bachelor's degree in Computer Science and Engineering. My passion lies in unraveling intricate problems and creating innovative solutions that transcend the boundaries of conventional thinking. I find great joy in contributing to open-source projects, knowing that my work can positively impact the wider tech community. Collaboration is at the core of my approach, and I thrive in team environments, sharing knowledge and learning from others. As I continue to expand my skills and knowledge, I'm eager to make a lasting mark in the world of technology, leaving behind a legacy of excellence and ingenuity.

**Comment by abhijeetgauravm** [comment]
Has this issue been done?

**Comment by abhijeetgauravm** [comment]
Can I work on it @vishalvivekm ?
