### ISSUE TITLE
Hovering Built-In Integrations Card Buttons text black

### ISSUE THREAD

**Issue by vaibhav-xt** [layer5io/layer5#4568]
### Description

Build In Integration Page bottom, second card color change to black on hovering. 

Idle:
![Screenshot (22)](https://github.com/layer5io/layer5/assets/90946899/a50fb76c-84b7-4b58-afb1-44aa58b04715)
![Screenshot (19)](https://github.com/layer5io/layer5/assets/90946899/cbc99efb-47d5-40ee-b196-90bc8084da39)

### Expected Behavior

It must look like the first card. 

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shivankurchavan** [comment]
please assign me this issue

**Comment by leecalcote** [comment]
Is this issue only occurring on this page and not on the same button component on other pages?

**Comment by shivankurchavan** [comment]
@leecalcote I've understood your question. I'll make sure to check everything. 

@vaibhav-xt please share the link where the issue is occurring. Thank you.

**Comment by vishalvivekm** [comment]
> @leecalcote I've understood your question. I'll make sure to check everything.
> 
> @vaibhav-xt please share the link where the issue is occurring. Thank you.

https://layer5.io/cloud-native-management/meshery/integrations

**Comment by SainiAditya1** [comment]
@shivankurchavan are you working on this issue if not I would like to do this.

**Comment by shivankurchavan** [comment]
> @shivankurchavan are you working on this issue if not I would like to do this.

My apologies for the delay, it took me a while to understand the setup and functions as it is my first contribution. I'll get it done in a day or two. Sorry for the delay. 
Thank you for your support.

**Comment by vaibhav-xt** [comment]
@shivankurchavan today please be there in a meeting at 7:30pm. I'll try to put my points otherwise I'll share them with you.

**Comment by vaibhav-xt** [comment]
The issue required clear objectives and clarification. As I didn't get a chance in the meeting to put my agenda. 

@leecalcote  & @vishalvivekm  what is your opinion?
 My opinion is to close this issue by making a pull request via @shivankurchavan. Will raise another issue for this issue as button enhancement. I found thorough out the websites on hovering yellow buttons text color turns to white and not following Figma design. Check out Figma design which also said to make it rounded for the mobile section.
