### ISSUE TITLE
Navbar hovering effect highlights two elements simultaneously

### ISSUE THREAD

**Issue by saaagarsingh** [layer5io/layer5#4570]
### Description
Currently on hovering or clicking over projects in navbar highlights both Solutions and Projects together(Particularly with green color).

### Expected Behavior
It should highlight only a single element at once.

### Screenshots
Problem:
![navbarIssue1](https://github.com/layer5io/layer5/assets/85694019/1f4ee996-42d8-4704-8c71-ad5235055a3a)

Expected behaviour:

![navbarIssue2](https://github.com/layer5io/layer5/assets/85694019/58ed3407-afa8-44cb-af1d-ab31b42d4250)

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
This is a bug ✔️ and ideally, should be fixed. Thank you, @saaagarsingh

**Comment by Modern-artist** [comment]
Assign it to me @leecalcote as I have pointed it earlier.

**Comment by nakulbh** [comment]
Can you assign this bug to me @leecalcote, I am new to the commutnity and looking for contributions

**Comment by hirentimbadiya** [comment]
assigning FCFS wise to @Modern-artist , @nakulbh you can find other issues in the community.

**Comment by leecalcote** [comment]
155 "help wanted" issues - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by mihir2226** [comment]
i would like to work on this isssue @leecalcote

**Comment by leecalcote** [comment]
@mihir2226 good! Will you please review the open PR on this issue?

**Comment by mihir2226** [comment]
> @mihir2226 good! Will you please review the open PR on this issue?

Okay this is my slime reviewing. So I give my best :)
