### ISSUE TITLE
[Site] Move badge to separate list

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4573]
### Description
These badges are not in sets of list.
At - https://layer5.io/community/handbook/recognition

### Expected Behavior
Separate them. Move them into two lists. 
The two sets of badges need to be separated into two lists. Also, fix the typo in GitOPs, and make P a small case.

Set 1 name - Activity badges:
1. Design Pioneer
2. Application Pioneer
3. Sharing is caring
4. First design
5. Shipped
6. Need for speed
7. Hip Hacker
8. Streamer
9. GitOps with friends

Set 2 name - Projects:

1. Image Hub
2. MeshMap
3. Service Mesh Performance
4. Community
5. Meshery
6. Meshery Operator
7. Patterns
8. Landscape
9. Writer’s Program
10. Nighthawk
11. UI/UX
12. Meshery Catalog
13. Docker Extension
14. Meshery Docs

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ayushsinha25** [comment]
You may assign this to me

**Comment by leecalcote** [comment]
Hi @ayushsinha25, best to ask @Chadha93.

**Comment by leecalcote** [comment]
I'll assign on his behalf, so that you might start working on it straight away.

**Comment by nakulbh** [comment]
Can I also work on this @leecalcote ?

**Comment by abhijeetgauravm** [comment]
Can I work on it?

**Comment by leecalcote** [comment]
This is a small item. I'll assign @abhijeetgauravm and @nakulbh and warn you all that you're likely to step on each others toes. @Chadha93 will review the first PR up and will accept the first one that accomplishes the task.

**Comment by Chadha93** [comment]
:runner: @abhijeetgauravm @ayushsinha25 @nakulbh

**Comment by ayushsinha25** [comment]
> @ayushsinha25 how's it coming along? 
Trying...but having some problem with Gatsby and local website setup..."make file" causing some issue but am fine if someone does it before

**Comment by nakulbh** [comment]
@Chadha93 How do you want it to look like, I am not able to understand can you please explain.

**Comment by Chadha93** [comment]
> @Chadha93 How do you want it to look like, I am not able to understand can you please explain. Do I have to seprate GitOps and Friends in a list and First Collaborator in another list

@nakulbh @abhijeetgauravm, The two sets of badges need to be separated into two lists. Also, fix the typo in GitOPs, and make P a small case.

Set 1 name - Activity badges:
1. Design Pioneer
2. Application Pioneer
3. Sharing is caring
4. First design
5. Shipped
6. Need for speed
7. Hip Hacker
8. Streamer
9. GitOps with friends

Set 2 name - Projects:

1. Image Hub
2. MeshMap
3. Service Mesh Performance
4. Community
5. Meshery
6. Meshery Operator
7. Patterns
8. Landscape
9. Writer’s Program
10. Nighthawk
11. UI/UX
12. Meshery Catalog
13. Docker Extension
14. Meshery Docs

**Comment by Chadha93** [comment]
@nakulbh @abhijeetgauravm Just rearrangement and typo fix required here.
