### ISSUE TITLE
 Add a quote to the Layer5.io/community/community-managers page

### ISSUE THREAD

**Issue by kayceeDev** [layer5io/layer5#4579]
### Desired Behavior
We want to include a quote in the [layer5.io](https://layer5.io)  `/community/community managers` page.

> "Thank you so much for your kind words. I absolutely love this community"

See similar merged PR for reference #4562 

### Screenshots / Mockups
[See Mockup](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=16580-40239&mode=design&t=8zljk0lV92gX8jUQ-4)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vrinda-mahajan** [comment]
Hey, @kayceeDev can you assign it to me?

**Comment by kayceeDev** [comment]
> Hey, @kayceeDev can you assign it to me?
sure

**Comment by vrinda-mahajan** [comment]
Can you clarify whether I need to include a person's name and designation in this quote? @kayceeDev

**Comment by kayceeDev** [comment]
You don't need to include person's name or designation
