### ISSUE TITLE
[Community] Member Profile: Hetvi

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4594]
**Current Behavior**

@HetviSoni has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @HetviSoni as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @HetviSoni 
- Twitter: 
- LinkedIn: [hetvi-soni-46a99b1b6](https://www.linkedin.com/in/hetvi-soni-46a99b1b6/)
- Meshery Cloud: [fdac414b-613e-4213-aca8-5be83d3e4a56](https://meshery.layer5.io/user/fdac414b-613e-4213-aca8-5be83d3e4a56)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Dhirendra012** [comment]
Hi @vishalvivekm,
I want to work on this. Please assign me.

**Comment by vishalvivekm** [comment]
Thanks @dhirendra012

@HetviSoni Please toss in your bio, twitter and profile picture links, if you would :)

**Comment by HetviSoni** [comment]
Yes sure..Thank you for inviting me @vishalvivekm 

This is the required info @Dhirendra012 
Location: Gujarat, India
Twitter : I don't use 😅
bio:  Hi...I'm Hetvi Soni, an undergrad student at IIIT Vadodara majoring in Computer Science and Engineering.  I am a full-stack developer, always excited to contribute to open-source projects. I enjoy participating in hackathons and being a member of diverse communities. I have learned a lot while contributing to projects at Layer5 and interacting with community members. It has been an amazing experience.
I love connecting with different people so feel free to hit me up on my social handles.
Link to profile picture: https://drive.google.com/file/d/1d8B8pnezuKP8mLbxodU9MJQX5nmd41FJ/view?usp=sharing

**Comment by nakulbh** [comment]
hey @vishalvivekm @leecalcote  can i work on it ?
