### ISSUE TITLE
[Community] Member Profile: Vikramaditya

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4607]
**Current Behavior**

@Ghat0tkach has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Ghat0tkach as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Ghat0tkach 
- Twitter: [sarcasvik](https://twitter.com/sarcasvik)
- LinkedIn: [vikram1612](https://www.linkedin.com/in/vikram1612/)
- Meshery Cloud: [b0442e44-1d89-410e-a51b-8dc2b9e0c92e](https://meshery.layer5.io/user/b0442e44-1d89-410e-a51b-8dc2b9e0c92e)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@Ghat0tkach 
Please toss in your bio and the link to your profile picture.

**Comment by Chat-Ritik** [comment]
@vishalvivekm  Can this issue be assigned to me?

**Comment by Saksham294** [comment]
Sure @Chat-Ritik

**Comment by Ghat0tkach** [comment]
Thanks again @vishalvivekm  , Im grateful for this!
Hey @Chat-Ritik  , 
Below is my bio , I'll provide my profile pic soon.

##

Name:Vikramaditya Singh
Location: Singrauli , Madhya Pradesh

##

Greetings! I am truly passionate about technology and currently pursuing my undergraduate degree at Jabalpur Engineering College. My focus areas are Artificial Intelligence and Data Science, which are incredibly fascinating and full of possibilities!

I absolutely love exploring different technologies, especially the exciting world of cloud-native concepts. With immense appreciation, I want to thank Layer5 for being the beacon of guidance throughout my learning journey, offering invaluable help and resources.

Regarding programming, I have a solid grasp of Java, JavaScript, and React, and I've also explored the realms of Flutter, GraphQL, and Node.js - all of which have added a pinch of magic to my coding adventures.


But beyond technical skills, my greatest asset is my unwavering determination. It drives me to conquer new challenges and continually improve my abilities in the vast realm of technology.

Being part of this amazing community fills my heart with so much gratitude I'm genuinely excited about embracing every opportunity that comes my way. If you're a fellow newcomer driven by enthusiasm and zeal to contribute and learn, I'd be more than happy to help kickstart your journey!

🚀 Let's soar together into the wondrous and meshy world of Meshery!

**Comment by Ghat0tkach** [comment]
Hey @Chat-Ritik 

Here is the link of my profile pic
https://drive.google.com/file/d/1Hhza48JnHhXB-pxNOk4omUoHjUerpOCQ/view?usp=drivesdk
