### ISSUE TITLE
[Site] Update the /projects routes to /products

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4610]
### Description
Recently we switched from projects to products, and the routes (URL path) were not updated. 

### Expected Behavior
Please update all the /projects to /products in the site, and ensure sure by testing and visiting all the products/projects. 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hirentimbadiya** [comment]
I'd like to fix this. in first line @Chadha93 you mean to say from projects to products right ?

**Comment by hirentimbadiya** [comment]
@Chadha93, I'm facing difficulties building a website on my system. Even after running the "make clean" command, I keep encountering a Gatsby cache error. Additionally, there's a branch conflict problem. I'm going to assign this issue to @Cvr421. I'm feeling disappointed that I haven't been able to resolve it myself.

**Comment by hirentimbadiya** [comment]
> Hii @Chadha93 Can i work on this .

@Cvr421, you can work on this issue.

**Comment by Cvr421** [comment]
ok Thanks @hirentimbadiya . i'll start working on this.

**Comment by Cvr421** [comment]
Hii @Chadha93  actually I am getting multiple error while running make site command because of my ubuntu operating system and I am trying to solve the issue . till then I  would like to assign the issue  to the other volunteer @H-a-rshit to save time  .

**Comment by Ghat0tkach** [comment]
> Hii @Chadha93 actually I am getting multiple error while running make site command because of my ubuntu operating system and I am trying to solve the issue . till then I would like to assign the issue to the other volunteer @H-a-rshit to save time .

Hey @Cvr421  , I'll advise you to look up in discuss.layer5.io for solutions .

**Comment by Ghat0tkach** [comment]
Assigning it to @H-a-rshit

**Comment by Yana-Gupta** [comment]
Hi @Chadha93 , @Ghat0tkach I want to work on this issue, if noone is working.

**Comment by Ghat0tkach** [comment]
I have checked @H-a-rshit activity and he haven't been active since a week . This is something urgent and needed to be fix soon
@Yana-Gupta  , there you go
