### ISSUE TITLE
[Site] Design a new page for Layer5 products

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4611]
### Current Behavior
Currently, we don't have a user-facing design page for products. The previous projects page is being used for now. 

### Desired Behavior
Design a new professional products page for layer5.io/products. 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by DarrenDsouza7273** [comment]
@Chadha93 any reference material ?

**Comment by vermabraj** [comment]
@Chadha93  @leecalcote i want to work on the issue

**Comment by 4ddx** [comment]
@Chadha93 I'd be happy to work on this, could you please assign this to me?
 Also please provide more details on how the site's supposed to look.

**Comment by Chadha93** [comment]
Thanks for volunteering everyone, @Modern-artist and @Rexford74 are currently working on the designs, feel free to join today's websites meeting to provide feedback on the designs. https://layer5io.slack.com/archives/CLVT4TSG4/p1691145931066109?thread_ts=1690196534.862069&cid=CLVT4TSG4

**Comment by 4ddx** [comment]
Uh Hey @Chadha93, I'm not in this workspace, it doesn't allow me to join. What to do?

**Comment by Tabhi109** [comment]
@Chadha93 , Please assign this task to me , I am willing to do this !
