### ISSUE TITLE
On click resources icon: This XML file does not appear to have any style information.

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#4613]
### Description
On click resources icon I get the following message This XML file does not appear to have any style information.
I don't know if it has to be there or a link is given to it by mistake.

Someone please confirm. If its a issue please assign it to me.
@leecalcote @Chadha93 

Refer the following video to know the exact issue
### Screenshots

https://github.com/layer5io/layer5/assets/91942072/27dc9b85-ca9f-4b2f-81c0-76d358303b10

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment]
Hii @parmishh , we have already discussed about this on discuss.layer5.io

@thisiskaransgit already posted the solution.
''
The behavior you described, where clicking the feed icon on layer5.io/blogs redirects to feed.xml, is not an issue. It is a common practice for websites or blogs to provide an XML file called “feed.xml” that serves as an RSS or Atom feed.
By offering an RSS feed option, blogs enable readers who prefer using dedicated news aggregators or other similar services access to timely updates without having to visit the website separately.

''

**Comment by parmishh** [comment]
Thanks for the information I will close the issue

**Comment by parmishh** [comment]
.
