### ISSUE TITLE
[Community] Five and Friends: text color on hover of card - too low contrast

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4615]
### Current Behavior
On this [page](https://layer5.io/community/adventures-of-five-and-friends), the text contrast is too low on hover in light mode.

### Desired Behavior
Make text white on hover.

### Screenshots / Mockups

https://github.com/layer5io/layer5/assets/7570704/83e7aa3d-5e73-4da0-9fd0-7f0670ef62d3

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Sounds good, @nakulbh

**Comment by DkRadhey** [comment]
Sorry for making so many commits. I am new to open-source contributions. After commits, I just want the last commit to PR but didn't know how to mine previous commits that also got submitted. Can anyone help me so that it won't happen again?

**Comment by Ghat0tkach** [comment]
@DkRadhey  , Thanks for your interest in  community and we really appreciate your enthusiasm , However  do not prefer direct Pull requests without getting assigned. Please take care of this from the near future .
And this issue is already assigned to @nakulbh  .
There are a lot of issues which need help , feel free to check them out.
P.S do comment below the issues to show your interest.

**Comment by DkRadhey** [comment]
@Ghat0tkach Sorry for that. I will make sure that from next time it won't happen again.

**Comment by Chadha93** [comment]
> @DkRadhey , Thanks for your interest in community and we really appreciate your enthusiasm , However do not prefer direct Pull requests without getting assigned. Please take care of this from the near future . And this issue is already assigned to @nakulbh . There are a lot of issues which need help , feel free to check them out. P.S do comment below the issues to show your interest.

Well said @Ghat0tkach. @nakulbh I request you to review the PR.

**Comment by harshitkandpal** [comment]
I would like to work on this issue

**Comment by 4ddx** [comment]
Hey @leecalcote  @Ghat0tkach @Chadha93 I'd appreciate it if you could assign this issue to me, as it's been about 2 weeks since the issue was opened. 

Thanks!
Best

**Comment by Ghat0tkach** [comment]
@nakulbh are you still working on this issue?

**Comment by nakulbh** [comment]
> @nakulbh are you still working on this issue?
> 

Somebody made a PR on this issue while I was working, after then I stopped working on it

**Comment by nakulbh** [comment]
@Ghat0tkach can I continue working on this ?

**Comment by 4ddx** [comment]
Hey @nakulbh , could you please pass this one onto me, if you don't mind? 

Thanks,
Best

**Comment by Ghat0tkach** [comment]
@nakulbh do you wish to work on this issue or pass it to @4ddx ?

**Comment by nakulbh** [comment]
> @nakulbh do you wish to work on this issue or pass it to @4ddx ?
> 

Pass it to @4ddx

**Comment by 4ddx** [comment]
> > @nakulbh do you wish to work on this issue or pass it to @4ddx ?
> 
> Pass it to @4ddx

Thanks @nakulbh  :D

**Comment by 4ddx** [comment]
Sorry for the earlier pr's. Signoff was not configured properly
