### ISSUE TITLE
[Handbook] Add card for Adventures of Five and Friends

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4616]
### Current Behavior
On the community handbook [page](https://layer5.io/community/handbook), there is no card for Adventures of Five and Friends.

### Desired Behavior
Add a card for Adventures of Five and Friends on the handbook, link it to https://layer5.io/community/adventures-of-five-and-friends

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Shashank2104125** [comment]
@Chadha93 I am Interested in this issue. Please assign it to me.

**Comment by harshitkandpal** [comment]
hi I would like to work on this issue

**Comment by Ghat0tkach** [comment]
Thank you for volunteering guys , Will assign in chronological order
Dont forget to clear your doubts on our [slack](https://layer5io.slack.com/) and [discuss](discuss.layer5.io)
