### ISSUE TITLE
[Community] Add a section for Adventures of Five and Friends

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4617]
### Current Behavior
On the [community page](https://layer5.io/community), there is no section for Five and Friends.

### Desired Behavior
Add a section on the [community](https://layer5.io/community) page that points to the new [Adventures of Five and Friends](https://layer5.io/community/adventures-of-five-and-friends) page

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment]
Hii @Chadha93 , just a suggestion wouldn't it be better if we have CTA like meshmap for this rather than a seperate section?

**Comment by iconichal** [comment]
Interested in this issue. I can pick it up if it's available. If yes, also let me know what we want to add here - a section or CTA.

**Comment by Shashank2104125** [comment]
@Chadha93 I am Interested in this issue. Please assign it to me.

**Comment by Shashank2104125** [comment]
@Chadha93 if this issue is still open then please assign it to me because this would be my first time to start contributing, also this issue seems to be for beginners.

**Comment by Ghat0tkach** [comment]
Thank you for volunteering guys , Will assign in chronological order
Dont forget to clear your doubts on our [slack](https://layer5io.slack.com/) and [discuss](discuss.layer.io)

**Comment by Ghat0tkach** [comment]
@iconichal  , any updates?

**Comment by iArchitSharma** [comment]
@Ghat0tkach Can I work on this issue? It's been two weeks without any activity.

**Comment by iArchitSharma** [comment]
Hey @Chadha93, where can I find a similar button graphic?
![image](https://github.com/layer5io/layer5/assets/74408634/b19336b0-c40a-4e02-8d28-d82e2a593076)

**Comment by iArchitSharma** [comment]
This is how it looks currently. Any suggestions?
![ss](https://github.com/layer5io/layer5/assets/74408634/0c2d9fa4-683a-4872-8e25-1894a10c2b26)
