### ISSUE TITLE
[Site] Add a card/widget for Adventures of Five and Friends

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4618]
### Current Behavior
Currently, the [blog](https://layer5.io/blog) page has only one card/widget which is discuss forum. 

### Desired Behavior
Add a card/widget adjacent to the discuss CTA for Adventures of Five and Friends which points to this [page](https://layer5.io/community/adventures-of-five-and-friends)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shyamtawli** [comment]
Hey I would also like to work on it. But I confused about the design part. What should be the design of the card?

**Comment by DkRadhey** [comment]
Hey @Chadha93  could you please assign this to me?

**Comment by SaiSawant1** [comment]
@Chadha93 I would love to work on this issue can you please assign it to me?

**Comment by Shashank2104125** [comment]
@Chadha93 I am Interested in this issue. Please assign it to me.

**Comment by harshitkandpal** [comment]
hi I am interested to contribute.

**Comment by khushalsonawat** [comment]
Hello. I would like to take up this issue
Thanks

**Comment by vishalvivekm** [comment]
Folks, In the newcomers' call today this issue was assigned to @khushalsonawat . So let's give him the chance to propose a solution, meanwhile you're all welcome to review his efforts here.

**Comment by shyamtawli** [comment]
Hey @vishalvivekm I don't have any problem with anyone working on the issue but it should be assigned as first come first assign basis.

**Comment by Ghat0tkach** [comment]
> Hey @vishalvivekm I don't have any problem with anyone working on the issue but it should be assigned as first come first assign basis.

You're right @shyamtawli but we had already cleared about this on Slack , Few of the issues are only reserved for first-time only contributors .You should join on (slack){https://slack.layer5.io/} to get to know more about exclusive issues reserved for newcomers

We as Layer5 community always promotes newcomer and people wish to contribute but dont have any knowledge about how to contribute . Let's grow and learn together . 
We also have a lot of other issues as well

**Comment by ritiksaxena124** [comment]
Here is a [graphic ](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=17042%3A3074&mode=design&t=HBg03EZYehqH3iPx-1)that we can use as a widget

**Comment by Ghat0tkach** [comment]
@khushalsonawat any updates?

**Comment by khushalsonawat** [comment]
Hi,
I'm on it. Will put up a PR by today

**Comment by abhijeetgauravm** [comment]
hey @khushalsonawat have u done?

**Comment by 4ddx** [comment]
Hey @Ghat0tkach @vishalvivekm there's been no PR since last week, can i take it up if no one's working on it?

**Comment by Ghat0tkach** [comment]
@khushalsonawat May I know your status? its already been a week

**Comment by khushalsonawat** [comment]
Does this look fine?
![image](https://github.com/layer5io/layer5/assets/72885226/d3d757fc-e438-469a-ab93-17328e38d4e5)

**Comment by Ghat0tkach** [comment]
@khushalsonawat 
Let's discuss it on the websites call. Please add this as an agenda item in the (meeting minutes)[https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk], if you would :)

**Comment by khushalsonawat** [comment]
@Ghat0tkach I have put up a PR for this issue. The pr number is 1908.

**Comment by abhijeetgauravm** [comment]
hey @Chadha93 seems like its the duplicate issue of  #4916 .
