### ISSUE TITLE
The pointer disappears when I try to click on search icon

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#4629]
### Description
The pointer disappears when I try to click on search icon   at    https://layer5.io/blog

### Expected Behavior
Pointer must not disappear

I don't know if it is actually a problem or it has to be like that
Please confirm. If it was made like that intentionally then I will close this issue
If its a issue then please assign me😊

### Screenshots

https://user-images.githubusercontent.com/91942072/222900726-bac9d20e-a8c4-4e2f-932e-51091a9d95b4.mp4

### Environment:
- Host OS: 
- Browser: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and designs for Layer5 site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). 
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.png" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by DkRadhey** [comment]
@parmishh I would like to work on this. Could you assign this to me?

**Comment by parmishh** [comment]
@DkRadhey Hi I have already asked to assign it to me😅

**Comment by DarrenDsouza7273** [comment]
@parmishh You can go ahead assigned the issue to you
