### ISSUE TITLE
Twitter's logo has been changed to X

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#4631]
### Current Behavior
Twitter's logo has been changed to X .I was thinking if we need to update the logo on the layer5 website.
What are the views on this/Any comments?
@leecalcote 
I made some changes it will look somewhat as in the video.
It can be assigned to me if it needs to be changed.

### Screenshots / Mockups

https://github.com/layer5io/layer5/assets/91942072/fc24b4eb-2018-43b7-9f78-b30fe88340f1

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Sounds about right. When the new logo is available here - https://about.twitter.com/en/who-we-are/brand-toolkit, it might be about time to update.

**Comment by aaronsgeorge** [comment]
Could you please assign this issue to me

**Comment by EraKin575** [comment]
Please assign me this

**Comment by leecalcote** [comment]
@aaronsgeorge and @EraKin575 there are about 7 or site that need to be updated, too - https://layer5.io/community/handbook/repository-overview

**Comment by aaronsgeorge** [comment]
yes ill work on it please assign it to me

**Comment by Ghat0tkach** [comment]
there you go @parmishh

**Comment by leecalcote** [comment]
@aaronsgeorge will you or @EraKin575 open up issues on the other sites listed in the repo overview above?

**Comment by EraKin575** [comment]
Yep!

**Comment by saaagarsingh** [comment]
Hey @parmishh are you working on this??

**Comment by thisiskaransgit** [comment]
@parmishh, are you actively working on this, please signal, if not, I'll assign any of the other volunteers.

**Comment by parmishh** [comment]
@thisiskaransgit yes, I am little busy this week. please assign it to others.🚀

**Comment by thisiskaransgit** [comment]
@EraKin575, please take care of this one too

**Comment by EraKin575** [comment]
Sure!

**Comment by thisiskaransgit** [comment]
@EraKin575, what's the progress?

**Comment by Navansh** [comment]
Please assign this to me

**Comment by Ghat0tkach** [comment]
There you go @Navansh

**Comment by Mohith234** [comment]
@Navansh Please provide an update on this. If you are unable to work on it, No sweat feel free to tell us. We'll assign it to the other contributors.

**Comment by PRANJALRANA11** [comment]
Assign this issue to me

**Comment by captain-Akshay** [comment]
hiI @Mohith234  please assign it to me

**Comment by Navansh** [comment]
> @Navansh Please provide an update on this by the EOD. If you are unable to work on it, No sweat feel free to tell us. We'll assign it to the other contributors.

Sorry for the delay, I've pushed new changes for the issue, please look into it. Thanks

**Comment by niranjan-kurhade** [comment]
Has this issue been solved? If not I would like to work on it. @thisiskaransgit

**Comment by leecalcote** [comment]
@captain-Akshay @niranjan-kurhade help is needed here - https://github.com/layer5io/layer5/pull/4755#issuecomment-1735467280
