### ISSUE TITLE
Meshary cloud github link not found

### ISSUE THREAD

**Issue by SNIPACER** [layer5io/layer5#4634]
### Description

In this [page](https://layer5.io/community/handbook/repository-overview), github link got 404 error on Meshary cloud row.
### Expected Behavior

I think we can this [https://github.com/meshery/meshery](https://github.com/meshery/meshery) to that github icon link
### Screenshots

![Screenshot from 2023-07-27 10-58-55-5](https://github.com/layer5io/layer5/assets/92214782/d9c99671-d380-492e-8fe7-1d36dc65f8c6)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks. We might want to change this link, however, it is available link. It’s just that you don’t have access to it.

**Comment by leecalcote** [comment]
Ideally, we can include some additional information about how to get access. // @Chadha93

**Comment by SNIPACER** [comment]
> Thanks. We might want to change this link, however, it is available link. It’s just that you don’t have access to it.

Ok, got it

**Comment by Chadha93** [comment]
> Ideally, we can include some additional information about how to get access. // @Chadha93

Changing the link seems relevant for now. @SNIPACER, you can point it to the [meshery](https://github.com/meshery/meshery) repository for now. Will you also update this issue by adding one more item? Which is to replace the GH link for the MeshMap repository to https://github.com/layer5labs/meshmap-snapshot

**Comment by SNIPACER** [comment]
Hi, @leecalcote @vishalvivekm 
I changed the link as @Chadha93 said and assigned to me. Thanks for this opportunity. This is my first contribution in my life to open source community, feeling happy . Thanks @Chadha93 @leecalcote @vishalvivekm. I have made a pull request. Thanks once again.

**Comment by Chadha93** [comment]
> Hi, @leecalcote @vishalvivekm I changed the link as @Chadha93 said and assigned to me. Thanks for this opportunity. This is my first contribution in my life to open source community, feeling happy . Thanks @Chadha93 @leecalcote @vishalvivekm. I have made a pull request. Thanks once again.

Good to hear @SNIPACER, please link the PR to this issue.

**Comment by SNIPACER** [comment]
Yeah @Chadha93, I did that 😊. Thanks
