### ISSUE TITLE
Remove "below" from label-commenter-config.yml

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4639]
### Current Behavior
Notice the `below` in "DCO check below"
https://github.com/layer5io/layer5/blob/19d16cfa3aad4fdc10f7aadb9e4310f158a9d8c9/.github/label-commenter-config.yml#L28

https://github.com/layer5io/layer5/blob/19d16cfa3aad4fdc10f7aadb9e4310f158a9d8c9/.github/label-commenter-config.yml#L33
### Desired Situation

Remove the preposition "below" from lines 28 and 33

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by xmayukx** [comment]
@vishalvivekm  Can you assign me this issue? Would love to work on it.

**Comment by csengineer1990** [comment]
can I work on it? can you assign to me?

**Comment by sudhanshutech** [comment]
assigning in fcfs order
