### ISSUE TITLE
[About] Rearrange order of text and images in mobile view

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4640]
### Description 

On the About page ( layer5.io/about), text and images are not interleaved. Instead, long walls of text followed by multiple adjacent images are shown.

### Expected Behavior
interleave text and images one after the other. 

### Screenshots

https://github.com/layer5io/layer5/assets/7570704/b723255c-16fd-46a8-ae2a-e6f618c34bc0

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by abhinavrathore25** [comment]
I would like to work on this.

**Comment by Aarav238** [comment]
I would like to work on it . @leecalcote

**Comment by hirentimbadiya** [comment]
Assigning in chronological order, @GitsOfVivek , you can begin working on this task, while other volunteers can explore and address other issues in the community :)

**Comment by leecalcote** [comment]
@GitsOfVivek, if you don't understand the issue, please study it first and be prepare to solve it before asking for assignment, and subsequently, asking people to explain it to you. Here is more explanation offered by @thisiskaransgit on what to do to fix this issue:

<img width="357" alt="Screenshot 2023-07-29 at 9 14 48 AM" src="https://github.com/layer5io/layer5/assets/7570704/013338d2-56fd-4074-9ad4-a76c1ceb53f9">

@officialarmannqureshi or @Aarav238 have you built this site, yet? If so, do either of you understand the issue and are ready to execute?

**Comment by sarkartanmay393** [comment]
@leecalcote I raised a solution. I used a custom class name to show/hide any component. And added the CSS code in `about.style.js` file, as it was imported in `about.js`.

**Comment by leecalcote** [comment]
Freeing up issue assignment. Help wanted.

**Comment by ShravaniAK** [comment]
i would like to work

**Comment by ShravaniAK** [comment]
I'll submit a pr today
