### ISSUE TITLE
Information not contained in cards in mobile view

### ISSUE THREAD

**Issue by parmishh** [layer5io/layer5#4645]
### Description
In mobile view the contents are not contained inside the cards at::  https://layer5.io/blog/meshery/how-to-bind-kubernetes-service-account-with-clusterrole

### Expected Behavior
the contents should be inside the cards and should be responsive

please assign this task to me if it needs a fix!
### Screenshots
<img width="350" alt="dc" src="https://github.com/layer5io/layer5/assets/91942072/20fa453c-8031-4e94-9aac-87d3626bb55b">

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by HetviSoni** [comment]
@parmishh its already fixed. Just refresh the page or visit it using your mobile phone.

**Comment by parmishh** [comment]
@HetviSoni Thanks for the information. I'll close the issue.
