### ISSUE TITLE
[Home] Add Citi logo to list of "ENGAGING AND COLLABORATING WITH" section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4648]
### Current Behavior
Citibank actively contributes to Meshery.

### Desired Behavior
Add the Citi logo to the "ENGAGING AND COLLABORATING WITH" section on the home page.

### Screenshots / Mockups
<img width="748" alt="Screenshot 2023-07-28 at 6 03 16 AM" src="https://github.com/layer5io/layer5/assets/7570704/ba675588-5794-48cf-a209-23389e5c9fde">

### Implementation
1. Source the Citi logo. 
2. Use an SVG or Web image format, not PNG or other.

### Acceptance Tests
1. Logo appears fine in both light and dark modes.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VSatwika** [comment]
Could I work on this issue @leecalcote?

**Comment by abhinavrathore25** [comment]
I would like to work on that.

**Comment by leecalcote** [comment]
Thanks for volunteering!

**Comment by Aarav238** [comment]
I would like to work on it @leecalcote
