### ISSUE TITLE
typo in community's blog and community's page

### ISSUE THREAD

**Issue by abhijeetgauravm** [layer5io/layer5#4654]
### Description

There is some typo in community's blog [here](https://layer5.io/blog/community/meet-the-meshmate-yash-sharma)  (experience) and also   [here](https://layer5.io/blog/meshery/changing-meshery-release-channels) (subscription)  and community's page [here](https://layer5.io/community) (meaningfully)

### Screenshots

![image](https://github.com/layer5io/layer5/assets/65087356/cae479d2-44bd-4282-8fd0-e0bc354aa74b)

![image](https://github.com/layer5io/layer5/assets/65087356/bc95e4a9-e6be-4f54-a5df-d2de7492450b)

![image](https://github.com/layer5io/layer5/assets/65087356/53f1a8d1-9eb8-400d-a4e1-b162db332b6a)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by abhijeetgauravm** [comment]
I would like to fix it!

**Comment by hirentimbadiya** [comment]
@abhijeetgauravm please point out typos in issue description

**Comment by abhijeetgauravm** [comment]
@hirentimbadiya updated!

**Comment by Ghat0tkach** [comment]
@abhijeetgauravm there you go
