### ISSUE TITLE
Failure to Navigate Back to Home Page on Incorrect Path and Error Page Display

### ISSUE THREAD

**Issue by PRANJALRANA11** [layer5io/layer5#4658]
### Description
When attempting to access a page with an incorrect path or non-existent URL on the website, the application does not automatically navigate back to the home page. Instead, it displays an error page, leaving the user stranded and unable to easily return to the main page.

### Steps to Reproduce:

Open the website .
Manually enter an incorrect path or non-existent URL in the address bar.
Observe that instead of being redirected to the home page, an error page is displayed.

### Expected Behavior
Upon entering an incorrect path or non-existent URL, the application should automatically redirect the user back to the home page, providing a seamless and user-friendly experience.

###Actual Behavior:
The application displays an error page when an incorrect path or non-existent URL is entered, failing to navigate back to the home page automatically.

###Possible Solution:
The application should be modified to handle incorrect paths and non-existent URLs more effectively. One possible solution is to implement a server-side or client-side redirection mechanism that automatically sends users back to the home page when an error occurs due to incorrect paths or invalid URLs.

**Comment by sarkartanmay393** [comment]
@PRANJALRANA11 I think its normal showing an error page though.

**Comment by Savio629** [comment]
@PRANJALRANA11 I don't think we should redirect user directly. It necessary to have an error page!

**Comment by EraKin575** [comment]
can I work on this?
