### ISSUE TITLE
[Learn] Increasing the Z-index of the Scroll Up button

### ISSUE THREAD

**Issue by Karmpatel960** [layer5io/layer5#4663]
**Current State:**
The subscribe button is overlapping with the scroll-up button
Link : https://layer5.io/learn/service-mesh-labs
<img width="259" alt="image" src="https://github.com/layer5io/layer5/assets/96860884/d696e949-63a5-4c71-a9f8-a1d17d838c0e">

**Desired State:**
Scroll Up Button should not under subscribe Button

---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by Karmpatel960** [comment]
Can you please assign me this issue? I want to work on it.

**Comment by DkRadhey** [comment]
@Ghat0tkach @leecalcote Can I work on this issue?

**Comment by leecalcote** [comment]
Thanks, @Karmpatel960.

@DkRadhey, there is a related bug that occurs in Safari wherein the Subscribe section overlaps the list items in the footer. Help needed here. Must have Safari.

**Comment by DkRadhey** [comment]
@leecalcote Sorry, I don't have safari as I'm a windows user. Is there any other issue I can work on?

**Comment by leecalcote** [comment]
Yes, there are about 170 open help wanted issues currently
