### ISSUE TITLE
Display integration containers adjacent to each other in a row for better mobile view

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#4665]
### Current Behavior

Currently, when viewing the Layer5 website on a mobile device, the integration containers appear to be queued one after the other in a vertical list, which takes up a lot of vertical space on the screen
### Desired Behaviour

Integration containers should be displayed adjacent to each other in a row, with smaller container sizes and margins, allowing more integrations to be displayed on the screen at once
### Screenshots / Mockups
 
   <img src="https://github.com/layer5io/layer5/assets/92504666/3eeeb649-cf75-46f5-85bf-f500c9e6f22c" width="30%" >

 
### Implementation

Shrink the size of containers and margins for a row of integrations in mobile view

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Cvr421** [comment]
Hii @thisiskaransgit  /assign

**Comment by DarrenDsouza7273** [comment]
can i work on this @thisiskaransgit

**Comment by DkRadhey** [comment]
@thisiskaransgit Can I work this issue?

**Comment by Cvr421** [comment]
ok @thisiskaransgit
