### ISSUE TITLE
Update MeshMap Designer integration count dynamically on the design page

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/layer5#4666]
### Current Behavior
In https://layer5.io/cloud-native-management/meshmap/design, the number of integrations are outdated.

### Desired Behavior

 This should be dynamically updated, same way they are being updated in homepage

### Screenshots / Mockups

![Screenshot from 2023-07-31 16-52-52](https://github.com/layer5io/layer5/assets/92504666/9a369f86-250a-45b8-99f0-24845bf96518)

### Implementation

copy the same logic available in the integration section for updating the numbers with the workflow

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by saaagarsingh** [comment]
Can I work on this @thisiskaransgit?

**Comment by Cvr421** [comment]
Hii @thisiskaransgit  /assign
