### ISSUE TITLE
[Bug] Writing Programme  Background Color Inconsistency in Dark Mode

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4667]
### Description

Currently, the content box in the [writing program](https://layer5.io/community/handbook/writing-program) does not adapt correctly to dark mode. When the dark mode is enabled, the content box background remains white, which leads to poor visibility and an inconsistent user experience.

![image](https://github.com/layer5io/layer5/assets/59855919/5ddc79ff-5244-4e5f-a886-b690ed9ef1b6)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Chat-Ritik** [comment]
Hey @Ghat0tkach, can I work on this issue?

**Comment by DarrenDsouza7273** [comment]
Assigned it to you @Chat-Ritik 
if you have any doubts or queries you can address them on our slack channel or mention the same on the discussion forum

**Comment by Chat-Ritik** [comment]
@Ghat0tkach @DarrenDsouza7273 As far as I can make out, it is expected to transform the background-color(outside form) to black with some opacity making it somewhat translucent. Am I right? Do clarify. Thanks

**Comment by Ghat0tkach** [comment]
@Chat-Ritik 

You just need to change 
https://github.com/layer5io/layer5/blob/3e94360f3c630db2abd3ba863f423ab9bbd17f28/src/sections/app.style.js#L215

to 

    background-color: rgb(0 ,0,0, 0.75);

**Comment by DkRadhey** [comment]
@Ghat0tkach May I?

**Comment by DarrenDsouza7273** [comment]
> @Ghat0tkach May I?
You can checkout other available issues @DkRadhey as it has already been resolved by @Chat-Ritik
