### ISSUE TITLE
Points aren't in correct alignment!

### ISSUE THREAD

**Issue by abhijeetgauravm** [layer5io/layer5#4668]
### Description

Points aren't in correct alignment [here](https://64b5a6d647333e5a58a5b133--layer5.netlify.app/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures).
It would look good if 'application' and 'gateways' align with other points [here](https://64b5a6d647333e5a58a5b133--layer5.netlify.app/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition).
It would look good if 'Be' would be align with 'production' [here](https://64b5a6d647333e5a58a5b133--layer5.netlify.app/learn/service-mesh-books/istio-up-and-running).
### Expected Behavior

They should be aligned.

### Screenshots

![image](https://github.com/layer5io/layer5/assets/65087356/0b60525a-5515-439f-bafb-2a6f0b75916d)

![image](https://github.com/layer5io/layer5/assets/65087356/b941c113-bc08-4836-a963-aefc10f5737c)

![image](https://github.com/layer5io/layer5/assets/65087356/dff8ca4b-b033-455f-b5bd-7acc978b5ada)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by abhijeetgauravm** [comment]
I would like to fix it !

**Comment by DkRadhey** [comment]
@leecalcote @Ghat0tkach Can I work on the issue, if @abhijeetgauravm is not interested? If yes, please assign it to me.

**Comment by abhijeetgauravm** [comment]
I m on it ! @DkRadhey . Will raise PR soon!

**Comment by leecalcote** [comment]
I very much appreciate this, although - - https://github.com/layer5io/layer5/pull/4717#issuecomment-1672187721
