### ISSUE TITLE
[Mega Menu] Fine-tune responsive fitting of menu items

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4669]
### Description
Menu items are somewhat difficult to read on smaller width desktop screens.

### Expected Behavior
<img width="1031" alt="Screenshot 2023-07-31 at 2 40 43 PM" src="https://github.com/layer5io/layer5/assets/7570704/7594ee57-946c-4fa7-ad46-b8765cf5a62a">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShivangRawat30** [comment]
@leecalcote I would like to work on this issue

**Comment by leecalcote** [comment]
Thanks, @ShivangRawat30 👍

**Comment by Manish4044** [comment]
Can I work on this issue, since the linked PR had no further activity since 2 weeks?

**Comment by Chetax** [comment]
@saurabh100ni  Can I Work On This Isssue Also If @Manish4044 Has No Problem .As This Can Be Become My First PR In layer5.

**Comment by saurabh100ni** [comment]
@Manish4044 Do let me know if you are still interested in working on this issue by this evening and if not @Chetax you may take this forward.

**Comment by Chetax** [comment]
i want to work on this issue caan you please assign it to me

**Comment by Chetax** [comment]
@Manish4044 , As We See Now Thair Is Fine-tune responsive fitting of menu items, Right ?
![Screenshot 2023-12-22 180419](https://github.com/layer5io/layer5/assets/99749401/2640c593-f306-4f14-b93b-122912c081de)

**Comment by saurabh100ni** [comment]
Yes, Thanks for calling this out @Chetax, I will just close this issue.
