### ISSUE TITLE
Upgrade to Jekyll 4.0.1

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#467]
**Current State:**
The layer5.io site is running Jekyll 4.0.0.

**Desired State:**
The layer5.io site needs to be updated to Jekyll 4.0.1.

**Comment by leecalcote** [comment]
@morrme, to knock this one out, you'll make a quick update in the [Gemfile](https://github.com/layer5io/layer5/blob/master/Gemfile), then build and verify that the site works.

**Comment by morrme** [comment]
@leecalcote Thanks but I believe @kushthedude  has reassigned these to someone else. :)

**Comment by kushthedude** [comment]
Hi @morrme that issue was in meshery.io & this is an indifferent repo, you are welcome to knock this out!

**Comment by morrme** [comment]
@kushthedude @leecalcote That's totally fine, no worries.  I'm glad I was able to help with other issues.

**Comment by leecalcote** [comment]
FYI -  It's a slight bit confusing, but there are three sites currently in the community that are running on Jekyll:

- meshery.io
- layer5.io
- docs.meshery.io

**Comment by morrme** [comment]
@leecalcote not confusing at all! I just think you may have people better suited to assist.

**Comment by kushthedude** [comment]
@crustyy would you like to fix this one too?

**Comment by crustyy** [comment]
yes i'll take it :)!!
