### ISSUE TITLE
[Bug] Duplication of Integration operators

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4686]
### Description

![image](https://github.com/layer5io/layer5/assets/59855919/4360b121-9baf-4b34-b72c-1fdf4c119ca9)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by abhijeetgauravm** [comment]
I would like to work!

**Comment by iArchitSharma** [comment]
✋✋✋

**Comment by Ghat0tkach** [comment]
@abhijeetgauravm  , Since this issue is meant for first-timers only, I'm afraid I won't be able to assign it to existing contributors.

@iArchitSharma there you go!

**Comment by abhijeetgauravm** [comment]
Oh sry! Go for it @iArchitSharma !

**Comment by Ghat0tkach** [comment]
@abhijeetgauravm  , We do have a lot of issues available .Please feel free to check them as well

**Comment by vishalsingh2972** [comment]
I would like to try this out, also is prerequisite of basic js enough or do we need anything else as well?

**Comment by Ghat0tkach** [comment]
hey @vishalsingh2972 , Unfortunately This issue is a bit complex .Please free to check other issues , we do have a lot of them

**Comment by vishalsingh2972** [comment]
> hey @vishalsingh2972 , Unfortunately This issue is a bit complex .Please free to check other issues , we do have a lot of them

Thanks for the heads up @Ghat0tkach , just curious what tech stack will solve this issue?

**Comment by Ghat0tkach** [comment]
@vishalsingh2972  , This requires access to spreadsheets whose access is restricted to maintainers😅

**Comment by Aarav238** [comment]
its been one and still this issue is not ressolved, please assign this to me @Ghat0tkach .
