### ISSUE TITLE
ENGAGING AND COLLABORATING container Display in row format . Adjacent to each other in Mobile view.

### ISSUE THREAD

**Issue by Cvr421** [layer5io/layer5#4687]
### Description

ENGAGING AND COLLABORATING container needs to be Display in row format . Adjacent to each other in Mobile view.
I think we need to make these logo in row. With Small size to show more logo on the screen .

### Screenshots

![Screenshot 2023-08-03 151157](https://github.com/layer5io/layer5/assets/82499697/dc094630-6306-4ac4-82ec-7451836c160d)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Cvr421** [comment]
Hii @leecalcote @Chadha93 @thisiskaransgit .Please review this issue if you find relevant enough do assign it to me.

**Comment by thisiskaransgit** [comment]
@Cvr421, the section _is_ reponsive...

**Comment by Cvr421** [comment]
> @Cvr421, the section _is_ reponsive...

OK @thisiskaransgit  so i think the issue is with my browser . So should i close this issue

**Comment by DarrenDsouza7273** [comment]
Since all our websites are designed to be responsive, the observed behavior is expected and not an issue. @Cvr421 
I will close the issue
Thank you.
