### ISSUE TITLE
Twitter logo not visible

### ISSUE THREAD

**Issue by EraKin575** [layer5io/layer5#4693]
### Description
NO twitter logo visible on https://meshery.layer5.io/error_meshery_version_incompatible?error=Meshery+Deployment+Incompatible&error_type=MESHERY_DEPLOYMENT_INCOMPATIBLE
![image](https://github.com/layer5io/layer5/assets/100225222/dd4df2ca-e42f-47bf-8a8c-716841a6acd0)

### Expected Behavior
Design it such that it becomes visible

### Environment:
- Host OS: LInux
- Browser: Microsoft Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by santoshy1101** [comment]
i want to work on this issue.

**Comment by Cvr421** [comment]
Can i work on this.

**Comment by DkRadhey** [comment]
@EraKin575 @Ghat0tkach Can I work on this issue?

**Comment by DarrenDsouza7273** [comment]
@EraKin575 are you taking up this issue or should i assign the next person?

**Comment by meaayush** [comment]
can you assign this to me?

**Comment by EraKin575** [comment]
@DarrenDsouza7273 please assign it another contributor

**Comment by leecalcote** [comment]
Thanks, @EraKin575.

And thanks to all others who have volunteered. This code is not stored in this repo. Access to the repo in which it is stored requires that you be accepted as a participant in Layer5's internship program. I encourage you all to participate in that program. Read the FAQs on layer5.io/programs to learn how to best position your candidacy. 

Assigning to @duckling69

**Comment by duckling69** [comment]
This can be close here I've raise pr to fix it in correct repo
