### ISSUE TITLE
Issue with Learning Path Link After Requesting Free Ebook

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#4695]
### Description
When submitting the required details to receive the free ebook on the page [The Enterprise Path to Service Mesh Architectures](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures), a confirmation message for the free learning path is displayed. However, upon clicking the provided link, a 404 error occurs.

### Steps to Reproduce:

1. Go to [The Enterprise Path to Service Mesh Architectures](https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures) page.
2. Enter the required details and submit to request the free ebook.
3. Observe the confirmation message mentioning the free learning path.
4. Click on the provided link for the learning path.

### Expected Result:
Clicking the link should lead to the free learning path related to service meshes.

### Actual Result:
Clicking the link results in a 404 error page.

### Additional Information:
The learning path link that is not working: https://layer5.io/learn/learning-path

This issue prevents users from accessing the intended learning path after requesting the free ebook. It would be greatly appreciated if this link could be fixed to provide a seamless learning experience.

### Screenshots
1. Before submitting the form:
![image](https://github.com/layer5io/layer5/assets/74408634/28147c33-0451-4be4-b7ab-74e4d62d8f8c)
2.  After Submission:
![image](https://github.com/layer5io/layer5/assets/74408634/bcb47115-f0d2-4ece-8d39-071734fcd628)
3. learning path page:
![image](https://github.com/layer5io/layer5/assets/74408634/79f7ed42-ab80-46e0-b78f-208a40fdd68d)

### Environment:
- Host OS: Windows 11
- Browser: Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by iArchitSharma** [comment]
ps: if possible I would love to work on this issue

**Comment by leecalcote** [comment]
Thanks!

**Comment by abhijeetgauravm** [comment]
hey @iArchitSharma have u done or facing any issue?

**Comment by abhijeetgauravm** [comment]
hey @iArchitSharma r u doing it ?

**Comment by iArchitSharma** [comment]
@abhijeetgauravm Sure, I'm currently working on it. I'm in the process of familiarizing myself with the Gatsby framework since I'm new to it.

**Comment by abhijeetgauravm** [comment]
Yeah @iArchitSharma 🚀

**Comment by iArchitSharma** [comment]
@leecalcote, the problem was actually present on two pages:

The issue was identified on this specific page: https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures

Similarly, the same problem was also discovered on the following page: https://layer5.io/learn/service-mesh-books/the-enterprise-path-to-service-mesh-architectures-2nd-edition

The solution has been implemented as part of pull request #4710 , successfully resolving the issue on both pages.
