### ISSUE TITLE
Create a PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#470]
**Current Behavior**
This repo is missing a template to present to contributors when they create a PR.

**Desired Behavior**
Using https://github.com/layer5io/service-mesh-performance-specification/blob/master/.github/PULL_REQUEST_TEMPLATE.md as a template (can simply copy this file), create a PULL_REQUEST_TEMPLATE.md in the .github folder of this repo.

**Comment by HarshKapadia2** [comment]
Hey can I try to handle this issue?

**Comment by leecalcote** [comment]
@HarshKapadia2 yes, please, that would be wonderful.

**Comment by HarshKapadia2** [comment]
How do you want me to handle the `signed commits` part of the template that you linked?
That part doesn't exist in the `CONTRIBUTING.md` of this repo.

**Comment by leecalcote** [comment]
Oh, great question, @HarshKapadia2. Perhaps, you'd like to knock both of these issues - https://github.com/layer5io/layer5/issues/471

**Comment by HarshKapadia2** [comment]
Alright! Do assign me to that issue as well! 😄
