### ISSUE TITLE
[Community] Handbook: text color on hover of card - too low contrast

### ISSUE THREAD

**Issue by 4ddx** [layer5io/layer5#4706]
### Current Behavior

Similar to Issue #4615 , the contrast is too low on this page : [handbook-page](https://layer5.io/community/handbook)

### Desired Situation

Make text white on hover.

![image](https://github.com/layer5io/layer5/assets/130624861/8322db46-bcf6-4f3d-ae74-0daa7e6eaab9)

@leecalcote @Ghat0tkach I can fix this issue if any one of you assigns it to me 

  Thanks,
  Best

**Comment by malaviya-parth** [comment]
Can I please resolve this issue

**Comment by 4ddx** [comment]
> Can I please resolve this issue

I've already made a PR, just waiting for it to be fixed

**Comment by malaviya-parth** [comment]
> > Can I please resolve this issue
> 
> I've already made a PR, just waiting for it to be fixed

Oh, I am sorry
