### ISSUE TITLE
Include instructions on signing commits in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#471]
**Current Behavior**
The [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) in this repo is missing an explanation and instructions on signing off on commits.

**Desired Behavior**
A copy of the same instructions from the Meshery repo's CONTRIBUTING.md's [section on signing commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) should be placed in into this repo's contributing instructions.

We will need to copy over the screenshots as well, which can be placed into a new `readme` folder in this directory - https://github.com/layer5io/layer5/tree/master/assets/images

**Comment by HarshKapadia2** [comment]
On it!

**Comment by leecalcote** [comment]
Very good! 😄

**Comment by leecalcote** [comment]
@HarshKapadia2 assuming that you find this and other [Layer5 Projects](https://layer5.io/projects) of interest, I welcome you to join the community here - http://slack.layer5.io. 👍
