### ISSUE TITLE
'Kubernetes Service' between service interface and pod isn't visible 

### ISSUE THREAD

**Issue by abhijeetgauravm** [layer5io/layer5#4712]
### Description

'Kubernetes Service' between service interface and pod isn't visible in dark as well as light mode.

### Expected Behavior

It should be visible.
### Screenshots

![image](https://github.com/layer5io/layer5/assets/65087356/8fb2655a-6f26-4061-88f8-ca715b32497d)

![image](https://github.com/layer5io/layer5/assets/65087356/c8012a32-719f-470e-8a18-d52650d2f390)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VivekBaldha0712** [comment]
I can take this up. Please assign this task to me

**Comment by shivankurchavan** [comment]
Please assign me this issue @DarrenDsouza7273

**Comment by Shreya111111** [comment]
@abhijeetgauravm plz assign this issue to me
