### ISSUE TITLE
Improve the Twitter Icon

### ISSUE THREAD

**Issue by kumarankit999** [layer5io/layer5#4722]
### Current Behavior
there is showing an old icon of Twitter

### Desired Behavior
It should show the new and improved version icon

### Screenshots / Mockups
![image](https://github.com/layer5io/layer5/assets/111564362/98c5ff5f-08b9-4dd9-a2c0-9d9c2e167bb1)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ghat0tkach** [comment]
Welcome @kumarankit999  to the Layer5 community , We are delighted to see your interest in our community and enthusiasm to contribute , 
Unfortunately , this is a duplicated issue for
https://github.com/layer5io/layer5/issues/4631

**Comment by DarrenDsouza7273** [comment]
Should i close this issue @Ghat0tkach ?

**Comment by VivekBaldha0712** [comment]
i would like to solve this issue. Please assign this task to me

**Comment by Ghat0tkach** [comment]
Yes , Thanks @DarrenDsouza7273

**Comment by Ghat0tkach** [comment]
> Should i close this issue @Ghat0tkach ?

Yes , Thanks @DarrenDsouza7273

**Comment by DarrenDsouza7273** [comment]
Closing this issue as it is a duplicated issue for #4631
