### ISSUE TITLE
[Community] Member Profile: Rex

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4724]
**Current Behavior**

@Rexford74 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Rexford74 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Rexford74 
- Twitter: [rexford__](https://twitter.com/rexford__)
- LinkedIn: [rex-joshua-designer](https://www.linkedin.com/in/rex-joshua-designer/)
- Meshery Cloud: [f0a2dc22-e7c6-4143-a984-1f6c22f8e696](https://meshery.layer5.io/user/f0a2dc22-e7c6-4143-a984-1f6c22f8e696)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@Rexford74 would you please toss in a link to your profile picture and your bio ?

**Comment by shivankurchavan** [comment]
I'd like to work on this issue @DarrenDsouza7273

**Comment by DarrenDsouza7273** [comment]
Assigning it to you @shivankurchavan

**Comment by DarrenDsouza7273** [comment]
you can checkout #4728 for reference @shivankurchavan

**Comment by Rexford74** [comment]
Oh wow! Thanks for helping out with this guys. It's a great honor. This is a link to my profile picture (![ZgUZQV15_400x400](https://github.com/layer5io/layer5/assets/98197344/e9aad880-2ef2-4a6b-9b62-c02cd5421246)).
Thank you guys!

**Comment by shivankurchavan** [comment]
hello @Rexford74 , what do you think about this bio ? please suggest improvements also suggest any art or sport you're interested in, which you'd like to mention here in bio. 

I embody the traits of an inquisitive developer, driven by an insatiable thirst for knowledge across a spectrum of technologies, each offering a myriad of possibilities waiting to be unveiled. My fascination gravitates towards the realm of UI/UX, where I find myself captivated by the art of crafting seamless and intuitive user experiences. My enthusiasm extends to the world of open source, where I am actively involved in collaborative and community-driven projects. A perpetual learner, I am fueled by an unwavering motivation to continually expand my skill set.

**Comment by Ghat0tkach** [comment]
@shivankurchavan , 

@Rexford74 will provide his bio 😄😄

**Comment by shivankurchavan** [comment]
Okay 😅😃

**Comment by Golu7667** [comment]
@Rexford74 provide your bio
