### ISSUE TITLE
[Community] Member Profile: Gopi Vaibhav

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4726]
**Current Behavior**

@gopivaibhav  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize  @gopivaibhav  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  @gopivaibhav
- Twitter: [gopi_vaibhav](https://twitter.com/gopi_vaibhav)
- LinkedIn: [gopivaibhav](https://www.linkedin.com/in/gopivaibhav/) 
- Meshery Cloud: [85339de7-8ca2-4543-8793-1ebb1e76bf99](https://meshery.layer5.io/user/85339de7-8ca2-4543-8793-1ebb1e76bf99)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Ghat0tkach** [comment]
@gopivaibhav would you please toss in a link to your profile picture and your bio ?😎🙌

**Comment by gopivaibhav** [comment]
You can find my picture [here](https://drive.google.com/file/d/1ASNnHJxBEEZGidDMrhHaMZokGTMjfK9n/view?usp=sharing) @Ghat0tkach 

My bio-

I am a Final year CSE student from IIIT Lucknow. I am an experienced MERN Stack Developer with a solid background in Python web frameworks, notably Django. My journey in the tech world has led me to actively contribute to prominent open-source projects like Layer5 and Oppia, through which I started learning to use Golang, Gatsby, GraphQL, Docker, k8s, etc.

Aside from coding, I am a passionate student who is continuously pursuing new hobbies, such as trying new video games and participating in outdoor activities.

I am constantly open to new and intriguing possibilities and look forward to meeting like-minded professionals. If you have a passion for web development, open-source contributions, or technology in general, let's connect and discuss how we might collaborate to create extraordinary digital solutions!  🚀

**Comment by Nithinyanamaddi** [comment]
I would like to work on it, can someone assign it to me.

**Comment by Ghat0tkach** [comment]
@Nithinyanamaddi , have you set up the layer5 website locally??👀

**Comment by ShravaniAK** [comment]
I would like to work on this , if its not assigned to anyone yet

**Comment by Nithinyanamaddi** [comment]
> @Nithinyanamaddi , have you set up the layer5 website locally??👀

Yes, I set it up locally.

**Comment by Ghat0tkach** [comment]
Ok @Nithinyanamaddi , There you go 
Please join us on Slack and ask openly on discuss.layer5.io if you have any doubts
