### ISSUE TITLE
our project button in About section is Overlapping .

### ISSUE THREAD

**Issue by ShravaniAK** [layer5io/layer5#4729]
### Description

our project button in About section is Overlapping .

### Screenshots

<img width="936" alt="Screenshot 2023-08-12 at 1 57 23 PM" src="https://github.com/layer5io/layer5/assets/97099574/073cf510-3f1f-4768-aedd-38b3ca9e1faa">

### Environment:
- Host OS:macos
- Browser:chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShravaniAK** [comment]
I want to resolve this issue

**Comment by hirentimbadiya** [comment]
there you go @ShravaniAK
