### ISSUE TITLE
[Blog] The Importance of GitHub Stars

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4745]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** The Importance of GitHub Stars
**Topic:** 
**Core points to convey in the post:** 
1. How individuals use GitHub stars as an indicator of project health, popularity, and usage.
1. How GitHub uses stars for tracking trending projects.
1. All the other ways in which stars matter...

- Include Five and his star-fueled rocket adventures - https://layer5.io/community/adventures-of-five-and-friends

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by leecalcote** [comment]
@Anita-ihuman fyi

**Comment by nwanduka** [comment]
Hi @leecalcote 

I'd like to work on this issue.

In addition to the core points you've listed, I suggest we also talk about what Github stars are, and how to star a project. These points will provide background info for readers who are not familiar with Github terminologies. Here's my proposed flow for the blog:

**Title: Importance of Github Stars**
**Core points to convey in the post:**
1. What are Github Stars?
2. How individuals use GitHub stars as an indicator of project health, popularity, and usage.
3. How GitHub uses stars for tracking trending projects.
4. All the other ways in which stars matter.
5. How to star a project

What do you think?

**Comment by leecalcote** [comment]
Sounds real good, @nwanduka

**Comment by nwanduka** [comment]
Hi @leecalcote, I've completed the draft for the blog. You'll find it [here](https://docs.google.com/document/d/1ElKsQG3i9MF-tFSy7IeSy5HLfgcrcfVcb9-CCktcgtY/edit?usp=sharing). Please review and let me know if there are any adjustments to be made before publishing.
