### ISSUE TITLE
[Event] Add new event IstioCon Virtual 2023

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4756]
Please add the following event to layer5.io/events.

**Event:** IstioCon Virtual 2023
- Event Title: Multiplayer Istio: Collaborative WASM Plugins with Intel and Layer5
- Event Link: https://events.linuxfoundation.org/istiocon/
- Talk Description: Join Layer5 and Intel at the Istio conference on Monday, Sept. 25th to Tuesday, Sep. 26th. IstioCon is a 100% virtual event that is designed to connect community members across the globe with Istio and the Istio ecosystem.
- Registration Link: https://cvent.me/LnMXkN
- Speakers: Lee Calcote, Xin Huang
- Thumbnail image - 
![Untitled](https://github.com/layer5io/layer5/assets/65453826/f3ca3d06-b5aa-4eeb-8854-a04a3365bd22)

- Deck: 
- Video: 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by malaviya-parth** [comment]
I would like to work on it

**Comment by hirentimbadiya** [comment]
go on @malaviya-parth
