### ISSUE TITLE
Fix Spacing Issue between Subscribe button and input in CTA

### ISSUE THREAD

**Issue by arpitghura** [layer5io/layer5#4757]
### Current Behavior

![image](https://github.com/layer5io/layer5/assets/41796013/6163b8e8-0924-4664-96c0-e820198ef290)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by arpitghura** [comment]
I would like to work on this issue.

**Comment by VivekBaldha0712** [comment]
i would like to work on this.

**Comment by Yagi91** [comment]
Please assign this to me

**Comment by iArchitSharma** [comment]
@arpitghura, could you please provide further explanation regarding this issue? Specifically, could you indicate the screen size at which this issue occurs and provide the link to the page where it can be observed?

**Comment by iArchitSharma** [comment]
@arpitghura, I checked, and the issue only appears for a width size of 768px and 769px. I believe the desired behavior of this section or CTA should be the same as at 767px.

**Comment by Abiey2579** [comment]
@arpitghura have you resolved the issue yet? Or still on it?

**Comment by arpitghura** [comment]
> @arpitghura have you resolved the issue yet? Or still on it?

I am waiting for the assignment of task. As soon as task is assigned, I will start working on it.

**Comment by iArchitSharma** [comment]
@arpitghura, maybe you should discuss it on [Slack](https://slack.layer5.io/) or during the next development [meeting](https://layer5.io/community/calendar).

**Comment by vishalvivekm** [comment]
@arpitghura 

Let's discuss this on Today's websites call. Please Join the meeting : https://meet.layer5.io/websites at 5:30 PM IST.
Meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit
// @iArchitSharma @Abiey2579

**Comment by arpitghura** [comment]
@vishalvivekm I have discussed this issue in the meet. Can you please assign it to me.

**Comment by abhijeetgauravm** [comment]
Here u go @arpitghura
