### ISSUE TITLE
Inactive Slack Workspace link in Newcomers webpage

### ISSUE THREAD

**Issue by Debaditya-Som** [layer5io/layer5#4758]
**Description:**
When attempting to join the community collaboration workspace via the provided Slack link on the website, users are encountering an issue where the link appears to be inactive, displaying the message "This link is no longer active."

**Expected Behavior:**
Clicking on the Slack workspace join link should successfully redirect users to the Slack website where they can proceed to join the community collaboration workspace without encountering an "inactive link" error message.

**Attachments:**
![Screenshot 2023-08-18 193023](https://github.com/layer5io/layer5/assets/121785700/b69922d4-740d-40e1-a364-2918197ffb44)

**Comment by abhijeetgauravm** [comment]
Can u provide the link of the page @Debaditya-Som where this issue is taking place?

**Comment by abhijeetgauravm** [comment]
Can u provide the link of page where this issue is taking place? @Debaditya-Som

**Comment by Debaditya-Som** [comment]
Here's the link to the website:
https://layer5.io/community/newcomers

**Comment by abhijeetgauravm** [comment]
hey @Debaditya-Som I just checked links are working fine .

**Comment by Ghat0tkach** [comment]
@Debaditya-Som its working fine for me as we
