### ISSUE TITLE
Incorrect Color Code for "Keppel" Color in themeStyles.js

### ISSUE THREAD

**Issue by Debaditya-Som** [layer5io/layer5#4760]
**Description :**
In the themeStyles.js file, there is an inconsistency in the color code for the "Keppel" color. The color code specified as #00d3a9 is incorrect and corresponds to the "Caribbean Green" color. The accurate HEX code for the "Keppel" color is #3ab09e.

**Proposed Solution :**
Update the color code for the "Keppel" color to the correct HEX code, #3ab09e, on both line 21 and line 249 of the themeStyles.js file.

**Impact:**
Correcting the color code will ensure the visual consistency of the theme and accurately reflect the intended "Keppel" color across the application's UI elements.

**Comment by leecalcote** [comment]
@Debaditya-Som, thanks for this. Yes, it will and you're right... save that you'll need to ensure that all uses/references of these color are updated so that the rest of the site isn't broadly, negatively affected.

**Comment by Debaditya-Som** [comment]
@leecalcote  I have already given a PR regarding this, updating the themeStyles.js file. I'm checking if there are any other files where I need to modify this change. 
Thank you
