### ISSUE TITLE
[Visual Design] New Recognition Badge: GitOps Connected

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4782]
### Current Behavior
[Layer5 recently announced](https://layer5.io/blog/community/layer5-recognition-program) an enhancement to the ways in which it recognizes milestones achieved by contributors and users.(see community handbook) with an improved badge award system --> https://badges.layer5.io.

### Desired Behavior
An initial set of badges exists, however, there are a number of new badges that need to be created. This issue calls for a volunteer to draft a new badge.

**Who is this badge for?**  
Users

**What milestone does this badge recognize?** 
This badge is awarded to users upon establishment of a connection with Meshery GitHub App.

### Implementation
1. Leverage [Layer5 brand guide](https://layer5.io/company/brand) to create designs for a new badge.
1. Create one or more new badge design drafts in the community Figma file on the [Assets: Member Cards and Badges](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=18929-6269&mode=design&t=EWSK72cRG8wx4E8g-4) page. Alternatively, after submitting a community member form, request the `badges.ai` file if you prefer to work within Adobe Illustrator.
1. Post your Call-for-Design-Review on https://discuss.layer5.io. 
1. Attend a weekly "Websites" meeting ([held on Mondays](https://meet.layer5.io)), present your design, and receive feedback.

### Acceptance Tests
1. Community (at-large) has been given an opportunity to review. 
1. Maintainers have reviewed and approved badge designs.

#### Mockups
_see existing badge designs for inspiration and brand styling_

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Shreya111111** [comment]
kindly assign this to me

**Comment by Chadha93** [comment]
Thanks for the heads-up @Shreya111111. Assigned. Please also present an update at Monday's Website's meeting.

**Comment by Shreya111111** [comment]
@Chadha93 sure

**Comment by Shreya111111** [comment]
@Chadha93 from where can i get the edit access to figma file

**Comment by Shreya111111** [comment]
@Chadha93 can i do it in my own figma

**Comment by Shreya111111** [comment]
or the figma file above as it requires access

**Comment by Ghat0tkach** [comment]
hey @Shreya111111 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by Shreya111111** [comment]
@Ghat0tkach I'm unable to attend meet due to some unforeseen urgent work. will share my design till tomorrow evening

**Comment by vishalvivekm** [comment]
@Shreya111111 would you please sound off with the status on the issue on today's websites call ? 
Please join the call at 5:30 PM IST : https://meet.layer5.io/websites
Meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima

**Comment by leecalcote** [comment]
Draft designs to review, @Shreya111111?

**Comment by leecalcote** [comment]
Let's free up assignment given the lack of current momentum.

**Comment by nwanduka** [comment]
This badge has already been designed by John Areola. He shared the design on the Slack channel and it has been added to the assets folder [here.](https://github.com/layer5labs/meshery-extensions-packages/tree/master/assets/badges/gitops-connected) So I guess this issue is ready to be closed.

**Comment by leecalcote** [comment]
Thank you!
