### ISSUE TITLE
[Visual Design] New Recognition Badge: MeshMap Snapshot

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4783]
### Current Behavior
[Layer5 recently announced](https://layer5.io/blog/community/layer5-recognition-program) an enhancement to the ways in which it recognizes milestones achieved by contributors and users.(see community handbook) with an improved badge award system --> https://badges.layer5.io.

### Desired Behavior
An initial set of badges exists, however, there are a number of new badges that need to be created. This issue calls for a volunteer to draft a new badge.

**Who is this badge for?**  
Users

**What milestone does this badge recognize?** 
This badge is awarded to users upon creation of their first infrastructure screenshot directly in their pull request.

### Implementation
1. Leverage [Layer5 brand guide](https://layer5.io/company/brand) to create designs for a new badge.
1. Create one or more new badge design drafts in the community Figma file on the [Assets: Member Cards and Badges](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=18929-6269&mode=design&t=EWSK72cRG8wx4E8g-4) page. Alternatively, after submitting a community member form, request the `badges.ai` file if you prefer to work within Adobe Illustrator.
1. Post your Call-for-Design-Review on https://discuss.layer5.io. 
1. Attend a weekly "Websites" meeting ([held on Mondays](https://meet.layer5.io)), present your design, and receive feedback.

### Acceptance Tests
1. Community (at-large) has been given an opportunity to review. 
1. Maintainers have reviewed and approved badge designs.

#### Mockups
_see existing badge designs for inspiration and brand styling_

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by nwanduka** [comment]
I'd like to work on this issue, please.

**Comment by Ps1231** [comment]
Hey @leecalcote I'd really like to work on this issue .

**Comment by abhijeetgauravm** [comment]
Assigning in chronological order! Go for it @nwanduka

**Comment by nwanduka** [comment]
On it

**Comment by nwanduka** [comment]
[Here's the badge design](https://www.figma.com/file/vXAzeVtZhbCQrr9rRrpAUJ/Untitled?type=design&node-id=0%3A1&mode=design&t=hGc2UL4MSY7yxVx0-1) I came up with for this issue. I don't have access to edit the community Figma file yet so I designed it in a separate draft. Any comments/reviews on the design?

**Comment by abhijeetgauravm** [comment]
> [Here's the badge design](https://www.figma.com/file/vXAzeVtZhbCQrr9rRrpAUJ/Untitled?type=design&node-id=0%3A1&mode=design&t=hGc2UL4MSY7yxVx0-1) I came up with for this issue. I don't have access to edit the community Figma file yet so I designed it in a separate draft. Any comments/reviews on the design?

@ritiksaxena124 thoughts?

**Comment by ritiksaxena124** [comment]
Great work @nwanduka 👏 closing this as it is completed.

**Comment by nwanduka** [comment]
Awesome! On to the next 🚀

**Comment by nwanduka** [comment]
Awesome. On to the next 🚀
