### ISSUE TITLE
[Community] Member Profile: Aritra Majumder

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4786]
**Current Behavior**

@Aritra8438  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Aritra8438 s a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Aritra8438 
- Twitter: 
- LinkedIn: [aritra-majumder-juee23](https://www.linkedin.com/in/aritra-majumder-juee23 )
- Meshery Cloud:[1b462fee-7808-4a79-a504-9c4e986f32b9](https://meshery.layer5.io/user/1b462fee-7808-4a79-a504-9c4e986f32b9) 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Ghat0tkach** [comment]
@Aritra8438 ,would you please toss in a link to your social links ,pic and your bio ⭐

**Comment by brijeshbhikadiya** [comment]
i would like to work on this issue.

**Comment by Aritra8438** [comment]
Hi @brijeshbhikadiya, this is not an issue to work with, I guess.

**Comment by brijeshbhikadiya** [comment]
sorry i would like to work on it.

**Comment by Aritra8438** [comment]
[profile pic](https://media.licdn.com/dms/image/D4D03AQFTTMT-7HNEHQ/profile-displayphoto-shrink_400_400/0/1683474189737?e=1698278400&v=beta&t=O1mBi4fseRGZISX1LSeabgTU5DaUfthfoFCOTnlDHBQ)

I don't really use Twitter.

**Comment by Aritra8438** [comment]
> sorry i would like to work on it.

Hi, @brijeshbhikadiya. May I ask what do you want to do with this issue? I'm not sure, @Ghat0tkach??

**Comment by Aritra8438** [comment]
Not sure with these, but no problem with me, I have attached my pic in the comment.

**Comment by vobanghia12** [comment]
Hi could I work on this issue please ? Thanks

**Comment by hirentimbadiya** [comment]
> Hi could I work on this issue please ? Thanks

hey @vobanghia12, @brijeshbhikadiya is already working on this issue, you can look for other issues in community.

**Comment by brijeshbhikadiya** [comment]
@Aritra8438  give me your bio so that i can add your community member profile in layer5 community member page.

**Comment by Aritra8438** [comment]
Aritra (You can omit surname if allowed)
Chennai, India
Hi, I'm Aritra, currently pursuing Master's in Computer science at Chennai Mathematical Institute. I'm also a software developer and open-source enthusiast.

Is that enough? @brijeshbhikadiya

**Comment by brijeshbhikadiya** [comment]
@Aritra8438 give me more detailed bio.

**Comment by Aritra8438** [comment]
Okay! Add:
I'm currently a Google Summer of Code '23 contributor at Mathesar. Besides development, I love mathematics, soccer and anime.
@brijeshbhikadiya

**Comment by brijeshbhikadiya** [comment]
okay that's enough

**Comment by brijeshbhikadiya** [comment]
okay that's enough

**Comment by Ghat0tkach** [comment]
hey @brijeshbhikadiya 
let's discuss about your progress on the websites call.
Please add this as an agenda item in the meeting minutes, if you would :)
https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima
