### ISSUE TITLE
Search Bar loses Focus when you don't type fast

### ISSUE THREAD

**Issue by Layak-Ali** [layer5io/layer5#4788]
### Description
I'm having trouble with Layer5's website's search function. When I type to search for blogs, it shows results for each letter I enter. However, if I don't type quickly, it removes my cursor, which makes the search frustrating. For instance, I need to click the search bar multiple times to search for something like '**How to bind Kubernetes**'.

### Expected Behavior
The cursor should remain in the search bar without being interrupted or removed, regardless of typing speed.

### Screenshots
![Screenshot (28)](https://github.com/layer5io/layer5/assets/93964740/e86994e0-d579-48ed-93a8-f0e3a99c72ea)

### Environment:
- Host OS: Windows
- Browser: Brave Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
@kayceeDev will you validate this report as an issue?

**Comment by kayceeDev** [comment]
> @kayceeDev will you validate this report as an issue?

This is not an issue. We run a query with the value in the search box after every 5 seconds of inactivity. That is, if you add a new letter to the search and don't type anything for 5 secs, a query is run with the  value inside the search. We used a denounce input to make sure the search box doesn't lag when you type quickly. All you have to do when you see that the focus is removed from the search is to set it in focus again and type more words or a new word. Remember that without this delay before making the search, we will have to make a query for each keystroke immediately and this lags the UI.

**Comment by Layak-Ali** [comment]
While I was searching, the focus was removed after just 1 second of inactivity. This made it difficult to search for a specific blog properly.

**Comment by kayceeDev** [comment]
> While I was searching, the focus was removed after just 1 second of inactivity. This made it difficult to search for a specific blog properly.

Alright, I will validate this issue @leecalcote. An optimization idea is a welcomed one. @Layak-Ali looking forward to your PR.

**Comment by iArchitSharma** [comment]
@kayceeDev, I tried searching as a user, and it's taking less than a second of inactivity before debouncing
It's difficult to type in the search bar.

**Comment by kayceeDev** [comment]
@Layak-Ali will you like to take up this issue?

**Comment by iArchitSharma** [comment]
@kayceeDev, I'd be happy to work on this issue if @Layak-Ali isn't planning to.

**Comment by kayceeDev** [comment]
> @kayceeDev, I'd be happy to work on this issue if @Layak-Ali isn't planning to.

Alright. Let's wait for @Layak-Ali awhile.

**Comment by kayceeDev** [comment]
> @kayceeDev, I'd be happy to work on this issue if @Layak-Ali isn't planning to.

Here you go.

**Comment by Layak-Ali** [comment]
Oh sorry guys @kayceeDev @iArchitSharma for not responding. I was busy the last few days due to exams. I planned to work on it today/tommorow but its fine if you want to work on it.

**Comment by iArchitSharma** [comment]
@kayceeDev, the **debounceTimeout** was initially set to 500ms (0.5 seconds). I am submitting a pull request to change it to 5000ms (5 seconds)

**Comment by kayceeDev** [comment]
> @kayceeDev, the **debounceTimeout** was initially set to 500ms (0.5 seconds). I am submitting a pull request to change it to 5000ms (5 seconds)

Think about this before increasing the timeout, is 5 secs user friendly? Will a user searching for a blog willing to wait for 5 seconds to have search results returned? Can you make it better and return search results in real time? What are the edge cases? will there be a performance reduction since the query will be run on each value typed in the search box? If all these questions are checked out and increasing the timeout helps, then maybe that can be accepted as the solution. 

I am open to discussing your thoughts process with increasing the timeout.

**Comment by kayceeDev** [comment]
@Layak-Ali can you also share ways you had in mind to solve this issue to give @iArchitSharma some ideas

**Comment by Layak-Ali** [comment]
I planned to increase the time to 1 or 2 second(s) which is more than enough. Users will press enter rather than wait 5 seconds.
