### ISSUE TITLE
[Calendar] Remove "SMI Community Meeting" from Meetings table

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4793]
### Current Behavior
The[ layer5.io/calendar page](https://layer5.io/community/calendar#meetings) has an entry for "CNCF SMI Community Meeting", which needs to be removed.

### Desired Situation
Edit this page - https://github.com/layer5io/layer5/blob/master/src/pages/community/calendar.js

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VamshiReddy02** [comment]
Can I work on this Issue?

**Comment by jiyanpatil07** [comment]
@leecalcote 
would like to work on this issue!
Thank You

**Comment by Ghat0tkach** [comment]
Thank you for volunteering gents, Assigning in chronological order
