### ISSUE TITLE
[Community] Member Profile: Vaibhav Malik

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4798]
**Current Behavior**

@VaibhavMalik4187  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @VaibhavMalik4187 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @VaibhavMalik4187
- Twitter: 
- LinkedIn: [vaibhavmalik4187](https://www.linkedin.com/in/vaibhavmalik4187) 
- Meshery Cloud: [495185a6-7aa4-4c66-a7ff-2e5e7e7c9768](https://meshery.layer5.io/user/495185a6-7aa4-4c66-a7ff-2e5e7e7c9768) 
- Link to profile picture:[link](https://gitlab.com/uploads/-/system/user/avatar/10628053/avatar.png?width=400)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Ghat0tkach** [comment]
@VaibhavMalik4187 would you please toss your bio here? 😎

**Comment by Layak-Ali** [comment]
@Ghat0tkach can you assign me this issue. I would like to work on it.

**Comment by VaibhavMalik4187** [comment]
Bio:
Hi, I am an ardent advocate of open-source initiatives, presently engrossed in the realms of DevOps and Backend development. I have had the privilege of participating as a mentee in the Google Summer of Code (GSoC) program under the aegis of Inkscape for two consecutive years. Moreover, during the recent summer term, I undertook an internship at Sprinklr, situated in Gurgaon, where I assumed the role of a Product Engineer.
I hold a distinct inclination towards C and C++, considering them as my primary programming preferences. Should you require any assistance in embarking upon open-source contributions, please do not hesitate to reach out to me. Your inquiries are most welcome.

**Comment by sarfarazstark** [comment]
If the issue is still open please assign me I would like to work on it

**Comment by Layak-Ali** [comment]
no. i am working on it

**Comment by aarav1656** [comment]
![Screenshot from 2023-08-19 09-20-02](https://github.com/layer5io/layer5/assets/110886757/5e5fe6b0-d413-40db-b83e-64c76f242df9)
I have done it, pls assign me

**Comment by aarav1656** [comment]
![Screenshot from 2023-08-31 15-29-39](https://github.com/layer5io/layer5/assets/110886757/d1edddfc-11a5-41e2-9fe2-13fff9839545)
I have done it, pls assign me

**Comment by aarav1656** [comment]
![image](https://github.com/layer5io/layer5/assets/110886757/bd15bbf7-69bb-46ac-955a-0d01e6c0b564)

I have done it, pls assign me

**Comment by dibyendu02** [comment]
I was in queue

**Comment by Layak-Ali** [comment]
@Ghat0tkach almost done. will PR at night. low internet connection at my university

**Comment by Ghat0tkach** [comment]
Since @Layak-Ali is unable to raise a PR, and this is quite important because we shouldn't wait any longer to recognize our valuable contributors, I'll take this into my own hands.

**Comment by Layak-Ali** [comment]
oh sorry. i couldnt do it due to low internet connection. Can you wait an hour please?

**Comment by Layak-Ali** [comment]
@Ghat0tkach can you please merge my PR?? I couldn't do it fast because Vaibhav replied his bio a bit late

**Comment by Layak-Ali** [comment]
@Ghat0tkach can you please merge this #4815 pull request ?

**Comment by Layak-Ali** [comment]
@Ghat0tkach can you merge this PR please?

**Comment by Ghat0tkach** [comment]
@Layak-Ali 
I am withdrawing my PR, but this does not mean that you should delay addressing the assigned issue until someone else takes care of it. Please consider addressing such matters promptly in the future.

**Comment by Layak-Ali** [comment]
@Ghat0tkach Yes i will try not to delay creating a PR.
