### ISSUE TITLE
[NG] Revise CONTRIBUTING.md

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#480]
**Description**

Revise the contributor's guide to highlight the changes caused by the shift from Jekyll to Gatsby.

**Comment by Jashpatel1** [comment]
@chandrashritii Does it mean to add another section in CONTRIBUTING.md regarding contributing to layer5-ng or replace the existing one?

**Comment by chandrashritii** [comment]
@Jashpatel1 We intend to update the original instructions here. This will actually require a little more context. Let's instead get you on one of the other open issues

**Comment by leecalcote** [comment]
> @chandrashritii Does it mean to add another section in CONTRIBUTING.md regarding contributing to layer5-ng or replace the existing one?

@Jashpatel1 the ask here is to augment the existing CONTRIBUTING.md in the `layer5-ng` branch with Gatsby instructions, not Jekyll instructions - https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md

**Comment by leecalcote** [comment]
Done
