### ISSUE TITLE
[Visual Design] New Recognition Badge: Review Rockstar Badge

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#4807]
### Current Behavior
[Layer5 recently announced](https://layer5.io/blog/community/layer5-recognition-program) an enhancement to the ways in which it recognizes milestones achieved by contributors and users. (see community handbook) with an improved badge award system --> https://badges.layer5.io/.

### Desired Behavior
An initial set of badges exists, however, there are a number of new badges that need to be created. This issue calls for a volunteer to draft a new badge.

#### Who is this badge for?
Contributors

#### What milestone does this badge recognize?
This badge is awarded to individuals who provide thorough and valuable code reviews.
### Implementation
1. Leverage [Layer5 brand guide](https://layer5.io/company/brand) to create designs for a new badge.
2. Create one or more new badge design drafts in the community Figma file on the [Assets: Member Cards and Badges](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=18929-6269&mode=design&t=EWSK72cRG8wx4E8g-4) page. Alternatively, after submitting a community member form, request the `badges.ai` file if you prefer to work with Adobe Illustrator.
3. Post your Call-for-Design-Review on https://discuss.layer5.io/.
4. Attend a weekly "Websites" meeting ([held on Mondays](https://meet.layer5.io/)), present your design, and receive feedback.
### Acceptance Tests
1. Community (at-large) has been given an opportunity to review.
2. Maintainers have reviewed and approved badge designs.
3. Once the design is finalized and approved then you can make the PR in the badges [repository](https://github.com/layer5labs/meshery-extensions-packages) after adding the badge in the badge folder inside assets and the static folder in repo.
### Mockups
See existing badge designs for inspiration and brand styling

<hr />
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ritiksaxena124** [comment]
Use [Badge Template.zip](https://github.com/layer5io/layer5/files/12496459/Badge.Template.zip) file to create badges

**Comment by csengineer1990** [comment]
I am a newcomer and also new to Figma so can I able to work on the above issues?

**Comment by ritiksaxena124** [comment]
Yes @csengineer1990 you can try your hands on 🙌

**Comment by nwanduka** [comment]
Hi @csengineer1990, any progress on this?

**Comment by nwanduka** [comment]
If this is still open, I'd like to give it a shot. @ritiksaxena124, can I go ahead?

**Comment by ritiksaxena124** [comment]
It has been days since we didn't hear from @csengineer1990 so @nwanduka it's all yours 👍

**Comment by nwanduka** [comment]
What do you think of this rockstar? 😂

![Review Rockstar](https://github.com/layer5io/layer5/assets/122698422/18bdf12e-2146-4917-95d3-02703aea3640)

**Comment by leecalcote** [comment]
It's pretty great, I think. I wonder if the figure couldn't / shouldn't be slightly larger in the hexagon version...

**Comment by nwanduka** [comment]
Thanks for the feedback, Lee. I see what you mean. How does it look now?
![Review Rockstar update](https://github.com/layer5io/layer5/assets/122698422/75836360-2937-42b4-a7f8-c021c5d2b59a)

**Comment by ritiksaxena124** [comment]
Looks good to me 👏. @nwanduka could you please share the SVG version of the badge?

**Comment by nwanduka** [comment]
Sure. Here you go @ritiksaxena124 
![Review Rockstar (Polygon)](https://github.com/layer5io/layer5/assets/122698422/7964608e-00d1-4751-b797-d8b5ce1c862b)
![Review Rockstar Badge](https://github.com/layer5io/layer5/assets/122698422/77af1afd-3340-4439-b624-3b23817cc11f)

Should I add them to the badges folder and raise a PR?

**Comment by Chenwei-Niu** [comment]
Hi, I tried to add this badge to the badges webpage. But I found that the font of the badge is incompatible with others.
<img width="599" alt="" src="https://github.com/layer5io/layer5/assets/61908960/ff3dbd83-3e5e-476a-8c07-bed9aaeb33c9">

Besides, the svg file seems having different style compared to others. Paths have no class selectors and there is no style tag in the svg file.
Other svg badge:
<img width="1191" alt="image" src="https://github.com/layer5io/layer5/assets/61908960/6f2f6cc6-dbda-4f09-937a-ef72b64655b6">
<img width="1201" alt="image" src="https://github.com/layer5io/layer5/assets/61908960/3fde6a41-782f-4363-b4a3-6d1f1cbdb643">


Review rockstar svg badge:
<img width="1196" alt="image" src="https://github.com/layer5io/layer5/assets/61908960/98df7081-939d-4a5c-a477-f95fbdd50ad1">


@nwanduka

**Comment by ritiksaxena124** [comment]
Thank you @nwanduka 🙌 you are amazing. I have added the badge to the site 👍
