### ISSUE TITLE
[NG] Identify all React plugins

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#481]
**Description**

Identify and make a list of all the React components currently used by the Layer5 site to prepare for the migration to Layer5-ng.

**Comment by Nikhil-Ladha** [comment]
The present Layer5 site is a Jekyll site. So, I don't get the purpose of the issue? @chandrashritii if you can explain a bit more?

**Comment by leecalcote** [comment]
@Nikhil-Ladha, yes, this is for the `layer5-ng` site under a branch by that same name.

**Comment by leecalcote** [comment]
@Tanuj22 create issues for each plugin on the list to incorporate.

**Comment by Nikhil-Ladha** [comment]
@leecalcote , now I get it. I think the title was a bit misleading 😅. Now, it's more clear.

**Comment by Tanuj22** [comment]
@leecalcote Do we need the Strapi and the sitemap plugin now or should we hold off on them.

**Comment by leecalcote** [comment]
We're ready for sitemap now.

**Comment by Tanuj22** [comment]
Closing as all plugins have been identified
