### ISSUE TITLE
[Visual Design] New Recognition Badge: Continuous Contributor Badge

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#4810]
### Current Behavior
[Layer5 recently announced](https://layer5.io/blog/community/layer5-recognition-program) an enhancement to the ways in which it recognizes milestones achieved by contributors and users. (see community handbook) with an improved badge award system --> https://badges.layer5.io/.

### Desired Behavior
An initial set of badges exists, however, there are a number of new badges that need to be created. This issue calls for a volunteer to draft a new badge.

#### Who is this badge for?
Contributors

#### What milestone does this badge recognize?
This badge is awarded to individuals for their consistent contributions over a certain period.

### Implementation
1. Leverage [Layer5 brand guide](https://layer5.io/company/brand) to create designs for a new badge.
2. Create one or more new badge design drafts in the community Figma file on the [Assets: Member Cards and Badges](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=18929-6269&mode=design&t=EWSK72cRG8wx4E8g-4) page. Alternatively, after submitting a community member form, request the `badges.ai` file if you prefer to work with Adobe Illustrator.
3. Post your Call-for-Design-Review on https://discuss.layer5.io/.
4. Attend a weekly "Websites" meeting ([held on Mondays](https://meet.layer5.io/)), present your design, and receive feedback.
### Acceptance Tests
1. Community (at-large) has been given an opportunity to review.
2. Maintainers have reviewed and approved badge designs.
### Mockups
See existing badge designs for inspiration and brand styling

<hr />
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ritiksaxena124** [comment]
Use [Badge Template.zip](https://github.com/layer5io/layer5/files/12496459/Badge.Template.zip) file to create badges

**Comment by nwanduka** [comment]
I'd like to work on this issue, please. @ritiksaxena124

**Comment by ritiksaxena124** [comment]
Assigning to you @nwanduka 🙌

**Comment by nwanduka** [comment]
Great! Time to get to work👩🏽‍💻

**Comment by nwanduka** [comment]
I came up with two design options for this badge. You'll find them [here](https://www.figma.com/file/vXAzeVtZhbCQrr9rRrpAUJ/Untitled?type=design&node-id=0%3A1&mode=design&t=W6xojhoowGBfpboD-1) on the frame named "Continuous Contributor".

Which do you think is better? I'll appreciate your honest feedback. @ritiksaxena124

**Comment by Opeyemi-Onifade** [comment]
Hello. I'd like to contribute on this. @ritiksaxena124 @nwanduka

**Comment by ritiksaxena124** [comment]
Hey @Opeyemi-Onifade, @nwanduka is working on this issue, no sweat we have a couple more issues similar to this. You can comment down your name on other issues so that we can assign you

**Comment by nwanduka** [comment]
@ritiksaxena124, you may have forgotten to close this issue.
