### ISSUE TITLE
Create new project card for "Service Mesh Distributed Performance Management"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#482]
**Current Situation**

@kushthedude is working through a Google Summer of Code internship that is focused on incorporating Envoy proxy's Nighthawk load generator into Meshery. We are missing a [project page](https://layer5.io/projects) that describes this.

**Implementation**

- This is the start to a project page (it began as a copy of the SMI project page) - 
https://github.com/layer5io/layer5/blob/master/collections/_projects/service-mesh-distributed-performance-management.md.
- a new project card should show up here https://layer5.io/projects

**Resources**
- this blog post describes the project - https://layer5.io/blog/gsoc-with-layer5-and-cncf
- this proposal describes the project - https://docs.google.com/document/d/1qgvkTYSBDga-QmLHR9uK-utgiWAUcpF5-2Z4zaNqej0/edit?usp=sharing
- this design spec describes the project - https://docs.google.com/document/d/1_hhQ5w1iLClgf7RvboI6il-eMKKAVPwz50GHm2VN4Bg/edit?usp=sharing

**Comment by Jashpatel1** [comment]
@leecalcote I would like to work on this issue.

**Comment by Jashpatel1** [comment]
@leecalcote I would like to work on this issue.

**Comment by kushthedude** [comment]
Sure go ahead @Jashpatel1 , ping me if you need more details about the content that needs to be exposed through the card.
