### ISSUE TITLE
[Community] Member Profile: Yash Sharma

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4820]
**Current Behavior**

@yash37158 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @yash37158 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @yash37158
- Twitter:[YashSha49433608](https://twitter.com/YashSha49433608)
- LinkedIn: [yash-sharma-7b688a19b](https://www.linkedin.com/in/yash-sharma-7b688a19b/)
- Meshery Cloud: 
- Link to profile picture:[link](https://drive.google.com/drive/folders/1Z6O09sf6TM_ye2hbl-pkduufzLv-lkex?usp=sharing)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Ghat0tkach** [comment]
@yash37158 please toss in your bio and meshery cloud uuid🚀

**Comment by akhilender-bongirwar** [comment]
Hey @Ghat0tkach, I would like to work on this issue.

**Comment by brijeshbhikadiya** [comment]
I would like to work on this issue assign me.

**Comment by abhijeetgauravm** [comment]
Assigning in chronological order!

**Comment by akhilender-bongirwar** [comment]
@yash37158 could you please provide me your bio and meshery cloud uuid  : ) ...

**Comment by vishalvivekm** [comment]
> @yash37158 could you please provide me your bio and meshery cloud uuid : ) ...

@yash37158

**Comment by yash37158** [comment]
Yeah sure @abhijeetgauravm, here you are with the details 

[BIO]
As a dedicated software developer deeply committed to the world of open-source software and community expansion, I have a strong fascination for the cloud-native ecosystem. My journey began with the discovery of Meshery, a pivotal introduction to this captivating field. Beyond my own growth, I find fulfillment in mentoring aspiring developers and actively participating in forums and communities to share valuable insights. My goal is to engineer scalable and efficient applications by delving into Microservices and harnessing the power of cloud technologies. My unwavering dedication to open source drives me to create exceptional solutions while staying at the forefront of the latest technologies. Let's collaborate to elevate the open-source community to new heights by crafting outstanding solutions together.

Uuid:
53ccd221-c66b-4815-93df-397013b0200a
