### ISSUE TITLE
[Screenshots] Actions Runner Controller (ARC) "How it Works See It in Action” section

### ISSUE THREAD

**Issue by Chadha93** [layer5io/layer5#4827]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/akri) has only two old screenshots of the designer and visualizer in the  "How it Works See It in Action” section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for **[Actions Runner Controller (ARC)](https://layer5.io/cloud-native-management/meshery/integrations/actions-runner-controller-arc)**  integration.

### Acceptance Points

- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser. 
- Use Incognito mode on chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sandramsc** [comment]
Hi, can I have this issue assigned to me please?

**Comment by abhijeetgauravm** [comment]
Yeah @sandramsc

**Comment by iArchitSharma** [comment]
Issue already fixed!
