### ISSUE TITLE
[Screenshots] Ambassador under 'How it Works See It in Action' section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4835]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/ambassador) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Ambassador](https://layer5.io/cloud-native-management/meshery/integrations/ambassador) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ATREAY** [comment]
Hey @saurabh100ni, mind if I work on this issue? 
I'm pretty new to meshmap, and I think it could be a great learning experience for me.

**Comment by saurabh100ni** [comment]
It it for sure, Here you go @ATREAY 😎🚀

**Comment by saurabh100ni** [comment]
There you go : https://docs.meshery.io/extensions/meshmap

**Comment by ATREAY** [comment]
Hey @saurabh100ni, I went through the documentation, but it mostly covers how to design the cluster. There isn't much on deploying, validating the design, or dealing with errors. It would be incredibly helpful if there were tutorials to guide us through these aspects. I'm having trouble enabling adapters; they seem to turn off automatically when I close the extension tab.

**Comment by saurabh100ni** [comment]
did you go through [Meshmap Designer Walkthrough ](https://youtu.be/qaoYRP3oLok)?

**Comment by ATREAY** [comment]
Yeah, I checked out the walkthrough, but here's the issue: in the very first step, the video says we're supposed to pick one adapter, but in my situation, those adapters aren't showing up even though I've turned them on in the extension.

Here's what the video showed:

![video image](https://github.com/layer5io/layer5/assets/66585295/b959f08e-a0c2-4a36-9c70-deb06dc8855a)

And here's what I'm seeing:

![meshmap adapters error](https://github.com/layer5io/layer5/assets/66585295/48cb6b48-dbfc-4352-a553-92ece964e791)

**Comment by TyagiRajat** [comment]
hey @narasimha-1511 i want to work on this issue , i have set up my local environtment

**Comment by narasimha-1511** [comment]
Go on @TyagiRajat
