### ISSUE TITLE
[Screenshots] Argocd Operator under 'How it Works See It in Action' section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4848]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/argocd-operator) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Argocd Operator](https://layer5.io/cloud-native-management/meshery/integrations/argocd-operator) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
can you please assign me this issue

**Comment by saurabh100ni** [comment]
Rock on @Harsha-10  😎🚀

**Comment by Harsha-10** [comment]
hey @saurabh100ni , there is only one design on ArgoCD in meshery catalog. can i use that for operator?

**Comment by saurabh100ni** [comment]
@Yashsharma1911 @sudhanshutech can help us.

**Comment by Harsha-10** [comment]
No reply here yet @saurabh100ni

**Comment by saurabh100ni** [comment]
Oh! I see, I will make sure that someone will go through this. Thanks for reminding

**Comment by Harsha-10** [comment]
Any update? @saurabh100ni

**Comment by Harsha-10** [comment]
<img width="960" alt="image" src="https://github.com/layer5io/layer5/assets/94053954/3f4a0761-73b0-4ebe-a4fe-b367e5466221">
Is this a correct one?

**Comment by saurabh100ni** [comment]
Hey @Harsha-10 you didn't include the ArgoCD Operator integration in this, please include it. [You can take this as reference.](https://6530c90e907db676fe074d36--layer5.netlify.app/cloud-native-management/meshery/integrations/backstage).

Thanks staying connected and engaging with us consistently ^ ^

**Comment by Harsha-10** [comment]
Thanks for this, i will check it out

**Comment by Harsha-10** [comment]
Since I have tried alot,I'm unable to solve the issue. I'm unassigning me...

**Comment by Aarya01Patil** [comment]
Hi @sandramsc @narasimha-1511 , I would love to work on this issue. Can you assign it to me?

**Comment by shivam1234100** [comment]
Hey @Ashparshp Can you please assign this to me , I believe I can fix this issue

**Comment by narasimha-1511** [comment]
Hey @Aarya01Patil as you have two another same issues assigned i am assigning this to @shivam1234100
