### ISSUE TITLE
[Screenshots] Consul under 'How it Works See It in Action' section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4873]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/consul) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Consul](https://layer5.io/cloud-native-management/meshery/integrations/consul) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
i would like to work on this

**Comment by Harsha-10** [comment]
hey i'm unable to figure out this issue, please unassign me

**Comment by saurabh100ni** [comment]
@Harsha-10 I'm unassigning you,
Ps: We have plenty of issues you might wanna lay your eyes on 👀

**Comment by Harsha-10** [comment]
Yeah sure, can you please tell what all i need to learn to solve these kind of issues? Like I'm only into web development... But I love to learn anything to contribute here @saurabh100ni

**Comment by saurabh100ni** [comment]
You just need to explore [MeshMap](https://layer5.io/cloud-native-management/meshmap/design) a little and then it's just web development.

**Comment by Harsha-10** [comment]
Okay thanks! I will definitely look into it and come back to this

**Comment by abhijeetgauravm** [comment]
> Yeah sure, can you please tell what all i need to learn to solve these kind of issues? Like I'm only into web development... But I love to learn anything to contribute here @saurabh100ni

hey @Harsha-10 u can go through this [docs](https://docs.meshery.io/extensions/meshmap) for better understanding of meshmap.

**Comment by Harsha-10** [comment]
Thank you so much!

**Comment by Yash-sudo-web** [comment]
hey @saurabh100ni, can i work on this issue?

**Comment by abhijeetgauravm** [comment]
there u go @Yash-sudo-web

**Comment by Yash-sudo-web** [comment]
@saurabh100ni , can you please specify the path to the folder where the screenshots needs to be added, thanks

**Comment by abhijeetgauravm** [comment]
hey @Yash-sudo-web you are supposed to add the new screenshots of the designer and visualizer in this path src/collections/integrations/_images
