### ISSUE TITLE
[Screenshots] Containerd under 'How it Works See It in Action' section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4875]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/containerd) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Containerd](https://layer5.io/cloud-native-management/meshery/integrations/containerd) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by thakuraman24** [comment]
I would like to try to add the screenshot can this issue be assigned to me?

**Comment by saurabh100ni** [comment]
Go on @thakuraman24 😎🚀

**Comment by thakuraman24** [comment]
would screenshots like this work for the new version of the mesh map? I know I also need to demonstrate some test design and visualization screenshots & videos but don't know where to find them, can you help me with that?
![Screenshot (63)](https://github.com/layer5io/layer5/assets/97963364/40d680bc-a88a-4d9b-b6eb-cdfce34e3710)

**Comment by Yash-sudo-web** [comment]
hey, @saurabh100ni  , can i work on this since the other person is unresponsive?

**Comment by saurabh100ni** [comment]
Go On @Yash-sudo-web 😎🚀

**Comment by ninadvyas** [comment]
hello can I work on this issue?

**Comment by ninadvyas** [comment]
Hey @saurabh100ni ,Can you tell me how to get new images for screenshots??

**Comment by sandramsc** [comment]
Hi @ninadvyas  do you still intend to work on this issue? Let us know so we know to allow you more time, otherwise, we'll need to free (unassign you) the issue to allow other contributors to give it a go. If you are encouraged to post questions related to the issue and ask for guidance via the [discussion forum](https://discuss.layer5.io/).

**Comment by surajvast1** [comment]
hey @iArchitSharma please assign this to me it would mean a lot thanks !!

**Comment by surajvast1** [comment]
Hello @iArchitSharma,
Regarding the screenshots, could you please advise on the preferred platform for uploading them? Additionally, is it ok to make changes in the code base?

**Comment by surajvast1** [comment]
@saurabh100ni please review
