### ISSUE TITLE
[Screenshots] Crossplane under 'How it Works See It in Action' section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4882]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/crossplane) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Crossplane](https://layer5.io/cloud-native-management/meshery/integrations/crossplane) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by harshit-paneri** [comment]
"Hello, may I take on this task?"k?"

**Comment by abhijeetgauravm** [comment]
there u go @harshit-paneri

**Comment by harshit-paneri** [comment]
Hey @abhijeetgauravm , can you please explain this issue? 
https://discuss.layer5.io/t/screenshots-crossplane-under-how-it-works-see-it-in-action-section/3584?u=harshit
What I understand is right.

**Comment by harshit-paneri** [comment]
Hello, I am unable to understand the concept of a mash map at this stage. Could you please assign this task to someone else? I am more comfortable working on front-end issues.

**Comment by abhijeetgauravm** [comment]
> Hey @abhijeetgauravm , can you please explain this issue? https://discuss.layer5.io/t/screenshots-crossplane-under-how-it-works-see-it-in-action-section/3584?u=harshit What I understand is right.

yeah @harshit-paneri u understood right though!

**Comment by coder12git** [comment]
Hey @abhijeetgauravm I want to work on this issue.

**Comment by abhijeetgauravm** [comment]
There u go @coder12git

**Comment by coder12git** [comment]
> There u go @coder12git

Thanks

**Comment by coder12git** [comment]
@abhijeetgauravm Hey, while running site using - make site , I am getting process killed issue, I found that my system is running out of memory , is there any way to fix this? Or is it possible for you to give me some compile files that's required to run the site, as it's taking lot's of space in my system to compile those files?

**Comment by saurabh100ni** [comment]
@coder12git Try using Git-Pod, it may help

**Comment by coder12git** [comment]
> @coder12git Try using Git-Pod, it may help

Yeah, it's working, thanks!

**Comment by saurabh100ni** [comment]
Anytime ;)

**Comment by coder12git** [comment]
Hey @saurabh100ni I was wondering, when I will get demo video which will tell about crossplane integration, as discussed in the last meet.
