### ISSUE TITLE
[Screenshots] Curiefense under 'How it Works See It in Action' section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4884]
### Current Behavior
Currently, [every integration](https://layer5.io/cloud-native-management/meshery/integrations/curiefense) has only two old screenshots of the designer and visualizer in the 'How it Works See It in Action' section.

### Desired Behavior
- Add new images and videos from the latest version of the software ([MeshMap](https://layer5.io/cloud-native-management/meshmap))
- Add screenshots for [Curiefense](https://layer5.io/cloud-native-management/meshery/integrations/curiefense) integration.

### Acceptance Tests
- Ensure your screenshot represents the use of a few specific integrations.
- The screenshot from the Designer mode should contain a valid design, refer to [meshery catalog](https://meshery.io/catalog) to use and view published designs.
- Add both Dark Mode and Light Mode screenshots.
- The screenshot should not be a snippet, take the full screenshot of your browser.
- Use Incognito mode on Chrome browser, to ensure your bookmark bar or any other items are not shown in the screenshot/video.

---

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by PRANJALRANA11** [comment]
please assign this issue to me

**Comment by abhijeetgauravm** [comment]
there u go @PRANJALRANA11

**Comment by thakuraman24** [comment]
@saurabh100ni this seems to be unassigned can you assigned this to me

**Comment by abhijeetgauravm** [comment]
there u go @thakuraman24

**Comment by thakuraman24** [comment]
I tried my best but wasn't able to do what was asked of in the issue so I am unassigning myself from this issue. It was a great experience for me to work on my first issue, although I was not able to complete it I learned a lot and got to say that the Layers5 community is very supportive. I will surely try to make some contributions in the future when I have gained some more knowledge of cloud-native development.

**Comment by abhijeetgauravm** [comment]
No sweat @thakuraman24 You are always welcome to contribute on the other open issues and learn while contributing. Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned anytime. And also feel free to post your doubts on [discuss.layer5.io](http://discuss.layer5.io/) and our [slack](https://slack.layer5.io/) channels if you got anytime.

**Comment by balagowda** [comment]
Is Anyone working on this issue? if not can i take this!

**Comment by saurabh100ni** [comment]
Go On @balagowda 😎🚀

**Comment by balagowda** [comment]
do i need to sign up for meshery beta program to update the ss ??

**Comment by abhijeetgauravm** [comment]
> do i need to sign up for meshery beta program to update the ss ??

Yeah @balagowda you need to sign up for Meshmap beta program.

**Comment by balagowda** [comment]
is this ss are ok??
<img width="1440" alt="Screenshot 2023-11-06 at 1 46 27 PM" src="https://github.com/layer5io/layer5/assets/111847375/4d9b70ed-7f32-46fa-a4ae-9e7a4f15b683">
<img width="1440" alt="Screenshot 2023-11-06 at 1 47 22 PM" src="https://github.com/layer5io/layer5/assets/111847375/e3a5590b-f390-4746-a8cd-610e632a4e10">
<img width="1440" alt="Screenshot 2023-11-06 at 2 09 53 PM" src="https://github.com/layer5io/layer5/assets/111847375/5ec339f5-f247-4422-b879-7e3e215ba375">
<img width="1440" alt="Screenshot 2023-11-06 at 2 11 14 PM" src="https://github.com/layer5io/layer5/assets/111847375/620189d6-cdcc-494f-b84c-526a365ab7bd">

**Comment by saurabh100ni** [comment]
@Yashsharma1911 @sudhanshutech @Mohith234 //

**Comment by 7arj** [comment]
i want to work on this issue @narasimha-1511

**Comment by narasimha-1511** [comment]
Go on @7arj 🚀
