### ISSUE TITLE
Create project card and page for "Image Hub"

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#489]
Image hub needs to be represented as a project on the [Layer5 site](https://layer5.io/projects). Currently, it is only mentioned in the [README](https://github.com/layer5io/layer5#image-hub).

**Tasks**

- [ ] A new [project page](https://layer5.io/projects) should be added, with a description of the Image hub project and its logo.
- [ ] A project card should also be added here - https://layer5.io/projects

**Resources**

-  Find the Image hub repo here - https://github.com/layer5io/image-hub

**Comment by leecalcote** [comment]
I wonder... does @chandrashritii ever sleep? 😉

**Comment by Jashpatel1** [comment]
@chandrashritii  Yaa sure.

**Comment by kushthedude** [comment]
Hey @chandrashritii , Do we really need this, as Image Hub is a sample application for consul (soon to be for other adapters)? I think we should just represent our signature project on the project page, one of which could be Learn-Layer5 once completed.

**Comment by chandrashritii** [comment]
> 
> 
> Hey @chandrashritii , Do we really need this, as Image Hub is a sample application for consul (soon to be for other adapters)? I think we should just represent our signature project on the project page, one of which could be Learn-Layer5 once completed.

@kushthedude The basic plan is to have a project page for both, Image hub and Learn-Layer5 in time and then migrating them to the layer5-ng site. Perhaps @leecalcote can explain this better.
