### ISSUE TITLE
k8s-icon-taking-extra-width

### ISSUE THREAD

**Issue by PRANJALRANA11** [layer5io/layer5#4890]
### Description
When you click on the k8s icon on the top right corner of the meshery playground then it is taking extra width which results in the bottom slider to display

### Expected Behavior
it shouldn't take the extra width on clicking 

### Screenshots
without clicking
![image](https://github.com/layer5io/layer5/assets/129268721/98cc6dd3-d729-4c13-b247-1b35219c0c28)

with clicking
![image](https://github.com/layer5io/layer5/assets/129268721/374c944b-3ab4-43fd-8621-bd288aeb27d1)

### Environment:
-Chrome  Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Akhilbisht798** [comment]
Hey, Can i work on this issue

**Comment by harshit-paneri** [comment]
Hey, can you assign me to this issue?

**Comment by dassudip2001** [comment]
is this issue fixed

**Comment by coder12git** [comment]
Hey, I want to work on this issue. Please assign to me

**Comment by PRANJALRANA11** [comment]
@abhijeetgauravm could you assign this issue

**Comment by Mohith234** [comment]
I'm closing this issue as it is not related to this repository.  

// @PRANJALRANA11
