### ISSUE TITLE
Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [layer5io/layer5#4891]
### Description
Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### Expected Behavior
Twitter logo should be changed to X

### Screenshots

<img width="960" alt="Screenshot 2023-09-08 101412" src="https://github.com/layer5io/layer5/assets/91591901/50559355-d69d-4298-b13c-3041e2a38882">

### Environment:
- Host OS: Windows
- Browser: chrome

@Ghat0tkach 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by abhijeetgauravm** [comment]
hey @lalitkumawat1m there is already an open issue related to it! #4631 . U can review the PR and can collaborate with the assignee in completing the mentioned issue!

**Comment by lalitkumawat1m** [comment]
Thanks for conforming

**Comment by lalitkumawat1m** [comment]
Thanks for conforming

**Comment by abhijeetgauravm** [comment]
@lalitkumawat1m, if you would like to work on this, you can review the PR for the mentioned issue and collaborate with the assignee to resolve it.
