### ISSUE TITLE
 Add Mention of Badges Site to Layer5.io Pages

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4892]
### Current Behavior

Layer5 recently announced an enhancement to the ways in which it recognizes milestones achieved by contributors and users. (see community handbook) with an improved badge award system --> https://badges.layer5.io/.
### Desired Situation

A short and crisp description of the badges site need to be added on the following pages

- [ ]  [community/newcomers](https://layer5.io/community/newcomers)

- [ ]  [community/members](https://layer5.io/community/members)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Ideally, this issue includes the creation of a small mockup for a badge recognition section on the two pages mentioned (or one of them). 

// @gopivaibhav

**Comment by PRANJALRANA11** [comment]
I will solve this issue

**Comment by shubhankar-mern** [comment]
is this still open..if it is..please assign it to me

**Comment by vj-codes** [comment]
@saurabh100ni hey I would like to work on this

**Comment by saurabh100ni** [comment]
Go On @vj-codes 😎🚀

**Comment by saurabh100ni** [comment]
@shubhankar-mern I'm sure you can have more issues to work on, Let's get this one to @vj-codes.

**Comment by abhijeetgauravm** [comment]
@vj-codes @shubhankar-mern There is already a PR open for it. You can also review the PR and let it move forward!

**Comment by eleensmathew** [comment]
Can i work on this?

**Comment by narasimha-1511** [comment]
I would like to contribute ? i did not understand the issue completly..

**Comment by saurabh100ni** [comment]
@eleensmathew, are you still up to contribute on this issue? If not. then let's get this issue assigned to @narasimha-1511.

**Comment by eleensmathew** [comment]
Im actually a bit busy right now, feel free to assign it to someone else.

**Comment by narasimha-1511** [comment]
can i do it now @saurabh100ni ?

**Comment by saurabh100ni** [comment]
Thanks for sending the  word @eleensmathew , affirmative @narasimha-1511 .

**Comment by narasimha-1511** [comment]
is it necessary to add badges in both the pages ? 
@saurabh100ni . i have added in members currently.

**Comment by saurabh100ni** [comment]
@narasimha-1511, [here is your answer](https://github.com/layer5io/layer5/issues/4892#issuecomment-1712205348)
