### ISSUE TITLE
Please fill out this form to provide insights for our upcoming design system.

### ISSUE THREAD

**Issue by Rexford74** [layer5io/layer5#4897]
**Current Behavior**

[This preliminary form,](https://forms.gle/GZ6rJLqg8CPD66rx6) created to get insights that will help us group users for further research in a bid to get sufficient data for our upcoming Design System has been given little to no attention so far.

**Desired Behavior**

[Please fill out this form](https://forms.gle/GZ6rJLqg8CPD66rx6) so that we can begin data collection and progress rapidly to creating all the required elements for a fully functional Design System to be used here at Layer5.
**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by nwanduka** [comment]
Done

**Comment by ManishKapoor5** [comment]
Done

**Comment by Narottamchy** [comment]
done

**Comment by ManishKapoor5** [comment]
Done

**Comment by pragyamishra56** [comment]
would be possible to assign me?

**Comment by sumisahu** [comment]
Done

**Comment by Ahsankhalid618** [comment]
Done

**Comment by sumisahu** [comment]
Done

**Comment by arunkarthicknm** [comment]
Done :)

**Comment by sumisahu** [comment]
Awesome, thank you so much!
