### ISSUE TITLE
[Grammar Adjustment] Learn - content next to the "Get Early Access" form

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#4907]
**Current State:**

- Link to website: https://play.meshery.io/
- Currently, the text reads as follows: "Sign-up to receive a user account, entitled with perpetually free and full access the Playground environment."

**Desired State:**

- The suggested change is to add the word _to_ so it reads: "Sign-up to receive a user account, entitled with perpetually free and full access to the Playground environment."

---
**Screenshot**
![mesh](https://github.com/layer5io/layer5/assets/19821445/8619c001-0175-46d2-af9f-b472a55a56f6)

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue

**Comment by shiivamtaneja** [comment]
Hi could you assign this issue to me

**Comment by Mohith234** [comment]
@VivekBaldha0712 Go ahead

**Comment by VivekBaldha0712** [comment]
This issue is raised in wrong repo. It should be on meshery @Mohith234

**Comment by sandramsc** [comment]
> This issue is raised in the wrong repo. It should be on meshery @Mohith234

Thank you for pointing this out, I've gone ahead and replicated the issue in the appropriate repo.
@VivekBaldha0712 Consider requesting re-assignment in that repo.
@Mohith234 As I contributor, I probably don't have the authority to close an issue, could you do this in the meantime?

**Comment by Mohith234** [comment]
Thank you @sandramsc and @VivekBaldha0712 for pointing this out.
