### ISSUE TITLE
[Grammar Adjustment] Learn - Frequently Asked Questions

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#4908]
**Current State:**

- Link to website: https://play.meshery.io/#signup-form
- Currently, the text in the 5th question reads as follows: "Are designs that I create in the Meshery Playground saved or will I look any work that I do in the playground?"

**Desired State:**

- The suggested change is to adjust the text so it reads: "Are designs that I create in the Meshery Playground saved or will I lose any work that I do in the playground?"

---
**Screenshot**

![mesh](https://github.com/layer5io/layer5/assets/19821445/3ab08b2b-85e7-4993-9f62-00a7812a19df)

**Comment by PRANJALRANA11** [comment]
could you assign this issue to me

**Comment by abhijeetgauravm** [comment]
there u go @PRANJALRANA11

**Comment by harshit-paneri** [comment]
May I work on it.

**Comment by sandramsc** [comment]
> This issue is raised in the wrong repo. It should be on meshery, I've gone ahead and replicated the issue in the appropriate repo.
@PRANJALRANA11 Consider requesting re-assignment in that repo.
@abhijeetgauravm  As I contributor, I probably don't have the authority to close an issue, could you do this in the meantime?

**Comment by abhijeetgauravm** [comment]
> > This issue is raised in the wrong repo. It should be on meshery, I've gone ahead and replicated the issue in the appropriate repo.
> > @PRANJALRANA11 Consider requesting re-assignment in that repo.
> > @abhijeetgauravm  As I contributor, I probably don't have the authority to close an issue, could you do this in the meantime?

yeah @sandramsc
