### ISSUE TITLE
Low Text contrast in dark mode for learning paths

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/layer5#4909]
### Description

Currently , the text is a bit lighter in dark mode of [learning paths](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started) which create a visiblity issue.
The istio logo is surrounded by border box.We need to remove it  as well. 
![image](https://github.com/layer5io/layer5/assets/59855919/5994e2db-e303-4548-9d74-8ce3b836a3a3)

### Expected Behavior

All the labs of the learning path should have better visibility 

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Shiv-2712** [comment]
Hello, I'm interested in working on this matter. Please assign it to me.

**Comment by harshit-paneri** [comment]
Hello, I can work on it.

**Comment by Shiv-2712** [comment]
Hello, could you please verify this? Is it satisfactory as it is, or should I make adjustments?

![image](https://github.com/layer5io/layer5/assets/74370135/021a3596-5a3a-40a9-884d-cc6e7960c0e9)

**Comment by abhijeetgauravm** [comment]
> Hello, could you please verify this? Is it satisfactory as it is, or should I make adjustments?
> 
> ![image](https://user-images.githubusercontent.com/74370135/268069637-021a3596-5a3a-40a9-884d-cc6e7960c0e9.png)

Looks good to me // @Ghat0tkach thoughts?

**Comment by Narottamchy** [comment]
can i work on this issue, please?

**Comment by AnshulGoyal589** [comment]
I would like to work on this issue, kindly assign it io me.

**Comment by nick2432** [comment]
can i work on this?

**Comment by Rohan-webd** [comment]
Hey , I would like to work on this, Please assign me this issue, Thanks.

**Comment by Shiv-2712** [comment]
I've created PR #4922, but it hasn't been approved yet.

**Comment by INFIZEUS** [comment]
Hey, Can I work on this issue. This will be my First ever contribution.

**Comment by Akshatverma01** [comment]
Hey can you please assign this issue to me
