### ISSUE TITLE
[UX - Responsiveness] Learn - text alignment not consistent 

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#4911]
### Current Behaviour

- Link to website: https://play.meshery.io/
- The paragraph text under "The Cloud Native Playground" is center aligned
- However the text under "Sign-up to receive a user account..." is left aligned, additionally, the subheading under "Frequently Asked Questions" is also left aligned.

#### Screenshots

![su](https://github.com/layer5io/layer5/assets/19821445/4f8b370b-0232-4b02-b8ae-5dc9e3cd1a30)
![fqa](https://github.com/layer5io/layer5/assets/19821445/4e957960-d23a-4c31-906f-1abfc9eb0153)

### Suggested Behaviour
- To maintain design consistency text should have the same format i.e either left aligned or center aligned.

#### Screenshots

![mp](https://github.com/layer5io/layer5/assets/19821445/70d23f48-746e-41f7-bc11-eb929ca8aacd)
![su](https://github.com/layer5io/layer5/assets/19821445/14b9406d-cf77-4ce0-9aef-3ee44783ceb4)

### Environment:
- Host OS: Mobile responsiveness
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by abhijeetgauravm** [comment]
there u go @anubhav1206

**Comment by anubhav1206** [comment]
Where exactly is the file that needs to be modified located?

**Comment by sandramsc** [comment]
> This issue is raised in the wrong repo. It should be on meshery, I've gone ahead and replicated the issue in the appropriate repo.
@anubhav1206  Consider requesting re-assignment in that repo ([meshery.io](https://github.com/meshery/meshery.io/issues/)).
@abhijeetgauravm  As a contributor, I probably don't have the authority to close an issue, could you do this in the meantime?

**Comment by abhijeetgauravm** [comment]
> > This issue is raised in the wrong repo. It should be on meshery, I've gone ahead and replicated the issue in the appropriate repo.
> > @anubhav1206  Consider requesting re-assignment in that repo ([meshery.io](https://github.com/meshery/meshery.io/issues/)).
> > @abhijeetgauravm  As a contributor, I probably don't have the authority to close an issue, could you do this in the meantime?

yup @sandramsc

**Comment by anubhav1206** [comment]
> > This issue is raised in the wrong repo. It should be on meshery, I've gone ahead and replicated the issue in the appropriate repo.
> > @anubhav1206  Consider requesting re-assignment in that repo ([meshery.io](https://github.com/meshery/meshery.io/issues/)).
> > @abhijeetgauravm  As a contributor, I probably don't have the authority to close an issue, could you do this in the meantime?

Sure, thanks!
