### ISSUE TITLE
[Community] Line height issue in Five and Friends CTA

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4915]
### Description
This new Call to Action (CTA) is displayed on one or more pages, including the [community page](https://layer5.io/community). It is in need of some fine-tuning. 

<img width="451" alt="Screenshot 2023-09-15 at 11 31 01 AM" src="https://github.com/layer5io/layer5/assets/7570704/ce2c8177-84f3-4abb-87d0-4cc04ac65e3b">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VamshiReddy02** [comment]
I want to work on this issue.

**Comment by hirentimbadiya** [comment]
@VamshiReddy02 , you can work on this issue.
