### ISSUE TITLE
[Blog] Add Five and Friends CTA to column of widgets.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4916]
### Current Behavior
The blog page has a column of widgets, including a Call to Action (CTA) for visiting the discussion forum.

### Desired Behavior
The relatively new "Five and Friends" CTA can be added to the blog page as another widget.

### Screenshots / Mockups
![Blog section](https://github.com/layer5io/layer5/assets/7570704/4efb7f98-7818-4ec3-872d-29b818d33e94)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by toth2000** [comment]
I will look into this
