### ISSUE TITLE
[UX] Learn - full text for "sign into" call to action not visible in light mode

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#4919]
### Current Behavior

- Link to website: https://layer5.io/learn/service-mesh-labs
- [Light mode] Currently when each learning path is opened by clicking on "Open Scenario", it reveals the text "Meshery Playground" as text in green color, which does not give much context to the user as to what options/steps they have to navigate the platform further. This only becomes clear if a user hovers over the already opened path revealing the full action option which states "Sign in to the Meshery Playground (free account) to continue your lab."

#### Screenshots
![lmode](https://github.com/layer5io/layer5/assets/19821445/cb9d913d-8e77-49c6-bc3c-c92405729875)

### Desired Behavior

Users should be able to see the option to navigate the platform further (before and after hovering over the path), this enhances user experience as not every user might have the notion to "hover" over an item to reveal the most important call to action/option which is signing up for a free Meshery Playground account to **continue their lab**.

### Screenshots

![dmode](https://github.com/layer5io/layer5/assets/19821445/f123deb5-2ca8-48c3-a2c4-73a857cd4ab6)

### Implementation

- [Light mode] Consider changing the text color for "Sign in to the Meshery Playground (free account) to continue your lab." to one that is different from its background, so its visible, before hover.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VamshiReddy02** [comment]
can I work on this issue?

**Comment by abhijeetgauravm** [comment]
Thanks @sandramsc . There u go @VamshiReddy02 !

**Comment by umerinsaan** [comment]
is there any guide, I want to setup this project on my local machine

**Comment by abhijeetgauravm** [comment]
> is there any guide, I want to setup this project on my local machine

hey @umerinsaan Please Check out  https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md for setting up your Local Development Environment.
