### ISSUE TITLE
[BUG]: the CHECK box goes out of DESIRE area

### ISSUE THREAD

**Issue by Sushilverma002** [layer5io/layer5#4927]
### Description
the content as check box goes out of desire area  so it make odd in the website.
have a look once :- https://layer5.io/cloud-native-management/meshmap
### Expected Behavior
the check box should be inside the box area.
### Screenshots
![image](https://github.com/layer5io/layer5/assets/114687502/b88dc445-0f3f-49eb-901e-e1af3ed034a8)
### Environment:
- Host OS:windows
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Mohith234** [comment]
@Sushilverma002 Could you send the full browser screenshot, At which breakpoint you are seeing this issue?

**Comment by Sushilverma002** [comment]
![image](https://github.com/layer5io/layer5/assets/114687502/38f08724-a128-4ccc-a798-9be420fe0b62)

**Comment by Sushilverma002** [comment]
@Mohith234 have a look!!!!!!!!!

**Comment by Mohith234** [comment]
@Sushilverma002 I couldn't replicate the same. I found out that the extension you are using causes it 

Try pausing the extension ( Blackbox AI )

**Comment by Sushilverma002** [comment]
ohh got it sorry for inconvenience. wait i'll close this issue.
