### ISSUE TITLE
[Community] Newcomers: Update mascot image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4929]
### Current Behavior
The [Newcomers page](https://layer5.io/community/newcomers) has an old version of Five, our stick figure mascot.

<img width="1340" alt="Screenshot 2023-09-17 at 8 41 39 PM" src="https://github.com/layer5io/layer5/assets/7570704/2ca04795-04b3-41ec-ade8-a4d141c2bcad">

### Desired Situation
Replace the old version with one of the available new versions of Five. Select from those available under https://layer5.io/brand

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by akhilender-bongirwar** [comment]
@leecalcote, I would like to work upon this issue. Please assign me : )

**Comment by PRANJALRANA11** [comment]
please assign issue to me

**Comment by abhijeetgauravm** [comment]
Assigning in chronological order. There u go @akhilender-bongirwar

**Comment by rcypankaj** [comment]
Hlo Dear, Can you assign it to me It is my First contibution.

**Comment by abhijeetgauravm** [comment]
> Hlo Dear, Can you assign it to me It is my First contibution.

hey @rcypankaj we have a bunch of good first issues open , you are most welcome to contribute!
