### ISSUE TITLE
[UX] Learn - full text for "sign into" call to action not visible in light mode

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#4931]
### Current Behavior

- Link to website: 
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-istio
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-linkerd
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-consul
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-kuma
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-nsm
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-traefik
https://layer5.io/learn/service-mesh-labs/working-with-meshery-and-open-service-mesh
https://layer5.io/learn/service-mesh-labs/running-performance-tests
https://layer5.io/learn/service-mesh-labs/traffic-splitting-with-meshery

- [Light mode] Currently when each learning path is opened by clicking on the **arrow in the top right corner**, it reveals the text "Meshery Playground" as text in green color, which does not give much context to the user as to what options/steps they have to navigate the platform further. This only becomes clear if a user turns on dark mode revealing the full action option which states "Sign in to the Meshery Playground (free account) to continue your lab."

#### Screenshots
![imageedit_9_6992306970](https://github.com/layer5io/layer5/assets/19821445/ee6f799f-7871-4db2-aa03-aa9ccf1893ca)

![mesh](https://github.com/layer5io/layer5/assets/19821445/d00c24cc-53bd-4a1f-a014-59f51ccb3a4c)

### Desired Behavior

Users should be able to see the option to navigate the platform further (before and after color mode is enabled), this enhances user experience as not every user might have the notion to turn on dark mode to reveal the most important call to action/option which is signing up for a free Meshery Playground account to **continue their lab**.

### Screenshots

![dmesh](https://github.com/layer5io/layer5/assets/19821445/b937263e-a13c-49d8-a85a-c4989dddacd0)

### Implementation

- [Light mode] Consider changing the text color for "Sign in to the Meshery Playground (free account) to continue your lab." to one that is different from its background, so it's visible, in light mode.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VamshiReddy02** [comment]
I can fix all that, please assign it to me.

**Comment by abhijeetgauravm** [comment]
There u go @VamshiReddy02

**Comment by smsh2205** [comment]
I'd like to work on this issue. Could you please assign it to me?
