### ISSUE TITLE
[Documentation] update the CONTRIBUTING.md with Issues & Pull Requests sections

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#4932]
### Current Behavior

The contributing guide is a great way to introduce new and existing contributors on how to add their contributions to the projects within an organization. Currently, the CONTRIBUTING.md does not state that there is a first-come-first-serve procedure when it comes to assigning open issues. Although this is stated on the main website [here](https://layer5.io/community/newcomers) under the section,
"Finding an Issue to Work On", it will serve as a good reminder to have it within this file in the repo as well.

### Desired Situation

Add/update the following sections within the CONTRIBUTING.md of the [Layer5](https://github.com/layer5io/layer5) projects:
- Issues & Pull Requests --> i.e _Creating an Issue, Working on an issue (get it assigned to you)_
- Reviewing Pull Requests

### Checklist for projects
All the CONTRIBUTING.md's need to be updated using above mentioned desired state.

- [x] [ layer5](https://github.com/layer5io/layer5)
- [ ] [meshery](https://github.com/meshery/meshery/issues/8848) --> [repo](https://github.com/meshery/meshery)
- [ ] [meshery.io](https://github.com/meshery/meshery.io/issues/1428)  --> [repo](https://github.com/meshery/meshery.io)
- [ ] [play](https://github.com/meshery/play/issues/148) --> [repo](https://github.com/meshery/play)
- [ ] [meshkit](https://github.com/meshery/meshkit/issues/372) --> [repo](https://github.com/meshery/meshkit)

- [ ] [meshsync](https://github.com/meshery/meshsync/issues/246) --> [repo](https://github.com/meshery/meshsync)
- [ ] [meshmap](https://github.com/layer5labs/meshery-extensions-packages/issues/176)  --> [repo](https://github.com/layer5labs/meshery-extensions-packages)
- [ ] [getnighthawk](https://github.com/layer5io/getnighthawk/issues/338) --> [repo](https://github.com/layer5io/getnighthawk)
- [ ] [learn-layer5](https://github.com/layer5io/learn-layer5/issues/93) --> [repo](https://github.com/layer5io/learn-layer5) 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sandramsc** [comment]
Hi, I would like to work on this issue, can I have it assigned to me please?

**Comment by abhijeetgauravm** [comment]
Yeah @sandramsc
