### ISSUE TITLE
[Community] Member Profile: Abhijeet Gaurav

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4937]
**Current Behavior**

@abhijeetgauravm has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @abhijeetgauravm as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @abhijeetgauravm
- Twitter: [@abhijeetgauravm](https://twitter.com/abhijeetgauravm)
- LinkedIn: [abhijeet-gaurav-971b01a4](abhijeet-gaurav-971b01a4)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue. Please assign this task to me.

**Comment by saurabh100ni** [comment]
@abhijeetgauravm 
can you comment on your following?
Meshery Cloud:
Link to profile picture:

**Comment by saurabh100ni** [comment]
you got it @VivekBaldha0712 🙂

**Comment by abhijeetgauravm** [comment]
> Meshery Cloud:
> Link to profile picture:

Linkedin: https://www.linkedin.com/in/abhijeet-gaurav-971b01a4/
Meshery Cloud: https://meshery.layer5.io/user/c9432f12-f9d2-4c99-8704-8b750e42c023
Link to profile picture: https://drive.google.com/file/d/14CO578U0-J8dLAf-ZDImp12JPCD2zJcD/view?usp=drive_link

**Comment by VivekBaldha0712** [comment]
hey @abhijeetgauravm , Will you please provide your bio for profile

**Comment by abhijeetgauravm** [comment]
> hey @abhijeetgauravm , Will you please provide your bio for profile

Yeah Sure @VivekBaldha0712 

Hello! I'm Abhijeet, a tech enthusiast on a journey of discovery. I'm constantly exploring the ever-evolving landscape of DevOps, Open Source and Web Development. I'm eager to contribute my energy and fresh perspectives to the field. I firmly believe that learning is a lifelong adventure, and I'm here to soak up knowledge like a sponge. Let's connect, share ideas, and embark on this exciting journey of growth and discovery together! 🚀🌍
