### ISSUE TITLE
[Community] Member Profile: Shravani Kaware

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4938]
**Current Behavior**

@ShravaniAK has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @ShravaniAK as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @ShravaniAK
- Twitter: [@ShravaniKaware](https://twitter.com/ShravaniKaware)
- LinkedIn: [in/shravani-kaware-b3620022a](https://www.linkedin.com/in/shravani-kaware-b3620022a/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by malaviya-parth** [comment]
Glad if I get to work on this

**Comment by saurabh100ni** [comment]
you got it @malaviya-parth 😎🚀

**Comment by ShravaniAK** [comment]
Here are the links,

Meshery Cloud: https://meshery.layer5.io/user/482be9ac-d29b-4912-9013-e6a7f2c02e8a
Link to profile picture: https://drive.google.com/file/d/1QZm24r9t-OxG4z5rFILLUQ_fG0oaJgWS/view?usp=sharing

**Comment by malaviya-parth** [comment]
Hey @ShravaniAK, can you please provide your bio to be added in the profile.

**Comment by ShravaniAK** [comment]
bio: hello!
I am Shravani kaware, currently pursuing my bachelor in technology at the India Institute of information technology Vadodara. I am a tech enthusiast and love to learn and explore different areas of technology. I am a Mern stack developer. I am passionate about driving innovation in the tech world! As a dedicated woman in technology, I thrive on turning complex challenges into impactful solutions.
