### ISSUE TITLE
[Community] Member Profile: Rhoda Michael

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#4942]
**Current Behavior**

@the-techgurl has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @the-techgurl as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @the-techgurl
- Twitter: 
- LinkedIn: 
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by saurabh100ni** [comment]
@the-techgurl can you comment following details of yours:
- Twitter:
- LinkedIn:
- Meshery Cloud:
- Link to profile picture:
- bio

**Comment by VivekBaldha0712** [comment]
I would like to work. Can you please assign this to me

**Comment by saurabh100ni** [comment]
sure @VivekBaldha0712 you got it 😎🚀

**Comment by the-techgurl** [comment]
Sure @saurabh100ni 

- [Twitter](https://twitter.com/_RhodaMichael)

- [LinkedIn](https://www.linkedin.com/in/rhodamichael/)

- [Meshery Cloud](https://meshery.layer5.io/user/b93a7eef-01f1-4ab0-b129-690b28b6a6d7)

- [Link to profile picture](https://drive.google.com/file/d/13F6fCCur_ED1Krih_iveksevaH-iw3lI/view?usp=sharing)

- Bio: I'm Rhoda Michael, a User Experience Designer/Researcher based in Nigeria I focus on accessibility and inclusion for users. I enjoy writing and reading.
