### ISSUE TITLE
Frequently Asked Questions font is very small in mobile view

### ISSUE THREAD

**Issue by dhamkirti21** [layer5io/layer5#4946]
### Current Behavior

The Frequently Asked Questions in Pricing Section of Layer5 Website has very small font size for the questions in mobile view
![image](https://github.com/layer5io/layer5/assets/78336507/e296343d-4bc9-49c2-b6c6-a91f4e1112c1)

### Desired Situation

it must be little more than the present size of the font so that it should be more readable.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by dhamkirti21** [comment]
@pateldivyesh1323  you may work on it

**Comment by harshit-senpai** [comment]
hey, in the Assigned section, it does not show assigned to anyone so I would like to work on it. if it's not already assigned.

**Comment by Narottamchy** [comment]
hey can i work on this issue
