### ISSUE TITLE
[Documentation] Link hyperlinks to URL querystrings  and get the specific section location (#anchor) in your clipboard

### ISSUE THREAD

**Issue by goldfishdolphin** [layer5io/layer5#4947]
### Description

When you click on a hyperlink that is linked to an anchor, such as a heading, the anchor isn't included in the URL querystring. Consequently, when you attempt to share a specific section of a page by clicking the anchor, then copying the URL from your browser's address bar, the clipboard doesn't capture the specific section location represented by the anchor (#anchor).

https://docs.meshery.io/reference/error-codes

### Expected Behavior

The expected outcome for the error code reference page is to have each error code readily hyperlinked and accessible from different locations, including the Notification Center within the Meshery UI.
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Good! 

Consider reopening this issue under `meshery/meshery`, if you would. Also, you're at leisure to self-assign, if appropriate.
