### ISSUE TITLE
[Documentation] : Missing detailed information for some error codes 

### ISSUE THREAD

**Issue by goldfishdolphin** [layer5io/layer5#4948]
### Description

Currently, there is some information (Probable Cause, Suggested Remediation and Long Description)  missing for some error codes like ErrClientConfigCode-1008, ErrClientConfigCode-1009 etc...

https://docs.meshery.io/reference/error-codes

### Expected Behavior

The error code reference should give detailed information about individual errors and how to resolve them.

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Good, good. This issue can make its way on over to https://github.com/meshery/meshery. It's encouraging to see new life being breathed into this user-critical area.
