### ISSUE TITLE
Formating in meshery filters catlog is not right 

### ISSUE THREAD

**Issue by dhamkirti21** [layer5io/layer5#4951]

**Comment by shiivamtaneja** [comment]
Hey can i work on this?

**Comment by shiivamtaneja** [comment]
Also i think this issue is raised in the wrong repo. It should be on meshery, @abhijeetgauravm can you please confirm?

**Comment by abhijeetgauravm** [comment]
> Also i think this issue is raised in the wrong repo. It should be on meshery, @abhijeetgauravm @Mohith234 could you please confirm?

Yeah, It is a part of [meshery.io](https://meshery.io/) site, So this issue is raised in the wrong repo.

// @shiivamtaneja @dhamkirti21

**Comment by shiivamtaneja** [comment]
If it is raised in the meshery repo, then i would like to work on this
