### ISSUE TITLE
Link color in meshery byteVerse blogs is little odd for light mode 

### ISSUE THREAD

**Issue by dhamkirti21** [layer5io/layer5#4952]

**Comment by shiivamtaneja** [comment]
I think this issue is raised in the wrong repo. It should be on meshery, @abhijeetgauravm could you please confirm?

**Comment by Mohith234** [comment]
Yep, It is a part of [meshery.io](https://meshery.io/) site, So this issue is raised in the wrong repo.

// @shiivamtaneja @dhamkirti21
