### ISSUE TITLE
Need to add **book demo** to Layer5.io

### ISSUE THREAD

**Issue by Modern-artist** [layer5io/layer5#4956]
### Description
There are a number of people that book demos so we do need it exposed in [layer5.io](http://layer5.io/), like on the /meshmap page as an example.

### Expected Behavior
We need to add **book demo** to [layer5.io](http://layer5.io/)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shishiro26** [comment]
I would like to work on this

**Comment by abhijeetgauravm** [comment]
there u go @shishiro26

**Comment by shishiro26** [comment]
Hi @Modern-artist @abhijeetgauravm ,

I'm new to open source and I'm interested in helping to add a "book demo" button to Layer5.io. I'm not sure where to start, so I'm looking for some guidance.

Here are some questions I have:

What are the technical specifications for the button? For example, what size and color should it be? Where should it be placed on the page?
What are the steps involved in adding the button to Layer5.io?
Are there any specific tools or resources that I will need?

**Comment by abhijeetgauravm** [comment]
hey @shishiro26 Have you set up your local development environment?

**Comment by shishiro26** [comment]
yes, I have set up the local development environment

**Comment by abhijeetgauravm** [comment]
> Hi @Modern-artist @abhijeetgauravm ,
> 
> I'm new to open source and I'm interested in helping to add a "book demo" button to Layer5.io. I'm not sure where to start, so I'm looking for some guidance.
> 
> Here are some questions I have:
> 
> What are the technical specifications for the button? For example, what size and color should it be? Where should it be placed on the page? What are the steps involved in adding the button to Layer5.io? Are there any specific tools or resources that I will need?

// @Modern-artist

**Comment by Modern-artist** [comment]
What are the technical specifications for the button?
->You don't have to create any new button components.

For example, what size and colour should it be? 
-> @ritiksaxena124 will guide you with this.

Where should it be placed on the page?
-> That is the issue. Brainstorm it and DM the solution to me in Slack.

What are the steps involved in adding the button to Layer5.io?
->NO, you don't have to add any button component.

Are there any specific tools or resources that I will need?
->Probably Figma will help you.

**Comment by abhijeetgauravm** [comment]
hey @shishiro26 Please make sure you join our [Slack channel](https://layer5io.slack.com/ssb/redirect) too(if not) where you can ask your queries whenever you get stuck in any problem.

**Comment by HarshDeep61034** [comment]
I would like to work on this, as no one is assigned!

**Comment by iArchitSharma** [comment]
@ritiksaxena124 do we still need this?
