### ISSUE TITLE
[Handbook] Repository Overview: Add Sistent project to the table

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4959]
### Current Behavior
This page offers a very brief overview of repos by tech - https://layer5.io/community/handbook/repository-overview. It is missing the Sistent Design System project.

### Desired Situation
List the [Sistent](https://giithub.com/layer5io/sistent) Design System project in one of the tables.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by akhilender-bongirwar** [comment]
Hey @leecalcote, I would like to work on this issue.

**Comment by coder12git** [comment]
Hey @leecalcote , I would like to work on this issue.

**Comment by leecalcote** [comment]
@akhilender-bongirwar do you mind if we let @coder12git take a crack at this one?

**Comment by coder12git** [comment]
Thanks @leecalcote

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar do you mind if we let @coder12git take a crack at this one?

Of course, I don't foresee any issues with that @leecalcote
