### ISSUE TITLE
[typo] Newcomers Form

### ISSUE THREAD

**Issue by shashank-kavli** [layer5io/layer5#4969]
### Description

I was filling the newcomers form at https://layer5.io/newcomers and found that it has a couple of grammatical errors.
### Expected Behavior

- it should be 'simply ask to be partnered' instead of 'simple ask to be partnered'
- it should be 'aspect of a project' instead of 'aspect a project'

### Screenshots
![Screenshot_2023-09-27_11-21-14](https://github.com/layer5io/layer5/assets/121170732/46ee5761-2bc8-4524-bc7f-06f1f930ca54)

I'd like to work on this issue

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VivekBaldha0712** [comment]
I would like to work on this issue

**Comment by Jat1nSood** [comment]
can you assign this to me. I have already fixed it.

**Comment by narasimha-1511** [comment]
can you assing me this i had fixed it

**Comment by Mohith234** [comment]
There is already an open PR so Instead of creating a new PR you can provide value by reviewing the existing PR @narasimha-1511 

Read the contributing guidelines [here](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by narasimha-1511** [comment]
@Jat1nSood  you need to sign the commit then your PR will be accepted
you need to commit like this .. (git commit -s -m "<Your message here>")

**Comment by narasimha-1511** [comment]
Other wise use Rebase to again to go bachk and again sign it
