### ISSUE TITLE
Add hyperlink of FAQ to required table of repository-overview page

### ISSUE THREAD

**Issue by Jat1nSood** [layer5io/layer5#4981]
### Current Behavior
Currently there are some repos which are not accessible to everyone. This creates confusion for newcomer.
### Desired Behavior
It should explain why it is not accessible to everyone.
### Screenshots / Mockups
<img width="1273" alt="image" src="https://github.com/layer5io/layer5/assets/117588226/56a20ed0-809d-4904-a45f-ad6d19987fc2">
### Implementation
We can add hyperlink to that section which will lead to FAQ page where we can answer to the quiestion
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Jat1nSood** [comment]
I would like to work on this issue

**Comment by narasimha-1511** [comment]
I would like to work on this issue please assign me this

**Comment by VamshiReddy02** [comment]
can I work on this issue?

**Comment by Narottamchy** [comment]
can i work on this issue, please?

**Comment by Jat1nSood** [comment]
@saurabh100ni Please review this issue

**Comment by saurabh100ni** [comment]
@ritiksaxena124 @Rajdip019 //

**Comment by Jat1nSood** [comment]
Hi @vishalvivekm @leecalcote , Please review this PR.

**Comment by leecalcote** [comment]
> Hi @vishalvivekm @leecalcote , Please review this PR.

@sandramsc is a trusted reviewer in this regard.
