### ISSUE TITLE
[UI] No Hover Effect on Cards

### ISSUE THREAD

**Issue by Akshun-01** [layer5io/layer5#4986]
### Description

These cards don't have the commonly used glowing hover effect on the rest of the site, which makes it look inconsistent.
Page link: https://layer5.io/learn/learning-paths

![image](https://github.com/layer5io/layer5/assets/93793691/984f806f-a496-4d9d-b282-db3255f17bbd)

### Expected Behavior

We can add a border glow effect on hover to these cards as well, to make the design look uniform and even. 
![image](https://github.com/layer5io/layer5/assets/93793691/62b25130-f4b7-4dcd-b01a-acd2b388c641)

### Environment:
- Host OS: Windows
- Browser: Chrome 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Akshun-01** [comment]
I would be happy to work on this issue.

**Comment by shiivamtaneja** [comment]
Hey @Akshun-01 are you working on this?

**Comment by Akshun-01** [comment]
Just analyzed it yet, waiting for the maintainer to review and assign it so I can move forward with it.

**Comment by vishalvivekm** [comment]
@Akshun-01 
Let's discuss this on Monday's website call. Please add it as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), If you would :) 
// @shiivamtaneja

**Comment by Aarav238** [comment]
Heyy I would like to work it, please assign this issue to me .

**Comment by Akshun-01** [comment]
Hey @Aarav238, sorry but I am already working on this one.

@vishalvivekm @ritiksaxena124 could you assign it, to avoid any future confusion, thanks.

**Comment by Akshun-01** [comment]
Hey, I have added the same style as other pages. Please review and tell me if some changes are required 


https://github.com/layer5io/layer5/assets/93793691/ccc53784-3ed9-40ac-abf6-212bbd668269
