### ISSUE TITLE
Duplicate 'Subscribe to Newsletter' on Blog Page

### ISSUE THREAD

**Issue by akhilender-bongirwar** [layer5io/layer5#4987]
### Description

There is an issue on the page: https://layer5.io/blog. When scrolling down to the bottom of the page, the problem described in the screenshot below is observed.

#### Steps to reproduce 
- Navigate to https://layer5.io/blog
- Scroll down to the bottom of the page
- The issue is depicted in the following screenshot:

### Screenshots
![Screenshot 2023-10-01 020746](https://github.com/layer5io/layer5/assets/112749383/8895df08-df4f-4956-9127-f9b3c9779985)

### Expected Behavior

There should either be a gap between the "Subscribe to Newsletter" section above and the footer, or the "Subscribe to Newsletter" section should be removed since there is already one at the bottom in the footer.

### Environment:
- Host OS: Windows
- Browser: Chrome, Brave,Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by akhilender-bongirwar** [comment]
If the above issue is valid, I would like to work on this under hacktoberfest2023.

**Comment by narasimha-1511** [comment]
I Would also like to work on this issue..

**Comment by vishalvivekm** [comment]
@akhilender-bongirwar 
Let's discuss this on Monday's website call. Please add it as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), If you would :)

**Comment by prakashAditya639** [comment]
Please assign me this issue under hacktoberfest

**Comment by PRATHAM1ST** [comment]
I would like to work on this issue, can u assign me at this ??

**Comment by prakashAditya639** [comment]
@akhilender-bongirwar Can you please review my pr

**Comment by akhilender-bongirwar** [comment]
@prakashAditya639, appreciate your enthusiasm to contribute but actually the team is still discussing what might be possible solution to this issue. We don't want to abruptly remove the subscribe button. We are still planning on alternatives to this. Please keep looking out for other open issues we have plenty of them. Yeah most of them will be assigned under the label: "Hacktoberfest".

**Comment by Shreyas0410** [comment]
Is it because of rendering of src/sections/subscribe/subscribe.js of this "Subscribe to news letter" as well as from the footer src/sections/General/Footer/index.js ? @vishalvivekm

**Comment by AbiodunVlad** [comment]
@akhilender-bongirwar I'll like to fix this issue. I see you haven't assigned it to anyone yet.
@vishalvivekm
