### ISSUE TITLE
Styling Inconsistency on Nighthawk Page: Cards Missing Green Layout and Hover Effect

### ISSUE THREAD

**Issue by akhilender-bongirwar** [layer5io/layer5#4988]
### Description
![Screenshot 2023-10-01 024015](https://github.com/layer5io/layer5/assets/112749383/33da7e23-ef7c-4dea-8f9c-8f43e7328018)

The screenshot above is from https://layer5.io/. As you can see, for every card, there is a green color layout that changes to white on hover.
However, when you navigate to the Nighthawk page, the cards don't have the above colors.

#### Steps to Reproduce
- Navigate to https://layer5.io/projects/nighthawk
- Scroll down to "Distributed Performance Management"
- You can see the screenshot below

![Screenshot 2023-10-01 024930](https://github.com/layer5io/layer5/assets/112749383/61c7a0e2-827b-4899-8d1e-ee24b43c766d)

### Expected Behavior

- The layout should be green in color, and on hover, it should change to white color.

### Environment:
- Host OS: Windows
- Browser: Chrome, Brave,Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue under hacktoberfest2023 : ).

**Comment by ojasaklechayt** [comment]
Hello, I would like to work on this issue under hacktoberfest 2023

**Comment by Jat1nSood** [comment]
> Hello, I would like to work on this issue under hacktoberfest 2023

HI @ojasaklechayt . friendly reminder please wait for issue to get assigned to you before creating a PR.

**Comment by akhilender-bongirwar** [comment]
Thank you, folks, for your enthusiasm to contribute to the issue. However, after today's website meeting, @leecalcote has suggested that this change is not required. We have various other issues, so please keep looking for opportunities to contribute.
