### ISSUE TITLE
Duplicate Meta descriptions

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#4996]
### Current Behavior

   The 2 pages have duplicate meta descriptions:
   - 1. https://layer5.io/learn/service-mesh-books/service-mesh-patterns
   - 2. https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership

Steps to check : Go to these pages, view the source-code ( CTRL+U) and search for `og:description`

### Desired Situation

The two pages should have different meta descriptions.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AbiodunVlad** [comment]
I want to work on this issue and write different meta descriptions for the pages.

**Comment by narasimha-1511** [comment]
i also want to work on this issue

**Comment by prakashAditya639** [comment]
@vishalvivekm Can you please assign me this issue under hacktoberfest topic

**Comment by ankushbhardwaj408** [comment]
Closed via- #5002
