### ISSUE TITLE
[Handbook] Repository Overview: Update Maintainer list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#4999]
### Current Behavior
Gaurav Chadha is no longer a maintainer.

### Desired Situation
One this page, https://layer5.io/community/handbook/repository-overview, remove "Gaurav Chadha" from the lists.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VivekBaldha0712** [comment]
I would like to work on this

**Comment by leecalcote** [comment]
Thanks, @VivekBaldha0712

**Comment by CrypticRevenger** [comment]
please assign me , I want  to do it,

**Comment by abhijeetgauravm** [comment]
Hey @CrypticRevenger, the PR for the issue is already up, but that shouldn't stop you from contributing 🦾. We do have a bunch of good first issues open, and you are most welcome to contribute!
