### ISSUE TITLE
[Grammar Adjustment] Community - Our Community Members

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5010]
**Current State:**

- Link to website: https://layer5.io/community
- Currently, the text in the paragraph under the Our **Community Members** section reads as follows: "...Every member is encourage to embrace these values and support one another in meaningfully and consistently advancing the community's open source initiatives."

**Desired State:**

- The suggested change is to adjust the text so it reads as: "Every member is encouraged to embrace these values and support one another in meaningfully and consistently advancing the community's open source initiatives."

---
**Screenshot**

![typo](https://github.com/layer5io/layer5/assets/19821445/363c49b5-de2f-4bd3-815c-2bc5ae5cadda)

**Comment by shishiro26** [comment]
I would like to 2o4k on this can u please assign these to me

**Comment by trinayreddy4** [comment]
@sandramsc please checkout the PR , I have Solved this issue. Hoping to hear it back from you.

**Comment by sandramsc** [comment]
@trinayreddy4  please familiarize yourself with the [Contributing guidelines](https://layer5.io/community/newcomers), particularly the section under "Finding an Issue to Work On": you need to request for an issue to be assigned to you first before opening PR (this reduces the risk of wasting your time and effort as a result of the issue being rightfully assigned to someone else), i.e only after it is assigned to you then open the PR.

**Comment by Debaditya-Som** [comment]
> @trinayreddy4 please familiarize yourself with the [Contributing guidelines](https://layer5.io/community/newcomers), particularly the section under "Finding an Issue to Work On": you need to request for an issue to be assigned to you first before opening PR (this reduces the risk of wasting your time and effort as a result of the issue being rightfully assigned to someone else), i.e only after it is assigned to you then open the PR.

@sandramsc if allowed, i would love to work on this issue?

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order!
