### ISSUE TITLE
Feat: Update Twitter Icon

### ISSUE THREAD

**Issue by pragyamishra56** [layer5io/layer5#5013]
**Title: Update Twitter Icon**

1. **Current Behavior:**
The current Twitter icon used in the application is outdated and does not align with the latest design standards. It lacks consistency with other social media icons, affecting the overall user experience.

2. **Desired Behavior:**
We aim to update the Twitter icon to ensure it matches the current design guidelines and maintains visual consistency with other social media icons on the platform. This enhancement will provide a more cohesive and visually appealing user interface.

3. **Screenshots / Mockups:**
![Screenshot 2023-10-08 153339](https://github.com/layer5io/layer5/assets/115208912/97e7b010-4aed-49cc-a5fc-e4e691a6eb00)

4. **Implementation:**
To implement this update, follow these steps:
   - Identify the current Twitter icon asset.
   - Design or source a new Twitter icon that aligns with the updated design guidelines.
   - Replace the old icon with the new one in the application's codebase.
   - Test the new icon in different contexts to ensure it displays correctly and is visually consistent.
   - Update documentation or guidelines, if necessary, to reflect the change for future maintenance.
   - 

5. **Acceptance Tests:**
   - The updated Twitter icon should be visually consistent with other social media icons on the platform.
   - The icon should display correctly in different resolutions and on various devices.
   - Any relevant documentation or guidelines should reflect the change.
   - User feedback should indicate improved visual consistency and a more polished user interface.
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by pragyamishra56** [comment]
I hope you're doing well. I'm Pragya Mishra, working as a Front-end developer and I'm excited about this project. This would be my first time for Hacktoberfest 2023 contribution to an open-source project, and I'm eager to get started.
I've been looking through the issues and I'm particularly drawn to this issue. It seems like a great start for me to learn and contribute to this project.
Could I take on this issue? I'm more than willing to put in the effort and would greatly appreciate your guidance on how to proceed.
Thanks a lot for your time and consideration!

**Comment by abhijeetgauravm** [comment]
Hey @pragyamishra56, we really appreciate your enthusiasm to contribute. However, this issue is already being addressed by a contributor, as you can see [here](https://github.com/layer5io/layer5/issues/4631), and there is an open [PR](https://github.com/layer5io/layer5/pull/5001) for it. But that shouldn't stop you from contributing 🦾. You can also review the open PR. And  we have a bunch of other open issues, and you are most welcome to contribute.
