### ISSUE TITLE
Change the color of Meshery logo to keppel green

### ISSUE THREAD

**Issue by VivekBaldha0712** [layer5io/layer5#5015]
### Description

Color of the Meshery logo is white. It should be Keppel Green.

### Screenshots

<img width="950" alt="image" src="https://github.com/layer5io/layer5/assets/86009821/3b65852e-bc5b-4d85-92cc-b205e1a4730f">

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by VivekBaldha0712** [comment]
I would like to work on this

**Comment by shishiro26** [comment]
I would like to work on this . Can u please assign it to me.

**Comment by pragyamishra56** [comment]
@VivekBaldha0712  I hope you're doing well. I'm Pragya Mishra, working as a Front-end developer and I'm excited about this project. This would be my first time for Hacktoberfest 2023 contribution to an open-source project, and I'm eager to get started.
I've been looking through the issues . It seems like a great start for me to learn and contribute to this project.
Could I take on this issue? I'm more than willing to put in the effort and would greatly appreciate your guidance on how to proceed.
Thanks a lot for your time and consideration!

**Comment by abhijeetgauravm** [comment]
Hey @VivekBaldha0712 Let's discuss this on website call today at 5:30 PM IST / 7 AM Central time. Pleasde add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima)

**Comment by VivekBaldha0712** [comment]
@leecalcote  Please assign this issue

**Comment by vishalvivekm** [comment]
Hi @VivekBaldha0712 
Thanks for opening this.
Please use this svg :
```
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 393.99 86.33"><defs><style>.cls-1{fill:#00d3a9;}.cls-2{fill:#00b39f;}.cls-3{fill:#fff;}</style></defs><polygon class="cls-1" points="48.87 21.97 48.87 41.12 65.47 31.51 48.87 21.97"/><polygon class="cls-1" points="48.87 45.13 48.87 64.36 65.62 54.79 48.87 45.13"/><polygon class="cls-2" points="46.48 40.99 46.48 22.14 30.09 31.53 46.48 40.99"/><path class="cls-2" d="M13.61,64.3A40.22,40.22,0,0,0,26.32,77.09V56.94Z"/><polygon class="cls-2" points="46.48 64.28 46.48 45.27 30.05 54.78 46.48 64.28"/><polygon class="cls-1" points="28.71 75.89 45.35 66.38 28.71 56.76 28.71 75.89"/><polygon class="cls-2" points="66.76 76 66.76 56.89 50.14 66.39 66.76 76"/><path class="cls-2" d="M83,62.08a39.77,39.77,0,0,0,4.7-17.18L70.42,54.8Z"/><polygon class="cls-1" points="69.15 52.77 85.84 43.23 69.15 33.63 69.15 52.77"/><polygon class="cls-2" points="66.76 29.5 66.76 10.51 50.22 19.99 66.76 29.5"/><polygon class="cls-2" points="66.76 52.69 66.76 33.53 50.18 43.12 66.76 52.69"/><polygon class="cls-2" points="47.68 83.25 47.68 83.25 47.67 83.25 47.68 83.25"/><polygon class="cls-1" points="28.71 33.49 28.71 52.79 45.41 43.13 28.71 33.49"/><path class="cls-2" d="M46.48,3.08A39.7,39.7,0,0,0,28.89,7.73L46.48,17.84Z"/><polygon class="cls-1" points="28.71 10.38 28.71 29.57 45.42 19.99 28.71 10.38"/><path class="cls-2" d="M26.32,9.22A40.28,40.28,0,0,0,13.6,22l12.72,7.33Z"/><path class="cls-1" d="M66.65,7.82A40,40,0,0,0,48.87,3.08V18Z"/><path class="cls-1" d="M7.61,44.56A39.92,39.92,0,0,0,12.4,62.23l12.88-7.45Z"/><path class="cls-1" d="M12.4,24.08A39.84,39.84,0,0,0,7.61,41.66L25.3,31.52Z"/><path class="cls-2" d="M28.85,78.56a39.76,39.76,0,0,0,17.63,4.67V68.48Z"/><path class="cls-1" d="M81.78,22.07A40.24,40.24,0,0,0,69.15,9.29V29.38Z"/><path class="cls-1" d="M69.15,77A40.31,40.31,0,0,0,81.84,64.15L69.15,56.82Z"/><path class="cls-2" d="M87.74,41.56A39.92,39.92,0,0,0,83,24.13L70.25,31.51Z"/><path class="cls-1" d="M48.87,83.23a39.67,39.67,0,0,0,17.59-4.65L48.87,68.42Z"/><polygon class="cls-2" points="26.32 52.62 26.32 33.69 9.88 43.12 26.32 52.62"/><polygon class="cls-3" points="277.25 31.09 277.25 32.59 277.25 39.64 277.25 48.24 277.25 60.79 310.66 60.79 310.66 53.74 284.3 53.74 284.3 48.24 284.3 46.69 304.55 46.69 304.55 39.64 284.3 39.64 284.3 32.59 310.66 32.59 310.66 25.54 277.25 25.54 277.25 31.09"/><polygon class="cls-3" points="148.72 31.09 148.72 32.59 148.72 39.64 148.72 48.24 148.72 60.79 182.13 60.79 182.13 53.74 155.76 53.74 155.76 48.24 155.76 46.69 176.02 46.69 176.02 39.64 155.76 39.64 155.76 32.59 182.13 32.59 182.13 25.54 148.72 25.54 148.72 31.09"/><path class="cls-3" d="M228.38,51.58a8.74,8.74,0,0,1-.73,3.57,9,9,0,0,1-2,2.93,9.7,9.7,0,0,1-2.94,2,9.12,9.12,0,0,1-3.6.73h-33V53.36h33a1.76,1.76,0,0,0,1.79-1.78V48.71a1.72,1.72,0,0,0-.52-1.27,1.74,1.74,0,0,0-1.27-.52H195.39a8.9,8.9,0,0,1-3.57-.72,9.4,9.4,0,0,1-5-5,8.94,8.94,0,0,1-.73-3.57V34.8a9,9,0,0,1,.73-3.59,9.45,9.45,0,0,1,5-4.94,8.74,8.74,0,0,1,3.57-.73h33V33h-33a1.78,1.78,0,0,0-1.79,1.79v2.87a1.76,1.76,0,0,0,1.79,1.78h23.73a9,9,0,0,1,3.6.73,9.58,9.58,0,0,1,2.94,2,9.39,9.39,0,0,1,2,2.93,9,9,0,0,1,.73,3.6Z"/><path class="cls-3" d="M272.84,60.79h-6.72V46.92H239.91V60.79h-6.73V39.45h32.94V25.54h6.72ZM239.91,36.14h-6.73V25.54h6.73Z"/><polygon class="cls-3" points="368.76 37.88 359.95 25.54 351.14 25.54 365.24 46.69 365.24 60.79 372.28 60.79 372.28 46.69 386.38 25.54 377.68 25.54 368.76 37.88"/><path class="cls-3" d="M322.65,32.26h18.08v7.33H326.16v6.72h3.35l12.78,14.48H351L338.21,46.31h5a5.47,5.47,0,0,0,5.47-5.47V31a5.47,5.47,0,0,0-5.47-5.48H315.75V60.79h7Z"/><path class="cls-3" d="M143.29,60.79h-7.47V35.08a2,2,0,0,0-.16-.8,2.15,2.15,0,0,0-.45-.66,2.31,2.31,0,0,0-.66-.44,1.94,1.94,0,0,0-.8-.17H99.21V25.54h34.54a9.22,9.22,0,0,1,3.69.75,9.46,9.46,0,0,1,5.1,5.1,9.22,9.22,0,0,1,.75,3.69Zm-36.61,0H99.21V33l7.47-2Zm18.29,0h-7.48V36.93H125Z"/></svg>
```
<hr>
@shishiro26 @pragyamishra56 
Here you'll find many good-first and help-wanted issues:

https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
