### ISSUE TITLE
In the integration section of Layer5 Website's Home Page honeycombs are not centered in the mobile view.

### ISSUE THREAD

**Issue by harshit-senpai** [layer5io/layer5#5021]
**Current State:**
The current view of the Integrations section is not centered on the mobile view.
![image](https://github.com/layer5io/layer5/assets/93075068/347031f4-01b9-4de7-8bef-6f0f0b0a1f39)

**Desired State:**
The section would look better if the honeycombs were to be in the center.
![image](https://github.com/layer5io/layer5/assets/93075068/29ac94ec-2a6e-4b11-86e8-dcb5bd2750f9)

if this issue is valid i would like to work on it 
---
**Contributor Resources**
The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- Check the Learn Layer5 site [Design Spec](https://docs.google.com/document/d/1tQ9tLbetBVKP7z76FR19vsxbAfoFHZzZYxCt7lJpAhU/edit) to know more about the site structure and development plans.
- Checkout the Learn Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/?node-id=4853%3A0).

**Comment by gambhirsharma** [comment]
![Screenshot 2023-10-10 at 8 58 33 PM (2)](https://github.com/layer5io/layer5/assets/69895353/4d959cec-466b-4a19-a92b-5effaf6426c5)

what about this offset gap that's only on the right side? I want to make the items in the center

**Comment by iArchitSharma** [comment]
> ![Screenshot 2023-10-10 at 8 58 33 PM (2)](https://user-images.githubusercontent.com/69895353/273971700-4d959cec-466b-4a19-a92b-5effaf6426c5.png)
> 
> what about this offset gap that's only on the right side? I want to make the items in the center

Got ya its starting from width 333 and below

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. As @harshit-senpai  raised this issue , he wants to work on this let it get assigned to @harshit-senpai .

**Comment by iArchitSharma** [comment]
@devarshishimpi @gambhirsharma, issues are assigned in chronological order, so let @harshit-senpai work on it. Meanwhile, you guys can help with the review process.

**Comment by devarshishimpi** [comment]
No issues! Thank you.

**Comment by abhijeetgauravm** [comment]
@harshit-senpai any updates here?

**Comment by harshit-senpai** [comment]
> @harshit-senpai any updates here?

Yeah I have applied changes in chrome while inspecting, but there seems to be an issue in local development where the setup keeps on stoping at arround 93-99%.

**Comment by abhijeetgauravm** [comment]
> > @harshit-senpai any updates here?
> 
> Yeah I have applied changes in chrome while inspecting, but there seems to be an issue in local development where the setup keeps on stoping at arround 93-99%.

Hey @harshit-senpai, [discuss.layer5.io](http://discuss.layer5.io/) is the best place to ask doubts. Could you please post your doubts here?

**Comment by harshit-senpai** [comment]
@abhijeetgauravm I have discussed on slack on solution that I got was to use GitPod

**Comment by iArchitSharma** [comment]
@harshit-senpai you can also use WSL or mingw32

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm I have discussed on slack one solution that I got was to use GitPod

@harshit-senpai  If you're on a Windows environment then it is highly recommended that you install [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install) both for performance and ease of use. However if you are facing difficulty while setting up your local development environment on WSL [discuss.layer5.io](http://discuss.layer5.io/) is the best place to ask doubts along with the screenshots if you have any. Alternatively, you can use Gitpod but it is limited to 50 hrs per month for free.

**Comment by abhijeetgauravm** [comment]
@devarshishimpi would you like to work here?

**Comment by abhijeetgauravm** [comment]
Any updates here @devarshishimpi @gambhirsharma ?

**Comment by devarshishimpi** [comment]
Hey! @abhijeetgauravm Would it be fine if we submit a pull-request tomorrow with all the necessary changes and updates?

**Comment by gambhirsharma** [comment]
<img width="1094" alt="image" src="https://github.com/layer5io/layer5/assets/69895353/1b7278fd-8a20-45c1-b8d4-a1f82bc51e08">

Error while `make site`

**Comment by abhijeetgauravm** [comment]
Hey @gambhirsharma try removing the node modules and re-install the dependencies using make setup command. Could you post your doubts on our public [slack](https://slack.layer5.io/) channels too ? Also our discuss forum [discuss.layer5.io](http://discuss.layer5.io/) is the best place to ask doubts if you have any.

**Comment by souravbhunia07** [comment]
Is this issue closed? if not can you please assign it to me?

**Comment by abhijeetgauravm** [comment]
Hey @devarshishimpi Could you post your doubts on our public [slack](https://slack.layer5.io/) channels too ? Also our discuss forum [discuss.layer5.io](http://discuss.layer5.io/) is the best place to ask questions.

**Comment by abhijeetgauravm** [comment]
@devarshishimpi any updates here?

**Comment by abhijeetgauravm** [comment]
@souravbhunia07 would you like to address it?

**Comment by narasimha-1511** [comment]
i would like to work on this issue?
