### ISSUE TITLE
[Community] Member Profile: Archit Sharma

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5024]
**Current Behavior**

@iArchitSharma has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @iArchitSharma as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @iArchitSharma
- Twitter: [IArchitSharma](https://twitter.com/IArchitSharma)
- LinkedIn: https://www.linkedin.com/in/iarchitsharma/
- Meshery Cloud: 
- Link to profile picture: [Image](https://media.licdn.com/dms/image/D4D03AQEOedBLI8sjbw/profile-displayphoto-shrink_800_800/0/1692993231433?e=1702512000&v=beta&t=IG-5G7Kyzz3_Oec9Sib8Taphvh1vUGcIQ9a9ov83v5E)

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by VivekBaldha0712** [comment]
I would like to work on this

**Comment by saurabh100ni** [comment]
Go on @VivekBaldha0712 😎🚀

**Comment by saurabh100ni** [comment]
@iArchitSharma 

Please comment on your Meshery Cloud profile link 
(Please also share your picture for the member profile if you have any specifically, I have shared the one on your LinkedIn profile).

**Comment by iArchitSharma** [comment]
@saurabh100ni 
Meshery cloud profile link - https://meshery.layer5.io/user/2662825c-2bc7-4dea-a7ef-91269d334f71
Profile picture - https://drive.google.com/file/d/14q_wxlINtkzULVjktna9a1iVvETK1CJc/view?usp=sharing

**Comment by VivekBaldha0712** [comment]
hey @iArchitSharma , Can you please provide your bio for profile.

**Comment by iArchitSharma** [comment]
@VivekBaldha0712 
`Hi, I'm Archit Sharma, an undergraduate student in Information Technology and an open-source enthusiast. I enjoy contributing to open-source projects and building web applications using Node.js and React.`

**Comment by iArchitSharma** [comment]
Thanks @VivekBaldha0712
