### ISSUE TITLE
[Community] Member Profile: Daniel Kiptoon

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5026]
**Current Behavior**

@KiptoonKipkurui has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @KiptoonKipkurui as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @KiptoonKipkurui 
- Twitter: 
- LinkedIn: [daniel-kipkurui-kiptoon-56b8a1177](https://www.linkedin.com/in/daniel-kipkurui-kiptoon-56b8a1177/)
- Meshery Cloud: [a1837b00-c5b8-4a91-86d6-dec9527d70be](https://meshery.layer5.io/user/a1837b00-c5b8-4a91-86d6-dec9527d70be)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by akhilender-bongirwar** [comment]
@vishalvivekm, I would like to get assigned.

**Comment by KiptoonKipkurui** [comment]
@vishalvivekm let me work on this, for the image link, you need me to upload it somewhere then send a link?

**Comment by ankushbhardwaj408** [comment]
Hi @vishalvivekm i would like to work on this.Please assign it to me.

**Comment by vishalvivekm** [comment]
> @vishalvivekm let me work on this, for the image link, you need me to upload it somewhere then send a link?

Yeah that would work, or you can just simply drop your image here in GitHub comments too.

@akhilender-bongirwar since @KiptoonKipkurui himself has volunteered for this issue, will have to assign this to @KiptoonKipkurui . 😃 

@ankushbhardwaj408 
Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by KiptoonKipkurui** [comment]
![DANIEL KIPTOON](https://github.com/layer5io/layer5/assets/50325211/b689fa17-2969-471f-ae7d-d12579c2f311)

**Comment by KiptoonKipkurui** [comment]
twitter/x: https://twitter.com/danchi101
bio: Daniel Kiptoon is a seasoned software engineer with a fervent passion for creating scalable systems, mastering the intricacies of distributed computing (Kubernetes and Docker), and promoting DevSecOps principles. He aspires to improve the technology landscape with innovative solutions and to lead the conversations on the next generation cloud-native solutions.

**Comment by KiptoonKipkurui** [comment]
@vishalvivekm thanks for your help so far, let me know if I need to supply anything else,

**Comment by Debaditya-Som** [comment]
@vishalvivekm, for being recognized as a contributor to Layer5io, do we need to contribute only to Layer5 website or any other projects of Layer5 like Meshery or Sistent?

**Comment by vj-codes** [comment]
@vishalvivekm hey I would like to work on this

**Comment by abhijeetgauravm** [comment]
> @vishalvivekm thanks for your help so far, let me know if I need to supply anything else,

Hey @KiptoonKipkurui, will you work on this, or should we give a chance to volunteers to work on this?

**Comment by KiptoonKipkurui** [comment]
@abhijeetgauravm I am working on this, I hadnt understood before what is expected

**Comment by Mohith234** [comment]
@KiptoonKipkurui Any update? If not we can assign it to other contributors. 

Let's not wait for too long and get this fixed soon.

**Comment by KiptoonKipkurui** [comment]
@Mohith234 Sorry for the sluggish movement on this, I have had a medical emergency that inhibited my fluid operation. I will get it done by end of day today

**Comment by vishalvivekm** [comment]
> @Mohith234 Sorry for the sluggish movement on this, I have had a medical emergency that inhibited my fluid operation. I will get it done by end of day today

No sweat @KiptoonKipkurui. Thanks for sending word. Get well soon and yeah please do let me know if I should assist here.
