### ISSUE TITLE
 [Grammar Adjustment] Community - Community Membership

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5028]
**Current State:**

- Link to website: https://layer5.io/community/members
- Currently, there's a sentence in the paragraph next to the **Community Membership** heading reads as follows: "We also spend a great deal of time trying to recognize and uplift contributors on the Layer5 and Meshery Twitter accounts whether "contribution" means code or any of the other various forms of being involved int the projects and community."

**Desired State:**

- The suggested change is to adjust the sentence so it reads as: "We also spend a great deal of time trying to recognize and uplift contributors on the Layer5 and Meshery Twitter accounts whether "contribution" means code or any of the other various forms of being involved in the projects and community."

---
**Screenshot**

![imageedit_2_8919288326](https://github.com/layer5io/layer5/assets/19821445/ebb9c6a7-2fec-499d-b62b-413fae8c5a68)

**Comment by geetika005** [comment]
Can you please assign this issue to me

**Comment by Harsha-10** [comment]
I would like to work on this

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering. Assigning in chronological order!

**Comment by geetika005** [comment]
Can you please add the hacktoberfest label as i am participating in hacktoberfest @abhijeetgauravm
