### ISSUE TITLE
[NG] Migrate content of existing Footer to new Footer component

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#503]
**Current Behavior**
The content of the existing site [footer.html](https://github.com/layer5io/layer5/blob/master/_includes/footer.html) needs to be migrated to the layer5-ng site.

**Desired Behavior**
Layer5-ng site's footer should have almost all the same content.

**Implementation**
1. Update colors to match [Layer5's brand](https://layer5.io/brand)
1. Make twitter feed a separate component; embed twitter feed component into new footer.
1. Make language flags a separate component; embed language flags component into new footer.

**Comment by Jashpatel1** [comment]
Closing this as addresses in #532
