### ISSUE TITLE
[Community] Member Profile: Akshay Sharma

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5033]
**Current Behavior**

@captain-Akshay has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @captain-Akshay as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @captain-Akshay
- Twitter: [@akshay_0503](https://twitter.com/akshay_0503)
- LinkedIn: [akshay-sharma-76a267203](https://www.linkedin.com/in/akshay-sharma-76a267203/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation of how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by saurabh100ni** [comment]
@captain-Akshay Please Drop the following in the comments:
- Meshery Cloud:
- Link to profile picture:
- Bio:

**Comment by shishiro26** [comment]
Hi@saurabh100ni I would like to work on this . Can u please assign this to me.

**Comment by saurabh100ni** [comment]
Go On @shishiro26 😎🚀

**Comment by captain-Akshay** [comment]
meshery-cloud: https://meshery.layer5.io/user/51f49d2c-0050-4bdb-9bce-fdddcb4742be
profile-pic: https://media.licdn.com/dms/image/D4D03AQEfhGAuUAWIyg/profile-displayphoto-shrink_800_800/0/1680550303473?e=1702512000&v=beta&t=MjLtiAZU690wcIYlnQNJkmUwDamlfWSZZrrC20Q3xd0
bio: Hi,I like to code!

**Comment by captain-Akshay** [comment]
Thanks @shishiro26 for this! :+1:
