### ISSUE TITLE
[Community] Member Profile: Parthib Datta

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5034]
**Current Behavior**

@ptdatta has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @ptdatta as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @ptdatta
- Twitter: [@parthibdatta123](https://twitter.com/parthibdatta123)
- LinkedIn: [parthib-datta-90b29b1b4](https://www.linkedin.com/in/parthib-datta-90b29b1b4/)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by saurabh100ni** [comment]
@ptdatta Please Drop the following in the comments:

- Meshery Cloud:
- Link to profile picture:
- Bio:

**Comment by ptdatta** [comment]
> @ptdatta Please Drop the following in the comments:
> 
> * Meshery Cloud:
> * Link to profile picture:
> * Bio:

Thank you so much @saurabh100ni 
 - Meshery Cloud: https://meshery.layer5.io/user/55a18ae1-fef3-4ffc-a385-1973ca2c9fd8
 - Link to profile picture: https://drive.google.com/file/d/1_teTIrmLQAwZJzfd3HywR9xFV7ezM81J/view?usp=drive_link
 - Bio: Hi there! I'm a passionate software engineer currently pursuing my B.Tech in Computer Science at the University of Calcutta. I thrive in the world of technology and have a deep love for Open Source and community-driven initiatives. My interests span the entire spectrum of full-stack development, from crafting user-friendly frontends to building robust backends and optimizing infrastructure for seamless user experiences. I'm dedicated to creating innovative solutions that make a positive impact and am excited to continue my journey in the world of technology.

**Comment by milinddethe15** [comment]
Hi, I want to work on this. Assign me.

**Comment by ankushbhardwaj408** [comment]
Hi i would like to work on this.

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order. And @ankushbhardwaj408 Feel free to take up one of many open good-first and help-wanted issues from here:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+
Feel free to check these out and comment to get assigned.

**Comment by milinddethe15** [comment]
Hi @ptdatta, I can't access your profile photo through the link you provided. Kindly change the permission or accept my request for access through google drive.

**Comment by ptdatta** [comment]
> Hi @ptdatta, I can't access your profile photo through the link you provided. Kindly change the permission or accept my request for access through google drive.

Sorry @milinddethe15 I forgot to change the access.
