### ISSUE TITLE
Responsive Issue on Cards

### ISSUE THREAD

**Issue by Akshun-01** [layer5io/layer5#5045]
### Description

The cards on page: https://layer5.io/learn/learning-paths
are not mobile responsive.

![image](https://github.com/layer5io/layer5/assets/93793691/1a2738b1-e030-4608-bfc6-5aa4bb3c1257)

### Expected Behavior

The cards and content within should be made responsive so that they are easier for users to use even on other screen sizes.

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by arianxq** [comment]
I will solve this issue

**Comment by shishiro26** [comment]
I would like to work on this can u please assign this to me.

**Comment by abhijeetgauravm** [comment]
Assigning in chronological order gents. @shishiro26  Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
