### ISSUE TITLE
[About] Change collaboration map SVG image to brand colors

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5046]
### Current Behavior
The collaboration map on the about page is using blue and red coloring. https://layer5.io/company/about

<img width="1272" alt="Screenshot 2023-10-16 at 8 41 41 PM" src="https://github.com/layer5io/layer5/assets/7570704/ae9d7d68-f8f8-40a7-b2f9-b33aeb5cf454">

### Desired Situation
Ideally, it is using colors from our brand color scheme --> https://layer5.io/brand

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
I would like to work on this issue

**Comment by arunkarthicknm** [comment]
I can do this, please assign me if needed :)

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order. @arunkarthicknm Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
