### ISSUE TITLE
Add "All Integrations" button

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5047]
### Current Behavior
On https://layer5.io/cloud-native-management/meshmap/design, the Built-in Integrations section needs to have a button leading the visitor to the page that displays all integrations.

### Desired Situation
1. Add new button linking to this page: https://layer5.io/cloud-native-management/meshery/integrations
1. Ensure responsive underline image placement in the Built-in Integrations heading.

### Mockup:

<img width="1301" alt="Screenshot 2023-10-16 at 9 32 59 PM" src="https://github.com/layer5io/layer5/assets/7570704/6067be25-af9c-4ad9-b859-2916acd2e0d3">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vamsi4845** [comment]
would like to work on this

**Comment by Petrificus-totalus** [comment]
Hi, could you pls assign this one to me ?

**Comment by Himanshu1801** [comment]
Hi @leecalcote, 
I'm interested in working on this feature request. Could you please assign it to me?

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order. @Petrificus-totalus @Himanshu1801 Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by vamsi4845** [comment]
Is there any way to set up this on the web?

**Comment by abhijeetgauravm** [comment]
> Is there any way to set up this on the web?, I'm facing probelm during setup locally (make installation)


Hey @vamsi4845 If you're on a Windows environment then it is highly recommended that you install [Windows Subsystem for Linux (WSL)](https://docs.microsoft.com/en-us/windows/wsl/install) both for performance and ease of use. However if you are facing difficulty while setting up your local development environment on WSL [discuss.layer5.io](http://discuss.layer5.io/) is the best place to ask doubts along with the screenshots if you have any.

**Comment by abhijeetgauravm** [comment]
> Hi @abhijeetgauravm I have setup the project locally and it is working flawlessly, so can you assign this to me.

@Himanshu1801, really appreciate your enthusiasm to contribute but let's give some time to @vamsi4845 to work on this! In the meanwhile, please feel free to check these open issues and comment to get assigned.
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by vamsi4845** [comment]
ok l'm almost done setting up

**Comment by Shiva953** [comment]
I've successfully added the integration button and tested the changes locally.

https://github.com/layer5io/layer5/assets/120790871/dad02865-95c3-4676-abcf-44cfc5ec4ad5

Should I raise a PR?

**Comment by vamsi4845** [comment]
@abhijeetgauravm I'm getting issues in pull request checks. Need some help!

**Comment by vamsi4845** [comment]
@abhijeetgauravm I'm not able to solve the issues. you can assign this to someone

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm I'm not able to solve the issues. you can assign this to someone



> @abhijeetgauravm I'm getting issues in pull request checks. Need some help!

Hey @vamsi4845 commented on the PR!

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm I'm getting issues in pull request checks. Need some help!

Hey @vamsi4845 commented on the PR!

**Comment by vamsi4845** [comment]
@abhijeetgauravm Yeah I tried that still not able to solve that,you can assign this to someone

**Comment by abhijeetgauravm** [comment]
there u go @Petrificus-totalus

**Comment by Petrificus-totalus** [comment]
Please hand this over to the next volunteer due to personal reason. Thank you @abhijeetgauravm.

**Comment by Shiva953** [comment]
can I take it now? @abhijeetgauravm 
I've already done the required changes.

**Comment by Himanshu1801** [comment]
Hi @abhijeetgauravm, please assign it to me.

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order. There u go @Himanshu1801 and @Shiva953 you can help in reviewing the PR! And Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
