### ISSUE TITLE
[Community] Member Profile: Mohith Gadireddy

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5051]
**Current Behavior**

@Mohith234 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Mohith234 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Mohith234
- Twitter: 
- LinkedIn: [in/mohith-gadireddy](https://linkedin.com/in/mohith-gadireddy)
- Meshery Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by saurabh100ni** [comment]
@Mohith234 please share following :
- Twitter: 
- Meshery Cloud: 
- Link to profile picture:
- bio

**Comment by Harsha-10** [comment]
I would like to work on this issue

**Comment by saurabh100ni** [comment]
Go on @Harsha-10 😎🚀

**Comment by Harsha-10** [comment]
Can you please add the hactoberfest label as I'm participating in it....@saurabh100ni

**Comment by saurabh100ni** [comment]
Sure thing ^ ^

**Comment by Harsha-10** [comment]
Thank you!

**Comment by Harsha-10** [comment]
Please share the details @Mohith234

**Comment by Mohith234** [comment]
- **Twitter** : https://twitter.com/mohith_twt
- **Meshery Cloud** : https://meshery.layer5.io/user/92b8fb72-fa12-4a7e-9a40-c7f79b292248
- **Link to profile picture** : https://drive.google.com/file/d/1U1-j7h3zz_HsWa67Qm3c1Y2Cf10uwgz6/view?usp=drivesdk
- **Bio** : Hello there! I am a Full Stack Developer and a tech enthusiast, always eager to contribute to open-source projects. I have a strong passion for DevOps and the Cloud Native ecosystem, and I have gained valuable experience in these areas through my contributions to OSS. Contributing to Layer5 is one of the pivotal steps that helped me improve my skillset.
