### ISSUE TITLE
Add Projects in navigation bar

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5054]
### Current Behavior
We list Products and Projects inside the same dropdown in the navigation bar.
![image](https://github.com/layer5io/layer5/assets/51539117/d726183f-51e0-46a7-a1ca-5d086201ee01)

### Desired Behavior
1. Change **_Products_** title in the navigation bar to **_Products/Projects_**.
![image](https://github.com/layer5io/layer5/assets/51539117/ac5664a7-7e54-47b8-be1a-91c7b97878e8)

2. Add a **_Project_** title inside the dropdown.
3. List all products inside **_Products_** title  and projects inside **_Projects_** title. 
    - All list item above "---" in the current implementation is Product and list items below "---" are projects 
5. Link **_Projects_** title to [layer5.io/projects](https://layer5.io/projects) page

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by xbelix** [comment]
Hey I'm ready for this, assign me :)

**Comment by aakashdeepsil** [comment]
Hi team,
Can I please take this issue?

**Comment by Sadman95** [comment]
Hello
Can I contribute?

**Comment by ritiksaxena124** [comment]
Thank you @aakashdeepsil and @Sadman95 for your interest in this issue, we follow first come first serve so @xbelix you can start working on this issue.

**Comment by abhijeetgauravm** [comment]
@aakashdeepsil  @Sadman95  Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by abhay-raj19** [comment]
Pls assign it to me, i can work on this and will add up the PR within 2 hrs and will also add up the projects in the section

**Comment by sandramsc** [comment]
@abhay-raj19 please read the comment history to familiarize yourself with the issue update. This issue has already been assigned to someone else. As mentioned in a previous issue [here](https://github.com/layer5io/layer5/issues/5065#issuecomment-1773882218) I recommend again that you look at the **Assignees** box before you ask for an issue to be assigned to you. Let's focus on collaboration and not competition.

> Pls assign it to me, i can work on this and will add up the PR within 2 hrs and will also add up the projects in the section

@abhay-raj19 please read the comment history to familiarize yourself with the issue update. This issue has already been assigned to someone else. As mentioned in a previous issue [here](https://github.com/layer5io/layer5/issues/5065#issuecomment-1773882218) I recommend again that you look at the **Assignees** box before you ask for an issue to be assigned to you. Let's focus on collaboration and not competition.

**Comment by Mohith234** [comment]
@xbelix Any update?

**Comment by hemantmm** [comment]
Hi, @Mohith234 if @xbelix is not working on this issue, I could take up this

**Comment by abhijeetgauravm** [comment]
Since there is no updates from @xbelix, let it get assigned to @aakashdeepsil . And @abhay-raj19 @hemantmm Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by aakashdeepsil** [comment]
Thanks for the opportunity. I will begin the work soon.

**Comment by balagowda** [comment]
hello @aakashdeepsil, are you working on this??

**Comment by aakashdeepsil** [comment]
> hello @aakashdeepsil, are you working on this??

Yes. I just created a PR for the issue.

**Comment by iampaandey** [comment]
@leecalcote is this still open?

**Comment by abhijeetgauravm** [comment]
> @leecalcote is this still open?

Yeah @iampaandey and there is already a PR open for it. @iampaandey Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
