### ISSUE TITLE
Incorrect Meshery Catalog Link In Readme file

### ISSUE THREAD

**Issue by Kaushik080** [layer5io/layer5#5061]
### Description
On clicking the heading of Meshery Catalog in Readme file it redirects to wrong page - https://layer5.io/projects/catalog
![image](https://github.com/layer5io/layer5/assets/120493528/a3f29722-9c5c-40ad-8b6b-b13a64b74694)

![image](https://github.com/layer5io/layer5/assets/120493528/8a1b3b67-6195-4072-840d-9bd357793054)

### Expected Behavior
On clicking on the heading of Meshery Catalog in Readme file it should redirect to -https://layer5.io/catalog
![image](https://github.com/layer5io/layer5/assets/120493528/a4436a5b-3328-45d9-9221-e34ea942909a)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by adityadeshpande09** [comment]
Hey,I'd like to work on this issue,please assign me
.

**Comment by abhijeetgauravm** [comment]
there u go @adityadeshpande09
