### ISSUE TITLE
SEO Enhancements in Collections

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5064]
### Description of Issue

Various page collections are in need of SEO enhancements as described in @randychilau's message below:

> If you wanted expand your previous work even further in another PR, here are some possible tasks:
> 
> As you mentioned in your notes regarding the `news` pages, there was a field `subtitle` not being used.
>    - to improve SEO for these pages, update the `news` mdx files with a proper `frontmatter` field and content to be shown in the `head` section. Options may include adding content for the `subtitle` field or adding a `description` field and using the first two sentences of the post as content.
>   - find the instructions for creating MDX files in each collection (e.g. `news`) and review/update them to make sure it indicates which fields should be required before publishing and why.
> 
> Other mdx page collections that could benefit from better SEO:
>   - there are MDX files in folders `src/collections/members` and `content-learn` that are using templates that could also be improved. (note: if the content for a potential field may seem too long (e.g. `bio`), you can use javascript techniques to only include a portion of that content in the field).
> 
> Cheers,
> Randy
> 

_Originally posted by @randychilau in https://github.com/layer5io/layer5/issues/4898#issuecomment-1719879317_

**Comment by leecalcote** [comment]
// @randychilau @Mohith234

**Comment by narasimha-1511** [comment]
i would like to work on this issue

**Comment by Mohith234** [comment]
Thanks for volunteering @narasimha-1511, I'm currently working on this task. I would suggest you pick up other [open issues](https://github.com/layer5io/layer5/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee)

Thank you
