### ISSUE TITLE
[Layer5 GitHub Process] Convert contents to markdown

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5065]
### Current Behavior
The [Layer5 GitHub Process](https://docs.google.com/document/d/1FzX-C_xy9hZ3Eu9dcCE0unhFV5LRUrb5YLn_MGYuG6Y/edit) is currently in the form of a Google document.

### Desired Situation
Convert the Google document content to markdown and  add it to the Community Handbook

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by abhay-raj19** [comment]
Hey @sandramsc i would like to work on this issue can you assign it to me , i can do it .

**Comment by sandramsc** [comment]
> Hey @sandramsc i would like to work on this issue can you assign it to me , i can do it .

Hi @abhay-raj19 Thank you for your enthusiasm to contribute, but this issue has already been assigned. A good practice before asking for issue assignment is to check the top right section under **Assignees** to see if an issue is assigned or not. 

I'd recommend taking a look at our [Newcomers guide](https://layer5.io/community/newcomers)  if you havn't already, particularly the section under "Finding an issue to work on".

**Comment by abhay-raj19** [comment]
okay okay @sandramsc i thought that 2 days have completed and NO PR for the changes have been raised so I thought to ask for the changes if you are working on it or not.No issues

**Comment by sandramsc** [comment]
> okay okay @sandramsc i thought that 2 days have completed and NO PR for the changes have been raised so I thought to ask for the changes if you are working on it or not.No issues

We encourage all contributors to be helpful with the comments that they give. With this said we also encourage contributors to be supportive of one another within the community and not pressure anyone to contribute. In addition to the above mentioned we also encourage collaboration over competion. 

Consider taking a look at unasigned issues or reading the comment history to see if an assigned issue is looking for contributor collaboration.
