### ISSUE TITLE
Removal of Unnecessary hypen in product tab 

### ISSUE THREAD

**Issue by abhay-raj19** [layer5io/layer5#5069]
### Current Behavior

while I am opening up the product tab inside the navbar options there are 3 unnecessary hypens in the product sections

### Screenshots / Mockups

<img width="960" alt="image" src="https://github.com/layer5io/layer5/assets/96302417/093fba4c-a61e-4e06-b258-619607cc34b0">

### Implementation

will remove up the hypens and will see to any addition of the navigation page if not then will re arrange them In correct order.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

Pls assign it to me will raise up the PR ASAP .

**Comment by shivamrazorpay** [comment]
@abhay-raj19 these are used to separate the product & project section, there is already an [issue](https://github.com/layer5io/layer5/issues/5054) open to fix this.

**Comment by sandramsc** [comment]
This issue is a duplicate, based on the points made by @shivamrazorpay.
@abhay-raj19 Please scan issues before creating new ones to be certain that it hasn't already been raised.

**Comment by abhijeetgauravm** [comment]
Since these "---"are used to separate the product & project section. We aren't planning to remove as for now!
