### ISSUE TITLE
[NG]Add ES-lint in the repository

### ISSUE THREAD

**Issue by kushthedude** [layer5io/layer5#507]
**Description**
Add ES-lint in the repository

----
**Resources**
[Gatsby with ESLint](https://www.gatsbyjs.org/docs/eslint/)
[A blog on ESLint with Gatsby](https://dev.to/peshov/how-to-setup-gatsbyjs-starter-with-typescript-eslint-prettier-4jh3)
[ESLint Official Docs](https://eslint.org/docs/user-guide/getting-started)

**Additional Notes**
After invoking the ES-Lint we would probably want to have a CI-Action to check the following which can be dealt on a later issue.

**Comment by leecalcote** [comment]
@crustyy you had a PR on this earlier, right?

**Comment by crustyy** [comment]
Yes @leecalcote but i have to change some rules there that's why i made a pr there once all the rules are set and errors are removed i'll make a fresh pr here

**Comment by kushthedude** [comment]
Fixed in #528
