### ISSUE TITLE
[Community] Member Profile: Hauwa Ismail Ahmad

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5071]
**Current Behavior**

Hauwa has been a consistent contributor and community member.

**Desired Situation**
Let's recognize Hauwa as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: 
- Twitter: [hauwy_ismyl](https://twitter.com/hauwy_ismyl)
- LinkedIn: [hauwa-ismail-75224a255](https://www.linkedin.com/in/hauwa-ismail-75224a255)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by IrfanSalim** [comment]
Hey, I would like to work on this, please assign.

**Comment by hemantmm** [comment]
Hi, @vishalvivekm I would like to work on this issue

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order. @hemantmm Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by vishalvivekm** [comment]
Thanks @IrfanSalim 
Here you go:

bio: ` Dedicated to helping Layer5 thrive in the digital landscape. Avid reader, music enthusiast, and an admirer of art (not abstract),`

Profile_picture: 
![lumii_20230805_092739018](https://github.com/layer5io/layer5/assets/110674407/4f948727-754e-418e-b7fb-5f35ccbfe388)

**Comment by IrfanSalim** [comment]
Thanks for sharing @vishalvivekm

**Comment by IrfanSalim** [comment]
Hey, @vishalvivekm 

I have the site up and running and I have added the folder for the new member with the details and the profile pictures well, but it's not reflecting on the member's page, am I missing something?

**Comment by Harsha-10** [comment]
Check whether you typed the name in the url in small letters

**Comment by IrfanSalim** [comment]
I meant the added member is not visible on this page:

![image](https://github.com/layer5io/layer5/assets/109443065/c6741869-2dbf-455f-b108-f122fae7e8f8)

**Comment by Harsha-10** [comment]
Can you see the member's profile?

**Comment by IrfanSalim** [comment]
Nope, nothing for this member.

I added this: 
![image](https://github.com/layer5io/layer5/assets/109443065/262c28f8-b05d-46b5-b2d8-5218ecda529b)

**Comment by vishalvivekm** [comment]
@IrfanSalim if you could please PR the changes, let's see what's the issue

**Comment by Harsha-10** [comment]
Share the screenshot for /community/members/hauwa-ismail-ahmad

**Comment by IrfanSalim** [comment]
Sure @vishalvivekm 

@Harsha-10 
![image](https://github.com/layer5io/layer5/assets/109443065/6b7224a2-322f-44d5-9cf8-a7b212685b05)

**Comment by IrfanSalim** [comment]
"Here empty github user handle, cloud user id and location is causing the error, you are facing in preview!"

Can we get these details? @vishalvivekm
