### ISSUE TITLE
 intra page navigation text is being cutoff in contribution page

### ISSUE THREAD

**Issue by Harsha-10** [layer5io/layer5#5081]
### Description
The navigation text on right side is not visible completely in [contribution page](https://layer5.io/community/handbook/contribution)

### Expected Behavior

The sections on right side are completely visible with good amount of space in between text and edge.

### Screenshots
![image](https://github.com/layer5io/layer5/assets/94053954/faa97a3b-d94f-4e92-8f05-0e11be401ec1)

### Environment:
- Host OS: Windows 11
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
Can i work on this?

**Comment by leecalcote** [comment]
Thank you. Yes, please.

**Comment by Harsha-10** [comment]
can anyone update whether the issue is same for 15.6 inch laptops too

**Comment by Mohith234** [comment]
It's working fine on my 15-inch laptop @Harsha-10

**Comment by Harsha-10** [comment]
Okay, thanks @Mohith234

**Comment by Mohith234** [comment]
@Harsha-10 Please add your agenda item and provide your updates on today's [website meeting](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit)

**Comment by Harsha-10** [comment]
Sorry for that delay, i was having an exam since then.i have completed it yesterday, i will start working on it today.

**Comment by Harsha-10** [comment]
<img width="960" alt="image" src="https://github.com/layer5io/layer5/assets/94053954/82d11128-c9af-4396-baf4-031bc7bcbea9">
can you please explain your take on this.....i think it's not a good idea to change the margin of whole page as it's happening only in 14 inch screens. so is there any alternative way to make it look good or the above padding could be fine?

**Comment by bunnyDasari** [comment]
can i take this issue @leecalcote

**Comment by abhijeetgauravm** [comment]
> can i take this issue @leecalcote

@bunnyDasari there is already a PR open for this, however you can help in reviewing the PR. And  Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
