### ISSUE TITLE
Internavigation Links and Content Order Discrepancy

### ISSUE THREAD

**Issue by ankushbhardwaj408** [layer5io/layer5#5106]
### Description
On this page, there is a discrepancy between the internavigation links and the content order. The internavigation links are located on the right side of the page, but the order of internavigation and content on the site does not match. Additionally, there is an internavigation link that does not have any corresponding content on the page.

### Expected Behavior
1. Internavigation links should correspond to the content on the site in the same order.
2. All internavigation links should have relevant content on the page they are linking to.

### Screenshots
![Screenshot 2023-11-04 231100](https://github.com/layer5io/layer5/assets/93874580/6a884d53-f11d-4feb-a0f0-f9f0957bf197)
![Screenshot 2023-11-04 231028](https://github.com/layer5io/layer5/assets/93874580/b1d6cc17-a8fb-4b8d-88c9-473b70b8d984)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ankushbhardwaj408** [comment]
If this is a valid issue. I would like to work on this.

**Comment by leecalcote** [comment]
Thank you, @ankushbhardwaj408

**Comment by leecalcote** [comment]
What we really need is for this to be dynamic.

**Comment by ankushbhardwaj408** [comment]
> What we really need is for this to be dynamic.

I dont understand what you mean by dynamic.

**Comment by leecalcote** [comment]
Why are you having to fix a bug here?

**Comment by ankushbhardwaj408** [comment]
No, I think there is nothing out of date, it is just the order of the links and the content on the site does not match and as I mentioned earlier there is Profile Badges internavigation link that does not have any corresponding content on the page.

**Comment by leecalcote** [comment]
Ok. Never mind, then. Let’s close this issue. We’re clearly going round in circles and will only continue to do so.
