### ISSUE TITLE
Duplicate Meta descriptions

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5109]
### Current Behavior

   The 10 pages have duplicate meta descriptions:
   - 1. https://layer5.io/community/events/hacktoberfest-2022-docker-extensions-show-n-tell
   - 2. https://layer5.io/programs/hacktoberfest
   - 3. https://layer5.io/community/events/kubecon-cloudnative-north-america-2022
   - 4. https://layer5.io/company/news/layer5-and-hashicorp-launch-service-mesh-partnership
   - 5. https://layer5.io/community/events/hacktoberfest-prep-2023-easing-into-cncf-open-source-projects
   - 6. https://layer5.io/community/events/kcd-chennai-2023
   - 7. https://layer5.io/community/events/may-maintainers-circle-2023
   - 8. https://layer5.io/community/events/kubecon-cloudnativecon-eu-amsterdam-2023
   - 9. https://layer5.io/community/events/kubecon-cloudnativecon-north-america-chicago-2023
   - 10. https://layer5.io/community/events/istiocon-virtual-2023

Steps to check : Go to these pages, view the source-code ( CTRL+U) and search for `og:description`

### Desired Situation

The 10 pages should have different meta descriptions.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by iArchitSharma** [comment]
@vishalvivekm where are the events pages getting the `og:description` from i checked [templates/events.js](https://github.com/layer5io/layer5/blob/master/src/templates/events.js) description in SEO tag is different from the description that i see on source-code code of events page?

**Comment by Mohith234** [comment]
@iArchitSharma It is coming from [templates/events-single.js](https://github.com/layer5io/layer5/blob/master/src/templates/event-single.js). We need to add the description here.

**Comment by iArchitSharma** [comment]
Also @vishalvivekm @Mohith234 4th links `og:description` is already unique
