### ISSUE TITLE
Incorrect Order of Section Titles on Recognition Page

### ISSUE THREAD

**Issue by Savio629** [layer5io/layer5#5111]
### Description
Incorrect Order of Section Titles on Recognition Page
![image](https://github.com/layer5io/layer5/assets/91362589/9ca36b4d-2bd0-4293-819f-19d2936a9e48)

### Expected Behavior
The table of contents of section titles should be swapped

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
I would like to work on it

**Comment by jayesnc2512** [comment]
Hi, I'm a beginner and I wanted to solve this issue.

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering, folks. Since @jayesnc2512 is a first-time contributor, let's assign the task to him. And @Harsha-10 Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.
