### ISSUE TITLE
New Design needed for Github Workflow section

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5117]
### Current Behavior
Currently the section looks like this on this [page](https://layer5.io/cloud-native-management/gitops/snapshot#:~:text=See%20this%20sample%20GitHub%20workflow%20(action.yml)%20for%20more%20configuration%20details.)
![image](https://github.com/layer5io/layer5/assets/101441772/70656bf2-e065-454a-b557-d101c18ff93d)

### Desired Behavior
We need a new design for this specific section and also a better message.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by balagowda** [comment]
I would like to work on this

**Comment by sandramsc** [comment]
> I would like to work on this

Hi, could you indicate what your approach to resolving this might look like for the items indicated?

**Comment by balagowda** [comment]
i made these changes
<img width="1440" alt="Screenshot 2023-11-15 at 11 20 15 PM" src="https://github.com/layer5io/layer5/assets/111847375/ba8ba233-5c18-4479-8202-c742be37c62d">

**Comment by balagowda** [comment]
@saurabh100ni is this a expected outcome

**Comment by saurabh100ni** [comment]
thanks for the help @balagowda this section has to go for now, may be a thing to get done in future because we will be having new design in the section and for the section, so I am closing this issue for now.
