### ISSUE TITLE
Link redirection is not Proper in intra-page

### ISSUE THREAD

**Issue by balagowda** [layer5io/layer5#5119]
### Description
Under handbook link the about page, repo overview, Learning pages the intra-page link direction is properly redirecting

https://github.com/layer5io/layer5/assets/111847375/5adc91e8-3614-4400-8ae2-565e9c947380

### Expected Behavior
intra-page redirection should direct properly

### Screenshots

https://github.com/layer5io/layer5/assets/111847375/41a1edd5-e320-44a1-9f58-bd5c41cf0459

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by balagowda** [comment]
Please assign it to me it's ready for PR 🚀

**Comment by ankushbhardwaj408** [comment]
Hi @balagowda there is already an open issue regarding the same #5068 . Please look into that issue and if you have any suggestions comment there.

**Comment by balagowda** [comment]
@ankushbhardwaj408 the issue #5068 it's about transition smoothness but this is about correction of link redirection navigation.

**Comment by ankushbhardwaj408** [comment]
@balagowda The issue is about inter page navigation and smoothness. Please read the comments, then you will understand and read this PR #5077.

**Comment by sandramsc** [comment]
Please update the issue descripption to state with more detail what the problem is. If the intra-page link **IS** redirecting properly then there isn't an issue here.

**Comment by balagowda** [comment]
In this this issue , when user click the intra-page link it's navigation for top element  is not properly navigating to the header
it's navigating further below wrt header
<img width="1440" alt="Screenshot 2023-11-14 at 2 13 32 PM" src="https://github.com/layer5io/layer5/assets/111847375/28feae7b-668d-4505-89cc-1d057dd7f74b">
