### ISSUE TITLE
Uneven Height of Cards in the Community Page

### ISSUE THREAD

**Issue by trinayreddy4** [layer5io/layer5#5120]
### Description
The Two Cards At the Bottom of the page are of not the same height

### Expected Behavior
Expecting the two cards to be in the same size.

### Screenshots
![Screenshot 2023-11-13 205139](https://github.com/layer5io/layer5/assets/109901688/b92fd6d8-0c11-4d79-93cb-c394382bf41b)

### Environment:
- Host OS: Windows 11
- Browser: Google Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by trinayreddy4** [comment]
if the issue is valid can i get assigned to work on it?

**Comment by abhijeetgauravm** [comment]
Yeah its not looking consistent though! // @Mohith234 @ritiksaxena124 @sudhanshutech

**Comment by roshil1206** [comment]
@trinayreddy4 Can i get assigned to work on the issue.

**Comment by Shiva953** [comment]
I would like to take this issue!

**Comment by Raj100679** [comment]
@leecalcote 
I have updated the size are they good?
![Screenshot (121)](https://github.com/layer5io/layer5/assets/85561967/4d625581-2e1b-44f8-a820-6dd41482ef2d)
![Screenshot (122)](https://github.com/layer5io/layer5/assets/85561967/6c2338b2-c340-480c-b74b-6a1fd328b98a)

**Comment by leecalcote** [comment]
No, not quite. Be sure to center align vertically.

**Comment by trinayreddy4** [comment]
@abhijeetgauravm

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm any Assignees?

Thanks for volunteering gents. Since there is already a PR up by @Raj100679, You can help in reviewing the PR though and let it move forward. @Raj100679  really appreciate your enthusiasm to contribute. However, please refrain from creating direct PRs without getting assigned first.

**Comment by Raj100679** [comment]
@abhijeetgauravm Sorry, will keep that in my mind

**Comment by Raj100679** [comment]
> No, not quite. Be sure to center align vertically.

I am confused how it should , could you explain more

**Comment by Raj100679** [comment]
@leecalcote will update and revert
