### ISSUE TITLE
On refreshing the layer5.io homepage, its taking us to integrations section

### ISSUE THREAD

**Issue by abhijeetgauravm** [layer5io/layer5#5124]
### Description

Whenever refreshing the layer5.io homepage its taking us to integrations section!
### Expected Behavior

It should point to starting/top of the page.
### Screenshots

https://github.com/layer5io/layer5/assets/65087356/50d58cc6-11f3-4f48-8130-313dd764180b

### Environment:
- Host OS: Windows
- Browser: Microsoft Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by balagowda** [comment]
@abhijeetgauravm

**Comment by leecalcote** [comment]
@abhijeetgauravm @balagowda thank you for jumping on this! This is a high priority bug.
