### ISSUE TITLE
[Handbook] Word repetition 

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5128]
### Description

Currently the word "other" is repeated twice (after each other) in a sentence. 

Path: Handbook > [General FAQ's](https://layer5.io/community/handbook/faq) > last answer --> "...the community calendar, while other other times they are simply self-organized by interested contributors."
### Expected Behavior

Removing the duplicate word _other,_ would fix the grammar/typo i.e "...the community calendar, while other times they are simply self-organized by interested contributors."

### Screenshots

![img](https://github.com/layer5io/layer5/assets/19821445/eba92416-d982-4c25-aad1-d43f5c88b4d9)
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
I would like to work on it

**Comment by sandramsc** [comment]
@Harsha-10  I have assigned this to you.
