### ISSUE TITLE
[Meshery Docs] Quick Start - typo

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5131]
### Description

Path: Meshery Docs - [Quick Start](https://docs.meshery.io/installation/quick-start)
This sentence has typo: "...Kubernetes API Server availabe in the control plane. "

### Expected Behavior

Fix spelling: "...Kubernetes API Server available in the control plane. "
### Screenshots

![imageedit_1_4153899375](https://github.com/layer5io/layer5/assets/19821445/bd2eca54-7bc0-41e1-ae8e-8eca050139e6)
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Harsha-10** [comment]
i can fix it on the go with previous issue

**Comment by Harsha-10** [comment]
i think this issue need to be opened in meshery docs @sandramsc

**Comment by sandramsc** [comment]
> i think this issue need to be opened in meshery docs @sandramsc



> i think this issue need to be opened in meshery docs @sandramsc

@Harsha-10 Good call,closing this, tagged you on issue in the correct repo, feel free to give it ago.

**Comment by Harsha-10** [comment]
Yeah sure

**Comment by sandramsc** [comment]
@Harsha-10 Good call,closing this, tagged you on issue in the correct repo, feel free to give it ago.

**Comment by sandramsc** [comment]
@Harsha-10 Good call,closing this, tagged you on issue in the correct repo, feel free to give it ago.

**Comment by sandramsc** [comment]
@Harsha-10 Good call, closing this, tagged you on issue in the correct repo, feel free to give it ago.
