### ISSUE TITLE
Logos are repeated on layer5.io website : Built-In Integrations section

### ISSUE THREAD

**Issue by varshashinde003** [layer5io/layer5#5136]
### Description
On the Integrations page below logos are repeated. 
1. Contour: 
2. Istio
3. Fluentd operator

### Expected Behavior
It should be displayed only once like other logos

### Screenshots
https://layer5.io/cloud-native-management/meshery/integrations
https://github.com/layer5io/layer5/assets/37326749/eb19a982-1585-438f-98b3-4be212f083eb

### Environment:
- Host OS: macOs
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ankushbhardwaj408** [comment]
// @ritiksaxena124 @sudhanshutech @abhijeetgauravm

**Comment by abhijeetgauravm** [comment]
Hey @varshashinde003 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by omesh-omg** [comment]
Can it be assigned to me @varshashinde003 @sandramsc @abhijeetgauravm  I would like to give it a try

**Comment by aakashmb** [comment]
I'm happy to work on this issue @varshashinde003

**Comment by abhijeetgauravm** [comment]
Hey @varshashinde003 Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by abhijeetgauravm** [comment]
Hey @varshashinde003  Let's discuss this on website call tomorrow at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Deepkha** [comment]
I'm happy to work on this issue @varshashinde003 , please assign it to me.

**Comment by kishore2k** [comment]
istio and istio base
contour and contour-operator
fluentd and fluentd operator

all these have same index.mdx files and therefore the integration icons gets repeated and the content is same after selection of an integration icon.

Should I remove one of the repeated integration or update content in any one of the repeated integrations.

**Comment by narasimha-1511** [comment]
i want to contribute ..

**Comment by Chay2203** [comment]
Please assign me this issue

**Comment by narasimha-1511** [comment]
Hey the issue no more exists i checked all of the integration u mentioned no logos are repeated they are the same integration example: Istio , Istio Operator, Istio Rate Limit Operator
