### ISSUE TITLE
[NG] Add the news items section with a news post

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#514]
**Current Behavior**
Currently, The layer5-ng site does not have a news section, So generate a news section which can cater to all the news posts. Also, add a sample news post for preview.

**Desired Behavior**
The news posts can be found [here](https://layer5.io/news).

---
[Optional] **Alternatives**
A possible solution can be replicating the blog section and using the same template as the blogs for the news items.

**Comment by anirudhjain75** [comment]
@Jashpatel1 I would like to try to solve this. Let me know if you're not working on this :)

**Comment by Jashpatel1** [comment]
@anirudhjain75 I guess as Lee stated you can start with moving blogs for now.

**Comment by Tanuj22** [comment]
Fixed in #722
