### ISSUE TITLE
In footer "Subscribe to out newsletter" doesn't position well at some screen size

### ISSUE THREAD

**Issue by Raj100679** [layer5io/layer5#5148]
### Description
In footer section, "Subscribe to our newsletter" input doesn't looks great at some screen sizes

### Screenshots
![Screenshot (128)](https://github.com/layer5io/layer5/assets/85561967/127ea61f-262b-4c56-be35-bc40a9b71a60)
![Screenshot (129)](https://github.com/layer5io/layer5/assets/85561967/60f2c95e-bdf3-4541-ad53-7f0246078195)

### Environment:
- Host OS: Windows
- Browser: Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Raj100679** [comment]
@leecalcote @abhijeetgauravm @vishalvivekm Can you check if it s valid issue?

**Comment by abhijeetgauravm** [comment]
> @leecalcote @abhijeetgauravm @vishalvivekm Can you check if it s valid issue?

Yeah @Raj100679 i can see the same sort of inconsistency on edge and chrome browser too.

**Comment by akashyeole** [comment]
hey can you please assign this to me @abhijeetgauravm ?

**Comment by Raj100679** [comment]
Hey @abhijeetgauravm I am already working on one issue at meshery, You can assign @akashyeole

**Comment by Nasirahamad88** [comment]
This is not a big problem. When the devices width(1060-1199)px.

**Comment by Nasirahamad88** [comment]
In this width range, apply a top margin of 100px to resolve this issue.@abhijeetgauravm

**Comment by Nasirahamad88** [comment]
I solved this problem can you check?

**Comment by abhijeetgauravm** [comment]
Hey @akashyeole, since there is already a PR open by @Nasirahamad88, could you please help in reviewing the PR and move it forward? Also, @Nasirahamad88, please refrain from creating direct PRs without getting assigned first.

**Comment by abhijeetgauravm** [comment]
@akashyeole do you want to address this?

**Comment by Jat1nSood** [comment]
Hi guys  @abhijeetgauravm  @, I saw the issue and I have one doubt that if "subscribe to our newsletter" and "Join our community"  are same? 

Like Here: 

<img width="1240" alt="image" src="https://github.com/layer5io/layer5/assets/117588226/17326d8a-0092-4e30-931f-6ecbb49b38ac">

<img width="517" alt="image" src="https://github.com/layer5io/layer5/assets/117588226/3aa9d9a3-60ae-4f2f-9a90-8d473f8ddd80">

If they are we can simply hide the latter for small screens..

**Comment by prabhjeevnijjar** [comment]
Hi @abhijeetgauravm I have solved the issue locally would like your review.

I'd like to pick this issue if @akashyeole has no problem with it.

Regards / Prabhjeev

**Comment by abhijeetgauravm** [comment]
Since there is no response from @akashyeole . Let it get assigned to you @prabhjeevnijjar

**Comment by abhijeetgauravm** [comment]
> Hi guys @abhijeetgauravm @, I saw the issue and I have one doubt that if "subscribe to our newsletter" and "Join our community" are same?
> 
> Like Here:
> 
> <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/117588226/290923455-17326d8a-0092-4e30-931f-6ecbb49b38ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3Mjc4ODEsIm5iZiI6MTcwMjcyNzU4MSwicGF0aCI6Ii8xMTc1ODgyMjYvMjkwOTIzNDU1LTE3MzI2ZDhhLTAwOTItNGUzMC05MzFmLTZlY2JiNDliMzhhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxMTUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDlhM2ZkMTU2ZDBkZTYxNzE2YzMxOWQ5NjEwMjYwMmYxMDdmNDMwZWJhYTgxMmFjYjJiZTg5ZDExZDRlZDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZEmRmFJ1RHjfDgjpAR4sXRUqQtvl4elMDVzFcGp9xbs"> <img alt="image" width="517" src="https://private-user-images.githubusercontent.com/117588226/290923506-3aa9d9a3-60ae-4f2f-9a90-8d473f8ddd80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3Mjc4ODEsIm5iZiI6MTcwMjcyNzU4MSwicGF0aCI6Ii8xMTc1ODgyMjYvMjkwOTIzNTA2LTNhYTlkOWEzLTYwYWUtNGYyZi05YTkwLThkNDczZjhkZGQ4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNlQxMTUzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2VmYThhZmFkMDg4NzNhZjc5YjljZDk3MzIxY2Q0MzYzN2ZmOWFmZDBiNDc0ZTZlMzllOGU2NDEyMjBjOWVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BYOslYdceceP5cPljzYlMwj4bv_8BhMiNwRFjQb2OYk">
> If they are we can simply hide the latter for small screens..

Hey @Jat1nSood Let's discuss this on website call on Monday at 6:30 PM IST / 7 AM Central time!

**Comment by prabhjeevnijjar** [comment]
@abhijeetgauravm When can we discuss on this ?

**Comment by abhijeetgauravm** [comment]
> @abhijeetgauravm When can we discuss on this ?

Let's discuss this on website call Monday at 6:30 PM IST / 7 AM Central time. Please add this as an agenda item in the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.lohhtewfwima).

**Comment by Ashparshp** [comment]
@abhijeetgauravm, @saurabh100ni The reported issue is resolved. Could you please review and close this duplicate?

Refer issue #3865
