### ISSUE TITLE
[Image Carousel] Investigate issues with aspect ratio

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5156]
### Current Behavior
The image carousel component that is used on integration pages ([like this one](https://layer5.io/cloud-native-management/meshery/integrations/aws-target-group-binding)) skews images as they are presented in the side navigator.

### Desired Behavior
Ideally, all images have their aspect ratio maintained at all times even if it means cropping an image or making it smaller to fit the given space.

### Screenshots / Mockups
<img width="1058" alt="Screenshot 2023-11-27 at 8 23 13 AM" src="https://github.com/layer5io/layer5/assets/7570704/89188bd3-9ad5-4dec-9036-3abb62a73061">

### Implementation
1. INvestigate and improve our documentation with respect to the ideal dimensions of the current image carousel's configuration. 
2. Document those image dimensions with respect to the side menu.
3. Explore solutions that make image sizing dynamic, like use of `object-fit`.

### Acceptance Tests
1. Documentation is updated.
2. Image aspect ratios are maintained.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vishalvivekm** [comment]
@leecalcote I'd like to investigate and fix the issue. Can it please be assigned to me ?

**Comment by ankushbhardwaj408** [comment]
![Screenshot 2023-11-27 203023](https://github.com/layer5io/layer5/assets/93874580/40c413e8-06a6-4e60-ad30-457f2b6af3a2)
@leecalcote i think either contain or cover can work as in both cases the aspect ratio of the image will not change

**Comment by leecalcote** [comment]
Thank you, gents. @ankushbhardwaj408, yes, I think that you're right that both are worth exploring.
