### ISSUE TITLE
[Community] Member Profile: Victoria Nduka

### ISSUE THREAD

**Issue by abhijeetgauravm** [layer5io/layer5#5160]
**Current Behavior**

@nwanduka  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @nwanduka  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @nwanduka
- Twitter: [nwa_nduka](https://twitter.com/nwa_nduka)
- LinkedIn:  [in/victorianduka](https://www.linkedin.com/in/victorianduka/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by nwanduka** [comment]
Here you go @abhijeetgauravm 

- Layer5 Cloud: https://meshery.layer5.io/user/3011fa51-84c4-444e-a072-ec1cad9885b0

- Link to profile picture: https://drive.google.com/file/d/1A9VQfsy_nNwBDORG-ZWETDcUzHKvEYHi/view?usp=sharing

- Bio: I’m an evolving creative. I go where my interests lead me: engineering, writing, and now design. Currently exploring design in open source. So far, so good.

**Comment by balagowda** [comment]
@abhijeetgauravm i would like to work on this

**Comment by abhijeetgauravm** [comment]
There u go @balagowda
