### ISSUE TITLE
[UI] Mockup and Implement the new whiteboarding page

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5161]
### Current Behavior
Whiteboarding is a new feature that was recently added to the playground and we don't have a dedicated page for it. 

### Desired Behavior
- Create a mockup of the new page for the whiteboarding feature and Implement it.
- Read about the whiteboarding feature [here](https://docs.layer5.io/meshmap/designer/whiteboarding/).
- Take inspiration from - https://www.eraser.io/use-case/wireframes

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by nwanduka** [comment]
Hi @ritiksaxena124, I’d like to work with you on this.

**Comment by ritiksaxena124** [comment]
Initial [mockup ](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=22241%3A3620&mode=design&t=dsoVsrxvJmCvnYuA-1)

**Comment by ritiksaxena124** [comment]
This issue is already complete 🙌
