### ISSUE TITLE
[News] Add new article "The Top 12 CNCF Sandbox Projects of 2021"

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5174]
We're in the news! Using the contributing instructions for [adding news](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#adding-news), please add the following article to the [Layer5 Newsroom](https://layer5.io/news).

Please create a new News entry for this article. Backdate the entry as appropriate.

**Article:**
- Title: The Top 12 CNCF Sandbox Projects of 2021
- Link: https://techgenix.com/the-top-12-cncf-sandbox-projects-of-2021/

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
Hello @leecalcote and @sudhanshutech, I'm interested in taking on this task. Could you kindly assign it to me? Appreciate your assistance! Thank you!

**Comment by abhijeetgauravm** [comment]
Thanks for volunteering gents. Assigning in chronological order. @Ashparshp Here you'll find many good-first and help-wanted issues:
https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

Feel free to check these out and comment to get assigned.

**Comment by cesartheroman** [comment]
@abhijeetgauravm thank you, I'll get started on this!
