### ISSUE TITLE
[NG] Migrate blogs from layer5 to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#519]
**Current Behavior**
The current layer5-ng has few sample blogs for reference.

**Desired Behavior**
Migrate blogs from [layer5](https://layer5.io/blog) to the blogs section under [layer5-ng](https://github.com/layer5io/layer5/tree/layer5-ng) using the filesystem-plugin.

---

**Comment by Jashpatel1** [comment]
@anirudhjain75 It would be great help if you would tackle this issue.

**Comment by chandrashritii** [comment]
@anirudhjain75 Thank you for taking an interest in the project 🎈 If you do decide to take this up, take a look at the #496 PR, to get a better idea of what needs to be done.

**Comment by Jashpatel1** [comment]
All the blocks have been added.
