### ISSUE TITLE
[UI] Implement the Use cases page

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5190]
### Current Behavior
We don't have a page on the layer5.io site where we list all the use cases of our product

### Desired Behavior
Implement the new page for use cases. 
- URL can be _layer5.io/use-cases_
- Reuse the already available component for creating the page

### Screenshots / Mockups
**Figma mockup** [link](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=22614%3A2202&mode=design&t=e0WXbkXFLIZht76u-1)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, what all content are you planning to include on this page? Can I get some ideas, to draft a prototype?

**Comment by balagowda** [comment]
@ritiksaxena124 i would like to work on this.

**Comment by saikiranpatil** [comment]
i would like to work on this

**Comment by ritiksaxena124** [comment]
Thank you @Akshun-01 @balagowda @saikiranpatil for your interest in this issue. We have a rule to assign issues on first come first serve basis but that doesn't stop you from contributing. We have many issues that need attention, you can grab anyone of those.
@Akshun-01 we already have a mockup for that page but we need a contributor to implement it.

**Comment by Akshun-01** [comment]
@ritiksaxena124, yeah sure! Would be my pleasure to help^^

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, where can i access the mockup from?

**Comment by ritiksaxena124** [comment]
Any update @Akshun-01?

**Comment by Akshun-01** [comment]
> Any update @Akshun-01?

I have started working on the page, I'll give an update by tomorrow!

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, here is the update for the use case page 

https://github.com/layer5io/layer5/assets/93793691/4502ec4a-07cd-4a22-a485-a9550a1a1e4a

**Comment by Akshun-01** [comment]
Hey, @ritiksaxena124 as discussed in yesterday's meeting, I think I should be using an already existing card.
Lee gave two for reference: 
- https://layer5.io/learn/service-mesh-workshops
-  https://layer5.io/community/events

Which one should we implement ( I find the workshop one to be better as we don't have any external link to follow up to)
Just an idea;
But I wanted to point out one major thing about the cards used in the workshops page, its "Read More" button is just annoying I think, It messes with the layout of the complete page and we already have individual pages for it so I think the open in window should be re-labeled as the new Read More and we should get rid of the "Read More" which opens it up in the same page.

So what's your say in this and how should we proceed with the issue further?

**Comment by Rexford74** [comment]
Hey @ritiksaxena124, please I'm curious. Is this not the same with the solutions page that was designed a while back? Do correct me if I'm wrong...

**Comment by ritiksaxena124** [comment]
> Hey, @ritiksaxena124 as discussed in yesterday's meeting, I think I should be using an already existing card. Lee gave two for reference:
> 
> * https://layer5.io/learn/service-mesh-workshops
> * https://layer5.io/community/events
> 
> Which one should we implement ( I find the workshop one to be better as we don't have any external link to follow up to) Just an idea; But I wanted to point out one major thing about the cards used in the workshops page, its "Read More" button is just annoying I think, It messes with the layout of the complete page and we already have individual pages for it so I think the open in window should be re-labeled as the new Read More and we should get rid of the "Read More" which opens it up in the same page.
> 
> So what's your say in this and how should we proceed with the issue further?

@Akshun-01, We can use the same card that we have on the workshops page and instead of relabelling the window icon keep it as it is, no need to change that and yes you are right we can hide the "Read More" which opens it up on the same page as the pages that we have are very long and will mess up the page layout (*only for the use cases page).



@Rexford74 this page is different from the Solutions page. How? This page is like a grid view you see on shopping sites where they show grids of cards for products, in our case we will be listing features and the solutions page is a dedicated page that talks about the pain points and their solution.

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, the data in workshop's card is being fed as follows:
![image](https://github.com/layer5io/layer5/assets/93793691/970357c5-01fb-4aaf-8d23-54ed934dae5b)

Could you please guide me, how should I implement this?

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, 
I reused the **Workshop Card** as was discussed earlier.
Actually, in its original implementation, it used GraphQL to retrieve data and its structure was pretty complicated.
So I made a local object matching the fields that were required. 
But the `publicURL` field is not accepting either URL or local image location, so I am struggling to make that work. 

Other than that, it is pretty much complete, but I had to remove most of the part( as it was related to the "learn more" button).
[UseCases Page Implentation](https://github.com/layer5io/layer5/assets/93793691/27a0d7f6-ca0c-45bc-842b-13ef89850321)

This is how it is looking (already mentioned about the image bug). I'll make a draft pr for you to see the code too!^^

**Comment by Akshun-01** [comment]
@ritiksaxena124 @vishalvivekm 
Hey, can anyone help with the image bug please!

**Comment by saurabh100ni** [comment]
@Akshun-01 would you please make and discuss a forum post about the help you need?

**Comment by Akshun-01** [comment]
Hey @saurabh100ni, really sorry for the late reply.
I created a post regarding the same. Thanks for this!

here is the link to it : https://discuss.layer5.io/t/help-needed-integrating-data-using-graphql-for-use-cases-page/4574

**Comment by vishalvivekm** [comment]
@Akshun-01 take a look at the PR,https://github.com/layer5io/layer5/pull/5235 I've added commit which dynamically fetches data using query.

**Comment by iArchitSharma** [comment]
Comment to get assigned

**Comment by psankhe28** [comment]
Hi @iArchitSharma , can I work on this issue?

**Comment by Ashparshp** [comment]
@psankhe28 Any update?

**Comment by hargunkaur286** [comment]
@iArchitSharma @Ashparshp Can I work on this issue if no one's working on it?

**Comment by Ashparshp** [comment]
@hargunkaur286,
As we haven't heard anything from @psankhe28, I am unassigning them from the issue and assigning it to you. Please go ahead.

**Comment by sudhanshutech** [comment]
@hargunkaur286 any luck?

**Comment by vishalvivekm** [comment]
Folks, I just wanted to point that quite a lot is already done here : https://github.com/layer5io/layer5/issues/5190
I've reopened the mentioned PR, and see what kept it from being merged given that the changes were reviewed a couple of times on the websites call and that we added the support for dynamically querying use-cases: https://github.com/layer5io/layer5/pull/5235/commits/6aa5971dbbf5bec12fddb75adc132c5d3e181b26

**Comment by hargunkaur286** [comment]
> @hargunkaur286 any luck?

almost done, will be raising pr today
