### ISSUE TITLE
[NG] Add Google Analytics Plugin

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#520]
**Desired Behavior**
Add and configure the [gatsby plugin for google analytics](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/?=ana) in [layer5-ng](https://github.com/layer5io/layer5/tree/layer5-ng). Related to #481 

---
This issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@dhruv0000 can you knock this one out?

**Comment by leecalcote** [comment]
For Layer5-NG:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-MDVP5FT6JY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-MDVP5FT6JY');
</script>
```

**Comment by chinmaym07** [comment]
@leecalcote I want to take this up.

**Comment by leecalcote** [comment]
Good, good. :thu
