### ISSUE TITLE
[NG] Add pagination plugin

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#521]
**Desired Behavior**
Add and configure [gatsby plugin for pagination](https://www.gatsbyjs.org/packages/gatsby-awesome-pagination/) in[ layer5-ng](https://github.com/layer5io/layer5/tree/layer5-ng). Related to #481

**Comment by codetheorem** [comment]
Assign this to me.

**Comment by Tanuj22** [comment]
@codetheorem Go ahead
