### ISSUE TITLE
[Community] Member Profile: Vihas Makwana

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5215]
**Current Behavior**

@VihasMakwana has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @VihasMakwana as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @VihasMakwana
- Twitter: 
- LinkedIn: [/in/makvihas/](https://www.linkedin.com/in/makvihas/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by saurabh100ni** [comment]
@VihasMakwana please share the following details:

- Bio: 
- Layer5 Cloud: 
- Link to profile picture:
- Twitter:

**Comment by IrfanSalim** [comment]
Hey, I would like to take this up

**Comment by saurabh100ni** [comment]
Go on @IrfanSalim 😎🚀

**Comment by VihasMakwana** [comment]
@IrfanSalim @saurabh100ni @leecalcote 

Bio: I love to work on cloud-native software. I can basically work with anything - Server, UI, Databases, Distributed Systems etc. Enjoying my journey.

Layer5 Cloud: https://meshery.layer5.io/user/5f974be3-8e9e-4ec0-89ae-01d130361df1
Link to profile picture: [link](https://lh3.googleusercontent.com/fife/AGXqzDkBvY_2t8KGtwAx1TEk_Xk43dM1RaKGGKqdPj2nTDvYpvvkoTeBtQTm5KBOuDvkqdCOqxTPUQUFf_CU-uc6D_xYiZtDhKFTcReI7Pf_nsd58L2i6FwzT_U4gMpj87hzzWn2E3wWjcl_MVc1Ozx-aErFQxayoki-tZpQg7aQ7ys0MlEXziJXhNA3oBds5EPn-Kgt1nHhKyF2mGrb1ZfVW-5Logak2k5trkiQpCI4L7nGpC_P3Tgdwgot9NiWdbZl4tj7mZsvFju-7FwIeMDZyvhAPWqTllBr8yCisPAA285T3brhRQV7lW1U68DwKeL-DakMoOEGOFI5d9jrkK8hj1LLutKc2b3wIizvZ03JlkQ0HQmPt-HrdxgJlov-glmu9k9toHzAPGHUNMnKp6JbgpE28CU6EJw_5qMNvBSKy6MCEyukbD2Oz5kr5TfTux9yrWiq3Xzs5CHHXpW-Mmu3uf_nsoC2D7KY3JfKg3ABqq6OEQB8qVD5OqSLjdSzV-rIFf9USKRoyxvXAmyba8wt_rTkKpuPutFHF64alQSTcF2WfMFV5boEXwvb1H_yP2BcS8uj3uQraiNAihERaurh5O7-cYPlUJaTNH2zp1BiBX6o4UFVssldtJIAvXXmcCqVQA7avmip5Z_sl93lEx1N2J0KPgnN2JwyVr6D4QNMfKz9HbokXgCpVPe5aivIpq3p4o-jP4fsF8adnlGBX28L8iRZAe8o0AJHJAYMBspEvcABLa_8VFqoknLziMeKrtudHbl5fevX68UT1ZgI2HQ6a3YP4HVMWgthKDq138SfxsNLBIsuNcL2RJEr0ZTOAFURqlZKIej74txbBnaTRVmHQCNAH89O6mJd2dwB3tO4Ie50mEQByZBqd0V4hU9I_qjcPQkrsLmBBF8bur049ioltocG7FJmY94wdhwE_JRJH5rhhqwHU6C51cJ4Fxf1Os4TDV8BtdcrBepToqtvefI1G_MsAXohMSeocJ2spbtdwioYlj6J5PsgdBYALBu_2sj_Y2wK5n003tyVsEutfQH-1-97lhMQwUrUCKknbMYsrsuYiLgyuK2vJ6BCGtsySuIrHYhSN-cZ4rVU1zT1qoSKeS7bUhGdKz5LuPy8H8LmhdVkrAwBU_aZErolRAebhrTWkMmGzmWN27YSrwrjktn1LHcqCVYr0strM6m9-iAiKaVe65tbHA1ummd_FllKG7czbWkvXjFyRRkrIgLH1PeORHBLfcg47sNmpJyv8G3_I3LUra05wpi-xOVlemdGc9J-eO4zael5nqgZggTSPl-B4L5uVIlj991Q9OogMxfcbgmB4U7G2v2dzSHN7kAA2U6Y8FriOVhIQp2Hl4hs-lJ8OTlRZ-Lvtjpqo1SCmEKuAHL-SZ1pX-E-5CKEOHlFpqFooZFhRDGszMC_O83a_eLADfjK6bBJ8kaWrQJZ0-jIehEXZCYo9xE_gPYBU7fSVj18YySd4EjZXeGvqg3ynXgrIGLUhM08VyiXASRhEVO6Zj49BD8GE5uywuVcUSGFb7eajR2Y-DgKdQ7gmcXVkljfjcXRUJsV43OzQqK3oRsF=w1366-h608)
Twitter: [@VihasM](https://twitter.com/VihasM)

**Comment by IrfanSalim** [comment]
Hi @VihasMakwana 
The profile picture link is not accessible, permission needed.

**Comment by VihasMakwana** [comment]
@IrfanSalim https://drive.google.com/file/d/1RbFNEO_zdl5bzr1UlA5Q27YRP3ZL2ecq/view?usp=drive_link
does this work?

**Comment by IrfanSalim** [comment]
Yes, that works, thanks.
