### ISSUE TITLE
Brands Section gets trimmed and rendered vertically during page load . 

### ISSUE THREAD

**Issue by aabidsofi19** [layer5io/layer5#5216]
### Description

The brands section ( which a slider ) gets rendered vertically and trimmed during the initial render / page load , which cause a glitch and is bad as it cause a Layout Shift .
![image](https://github.com/layer5io/layer5/assets/65964225/f975ba54-1107-437e-ad5e-fc1ff50597b6)
 

### Expected Behavior

This should be always rendered horizontally , we might render it statically till the javascript loads for it . 
![image](https://github.com/layer5io/layer5/assets/65964225/2a7f7283-8b05-40b3-83a5-0662add84ef6)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by prabhjeevnijjar** [comment]
@aabidsofi19 Please assign this issue for me. I'll work on it

**Comment by abhijeetgauravm** [comment]
There u go @prabhjeevnijjar

**Comment by prabhjeevnijjar** [comment]
The PR for this issue was merged @abhijeetgauravm

**Comment by abhijeetgauravm** [comment]
Yeah thanks for the prompt fix @prabhjeevnijjar ! So closing this as completed by #5222
