### ISSUE TITLE
[NG] Add sitemap plugin

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#522]
**Desired Behavior**
Add and configure the [gatsby plugin for sitemap](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/?=sitemap) in [layer5-ng](https://github.com/layer5io/layer5/tree/layer5-ng). Related to #481

**Comment by leecalcote** [comment]
Example of a sitemap from the current site - https://layer5.io/sitemap.xml

**Comment by Tanuj22** [comment]
Fixed in #630
