### ISSUE TITLE
[Bug] Overflow issues on Layer5 website

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5231]
### Description
Because of occasional Overflow issues, the Navbar isn't of complete width which needs to be fixed on [Layer5.io](https://layer5.io/)

### Screenshots
![image](https://github.com/layer5io/layer5/assets/101441772/f150be9f-5f75-4745-8d09-881bf37eff15)

The width on which it is tested in chrome:
![image](https://github.com/layer5io/layer5/assets/101441772/3a1b2dbc-39b4-4835-8553-da3a5076e566)

Width
### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by prabhjeevnijjar** [comment]
Hi I'd like to work on this issue @saurabh100ni saurabh100ni

**Comment by saurabh100ni** [comment]
Go for it @prabhjeevnijjar 😎🚀

**Comment by prabhjeevnijjar** [comment]
Hi @saurabh100ni 
May I know
What browser are you using
Screen res of you machine

**Comment by saurabh100ni** [comment]
Hey @prabhjeevnijjar I have updated the issue Description.

**Comment by prabhjeevnijjar** [comment]
Hey @saurabh100ni I think we can open this issue for more contributors
If someone get a better solution.

**Comment by saurabh100ni** [comment]
Thank you for sending the word @prabhjeevnijjar.

**Comment by anshitmishra** [comment]
@saurabh100ni I would love to work on this. Please assign it to me.

**Comment by saurabh100ni** [comment]
Good deal @anshitmishra 😎🚀
