### ISSUE TITLE
[BUG] Options not visible in roles dropdown list on meshmap page

### ISSUE THREAD

**Issue by akshat-kaushik** [layer5io/layer5#5232]
### Description
https://layer5.io/cloud-native-management/meshmap
Here at "join the beta" form "select role" options are not visible. 

### Expected Behavior
Text color should be changed

### Screenshots
![Screenshot 2023-12-26 112840](https://github.com/layer5io/layer5/assets/93491696/3c2f5f1b-7984-457d-a8da-0fc7d651e7e8)

### Environment:
- Host OS: windoes
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by kishore2k** [comment]
can i take on this issue ?

**Comment by surajvast1** [comment]
I believe I can handle this effectively. Could you please assign me the issue? I appreciate your consideration.

**Comment by leecalcote** [comment]
@surajvast1, please do. Make sure to note the current attempt and it's feedback - https://github.com/layer5io/layer5/pull/5246

**Comment by surajvast1** [comment]
"In my assessment, the implemented part appears correct. Adding a slight amount of padding would enhance user experience, making it easier for them to select the proper text."

**Comment by srujan0404** [comment]
@leecalcote I see no development in this, Can I please take on this

**Comment by leecalcote** [comment]
@srujan0404 I'm not sure that this bug remains. Given the criticality of this form and it's high amount of use, we couldn't wait longer and so some time ago, I made some updates. Here's what we've got currently:

<img width="1238" alt="Screenshot 2024-03-01 at 12 12 57 AM" src="https://github.com/layer5io/layer5/assets/7570704/cd60fc59-d742-4971-9919-c92609e592b8">


Will you have a look? Do you see anything different? If not, let's go ahead and close this one and crack open some other new items (there are many).

**Comment by srujan0404** [comment]
![Screenshot 2024-03-01 094505](https://github.com/layer5io/layer5/assets/140909375/86b1981b-e32c-431e-937e-2b69cfe23838)
@leecalcote But I still find this issue in my environment

**Comment by leecalcote** [comment]
Thanks for confirming. Let’s fix. 🗂️👍

**Comment by sudhanshutech** [comment]
@srujan0404 completed?
