### ISSUE TITLE
Duplicate meta descriptions on member profiles [SEO]

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#5237]
### Description
In all the member profiles **layer5.io** we have same meta description  **(not a good thing for SEO)**
You can access all member profiles here: https://layer5.io/community/members

![image](https://github.com/layer5io/layer5/assets/74408634/8d4ebd71-2746-4755-ba3d-a492871d8e56)

### Expected Behavior
Add a unique description for all the member profile pages

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AjaxAueleke** [comment]
@iArchitSharma can I work on this?

**Comment by iArchitSharma** [comment]
sure @AjaxAueleke
