### ISSUE TITLE
Add new issue template for Layer5-ng contributions

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#524]
**Current Behavior**
The current issue templates assume work will be done on the `master` branch.

**Desired Behavior**
This repo needs an issue template that provides `layer5-ng` specific instructions.

e.g. 

```
---
**Resources**
This issue pertains to the next-generation of the layer5.io website. The site uses Gatsby and Strapi.
- See [`layer5-ng` contributing instructions](link here)

```

**Comment by Ruth-ikegah** [comment]
I am a little bit confused.  Does the desired behaviour mean configuring the templates to show the example you gave @leecalcote

**Comment by leecalcote** [comment]
Here's the layer5-ng contributing.md - https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md

**Comment by leecalcote** [comment]
@Ruth-ikegah Here's a link to the Layer5 Websites meeting minutes - https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#
