### ISSUE TITLE
"Select your role" dropdown not visible in dark mode

### ISSUE THREAD

**Issue by prabhjeevnijjar** [layer5io/layer5#5242]
### Description

LINK: https://layer5.io/cloud-native-management/meshmap

Enable dark mode and go to the form in Signup for
MeshMap Beta

Here dropdown options are not visible.

They only become visbible when we hover over each item
Note: It works fine on macos

### Expected Behavior

Here dropdown should be visible

### Screenshots

![image](https://github.com/layer5io/layer5/assets/30125794/294e36bd-0094-4205-8309-36bfea9e0d2e)

### Environment:
- Host OS: Windows 10 pro
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by prabhjeevnijjar** [comment]
@saurabh100ni  I would also like to work on this if you find this issue valid.

**Comment by saurabh100ni** [comment]
go for it @prabhjeevnijjar 🚀

**Comment by leecalcote** [comment]
@prabhjeevnijjar it would be great if you took a crack at this. You did some fine work on your last PR.
