### ISSUE TITLE
[README] Update Layer5-ng README to be a copy of the Layer5 README

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#525]
**Description**
The [README in the `layer5-ng` branch](https://github.com/layer5io/layer5/blob/layer5-ng/README.md) should be the same as the [README in the `master` branch](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).

**Comment by Anita-ihuman** [comment]
i  am on it

**Comment by leecalcote** [comment]
Thank you, @Anita-ihuman. 👍 Heads-up, @dmoini has opened a PR on this - #526

**Comment by Tanuj22** [comment]
Fixed in #526
