### ISSUE TITLE
Make page content dynamic

### ISSUE THREAD

**Issue by prabhjeevnijjar** [layer5io/layer5#5271]
### Desired Situation

Update the “diagram tool” and the “orchestration tool” pages to use a graphql query to dynamically list the “You may also like” section at the bottom of the page. This section should be dynamically populated, not statically.
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by prabhjeevnijjar** [comment]
@leecalcote Please assign 

Also where should i query this data from ?

**Comment by leecalcote** [comment]
@prabhjeevnijjar from the collection of pages. Add metadata to the pages, if needed.

**Comment by prabhjeevnijjar** [comment]
@leecalcote @iArchitSharma  Just picked the task,
Can you share the URL on the above pages

**Comment by vishalvivekm** [comment]
> @leecalcote @iArchitSharma Just picked the task, Can you share the URL on the above pages

Hi @prabhjeevnijjar, here's the link of the pages:
https://layer5.io/cloud-native-management/generate-aws-architecture-diagram
https://layer5.io/cloud-native-management/generate-gcp-architecture-diagram
https://layer5.io/cloud-native-management/generate-kubernetes-architecture-diagram

**Comment by prabhjeevnijjar** [comment]
Thanks @vishalvivekm

**Comment by vishalvivekm** [comment]
following no progress so far.
I'ma take over this one issue. 
self-assigning
