### ISSUE TITLE
[Community] Member Profile: Ahmed Jamil

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#5292]
**Current Behavior**

@AjaxAueleke has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @AjaxAueleke as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @AjaxAueleke
- Twitter: 
- LinkedIn: [/in/muhammad-ahmed-97578b1ab/](https://www.linkedin.com/in/muhammad-ahmed-97578b1ab/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by srujan0404** [comment]
Please assign this issue to me, I would like to work on it @iArchitSharma

**Comment by surajvast1** [comment]
Please assign me this @iArchitSharma I would love to work on this  .Thanks

**Comment by AjaxAueleke** [comment]
@iArchitSharma here are the missing details:
twitter: https://twitter.com/mo_ahmed_jamil
bio: Hi! I'm Ahmed Jamil, an enthusiastic software engineer and undergraduate student diving deep into the world of open source and cloud-native technologies.
link to profile picture: https://avatars.githubusercontent.com/u/62912869?v=4

**Comment by srujan0404** [comment]
@AjaxAueleke @iArchitSharma I have not been provided with the link of the Layer5 Cloud

**Comment by iArchitSharma** [comment]
@AjaxAueleke link to you layer5 cloud profile

**Comment by AjaxAueleke** [comment]
@iArchitSharma @srujan0404 sorry I forgot to include that:
layer 5 profile: https://meshery.layer5.io/user/93770230-940d-43eb-bd97-0a40bdd4ec5d
Location: Karachi, Pakistan
