### ISSUE TITLE
[Community] Member Profile: Ripul Handoo

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#5293]
**Current Behavior**

@RipulHandoo has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @RipulHandoo as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @RipulHandoo
- Twitter: 
- LinkedIn: [/in/ripul-handoo/](https://www.linkedin.com/in/ripul-handoo/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by iArchitSharma** [comment]
@RipulHandoo please share the following details:

- Bio: 
- Layer5 Cloud: 
- Link to profile picture:
- Twitter:

**Comment by Vidip-Ghosh** [comment]
Is this issue open for everyone OR only the mentioned person can work?

**Comment by RipulHandoo** [comment]
> @RipulHandoo please share the following details:
> 
> * Bio: Hello, I'm Ripul Handoo, currently pursuing my B.Tech in Computer Science and Engineering at VIT, Pune. I am passionate about learning new technologies and actively contribute to open-source projects.
> * Layer5 Cloud: https://meshery.layer5.io/user/a7b465ad-21eb-4f3f-9c84-56de76aebe62
> * Link to profile picture: https://photos.app.goo.gl/yaH5MzBG8CF4boPR6
> * Twitter: https://twitter.com/ripul_handoo

**Comment by iArchitSharma** [comment]
yes @Vidip-Ghosh, its open would you like to work on it?

**Comment by srujan0404** [comment]
please assign this issue to me @iArchitSharma

**Comment by Raj100679** [comment]
@iArchitSharma I would like to work on this

**Comment by surajvast1** [comment]
Please assign me this @iArchitSharma I would love to work on this  .Thanks
