### ISSUE TITLE
Inappropriate Display of 'Get Started' Button for Users with Layer5io Account

### ISSUE THREAD

**Issue by captain-Akshay** [layer5io/layer5#5295]
### Description

The [site](https://layer5.io/) currently displays a signup button regardless of whether the user has a cookie indicating prior signup. This behavior is not consistent with user expectations and may lead to confusion.

### Expected Behavior

After a user has signed up and a relevant cookie is present, the 'Get Started' button should not be displayed to enhance a streamlined and personalized user experience.

### Possible Solution:
Implement logic to check for the presence of a signup-related cookie. If the cookie is present, do not display the signup button. Ensure this check is performed consistently across page loads.

### Screenshots

(This is even i have logged in Layer5io)

![image](https://github.com/layer5io/layer5/assets/59491379/5b8aa208-e138-44c4-a9d0-8773ff357d3a)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by captain-Akshay** [comment]
@narasimha-1511 sorry I forgot to assign it to me but if you can fix it then please raise a PR for it and i will make sure that the it merged!

**Comment by JyothiSwaroopReddy07** [comment]
We cant access the cookies of other website from correct website. As "Get Started" is in layer5.io and we are registering on meshery.layer5.io . Access these cookie is not possible. I have tried it.

**Comment by leecalcote** [comment]
@Shabab007 @prajjwalyd FYI

**Comment by leecalcote** [comment]
I'll have to try this out...
