### ISSUE TITLE
Duplicate List Category Mesh

### ISSUE THREAD

**Issue by narasimha-1511** [layer5io/layer5#5298]
### Description

In the DropDown of Technology i found duplicates you can see it in below video 
### Expected Behavior

expected that there should be unique elements present
### Screenshots

[Screencast from 2024-01-18 17-37-56.webm](https://github.com/layer5io/layer5/assets/129654598/9179ed36-447e-4896-9287-5d4f2c3fb747)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
I want to work on this issue..

**Comment by JyothiSwaroopReddy07** [comment]
hi, I have fixed the issue

**Comment by narasimha-1511** [comment]
@JyothiSwaroopReddy07 Great!
