### ISSUE TITLE
Add regpatrol to tools section landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#53]
Hi @suryadu, will you consider adding a listing for https://ibmcloud-perf.istio.io/regpatrol/ to the [service mesh landscape](https://layer5.io/landscape/) under the [Tools](https://github.com/layer5io/layer5/blob/master/_includes/service-mesh-tools.html) section?

**Comment by leecalcote** [comment]
@jnativio, you're help here would be most appreciated --> https://github.com/layer5io/layer5/blob/master/_includes/service-mesh-tools.html

**Comment by jijillery** [comment]
Hi @suryadu, I’m working to ensure all relevant projects are represented in the [service mesh landscape](https://layer5.io/landscape). We would love to have regpatrol included. Will you consider updating the landscape with a quick pull request? 

We do our best to ensure that projects and their capabilities are accurately represented, and so, we ask for project representatives to submit these updates directly. 

Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for making your edits.

Thank you!
@jijillery
