### ISSUE TITLE
Fix stretching of some brand logos

### ISSUE THREAD

**Issue by prabhjeevnijjar** [layer5io/layer5#5308]
### Description

Visit the page:
https://layer5.io/cloud-native-management/meshery/integrations

Notice some brand logos are stretched this needs fixing
<img width="657" alt="Screenshot 2024-01-20 at 8 47 31 PM" src="https://github.com/layer5io/layer5/assets/30125794/03ab4e18-f1d9-4e96-979e-3702b54b95a2">

### Environment:
- Host OS: iOS/Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by prabhjeevnijjar** [comment]
Go ahead 🙌

**Comment by Abraham599** [comment]
![image](https://github.com/layer5io/layer5/assets/76934781/6aad182f-1e4e-4719-9e68-73fa6ed1704d)

@prabhjeevnijjar please have a look at this fix, if it's enough then I will PR.

**Comment by narasimha-1511** [comment]
Hey @leecalcote it's been many days there is no response from @Abraham599 .
i want to work on this issue..

**Comment by leecalcote** [comment]
All, this has been an issue for nearly four months. I took a few minutes to fix it just now as it is prominent on our landing page.
