### ISSUE TITLE
[Integration logo AMD] - Logo is out of proportion

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5309]
Link: [270+ Built-In Integrations](https://layer5.io/)
Section under "270+ Built-In Integrations"

Currently, the AMD integration logo looks out of proportion. 

### Desired state

Adjust the proportions of the logo to accurately reflect the original design.

#### Before

![amd2](https://github.com/layer5io/layer5/assets/19821445/47673d46-680f-4143-adc4-786f807e9017)

#### After

![amdaft](https://github.com/layer5io/layer5/assets/19821445/63186b24-03c5-4e2c-b339-9bb64b26f800)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sandramsc** [comment]
CC: @iArchitSharma

**Comment by prabhjeevnijjar** [comment]
Hey Sandra, I just opened the same issue https://github.com/layer5io/layer5/issues/5308 a couple hours earlier

**Comment by nikhilkalburgi** [comment]
I added object-fit: contain and this is the result:
![image](https://github.com/layer5io/layer5/assets/70331875/a7ae29f7-cf45-4097-acaa-e6e6440a2a45)

If this is fine then I can raise a PR

**Comment by nikhilkalburgi** [comment]
Also check this possible solution:
```
  alt={item.frontmatter.title}
- height = {70}
- width = {70}
+ height={(item.frontmatter.title == 'AMD GPU')? 'auto' : '70'}
+ width={(item.frontmatter.title == 'AMD GPU')? '95' : '70'}
  style={{
  filter:
```
Result:
![image](https://github.com/layer5io/layer5/assets/70331875/8a5a95a9-0758-4b29-b311-fc0124ea8b10)

Some icons are very small and also can be improved with above logic:
![image](https://github.com/layer5io/layer5/assets/70331875/77320c27-297d-4ae6-89ed-bc6eb3b2eb32)

**Comment by sandramsc** [comment]
> Hey Sandra, I just opened the same issue #5308 a couple hours earlier

Hi @prabhjeevnijjar Thank you for this, closing issue as duplicate.
