### ISSUE TITLE
The Integration Titles Breaks unnecessarily on hover

### ISSUE THREAD

**Issue by nikhilkalburgi** [layer5io/layer5#5311]
### Description
Some Titles break to new lines on hover that reducing the responsiveness of the site

### Expected Behavior
The break should be applied to text beforehand and should not break dynamically on hover

### Screenshots

https://github.com/layer5io/layer5/assets/70331875/aca19f1e-5b1f-42f7-869a-67ea8362648f

### Environment:
- Host OS: windows
- Browser: All

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by nikhilkalburgi** [comment]
If you agree then **Assign this issue to me**

**Comment by Ashparshp** [comment]
@ritiksaxena124 @saurabh100ni Could you kindly review and consider adjusting the transition speed to make it a bit slower? This modification aims to enhance the overall user experience by ensuring a smoother and more aesthetically pleasing transition effect on hover.

**Comment by Ashparshp** [comment]
@saurabh100ni Is there a plan for @nikhilkalburgi to address this issue? If not, I'm willing to take work on resolving it.

**Comment by saurabh100ni** [comment]
Thanks for the heads-up @Ashparshp.
@nikhilkalburgi are you still up for the issue? If not we can assign this issue to @Ashparshp.

**Comment by nikhilkalburgi** [comment]
Hi @saurabh100ni , @Ashparshp,

I have raised a PR on this topic . Let me know if anything more needs to be done

**Comment by Ashparshp** [comment]
It's working fine now. Thanks @nikhilkalburgi.
