### ISSUE TITLE
[Bug] Name of the Maintainers isn't visible in dark mode.

### ISSUE THREAD

**Issue by saurabh100ni** [layer5io/layer5#5314]
### Description
In _Meet The Maintainer_ Blog series, the maintainer's name is not visible in dark mode.

### Expected Behavior
Rendering needs to be fixed.

### Screenshots
Example used for screenshots : [here](https://layer5.io/blog/community/meet-the-maintainer-michael-gfeller)
![image](https://github.com/layer5io/layer5/assets/101441772/02a7616b-3018-41a7-a6ba-0bca53af6d29)
![image](https://github.com/layer5io/layer5/assets/101441772/44866694-9a46-4254-946e-50e311a71ea9)

### Environment:
- Host OS: Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by srujan0404** [comment]
hi @saurabh100ni i would like to solve this issue, Please assign this to me

**Comment by saurabh100ni** [comment]
Hey @srujan0404 for the fair selection, let's get this issue assigned to @Abraham599. I'm sure you can help with other issues.
