### ISSUE TITLE
[Figma] Sitemap: Annotate each page with Call to Action (CTA)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5336]
### Current Behavior
We’re in need of annotating this sitemap with pages that have a Call to Action (CTA) section and pages that don’t - https://www.figma.com/file/NhIOpCs8nJdNluFGgCFtEb/Layer5.io-Sitemap?type=whiteboard&node-id=0-1&t=lR6dIEbCJmcl5Zuj-0

### Desired Situation

<img width="909" alt="Screenshot 2024-01-23 at 12 33 26 PM" src="https://github.com/layer5io/layer5/assets/7570704/583a52b3-260c-476d-8d6f-5ffbe392e288">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ritiksaxena124** [comment]
@nwanduka thank you victoria for completing this task
