### ISSUE TITLE
[UI] Add animations to a section

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5344]
### Current Behavior
When the site loads we show all the content at once and there are not many animations for different components/sections of the site pages.

### Desired Behavior
Add animations to the section shown below screenshot [present on the homepage of layer5.io]. 
See the [site1](https://www.rejouice.com/) or [site2](https://brainboard.co/) for inspiration on what animation we can use.

![image](https://github.com/layer5io/layer5/assets/51539117/bb264a27-72d3-49b4-aa79-4c94df33681a)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
Hey @ritiksaxena124 , I'm interested in working on the UI enhancement issue. Could you let me know if it's a high-priority task, and if not, I'd love to take my time to work on it. Additionally, could you provide more details or specific requirements for the animations you have in mind?

**Comment by ritiksaxena124** [comment]
@Ashparshp if you can show some progress in the next website's meeting then sure go ahead

**Comment by Ashparshp** [comment]
@ritiksaxena124 Perfect! Thanks a lot!

**Comment by Ashparshp** [comment]
I'm currently swamped with various college projects, assignments, exams, and placement preparation. As I won't be active for a while, I'm making this issue open for all. If anyone is interested.

**Comment by JayKay24** [comment]
Hi. I'd like to work on this.

**Comment by hargunkaur286** [comment]
@ritiksaxena124 Can I work on this issue?

**Comment by Ashparshp** [comment]
Since @JayKay24 hasn't responded, I'll ask @harnoorkaur if she is willing to work on this task. Is that okay?

**Comment by hargunkaur286** [comment]
@Ashparshp if you meant to mention me, can you please assign it to me?

**Comment by sudhanshutech** [comment]
@hargunkaur286 any luck?
