### ISSUE TITLE
Options to select Roles become invisible in Dark Mode

### ISSUE THREAD

**Issue by myselfprincee** [layer5io/layer5#5358]
### Description
There's a issue which makes the options invisible as shown in the images. This is a beginner-friendly problem, and I'm eager to address it.

### Expected Behavior
Options should be visible and accessible. Please see the screenshot below for reference.

<div style="display: flex; justify-content: center;">
    <p float="left">
        <img src="https://github.com/layer5io/layer5/assets/114233864/1cfbecef-7c73-44ce-bb7e-c01b59a2c8eb" alt="Image 1" width="300"/>
OR
        <img src="https://github.com/layer5io/layer5/assets/114233864/4495f81d-08b1-4dad-8d07-5f7dce85f622" alt="Image 2" width="300"/>
    </p>
</div>

### Screenshot of the issue
<img src="https://github.com/layer5io/layer5/assets/114233864/cfa05e1a-c71c-4229-a881-2daf5c0e6ad3" alt="Image 1" width="300"/>

### Environment:
- Host OS: Windows 11 Pro Insider Preview Version. 22H2
- Browser: Tested on Google Chrome, Microsoft Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by myselfprincee** [comment]
Please assign me the issue I am eager to solve it.

**Comment by narasimha-1511** [comment]
i also want to workon this issue?

**Comment by Ashparshp** [comment]
@myselfprincee Please try to mention how to reproduce the issue so that other can check if it's an issue.

**Comment by saurabh100ni** [comment]
this issue is fixed by the PR #5246. which is why I am closing this issue

**Comment by myselfprincee** [comment]
> this issue is fixed by the PR #5246. which is why I am closing this issue

No issues
