### ISSUE TITLE
Replace Meshery Operator image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5375]
### Current Behavior

<img width="1192" alt="Screenshot 2024-01-18 at 11 56 39 AM" src="https://github.com/layer5io/layer5/assets/7570704/deca840f-19c9-47c2-8dc1-a72d65422628">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ritiksaxena124** [comment]
This issue is already fixed @leecalcote.
![image](https://github.com/layer5io/layer5/assets/51539117/1d8c3055-0f00-42d9-a13c-25c662495558)

**Comment by leecalcote** [comment]
Oh, thank you.
