### ISSUE TITLE
Update the German and Indian flag in the current Layer5 site

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#538]
**Description**
In the current Layer5 site, German(3rd) and Indian(8th) flags are inappropriate. Replace them with proper flags.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/43696490/88757316-55e1be00-d183-11ea-925f-df9fabd3eea2.JPG)

 **To Reproduce**
1. Go to [https://layer5.io/]('https://layer5.io/')
2. Move to the languages section in footer.
3. See error.

**Comment by kushthedude** [comment]
@Jashpatel1 Is that Indian flag? I don't see Hindi in it.

**Comment by Jashpatel1** [comment]
> @Jashpatel1 Is that Indian flag? I don't see Hindi in it.

Its Tamil.

**Comment by Neilblaze** [comment]
@Jashpatel1 assigm me this, also keeping the limelight upon the above, do I have the permission to add external flag svg's for replacing the existing ones?

**Comment by Neilblaze** [comment]
Also, for svg's, can I import them from [icons8](https://icons8.com/) or Flaticon(https://www.flaticon.com/) ?

**Comment by Neilblaze** [comment]
@Jashpatel1 please review the PR. I'll fix the DCO error tomorrow which I am getting.

**Comment by Neilblaze** [comment]
@Jashpatel1 please review PR #542
