### ISSUE TITLE
[ MeshMap UI ] Floating Component List Bug in Empty MeshMap Canvas 

### ISSUE THREAD

**Issue by yash37158** [layer5io/layer5#5408]
### Description

Encountered an unexpected UI behavior in MeshMap while working with an empty canvas. When double-clicked action is performed anywhere on the empty canvas, a list of components starts floating on the screen, obscuring the workspace and disrupting the workflow.

Steps to Reproduce:

* Open a new project in MeshMap.
* Ensure the canvas is completely empty, with no components or elements present.
* Double-click anywhere on the empty canvas.

### Expected Behavior

No action should occur upon double-clicking an empty canvas.

### Screenshots

<img width="500" alt="Screenshot 2024-02-16 at 1 30 59 AM" src="https://github.com/layer5io/layer5/assets/68152307/01b0ed75-a248-4c0b-9f34-512600ba81df">

### Environment:
- Host OS: Mac
- Browser: chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
thank you, @yash37158 💯

**Comment by yash37158** [comment]
No sweat @leecalcote

**Comment by captain-Akshay** [comment]
@yash37158 can you please test it once again because it's not happening for me now.
I m on firefox ubuntu

**Comment by ritiksaxena124** [comment]
@captain-Akshay confirmed it's fixed.
