### ISSUE TITLE
Links not working in "Adventures of Five and Friends" section

### ISSUE THREAD

**Issue by izuca** [layer5io/layer5#5416]
### Description
I am reporting an issue with the links in the "Adventures of Five and Friends" section on https://layer5.io/community/adventures-of-five-and-friends. When I click on any of the links, nothing happens. 

### Expected Behavior
The "Adventures of Five and Friend" section's links should open the corresponding PDF documents, redirect to another page or show any error messages.

### Screenshots
![ScreenshotFiveAndFriendsLinksBug](https://github.com/layer5io/layer5/assets/49051133/b14eadd3-cc7f-4090-ab90-a389011ce1e1)

### Environment:
- Host OS: Linux Mint Una and Android 14
- Browser: Chrome and Edge

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by izuca** [comment]
If possible, I would like to work on this bug

**Comment by vishalvivekm** [comment]
> If possible, I would like to work on this bug

Hi @izuca 
Thanks for opening up the issue.

The first chapter `Meet Five` is published and can be opened on clicking the card, other chapters however, are still work in progress and will be published soon.

// @ritiksaxena124
