### ISSUE TITLE
`Publish your own design` should redirect to more meaningful page

### ISSUE THREAD

**Issue by ShivamCoder23** [layer5io/layer5#5423]
### Current Behavior

The current place where the Publish button redirects doesn't seems helping in https://layer5.io/cloud-native-management/catalog
![image](https://github.com/layer5io/layer5/assets/160073697/2f9c7599-3096-4c34-94af-6973b9556cee)

### Desired Behavior

It should either redirect to meshery docs or layer5 docs

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
@ShivamCoder23 Please ensure that each issue not only addresses the problem but also includes clear paths and navigation instructions for others to understand and check.

**Comment by ayushsinha25** [comment]
@vishalvivekm can you assign me this issue?

**Comment by vishalvivekm** [comment]
> @vishalvivekm can you assign me this issue?

Sure, go ahead @ayushsinha25

**Comment by Ashparshp** [comment]
Any updates, @ayushsinha25?

**Comment by Muhammed-Moinuddin** [comment]
I would like to work on it. @sudhanshutech
