### ISSUE TITLE
Dropdown content is not visible during Dark-Mode.

### ISSUE THREAD

**Issue by Chay2203** [layer5io/layer5#5428]
### Description

https://layer5.io/cloud-native-management/meshmap

While joining the Beta Programme, there is a dropdown to select "which role best identifies you", the content in the dropdown menu is not visible when dark mode is used.
 
### Expected Behavior
The dropdown menu does not show content when dark mode is selected. The font must be changed accordingly for easy visibility of roles in the dropdown menu.

### Screenshots
![Screenshot from 2024-03-01 09-30-34](https://github.com/layer5io/layer5/assets/69190057/a1c7e7d7-d526-46b2-b8c2-837ffb79b0f2)
![Screenshot from 2024-03-01 09-30-25](https://github.com/layer5io/layer5/assets/69190057/89db9ad7-2cef-41e8-8cdd-026aaf73f03b)

### Environment:
- Host OS: Linux, Windows
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Chay2203** [comment]
@saurabh100ni I want to work on this issue, can you please assign me to this?

**Comment by srujan0404** [comment]
![image](https://github.com/layer5io/layer5/assets/140909375/cdba1c7c-0cff-491e-a406-d7fc76025f93)
@saurabh100ni I too find the issue in my end, btw my OS is windows

**Comment by narasimha-1511** [comment]
@Chay2203  this issue is already created , https://github.com/layer5io/layer5/issues/5232 
so try to contribute there
