### ISSUE TITLE
Rectify the alignment of the image of the blog page

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#543]
**Description**
In the [blog](https://deploy-preview-542--layer5io.netlify.app/blog/google-summer-of-code-2020-service-mesh-performance-with-envoy-nighthawk) page when kept is in responsive(mobile) view, the GSOC image gets shifted towards left. This needs to be fixed.

**Screenshots**
![Layer5- Blog imgscrt](https://user-images.githubusercontent.com/48355572/88918366-f2d94f80-d286-11ea-93fc-c1abac0c2dfa.png)

**Enviroment:**
 - Browser: Chrome, Firefox, Opera
 - Device: Laptop, Mobile(Android)

---
[Optional] **To Reproduce**
1. Go to [blog](https://deploy-preview-542--layer5io.netlify.app/blog/google-summer-of-code-2020-service-mesh-performance-with-envoy-nighthawk)
2. Scroll down a bit

**Comment by leecalcote** [comment]
Good eye, @Neilblaze
