### ISSUE TITLE
Dark mode issue in dropdown of `meshmap` access form 

### ISSUE THREAD

**Issue by ShivamCoder23** [layer5io/layer5#5436]
### Description

In https://layer5.io/cloud-native-management/meshmap page the meshmap access form having dark mode bug that is the options are not visible

https://github.com/layer5io/layer5/assets/160073697/44152b63-205b-4ad9-9aec-781f7fe4baa9

### Expected Behavior

It should be properly visible in dark mode also

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by shibu-g** [comment]
can i start working in this issue?

**Comment by Chay2203** [comment]
@ShivamCoder23 @shibu-g This issue is already created, https://github.com/layer5io/layer5/issues/5232
so try to contribute there :D

**Comment by Chay2203** [comment]
@leecalcote I think you can close this issue

**Comment by leecalcote** [comment]
Thank you, gents. Let's go ahead and mark this as a dupe. Thanks for filing this, big S.
