### ISSUE TITLE
Site builds are failing

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5438]
### Description
```
error Page data from page-data.json for the failed page "/cloud-native-management/playground.html": {
  "componentChunkName": "component---src-pages-cloud-native-management-playground-js",
  "path": "/cloud-native-management/playground.html",
failed Building static HTML for pages - 11.145s
  "result": {
    "pageContext": {}
  },
  "staticQueryHashes": [
    "1376321266",
    "4047814605"
  ],
  "matchPath": "/cloud-native-management/playground"
}
error Building static HTML failed for path "/cloud-native-management/playground.html"

  17 |     className: "service-mesh_svg__st0"
  18 |   })), _path2 || (_path2 = /*#__PURE__*/React.createElement("path", {
> 19 |     d: "M279.3 309.2c-16.6 0-24.9-36.2-33.2-72.5-8.3-36.2-16.6-72.5-33.2-72.5",
     | ^
  20 |     className: "service-mesh_svg__st1"
  21 |   })), _path3 || (_path3 = /*#__PURE__*/React.createElement("path", {
  22 |     d: "M83.9 88.5c0-15.1 12.2-27.3 27.3-27.3 7.2 0 14.2 2.9 19.3 8 5.1 5.1 8 12.1 8 19.3 0 15.1-12.2 27.3-27.3 27.3-15.1.1-27.3-12.2-27.3-27.3zM0 164.3C0 149.2 12.2 137 27.3 137c7.2 0 14.2 2.9 19.3 8 5.1 5.1 8 12.1 8 19.3 0 15.1-12.2 27.3-27.3 27.3-15.1 0-27.3-12.2-27.3-27.3z",


  WebpackError:Minified React error #130; visit 
https://reactjs.org/docs/error-
  decoder.html?invariant=130&args[]=undefined&args[]= for the full message or us  e the non-minified dev environment for full errors and additional helpful warn  ings.
  
  - service-mesh.svg:19 
    Layer5/src/assets/images/service-mesh-icons/service-mesh.svg:19:1
  
  - service-mesh.svg:15 
    Layer5/src/assets/images/service-mesh-icons/service-mesh.svg:15:4
  
  - service-mesh.svg:26 
    Layer5/src/assets/images/service-mesh-icons/service-mesh.svg:26:1
  
  - static-entry.js:303 
    Layer5/.cache/static-entry.js:303:22
  
  - background.svg:163 
    Layer5/src/assets/images/homePage-images/background.svg:163:1

```

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
i think there is an issue with the image in react on how it is impoprted in react i had similar error before @leecalcote

**Comment by sudhanshutech** [comment]
@iArchitSharma is this still a issue

**Comment by sudhanshutech** [comment]
@iArchitSharma ?
