### ISSUE TITLE
Update the existing flags with the border ones 

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#544]
**Description**
In the current Layer5 site, French(2nd), Italian(4th) & Russian(6th) flags doesn't seem to have any border. Replace them with proper bordered flags.

**Screenshots**
![flags - inappropriate](https://user-images.githubusercontent.com/48355572/88930319-f544a500-d298-11ea-879b-7a1460c7dcc3.JPG)

 **To Reproduce**
1. Go to https://layer5.io/
2. Scroll down to the languages section in footer.
3. See error

In reference to PR #542  &  Issue #538

**Comment by Neilblaze** [comment]
@Nikhil-Ladha @leecalcote any idea about the Japanese flag? It seems to be bordered on 110% scale, but above 110% or below 110% this looks like this. [Environment - Ubuntu/Windows , Browser- Chrome]

**Comment by Nikhil-Ladha** [comment]
You can apply a fixed width to all the flags, then apply a border to them. I think it will fix your issue.

**Comment by Neilblaze** [comment]
Thanks for the suggestion @Nikhil-Ladha . Also, why is the title of Indian flag marked as "Tamil"? Should I replace that by "India"?

**Comment by Nikhil-Ladha** [comment]
The title represents to which language the page will be converted to on clicking the flag. So, it is "Tamil", we can change to "Hindi" or leave it like that.

**Comment by Neilblaze** [comment]
Closing this issue, as I have attached the updates with PR #542
