### ISSUE TITLE
In the Homepage section of Layer5 Website's Home Page honeycombs are not centered in the mobile view.

### ISSUE THREAD

**Issue by narasimha-1511** [layer5io/layer5#5441]
### Description
Current State:
The current view of the Integrations section in home page is not centered on the mobile view

### Expected Behavior
Desired state should be to make those hexagons smaller and look same as on width 334 and above

and also set the height that is not looking good on 334 below ..

### Screenshots

https://github.com/layer5io/layer5/assets/129654598/ec2c2c1c-736e-4cef-83cd-871f825398d7

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
Hey can i work on this issue @iArchitSharma

**Comment by iArchitSharma** [comment]
yes please @narasimha-1511

**Comment by srujan0404** [comment]
https://github.com/layer5io/layer5/assets/140909375/f4574d82-d17d-4119-a8f4-721fb22a5893

hey @iArchitSharma @narasimha-1511, I don't see this issue in my setup.

**Comment by narasimha-1511** [comment]
@srujan0404 is this the home page or the integrations one?

**Comment by srujan0404** [comment]
@narasimha-1511 this one is the integrations one, but also checked with the home page :)

**Comment by iArchitSharma** [comment]
@narasimha-1511 i don't see the problem on same size either
