### ISSUE TITLE
[Community] Member Profile: Cesar Roman

### ISSUE THREAD

**Issue by Satakshijain** [layer5io/layer5#5444]
**Current Behavior**

@cesartheroman has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @cesartheroman as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @cesartheroman 
- Twitter:
- LinkedIn: /in/cesartheroman
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by narasimha-1511** [comment]
hey can i work on this issue @Satakshijain

**Comment by cesartheroman** [comment]
- Twitter: https://twitter.com/cesartheroman
- Layer5 Cloud: https://meshery.layer5.io/user/ec5a1cd6-e03f-4aa8-9bca-1334e20042ff
- Bio: I'm a Chicago-based, "Boogie Down Bronx" raised, full stack software engineer specializing in JavaScript, TypeScript, React, and Node.

Currently, I'm a free agent looking to join an exciting tech company with strong leadership, team culture, and growth opportunities!

- Link to profile picture: https://drive.google.com/file/d/1mDu6QOwQzz2AigClwCARRK9c2wLElHQA/view?usp=sharing

@Satakshijain Thank you!

**Comment by AllenOps08** [comment]
@Satakshijain @narasimha-1511 are you working on this? If not , I'd like to take over

**Comment by Satakshijain** [comment]
Yes @AllenOps08 I am working on it
