### ISSUE TITLE
[Post Blog] - Demistifying Open Source

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5446]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** 
Demistifying Open Source

**Topic:** 
A Personal Journey and Insights into Getting Started

**Core points to convey in the post:** 
1. Getting Started: Choosing a project to contribute to
1. What skills do I need to get started?
1. My Open Source Journey: From Curiosity to Contribution
1. How to Get Started with Meshery - Making your first contributions
1. Reflections on Personal and Professional Growth

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by Coderayush13** [comment]
I want to work on this issue
