### ISSUE TITLE
[Community] Member Profile: Sangram Rath

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5463]
**Current Behavior**

@sangramrath has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @sangramrath as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @sangramrath
- Twitter: [mr_sangramrath](https://twitter.com/mr_sangramrath)
- LinkedIn: [in/sangramrath](https://www.linkedin.com/in/sangramrath/)
- Layer5 Cloud: [7dde79fb-2778-4a66-9ce5-6772bafe8df8](https://meshery.layer5.io/user/7dde79fb-2778-4a66-9ce5-6772bafe8df8)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@sangramrath Toss in a link to your profile picture and your bio, if you would, please :)

**Comment by Satakshijain** [comment]
@vishalvivekm Can I work on this issue ?

**Comment by DarrenDsouza7273** [comment]
@Satakshijain you can work on this once @saaagarsingh shares his details

**Comment by saaagarsingh** [comment]
Hey @DarrenDsouza7273 do I need to share something or do something on this?

**Comment by DarrenDsouza7273** [comment]
> Hey @DarrenDsouza7273 do I need to share something or do something on this?

No sorry i tagged the wrong person mb

**Comment by DarrenDsouza7273** [comment]
> Hey @DarrenDsouza7273 do I need to share something or do something on this?

sorry for the inconvenience caused

**Comment by saaagarsingh** [comment]
No probs....

**Comment by AbhisekOmkar** [comment]
what's the issue ?? can you explain properly

**Comment by sangramrath** [comment]
@vishalvivekm missed this, here are the details:

https://res.cloudinary.com/dzch7xh6n/image/upload/v1711954496/Sangram-HeadShot-HighRes_ku87ed.jpg

_Sangram Rath is a seasoned technology professional working as a Cloud Architect, mostly designing and implementing solutions on cloud and cloud native technologies such as Kubernetes, OpenShift etc., and has a background going back to datacenters and virtualization. A large part of his experience has been designing and deploying open source applications on cloud. He also acts as a technology advisor helping companies and startups with technology stack selection, competency building and anything that comes. A big area of interest for him is L&D, training and course/content creation. With multiple certifications across platforms and technologies, he has delivered hundreds of trainings over the past decade on emerging technologies and has been a Microsoft Certified Trainer too. He has spoken at conferences like Digital Ocean Tide, Open Source Summit (NA & Europe), AZConf, Open Source India, Google DevFest to name a few and conducted Docker & Kubernetes workshops for companies like Microsoft. He has also been a hackathon judge at Microsoft Reactor in Bangalore._
