### ISSUE TITLE
[Bug]: The community onboarding form has bugs on the profile picture and twitter profile section.

### ISSUE THREAD

**Issue by Haimantika** [layer5io/layer5#5477]
### Description
1. After the renaming of Twitter to X, the profile links now start with ‘x.com’ when you try to enter that in the form, it shows invalid. 
2. The profile picture component is a text input and should be changed to an upload component. 
### Expected Behavior
1. The twitter profile section accepts both twitter.com and x.com links
2. The profile picture component is updated to allow uploading of pictures

### Screenshots
![IMG_2225](https://github.com/layer5io/layer5/assets/32809211/913c6d9c-1ad2-42da-b7cf-8ac3a8c83e10)

![IMG_2224](https://github.com/layer5io/layer5/assets/32809211/5ca5d4c1-6800-4cca-9925-29de32791895)

### Environment:
- Host OS:
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Yashsharma1911** [comment]
@iArchitSharma @vishalvivekm ^^

**Comment by Yashsharma1911** [comment]
@vishalvivekm any review on task 2?

**Comment by bunnyDasari** [comment]
@Yashsharma1911 are you working on this issue?

**Comment by Yashsharma1911** [comment]
@bunnyDasari no I'm not, please take forward the with PR if issue still persist, ifnot please raise request to close this issue by dropping a comment in this issue

**Comment by bunnyDasari** [comment]
@Yashsharma1911  can you locate the file i can fix the bug

**Comment by kauxp** [comment]
can you please assign this issue to me?

**Comment by sudhanshutech** [comment]
@kauxp please do wait for issue to be assinged otherwise it created conflicts.

**Comment by sudhanshutech** [comment]
I would say for the issue 2, it is not required since its clearly written that provide the url of your image. We might can stick with that. Any feedback from you @vishalvivekm ?

**Comment by sudhanshutech** [comment]
@kauxp though if you had a pr is that function is taking the image and converting to url? because the spreadsheet that this data stored is stored in form url.

**Comment by kauxp** [comment]
okay, I will try to convert the image in URL if possible and keep you updated.

**Comment by vishalvivekm** [comment]
> I would say for the issue 2, it is not required since its clearly written that provide the url of your image. We might can stick with that. Any feedback from you @vishalvivekm ?

Yeah it's not under consideration to have this.
