### ISSUE TITLE
Remove green background from the Layer5 MeshMate section image

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5482]
### Current Behavior
There is a green color showing up in the background of the images in the Layer5 Meshmates section on [the community page.](https://layer5.io/community)
![image](https://github.com/layer5io/layer5/assets/51539117/7ebdc76c-3014-4604-a9de-a22b313b1f88)

### Desired Behavior
Remove the green background from the images in the Layer5 MeshMate section on the community page

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by JayKay24** [comment]
Hi. I'd like to work on this issue.

**Comment by ritiksaxena124** [comment]
Thanks for jumping in @JayKay24. Go Ahead 🚀
