### ISSUE TITLE
[Sistent] Missing a description of the project

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5485]
### Current Behavior
This page is missing a description of what the project is about - https://layer5.io/projects/sistent/about

<img width="779" alt="Screenshot 2024-04-12 at 1 19 14 PM" src="https://github.com/layer5io/layer5/assets/7570704/941ccb33-d4b4-4328-acbf-462b8b2f3c93">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ritiksaxena124** [comment]
Closing this issue as completed via #5489 PR
