### ISSUE TITLE
"Layer" text of Layer-5 celebration pic getting blended with the white background

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#549]
**Description**
The "Layer" text of the celebration [image](https://github.com/layer5io/layer5/blob/master/.github/welcome/Layer5-celebration.png) after each successful PR merge gets completely blended with the white background. Whereas for custom dark theme for Github, it looks completely fine.

**Screenshots**

- For default white Github theme :- 
![white](https://user-images.githubusercontent.com/48355572/89048283-402fec80-d36d-11ea-80c2-4a567dac5421.JPG)

- For dark Github theme :-
![dark](https://user-images.githubusercontent.com/48355572/89048336-5473e980-d36d-11ea-8aaa-262151c95e47.JPG)

---
**Possible fix**
Add an opaque background (like #fcfcfc) for this [image](https://github.com/layer5io/layer5/blob/master/.github/welcome/Layer5-celebration.png) & update the path in config.yml to make changes for the newcomer bot.

**Comment by kushthedude** [comment]
@Neilblaze You may want to take look at the image which is used in meshery repository.

**Comment by Neilblaze** [comment]
Yes [this](https://github.com/layer5io/meshery/blob/master/.github/welcome/Layer5-celebration.png) is the best possible replacement for [this](https://github.com/layer5io/layer5/blob/master/.github/welcome/Layer5-celebration.png) image. I'm creating a PR regarding this!

**Comment by kushthedude** [comment]
Please go ahead!

**Comment by Neilblaze** [comment]
@kushthedude review the PR please.
