### ISSUE TITLE
[Community] Member Profile: Deepak Reddy

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5490]
**Current Behavior**

@deepak4566 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @deepak4566 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @deepak4566
- Twitter: https://twitter.com/DeepakR95448261
- LinkedIn: https://www.linkedin.com/in/deepak4566/
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@deepak4566 Toss in your other links, bio and profile picture, if you would, please :)

**Comment by Satakshijain** [comment]
Hey Vivek, I would like to work on this issue

**Comment by vishalvivekm** [comment]
> Hey Vivek, I would like to work on this issue

Hi @Satakshijain, thank you for jumping in.
As you've already submitted a couple of similar PRs before, let's assign this one to any first-timer, please.

**Comment by Satakshijain** [comment]
Sure, no issues 
I will take up some another issue

**Comment by deepak4566** [comment]
Profile picture -https://drive.google.com/file/d/1yJRCb9b3tEKYS8a2vidhn8g2v-Pxhu1X/view?usp=drivesdk

Bio -
Deepak is an tech enthusiast who loves to solve real world enginnering problems , he is an freelancer in ML and cloud enginnering where he solves problems like reducing latency ,downtime and designing  backend architecture for organisations , he is also passionate about cloud native technologies and active contributor for kubernetes , layer5 . He is  also tech youtuber where he discuss about production grade cloud projects which include cloud native ecosystem.

**Comment by Aryakoste** [comment]
Hello @vishalvivekm. I would like to work on this issue.

**Comment by sudhanshutech** [comment]
go ahead @Aryakoste

**Comment by leecalcote** [comment]
🎈 @deepak4566! 🎈
