### ISSUE TITLE
[Getting started with mesheryctl] - Grammar adjustment

### ISSUE THREAD

**Issue by sandramsc** [layer5io/layer5#5504]
#### Current Behavior

Currently, the text on the "Getting started with mesheryctl" blog post reads as follows: " ...while enabling you with the tools and knowledge to glean the most of out your service mesh performance, while keeping your overhead to a minimum."

#### Expected Behavior

To increase readability and user experience the sentence could read as follows: "...while enabling you with the tools and knowledge to glean the most out of your service mesh performance, while keeping your overhead to a minimum."

#### Current Behavior

Currently, the word mesheryctl is missing a closing tag to complete the code block in the sentence (see sentence in screenshot Part 2)

#### Expected Behavior

To increase readability and maintain consistency add closing: "... `mesheryctl` ..." 

### Part 1
![Screenshot 2024-04-26 010024](https://github.com/layer5io/layer5/assets/19821445/b5f9d10b-27b1-4eae-a156-1b2b0749e1d6)

### Part 2
![mesh](https://github.com/layer5io/layer5/assets/19821445/4183fce3-2385-40cb-b531-afde42be7854)

### Environment:
- Host OS: Windows 11
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by RafaelJohn9** [comment]
May I be assigned this issue

**Comment by sandramsc** [comment]
@RafaelJohn9 I have assigned this to you.

**Comment by RafaelJohn9** [comment]
thanks @sandramsc
