### ISSUE TITLE
[Animation] Add animation to "Manage your Cloud Native mess" section on homepage

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5513]
### Current Behavior
The integrations shown inside the section are static, There is no animation
![image](https://github.com/layer5io/layer5/assets/51539117/c18b0688-186c-463d-a5a0-fc9116a850ad)

### Desired Behavior
Add animation such that the integrations integrations at the first column move in a downward direction and integrations in the second column move upward direction infinitely.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by JonathanKoerber** [comment]
Hi this looks like a interesting could I be assigned to this issue?

**Comment by ritiksaxena124** [comment]
Sure @JonathanKoerber go ahead 👍

**Comment by JonathanKoerber** [comment]
Hi, making progress but don't quite have it figured out. Should be able to be done my the end of this week.

**Comment by sudhanshutech** [comment]
@hargunkaur286

**Comment by JonathanKoerber** [comment]
Hi @sudhanshutech and @ritiksaxena124  I have made the animation. To make it visible there is a check that I've disabled. Am I Ok to disable the ckeck. It seem to check if the images are inside the screen with this `import { useInView } from "react-intersection-observer"`. 

![layer5-animation](https://github.com/layer5io/layer5/assets/14159224/806f8e7e-084d-4d0b-a852-0f8e0e28687f)

Please let me know what I should do.

**Comment by JonathanKoerber** [comment]
For more context this is the check that I've disabled. Its seems to be an external library.

![Screenshot from 2024-06-12 19-39-09](https://github.com/layer5io/layer5/assets/14159224/4b12a8fa-dd46-47ac-9842-f5aee34fc2ee)
