### ISSUE TITLE
[Sistent] Add a copy button to copy code

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5517]
### Current Behavior
On code tab of any component page in [Sistent](https://layer5.io/projects/sistent/components/button/code) don't allow users to copy the copy with one click. Users have to copy the whole component code manually.

### Desired Behavior
Add a copy  icon allowing users to copy the component code by just one click.
![image](https://github.com/layer5io/layer5/assets/51539117/42b30e0e-7770-4d30-a31f-6892cd8bd662)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
I will be wroking on this issue.

**Comment by yogeshmlv** [comment]
Hi! If this issue hasn't been resolved yet, please assign it to me. I'll work on fixing it

**Comment by narasimha-1511** [comment]
i am Working on this @yogeshmlv

**Comment by barkhaaroraa** [comment]
hi could i work on this issue?

**Comment by narasimha-1511** [comment]
I am working on this @barkhaaroraa !

**Comment by MadGanGithub** [comment]
Hey @ritiksaxena124 , shall I work on this?
