### ISSUE TITLE
[Sistent] Implement Modal component page 

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5519]
### Current Behavior
There is no page for Modal in [Sistent](https://layer5.io/projects/sistent/components)

### Desired Behavior
Implement the modal page using this [Figma mockup](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=5209%3A13685&mode=design&t=qP2uRkuetMXltHDo-1)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
Hey @ritiksaxena124 can i get some refrence about this modal ?

**Comment by Rexford74** [comment]
Hi @narasimha-1511! Do you still intend to take up this issue?

**Comment by JonathanKoerber** [comment]
Hello I'm looking for a first issue. If its is still free could i work of it?

**Comment by narasimha-1511** [comment]
@Rexford74 I am actuvally confused what to do in this issue , i am not clear .

**Comment by Rexford74** [comment]
Okay. Let me explain a little more. So under components in Sistent on the Layer5 website, there is a page for [button component](https://layer5.io/projects/sistent/components/button), and one for [text input](https://layer5.io/projects/sistent/components/text-input). This issue is to create a page for modals as is seen in the mockups just like we have for buttons & text input.

**Comment by Aryakoste** [comment]
Hello @ritiksaxena124 I would like to work on this issue.

**Comment by ritiksaxena124** [comment]
Sure @Aryakoste go ahead 👍

**Comment by vishalvivekm** [comment]
Hey @Aryakoste, do you have any updates that you wanna share ?
let's discuss this on today's website meeting at 5:30 PM IST. I am adding this as an [agenda item](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk). Please Join [https://meet.layer5.io/websites](https://www.google.com/url?q=http://meet.layer5.io/websites&sa=D&source=calendar&usd=2&usg=AOvVaw1CNpNwmYd_rTFcQa_7fBB5) if you are available during the meet.

**Comment by Aryakoste** [comment]
Sorry. Not available at that time.

**Comment by Aryakoste** [comment]
I have completed all the text part of modal component with overview, guidance and code section. Now just the example modals remains. I wanted to ask that for the code of Button and TextInput components there was a component in layer5/sistent node module which in turns use material ui. But for modal there is no component available layer5/sistent or there maybe and idk. So how should i proceed with this should i create custom modal component or something. @ritiksaxena124

**Comment by Aryakoste** [comment]
And in guidance and code section there are multiple varieties of modals. So do i have to create every variety using components.

**Comment by Rexford74** [comment]
I didn't know you were already working on this issue. Was just about to assign another contributor.. 😅. Thank you for raising these concerns @Aryakoste I'll look into it and give you feedback before the end of today.

**Comment by hargunkaur286** [comment]
Can I work on this issue? @Rexford74

**Comment by deauthe** [comment]
hey @Rexford74 , is this issue available to work on?

**Comment by Aryakoste** [comment]
Hello @Rexford74 Any updates on how should i proceed with this issue.

**Comment by vishalvivekm** [comment]
> Hello @Rexford74 Any updates on how should i proceed with this issue.

@Rexford74 @Aryakoste Let's make sure to discuss this in Monday's websites call.

**Comment by hargunkaur286** [comment]
Can you please assign this issue to someone else? @sudhanshutech I tried but wasn't able to figure out.
