### ISSUE TITLE
[Events] Feature tag not working as expected

### ISSUE THREAD

**Issue by ritiksaxena124** [layer5io/layer5#5521]
### Current Behavior
If the frontmatter of the `index.mdx` file of an event contains a tag `featured: false`, the event should not feature on the events page but the event is still featured.  [[Refer to this event](https://github.com/layer5io/layer5/blob/e4bb69a314e7b14e41ab8e14bb9eb360f4fddf39/src/collections/events/making-the-cncf-landscape-interactive-with-meshery/index.mdx?plain=1#L11)] code for reference.

### Desired Behavior
If any event has `featured: false` in frontmatter, the event should not be featured.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ritiksaxena124** [comment]
Go ahead @psankhe28 🚀

**Comment by Ashparshp** [comment]
Any updates, @psankhe28?

**Comment by psankhe28** [comment]
> Any updates, @psankhe28?

Actually, due to my exams, I am a bit busy and have not been able to work on this.

**Comment by Aryakoste** [comment]
Hello @ritiksaxena124 @leecalcote I would like to work on this issue.

**Comment by Ashparshp** [comment]
Go ahead @Aryakoste..

**Comment by leecalcote** [comment]
Thank you, @Ashparshp 👍
