### ISSUE TITLE
[Sistent] Page Content Update - Color: Code

### ISSUE THREAD

**Issue by Rexford74** [layer5io/layer5#5527]
### Current Behavior
The 'Color' page in the Sistent implementation contains the color tokens that help identify all the colors intended to be used across Layer5 and its solutions, grouping them as tokens for easy identification. These tokens have been updated recently, however, that change does not yet reflect in the current Sistent implementation.

### Desired Behavior
Update the 'Code' page under color in Sistent using this [Figma design](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=5818%3A18731&mode=design&t=v09PITdFGPxVhl66-1) as a guide.

### Implementation
Check out the design and then navigate to the corresponding [implemented page](https://layer5.io/projects/sistent/identity/color/code) on the Layer5 website. Compare each token in both light and dark mode and ensure that the implementation matches the design.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hargunkaur286** [comment]
@Rexford74 Can I work on this issue?

**Comment by ritiksaxena124** [comment]
Sure @hargunkaur286, go ahead

**Comment by vishalvivekm** [comment]
Hi @hargunkaur286 
Let's discuss your progress on the issue so far in the next websites meeting on Monday.
Meeting minues: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit
