### ISSUE TITLE
[Sistent] Page Content Update - Typography: Code

### ISSUE THREAD

**Issue by Rexford74** [layer5io/layer5#5528]
### Current Behavior
The 'Typography' page in the Sistent implementation contains the text tokens that help identify all the defined text intended to be used across Layer5 and its solutions, grouping them as tokens for easy identification. These tokens have been updated recently, however, that change does not yet reflect in the current Sistent implementation.

### Desired Behavior
Update the 'Code' page under typography in Sistent using this [Figma design](https://www.figma.com/file/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?type=design&node-id=1720%3A7928&mode=design&t=v09PITdFGPxVhl66-1) as a guide.

### Implementation
Check out the design and then navigate to the corresponding [implemented page](https://layer5.io/projects/sistent/identity/typography/code) on the Layer5 website. Compare both of them and ensure that the implementation matches the design.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hargunkaur286** [comment]
@ritiksaxena124 Can I work on this issue?

**Comment by shailpujan88** [comment]
Hey, @Rexford74  and @ritiksaxena124  Can work I on this issue?

**Comment by a19hu** [comment]
@Rexford74 can you explain this issue

**Comment by Ashparshp** [comment]
@hargunkaur286, @shailpujan88, @a19hu, and @11happy, Thank you all for your interest in this issue.

@hargunkaur286, can you please confirm if you want to work on this issue? If not, we'll reassign it to the next person in line.

We will proceed in chronological order based on @hargunkaur286's response.

**Comment by a19hu** [comment]
@Ashparshp @Rexford74 for dark mode not available image in [figma design](https://www.figma.com/design/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?node-id=1720-7928&t=mEQ0WL8l33twlRhF-0)

**Comment by hargunkaur286** [comment]
@Ashparshp I'll work on it.

**Comment by Ashparshp** [comment]
@hargunkaur286,
Thanks for taking on the issue! I've assigned it to you. For now, let's focus on implementing the light mode design. We can address the dark mode later.
Let me know if you need any help!

**Comment by a19hu** [comment]
@hargunkaur286 are you working on this issue??

**Comment by Rexford74** [comment]
Thank you for helping to assign this issue @Ashparshp. For the Dark Mode questions, I have attached a [link to dark mode](https://www.figma.com/design/ekm0Hh6M25bSKpP5BcIJom/Sistent-Design-System?node-id=6284-10450&t=XewTEf62K0xMlpAj-1) for both pages. 
@hargunkaur286 I'm aware you worked previously on 'Color'. If you faced the same dark mode issue, you can point it out here so that I can give some time for you to implement the dark mode change in the previous PR that you raised. If not I think it's ready to be merged as earlier agreed.

**Comment by Rexford74** [comment]
@11happy, I sincerely apologize. I couldn't assign the issue to you as discussed on Wednesday's Meshery call because issues are assigned in the order the requests come in. It's my fault in this case because I hadn't looked at the issue in a while to see that assignment requests had already been made. As a compromise, here is another [Meshery issue](https://github.com/meshery/meshery/issues/10743) that has been left unattended for a while now. The previous assignee couldn't get it done and it will be of much help if you can round it off and raise a PR. If you'd like to work on it, kindly drop a comment so I can get you assigned. 
Please let me know what you decide @11happy. Thank you for your patience.

**Comment by hargunkaur286** [comment]
@Rexford74 Thank you for updating the figma file, I am working on this issue and will be raising the PR soon. I had no problem in implementing the previous 'color' issue for dark mode, as it already had the required images. You can review that PR. Thanks

**Comment by Rexford74** [comment]
Thank you for working on this. I'll take a look and drop a review. Well done!
