### ISSUE TITLE
Carrers card issue

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5533]
### Description
When hovering over cards on the website, the text transformation appears to be glitchy and not smooth. This issue is affecting the user experience negatively.

### Expected Behavior
I expect the text transformation on the cards to be smooth and seamless when hovering over them.

### Video

https://github.com/layer5io/layer5/assets/150526286/fb0ee4dc-3e02-4529-bae1-c4dfe88e0e51

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
@iArchitSharma Could you check this? Text transformation on hover seems glitchy.

**Comment by Ashparshp** [comment]
@hargunkaur286 You can take this one! Availble?

**Comment by hargunkaur286** [comment]
@Ashparshp Sure, I'll look into it. Can you please provide me with the exact page link?

**Comment by Ashparshp** [comment]
@hargunkaur286 https://layer5.io/careers

**Comment by snikhil-vaddhi** [comment]
Is this issue stilll available? Can i work on it

**Comment by Ashparshp** [comment]
@hargunkaur286, can you please confirm if you are currently working on the text transformation glitch on the careers page? If you are not able to continue, we can reassign the issue to @snikhil-vaddhi

**Comment by Ashparshp** [comment]
@snikhil-vaddhi, if @hargunkaur286 is unable to proceed, I'll assign the issue to you. Please stand by for confirmation.
