### ISSUE TITLE
[Sistent] Code syntax highlighting for sistent components

### ISSUE THREAD

**Issue by lakshz** [layer5io/layer5#5534]
### Current Behavior

Currently, the code shown for [sistent components](https://layer5.io/projects/sistent/components/button/code), is rendered as plain-text. 

### Desired Behavior
The JSX syntax should be highlighted.

### Screenshots / Mockups

Existing UI:
<img width="1156" alt="Screenshot 2024-05-12 at 14 22 07" src="https://github.com/layer5io/layer5/assets/81241551/d3e76cef-075b-418a-a488-94da659acfdf">

### Implementation

we can utilize existing libraries for it.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by mannika763** [comment]
is this issue open? i saw some commits.

**Comment by Ashparshp** [comment]
@mannika763 do you wanna work on this issue?

**Comment by mannika763** [comment]
Yes please @Ashparshp

**Comment by Ashparshp** [comment]
@mannika763 Since we haven't heard back from @lakshz for a while, I can assign this issue to you..

**Comment by Ashparshp** [comment]
@mannika763 Refer the previous PR and discussion in that and also, @sudhanshutech Can share more about it!

**Comment by mannika763** [comment]
Hi @Ashparshp 
This is how the changes are looking in the UI. Before I make a PR, I wanted to confirm with you if everything looks good.
![image](https://github.com/layer5io/layer5/assets/84311047/b424a79c-0aa2-4e92-b889-fb46cbb5e4d9)
![image](https://github.com/layer5io/layer5/assets/84311047/31f40d8c-22c0-46ac-b008-720b2064288e)
