### ISSUE TITLE
[Community] Member Profile: Chris Carrier 

### ISSUE THREAD

**Issue by dextrot** [layer5io/layer5#5537]
**Current Behavior**

@ctcarrier has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @ctcarrier as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @ctcarrier
- Twitter: 
- LinkedIn: [in/ctcarrier/](https://www.linkedin.com/in/ctcarrier/)
- Layer5 Cloud: [e9502d25-f9c0-4b64-8366-8941617aa0fb](https://meshery.layer5.io/user/e9502d25-f9c0-4b64-8366-8941617aa0fb)
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by narasimha-1511** [comment]
Hey Work on this @dextrot

**Comment by a19hu** [comment]
Hey @dextrot can i work on this issue?

**Comment by vishalvivekm** [comment]
@narasimha-1511, as you've worked on a couple of these items, let's give assign this one to @a19hu.
@a19hu will you please confirm, if you've set up the site locally ?

**Comment by shailpujan88** [comment]
@vishalvivekm  Can I work on this?

**Comment by vishalvivekm** [comment]
> @vishalvivekm Can I work on this?

Hi @shailpujan88, 
We assign issue following FCFS, so let's first wait for @a19hu, if he's set up the project locally and wants to tackle the issue.

**Comment by a19hu** [comment]
> @narasimha-1511, as you've worked on a couple of these items, let's give assign this one to @a19hu. @a19hu will you please confirm, if you've set up the site locally ?

@vishalvivekm yes, setup is done

**Comment by ctcarrier** [comment]
Bio:
Chris Carrier is a hands-on technical leader known for building globally remote teams and driving continual improvement. With extensive experience in technical leadership, cloud infrastructure, and software architecture, Chris has delivered significant value to organizations large and small. He excels in reducing infrastructure costs, enhancing system security, and optimizing development pipelines. Passionate about solving big problems, Chris has successfully led teams through funding rounds, compliance milestones, and times of rapid growth.

Twitter: https://x.com/ctcarrier

![PXL_20240522_135035120](https://github.com/layer5io/layer5/assets/667357/0fc83eda-bcd1-49ff-8b1c-03dc4345da9f)

**Comment by narasimha-1511** [comment]
Go on @a19hu 🚀
