### ISSUE TITLE
[Sisten]: About Sisten Page - Table of content alignment 

### ISSUE THREAD

**Issue by surajgjadhav** [layer5io/layer5#5550]
### Description
logo is not aligned centered in Identity section under Table of content Page

### Expected Behavior
It should align centered with text content like this:
![image](https://github.com/layer5io/layer5/assets/31582237/57d4aef0-3eea-4992-9507-9ce6b6c6539f)
Solution is to add `align-items: center` property to flex

### Screenshots
![image](https://github.com/layer5io/layer5/assets/31582237/847610e2-ad99-4a31-a9cc-a9b111b2a161)

### Environment:
- Host OS: Windows
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by surajgjadhav** [comment]
Hi @Rexford74,
Please check this issue and let me know if this is to be done
I can take that up
Thanks

**Comment by Rexford74** [comment]
Thank you for raising this issue, @surajgjadhav. It is definitely something that needs to be adjusted. I'll assign it to you and hope to get an update soonest.

**Comment by surajgjadhav** [comment]
Sry I was not active for 2 days. Will raise PR in some time.
Thanks
