### ISSUE TITLE
[Community] Member Profile: Matthieu EVRIN

### ISSUE THREAD

**Issue by captain-Akshay** [layer5io/layer5#5566]
**Current Behavior**
@lekaf974 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @lekaf974 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @lekaf974
- Twitter:@mevrin
- LinkedIn: 
- Layer5 Cloud: e4a0ec88-35c6-4976-9715-f3d0f8ff029e
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by captain-Akshay** [comment]
@lekaf974 please share the following details:
Bio:
Link to profile picture:
Linkedin:

**Comment by lekaf974** [comment]
Hi @captain-Akshay it is really appreciate  

Bio: 
```text
Enthusiastic technology lover mainly on opensource technology mainly on Kubernetes and it ecosystem. Always wanted to contribute to open-source but id not know how and where to start until my first contribution for Meshery. I have a background in several domains related to computer science (networking, linux system admin, java developer, database administrator) and became a Platform Engineer since a while now. I like coding mostly in the backend and in automation.
I am always wanting to learn and share with others so you don't hesitate to connect with me on social media.
```

Linkedin: https://www.linkedin.com/in/matthieu-evrin/

Link to profile picture: https://media.licdn.com/dms/image/C5603AQGMRe6pnlFWjA/profile-displayphoto-shrink_800_800/0/1517283006691?e=1723075200&v=beta&t=5-V6AtZW7d9Nfmw7NmlXTyezqBWdqkpoOiBJzPVsJQA

**Comment by preyanshu** [comment]
Hey can I work on this?

**Comment by captain-Akshay** [comment]
There you go @preyanshu
