### ISSUE TITLE
[Sistent]: Buttons example don't have gap in between

### ISSUE THREAD

**Issue by surajgjadhav** [layer5io/layer5#5568]
### Description

Buttons example don't have gap in between
### Expected Behavior

Their should be gap in between the button (gap size needs to be finalize)
![image](https://github.com/layer5io/layer5/assets/31582237/5dfccb00-0314-4424-9971-2cab8ba7773e)

### Screenshots

![image](https://github.com/layer5io/layer5/assets/31582237/6a2dda8b-e5fd-4924-a446-6667908cf96b)

### Environment:
- Host OS: any
- Browser: any

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by surajgjadhav** [comment]
Hi @sudhanshutech ,
As discussed in the meeting, created this ticket to handle a bug.
One thing to finalize is the gap in between the button
could you please help with that
Thanks

**Comment by preyanshu** [comment]
hii @surajgjadhav can i work on this issue?

**Comment by sudhanshutech** [comment]
@preyanshu lets get you another issue
