### ISSUE TITLE
[NG] Add privacy policy and terms of service to layer5-ng site

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#557]
**Current Behavior**
The current Layer5 site has a [privacy policy](https://meshery.layer5.io/privacy-policy.html) and [terms of service](https://meshery.layer5.io/terms-of-service.html) posted.

**Desired Behavior**
These two agreements need to be publicly available in the `layer5-ng` site (the new site in that branch in this repo). They should be linked to as they are currently - https://github.com/layer5io/layer5/blob/3848fe512d2149daaf3d3fb1c83819ac9012726a/_includes/footer.html#L106-L108

---
**Resources**
This issue pertains to the next-generation of the layer5.io website. The site uses Gatsby and Strapi.
- See [`layer5-ng` contributing instructions] **[link here](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)**

**Comment by Tanuj22** [comment]
Fixed in #532
