### ISSUE TITLE
[Community] Member Profile: Dahyeon Kang

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#5573]
**Current Behavior**

@dusdjhyeon has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @dusdjhyeon as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @dusdjhyeon
- Twitter: 
- LinkedIn: 
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by iArchitSharma** [comment]
@dusdjhyeon please share the following details:
Bio:
Link to profile picture:
Linkedin:

**Comment by preyanshu** [comment]
@iArchitSharma hiiii , i would like to work on this

**Comment by dusdjhyeon** [comment]
> @dusdjhyeon please share the following details: Bio: Link to profile picture: Linkedin:

This is my information!

Github: https://github.com/dusdjhyeon
Bio(Blog):  https://medium.com/@dusdjhyeon
Link to profile picture: https://platform-logos-myprofile-api-prod.s3.us-east-2.amazonaws.com/dusdjhyeon.png?v=1707968854694
Linkedin: www.linkedin.com/in/다현-강-27a578297
Twitter: https://x.com/dusdjhyeon

**Comment by Venki1402** [comment]
@preyanshu I also want to work on this issue 
  is there any progress till now ??

**Comment by Venki1402** [comment]
@iArchitSharma 
I would like to work on this issue as well. Could you please let me know if there has been any progress so far?

Thank you!

**Comment by sudhanshutech** [comment]
hey @Venki1402 lets move here with first come basis. Lets get you another issue

**Comment by iArchitSharma** [comment]
@preyanshu just to confirm, are you working on this?

**Comment by iArchitSharma** [comment]
@Preyanshu, let's find you another issue to work on. This one needed to be completed urgently as part of the onboarding process

**Comment by preyanshu** [comment]
> @preyanshu, let's find you another issue to work on. This one needed to be completed urgently as part of the onboarding process

yaaaa no problem actually i was no available at that moment
