### ISSUE TITLE
Fix sidebar notification drawer

### ISSUE THREAD

**Issue by Golu7667** [layer5io/layer5#5575]
### Description
When you hover over the notification icon, the sidebar notifications drawer does not open properly. This behavior is undesirable.
### Expected Behavior
When I hover over the notification icon, the sidebar notification drawer should open properly

### Screenshots

![meserynoti](https://github.com/layer5io/layer5/assets/103061012/bfa3caab-73ff-4869-ab30-a87a3328797e)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by leecalcote** [comment]
Thanks, @Golu7667. Two items to note:

1. This issue is pertinent to github.com/meshery/meshery.
2. That "peek" behavior in Meshery UI is intentional.

Given these two items, will you close out this particular issue. Please do raise new issues as you come across similar issues. 👍
