### ISSUE TITLE
Add new Twitter handle to SMP project page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#558]
**Current Behavior**
The [project page describing SMP](https://layer5.io/projects/service-mesh-performance) does not include reference to the project's Twitter handle (https://twitter.com/smp_spec)

**Desired Behavior**
The project page describing SMP should include a link to the new Twitter handle (or perhaps, a small feed of its latest tweets) - https://twitter.com/smp_spec

**Comment by smritiRGI** [comment]
Want to start with fixing it

**Comment by leecalcote** [comment]
Thank you, @smritiRGI. That would be great.

**Comment by smritiRGI** [comment]
How to run this from windows?

**Comment by leecalcote** [comment]
@usamaidrsk would you be able to assist here?

@smritiRGI you are welcome to jump into the community slack in order to engage a little more real-time - http://slack.layer5.io

**Comment by PluckyPrecious** [comment]
Hello @usamaidrsk @smritiRGI how is this coming up?

**Comment by usamaidrsk** [comment]
Hello @PluckyPrecious, I  failed to connect with @smritiRGI, Ii shall be glad to work along with you

**Comment by godslayer201** [comment]
@leecalcote is this still up for grabs? Would like to work on this with the past assignees.

**Comment by PluckyPrecious** [comment]
Hello @godslayer201 sure you can go ahead.

**Comment by leecalcote** [comment]
The footer style and twitter feeds of two other Layer5 projects have decent design from which to copy - https://meshery.io and https://layer5.io

**Comment by leecalcote** [comment]
Since the time that this issue was opened, it seems that a Twitter feed was added to the project page. I do see another issue that needs to be addressed, however.

There are a number of elements on this page that are not responsive and break in a mobile view:

![AA46A7F4-8311-48C4-B62D-D709606D7292](https://user-images.githubusercontent.com/7570704/93599879-68f35c00-f984-11ea-9e27-92878935b321.png)

**Comment by leecalcote** [comment]
@smritiRGI @usamaidrsk Is this mobile formatting issue something that either of you are interested to address?

**Comment by Nikhil-Ladha** [comment]
The issue is fixed, I just checked it. @leecalcote can you please confirm it from your end too?

**Comment by Jashpatel1** [comment]
> The issue is fixed, I just checked it. @leecalcote can you please confirm it from your end too?

Yes, it is fixed.

**Comment by Nikhil-Ladha** [comment]
I think it is not for the ng site, @Jashpatel1 can you take a quick look. The feed is fixed to one tweet.

**Comment by Jashpatel1** [comment]
Yes, just a small change needed.

**Comment by Nikhil-Ladha** [comment]
Can you please send the quick PR?

**Comment by leecalcote** [comment]
Completed.
