### ISSUE TITLE
The alignment of the pattern picture on the Meshmate page is not accurate.

### ISSUE THREAD

**Issue by Aviral0702** [layer5io/layer5#5590]
### Description

The pattern picture with meshmate on the Meshmate page on the Layer5 Community site in not aligned properly.

How to reproduce : Visit this link https://layer5.io/community/meshmates

![image](https://github.com/layer5io/layer5/assets/134831178/8116e6f8-8c1e-41ff-b305-6a857dff5bb2)
 

### Expected Behavior
The logo should be aligned properly within the green frame.

### Environment:
- Host OS: Linux
- Browser: Chrome, Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by gagan-bhullar-tech** [comment]
@Aviral0702 I can work on this. Can you assign this to me

**Comment by Venki1402** [comment]
@Aviral0702 It's aligned properly on safari

<img width="1429" alt="Screenshot 2024-06-19 at 09 40 06" src="https://github.com/layer5io/layer5/assets/141071215/9c17c494-6fc5-403c-bfb5-719a1f99c8ea">

**Comment by gagan-bhullar-tech** [comment]
@Aviral0702 can you please assign it to me.

**Comment by Ashparshp** [comment]
@Aviral0702 If you're not posting the URL explicitly in the issue or not mentioning it, please ensure that the image is not cropped so people can easily locate the URL.
