### ISSUE TITLE
Icons size too big for small screens

### ISSUE THREAD

**Issue by GaganpreetKaurKalsi** [layer5io/layer5#5595]
### Description
For certain icons on https://layer5.io/company/brand, the icon size is too big for small screens.

<img src="https://github.com/layer5io/layer5/assets/54144759/7124eb64-9222-4b09-a501-bea575246c5c" width="400px" />
<img src="https://github.com/layer5io/layer5/assets/54144759/c74adca9-8a8c-4f2c-a83e-9c88c462ec5f" width="180px" />
<img src="https://github.com/layer5io/layer5/assets/54144759/a712c814-55d7-44b7-b7ab-8ec4ef9f3193" width="180px" />

### Expected Behavior
Whole viewport shouldn't be covered by 2 big images alone

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by hargunkaur286** [comment]
Can I work on this issue? @GaganpreetKaurKalsi

**Comment by Ashparshp** [comment]
@hargunkaur286 Let's address this issue.
