### ISSUE TITLE
[NG] Support for SVGs as featured images in blog posts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#560]
> Whenever an SVG is available, let's choose an SVG over a PNG.  I will provide one that can be used.

There is some predefined properties for blog-grid image. On using a svg image they are failing to work. @Tanuj22 can you tell something about this in case you know.

_Originally posted by @Jashpatel1 in https://github.com/layer5io/layer5/pull/555_

**Comment by Tanuj22** [comment]
This is a known [issue](https://github.com/gatsbyjs/gatsby/issues/10297) with gatsby image. A workaround is suggested in the issue thread.

**Comment by Tanuj22** [comment]
@leecalcote This can be closed.
