### ISSUE TITLE
Add the Testimonials in Product page

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#5612]
### Current Behavior
Currently we don't have any Testimonial on our product page - https://layer5.io/products
### Desired Behavior
Add the Testimonials in Product page, just like we have them here in bottom - https://layer5.io/cloud-native-management/generate-aws-architecture-diagram
![image](https://github.com/layer5io/layer5/assets/74408634/f6dff291-16cf-414e-9631-d19fac314046)

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Riyazul555** [comment]
Hey @iArchitSharma can I work on this issue?

**Comment by Ashparshp** [comment]
@Riyazul555 Go ahead!

**Comment by ConradKash** [comment]
@Riyazul555  any updates.

**Comment by Riyazul555** [comment]
Ya testimonials are almost ready 
Can you please give me the info you need in testimonials 
@ConradKash

**Comment by ConradKash** [comment]
Hello @Riyazul555 . I was just checking progress  because I am looking for an issue to contribute to

**Comment by iArchitSharma** [comment]
@Riyazul555 are you working on this?

**Comment by STSonyThomas** [comment]
Hey @iArchitSharma can I work on this issue? I'll get it done in 5 days.
