### ISSUE TITLE
Qanelas Soft flashes, then disappears into Roboto

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5616]
:bug: Visiting <https://layer5.io/cloud-native-management/meshery/integrations/argo-cd-operator|this page>, I see Qanelas Soft font momentarily, before the font family is switched to Roboto. :cold_sweat: Our intention is to be displaying Qanelas Soft. :help-wanted: fixing this :ladybug: .

[Slack Message](https://layer5io.slack.com/archives/C015QJKUMPU/p1719530505935159)

**Comment by arunkarthicknm** [comment]
Can I take this issue ? @leecalcote

**Comment by leecalcote** [comment]
Thanks, @arunkarthicknm

**Comment by arunkarthicknm** [comment]
Hey @leecalcote, its changing for lot of our integrations🫤. For eg: I noticed in ( Apache ShardingSphere, AWS CloudFront, AWS Load Balancer, .. and a lot )

**Comment by iArchitSharma** [comment]
Fixed with https://github.com/layer5io/layer5/pull/5629
