### ISSUE TITLE
Overflow issue on mobile view

### ISSUE THREAD

**Issue by iArchitSharma** [layer5io/layer5#5626]
### Description
We overflow issue as you can see the page is horizontally scrollable in mobile view
Link of page - https://layer5.io/company/brand
![image](https://github.com/layer5io/layer5/assets/74408634/ac60d7b5-0bd1-437a-b227-4904e0145fd0)

### Expected Behavior
Page shouldn't be horizontally scrollable in mobile view

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by iArchitSharma** [comment]
@hargunkaur286

**Comment by hargunkaur286** [comment]
Can you please assign this issue to me

**Comment by Rishikesh63** [comment]
@iArchitSharma  can you please assign this issue to me
