### ISSUE TITLE
Remove unnecessary console logs

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [layer5io/layer5#5627]
### Current Behavior
Currently layer5 website (https://layer5.io/) is having unnecessary console logs.

### Desired Behavior
These Console logs should be removed.

### Screenshots / Mockups
![Screenshot from 2024-07-01 19-37-45](https://github.com/layer5io/layer5/assets/54661456/0724fefb-2df9-41e9-9885-f7313e456599)

### Implementation
Simply remove the console logs.

### Note
I won't work on it. Kindly assign it to any new comer.

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by r-kundan** [comment]
I did this without any assignee please check it out

**Comment by r-kundan** [comment]
ok
