### ISSUE TITLE
[Community] Member Profile: Suraj Jadhav

### ISSUE THREAD

**Issue by Deepak0320Singhal** [layer5io/layer5#5630]
**Current Behavior**

@surajgjadhav has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @surajgjadhav as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: [surajgjadhav](https://github.com/surajgjadhav)
- Twitter: [surajjadhav63](https://x.com/surajjadhav63)
- LinkedIn: [suraj-g-jadhav](https://www.linkedin.com/in/suraj-g-jadhav/)
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by hargunkaur286** [comment]
Can I work on this issue?

**Comment by surajgjadhav** [comment]
layer5 cloud link: https://meshery.layer5.io/user/dabb4156-08df-474b-b43a-36b39725f165
Bio:

Suraj is a full-stack developer specialized in React, JavaScript, TypeScript, and Node.js. He is passionate about crafting innovative solutions and thrives in dynamic environments where he can contribute to the development of cutting-edge features with a focus on reliability and efficiency. Suraj also enjoys contributing to open source projects, which allows him to give back to the community while honing his skills.

**Comment by hargunkaur286** [comment]
@surajgjadhav Where can I get the link to your profile picture?

> layer5 cloud link: https://meshery.layer5.io/user/dabb4156-08df-474b-b43a-36b39725f165 Bio:
> 
> Suraj is a full-stack developer specialized in React, JavaScript, TypeScript, and Node.js. He is passionate about crafting innovative solutions and thrives in dynamic environments where he can contribute to the development of cutting-edge features with a focus on reliability and efficiency. Suraj also enjoys contributing to open source projects, which allows him to give back to the community while honing his skills.



> layer5 cloud link: https://meshery.layer5.io/user/dabb4156-08df-474b-b43a-36b39725f165 Bio:
> 
> Suraj is a full-stack developer specialized in React, JavaScript, TypeScript, and Node.js. He is passionate about crafting innovative solutions and thrives in dynamic environments where he can contribute to the development of cutting-edge features with a focus on reliability and efficiency. Suraj also enjoys contributing to open source projects, which allows him to give back to the community while honing his skills.

**Comment by surajgjadhav** [comment]
> @surajgjadhav Where can I get the link to your profile picture? Also, your location
> 

Hi @hargunkaur286 ,
Profile Pic link: https://drive.google.com/file/d/105HKZkzLU_wWjqyItcNZ5DfDc9jAde_M/view?usp=drivesdk

Thanks
