### ISSUE TITLE
Mobile Experience Improvement

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5638]
### Description
The Layer5 Community Handbook page at [Layer5 Community Handbook](https://layer5.io/community/handbook) needs improvements for better mobile experience. Currently, the content and buttons are not fit for smaller screen.

### Expected Behavior
Community handbook page to be fully responsive and user-friendly on mobile devices. Content should adjust properly, and buttons should be in size.

### Screenshots
![Community](https://github.com/layer5io/layer5/assets/150526286/99026b38-78e4-4dbb-93b1-6c3038b13f67)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Sakshampoply** [comment]
please assign this issue to me

**Comment by krishkumar84** [comment]
please assign this issue too me

**Comment by r-kundan** [comment]
please assign this issue too me

**Comment by Ashparshp** [comment]
Hey @krishkumar84,
This issue is already assigned to someone. We assign issues in chronological order. I'll assign you another issue shortly. Thanks for your interest!
