### ISSUE TITLE
Improve Mobile-Friendliness of "Learn Cloud Native" Section

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5645]
### Description
- The content does not fit well on the smaller screens.

### Expected Behavior
- The content should be responsive and fit properly on mobile screens.

### Steps to Reproduce:
- Open the [Layer5 Learn page](https://layer5.io/learn) on a mobile device.

### Screenshots
![Screenshot_2024-07-07-16-48-05-181_com android chrome](https://github.com/layer5io/layer5/assets/150526286/9d08df31-b5bd-4843-853c-392dbc086c0c)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by MUFFANUJ** [comment]
Please assign this to me

**Comment by vishalvivekm** [comment]
@MUFFANUJ 
I notice two your PRs submitted without the Issues being assigned to you. Please understand that it's important for us to uphold community guidelines.

 I understand that you may not have had the chance to go through the [contributing guides](https://layer5.io/community/handbook/contribution#:~:text=Contributor%20Guidance%3A) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook). 
Please go through these documents and I hope you'll keep them in mind for future.

**Comment by vishalvivekm** [comment]
As for this issue, @Ashparshp Let's make call for volunteer on Websites call tomorrow.
Adding this into meeting minutes.

**Comment by r-kundan** [comment]
Please assign this to me

**Comment by MUFFANUJ** [comment]
> @MUFFANUJ I notice two your PRs submitted without the Issues being assigned to you. Please understand that it's important for us to uphold community guidelines.
> 
> I understand that you may not have had the chance to go through the [contributing guides](https://layer5.io/community/handbook/contribution#:~:text=Contributor%20Guidance%3A) and code of conduct outlined in the [community handbook](https://layer5.io/community/handbook). Please go through these documents and I hope you'll keep them in mind for future.

I totally understand my mistake in the prior Pull requests, but this one wasn't assigned to anyone so cant I take this one?

**Comment by jaysomani** [comment]
Can i work on this?

**Comment by iamclintgeorge** [comment]
Can you assign me this issue?

**Comment by Ashparshp** [comment]
@iamclintgeorge Also, for bigger screens as well the background is too much we can reduce it as well!

**Comment by iamclintgeorge** [comment]
@Ashparshp Sure, i will look into it!!

**Comment by iamclintgeorge** [comment]
![Screenshot from 2024-07-09 21-04-40](https://github.com/layer5io/layer5/assets/152721610/d4c3f75b-72fa-4213-afd1-51d978e76015)


@Ashparshp  Is this fine?

Also as per your request, i decreased the height of the background from 35rem to 30rem.

**Comment by Ashparshp** [comment]
Thanks, @Harsh-svg988! Please go ahead and generate a pull request so we can review it better. By the way, are you also increasing the font size?

**Comment by iamclintgeorge** [comment]
Yes i had increased it. Thanks for pointing out, i will the changes to make it look consistent with the other headings.

**Comment by Ashparshp** [comment]
Thanks for pointing that out. From where are you maintaining the consistency with the other headings?

**Comment by iamclintgeorge** [comment]
I had set the size of the "Learn Cloud Native" heading relatively more than the other headings that are present in the same page such as the "Service Mesh Books" Heading. I have made the required corrections.

![Screenshot from 2024-07-09 21-43-18](https://github.com/layer5io/layer5/assets/152721610/441dff5c-3224-46cf-8e26-fb1945a5ae9b)

![Screenshot from 2024-07-09 21-44-10](https://github.com/layer5io/layer5/assets/152721610/185c2cda-651e-45c1-a556-4b86376f5922)
