### ISSUE TITLE
Horizontal Scrolling issue (mobile)

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [layer5io/layer5#5649]
### Description
Horizontal scrolling (mobile) issue on page: https://layer5.io/programs/lfx 

### Expected Behavior
There should be no scrolling

### Screenshots
![Screenshot from 2024-07-08 04-40-31](https://github.com/layer5io/layer5/assets/54661456/7cc1dc55-0c8a-4d54-b975-9eba655b8c44)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Nirajan1-droid** [comment]
may i have the assign? please :)

**Comment by Nirajan1-droid** [comment]
i think it's been already resolved in PR:
https://github.com/layer5io/layer5/pull/5635

**Comment by Muhammed-Moinuddin** [comment]
> may i have the assign? please :)
> 

It will be assigned via meeting today  .

**Comment by Muhammed-Moinuddin** [comment]
> i think it's been already resolved in PR:
> https://github.com/layer5io/layer5/pull/5635
> 

Nope that's different.

**Comment by rahulharpal1603** [comment]
I want to take up this issue. It is a simple fix. Adding word-wrap CSS attribute would fix it.

**Comment by rahulharpal1603** [comment]
Sorry, I added a PR by mistake, I will send a new PR with all the signoffs by tomorrow.

**Comment by Muhammed-Moinuddin** [comment]
> Sorry, I added a PR by mistake, I will send a new PR with all the signoffs by tomorrow.

No worries. Take your time.
