### ISSUE TITLE
Text alignment issue in the feature list

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5651]
### Description
The text alignment in the feature list section on the mobile view doesn't look good, especially after the first two lines. This misalignment affects readability and overall user experience.

### URL
The issue can be observed on the [Layer5 Pricing page](https://layer5.io/pricing).

### Steps to Reproduce
1. Open the Layer5 Pricing page on a mobile device.
2. Navigate to the feature list section.
3. Observe the text alignment issues

### Expected Behavior
The text should be properly aligned, maintaining a consistent format for better readability.

### Screenshots
![Screenshot_2024-07-08-17-26-27-251_com android chrome](https://github.com/layer5io/layer5/assets/150526286/926543dd-f671-47cc-a76c-26237cc2dda3)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by ShyanRoyChoudhury** [comment]
I would like to work on it @Ashparshp

**Comment by Harsh-svg988** [comment]
I would love to work on it @Ashparshp please aasign me

**Comment by Raaaaaahul** [comment]
@Ashparshp if this issue is not assigned i would happy to contribute if not, could you suggest any another issue

**Comment by ENUMERA8OR** [comment]
I would like to work on this issue.

**Comment by Ashparshp** [comment]
@ShyanRoyChoudhury @Harsh-svg988 @Raaaaaahul @ENUMERA8OR
Thanks, everyone, for your interest! Since this is a first-timer issue, and also we assign issues in chronological order. @ShyanRoyChoudhury is first in line. If they can't continue, we'll move to the next person.

So, please confirm who's just getting started?
And also, we'll be opening new good first issues as well, make sure to be active and mention once so, that I can ask you to get started!!

**Comment by mannika763** [comment]
Hey @Ashparshp 
if no one is up then i would like to work on this issue

**Comment by Harsh-svg988** [comment]
if @ShyanRoyChoudhury  can't continue i would like to work on it

**Comment by Ashparshp** [comment]
He is already working on an assignment, so you can proceed with this one. I'm assigning it to you.

**Comment by Harsh-svg988** [comment]
Hey @Ashparshp  I have raised the PR  and feel free to give any feedback....
