### ISSUE TITLE
Text alignment and layout issue on blog page

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5652]
### Description
The text alignment and layout on the blog page do not look good in the mobile view, particularly in the "Tags" section and the blog content cards. This misalignment affects readability and the overall user experience.

### URL
The issue can be observed on the [Layer5 Blog page](https://layer5.io/blog/community/the-mythical-10x-engineer).

### Steps to Reproduce
1. Open the blog page on a mobile device.
2. Observe the text alignment issues in the "Tags" section and the layout of the blog content cards

### Expected Behavior
The text and layout should be properly aligned and formatted for a consistent and visually appealing presentation on mobile devices.
### Screenshots
![Screenshot_2024-07-08-17-34-58-082_com android chrome](https://github.com/layer5io/layer5/assets/150526286/3c1fbbd8-4481-47b2-92d4-c924314795aa)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by MUFFANUJ** [comment]
Please assign it to me

**Comment by ShyanRoyChoudhury** [comment]
I would like to work on it @Ashparshp

**Comment by ayush-343** [comment]
I would like to work on it @Ashparshp

**Comment by Ashparshp** [comment]
@ayush-343 Thanks for your interest! This issue is meant for first-timers to get started, and it has already been assigned. We proceed in chronological order, so keep an eye out for more issues soon. 😊

In the meantime, you can check out this issue: https://github.com/layer5io/layer5/issues/5651

**Comment by Ashparshp** [comment]
@ShyanRoyChoudhury Any luck?

**Comment by ShyanRoyChoudhury** [comment]
Working on it. My apologies for the delay. Got pre-occupied with some other work. Will create PR soon. @Ashparshp

**Comment by Ashparshp** [comment]
@ShyanRoyChoudhury Are you still working on it, or should we give someone else a chance to fix this one?

**Comment by ShyanRoyChoudhury** [comment]
@Ashparshp My apologies for the extreme delay. Submitted the pull request.

**Comment by AKRAM-2002** [comment]
Already solved

**Comment by Ashparshp** [comment]
Already solved, closing this now.
