### ISSUE TITLE
[Community] Member Profile: Shlok Mishra

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5655]
**Current Behavior**

@Jougan-0 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Jougan-0 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Jougan-0
- Twitter: Jougan0
- LinkedIn: shlok08
- Layer5 Cloud: 958953e8-890e-4217-93f9-84322cc5f952
- Link to profile picture: https://avatars.githubusercontent.com/u/99207534?v=4

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by ConradKash** [comment]
Can you assign it to me

**Comment by Meetverma** [comment]
Hey @leecalcote Can u please sign it to me, Thanks!

**Comment by Ashparshp** [comment]
@ConradKash, I've assigned the issue to you. Thanks for taking it on!

@Meetverma, we go in chronological order to keep it fair for everyone. No worries, there will be more issues coming up! 👍😊 Thanks for your intrest!
