### ISSUE TITLE
[Community] Member Profile:

### ISSUE THREAD

**Issue by Jougan-0** [layer5io/layer5#5656]
**Current Behavior**

@dragon-slayer875  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @dragon-slayer875  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @dragon-slayer875 
- Twitter: 
- LinkedIn: rudrakshtyagi875 only https://www.linkedin.com/in/<profilename> -->
- Layer5 Cloud: ceb1505b-7d0d-4f72-b2ac-89e66b85bb2f only UUID https://meshery.layer5.io/user/<uuid> -->
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Venki1402** [comment]
@Jougan-0 can I work on this issue?

**Comment by Ashparshp** [comment]
@Venki1402 Go ahead!

**Comment by Venki1402** [comment]
Hey @dragon-slayer875 Could you please share your twitter handle, link to your profile picture and your bio here?

**Comment by dragon-slayer875** [comment]
> Hey @dragon-slayer875 Could you please share your twitter handle, link to your profile picture and your bio here?

@Rudrakshtyagi11
Image: https://drive.google.com/file/d/1KercymTt1054HjsKfGuqzXYMTj2lbp07/view?usp=drivesdk
Bio: In pursuit of being a master of all trades
