### ISSUE TITLE
Add SMP logo to the brand page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#566]
**Description**
The Layer5 [brand page](https://layer5.io/brand) doesn't mention any guidelines for the SMPS project.

**Expected Behavior**

In addition to appropriate guidelines, the new SMPS logo should also be added to the [brand page.](https://layer5.io/brand) The logo can be found in the [SMPS brand kit](https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smps-brand-kit.zip)

**Comment by leecalcote** [comment]
The `horizontal`, `stacked`, and `icon` folders can be zipped up in a similar fashion to the other project brand kits. The `resources` folder should not be included.

**Comment by leecalcote** [comment]
@chandrashritii will you finish this one off?
