### ISSUE TITLE
redirect mismatch

### ISSUE THREAD

**Issue by Venki1402** [layer5io/layer5#5662]
### Description

being redirected to : 2662825c-2bc7-4dea-a7ef-91269d334f71

### Expected Behavior

should be redirected to :
99b3cfd0-4269-4ee8-9ac7-392dd24c1c02  --OR--  c04a5da4-17ff-4774-ad47-30dff8d8d642 
(I'm Not Sure 😅)

### Screenshots

https://github.com/layer5io/layer5/assets/141071215/f7200814-12f8-4adf-9060-d6580dbd2763

### Environment:
- Host OS: macOS
- Browser: Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
Go on @Venki1402

**Comment by Venki1402** [comment]
@dusdjhyeon could you confirm your profile?

**Comment by dusdjhyeon** [comment]
> @dusdjhyeon could you confirm your profile?

https://meshery.layer5.io/user/99b3cfd0-4269-4ee8-9ac7-392dd24c1c02
This is mine.
