### ISSUE TITLE
[Community] Member Profile: Tharun 

### ISSUE THREAD

**Issue by Deepak0320Singhal** [layer5io/layer5#5665]
**Current Behavior**

@dottharun  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @dottharun  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @dottharun 
- Twitter:  dottharun
- LinkedIn: tharuntchn
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by dottharun** [comment]
Layer5 Cloud: https://meshery.layer5.io/user/0e0f60e5-fb6c-4006-9b1f-74cfa51dc659
Link to profile picture: https://drive.google.com/file/d/16ml-EGd4bkt78-j25QbLNeTyjmowuQ9r/view?usp=sharing

**Comment by ConradKash** [comment]
Kindly assign it to me

**Comment by sudhanshutech** [comment]
@ConradKash lets go
