### ISSUE TITLE
[NG] Change the links generated for individual blog posts 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#567]
**Current Situation**
The `layer5-ng` site is generating the links for individual blogs as a path to the file. Eg. This [blog](https://layer5ng.netlify.app/blogs/2020/2020-07-16-growing-as-an-open-source-contributor-with-layer5/) has a path `blogs/2020/2020-07-16-growing-as-an-open-source-contributor-with-layer5/`

**Desired Situation**
The links should look like this `blog/<category>/<title>`. This would involve adding a new category field in the frontmatter of the blogs.

**Resources**
This issue pertains to the next-generation of the layer5.io website. The site uses Gatsby and Strapi.
- See [`layer5-ng` contributing instructions] **[link here](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)**

**Comment by was-coder** [comment]
@Tanuj22 @leecalcote  i will like to work on this issue, i might also message you on slack @Tanuj22 for guidance on it

**Comment by Tanuj22** [comment]
@was-coder please go ahead. Note that we haven't decided on the catogories for each blog so add a dummy value for now.

**Comment by leecalcote** [comment]
Gents, let's see if we can fit the posts into one of the following categories:

- "community" - posts contributed by community members that are focused on their experience with the community and open source in general
- "meshery" - posts that focus more so on Meshery as a tool, what it can do, and so on.
- "service mesh" - posts that focus on service meshes like Istio, Consul, Linkerd, and so on.

**Comment by was-coder** [comment]
Hi Tanuj. Can you please reassign this to another person. I am stuck with
some personal stuff

**Comment by Tanuj22** [comment]
@was-coder No problem :+1:

**Comment by was-coder** [comment]
Thanks for understanding
