### ISSUE TITLE
Related resources container are not responsive content are overflowing 

### ISSUE THREAD

**Issue by upsaurav12** [layer5io/layer5#5670]
### Description

In ``What is Kubernetes`` page (Dont know about other one) containers in ``related resources`` are not responsive content are overflowing from their original state 
here is the video

https://github.com/layer5io/layer5/assets/116784047/09858442-a4e0-45ed-bad3-802f85bafa08

 

### Expected Behavior

Content shouldnt overflow from their original state . 
Also their is extra width for smaller width as you can see in the starting of the video that should also be fixes

### Environment:
- Host OS: Linux mint(UBUNTU)
- Browser:MOZILLA

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by upsaurav12** [comment]
I want to work on this issue

**Comment by Ashparshp** [comment]
@upsaurav12 Go ahead!

**Comment by upsaurav12** [comment]
When i done in setup project and rechecked it i am getting this thing 

https://github.com/layer5io/layer5/assets/116784047/6cdb29f9-f6bb-44c7-bb93-4ac5dc7d6e90

I am not able to understand what is happening ??? do you have any idea what is the reason

**Comment by CodeMaverick2** [comment]
Hey @Ashparshp I would like to solve this issue please assign me

**Comment by upsaurav12** [comment]
i am working in this issue kindly look up on other issue

**Comment by CodeMaverick2** [comment]
Sure go ahead

**Comment by Ashparshp** [comment]
@CodeMaverick2 Thanks for asking! As we move in chronological order to maintain the flow, I will make sure to ask you when I open some issues soon!

**Comment by CodeMaverick2** [comment]
Sure Would be eager to contribute

**Comment by Ashparshp** [comment]
@upsaurav12 Please check the PR for this issue as well. I mentioned you to see if it solves this too.

**Comment by upsaurav12** [comment]
No from my side the  issue still persists.
![image](https://github.com/user-attachments/assets/1480b8eb-725a-475a-970b-66158b9164cc)

**Comment by Ashparshp** [comment]
@upsaurav12 Yep yep!! My bad.

**Comment by upsaurav12** [comment]
Closing this issue 
Thanks.
