### ISSUE TITLE
Align items in Career/Software-engineer-internship page

### ISSUE THREAD

**Issue by iamclintgeorge** [layer5io/layer5#5675]
### Description
The Internship Details in the Career/Software-engineer-internship page happen to appear unaligned when viewed from a device with higher resolution.

#### Ideally, the intended view of the page should look something like this:
![Screenshot from 2024-07-12 21-22-56](https://github.com/user-attachments/assets/7034bafb-47dc-41d3-88f5-3f2b21487aea)

#### How it looks when viewed from a screen with higher resolution:
![Screenshot from 2024-07-12 15-21-54](https://github.com/user-attachments/assets/de44b38a-4aed-4068-a8eb-049071614ec4)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by iamclintgeorge** [comment]
@Ashparshp @vishalvivekm Can you please assign me this issue?

**Comment by Ashparshp** [comment]
@iamclintgeorge Go ahead!

**Comment by iamclintgeorge** [comment]
Thank you so much!! @Ashparshp
