### ISSUE TITLE
hover modal on nav should be in center

### ISSUE THREAD

**Issue by preyanshu** [layer5io/layer5#5679]
### Description
hover modal on nav should be in center
![image](https://github.com/user-attachments/assets/bae88a06-f5c7-4f71-b1e3-ff707cdedd4a)

### Expected Behavior
the hover modal should be in the center

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by preyanshu** [comment]
hi @Ashparshp can u validate this issue and if valid assign it to me

**Comment by Ashparshp** [comment]
Hi @preyanshu, thank you for the report. After review, this does not seem to be a valid issue as the hover modal behavior is consistent with the intended design. Please let me know if you have any other suggestions.

**Comment by Ashparshp** [comment]
Hi @preyanshu, thank you for the report. After review, this does not seem to be a valid issue as the hover modal behavior is consistent with the intended design. Please let me know if you have any other suggestions.

**Comment by vishalvivekm** [comment]
> hi @Ashparshp can u validate this issue and if valid assign it to me

Let's discuss this on Websites' call. Add this as an agenda item into the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit), if you would :)

**Comment by Ashparshp** [comment]
@preyanshu Not a valid issue, right?

**Comment by vishalvivekm** [comment]
> @preyanshu Not a valid issue, right?

will be closing for now. Thank you @preyanshu, we'll open the issue if the need arises.
