### ISSUE TITLE
Add Layer5 youtube playlists to the community page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#568]
The youtube playlists for [community meetings](https://www.youtube.com/playlist?list=PL3A-A6hPO2IMPPqVjuzgqNU5xwnFFn3n0) and [development meetings](https://www.youtube.com/playlist?list=PL3A-A6hPO2INr4oEIorJqC8N0FtxnYj0a) should be embedded in the https://layer5.io/community page, preferable above the `engage` section.

**Comment by leecalcote** [comment]
Embedding a playlist - https://support.google.com/youtube/answer/171780?hl=en-GB#

**Comment by Anita-ihuman** [comment]
I am on this

**Comment by Pariola-droid** [comment]
Have got this

**Comment by Anita-ihuman** [comment]
Will get to it

**Comment by Nikhil-Ladha** [comment]
@Anita-ihuman now would be good time to submit the PR...unless you are not interested in a hacktoberfest swag? :')

**Comment by Anita-ihuman** [comment]
I apologize for the delay on this singular issue. My PC caused me a lot of setbacks. I noticed the youtube link has been embedded under the community dropdown menu. Is it still ok to go ahead with the fix?

**Comment by Fahdmoh01** [comment]
Is this issue still opened?

**Comment by Nikhil-Ladha** [comment]
@Anita-ihuman , the issue here states to embed an iframe of the playlist which can be found following the steps in the link mentioned in the first comment of the issue. So, if you are working please give a heads up else I will assign it to Fahd 🙂

**Comment by Fahdmoh01** [comment]
Alright, taking this up👍🏿

**Comment by Fahdmoh01** [comment]
Hello @chandrashritii what do you mean by Engage Section? I am working on this issue but I need this clarification to proceed

**Comment by leecalcote** [comment]
Thank you for this effort, @Fahdmoh01!
