### ISSUE TITLE
Layer5 Community Member Text is Not Responsive

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5684]
### Description
The text "Layer5 Community Member" on the [community members page](https://layer5.io/community/members) is not responsive. It does not scale properly across different screen sizes, causing layout issues on smaller devices.

#### **Steps to Reproduce**
1. Go to [Layer5 Community Members Page](https://layer5.io/community/members).
2. Resize the browser window to a smaller size or view the page on a mobile device.
3. Observe that the text "Layer5 Community Member" does not adjust to fit the screen properly.

### Expected Behavior
The text "Layer5 Community Member" should be responsive and adjust its size and position appropriately across all screen sizes to ensure a consistent user experience.

### Screenshots
![Members](https://github.com/user-attachments/assets/a1a48805-d483-47eb-94b1-d1b852e4cbea)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by akaBisht** [comment]
@Ashparshp  I want to work on this issue.

**Comment by Ashparshp** [comment]
@akaBisht Go ahead!

Note: The issue persists for all member profiles.
