### ISSUE TITLE
[NG] Add news section 

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#569]
Create a news section for the Layer5-ng site

- Should retain most of the functionalities of the blog section.
- Should be formatted appropriately for news items. A hint as to what content would be added in the new section can be taken from the existing [news section](https://layer5.io/news) on the layer5.io site.

**Comment by Jashpatel1** [comment]
There's already an issue for this. Issue #514

**Comment by chandrashritii** [comment]
Duplicate of #514. Closing issue.
