### ISSUE TITLE
Improve the page layout on mobile view

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5690]
### Description

Improve the mobile view of [this](https://layer5.io/solutions/gitops) page

### Expected Behavior

Make sure that the two sections do not overlap with each other and the heading of the next section(What is GitOps) starts after the end of the first section like it is in the Desktop view.

### Screenshots

<img width="294" alt="Screenshot 2024-07-17 at 4 22 08 PM" src="https://github.com/user-attachments/assets/074cc407-df3b-4e45-aea6-343bcc9defc0">

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
go on @Harsh-svg988 🚀

**Comment by Ashparshp** [comment]
@Harsh-svg988 Any updates? If you have any questions, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

Fox

**Comment by Ashparshp** [comment]
@AlfiyaSiddique Any updates? If you have any questions, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Ashparshp** [comment]
@Harsh-svg988 Any updates? If you have any questions, let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).

**Comment by Harsh-svg988** [comment]
Working on it

**Comment by Harsh-svg988** [comment]
Hey @Ashparshp  i have raised PR for this can you verify it

**Comment by Ashparshp** [comment]
@Harsh-svg988 Can't see the PR!

**Comment by Ashparshp** [comment]
@Harsh-svg988 Any luck?

**Comment by ConradKash** [comment]
Can i work on this issue

**Comment by Ashparshp** [comment]
@ConradKash, Availble?

**Comment by ConradKash** [comment]
Yes.
That would be amazing

**Comment by hargunkaur286** [comment]
Since we didn't hear back from @Harsh-svg988.. I am assigning it to @ConradKash. Please go ahead!

**Comment by ConradKash** [comment]
You haven't assigned it to me yet.

**Comment by Ashparshp** [comment]
@ConradKash, Any luck?

**Comment by anniepauline** [comment]
I'll work on it!

**Comment by yaten2302** [comment]
Hey @hargunkaur286 , I would like to work on this issue!

**Comment by Ashparshp** [comment]
@ConradKash, since we haven't heard back from you, I'm unassigning this issue.

@anniepauline, I noticed you already have an assignment. It would be great if you could complete that first, and then you can take on this issue. Hope that's okay!

@yaten2302, happy to have you on board for this issue! Thank you..

**Comment by yaten2302** [comment]
@Ashparshp , thanks for assigning this issue to me 👍 I'll create a PR ASAP.
