### ISSUE TITLE
Bug: A file with trailing space in path causes error while cloning the repo

### ISSUE THREAD

**Issue by AlfiyaSiddique** [layer5io/layer5#5692]
### Description
There are two files with the below paths:
1.` src/collections/members/shlok-mishra /index.mdx`
2. `src/collections/members/shlok-mishra /shlok-mishra.webp`
They have trailing space in the path which causes the error while setting up the repo on local.
The error says:

> fatal: unable to checkout working tree
>warning: Clone succeeded, but checkout failed.
>You can inspect what was checked out with 'git status'
>and retry with 'git restore --source=HEAD :/'

### Expected Behavior
To get cloned without any error.

### Screenshots
![image](https://github.com/user-attachments/assets/c4c06904-cf90-4e2a-9a65-223584ea8a62)

### Environment:
- Host OS: Windows 10
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by AlfiyaSiddique** [comment]
**Who gets affected by this issue ?**
The newcomers that are trying to set up the repository on local and they are not smoothly able to clone the repo.
This also consumes their time while figuring out the reason behind the error.

**Solution**

- To fix the invalid file paths
- Make sure there is no space in the path.

If you find this issue a valid one, then please assign this issue to me.
I will raise a PR with fix
Thanks for your time.

**Comment by hargunkaur286** [comment]
@AlfiyaSiddique I cloned the repository again and didn't face any issue. Also, I cross checked the file names, they are correct. Thanks for your time 🙂 I am closing this issue

**Comment by mannika763** [comment]
Hey @hargunkaur286 
I am trying to clone it and am getting this error. I have been encountering this error for the past week.
![image](https://github.com/user-attachments/assets/b435ccc0-02e9-4816-8f72-25b6524253fa)

**Comment by AlfiyaSiddique** [comment]
Yes I faced the same issue that's why  raised the issue. It's due to the space in the end of  `shlok-mishra` folder name.  @mannika763 try removing that space in your forked repo on GitHub. And then clone it if facing error in cloning.

@hargunkaur286 let me know if a PR needs to be raised for this.

**Comment by hargunkaur286** [comment]
@Ashparshp Can you please confirm if this is a valid issue, we can reopen this, if it is. I didn't face the issue though.

**Comment by Ashparshp** [comment]
@hargunkaur286, I am facing this issue too. It seems the problem may not exist for some users if not updated.
It appears that your local repository might not be up-to-date, which could be why you aren't seeing the issue. Could you please run `git pull upstream` master to sync your local repository with the main one? This will ensure it is up-to-date and might help reproduce the issue if it is still present.
If confirmed, I suggest addressing this issue with priority..

**Comment by hargunkaur286** [comment]
> @hargunkaur286, I am facing this issue too. It seems the problem may not exist for some users if not updated. It appears that your local repository might not be up-to-date, which could be why you aren't seeing the issue. Could you please run `git pull upstream` master to sync your local repository with the main one? This will ensure it is up-to-date and might help reproduce the issue if it is still present. If confirmed, I suggest addressing this issue with priority..

Yes, I synced the fork and pulled upstream and cloned again for this issue, but couldn't replicate it. But, if it's an issue in most of the systems, then it might be there. Let's address it then.

**Comment by vishalvivekm** [comment]
Thank you for reporting this @AlfiyaSiddique 
Issues like this need to be fixed pronto

https://github.com/layer5io/layer5/commit/42b3528d55e1e665edb9cb9bc7e7b42680f4aff5
