### ISSUE TITLE
Card should be clickable (Sistent/Components)

### ISSUE THREAD

**Issue by Muhammed-Moinuddin** [layer5io/layer5#5696]
### Current Behavior
Card is not clickable(not leading to target page), just **Learn More button** is clickable. 

### Desired Behavior
Whole card (eg, Sistent/Component/Button Card) should be clickable and leading to proper page.

### Screenshots / Mockups

https://github.com/user-attachments/assets/650d0c4b-2eb2-41f1-94be-f57cdf5b455d

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin Please confirm whether this is an issue or a design choice.

**Comment by iamclintgeorge** [comment]
If you are looking for someone to work on this issue then let me know as i am interested in working on this issue. @Muhammed-Moinuddin

**Comment by Muhammed-Moinuddin** [comment]
> If you are looking for someone to work on this issue then let me know as i am interested in working on this issue. @Muhammed-Moinuddin 

I'll assign it to you. Let me just confirm this feature request first.

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin If we do so, then there will be ask for major changes in card as learn more section of the card will not be a valid UX!! So, it doesn't make any sense ig!! Well, let's have some suggestions @sudhanshutech @hargunkaur286?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin If we do so, then there will be ask for major changes in card as learn more section of the card will not be a valid UX!! So, it doesn't make any sense ig!! Well, let's have some suggestions @sudhanshutech @hargunkaur286?

Discussion is important, but I disagree with your opinion. It will make UX better. Cards on other places of website also support this feature.

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin Thank you for opening it. Let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk)

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin Thank you for opening it. Let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk)

Yes.

**Comment by AnkityadavIITR** [comment]
Hii @Muhammed-Moinuddin and @Ashparshp , if this issue is still valid i would like to work on it.

**Comment by Ashparshp** [comment]
@AnkityadavIITR Not decided yet. Make sure to join us for the Monday call for more!

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin @vishalvivekm As we discussed, this is not going to be implemented, so I am closing this as Not Planned.

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin @vishalvivekm As we discussed, this is not going to be implemented, so I am closing this as Not Planned.

No worries. But @Rexford74 suggested that whole card should be clickable via slack.

**Comment by Ashparshp** [comment]
@Muhammed-Moinuddin No idea about it.. I'll be reopening it..

**Comment by KKartikay-27** [comment]
Can I work on this ??

**Comment by DevMhrn** [comment]
@Muhammed-Moinuddin , Could you please assign it to me

**Comment by narasimha-1511** [comment]
Go on @DevMhrn 🚀

**Comment by DevMhrn** [comment]
@Muhammed-Moinuddin I have made the pull request, and solved it , could you please review it

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin I have made the pull request, and solved it , could you please review it

Let's review this in tomorrows website meeting. https://layer5.io/community/calendar
I've already added it to meetings agenda item.

**Comment by DevMhrn** [comment]
@Muhammed-Moinuddin @Ashparshp Please check the updated pr , I have made the changes

**Comment by DevMhrn** [comment]
@Ashparshp @Muhammed-Moinuddin could you please review this pr, and check if it mergable or not

**Comment by Ashparshp** [comment]
@DevMhrn Were you in the last Monday call? We had a discussion about it.

**Comment by DevMhrn** [comment]
@Ashparshp I was unable to join the meeting, but i watched the recording later and i corrected the code and made the changes , and also @Muhammed-Moinuddin asked to fix the title color which i missed earlier and now everything looks good , could you please review it.

**Comment by Muhammed-Moinuddin** [comment]
You have not followed all the requested changes. The PR also have DCO issues.

**Comment by DevMhrn** [comment]
@Muhammed-Moinuddin I think i have solved the issue related to the review i was given  in the last meeting ,  you can check now  , it works on different themes and same color changes as you asked to do. But still I will  attend the monday meeting , 

by the way how will i join the meeting @Ashparshp ?
