### ISSUE TITLE
[NG] Style changes to blog cards.

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#570]
**Desired Behavior**
The [blogs cards](https://layer5ng.netlify.app/blog-grid) in layer5-ng need some style changes.

-  The images on the thumbnail aren't aligned properly. The images should fill the height of the container without being cropped out.
![Screenshot from 2020-08-04 01-11-47](https://user-images.githubusercontent.com/42486853/89220609-83998d80-d5ef-11ea-8684-8d8bd339c130.png)
- The scaling up effect in case of png images aren't smooth as compared to svgs. Example: `Starting SMI Conformance Testing with Meshery` blog has a svg thumbnail. 
 

---
**Resources**
This issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Neilblaze** [comment]
I guess modifying the height of those png images will fix this issue. Assign me this please @Tanuj22

**Comment by Neilblaze** [comment]
@leecalcote I guess a replacement image for `Layer5: Landscape Spectrums Revisited` blog card will look much better that what it's now.

**Comment by Neilblaze** [comment]
@leecalcote same issue is also pertaining for Layer5 [blog](https://layer5.io/blog) page too. I would love to work upon that :)

**Comment by Nikhil-Ladha** [comment]
Well, we tried that @Neilblaze , but you can give another try and come up with a solution. You can take this up👍🏼

**Comment by Neilblaze** [comment]
Sure I'm on it 😃

**Comment by Neilblaze** [comment]
closed via #694
