### ISSUE TITLE
Visibility issues on What is Multi-Cluster Kubernetes?

### ISSUE THREAD

**Issue by upsaurav12** [layer5io/layer5#5709]
### Description

There is some visibility issue on What is Multi-Cluster Kubernetes like this 
![image](https://github.com/user-attachments/assets/fc6fbf01-0b78-46c3-8422-e59feeb754bf)

you can go to the page also 
'https://layer5.io/resources/kubernetes/what-is-multi-cluster-kubernetes' see the page in ``dark mode only``
This is specially for 

### Expected Behavior
Text Content should be visible in Dark becuase it is visible in ``light`` mode

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
@upsaurav12, thank you for opening the issue. Would you like to work on it, or should we consider involving some newcomers? Additionally, the image at the bottom of the page is not mobile-friendly. Please update the issue with the image to illustrate this problem, so we can address it as well.

**Comment by upsaurav12** [comment]
No you should give chance to other new-commers also (although i am also a new comer but i have opened some couple of the issue and working on them so no time to work on this issue)

**Comment by Ashparshp** [comment]
@upsaurav12, cool! Thanks for sending your words. If you're not willing to work on an issue, you can also add a help-wanted tag!!

**Comment by upsaurav12** [comment]
No idea about adding tags

**Comment by Ashparshp** [comment]
@upsaurav12 It's in labels!

**Comment by akaBisht** [comment]
@Ashparshp  I want to work on this issue.

**Comment by AnkityadavIITR** [comment]
@Ashparshp Hi, If this issue is not assigned to anyone yet i would like to work on it

**Comment by Ashparshp** [comment]
@akaBisht @AnkityadavIITR Thanks for showing your interest! We assign issues in chronological order to maintain our workflow. I'm assigning this to @akaBisht for now. We'll assign a new issue to you shortly, @AnkityadavIITR .

**Comment by upsaurav12** [comment]
@AnkityadavIITR you can see the other issues also in issue tab but even if you dont got any issue assigned then can create you issue if you feel that if there is a bug or what features you wants to work

**Comment by akaBisht** [comment]
Hey @Ashparshp, can you tell me if I am approaching this issue the right way? If not, can you suggest a better way to deal with it?
