### ISSUE TITLE
[NG] Feature images in individual blogs

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#571]
**Desired Behavior**
The images on the thumbnail of the blogs should also be featured in the respective blog posts. A suggestion is to show it behind the title in the individual blogs. 

---
**Resources**
This issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
Solved in #618
