### ISSUE TITLE
Extra width in Layer5 home page for smaller width 

### ISSUE THREAD

**Issue by upsaurav12** [layer5io/layer5#5711]
### Description

Currently the Home page is not responsive for smaller width it has extra width which leads to horizontal scrolling 
https://github.com/user-attachments/assets/6bbc2b93-fa36-412f-95be-8e528c57536b

### Expected Behavior

There should not extra width 

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Ashparshp** [comment]
@upsaurav12 Refresh your page and try again!

**Comment by upsaurav12** [comment]
not working 

https://github.com/user-attachments/assets/bcc83709-4a43-41fc-8f52-47826e066955

**Comment by Ashparshp** [comment]
Yes, it’s a valid issue! there is horizontal scrolling. @upsaurav12, are you taking up this issue?

**Comment by upsaurav12** [comment]
Yes i am taking this but confused that what is its cause

**Comment by hargunkaur286** [comment]
@upsaurav12 Thank you for raising this issue. Let's discuss it in today's meeting. Adding this to [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk)

**Comment by upsaurav12** [comment]
> @upsaurav12 Thank you for raising this issue. Let's discuss it in today's meeting. Add this to [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit#heading=h.69qskjv558bk) if you would :)

Sorry for late response i was not able to add this in meeting minute. Can i add this for next meeting

**Comment by Ashparshp** [comment]
@upsaurav12 Thanks!

Fixed: #5729

**Comment by Ashparshp** [comment]
@upsaurav12 You can help in review to this PR as it fixes all the pages!

#5729

**Comment by upsaurav12** [comment]
so should i close this issue ??

**Comment by upsaurav12** [comment]
That's nice,
@Ashparshp So do i have to close this issue?

**Comment by Ashparshp** [comment]
@upsaurav12 Don't close this for now; we will close it. However, please review that PR, as it may help you as well since you were unsure about the fix for this!

**Comment by siddharthbaleja7** [comment]
@Ashparshp Is this issue still open?

**Comment by Ashparshp** [comment]
Thank you @siddharthbaleja7 for showing the intrest, it's been resolved.
Thank you @upsaurav12.
