### ISSUE TITLE
Make Community Calendar Page Mobile-Friendly

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5716]
### Description
The current design of the Community Calendar page is not mobile-friendly. Please make the following improvement...
Adding to the calendar should be a primary consideration.

### Expected Behavior
Ensure the page is mobile-friendly.Make the "Add to Your Calendar" button visible in normal mode.

### Screenshots
![Screenshot_2024-07-23-05-57-28-995_com android chrome](https://github.com/user-attachments/assets/f36a0a46-d52b-4dbf-b6c0-b8069688529d)

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by devesh-2002** [comment]
May I take this issue?

**Comment by BHAV0207** [comment]
@Ashparshp  I would like to work on this issue

**Comment by dakshkanaujia** [comment]
@Ashparshp Please assign me the issue I have started working on it

**Comment by vishalvivekm** [comment]
@Ashparshp @hargunkaur286 
I wonder if this is an valid issue, on mobile view one can scroll horizontally to see the remaining right side of the calendar.

**Comment by Ashparshp** [comment]
@vishalvivekm @hargunkaur286 Are we considering some enhancement to it? Or rather we can close this issue?

**Comment by samrat12x** [comment]
hello ,i am a beginner contributor.
 I havent contributed yet,
 But I would like to know  ,can  anyone start solving this issue in parallel even if someone is already assigned to it.
 
 what if the other person has done a better work than the one who was assigned

**Comment by devesh-2002** [comment]
I am not able to work upon this issue, due to some reasons. Please anyone interested, can work upon this issue.

**Comment by Ashparshp** [comment]
@samrat12x Go ahead!

**Comment by samrat12x** [comment]
> @samrat12x Go ahead!

thanks. Will do my best

**Comment by kdotmanoj** [comment]
issue is still not resolved can i work on it ;) @Ashparshp

**Comment by thedeeppp** [comment]
I would like to work on it if no one is working @hargunkaur286 @Ashparshp

**Comment by Shubhf** [comment]
If issue is not resolved , Can I work on it ? @Ashparshp 
I think in order to improve mobile friendliness of the Community Calender page, I will resdesign the layout to ensure responsiveness and usability on all types of device.This includes making Add to Calender button prominently visible and accessible in all views(laptop, and mobile both),which will enhance user experience

**Comment by samrat12x** [comment]
@Shubhf yeah go ahead.

**Comment by Anand-Theertha** [comment]
I would love to work on this, if it is still unresolved.

**Comment by Kneatrum** [comment]
Hi @Shubhf , I know you are working on this but allow me to ask if reversing the order of the toolbars is acceptable or can be an option as described below.  I am not an expert in front-end so this is just a question out of curiosity.
![image](https://github.com/user-attachments/assets/47d63061-9216-434b-af39-830f5f58ce00)
![image](https://github.com/user-attachments/assets/3b9344c4-82b6-4eda-8821-3f1e621db2b9)

**Comment by Ashparshp** [comment]
@Anand-Theertha,, it's not an issue, but feel free to give it a try for some enhancements if you'd like.

**Comment by Ashparshp** [comment]
Closing this issue as it is no longer valid.
