### ISSUE TITLE
reword the CTA text

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5717]
### Current Behavior

![image](https://github.com/user-attachments/assets/770bec7b-dc24-4e04-af5d-8de9cfc0ef46)

### Desired Situation

change the word `Open Playground` to `Open in Demo System`

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by PrtHub** [comment]
I want to work on this issue. can you assign it to me?

**Comment by hargunkaur286** [comment]
@PrtHub sure, please go ahead!

**Comment by siddharthbaleja7** [comment]
Can you please assign this issue to me ?

**Comment by vishalvivekm** [comment]
@PrtHub would you like to share your progress with the issues #5717 and #5718 ?
We've our weekly websites meeting today at 5:30 PM IST.
Meeting link : https://meet.layer5.io/websites
Meeting minutes: https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit

// @Ashparshp

**Comment by PrtHub** [comment]
I am sorry, for some reason I couldn't set it up locally, even though I have tried many times.

**Comment by Ashparshp** [comment]
@PrtHub You can drop the issue you're facing in slack or in discussion forum!

**Comment by vishalvivekm** [comment]
> I am sorry, for some reason I couldn't set it up locally, even though I have tried many times.

Thank you for letting us know @PrtHub.
Note: Fastest way to spin up the site is using Codespaces, follow the setup guide here : https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#prerequisites

**Comment by SAHU-01** [comment]
@vishalvivekm is this issue `up for grab`? If so, can you assign it to me?

**Comment by siddharthbaleja7** [comment]
Can you please assign this issue to me ?

**Comment by hargunkaur286** [comment]
@SAHU-01 Since you are already working on a couple of issues, let's give first time contributors a chance. 🙂@siddharthbaleja7 May I know if you have the project setup locally?

**Comment by hargunkaur286** [comment]
okay, @siddharthbaleja7 please go ahead, i am assigning it to you! @I-karmayogi please look out for more issues

**Comment by Shubhf** [comment]
@hargunkaur286 Pls assign this issue to me

**Comment by Ashparshp** [comment]
@vishalvivekm Use playground? Not Open playground, right?
