### ISSUE TITLE
Website not correctly aligned according to different devices. 

### ISSUE THREAD

**Issue by hollermay** [layer5io/layer5#5721]
### Description
I use a 6.2 inch phone and it does not correctly align to the page and it keeps zooming in everytime. 

### Expected Behavior
The website's should be more responsive and more aligned to the dimensions of the devices. 

### Screenshots
![Screenshot_20240724-111543.jpg](https://github.com/user-attachments/assets/139a4c55-70f0-4bc0-a82b-b9f80df3a92a)

### Environment:
- Host OS: XOS V13.0.0
- Browser: Chrome

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by BHAV0207** [comment]
@hollermay  I would like to work on this issue, please assign me this issue

**Comment by Swarnim114** [comment]
@hollermay  Please assign this issue to me

**Comment by mayank1365** [comment]
@hollermay please assign this issue to me

**Comment by hollermay** [comment]
@leecalcote

**Comment by leecalcote** [comment]
@Ashparshp @vishalvivekm @hargunkaur286

**Comment by hargunkaur286** [comment]
As we assign the issues using FCFS rule, @BHAV0207  please go ahead, I'm assigning it to you. Meanwhile, @Swarnim114 @mayank1365 please look out for more issues. Thanks

**Comment by Dipti0704** [comment]
@leecalcote will be done by end of date, have raise a pr , but facing an issue, just resolving it and will create a pr of it .

**Comment by hollermay** [comment]
@hargunkaur286 pls review the PR
