### ISSUE TITLE
[Project] Update link and description of Service Mesh Performance Specification on Meshery page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#573]
**Current Behavior**
This section on the [Meshery page](https://layer5.io/meshery#performance-spec) is in need of being refreshed.

**Desired Behavior**
- [ ] This section could also do with an updated description of the SMPS initiative.
- [ ] The link in this section should point to the new https://smp-spec.io website.
- [ ] The `name` of the `a` tag for this section should be updated from #performance-spec to `#smps`.
- [ ] SMP logos can be found under layer5io/brand

---
**Screenshot**
<img width="816" alt="Screen Shot 2020-08-03 at 7 22 12 PM" src="https://user-images.githubusercontent.com/7570704/89239445-d4dd5900-d5be-11ea-9ba7-615fadc5290f.png">

---
**Resources**
This issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. 
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by usamaidrsk** [comment]
how to go on this?

**Comment by leecalcote** [comment]
@usamaidrsk I missed your comment earlier. You're most welcome to take on this issue. For assistance @Ruth-ikegah or @PluckyPrecious or @JubayerJoy would make for a great partner here.

**Comment by JubayerJoy** [comment]
Hi @usamaidrsk, are you working on a solution? I'd be glad to join you 🙂

**Comment by PluckyPrecious** [comment]
Issue fixed, i'll close now.
