### ISSUE TITLE
[Community] Member Profile: Hargun Kaur

### ISSUE THREAD

**Issue by Ashparshp** [layer5io/layer5#5730]
**Current Behavior**

@hargunkaur286 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @hargunkaur286 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @hargunkaur286
- Twitter: https://x.com/hargunkaur286
- LinkedIn: https://www.linkedin.com/in/hargun-kaur-0b5b8a242/
- Layer5 Cloud: https://meshery.layer5.io/user/2d7df104-da82-4618-a8be-7bf9e03dc86c
- Link to profile picture: https://drive.google.com/file/d/19Vof7_K0XnjUWEg_XYI8Tsr642p2HQvT/view?usp=sharing

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by Dipti0704** [comment]
hey @Ashparshp  I would like to work on this issue, please assign me this issue

**Comment by Ashparshp** [comment]
@Dipti0704 Thank you for taking this on. I have assigned you the issue...

**Comment by sudhanshutech** [comment]
@Dipti0704 done?

**Comment by Dipti0704** [comment]
@sudhanshutech  have rasied a pr for it , facing some issues with it , fixing the issues and will raise another pr by end of date

**Comment by Dipti0704** [comment]
@sudhanshutech done with the PR , please review
