### ISSUE TITLE
Dark-mode friendly support for search input field

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5734]
### Current Behavior
See the https://layer5.io/blog page and it's use of an input field while in dark mode.
See also the site home page and https://layer5.io/cloud-native-management/meshery/integrations for additional uses of a search input field.

Be sure to adhere to the Acceptance Tests below.

### Desired Behavior

![Screenshot 2024-07-26 at 4 50 08 PM](https://github.com/user-attachments/assets/8d5449fa-6355-4cae-9003-21229955a949)

### Acceptance Tests
1. All search input fields for follow the same dark-mode friendly behavior.
    1. [Integrations](https://layer5.io/cloud-native-management/meshery/integrations) page
    2. Home page
    3. Blog page

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Dipti0704** [comment]
hey @leecalcote   I would like to work on this issue, please assign me this issue

**Comment by BarryByte** [comment]
hey @leecalcote please assign me this issue.

**Comment by Indrajeety993648** [comment]
hey @leecalcote  please assign it to me . I would love to work on this issue , Thank You

**Comment by hollermay** [comment]
Hey @leecalcote @hargunkaur286 , I'm available for this issue now and have also worked around layer5, you can assign me this

**Comment by narasimha-1511** [comment]
Hey @Dipti0704 you have already working on other issue i am assigning this to @BarryByte

**Comment by Ashparshp** [comment]
Thank you all for your interest in working on this issue!

I apologize for any confusion regarding the assignments. We appreciate your ask and will ensure that future assignments follow the chronological order of requests. For now, @Dipti0704, thank you for your patience. We'll proceed with the issue based on our current process and prioritize assignments accordingly.

Thanks again to @BarryByte, @Indrajeety993648, and @hollermay for your willingness to contribute.

**Comment by Ashparshp** [comment]
@BarryByte Any updates?

**Comment by BarryByte** [comment]
Hello @Ashparshp, 
Sorry for the delay in discussing the approach. The issue can be fixed by implementing a dark mode switcher for the entire Blog page. Currently, the background color of the search input field is grey in light mode and white in dark mode, which is not consistent.

Refer to these images for a better understanding of the issue:

![Screenshot from 2024-07-28 12-17-26](https://github.com/user-attachments/assets/0f5d1ba2-19f6-46f0-8a33-545b560e8a18)
![Screenshot from 2024-07-28 12-17-13](https://github.com/user-attachments/assets/902814b5-6d48-4470-b89b-83b8773aaf27)

The color hex code does not change when the theme is toggled. Therefore, we need to implement separate changes for the Blog page when the theme is switched.
If i am missing something please add to it.

**Comment by Ashparshp** [comment]
@BarryByte Refer: https://layer5.io/projects/sistent/identity/color/guidance

**Comment by sudhanshutech** [comment]
@BarryByte any luck?

**Comment by Shubhf** [comment]
@sudhanshutech Can I take up this issue?

**Comment by Mandeep56Singh** [comment]
@sudhanshutech isn't there any command which can automate assigning issues to people. like .take for assigning issues ?

**Comment by Ashparshp** [comment]
@Mandeep56Singh, We generally provide access to assign issues to contributors who have shown consistent participation and commitment to the project. This ensures that the right people have the responsibility to manage issues effectively.

**Comment by Ashparshp** [comment]
@Shubhf, you have already pending issues, please get those done first.

**Comment by Ashparshp** [comment]
@BarryByte, as we haven't heard back from you, I've unassigned you.

**Comment by Ashparshp** [comment]
@Mandeep56Singh, intrested on taking?

**Comment by Mandeep56Singh** [comment]
@Ashparshp hmm...
ok

**Comment by THEBOSS0369** [comment]
Hey @leecalcote  @Ashparshp @sudhanshutech!
 Can i take this issue? I can work on this. Thanks

**Comment by Ashparshp** [comment]
@THEBOSS0369,

Go ahead please..
