### ISSUE TITLE
Rename the PlaceHolder Text

### ISSUE THREAD

**Issue by narasimha-1511** [layer5io/layer5#5738]
### Description

![image](https://github.com/user-attachments/assets/bfef1532-ba80-42f1-b472-f7dddf454167)
So here in the PlaceHolder the text is `PlaceHolder goes here` instead i think it should be `placeHolder`

You can check this here : https://layer5.io/projects/sistent/components/text-input

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by narasimha-1511** [comment]
let me confirm if the issue is valid @Ashparshp !

**Comment by hollermay** [comment]
I want to work on this issue @Ashparshp

**Comment by sanjanaynvsdl** [comment]
Hey @narasimha-1511,
can you please assign this issue ?

**Comment by siddharthbaleja7** [comment]
@Ashparshp can you please assign this issue to me?

**Comment by UtkershBasnet** [comment]
@narasimha-1511 I'd like to work on this issue

**Comment by Yash020405** [comment]
@narasimha-1511 I would like to resolve this issue

**Comment by ankur-kalita** [comment]
hey @narasimha-1511 I want to contribute to this project, could you please assign me this issue?

**Comment by Ashparshp** [comment]
@hollermay, @siddharthbaleja7, @UtkershBasnet, @Yash020405, @ankur-kalitaThank you all for your interest in working on this issue! We appreciate your enthusiasm. Please join us for the newcomers call today, where we'll confirm the validity of this issue and discuss it further.Additionally, we have several other issues in the Meshery and Docs projects that need attention. We encourage you to check them out and comment if you're interested in contributing. Your support is invaluable to our community.@narasimha-1511 Agree, we could address this in the newcomers call today. If we find it valid, we'll call for volunteers then.

**Comment by Ashparshp** [comment]
@hollermay, @siddharthbaleja7, @UtkershBasnet, @Yash020405, @ankur-kalita

Do you guys have your local setup ready?

@hollermay, since you're already working on an issue, we'll assign the next one in chronological order to the others!

**Comment by vexora-0** [comment]
hey @narasimha-1511 I would like to work on this

**Comment by siddharthbaleja7** [comment]
@Ashparshp Setup Done.

**Comment by Ashparshp** [comment]
@siddharthbaleja7 Assigned to you! Go ahead.

**Comment by sudhanshutech** [comment]
@vexora-0 thanks for pr  but please be aware next time that the issue was already assigned and he had already raised a pr. So you can review that pr. And its recommended that you can ask first to get any issue assigned.

**Comment by vexora-0** [comment]
sure @sudhanshutech
