### ISSUE TITLE
[Community] Member Profile: Muhammed Moinuddin

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5739]
**Current Behavior**

@Muhammed-Moinuddin  has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Muhammed-Moinuddin  as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub:  @Muhammed-Moinuddin
- Twitter: https://x.com/moin_TheCoder?t=ie3DABxFX5ep5c57esC4SQ&s=09
- LinkedIn:   https://www.linkedin.com/in/muhammad-moinuddin-software-developer/
- Layer5 Cloud:  https://meshery.layer5.io/user/dce018e4-dde0-4937-931f-b62de3fd5d42
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@Muhammed-Moinuddin Toss in your bio, profile picture and twitter, if you would :)

**Comment by sanjanaynvsdl** [comment]
Hey @narasimha-1511 can you please assign this issue to me?

**Comment by hargunkaur286** [comment]
@sanjanaynvsdl Sure, please go ahead!

**Comment by narasimha-1511** [comment]
Hey @hargunkaur286 as you have worked on similar issue , i am assigning this to @sanjanaynvsdl

**Comment by sanjanaynvsdl** [comment]
Hey @hargunkaur286,
I've created [PR](https://github.com/layer5io/layer5/pull/5746)  to address this issue. Please review it at your convenience.
