### ISSUE TITLE
[Project] Update Service Mesh Standards section on Meshery page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#574]
**Current Behavior**
This section on the [Meshery page](https://layer5.io/meshery#performance-spec) is in need of being refreshed.

**Desired Behavior**
- [ ] This section could do with an updated description of the SMPS initiative.
- [ ] The link in this section should point to the new https://smp-spec.io website.
- [ ] This section needs to use the new SMPS logo (see https://layer5.io/assets/resources/brand/smps-brand-kit.zip)

---
**Screenshot**
![Screen Shot 2020-08-03 at 7 30 40 PM](https://user-images.githubusercontent.com/7570704/89240115-c55f0f80-d5c0-11ea-8bed-f0d1efd4bdce.png)

---
** Layer5.io Resources**
This issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. 
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Atandanafiu** [comment]
I'd like to take this up

**Comment by PluckyPrecious** [comment]
Sure go ahead @Atandanafiu 👍🏽

**Comment by PluckyPrecious** [comment]
Hello @Atandanafiu how is it coming up? 😃

**Comment by Nikhil-Ladha** [comment]
@Neilblaze ?

**Comment by Nikhil-Ladha** [comment]
@leecalcote is there something that still needs to be done for this issue?
The only change which I understand here is the link to the new site, everything else is done, isn't it?
We have a PR #931 which does that, if anything else is left, can you please add there?
