### ISSUE TITLE
Missing Badges in Community Handbook

### ISSUE THREAD

**Issue by dextrot** [layer5io/layer5#5744]
### Description

The [recognition section ](https://layer5.io/community/handbook/recognition)in community handbook is missing badges
![image](https://github.com/user-attachments/assets/24619270-8201-4b5f-9723-e124cd93b17c)

### Expected Behavior

Updated list of badges from https://badges.layer5.io/
### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by BHAV0207** [comment]
hey , @dextrot I would like to work on this issue , please assign me this issue

**Comment by Dipti0704** [comment]
hey , @dextrot I would like to work on this issue, please assign me this issue

**Comment by MrPhenomenal3110** [comment]
Hey @dextrot , I would like to work on this issue.

**Comment by narasimha-1511** [comment]
as this is firstcome first serve i am assigning this to @BHAV0207
