### ISSUE TITLE
lint errors while running `npm run pretest`

### ISSUE THREAD

**Issue by narasimha-1511** [layer5io/layer5#5747]
### Description

There were lot of indentation and spacing errors while running `npm run pretest`

### Expected Behavior

There should be no indentation errors

### Screenshots

https://github.com/user-attachments/assets/c5ec01c7-301a-452a-9e85-a2c762f0f2f0

Just run `npm run preset` to reproduce the errors and fix them

### Environment:
- Host OS:
- Browser:

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by MrPhenomenal3110** [comment]
hey @narasimha-1511 I would like to work on this issue !

**Comment by narasimha-1511** [comment]
Go on @MrPhenomenal3110 🚀

**Comment by MrPhenomenal3110** [comment]
@narasimha-1511  After fixing all the other linting issues, the test files are throwing an error `'it' is not defined` when running `npm run pretest`. Also, I do not see any `test` script in the `package.json`.

**Comment by Ashparshp** [comment]
@MrPhenomenal3110, any luck?

**Comment by MrPhenomenal3110** [comment]
> @MrPhenomenal3110, any luck?

No. I have been busy with my work. I did not get enough time to think about this.
