### ISSUE TITLE
Update SMPS project page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#575]
The [project page](https://layer5.io/projects/performance) and the project card for SMPS on the layer5.io site needs to be updated with the new SMPS logo. The logo can be found in the [SMPS brand kit](https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smps-brand-kit.zip).

![Screenshot_2020-08-04 Service Mesh Performance Specification](https://user-images.githubusercontent.com/34476976/89242160-7b0c7b80-d61e-11ea-8ef3-8b3f0ac96cdb.png)

**Comment by Nraj923** [comment]
Can I make a contribution for this?

**Comment by leecalcote** [comment]
@Nraj923 that would be excellent, yes. 👍

**Comment by leecalcote** [comment]
@Nraj923 Thanks for taking this on. I welcome you to join the Layer5 community - http://slack.layer5.io. Lot's of friendly, helpful contributors here.

**Comment by Rohan-GD** [comment]
is this closed, i would like to try it out too

**Comment by leecalcote** [comment]
Nope, it's still open. Yes, @Rohan-GD. That would be great. Thank you.

**Comment by Rohan-GD** [comment]
Alright thanks, I'll try to finish as early as possible

**Comment by Rohan-GD** [comment]
Also, this is my first time contributing and I have some doubts regarding where the website code is..

**Comment by leecalcote** [comment]
@Rohan-GD sure, no problem. Two things:

1. you're welcome to join the community Slack - http://slack.layer5.io
1. the source for the page is here - https://github.com/layer5io/layer5/blob/master/collections/_projects/service-mesh-performance.md and here and her - https://github.com/layer5io/layer5/blob/master/collections/_pages/service-mesh-performance.html (two spots)

**Comment by Rohan-GD** [comment]
Alrighty
