### ISSUE TITLE
Update Code_Of_Conduct.md

### ISSUE THREAD

**Issue by Swarnim114** [layer5io/layer5#5766]
## Enhance Code of Conduct
The current CODE_OF_CONDUCT.md file requires updates to better reflect our community standards. This pull request aims to improve the code of conduct, ensuring a more inclusive and respectful environment for all contributors.

### Expected Changes

    Revise the code of conduct to align with industry best practices
    Clarify expectations for behavior and communication
    Add or remove sections as necessary to ensure comprehensive coverage

Reference
Please review the current CODE_OF_CONDUCT.md file: 
![image](https://github.com/user-attachments/assets/f0c3f644-676f-4d51-87c6-de6c2956bccf)

**Comment by Swarnim114** [comment]
I would like to work on this

**Comment by Ashparshp** [comment]
@Swarnim114 Nice enhancement! Was this requested, or did you do it on your own?

**Comment by Swarnim114** [comment]
@Ashparshp No explicit request, but I saw room for improvement and took the liberty of raising a PR as it was an easy to do change.  Hope this is okay!

**Comment by Ashparshp** [comment]
Thanks @Swarnim114!

**Comment by sudhanshutech** [comment]
is this needed @vishalvivekm ?

**Comment by vishalvivekm** [comment]
Usually, changes to areas related to governance and code of conduct aren't made unless specifically asked.
We'll review these changes on upcoming websites meeting // @Ashparshp

**Comment by Ashparshp** [comment]
@vishalvivekm Yes, there's nothing significant changed, just a reformation of the text for better visuals and readability, adding headings and numbers.
