### ISSUE TITLE
Components is not center for larger screen

### ISSUE THREAD

**Issue by amitamrutiya** [layer5io/layer5#5775]
### Description
On this [link](https://layer5.io/projects/sistent/components) the component section is not centered on larger screens, although it is centered on normal screens.

### Expected Behavior
The component section should be centered on all screen sizes.

### Screenshots
![image](https://github.com/user-attachments/assets/04041b0b-9cc8-48f0-b4df-aacd93156ccd)

### Addtional Information
If you find this issue valid, I would like to fix it.

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by SarthakPaandey** [comment]
I want to work on this issue. May you assign this to me @amitamrutiya ?

**Comment by amitamrutiya** [comment]
Hey @SarthakPaandey,

Thanks for showing interest in solving this issue. I am currently waiting for confirmation from the maintainers. If they find this issue valid, I will start working on it. In the meantime, you can look for other issues to work on.

**Comment by Sushant9473** [comment]
i want to work on this issue .

**Comment by narasimha-1511** [comment]
Hey @Sushant9473 let's discuss this on the website's call. Please add this as an agenda item to the [meeting minutes](https://docs.google.com/document/d/1XczAHXVe2FIWPqiF57ospJ43zw5cZQ7ui8mn39v5EvA/edit?usp=drivesdk).
and i am assigning this is @Sushant9473  as he has raised a PR , but from now remember to get the issue assigned to you before you work on this.
