### ISSUE TITLE
Issue: HTML and Markdown Mixing 

### ISSUE THREAD

**Issue by Manan21st** [layer5io/layer5#5778]
Description: Your document combines HTML and Markdown elements, such as using "p" and "h2" tags alongside Markdown headings (e.g., # for headings). This mix can lead to inconsistent rendering across different platforms or tools. It's generally best to use one method consistently throughout the document to ensure uniform appearance and avoid potential display issues. For example, if you use Markdown for headings, stick with Markdown for paragraphs and lists as well, rather than switching to HTML.

**Comment by TUSHAR1651** [comment]
@narasimha-1511 PLease assign this Issue to me

**Comment by narasimha-1511** [comment]
can you please elaborate the issue @Manan21st ?

**Comment by Manan21st** [comment]
> can you please elaborate the issue @Manan21st ?

for example, can you change this?

<img width="796" alt="image" src="https://github.com/user-attachments/assets/b1c2a0ea-f850-4eaf-9a54-580f10e1a2f4">

**Comment by narasimha-1511** [comment]
ok! Go on @TUSHAR1651 🚀

**Comment by sudhanshutech** [comment]
@Manan21st please be more descriptive where is the issue and why its needed. Lets close this issue for now , please do create a new issue if required again and if you want to know is it required or not please create a topic at discuss forum or join our website meetings to discuss this issue.
