### ISSUE TITLE
Create link to author profile

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#578]
**Current Behavior**
All blog posts have authors. When a post's author also has a member profile within the [_members collection](https://github.com/layer5io/layer5/tree/master/collections/_members) the author name should be hyperlinked to a page displaying their profile.

**Desired Behavior**
The member profiles are available at https://layer5.io/community/members/<author-name>. The blog post author name should link to this page, when the author's name matches the name of an existing member. Otherwise, leave the author name without a hyperlink.

Author name missing hyperlink:
<img width="616" alt="Screen Shot 2020-08-04 at 4 30 56 PM" src="https://user-images.githubusercontent.com/7570704/89347763-fdbe2680-d670-11ea-9f0d-fc0512e34ddd.png">

**Related issue: #579**

**Comment by Neilblaze** [comment]
@leecalcote the link for member profiles i.e. `https://layer5.io/community/members/` is invalid. Can you please update the link?

**Comment by Neilblaze** [comment]
I guess issue #579 needs to be solved first then anyone can hop into [#578](https://github.com/layer5io/layer5/issues/578) :smile:

**Comment by Kennygrace** [comment]
I'll like to take this up, if it's still open @leecalcote

**Comment by Kennygrace** [comment]
Okay then

**Comment by PluckyPrecious** [comment]
Hello @kishore007k @Kennygrace would anyone of you like to work on this? We found a way to run Jekyll on Windows, do ping me on slack.🤝

**Comment by kishore007k** [comment]
@PluckyPrecious Yeah I'm up for it! Will give it a try.

**Comment by PluckyPrecious** [comment]
Awesome 😎 I’ll assign you.

**Comment by Nikhil-Ladha** [comment]
Closed #795
