### ISSUE TITLE
Broken Link  CNCF in Partner Page .. 

### ISSUE THREAD

**Issue by Jash2606** [layer5io/layer5#5780]
### Description
There is a broken link on the partner page for CSCF. You can find the issue on the [partners](https://layer5.io/partners).

### Expected Behavior
The link should navigate to the correct and functional page.

### Screenshots

![Screenshot 2024-08-04 115545](https://github.com/user-attachments/assets/c65880f9-20f7-4f65-8372-44c89085cc76)

## Note: 
I will be working on this issue, so please do not request assignment. Thank you.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Jash2606** [comment]
I want to work on this issue can i get the correct link for this one @vishalvivekm @leecalcote

**Comment by kauxp** [comment]
Can you please assign this to me?

**Comment by Jash2606** [comment]
> Can you please assign this to me?

I will be Working on this issue !!

**Comment by leecalcote** [comment]
There’s no need yell, @Jash2606

**Comment by leecalcote** [comment]
@Jash2606 thanks for filing this issue. Please make haste in resolving it. 

@hargunkaur286, if this issue isn’t fixed by tomorrow, will you please fix it? 404s like this are a relatively high priority.

**Comment by hargunkaur286** [comment]
> @Jash2606 thanks for filing this issue. Please make haste in resolving it.
> 
> @hargunkaur286, if this issue isn’t fixed by tomorrow, will you please fix it? 404s like this are a relatively high priority.

Sure @leecalcote 📝

**Comment by Jash2606** [comment]
> @Jash2606 thanks for filing this issue. Please make haste in resolving it.
> 
> @hargunkaur286, if this issue isn’t fixed by tomorrow, will you please fix it? 404s like this are a relatively high priority.

Hey @leecalcote ,

It appears that the name 'layer5' is not listed among the CNCF members in the screenshots provided, although 'meshery' is present. Should we consider 'meshery' under the 'layer5' organization for this matter?
LAYER5:
![Screenshot 2024-08-05 181715](https://github.com/user-attachments/assets/b8b669a2-c3c1-4fb3-943d-f86cea92c2c3)
MESHERY:
![Screenshot 2024-08-05 181729](https://github.com/user-attachments/assets/1947f80f-8048-4830-a204-b18ad29a5580)

**Comment by Jash2606** [comment]
Hey @leecalcote , 

I had raised a pr for this issue , Could you review it and let me know if any further changes needed .
