### ISSUE TITLE
Empty tag found in getting started learn page

### ISSUE THREAD

**Issue by amitamrutiya** [layer5io/layer5#5786]
### Description
Link: [Learn Getting Started Page](https://layer5.io/learn/learning-paths/mastering-service-meshes-for-developers/introduction-to-service-meshes/istio/getting-started)
An empty tag found in step 3 doesn't represent anything.

### Expected Behavior
It should be removed.

### Screenshots
![image](https://github.com/user-attachments/assets/10d96896-6667-4622-98ac-757d2ebf81f8)

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by amitamrutiya** [comment]
If you find this issue valid then I want to work on this.

**Comment by siddharthbaleja7** [comment]
@narasimha-1511 Can you please assign this issue to me?
