### ISSUE TITLE
Not able to get back on mobile screen

### ISSUE THREAD

**Issue by amitamrutiya** [layer5io/layer5#5789]
### Description
Link: [Layer5 Sistent page](https://layer5.io/projects/sistent/about)
When visiting this sistent all pages on a mobile device, pressing the back arrow or the table of contents text does not return the user to the previous screen.

### Expected Behavior
The user should be able to return to the previous screen.

### Screenshots
![image](https://github.com/user-attachments/assets/be95178e-a9f7-4939-a231-5642ef5a9347)

### Environment:
- Host OS: Linux
- Browser: Firefox

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by amitamrutiya** [comment]
If you find this issue valid then I want to work on this.

**Comment by vishalvivekm** [comment]
@Muhammed-Moinuddin didn't you have one PR fixing this ? did we get that merged ?

**Comment by Muhammed-Moinuddin** [comment]
> @Muhammed-Moinuddin didn't you have one PR fixing this ? did we get that merged ?

Yup it is resolved. Not merged as it needs some enhancement yet.
