### ISSUE TITLE
Community member profile page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#579]
**Current Behavior**
Individual pages are generated for each person in the [_members collection](https://github.com/layer5io/layer5/tree/master/collections/_members) at https://layer5.io/community/members/<member-name>. Each member page is blank, though, because there is no HTML snippet that has been created to present a member's profile (e.g.,`{% include member.html %}` ).

**Desired Behavior**
Create a `member-html` and a `members-list.html` in order to present the "_members" collection and display a member's profile.

**Related Issue: #578**

---
**Resources**

This issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@Neilblaze up for the challenge?

**Comment by Neilblaze** [comment]
Yeah I would love to :smile: . But it may take a bit long as my semester will be starting tomorrow onwards. Hope it feels ok :smiley:

**Comment by leecalcote** [comment]
No sweat. School _always_ comes first.
