### ISSUE TITLE
Some of the Academic Partners logo is not working.

### ISSUE THREAD

**Issue by srivastavaarpit977** [layer5io/layer5#5791]
###Current Behaviour:
Some of the academic partners logo is not working...i.e when you click to see the academic partner ...it is not clickable.

###Expected:
All the Academic Partners logo should be working.

P.S..(I will be working on this issue..Thanks)

**Comment by srivastavaarpit977** [comment]
I want to work on this issue , 

@leecalcote @vishalvivekm  , Could you assign me this issue!

**Comment by sudhanshutech** [comment]
@srivastavaarpit977 please explain the issue properly . Specific logos ...

**Comment by Ashparshp** [comment]
@srivastavaarpit977, Please mention the steps to reproduce the issue, and if possible, include the URL along with screenshots to help us understand better.

**Comment by siddharthbaleja7** [comment]
@srivastavaarpit977 Any updates on this?

**Comment by Ashparshp** [comment]
Not clear! Closing it.
