### ISSUE TITLE
[Community] Member Profile: Please invite me to the community 

### ISSUE THREAD

**Issue by andrisecops** [layer5io/layer5#5798]
**Current Behavior**

<@andrisecops> has been a consistent contributor and community member.

**Desired Situation**
Let's recognize <@andrisecops> as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: andrisecops
- Twitter: andrisecops
- LinkedIn: andrimuda
- Layer5 Cloud: 
- Link to profile picture:

Thank you for accepting me as a member of your organization, for that let me introduce myself. my name is ANDRI, I have a high curiosity, a strong willingness to learn and like to do development. my current job `Part-time Cybersecurity Research` can be said that this work is a hobby for me. I also have a personal blog and I am currently focusing on creating a travel website and bug bounty through programs such as hackerone, and bugcrowd. I would love to get an offer to work at your company and or maybe an offer to do web pentesting for your company.

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by mannika763** [comment]
@andrisecops 
i would like to work on this issue.

**Comment by BarryByte** [comment]
@sudhanshutech @blake Please assign this issue to me. Thanks.

**Comment by andrisecops** [comment]
yes

**Comment by sudhanshutech** [comment]
@andrisecops  it's great to see your interest in getting invited! However, there's a process for obtaining a member profile. Member profiles are a form of recognition for contributors who have consistently contributed over time. When you meet those criteria, the community managers will automatically create an issue and send an invitation.

Let's close this issue for now @BarryByte .
