### ISSUE TITLE
[Event] Add Enlightning episode

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5808]
Please add the following event to layer5.io/events.

**Event:**
- Event Title: Infrastructure as Design by Meshery
- Event Link: https://www.linkedin.com/feed/update/urn:li:activity:7229161401427062785
- Talk Description: Meshery is a self-service engineering platform that enables the collaborative design and operation of cloud and cloud native infrastructure. With over 320 built-in integrations, Meshery seamlessly integrates with every CNCF project and your existing tools, across multiple clouds and Kubernetes clusters. 
 
Join host Whitney Lee and guest Lee Calcote to learn more! 
 

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h4>Contributor Resources</h4>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by BHAV0207** [comment]
I would like to work on this issue @leecalcote
