### ISSUE TITLE
[UI] Found Invalid read more button

### ISSUE THREAD

**Issue by amitamrutiya** [layer5io/layer5#5814]
### Description
Link: https://layer5.io/community/adventures-of-five-and-friends
When we hover over the following card, the "Read More" button appears but does not redirect anywhere.
- Planet Prometheus
- Planet Jaeger
- Planet Meshery

### Expected Behavior
If no link is available to attach, remove it.

### Screenshots
![image](https://github.com/user-attachments/assets/564b1882-f2d0-4a47-a016-cec692c66436)

### Environment:
- Host OS: Linux
- Browser: Firefox

### If you find this issue valid, I want to work on it.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by kdotmanoj** [comment]
@amitamrutiya can i please work on this issue ;
)
