### ISSUE TITLE
[Community] Member Profile: Ijeoma Eti

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#5825]
**Current Behavior**

@Aijeyomah has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Aijeyomah as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @Aijeyomah
- Twitter: https://twitter.com/EtiIjeoma
- LinkedIn: https://www.linkedin.com/in/ijeoma-eti
- Layer5 Cloud: 
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by vishalvivekm** [comment]
@aijeyomah
Toss in your bio, profile picture and link to your Layer5 cloud profile, if you would, please.

**Comment by Aijeyomah** [comment]
> @Aijeyomah Toss in your bio, profile picture and link to your Layer5 cloud profile, if you would, please.

Profile Picture: https://ibb.co/vPHgytG

**Comment by Ashparshp** [comment]
Cloud ID: https://meshery.layer5.io/user/551da661-8632-415f-b69f-ecb298b88575

**Comment by hollermay** [comment]
@Ashparshp Can I do this?

**Comment by vishalvivekm** [comment]
> @Ashparshp please assign me this issue, I'll do it

Thank you @hollermay 
I see you currently have one existing assignments

**Comment by ShivanshuGupta07** [comment]
@Ashparshp can you assign me this?

**Comment by Ashparshp** [comment]
@hollermay, we appreciate your enthusiasm! Let's first focus on the issue that's currently assigned to you. If you need any help with that, feel free to reach out. we're here to assist. This particular issue is quite basic, so we'd like to give newcomers a chance to contribute. I hope you understand!

**Comment by Ashparshp** [comment]
@ShivanshuGupta07, do you have your local setup ready?

**Comment by ShivanshuGupta07** [comment]
@Ashparshp Sorry.. currently not, but I will do it

**Comment by Ashparshp** [comment]
@ShivanshuGupta07, get it done and if face issue while setting up.. ask for it please!

**Comment by Himanshu-kiran** [comment]
@Ashparshp Will be thankful if you could share the docs & things exactly to follow for setting up locally
(Want to work on migration and frontend project)

**Comment by vishalvivekm** [comment]
Here's the setup guide : 
1. https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#prerequisites
2. [Video] Step by step setup guide for Windows: https://m.youtube.com/watch?v=uwqIgdy82Wo
3. Check out [community forum](https://discuss.layer5.io) and search for any issues you're running into, you'll find several existing answers / posts, otherwise simple crack open a new topic.

**Comment by Shubhf** [comment]
Hey @Ashparshp Can I take up this issue?

**Comment by Ashparshp** [comment]
@ShivanshuGupta07, are you ready with the setup? Or we can move to the next one in queue?

**Comment by ShivanshuGupta07** [comment]
@Ashparshp , I am done with understanding the code, but I am not available till Monday, so to can move this task to someone. Thankyou @Ashparshp

**Comment by Ashparshp** [comment]
@Himanshu-kiran, do you have your local setup ready?

**Comment by sparshagl** [comment]
Hi @Ashparshp, could I contribute to this as my first issue?

I'm just trying to get familiar with the community and have already set up a working local development environment for the project.

In case there's already someone working on this, could you point me to other similar issues as a first-time contributor?
