### ISSUE TITLE
[Handbook] Update Repository Overview to mark meshery-smi-conformance-action as archived

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5832]
### Current Behavior
This repo is now archived - https://github.com/layer5io/meshery-smi-conformance-action

### Desired Situation
The https://layer5.io/community/handbook/repository-overview page should reflect this archived status.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by H-A-R-S-H-K** [comment]
@leecalcote can i work on this?

**Comment by Ashparshp** [comment]
@H-A-R-S-H-K, go ahead.

**Comment by leecalcote** [comment]
Thanks!
