### ISSUE TITLE
[Community] Member Profile for Ankita Sahu

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5834]
**Current Behavior**

@SAHU-01 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @SAHU-01 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/SAHU-01
- Twitter: https://x.com/asahu_dev
- LinkedIn: https://www.linkedin.com/in/asahudev/?original_referer=https%3A%2F%2Fgithub.com%2F
- Layer5 Cloud: https://meshery.layer5.io/user/ff1f8398-e501-4bb2-817f-80edffd0d37b
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by siddharthbaleja7** [comment]
@hargunkaur286 Can you assign this to me?

**Comment by hargunkaur286** [comment]
@SAHU-01 can you please provide with link to your profile picture

**Comment by hargunkaur286** [comment]
Sure, @siddharthbaleja7 please go ahead!

**Comment by Spoorthy1423** [comment]
Hey!! @hargunkaur286 i would love to work on this issue, can u please assign me!!

**Comment by siddharthbaleja7** [comment]
@hargunkaur286 Any updates about the profile picture?

**Comment by SAHU-01** [comment]
> @SAHU-01 can you please provide with link to your profile picture

Sure you can find a link to my image below, 
Image: https://drive.google.com/file/d/1r3aYfIe7hZhztSz_rIrgZjm0znBiUpJH/view?usp=sharing

Apologies for the delay @siddharthbaleja7  and thanks for working on it!

**Comment by sudhanshutech** [comment]
@siddharthbaleja7 done?

**Comment by siddharthbaleja7** [comment]
@sudhanshutech Yes Done.
