### ISSUE TITLE
[Community] Member Profile of Jerens Lensun

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5835]
**Current Behavior**

@jerensl has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @jerensl as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/jerensl
- Twitter: https://x.com/jerensl22
- LinkedIn: https://www.linkedin.com/in/jerensl
- Layer5 Cloud: https://meshery.layer5.io/user/2e246a4a-11e3-4b99-8c79-e42f8565e4be
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by hargunkaur286** [comment]
@jerensl Do you mind adding link to your profile picture please, if you would

**Comment by siddharthbaleja7** [comment]
@hargunkaur286 Can you please assign this to me?

**Comment by hargunkaur286** [comment]
@siddharthbaleja7 since you have been assigned a similar issue, let's give chance to new contributors please..

**Comment by narayanibokde9** [comment]
@hargunkaur286 could you please assign this issue to me?

**Comment by jerensl** [comment]
Thanks for making this one for me. 

Here is the link to my profile picture: https://drive.google.com/file/d/17VU0ZkaUIQbZVsN9dV81CtKMFV35HpHo/view?usp=sharing

**Comment by Spoorthy1423** [comment]
Hey!! @hargunkaur286 i would love to work on this issue, can u please assign me!!

**Comment by hargunkaur286** [comment]
@Spoorthy1423 may I know if you have the repository setup locally?

**Comment by Spoorthy1423** [comment]
I am on it, may i know the next steps to be followed!

**Comment by hargunkaur286** [comment]
Once you confirm that you have the repository setup locally, we can assign you the issue. Make sure to join our [Slack](https://layer5io.slack.com/) channel if you have any queries.

**Comment by Spoorthy1423** [comment]
Yes!! i had setup this repo in local, please assign me this issue!!

**Comment by hargunkaur286** [comment]
Go ahead @Spoorthy1423 🚀

**Comment by Spoorthy1423** [comment]
Hey!! @hargunkaur286 can u review my pr please!! i would love to work on this issue further..
