### ISSUE TITLE
[Community] Member Profile of Aviral Asthana

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5836]
**Current Behavior**

@Aviral0702 has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @Aviral0702 as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/Aviral0702
- Twitter: 
- LinkedIn: https://www.linkedin.com/in/aviral-asthana-02b70824b/
- Layer5 Cloud: https://meshery.layer5.io/user/3f770688-e487-45c2-943b-c94b950d3d69
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by hargunkaur286** [comment]
@Aviral0702 do you mind adding link to your profile picture please, if you would

**Comment by Aviral0702** [comment]
Yes, adding the link

**Comment by anshikavashistha** [comment]
@hargunkaur286 May I work on this ?

**Comment by Spoorthy1423** [comment]
Hey!! @hargunkaur286 i would love to work on this issue, can u please assign me!!

**Comment by hargunkaur286** [comment]
Since we follow the First come first rule to assign issues, @anshikavashistha may I know if you have the repository setup locally? @Spoorthy1423 I'll assign you other issue

**Comment by anshikavashistha** [comment]
@hargunkaur286  Yes I have set up the repo locally

**Comment by hargunkaur286** [comment]
Please go ahead @anshikavashistha 🚀

**Comment by Ashparshp** [comment]
@anshikavashistha, any luck?

**Comment by sudhanshutech** [comment]
@anshikavashistha still working?

**Comment by balagowda** [comment]
@anshikavashistha I noticed you were working on this issue. Are you still actively working on it? If not, I would be interested in taking it over.

**Comment by Ashparshp** [comment]
@anshikavashistha, I don't see anything particularly unique about this. If you're facing any issues while working on it, please let us know. If we don't hear back from you, we'll assume you're not good to go and might assign the task to someone else.

**Comment by sudhanshutech** [comment]
@balagowda lets get you on this issue

**Comment by anshikavashistha** [comment]
PTAL @Ashparshp @sudhanshutech

**Comment by balagowda** [comment]
@Aviral0702, could you share a short bio would be great. Thanks!
