### ISSUE TITLE
[Community] Member Profile for Amit Amrutiya

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5838]
**Current Behavior**

@amitamrutiya has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @amitamrutiya as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: https://github.com/amitamrutiya
- Twitter: https://x.com/AmitAmrutiya2
- LinkedIn: https://www.linkedin.com/in/amit-amrutiya-109b19241
- Layer5 Cloud: https://meshery.layer5.io/user/f78208b9-fe7f-4e4c-8f16-cd70453b5cd6
- Link to profile picture:

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by hargunkaur286** [comment]
@amitamrutiya do you mind adding link to your profile picture please, if you would..

**Comment by amitamrutiya** [comment]
Thank you so much, Team! I'm truly honored to be recognized. Excited to be a part of this amazing community and looking forward to continuing our journey together! 🎉"

Profile Image :  https://github.com/user-attachments/assets/f2c36dec-f52f-4c8e-bf8f-66b698f381bf

**Comment by narayanibokde9** [comment]
@hargunkaur286 could you please assign this to me? Thank you.

**Comment by hargunkaur286** [comment]
Thank you for sounding off @narayanibokde9 ! May I know if you have the repository set up locally?

**Comment by Spoorthy1423** [comment]
Hey!! @hargunkaur286 i would love to work on this issue, can u please assign me!!

**Comment by Ashparshp** [comment]
Go ahead @Spoorthy1423..

**Comment by Ashparshp** [comment]
@Spoorthy1423, since you've already worked on this same issue, let's give someone else a chance to try and solve it. Hope that's okay with you?

**Comment by digvijay3184** [comment]
I want to work on this issue ,  plz assign this to me .

**Comment by hargunkaur286** [comment]
@digvijay3184 may i know if you have respository setup?

**Comment by Dip-Gyawali** [comment]
I want to work on this issue please assign it to me .

**Comment by hargunkaur286** [comment]
@Dip-Gyawali do you have the repository setup locally?

**Comment by Dip-Gyawali** [comment]
@hargunkaur286  yes

**Comment by hargunkaur286** [comment]
Go ahead @Dip-Gyawali 🚀

**Comment by Dip-Gyawali** [comment]
@hargunkaur286  i have already created a pull request
