### ISSUE TITLE
[Blog] Meet the Maintainer: Hussaina Begum

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5884]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Description:**
We are continuing our series of "Meet the Maintainer" and would like to add the interview post of Hussaina Begum, who is one of our Meshery Maintainers under the [blogs](https://layer5.io/blog) section.

You can refer to other [blog posts](https://layer5.io/blog/open-source/meet-the-maintainer-xin-huang) for maintainers and similarly write the blog by referring this [document](https://docs.google.com/document/d/194TgTNuRx6xblgqhpoV3HuhSq8RfHeAXyLbI1v-8OoA/edit) for the blog post.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by TechSenseiX** [comment]
I am eager to work on this

**Comment by hargunkaur286** [comment]
Thank you for volunteering @TechSenseiX Please go ahead! 🚀
