### ISSUE TITLE
[Event] Hacktoberfest 2023: disable signup form

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5888]
### Current Behavior
The signup form needs to be disabled on this event page - https://layer5.io/community/events/hacktoberfest-prep-2023-easing-into-cncf-open-source-projects (set `register` to false).

### Desired Situation
Also, the event should no longer be `upcoming`.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sashhh31** [comment]
can you assign me with this ?

**Comment by Kneatrum** [comment]
Hi @leecalcote , I would like to work on this issue. Can you please assign it to me?

**Comment by leecalcote** [comment]
You bet. Assigning in chronological order…
