### ISSUE TITLE
[sistent] Add `CustomTooltip` component to the sistent components page

### ISSUE THREAD

**Issue by dragon-slayer875** [layer5io/layer5#5890]
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [CustomTooltip](https://github.com/layer5io/sistent/blob/a930045dd84d8ea45d9026ef1da98d107d66a49d/src/custom/CustomTooltip/customTooltip.tsx).
![image](https://github.com/user-attachments/assets/e4b49ddb-b7ac-4c7d-af31-cc258163616f)

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The CustomTooltip comopnent currently needs this representation.

### Desired Behavior

Proper documentation for `CustomTooltip` component similar to `Button` component on  https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation about the various component props and their expected values
- Code examples for the various variants that a component might have (if any).

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Vidit-Kushwaha** [comment]
Hi @leecalcote I would like to work on this issue.
