### ISSUE TITLE
[Landscape] Add OSM to the service mesh landscape

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#591]
**Current State:**
Currently, the landscape page of the layer site lists all known service meshes. But, as OSM was introduced recently, the page lacks that mesh!

**Desired State:**
OSM should be added to the landscape, with complete details in the appropriate part of the landscape.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)

@phillipgibson , @lachie83

**Comment by leecalcote** [comment]
@phillipgibson thanks for considering making a PR to have OSM represented in the [service mesh landscape](https://layer5.io/landscape). We encourage representatives of the projects/products in the landscape to curate and maintain their listings so as to guarantee their freshness and accuracy of representation. See the [instructions for updating the landscape]([here](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)).

**Comment by Nikhil-Ladha** [comment]
Hello @phillipgibson, if you could help us out in adding these details in the landscape at the earliest it would be very grateful :)
Or, if you have already planned out to update it in a day or so. That's also fine!

**Comment by phillipgibson** [comment]
@leecalcote am I just editing the meshes.yml file?

**Comment by Nikhil-Ladha** [comment]
> @leecalcote am I just editing the meshes.yml file?

Yes @phillipgibson . Also, if you could add the details in the non-functional.yml file that would be great, you can leave out the icon, weight field there.

**Comment by Nikhil-Ladha** [comment]
Hi @phillipgibson , any updates over here?

**Comment by PluckyPrecious** [comment]
Hi @Nikhil-Ladha, if it’s okay i could give a hand.

**Comment by Nikhil-Ladha** [comment]
> Hi @Nikhil-Ladha, if it’s okay i could give a hand.

For what @PluckyPrecious ?

**Comment by phillipgibson** [comment]
ok will PR this soon

**Comment by Nikhil-Ladha** [comment]
> ok will PR this soon

Thank you!🙂
