### ISSUE TITLE
[Handbook] Repository Overview: Background color for archived projects

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#5926]
### Current Behavior
The [Repository Overview page](https://layer5.io/community/handbook/repository-overview) found in the Community Handbook lists most of the projects that are steward by the community and their respective GitHub repositories.

### Desired Situation
Ideally, archived projects are visually offset from other projects somehow, like having a dark or disabled gray color in their table row background.

<img width="74" alt="Screenshot 2024-09-24 at 6 22 49 PM" src="https://github.com/user-attachments/assets/3a6f366f-0d17-4187-a631-5fd282e03f3c">

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Kneatrum** [comment]
I would like to work on this

**Comment by Ashparshp** [comment]
Thanks, @Kneatrum...
Go ahead!
