### ISSUE TITLE
Replace logos in user profile

### ISSUE THREAD

**Issue by Touriist** [layer5io/layer5#5938]
### Current Behavior

in user profile dropdown items: 
![image](https://github.com/user-attachments/assets/5f9a9103-2ed6-48de-93f0-0942ab5005e0)

### Desired Situation

- for Cloud, replace Meshery logo with 5 of Layer5: 
https://raw.githubusercontent.com/layer5io/layer5/refs/heads/master/src/assets/images/layer5/5%20icon/svg/light/5-light-bg.svg
- for Playground, replace the icon with Meshery logo.
---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Dhirendra012** [comment]
please assign this issue to me

**Comment by Touriist** [comment]
> please assign this issue to me

will you confirm, if you have set up the site or need  help in doing so?

**Comment by Dhirendra012** [comment]
Yes , I have setup the site

**Comment by Touriist** [comment]
> Yes , I have setup the site

Thank you @Dhirendra012
