### ISSUE TITLE
[Sistent] Add Typography component to the sistent components page

### ISSUE THREAD

**Issue by dragon-slayer875** [layer5io/layer5#5949]
### Current Behavior

Layer5 and it's projects use [Sistent](https://github.com/layer5io/sistent) library to enable easy component reusability among our various projects.
One such component is [Typography](https://github.com/layer5io/sistent/blob/5529c342c6ad2b00b8e8d08deafc02fe72fe5513/src/base/Typography/Typography.tsx).

https://playground.meshery.io/
![image](https://github.com/user-attachments/assets/37b75542-f8a0-4251-9a90-fe6bb9431f62)

Ideally, all sistent components are represented on https://layer5.io/projects/sistent/components, so a centralized usage and example documentation can be maintained. This will aid new developers to more quickly jump into contributing to the various projects.
The Typography component currently needs this representation.

### Desired Behavior

Proper documentation for Typography component similar to Button component on https://layer5.io/projects/sistent/components
The documentation should include:
- Explanation of the the function that the component serves in context of it's usage.
- Code examples.
- Stylistic guidelines to be followed while using the component in code (if any).

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 🎨 See [Sistent Repository](https://github.com/layer5io/sistent).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by mdkaifansari04** [comment]
@dragon-slayer875  I would like to work on this issue

**Comment by dragon-slayer875** [comment]
@vishalvivekm @sudhanshutech can you please assign this issue to @mdkaifansari04 ?
I seem to not have assignment rights.

**Comment by mdkaifansari04** [comment]
I'm working on the issue, got busy with some college stuff

**Comment by vishalvivekm** [comment]
> I'm working on the issue, got busy with some college stuff

Thank you for sounding off @mdkaifansari04 👍

**Comment by sudhanshutech** [comment]
@mdkaifansari04 seems its a mistake from our side. Typography is already there added so may be we have missed that. Lets get you assigned to  other issue. There are few other issues in this area which are unassigned so you can ask to work for that.

**Comment by mdkaifansari04** [comment]
@sudhanshutech I'm not sure if it is present in the current branch
![image](https://github.com/user-attachments/assets/ecc03b2c-4f7d-470b-ac5d-73a866df51b2)
