### ISSUE TITLE
Add entry for Open Service Mesh on layer5.io/meshery

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#595]
**Current Behavior**
Meshery has an alpha adapter for Open Service Mesh in the `meshery-osm` repo.

**Desired Behavior**
This alpha state adapter should be represented on meshery.io

OSM logo - 
[osm.svg.zip](https://github.com/layer5io/meshery.io/files/5039020/osm.svg.zip)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by PluckyPrecious** [comment]
Opss! 😮 @leecalcote I think did this while working on #612

**Comment by leecalcote** [comment]
Ah, yes. Nice work, @PluckyPrecious
