### ISSUE TITLE
Animation vanishes on scrolling

### ISSUE THREAD

**Issue by hargunkaur286** [layer5io/layer5#5985]
### Description

In [this](https://layer5.io/cloud-native-management/meshery/operating-cloud-native-infra) page, when we scroll through the page, the animation shows up for a second and then vanishes away. 

### Expected Behavior

We want the animation to load properly and not vanish away, when we scroll down the page.

### Screenshots

https://github.com/user-attachments/assets/ef567bd3-e7a0-414a-91d7-e83f4e1e638c

### Environment:
- Host OS: MacOs
- Browser: Google Chrome, Safari

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vishalvivekm** [comment]
@hargunkaur286 let's make a call for Volunteers on today's call.

**Comment by deepikaa0402** [comment]
Hi! Can you please assign this issue to me

**Comment by Aryam2121** [comment]
can you please assign to me

**Comment by hargunkaur286** [comment]
@deepikaa0402 @Aryam2121 Thank you for sounding off. Do you mind telling if you have the repository setup?

**Comment by Aryam2121** [comment]
yes i have repository Setup and you assign to me please

**Comment by hargunkaur286** [comment]
Go ahead @Aryam2121 :)

**Comment by Aryam2121** [comment]
please accept my twitter request i want to know something more about this @hargunkaur286

**Comment by Aryam2121** [comment]
hey @hargunkaur286  please follow back me on twitter i want to dm for some kind information i ask for this issue

**Comment by vishalvivekm** [comment]
@Aryam2121 
Please note that all issue-related discussions should be kept public and within this GitHub issue thread.
You can also discuss them in:
1. `#websites` channel in Layer5's Slack community at https://slack.layer5.io.
2. Our discussion forum https://discuss.layer5.io/
3. Weekly website meetings on Mondays at [meet.layer5.io](https://meet.layer5.io/)

Before proceeding further, please:
 - Fork the repository and set up the project locally (it looks like you haven't forked the project yet)
 - Review our contributor handbook for [guidelines on contributing](https://layer5.io/community/handbook/contribution) and [code of conduct](https://layer5.io/community/handbook).

**Comment by Anand-Theertha** [comment]
Hey @hargunkaur286, I would like to check this out.

**Comment by Aryam2121** [comment]
why you unassign me

**Comment by Aryam2121** [comment]
and how you have right to unassign someone who work in that issue and assign any other

**Comment by sudhanshutech** [comment]
@Anand-Theertha any updates?

**Comment by Anand-Theertha** [comment]
I'm currently working on this issue @sudhanshutech 
https://github.com/layer5io/layer5/issues/5908

**Comment by sudhanshutech** [comment]
oh okay. @MaryannGitonga would you like to give it a shot?

**Comment by balagowda** [comment]
@hargunkaur286, @sudhanshutech I come across this issue. here animation shows up for a second and then vanishes because the minimum value set for >= 2. {activeExampleIndex >= 2 ? "show " : "render "} due to this condition animation is not visible for 0 and 1. also when user scroll it up it won't visible too.

**Comment by Ajay-singh1** [comment]
@balagowda If you can fix this go on and raise a PR  as I think nobody is working on this right now.

**Comment by leecalcote** [comment]
Thank you, @Ajay-singh1 👍

**Comment by balagowda** [comment]
@hargunkaur286 , @Ajay-singh1 this might look good?

Uploading Untitled.mov…

**Comment by balagowda** [comment]
@hargunkaur286 , @Ajay-singh1 this might look good?

https://github.com/user-attachments/assets/43a9a85f-d54a-40cd-aa4c-aeb93b56b399

**Comment by Ajay-singh1** [comment]
> @hargunkaur286 , @Ajay-singh1 this might look good?
> 
>  Untitled.mov

Nice I loved it! Wait for others feedack.
