### ISSUE TITLE
T-Shirt Size "XXL" is missing from newcomers page

### ISSUE THREAD

**Issue by void-hr** [layer5io/layer5#5994]
### Description

As present before, T-Shirt size XXL is not available after last radio button. Option is not available for both dark and light mode

[Newcomers Page](https://layer5.io/newcomers)

### Expected Behavior
There should be `XXL`  after last radio button

### Screenshots
![image](https://github.com/user-attachments/assets/372e48d9-d339-4775-8dd6-68373cdf2a9f)

### Environment:
- Host OS: Windows 10
- Browser: Brave

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by void-hr** [comment]
I am looking forward to take this issue and fix it!

**Comment by hargunkaur286** [comment]
Thank you for reporting this @void-hr please go ahead!

**Comment by vishalvivekm** [comment]
Thank you @void-hr 🚀
