### ISSUE TITLE
Add Tigera Secure to landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#60]
@liljenstolpe, @kprabhak, @ahrkrak it'd be great to have Tigera represented in the [landscape](https://layer5.io/landscape). Will you consider a contributing a PR to ensure its accuracy?

**Comment by ahrkrak** [comment]
Funny you mention that - I just raised it with our VP Marketing, Andy
Wright, yesterday.

Let's make this happen!

**Comment by leecalcote** [comment]
@ahrkrak excellent. :) Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) to get the landscape updated.

**Comment by leecalcote** [comment]
@ahrkrak @kprabhak @liljenstolpe we're scrubbing issues today, so I'm giving this one a bump. We'll be presenting this landscape at the upcoming KubeCon EU.

**Comment by jijillery** [comment]
Hi @liljenstolpe, @kprabhak, @ahrkrak, I’m working to ensure all relevant projects are represented in the [service mesh landscape](https://layer5.io/landscape). We would love to have Tigera Secure included. Will you consider updating the landscape with a quick pull request? 

We do our best to ensure that projects and their capabilities are accurately represented, and so, we ask for project representatives to submit these updates directly. 

Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for making your edits.

Thank you!
@jijillery
