### ISSUE TITLE
[Project] Add project links to the SMI Conformance design specs on the /smi page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#601]
**Current Behavior**
The https://layer5.io/projects/service-mesh-interface is in need of pointing people to the design specs and highlighting the two contributor blog posts on the project.

**Desired Behavior**
The [project design specifications](https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit) should be linked to in this project description.

**Implementation**
1. Create a second button on the page "Design Specifications".
1. Add a callout to this blog post - https://layer5.io/blog/community/communitybridge-2020-teaching-service-meshes-to-be-compliant
1. Add a callout to this blog post - https://layer5.io/blog/community/SMI-conformance-testing-with-meshery

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@Nraj923, would you like to take this one?

**Comment by pranikz** [comment]
Hey @leecalcote would like to take up this issue and implement the same. Can u help me?

**Comment by leecalcote** [comment]
@pranikz sure. I'll assign the issue to you. I'm tagging @Ruth-ikegah @Anita-ihuman @PluckyPrecious as contributors capable and willing to assist here. Jump into the Layer5 Slack as you tackle the issue, if real-time chat is helpful - http://slack.layer5.io

**Comment by Ruth-ikegah** [comment]
Hi @pranikz , if you have any problems tackling this issue, you can ask your questions, here or on the slack channel

**Comment by Ayushbajpai19** [comment]
Hi, I want to contribute to the above issues, can you guide me through the process?

**Comment by Ruth-ikegah** [comment]
Hi @Ayushbajpai19 that's nice, but someone has already been assigned to this issue. Please hop in our slack channel : http://slack.layer5.io/

Let's find you another issue

**Comment by PluckyPrecious** [comment]
Hello @pranikz do you need a hand working on this? And if you’re fixed with other issues kindly indicate so @Ayushbajpai19 could take it up.👍🏽

**Comment by leecalcote** [comment]
The formatting on this page could use some attention. @pranikz, is this issue still of interest?

**Comment by Fahdmoh01** [comment]
Kindly assign me to this issue if it's still not fixed

**Comment by Fahdmoh01** [comment]
@PluckyPrecious

**Comment by Fahdmoh01** [comment]
@Nikhil-Ladha Helllo there, Can you kindly assign this to me? That's if it's still free

**Comment by Nikhil-Ladha** [comment]
Sure @Fahdmoh01 👍🏼

**Comment by Fahdmoh01** [comment]
Thanks👍

**Comment by Ruth-ikegah** [comment]
Sorry I think I was doing at the same time as @Nikhil-Ladha

**Comment by Ruth-ikegah** [comment]
You can go ahead with tackling this @Fahdmoh01 . If you have any questions please feel free to ask

**Comment by Fahdmoh01** [comment]
Oh okay, it's fine

**Comment by Fahdmoh01** [comment]
Sure👍🏿

**Comment by Fahdmoh01** [comment]
@leecalcote Hello Lee, I just completed Implementation No.1. What do you mean by Callouts? One the boxes in the blog as shown in the image below? ![image](https://user-images.githubusercontent.com/34211858/96246261-ff3b9180-0fc5-11eb-9026-5be9a519ca3c.jpeg)

**Comment by leecalcote** [comment]
Thanks, @Fahdmoh01. "Callouts" meaning a hyperlink and/or button.

**Comment by Fahdmoh01** [comment]
Which will lead the user to the Design Specifications?

**Comment by Fahdmoh01** [comment]
@leecalcote

**Comment by Fahdmoh01** [comment]
Alright, got it.
