### ISSUE TITLE
[CI] Add `project/sistent` label automatically to pull requests related to sistent project

### ISSUE THREAD

**Issue by sudhanshutech** [layer5io/layer5#6016]
### Desired Behavior

If there any change happens meanings any pull requests within sistent here -> https://layer5.io/projects/sistent then the github bot should automatically labelled with `project/sistent`.

### Screenshots / Mockups

![{135167CD-10B7-4056-A816-B51C56D9E41C}](https://github.com/user-attachments/assets/f7709ed2-d916-4c96-8aaf-1182121b5e6b)

### Acceptance Tests

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
-  🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by thiha-min-thant** [comment]
Hi @sudhanshutech , can you please assign me?
