### ISSUE TITLE
Unable to download generated token

### ISSUE THREAD

**Issue by AmTryingMyBest** [layer5io/layer5#6020]
### Description
The download button for tokens stays unresponsive when a user clicks on it in an attempt to download the token. 

### Steps to Reproduce
1. As a logged in user, navigate to your tokens page.
2. Click on the download button on an available token
3. Note that there's no response from the application. Download doesn't commence.
 

### Expected Behavior
On Clicking download button to initiate downloading the token, the token should download.

### Screenshots
![Screenshot 2024-10-22 at 06 49 55](https://github.com/user-attachments/assets/a43fc4d3-82ef-4cea-915d-f9e07305f41b)

### Environment:
- Host OS: MacOs Sonoma 14.6.1
- Browser: Chrome Version 129.0.6668.101
- URL/environment - https://meshery.layer5.io/security/tokens

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by sudhanshutech** [comment]
@AmTryingMyBest thank you for pointing this bug and opening issue. We will note this down and since this is not right place to open this issue so i will see and open a issue where it need to be. Thanks again
