### ISSUE TITLE
[Community] Member Profile: Aditya Mohan

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#6026]
**Current Behavior**

@TraXIcoN has been a consistent contributor and community member.

**Desired Situation**
Let's recognize @TraXIcoN as a contributor and community member by creating a profile on https://layer5.io/community/members.

- GitHub: @TraXIcoN
- Twitter: 
- LinkedIn: https://www.linkedin.com/in/adityamohan16/
- Layer5 Cloud: 
- Link to profile picture: https://meshery.layer5.io/user/27896d35-9e3d-4242-9cf5-aeba4ebd24e8

A detailed explanation on how to set up a community member profile can be found in the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

---

**Contributor Resources**

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs). Join the [Layer5 Community](https://slack.layer5.io) for access.

**Comment by TraXIcoN** [comment]
@vishalvivekm Thanks for adding me to the members page.

Bio: Aditya Mohan: Open-source enthusiast, full-stack developer, and M.S. Computer Science student at Georgia State University—blending creativity in code, music, and gaming with a passion for tech and gadgets, and always on the lookout for the next cool toy to tinker with.

X: https://x.com/chifladoadiii16

Profile picture: https://i.postimg.cc/0y5Wzx0F/Aditya-Mohan.png

**Comment by vladboisa** [comment]
@vishalvivekm Hi, can u assign me to this issue? Thank you in advance
