### ISSUE TITLE
Update the SVG

### ISSUE THREAD

**Issue by vishalvivekm** [layer5io/layer5#6044]
### Current Behavior

on https://layer5.io/products, the following svg which refers to MeshMap needs to be updated with "Kanvas" along with its new logo
![image](https://github.com/user-attachments/assets/b7cfac08-cec0-4304-8811-273f92de9a84)

the new logo can be found here: 
https://layer5.io/company/brand
The link to svg in Layer5's figma design files: https://www.figma.com/design/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=19721-5171&node-type=frame&t=egfyvEP6nkQq4X0H-0
### Desired Situation

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by vishalvivekm** [comment]
@hargunkaur286 ^^

**Comment by ltdphat0311** [comment]
Can you assign to me?
