### ISSUE TITLE
Add Release Drafter for the repository

### ISSUE THREAD

**Issue by kushthedude** [layer5io/layer5#606]
**Current Situation**

Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Desired Situation**

Add ReleaseDrafter configuration yaml file & GitHub Action.

---

**Additional context**

[ReleaseDrafter Configuration File](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[ReleaseDrafter GitHub Action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

---
**Contributor Resources**

- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Neilblaze** [comment]
Closing this via [#610](https://github.com/layer5io/layer5/pull/610)
