### ISSUE TITLE
Enable Dynamic Imports in Sistent Documentation to Improve the Component Addition Process.

### ISSUE THREAD

**Issue by Vidit-Kushwaha** [layer5io/layer5#6065]
### Current Behavior

Currently, adding a new component to the Sistent library documentation requires modifying eight separate files, which includes navigating through dynamic pages and manually setting up each component. This process is repetitive and prone to errors.

![image](https://github.com/user-attachments/assets/c2ccd076-d3ab-43e4-b86a-036279bdf560)

### Desired Situation

The goal is to dynamically add new components without modifying multiple files. This change would streamline the process, reduce boilerplate, and allow for faster and more reliable updates.

- [ ] Refactor code to support dynamic loading of new components in the documentation.
- [ ] Update navigation to detect and list new components automatically.
- [ ] Test dynamic component imports to ensure compatibility with existing structure.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by Vidit-Kushwaha** [comment]
@sudhanshutech can you assign to me??

**Comment by sudhanshutech** [comment]
go ahead @Vidit-Kushwaha
