### ISSUE TITLE
[Blog]

### ISSUE THREAD

**Issue by Ruhi-Khan** [layer5io/layer5#6079]
Contributors and community members are encouraged to post on https://layer5.io/blog. A new blog post fitting the following description is requested to be written by a community member:

**Desired Title:** 
**Topic:** 
**Core points to convey in the post:** 
1.
1.
1.

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="16px" align="left" /><h3>Contributor Resources</h3>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
- See Layer5 site designs in this [Figma project](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

**Comment by sudhanshutech** [comment]
@Ruhi-Khan i guess you missed the information to fill for which you are you requesting a blog. Please also add a meaningful title to the issue

**Comment by sudhanshutech** [comment]
I am closing this issue since there is no proper description. Please fell free to open with proper reference. Thanks
