### ISSUE TITLE
Add Aporeto to the landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#61]
@dstiliadis @satyamsi it'd be great to have Aporeto represented in the [landscape](https://layer5.io/landscape). Will you consider a contributing a PR to ensure its accuracy?

Perhaps, under the "Commercial Offerings" column for Istio?

**Comment by dstiliadis** [comment]
Will do. Added it in the todo list.

**Comment by leecalcote** [comment]
@dstiliadis good deal. Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) to get the landscape updated.

**Comment by leecalcote** [comment]
@dstiliadis we're scrubbing issues today, so I'm giving this one a bump. We'll be presenting this landscape at the upcoming KubeCon EU.

**Comment by jijillery** [comment]
Github request to contribute:

Hi @dstiliadis and @satyamsi, I’m working to ensure all relevant projects are represented in the [service mesh landscape](https://layer5.io/landscape). We would love to have Aporeto included. Will you consider updating the landscape with a quick pull request? 

We do our best to ensure that projects and their capabilities are accurately represented, and so, we ask for project representatives to submit these updates directly. 

Here are [contribution instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) for making your edits.

Thank you!
@jijillery
