### ISSUE TITLE
Badge Misalignment in "Special Edition Badges" Section in badges.layer5.io

### ISSUE THREAD

**Issue by Vidit-Kushwaha** [layer5io/layer5#6121]
### Description

The Hacktoberfest badge in the "Special Edition Badges" section on the [badges.layer5.io](https://badges.layer5.io/) website is misaligned compared to the Docker Captain and CNCF Ambassador badges. This disrupts the visual consistency of the section.

### Expected Behavior

All badges should be evenly aligned with consistent spacing and centred text.

### Screenshots

![Screenshot 2024-12-11 112822](https://github.com/user-attachments/assets/ee5d130f-f43e-4c36-a768-ddd7d927230d)

### Environment:
- Host OS: Windows 11
- Browser: Microsoft Edge v131

---
<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/layer5/5-light-small.svg" width="24px" align="left" /><h2>Contributor Resources and <a href="https://layer5.io/community/handbook">Handbook</a></h2>

The layer5.io website uses Gatsby, React, and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- 📚 See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md).
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.layer5.io).

<img src="https://raw.githubusercontent.com/layer5io/layer5/master/.github/assets/images/buttons/community.webp" height="22px" align="left" />Join the Layer5 Community by submitting your [community member form](https://layer5.io/newcomer).

**Comment by FilledEther20** [comment]
Hi @Vidit-Kushwaha I would like to work on it ... could u please assign me this issue. Thanks!

**Comment by Vidit-Kushwaha** [comment]
Hi @FilledEther20 Under the layer5labs/meshery-extensions-package, this issue is open. It is duplicate. If you want to work on issue, refer to this  [#448 layer5labs/meshery-extensions-packages](https://github.com/layer5labs/meshery-extensions-packages/issues/448) I am closing this issue.
