### ISSUE TITLE
[Projects] SMP references in /meshery

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#620]
Thank you, @JubayerJoy. There's one more on the layer5.io site at layer5.io/meshery - - 
<img width="562" alt="Screen Shot 2020-08-13 at 9 33 33 PM" src="https://user-images.githubusercontent.com/7570704/90207750-b17b9080-ddac-11ea-908e-965d8ae09eb0.png">

The latest SMP logos are available in the Layer5 Sites drive.

_Originally posted by @leecalcote in https://github.com/layer5io/meshery/issues/1379#issuecomment-673850213_

**Comment by JubayerJoy** [comment]
Hi @leecalcote, I'm working on it 👍
