### ISSUE TITLE
Add community calendar button to set of social buttons

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#621]
**Current Behavior**
The current set of horizontal social buttons on the layer5.io site does not have a button for the community calendar.

**Desired Behavior**
Add the existing button for the community calendar (screenshot from the layer5.io/meshery page) to the list of [social buttons](https://github.com/layer5io/layer5/blob/master/_includes/partials/hori-social.html).

<img width="512" alt="Screen Shot 2020-08-13 at 3 32 12 PM" src="https://user-images.githubusercontent.com/7570704/90209907-2c937580-ddb2-11ea-88fc-2330b3f64f6e.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Neilblaze** [comment]
@leecalcote you mean [this](https://bit.ly/2SbrRhe) right?
