### ISSUE TITLE
[NG] search plugin

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#623]
**Description**

Implement the search plugin on the `layer5-ng` site.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by thescripted** [comment]
Hey, I can tackle this issue if it still needs to be worked on!

I believe that when implementing the search plugin, this is the file that should be indexed: https://github.com/layer5io/layer5/tree/master/collections/_blogs 

and a method to query the search should be provided here:
https://github.com/layer5io/layer5/blob/4a96bae8df4bf876c0509671821ebefe0ccbb86b/src/sections/Blog-sidebar

Is that within the ballpark?

**Comment by leecalcote** [comment]
@chandrashritii, yes?

**Comment by chandrashritii** [comment]
@leecalcote This issue is blocked. Waiting for the strapi integration before pushing forward with the search plugin CC// @Tanuj22

@thescripted Thanks for taking this up. That looks like the right approach but we intend to integrate [strapi ](https://strapi.io/) with the current layer5-ng site which might cause issues with the plugin integration. Strapi should be set up soon. In the meanwhile, do take a look at other open issues

**Comment by raghavaggarwal99** [comment]
Hi, is this still open @chandrashritii

**Comment by Nikhil-Ladha** [comment]
@Tanuj22 ^^

**Comment by Tanuj22** [comment]
> Hi, is this still open @chandrashritii

Yes it is @raghavaggarwal99. For starters, we are looking to add a search in https://layer5ng.netlify.app/blog. I had looked a bit into `lunarJS` (https://css-tricks.com/how-to-add-lunr-search-to-your-gatsby-website/). You can follow that or if you think there is a better option please suggest :)

**Comment by chinmaym07** [comment]
Hey @Tanuj22 can I try to implement this .?

**Comment by shubhank-saxena** [comment]
@Tanuj22 will this do the trick?
https://www.gatsbyjs.com/plugins/@gatsby-contrib/gatsby-plugin-elasticlunr-search

**Comment by leecalcote** [comment]
@Harshita-Kanal, is this something you might tackle?

**Comment by YashKamboj** [comment]
Taking this up!!!

**Comment by kayceeDev** [comment]
I am working on this now. I Have gotten the search to work. I will fix up a few things create a PR
