### ISSUE TITLE
[NG] Create project layout

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#625]
**Description**

Convert the existing `pricing` module to `features` module to be used in the Project layout.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
I think we can have a project layout for a few projects, but for those like meshery and such we can't have them due to much diverse data to be displayed. So how about for now we have a template for others and a separate one for meshery. Any comments @chandrashritii @leecalcote @Nikhil-Ladha ?

**Comment by leecalcote** [comment]
@Jashpatel1 totally. That sounds most appropriate.

**Comment by Jashpatel1** [comment]
Fixed  in #733
