### ISSUE TITLE
Improve the UI of meshery page

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#627]
**Current Behavior**
There are a lot of things in the [meshery](https://layer5.io/meshery) page that might need to be changed. 

- Go to the meshery page - https://layer5.io/meshery
- Scroll down the page & see.

**Screenshot** 
![Layer5-Meshery](https://user-images.githubusercontent.com/48355572/90263459-52ca1b80-de6d-11ea-8c05-cf645ab554ff.png)

In reference to the screenshot above, we can refine the following marked items.

- Align the contents `Baseline, Measure, and Assess` card properly (align-center).
- Fix the padding of the embed YouTube video in center.
- In the `Community` section, those icons needs to be properly scaled & aligned.
- I think the `Fork me on Github` ribbon doesn't look good on `Community` & `Service Mesh Performance Specification` section. We may remove one from the community section.
- The svg in the subscribe section needs to be magnified a little bit.

@leecalcote @chandrashritii 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
These are all good highlights (things that need fixing), @Neilblaze.

**Comment by Neilblaze** [comment]
Yeah. I think it'll be better if we disintegrate these issues into small parts & create FTO issues.

What say? @chandrashritii @leecalcote

**Comment by Neilblaze** [comment]
Just now another thing just stroked my mind. If we look closely, this ↓ can also be fixed.

![abovfooter](https://user-images.githubusercontent.com/48355572/90289558-bec27900-de99-11ea-8786-da0b56b6812c.JPG)

- We can align `Language` & `Contact` on same level.
- Properly position `Language` & `Contact` with respect to their corresponding svg's
