### ISSUE TITLE
[NG] Change the site url for layer5-ng

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#631]
**Desired Situation**
Change the [siteUrl](https://github.com/layer5io/layer5/blob/layer5-ng/gatsby-config.js#L6) to new url. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Neilblaze** [comment]
Wouldn't it be better if we create a section in the README file of the `Layer5` repo and position in the top, where we can keep the two different sites URL's where one of them will redirect to the `layer5-ng` and another to the current one made with Jekyll and GitHub Pages i.e. [this](https://layer5.io/)?

And also a simple info about branch checkout for easy directory mobility!

**Comment by leecalcote** [comment]
@Neilblaze good thinking. The logic here is that a number of people swing by the layer5 repo's readme in search of descriptions of the projects and the community. While many people do swing by to contribute, they are the fewer of the two groups. So, the instructions surrounding the (temporary) hosting of two sites in one repo is documented in Issue Templates, where contributors will see them and people interested in the project and community won't.

**Comment by Neilblaze** [comment]
> @Neilblaze good thinking. The logic here is that a number of people swing by the layer5 repo's readme in search of descriptions of the projects and the community. While many people do swing by to contribute, they are the fewer of the two groups. So, the instructions surrounding the (temporary) hosting of two sites in one repo is documented in Issue Templates, where contributors will see them and people interested in the project and community won't.

Yes, I completely agree!
Maybe we can open up a separate issue where anyone of us can register him/herself regarding what you just suggested! :thinking:

**Comment by Neilblaze** [comment]
Where if we add a **small & brief** section in the [README](https://github.com/layer5io/layer5/blob/master/README.md) file of the **Layer5 repo** and position it in the **top**, where we can keep track the two different sites URL's where one of them will redirect to the [layer5-ng](https://layer5ng.netlify.app/) and another to the [current one](https://layer5.io/) made with Jekyll and GitHub Pages!

**Comment by Tanuj22** [comment]
FIxed
