### ISSUE TITLE
Update Brand page to include Service Mesh Performance project logos

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#636]
**Current Behavior**
The Layer5 [brand page](https://layer5.io/brand) is missing a section for the [Service Mesh Performance](https://smp-spec.io) (SMP) project's logos and usage guidelines. 

**Expected Behavior**
There should be a section for the SMP project and its logos.

**Implementation**
1. Create a new section on the page for Service Mesh Performance
1. Use images from the [SMP brand kit](https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smps-brand-kit.zip).
1. Provide a download button for the [SMP brand kit](https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smps-brand-kit.zip).
1. Show color scheme (included in brand kit)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by manishkrjha** [comment]
Hello, I'd love to work on this issue I just need little clarification, you want a Service Mesh Performance section same as **layer-5, Meshery and Image-Hub** sections on brand page? 

Also, the SMP brand kit is not working.

Thanks.

**Comment by PluckyPrecious** [comment]
Hello @manishkrjha please do go ahead. Perfecto 👌🏽  you’re right on track. Here’s the link [SMP brand kit](https://github.com/layer5io/layer5/blob/master/assets/resources/brand/smp-brand-kit.zip)

**Comment by manishkrjha** [comment]
I'm having little trouble in finding the HTML file that has brand page's code. Can you guide to the same?

**Comment by PluckyPrecious** [comment]
@manishkrjha you’ll find it here `assets/resources/brand/smp-brand-kit`

**Comment by PluckyPrecious** [comment]
Hi @manishkrjha find it here `collections/pages/brand.html` 😊

**Comment by leecalcote** [comment]
@manishkrjha Thanks! This does look good.

You'll want to push to your fork (https://github.com/manishkrjha/layer5), not directly to layer5io/layer5. From there, you can then raise a PR to merge the difference between https://github.com/manishkrjha/layer5 and layer5io/layer5. 

Reference - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md

**Comment by Nikhil-Ladha** [comment]
Closed #666
