### ISSUE TITLE
[Landscape] Kuma updates

### ISSUE THREAD

**Issue by subnetmarco** [layer5io/layer5#637]
**Current State:**

1. It says Kuma has no support for gRPC.
2. It says Kuma has experimental support for multi-cluster.
3. It says Kuma is multi-tenant only with Kong Enterprise.
4. It says "?" on Prometheus support
5. It says "?" on tracing support.
6. It says "?" on encryption.

**Desired State:**

1. Kuma does support gRPC.
2. Kuma has finalized support for multi-cluster (and multi-cloud, and hybrid Kubernets + VMs) thanks to the [multi-zone deployment](https://kuma.io/docs/0.7.0/documentation/deployments/#multi-zone-mode).
3. Kuma is multi-mesh in the OSS version to support multiple individual meshes in a single Kuma clusters.
4. Kuma has a native Prometheus support thanks to the "Traffic Metrics" policy, also with bundled Grafana dashboards.
5. Kuma has a native tracing support thanks to the "Traffic Tracing" policy.
6. Kuma supports mTLS encryption with two different CA backends, "builtin" and "provided", thanks to the "mTLS" policy.

---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

**Comment by Neilblaze** [comment]
Not sure about what to replace "Kong Enterprise only" by any other regarding bullet no. 3 
Rest, I'm creating a pr with updated info's!

**Comment by subnetmarco** [comment]
> Not sure about what to replace "Kong Enterprise only" by any other, regarding bullet no. 3

@Neilblaze It should be replaced with "Yes".

**Comment by leecalcote** [comment]
Reopening. Need to update given this input - https://github.com/layer5io/layer5/pull/638#issuecomment-675800316

**Comment by Neilblaze** [comment]
Here you go! :smiley:

**Comment by subnetmarco** [comment]
Thanks!
