### ISSUE TITLE
Update "submit issue" link to reference layer5

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#64]
the "please submit an issue" hyperlink points to the old repo location - https://github.com/leecalcote/layer5/issues. Needs updating.

**Comment by yogi4** [comment]
@leecalcote looks like you already fixed this.

**Comment by leecalcote** [comment]
@yogi4 I actually didn't. The experience is deceiving in that GitHub kindly automatically redirects old repo references to their new location.

**Comment by leecalcote** [comment]
@yogi4 surprisingly, we never got round to this one. :)

**Comment by leecalcote** [comment]
Thanks, @anandrkskd!
