### ISSUE TITLE
Update /meshery page to include SMP logo in the SMP section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#640]
**Current Behavior**
This section of the Meshery page is missing the SMP logo.

<img width="1095" alt="Screen Shot 2020-08-18 at 8 08 58 AM" src="https://user-images.githubusercontent.com/7570704/90517017-6f46ac00-e12a-11ea-8cc4-1bdb5dca0f9d.png">

**Desired Behavior**
Display the SMP logo in this section - https://github.com/layer5io/layer5/blob/master/assets/projects/smp/stacked/smp-dark.svg

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Neilblaze** [comment]
I'm on it! :zap:
