### ISSUE TITLE
[Project] Meshery: add comma as a separator in the count of performance tests run

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#650]
**Current Behavior**
The number of performance tests run by Meshery users is shown on layer5.io/meshery. This data is retrieved from a public, remote endpoint, which does not include comma separators for thousandths places.

<img width="540" alt="Screen Shot 2020-08-18 at 2 14 50 PM" src="https://user-images.githubusercontent.com/7570704/90590210-91314480-e1a5-11ea-97a0-d5d8bc5adb0b.png">

**Desired Behavior**
Use CSS or Javascript to insert a comma after the thousandths place (e.g. 1,062).

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by was-coder** [comment]
can i take up this challenge @leecalcote @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
sure @was-coder !

**Comment by was-coder** [comment]
Please i need clarity on this issue. I thought i am able to implement it but that has not been the case

**Comment by PluckyPrecious** [comment]
In what aspect do you need clarification?

**Comment by was-coder** [comment]
I am to add comma as a count separator but when I fork and cloned the
project I was lost on where to even start my coding from, where to include
it

**Comment by PluckyPrecious** [comment]
You’re to work on the [Meshery Section](https://layer5.io/meshery), you can add the code [here](https://github.com/layer5io/layer5/blob/master/_includes/meshery.html)  _includes/Meshery.html . Hope we good to go?😊

**Comment by was-coder** [comment]
Thanks so much I will check this out

**Comment by PluckyPrecious** [comment]
👍🏽
