### ISSUE TITLE
Add a description of the “SMI Conformance” project to the README.md

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/layer5#658]
**Current Behavior**

This README.md file does not have a description for SMI Conformance as it has for other projects like Service Mesh Landscape,, Meshery etc.

**Desired Situation**

On the README.md file, add a short description for [SMI Conformance](https://layer5.io/projects/service-mesh-interface) in the same format as the others.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Abiola-Farounbi** [comment]
Hi, i would like to take this up

**Comment by Ruth-ikegah** [comment]
Sure @Abiola-Farounbi !
