### ISSUE TITLE
Add new event to the layer5 site

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#659]
**Description**

Our session on **Solving the Service Mesh Adopter’s Dilemma** has been accepted for the **2020 All Day DevOps** event, to be conducted on November 12, 2020.
Add a project card for the "2020 All Day DevOps" to the [events section](https://layer5.io/events) on the layer5.io site. Link the card to the official event site - https://www.alldaydevops.com/register-2020 and include the event date, similar to what has been done for the other events listed on the page.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Yusadolat** [comment]
Hey @chandrashritii I'd like to work on this 😄
