### ISSUE TITLE
[NG] Change from pink to layer5 brand colours

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#672]
**Desired Situation**
The layer5ng site is having pink colour in most of its pages. It should be changed to layer5 brand colours.

I think changes in most places would take place if the theme colours in [this folder](https://github.com/layer5io/layer5/tree/layer5-ng/src/theme) are changed. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Currently, the primary action color of layer5.io is a dark yellow (#EBC017), which can begin to be integrated into the layer5-ng site.

**Comment by Nikhil-Ladha** [comment]
Like for the moment, the arrows that we have can get the yellow color instead of orange to begin with. And with time it can be used in other areas as well

**Comment by bellomuboye** [comment]
I'd like to take this up

**Comment by Nikhil-Ladha** [comment]
@bellomuboye any updates here?

**Comment by Jashpatel1** [comment]
@bellomuboye If you are stuck somewhere, I would be happy to help you go through your first contribution to Layer5.
