### ISSUE TITLE
[Bug] UI - Right-side of each page is spilling over

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#675]
**Description**
An unwanted bit of extra space is shown to the right of each page on layer5.io. This might be caused by the recent addition of the community calendar button in the **Connect** section in the footer.

**Screenshots**
<img width="479" alt="Screen Shot 2020-08-25 at 7 23 08 AM" src="https://user-images.githubusercontent.com/7570704/91175110-e093db00-e6a5-11ea-88b3-2af8a49f3f02.png">

**Enviroment:**
 - OS: MacOS
 - Browser: Safari

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Neilblaze** [comment]
@leecalcote Maybe this issue is browser dependent :thinking: 
I am using Chrome & Firefox (latest version) & I am not facing this issue :confused:

**Comment by Neilblaze** [comment]
**UPDATE: I am facing this issue on Opera**(on responsive view)! 
Since, I am currently working on revamping the existing [smp-spec](https://smp-spec.io/) site, someone can take this up for now, else I shall hop in to fix this after some days :smile:
