### ISSUE TITLE
Add RVM Description to Layer5 Documentation

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/layer5#676]
**Current Behavior**
Windows users are having issues using Jekyll and there's no description to help with that.

**Desired Situation**
Provide a description of RVM to the `set up your development environment` section of the Layer5 Doc by adding this line.

`Note: Windows users can run Jekyll by following the [Windows Installation Guide](https://jekyllrb.com/docs/installation/windows/) and also install Ruby Version Manager [RVM](https://rvm.io) - a command-line tool which allows you to easily install, manage and work with multiple ruby environments on your local machine. Alternatively, if you're running Windows 10, updated to version 1903 Build 18362 or higher you can upgrade to Windows Subsystem for Linux [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)`

The additional lines can be added right after *Jekyll Docs* .👍🏽

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by emmanuellar** [comment]
Hi Precious. I'd love to take this up.

**Comment by PluckyPrecious** [comment]
Hi @emmanuellar sure go ahead. 👍🏽

**Comment by Atandanafiu** [comment]
can still help with this!!

**Comment by PluckyPrecious** [comment]
Hey @Atandanafiu I just assigned you to one.

**Comment by emmanuellar** [comment]
Hi Precious, sorry it has taken so long,  I've gone through the repo, but I can't find a "set up your development environment" section in any of the documents. The documents I've gone through are contributing.MD, read.me, code of conduct and others.
Please any help would be appreciated

**Comment by Ruth-ikegah** [comment]
Hi @emmanuellar you can add this description on the Contributing.md file on this repository. Since there is no section on the file, go ahead to create one and add the note.

**Comment by emmanuellar** [comment]
Alright then. Thanks
