### ISSUE TITLE
Update Brand page to use CSS color blocks, not images for color schemes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#681]
**Current Behavior**
Akin to what @manishkrjha accomplished in https://github.com/layer5io/layer5/pull/666 for the SMP project, convert all color scheme images (for each project) to colored blocks with color codes inside.

**Implementation**
1. Create color-filled, box-shaped divs with each color code number inside of them for each of the project color schemes.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Great job on #666, @manishkrjha, would you like to grab this issue? You're most welcome to jump into the Layer5 community here - http://slack.layer5.io. There's much going on in there.

**Comment by manishkrjha** [comment]
@leecalcote Ya sure. I'll do this 🙌

**Comment by leecalcote** [comment]
Awesome. Thank you, @manishkrjha

**Comment by manishkrjha** [comment]
Just needed little clarification, as you've mentioned ***(for each project)*** 

Does it mean all sections on brand page or are there other projects too?

**Comment by Nikhil-Ladha** [comment]
> Just needed little clarification, as you've mentioned _**(for each project)**_
> 
> Does it mean all sections on brand page or are there other projects too?

Yeah, he meant that only. Each section in the brand page.

**Comment by Nikhil-Ladha** [comment]
Also, while you are working with that part can you please do refine the page a bit for responsiveness, and also few font size changes and stuff to look good in all views.
I will open a seperate issue for it you can add mention that issue too, in the PR 🙂

**Comment by manishkrjha** [comment]
@Nikhil-Ladha Ok sure, I'll mention that in my PR

**Comment by Josephchinedu** [comment]
has it been attended too?

**Comment by Nikhil-Ladha** [comment]
> has it been attended too?

Yes @Josephchinedu it has been.
