### ISSUE TITLE
Offset request to star project with whitespace and tabs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#683]
**Current Behavior**
Within the Welcome bot [example here](https://github.com/layer5io/layer5/pull/664#issuecomment-678089961) that thanks first-time contributors for their efforts, a request to star the repo should be included and it should be slightly offset to improve its visibility.

**Implementation**
Update or add the following line(s) to [.github/config.yml](../blob/master/.github/config.yml):

```
 &nbsp;
 &#9; &nbsp; &#9;  &nbsp; &#9;  &nbsp; &#9;   :star: Please [star the project](../stargazers) if you have yet to do so.

```

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by sachin4840** [comment]
I would like to contribute. Can you assign it to me

**Comment by leecalcote** [comment]
@sachin4840 sounds great. Let’s get the issue assigned to you. I recommend and welcome you to join the Layer5 Slack - http://slack.layer5.io. Lots of resources and helpful folks inside.

**Comment by PluckyPrecious** [comment]
Hello @sachin4840 how is it coming up? 😊

**Comment by Josephchinedu** [comment]
i'll love to contribute

**Comment by PluckyPrecious** [comment]
Hello @sachin4840 if you are fixed, @Josephchinedu could take this up.

**Comment by Josephchinedu** [comment]
> Hello @sachin4840 if you are fixed, @Josephchinedu could take this up.

i've updated it. waiting for contributor to view it
