### ISSUE TITLE
[Landscape] Move background image to behind the Categories table.

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#684]
**Current Behavior**

Currently, there is a background image behind the service mesh timeline.

<img width="1392" alt="Screen Shot 2020-08-27 at 9 06 27 PM" src="https://user-images.githubusercontent.com/7570704/91513166-4ef4bb00-e8a9-11ea-8db8-08ec55e5b21c.png">

The colors of the timeline and the background image overlap too much, causing them to conflict.

**Desired Behavior**
This background image should be relocated to the section below the timeline, the Categories section. This image should show up behind the table in this section.

<img width="1350" alt="Screen Shot 2020-08-27 at 9 09 33 PM" src="https://user-images.githubusercontent.com/7570704/91513326-b0b52500-e8a9-11ea-8d8f-271bb5008bc6.png">

**Comment by SkyC0der** [comment]
I would like to this up

**Comment by SkyC0der** [comment]
I would like to take this up

**Comment by Nikhil-Ladha** [comment]
Sure @SkyC0der , go ahead 👍🏼

**Comment by Ruth-ikegah** [comment]
Nice work @SkyC0der
