### ISSUE TITLE
[Bug] UI - Brand page needs to be more responsive

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#688]
**Description**

The logo's of projects are overlapping on the mobile view and the image size needs to be adjusted for the colors subheading under `Layer5` section.

**Expected Behavior**

The images should not overlap, instead the size of the image can be reduced a bit for the mobile view to show them side-by-side.
The image of the colors under Layer5 section can be revamped as per the modifications in the SMP section.
**Screenshots**

![Screenshot from 2020-08-29 14-21-13](https://user-images.githubusercontent.com/29438875/91633141-97c08700-ea03-11ea-8b99-8479482a5d3c.png)
![Screenshot from 2020-08-29 14-21-06](https://user-images.githubusercontent.com/29438875/91633147-9beca480-ea03-11ea-957e-b90c6583ac13.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Nikhil-Ladha** [comment]
Related to #681 

@manishkrjha ^^

**Comment by manishkrjha** [comment]
@Nikhil-Ladha Understood 👍

**Comment by Nikhil-Ladha** [comment]
Closed #693
