### ISSUE TITLE
Correct Star The Project Link In Welcome Bot

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/layer5#690]
**Current Behavior**
The link to `star the project` in the [config.yml](https://github.com/layer5io/layer5/blob/41ed36c003ac0e315969d3a909241fcd793724df/.github/config.yml#L22) directs contributors to star a personal account outside layer5. 

**Desired Situation**
It should be corrected to `(../stargazers)` to direct contributors to the exact layer5 project repo.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by claire-me** [comment]
Hello @PluckyPrecious I'd like to take this issue

**Comment by PluckyPrecious** [comment]
Sure, go ahead. @claire-me 👍🏽
