### ISSUE TITLE
[NG] Change the font color to a darker shade

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#696]
**Current Behavior**
Currently, the single blog page in layer5-ng site has default grey text for paragraphs. It seems to be less readable.

**Desired Behavior**
Change the colour of text to black aur a darker grey such that its easily readable. The CSS file where the changes are to be applied is [here.](https://github.com/layer5io/layer5/blob/layer5-ng/src/posts/blogs/Blog.style.js)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by was-coder** [comment]
@Jashpatel1 @leecalcote can i take up this issue

**Comment by Jashpatel1** [comment]
> @Jashpatel1 @leecalcote can i take up this issue

Yaa, sure. Please go ahead.

**Comment by Jashpatel1** [comment]
Resolved in #701
