### ISSUE TITLE
[NG] Remove the left padding in subitems of Footer

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#699]
**Current Behavior**
This issue pertains to layer5-ng site. The subitems in the footer have left padding making it look as indented.

**Desired Behavior**
Remove the left-padding to make it in line with its title. The changes have to be made in [styles of Footer section.](https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/Footer/footer.style.js) As it is a change to be made in layer5-ng branch, pull a request in the layer5-ng branch.

---
<img width="1276" alt="Screen Shot 2020-09-02 at 2 00 53 PM" src="https://user-images.githubusercontent.com/43696490/92067438-eedaa900-edc1-11ea-8703-2152202f5d69.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by was-coder** [comment]
@Jashpatel1 @leecalcote can i take up this issue

**Comment by Jashpatel1** [comment]
@was-coder Hey if you are stuck somewhere, jump into slack, and we can make a combined effort to the website.

**Comment by was-coder** [comment]
I am sorry for delaying, it is just that I am so busy. Can you please
reassign to another person, I will be back to contribute when I am free

**Comment by leecalcote** [comment]
@was-coder thank you for letting us know. 👍

**Comment by was-coder** [comment]
I will be back after I sort out things. Thanks
