### ISSUE TITLE
Use slackin

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#7]
The social icons for Slack on the site (top and bottom of page) link to https://layer5io.slack.com. This hyperlink should be changed to https://slack.layer5.io and leverage slackin (https://github.com/rauchg/slacki) to allow the public to join the community slack account.

**Comment by rootsongjc** [comment]
https://slack.layer5.io can’t be reached

**Comment by leecalcote** [comment]
@rootsongjc, http://slack.layer5.io is now available (unfortunately, not SSL - $). 

@yogi4, this new link needs to displace the existing link used for the Slack social icon on the site.

**Comment by yogi4** [comment]
Modified the url and tested this to be working . This issue can be closed.
