### ISSUE TITLE
[Landscape] Remove SOFAMesh Duplicate from Categories

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/layer5#703]
**Current State:**
The [Layer5 landscape](https://layer5.io/landscape) categories service mesh section has a duplicate of SOFAMesh.
![categories](https://user-images.githubusercontent.com/59584014/92104287-01aca800-edd9-11ea-95a5-70b09238ddee.PNG)

**Desired State:**
- [ ] Remove SOFAMesh duplicate
 
---
**Contributor Resources**
- [Instructions for updating the landscape](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#updating-the-service-mesh-landscape)
- Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).

**Comment by VictoryWekwa** [comment]
can i work on this?

**Comment by leecalcote** [comment]
@PluckyPrecious great write up. 👍 

@VictoryWekwa, yes, please. Both of these items need completed. SOFAmesh's deduplication is straight-forward, where OSM's listing will take a bit of assistance from @phillipgibson  in the issue https://github.com/layer5io/layer5/issues/591

// @Nikhil-Ladha

**Comment by PluckyPrecious** [comment]
Didn't know part of the issue is duplicate, so I just did an update @VictoryWekwa hope it's clear. 😃

**Comment by VictoryWekwa** [comment]
Okay.
That's fine
