### ISSUE TITLE
[NG] Migrate the site data for the GSoC page to the layer5-ng site

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#705]
**Description**
Currently, the internship page dedicated to [GSoC](https://layer5ng.netlify.app/careers/programs/gsoc/2020) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [GSoC page](https://layer5.io/programs//gsoc/2020) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vinayaksh42** [comment]
I would like to work on this issue

**Comment by leecalcote** [comment]
Excellent.

**Comment by vinayaksh42** [comment]
As i am able to see in this repo, There is no career page yet. So am i like supposed to make the career page first or just make a skeleton for the career page and directly work with the gsoc page? @chandrashritii
