### ISSUE TITLE
[NG] Migrate site data for CommunityBridge to the layer5-ng site

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#707]
**Description**
Currently, the internship page dedicated to [CommunityBridge](https://layer5ng.netlify.app/careers/programs/communitybridge/2020) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [CommunityBridge](https://layer5.io/programs/communitybridge) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by UdokaVrede** [comment]
Hi @chandrashritii I noticed the issue 705,706 and 707 are all similar I'd love to fix this. I've been looking at the code base but I'm not just getting it pls I'd need a guide.

**Comment by codetheorem** [comment]
Assign this to me.

**Comment by leecalcote** [comment]
Oops. I assigned to @codetheorem based on only seeing the single request for assignment. I now see @UdokaVrede's request for clarification. 

@UdokaVrede, @chandrashritii are you working on this yet or is it up for grabs?

**Comment by Jashpatel1** [comment]
@UdokaVrede In case you find any difficulty, you can jump into slack. We will definitely find a way out.

**Comment by chandrashritii** [comment]
Hey @UdokaVrede We'd love to help you out. Do signal if you want to be assigned to this issue. Can you explain what issues you're facing?

@codetheorem Thank you for asking 👍  I see that you're already been assigned on #706. Let's wait for @UdokaVrede to confirm their interest on this one.

**Comment by UdokaVrede** [comment]
Hi @chandrashritii assign this to me

**Comment by vinayaksh42** [comment]
Hey @UdokaVrede are you working on this issue? if not i would like to work on it.

**Comment by chandrashritii** [comment]
@UdokaVrede Sure 👍 Please take it away.

@vinayaksh42 Seeing that @UdokaVrede asked first, let's find you another issue to work on.

**Comment by Tanuj22** [comment]
@UdokaVrede are you working on this?

**Comment by UdokaVrede** [comment]
I got a new device, I have been having issues setting up, I have unassigned myself so someone else could pick up the issue, so you can go ahead with it. @Tanuj22

**Comment by geraldmaboshe** [comment]
Hey @chandrashritii , I would like to take up this

**Comment by Tanuj22** [comment]
@geraldmaboshe Go ahead. One thing to note here is that. For this page, you simply need to create a file in `collections/programs` and fill the data accordingly taking reference from the gsoc and gsod page already available.

**Comment by geraldmaboshe** [comment]
> @geraldmaboshe Go ahead. One thing to note here is that. For this page, you simply need to create a file in `collections/programs` and fill the data accordingly taking reference from the gsoc and gsod page already available.

Cool, thanks
