### ISSUE TITLE
[NG] Migrate site data for the Internships page to the layer5-ng site

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#708]
**Description**
Currently, the page dedicated to [Internships](https://layer5ng.netlify.app/careers/programs/internships) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Internships](https://layer5.io/careers/internships) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by iambami** [comment]
Can I do this?

**Comment by PluckyPrecious** [comment]
Hi @iambami ”can I do this” is totally dependent on you, would you like to give it a shot? 😊

**Comment by leecalcote** [comment]
@PluckyPrecious, ha!

@iambami, do your worst! 😉 Note that this issue calls for the populating of pages from the currently layer5.io site under this repo's `master` branch (the site uses Jeykll) over to this same repo's `layer5-ng` branch (the new site uses Gatsby).

**Comment by Jashpatel1** [comment]
@iambami In case you are stuck somewehere, feel free to ask for it. If you want some help setting it up or understanding the code base, you can jump into slack.

**Comment by leecalcote** [comment]
Much appreciated, @Jashpatel1. 

Be sure to take advantage of this offer, @iambami. Here's a Gatsby tutorial that @Jashpatel1 and @Tanuj22 gave in case you weren't on this call - https://www.youtube.com/watch?v=RM3p0nKwuG0

**Comment by Tanuj22** [comment]
FIxed in #826
