### ISSUE TITLE
[NG] Migrate site data for the Partners page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#709]
**Description**
Currently, the page dedicated to [Partners](https://layer5ng.netlify.app/contact/partners) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Partners page](https://layer5.io/partners) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Pratyush-Saxena** [comment]
@chandrashritii , Can I resolve this issue

**Comment by leecalcote** [comment]
That would be great, @Pratyush-Saxena 👍 FYI, there is a meeting today at 6pm IST to discuss this website (and others). Jump in - https://bit.ly/2SbrRhe

**Comment by Pratyush-Saxena** [comment]
> **Description**
> Currently, the page dedicated to [Partners](https://layer5ng.netlify.app/contact/partners) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error.
> 
> **Expected Behavior**
> 
> The data from the [Partners page](https://layer5.io/partners) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site.
> 
> **Contributor Resources**
> The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.
> 
> If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> 
> * See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> 
> If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
> 
> * See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

@leecalcote Pls tell me either you want just to display [Partners](https://layer5.io/partners) on clicking Partner page link on  [layer5-ng site](https://layer5ng.netlify.app/) or you want me to create Partner page of its own

**Comment by Jashpatel1** [comment]
> > **Description**
> > Currently, the page dedicated to [Partners](https://layer5ng.netlify.app/contact/partners) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error.
> > **Expected Behavior**
> > The data from the [Partners page](https://layer5.io/partners) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site.
> > **Contributor Resources**
> > The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.
> > If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
> > 
> > * See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)
> > 
> > If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
> > 
> > * See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)
> 
> @leecalcote Pls let me know either you want just to display [Partners](https://layer5.io/partners) on clicking Partner page link on [layer5-ng site](https://layer5ng.netlify.app/) or you want me to create Partner page of its own

Yaa, so yo would have to create a partners page in pages folder in layer5-ng site, and migrate the data from the layer5 site. If you need any help you can join layer5 community on slack.

**Comment by Pratyush-Saxena** [comment]
All right @Jashpatel1 ...Thanku

**Comment by chandrashritii** [comment]
Thank you for taking this on @Pratyush-Saxena. I believe @Jashpatel1 has answered your question here. Let us know if you have any other doubts 👍

**Comment by Tanuj22** [comment]
@Pratyush-Saxena any updates here?

**Comment by Pratyush-Saxena** [comment]
@Tanuj22 ..actually i am new to react and on my way in learning it , so it may take up some more time . i guess you must assign it to someone else, if you want it to be completed in a set of time .

**Comment by Nikhil-Ladha** [comment]
Thank you for the heads up @Pratyush-Saxena :+1: 
@Neilblaze ^^, ping me once you are ready :slightly_smiling_face:

**Comment by ashutosh1401** [comment]
I could resolve this one if it isn't assigned to someone

**Comment by Neilblaze** [comment]
@ashutosh1401 Sure! Go for it! :+1:

**Comment by ashutosh1401** [comment]
Do i need to create a folder in pages section about partners and its component in sections and in this way a separate route would be created of partner section

**Comment by Tanuj22** [comment]
@ashutosh1401 Yes

**Comment by ashutosh1401** [comment]
Where could i get those images

**Comment by Tanuj22** [comment]
> Where could i get those images

Download it from the current site. You can keep them in a partners folder inside src/images folder

**Comment by ashutosh1401** [comment]
Is material icons are used in layer5-ng or any other icons are used ?

**Comment by Tanuj22** [comment]
> Is material icons are used in layer5-ng or any other icons are used ?

`react-icons`

**Comment by Jashpatel1** [comment]
Closing this with #993 . Opening up another issue for change in the layout
