### ISSUE TITLE
[NG] Migrate site data for the Careers page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#710]
**Description**
Currently, the page dedicated to [Careers](https://layer5ng.netlify.app/careers) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Careers](https://layer5.io/careers) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
@alabobriggs Would you like to take this up?

**Comment by alabobriggs** [comment]
Yes I will jump on this.

**Comment by Jashpatel1** [comment]
@alabobriggs Hey if you are stuck somewhere, please feel free to ask out. I would be happy to help you with your contribution to Layer5.

**Comment by chandrashritii** [comment]
@vinayaksh42 Would you like to take this on?

**Comment by vinayaksh42** [comment]
Sure @chandrashritii

**Comment by Jashpatel1** [comment]
Fixed in #783
