### ISSUE TITLE
[NG] Migrate the site data for the Contact page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#711]
**Description**
Currently, the page dedicated to [Contact](https://layer5ng.netlify.app/contact) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Contact](https://layer5.io/contact) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by dea1j** [comment]
I will like to take up this issue

**Comment by leecalcote** [comment]
hi @dea1j, that sounds great!

**Comment by chandrashritii** [comment]
@dea1j Thank you for taking this on! Please let me know if you stumble across any roadblocks while solving this issue. I'll do my best to help you out 🎈

**Comment by Tanuj22** [comment]
Hey, @dea1j are you still working on this?

**Comment by kishore007k** [comment]
I would love to work on this! If it is still open
