### ISSUE TITLE
[NG] Migrate the site data for the Brand page

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#712]
**Description**
Currently, the [Brand page](https://layer5ng.netlify.app/company/brand) on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error. 

**Expected Behavior**

The data from the [Brand page](https://layer5.io/brand) on the [layer5.io site](https://layer5.io/) needs to be migrated to the layer5-ng site. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by chandrashritii** [comment]
@iamsurajdc Do you want to take this one up?

**Comment by iamsurajdc** [comment]
@chandrashritii Sure.

**Comment by chandrashritii** [comment]
@iamsurajdc Thank you for taking this on! Please let me know if you need any help or have any questions regarding this issue 🎈
