### ISSUE TITLE
[NG] Migrate the site data for the Landscape page (Resources section) 

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#714]
**Description**
Currently, the following pages on the Resources section on the [layer5-ng site](https://layer5ng.netlify.app/) points to a 404 error:

- [ ]  [Service Mesh Comparison](https://layer5ng.netlify.app/landscape)
- [ ] [Service Mesh Tools](https://layer5ng.netlify.app/landscape#tools)

[Service Mesh Books](https://layer5ng.netlify.app/learn/books) - Issue #780 
[Service Mesh Workshops](https://layer5ng.netlify.app/learn/workshops) - Issue #781 

**Expected Behavior**

The data can be sourced from the following pages on the [layer5.io site](https://layer5.io/):

- [Service Mesh Comparison](https://layer5.io/landscape)
- [Service Mesh Tools](https://layer5.io/landscape#tools)
- [Service Mesh Books](https://layer5.io/books)
- [Service Mesh Workshops](https://layer5.io/workshops)

**Note**

**Individual PR's may be opened by different contributors for the four pages separately. Kindly add `This PR references #"Issue-number"` to your PR when you attempt to do so.**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by iambami** [comment]
I'll love to solve this

**Comment by leecalcote** [comment]
Excellent, @iambami 👍

**Comment by leecalcote** [comment]
@chandrashritii will you mark this issue as an epic and open two other issues with the `issue/child` label: workshops and books? The Landscape should be it's own issue.

The title of this issue is identical to the title of issue #713

**Comment by tripathyprateek** [comment]
@chandrashritii I will take up this issue if no one is assigned.

**Comment by Nikhil-Ladha** [comment]
Sure @tripathyprateek . Go ahead.
Take the data from the existing site, but feel free to come up with some innovative and cool design.

**Comment by geraldmaboshe** [comment]
Hey @chandrashritii I would like to take this up

**Comment by Neilblaze** [comment]
@geraldmaboshe Sure! Go for it :+1:
