### ISSUE TITLE
[README] Bug: Misspelling needs fixed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#716]
**Description**
The readme.md in this repo has the following error:

<img width="826" alt="Screen Shot 2020-09-04 at 9 48 02 AM" src="https://user-images.githubusercontent.com/7570704/92252456-dd61d180-ee93-11ea-9745-7286a8a62cce.png">

**Comment by leecalcote** [comment]
THanks, @Josephchinedu 👍

**Comment by wesley-moody** [comment]
Taken care of. Thank you!

**Comment by Josephchinedu** [comment]
should i remove open that ends it

**Comment by Josephchinedu** [comment]
i mean "Open" after the calendar

**Comment by PluckyPrecious** [comment]
> Taken care of. Thank you!

Hello @wesley-moody this issue was already assigned to someone else.

**Comment by Josephchinedu** [comment]
Fixed. waiting for contributor to review and merge it
