### ISSUE TITLE
[SMP] Add KubeCon EU talk to performance project page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#719]
**Current Behavior**
KubeCon EU talks are out. [This talk](https://www.youtube.com/watch?v=rgnb0-ntPko&list=PL3A-A6hPO2IOpTbdH89qR-4AE0ON13Zie) needs to be added to the second section of this page - https://layer5.io/projects/service-mesh-performance.

It would be nice if this talk is embedded as a Youtube video on this page  - https://github.com/layer5io/layer5/blob/master/collections/_projects/service-mesh-performance.md. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by abadon7** [comment]
Hi @leecalcote. I would like to help with this as my first PR.

**Comment by leecalcote** [comment]
Thank you, @abadon7. That would be great.

**Comment by leecalcote** [comment]
@abadon7 you're most welcome to join the Layer5 community as well: http://slack.layer5.io

**Comment by abadon7** [comment]
Hi @leecalcote. I did not notice, before PR, that the information in "/collections/_projects/service-mesh-performance.md" appears on https://layer5.io/projects/service-mesh-performance, in the way see it, as the first section of the page and "_includes/performance.html" as second one. So with the video in both files, it appears on the page duplicated. Please, help me know what I am missing. Thanks.
