### ISSUE TITLE
[NG] Mega Menu Losing Focus

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#725]
**Description**
The mega menu appears and disappears undesirably. 

**Expected Behavior**
Once the menu appears, it should remain visible so long as the user's mouse is in the same menu area.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/7570704/92333340-396e5680-f04a-11ea-9bd5-4b1eccc476f0.gif)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
@shivaylamba we're going stale here. ;)

**Comment by leecalcote** [comment]
@vineethvanga18 as you dig into the Mega Menu, will you add the ability to include a separator between list items? This screenshots shows a red horizontal line that would ideally be light gray. An attribute in data.js could be added to identify whether a specific menu item should have this horizontal line above it.

Will you also add the ability for a given menu to have a call to action link (bottom aligned)? 
<img width="1030" alt="Screen Shot 2020-11-24 at 9 49 29 PM" src="https://user-images.githubusercontent.com/7570704/100181464-eca75880-2e9f-11eb-8b9b-14d3d4b624e7.png">

**Comment by Jashpatel1** [comment]
@leecalcote Is it addressed completely?

**Comment by leecalcote** [comment]
@Jashpatel1, other than issues with the overall size of the menu and the desire to move away from showing the two feature highlights as cards, yes.

**Comment by leecalcote** [comment]
We can open a new issue for the other mega menu items, @vineethvanga18

**Comment by vineethvanga18** [comment]
Okay @leecalcote. Do you want me to do that?

**Comment by leecalcote** [comment]
Yes, please.

**Comment by vineethvanga18** [comment]
@leecalcote should the images be displayed as cards?

**Comment by vineethvanga18** [comment]
Also should I close this issue now?

**Comment by leecalcote** [comment]
Sounds real good, yes. Mission accomplished here.
