### ISSUE TITLE
[Community] Hyperlink to community incident form in code of conduct

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#729]
**Current Behavior**
The https://layer5.io/community page has a section describing the code of conduct:

```

Code of Conduct
The comfort and safety of Layer5 community members is our priority. 
You must agree to the Code of Conduct to participate in the Layer5 community, 
and any violations of the Code of Conduct will be taken seriously. To report any 
violations please fill out this incident form.

```

**Desired Situation**
The text "this incident form" in the paragraph above should have the Layer5 Community Incident Report form hyperlinked and available to receive incident reports - https://docs.google.com/forms/d/e/1FAIpQLSeWzC5HjlHugFjB0TtaAVnSkPPqsRQ3JRYjdwyDXf0oyRxcdQ/viewform

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ashleypean** [comment]
I’d love to work on this one if it’s not taken

**Comment by leecalcote** [comment]
@ashleypean, that would be most helpful. Yes, thank you.
