### ISSUE TITLE
[Community] Hyperlink to full-length code of conduct on Community page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#730]
**Current Behavior**
The https://layer5.io/community page has a section describing our code of conduct:

```

Code of Conduct
The comfort and safety of Layer5 community members is our priority. 
You must agree to the Code of Conduct to participate in the Layer5 community, 
and any violations of the Code of Conduct will be taken seriously. To report any 
violations please fill out this incident form.

```

**Desired Situation**
In the second sentence of the paragraph above, the text "Code of Conduct" should have the Layer5 Code of Conduct hyperlinked and available to view. Hyperlink: `/terms/code-of-conduct`

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by NorbertLuszkiewicz** [comment]
Hey I would love to tackle this one

**Comment by Jashpatel1** [comment]
@leecalcote Is the page created for the link you mentioned as I cant find one on the website?

**Comment by leecalcote** [comment]
@NorbertLuszkiewicz sounds great. Thank you. 🎈 

@Jashpatel1, you're right. This URL is (was) absent. It should now be present as of the merge of #728

**Comment by leecalcote** [comment]
@NorbertLuszkiewicz if you haven't received an invitation to join the Layer5 community, please consider this your special invitation. 😄 There are a number of resources available to community members here - http://slack.layer5.io (no obligation to join, just want to ensure that you know you're most welcome to).
