### ISSUE TITLE
[NG] Create a card component for news and blogs pages 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#735]
**Current Behavior**
The [news](https://layer5ng.netlify.app/news) and [blog](https://layer5ng.netlify.app/blog) pages of the layer5ng site uses contains a card. The code and the styles are being repeated in these pages for the card. 

**Desired Behavior**
Create a separate card component that can be imported into these pages.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Nikhil-Ladha** [comment]
Closed #736
