### ISSUE TITLE
[UI]: Add a filter feature for the active/inactive members

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#739]
**Current Behavior**

Currently, the layer5.io/community/members page contains 2 buttons (legends) to represent the active/inactive status of the members in the community.
 
**Desired Behavior**

A new `category` front-matter can be added to all the member profiles which should state active/inactive, and based on that filtering should happen. Upon, filtering the desired URL should be 
layer5.io/community/active/members <-- For active members
layer5.io/community/inactive/members <-- For inactive members

Basically, in the above URL, the active/inactive is the category value from the member profile.

---
[Optional] **In case of any doubts**

Feel free to reach out to @Nikhil-Ladha or the websites channel on slack.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
I would like to work on this. If this is still open.

**Comment by Nikhil-Ladha** [comment]
Sure!
