### ISSUE TITLE
Add OpenShift to landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#74]
@thoraxe, it'd be great to have OpenShift represented in the [landscape](https://layer5.io/landscape). Will you consider a contributing a PR to ensure its accuracy?

Perhaps, under the "Commercial Offerings" column for Istio?

**Comment by leecalcote** [comment]
/cc @mwringe - in addition to OpenShift, it'd be good to ensure that Kiali is well-represented. Will you consider a PR against the tools section? https://layer5.io/landscape/#tools

This landscape is being referenced in three O'Reilly books on the topic of service meshes.

**Comment by mwringe** [comment]
@leecalcote I created a PR for Kiali here: https://github.com/layer5io/layer5/pull/77

**Comment by thoraxe** [comment]
Given that Red Hat is not currently planning to sell Istio as a stand-alone product, would you still consider it a "commercial offering" given that it's included as a feature of OpenShift?

I'm happy to add OpenShift here.

**Comment by leecalcote** [comment]
@thoraxe good call out. I agree that listing of OpenShift as a commercial offering, perhaps, is conflating of OpenShift's larger functionality and detracting of the focus of this service mesh-centric landscape. Thanks for highlighting this.
