### ISSUE TITLE
[Docs] Update Layer5 Contributing Doc

### ISSUE THREAD

**Issue by PluckyPrecious** [layer5io/layer5#746]
**Current Behavior**
The CONTRIBUTING.md is missing the caveat about Jekyll production & dev env amongst others.

**Desired Situation**

[ ] Add [this caveat as seen in line 71](https://github.com/layer5io/service-mesh-performance/commit/a8af02878eb4711ccadb2e4fe01dad7b65a5b1b3#diff-6a3371457528722a734f3c51d9238c13)  to the [CONTRIBUTING.md](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#contribution-flow) Contribution Flow section.

[ ] Update Set up your development environment section as seen in line [49-54](https://github.com/layer5io/service-mesh-performance/commit/a8af02878eb4711ccadb2e4fe01dad7b65a5b1b3#diff-6a3371457528722a734f3c51d9238c13).

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by PluckyPrecious** [comment]
Hey @Hack-Light here's a good issue to get started with. 😃

**Comment by Hack-Light** [comment]
Ok, let me take on this

**Comment by PluckyPrecious** [comment]
Awesome!
