### ISSUE TITLE
Batch Transition to MeshMate Emeritus

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#750]
**Current Behavior**
Some members of our initial batch of MeshMates have become inactive in their role and in the community.

**Desired Situation**
The following MeshMates should be transitioned to _MeshMate Emeritus_.

- Naveen Jain
- Kanishkar J
- Ashis Kumar Singh
- Shivay Lamba

**(f) MeshMate Emeritus; Program Graduation.** Once a MeshMate, always a MeshMate. Despite this sentiment, inevitably, there will come a time when any given MeshMate may need to move on. In these instances, you may signal your desire to become a MeshMate Emeritus, by communicating this request to any of the MeshMate Program Managers. MeshMates move on from the program for any given reason: your focus may shift, you might change jobs, your technological interests may change, and so on. 

Whatever the reason, when you can or are no longer dedicating the time needed to handle the responsibilities of being an active MeshMate. When this happens, you are encouraged to add yourself as a MeshMate Emeritus. Like any other member of the community, how actively involved you are may fluctuate over time. You might return and desire to resume your post as a MeshMate. When an emeritus returns to being more active in the community, you may be promoted back to at the discretion of the MeshMate Program Managers.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
// @Nikhil-Ladha @NupurThakur27 @vijcheru @kushthedude

**Comment by Nikhil-Ladha** [comment]
Closed #757
