### ISSUE TITLE
[Community] Style MeshMate cards similarly to member cards

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#751]
**Description**
The cards on this page - https://layer5.io/community/meshmates - need to change color on hover like the member cards on https://layer5.io/community/members.

**Resources**
- [Collection of members](https://github.com/layer5io/layer5/tree/master/collections/_members)
- [Relevant style](https://github.com/layer5io/layer5/blob/master/assets/css/materialize.css#L2868-L2892) (some but maybe not all of it) 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by NorbertLuszkiewicz** [comment]
Hey I would love to tackle this one

**Comment by Nikhil-Ladha** [comment]
Hi @NorbertLuszkiewicz yes please, go ahead.
