### ISSUE TITLE
Visually distinguish categories in Functional section

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#76]
With the insertion of all categories of projects related to service meshes, the Functional table has become hard to read and garner insight from. Either by row color or some other mechanism, let's provide visual indication of groupings of items in by category in the functional table in the landscape.

**Comment by leecalcote** [comment]
@yogi4 Can we color cut this table not by alternating rows, but by category?

**Comment by yogi4** [comment]
@leecalcote sent out a pull request for this , waiting on PR and Merge to close this issue

**Comment by yogi4** [comment]
This has been resolved
