### ISSUE TITLE
SMP section listed twice on the brand page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#766]
**Description**
On the https://layer5.io/brand page, the SMP section is listed twice. See the screenshot below.

**Expected Behavior**
SMP section should only be shown 

**Screenshots**
<img width="1037" alt="Screen Shot 2020-09-14 at 7 42 29 AM" src="https://user-images.githubusercontent.com/7570704/93091361-95953400-f663-11ea-92de-26aae9883e8a.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by NorbertLuszkiewicz** [comment]
I would like to work on this issue

**Comment by Tanuj22** [comment]
Go ahead @NorbertLuszkiewicz

**Comment by Tanuj22** [comment]
Fixed in #767
