### ISSUE TITLE
[NG] Duplicative "every" listed in `banner` module

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#768]
**Description**
Two "every"s are included in the header in the `banner` module.

**Expected Behavior**
Only the emphasized (bolded) "every" should be shown.

**Screenshots**
<img width="696" alt="Screen Shot 2020-09-14 at 2 13 34 PM" src="https://user-images.githubusercontent.com/7570704/93128278-d9ecf800-f694-11ea-9e66-140a7d980f04.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Harshita-Kanal** [comment]
Can I take this up ?

**Comment by Tanuj22** [comment]
@Harshita-Kanal Go ahead

**Comment by Tanuj22** [comment]
Fixed in #772
