### ISSUE TITLE
[NG] Remove unused styles  

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#770]
**Current Behavior**
The single blog page and the single news page contains many unused styles. The styles are also found for the single blog page [here](https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/Blog-single/blogSingle.style.js) and the single news page [here](https://github.com/layer5io/layer5/blob/layer5-ng/src/sections/News-single/NewsSingle.style.js). 

**Desired Situation**
Remove any classes or tag styles not being used. 

Note: The styles are only being used in the corresponding `index.js` files where the stylesheets are present. 

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by vinayaksh42** [comment]
Can i work on this issue? @leecalcote @Tanuj22

**Comment by Tanuj22** [comment]
Please go ahead @vinayaksh42
