### ISSUE TITLE
[chore] Add updated meeting links to the readme

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#771]
**Description**

Replace the respective zoom links for all the Layer5 meeting with the redirected links in the [Readme](https://github.com/layer5io/meet), for example: Layer5 community meeting: https://meet.layer5.io/community
The redirected links have been updated in the Layer5 community calendar and can be sourced from there.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by agalakova-m** [comment]
Hello there! I would be glad to help, but I can't reach community calendar by this link: https://calender.google.com/calendar/b/1?cid=bGF5ZXI1LmlvX2VoMmFhOWRwZjFnNDBlbHZvYzc2MmpucGhzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20

**Comment by leecalcote** [comment]
@agalakova-m, thank you for volunteering here. That's great. Hmm. Perhaps, this link will do the trick:

https://calendar.google.com/calendar/u/0/r?cid=bGF5ZXI1LmlvX2VoMmFhOWRwZjFnNDBlbHZvYzc2MmpucGhzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20&pli=1

**Comment by leecalcote** [comment]
Also, here's a helpful listing of the revised links - https://github.com/layer5io/meet/blob/master/README.md

**Comment by agalakova-m** [comment]
Ok, thanks! But now I'm not sure what file we are talking about, I should change the original Readme.md (https://github.com/layer5io/layer5/blob/master/README.md), right? I just can't see any zoom links in here. Sorry if it's kind of misunderstanding

**Comment by chandrashritii** [comment]
@agalakova-m 
The revised links can be found here - https://github.com/layer5io/meet/blob/master/README.md. I'll explain with an example. 
For the Layer5 community meeting:
- meet.layer5.io/community: https://zoom.us/j/92211493668

The revised link would be https://meet.layer5.io/community

**Comment by sumana-19** [comment]
@chandrashritii  I'd be interested to do this. Can you assign this to me?

**Comment by sumana-19** [comment]
@leecalcote  Thanks for assigning this to me. So, do I have to just replace the Zoom meeting links with the link https://meet.layer5.io/community, right?

**Comment by chandrashritii** [comment]
@sumana-19 Yes. You simply have to list the meeting links in the below format on https://github.com/layer5io/meet/blob/master/README.md:
 Layer5 community Meeting -  https://meet.layer5.io/community

You may source the meeting links from the meetings table on https://layer5.io/community.

**Comment by chandrashritii** [comment]
@sumana-19 Do let me know if you have any other questions
