### ISSUE TITLE
[Project] Service Mesh Interface: text alignment

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#773]
**Description**
The text on the [Service Mesh Interface project](https://layer5.io/projects/service-mesh-interface) is center-aligned (see screenshot).

**Expected Behavior**
This text should be left-aligned.

**Screenshots**
<img width="1375" alt="Screen Shot 2020-09-15 at 5 58 28 AM" src="https://user-images.githubusercontent.com/7570704/93211306-a8247180-f726-11ea-9206-c36bb3232957.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Pratyush-Saxena** [comment]
@leecalcote i would like to take up this one....as my first contribution to layer5

**Comment by Tanuj22** [comment]
@Pratyush-Saxena please go ahead

**Comment by Pratyush-Saxena** [comment]
@Tanuj22 @leecalcote ...While setting up dev enviroment ...i m getting this error
``` ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory```...
pls help me in getting through this..

**Comment by Nikhil-Ladha** [comment]
> @Tanuj22 @leecalcote ...While setting up dev enviroment ...i m getting this error
> ` ruby: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory`...
> pls help me in getting through this..

Are you on windows, @Pratyush-Saxena ?

**Comment by Pratyush-Saxena** [comment]
no ...I use manjaro linux

**Comment by Nikhil-Ladha** [comment]
Okay, then if you are using ruby installed fron the linux package manager. I would suggest to remove it, and use rvm instead for ruby and then try it again.

**Comment by Tanuj22** [comment]
> Okay, then if you are using ruby installed fron the linux package manager. I would suggest to remove it, and use rvm instead for ruby and then try it again.

@Pratyush-Saxena alse do take care that you install ruby 2.7.0

**Comment by Pratyush-Saxena** [comment]
> Okay, then if you are using ruby installed fron the linux package manager. I would suggest to remove it, and use rvm instead for ruby and then try it again.
@Nikhil-Ladha can u pls ...explain how should i do that

**Comment by Nikhil-Ladha** [comment]
The procedure is listed in the contributing guide AFAIRC. @chandrashritii @PluckyPrecious can you guys please point it out that?

**Comment by Nikhil-Ladha** [comment]
You can remove ruby then, install rvm from this link https://rvm.io/ 
Then, install ruby-2.7.0 using rvm itself, and set is as the default version. Then, try building the site.

**Comment by chandrashritii** [comment]
@Pratyush-Saxena 
Completely remove the currently installed version(s) of ruby from your system and do a clean install. The archlinux wiki instructions for installing ruby with rvm should work for manjaro linux. Try following this [tutorial](https://wiki.archlinux.org/index.php/RVM). 
Another good [reference source](https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-on-arch-linux-with-rvm). Once you have rvm installed, you can go ahead and install ruby-2.7.0 using rvm, as @Nikhil-Ladha and @Tanuj22 have suggested. Hope this helps :)

**Comment by Pratyush-Saxena** [comment]
@leecalcote @Nikhil-Ladha @chandrashritii @Tanuj22 ...i just make this website run with ruby v2.7.1(coz as i said before i m unable to setup dev env on my local machine so I m working on gitpod which supports v2.7.1) and i found the issue  resolved automatically ..... i guess should now use rubyv2.7.1
![demo](https://user-images.githubusercontent.com/52444607/93671328-a90b2980-fabf-11ea-8e1c-982042abe545.png)

**Comment by Nikhil-Ladha** [comment]
Means, you are saying the issue is with ruby 2.7.0?
But, all of the members here are running it on the same version 🤔. Maybe, some other issue might have occurred which you are missing or so.

**Comment by Pratyush-Saxena** [comment]
> Means, you are saying the issue is with ruby 2.7.0?
> But, all of the members here are running it on the same version . Maybe, some other issue might have occurred which you are missing or so.

I think we must check it out if the site is ready to get updated with ruby v2.7.1.....
