### ISSUE TITLE
Add Hyperfoil as a tool to the landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#78]
Hi @rvansa, will you consider adding a listing for [Hyperfoil](https://github.com/Hyperfoil/Hyperfoil) to the [service mesh landscape](https://layer5.io/landscape) under the [Tools](https://github.com/layer5io/layer5/blob/master/_includes/service-mesh-tools.html) section? Given its use for load testing istio and envoy, we'd love to have an accurate listing of the tool described here.

**Comment by rvansa** [comment]
Makes sense, thanks for pointing this out.

**Comment by leecalcote** [comment]
Thank you for this, @rvansa
