### ISSUE TITLE
[NG] Migrate the site data for the Books page (Resources section)

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#780]
**Description**

Currently, the following page on the Resources section on the [layer5-ng](https://layer5ng.netlify.app/) site points to a 404 error:

[Service Mesh Books](https://layer5ng.netlify.app/learn/books) 

Migrate the content from the Layer5.io site. The data can be sourced from the following page on the [layer5.io](https://layer5.io/) site:

[Service Mesh Books](https://layer5.io/books)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@chandrashritii this is already done https://layer5ng.netlify.app/books

**Comment by chandrashritii** [comment]
Thanks @Tanuj22 

Closing #780
