### ISSUE TITLE
[NG] Migrate the site data for the Workshops page (Resources section)

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#781]
**Description**

Currently, the following page on the Resources section on the [layer5-ng](https://layer5ng.netlify.app/) site points to a 404 error:

[Service Mesh Workshops](https://layer5ng.netlify.app/learn/workshops)

Migrate the content from the Layer5.io site. The data can be sourced from the following page on the [layer5.io](https://layer5.io/) site:

[Service Mesh Workshops](https://layer5.io/workshops)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by JubayerJoy** [comment]
Hi @chandrashritii, I will take it if no one is pre-assigned.

**Comment by chandrashritii** [comment]
Sure @JubayerJoy Go ahead 👍

**Comment by Tanuj22** [comment]
@JubayerJoy are you working on this?

**Comment by JubayerJoy** [comment]
Hi @Tanuj22!
I am still learning gatsby, It'll take time.
Feel free to take this if you want.

**Comment by Jashpatel1** [comment]
@kishore007k Do you want to give it a try?

**Comment by kishore007k** [comment]
Yeah sure! @Jashpatel1

**Comment by Jashpatel1** [comment]
Closing with #951
