### ISSUE TITLE
Change SEO title 

### ISSUE THREAD

**Issue by Pratyush-Saxena** [layer5io/layer5#789]
**Current Behavior**

seo title must be change of some pages in [layer5ng](https://layer5ng.netlify.app)..like [gsoc](https://layer5ng.netlify.app/gsoc) , [gsod](https://layer5ng.netlify.app/gsod) and others if any...
![seo_title](https://user-images.githubusercontent.com/52444607/93707368-8aeb0b00-fb4b-11ea-8056-c2610cca06ae.png)

**Desired Behavior**

![seo](https://user-images.githubusercontent.com/52444607/93707390-c8e82f00-fb4b-11ea-8afc-a24bbf25b9ea.png)

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Nikhil-Ladha** [comment]
It is so because the links are not set correctly yet, as the pages are not ready.

**Comment by tripathyprateek** [comment]
Yes, this can be taken up later once all the pages are designed.

**Comment by Pratyush-Saxena** [comment]
ok then i think we should close it for now!!!

**Comment by tripathyprateek** [comment]
@Pratyush-Saxena feel free to take a look around. There are a lot of issues you can contribute to.
