### ISSUE TITLE
[Community] Fix styling of Community Members page

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#791]
**Description**

In the [community members](https://layer5.io/community/members) page, the current desktop-mode view is this :-

![Community_memb](https://user-images.githubusercontent.com/48355572/93720728-81dc5700-fba8-11ea-8021-40b90cb9048b.JPG)

We need to change the styling to this :-

![Community_memb2](https://user-images.githubusercontent.com/48355572/93720740-96b8ea80-fba8-11ea-8a70-09b525e79b2e.JPG)

**Expected Changes**

Follow the second screenshot!

- Align the `A warm and welcoming collection of open sourcers.` (description text) to center, just below the `Community Members` header-name.
- Bring the `Active / Inactive` legend just below the description text & align it in center.
- Fix the positioning of 1st profile card. 

**Environment:**
 - OS: [Windows / Ubuntu]
 - Browser: [e.g. Chrome, Firefox, Safari]

**NOTE :** The mobile view / responsive view has no issues!

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
Hey @leecalcote  If this issue is still open I'm interested.

Is this how it should be?

### Desktop View :

![Desktop View](https://user-images.githubusercontent.com/34863222/93908253-0b606600-fd1c-11ea-974c-5c5760098b11.PNG)

### Tablet View :

![Tablet View](https://user-images.githubusercontent.com/34863222/93908260-0d2a2980-fd1c-11ea-8c94-127a9b759873.PNG)

### Mobile View :

![Mobile View](https://user-images.githubusercontent.com/34863222/93908265-0d2a2980-fd1c-11ea-9f08-b4a4c41e1e2c.PNG)

**Comment by Nikhil-Ladha** [comment]
The legend must be right aligned. In all the views.

**Comment by kishore007k** [comment]
@Nikhil-Ladha But in the issue, @leecalcote  mentioned it to be in the center.

**Comment by Nikhil-Ladha** [comment]
I don't think it would look good, in the centre.
I myself created this page, but due to some other changes this issue has occured.

**Comment by kishore007k** [comment]
Ok Sure will do that. @Nikhil-Ladha

**Comment by Neilblaze** [comment]
@Nikhil-Ladha Idk why but I think the desktop view and the tablet view looks fine here, but for the mobile view the legend alignment can be changed to like what it is in desktop view or like in stack like structure.

**Comment by Nikhil-Ladha** [comment]
Well, as per the design the legends should be aligned to either side of the screen and not in the centre.

Let's have few more suggestions here
@leecalcote @Tanuj22 @Jashpatel1 @chandrashritii

**Comment by Neilblaze** [comment]
Yeah I'm taking suggestions whether that looks better on the center or in the either side of the screen :smiley:

**Comment by kishore007k** [comment]
@Nikhil-Ladha Is this ok?

![Capture10](https://user-images.githubusercontent.com/34863222/94137688-6ca34900-fe84-11ea-9967-5ecf074f24ce.PNG)

**Comment by Nikhil-Ladha** [comment]
The text should be in center, and the legend should be in next line, aligned to the right.

**Comment by kishore007k** [comment]
This issue has already solved But why is it not yet closed?
Reference #814  
@Nikhil-Ladha @Neilblaze @leecalcote

**Comment by Nikhil-Ladha** [comment]
Because you didn't mention the the issue number in the PR description like 'The PR fixes #<issue_number>'.

**Comment by Nikhil-Ladha** [comment]
Closed #814

**Comment by leecalcote** [comment]
@kishore007k - https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by kishore007k** [comment]
@leecalcote Thank you for the reference.
