### ISSUE TITLE
Fix the styling of Workshops page!

### ISSUE THREAD

**Issue by Neilblaze** [layer5io/layer5#792]
**Current Behavior :-**

In the [workshops](https://layer5.io/workshops) page, the styling of the cards needs to be improved. With that the position & alignment issues of the illustrations needs to be fixed. I am attaching two images, one of them refers to the screenshot of the workshop page of the current [Layer5](https://layer5.io) site; and another one is for the required changes.

**Screenshots :-**

- Existing site :
![Existing_site](https://user-images.githubusercontent.com/48355572/93721494-50ff2080-fbae-11ea-89a1-5b3cb0e150dd.png)

- Expected changes :
![L5_Workshop_2](https://user-images.githubusercontent.com/48355572/93721503-62482d00-fbae-11ea-8abe-865e7c3e2b2b.png)

Click on the second image, go through it. There the required changes are listed in appropriate order!
---

**NOTE :-**

This issue is reflective on both desktop-view & mobile view. So both of them has to be taken in consideration :)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Pratyush-Saxena** [comment]
@Neilblaze can I take up this issue..

**Comment by Neilblaze** [comment]
Sure! Go for it. :+1:

**Comment by Pratyush-Saxena** [comment]
@Neilblaze please checkout my pr #820

**Comment by Neilblaze** [comment]
@Pratyush-Saxena added review on #820

**Comment by leecalcote** [comment]
@Pratyush-Saxena thank you for your efforts here. 👍

**Comment by Tanuj22** [comment]
FIxed in #820
