### ISSUE TITLE
[NG] Add community page

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#793]
Create the [community page ](https://layer5.io/community) for `layer5-ng` site

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@vinayaksh42 would you like to work on this?

**Comment by vinayaksh42** [comment]
> @vinayaksh42 would you like to work on this? 

Sure I would like to do this issue

**Comment by Tanuj22** [comment]
@vinayaksh42 any updates here?

**Comment by vinayaksh42** [comment]
sorry for the delay. I am on it now @Tanuj22

**Comment by Tanuj22** [comment]
@vinayaksh42 are you working on this?

**Comment by Tanuj22** [comment]
@vinayaksh42 we need to move ahead. Unassigning you so other contributors can take a crack at it.

**Comment by codetheorem** [comment]
@Tanuj22 assign this to me.
