### ISSUE TITLE
[NG] Migrate Projects to the layer5-ng site

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#794]
**Current Behavior**

The Projects section has just SMP added currently in the layer5-ng website.

**Desired Situation**
Add projects(excluding Meshery and Landscape) to the project folder in collections. A project(Service mesh Performance) has been added for reference. The data can be found at the [Projects Page](https://layer5.io/projects).

- [ ] Distributed Performance Management Page ([Data](https://layer5.io/projects/service-mesh-distributed-performance-management))
- [ ] Image Hub Page ([Data](https://layer5.io/projects/image-hub))
- [ ] Service Mesh Interface Conformance Page ([Data](https://layer5.io/projects/service-mesh-interface))

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Harshita-Kanal** [comment]
I can do this, by when am I supposed to complete it ?

**Comment by Jashpatel1** [comment]
> I can do this, by when am I supposed to complete it ?

There is no such deadline, just be comfortable in working on it. You can ping on slack if you get stuck anywhere.

**Comment by Harshita-Kanal** [comment]
Can I take it up ?

**Comment by Tanuj22** [comment]
@Jashpatel1 you can create separate issues for each of  the projects to help move it faster
