### ISSUE TITLE
[Meshery] Broken image for Maesh logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#800]
**Description**
The multi-mesh table on the layer5.io/meshery page has a broken image.

**Expected Behavior**
An svg of the Maesh logo should be stored in this repo and displayed in the table.

**Screenshots**
<img width="640" alt="Screen Shot 2020-09-22 at 7 43 28 AM" src="https://user-images.githubusercontent.com/7570704/93883590-61df8d00-fca7-11ea-90c7-bd9e6d7990dd.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by bartkalanski** [comment]
Hi! Would you mind if I have a go at this ?

**Comment by Neilblaze** [comment]
@bartkalanski Sure! Go for it. :+1:

**Comment by Neilblaze** [comment]
@leecalcote it's also there for the [meshery readme](https://github.com/layer5io/meshery/blob/master/README.md) too!

![yoyo](https://user-images.githubusercontent.com/48355572/94187390-83b65b00-fec5-11ea-8d23-1929937d54fb.JPG)
