### ISSUE TITLE
[NG] Change the position of external link on the card

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#809]
**Desired Behavior**
Move the external link icon to the right of the card. Changes are to be made in [`components/Card`](https://github.com/layer5io/layer5/tree/layer5-ng/src/components/Card) directory.

Check out https://layer5ng.netlify.app/news for this

![Screenshot from 2020-09-24 01-55-30](https://user-images.githubusercontent.com/42486853/94066040-8ce1f200-fe09-11ea-848b-2d8de822b6e3.png)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by NorbertLuszkiewicz** [comment]
I would like to take up this one

**Comment by Tanuj22** [comment]
Please go ahead @NorbertLuszkiewicz
