### ISSUE TITLE
Update color according to the color code

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#818]
**Description**
The [brand page](https://layer5.io/brand) has one of the colors mentioned as #00d3a9, but the color card it maps to is given as black.

**Expected Behavior**
Update the color in the color card to #00d3a9.

**Screenshots**
![image](https://user-images.githubusercontent.com/43696490/94223041-97d17b00-ff0c-11ea-9b49-c3a4b206bd80.png)

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by manishkrjha** [comment]
Is this issue assigned to anyone? If not then I can fix this.

**Comment by Jashpatel1** [comment]
> Is this issue assigned to anyone? If not then I can fix this.

Noone is assigned yet. Please go ahead.
