### ISSUE TITLE
[Books] Buttons misaligned on service mesh book

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#821]
**Description**
The book on [this webpage](https://layer5.io/books/the-enterprise-path-to-service-mesh-architectures) has buttons landing on the side of it. See screenshot. Source code for the page [is here](https://github.com/layer5io/layer5/blob/master/collections/_books/2018-06-11-the-enterprise-path-to-service-mesh-architectures.md).

**Expected Behavior**
Buttons should be beneath the book.

**Screenshots**
<img width="1309" alt="Screen Shot 2020-09-25 at 6 07 20 PM" src="https://user-images.githubusercontent.com/7570704/94323090-1dc7e300-ff5a-11ea-8b86-088b42a826b9.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Jashpatel1** [comment]
@leecalcote Can we add the hacktoberfest label here?

**Comment by leecalcote** [comment]
Sounds great, yes. Hopefully, someone picks it up sooner, but, yes.

**Comment by bartkalanski** [comment]
I'm working on a React project atm but could probably get this done by Monday ?

**Comment by knowyours** [comment]
Hello, this is my very first open source contribution. Can I get a bit more information about which file I have to work on?

**Comment by knowyours** [comment]
I made a change that corrects this issue and made a PR but forgot to ask to be assigned to the issue? Can I work on this?

**Comment by Nikhil-Ladha** [comment]
You are most welcome to do so @knowyours 💯
