### ISSUE TITLE
[NG] Migrate recent two blogs to Layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#825]
**Current Behavior**
Recently, two [blogs](https://layer5.io/blog) have been added to layer5.

**Desired Situation**
Migrate those two blogs to the layer5-ng website.

- [ ] [Announcing Meshery v0.4.0](https://layer5.io/blog/meshery/announcing-meshery-v0.4.0)
- [ ] [My Journey from a contributor to maintainer](https://layer5.io/blog/community/my-journey-from-a-contributor-to-a-maintainer)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ashutosh1401** [comment]
Could i work on this issue if it is still open

**Comment by Jashpatel1** [comment]
@manishdangi98 Are you still working on it?

**Comment by manishdangi98** [comment]
Yes, @Jashpatel1, I have migrated one blog, [My Journey from a contributor to maintainer](https://layer5.io/blog/community/my-journey-from-a-contributor-to-a-maintainer); this is remaining today. I will complete this by today

**Comment by Jashpatel1** [comment]
> Could i work on this issue if it is still open

Sorry to say, the issue is already assigned to someone else. I will tag you on some other open issue soon. Thanks for your interest in contributing to layer5.

**Comment by Jashpatel1** [comment]
> Yes, @Jashpatel1, I have migrated one blog, [My Journey from a contributor to maintainer](https://layer5.io/blog/community/my-journey-from-a-contributor-to-a-maintainer); this is remaining today. I will complete this by today

@manishdangi98 Can we expect a PR for this issue by tonight? Feel free to share if you are stuck somewhere.

**Comment by manishdangi98** [comment]
@Jashpatel1 at some places .mdx file treating markdown as the simple text I am not able to figure it out

**Comment by Jashpatel1** [comment]
> @Jashpatel1 at some places .mdx file treating markdown as the simple text I am not able to figure it out

Can you open a PR, and then we can discuss after looking at the code. 
Another option is you can ping me on slack.
