### ISSUE TITLE
[NG] Add Layer5 and HashiCorp Launch Service Mesh Partnership news article

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#830]
**Desired Behavior**
Add `Layer5 and HashiCorp Launch Service Mesh Partnership` news article present on the [current site](https://layer5.io/company/news/layer5-hashicorp-launch-service-mesh-partnership) to layer5ng. Check[ #815](https://github.com/layer5io/layer5/issues/815) for more more details. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by iambami** [comment]
hi would love to take on this

**Comment by iambami** [comment]
can hactoberfest lebel be on this?

**Comment by Tanuj22** [comment]
@iambami please go ahead. Applying the hactoberfest label :)

**Comment by iambami** [comment]
Alright

**Comment by Jashpatel1** [comment]
@iambami Are you working on this issue? Please feel free to ask if you get stuck somewhere.

**Comment by iambami** [comment]
Yes I am.

**Comment by Tanuj22** [comment]
@iambami any updates?

**Comment by Tanuj22** [comment]
We need to move ahead @iambami. I am unassigning you so that other contributors can take a crack at it.

**Comment by Tanuj22** [comment]
FIxed in #968
