### ISSUE TITLE
[NG] Add What the Numbers Say about How Service Meshes Are Used Today news article  

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#831]
**Desired Behavior**
Add `What the Numbers Say about How Service Meshes Are Used Today` news article present on the [current site](https://layer5.io/https:/thenewstack.io/what-the-numbers-say-about-how-service-meshes-are-used-today/) to layer5ng. Check[ #815](https://github.com/layer5io/layer5/issues/815) for more more details. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by mehanix** [comment]
Hello, I could do this if that's okay! Could I be assigned, please?

Thank you!

**Comment by Tanuj22** [comment]
@mehanix Please go ahead.

**Comment by mehanix** [comment]
Thank you for the learning opportunity! I'll get it done in time for Hacktober.

**Comment by Tanuj22** [comment]
> Thank you for the learning opportunity! I'll get it done in time for Hacktober.

Awesome. Do jump into Layer5 community  http://slack.layer5.io. It's a welcoming place. :)

**Comment by Jashpatel1** [comment]
@mehanix Are you working on this issue? Please feel free to ask if you get stuck somewhere.

**Comment by mehanix** [comment]
Hello,

University just started in my country, therefore a lot of things have piled up in my log. I'll try to complete this by the end of the week, if that's okay? If not, tell me and I'll move higher up in my priority queue.

Thank you!

**Comment by Jashpatel1** [comment]
> Hello,
> 
> University just started in my country, therefore a lot of things have piled up in my log. I'll try to complete this by the end of the week, if that's okay? If not, tell me and I'll move it higher up in my priority queue.
> 
> Thank you!

No worries, you can do it by this week.
