### ISSUE TITLE
[NG] Add Vendors make a splash in 2019 service mesh implementation rush news article

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#833]
**Desired Behavior**
Add `Vendors make a splash in 2019 service mesh implementation rush` news article present on the [current site](https://layer5.io/news/vendors-make-a-splash-in-2019-service-mesh-implementation-rush) to layer5ng. Check[ #815](https://github.com/layer5io/layer5/issues/815) for more more details. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
> Done waiting for it to be approved

Good deal. @jomefavourite, be sure to reference the issue number that your PR fixes in the PR description (e.g. "fixes #833).

**Comment by jomefavourite** [comment]
@leecalcote 
> Good deal. @jomefavourite, be sure to reference the issue number that your PR fixes in the PR description (e.g. "fixes #833).

Yh I will, turns out the push wasn't done properly, I'll get back to it.

**Comment by jomefavourite** [comment]
I just made another PR again, hope I got it right now
