### ISSUE TITLE
[NG] Add The New Stack: Meshery in top 3 service mesh developments in 2020 news article

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#834]
**Desired Behavior**
Add `The New Stack: Meshery in top 3 service mesh developments in 2020` news article present on the [current site](https://layer5.io/news/meshery-in-top3-service-mesh-developments-in-2020) to layer5ng. Check[ #815](https://github.com/layer5io/layer5/issues/815) for more more details. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@lolyparty Can you take this?

**Comment by lolyparty** [comment]
> @lolyparty Can you take this?

Yes

**Comment by lolyparty** [comment]
the thumbnail is a png file and not svg should I use it like that?

**Comment by Tanuj22** [comment]
> the thumbnail is a png file and not svg should I use it like that?

Yeah

**Comment by lolyparty** [comment]
hey @Tanuj22 please can you help me? I keep getting this error while trying to view the news 
![Annotation 2020-09-27 044748](https://user-images.githubusercontent.com/49575651/94355540-cc644480-007c-11eb-83d8-30162018cb96.png)

**Comment by Tanuj22** [comment]
@lolyparty Two things to try out -
- Stop the development server. Then delete the `.cache` and `public` folder and restart the server.
- If still you get the same error. Check the build logs. There must be some error message present there.

**Comment by lolyparty** [comment]
> @lolyparty Two things to try out -
> 
> * Stop the development server. Then delete the `.cache` and `public` folder and restart the server.
> * If still you get the same error. Check the build logs. There must be some error message present there.

ok, I'll try that. Another question though, the link containing texts are not really differentiated from other text how do I differentiate them should I use <i></i> tag like this?
![Annotation 2020-09-27 053956](https://user-images.githubusercontent.com/49575651/94356237-efdebd80-0083-11eb-8ec7-c7b02074a209.png)

**Comment by Tanuj22** [comment]
> > @lolyparty Two things to try out -
> > 
> > * Stop the development server. Then delete the `.cache` and `public` folder and restart the server.
> > * If still you get the same error. Check the build logs. There must be some error message present there.
> 
> ok, I'll try that. Another question though, the texts containing links are not really differentiated from other text how do I differentiate them should I use tag like this?
> ![Annotation 2020-09-27 053956](https://user-images.githubusercontent.com/49575651/94356237-efdebd80-0083-11eb-8ec7-c7b02074a209.png)

This must have changed due to a recent PR about Color changes. You can ignore this for now. It is controlled centrally so we can change it later.

**Comment by lolyparty** [comment]
> > > @lolyparty Two things to try out -
> > > 
> > > * Stop the development server. Then delete the `.cache` and `public` folder and restart the server.
> > > * If still you get the same error. Check the build logs. There must be some error message present there.
> > 
> > 
> > ok, I'll try that. Another question though, the texts containing links are not really differentiated from other text how do I differentiate them should I use tag like this?
> > ![Annotation 2020-09-27 053956](https://user-images.githubusercontent.com/49575651/94356237-efdebd80-0083-11eb-8ec7-c7b02074a209.png)
> 
> This must have changed due to a recent PR about Color changes. You can ignore this for now. It is controlled centrally so we can change it later.

ok
