### ISSUE TITLE
[NG] Add KubeCon NA: CNCF SIG Network Set Intro and Deep-Dive news article 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#836]
**Desired Behavior**
Add `KubeCon NA: CNCF SIG Network Set Intro and Deep-Dive` news article present on the [current site](https://layer5.io/company/news/cncf-sig-network-intro-and-deep-dive) to layer5ng. Check[ #815](https://github.com/layer5io/layer5/issues/815) for more more details. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by anshdhinhgra47** [comment]
I'd like to give this a shot

**Comment by Tanuj22** [comment]
@anshdhinhgra47 Please go ahead

**Comment by anshdhinhgra47** [comment]
Thanks for assigning the issue!
Also, would it be okay if I create a PR on or after October 1st?

**Comment by Tanuj22** [comment]
> Thanks for assigning the issue!
> Also, would it be okay if I create a PR on or after October 1st?

Yeah Sure

**Comment by anshdhinhgra47** [comment]
Thank you :)
