### ISSUE TITLE
[NG] Add Forrester: Layer5 and Meshery Help Developers Focus On The Business news article 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#838]
**Desired Behavior**
Add `Forrester: Layer5 and Meshery Help Developers Focus On The Business` news article present on the [current site](https://layer5.io/news/layer5-meshery-forrester) to layer5ng. Check[ #815](https://github.com/layer5io/layer5/issues/815) for more more details. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
I'd like to work on this

**Comment by Tanuj22** [comment]
> I'd like to work on this

Go ahead

**Comment by lolyparty** [comment]
On it

**Comment by Jashpatel1** [comment]
Closed with #867
