### ISSUE TITLE
[NG] Migrate Code of conduct page to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#848]
**Current Behavior**
The current website has code of conduct over [here.](https://layer5.io/terms/code-of-conduct) This is to be migrated to layer5-ng. 

**Desired Situation**
Create a page for code of conduct in the pages folder.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by JubayerJoy** [comment]
If strictly not for first-timers, I want to give it a shot. @Jashpatel1

**Comment by leecalcote** [comment]
@JubayerJoy, nope, it's not. Please take it away. 👍

**Comment by Jashpatel1** [comment]
Are you working on this @JubayerJoy . Please feel free to ping me on slack if you get stuck.

**Comment by JubayerJoy** [comment]
Hi @Jashpatel1,
I am still in the learning phase of gastby, it will take me some time.

Feel free to assign this to someone with more experience.

**Comment by Tanuj22** [comment]
@JubayerJoy thanks for the heads up.

**Comment by Tanuj22** [comment]
@ashutosh1401 would you like to work on this?

**Comment by ashutosh1401** [comment]
If this issue could be solved using react then i would be able to do it but if graphql is required then it would be some difficulty

**Comment by Jashpatel1** [comment]
> If this issue could be solved using react then i would be able to do it but if graphql is required then it would be some difficulty

It wont require graphql.

**Comment by ashutosh1401** [comment]
Then assign this one to me

**Comment by ashutosh1401** [comment]
Where the code of conduct route would be kept so that it could run and their is need to create a separate code of conduct component in sections folder or not or we have to completely write whole component in pages section

**Comment by Tanuj22** [comment]
> Where the code of conduct route would be kept so that it could run and their is need to create a separate code of conduct component in sections folder or not or we have to completely write whole component in pages section

Create a folder called `terms` in the pages folder. Add a file called `code-of-conduct.js` in it. This will automatically create a route. Then make a section and import it in this file and use it (take reference of other files in the pages folder)
