### ISSUE TITLE
Delete duplicate Service Mesh Interface Page

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#849]
**Description**
Just a small update in the issue, as we already have a same project page so I am redefining the issue as deleting the service mesh page. Hope its okay with the change @bartkalanski . You will have to just delete the [smi page](https://github.com/layer5io/layer5/blob/master/collections/_pages/service-mesh-interface.html) from the [pages folder](https://github.com/layer5io/layer5/blob/master/collections/_pages).

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by bartkalanski** [comment]
Do you mind if I do this for hacktober fest

**Comment by Jashpatel1** [comment]
> Do you mind if I do this for hacktober fest ?

Cool, go ahead. I am assigning this to you.

**Comment by bartkalanski** [comment]
I appreciate it, thank you :)

**Comment by ampsteric** [comment]
I would like to work on this issue as well. please assign in case the issue is not resolved.

**Comment by Jashpatel1** [comment]
> I would like to work on this issue as well. please assign in case the issue is not resolved.

Sorry to say, Bart has already shown interest in working on this issue. Please look forward for other issues you can look to tackle. Thanks for your interest.

**Comment by bartkalanski** [comment]
> **Description**
> Just a small update in the issue, as we already have a same project page so I am redefining the issue as deleting the service mesh page. Hope its okay with the change @bartkalanski . You will have to just delete the [smi page](https://github.com/layer5io/layer5/blob/master/collections/_pages/service-mesh-interface.html) from the [pages folder](https://github.com/layer5io/layer5/blob/master/collections/_pages).

I'm happy with the change, so to confirm, rather than fix the overview typo I'll have to delete the smi page and then submit a PR ?

**Comment by Jashpatel1** [comment]
Closing with #870
