### ISSUE TITLE
[NG] Migrate the Meshmates page to Layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#850]
**Current Behavior**
The current website has [Meshmates](https://layer5.io/community/meshmates) page under the community section.

**Desired Situation**
Migrate the Meshmates page under the [community folder](https://github.com/layer5io/layer5/tree/layer5-ng/src/pages/community) in pages section.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by geraldmaboshe** [comment]
Hey @Jashpatel1  I would like to take up this

**Comment by Jashpatel1** [comment]
> Hey @Jashpatel1  I would like to take up this

Yaa sure, please go ahead. Thanks
