### ISSUE TITLE
[NG] Migrate the About page to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#851]
**Current Behavior**
The current website has an About Us page. The page can be seen [here](https://layer5.io/about).

**Desired Situation**
Migrate the About Us page to layer5-ng.

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Harshita-Kanal** [comment]
Can I take this up ?

**Comment by Jashpatel1** [comment]
Yaa sure, go ahead.
