### ISSUE TITLE
[NG] Migrate Events Page to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#855]
**Current Behavior**
The current website has events page over [here](https://layer5.io/events).

**Desired Situation**
Create an events page under the pages section. 
Tip: There is a[ card component](https://github.com/layer5io/layer5/tree/layer5-ng/src/components/Card) already made, which can be used as required.

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by naman360** [comment]
Can I work on this issue?

**Comment by Jashpatel1** [comment]
> Can I work on this issue?
> 

Yaa sure, please go ahead. Thank you.

**Comment by Nikhil-Ladha** [comment]
@naman360 if you are stuck anywhere...feel free to ping me or @Jashpatel1 in slack :slightly_smiling_face:

**Comment by naman360** [comment]
yes sure.

**Comment by Jashpatel1** [comment]
> yes sure. where is the slack link?

Here it is [http://slack.layer5.io/](http://slack.layer5.io/) . We look forward to welcome you in being a part of the community.

**Comment by Tanuj22** [comment]
@naman360 are you working on this?

**Comment by naman360** [comment]
Yes I am

**Comment by vinayaksh42** [comment]
@naman360 are you working on this issue? if not I would like to take this issue?

**Comment by vinayaksh42** [comment]
@Tanuj22 @Nikhil-Ladha can i work on this issue?

**Comment by Nikhil-Ladha** [comment]
@naman360 , since this issue had been assigned to you for around 20 days and we haven't got any updates from your end. Would like to say anything for that, otherwise we will be assigning this issue to @vinayaksh42 to get things moving forward, rather than having a backlog.

**Comment by Tanuj22** [comment]
I got no response from @naman360 on slack also, so @vinayaksh42 go ahead.

**Comment by Jashpatel1** [comment]
Closing with #989
