### ISSUE TITLE
remove scroll-bars 

### ISSUE THREAD

**Issue by Pratyush-Saxena** [layer5io/layer5#862]
**Current Behavior**
remove these unwanted scroll bars in [workshop page](https://layer5.io/workshops)

![sc](https://user-images.githubusercontent.com/52444607/94712536-3de71000-0367-11eb-80dc-b7adc8893c28.png)
![sc2](https://user-images.githubusercontent.com/52444607/94712579-4f301c80-0367-11eb-928a-b68c8896bc0b.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by knowyours** [comment]
Hello, can I take this issue up?

**Comment by Pratyush-Saxena** [comment]
yes, go ahead

**Comment by knowyours** [comment]
@Pratyush-Saxena Thanks for the confirmation. Can I be assigned to this issue please?

**Comment by knowyours** [comment]
I was able to fix the unwanted scrollbars problem but there seems to be a blank space appearing in the preview build. Can you please review this? @Pratyush-Saxena

![image](https://user-images.githubusercontent.com/66682806/94771388-b2a46380-03d4-11eb-9470-73d3beeb8392.png)
