### ISSUE TITLE
[NG] Migrate the UI Engineer page to layer5-ng

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#863]
**Current Behavior**
The current `layer5-ng` site contains a single post on the [careers page ](https://layer5ng.netlify.app/careers)

**Desired Behavior**
Add the [UI Engineer page ](https://layer5.io/careers/ui-engineer) from the [current site](https://layer5.io/careers) into layer5-ng. 

The data for the various job post are found inside [this folder](https://github.com/layer5io/layer5/tree/master/collections/_careers). Reference on how to a post of in the careers section in layer5-ng can be taken from an already added post of Digital Marketing Internship in [this folder](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/careers). (Change `type: internship` to `type: job`) 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
> Please i'll love to understand this

Hey @Josephchinedu, what would you like to understand?

**Comment by geraldmaboshe** [comment]
Hey @Tanuj22 I would like to take up this
