### ISSUE TITLE
[NG] Remove the extra padding from Single News template

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#868]
**Description**
The single news page has a lot of padding at the bottom. It sums up for mobile view even.

**Expected Behavior**
Remove the extra padding present from the single news template.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/43696490/94762920-98fc1f80-03c6-11eb-9604-07c9beaa5d9a.JPG)
![Capture](https://user-images.githubusercontent.com/43696490/94762964-b3ce9400-03c6-11eb-9339-073b5a660d57.JPG)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by stevenbudinata** [comment]
Hi, can you assign me to this. Thank you

**Comment by nimendrak** [comment]
I would like to contribute in this.

**Comment by Jashpatel1** [comment]
> Hi, can you assign me to this. Thank you

Sure, please go ahead. The issue relates to layer5-ng website. Please look into the contributor resources to know about it.

**Comment by Jashpatel1** [comment]
> I would like to contribute in this.

Sorry to say but a person has already shown his interest in contributing to this issue. Please look into other issues present on layer5. You will find many good first issues in the near future as well. Thanks for your interest.

**Comment by leecalcote** [comment]
@nimendrak fear not! We have you covered. 😄 Have a look-see - https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+

**Comment by Jashpatel1** [comment]
Closing with #869
