### ISSUE TITLE
Update AVI Networks entry

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#87]
Hi @paib, @sudswasavi, @rangar, @oletizi, will you consider adding a listing for [AVI's service mesh](https://github.com/avinetworks/servicemesh) to the [service mesh landscape](https://layer5.io/landscape)? We'd love to have an accurate listing of the tool described here.

**Comment by chugtum** [comment]
Hi @leecalcote 

Thanks for reaching out. We would love to be there on the list of Service Mesh Landscape. Here are the details. Do let me know, if you need any other information.

We currently have two projects w.r.t Service Mesh. Our existing proprietary Avi Container Services (Host Based Proxy Model) and the recently launched Istio Integrated Universal Service Mesh.

1. 
**Name:** [Istio Integrated Universal Service Mesh Dec, 2018 ](https://avinetworks.com/universal-service-mesh/)
**Category:** Service Mesh 
**Open Source:** Partially [Link to Repo: https://github.com/avinetworks/servicemesh)]
**Governance:**  Avi Networks
**Primary Language:** Go, C++ 
**Project Announce:** Dec, 2018 
**GA / 1.0:** Q2, 2019 
**Commercial Offerings:** [Istio Integrated Universal Service Mesh](https://avinetworks.com/universal-service-mesh/) 

2.
**Name:** [Avi Container Services (Host Based Proxy Model)](https://avinetworks.com/service-mesh-for-openshift-kubernetes/)
**Category:** Service Mesh 
**Open Source:** No 
**Governance:**  Avi Networks
**Primary Language:** C, C++, Python  
**Project Announce:** Feb, 2016 
**GA / 1.0:** 2016 
**Commercial Offerings:** [Avi Container Service Mesh (Host Based Proxy)](https://avinetworks.com/service-mesh-for-openshift-kubernetes/)

**Comment by leecalcote** [comment]
@chugtum thanks! @sakomws will you take this one? Or @chugtum you're most encouraged (it's nice when project/product representatives "own" their listing) to PR directly as well - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md.

**Comment by sakomws** [comment]
@leecalcote I will take over it.

**Comment by leecalcote** [comment]
Thank you, @sakomws.

**Comment by leecalcote** [comment]
@chugtum took care of us here. Closing out issue.

**Comment by leecalcote** [comment]
Oops. I spoke too soon. Reopening issue.
