### ISSUE TITLE
[Programs] Schedule another Hacktoberfest meetup

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#881]
**Current Behavior**
Each Thursday this month, the Layer5 community will host a Hacktoberfest meetup at the Newcomers call.

**Desired Situation**
A new Hacktoberfest meetup (akin to this one - https://organize.mlh.io/participants/events/4796) should be scheduled for each Thursday.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by tripathyprateek** [comment]
I will update the link to the Meetup once it gets approved by today.
