### ISSUE TITLE
[Books] Add second edition of The Enterprise Path to Service Mesh Architectures

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#883]
**Current Behavior**
There is a new edition of this book coming out shortly - https://layer5.io/books/the-enterprise-path-to-service-mesh-architectures

**Desired Behavior**
1. The second edition should be added as a new entry. This description may be used:
```
Planning to build a microservice-driven cloud native application or looking to modernize existing application services? Consider using a service mesh. A service mesh approach can help you create robust and scalable applications, but it also introduces new challenges. This updated report answers common questions regarding service mesh architectures through the lens of a large enterprise. 

Author Lee Calcote, founder and CEO of Layer5, shows developers, operators, architects, and IT leaders how to evaluate your organization’s readiness for using a service mesh—and provides a clear path to help you adopt one. You’ll evaluate several factors when deciding which applications should be built from the ground up and which can be converted with a new service mesh architecture. 

This updated edition discusses several service meshes available and the tools you need to implement them. You’ll explore:

- Service mesh concepts, architecture, and components, such as control planes and data planes
- How a service mesh provides observability, resiliency, security, and traffic control of distributed application services
- Differences among service meshes and service mesh components from several vendors
- How service meshes compare to related technologies, including container orchestrators, API gateways, and client-side libraries
- Practical steps for service mesh adoption, deployment, customization, and integration
- The intelligence of the service mesh management plane and the power of the data plane

Author: Lee Calcote
Publisher: O’Reilly
Publish Date: October 2020
```
2. The first edition entry should remain as-is.

**Book Cover**
Use this image as the book cover for the second edition entry. Resize as needed.
![the-enterprise-path-to-service-mesh-architectures_2nd-edition](https://user-images.githubusercontent.com/7570704/94847905-d376b400-03e8-11eb-8985-3c4a1f0aeb21.png)

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by oyakhilomee** [comment]
@Lee I'll like to take this.

**Comment by akashgp09** [comment]
Hey @leecalcote can I take this issue.

**Comment by leecalcote** [comment]
Sounds good, @akashgp09.

@oyakhilomee i appreciate your help here and on other issues. This book will be published shortly and so let’s allow @akashgp09 to carry this issue forward, if that’s ok.

**Comment by oyakhilomee** [comment]
Sure, that's OK.
