### ISSUE TITLE
[Programs] Add Layer5 Community Hacktoberfest logo to program page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#884]
**Current Behavior**
The Layer5 community have a special Hacktoberfest graphic to share on this page - https://layer5.io/programs/hacktoberfest

**Desired Behavior**
Add the graphic below to the Hacktoberfest page. Replace the existing generic graphic with this one.
![Layer5-Hacktoberfest](https://user-images.githubusercontent.com/7570704/94851172-b1336500-03ed-11eb-917c-9bdb67ba8684.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by bartkalanski** [comment]
I’m away for a little birthday celebration but will try and get it done by Sunday if that’s okay ?

**Comment by leecalcote** [comment]
@bartkalanski thanks much. Yes, sounds real good. The next Layer5 Hacktoberfest meetup is on Thursday, October 8th.
