### ISSUE TITLE
[Programs] Add button for hacktoberfest to list of programs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#888]
**Current Behavior**
On the front page of https://layer5.io is listed four program that Layer5 participates in (see screenshot)

**Desired Behavior**
The https://layer5.io/programs/hacktoberfest should be represented by a button as well.

**Screenshot**
<img width="1220" alt="Screen Shot 2020-10-01 at 7 52 45 PM" src="https://user-images.githubusercontent.com/7570704/94877379-f1134000-041f-11eb-8763-ca2b2044e8c5.png">

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by EdgeKing810** [comment]
Hey, I want to work on this. Please assign me!

**Comment by knowyours** [comment]
@leecalcote @Nikhil-Ladha  Can I be assigned to work on this issue?

**Comment by Nikhil-Ladha** [comment]
@knowyours , this issue was already worked upon by @EdgeKing810 . So, you can close your PR, and look for other issues to work upon. I am preferring his PR as he asked earlier for it.😅

**Comment by knowyours** [comment]
@Nikhil-Ladha No problem :)
