### ISSUE TITLE
[NG] Migrate Meshery Page to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#893]
**Current Behavior**
The current meshery page is as shown [here](https://layer5.io/meshery).

**Desired Situation**
Migrate the meshery page and make use of sections that are provided in the template.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by spielers** [comment]
@Jashpatel1 I would love to work on this issue

**Comment by Jashpatel1** [comment]
> @Jashpatel1 I would love to work on this issue

Sorry to say, this issue is already assigned, please look out for other issues on layer5. Thanks for your interest in contributing to layer5.
