### ISSUE TITLE
Update MeshMate cards

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#894]
**Current Behavior**

The individual MeshMate cards currently don't reflect details about the MeshMate on this [page](https://layer5.io/community/meshmates).

**Desired Behavior**

Each MeshMate card should include the following details about the MeshMate, in the below-mentioned order. This should preferably be placed under their name and above their Social ID's:
- Domain(s)
- Timezone

The details for each MeshMate can found in this [document](https://docs.google.com/document/d/1omot8vRinfQlNKMt5KRBlGiHJRMC6xEdRd0o0jIifrM/edit?usp=sharing).

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by knowyours** [comment]
@chandrashritii Can I take this issue up? And can you please brief a bit more about what should be done?

**Comment by knowyours** [comment]
Should the changes mentioned be done in "https://layer5.io/community/meshmates" itself or in th card that appears on each page after clicking on each card from the above mentioned page?

**Comment by chandrashritii** [comment]
@knowyours The changes should be done in the page that appears when you click on the card. For example, For Kush Trivedi, the details should be added on https://layer5.io/community/members/kush-trivedi.

Any suggestions here? @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Yes correct @chandrashritii . This is what needed, also a backdrop of the MeshMate logo can be added here.

**Comment by geraldmaboshe** [comment]
Hey @chandrashritii  I would like to take up this

**Comment by chandrashritii** [comment]
Sure @geraldmaboshe Go ahead 👍

**Comment by leecalcote** [comment]
> @knowyours The changes should be done in the page that appears when you click on the card. For example, For Kush Trivedi, the details should be added on https://layer5.io/community/members/kush-trivedi.
> 
> Any suggestions here? @Nikhil-Ladha

Yes, that's right. The description in the issue calls for details to be placed on the cards on the /community/meshmates page, however. Hence, the confusion.

@geraldmaboshe's recent PR on this issue places the details on the page listing the collection of MeshMates (as characterized in the issue description), not on the individual MeshMate member pages. @chandrashritii will you work with @geraldmaboshe to correct?

**Comment by geraldmaboshe** [comment]
> > @knowyours The changes should be done in the page that appears when you click on the card. For example, For Kush Trivedi, the details should be added on https://layer5.io/community/members/kush-trivedi.
> > Any suggestions here? @Nikhil-Ladha
> 
> Yes, that's right. The description in the issue calls for details to be placed on the cards on the /community/meshmates page, however. Hence, the confusion.
> 
> @geraldmaboshe's recent PR on this issue places the details on the page listing the collection of MeshMates (as characterized in the issue description), not on the individual MeshMate member pages. @chandrashritii will you work with @geraldmaboshe to correct?

@chandrashritii
