### ISSUE TITLE
Regression Issue: Add SOFAMesh to service mesh list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#9]
Recent updates have undone #3. SOFAMosn is listed under proxies, but SOFAMesh has gone missing.

**Comment by rootsongjc** [comment]
[SOFAMesh](https://github.com/alipay/sofa-mesh) should be listed on Service Mesh category.

**Comment by leecalcote** [comment]
Addressed in #15. Thank you, @rootsongjc!
