### ISSUE TITLE
Add Yggdrasil to the landscape

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#90]
@DewaldV, @Joseph-Irving it'd be great to have Yggdrasil represented in the [landscape](https://layer5.io/landscape). The [contributing](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md) doc has instructions on how to update. Will you consider contributing a PR to ensure its accuracy?

**Comment by Joseph-Irving** [comment]
Hey, would be happy to, I'm not entirely sure where it fits in your categories, I think service proxy is probably the closest.

**Comment by leecalcote** [comment]
@Joseph-Irving excellent. To the extent that it's a control plane, it probably fits within the service mesh category.

**Comment by leecalcote** [comment]
@Joseph-Irving, but if you consider it a service proxy, let's start there instead. ;)

**Comment by Joseph-Irving** [comment]
@jijillery I've raised a PR https://github.com/layer5io/layer5/pull/142

**Comment by leecalcote** [comment]
Much appreciated, @Joseph-Irving. 👍
