### ISSUE TITLE
Content overlapping on the hacktoberfest program page

### ISSUE THREAD

**Issue by Nikhil-Ladha** [layer5io/layer5#907]
**Description**

In the mobile view, the google from iframe is overlapping on the content of the hacktober fest program on the page layer5.io/programs/hactoberfest
**Expected Behavior**

The iframe should be moved to the bottom of the content in the mobile view.
**Screenshots**

![Screenshot from 2020-10-03 23-56-32](https://user-images.githubusercontent.com/29438875/94999105-a71f8b00-05d4-11eb-9506-7f8bc63b7572.png)

Expected to be like:
![Screenshot from 2020-10-04 00-09-24](https://user-images.githubusercontent.com/29438875/94999295-0fbb3780-05d6-11eb-8189-4fdce1a5b545.png)
![Screenshot from 2020-10-04 00-09-30](https://user-images.githubusercontent.com/29438875/94999297-1184fb00-05d6-11eb-83c4-a17793f8368f.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ashutosh1401** [comment]
Could i work in this issue

**Comment by ritik307** [comment]
i would like to contribute to this issue

**Comment by Nikhil-Ladha** [comment]
Sure @ritik307 go ahead!

**Comment by ashutosh1401** [comment]
Could i also work on this issue

**Comment by Nikhil-Ladha** [comment]
> Could i also work on this issue

Sorry, @ashutosh1401 . You can take up some other open issue🙂

**Comment by Nikhil-Ladha** [comment]
@ritik307 any progress here?
If stuck feel free to ping me in slack :slightly_smiling_face:

**Comment by chandrashritii** [comment]
Hey @ritik307 Considering that hacktoberfest is going on and that this is a pretty major UI issue, it needs to be fixed as soon as possible. Please do signal if you're working on this by today otherwise I'll take it up.

**Comment by leecalcote** [comment]
Hi All, my apologies... we're getting much traffic on this page and so need to urgently press forth on a fix.

@ritik307 it's fantastic that you jumped in here. It turns out that this is a hot potato. There are many more issues where this came from: [help-wanted](https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+). Please take your pick. If you can't find one, jump into the Layer5 Community (http://slack.layer5.io) and we'll get you going.
