### ISSUE TITLE
[NG] Migrate GSoC19 page to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#908]
**Current Behavior**
The current website has GSoC19 page over [here](https://layer5.io/programs/gsoc/2019).

**Desired Situation**
Migrate the GSoC19 page to layer5-ng. See the migration of [GSoC20 page](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/programs/gsoc-2020) for reference.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ashutosh1401** [comment]
I couldn't understand issue well could you explain it in more simpler way

**Comment by Jashpatel1** [comment]
There is a current Jekyll-based website deployed at [https://layer5.io/](https://layer5.io/). We are migrating to Gatsby(a React framework) based website which is currently stored in the same repo under[ layer5-ng branch.](https://github.com/layer5io/layer5/tree/layer5-ng) The issue is to migrate two blogs from the current website(i.e. master branch) to layer5-ng website(i.e. layer5-ng branch). There are already a lot of blogs present in layer5-ng which you can see for a reference.

**Comment by ashutosh1401** [comment]
So i have to write .mdx file for GSOC19 page as mentioned in the reference GSOC20 page or a react page if i work on this issue

**Comment by Jashpatel1** [comment]
> So i have to write .mdx file for GSOC19 page as mentioned in the reference GSOC20 page or a react page if i work on this issue

A .mdx file

**Comment by ashutosh1401** [comment]
Could i work on this issue

**Comment by Jashpatel1** [comment]
> Could i work on this issue

Yaa sure, please go ahead.

**Comment by ashutosh1401** [comment]
I am facing this error while setting it up locally when i type `make setup-libs`  i got : `bash: make: command not found`

**Comment by Jashpatel1** [comment]
> I am facing this error while setting it up locally when i type `make setup-libs`  i got : `bash: make: command not found`

Please refer to the contributing guidelines for layer5-ng present under the issue.

**Comment by ashutosh1401** [comment]
yes

> 
> 
> > I am facing this error while setting it up locally when i type `make setup-libs`  i got : `bash: make: command not found`
> 
> Please refer to the contributing guidelines for layer5-ng present under the issue. Do you have npm, nodejs and gatsby-cli installed?

Yes i have installed npm, nodejs and gatsby-cli, i am working in windows 10 OS.

**Comment by Tanuj22** [comment]
@ashutosh1401 that's an issue with windows to run `make` commands. You can follow these commands - 

- `npm install` in place of `make setup-libs`
- `npm start` in place of `make site`

**Comment by ashutosh1401** [comment]
@Tanuj22 thanks

**Comment by Jashpatel1** [comment]
Closing with #917
