### ISSUE TITLE
[NG] Migrate MLH2020 page to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#909]
**Current Behavior**
The current website has MLH2020 page over [here.](https://layer5.io/programs/mlhfellowship/2020)

**Desired Situation**
Migrate the MLH2020 page to layer5-ng. Please look into how various [programs](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/programs) have been migrated for reference.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
I'd like to work on this.

**Comment by spielers** [comment]
Hey, @Jashpatel1 I would like to migrate this.

**Comment by lolyparty** [comment]
> Hey, @Jashpatel1 I would like to migrate this.

Hey, @spielers, I'm already on this.  I'll make sure to tag you when I find a new issue for you.

**Comment by lolyparty** [comment]
@Jashpatel1 there's no picture for mlh logo [here](https://layer5.io/programs/mlhfellowship/2020)

**Comment by Jashpatel1** [comment]
> @Jashpatel1 there's no picture for mlh logo [here](https://layer5.io/programs/mlhfellowship/2020)

You can download from here https://github.com/MLH/mlh-localhost-github/blob/master/static/logo.svg

**Comment by lolyparty** [comment]
> > @Jashpatel1 there's no picture for mlh logo [here](https://layer5.io/programs/mlhfellowship/2020)
> 
> You can download from here https://github.com/MLH/mlh-localhost-github/blob/master/static/logo.svg

Thank you

**Comment by Jashpatel1** [comment]
Closing with #923
