### ISSUE TITLE
[NG] Migrate two blogs to layer5-ng

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#911]
**Current Behavior**
Recently, two blogs have been added to layer5.

**Desired Situation**
Migrate those two blogs to layer5-ng. Please look into other[ migrated blogs](https://github.com/layer5io/layer5/tree/layer5-ng/src/collections/blog) for reference.

- [ ] [Learn to write and deploy WASM filters](https://layer5.io/blog/webassembly/learn-how-to-write-wasm-filters-for-envoy-in-rust-and-deploy-with-consull) 
- [ ] [Announcing Meshmates](https://layer5.io/blog/community/announcing-meshmatesl) 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
I would like to work on this issue

**Comment by Jashpatel1** [comment]
Thanks, Please go ahead.
