### ISSUE TITLE
Grey Matter Update

### ISSUE THREAD

**Issue by brianlitalien** [layer5io/layer5#92]
We need to update the language on the Grey Matter hover over to the following "Grey Matter is an Istio-compliant, Envoy proxy based hybrid cloud service mesh platform for business insight and secure data control with your Microservices."

Also, Grey Matter should be marked YES for the following Functional table sections:  Multi-cluster, Multi-tenant, Auto Proxy Injection, and Encryption.

For the Non-Functional Section:

Grey Matter | Service Mesh | No | Decipher Technology Studios | Go | Nov 2017 | Feb 2019 | Grey Matter

**Comment by joshua-rutherford** [comment]
@hiromis, can you take an action to open a pull request against this repository to fix the issues above?
