### ISSUE TITLE
Incorrect Placement of icons in https://layer5ng.netlify.app/classic in Integration section

### ISSUE THREAD

**Issue by ashutosh1401** [layer5io/layer5#922]
**Description**

Their is mention of Slack in integration section but the image icon is attached is of instagram and similiar problem exists with instagram as it has slack icon. This issue is present in layer5-ng website [Layer5-ng](https://layer5ng.netlify.app/classic).

**Expected Behavior**

Icons of respective links must be at their positions.

**Screenshots**

![Screenshot (182)](https://user-images.githubusercontent.com/56783815/95092560-68f5a900-0745-11eb-95d8-344eb710e6a8.png)

**Enviroment:**
 - OS: [Windows]
 - Browser: [firefox]
 - Version: [81.0.1 ]
 - Device: [laptop]

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by bartkalanski** [comment]
Do you mind if I have a go at this ?

**Comment by ashutosh1401** [comment]
I am not the maintainer but i just discovered this issue and i would like to solve this one with confirmation with one of the maintainer so that they could add more appropriate labels or approve this issue

**Comment by leecalcote** [comment]
Thanks for raising this up, @ashutosh1401, and for raising your hand, @bartkalanski. 

We'll want to step back a little here before executing on changes to this page. This page is a template that we've yet to give holistic consideration as to what to do with it. 

Here is a spreadsheet that tracks outstanding items for the creation of the new layer5.io site (rebasing from Jekyll to Gatsby) - https://docs.google.com/spreadsheets/d/1INpwC-5ithNR0rJ8EWWTyAIaPm8vl-gnQJ2jL57Fdb0/edit. This spreadsheet and other assets can be found in the Layer5 Community drive.

It'd be good to check in the #websites channel in the Layer5 Slack to coordinate on areas of need (there are many). Do either of the two of you have proficiency in Adobe After Effects, by chance?

**Comment by leecalcote** [comment]
Gents, in a similar vein, an issue can be opened to fix the overlap of text and arrows seen here:

<img width="1332" alt="Screen Shot 2020-10-05 at 6 47 14 AM" src="https://user-images.githubusercontent.com/7570704/95101923-599c3e80-06f8-11eb-8343-cb8b47b759f9.png">

**Comment by bartkalanski** [comment]
> Thanks for raising this up, @ashutosh1401, and for raising your hand, @bartkalanski.
> 
> We'll want to step back a little here before executing on changes to this page. This page is a template that we've yet to give holistic consideration as to what to do with it.
> 
> Here is a spreadsheet that tracks outstanding items for the creation of the new layer5.io site (rebasing from Jekyll to Gatsby) - https://docs.google.com/spreadsheets/d/1INpwC-5ithNR0rJ8EWWTyAIaPm8vl-gnQJ2jL57Fdb0/edit. This spreadsheet and other assets can be found in the Layer5 Community drive.
> 
> It'd be good to check in the #websites channel in the Layer5 Slack to coordinate on areas of need (there are many). @Jashpatel1, @Tanuj22, and @Nikhil-Ladha just gave a break down of this effort on the weekly Layer5 Websites Meeting (layer5.io/community) an hour or so ago. The meeting recording will be up in an hour (https://www.youtube.com/channel/UCFL1af7_wdnhHXL1InzaMvA?sub_confirmation=1).
> 
> Do either of the two of you have proficiency in Adobe After Effects, by chance?

Thanks for the info Lee, sadly I'm not familiar with Adobe after Effects
