### ISSUE TITLE
The GSoC, GSoD, Community Bridge link on the Home Page and footer return 404 Not Found

### ISSUE THREAD

**Issue by daksh-sagar** [layer5io/layer5#924]
This is the link - https://layer5.io/programs/communitybridge/2020
Upon visiting the link the page said to file an issue so I did 😁

**Comment by leecalcote** [comment]
Haha! Thank you, @daksh-sagar. 👍

**Comment by daksh-sagar** [comment]
@leecalcote I would like to work on this please 🙂
