### ISSUE TITLE
[NG] Overlapping of text and arrows Layer5ng

### ISSUE THREAD

**Issue by bartkalanski** [layer5io/layer5#925]
**Description**
Overlapping of text and arrows on ```Layer5ng``` landing page.

**Screenshot**
![layer5-wrong](https://user-images.githubusercontent.com/61667381/95240596-8dfd2100-0804-11eb-802f-a561f63a283f.png)

**Expected Behaviour**
The text and arrows should be separated, as seen below.

**Screenshot**
![layer5-desired](https://user-images.githubusercontent.com/61667381/95240466-5bebbf00-0804-11eb-9d45-f2d10edfaaa1.png)
 

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---

**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
Hey, @spielers signify if you'd like to work on this

**Comment by spielers** [comment]
Definitely I'll work on it assign me !

**Comment by Jashpatel1** [comment]
Closing with #1018
