### ISSUE TITLE
[NG] Add "Proudly Maintainers of" section to home page

### ISSUE THREAD

**Issue by jijillery** [layer5io/layer5#928]
**Current Behavior**
Layer5 is a maintainer of the following projects and organizations:

Meshery, Service Mesh Interface, Service Mesh Performance, CNCF, Envoy, Istio

**Desired Behavior**
Create a new section that has the logos of each of these projects / organizations. Logos can be found in the Layer5 Community drive and/or on github.com/cncf/artwork and layer5.io/brand

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by k-guy-dev** [comment]
hey! @jijillery @leecalcote I would really love to take this issue.

**Comment by leecalcote** [comment]
Sounds great, @k-guy-dev

**Comment by leecalcote** [comment]
Thanks for jumping in. 👍

**Comment by PluckyPrecious** [comment]
Hey @k-guy-dev how is this coming up?

**Comment by Jashpatel1** [comment]
Any progress here guys? @k-guy-dev

**Comment by k-guy-dev** [comment]
> Any progress here guys? @k-guy-dev

@Jashpatel1 sorry for the inactivity. You can take over this issue.

**Comment by leecalcote** [comment]
@k-guy-dev, no sweat. Plenty of other issues where this comes from. Thank you for signaling on this one.

**Comment by Grumpyyash** [comment]
@Jashpatel1, Can I take this issue up?

**Comment by leecalcote** [comment]
@austinogiza, do we have a design on this?

**Comment by Jashpatel1** [comment]
Will be tracked in #1421
