### ISSUE TITLE
[Event] Add CNCF Virtual Ambassador Day to the layer5.io/events page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#942]
**Current Behavior**
Meshery will be on display at the CNCF [Virtual Cloud Native Ambassador Day](https://community.cncf.io/events/details/cncf-cncf-ambassadors-presents-virtual-cloud-native-ambassador-day/#/).

**Desired Behavior**
- The `events` collection should have an entry for this event.
- The https://layer5.io/events page should list this event.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by ealvarez968** [comment]
Hi, 

I would like to contribute to this project, can you assign me this issue ?

**Comment by leecalcote** [comment]
Hi @ealvarez968, that would be fantastic. Thank you.

**Comment by ealvarez968** [comment]
Hello, 

I got the project up an running on my machine but I have some questions.

1. I have to add the  CNCF Virtual Cloud Native Ambassador Day to the upcomming industry events at [events]( https://layer5.io/events), right?
1. Where can I found the assets to add this event and the text?
1. The file that I should modify is _data/events.yml right ?

Regards

**Comment by leecalcote** [comment]
Hi @ealvarez968, good questions:

1. Yes
2. The Ambassador logo will do the trick - https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-ambassador-logos
3. Yes

**Comment by ealvarez968** [comment]
Hello,

I have a question, should I update layer5-ng  branch or just master ?

**Comment by Nikhil-Ladha** [comment]
No, that's a seperate site.
