### ISSUE TITLE
[Event] Add ServiceMeshCon 2020 to the /events page

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#943]
**Upcoming Event**
Meshery and SMP will be on display at ServiceMeshCon 2020 - https://events.linuxfoundation.org/servicemeshcon-north-america/

**Desired Behavior**
- The `events` collection should have an entry for this event.
- The https://layer5.io/events page should list this event.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by lolyparty** [comment]
Would like to work on this

**Comment by codetheorem** [comment]
Assign this to me.

**Comment by lolyparty** [comment]
> Assign this to me.

Hello, @codetheorem I'm on this. I would look at for other issues you can work on for you.

**Comment by codetheorem** [comment]
I have added servicemeshcon in layer5-ng only.

**Comment by lolyparty** [comment]
> I have added servicemeshcon in layer5-ng only.

Ok then, you can work on this. I'll assign it to you now. why did you link this issue to your PR? This issue is related to the old layer5 site note layer5-ng

**Comment by leecalcote** [comment]
@lolyparty Good highlight on the need for this event to be captured on both the current and new website. Will you carry forward the other half of this issue on the layer5.io (current site)? If you're able to do it before Friday - excellent. If not, let's ask another contributor (time is off the essence as we'll be talking about our participation in the conference).

@codetheorem thank you for knocking this out on the layer5-ng site.

**Comment by lolyparty** [comment]
> @lolyparty Good highlight on the need for this event to be captured on both the current and new website. Will you carry forward the other half of this issue on the layer5.io (current site)? If you're able to do it before Friday - excellent. If not, let's ask another contributor (time is off the essence as we'll be talking about our participation in the conference).
> 
> @codetheorem thank you for knocking this out on the layer5-ng site.

Hey Lee! I won't be able to go on with the issue. I've assigned it to @codetheorem I'll send you a message on slack.

**Comment by leecalcote** [comment]
@lolyparty Ok, no sweat. Understood. Thanks for communicating this.

**Comment by leecalcote** [comment]
Oh.... @codetheorem, I see both PRs now. Excellent.
