### ISSUE TITLE
List new workshops on the Layer5 site

### ISSUE THREAD

**Issue by chandrashritii** [layer5io/layer5#945]
**Desired Situation**

The following new workshops have to be added to the [Layer5 workshops](https://layer5.io/workshops) page:

- [Linkerd Fundamentals](https://learning.oreilly.com/live-training/courses/service-mesh-fundamentals-with-linkerd/0636920418085/)
- [Advanced Istio](https://learning.oreilly.com/live-training/courses/advanced-istio/0636920418108)
- [Introduction to Istio](https://learning.oreilly.com/live-training/courses/introduction-to-istio/0636920422679)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by emmanuellar** [comment]
Hi, I'd love to take this up

**Comment by leecalcote** [comment]
Thank you, @emmanuellar. 👍

**Comment by emmanuellar** [comment]
Hi @leecalcote, please I need help  here.
The workshop.html page doesn't have the workshop listed. Seems the workshops are being called from somewhere (where I need to fix these new ones)
I'd love you to please point me to where I can look

**Comment by emmanuellar** [comment]
Hi @leecalcote I think I found it. Will send updates

**Comment by emmanuellar** [comment]
Hi @leecalcote, for the first workshop above, there are no images (flier of the workshop) which I can add to the page. What can I do about that?

**Comment by leecalcote** [comment]
@emmanuellar great question. Here you are:

- [workshops/service-mesh-fundamentals-with-linkerd.jpg](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/workshops/service-mesh-fundamentals-with-linkerd.jpg)
- [workshops/service-mesh-fundamentals-with-linkerd-small.jpg](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/workshops/service-mesh-fundamentals-with-linkerd-small.jpg)
- [workshops/introduction-to-istio.jpg](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/workshops/introduction-to-istio.jpg)
- [workshops/introduction-to-istio-small.jpg](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/workshops/introduction-to-istio-small.jpg)
- [workshops/advanced-istio.jpg](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/workshops/advanced-istio.jpg)
- [workshops/advanced-istio-small.jpg](https://raw.githubusercontent.com/layer5io/layer5/master/assets/images/workshops/advanced-istio-small.jpg)

**Comment by emmanuellar** [comment]
Thanks so much @leecalcote 
I've fixed the images. Is there a way I can preview the workshop.html page so I can see the changes I've made?
Or should I go ahead and send a PR?

**Comment by Nikhil-Ladha** [comment]
Yes, @emmanuellar . At first if you haven't, you need to setup your env by installing ruby using rvm (prefered). Then set the ruby version to the one used in the Gemfile. Then run the `bundle install` command. If this command gives sime error or warning like bundle not recognised or update bundler then you will need to run `gem install bundler-2.1.4` then again `bundle install` after rhis command is executed successfully. Run `make site` command to see the preview of the iste on `localhost:4000`.

If you face any issue feel free to ping me in slack.

**Comment by chandrashritii** [comment]
@emmanuellar Any updates here?

**Comment by emmanuellar** [comment]
Hi @chandrashritii @leecalcote not yet. Please I'd love to be unassigned from this task as I'm having a lot of issues running the program on my system to preview the pages. I'd love to keep contributing on other tasks that doesn't involve running the program on my system. Thanks

**Comment by leecalcote** [comment]
@emmanuellar no sweat. Completely understood. There are a number of other issues perhaps better aligned. 👍
