### ISSUE TITLE
[NG] Improvise the responsiveness of Brand page of layer5-ng

### ISSUE THREAD

**Issue by iamsurajdc** [layer5io/layer5#946]
**Current Behavior** : 

The current [Brand page](https://layer5ng.netlify.app/brand) on the [layer5-ng site](https://layer5ng.netlify.app/) is live, which comprises distinct layer5 brand div's.

**Desired Behavior** : 
-  Align the pallets (color-boxes) in meshery and SMP to center in mobile view.

 

![95051883-a0476400-070b-11eb-9791-60c66ec0db2a](https://user-images.githubusercontent.com/32074031/95621635-a9c82780-0a8f-11eb-9b05-929717c22669.png)

-   Keep the contact us part below the heading in the mobile view.
-  The section header should have a bigger font size and should be properly left-aligned similar to other sub-headings.

![95051913-ab01f900-070b-11eb-9245-567098926f35](https://user-images.githubusercontent.com/32074031/95621702-c3696f00-0a8f-11eb-979f-f381f5a8d385.png)

- The grayscale and the color, colors are getting mixed up as we make the view responsive and move to a mobile view or tablet view.

![image](https://user-images.githubusercontent.com/32074031/95622540-57880600-0a91-11eb-95a8-05077276b8d2.png)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Fahdmoh01** [comment]
Hello guys, new commer here. I would like to be assigned to this issue

**Comment by ashutosh1401** [comment]
I would also like to contribute on this issue

**Comment by Tanuj22** [comment]
> Hello guys, new commer here. I would like to be assigned to this issue

@Fahdmoh01 please go ahead.

**Comment by Tanuj22** [comment]
> I would also like to contribute on this issue

@ashutosh1401 sorry, you can check out some other issue

**Comment by Fahdmoh01** [comment]
Thanks will do my best👍🏿

**Comment by Nikhil-Ladha** [comment]
@ashutosh1401 if you want...this issue is open for grab.

**Comment by codetheorem** [comment]
Assign this to me

**Comment by Nikhil-Ladha** [comment]
Cool
