### ISSUE TITLE
[DOC]The Helm v2 scripts in a wrong way and need to be fix

### ISSUE THREAD

**Issue by Aisuko** [layer5io/layer5#965]
**Current State:**

Going to the https://layer5.io/meshery#getting-started and you can see that for kubernetes user the deployment way is deploy the `yaml`, but we need to add the other ways that we already have been haved 

**Desired State:**

Reference link:

https://meshery.layer5.io/docs/installation/platforms/kubernetes

**Comment by akashgp09** [comment]
@Aisuko can you provide some more info.

**Comment by Aisuko** [comment]
> @Aisuko can you provide some more info.

We should update the scripts for `Kubernetes user` which on the `layer5.io` document site. And we already have the scripts(https://meshery.layer5.io/docs/installation/platforms/kubernetes Using Helm), so just copy the scripts into the `layer5.io` document site the location where title named `Kubernetes user` and replace the current contents.

**Comment by vinayaksh42** [comment]
Can I work on this issue? @Aisuko

**Comment by Aisuko** [comment]
> Can I work on this issue? @Aisuko


Yes, please.

**Comment by vinayaksh42** [comment]
Can you assign this issue to me? @Aisuko
