### ISSUE TITLE
[NG] Add dark theme to Layer5-NG.

### ISSUE THREAD

**Issue by codetheorem** [layer5io/layer5#972]
**Current Behavior**

There is only a light theme present currently.

**Desired Behavior**

Add a dark theme to the layer5-ng website.

---
 **Alternatives**

Use this https://www.gatsbyjs.com/plugins/gatsby-plugin-dark-mode/.

 **Additional context**

You can add a dark theme in the theme folder in src.

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Sounds pretty great. Certainly, worth trying out.

**Comment by Fahdmoh01** [comment]
I want to work on this issue. Kindly assign me to this. @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
This requires you to work upon gatsby/react, are you comfortable with it now @Fahdmoh01 ?

**Comment by Fahdmoh01** [comment]
Oh okay, I wait and come back later if it's still opened.

**Comment by kishore007k** [comment]
I would like to work on this issue. @Nikhil-Ladha

**Comment by geraldmaboshe** [comment]
May I try this out?

**Comment by geraldmaboshe** [comment]
> May I try this out?

@Tanuj22   @Nikhil-Ladha

**Comment by Nikhil-Ladha** [comment]
Sure, you can. I think if we intend to go for a dark theme then we will be using the 'jungle green' color as the background for the theme, and not black. Also, work with the appropriate brand colors to see how it goes.


Doing the changes centrally in the themes/app/theme.style.js should be the approach I think.

**Comment by leecalcote** [comment]
Sounds great, @geraldmaboshe, and like good counsel @Nikhil-Ladha

**Comment by geraldmaboshe** [comment]
Cool, on it!
