### ISSUE TITLE
[NG] Change from class based component to fuction based component 

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#977]
**Current Behavior**
The [members page](https://github.com/layer5io/layer5/blob/layer5-ng/src/pages/community/members.js) and the [blog page](https://github.com/layer5io/layer5/blob/layer5-ng/src/templates/blog.js) are using Class based Components,

**Desired Behavior**
Change them to function based components using [react hooks](https://reactjs.org/docs/hooks-intro.html) for state management. 

---
[Optional] **Alternatives**

[Optional] **Additional context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by codetheorem** [comment]
Assign this to me.

**Comment by kishore007k** [comment]
> Assign this to me.

Go ahead @codetheorem

**Comment by k-charette** [comment]
Hi! I noticed someone is already assigned to this issue. Though I was interested in helping out so I tried it solve this on my own for fun. 
I already have a fix and ready to submit a PR for review. If the original assignee wants to submit theirs I'll step away. Thank you!

**Comment by codetheorem** [comment]
@k-charette you can submit a PR.

**Comment by kishore007k** [comment]
@k-charette Nice work 🤙
@codetheorem So generous of you 😉
