### ISSUE TITLE
[NG] see more not working properly in workshop grid in layer5-ng

### ISSUE THREAD

**Issue by Tanuj22** [layer5io/layer5#981]
**Description**
Currently, when see more button another card is clicked with the previous one being open, the previous one collapses
![ezgif-2-421f984b965e](https://user-images.githubusercontent.com/42486853/96470342-ce6c8e00-124b-11eb-9b75-3555c219a47e.gif)

**Expected Behavior**
The previous one should collapse and the new one should expand. 

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
@kishore007k can you look into this?

**Comment by kishore007k** [comment]
Sure @Tanuj22
