### ISSUE TITLE
[NG] Improve Button component with new properties

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#982]
**Current Behavior**
the current reusecore/Button requires wrapping an `<a>` around it, does not include a selectable color theme, require `alt` and `title` properties for the `<button>` or `<a>` tags.

**Desired Behavior**
Consider swapping for this component - https://www.npmjs.com/package/@hashicorp/react-button, which incorporates a number of useful properties; e.g.:

```
                  <Button
                    key={link.text}
                    title={link.text}
                    linkType={link.type}
                    url={link.url}
                    theme={{ variant, brand }}
                  />
```
---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by Tanuj22** [comment]
Fixed in #1032
