### ISSUE TITLE
[NG] Add member profiles for newly added contributors

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/layer5#984]
**Current Behavior**
Recently, Ameya Agashe and Prateek Tripathy have been added as contributors to [layer5](https://layer5.io/community/members) site.

**Desired Situation**
Add those members to [layer5-ng](https://layer5ng.netlify.app/community/members) site as well.
- [ ] [Ameya Agashe](https://layer5.io/community/members/ameya-agashe) 
- [ ] [Prateek Tripathy](https://layer5.io/community/members/prateek-tripathy)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by codetheorem** [comment]
assign this to me.
