### ISSUE TITLE
Add 3Scale to the landscape

### ISSUE THREAD

**Issue by dudash** [layer5io/layer5#99]
It's API Management including an API Gateway (uses NGINX). It looks like that should go in the non-functional list.  There is an [Istio Mixer adapter](https://github.com/3scale/3scale-istio-adapter) for it as well. Not 100% sure on the dates, but something like this:

```
- name: 3Scale
  opensource: "Yes"
  link: https://github.com/3scale
  governance: Red Hat
  primary-lang: Lua
  announce-date: December 2014
  ga-1-date: December 2014
  commerical: Red Hat 
  category: API Gateway
```

**Comment by leecalcote** [comment]
Hi @dudash, thanks for suggesting 3scale! This is great. We'll certainly incorporate into the landscape. If we're too slow or you're inclined, we'll happily take a PR reflecting this change. It would be an update to both the [non-functional.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/non-functional.yml) and the [gw.yml](https://github.com/layer5io/layer5/blob/master/_data/categories/gw.yml) files. Fire away. :)

**Comment by dudash** [comment]
sure, I'll add it in and submit a PR
