### ISSUE TITLE
Recognition of Kishore Kumar's contributions and status as a community member

### ISSUE THREAD

**Issue by leecalcote** [layer5io/layer5#991]
**Current Behavior**
@kishore007k is an active contributor in the Layer5 community.

**Desired Behavior**
A profile for @kishore007k should be created and visible on `/community/members`.

- [Link to profile picture](https://user-images.githubusercontent.com/34863222/96668979-f528e280-1379-11eb-9182-ec6113944811.jpeg)

---
**Contributor Resources**
The `layer5` repo contains two websites. The current generation and the next-generation of the layer5.io site.

If the `layer5-ng` label is absent on this issue, then this issue pertains to the current generation of the layer5.io website, which uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/layer5io/layer5/tree/master).
- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

If the `layer5-ng` label is present on this issue, then this issue pertains to the next-generation of the layer5.io website, which uses Gatsby, Strapi, and GitHub Pages. Site content is found under the [`layer5-ng` branch](https://github.com/layer5io/layer5/tree/layer5-ng).
- See [`layer5-ng` contributing instructions](https://github.com/layer5io/layer5/blob/layer5-ng/CONTRIBUTING.md)

**Comment by kishore007k** [comment]
Thank you @leecalcote It feels great working with this community.
It should be a perfect issue for the first time Contributors.
It would like to use this [Profile Pic](https://user-images.githubusercontent.com/34863222/96668979-f528e280-1379-11eb-9182-ec6113944811.jpeg) is instead.

**Comment by leecalcote** [comment]
Excellent. 😄 Updating the issue description with new profile pic to avoid confusion...

**Comment by akashgp09** [comment]
@leecalcote Can you assign this to me.

**Comment by kishore007k** [comment]
Go for it @Akanksha1212
